# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 48 (nevine..nuha).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": nevine -> "نفينe" (broken Latin-Arabic mix);
   nibal -> Latin "Nibal"; nimra -> "عربي_Nimra" (placeholder); ninos -> Latin
   "Ninos"; nisreen -> empty; noor -> empty; nouman -> empty; nour -> empty;
   noon -> Latin "Noon"; nooni -> Latin "Nooni"; noriza -> Latin "Noriza";
   noshi -> Latin "Noshi"; nousha -> Latin "Nousha"; novin -> Latin "Novin";
   noya -> Latin "Noya"; nisrin -> نسرين (correct); nishat -> نِشَةَط (broken);
   nighat -> نِيحَط (broken); nikhat -> نِخَات (broken); nihad -> نيهات;
   nihal -> نيحل; nihel -> نهل; nija -> نيج ة; nizal -> نزل; nizar -> نزار (correct);
   nobar -> أحمد; nora -> علي; nivin -> عائشة; noushin -> عائشة.
 * EMPTY STUBS (8-key records, no data): nisreen, noor, nouman, nour.
 * MISLABELLED ORIGIN: nikzad (Persian), nilofar/nilofer/niloufar/nilufar
   (Persian), nishat (Urdu/Persian), nitasha (Hindi/Bengali), nina (various),
   ninos (Aramaic/Spanish), nissan (Hebrew/Aramaic), nooshin/nosheen/noshin
   (Persian), nousha (Persian), novin (Persian), noya (Hebrew/other),
   niaz/niyaz/niyazi (Persian), nisrin (Persian), nibras (Arabic, correct).
 * DEGARBLED GLOSSES: neyla "Night or Light", nezha "Gleaming, Radiant",
   niam "Grace, beauty", niaz "Religious devotion", niazi "Helper, supporter",
   nibal "Strong, Firm", nibras "Little drop", nida "Call or Invocation",
   nidal "Struggle, Battle, War", nighat "Night", niha "Nurse, Intimidated, Delighted",
   nihad "Desire, Wish", nihal "Radiant, shining, glowing", nihan "Delight, Grace",
   nihel "Light, Illuminated", nija "Joyful", nijat "Deliverance, Salvation",
   nikhat "Jasmine", nikzad "Victorious", nilofer "Light of the eyes",
   nimah "Grace, Beauty", nimr "Lion", nimra "Noble and blessed",
   nimrah "Pure and Clean", nimrat "Night", nina "Gentle, delicate",
   nisa "Women, Lady", nisaa "Four Women", nisar "Friend, Intimate, Companion",
   nishat "Garden, Paradise", nisma "Gift of God", nisrin "Venus, love, beauty",
   nissan "Fruit", nitasha "Night, Star", nivin "Gift, Grace",
   niyaz "performing the daily acts of worship", niyazi "Righteous one",
   nizaar "Guide, Protector", nizal "Ascending, Mounting, Rising",
   nizami "Memory, Knowledge", nizar "Victory, Glory", noaman "Restorer",
   nobar "Noble, Bright", nofal "Wolf", noha "Rest, Repose, Serenity",
   nojood "Gentle Breeze", nomaan "Relenting, Forgiving", noman "Tranquil, Restful",
   nooh "Rest, Repose, Peace", noon "12th month", nooni "Nur or Light",
   noorah "Light of God", noorain "Light of the moon", nooran "Radiant, Full of Light",
   noore "Light, Glow", noori "Light, Radiance", noorjahan "Light of the World",
   noorul "Light", nooshin "Light, Radiant", norah "Light", noreen "Light, radiant",
   norhan "Gift from Allah", noriza "Light, bright, beautiful",
   noshaba "Gift, blessing", nosheen "Light, Illumination", noshi "Gift, Blessing",
   noshin "Gift, Grace", nouf "Soft, gentle breeze", noufal "Flooded",
   nouh "Prophet Noah", nouha "Gift, Grace", nourhan "Light, Illumination",
   nouria "Light, Radiance", nousha "Light, Radiant", noushin "Jewel",
   novin "New, Fresh", noya "New, fresh, young", nuaim "Given by God",
   nufail "Successful in Faith", nuh "Prophet Noah",
   nuha "Prophetess in Arabic mythology".
 * GENDER ERRORS: nibras, nidaa, nihad, nijat, nisa, nisar, nisma, nissan,
   noore, noorul, norhan, nobar, noon were labelled unisex where documented
   usage is male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated47 import GLOSSES as _G47

GLOSSES = dict(_G47)
GLOSSES.update({
    "nevine": {"en": "Nevine; a female given name", "ur": "نوین (زنانہ نام)", "fa": "نوین (نام زنانه)", "hi": "नेवीन (स्त्री नाम)", "ps": "نوین (ښځينه نوم)", "ar": "نِيفِين (اسْم عَلَم مُؤَنَّث)"},
    "neyla": {"en": "Neyla; a female given name", "ur": "نیلہ (زنانہ نام)", "fa": "نیله (نام زنانه)", "hi": "नेयला (स्त्री नाम)", "ps": "نیله (ښځينه نوم)", "ar": "نَيْلَة (اسْم عَلَم مُؤَنَّث)"},
    "nezha": {"en": "Nezha; a female given name", "ur": "نزہہ (زنانہ نام)", "fa": "نزهه (نام زنانه)", "hi": "नेज़हा (स्त्री नाम)", "ps": "نزهه (ښځينه نوم)", "ar": "نُزْهَة (اسْم عَلَم مُؤَنَّث)"},
    "niam": {"en": "Niam; blessing, favour", "ur": "نعم، نعمت", "fa": "نعم، نعمت", "hi": "निअम, आशीर्वाद", "ps": "نعم، نعمت", "ar": "نِعَم، النِّعْمَة"},
    "niaz": {"en": "Niaz; supplication, entreaty (Persian)", "ur": "نیاز، التجا، دعا", "fa": "نیاز، نیاز و دعا", "hi": "नियाज़, प्रार्थना", "ps": "نیاز، دعا", "ar": "نِيَاز (التَّضَرُّع)"},
    "niazi": {"en": "Niazi; a male given name", "ur": "نیازی (مردانہ نام)", "fa": "نیازی (نام مردانه)", "hi": "नियाज़ी (पुरुष नाम)", "ps": "نیازي (نر نوم)", "ar": "نِيَازِي (اسْم عَلَم مُذَكَّر)"},
    "nibal": {"en": "Nibal; a female given name", "ur": "نبال (زنانہ نام)", "fa": "نبال (نام زنانه)", "hi": "निबाल (स्त्री नाम)", "ps": "نبال (ښځينه نوم)", "ar": "نِبَال (اسْم عَلَم مُؤَنَّث)"},
    "nibras": {"en": "Nibras; lamp, lantern", "ur": "نبراس، چراغ، قندیل", "fa": "نبراس، چراغ", "hi": "निबरास, दीपक", "ps": "نبراس، څراغ", "ar": "النِّبْرَاس، الْمِصْبَاح"},
    "call": {"en": "Call, invocation, summons", "ur": "ندا، پکار، آواز", "fa": "ندا، فراخوان", "hi": "निदा, पुकार", "ps": "ندا، غږ", "ar": "النِّدَاء، الدُّعَاء"},
    "nidal": {"en": "Nidal; struggle, conflict", "ur": "نضال، جدوجہد، جدال", "fa": "نضال، مبارزه", "hi": "निदाल, संघर्ष", "ps": "نضال، مبارزه", "ar": "النِّضَال، الْكِفَاح"},
    "nighat": {"en": "Nighat; a female given name", "ur": "نگہت (زنانہ نام)", "fa": "نگهت (نام زنانه)", "hi": "निगहत (स्त्री नाम)", "ps": "نگهت (ښځينه نوم)", "ar": "نِگْهَت (اسْم عَلَم مُؤَنَّث)"},
    "niha": {"en": "Niha; a female given name", "ur": "نیہا (زنانہ نام)", "fa": "نیها (نام زنانه)", "hi": "नीहा (स्त्री नाम)", "ps": "نیها (ښځينه نوم)", "ar": "نِيهَا (اسْم عَلَم مُؤَنَّث)"},
    "nihad": {"en": "Nihad; a male given name", "ur": "نہاد (مردانہ نام)", "fa": "نهاد (نام مردانه)", "hi": "निहाद (पुरुष नाम)", "ps": "نهاد (نر نوم)", "ar": "نِهَاد (اسْم عَلَم مُذَكَّر)"},
    "nihal": {"en": "Nihal; sapling, young plant", "ur": "نہال، پودا، نوجوان درخت", "fa": "نهال، نهال درخت", "hi": "निहाल, पौधा", "ps": "نهال، نوی ونې", "ar": "النِّهَال، الْغَرْس"},
    "nihan": {"en": "Nihan; hidden, concealed (Persian)", "ur": "نہان، پوشیدہ، چھپا ہوا", "fa": "نهان، پنهان", "hi": "निहान, छिपा हुआ", "ps": "نهان، پټ", "ar": "نِهَان (الْمُخْفَى)"},
    "nihel": {"en": "Nihel; a female given name", "ur": "نہل (زنانہ نام)", "fa": "نهل (نام زنانه)", "hi": "निहेल (स्त्री नाम)", "ps": "نهل (ښځينه نوم)", "ar": "نِهَل (اسْم عَلَم مُؤَنَّث)"},
    "nija": {"en": "Nija; a female given name", "ur": "نیجہ (زنانہ نام)", "fa": "نیجه (نام زنانه)", "hi": "निजा (स्त्री नाम)", "ps": "نیجه (ښځينه نوم)", "ar": "نِيجَة (اسْم عَلَم مُؤَنَّث)"},
    "nijat": {"en": "Nijat; salvation, deliverance", "ur": "نجات، خلاصی", "fa": "نجات، رهایی", "hi": "निजात, मुक्ति", "ps": "نجات، خلاصون", "ar": "النَّجَاة، الْخَلَاص"},
    "nikhat": {"en": "Nikhat; a female given name", "ur": "نکہت (زنانہ نام)", "fa": "نکهت (نام زنانه)", "hi": "निखत (स्त्री नाम)", "ps": "نکهت (ښځينه نوم)", "ar": "نِكْهَت (اسْم عَلَم مُؤَنَّث)"},
    "nikzad": {"en": "Nikzad; well-born (Persian)", "ur": "نیکزاد، نیک نسل", "fa": "نیکزاد، از نسل نیک", "hi": "निकज़ाद, अच्छे कुल का", "ps": "نیکزاد، نیک نسل", "ar": "نِيكْزَاد (اسْم عَلَم فَارِسِيّ)"},
    "water_lily2": {"en": "Water lily, lotus", "ur": "نیلوفر، کنول", "fa": "نیلوفر، نیلوفر آبی", "hi": "नीलोफ़र, कमल", "ps": "نیلوفر، نيلوفر", "ar": "النِّيلُوفَر"},
    "nimah": {"en": "Nimah; blessing, favour", "ur": "نعمہ، نعمت", "fa": "نعمه، نعمت", "hi": "निमा, आशीर्वाद", "ps": "نعمه، نعمت", "ar": "النِّعْمَة، الرَّحْمَة"},
    "nimr": {"en": "Nimr; leopard, panther", "ur": "نمر، چیتا، تیندوا", "fa": "نمر، پلنگ", "hi": "निम्र, तेंदुआ", "ps": "نمر، پړانګ", "ar": "النِّمْر"},
    "nimra": {"en": "Nimra; a female given name", "ur": "نمرہ (زنانہ نام)", "fa": "نمره (نام زنانه)", "hi": "निमरा (स्त्री नाम)", "ps": "نمره (ښځينه نوم)", "ar": "نِمْرَة (اسْم عَلَم مُؤَنَّث)"},
    "nimrah": {"en": "Nimrah; a female given name", "ur": "نمرہ (زنانہ نام)", "fa": "نمره (نام زنانه)", "hi": "निमरा (स्त्री नाम)", "ps": "نمره (ښځينه نوم)", "ar": "نِمْرَة (اسْم عَلَم مُؤَنَّث)"},
    "nimrat": {"en": "Nimrat; a female given name", "ur": "نمرت (زنانہ نام)", "fa": "نمرت (نام زنانه)", "hi": "निमरत (स्त्री नाम)", "ps": "نمرت (ښځينه نوم)", "ar": "نِمْرَت (اسْم عَلَم مُؤَنَّث)"},
    "nina": {"en": "Nina; a female given name", "ur": "نینا (زنانہ نام)", "fa": "نینا (نام زنانه)", "hi": "नीना (स्त्री नाम)", "ps": "نینا (ښځينه نوم)", "ar": "نِينَا (اسْم عَلَم مُؤَنَّث)"},
    "ninos": {"en": "Ninos; a male given name (Aramaic)", "ur": "نینوس (مردانہ نام)", "fa": "نینوس (نام مردانه)", "hi": "निनोस (पुरुष नाम)", "ps": "نینوس (نر نوم)", "ar": "نِينُوس (اسْم عَلَم آرَامِيّ)"},
    "women": {"en": "Women", "ur": "نساء، عورتیں", "fa": "نساء، زنان", "hi": "निसा, स्त्रियाँ", "ps": "نساء، ښځې", "ar": "النِّسَاء"},
    "nisar": {"en": "Nisar; sacrifice, scattering", "ur": "نثار، قربان، بکھیرنا", "fa": "نثار، فدا", "hi": "निसार, न्योछावर", "ps": "نثار، قربان", "ar": "النِّثَار، الْفِدَاء"},
    "garden": {"en": "Garden, paradise", "ur": "نشاط، باغ، جنت", "fa": "نشاط، باغ", "hi": "निशात, बाग़", "ps": "نشاط، باغ", "ar": "النِّشَاط (الْبُسْتَان)"},
    "nisma": {"en": "Nisma; a breeze, a breath", "ur": "نسمہ، ہلکی ہوا", "fa": "نسمه، نسیم", "hi": "नसमा, हल्की हवा", "ps": "نسمه، نرمه باد", "ar": "النَّسْمَة، النَّسِيم"},
    "nisreen": {"en": "Nisreen; wild rose, narcissus", "ur": "نسرین، جنگلی گلاب", "fa": "نسرین، گل نرگس", "hi": "निसरीन, जंगली गुलाब", "ps": "نسرین، وحشي ګلاب", "ar": "النِّسْرِين"},
    "nisrin": {"en": "Nisrin; wild rose, narcissus", "ur": "نسرین، جنگلی گلاب", "fa": "نسرین، گل نرگس", "hi": "निसरीन, जंगली गुलाब", "ps": "نسرین، وحشي ګلاب", "ar": "النِّسْرِين"},
    "nissan": {"en": "Nissan; a male given name (Aramaic)", "ur": "نیسان (مردانہ نام)", "fa": "نیسان (نام مردانه)", "hi": "निसान (पुरुष नाम)", "ps": "نیسان (نر نوم)", "ar": "نِيسَان (اسْم عَلَم آرَامِيّ)"},
    "nitasha": {"en": "Nitasha; a female given name", "ur": "نتاشا (زنانہ نام)", "fa": "نتاشا (نام زنانه)", "hi": "निताशा (स्त्री नाम)", "ps": "نتاشا (ښځينه نوم)", "ar": "نِيتَاشَا (اسْم عَلَم مُؤَنَّث)"},
    "nivin": {"en": "Nivin; a female given name", "ur": "نیون (زنانہ نام)", "fa": "نیون (نام زنانه)", "hi": "निविन (स्त्री नाम)", "ps": "نیون (ښځينه نوم)", "ar": "نِيفِين (اسْم عَلَم مُؤَنَّث)"},
    "niyaz": {"en": "Niyaz; supplication, entreaty (Persian)", "ur": "نیاز، التجا، دعا", "fa": "نیاز، نیاز و دعا", "hi": "नियाज़, प्रार्थना", "ps": "نیاز، دعا", "ar": "نِيَاز (التَّضَرُّع)"},
    "niyazi": {"en": "Niyazi; a male given name", "ur": "نیازی (مردانہ نام)", "fa": "نیازی (نام مردانه)", "hi": "नियाज़ी (पुरुष नाम)", "ps": "نیازي (نر نوم)", "ar": "نِيَازِي (اسْم عَلَم مُذَكَّر)"},
    "nizaar": {"en": "Nizaar; a male given name", "ur": "نزار (مردانہ نام)", "fa": "نزار (نام مردانه)", "hi": "निज़ार (पुरुष नाम)", "ps": "نزار (نر نوم)", "ar": "نِزَار (اسْم عَلَم مُذَكَّر)"},
    "nizal": {"en": "Nizal; a male given name", "ur": "نزال (مردانہ نام)", "fa": "نزال (نام مردانه)", "hi": "निज़ाल (पुरुष नाम)", "ps": "نزال (نر نوم)", "ar": "نِزَال (اسْم عَلَم مُذَكَّر)"},
    "nizam": {"en": "Nizam; order, system, arrangement", "ur": "نظام، ترتیب، انتظام", "fa": "نظام، سامانه", "hi": "निज़ाम, व्यवस्था", "ps": "نظام، ترتیب", "ar": "النِّظَام، التَّرْتِيب"},
    "nizami": {"en": "Nizami; of order, regulatory", "ur": "نظامی، نظام سے منسوب", "fa": "نظامی، منسوب به نظام", "hi": "निज़ामी, व्यवस्था से संबंधित", "ps": "نظامي، د نظام اړوند", "ar": "النِّظَامِي، مَنْسُوب إِلَى النِّظَام"},
    "nizar": {"en": "Nizar; a male given name", "ur": "نزار (مردانہ نام)", "fa": "نزار (نام مردانه)", "hi": "निज़ार (पुरुष नाम)", "ps": "نزار (نر نوم)", "ar": "نِزَار (اسْم عَلَم مُذَكَّر)"},
    "naaman2": {"en": "Nu'man; a male given name", "ur": "نعمان (مردانہ نام)", "fa": "نعمان (نام مردانه)", "hi": "नोमान (पुरुष नाम)", "ps": "نعمان (نر نوم)", "ar": "نُعْمَان (اسْم عَلَم مُذَكَّر)"},
    "nobar": {"en": "Nobar; a male given name (Persian)", "ur": "نوبر (مردانہ نام)", "fa": "نوبر (نام مردانه)", "hi": "नोबर (पुरुष नाम)", "ps": "نوبر (نر نوم)", "ar": "نُوبَر (اسْم عَلَم فَارِسِيّ)"},
    "nofal": {"en": "Nofal; a male given name", "ur": "نوفل (مردانہ نام)", "fa": "نوفل (نام مردانه)", "hi": "नौफ़ल (पुरुष नाम)", "ps": "نوفل (نر نوم)", "ar": "نَوْفَل (اسْم عَلَم مُذَكَّر)"},
    "noha": {"en": "Noha; intelligence, understanding", "ur": "نہیٰ، عقل، فہم", "fa": "نهی، خرد", "hi": "नुहा, बुद्धि", "ps": "نهی، عقل", "ar": "النُّهَى، الْعَقْل"},
    "nojood": {"en": "Nojood; a female given name", "ur": "نجود (زنانہ نام)", "fa": "نجود (نام زنانه)", "hi": "नजूद (स्त्री नाम)", "ps": "نجود (ښځينه نوم)", "ar": "نُجُود (اسْم عَلَم مُؤَنَّث)"},
    "nomaan": {"en": "Nomaan; a male given name", "ur": "نعمان (مردانہ نام)", "fa": "نعمان (نام مردانه)", "hi": "नोमान (पुरुष नाम)", "ps": "نعمان (نر نوم)", "ar": "نُعْمَان (اسْم عَلَم مُذَكَّر)"},
    "noman": {"en": "Noman; a male given name", "ur": "نعمان (مردانہ نام)", "fa": "نعمان (نام مردانه)", "hi": "नोमान (पुरुष नाम)", "ps": "نعمان (نر نوم)", "ar": "نُعْمَان (اسْم عَلَم مُذَكَّر)"},
    "nuh": {"en": "Nuh; Noah (prophet)", "ur": "نوح، حضرت نوح علیہ السلام", "fa": "نوح، حضرت نوح", "hi": "नूह, नूह नबी", "ps": "نوح، حضرت نوح", "ar": "نُوح (اسْم نَبِيّ)"},
    "noon": {"en": "Noon; the letter nūn", "ur": "نون، حرف ن", "fa": "نون، حرف ن", "hi": "नून, अक्षर न", "ps": "نون، د ن توری", "ar": "النُّون (حَرْف)"},
    "nooni": {"en": "Nooni; a female given name", "ur": "نونی (زنانہ نام)", "fa": "نونی (نام زنانه)", "hi": "नूनी (स्त्री नाम)", "ps": "نوني (ښځينه نوم)", "ar": "نُونِي (اسْم عَلَم مُؤَنَّث)"},
    "light": {"en": "Light, radiance", "ur": "نور، روشنی", "fa": "نور، روشنایی", "hi": "नूर, प्रकाश", "ps": "نور، رڼا", "ar": "النُّور"},
    "noora": {"en": "Noora; light (feminine)", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नूरा, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "noorah": {"en": "Noorah; light (feminine)", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नूरा, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "noorain": {"en": "Noorain; two lights", "ur": "نورین، دو نور", "fa": "نورین، دو نور", "hi": "नूरैन, दो प्रकाश", "ps": "نورین، دوه رڼا", "ar": "النُّورَيْن (نُورَان)"},
    "nooran": {"en": "Nooran; full of light", "ur": "نوران، روشنی سے بھرا", "fa": "نوران، پر از نور", "hi": "नूरान, प्रकाश से भरा", "ps": "نوران، رڼا ډک", "ar": "نُورَان، الْمُنِير"},
    "noorani": {"en": "Noorani; luminous, of light", "ur": "نورانی، روشن، نور والا", "fa": "نورانی، نورانی", "hi": "नूरानी, प्रकाशमान", "ps": "نوراني، روښانه", "ar": "النُّورَانِي، الْمُنِير"},
    "noore": {"en": "Noore; light, glow", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नूरे, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "noori": {"en": "Noori; luminous, of light", "ur": "نوری، روشن", "fa": "نوری، نورانی", "hi": "नूरी, प्रकाशमान", "ps": "نوري، روښانه", "ar": "النُّورِي، الْمُنِير"},
    "noorjahan": {"en": "Noorjahan; light of the world", "ur": "نورجہاں، جہاں کی روشنی", "fa": "نورجہان، نور جهان", "hi": "नूरजहाँ, संसार का प्रकाश", "ps": "نورجہان، د نړۍ رڼا", "ar": "نُور جِهَان (نُور الْعَالَم)"},
    "noorul": {"en": "Noorul; light of (construct)", "ur": "نور ال، نورِ", "fa": "نور ال، نورِ", "hi": "नूरुल, प्रकाश", "ps": "نور ال، د رڼا", "ar": "نُورُ الـ (الْإِضَافَة)"},
    "nooshin": {"en": "Nooshin; sweet, pleasant (Persian)", "ur": "نوشین، شیریں", "fa": "نوشین، شیرین", "hi": "नूशीन, मधुर", "ps": "نوشین، خوږ", "ar": "نُوشِين (الْحُلْو)"},
    "nora": {"en": "Nora; light (feminine)", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नोरा, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "norah": {"en": "Norah; light (feminine)", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नोरा, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "noreen": {"en": "Noreen; light, luminous", "ur": "نورین، روشن", "fa": "نورین، نورانی", "hi": "नौरीन, प्रकाशमान", "ps": "نورین، روښانه", "ar": "نُورِين، الْمُنِيرَة"},
    "norhan": {"en": "Norhan; light, illumination", "ur": "نورحان، روشنی", "fa": "نورحان، روشنایی", "hi": "नूरहान, प्रकाश", "ps": "نورحان، رڼا", "ar": "نُور حَان (النُّور)"},
    "noriza": {"en": "Noriza; a female given name", "ur": "نوریزہ (زنانہ نام)", "fa": "نوریزه (نام زنانه)", "hi": "नोरीज़ा (स्त्री नाम)", "ps": "نوریزه (ښځينه نوم)", "ar": "نُورِيزَة (اسْم عَلَم مُؤَنَّث)"},
    "noshaba": {"en": "Noshaba; a female given name", "ur": "نوشابہ (زنانہ نام)", "fa": "نوشابه (نام زنانه)", "hi": "नौशाबा (स्त्री नाम)", "ps": "نوشابه (ښځينه نوم)", "ar": "نُوشَابَة (اسْم عَلَم مُؤَنَّث)"},
    "nosheen": {"en": "Nosheen; sweet, pleasant (Persian)", "ur": "نوشین، شیریں", "fa": "نوشین، شیرین", "hi": "नौशीन, मधुर", "ps": "نوشین، خوږ", "ar": "نُوشِين (الْحُلْو)"},
    "noshi": {"en": "Noshi; a female given name", "ur": "نوشی (زنانہ نام)", "fa": "نوشی (نام زنانه)", "hi": "नौशी (स्त्री नाम)", "ps": "نوشي (ښځينه نوم)", "ar": "نُوشِي (اسْم عَلَم مُؤَنَّث)"},
    "noshin": {"en": "Noshin; sweet, pleasant (Persian)", "ur": "نوشین، شیریں", "fa": "نوشین، شیرین", "hi": "नौशीन, मधुर", "ps": "نوشین، خوږ", "ar": "نُوشِين (الْحُلْو)"},
    "nouf": {"en": "Nouf; a female given name", "ur": "نوف (زنانہ نام)", "fa": "نوف (نام زنانه)", "hi": "नौफ़ (स्त्री नाम)", "ps": "نوف (ښځينه نوم)", "ar": "نَوْف (اسْم عَلَم مُؤَنَّث)"},
    "noufal": {"en": "Noufal; a male given name", "ur": "نوفل (مردانہ نام)", "fa": "نوفل (نام مردانه)", "hi": "नौफ़ल (पुरुष नाम)", "ps": "نوفل (نر نوم)", "ar": "نَوْفَل (اسْم عَلَم مُذَكَّر)"},
    "nouh": {"en": "Nouh; Noah (prophet)", "ur": "نوح، حضرت نوح علیہ السلام", "fa": "نوح، حضرت نوح", "hi": "नूह, नूह नबी", "ps": "نوح، حضرت نوح", "ar": "نُوح (اسْم نَبِيّ)"},
    "nouha": {"en": "Nouha; intelligence, understanding", "ur": "نہیٰ، عقل، فہم", "fa": "نهی، خرد", "hi": "नुहा, बुद्धि", "ps": "نهی، عقل", "ar": "النُّهَى، الْعَقْل"},
    "nouman": {"en": "Nouman; a male given name", "ur": "نعمان (مردانہ نام)", "fa": "نعمان (نام مردانه)", "hi": "नोमान (पुरुष नाम)", "ps": "نعمان (نر نوم)", "ar": "نُعْمَان (اسْم عَلَم مُذَكَّر)"},
    "nour": {"en": "Nour; light, radiance", "ur": "نور، روشنی", "fa": "نور، روشنایی", "hi": "नूर, प्रकाश", "ps": "نور، رڼا", "ar": "النُّور"},
    "noura": {"en": "Noura; light (feminine)", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नूरा, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "nouran": {"en": "Nouran; full of light", "ur": "نوران، روشنی سے بھرا", "fa": "نوران، پر از نور", "hi": "नूरान, प्रकाश से भरा", "ps": "نوران، رڼا ډک", "ar": "نُورَان، الْمُنِير"},
    "noureen": {"en": "Noureen; light, luminous", "ur": "نورین، روشن", "fa": "نورین، نورانی", "hi": "नौरीन, प्रकाशमान", "ps": "نورین، روښانه", "ar": "نُورِين، الْمُنِيرَة"},
    "nourhan": {"en": "Nourhan; light, illumination", "ur": "نورحان، روشنی", "fa": "نورحان، روشنایی", "hi": "नूरहान, प्रकाश", "ps": "نورحان، رڼا", "ar": "نُور حَان (النُّور)"},
    "nouria": {"en": "Nouria; luminous, of light", "ur": "نوریہ، روشن", "fa": "نوریه، نورانی", "hi": "नूरिया, प्रकाशमान", "ps": "نوریه، روښانه", "ar": "النُّورِيَة، الْمُنِيرَة"},
    "nousha": {"en": "Nousha; a female given name (Persian)", "ur": "نوشہ (زنانہ نام)", "fa": "نوشا (نام زنانه)", "hi": "नौशा (स्त्री नाम)", "ps": "نوشا (ښځينه نوم)", "ar": "نُوشَا (اسْم عَلَم فَارِسِيّ)"},
    "noushin": {"en": "Noushin; sweet, pleasant (Persian)", "ur": "نوشین، شیریں", "fa": "نوشین، شیرین", "hi": "नौशीन, मधुर", "ps": "نوشین، خوږ", "ar": "نُوشِين (الْحُلْو)"},
    "novin": {"en": "Novin; new, fresh (Persian)", "ur": "نوین، نیا، تازہ", "fa": "نوین، نو، تازه", "hi": "नोवीन, नया", "ps": "نوین، نوی", "ar": "نُوفِين (الْجَدِيد)"},
    "noya": {"en": "Noya; a female given name", "ur": "نویہ (زنانہ نام)", "fa": "نویا (نام زنانه)", "hi": "नोया (स्त्री नाम)", "ps": "نویا (ښځينه نوم)", "ar": "نُويَة (اسْم عَلَم مُؤَنَّث)"},
    "nuaim": {"en": "Nuaim; a male given name", "ur": "نعیم (مردانہ نام)", "fa": "نعیم (نام مردانه)", "hi": "नुऐम (पुरुष नाम)", "ps": "نعیم (نر نوم)", "ar": "نُعَيْم (اسْم عَلَم مُذَكَّر)"},
    "nufail": {"en": "Nufail; a male given name", "ur": "نفیل (مردانہ نام)", "fa": "نفیل (نام مردانه)", "hi": "नुफ़ैल (पुरुष नाम)", "ps": "نفیل (نر نوم)", "ar": "نُفَيْل (اسْم عَلَم مُذَكَّر)"},
    "nuha": {"en": "Nuha; intelligence, understanding", "ur": "نہیٰ، عقل، فہم", "fa": "نهی، خرد", "hi": "नुहा, बुद्धि", "ps": "نهی، عقل", "ar": "النُّهَى، الْعَقْل"},
})

CUR = {
 "nevine": ("نِيفِين", "نیوین", "نیوین", "नेवीन", "نیوین", "nevine", "Arabic", "Female",
            "Arabic نِيفِين (Nīfīn)", False, "high",
            "Nevine is Arabic نِيفِين (Nīfīn) 'beautiful, fair'. CRITICAL SOURCE ERROR: the source gave the broken string 'نفينe' (a Latin-Arabic mix); the correct form is نِيفِين. The source gloss 'New, Fresh' is unsupported and has been replaced with the lexical sense. Same name as neveen."),
 "neyla": ("نَيْلَة", "نیلہ", "نیله", "नेयला", "نیله", "neyla", "Arabic", "Female",
           "Arabic نَيْلَة (Nayla)", False, "medium",
           "Neyla is recorded as Arabic نَيْلَة (Nayla), a female given name. The source gloss 'Night or Light' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nezha": ("نُزْهَة", "نزہہ", "نزهه", "नेज़हा", "نزهه", "nezha", "Arabic", "Female",
           "Arabic root ن ز ه (n-z-h); نُزْهَة (Nuzha)", False, "high",
           "Nezha is Arabic نُزْهَة (Nuzha) 'excursion, outing, promenade', from the root ن ز ه (n-z-h). The source gloss 'Gleaming, Radiant' is unsupported and has been replaced with the lexical sense. Same name as nazha."),
 "niam": ("نِعَم", "نعم", "نعم", "निअम", "نعم", "niam", "Arabic", "Female",
          "Arabic root ن ع م (n-ʿ-m); نِعَم (Niʿam)", False, "high",
          "Niam is Arabic نِعَم (Niʿam) 'blessings, favours', the plural of نِعْمَة (niʿma), from the root ن ع م (n-ʿ-m). The source gloss 'Grace, beauty' is broadly consistent."),
 "niaz": ("نِيَاز", "نیاز", "نیاز", "नियाज़", "نیاز", "niaz", "Persian", "Male",
          "Persian نیاز (niyāz)", False, "high",
          "Niaz is Persian نیاز (niyāz) 'supplication, entreaty'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Religious devotion' is broadly consistent. Same name as niyaz."),
 "niazi": ("نِيَازِي", "نیازی", "نیازی", "नियाज़ी", "نیازي", "niazi", "Persian", "Male",
           "Persian نیاز (niyāz) + relational ending", False, "high",
           "Niazi is Persian نیاز (niyāz) + a relational ending, a male given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Helper, supporter' is unsupported and has been replaced with the documented identification. Same name as niyazi."),
 "nibal": ("نِبَال", "نبال", "نبال", "निबाल", "نبال", "nibal", "Arabic", "Female",
           "Arabic نِبَال (Nibāl)", False, "medium",
           "Nibal is recorded as Arabic نِبَال (Nibāl), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nibal' instead of a script form and labelled the gender male; documented usage is predominantly female. The source gloss 'Strong, Firm' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nibras": ("نِبْرَاس", "نبراس", "نبراس", "निबरास", "نبراس", "nibras", "Arabic", "Male",
            "Arabic root ن ب ر س (n-b-r-s); نِبْرَاس (Nibrās)", False, "high",
            "Nibras is Arabic نِبْرَاس (Nibrās) 'lamp, lantern', from the root ن ب ر س (n-b-r-s). The source gloss 'Little drop' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nida": ("نِدَاء", "ندا", "ندا", "निदा", "ندا", "call", "Arabic", "Female",
          "Arabic root ن د و (n-d-w); نِدَاء (Nidāʾ)", False, "high",
          "Nida is Arabic نِدَاء (Nidāʾ) 'call, invocation, summons', from the root ن د و (n-d-w). The source gloss 'Call or Invocation' is consistent. Same name as nidaa."),
 "nidaa": ("نِدَاء", "ندا", "ندا", "निदा", "ندا", "call", "Arabic", "Female",
           "Arabic root ن د و (n-d-w); نِدَاء (Nidāʾ)", False, "high",
           "Nidaa is Arabic نِدَاء (Nidāʾ) 'call, invocation', from the root ن د و (n-d-w). The source gloss 'Call, Invitation' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as nida."),
 "nidal": ("نِضَال", "نضال", "نضال", "निदाल", "نضال", "nidal", "Arabic", "Male",
           "Arabic root ن ض ل (n-ḍ-l); نِضَال (Niḍāl)", False, "high",
           "Nidal is Arabic نِضَال (Niḍāl) 'struggle, conflict', from the root ن ض ل (n-ḍ-l). The source gloss 'Struggle, Battle, War' is broadly consistent."),
 "nighat": ("نِگْهَت", "نگہت", "نگهت", "निगहत", "نگهت", "nighat", "Urdu", "Female",
            "Urdu نگہت (nighat), from Persian", False, "medium",
            "Nighat is an Urdu female given name. CRITICAL SOURCE ERROR: the source gave نِيحَط (a broken form) and labelled the origin Arabic; the name is Urdu. The source gloss 'Night' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "niha": ("نِيهَا", "نیہا", "نیها", "नीहा", "نیها", "niha", "Arabic", "Female",
          "Arabic نِيهَا (Nīhā)", False, "medium",
          "Niha is recorded as Arabic نِيهَا (Nīhā), a female given name. The source gloss 'Nurse, Intimidated, Delighted' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nihad": ("نِهَاد", "نہاد", "نهاد", "निहाद", "نهاد", "nihad", "Arabic", "Male",
           "Arabic نِهَاد (Nihād)", False, "medium",
           "Nihad is recorded as Arabic نِهَاد (Nihād), a male given name. CRITICAL SOURCE ERROR: the source gave نيهات (a non-standard form) and labelled the gender unisex; documented usage is predominantly male. The source gloss 'Desire, Wish' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nihal": ("نِهَال", "نہال", "نهال", "निहाल", "نهال", "nihal", "Arabic", "Female",
           "Arabic root ن ه ل (n-h-l); نِهَال (Nihāl)", False, "high",
           "Nihal is Arabic نِهَال (Nihāl) 'sapling, young plant', from the root ن ه ل (n-h-l). CRITICAL SOURCE ERROR: the source gave نيحل (a non-standard form). The source gloss 'Radiant, shining, glowing' is unsupported and has been replaced with the lexical sense."),
 "nihan": ("نِهَان", "نہان", "نهان", "निहान", "نهان", "nihan", "Persian", "Female",
           "Persian نهان (nihān)", False, "high",
           "Nihan is Persian نهان (nihān) 'hidden, concealed'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Delight, Grace' is unsupported and has been replaced with the lexical sense."),
 "nihel": ("نِهَل", "نہل", "نهل", "निहेल", "نهل", "nihel", "Arabic", "Female",
           "Arabic نِهَل (Nihel)", False, "medium",
           "Nihel is recorded as Arabic نِهَل (Nihel), a female given name. CRITICAL SOURCE ERROR: the source gave نهل (a non-standard form). The source gloss 'Light, Illuminated' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nija": ("نِيجَة", "نیجہ", "نیجه", "निजा", "نیجه", "nija", "Arabic", "Female",
          "Arabic نِيجَة (Nīja)", False, "medium",
          "Nija is recorded as Arabic نِيجَة (Nīja), a female given name. CRITICAL SOURCE ERROR: the source gave نيج ة (a broken form). The source gloss 'Joyful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nijat": ("نَجَاة", "نجات", "نجات", "निजात", "نجات", "nijat", "Arabic", "Male",
           "Arabic root ن ج و (n-j-w); نَجَاة (Najāh)", False, "high",
           "Nijat is Arabic نَجَاة (Najāh) 'salvation, deliverance', from the root ن ج و (n-j-w). The source gloss 'Deliverance, Salvation' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as nejat."),
 "nikhat": ("نِكْهَت", "نکہت", "نکهت", "निखत", "نکهت", "nikhat", "Urdu", "Female",
            "Urdu نکہت (nikhat), from Persian", False, "medium",
            "Nikhat is an Urdu female given name. CRITICAL SOURCE ERROR: the source gave نِخَات (a broken form) and labelled the origin Arabic; the name is Urdu. The source gloss 'Jasmine' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nikzad": ("نِيكْزَاد", "نیکزاد", "نیکزاد", "निकज़ाद", "نیکزاد", "nikzad", "Persian", "Male",
            "Persian نیکزاد (nīkzād)", False, "high",
            "Nikzad is Persian نیکزاد (nīkzād) 'well-born'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Victorious' is unsupported and has been replaced with the lexical sense."),
 "nilofar": ("نِيلُوفَر", "نیلوفر", "نیلوفر", "नीलोफ़र", "نیلوفر", "water_lily2", "Persian", "Female",
             "Persian نیلوفر (nīlūfar)", False, "high",
             "Nilofar is Persian نیلوفر (nīlūfar) 'water lily, lotus'. CRITICAL SOURCE ERROR: the source gave نيلفر (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Lotus Flower' is consistent. Same name as nelofar."),
 "nilofer": ("نِيلُوفَر", "نیلوفر", "نیلوفر", "नीलोफ़र", "نیلوفر", "water_lily2", "Persian", "Female",
             "Persian نیلوفر (nīlūfar)", False, "high",
             "Nilofer is Persian نیلوفر (nīlūfar) 'water lily, lotus'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Light of the eyes' is unsupported and has been replaced with the lexical sense. Same name as nelofar."),
 "niloufar": ("نِيلُوفَر", "نیلوفر", "نیلوفر", "नीलोफ़र", "نیلوفر", "water_lily2", "Persian", "Female",
              "Persian نیلوفر (nīlūfar)", False, "high",
              "Niloufar is Persian نیلوفر (nīlūfar) 'water lily, lotus'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Lotus flower' is consistent. Same name as nelofar."),
 "nilufar": ("نِيلُوفَر", "نیلوفر", "نیلوفر", "नीलोफ़र", "نیلوفر", "water_lily2", "Persian", "Female",
             "Persian نیلوفر (nīlūfar)", False, "high",
             "Nilufar is Persian نیلوفر (nīlūfar) 'water lily, lotus'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Lotus flower' is consistent. Same name as nelofar."),
 "nimah": ("نِعْمَة", "نعمہ", "نعمه", "निमा", "نعمه", "nimah", "Arabic", "Female",
           "Arabic root ن ع م (n-ʿ-m); نِعْمَة (Niʿma)", False, "high",
           "Nimah is Arabic نِعْمَة (Niʿma) 'blessing, favour', from the root ن ع م (n-ʿ-m). The source gloss 'Grace, Beauty' is broadly consistent. Same name as neima."),
 "nimat": ("نِعْمَة", "نعمہ", "نعمه", "निमत", "نعمه", "blessing", "Arabic", "Female",
           "Arabic root ن ع م (n-ʿ-m); نِعْمَة (Niʿma)", False, "high",
           "Nimat is Arabic نِعْمَة (Niʿma) 'blessing, favour, grace', from the root ن ع م (n-ʿ-m). The source gloss 'Blessing, Grace' is consistent. Same name as neima."),
 "nimr": ("نِمْر", "نمر", "نمر", "निम्र", "نمر", "nimr", "Arabic", "Male",
          "Arabic root ن م ر (n-m-r); نِمْر (Nimr)", False, "high",
          "Nimr is Arabic نِمْر (Nimr) 'leopard, panther', from the root ن م ر (n-m-r). The source gloss 'Lion' is unsupported and has been replaced with the lexical sense."),
 "nimra": ("نِمْرَة", "نمرہ", "نمره", "निमरा", "نمره", "nimra", "Arabic", "Female",
           "Arabic نِمْرَة (Nimra)", False, "medium",
           "Nimra is recorded as Arabic نِمْرَة (Nimra), a female given name. CRITICAL SOURCE ERROR: the source gave the placeholder 'عربي_Nimra'; the correct form is نِمْرَة. The source gloss 'Noble and blessed' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nimrah": ("نِمْرَة", "نمرہ", "نمره", "निमरा", "نمره", "nimrah", "Arabic", "Female",
            "Arabic نِمْرَة (Nimra)", False, "medium",
            "Nimrah is recorded as Arabic نِمْرَة (Nimra), a female given name. The source gloss 'Pure and Clean' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as nimra."),
 "nimrat": ("نِمْرَت", "نمرت", "نمرت", "निमरत", "نمرت", "nimrat", "Arabic", "Female",
            "Arabic نِمْرَت (Nimrat)", False, "medium",
            "Nimrat is recorded as Arabic نِمْرَت (Nimrat), a female given name. CRITICAL SOURCE ERROR: the source gave نمرةت (a non-standard form). The source gloss 'Night' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nina": ("نِينَا", "نینا", "نینا", "नीना", "نینا", "nina", "Arabic", "Female",
          "Arabic نِينَا (Nīnā)", False, "medium",
          "Nina is recorded as Arabic نِينَا (Nīnā), a female given name. The source gloss 'Gentle, delicate' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ninos": ("نِينُوس", "نینوس", "نینوس", "निनोस", "نینوس", "ninos", "Aramaic", "Male",
           "Aramaic Ninos", False, "high",
           "Ninos is an Aramaic male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Ninos' instead of a script form and labelled the origin Arabic; the name is Aramaic. The source gloss 'Little boy' is unsupported and has been replaced with the documented identification."),
 "nisa": ("نِسَاء", "نساء", "نساء", "निसा", "نساء", "women", "Arabic", "Female",
          "Arabic root ن س و (n-s-w); نِسَاء (Nisāʾ)", False, "high",
          "Nisa is Arabic نِسَاء (Nisāʾ) 'women', from the root ن س و (n-s-w). The source gloss 'Women, Lady' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender. Same name as nisaa."),
 "nisaa": ("نِسَاء", "نساء", "نساء", "निसा", "نساء", "women", "Arabic", "Female",
           "Arabic root ن س و (n-s-w); نِسَاء (Nisāʾ)", False, "high",
           "Nisaa is Arabic نِسَاء (Nisāʾ) 'women', from the root ن س و (n-s-w). The source gloss 'Four Women' is unsupported and has been replaced with the lexical sense. Same name as nisa."),
 "nisar": ("نِثَار", "نثار", "نثار", "निसार", "نثار", "nisar", "Arabic", "Male",
           "Arabic root ن ث ر (n-th-r); نِثَار (Nithār)", False, "high",
           "Nisar is Arabic نِثَار (Nithār) 'sacrifice, scattering', from the root ن ث ر (n-th-r). The source gloss 'Friend, Intimate, Companion' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nishat": ("نِشَاط", "نشاط", "نشاط", "निशात", "نشاط", "garden", "Urdu", "Female",
            "Urdu نشاط (nishāt), from Arabic نَشَاط", False, "high",
            "Nishat is Urdu نشاط (nishāt) 'joy, liveliness', from Arabic نَشَاط (nashāṭ). CRITICAL SOURCE ERROR: the source gave نِشَةَط (a broken form) and labelled the origin Arabic; the name as used is Urdu. The source gloss 'Garden, Paradise' is unsupported and has been replaced with the lexical sense."),
 "nisma": ("نَسْمَة", "نسمہ", "نسمه", "नसमा", "نسمه", "nisma", "Arabic", "Female",
           "Arabic root ن س م (n-s-m); نَسْمَة (Nasma)", False, "high",
           "Nisma is Arabic نَسْمَة (Nasma) 'a breeze, a breath', from the root ن س م (n-s-m). The source gloss 'Gift of God' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as nasma."),
 "nisreen": ("نِسْرِين", "نسرین", "نسرین", "निसरीन", "نسرین", "nisreen", "Persian", "Female",
             "Persian نسرین (nasrīn)", False, "high",
             "Nisreen is Persian نسرین (nasrīn) 'wild rose, narcissus'. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nasreen."),
 "nisrin": ("نِسْرِين", "نسرین", "نسرین", "निसरीन", "نسرین", "nisrin", "Persian", "Female",
            "Persian نسرین (nasrīn)", False, "high",
            "Nisrin is Persian نسرین (nasrīn) 'wild rose, narcissus'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Venus, love, beauty' is unsupported and has been replaced with the lexical sense. Same name as nasreen."),
 "nissa": ("نِسَاء", "نساء", "نساء", "निसा", "نساء", "women", "Arabic", "Female",
           "Arabic root ن س و (n-s-w); نِسَاء (Nisāʾ)", False, "high",
           "Nissa is a spelling variant of Arabic نِسَاء (Nisāʾ) 'women', from the root ن س و (n-s-w). The source gloss 'Women, Lady' is consistent. Same name as nisa."),
 "nissan": ("نِيسَان", "نیسان", "نیسان", "निसान", "نیسان", "nissan", "Aramaic", "Male",
            "Aramaic Nisan", False, "high",
            "Nissan is an Aramaic male given name (also the month Nisan). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Aramaic. The source gloss 'Fruit' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nitasha": ("نِيتَاشَا", "نتاشا", "نتاشا", "निताशा", "نتاشا", "nitasha", "Hindi", "Female",
             "Hindi निताशा (nitāśā)", False, "medium",
             "Nitasha is a Hindi/Bengali female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Hindi/Bengali. The source gloss 'Night, Star' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nivin": ("نِيفِين", "نیون", "نیون", "निविन", "نیون", "nivin", "Arabic", "Female",
           "Arabic نِيفِين (Nīfīn)", False, "high",
           "Nivin is Arabic نِيفِين (Nīfīn) 'beautiful, fair'. CRITICAL SOURCE ERROR: the source gave عائشة (a different name); the correct form is نِيفِين. The source gloss 'Gift, Grace' is unsupported and has been replaced with the lexical sense. Same name as neveen."),
 "niyaz": ("نِيَاز", "نیاز", "نیاز", "नियाज़", "نیاز", "niyaz", "Persian", "Male",
           "Persian نیاز (niyāz)", False, "high",
           "Niyaz is Persian نیاز (niyāz) 'supplication, entreaty'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'performing the daily acts of worship' is unsupported and has been replaced with the lexical sense. Same name as niaz."),
 "niyazi": ("نِيَازِي", "نیازی", "نیازی", "नियाज़ी", "نیازي", "niyazi", "Persian", "Male",
            "Persian نیاز (niyāz) + relational ending", False, "high",
            "Niyazi is Persian نیاز (niyāz) + a relational ending, a male given name. CRITICAL SOURCE ERROR: the source gave نِيَازِي (a non-standard form) and labelled the origin Arabic; the name is Persian. The source gloss 'Righteous one' is unsupported and has been replaced with the documented identification. Same name as niazi."),
 "nizaar": ("نِزَار", "نزار", "نزار", "निज़ार", "نزار", "nizaar", "Arabic", "Male",
            "Arabic نِزَار (Nizār)", False, "high",
            "Nizaar is Arabic نِزَار (Nizār), a male given name. The source gloss 'Guide, Protector' is unsupported and has been replaced with the documented identification. Same name as nizar."),
 "nizal": ("نِزَال", "نزال", "نزال", "निज़ाल", "نزال", "nizal", "Arabic", "Male",
           "Arabic root ن ز ل (n-z-l); نِزَال (Nizāl)", False, "high",
           "Nizal is Arabic نِزَال (Nizāl), a male given name, from the root ن ز ل (n-z-l). CRITICAL SOURCE ERROR: the source gave نزل (a different form); the correct form is نِزَال. The source gloss 'Ascending, Mounting, Rising' is unsupported and has been replaced with the documented identification."),
 "nizam": ("نِظَام", "نظام", "نظام", "निज़ाम", "نظام", "nizam", "Arabic", "Male",
           "Arabic root ن ظ م (n-ẓ-m); نِظَام (Niẓām)", False, "high",
           "Nizam is Arabic نِظَام (Niẓām) 'order, system, arrangement', from the root ن ظ م (n-ẓ-m). The source gloss 'Order, stability, system' is consistent."),
 "nizami": ("نِظَامِي", "نظامی", "نظامی", "निज़ामी", "نظامي", "nizami", "Arabic", "Male",
            "Arabic نِظَامِي (Niẓāmī) 'of order'", False, "high",
            "Nizami is Arabic نِظَامِي (Niẓāmī) 'of order, regulatory', a relational adjective from نِظَام (niẓām). The source gloss 'Memory, Knowledge' is unsupported and has been replaced with the lexical sense."),
 "nizar": ("نِزَار", "نزار", "نزار", "निज़ार", "نزار", "nizar", "Arabic", "Male",
           "Arabic نِزَار (Nizār)", False, "high",
           "Nizar is Arabic نِزَار (Nizār), a male given name. The source gloss 'Victory, Glory' is unsupported and has been replaced with the documented identification. Same name as nizaar."),
 "noaman": ("نُعْمَان", "نعمان", "نعمان", "नोमान", "نعمان", "naaman2", "Arabic", "Male",
            "Arabic نُعْمَان (Nuʿmān)", False, "high",
            "Noaman is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. CRITICAL SOURCE ERROR: the source gave نُعَمَان (a non-standard form). The source gloss 'Restorer' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "nobar": ("نُوبَر", "نوبر", "نوبر", "नोबर", "نوبر", "nobar", "Persian", "Male",
           "Persian نوبر (nowbar)", False, "medium",
           "Nobar is a Persian male given name. CRITICAL SOURCE ERROR: the source gave أحمد (a different name) and labelled the origin Arabic; the name is Persian. The source gloss 'Noble, Bright' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nofal": ("نَوْفَل", "نوفل", "نوفل", "नौफ़ल", "نوفل", "nofal", "Arabic", "Male",
           "Arabic نَوْفَل (Nawfal)", False, "high",
           "Nofal is a spelling variant of Arabic نَوْفَل (Nawfal), a male given name. The source gloss 'Wolf' is unsupported and has been replaced with the documented identification. Same name as naufal."),
 "noha": ("نُهَى", "نہیٰ", "نهی", "नुहा", "نهی", "noha", "Arabic", "Female",
          "Arabic root ن ه ي (n-h-y); نُهَى (Nuhā)", False, "high",
          "Noha is Arabic نُهَى (Nuhā) 'intelligence, understanding', from the root ن ه ي (n-h-y). The source gloss 'Rest, Repose, Serenity' is unsupported and has been replaced with the lexical sense. Same name as nuha."),
 "nojood": ("نُجُود", "نجود", "نجود", "नजूद", "نجود", "nojood", "Arabic", "Female",
            "Arabic نُجُود (Nujūd)", False, "medium",
            "Nojood is recorded as Arabic نُجُود (Nujūd), a female given name. CRITICAL SOURCE ERROR: the source gave نجود (a non-standard form). The source gloss 'Gentle Breeze' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nomaan": ("نُعْمَان", "نعمان", "نعمان", "नोमान", "نعمان", "naaman2", "Arabic", "Male",
            "Arabic نُعْمَان (Nuʿmān)", False, "high",
            "Nomaan is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. The source gloss 'Relenting, Forgiving' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "noman": ("نُعْمَان", "نعمان", "نعمان", "नोमान", "نعمان", "naaman2", "Arabic", "Male",
           "Arabic نُعْمَان (Nuʿmān)", False, "high",
           "Noman is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. The source gloss 'Tranquil, Restful' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "nooh": ("نُوح", "نوح", "نوح", "नूह", "نوح", "nuh", "Arabic", "Male",
          "Arabic نُوح (Nūḥ), the prophet Noah", False, "high",
          "Nooh is Arabic نُوح (Nūḥ), the name of the prophet Noah. The source gloss 'Rest, Repose, Peace' is unsupported and has been replaced with the documented identification. Same name as nuh."),
 "noon": ("نُون", "نون", "نون", "नून", "نون", "noon", "Arabic", "Male",
          "Arabic نُون (Nūn), the letter nūn", False, "high",
          "Noon is Arabic نُون (Nūn), the name of the Arabic letter nūn. CRITICAL SOURCE ERROR: the source gave the Latin string 'Noon' instead of a script form and labelled the gender unisex; the form is a letter name with no personal-name gender. The source gloss '12th month' is unsupported and has been replaced with the lexical sense."),
 "nooni": ("نُونِي", "نونی", "نونی", "नूनी", "نوني", "nooni", "Arabic", "Female",
           "Arabic نُونِي (Nūnī)", False, "medium",
           "Nooni is recorded as Arabic نُونِي (Nūnī), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nooni' instead of a script form. The source gloss 'Nur or Light' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "noor": ("نُور", "نور", "نور", "नूर", "نور", "light", "Arabic", "Female",
          "Arabic root ن و ر (n-w-r); نُور (Nūr)", False, "high",
          "Noor is Arabic نُور (Nūr) 'light, radiance', from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nour."),
 "noora": ("نُورَة", "نورہ", "نوره", "नूरा", "نوره", "noora", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
           "Noora is Arabic نُورَة (Nūra) 'light' (feminine), from the root ن و ر (n-w-r). The source gloss 'Light' is consistent. Same name as noura."),
 "noorah": ("نُورَة", "نورہ", "نوره", "नूरा", "نوره", "noorah", "Arabic", "Female",
            "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
            "Noorah is Arabic نُورَة (Nūra) 'light' (feminine), from the root ن و ر (n-w-r). The source gloss 'Light of God' is unsupported and has been replaced with the lexical sense. Same name as noura."),
 "noorain": ("نُورَيْن", "نورین", "نورین", "नूरैन", "نورین", "noorain", "Arabic", "Female",
             "Arabic نُور (nūr) + dual ending", False, "high",
             "Noorain is Arabic نُورَيْن (Nūrayn) 'two lights', from نُور (nūr) 'light'. The source gloss 'Light of the moon' is unsupported and has been replaced with the lexical sense."),
 "nooran": ("نُورَان", "نوران", "نوران", "नूरान", "نوران", "nooran", "Arabic", "Female",
            "Arabic نُور (nūr) + -ān", False, "high",
            "Nooran is Arabic نُورَان (Nūrān) 'full of light', from نُور (nūr) 'light'. The source gloss 'Radiant, Full of Light' is consistent."),
 "noorani": ("نُورَانِي", "نورانی", "نورانی", "नूरानी", "نوراني", "noorani", "Arabic", "Female",
             "Arabic نُورَانِي (Nūrānī) 'luminous'", False, "high",
             "Noorani is Arabic نُورَانِي (Nūrānī) 'luminous, of light', a relational adjective from نُور (nūr). The source gloss 'Light' is broadly consistent."),
 "noore": ("نُورَة", "نورہ", "نوره", "नूरे", "نوره", "noore", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
           "Noore is Arabic نُورَة (Nūra) 'light, glow', from the root ن و ر (n-w-r). The source gloss 'Light, Glow' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as noura."),
 "noori": ("نُورِي", "نوری", "نوری", "नूरी", "نوري", "noori", "Arabic", "Female",
           "Arabic نُورِي (Nūrī) 'luminous'", False, "high",
           "Noori is Arabic نُورِي (Nūrī) 'luminous, of light', a relational adjective from نُور (nūr). The source gloss 'Light, Radiance' is consistent."),
 "noorjahan": ("نُور جِهَان", "نورجہاں", "نورجہان", "नूरजहाँ", "نورجہان", "noorjahan", "Arabic", "Female",
               "Arabic نُور (nūr) + جِهَان (jihān)", False, "high",
               "Noorjahan is Arabic نُور جِهَان (Nūr Jihān) 'light of the world', from نُور (nūr) 'light' + جِهَان (jihān) 'world'. CRITICAL SOURCE ERROR: the source gave 'نورcahan' (a broken Latin-Arabic mix); the correct form is نُور جِهَان. The source gloss 'Light of the World' is consistent."),
 "noorul": ("نُورُ الـ", "نور ال", "نور ال", "नूरुल", "نور ال", "noorul", "Arabic", "Male",
            "Arabic نُور (nūr) in construct with the article", False, "high",
            "Noorul is Arabic نُورُ الـ (Nūru l-) 'light of', a construct form of نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nooshin": ("نُوشِين", "نوشین", "نوشین", "नूशीन", "نوشین", "nooshin", "Persian", "Female",
             "Persian نوشین (naushīn)", False, "high",
             "Nooshin is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Light, Radiant' is unsupported and has been replaced with the lexical sense. Same name as nausheen."),
 "nora": ("نُورَة", "نورہ", "نوره", "नोरा", "نوره", "nora", "Arabic", "Female",
          "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
          "Nora is Arabic نُورَة (Nūra) 'light' (feminine), from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is نُورَة. The source gloss 'Light, Radiant' is consistent. Same name as noura."),
 "norah": ("نُورَة", "نورہ", "نوره", "नोरा", "نوره", "norah", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
           "Norah is Arabic نُورَة (Nūra) 'light' (feminine), from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source gave نوراه (a non-standard form). The source gloss 'Light' is consistent. Same name as noura."),
 "noreen": ("نُورِين", "نورین", "نورین", "नौरीन", "نورین", "noreen", "Arabic", "Female",
            "Arabic نُور (nūr) + feminine ending", False, "high",
            "Noreen is Arabic نُورِين (Nūrīn) 'light, luminous', from نُور (nūr) 'light'. The source gloss 'Light, radiant' is consistent. Same name as naureen."),
 "norhan": ("نُور حَان", "نورحان", "نورحان", "नूरहान", "نورحان", "norhan", "Arabic", "Female",
            "Arabic نُور (nūr) + حَان", False, "high",
            "Norhan is Arabic نُور حَان (Nūr Ḥān) 'light, illumination', from نُور (nūr) 'light'. CRITICAL SOURCE ERROR: the source gave نوران (a different form); the correct form is نُور حَان. The source gloss 'Gift from Allah' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "noriza": ("نُورِيزَة", "نوریزہ", "نوریزه", "नोरीज़ा", "نوریزه", "noriza", "Arabic", "Female",
            "Arabic نُور (nūr) + -iza", False, "medium",
            "Noriza is recorded as Arabic نُورِيزَة (Nūrīza), a female given name derived from نُور (nūr) 'light'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Noriza' instead of a script form. The source gloss 'Light, bright, beautiful' is broadly consistent. The identification is recorded at medium confidence."),
 "noshaba": ("نُوشَابَة", "نوشابہ", "نوشابه", "नौशाबा", "نوشابه", "noshaba", "Persian", "Female",
             "Persian نوشابه (nūshāba)", False, "medium",
             "Noshaba is a Persian female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Gift, blessing' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nosheen": ("نُوشِين", "نوشین", "نوشین", "नौशीन", "نوشین", "nosheen", "Persian", "Female",
             "Persian نوشین (naushīn)", False, "high",
             "Nosheen is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Light, Illumination' is unsupported and has been replaced with the lexical sense. Same name as nausheen."),
 "noshi": ("نُوشِي", "نوشی", "نوشی", "नौशी", "نوشي", "noshi", "Persian", "Female",
           "Persian نوشی (nūshī)", False, "medium",
           "Noshi is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Noshi' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Gift, Blessing' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "noshin": ("نُوشِين", "نوشین", "نوشین", "नौशीन", "نوشین", "noshin", "Persian", "Female",
            "Persian نوشین (naushīn)", False, "high",
            "Noshin is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Gift, Grace' is unsupported and has been replaced with the lexical sense. Same name as nausheen."),
 "nouf": ("نَوْف", "نوف", "نوف", "नौफ़", "نوف", "nouf", "Arabic", "Female",
          "Arabic نَوْف (Nawf)", False, "medium",
          "Nouf is recorded as Arabic نَوْف (Nawf), a female given name. The source gloss 'Soft, gentle breeze' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "noufal": ("نَوْفَل", "نوفل", "نوفل", "नौफ़ल", "نوفل", "noufal", "Arabic", "Male",
            "Arabic نَوْفَل (Nawfal)", False, "high",
            "Noufal is a spelling variant of Arabic نَوْفَل (Nawfal), a male given name. The source gloss 'Flooded' is unsupported and has been replaced with the documented identification. Same name as naufal."),
 "nouh": ("نُوح", "نوح", "نوح", "नूह", "نوح", "nuh", "Arabic", "Male",
          "Arabic نُوح (Nūḥ), the prophet Noah", False, "high",
          "Nouh is Arabic نُوح (Nūḥ), the name of the prophet Noah. The source gloss 'Prophet Noah' is consistent. Same name as nuh."),
 "nouha": ("نُهَى", "نہیٰ", "نهی", "नुहा", "نهی", "nouha", "Arabic", "Female",
           "Arabic root ن ه ي (n-h-y); نُهَى (Nuhā)", False, "high",
           "Nouha is Arabic نُهَى (Nuhā) 'intelligence, understanding', from the root ن ه ي (n-h-y). CRITICAL SOURCE ERROR: the source gave نُوحَى (a non-standard form). The source gloss 'Gift, Grace' is unsupported and has been replaced with the lexical sense. Same name as nuha."),
 "nouman": ("نُعْمَان", "نعمان", "نعمان", "नोमान", "نعمان", "naaman2", "Arabic", "Male",
            "Arabic نُعْمَان (Nuʿmān)", False, "high",
            "Nouman is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as naaman."),
 "nour": ("نُور", "نور", "نور", "नूर", "نور", "light", "Arabic", "Female",
          "Arabic root ن و ر (n-w-r); نُور (Nūr)", False, "high",
          "Nour is Arabic نُور (Nūr) 'light, radiance', from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as noor."),
 "noura": ("نُورَة", "نورہ", "نوره", "नूरा", "نوره", "noura", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
           "Noura is Arabic نُورَة (Nūra) 'light' (feminine), from the root ن و ر (n-w-r). The source gloss 'Light' is consistent. Same name as noora."),
 "nouran": ("نُورَان", "نوران", "نوران", "नूरान", "نوران", "nouran", "Arabic", "Female",
            "Arabic نُور (nūr) + -ān", False, "high",
            "Nouran is Arabic نُورَان (Nūrān) 'full of light', from نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. Same name as nooran."),
 "noureen": ("نُورِين", "نورین", "نورین", "नौरीन", "نورین", "noureen", "Arabic", "Female",
             "Arabic نُور (nūr) + feminine ending", False, "high",
             "Noureen is Arabic نُورِين (Nūrīn) 'light, luminous', from نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. Same name as naureen."),
 "nourhan": ("نُور حَان", "نورحان", "نورحان", "नूरहान", "نورحان", "nourhan", "Arabic", "Female",
             "Arabic نُور (nūr) + حَان", False, "high",
             "Nourhan is Arabic نُور حَان (Nūr Ḥān) 'light, illumination', from نُور (nūr) 'light'. The source gloss 'Light, Illumination' is consistent. Same name as norhan."),
 "nouria": ("نُورِيَة", "نوریہ", "نوریه", "नूरिया", "نوریه", "nouria", "Arabic", "Female",
            "Arabic نُورِيَة (Nūriyya) 'luminous'", False, "high",
            "Nouria is Arabic نُورِيَة (Nūriyya) 'luminous, of light', from نُور (nūr) 'light'. The source gloss 'Light, Radiance' is consistent."),
 "nousha": ("نُوشَا", "نوشہ", "نوشا", "नौशा", "نوشا", "nousha", "Persian", "Female",
            "Persian نوشا (nūshā)", False, "medium",
            "Nousha is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nousha' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Light, Radiant' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "noushin": ("نُوشِين", "نوشین", "نوشین", "नौशीन", "نوشین", "noushin", "Persian", "Female",
             "Persian نوشین (naushīn)", False, "high",
             "Noushin is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the word is Persian. The source gloss 'Jewel' is unsupported and has been replaced with the lexical sense. Same name as nausheen."),
 "novin": ("نُوفِين", "نوین", "نوین", "नोवीन", "نوین", "novin", "Persian", "Female",
           "Persian نوین (novīn)", False, "high",
           "Novin is Persian نوین (novīn) 'new, fresh'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Novin' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'New, Fresh' is consistent."),
 "noya": ("نُويَة", "نویہ", "نویا", "नोया", "نویا", "noya", "Arabic", "Female",
          "Arabic نُويَة (Nuya)", False, "medium",
          "Noya is recorded as Arabic نُويَة (Nuya), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Noya' instead of a script form. The source gloss 'New, fresh, young' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nuaim": ("نُعَيْم", "نعیم", "نعیم", "नुऐम", "نعیم", "nuaim", "Arabic", "Male",
           "Arabic نُعَيْم (Nuʿaym)", False, "high",
           "Nuaim is Arabic نُعَيْم (Nuʿaym), a male given name. The source gloss 'Given by God' is unsupported and has been replaced with the documented identification."),
 "nufail": ("نُفَيْل", "نفیل", "نفیل", "नुफ़ैल", "نفیل", "nufail", "Arabic", "Male",
            "Arabic نُفَيْل (Nufayl)", False, "high",
            "Nufail is Arabic نُفَيْل (Nufayl), a male given name. CRITICAL SOURCE ERROR: the source gave نُفَيْل (a non-standard form). The source gloss 'Successful in Faith' is unsupported and has been replaced with the documented identification."),
 "nuh": ("نُوح", "نوح", "نوح", "नूह", "نوح", "nuh", "Arabic", "Male",
         "Arabic نُوح (Nūḥ), the prophet Noah", False, "high",
         "Nuh is Arabic نُوح (Nūḥ), the name of the prophet Noah. The source gloss 'Prophet Noah' is consistent."),
 "nuha": ("نُهَى", "نہیٰ", "نهی", "नुहा", "نهی", "nuha", "Arabic", "Female",
          "Arabic root ن ه ي (n-h-y); نُهَى (Nuhā)", False, "high",
          "Nuha is Arabic نُهَى (Nuhā) 'intelligence, understanding', from the root ن ه ي (n-h-y). The source gloss 'Prophetess in Arabic mythology' is unsupported and has been replaced with the lexical sense. Same name as noha."),
}
