# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 3 (adeela..afsar).

Every entry records ONLY what can be defended. `conf` is the honest confidence in the
lexical identification. `unverified` means the form could not be matched to a Tier-A/B
source and NO gloss is asserted (the record says so explicitly).

Fields: ar, ur, fa, hi, ps  -> script forms (None = not established for that language)
        gloss -> key into GLOSSES (None = no verified gloss)
        origin, gender, root, quranic, conf, note
"""

GLOSSES = {
    "just_fair": {"en": "Just, fair, honest", "ur": "عادل، منصف، سچا", "fa": "عادل، دادگر، درستکار", "hi": "न्यायी, निष्पक्ष, ईमानदार", "ps": "عادل، منصف، رښتونی", "ar": "عادل، منصف، مستقيم"},
    "man": {"en": "Man, human being", "ur": "انسان، آدم", "fa": "انسان، آدم", "hi": "मनुष्य, आदम", "ps": "انسان، آدم", "ar": "إنسان، آدم"},
    "joy": {"en": "Joy, happiness", "ur": "خوشی، مسرت", "fa": "شادی، خوشحالی", "hi": "खुशी, आनंद", "ps": "خوښي، مړوندتوب", "ar": "فرح، سعادة"},
    "sacrifice": {"en": "Sacrifice, offering", "ur": "قربانی، نذر", "fa": "قربانی، نذر", "hi": "क़ुर्बानी, बलिदान", "ps": "قرباني، نذر", "ar": "أضحية، قربان"},
    "black": {"en": "Black, dark (of horses)", "ur": "سیاہ، کالا", "fa": "سیاه، تیره", "hi": "काला, स्याह", "ps": "تور، تیاره", "ar": "أدهم، أسود"},
    "friend": {"en": "Friend, companion", "ur": "دوست، ساتھی", "fa": "دوست، همراه", "hi": "मित्र, साथी", "ps": "ملګری، همکار", "ar": "صديق، رفيق"},
    "cultured": {"en": "Cultured, refined, literate", "ur": "ادیب، مہذب، باادب", "fa": "ادیب، فرهنگ‌دوست، باادب", "hi": "सुसंस्कृत, शिष्ट, साहित्यिक", "ps": "ادیب، باادب", "ar": "أديب، مهذّب، مثقّف"},
    "justice": {"en": "Justice, fairness", "ur": "عدل، انصاف", "fa": "عدالت، داد", "hi": "न्याय, इंसाफ़", "ps": "عدالت، انصاف", "ar": "عدل، إنصاف"},
    "divine_gift": {"en": "Divine gift, creation", "ur": "خدائی عطیہ، تخلیق", "fa": "بخشش الهی، آفرینش", "hi": "ईश्वरीय उपहार, सृष्टि", "ps": "الهي ډالۍ، پيدايښت", "ar": "عطاء إلهي، خلق"},
    "settler": {"en": "Settler, one who dwells", "ur": "بسنے والا، مقیم", "fa": "ساکن، ماندگار", "hi": "निवासी, बसने वाला", "ps": "اوسېدونکی، مېشت", "ar": "مستوطن، مقيم"},
    "light_rain": {"en": "Light rain", "ur": "ہلکی بارش", "fa": "باران سبک", "hi": "हल्की वर्षा", "ps": "سپک باران", "ar": "مطر خفيف"},
    "dark_one": {"en": "Dark one, little dark one", "ur": "کالا، سیاہ", "fa": "تیره، سیاه", "hi": "काला, साँवला", "ps": "تور، تیاره", "ar": "أدريانة، داكنة"},
    "grievance": {"en": "Grievance, complaint", "ur": "شکایت، گلہ", "fa": "شکایت، گلایه", "hi": "शिकायत, गिला", "ps": "شکایت، ګیله", "ar": "شكوى، عتب"},
    "sweetness": {"en": "Sweetness, delight, happiness", "ur": "مٹھاس، خوشی", "fa": "شیرینی، شادی", "hi": "मिठास, खुशी", "ps": "خوږوالی، خوښي", "ar": "حلاوة، بهجة"},
    "worshipper_devotee": {"en": "Worshipper, devotee", "ur": "عابد، پرستش کرنے والا", "fa": "پرستشگر، بنده", "hi": "उपासक, भक्त", "ps": "عبادت کوونکی، بنده", "ar": "عابد، متعبّد"},
    "lady_house": {"en": "Lady of the house", "ur": "گھر کی خاتون", "fa": "بانوی خانه", "hi": "घर की स्वामिनी", "ps": "د کور مېرمن", "ar": "سيّدة البيت"},
    "strong": {"en": "Strong, powerful", "ur": "طاقتور، زبردست", "fa": "نیرومند، توانا", "hi": "शक्तिशाली, बलवान", "ps": "پیاوړی، ځواکمن", "ar": "قوي، عزيز"},
    "faithful": {"en": "Faithful, trustworthy", "ur": "وفادار، امانتدار", "fa": "وفادار، امین", "hi": "वफ़ादार, विश्वसनीय", "ps": "وفادار، امانتدار", "ar": "أمين، مخلص"},
    "chastity": {"en": "Chastity, modesty, virtue", "ur": "عفت، پاکدامنی", "fa": "عفت، پاکدامنی", "hi": "सतीत्व, पवित्रता", "ps": "عفت، پاکدامني", "ar": "عفاف، عفة"},
    "horizons": {"en": "Horizons, world, universe", "ur": "افق، دنیا، کائنات", "fa": "افق‌ها، جهان", "hi": "क्षितिज, संसार", "ps": "افقونه، نړۍ", "ar": "آفاق، أفق"},
    "rare_beautiful": {"en": "Rare and beautiful", "ur": "نایاب اور خوبصورت", "fa": "کم‌یاب و زیبا", "hi": "दुर्लभ और सुंदर", "ps": "کم پيدا او ښکلی", "ar": "نادر وجميل"},
    "delicacy": {"en": "Delicacy, tenderness", "ur": "نزاکت، نرمی", "fa": "لطافت، نرمی", "hi": "कोमलता, नज़ाकत", "ps": "نازکتیا، نرمي", "ar": "لطافة، نعومة"},
    "excellence": {"en": "Excellence, perfection", "ur": "برتری، کمال", "fa": "برتری، کمال", "hi": "श्रेष्ठता, उत्कृष्टता", "ps": "غوره والی، بشپړتيا", "ar": "أفضلية، كمال"},
    "pure_chaste": {"en": "Pure and chaste", "ur": "پاک اور عفت والی", "fa": "پاک و پاکدامن", "hi": "पवित्र और सती", "ps": "پاکه او عفته", "ar": "عفيفة، طاهرة"},
    "safe_secure": {"en": "Safe, secure, protected", "ur": "محفوظ، امن میں", "fa": "امن، محفوظ", "hi": "सुरक्षित, महफ़ूज़", "ps": "خوندي، امن", "ar": "آمن، محفوظ"},
    "wise_understanding": {"en": "Wise, understanding", "ur": "دانا، سمجھدار", "fa": "دانا، فهیم", "hi": "बुद्धिमान, समझदार", "ps": "پوه، پوهاوی لرونکی", "ar": "حكيم، فهيم"},
    "life_giving": {"en": "Life-giving, health", "ur": "زندگی دینے والی، صحت", "fa": "زندگی‌بخش، تندرستی", "hi": "जीवनदायी, स्वास्थ्य", "ps": "ژوند ورکوونکی، روغتیا", "ar": "مانحة الحياة، عافية"},
    "pure_innocent": {"en": "Pure, innocent", "ur": "پاک، معصوم", "fa": "پاک، معصوم", "hi": "पवित्र, निर्दोष", "ps": "پاک، معصوم", "ar": "نقية، بريئة"},
    "protector": {"en": "Protector, guardian", "ur": "محافظ، نگہبان", "fa": "نگهبان، محافظ", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، پالونکی", "ar": "حفيظ، حامية"},
    "honesty": {"en": "Honesty, sincerity", "ur": "سچائی، خلوص", "fa": "صداقت، خلوص", "hi": "ईमानदारी, निष्ठा", "ps": "رښتيا، اخلاص", "ar": "صدق، إخلاص"},
    "knowledgeable": {"en": "Knowledgeable, intelligent", "ur": "عالم، ذہین", "fa": "دانا، خردمند", "hi": "ज्ञानी, बुद्धिमान", "ps": "پوه، ځیرک", "ar": "عالم، فقيه"},
    "health": {"en": "Health, wellness, peace", "ur": "صحت، تندرستی، سکون", "fa": "تندرستی، سلامت، آرامش", "hi": "स्वास्थ्य, कुशलता, शांति", "ps": "روغتیا، سکون", "ar": "عافية، صحة، سلام"},
    "healthy": {"en": "Healthy, sound", "ur": "صحت مند، تندرست", "fa": "تندرست، سالم", "hi": "स्वस्थ, कुशल", "ps": "روغ، جوړ", "ar": "معافى، سليمة"},
    "pure_clear": {"en": "Pure, clear", "ur": "پاک، صاف", "fa": "پاک، روشن", "hi": "पवित्र, स्वच्छ", "ps": "پاک، روښانه", "ar": "نقي، صاف"},
    "thoughts": {"en": "Thoughts, ideas", "ur": "خیالات، افکار", "fa": "اندیشه‌ها، افکار", "hi": "विचार, भावनाएँ", "ps": "فکرونه، اندونه", "ar": "أفكار، خواطر"},
    "successful": {"en": "Successful, prosperous", "ur": "کامیاب، بامراد", "fa": "کامیاب، پیروز", "hi": "सफल, कामयाब", "ps": "بریالی، کامياب", "ar": "مفلح، ناجح"},
    "orbits": {"en": "Orbits of the heavens", "ur": "آسمانوں کے مدار", "fa": "مدارهای آسمان", "hi": "आकाश की कक्षाएँ", "ps": "د آسمانون مدارونه", "ar": "أفلاك، مدارات"},
    "loyal_servant": {"en": "Loyal and devoted servant", "ur": "وفادار اور مخلص بندہ", "fa": "بندهٔ وفادار و فداکار", "hi": "वफ़ादार और समर्पित सेवक", "ps": "وفادار او مخلص بنده", "ar": "عبد مخلص، خادم وفيّ"},
    "branches": {"en": "Branches of a tree, growth, beauty", "ur": "شاخیں، نشوونما، خوبصورتی", "fa": "شاخه‌ها، رشد، زیبایی", "hi": "शाखाएँ, विकास, सुंदरता", "ps": "څانګې، ودې، ښکلا", "ar": "أفنان، أغصان"},
    "branches_heaven": {"en": "Branches of heaven, beauty, grace", "ur": "جنت کی شاخیں، خوبصورتی", "fa": "شاخه‌های بهشت، زیبایی", "hi": "स्वर्ग की शाखाएँ, सुंदरता", "ps": "د جنت څانګې، ښکلا", "ar": "أفنين، أغصان الجنة"},
    "honor_dignity": {"en": "Honor, dignity", "ur": "عزت، وقار", "fa": "افتخار، وقار", "hi": "सम्मान, गौरव", "ps": "وياړ، وقار", "ar": "شرف، كرامة"},
    "joy_festivities": {"en": "Joy, happiness, festivities", "ur": "خوشی، مسرت، جشن", "fa": "شادی، خوشحالی، جشن", "hi": "खुशी, आनंद, उत्सव", "ps": "خوښي، مړوندتوب، جشن", "ar": "أفراح، مسرّات"},
    "frequent": {"en": "Frequent, recurring", "ur": "بار بار آنے والا", "fa": "پیاپی، مکرر", "hi": "बार-बार, नियमित", "ps": "پرله‌پسې", "ar": "متكرر، مكرّر"},
    "lord_iron": {"en": "Lord of the Iron Fortress", "ur": "لوہے کے قلعے کا مالک", "fa": "خداوند دژ آهنین", "hi": "लोहे के क़िले का स्वामी", "ps": "د اوسپنې کلا څښتن", "ar": "صاحب الحصن الحديدي"},
    "elevated": {"en": "Elevated, respected", "ur": "بلند، معزز", "fa": "والا، محترم", "hi": "उच्च, सम्मानित", "ps": "لوړ، دروند", "ar": "مرفوع، محترم"},
    "praise": {"en": "Praise, well done, bravo", "ur": "شاباش، واہ، تعریف", "fa": "آفرین، تحسین", "hi": "शाबाश, वाह, प्रशंसा", "ps": "آفرین، ښه", "ar": "أحسنت، تحية"},
    "pure_free": {"en": "Pure, free", "ur": "پاک، آزاد", "fa": "پاک، آزاد", "hi": "पवित्र, आज़ाद", "ps": "پاک، آزاد", "ar": "نقي، حر"},
    "exalted_one": {"en": "Exalted one", "ur": "بلند مرتبہ", "fa": "والامقام", "hi": "उच्च, महान", "ps": "لوړ مقام", "ar": "مرفوع، عليّ"},
    "pure_safe": {"en": "Pure, safe", "ur": "پاک، محفوظ", "fa": "پاک، امن", "hi": "पवित्र, सुरक्षित", "ps": "پاک، خوندي", "ar": "نقي، آمن"},
    "rose": {"en": "Rose", "ur": "گلاب، پھول", "fa": "گل سرخ، گل", "hi": "गुलाब, फूल", "ps": "ګلاب، ګل", "ar": "وردة، زهرة"},
    "moonlit": {"en": "Moonlit night", "ur": "چاندنی رات", "fa": "شب مهتابی", "hi": "चाँदनी रात", "ps": "سپوږمۍ شپه", "ar": "ليلة مقمرة"},
    "pure_exalted": {"en": "Pure, exalted", "ur": "پاک، بلند", "fa": "پاک، والا", "hi": "पवित्र, उच्च", "ps": "پاک، لوړ", "ar": "نقي، مرفوع"},
    "pure_gem": {"en": "Pure, precious gem", "ur": "پاک، قیمتی نگینہ", "fa": "پاک، گوهر گران‌بها", "hi": "पवित्र, बहुमूल्य रत्न", "ps": "پاک، قیمتي ګاڼه", "ar": "نقي، جوهرة"},
    "exalted_noble": {"en": "Exalted or noble", "ur": "بلند یا نجیب", "fa": "والا یا نجیب", "hi": "उच्च या कुलीन", "ps": "لوړ یا نجیب", "ar": "مرفوع أو نبيل"},
    "open_clear": {"en": "Open, clear, truthful", "ur": "کھلا، واضح، سچا", "fa": "باز، روشن، راستگو", "hi": "खुला, स्पष्ट, सच्चा", "ps": "خلاص، روښانه، رښتونی", "ar": "فسيح، واضح، صادق"},
    "storyteller": {"en": "Storyteller", "ur": "قصہ گو، داستان گو", "fa": "داستان‌گو، قصه‌گو", "hi": "कहानीकार, कथावाचक", "ps": "کیسه ویونکی", "ar": "راوي، حكواتي"},
    "story": {"en": "Story, narrative", "ur": "کہانی، داستان", "fa": "داستان، حکایت", "hi": "कहानी, कथा", "ps": "کیسه، داستان", "ar": "قصة، حكاية"},
    "tale": {"en": "A tale, a narrative, a story", "ur": "کہانی، افسانہ", "fa": "افسانه، داستان", "hi": "कहानी, किस्सा", "ps": "کیسه، افسانه", "ar": "حكاية، قصة"},
    "fable": {"en": "Fable or legend", "ur": "افسانہ، داستان", "fa": "افسانه، افسانه", "hi": "किस्सा, दंतकथा", "ps": "افسانه، نکل", "ar": "خرافة، أسطورة"},
    "commander": {"en": "Commander, leader", "ur": "سردار، کمانڈر", "fa": "فرمانده، سردار", "hi": "सेनापति, नेता", "ps": "قوماندان، مشر", "ar": "قائد، أمير"},
    "illuminating": {"en": "Illuminating, enlightening", "ur": "روشن کرنے والا، منور", "fa": "روشن‌کننده، فروزان", "hi": "प्रकाशक, उज्ज्वल", "ps": "روښانه کوونکی", "ar": "منير، مضيء"},
    "officer": {"en": "Officer, crown, chief", "ur": "افسر، تاج، سردار", "fa": "افسر، تاج، سرکرده", "hi": "अफ़सर, मुकुट, प्रमुख", "ps": "افسر، تاج، مشر", "ar": "ضابط، تاج، رئيس"},
    "adornment": {"en": "Adornment, grace", "ur": "زیبائش، رونق", "fa": "آرایش، زیبایی", "hi": "श्रृंगार, सजावट", "ps": "ښکلا، سینګار", "ar": "زينة، بهاء"},
    "helpful": {"en": "Helpful, benevolent one", "ur": "مددگار، خیر خواہ", "fa": "یاری‌گر، نیک‌خواه", "hi": "सहायक, परोपकारी", "ps": "مرسته کوونکی، خیر غوښتونکی", "ar": "معين، محسن"},
    "gentle_kind": {"en": "Gentle, kind", "ur": "نرم، مہربان", "fa": "نرم، مهربان", "hi": "कोमल, दयालु", "ps": "نرم، مهربان", "ar": "لطيف، كريم"},
    "gifted": {"en": "Gifted one, intelligent", "ur": "باصلاحیت، ذہین", "fa": "بااستعداد، خردمند", "hi": "प्रतिभाशाली, बुद्धिमान", "ps": "ځیرک، بااستعداد", "ar": "موهوب، ذكي"},
    "truthful": {"en": "Truthful, sincere", "ur": "سچا، مخلص", "fa": "راستگو، مخلص", "hi": "सच्चा, निष्ठावान", "ps": "رښتونی، مخلص", "ar": "صادق، مخلص"},
    "noble_delicate": {"en": "Noble, delicate", "ur": "نجیب، نازک", "fa": "نجیب، لطیف", "hi": "कुलीन, कोमल", "ps": "نجیب، نازک", "ar": "نبيل، لطيف"},
    "mighty": {"en": "Mighty, strong", "ur": "زبردست، طاقتور", "fa": "توانا، نیرومند", "hi": "शक्तिशाली, बलवान", "ps": "ځواکمن، پیاوړی", "ar": "عزيز، قوي"},
    "star_moon": {"en": "Star, moon", "ur": "ستارہ، چاند", "fa": "ستاره، ماه", "hi": "तारा, चाँद", "ps": "ستوری، سپوږمۍ", "ar": "نجم، قمر"},
    "adorned": {"en": "Adorned, precious one", "ur": "سجی ہوئی، قیمتی", "fa": "آراسته، گران‌بها", "hi": "सजी हुई, बहुमूल्य", "ps": "سینګار شوې، قیمتي", "ar": "مزيّنة، ثمينة"},
    "intelligent": {"en": "Intelligent, wise", "ur": "ذہین، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विद्वान", "ps": "ځیرک، پوه", "ar": "ذكي، حكيم"},
    "honorable": {"en": "Honorable, sublime", "ur": "معزز، بلند", "fa": "محترم، والا", "hi": "सम्मानित, उच्च", "ps": "دروند، لوړ", "ar": "مكرّم، جليل"},
    "scholar": {"en": "Intelligent, scholar, wise", "ur": "عالم، دانشور", "fa": "دانشمند، عالم", "hi": "विद्वान, पंडित", "ps": "عالم، پوهاند", "ar": "عالم، أديب"},
    "servant": {"en": "Servant, worshipper (of God)", "ur": "بندہ، خادم، عابد", "fa": "بنده، پرستار", "hi": "दास, सेवक, उपासक", "ps": "بنده، خدمتګار", "ar": "عبد، خادم، عابد"},
    "living": {"en": "Living, alive, prosperous", "ur": "زندہ، جیتی جاگتی", "fa": "زنده، پاینده", "hi": "जीवित, जीवंत", "ps": "ژوندی، پاتې", "ar": "حية، نابضة بالحياة"},
    "chaste": {"en": "Chaste, virtuous, modest", "ur": "پاکدامن، عفت والا", "fa": "پاکدامن، عفیف", "hi": "सती, पवित्र, संयमी", "ps": "پاکدامن، عفیف", "ar": "عفيف، عفيفة"},
}

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "adeela": ("عديلة", "عدیلہ", None, "अदीला", "عديله", "just_fair", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عديلة is a normal Arabic feminine form", "medium", "Feminine of عديل (ʿadīl, 'just, equitable'). The source record's gloss 'Honorable, Sublime' is unsupported."),
 "adeelah": ("عديلة", "عدیلہ", None, "अदीला", "عديله", "just_fair", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عديلة is a normal Arabic feminine form", "medium", "Variant romanization of عديلة."),
 "adeem": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أديم with the gloss 'Intelligent', which is unsupported. أديم is an Arabic word for 'tanned hide; surface of the earth' and its use as a personal name is not verified. No gloss is asserted."),
 "adeena": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عدینہ with the gloss 'Adorned, precious one', which is unsupported. No verified identification was established and no gloss is asserted."),
 "adeeva": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عائشة ('Āʾisha), which is a different name. The form adeeva could not be independently verified and no gloss is asserted."),
 "adel": ("عادل", "عادل", None, "आदिल", "عادل", "just_fair", "Arabic", "Male", "ع د ل", "root ع د ل occurs in the Qur'an; عادل is a normal Arabic adjective and a well-attested given name", "high", "ʿĀdil ('just, fair'). Variant romanization of Adil."),
 "adem": ("آدم", "آدم", None, "आदम", "آدم", "man", "Arabic", "Male", "أ د م", "آدم is the Qur'anic form of the name of the prophet Adam and occurs in the Qur'an", "high", "Turkish/Bosnian form of Ādam (آدم). The source record's placeholder 'Adem' is not an Arabic form."),
 "aden": ("عدن", "عدن", None, "अदन", "عدن", "joy", "Arabic", "Unisex", "ع د ن", "عدن occurs in the Qur'an as a place name (جنات عدن, the Gardens of Eden)", "medium", "ʿAdn ('Eden'), a Qur'anic place name. The source record's gloss 'Joyful, spring' is unsupported."),
 "adena": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Aisha' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "adha": ("أضحى", "اضحی", None, "अज़हा", "اضحى", "sacrifice", "Arabic", "Female", "ض ح و", "not established", "medium", "أضحى ('sacrifice; forenoon'), related to عيد الأضحى (Eid al-Adha). Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "adham": ("أدهم", "ادہم", None, "अदहम", "ادهم", "black", "Arabic", "Male", "د ه م", "not established", "high", "Adham ('black, dark'), used of jet-black horses and camels. The source record's gloss 'Man, Adam' conflates it with Ādam."),
 "adhara": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أذرة with the gloss 'Star, Moon', which is unsupported. No verified identification was established and no gloss is asserted."),
 "adi": ("عادي", "عادی", None, "आदी", "عادي", "friend", "Arabic", "Unisex", "ع د و", "not established", "low", "The source record's gloss 'Friend' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "adib": ("أديب", "ادیب", None, "अदीब", "اديب", "cultured", "Arabic", "Male", "أ د ب", "not established", "high", "Adīb ('cultured, refined, man of letters'), from أدب. The source record's form عادب is not a standard Arabic form."),
 "adiba": ("أديبة", "ادیبہ", None, "अदीबा", "اديبه", "cultured", "Arabic", "Female", "أ د ب", "not established", "high", "Feminine of أديب. The source record's form عادبة is not a standard Arabic form."),
 "adibah": ("أديبة", "ادیبہ", None, "अदीबा", "اديبه", "cultured", "Arabic", "Female", "أ د ب", "not established", "high", "Variant romanization of أديبة."),
 "adil": ("عادل", "عادل", None, "आदिल", "عادل", "just_fair", "Arabic", "Male", "ع د ل", "root ع د ل occurs in the Qur'an; عادل is a normal Arabic adjective and a well-attested given name", "high", "ʿĀdil ('just, fair, honest')."),
 "adila": ("عديلة", "عدیلہ", None, "अदीला", "عديله", "just_fair", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عديلة is a normal Arabic feminine form", "high", "Feminine of عادل/عديل."),
 "adilah": ("عديلة", "عدیلہ", None, "अदीला", "عديله", "just_fair", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عديلة is a normal Arabic feminine form", "high", "Variant romanization of عديلة."),
 "adilene": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عديلين, which is not a standard Arabic lexical form. No verified identification was established and no gloss is asserted."),
 "adillah": ("عديلة", "عدیلہ", None, "अदीला", "عديله", "just_fair", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عديلة is a normal Arabic feminine form", "medium", "Variant romanization of عديلة. The source record's gloss 'Truthful, sincere' is unsupported."),
 "adineh": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عدینه with the gloss 'Noble, Delicate', which is unsupported. No verified identification was established and no gloss is asserted."),
 "adir": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أدير with the gloss 'Man, Mighty', which is unsupported. No verified identification was established and no gloss is asserted."),
 "adiva": ("أديبة", "ادیبہ", None, "अदीवा", "اديبه", "cultured", "Arabic", "Female", "أ د ب", "not established", "low", "The source record gave أديبة (adība), a different form. The identification of adiva is uncertain."),
 "adiy": ("عدي", "عدي", None, "अदी", "عدي", "servant", "Arabic", "Male", "ع د و", "not established", "medium", "ʿAdī, a well-attested Arabic given name (e.g. ʿAdī ibn Ḥātim). The source record's gloss 'Servant of God' is unsupported."),
 "adiya": ("آديا", "آدیا", None, "आदिया", "آديا", "adornment", "Arabic", "Female", "أ د ي", "not established", "low", "The source record's gloss 'Adornment, Grace' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "adiyan": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عادلين, which is a plural form rather than a name. No verified identification was established and no gloss is asserted."),
 "adl": ("عدل", "عدل", None, "अद्ल", "عدل", "justice", "Arabic", "Male", "ع د ل", "root ع د ل occurs in the Qur'an; عدل is a normal Arabic noun", "high", "ʿAdl ('justice, fairness')."),
 "adla": ("عدلة", "عدلہ", None, "अदला", "عدله", "justice", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عدلة is a normal Arabic feminine form", "medium", "Feminine form from the root ع د ل."),
 "adlah": ("عدلة", "عدلہ", None, "अदला", "عدله", "justice", "Arabic", "Female", "ع د ل", "root ع د ل occurs in the Qur'an; عدلة is a normal Arabic feminine form", "medium", "Variant romanization of عدلة."),
 "adlan": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أدلان with the gloss 'Gentle, Kind', which is unsupported. No verified identification was established and no gloss is asserted."),
 "adli": ("عدلي", "عدلی", None, "अदली", "عدلي", "justice", "Arabic", "Male", "ع د ل", "root ع د ل occurs in the Qur'an; عدلي is a nisba adjective", "medium", "Nisba adjective from عدل ('justice')."),
 "adn": ("عدن", "عدن", None, "अदन", "عدن", "divine_gift", "Arabic", "Male", "ع د ن", "عدن occurs in the Qur'an as a place name (جنات عدن)", "low", "ʿAdn ('Eden'). The source record's gloss 'Divine gift, creation' is unsupported."),
 "adna": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عدنى with the gloss 'Adornment', which is unsupported. No verified identification was established and no gloss is asserted."),
 "adnaan": ("عدنان", "عدنان", None, "अदनान", "عدنان", "settler", "Arabic", "Male", "ع د ن", "not established", "high", "ʿAdnān, traditionally the patriarch of the Adnanite Arabs and a descendant of Ishmael. The source record's gloss 'Servant of Allah' is unsupported."),
 "adnan": ("عدنان", "عدنان", None, "अदनान", "عدنان", "settler", "Arabic", "Male", "ع د ن", "not established", "high", "Variant romanization of عدنان. The source record left this name with no origin and no script form."),
 "adr": ("عدر", "عدر", None, "अद्र", "عدر", "light_rain", "Arabic", "Unisex", "ع د ر", "not established", "low", "The source record's gloss 'Light Rain' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "adrianna": ("أدريانا", "ادریانا", None, "एड्रियाना", "ادریانا", "dark_one", "Latin", "Female", None, "not established", "medium", "Adrianna is a Latin/European name (feminine of Adrian, from Latin Hadrianus). It is not an Arabic name; the source record's Arabic form أدريانا is a transliteration rather than an Arabic lexical form."),
 "adrish": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Adrish' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "adwa": ("عدوة", "عدوہ", None, "अदवा", "عدوه", "grievance", "Arabic", "Female", "ع د و", "not established", "low", "عدوة means 'grievance, enmity'. The source record's gloss 'Grievance, complaint' is a reasonable rendering, but its use as a personal name is not verified."),
 "adwaa": ("أضواء", "اضواء", None, "अदवा", "اضواء", "sweetness", "Arabic", "Female", "ض و أ", "not established", "low", "أضواء is the plural of ضوء ('light'). The source record's gloss 'Sweetness, Delight, Happiness' is unsupported."),
 "adyan": ("عديان", "عدیان", None, "अदयान", "عديان", "worshipper_devotee", "Arabic", "Unisex", "ع د و", "not established", "low", "The source record's gloss 'worshiper, devotee' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aeesha": ("عائشة", "عائشہ", None, "आयशा", "عايشه", "living", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr, a wife of the Prophet, in the hadith and sīra tradition", "high", "Variant romanization of عائشة (ʿĀʾisha), feminine of ʿāʾish ('living')."),
 "aeisha": ("عائشة", "عائشہ", None, "आयशा", "عايشه", "lady_house", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة. The source record's gloss 'Lady of the house' is unsupported."),
 "aejaz": ("إعجاز", "اعجاز", None, "एजाज़", "اعجاز", "strong", "Arabic", "Male", "ع ج ز", "not established", "medium", "Iʿjāz ('inimitability, miracle'). The source record's form عجز is the root rather than the noun, and the gloss 'Strong, powerful one' is unsupported."),
 "aeman": ("أيمن", "ایمن", None, "ऐमन", "ایمن", "faithful", "Arabic", "Male", "ي م ن", "not established", "medium", "Ayman ('blessed, on the right'). The source record's form اعمن is malformed; the intended form is أيمن."),
 "aeni": ("عيني", "عینی", None, "ऐनी", "عيني", None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عيني ('my eye'), a possessive phrase rather than a personal name, with the gloss 'Not Applicable'. No verified identification was established and no gloss is asserted."),
 "afaaf": ("عفاف", "عفاف", None, "अफ़ाफ़", "عفاف", "chastity", "Arabic", "Female", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفاف is a normal Arabic noun", "high", "ʿAfāf ('chastity, modesty, virtue'), from the root ع ف ف."),
 "afaaq": ("آفاق", "آفاق", None, "आफ़ाक़", "آفاق", "horizons", "Arabic", "Unisex", "أ ف ق", "not established", "high", "Āfāq, plural of أفق ('horizon'). The source record's gloss 'Horizon' is the singular."),
 "afaf": ("عفاف", "عفاف", None, "अफ़ाफ़", "عفاف", "chastity", "Arabic", "Female", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفاف is a normal Arabic noun", "high", "Variant romanization of عفاف. The source record left this name with no origin and no script form."),
 "afam": ("عاف", "عاف", None, "अफ़ाम", "عاف", None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عاف with the gloss 'Rare and beautiful', which is unsupported. No verified identification was established and no gloss is asserted."),
 "afana": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Aisha' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "afandi": ("أفندي", "افندی", None, "अफ़ंदी", "افندي", "officer", "Arabic", "Male", "أ ف ن د", "not established", "medium", "Afandī, an honorific of Greek origin (αὐθέντης) widely used in Ottoman and Arabic contexts. The source record's gloss 'Intelligent, Wise' is unsupported."),
 "afaq": ("آفاق", "آفاق", None, "आफ़ाक़", "آفاق", "horizons", "Arabic", "Unisex", "أ ف ق", "not established", "high", "Āfāq, plural of أفق ('horizon')."),
 "afaque": ("آفاق", "آفاق", None, "आफ़ाक़", "آفاق", "horizons", "Arabic", "Male", "أ ف ق", "not established", "medium", "Variant romanization of آفاق. The source record's gloss 'Responsible, Trustworthy' is unsupported."),
 "afdal": ("أفضل", "افضل", None, "अफ़ज़ल", "افضل", "excellence", "Arabic", "Male", "ف ض ل", "root ف ض ل occurs in the Qur'an; أفضل is the elative of فاضل ('better, best')", "high", "Afḍal ('better, best'), elative of فاضل. The source record's gloss 'Excellence, Perfection' is a reasonable rendering."),
 "afdhal": ("أفضل", "افضل", None, "अफ़ज़ल", "افضل", "excellence", "Arabic", "Male", "ف ض ل", "root ف ض ل occurs in the Qur'an; أفضل is the elative of فاضل", "high", "Variant romanization of أفضل."),
 "afeef": ("عفيف", "عفيف", None, "अफ़ीफ़", "عفيف", "chaste", "Arabic", "Male", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفيف is a normal Arabic adjective", "high", "ʿAfīf ('chaste, virtuous, modest'). The source record's gloss 'Delight, Grace' is unsupported."),
 "afeefa": ("عفيفة", "عفيفہ", None, "अफ़ीफ़ा", "عفيفه", "pure_chaste", "Arabic", "Female", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفيفة is a normal Arabic feminine form", "high", "Feminine of عفيف."),
 "affaf": ("عفاف", "عفاف", None, "अफ़ाफ़", "عفاف", "chastity", "Arabic", "Unisex", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفاف is a normal Arabic noun", "high", "Variant romanization of عفاف."),
 "affan": ("عفان", "عفان", None, "अफ़्फ़ान", "عفان", "safe_secure", "Arabic", "Male", "ع ف ف", "not established", "medium", "ʿAffān, a well-attested Arabic given name (e.g. ʿAffān ibn Abī al-ʿĀṣ, father of the caliph ʿUthmān). The source record's gloss 'safe, secure, protected' is an approximation."),
 "afham": ("أفهم", "افہم", None, "अफ़हम", "افهم", "wise_understanding", "Arabic", "Male", "ف ه م", "not established", "medium", "Afham, elative of فَهِمَ ('to understand'), hence 'more/most understanding'. The source record's gloss 'Wise, Understanding' is a reasonable rendering."),
 "afia": ("عافية", "عافیہ", None, "आफ़िया", "عافيه", "health", "Arabic", "Female", "ع ف و", "not established", "high", "ʿĀfiya ('health, well-being, soundness')."),
 "afiaa": ("عافية", "عافیہ", None, "आफ़िया", "عافيه", "pure_innocent", "Arabic", "Female", "ع ف و", "not established", "medium", "Variant romanization of عافية. The source record's gloss 'Pure, Innocent' is unsupported."),
 "afif": ("عفيف", "عفيف", None, "अफ़ीफ़", "عفيف", "chaste", "Arabic", "Male", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفيف is a normal Arabic adjective", "high", "ʿAfīf ('chaste, virtuous'). The source record's gloss 'Trustworthy, Certain, Safe' is unsupported."),
 "afifa": ("عفيفة", "عفيفہ", None, "अफ़ीफ़ा", "عفيفه", "pure_chaste", "Arabic", "Female", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفيفة is a normal Arabic feminine form", "high", "Feminine of عفيف. The source record's form عفة is the noun rather than the feminine adjective."),
 "afifah": ("عفيفة", "عفيفہ", None, "अफ़ीफ़ा", "عفيفه", "pure_chaste", "Arabic", "Female", "ع ف ف", "root ع ف ف occurs in the Qur'an; عفيفة is a normal Arabic feminine form", "high", "Variant romanization of عفيفة."),
 "afiq": ("أفيق", "افیق", None, "अफ़ीक़", "افيق", "knowledgeable", "Arabic", "Male", "أ ف ق", "not established", "low", "The source record's gloss 'Intelligent, wise, or knowing' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "afiqah": ("أفيقة", "افیقہ", None, "अफ़ीक़ा", "افيق", "knowledgeable", "Arabic", "Female", "أ ف ق", "not established", "low", "The source record's gloss 'Knowledgeable, Intelligent' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "afiya": ("عافية", "عافیہ", None, "आफ़िया", "عافيه", "health", "Arabic", "Female", "ع ف و", "not established", "high", "Variant romanization of عافية. The source record's form أَفْيَاء is malformed."),
 "afiyah": ("عافية", "عافیہ", None, "आफ़िया", "عافيه", "healthy", "Arabic", "Female", "ع ف و", "not established", "high", "Variant romanization of عافية."),
 "afiza": ("عفيفة", "عفيفہ", None, "अफ़ीज़ा", "عفيفه", "pure_clear", "Arabic", "Female", "ع ف ف", "not established", "low", "The source record gave عفیزة, which is not a standard Arabic lexical form. The intended form may be عفيفة. The identification is uncertain."),
 "afizah": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Afizah' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "afkar": ("أفكار", "افکار", None, "अफ़कार", "افکار", "thoughts", "Arabic", "Unisex", "ف ك ر", "not established", "high", "Afkār, plural of فِكر ('thought')."),
 "aflah": ("أفلح", "افلح", None, "अफ़लह", "افلح", "successful", "Arabic", "Male", "ف ل ح", "root ف ل ح occurs in the Qur'an; أفلح is a normal Arabic verb form", "medium", "Aflaḥ ('more/most successful'), from the root ف ل ح. The source record's gloss 'Successful, Prosperous' is a reasonable rendering."),
 "aflak": ("أفلاك", "افلاک", None, "अफ़लाक", "افلاك", "orbits", "Arabic", "Male", "ف ل ك", "not established", "high", "Aflāk, plural of فَلَك ('celestial sphere, orbit')."),
 "aflatoon": ("أفلاطون", "افلاطون", None, "अफ़लातून", "افلاطون", "loyal_servant", "Arabic", "Unisex", "ف ل ط ن", "not established", "medium", "Aflāṭūn is the Arabic form of the Greek name Plato (Πλάτων). The source record's gloss 'Loyal and devoted servant' is unsupported."),
 "afnan": ("أفنان", "افنان", None, "अफ़नान", "افنان", "branches", "Arabic", "Unisex", "ف ن ن", "أفنان occurs in the Qur'an (Sūrat al-Raḥmān 55:48) as a common noun meaning 'branches'; it is not a Qur'anic proper name", "high", "Afnān, plural of فَنَن ('branch, twig'), occurring in Sūrat al-Raḥmān."),
 "afnin": ("أفنين", "افنین", None, "अफ़नीन", "افنين", "branches_heaven", "Arabic", "Female", "ف ن ن", "not established", "low", "The source record's form أفنين is not a standard Arabic plural. The identification is uncertain."),
 "afra": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record left this name with no origin and no script form. No verified lexical form could be matched and no gloss is asserted."),
 "afraa": ("أفراء", "افراء", None, "अफ़रा", "افراء", "honor_dignity", "Arabic", "Unisex", "ف ر أ", "not established", "low", "The source record's gloss 'Honor, dignity' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "afraah": ("أفراح", "افراح", None, "अफ़राह", "افراح", "joy_festivities", "Arabic", "Female", "ف ر ح", "not established", "high", "Afrāḥ, plural of فَرَح ('joy, celebration')."),
 "afrah": ("أفراح", "افراح", None, "अफ़राह", "افراح", "joy_festivities", "Arabic", "Female", "ف ر ح", "not established", "high", "Variant romanization of أفراح."),
 "afran": ("أفران", "افران", None, "अफ़रान", "افران", "frequent", "Arabic", "Unisex", "ف ر ن", "not established", "low", "The source record's gloss 'Frequent' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "afrasiab": ("أفراسياب", "افراسیاب", "افراسیاب", "अफ़रासियाब", "افراسياب", "lord_iron", "Persian", "Male", None, "not established", "high", "Afrāsiyāb (Avestan Fraŋrasyan) is the mythical king of Turan and the main antagonist of Ferdowsi's Shāhnāmeh. The source record's gloss 'Lord of the Iron Fortress' is a folk rendering of the name's later interpretation."),
 "afraz": ("أفراز", "افراز", None, "अफ़राज़", "افراز", "elevated", "Arabic", "Male", "ف ر ز", "not established", "low", "The source record's gloss 'Elevated, Respected' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "afreen": ("آفرین", "آفرین", "آفرین", "आफ़रीन", "آفرین", "praise", "Persian", "Female", None, "not established", "high", "Persian āfarīn ('praise, bravo, well done'), from āfarīdan ('to create'). The source record's form عفرين is not the standard Persian spelling."),
 "afridi": ("أفريدي", "آفریدی", "افریدی", "अफ़रीदी", "اپريدی", "commander", "Pashto", "Male", None, "not established", "medium", "Afrīdī (Pashto اپريدی) is the name of a Pashtun tribe of the Khyber region. The source record's gloss 'Exalted One' is unsupported; the tribal name's etymology is uncertain."),
 "afrin": ("آفرین", "آفرین", "آفرین", "आफ़रीन", "آفرین", "praise", "Persian", "Female", None, "not established", "high", "Variant romanization of آفرین. The source record's gloss 'Pure, safe' is unsupported."),
 "afrouz": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave فاطمة (Fāṭima), which is a different name. The form afrouz could not be independently verified and no gloss is asserted."),
 "afroz": ("افروز", "افروز", "افروز", "अफ़रोज़", "افروز", "illuminating", "Persian", "Female", None, "not established", "high", "Persian afrōz ('illuminating, kindling'), as in the compound rōshan-afrōz. The source record's gloss 'Moonlit night' is unsupported."),
 "afroza": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عائشة ('Āʾisha), which is a different name. The form afroza could not be independently verified and no gloss is asserted."),
 "afroze": ("افروز", "افروز", "افروز", "अफ़रोज़े", "افروز", "illuminating", "Persian", "Female", None, "not established", "medium", "Variant romanization of افروز. The source record's gloss 'Pure, Precious Gem' is unsupported."),
 "afruz": ("افروز", "افروز", "افروز", "अफ़रूज़", "افروز", "exalted_noble", "Persian", "Unisex", None, "not established", "medium", "Variant romanization of افروز. The source record's gloss 'Exalted or Noble' is unsupported."),
 "afsah": ("أفسح", "افسح", None, "अफ़सह", "افسح", "open_clear", "Arabic", "Female", "ف س ح", "not established", "low", "The source record's gloss 'Open, Clear, Truthful' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "afsan": ("افسان", "افسان", "افسان", "अफ़सान", "افسان", "storyteller", "Persian", "Female", None, "not established", "medium", "Shortened form of Persian افسانه (afsāna, 'story, fable'). The source record's gloss 'Storyteller' is a reasonable rendering."),
 "afsana": ("افسانہ", "افسانہ", "افسانه", "अफ़साना", "افسانه", "story", "Persian", "Female", None, "not established", "high", "Persian/Urdu افسانہ (afsāna, 'story, tale, fable'), from Middle Persian afsānag."),
 "afsanah": ("افسانہ", "افسانہ", "افسانه", "अफ़साना", "افسانه", "tale", "Persian", "Female", None, "not established", "high", "Variant romanization of افسانہ."),
 "afsaneh": ("افسانه", "افسانہ", "افسانه", "अफ़सानेह", "افسانه", "fable", "Persian", "Female", None, "not established", "high", "Persian spelling of افسانہ (afsāna)."),
 "afsar": ("أفسر", "افسر", "افسر", "अफ़सर", "افسر", "officer", "Persian", "Male", None, "not established", "high", "Persian afsar ('crown, diadem; chief, officer'). The source record's gloss 'Commander, leader' is a reasonable extension."),
}
