# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 31 (inara..jabbar).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": inaya -> إنايا (should be عناية); inayah ->
   عناية but glossed as a month name; inshad -> نشد (should be إنشاد); inshaf ->
   نشانف (junk, should be إنصاف); intizar -> إنطزار (should be انتظار); inzamam ->
   إِنزَامَم (broken, should be انضمام); iqmal -> إقمال (should be إكمال);
   irfaan -> إرفان (should be عرفان); irtiza -> إرت۶ (broken, should be ارتضاء);
   isaam -> عيسام (should be عصام); isar -> عيسر (should be إيثار); ismah ->
   إسماع (should be عصمة); israt -> "Ali" (junk); issam -> إسماعيل (a different
   name, should be عصام); itaf -> إتف (should be إتحاف); itidal -> إعتدال
   (should be اعتدال); izaan -> إذان (should be أذان); izaz -> عزاز (should be
   إعزاز); izma -> عزما (should be عظمة); izzati -> إززةي (broken); izzi -> إزى
   (broken); inga -> احمد (junk); isad/isam/isir -> Latin in the Arabic column.
 * DEGARBLED / WRONG glosses: inara 'From the divine' (should be 'illumination');
   inayah "Name of the month of Sha'ban" (should be 'care, providence');
   ins 'Noble, Distinguished' (should be 'humanity, sociability'); intaj 'To Begin,
   To Create' (should be 'production'); inzamam 'Awakener, Encourager' (should be
   'joining, affiliation'); iqmal 'Victory, Triumph' (should be 'completion');
   irum 'Noble, Exalted, Elevated' (should be the place name Iram); isaam 'Given by
   God' (should be 'protector, safeguard'); isar 'Help, aid, support' (should be
   'altruism, preference'); ishaq 'Intense Love' (proper name Isaac); ishaque 'The
   one who worships Allah' (proper name Isaac); ishrat 'Gift, Grace, Favor' (should
   be 'society, joy'); ishtiaq 'gift, bounty, bestowal' (should be 'longing');
   isma 'Given by Allah' (should be the name Asma); ismah "God's perfection"
   (should be 'protection, chastity'); itab 'Gift, Reward' (should be 'reproach');
   itidal 'Fidelity, Loyalty' (should be 'moderation, balance'); iyas 'Healer'
   (should be 'consolation'); izaan 'Dazzling, Splendid' (should be 'call to
   prayer'); izma 'Mother of a lion' (should be 'greatness'); jaafar 'Concealed,
   Hidden' (proper name Ja'far); ishfaq 'The One Who Searches' (should be
   'compassion'); iskandar 'Follower of Alexander' (should be 'Alexander').
 * MISLABELLED ORIGIN: indah (Indonesian), indhira (Tamil), iraj (Persian),
   irem (Turkish), ishrat (Persian/Urdu), izzet (Turkish), israt (Persian/Urdu).
 * GENDER ERRORS: ins, inshad, inshaf, intikhab, inzamam, iqrar, iraj, irfaan,
   irfan, irsad, irshaad, irshad, isaac, isaam, isad, isam, isar, ishaaq, ishaq,
   ishaque, ishfaq, ishtiaq, ishtiyaq, isir, iskandar, ismail, israfil, israil,
   israr, issam, istabraq, itab, iyad, iyan, iyas, iyaz, izaan, izaz, izyan, izz,
   izzan, izzat, izzati, izzet, izzi, jaad, jaah, jabar were labelled female or
   unisex where documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: inas, insaf, intisar, iqbal, isa, ismail, isra,
   izzah (8-key stubs); indhira, inga, inji, insiya, isad, isam, isir, israt,
   itaf, iyan, izyan, izzan, izzani, izzati, izzi.
 * DUPLICATE CLUSTERS: inaya/inayah/inayat; irfaan/irfan/irfana;
   irsad/irshaad/irshad; isaac/ishaaq/ishaq/ishaque;
   ismaael/ismaeel/ismail; isra/israa/issra; issa/isa/iesa;
   ishtiaq/ishtiyaq; izat/izzat/izza/izzah; izz/izzat/izzati;
   jabar/jabbar; intezar/intizar.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated30 import GLOSSES as _G30

GLOSSES = dict(_G30)
GLOSSES.update({
    "illumination": {"en": "Illumination, lighting, enlightenment", "ur": "روشنی، تنویر، نور", "fa": "روشنایی، نورافشانی، تنویر", "hi": "प्रकाश, रोशनी, आलोक", "ps": "روښانه، رڼا، نور", "ar": "الإنارة، الإضاءة، النور"},
    "sociability": {"en": "Sociability, companionship, friendliness", "ur": "انس، ملنساری، صحبت", "fa": "انس، خوشمشربی، همدمی", "hi": "सामाजिकता, मिलनसारी, संगति", "ps": "انس، ملګرتیا، صحبت", "ar": "الإيناس، الأنس، الصحبة"},
    "care_providence": {"en": "Care, providence, solicitude", "ur": "عنانایت، دیکھ بھال، پروا", "fa": "عناایت، مراقبت، پروا", "hi": "देखभाल, कृपा, परवाह", "ps": "پاملرنه، عنایت، پروا", "ar": "العناية، الرعاية، الاهتمام"},
    "humanity": {"en": "Humanity, humankind; sociability", "ur": "انسانیت، انسان، انس", "fa": "انسانیت، آدمی، انس", "hi": "मानवता, मनुष्य, सामाजिकता", "ps": "انسانیت، انسان، انس", "ar": "الإنس، البشر، الأنس"},
    "fairness": {"en": "Fairness, justice, equity", "ur": "انصاف، عدل، داد", "fa": "انصاف، عدالت، داد", "hi": "न्याय, इंसाफ़, समानता", "ps": "انصاف، عدالت، داد", "ar": "الإنصاف، العدل، القسط"},
    "recitation": {"en": "Recitation, chanting, singing of poetry", "ur": "انشاد، گانا، ترنم", "fa": "انشاد، سرود، آواز", "hi": "पाठ, गायन, सस्वर वाचन", "ps": "انشاد، سندر، نغمه", "ar": "الإنشاد، الترتيل، الغناء"},
    "production": {"en": "Production, output, generation", "ur": "پیداوار، اخراج، تخلیق", "fa": "تولید، بازده، آفرینش", "hi": "उत्पादन, निर्माण, सृजन", "ps": "تولید، پیداښت، جوړونه", "ar": "الإنتاج، الإخراج، التوليد"},
    "waiting": {"en": "Waiting, anticipation, expectation", "ur": "انتظار، توقع، راہ دیکھنا", "fa": "انتظار، چشمبراهی، توقع", "hi": "प्रतीक्षा, इंतज़ार, अपेक्षा", "ps": "انتظار، تمه، هيله", "ar": "الانتظار، الترقّب، التوقّع"},
    "selection": {"en": "Selection, choice, preference", "ur": "انتخاب، چناؤ، پسند", "fa": "انتخاب، گزینش، پسند", "hi": "चयन, चुनाव, पसंद", "ps": "انتخاب، ټاکنه، خوښه", "ar": "الانتخاب، الاختيار، التفضيل"},
    "victory": {"en": "Victory, triumph, conquest", "ur": "فتح، نصرت، کامیابی", "fa": "پیروزی، فتح، نصرت", "hi": "विजय, जीत, फ़तह", "ps": "بریا، فتح، نصرت", "ar": "الانتصار، النصر، الفتح"},
    "joining": {"en": "Joining, affiliation, inclusion", "ur": "شمولیت، انضمام، شامل ہونا", "fa": "پیوستن، انضمام، شمولیت", "hi": "सम्मिलन, शामिल होना", "ps": "یوځای کېدنه، شمولیت", "ar": "الانضمام، الضمّ، الشمول"},
    "prosperity": {"en": "Prosperity, good fortune, success", "ur": "اقبال، خوش قسمتی، ترقی", "fa": "اقبال، نیکبختی، پیشرفت", "hi": "समृद्धि, सौभाग्य, उन्नति", "ps": "اقبال، نیکمرغي، پرمختګ", "ar": "الإقبال، الحظ، النجاح"},
    "completion": {"en": "Completion, perfection, making whole", "ur": "تکمیل، اتمام، مکمل کرنا", "fa": "تکمیل، اتمام، کاملکردن", "hi": "पूर्णता, समापन, पूरा करना", "ps": "بشپړتيا، پای، مکملول", "ar": "الإكمال، الإتمام، التكميل"},
    "read_recite": {"en": "Read! Recite! (imperative)", "ur": "پڑھو! تلاوت کرو!", "fa": "بخوان! تلاوت کن!", "hi": "पढ़ो! पाठ करो!", "ps": "لوله! تلاوت وکړه!", "ar": "اقرأ! الأمر بالقراءة والتلاوة"},
    "confirmation": {"en": "Confirmation, affirmation, pledge", "ur": "اقرار، تصدیق، عہد", "fa": "اقرار، تصدیق، پیمان", "hi": "पुष्टि, स्वीकृति, वचन", "ps": "اقرار، تصدیق، تړون", "ar": "الإقرار، التصديق، العهد"},
    "iraj": {"en": "Iraj; a Persian name of legendary kings", "ur": "ایرج، فارسی نام", "fa": "ایرج، نامی در شاهنامه", "hi": "ईरज, फ़ारसी नाम", "ps": "ایرج، فارسي نوم", "ar": "إيرج، اسم فارسي"},
    "iram": {"en": "Iram; a place name mentioned in the Qur'an", "ur": "ارم، قرآن میں مذکور مقام", "fa": "ارم، جاینام مذکور در قرآن", "hi": "इरम, क़ुरआन में उल्लिखित स्थान", "ps": "ارم، په قرآن کې ذکر شوی ځای", "ar": "إِرَم، موضع مذكور في القرآن"},
    "irem": {"en": "Irem; a Turkish female given name", "ur": "ایرم، ترکی زنانہ نام", "fa": "ایرم، نام زنانه ترکی", "hi": "इरेम, तुर्की स्त्री नाम", "ps": "ایرم، ترکي ښځينه نوم", "ar": "إيرم، اسم علم مؤنث تركي"},
    "gnosis": {"en": "Gnosis, deep knowledge, spiritual insight", "ur": "عرفان، معرفت، شناخت", "fa": "عرفان، معرفت، شناخت", "hi": "ज्ञान, इरफ़ान, आध्यात्मिक बोध", "ps": "عرفان، پوهه، پېژندنه", "ar": "العرفان، المعرفة، الإدراك"},
    "guidance_irshad": {"en": "Guidance, direction to the right path", "ur": "ارشاد، ہدایت، رہنمائی", "fa": "ارشاد، هدایت، راهنمایی", "hi": "मार्गदर्शन, इरशाद, हिदायत", "ps": "ارشاد، هدایت، لارښوونه", "ar": "الإرشاد، الهداية، الدلالة"},
    "contentment": {"en": "Contentment, satisfaction, acceptance", "ur": "ارتضا، قناعت، رضامندی", "fa": "ارتضا، قناعت، خشنودی", "hi": "संतोष, तुष्टि, स्वीकृति", "ps": "ارتضا، قناعت، رضامندي", "ar": "الارتضاء، الرضا، القناعة"},
    "isaac": {"en": "Isaac; the Qur'anic form of the name", "ur": "اسحاق، قرآن میں اسحاق", "fa": "اسحاق، صورت قرآنی اسحاق", "hi": "इसहाक़, क़ुरआन में इसहाक़", "ps": "اسحاق، په قرآن کې اسحاق", "ar": "إِسْحَاق، النبي المذكور في القرآن"},
    "protector": {"en": "Protector, safeguard, guardian", "ur": "عصام، محافظ، نگہبان", "fa": "عصام، نگهبان، پاسدار", "hi": "रक्षक, संरक्षक, हिफ़ाज़त", "ps": "ساتونکی، محافظ، نګران", "ar": "العصام، الحافظ، الحامي"},
    "altruism": {"en": "Altruism, preferring others, selflessness", "ur": "ایثار، بے غرضی، دوسروں کو ترجیح", "fa": "ایثار، دیگرخواهی، فداکاری", "hi": "परोपकार, निःस्वार्थता, त्याग", "ps": "ایثار، بې غرضي، قرباني", "ar": "الإيثار، التفضيل، الإحسان"},
    "evening": {"en": "Evening, nightfall; the evening prayer", "ur": "عشاء، شام، رات کا آغاز", "fa": "عشاء، شامگاه، نماز عشا", "hi": "इशा, संध्या, रात्रि", "ps": "عشاء، ماښام، د شپې لمانځه", "ar": "العشاء، المساء، صلاة العشاء"},
    "sign": {"en": "Sign, mark, indication", "ur": "اشارہ، نشان، علامت", "fa": "اشاره، نشان، علامت", "hi": "संकेत, इशारा, चिह्न", "ps": "اشاره، نښه، علامه", "ar": "الإشارة، العلامة، الرمز"},
    "compassion": {"en": "Compassion, tender concern, pity", "ur": "شفقت، ہمدردی، مہربانی", "fa": "شفقت، دلسوزی، مهربانی", "hi": "करुणा, सहानुभूति, दया", "ps": "شفقت، زړه سواندنه، مهرباني", "ar": "الإشفاق، الشفقة، الحنان"},
    "illumination_dawn": {"en": "Illumination, radiance, dawn light", "ur": "اشراق، روشنی، صبح کی کرن", "fa": "اشراق، روشنایی، سپیده", "hi": "प्रकाश, इशराक़, भोर", "ps": "اشراق، روښانه، سهار", "ar": "الإشراق، الإضاءة، ضوء الفجر"},
    "society": {"en": "Society, company, joy (Persian/Urdu)", "ur": "عشرت، صحبت، خوشی", "fa": "عشرت، همنشینی، شادی", "hi": "समाज, संगति, आनंद", "ps": "عشرت، صحبت، خوښي", "ar": "العشرة، الصحبة، المسرّة"},
    "longing": {"en": "Longing, yearning, ardent desire", "ur": "اشتیاق، آرزو، تڑپ", "fa": "اشتیاق، آرزو، سودازدگی", "hi": "उत्सुकता, लालसा, तड़प", "ps": "اشتیاق، هیله، تږي", "ar": "الاشتياق، الشوق، الحنين"},
    "alexander": {"en": "Alexander; the Arabic form of the name", "ur": "اسکندر، سکندر", "fa": "اسکندر، سکندر", "hi": "सिकंदर, इस्कंदर", "ps": "سکندر، اسکندر", "ar": "الإسكندر، سكندر"},
    "reform": {"en": "Reform, correction, setting right", "ur": "اصلاح، درستی، سدھار", "fa": "اصلاح، درستی، بهسازی", "hi": "सुधार, इस्लाह, संशोधन", "ps": "اصلاح، سمون، برابرول", "ar": "الإصلاح، التقويم، التسوية"},
    "submission": {"en": "Submission, surrender, peace", "ur": "اسلام، تسلیم، اطاعت", "fa": "اسلام، تسلیم، گردننهادن", "hi": "इस्लाम, समर्पण, आत्मसमर्पण", "ps": "اسلام، تسلیم، غاړه ایښودنه", "ar": "الإسلام، التسليم، الانقياد"},
    "asma": {"en": "Asma; a female given name", "ur": "اسماء (زنانہ نام)", "fa": "اسماء (نام زنانه)", "hi": "अस्मा (स्त्री नाम)", "ps": "اسماء (ښځينه نوم)", "ar": "أَسْمَاء (اسم علم مؤنث)"},
    "ishmael": {"en": "Ishmael; the Qur'anic form of the name", "ur": "اسماعیل، قرآن میں اسماعیل", "fa": "اسماعیل، صورت قرآنی اسماعیل", "hi": "इस्माईल, क़ुरआन में इस्माईल", "ps": "اسماعیل، په قرآن کې اسماعیل", "ar": "إِسْمَاعِيل، النبي المذكور في القرآن"},
    "protection_ismah": {"en": "Protection, safeguard, chastity", "ur": "عصمت، حفاظت، پاکدامنی", "fa": "عصمت، نگهداری، پاکدامنی", "hi": "संरक्षण, अस्मत, पवित्रता", "ps": "عصمت، ساتنه، پاکدامني", "ar": "العصمة، الحفظ، الامتناع"},
    "night_journey": {"en": "Night journey; the Prophet's night journey", "ur": "اسراء، شبِ معراج", "fa": "اسراء، سفر شبانه", "hi": "इसरा, रात्रि यात्रा", "ps": "اسراء، د شپې سفر", "ar": "الإسراء، السرى ليلاً"},
    "israfil": {"en": "Israfil; the angel who will blow the trumpet", "ur": "اسرافیل، صور پھونکنے والا فرشتہ", "fa": "اسرافیل، فرشته صور", "hi": "इसराफ़ील, तुरही फूँकने वाला फ़रिश्ता", "ps": "اسرافیل، د شپېلۍ وهونکی پرښته", "ar": "إِسْرَافِيل، الملك الموكل بالصور"},
    "israel": {"en": "Israel; the Qur'anic name of Jacob", "ur": "اسرائیل، قرآن میں یعقوب کا نام", "fa": "اسرائیل، نام قرآنی یعقوب", "hi": "इसराईल, क़ुरआन में याक़ूब का नाम", "ps": "اسرائیل، په قرآن کې د یعقوب نوم", "ar": "إِسْرَائِيل، اسم يعقوب في القرآن"},
    "persistence": {"en": "Persistence, insistence, determination", "ur": "اصرار، ہٹ، ثابت قدمی", "fa": "اصرار، پافشاری، استواری", "hi": "हठ, दृढ़ता, ज़िद", "ps": "اصرار، ټینګار، ثابت قدمي", "ar": "الإصرار، المثابرة، العزم"},
    "brocade": {"en": "Brocade; a fine woven fabric (Qur'anic)", "ur": "استبرق، دیبا، ریشمی کپڑا", "fa": "استبرق، دیبا، پارچه ابریشمی", "hi": "इस्तब्रक़, रेशमी वस्त्र", "ps": "استبرق، ورېښمین ټوکر", "ar": "الاستبرق، الديباج، الثوب الفاخر"},
    "reproach": {"en": "Reproach, gentle blame, censure", "ur": "عتاب، ملامت، ڈانٹ", "fa": "عتاب، سرزنش، ملامت", "hi": "उलाहना, डाँट, ताड़ना", "ps": "عتاب، ملامت، ګرمتيا", "ar": "العتاب، اللوم، المؤاخذة"},
    "gift_giving": {"en": "Gift-giving, presenting, bestowing", "ur": "اتحاف، تحفہ دینا، عطا", "fa": "اتحاف، هدیه دادن، بخشش", "hi": "उपहार देना, भेंट", "ps": "اتحاف، ډالۍ ورکول", "ar": "الإتحاف، الإهداء، العطاء"},
    "moderation": {"en": "Moderation, balance, evenness", "ur": "اعتدال، توازن، میانہ روی", "fa": "اعتدال، توازن، میانهروی", "hi": "संतुलन, मध्यमार्ग, इतिदाल", "ps": "اعتدال، توازن، منځلاری", "ar": "الاعتدال، التوازن، الاستواء"},
    "support_iyad": {"en": "Support, backing, reinforcement", "ur": "ایاد، سہارا، مدد", "fa": "ایاد، پشتیبانی، کمک", "hi": "सहारा, समर्थन, मदद", "ps": "ایاد، ملاتړ، مرسته", "ar": "الإياد، السند، الدعم"},
    "consolation": {"en": "Consolation, solace, comfort", "ur": "ایاس، تسلی، دلاسا", "fa": "ایاس، تسلی، دلجویی", "hi": "सांत्वना, तसल्ली, ढाढ़स", "ps": "ایاس، تسلي، زړه ښه کول", "ar": "الإياس، التسلية، العزاء"},
    "call_to_prayer": {"en": "Call to prayer, announcement", "ur": "اذان، پکار، اعلان", "fa": "اذان، بانگ، آواز", "hi": "अज़ान, पुकार, घोषणा", "ps": "اذان، بانګ، غږ", "ar": "الأذان، النداء، الإعلام"},
    "honoring_izaz": {"en": "Honoring, strengthening, showing respect", "ur": "اعزاز، عزت دینا، تقویت", "fa": "اعزاز، عزت دادن، تقویت", "hi": "सम्मान, इज़्ज़त देना, सशक्तीकरण", "ps": "اعزاز، عزت ورکول، پیاوړتیا", "ar": "الإعزاز، التكريم، التقوية"},
    "flourishing": {"en": "Flourishing, prosperity, thriving", "ur": "ازدہار، پھلنا پھولنا، ترقی", "fa": "ازدهار، شکوفایی، رونق", "hi": "फलना-फूलना, समृद्धि, उन्नति", "ps": "ازدهار، پرمختګ، شادابي", "ar": "الازدهار، الرفاهية، النماء"},
    "expression": {"en": "Expression, declaration, manifestation", "ur": "اظہار، بیان، ظاہر کرنا", "fa": "اظهار، بیان، آشکارسازی", "hi": "अभिव्यक्ति, इज़हार, प्रकटीकरण", "ps": "اظهار، بیان، ښکاره کول", "ar": "الإظهار، الإعلان، البيان"},
    "greatness": {"en": "Greatness, grandeur, majesty", "ur": "عظمت، بزرگی، جلال", "fa": "عظمت، بزرگی، جلال", "hi": "महानता, विशालता, गरिमा", "ps": "عظمت، لویي، جلال", "ar": "العظمة، الجلال، الكبرياء"},
    "glory": {"en": "Glory, might, honor", "ur": "عز، جلال، عزت", "fa": "عز، جلال، شکوه", "hi": "महिमा, गौरव, इज़्ज़त", "ps": "عز، جلال، ویاړ", "ar": "العزّ، الجلال، العظمة"},
    "izzet": {"en": "Izzet; a Turkish male given name", "ur": "عزت، ترکی نام", "fa": "عزت، نام ترکی", "hi": "इज़्ज़त, तुर्की नाम", "ps": "عزت، ترکي نوم", "ar": "عزّت، اسم تركي"},
    "generous_jaad": {"en": "Generous, bountiful, excellent", "ur": "جاد، سخی، بہترین", "fa": "جاد، بخشنده، نیکو", "hi": "उदार, दानवीर, उत्तम", "ps": "جاد، سخي، غوره", "ar": "الجاد، الكريم، الجواد"},
    "jafar": {"en": "Ja'far; a male given name", "ur": "جعفر (مردانہ نام)", "fa": "جعفر (نام مردانه)", "hi": "जाफ़र (पुरुष नाम)", "ps": "جعفر (نر نوم)", "ar": "جَعْفَر (اسم علم مذكر)"},
    "rank": {"en": "Rank, dignity, standing", "ur": "جاہ، مرتبہ، وقار", "fa": "جاه، مرتبه، وقار", "hi": "पद, प्रतिष्ठा, मर्यादा", "ps": "جاه، مرتبه، وقار", "ar": "الجاه، المنزلة، القدر"},
    "mountain": {"en": "Mountain, mount", "ur": "پہاڑ، جبل", "fa": "کوه، جبل", "hi": "पहाड़, जबल", "ps": "غر، جبل", "ar": "الجبل، الطود"},
    "compeller": {"en": "Compeller, almighty, restorer", "ur": "جبار، قہر کرنے والا، زبردست", "fa": "جبار، قهار، توانا", "hi": "जब्बार, सर्वशक्तिमान, प्रबल", "ps": "جبار، قهار، زورور", "ar": "الجبّار، القهار، العظيم"},
    "beautiful_indah": {"en": "Beautiful (Indonesian/Malay)", "ur": "خوبصورت (انڈونیشیائی)", "fa": "زیبا (اندونزیایی)", "hi": "सुंदर (इंडोनेशियाई)", "ps": "ښکلی (اندونیزیایي)", "ar": "جميل (إندونيسي)"},
    "indhira": {"en": "Indhira; a Tamil female given name", "ur": "اندهیرا (تمل زنانہ نام)", "fa": "ایندیرا (نام زنانه تامیلی)", "hi": "इंदिरा (तमिल स्त्री नाम)", "ps": "اندهیرا (تاميلي ښځينه نوم)", "ar": "إنديرا (اسم علم مؤنث تاميلي)"},
    "inga": {"en": "Inga; a Germanic female given name", "ur": "انگا (جرمن زنانہ نام)", "fa": "اینگا (نام زنانه ژرمنی)", "hi": "इंगा (जर्मनिक स्त्री नाम)", "ps": "انګا (جرمني ښځينه نوم)", "ar": "إنغا (اسم علم مؤنث جرماني)"},
    "inji": {"en": "Inji; an Egyptian female given name", "ur": "انجی (مصری زنانہ نام)", "fa": "اینجی (نام زنانه مصری)", "hi": "इंजी (मिस्री स्त्री नाम)", "ps": "انجي (مصري ښځينه نوم)", "ar": "إنجي (اسم علم مؤنث مصري)"},
    "isir": {"en": "Isir; a male given name", "ur": "اسیر (مردانہ نام)", "fa": "ایسیر (نام مردانه)", "hi": "इसिर (पुरुष नाम)", "ps": "ایسیر (نر نوم)", "ar": "إسير (اسم علم مذكر)"},
    "iyan": {"en": "Iyan; a male given name", "ur": "ایان (مردانہ نام)", "fa": "ایان (نام مردانه)", "hi": "इयान (पुरुष नाम)", "ps": "ایان (نر نوم)", "ar": "إيان (اسم علم مذكر)"},
    "izyan": {"en": "Izyan; a male given name", "ur": "ایزیان (مردانہ نام)", "fa": "ایزیان (نام مردانه)", "hi": "इज़यान (पुरुष नाम)", "ps": "ایزیان (نر نوم)", "ar": "إيزيان (اسم علم مذكر)"},
    "izzan": {"en": "Izzan; a male given name", "ur": "عزان (مردانہ نام)", "fa": "عزان (نام مردانه)", "hi": "इज़्ज़ान (पुरुष नाम)", "ps": "عزان (نر نوم)", "ar": "عَزَّان (اسم علم مذكر)"},
    "izzani": {"en": "Izzani; a given name", "ur": "عزانی (نام)", "fa": "عزانی (نام)", "hi": "इज़्ज़ानी (नाम)", "ps": "عزاني (نوم)", "ar": "عَزَّانِي (اسم علم)"},
})

CUR = {
 "inara": ("إنارة", "انارہ", "اناره", "इनारा", "اناره", "illumination", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); إِنَارَة (Ināra)", False, "medium",
           "Inara is Arabic إِنَارَة (Ināra) 'illumination, lighting, enlightenment', from the root ن و ر (n-w-r). The source gloss 'From the divine' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "inas": ("إيناس", "ای纳斯", "ای纳斯", "इनास", "ای纳斯", "sociability", "Arabic", "Female",
          "Arabic root أ ن س (ʾ-n-s); إِينَاس (Īnās)", False, "high",
          "Inas is Arabic إِينَاس (Īnās) 'sociability, companionship, friendliness', from the root أ ن س (ʾ-n-s). The source record was an 8-key stub with no data."),
 "inaya": ("عناية", "عنایہ", "عنایه", "इनाया", "عنایه", "care_providence", "Arabic", "Female",
           "Arabic root ع ن ي (ʿ-n-y); عِنَايَة (ʿInāya)", False, "high",
           "Inaya is Arabic عِنَايَة (ʿInāya) 'care, providence, solicitude', from the root ع ن ي (ʿ-n-y). CRITICAL SOURCE ERROR: the source gave إنايا (a different form) and glossed the name 'Compassionate and caring'; the correct form is عِنَايَة. Same name as inayah and inayat."),
 "inayah": ("عناية", "عنایہ", "عنایه", "इनाया", "عنایه", "care_providence", "Arabic", "Female",
            "Arabic root ع ن ي (ʿ-n-y); عِنَايَة (ʿInāya)", False, "high",
            "Inayah is Arabic عِنَايَة (ʿInāya) 'care, providence, solicitude', from the root ع ن ي (ʿ-n-y). CRITICAL SOURCE ERROR: the source glossed the name as \"Name of the month of Sha'ban\", which is unsupported; the lexical sense is 'care, providence'. Same name as inaya and inayat."),
 "inayat": ("عنايت", "عنايت", "عنايت", "इनायत", "عنايت", "care_providence", "Arabic", "Male",
            "Arabic root ع ن ي (ʿ-n-y); عِنَايَة (ʿInāya)", False, "medium",
            "Inayat is Arabic عِنَايَة (ʿInāya) 'care, providence, solicitude', from the root ع ن ي (ʿ-n-y); the form عِنَايَت is the Persian/Urdu rendering. The source gloss 'Favour, Pleasure' is broadly consistent. The source labelled the name unisex; documented usage is predominantly male in South Asia. Same name as inaya and inayah."),
 "indah": ("إنداه", "انداہ", "انداہ", "इंदा", "انداہ", "beautiful_indah", "Indonesian", "Female",
           "Indonesian indah", False, "low",
           "Indah is recorded at low confidence. The source gave إنداه and glossed the name 'Beautiful'; indah is an Indonesian/Malay word meaning 'beautiful', but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "indhira": ("إنديرا", "اندهیرا", "اندهیرا", "इंदिरा", "اندهیرا", "indhira", "Tamil", "Female",
             "Tamil இந்திரா (Intirā)", False, "low",
             "Indhira is recorded at low confidence. The source gave the broken form أنديةرا and glossed the name 'A star'; Indhira is a Tamil/South Indian female given name, but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "inga": ("إنغا", "انگا", "انگا", "इंगा", "انگا", "inga", "Germanic", "Female",
          "Germanic Inga", False, "low",
          "Inga is recorded at low confidence. The source gave the junk string احمد in the Arabic column and no meaning; Inga is a Germanic/Scandinavian female given name, but no lexical meaning could be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "inji": ("إنجي", "انجی", "انجی", "इंजी", "انجی", "inji", "Arabic", "Female",
          "Arabic إِنْجِي (Injī)", False, "low",
          "Inji is recorded at low confidence. The source gave إنجي and glossed the name 'Gift, Blessing'; إِنْجِي (Injī) is a documented Egyptian female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "ins": ("إنس", "انس", "انس", "इंस", "انس", "humanity", "Arabic", "Male",
         "Arabic root أ ن س (ʾ-n-s); إِنْس (Ins)", False, "medium",
         "Ins is Arabic إِنْس (Ins) 'humanity, humankind; sociability', from the root أ ن س (ʾ-n-s). The source gloss 'Noble, Distinguished' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "insaf": ("إنصاف", "انصاف", "انصاف", "इंसाफ़", "انصاف", "fairness", "Arabic", "Female",
           "Arabic root ن ص ف (n-ṣ-f); إِنْصَاف (Inṣāf)", False, "high",
           "Insaf is Arabic إِنْصَاف (Inṣāf) 'fairness, justice, equity', from the root ن ص ف (n-ṣ-f). The source record was an 8-key stub with no data."),
 "inshad": ("إنشاد", "انشاد", "انشاد", "इंशाद", "انشاد", "recitation", "Arabic", "Male",
            "Arabic root ن ش د (n-sh-d); إِنْشَاد (Inshād)", False, "medium",
            "Inshad is Arabic إِنْشَاد (Inshād) 'recitation, chanting, singing of poetry', from the root ن ش د (n-sh-d). CRITICAL SOURCE ERROR: the source gave نشد (a different form) and glossed the name 'Singing to Allah'; the correct form is إِنْشَاد."),
 "inshaf": ("إنصاف", "انصاف", "انصاف", "इंशाफ़", "انصاف", "fairness", "Arabic", "Male",
            "Arabic root ن ص ف (n-ṣ-f); إِنْصَاف (Inṣāf)", False, "low",
            "Inshaf is recorded at low confidence. The source gave the junk form نشانف and glossed the name 'Healing, Cure, Remedy'; the intended form is likely إِنْصَاف (Inṣāf), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as insaf."),
 "insiya": ("إنسية", "انسیہ", "انسیه", "इंसिया", "انسیه", "sociability", "Arabic", "Female",
            "Arabic root أ ن س (ʾ-n-s); إِنْسِيَّة (Insiyya)", False, "low",
            "Insiya is recorded at low confidence. The source gave إنسي and glossed the name 'Gentleness, Delicacy'; إِنْسِيَّة (Insiyya) is related to the root أ ن س (ʾ-n-s), but the source's form and gloss could not be confirmed. No confident meaning is asserted."),
 "intaj": ("إنتاج", "انتاج", "انتاج", "इंताज", "انتاج", "production", "Arabic", "Female",
           "Arabic root ن ت ج (n-t-j); إِنْتَاج (Intāj)", False, "medium",
           "Intaj is Arabic إِنْتَاج (Intāj) 'production, output, generation', from the root ن ت ج (n-t-j). The source gloss 'To Begin, To Create' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "intezar": ("انتظار", "انتظار", "انتظار", "इंतज़ार", "انتظار", "waiting", "Arabic", "Male",
             "Arabic root ن ظ ر (n-ẓ-r); اِنْتِظَار (Intiẓār)", False, "high",
             "Intezar is Arabic اِنْتِظَار (Intiẓār) 'waiting, anticipation, expectation', from the root ن ظ ر (n-ẓ-r). The source gloss 'Waiting, Anticipation' is consistent. Same name as intizar."),
 "intikhab": ("انتخاب", "انتخاب", "انتخاب", "इंतिख़ाब", "انتخاب", "selection", "Arabic", "Male",
              "Arabic root ن خ ب (n-kh-b); اِنْتِخَاب (Intikhāb)", False, "medium",
              "Intikhab is Arabic اِنْتِخَاب (Intikhāb) 'selection, choice, preference', from the root ن خ ب (n-kh-b). The source gloss 'Choosing, selection, preference' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "intisar": ("انتصار", "انتشار", "انتشار", "इंतिसार", "انتشار", "victory", "Arabic", "Female",
             "Arabic root ن ص ر (n-ṣ-r); اِنْتِصَار (Intiṣār)", False, "high",
             "Intisar is Arabic اِنْتِصَار (Intiṣār) 'victory, triumph, conquest', from the root ن ص ر (n-ṣ-r). The source record was an 8-key stub with no data."),
 "intizar": ("انتظار", "انتظار", "انتظار", "इंतिज़ार", "انتظار", "waiting", "Arabic", "Male",
             "Arabic root ن ظ ر (n-ẓ-r); اِنْتِظَار (Intiẓār)", False, "medium",
             "Intizar is Arabic اِنْتِظَار (Intiẓār) 'waiting, anticipation, expectation', from the root ن ظ ر (n-ẓ-r). CRITICAL SOURCE ERROR: the source gave إنطزار (a different form) and glossed the name 'To Expect, To Wait'; the correct form is اِنْتِظَار. Same name as intezar."),
 "inzamam": ("انضمام", "انضمام", "انضمام", "इंज़िमाम", "انضمام", "joining", "Arabic", "Male",
             "Arabic root ض م م (ḍ-m-m); اِنْضِمَام (Inḍimām)", False, "medium",
             "Inzamam is Arabic اِنْضِمَام (Inḍimām) 'joining, affiliation, inclusion', from the root ض م م (ḍ-m-m). CRITICAL SOURCE ERROR: the source gave the broken form إِنزَامَم and glossed the name 'Awakener, Encourager'; the correct form is اِنْضِمَام."),
 "iqbal": ("إقبال", "اقبال", "اقبال", "इक़बाल", "اقبال", "prosperity", "Arabic", "Male",
           "Arabic root ق ب ل (q-b-l); إِقْبَال (Iqbāl)", False, "high",
           "Iqbal is Arabic إِقْبَال (Iqbāl) 'prosperity, good fortune, success', from the root ق ب ل (q-b-l). The source record was an 8-key stub with no data."),
 "iqmal": ("إكمال", "اکمال", "اکمال", "इकमाल", "اکمال", "completion", "Arabic", "Male",
           "Arabic root ك م ل (k-m-l); إِكْمَال (Ikmāl)", False, "medium",
           "Iqmal is Arabic إِكْمَال (Ikmāl) 'completion, perfection, making whole', from the root ك م ل (k-m-l). CRITICAL SOURCE ERROR: the source gave إقمال (a different form) and glossed the name 'Victory, Triumph'; the correct form is إِكْمَال."),
 "iqra": ("اقرأ", "اقرأ", "اقرأ", "इक़रा", "اقرأ", "read_recite", "Arabic", "Female",
          "Qur'anic imperative; اِقْرَأْ (Iqraʾ)", True, "high",
          "Iqra is Arabic اِقْرَأْ (Iqraʾ) 'Read! Recite!', the imperative that opens the first Qur'anic revelation (Sūrat al-ʿAlaq). The source gloss 'Read, Recite, Learn' is broadly consistent."),
 "iqrar": ("إقرار", "اقرار", "اقرار", "इक़रार", "اقرار", "confirmation", "Arabic", "Male",
           "Arabic root ق ر ر (q-r-r); إِقْرَار (Iqrār)", False, "medium",
           "Iqrar is Arabic إِقْرَار (Iqrār) 'confirmation, affirmation, pledge', from the root ق ر ر (q-r-r). The source gloss 'Promise, Commitment' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "iraj": ("ایرج", "ایرج", "ایرج", "ईरज", "ایرج", "iraj", "Persian", "Male",
         "Persian ایرج (Īraj)", False, "medium",
         "Iraj is Persian ایرج (Īraj), a male given name borne by a legendary king in the Shahnameh. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Mountain, War' is unsupported and has been replaced with the documented identification."),
 "iram": ("إرام", "ارم", "ارم", "इरम", "ارم", "iram", "Arabic", "Female",
         "Qur'anic place name; إِرَم (Iram)", True, "medium",
         "Iram is Arabic إِرَم (Iram), a place name mentioned in the Qur'an (Iram of the pillars, Sūrat al-Fajr). The source gloss 'Architect or City' is unsupported and has been replaced with the documented identification. Recorded at medium confidence because the item is a place name rather than a descriptive lexical item."),
 "irem": ("إيرم", "ایرم", "ایرم", "इरेम", "ایرم", "irem", "Turkish", "Female",
         "Turkish İrem", False, "medium",
         "Irem is Turkish İrem, a documented female given name. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Moon' is unsupported and has been replaced with the documented identification."),
 "irfaan": ("عرفان", "عرفان", "عرفان", "इरफ़ान", "عرفان", "gnosis", "Arabic", "Male",
            "Arabic root ع ر ف (ʿ-r-f); عِرْفَان (ʿIrfān)", False, "high",
            "Irfaan is Arabic عِرْفَان (ʿIrfān) 'gnosis, deep knowledge, spiritual insight', from the root ع ر ف (ʿ-r-f). CRITICAL SOURCE ERROR: the source gave إرفان (a different form) and glossed the name 'Gentle, Compassionate, Free'; the correct form is عِرْفَان. Same name as irfan and irfana."),
 "irfan": ("عرفان", "عرفان", "عرفان", "इरफ़ान", "عرفان", "gnosis", "Arabic", "Male",
           "Arabic root ع ر ف (ʿ-r-f); عِرْفَان (ʿIrfān)", False, "high",
           "Irfan is Arabic عِرْفَان (ʿIrfān) 'gnosis, deep knowledge, spiritual insight', from the root ع ر ف (ʿ-r-f). The source gloss 'Perfection of the Faith' is unsupported and has been replaced with the lexical sense. Same name as irfaan and irfana."),
 "irfana": ("عرفانة", "عرفانہ", "عرفانه", "इरफ़ाना", "عرفانه", "gnosis", "Arabic", "Female",
            "Arabic root ع ر ف (ʿ-r-f); عِرْفَانَة (ʿIrfāna)", False, "low",
            "Irfana is recorded at low confidence. The source gave إرفانا and glossed the name 'Faithful, sincere'; عِرْفَانَة (ʿIrfāna) is the feminine of عِرْفَان (ʿIrfān), but the source's form and gloss could not be confirmed. No confident meaning is asserted. Same name as irfaan and irfan."),
 "irsad": ("إرشاد", "ارشاد", "ارشاد", "इरशाद", "ارشاد", "guidance_irshad", "Arabic", "Male",
           "Arabic root ر ش د (r-sh-d); إِرْشَاد (Irshād)", False, "high",
           "Irsad is Arabic إِرْشَاد (Irshād) 'guidance, direction to the right path', from the root ر ش د (r-sh-d). The source gloss 'Guidance' is consistent. Same name as irshaad and irshad."),
 "irshaad": ("إرشاد", "ارشاد", "ارشاد", "इरशाद", "ارشاد", "guidance_irshad", "Arabic", "Male",
             "Arabic root ر ش د (r-sh-d); إِرْشَاد (Irshād)", False, "high",
             "Irshaad is Arabic إِرْشَاد (Irshād) 'guidance, direction to the right path', from the root ر ش د (r-sh-d). The source gloss 'Guide, Leader' is broadly consistent. Same name as irsad and irshad."),
 "irshad": ("إرشاد", "ارشاد", "ارشاد", "इरशाद", "ارشاد", "guidance_irshad", "Arabic", "Male",
            "Arabic root ر ش د (r-sh-d); إِرْشَاد (Irshād)", False, "high",
            "Irshad is Arabic إِرْشَاد (Irshād) 'guidance, direction to the right path', from the root ر ش د (r-sh-d). The source gloss 'Guidance' is consistent. Same name as irsad and irshaad."),
 "irtiza": ("ارتضاء", "ارتضا", "ارتضا", "इर्तिज़ा", "ارتضا", "contentment", "Arabic", "Male",
            "Arabic root ر ض و (r-ḍ-w); اِرْتِضَاء (Irtiḍāʾ)", False, "medium",
            "Irtiza is Arabic اِرْتِضَاء (Irtiḍāʾ) 'contentment, satisfaction, acceptance', from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source gave the broken form إرت۶ and glossed the name 'Desire, Wish'; the correct form is اِرْتِضَاء."),
 "irum": ("إرم", "ارم", "ارم", "इरुम", "ارم", "iram", "Arabic", "Female",
          "Qur'anic place name; إِرَم (Iram)", True, "medium",
          "Irum is Arabic إِرَم (Iram), a place name mentioned in the Qur'an (Iram of the pillars). The source gloss 'Noble, Exalted, Elevated' is unsupported and has been replaced with the documented identification. Same name as iram."),
 "isa": ("عيسى", "عیسیٰ", "عیسی", "ईसा", "عیسی", "jesus", "Arabic", "Male",
         "Qur'anic proper name; عِيسَى (ʿĪsā)", True, "high",
         "Isa is Arabic عِيسَى (ʿĪsā), the Qur'anic form of Jesus, a prophet mentioned in the Qur'an. The source record was an 8-key stub with no data. Same name as issa and iesa."),
 "isaac": ("إسحاق", "اسحاق", "اسحاق", "इसहाक़", "اسحاق", "isaac", "Arabic", "Male",
           "Qur'anic proper name; إِسْحَاق (Isḥāq)", True, "high",
           "Isaac is Arabic إِسْحَاق (Isḥāq), the Qur'anic form of Isaac, a prophet mentioned in the Qur'an. The source gloss 'He Will Laugh, Joyous' is unsupported; the name is a proper name. Same name as ishaaq, ishaq and ishaque."),
 "isaam": ("عصام", "عصام", "عصام", "इसाम", "عصام", "protector", "Arabic", "Male",
           "Arabic root ع ص م (ʿ-ṣ-m); عِصَام (ʿIṣām)", False, "medium",
           "Isaam is Arabic عِصَام (ʿIṣām) 'protector, safeguard, guardian', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave عيسام (a different form) and glossed the name 'Given by God'; the correct form is عِصَام. Same name as isam and issam."),
 "isad": ("إسعاد", "اسعاد", "اسعاد", "इसाद", "اسعاد", "happiness", "Arabic", "Male",
          "Arabic root س ع د (s-ʿ-d); إِسْعَاد (Isʿād)", False, "low",
          "Isad is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Little one, young one'; the intended form is likely إِسْعَاد (Isʿād) 'making happy', but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "isam": ("عصام", "عصام", "عصام", "इसाम", "عصام", "protector", "Arabic", "Male",
          "Arabic root ع ص م (ʿ-ṣ-m); عِصَام (ʿIṣām)", False, "medium",
          "Isam is Arabic عِصَام (ʿIṣām) 'protector, safeguard, guardian', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source repeated the Latin string in the Arabic column and glossed the name 'Given by God'; the correct form is عِصَام. Same name as isaam and issam."),
 "isar": ("إيثار", "ایثار", "ایثار", "इसार", "ایثار", "altruism", "Arabic", "Male",
          "Arabic root أ ث ر (ʾ-th-r); إِيثَار (Īthār)", False, "medium",
          "Isar is Arabic إِيثَار (Īthār) 'altruism, preferring others, selflessness', from the root أ ث ر (ʾ-th-r). CRITICAL SOURCE ERROR: the source gave عيسر (a different form) and glossed the name 'Help, aid, support'; the correct form is إِيثَار."),
 "isha": ("عشاء", "عشاء", "عشاء", "इशा", "عشاء", "evening", "Arabic", "Female",
          "Arabic root ع ش و (ʿ-sh-w); عِشَاء (ʿIshāʾ)", False, "high",
          "Isha is Arabic عِشَاء (ʿIshāʾ) 'evening, nightfall; the evening prayer', from the root ع ش و (ʿ-sh-w). The source gloss 'Night, moon' is broadly consistent."),
 "ishaaq": ("إسحاق", "اسحاق", "اسحاق", "इसहाक़", "اسحاق", "isaac", "Arabic", "Male",
            "Qur'anic proper name; إِسْحَاق (Isḥāq)", True, "high",
            "Ishaaq is Arabic إِسْحَاق (Isḥāq), the Qur'anic form of Isaac, a prophet mentioned in the Qur'an. The source gloss \"God's promise\" is unsupported; the name is a proper name. Same name as isaac, ishaq and ishaque."),
 "ishaq": ("إسحاق", "اسحاق", "اسحاق", "इसहाक़", "اسحاق", "isaac", "Arabic", "Male",
           "Qur'anic proper name; إِسْحَاق (Isḥāq)", True, "high",
           "Ishaq is Arabic إِسْحَاق (Isḥāq), the Qur'anic form of Isaac, a prophet mentioned in the Qur'an. The source gloss 'Intense Love' is unsupported; the name is a proper name. Same name as isaac, ishaaq and ishaque."),
 "ishaque": ("إسحاق", "اسحاق", "اسحاق", "इसहाक़", "اسحاق", "isaac", "Arabic", "Male",
             "Qur'anic proper name; إِسْحَاق (Isḥāq)", True, "high",
             "Ishaque is a South Asian transliteration of Arabic إِسْحَاق (Isḥāq), the Qur'anic form of Isaac. The source gloss 'The one who worships Allah' is unsupported; the name is a proper name. Same name as isaac, ishaaq and ishaq."),
 "ishara": ("إشارة", "اشارہ", "اشاره", "इशारा", "اشاره", "sign", "Arabic", "Female",
            "Arabic root ش و ر (sh-w-r); إِشَارَة (Ishāra)", False, "medium",
            "Ishara is Arabic إِشَارَة (Ishāra) 'sign, mark, indication', from the root ش و ر (sh-w-r). The source gloss 'Sign or Symbol' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "ishfaq": ("إشفاق", "اشفاق", "اشفاق", "इशफ़ाक़", "اشفاق", "compassion", "Arabic", "Male",
            "Arabic root ش ف ق (sh-f-q); إِشْفَاق (Ishfāq)", False, "medium",
            "Ishfaq is Arabic إِشْفَاق (Ishfāq) 'compassion, tender concern, pity', from the root ش ف ق (sh-f-q). The source gloss 'The One Who Searches, Seeks, or Long' is unsupported and has been replaced with the lexical sense."),
 "ishraq": ("إشراق", "اشراق", "اشراق", "इशराक़", "اشراق", "illumination_dawn", "Arabic", "Female",
            "Arabic root ش ر ق (sh-r-q); إِشْرَاق (Ishrāq)", False, "high",
            "Ishraq is Arabic إِشْرَاق (Ishrāq) 'illumination, radiance, dawn light', from the root ش ر ق (sh-r-q). The source gloss 'Dawn, Morning Light' is broadly consistent."),
 "ishrat": ("عشرت", "عشرت", "عشرت", "इशरत", "عشرت", "society", "Persian", "Female",
            "Persian/Urdu عشرت (ishrat), from Arabic عِشْرَة", False, "medium",
            "Ishrat is Persian/Urdu عشرت (ishrat) 'society, company, joy', from Arabic عِشْرَة. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Gift, Grace, Favor' is unsupported and has been replaced with the lexical sense. Same name as israt."),
 "ishtiaq": ("اشتياق", "اشتیاق", "اشتیاق", "इश्तियाक़", "اشتیاق", "longing", "Arabic", "Male",
             "Arabic root ش و ق (sh-w-q); اِشْتِيَاق (Ishtiyāq)", False, "high",
             "Ishtiaq is Arabic اِشْتِيَاق (Ishtiyāq) 'longing, yearning, ardent desire', from the root ش و ق (sh-w-q). The source gloss 'gift, bounty, bestowal' is unsupported and has been replaced with the lexical sense. Same name as ishtiyaq."),
 "ishtiyaq": ("اشتياق", "اشتیاق", "اشتیاق", "इश्तियाक़", "اشتیاق", "longing", "Arabic", "Male",
              "Arabic root ش و ق (sh-w-q); اِشْتِيَاق (Ishtiyāq)", False, "medium",
              "Ishtiyaq is Arabic اِشْتِيَاق (Ishtiyāq) 'longing, yearning, ardent desire', from the root ش و ق (sh-w-q). CRITICAL SOURCE ERROR: the source gave إشتر ياق (a broken form); the correct form is اِشْتِيَاق. The source gloss 'Desire, Wish, Need' is broadly consistent. Same name as ishtiaq."),
 "isir": ("إسير", "اسیر", "اسیر", "इसिर", "اسیر", "isir", "Arabic", "Male",
          "Arabic إِسِير (Isīr)", False, "low",
          "Isir is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name \"Lion's Roar\"; the form إِسِير (Isīr) is not a well-attested Arabic personal name and the gloss is unsupported. No confident meaning is asserted."),
 "iskandar": ("إسكندر", "اسکندر", "اسکندر", "इस्कंदर", "اسکندر", "alexander", "Arabic", "Male",
              "Arabic الإسكندر (al-Iskandar)", False, "high",
              "Iskandar is Arabic الإِسْكَنْدَر (al-Iskandar) 'Alexander', a documented male given name. The source gloss 'Follower of Alexander' is unsupported and has been replaced with the lexical sense."),
 "islah": ("إصلاح", "اصلاح", "اصلاح", "इसलाह", "اصلاح", "reform", "Arabic", "Female",
           "Arabic root ص ل ح (ṣ-l-ḥ); إِصْلَاح (Iṣlāḥ)", False, "high",
           "Islah is Arabic إِصْلَاح (Iṣlāḥ) 'reform, correction, setting right', from the root ص ل ح (ṣ-l-ḥ). The source gloss 'To make right or correct' is consistent."),
 "islam": ("إسلام", "اسلام", "اسلام", "इस्लाम", "اسلام", "submission", "Arabic", "Male",
           "Arabic root س ل م (s-l-m); إِسْلَام (Islām)", False, "high",
           "Islam is Arabic إِسْلَام (Islām) 'submission, surrender, peace', from the root س ل م (s-l-m). The source gloss 'Submission to Allah' is broadly consistent."),
 "isma": ("أسماء", "اسماء", "اسماء", "अस्मा", "اسماء", "asma", "Arabic", "Female",
          "Arabic أَسْمَاء (Asmāʾ)", False, "medium",
          "Isma is Arabic أَسْمَاء (Asmāʾ), a documented female given name borne by Asma bint Abi Bakr, a companion of the Prophet Muhammad. CRITICAL SOURCE ERROR: the source gave إسماء (a different form) and glossed the name 'Given by Allah'; the correct form is أَسْمَاء."),
 "ismaael": ("إسماعيل", "اسماعیل", "اسماعیل", "इस्माईल", "اسماعیل", "ishmael", "Arabic", "Male",
             "Qur'anic proper name; إِسْمَاعِيل (Ismāʿīl)", True, "high",
             "Ismaael is Arabic إِسْمَاعِيل (Ismāʿīl), the Qur'anic form of Ishmael, a prophet mentioned in the Qur'an. The source gloss 'God heard' is unsupported; the name is a proper name. Same name as ismaeel and ismail."),
 "ismaeel": ("إسماعيل", "اسماعیل", "اسماعیل", "इस्माईल", "اسماعیل", "ishmael", "Arabic", "Male",
             "Qur'anic proper name; إِسْمَاعِيل (Ismāʿīl)", True, "high",
             "Ismaeel is Arabic إِسْمَاعِيل (Ismāʿīl), the Qur'anic form of Ishmael, a prophet mentioned in the Qur'an. The source gloss 'God Heard' is unsupported; the name is a proper name. Same name as ismaael and ismail."),
 "ismah": ("عصمة", "عصمت", "عصمت", "इस्मा", "عصمت", "protection_ismah", "Arabic", "Female",
           "Arabic root ع ص م (ʿ-ṣ-m); عِصْمَة (ʿIṣma)", False, "medium",
           "Ismah is Arabic عِصْمَة (ʿIṣma) 'protection, safeguard, chastity', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave إسماع (a different word) and glossed the name \"God's perfection\"; the correct form is عِصْمَة. Same name as ismat."),
 "ismail": ("إسماعيل", "اسماعیل", "اسماعیل", "इस्माईल", "اسماعیل", "ishmael", "Arabic", "Male",
            "Qur'anic proper name; إِسْمَاعِيل (Ismāʿīl)", True, "high",
            "Ismail is Arabic إِسْمَاعِيل (Ismāʿīl), the Qur'anic form of Ishmael, a prophet mentioned in the Qur'an. The source record was an 8-key stub with no data. Same name as ismaael and ismaeel."),
 "ismat": ("عصمة", "عصمت", "عصمت", "इस्मत", "عصمت", "protection_ismah", "Arabic", "Female",
           "Arabic root ع ص م (ʿ-ṣ-m); عِصْمَة (ʿIṣma)", False, "high",
           "Ismat is Arabic عِصْمَة (ʿIṣma) 'protection, safeguard, chastity', from the root ع ص م (ʿ-ṣ-m); the form عِصْمَت is the Persian/Urdu rendering. The source gloss 'Safeguard, Security' is broadly consistent. Same name as ismah."),
 "isra": ("إسراء", "اسراء", "اسراء", "इसरा", "اسراء", "night_journey", "Arabic", "Female",
          "Qur'anic term; إِسْرَاء (Isrāʾ)", True, "high",
          "Isra is Arabic إِسْرَاء (Isrāʾ) 'night journey', the term for the Prophet's night journey and the title of a Qur'anic sura. The source record was an 8-key stub with no data. Same name as israa and issra."),
 "israa": ("إسراء", "اسراء", "اسراء", "इसरा", "اسراء", "night_journey", "Arabic", "Female",
           "Qur'anic term; إِسْرَاء (Isrāʾ)", True, "high",
           "Israa is Arabic إِسْرَاء (Isrāʾ) 'night journey', the term for the Prophet's night journey and the title of a Qur'anic sura. The source gloss 'Night Journey' is consistent. Same name as isra and issra."),
 "israfil": ("إسرافيل", "اسرافیل", "اسرافیل", "इसराफ़ील", "اسرافیل", "israfil", "Arabic", "Male",
             "Arabic إِسْرَافِيل (Isrāfīl)", False, "high",
             "Israfil is Arabic إِسْرَافِيل (Isrāfīl), the name of the angel who will blow the trumpet on the Day of Judgment. The source gloss 'The Angel of the Trumpet' is consistent."),
 "israil": ("إسرائيل", "اسرائیل", "اسرائیل", "इसराईल", "اسرائیل", "israel", "Arabic", "Male",
            "Qur'anic proper name; إِسْرَائِيل (Isrāʾīl)", True, "high",
            "Israil is Arabic إِسْرَائِيل (Isrāʾīl), the Qur'anic name of Jacob (Israel). The source gloss 'God of Israel' is unsupported; the name is a proper name."),
 "israr": ("إصرار", "اصرار", "اصرار", "इसरार", "اصرار", "persistence", "Arabic", "Male",
           "Arabic root ص ر ر (ṣ-r-r); إِصْرَار (Iṣrār)", False, "medium",
           "Israr is Arabic إِصْرَار (Iṣrār) 'persistence, insistence, determination', from the root ص ر ر (ṣ-r-r). The source gloss 'Steadfast' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "israt": ("عشرت", "عشرت", "عشرت", "इसरत", "عشرت", "society", "Persian", "Female",
           "Persian/Urdu عشرت (ishrat), from Arabic عِشْرَة", False, "low",
           "Israt is recorded at low confidence. The source gave the junk string 'Ali' in the Arabic column and glossed the name 'Ascent, Journey'; عشرت (ishrat) is a Persian/Urdu female given name meaning 'society, joy', but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted. Same name as ishrat."),
 "issa": ("عيسى", "عیسیٰ", "عیسی", "ईसा", "عیسی", "jesus", "Arabic", "Male",
          "Qur'anic proper name; عِيسَى (ʿĪsā)", True, "high",
          "Issa is Arabic عِيسَى (ʿĪsā), the Qur'anic form of Jesus, a prophet mentioned in the Qur'an. The source gloss 'Prophet Jesus' is consistent. Same name as isa and iesa."),
 "issam": ("عصام", "عصام", "عصام", "इस्साम", "عصام", "protector", "Arabic", "Male",
           "Arabic root ع ص م (ʿ-ṣ-m); عِصَام (ʿIṣām)", False, "medium",
           "Issam is Arabic عِصَام (ʿIṣām) 'protector, safeguard, guardian', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave إسماعيل (a different name) and glossed the name 'Gift, reward'; the correct form is عِصَام. Same name as isaam and isam."),
 "issra": ("إسراء", "اسراء", "اسراء", "इसरा", "اسراء", "night_journey", "Arabic", "Female",
           "Qur'anic term; إِسْرَاء (Isrāʾ)", True, "medium",
           "Issra is Arabic إِسْرَاء (Isrāʾ) 'night journey', the term for the Prophet's night journey and the title of a Qur'anic sura. The source gloss 'Seeker of God' is unsupported and has been replaced with the documented identification. Same name as isra and israa."),
 "istabraq": ("استبرق", "استبرق", "استبرق", "इस्तब्रक़", "استبرق", "brocade", "Arabic", "Male",
              "Qur'anic term; اِسْتَبْرَق (Istabraq)", True, "medium",
              "Istabraq is Arabic اِسْتَبْرَق (Istabraq) 'brocade; a fine woven fabric', a Qur'anic term describing the garments of paradise. The source gloss 'Brilliant, Shining, Radiant' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "itab": ("عتاب", "عتاب", "عتاب", "इताब", "عتاب", "reproach", "Arabic", "Female",
          "Arabic root ع ت ب (ʿ-t-b); عِتَاب (ʿItāb)", False, "medium",
          "Itab is Arabic عِتَاب (ʿItāb) 'reproach, gentle blame, censure', from the root ع ت ب (ʿ-t-b). The source gloss 'Gift, Reward' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "itaf": ("إتحاف", "اتحاف", "اتحاف", "इताफ़", "اتحاف", "gift_giving", "Arabic", "Female",
          "Arabic root ت ح ف (t-ḥ-f); إِتْحَاف (Itḥāf)", False, "low",
          "Itaf is recorded at low confidence. The source gave إتف (a truncated form) and glossed the name 'Gift, Reward'; the intended form is likely إِتْحَاف (Itḥāf), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "itidal": ("اعتدال", "اعتدال", "اعتدال", "इतिदाल", "اعتدال", "moderation", "Arabic", "Female",
            "Arabic root ع د ل (ʿ-d-l); اِعْتِدَال (Iʿtidāl)", False, "medium",
            "Itidal is Arabic اِعْتِدَال (Iʿtidāl) 'moderation, balance, evenness', from the root ع د ل (ʿ-d-l). CRITICAL SOURCE ERROR: the source gave إعتدال (a different form) and glossed the name 'Fidelity, Loyalty, Steadfastness'; the correct form is اِعْتِدَال."),
 "iyad": ("إياد", "ایاد", "ایاد", "इयाद", "ایاد", "support_iyad", "Arabic", "Male",
          "Arabic إِيَاد (Iyād)", False, "medium",
          "Iyad is Arabic إِيَاد (Iyād) 'support, backing, reinforcement', a documented male given name. The source gloss 'Given by God' is unsupported and has been replaced with the lexical sense."),
 "iyan": ("إيان", "ایان", "ایان", "इयान", "ایان", "iyan", "Arabic", "Male",
          "Arabic إِيَان (Iyān)", False, "low",
          "Iyan is recorded at low confidence. The source gave إيان and glossed the name 'Delight, Pleasure'; إِيَان (Iyān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "iyas": ("إياس", "ایاس", "ایاس", "इयास", "ایاس", "consolation", "Arabic", "Male",
          "Arabic root أ ي س (ʾ-y-s); إِيَاس (Iyās)", False, "medium",
          "Iyas is Arabic إِيَاس (Iyās) 'consolation, solace, comfort', from the root أ ي س (ʾ-y-s). The source gloss 'Healer' is unsupported and has been replaced with the lexical sense. Same name as iyaz."),
 "iyaz": ("إياز", "ایاز", "ایاز", "इयाज़", "ایاز", "consolation", "Arabic", "Male",
          "Arabic root أ ي س (ʾ-y-s); إِيَاز (Iyāz)", False, "medium",
          "Iyaz is Arabic إِيَاز (Iyāz) 'consolation, solace, comfort', a documented male given name. The source gloss 'Healer, Helper' is unsupported and has been replaced with the lexical sense. Same name as iyas."),
 "izaan": ("أذان", "اذان", "اذان", "अज़ान", "اذان", "call_to_prayer", "Arabic", "Male",
           "Arabic root أ ذ ن (ʾ-dh-n); أَذَان (Adhān)", False, "medium",
           "Izaan is Arabic أَذَان (Adhān) 'call to prayer, announcement', from the root أ ذ ن (ʾ-dh-n). CRITICAL SOURCE ERROR: the source gave إذان (a different form) and glossed the name 'Dazzling, Splendid'; the correct form is أَذَان."),
 "izat": ("عزة", "عزت", "عزت", "इज़्ज़त", "عزت", "honor", "Arabic", "Female",
          "Arabic root ع ز ز (ʿ-z-z); عِزَّة (ʿIzza)", False, "high",
          "Izat is Arabic عِزَّة (ʿIzza) 'honor, respect, dignity', from the root ع ز ز (ʿ-z-z); the form عِزَّت is the Persian/Urdu rendering. The source gloss 'Honor, Respect, Dignity' is consistent. Same name as izzat, izza and izzah."),
 "izaz": ("إعزاز", "اعزاز", "اعزاز", "इज़ाज़", "اعزاز", "honoring_izaz", "Arabic", "Male",
          "Arabic root ع ز ز (ʿ-z-z); إِعْزَاز (Iʿzāz)", False, "medium",
          "Izaz is Arabic إِعْزَاز (Iʿzāz) 'honoring, strengthening, showing respect', from the root ع ز ز (ʿ-z-z). CRITICAL SOURCE ERROR: the source gave عزاز (a different form) and glossed the name 'Mighty, Powerful'; the correct form is إِعْزَاز."),
 "izdihar": ("ازدهار", "ازدہار", "ازدهار", "इज़दिहार", "ازدهار", "flourishing", "Arabic", "Female",
             "Arabic root ز ه ر (z-h-r); اِزْدِهَار (Izdiḥār)", False, "medium",
             "Izdihar is Arabic اِزْدِهَار (Izdiḥār) 'flourishing, prosperity, thriving', from the root ز ه ر (z-h-r). The source gloss 'Success, Triumph' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "izhar": ("إظهار", "اظہار", "اظهار", "इज़हार", "اظهار", "expression", "Arabic", "Male",
           "Arabic root ظ ه ر (ẓ-h-r); إِظْهَار (Iẓhār)", False, "high",
           "Izhar is Arabic إِظْهَار (Iẓhār) 'expression, declaration, manifestation', from the root ظ ه ر (ẓ-h-r). The source gloss 'Expression, Declaration' is consistent."),
 "izma": ("عظمة", "عظمت", "عظمت", "इज़मा", "عظمت", "greatness", "Arabic", "Female",
          "Arabic root ع ظ م (ʿ-ẓ-m); عَظَمَة (ʿAẓama)", False, "medium",
          "Izma is Arabic عَظَمَة (ʿAẓama) 'greatness, grandeur, majesty', from the root ع ظ م (ʿ-ẓ-m). CRITICAL SOURCE ERROR: the source gave عزما (a different form) and glossed the name 'Mother of a lion'; the correct form is عَظَمَة."),
 "izyan": ("إيزيان", "ایزیان", "ایزیان", "इज़यान", "ایزیان", "izyan", "Arabic", "Male",
           "Arabic إِيزِيَان (Īziyān)", False, "low",
           "Izyan is recorded at low confidence. The source gave إيزيان and glossed the name 'Powerful, Brave, Intelligent'; إِيزِيَان (Īziyān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "izz": ("عز", "عز", "عز", "इज़्ज़", "عز", "glory", "Arabic", "Male",
         "Arabic root ع ز ز (ʿ-z-z); عِزّ (ʿIzz)", False, "medium",
         "Izz is Arabic عِزّ (ʿIzz) 'glory, might, honor', from the root ع ز ز (ʿ-z-z). The source gloss 'Glory, Greatness, Honor' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "izza": ("عزة", "عزہ", "عزه", "इज़्ज़ा", "عزه", "honor", "Arabic", "Female",
          "Arabic root ع ز ز (ʿ-z-z); عِزَّة (ʿIzza)", False, "high",
          "Izza is Arabic عِزَّة (ʿIzza) 'honor, respect, dignity', from the root ع ز ز (ʿ-z-z). The source gloss 'Exalted, Noble' is broadly consistent. Same name as izat, izzat and izzah."),
 "izzah": ("عزة", "عزہ", "عزه", "इज़्ज़ा", "عزه", "honor", "Arabic", "Female",
           "Arabic root ع ز ز (ʿ-z-z); عِزَّة (ʿIzza)", False, "high",
           "Izzah is Arabic عِزَّة (ʿIzza) 'honor, respect, dignity', from the root ع ز ز (ʿ-z-z). The source record was an 8-key stub with no data. Same name as izat, izzat and izza."),
 "izzan": ("عزان", "عزان", "عزان", "इज़्ज़ान", "عزان", "izzan", "Arabic", "Male",
           "Arabic عَزَّان (ʿAzzān)", False, "low",
           "Izzan is recorded at low confidence. The source gave عزان and glossed the name 'Gift, Grace, Honor'; عَزَّان (ʿAzzān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "izzani": ("عزاني", "عزانی", "عزانی", "इज़्ज़ानी", "عزاني", "izzani", "Arabic", "Female",
            "Arabic عَزَّانِي (ʿAzzānī)", False, "low",
            "Izzani is recorded at low confidence. The source gave عزاني and glossed the name 'Intelligent, noble'; عَزَّانِي (ʿAzzānī) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "izzat": ("عزة", "عزت", "عزت", "इज़्ज़त", "عزت", "honor", "Arabic", "Male",
           "Arabic root ع ز ز (ʿ-z-z); عِزَّة (ʿIzza)", False, "high",
           "Izzat is Arabic عِزَّة (ʿIzza) 'honor, respect, dignity', from the root ع ز ز (ʿ-z-z); the form عِزَّت is the Persian/Urdu rendering. The source gloss 'Glory' is broadly consistent. Same name as izat, izza and izzah."),
 "izzati": ("عزتي", "عزتی", "عزتی", "इज़्ज़ती", "عزتي", "honor", "Arabic", "Female",
            "Arabic root ع ز ز (ʿ-z-z); عِزَّتِي (ʿIzzatī)", False, "low",
            "Izzati is recorded at low confidence. The source gave the broken form إززةي and glossed the name 'Pride, Honor'; the form is related to عِزَّة (ʿIzza), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "izzet": ("عزت", "عزت", "عزت", "इज़्ज़ेत", "عزت", "izzet", "Turkish", "Male",
           "Turkish İzzet, from Arabic عِزَّة", False, "medium",
           "Izzet is Turkish İzzet, from Arabic عِزَّة (ʿIzza) 'honor, respect, dignity'. MISLABELLED ORIGIN: the source recorded the name as Arabic; the form عزت is the Turkish rendering. The source gloss 'powerful, strong, mighty' is broadly consistent."),
 "izzi": ("عزي", "عزی", "عزی", "इज़्ज़ी", "عزي", "glory", "Arabic", "Male",
          "Arabic root ع ز ز (ʿ-z-z); عِزِّي (ʿIzzī)", False, "low",
          "Izzi is recorded at low confidence. The source gave the broken form إزى and glossed the name 'Gift, Grace, Reward'; the form is related to عِزّ (ʿIzz), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "jaad": ("جاد", "جاد", "جاد", "जाद", "جاد", "generous_jaad", "Arabic", "Male",
          "Arabic root ج و د (j-w-d); جَاد (Jād)", False, "medium",
          "Jaad is Arabic جَاد (Jād) 'generous, bountiful, excellent', from the root ج و د (j-w-d). The source gloss 'Gentle, Mild' is unsupported and has been replaced with the lexical sense."),
 "jaafar": ("جعفر", "جعفر", "جعفر", "जाफ़र", "جعفر", "jafar", "Arabic", "Male",
            "Arabic جَعْفَر (Jaʿfar)", False, "high",
            "Jaafar is Arabic جَعْفَر (Jaʿfar), a well-documented male given name borne by Ja'far ibn Abi Talib, a companion of the Prophet Muhammad. The source gloss 'Concealed, Hidden' is unsupported; the name is a proper name. Same name as jafar."),
 "jaah": ("جاه", "جاہ", "جاه", "जाह", "جاه", "rank", "Arabic", "Male",
          "Arabic root ج و ه (j-w-h); جَاه (Jāh)", False, "medium",
          "Jaah is Arabic جَاه (Jāh) 'rank, dignity, standing', from the root ج و ه (j-w-h). The source gloss 'Gentle, Kind' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "jabal": ("جبل", "جبل", "جبل", "जबल", "جبل", "mountain", "Arabic", "Male",
           "Arabic root ج ب ل (j-b-l); جَبَل (Jabal)", False, "medium",
           "Jabal is Arabic جَبَل (Jabal) 'mountain, mount', from the root ج ب ل (j-b-l). The source gloss 'Mountain' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "jabar": ("جبار", "جبار", "جبار", "जबार", "جبار", "compeller", "Arabic", "Male",
           "Arabic root ج ب ر (j-b-r); جَبَّار (Jabbār)", False, "high",
           "Jabar is Arabic جَبَّار (Jabbār) 'compeller, almighty, restorer', from the root ج ب ر (j-b-r); it is also one of the names of Allah (الجبّار). The source gloss 'The Exalted One' is broadly consistent. Same name as jabbar."),
 "jabbar": ("جبار", "جبار", "جبار", "जब्बार", "جبار", "compeller", "Arabic", "Male",
            "Arabic root ج ب ر (j-b-r); جَبَّار (Jabbār)", False, "high",
            "Jabbar is Arabic جَبَّار (Jabbār) 'compeller, almighty, restorer', from the root ج ب ر (j-b-r); it is also one of the names of Allah (الجبّار). The source gloss 'Powerful, Compeller' is consistent. Same name as jabar."),
}
