# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 7 (amaan..anabia)."""

GLOSSES = {
    "safety": {"en": "Security, safety, protection", "ur": "امان، سلامتی، تحفظ", "fa": "امنیت، ایمنی، حفاظت", "hi": "सुरक्षा, अमान, शांति", "ps": "امنیت، ساتنه", "ar": "أمان، أمن، حماية"},
    "eternity": {"en": "Eternity, perpetuity", "ur": "ابدیت، دوام", "fa": "جاودانگی، ابدیت", "hi": "अनंतता, शाश्वतता", "ps": "ابدي، دوام", "ar": "أبد، خلود"},
    "mother": {"en": "Mother", "ur": "ماں، والدہ", "fa": "مادر", "hi": "माँ, माता", "ps": "مور", "ar": "أم، والدة"},
    "mother_lion": {"en": "Mother of a lion", "ur": "شیر کی ماں", "fa": "مادر شیر", "hi": "शेर की माँ", "ps": "د زمری مور", "ar": "أم الأسد"},
    "hope": {"en": "Hope, expectation", "ur": "امید، توقع", "fa": "امید، انتظار", "hi": "आशा, अपेक्षा", "ps": "هيله، تمه", "ar": "أمل، رجاء"},
    "young_girl": {"en": "Young girl", "ur": "نوجوان لڑکی", "fa": "دختر جوان", "hi": "युवा लड़की", "ps": "ځوانه نجلۍ", "ar": "فتاة صغيرة"},
    "god_bounty": {"en": "God's bounty", "ur": "خدا کا فضل", "fa": "فضل خدا", "hi": "ईश्वर की कृपा", "ps": "د خدای فضل", "ar": "فضل الله"},
    "young_tender": {"en": "Young, tender", "ur": "نوجوان، نرم", "fa": "جوان، نازک", "hi": "युवा, कोमल", "ps": "ځوان، نرم", "ar": "صغيرة، ناعمة"},
    "hope_trust": {"en": "Hope, trust", "ur": "امید، اعتماد", "fa": "امید، اعتماد", "hi": "आशा, विश्वास", "ps": "هيله، باور", "ar": "أمل، ثقة"},
    "mother_mothers": {"en": "Mother of mothers", "ur": "ماؤں کی ماں", "fa": "مادر مادران", "hi": "माताओं की माता", "ps": "د مېندو مور", "ar": "أم الأمهات"},
    "peace": {"en": "Peace, safety, trust", "ur": "امن، سلامتی، اعتماد", "fa": "صلح، امنیت، اعتماد", "hi": "शांति, अमन, विश्वास", "ps": "سوله، امنیت", "ar": "أمان، سلام، ثقة"},
    "faith": {"en": "Faith, trust", "ur": "ایمان، اعتماد", "fa": "ایمان، اعتماد", "hi": "विश्वास, ईमान", "ps": "ایمان، باور", "ar": "إيمان، ثقة"},
    "wishes": {"en": "Wishes, aspirations", "ur": "تمنائیں، آرزوئیں", "fa": "آرزوها، امیدها", "hi": "इच्छाएँ, आकांक्षाएँ", "ps": "هیلې، ارمانونه", "ar": "أماني، رغبات"},
    "trust_faith": {"en": "Trust, faith, belief", "ur": "اعتماد، ایمان، یقین", "fa": "اعتماد، ایمان، باور", "hi": "विश्वास, ईमान, यक़ीन", "ps": "باور، ایمان", "ar": "ثقة، إيمان، يقين"},
    "eternal": {"en": "Eternal, immortal", "ur": "ابدی، لافانی", "fa": "جاودان، بی‌مرگ", "hi": "शाश्वत, अमर", "ps": "ابدي، نه مړ کېدونکی", "ar": "أبدي، خالد"},
    "long_life": {"en": "Long life and prosperity", "ur": "طویل عمر اور خوشحالی", "fa": "عمر طولانی و رفاه", "hi": "दीर्घायु और समृद्धि", "ps": "اوږد عمر او هوساینه", "ar": "طول العمر والرخاء"},
    "steadfast": {"en": "She who is steadfast", "ur": "ثابت قدم", "fa": "استوار، پایدار", "hi": "दृढ़, अटल", "ps": "ټینګه، ثابته", "ar": "ثابتة، راسخة"},
    "devoted_loyal": {"en": "Devoted, loyal", "ur": "مخلص، وفادار", "fa": "فداکار، وفادار", "hi": "समर्पित, वफ़ादार", "ps": "مخلصه، وفاداره", "ar": "مخلصة، وفية"},
    "amarjeet": {"en": "Eternal triumph, forever victorious", "ur": "ابدی فتح، ہمیشہ فاتح", "fa": "پیروزی جاودان", "hi": "अमर विजय, शाश्वत विजेता", "ps": "ابدي بریا", "ar": "نصر أبدي"},
    "gatherer": {"en": "Gatherer, sustainer", "ur": "جمع کرنے والا، پالنے والا", "fa": "گردآورنده، پرورنده", "hi": "संग्रहकर्ता, पोषक", "ps": "ټولونکی، پالونکی", "ar": "جامع، رازق"},
    "mother_love": {"en": "Mother's love", "ur": "ماں کی محبت", "fa": "مهر مادر", "hi": "माँ का प्यार", "ps": "د مور مینه", "ar": "حب الأم"},
    "gift_allah": {"en": "Gift of Allah", "ur": "اللہ کا تحفہ", "fa": "هدیهٔ خدا", "hi": "अल्लाह का उपहार", "ps": "د الله ډالۍ", "ar": "عطية الله"},
    "loving": {"en": "Loving", "ur": "محبت کرنے والا", "fa": "دوست‌دار، مهربان", "hi": "प्रेम करने वाला", "ps": "مینه کوونکی", "ar": "محب، ودود"},
    "amaya": {"en": "Amaya (Basque place name; 'the end, the mother city')", "ur": "امایا، باسک نام", "fa": "آمایا، نام باسکی", "hi": "अमाया, बास्क नाम", "ps": "امایا، باسک نوم", "ar": "أمايا، اسم باسكي"},
    "amazigh": {"en": "Free people (self-designation of the Amazigh/Berber peoples)", "ur": "آزاد لوگ، امازیغ", "fa": "مردم آزاد، آمازیغ", "hi": "स्वतंत्र लोग, अमाज़ीघ", "ps": "ازاد خلک، امازیغ", "ar": "الأمازيغ، الشعب الحر"},
    "ambergris": {"en": "Ambergris; fragrant substance", "ur": "عنبر، خوشبودار مادہ", "fa": "عنبر، مادهٔ خوشبو", "hi": "अंबर, सुगंधित पदार्थ", "ps": "عنبر، خوشبویه ماده", "ar": "عنبر، مادة عطرية"},
    "jewel": {"en": "Jewel, precious stone", "ur": "جواہر، قیمتی پتھر", "fa": "جواهر، سنگ گران‌بها", "hi": "रत्न, बहुमूल्य पत्थर", "ps": "ګاڼه، قیمتي ډبره", "ar": "جوهر، حجر كريم"},
    "moonlight": {"en": "Moonlight", "ur": "چاندنی", "fa": "مهتاب", "hi": "चाँदनी", "ps": "سپوږمۍ رڼا", "ar": "ضوء القمر"},
    "helper": {"en": "Helper", "ur": "مددگار", "fa": "یاری‌گر", "hi": "सहायक", "ps": "مرسته کوونکی", "ar": "معين، ناصر"},
    "honor_trust": {"en": "Honour, trustworthiness", "ur": "عزت، امانت داری", "fa": "شرف، امانت‌داری", "hi": "सम्मान, विश्वसनीयता", "ps": "وياړ، امانت", "ar": "شرف، أمانة"},
    "river": {"en": "River", "ur": "دریا، ندی", "fa": "رود، نهر", "hi": "नदी, दरिया", "ps": "سیند، رود", "ar": "نهر، جدول"},
    "trustworthy": {"en": "Trustworthy, honest", "ur": "امانتدار، دیانتدار", "fa": "امین، درستکار", "hi": "विश्वसनीय, ईमानदार", "ps": "امانتدار، رښتونی", "ar": "أمين، صادق"},
    "trustworthy_f": {"en": "Trustworthy, dependable (feminine)", "ur": "امانتدار، قابل اعتماد", "fa": "امین، قابل اعتماد", "hi": "विश्वसनीय, भरोसेमंद", "ps": "امانتداره، باوري", "ar": "أمينة، موثوقة"},
    "prince": {"en": "Prince, commander", "ur": "امیر، سردار", "fa": "امیر، فرمانده", "hi": "अमीर, सेनापति", "ps": "امیر، قوماندان", "ar": "أمير، قائد"},
    "princess": {"en": "Princess, ruler", "ur": "امیرہ، شہزادی، حاکمہ", "fa": "امیره، شاهزاده، فرمانروا", "hi": "अमीरा, राजकुमारी, शासिका", "ps": "امیره، شهزادګۍ", "ar": "أميرة، حاكمة"},
    "industrious": {"en": "Industrious one", "ur": "محنتی، جفاکش", "fa": "کوشا، سخت‌کوش", "hi": "परिश्रमी, मेहनती", "ps": "کوښښګره، زحمتکشه", "ar": "مجتهدة، نشيطة"},
    "tranquility": {"en": "Tranquility, serenity", "ur": "سکون، اطمینان", "fa": "آرامش، سکون", "hi": "शांति, सुकून", "ps": "سکون، آرام", "ar": "سكينة، هدوء"},
    "gentle_kind": {"en": "Gentle, kind", "ur": "نرم، مہربان", "fa": "نرم، مهربان", "hi": "कोमल, दयालु", "ps": "نرم، مهربان", "ar": "لطيف، كريم"},
    "present": {"en": "Present, existing", "ur": "موجود، حاضر", "fa": "موجود، حاضر", "hi": "वर्तमान, उपस्थित", "ps": "موجود، حاضر", "ar": "موجود، حاضر"},
    "servant": {"en": "Servant", "ur": "خادم، نوکر", "fa": "خدمتگزار، بنده", "hi": "सेवक, दास", "ps": "خدمتګار، بنده", "ar": "عبد، خادم"},
    "sweetness": {"en": "Sweetness", "ur": "میٹھاس", "fa": "شیرینی، لطافت", "hi": "मिठास", "ps": "خوږوالی", "ar": "حلاوة، عذوبة"},
    "work": {"en": "Work, labour, industriousness", "ur": "کام، محنت", "fa": "کار، کوشش", "hi": "काम, श्रम", "ps": "کار، زحمت", "ar": "عمل، اجتهاد"},
    "mother_believers": {"en": "Mother of the believers", "ur": "امہات المؤمنین میں سے", "fa": "مادر مؤمنان", "hi": "मोमिनों की माता", "ps": "د مومنانو مور", "ar": "أم المؤمنين"},
    "faithful": {"en": "Faithful, trustworthy", "ur": "وفادار، امانتدار", "fa": "وفادار، امین", "hi": "वफ़ादार, विश्वसनीय", "ps": "وفاداره، امانتداره", "ar": "أمينة، وفية"},
    "reliable": {"en": "Reliable, trustworthy", "ur": "قابل اعتماد، امانتدار", "fa": "قابل اعتماد، امین", "hi": "विश्वसनीय, भरोसेमंद", "ps": "باوري، امانتدار", "ar": "موثوق، أمين"},
    "tranquility_love": {"en": "Tranquility, sweetness, or love", "ur": "سکون، میٹھاس یا محبت", "fa": "آرامش، شیرینی یا عشق", "hi": "शांति, मिठास या प्रेम", "ps": "سکون، خوږوالی یا مینه", "ar": "سكينة، حلاوة أو حب"},
    "tranquility_hope": {"en": "Tranquility, hope", "ur": "سکون، امید", "fa": "آرامش، امید", "hi": "शांति, आशा", "ps": "سکون، هيله", "ar": "سكينة، أمل"},
    "noble_exalted": {"en": "Noble, exalted", "ur": "نجیب، بلند", "fa": "نجیب، والا", "hi": "कुलीन, उच्च", "ps": "نجیب، لوړ", "ar": "نبيل، مرفوع"},
    "patient": {"en": "One who is patient", "ur": "صبر کرنے والا", "fa": "شکیبا، صبور", "hi": "धैर्यवान, सब्र करने वाला", "ps": "صبر کوونکی", "ar": "صبار، صبور"},
    "long_lived": {"en": "Long-lived, prosperous", "ur": "طویل عمر، خوشحال", "fa": "دیرزیست، مرفه", "hi": "दीर्घायु, समृद्ध", "ps": "اوږد عمر، هوسا", "ar": "طويلة العمر، مزدهرة"},
    "mountain": {"en": "Mountain or high place", "ur": "پہاڑ یا بلند مقام", "fa": "کوه یا بلندی", "hi": "पर्वत या ऊँचा स्थान", "ps": "غر یا لوړ ځای", "ar": "جبل أو مكان عالٍ"},
    "builder": {"en": "Builder, one who constructs", "ur": "معمار، تعمیر کرنے والا", "fa": "سازنده، بناکننده", "hi": "निर्माता, बनाने वाला", "ps": "جوړونکی، معمار", "ar": "بنّاء، معماري"},
    "safe_peaceful": {"en": "Safe and peaceful", "ur": "محفوظ اور پرسکون", "fa": "ایمن و آرام", "hi": "सुरक्षित और शांत", "ps": "خوندي او آرام", "ar": "آمنة، مطمئنة"},
    "safe_secure": {"en": "Safe, secure, protected", "ur": "محفوظ، مامون", "fa": "ایمن، محفوظ", "hi": "सुरक्षित, महफ़ूज़", "ps": "خوندي، ساتل شوی", "ar": "آمنة، محفوظة"},
    "protection": {"en": "Protection, safety", "ur": "حفاظت، سلامتی", "fa": "حفاظت، ایمنی", "hi": "सुरक्षा, हिफ़ाज़त", "ps": "ساتنه، امنیت", "ar": "حماية، أمان"},
    "command": {"en": "Command, order, strength", "ur": "حکم، فرمان، طاقت", "fa": "فرمان، دستور، قدرت", "hi": "आदेश, हुक्म, शक्ति", "ps": "حکم، فرمان، ځواک", "ar": "أمر، قوة"},
    "mother_many": {"en": "Mother of many", "ur": "بہت سے بچوں کی ماں", "fa": "مادر بسیاری", "hi": "अनेकों की माता", "ps": "د ډېرو مور", "ar": "أم كثيرة الأولاد"},
    "high_born": {"en": "High-born, exalted", "ur": "بلند نسب، عالی", "fa": "بلندنسب، والا", "hi": "उच्च कुल, महान", "ps": "لوړ نسب، عالي", "ar": "رفيعة النسب، عليّة"},
    "high_status": {"en": "High status, exalted", "ur": "بلند مرتبہ، عالی", "fa": "بلندمرتبه، والا", "hi": "उच्च पद, महान", "ps": "لوړ مقام، عالي", "ar": "عالي المقام، رفيع"},
    "sweet_smelling": {"en": "Sweet-smelling, fragrant", "ur": "خوشبودار", "fa": "خوشبو", "hi": "सुगंधित", "ps": "خوشبویه", "ar": "عطرة، طيبة الرائحة"},
    "belonging_allah": {"en": "Belonging to Allah", "ur": "اللہ سے منسوب", "fa": "منسوب به خدا", "hi": "अल्लाह से संबंधित", "ps": "د الله اړوند", "ar": "منسوب إلى الله"},
    "protector": {"en": "Protector", "ur": "محافظ، نگہبان", "fa": "نگهبان، محافظ", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، محافظ", "ar": "حامي، حفيظ"},
    "noble_precious": {"en": "Noble, precious", "ur": "نجیب، قیمتی", "fa": "نجیب، گران‌بها", "hi": "कुलीन, बहुमूल्य", "ps": "نجیبه، قیمتي", "ar": "نبيلة، نفيسة"},
    "brave_strong": {"en": "Brave, strong", "ur": "بہادر، مضبوط", "fa": "دلیر، نیرومند", "hi": "वीर, बलवान", "ps": "زړور، پیاوړی", "ar": "شجاع، قوي"},
    "man_commander": {"en": "Man, commander", "ur": "مرد، سردار", "fa": "مرد، فرمانده", "hi": "पुरुष, सेनापति", "ps": "سړی، قوماندان", "ar": "رجل، قائد"},
    "proverbs": {"en": "Proverbs, parables, examples", "ur": "امثال، مثالیں", "fa": "مَثَل‌ها، نمونه‌ها", "hi": "कहावतें, उदाहरण", "ps": "مثالونه، متلونه", "ar": "أمثال، عبر"},
    "most_exalted": {"en": "The most exalted", "ur": "سب سے بلند", "fa": "بلندترین، والاترین", "hi": "सर्वोच्च, सबसे महान", "ps": "تر ټولو لوړه", "ar": "العليا، الأرفع"},
    "breath_life": {"en": "Breath, life", "ur": "سانس، زندگی", "fa": "نفس، زندگی", "hi": "साँस, जीवन", "ps": "ساه، ژوند", "ar": "نفس، حياة"},
    "grace_honor": {"en": "Grace, honour", "ur": "فضل، عزت", "fa": "فضل، شرف", "hi": "कृपा, सम्मान", "ps": "فضل، وياړ", "ar": "نعمة، شرف"},
    "nurse_supporter": {"en": "Nurse, supporter", "ur": "دایہ، مددگار", "fa": "پرستار، پشتیبان", "hi": "धात्री, सहायक", "ps": "نرس، ملاتړې", "ar": "حاضنة، ناصرة"},
    "good_news": {"en": "Giver of good news", "ur": "خوشخبری دینے والا", "fa": "مژده‌دهنده", "hi": "शुभ समाचार देने वाला", "ps": "زیرې ورکوونکی", "ar": "مبشّر، بشير"},
    "anabia": {"en": "Anabia (a modern given name; 'prophetess' in popular usage)", "ur": "انبیا، نبیوں سے منسوب", "fa": "انبیا، منسوب به پیامبران", "hi": "अनबिया, नबियों से संबंधित", "ps": "انبیا، د پیغمبرانو اړوند", "ar": "أنبياء، جمع نبي"},
}

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "amaan": ("أمان", "امان", None, "अमान", "امان", "safety", "Arabic", "Male", "أ م ن", "root أ م ن occurs in the Qur'an; أمان is a normal Arabic noun", "high", "Amān ('security, safety, protection')."),
 "amaar": ("عمار", "عمار", None, "अम्मार", "عمار", "builder", "Arabic", "Male", "ع م ر", "not established", "high", "ʿAmmār ('builder, one who constructs'), also the name of ʿAmmār ibn Yāsir, a companion of the Prophet. The source record's gloss 'Father of many' is unsupported."),
 "amad": ("أمد", "امد", None, "अमद", "امد", "eternity", "Arabic", "Male", "أ م د", "root أ م د occurs in the Qur'an; أمد is a normal Arabic noun", "medium", "Amad ('term, limit, duration'). The source record's gloss 'Eternity, Perpetuity' is an approximation."),
 "amah": ("أمة", "امہ", None, "अमा", "امه", "servant", "Arabic", "Female", "أ م و", "not established", "medium", "Amah ('maidservant, female servant'). The source record's gloss 'Mother of all' is unsupported."),
 "amaira": ("أميرة", "امیرہ", None, "अमायरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Amīra ('princess'). The source record's gloss 'Mother of a Lion' is unsupported."),
 "amal": ("أمل", "امل", None, "अमल", "امل", "hope", "Arabic", "Unisex", "أ م ل", "root أ م ل occurs in the Qur'an; أمل is a normal Arabic noun", "high", "Amal ('hope'). The source record left origin and gender blank."),
 "amala": ("أملة", "املہ", None, "अमला", "امله", "hope", "Arabic", "Female", "أ م ل", "not established", "medium", "Feminine form from أمل ('hope'). The source record's gloss 'Young girl' is unsupported."),
 "amalia": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'God's bounty' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amalin": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Young, Tender' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amalina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Hope, Trust' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amam": ("أمام", "امام", None, "अमाम", "امام", "mother_mothers", "Arabic", "Female", "أ م م", "not established", "low", "The source record's gloss 'Mother of Mothers' could not be matched to a Tier-A/B lexical source. The form resembles إمام ('leader'). The identification is uncertain."),
 "amama": ("أمامة", "امامہ", None, "अमामा", "امامه", "mother", "Arabic", "Female", "أ م م", "not established", "medium", "Amāma ('a woman who leads'). The source record's gloss 'Mother' is an approximation."),
 "aman": ("أمان", "امن", None, "अमन", "امن", "peace", "Arabic", "Male", "أ م ن", "root أ م ن occurs in the Qur'an; أمان is a normal Arabic noun", "high", "Amān ('peace, safety, trust')."),
 "amana": ("أمانة", "امانہ", None, "अमाना", "امانه", "faith", "Arabic", "Female", "أ م ن", "root أ م ن occurs in the Qur'an; أمانة is a normal Arabic noun", "high", "Amāna ('trust, faithfulness')."),
 "amanah": ("أمانة", "امانہ", None, "अमाना", "امانه", "faith", "Arabic", "Female", "أ م ن", "root أ م ن occurs in the Qur'an; أمانة is a normal Arabic noun", "high", "Variant romanization of أمانة."),
 "amaneh": ("أمانة", "امانہ", None, "अमानेह", "امانه", "hope_trust", "Arabic", "Female", "أ م ن", "not established", "medium", "Variant romanization of أمانة. The source record's gloss 'Hope, Trust' is a reasonable rendering."),
 "amani": ("أماني", "امانی", None, "अमानी", "اماني", "wishes", "Arabic", "Unisex", "أ م ن", "root أ م ن occurs in the Qur'an; أماني is a normal Arabic plural", "high", "Amānī, plural of أمنية ('wish'). The source record left origin and gender blank."),
 "amanina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Trust, faith, belief' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amar": ("عمار", "عمار", None, "अम्मार", "عمار", "builder", "Arabic", "Male", "ع م ر", "not established", "high", "ʿAmmār ('builder'). The source record's gloss 'Eternal, Immortal' is unsupported."),
 "amara": ("عمارة", "عمارہ", None, "अमारा", "عماره", "long_life", "Arabic", "Female", "ع م ر", "not established", "low", "The source record's gloss 'Long life and prosperity' could not be matched to a Tier-A/B lexical source. The form is related to عمر ('life, age'). The identification is uncertain."),
 "amarah": ("عمارة", "عمارہ", None, "अमारा", "عماره", "steadfast", "Arabic", "Female", "ع م ر", "not established", "low", "The source record's gloss 'She who is steadfast' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amarat": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Devoted, Loyal' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amarjeet": ("أمرجيت", "امر جیت", None, "अमरजीत", "امر جیت", "amarjeet", "Punjabi", "Male", None, "not established", "high", "Punjabi/Sikh Amarjīt, from Sanskrit अमर (amara, 'immortal') + जिति (jiti, 'victory') = 'eternal triumph'. The source record classified it as Arabic, which is incorrect."),
 "amas": ("أماس", "اماس", None, "अमास", "اماس", "gatherer", "Arabic", "Male", "أ م س", "not established", "low", "The source record's gloss 'Gatherer, Sustainer' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amat": ("أمة", "امت", None, "अमत", "امت", "servant", "Arabic", "Female", "أ م و", "not established", "medium", "Amah ('maidservant'). The source record's gloss 'Mother's love' is unsupported."),
 "amatul": ("أمة ال", "امۃ ال", None, "अमतुल", "امت ال", "servant", "Arabic", "Female", "أ م و", "not established", "medium", "First element of the compound amat al- ('maidservant of'), as in Amatullah. The source record's gloss 'Gift of Allah' is unsupported."),
 "amatus": ("أمة ال", "امۃ ال", None, "अमतुस", "امت ال", "servant", "Arabic", "Unisex", "أ م و", "not established", "low", "First element of the compound amat al-. The source record's gloss 'Loving' is unsupported."),
 "amaya": ("أمايا", "امایا", "آمایا", "अमाया", "امایا", "amaya", "Basque", "Female", None, "not established", "high", "Amaya is a Basque/Spanish name, from the Basque place name Amaya ('the end, the mother city'). The source record classified it as Arabic, which is incorrect."),
 "amazigh": ("أمازيغ", "امازیغ", "آمازیغ", "अमाज़ीघ", "امازیغ", "amazigh", "Berber", "Unisex", None, "not established", "high", "Amazigh (ⴰⵎⴰⵣⵉⵖ), the self-designation of the indigenous Berber peoples of North Africa, meaning 'free people'. The source record classified it as Arabic, which is incorrect."),
 "ambar": ("عنبر", "عنبر", "عنبر", "अंबर", "عنبر", "ambergris", "Arabic", "Female", "ع ن ب ر", "not established", "high", "ʿAnbar ('ambergris'), a fragrant substance used in perfumery; the source of English 'amber'."),
 "amber": ("عنبر", "عنبر", "عنبر", "अंबर", "عنبر", "ambergris", "Arabic", "Unisex", "ع ن ب ر", "not established", "high", "Variant romanization of عنبر. The source record's gloss 'Jewel, precious stone' is unsupported."),
 "ambreen": ("عنبرین", "عنبرین", "عنبرین", "अंबरीन", "عنبرین", "ambergris", "Arabic", "Female", "ع ن ب ر", "not established", "medium", "ʿAnbarīn, a Persian/Urdu derivative of عنبر ('ambergris'). The source record's gloss 'Moonlight' is unsupported."),
 "amdad": ("أمداد", "امداد", None, "अमदाद", "امداد", "helper", "Arabic", "Male", "م د د", "not established", "high", "Amdād, plural of مدد ('help, aid'). The source record's gloss 'Helper' is a reasonable rendering."),
 "ameed": ("عميد", "عمید", None, "अमीद", "عميد", "honor_trust", "Arabic", "Male", "ع م د", "not established", "medium", "ʿAmīd ('chief, dean, pillar of a group'). The source record's gloss 'Honor, Trustworthiness' is an approximation."),
 "ameel": ("أميل", "امیل", None, "अमील", "اميل", "river", "Arabic", "Male", "أ م ل", "not established", "low", "The source record's gloss 'River' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "ameen": ("أمين", "امین", None, "अमीन", "امين", "trustworthy", "Arabic", "Male", "أ م ن", "root أ م ن occurs in the Qur'an; أمين is a normal Arabic adjective", "high", "Amīn ('trustworthy, honest')."),
 "ameena": ("أمينة", "امینہ", None, "अमीना", "امينه", "trustworthy_f", "Arabic", "Female", "أ م ن", "not established", "high", "Feminine of أمين."),
 "ameenah": ("أمينة", "امینہ", None, "अमीना", "امينه", "trustworthy_f", "Arabic", "Female", "أ م ن", "not established", "high", "Variant romanization of أمينة."),
 "ameenat": ("أمينة", "امینت", None, "अमीनत", "امينت", "trustworthy_f", "Arabic", "Female", "أ م ن", "not established", "medium", "Variant romanization of أمينة."),
 "ameer": ("أمير", "امیر", None, "अमीर", "امير", "prince", "Arabic", "Male", "أ م ر", "not established", "high", "Amīr ('prince, commander')."),
 "ameera": ("أميرة", "امیرہ", None, "अमीरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Amīra ('princess, ruler')."),
 "ameerah": ("أميرة", "امیرہ", None, "अमीरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Variant romanization of أميرة."),
 "ameerat": ("أميرة", "امیرت", None, "अमीरत", "اميرت", "princess", "Arabic", "Female", "أ م ر", "not established", "medium", "Variant romanization of أميرة."),
 "amel": ("أمل", "امل", None, "अमेल", "امل", "hope", "Arabic", "Female", "أ م ل", "root أ م ل occurs in the Qur'an; أمل is a normal Arabic noun", "high", "Amal ('hope'). The source record's gloss 'Hope, Trust' is a reasonable rendering."),
 "amelia": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Industrious one' could not be matched to a Tier-A/B lexical source and no script form was supplied. Amelia is a Germanic/Latin name, not Arabic. No gloss is asserted."),
 "amena": ("أمينة", "امینہ", None, "अमेना", "امينه", "tranquility", "Arabic", "Female", "أ م ن", "not established", "medium", "Related to أمان ('safety, peace'). The source record's gloss 'Tranquility, Serenity' is a reasonable rendering."),
 "amer": ("عامر", "عامر", None, "आमिर", "عامر", "eternal", "Arabic", "Male", "ع م ر", "not established", "medium", "ʿĀmir ('inhabited, flourishing, populous'). The source record's gloss 'Eternal, Immortal' is unsupported."),
 "amial": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Gentle, Kind' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amid": ("عميد", "عمید", None, "अमीद", "عميد", "present", "Arabic", "Unisex", "ع م د", "not established", "low", "The source record's gloss 'Present' could not be matched to a Tier-A/B lexical source. The form resembles عميد ('chief'). The identification is uncertain."),
 "amil": ("عامل", "عامل", None, "आमिल", "عامل", "servant", "Arabic", "Male", "ع م ل", "not established", "medium", "ʿĀmil ('worker, agent, doer'). The source record's gloss 'Servant' is an approximation."),
 "amila": ("عاملة", "عاملہ", None, "आमिला", "عامله", "work", "Arabic", "Female", "ع م ل", "not established", "medium", "Feminine of عامل ('worker'). The source record's gloss 'Sweetness' is unsupported."),
 "amilah": ("عاملة", "عاملہ", None, "आमिला", "عامله", "work", "Arabic", "Female", "ع م ل", "not established", "medium", "Variant romanization of عاملة. The source record's gloss 'Work, labor, industrious' is a reasonable rendering."),
 "amima": ("أميمة", "امیمہ", None, "अमीमा", "اميمه", "mother_believers", "Arabic", "Female", "أ م م", "not established", "low", "The source record's gloss 'Mother of the believers' could not be matched to a Tier-A/B lexical source. The form resembles أميمة (diminutive of أمة). The identification is uncertain."),
 "amin": ("أمين", "امین", None, "अमीन", "امين", "trustworthy", "Arabic", "Male", "أ م ن", "root أ م ن occurs in the Qur'an; أمين is a normal Arabic adjective", "high", "Amīn ('trustworthy, honest')."),
 "amina": ("أمينة", "امینہ", None, "अमीना", "امينه", "trustworthy_f", "Arabic", "Female", "أ م ن", "not established", "high", "Feminine of أمين. The source record left origin and gender blank."),
 "aminah": ("أمينة", "امینہ", None, "अमीना", "امينه", "faithful", "Arabic", "Female", "أ م ن", "not established", "high", "Feminine of أمين; also the name of Āmina bint Wahb, mother of the Prophet Muhammad."),
 "aminat": ("أمينة", "امینت", None, "अमीनत", "امينت", "faithful", "Arabic", "Female", "أ م ن", "not established", "medium", "Variant romanization of أمينة."),
 "aminatou": ("أمينة", "امینتو", None, "अमीनातू", "اميناتو", "reliable", "Arabic", "Female", "أ م ن", "not established", "medium", "West African (Fulani/Wolof) form of أمينة."),
 "amine": ("أمينة", "امینہ", None, "अमीने", "امينه", "tranquility_love", "Arabic", "Female", "أ م ن", "not established", "medium", "Variant romanization of أمينة."),
 "amineh": ("أمينة", "امینہ", None, "अमीनेह", "امينه", "tranquility_hope", "Arabic", "Female", "أ م ن", "not established", "medium", "Variant romanization of أمينة."),
 "aminu": ("أمين", "امینو", None, "अमीनु", "امينو", "reliable", "Arabic", "Male", "أ م ن", "not established", "medium", "West African (Hausa/Fulani) form of أمين."),
 "aminul": ("أمين ال", "امین ال", None, "अमीनुल", "امين ال", "reliable", "Arabic", "Male", "أ م ن", "not established", "medium", "First element of the compound amīn al- ('trusted one of'), as in Aminul Islam."),
 "aminur": ("أمين ال", "امین ال", None, "अमीनुर", "امين ال", "trustworthy", "Arabic", "Male", "أ م ن", "not established", "medium", "First element of the compound amīn al-."),
 "amir": ("أمير", "امیر", None, "अमीर", "امير", "prince", "Arabic", "Male", "أ م ر", "not established", "high", "Amīr ('prince, leader, commander')."),
 "amira": ("أميرة", "امیرہ", None, "अमीरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Amīra ('princess'). The source record left origin and gender blank."),
 "amiraa": ("أميرة", "امیرہ", None, "अमीरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Variant romanization of أميرة."),
 "amirah": ("أميرة", "امیرہ", None, "अमीरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Variant romanization of أميرة."),
 "amirani": ("أميراني", "امیرانی", None, "अमीरानी", "اميراني", "prince", "Arabic", "Male", "أ م ر", "not established", "low", "The source record's gloss 'Prince, Commander' could not be matched to a Tier-A/B lexical source. The form is a derived compound. The identification is uncertain."),
 "amiri": ("أميري", "امیری", None, "अमीरी", "اميري", "prince", "Arabic", "Unisex", "أ م ر", "not established", "medium", "Nisba adjective from أمير ('prince')."),
 "amirul": ("أمير ال", "امیر ال", None, "अमीरुल", "امير ال", "prince", "Arabic", "Male", "أ م ر", "not established", "medium", "First element of the compound amīr al- ('commander of'), as in Amirul Momineen."),
 "amirun": ("أمير", "امیرون", None, "अमीरुन", "اميرون", "prince", "Arabic", "Male", "أ م ر", "not established", "low", "The source record's gloss 'Commander, Prince' could not be matched to a Tier-A/B lexical source. The form resembles a plural. The identification is uncertain."),
 "amjaad": ("أمجاد", "امجاد", None, "अमजाद", "امجاد", "noble_exalted", "Arabic", "Male", "م ج د", "not established", "medium", "Related to مجد ('glory, honour'). The source record's gloss 'Trustworthy' is unsupported."),
 "amjad": ("أمجد", "امجد", None, "अमजद", "امجد", "noble_exalted", "Arabic", "Male", "م ج د", "not established", "high", "Amjad, elative of مجيد ('glorious, noble')."),
 "amjed": ("أمجد", "امجد", None, "अमजद", "امجد", "noble_exalted", "Arabic", "Male", "م ج د", "not established", "high", "Variant romanization of أمجد."),
 "ammaar": ("عمار", "عمار", None, "अम्मार", "عمار", "builder", "Arabic", "Male", "ع م ر", "not established", "high", "ʿAmmār ('builder'), also the name of ʿAmmār ibn Yāsir, a companion of the Prophet. The source record's gloss 'One who is patient' is unsupported."),
 "ammaarah": ("عمارة", "عمارہ", None, "अम्मारा", "عماره", "long_lived", "Arabic", "Female", "ع م ر", "not established", "low", "The source record's gloss 'Long-lived, Prosperous' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amman": ("عمان", "عمان", None, "अम्मान", "عمان", "mountain", "Arabic", "Unisex", "ع م ن", "not established", "low", "The source record's gloss 'Mountain or high place' could not be matched to a Tier-A/B lexical source. The form is also the name of the Jordanian capital. The identification is uncertain."),
 "ammani": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Trustworthy and faithful' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "ammar": ("عمار", "عمار", None, "अम्मार", "عمار", "builder", "Arabic", "Male", "ع م ر", "not established", "high", "Variant romanization of عمار. The source record's gloss 'Long-lived, Pious, Builder' conflates several senses."),
 "ammarah": ("عمارة", "عمارہ", None, "अम्मारा", "عماره", "builder", "Arabic", "Unisex", "ع م ر", "not established", "medium", "ʿAmāra ('building, structure'). The source record's gloss 'Prosperous, Builder' is a reasonable rendering."),
 "amna": ("آمنة", "آمنہ", None, "आमना", "آمنه", "safe_peaceful", "Arabic", "Female", "أ م ن", "not established", "high", "Āmina ('safe, peaceful'); also the name of Āmina bint Wahb, mother of the Prophet Muhammad."),
 "amnah": ("آمنة", "آمنہ", None, "आमना", "آمنه", "safe_secure", "Arabic", "Female", "أ م ن", "not established", "high", "Variant romanization of آمنة."),
 "amnan": ("أمنان", "امنان", None, "अमनान", "امنان", "protection", "Arabic", "Female", "أ م ن", "not established", "low", "The source record's gloss 'Protection, Safety' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amr": ("عمرو", "عمرو", None, "अम्र", "عمرو", "command", "Arabic", "Male", "ع م ر", "not established", "high", "ʿAmr, a common Arabic personal name; also ʿamr ('command, order'). The source record's gloss 'Command, Order, Strength' is a reasonable rendering."),
 "amra": ("عمرة", "عمرہ", None, "अमरा", "عمره", "mother_many", "Arabic", "Female", "ع م ر", "not established", "low", "The source record's gloss 'Mother of many' could not be matched to a Tier-A/B lexical source. The form is also عمرة ('the lesser pilgrimage'). The identification is uncertain."),
 "amrah": ("عمرة", "عمرہ", None, "अमरा", "عمره", "high_born", "Arabic", "Female", "ع م ر", "not established", "low", "The source record's gloss 'High-born, Exalted' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amran": ("عمران", "عمران", None, "इमरान", "عمران", "high_status", "Arabic", "Male", "ع م ر", "عمران occurs in the Qur'an (Sūrat Āl ʿImrān 3:33) as a personal name", "high", "ʿImrān, the father of Maryam in Islamic tradition; also the name of the third sura of the Qur'an."),
 "amreen": ("عمرین", "عمرین", None, "अमरीन", "عمرین", "sweet_smelling", "Arabic", "Female", "ع م ر", "not established", "low", "The source record's gloss 'Sweet smelling' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amri": ("عمري", "عمري", None, "अमरी", "عمري", "belonging_allah", "Arabic", "Male", "ع م ر", "not established", "low", "The source record's gloss 'Belonging to Allah' could not be matched to a Tier-A/B lexical source. The form is a nisba from عمر. The identification is uncertain."),
 "amrin": ("عمرین", "عمرین", None, "अमरीन", "عمرین", "protector", "Arabic", "Male", "ع م ر", "not established", "low", "The source record's gloss 'Protector' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "amrina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble, Precious' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amro": ("عمرو", "عمرو", None, "अम्रो", "عمرو", "brave_strong", "Arabic", "Male", "ع م ر", "not established", "medium", "Variant romanization of عمرو. The source record's gloss 'Brave, Strong' is unsupported."),
 "amru": ("عمرو", "عمرو", None, "अम्रु", "عمرو", "man_commander", "Arabic", "Male", "ع م ر", "not established", "medium", "Variant romanization of عمرو. The source record's gloss 'Man, Commander' is unsupported."),
 "amsal": ("أمثال", "امثال", None, "अमसल", "امثال", "proverbs", "Arabic", "Male", "م ث ل", "not established", "high", "Amsāl, plural of مَثَل ('proverb, parable, example'). The source record's gloss 'Dear one, loved one' is unsupported."),
 "amyrah": ("أميرة", "امیرہ", None, "अमीरा", "اميره", "most_exalted", "Arabic", "Female", "أ م ر", "not established", "medium", "Variant romanization of أميرة. The source record's gloss 'The Most Exalted' is an approximation."),
 "ana": ("أنا", "انا", None, "अना", "انا", "breath_life", "Arabic", "Female", "أ ن ا", "not established", "low", "The source record's gloss 'Breath, Life' could not be matched to a Tier-A/B lexical source. The form is also the Arabic pronoun 'I'. The identification is uncertain."),
 "anaam": ("أنعام", "انعام", None, "अनआम", "انعام", "grace_honor", "Arabic", "Unisex", "ن ع م", "root ن ع م occurs in the Qur'an; أنعام is a normal Arabic noun", "medium", "Anʿām ('livestock, cattle'); also inʿām ('bestowal of favour'). The source record's gloss 'Grace, Honor' is an approximation."),
 "anaan": ("أنان", "انان", None, "अनान", "انان", "nurse_supporter", "Arabic", "Female", "أ ن ن", "not established", "low", "The source record's gloss 'Nurse, supporter' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "anaas": ("أناس", "اناس", None, "अनास", "اناس", "good_news", "Arabic", "Male", "أ ن س", "not established", "low", "The source record's gloss 'Giver of good news' could not be matched to a Tier-A/B lexical source. The form resembles أنس ('sociability'). The identification is uncertain."),
 "anabia": ("أنبياء", "انبیا", None, "अनबिया", "انبیا", "anabia", "Arabic", "Female", "ن ب أ", "أنبياء occurs in the Qur'an as the plural of نبي ('prophet')", "medium", "Anbiyāʾ, plural of nabī ('prophet'). As a modern given name it is used in South Asian Muslim communities. The source record's gloss 'From heaven' is unsupported."),
}
