# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 34 (kadira..keyvan).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": kadira -> كديرة (should be قديرة);
   kadri -> كدري (should be قدري); kadriya -> كدرية (should be قدرية);
   kaim -> كَايِم (should be قائم); kaina -> كاينا (should be كائنة);
   kair -> كير (should be خير); kaiser -> كَيْسَر (should be قيصر);
   kakuli -> "Ali" (junk); kalbi -> كَلْبي (should be قلبي);
   kaleela -> كليلا (should be كليلة); kalsoom -> كَلْسُوم (should be كلثوم);
   kalsum -> "Kalsum" (Latin); kamari -> كماري (should be قمري);
   kamaria -> كمارية (should be قمرية); kambiz -> كامبز (should be کامبیز);
   kamir -> كَمير (should be كمير); kaniz -> عائشة (a different name entirely);
   kanwal -> كنول (should be کنول); kanza -> "كنza" (mixed Latin);
   karawan -> كاروان (should be کاروان); kareen -> كارين (should be كارين, ok);
   kariman -> كريمًا ن (broken, should be كريمان); kas -> كاس (should be كأس);
   kasam -> كسام (should be قسم); kaseem -> كاسم (should be قاسم);
   kashmala -> كشمالا (should be كشمالا, ok); kausar/kauser -> كوسر (should be
   كوثر); kawah -> "كawah" (mixed Latin); kawtar -> كوتر (should be كوثر);
   kayan -> "kayan" (Latin); kaynat -> كَيْناَت (broken, should be كائنات);
   kayvan -> كَيْوَاَن (broken, should be کیوان); kazhal -> غزلة (should be
   غزالة); kazi -> كاظم (should be قاضي); kedar -> كيدار (should be كيدار, ok);
   kedma -> قدمة (should be قدمة); keivan -> كيفان (should be کیوان);
   keyvan -> كيوان (should be کیوان).
 * DEGARBLED / WRONG glosses: kadira 'Eternal, Everlasting' (should be 'capable,
   powerful (fem)'); kadri 'Providence, Generosity' (should be 'of destiny');
   kadriya "God's Grace" (should be 'of destiny (fem)'); kahil 'Friend of God'
   (should be 'mature, adult'); kahlil 'Friend of Allah' (should be 'friend');
   kaif 'Blessed, fortunate' (should be 'how; pleasure'); kaim 'Born from the
   ashes' (should be 'standing, resolute'); kaina 'Grace, Beauty' (should be
   'being, existing'); kair 'Pure, Clear' (should be 'goodness'); kais 'Raised,
   alive' (should be the name Qays); kaiser 'emperor, leader, ruler' (correct);
   kala 'Beautiful and elegant' (unsupported); kalan 'Slim, Beautiful'
   (unsupported); kalbi 'Friend of Allah' (should be 'of the heart'); kaleel
   'Messenger, Speaker' (should be 'weary; friend'); kaleela 'Little One,
   Beautiful One' (should be 'weary (fem)'); kalil 'Wise, Clever' (should be
   'weary'); kalima 'Statement of faith' (should be 'word'); kalsom 'Full of
   Flesh, Healthy, Rosy-Cheeked' (should be the name Kulthum); kalsoom
   'Praiseworthy, Laudable' (should be the name Kulthum); kalsum "Moon's light"
   (should be the name Kulthum); kaltham 'Tongue, Speech' (should be the name
   Kulthum); kamali 'Perfect, Beautiful' (should be nisba of Kamal); kaman
   "Kaman means 'the earth' or 'land'" (should be 'bow'); kamari 'Moonlike'
   (should be 'lunar'); kamaria 'Moonlight' (should be 'lunar (fem)'); kambiz
   'Intelligent, Wise' (should be the Persian name Kambiz); kamir 'Little Moon'
   (unsupported); kamna 'Loved One' (unsupported); kaneez 'Lady, slave of Allah'
   (should be 'maidservant'); kani 'Strong, Firm' (should be 'spring', Kurdish);
   kaniz 'Grace, beauty, or elegance' (should be 'maidservant'); kanwal
   'Elegance, Grace' (should be 'lotus'); kanza 'Treasure' (correct); karah
   'Mountain' (unsupported); karamat 'Miracles of God' (should be 'miracle,
   dignity'); kareema 'Tender and compassionate' (should be 'generous (fem)');
   kareen 'Pure, Radiant' (unsupported); kariman 'Graceful, Honored'
   (unsupported); karrar 'Noble and Brave Warrior' (should be 'one who returns
   to attack'); kas 'Helper, Supporter' (should be 'cup'); kasam 'Promise,
   Commitment' (should be 'oath'); kaseem 'Bringer of good news' (should be
   'divider'); kashan 'City of Craftsmen' (should be the Persian city Kashan);
   kashish 'Intense longing, yearning, or desire' (should be 'attraction');
   kashmala 'Moon' (unsupported); kashmir 'Jewel, Treasure' (should be the
   place name Kashmir); kasif 'Observer, Watcher' (should be 'revealer'); kasim
   'Just, equitable' (should be 'divider'); kasra 'Chest, fortress, strong'
   (should be 'a vowel mark'); kassab 'Cook, chef' (should be 'butcher'); kausar
   'Abundant Provision' (should be 'abundance'); kauser 'Grace' (should be
   'abundance'); kawah 'The Potter' (unsupported); kawsar 'Garden of Paradise'
   (should be 'abundance'); kawtar 'Generous Gift' (should be 'abundance');
   kayan 'Eternal, Everlasting' (should be 'being, entity'); kaynat 'The giver
   or distributor' (should be 'universe'); kayvan 'Mountain like' (should be
   the Persian name Kayvan); kaza 'Fortress, stronghold' (unsupported); kazhal
   'Unknown' (should be 'gazelle'); kazi 'helper, advisor, guide' (should be
   'judge'); kedar 'Descendant of Ishmael' (unsupported); kedma 'Gift, blessing'
   (unsupported); keivan 'Compassionate Friend' (should be the Persian name
   Keyvan); kelia 'Small hill' (unsupported); kenza 'Moon, Bright Star' (should
   be 'treasure'); keyan 'Sun' (should be 'being, entity'); keyvan 'Lord of the
   Mountain' (should be the Persian name Keyvan).
 * MISLABELLED ORIGIN: kambiz (Persian), kani (Kurdish), kanwal (Persian/Urdu),
   karawan (Persian), kashan (Persian), kayvan (Persian), keivan (Persian),
   keyvan (Persian), kareen (Western).
 * GENDER ERRORS: kadri, kafayat, kahlil, kaif, kalam, kalan, kalima, kameel,
   kamna, kani, karamat, karawan, kashaf, kashish, kashmir, kasra, kausar,
   kawkab, kawsar, kazi, keyan, keyvan were labelled female or unisex where
   documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: kamilah, kamran, karam, kareem, karima, kashif,
   kauthar, kawthar (8-key stubs); kakuli, kala, kalan, kamir, kamna, karah,
   kashmala, kawah, kaza, kedar, kedma, kelia.
 * DUPLICATE CLUSTERS: kadira/kadriya; kadri/kadriya; kafeel/kafil;
   kafi/kafeel; kahlil/kaleel/kalil; kaleem/kalim; kalsom/kalsoom/kalsum/
   kaltham; kamal/kamel/kameel; kamali/kamal; kamil/kameel/kamel;
   kamila/kamilah; kamari/kamaria; karam/kareem/karim; kareema/karima;
   kausar/kauser/kawsar/kawtar/kauthar/kawthar; kayan/keyan;
   kayvan/keivan/keyvan; kazi/kazim; kenza/kanza.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated33 import GLOSSES as _G33

GLOSSES = dict(_G33)
GLOSSES.update({
    "qadira": {"en": "Capable, powerful (feminine)", "ur": "قدیرہ، قادر (مؤنث)", "fa": "قدیره، قادر (مؤنث)", "hi": "क़ादिरा, सक्षम (स्त्री)", "ps": "قدیره، قادره", "ar": "القَدِيرَة، القادرة، المقتدرة"},
    "qadri": {"en": "Qadri; of destiny, belonging to Qadr", "ur": "قدری، قدر سے منسوب", "fa": "قدری، منسوب به قدر", "hi": "क़दरी, क़दर से", "ps": "قدري، د قدر اړوند", "ar": "القَدْرِيّ، منسوب إلى القدر"},
    "qadriyya": {"en": "Qadriyya; of destiny (feminine)", "ur": "قدریہ، قدر سے منسوب (مؤنث)", "fa": "قدریه، منسوب به قدر (مؤنث)", "hi": "क़दरिया, क़दर से (स्त्री)", "ps": "قدریه، د قدر اړوند", "ar": "القَدْرِيَّة، منسوبة إلى القدر"},
    "sufficiency": {"en": "Sufficiency, adequacy, enough", "ur": "کفایت، بساطت، کافی ہونا", "fa": "کفایت، بسندگی، کافی بودن", "hi": "पर्याप्तता, किफ़ायत", "ps": "کفایت، بسنه، پوره والی", "ar": "الكفاية، الكفاء، السداد"},
    "trustee": {"en": "Trustee, guarantor, sponsor", "ur": "کفیل، ضامن، ذمہ دار", "fa": "کفیل، ضامن، سرپرست", "hi": "ज़मानतदार, कफ़ील, संरक्षक", "ps": "کفیل، ضامن، پالونکی", "ar": "الكفيل، الضامن، الحميل"},
    "sufficient": {"en": "Sufficient, adequate, complete", "ur": "کافی، بس، پورا", "fa": "کافی، بسنده، تمام", "hi": "काफ़ी, पर्याप्त, पूर्ण", "ps": "کافي، بس، پوره", "ar": "الكافي، الحسب، المقنع"},
    "protector_kafil": {"en": "Protector, guardian, sponsor", "ur": "کافل، محافظ، سرپرست", "fa": "کافل، نگهبان، سرپرست", "hi": "संरक्षक, काफ़िल, पालनहार", "ps": "ساتونکی، کافل، پالونکی", "ar": "الكافل، الحافظ، الراعي"},
    "mature": {"en": "Mature, adult, full-grown", "ur": "کاہل، بالغ، پختہ", "fa": "کاهل، بالغ، رسیده", "hi": "वयस्क, परिपक्व, काहिल", "ps": "بالغ، پوخ، کاهل", "ar": "الكاهل، البالغ، الراشد"},
    "friend": {"en": "Friend, intimate companion", "ur": "خلیل، دوست، رفیق", "fa": "خلیل، دوست، یار", "hi": "मित्र, ख़लील, दोस्त", "ps": "ملګری، خلیل، دوست", "ar": "الخليل، الصديق، الرفيق"},
    "pleasure": {"en": "Pleasure, delight; 'how' (interrogative)", "ur": "کیف، لطف، مزہ", "fa": "کیف، لذت، خوشی", "hi": "आनंद, मज़ा, कैफ़", "ps": "کیف، خوند، خوښي", "ar": "الكيف، اللذة، المتعة"},
    "qaim": {"en": "Standing, resolute, upright", "ur": "قائم، کھڑا، ثابت قدم", "fa": "قائم، ایستاده، استوار", "hi": "क़ायम, खड़ा, दृढ़", "ps": "قائم، ولاړ، ټینګ", "ar": "القائم، الثابت، المستقيم"},
    "kaina": {"en": "Being, existing (feminine)", "ur": "کائنہ، موجود", "fa": "کائنه، موجود", "hi": "काइना, विद्यमान", "ps": "کائنه، موجوده", "ar": "الكائنة، الموجودة"},
    "universe": {"en": "Universe, creation, beings", "ur": "کائنات، کائنات، تخلیق", "fa": "کائنات، هستی، آفرینش", "hi": "ब्रह्मांड, कायनात, सृष्टि", "ps": "کائنات، هستي، پیداښت", "ar": "الكائنات، الكون، الخلق"},
    "goodness": {"en": "Goodness, welfare, charity", "ur": "خیر، بھلائی، نیکی", "fa": "خیر، نیکی، خوبی", "hi": "भलाई, ख़ैर, नेकी", "ps": "خیر، ښېګڼه، نیکي", "ar": "الخير، البر، النفع"},
    "qays": {"en": "Qays; a male given name", "ur": "قیس (مردانہ نام)", "fa": "قیس (نام مردانه)", "hi": "क़ैस (पुरुष नाम)", "ps": "قیس (نر نوم)", "ar": "قَيْس (اسم علم مذكر)"},
    "caesar": {"en": "Caesar, emperor, ruler", "ur": "قیصر، بادشاہ، شہنشاہ", "fa": "قیصر، امپراتور، پادشاه", "hi": "क़ैसर, सम्राट, शासक", "ps": "قیصر، امپراتور، پاچا", "ar": "القيصر، الإمبراطور، الملك"},
    "kakuli": {"en": "Kakuli; a given name", "ur": "کاکلی (نام)", "fa": "کاکلی (نام)", "hi": "काकुली (नाम)", "ps": "کاکلي (نوم)", "ar": "كَاكُلِي (اسم علم)"},
    "kala": {"en": "Kala; a female given name", "ur": "کالا (زنانہ نام)", "fa": "کالا (نام زنانه)", "hi": "काला (स्त्री नाम)", "ps": "کالا (ښځينه نوم)", "ar": "كَالَا (اسم علم مؤنث)"},
    "speech": {"en": "Speech, word, discourse", "ur": "کلام، بات، گفتگو", "fa": "کلام، سخن، گفتار", "hi": "कलाम, वाणी, बात", "ps": "کلام، وینا، خبرې", "ar": "الكلام، القول، الحديث"},
    "kalan": {"en": "Kalan; a given name", "ur": "کالان (نام)", "fa": "کالان (نام)", "hi": "कालान (नाम)", "ps": "کالان (نوم)", "ar": "كَالَان (اسم علم)"},
    "qalbi": {"en": "Of the heart, heartfelt", "ur": "قلبی، دل سے", "fa": "قلبی، از دل", "hi": "हार्दिक, क़ल्बी, दिल से", "ps": "زړه له، قلبي", "ar": "القلبي، من القلب"},
    "kalil": {"en": "Weary, tired; (also) friend", "ur": "کلیل، تھکا، دوست", "fa": "کلیل، خسته، دوست", "hi": "कलील, थका, मित्र", "ps": "کلیل، ستړی، ملګری", "ar": "الكليل، المتعب، الصديق"},
    "kalila": {"en": "Kalila; weary (feminine)", "ur": "کلیلہ، تھکی (مؤنث)", "fa": "کلیله، خسته (مؤنث)", "hi": "कलीला, थकी (स्त्री)", "ps": "کلیله، ستړې", "ar": "الكَلِيلَة، المتعبة"},
    "kalim": {"en": "Speaker; one who is spoken to", "ur": "کلیم، بولنے والا، ہم کلام", "fa": "کلیم، سخنگو، همسخن", "hi": "कलीम, वक्ता, संबोधित", "ps": "کلیم، ویناوال، همخبرې", "ar": "الكليم، المتكلم، المُكلَّم"},
    "word": {"en": "Word, utterance", "ur": "کلمہ، لفظ، بات", "fa": "کلمه، واژه، سخن", "hi": "शब्द, कलिमा, लफ़्ज़", "ps": "کلمه، کلمه، خبره", "ar": "الكلمة، اللفظ، القول"},
    "kulthum": {"en": "Kulthum; a female given name", "ur": "کلثوم (زنانہ نام)", "fa": "کلثوم (نام زنانه)", "hi": "कुलसूम (स्त्री नाम)", "ps": "کلثوم (ښځينه نوم)", "ar": "كُلْثُوم (اسم علم مؤنث)"},
    "perfection": {"en": "Perfection, completeness, maturity", "ur": "کمال، تکمیل، پختگی", "fa": "کمال، تمامیت، بلوغ", "hi": "पूर्णता, कमाल, परिपूर्णता", "ps": "کمال، بشپړتيا، پوخوالی", "ar": "الكمال، التمام، النضج"},
    "kamala": {"en": "Kamala; perfection (feminine)", "ur": "کمالہ، کمال (مؤنث)", "fa": "کماله، کمال (مؤنث)", "hi": "कमाला, पूर्णता (स्त्री)", "ps": "کماله، کمال", "ar": "الكَمَالَة، الكمال (مؤنث)"},
    "kamali": {"en": "Kamali; of Kamal, belonging to Kamal", "ur": "کمالی، کمال سے منسوب", "fa": "کمالی، منسوب به کمال", "hi": "कमाली, कमाल से", "ps": "کمالي، د کمال اړوند", "ar": "الكَمَالِيّ، منسوب إلى الكمال"},
    "bow": {"en": "Bow (weapon); arch", "ur": "کمان، دھنک", "fa": "کمان، قوس", "hi": "धनुष, कमान", "ps": "کمان، ليندۍ", "ar": "القوس، الكمان"},
    "qamari": {"en": "Lunar, of the moon", "ur": "قمری، چاند سے", "fa": "قمری، ماهی", "hi": "चंद्र, क़मरी", "ps": "قمري، سپوږميز", "ar": "القمري، من القمر"},
    "qamariyya": {"en": "Lunar, of the moon (feminine)", "ur": "قمریہ، چاند سے (مؤنث)", "fa": "قمریه، ماهی (مؤنث)", "hi": "क़मरिया, चंद्र (स्त्री)", "ps": "قمريه، سپوږميزه", "ar": "القَمَرِيَّة، من القمر"},
    "kambiz": {"en": "Kambiz; a Persian male given name", "ur": "کامبیز (فارسی نام)", "fa": "کامبیز (نام مردانه)", "hi": "काम्बीज़ (फ़ारसी नाम)", "ps": "کامبیز (فارسي نوم)", "ar": "كامبيز (اسم علم مذكر فارسي)"},
    "kamir": {"en": "Kamir; a male given name", "ur": "کمیر (مردانہ نام)", "fa": "کمیر (نام مردانه)", "hi": "कमीर (पुरुष नाम)", "ps": "کمیر (نر نوم)", "ar": "كَمِير (اسم علم مذكر)"},
    "kamna": {"en": "Kamna; a given name", "ur": "کمنہ (نام)", "fa": "کمنه (نام)", "hi": "कमना (नाम)", "ps": "کمنه (نوم)", "ar": "كَمْنَة (اسم علم)"},
    "kamran": {"en": "Kamran; prosperous, fortunate (Persian)", "ur": "کامران، خوش نصیب", "fa": "کامران، نیکبخت", "hi": "कामरान, भाग्यशाली", "ps": "کامران، نیکمرغه", "ar": "كامران، المحظوظ (فارسي)"},
    "maidservant": {"en": "Maidservant, female servant", "ur": "کنیز، لونڈی، خادمہ", "fa": "کنیز، خدمتگار (زن)", "hi": "दासी, कनीज़, सेविका", "ps": "کنیز، مېرمنه، خدمتګاره", "ar": "الكنيز، الأمة، الخادمة"},
    "kani": {"en": "Kani; spring, water source (Kurdish)", "ur": "کانی، چشمہ (کردی)", "fa": "کانی، چشمه (کردی)", "hi": "कानी, स्रोत (कुर्दी)", "ps": "کاني، چینه (کردي)", "ar": "كاني، النبع (كردية)"},
    "lotus": {"en": "Lotus, water lily (Persian/Urdu)", "ur": "کنول، نیلوفر", "fa": "نیلوفر، لاله آبی", "hi": "कमल, कनवल", "ps": "کنول، نیلوفر", "ar": "الكنول، النيلوفر (فارسي/أردو)"},
    "treasure": {"en": "Treasure, hoard", "ur": "کنز، خزانہ", "fa": "کنز، گنج", "hi": "ख़ज़ाना, कंज़", "ps": "کنز، خزانه", "ar": "الكنز، الذخيرة"},
    "karah": {"en": "Karah; a female given name", "ur": "کراہ (زنانہ نام)", "fa": "کراه (نام زنانه)", "hi": "कारा (स्त्री नाम)", "ps": "کراه (ښځينه نوم)", "ar": "كَرَاه (اسم علم مؤنث)"},
    "generosity_karam": {"en": "Generosity, bounty, nobility", "ur": "کرم، سخاوت، بزرگی", "fa": "کرم، بخشش، بزرگواری", "hi": "उदारता, करम, दानशीलता", "ps": "کرم، سخاوت، لویي", "ar": "الكرم، الجود، السخاء"},
    "miracle": {"en": "Miracle, dignity, honor", "ur": "کرامت، معجزہ، عزت", "fa": "کرامت، معجزه، بزرگواری", "hi": "करामत, चमत्कार, गरिमा", "ps": "کرامت، معجزه، عزت", "ar": "الكرامة، المعجزة، الشرف"},
    "caravan": {"en": "Caravan (Persian)", "ur": "کارواں، قافلہ", "fa": "کاروان، قافله", "hi": "काफ़िला, कारवाँ", "ps": "کاروان، قافله", "ar": "الكاروان، القافلة (فارسي)"},
    "karim": {"en": "Noble, generous, kind", "ur": "کریم، سخی، بزرگ", "fa": "کریم، بخشنده، بزرگوار", "hi": "करीम, उदार, दयालु", "ps": "کریم، سخي، لوی", "ar": "الكريم، الجواد، الشريف"},
    "karima": {"en": "Noble, generous (feminine)", "ur": "کریمہ، سخی (مؤنث)", "fa": "کریمه، بخشنده (مؤنث)", "hi": "करीमा, उदार (स्त्री)", "ps": "کریمه، سخي", "ar": "الكريمة، الجوادة، الشريفة"},
    "kareen": {"en": "Kareen; a female given name", "ur": "کارین (زنانہ نام)", "fa": "کارین (نام زنانه)", "hi": "करीन (स्त्री नाम)", "ps": "کارین (ښځينه نوم)", "ar": "كَارِين (اسم علم مؤنث)"},
    "kariman": {"en": "Kariman; noble, generous (dual/plural)", "ur": "کریمان، سخی لوگ", "fa": "کریمان، بخشندگان", "hi": "करीमान, उदार लोग", "ps": "کریمان، سخي خلک", "ar": "الكريمان، الجوادان"},
    "karrar": {"en": "Karrar; one who returns to the attack", "ur": "کرار، بار بار حملہ کرنے والا", "fa": "کرار، بازگشتکننده به نبرد", "hi": "कर्रार, बार-बार आक्रमण करने वाला", "ps": "کرار، بیا برید کوونکی", "ar": "الكَرَّار، العائد إلى القتال"},
    "cup": {"en": "Cup, goblet", "ur": "کاس، جام، پیالہ", "fa": "کاس، جام، پیاله", "hi": "प्याला, कास, जाम", "ps": "کاس، جام، پياله", "ar": "الكأس، الجام، القدح"},
    "oath": {"en": "Oath, vow, sworn pledge", "ur": "قسم، عہد، سوگند", "fa": "قسم، سوگند، پیمان", "hi": "क़सम, शपथ, सौगंध", "ps": "قسم، لوظ، سوګند", "ar": "القسم، اليمين، العهد"},
    "qasim": {"en": "Qasim; divider, distributor", "ur": "قاسم، تقسیم کرنے والا", "fa": "قاسم، تقسیمکننده", "hi": "क़ासिम, बाँटने वाला", "ps": "قاسم، وېشونکی", "ar": "القاسم، المقسّم، الموزّع"},
    "unveiling": {"en": "Unveiling, revelation, disclosure", "ur": "کشف، انکشاف، ظاہر ہونا", "fa": "کشف، آشکارسازی، مکاشفه", "hi": "अनावरण, कश्फ़, प्रकटीकरण", "ps": "کشف، ښکاره کېدنه", "ar": "الكشف، الإظهار، البيان"},
    "kashan": {"en": "Kashan; a city in Iran (Persian)", "ur": "کاشان، ایران کا شہر", "fa": "کاشان، شهری در ایران", "hi": "काशान, ईरान का शहर", "ps": "کاشان، د ایران ښار", "ar": "كاشان، مدينة في إيران (فارسي)"},
    "kashif": {"en": "Kashif; revealer, discoverer", "ur": "کاشف، ظاہر کرنے والا", "fa": "کاشف، آشکارکننده", "hi": "काशिफ़, प्रकट करने वाला", "ps": "کاشف، ښکاره کوونکی", "ar": "الكاشف، المظهر، المكتشف"},
    "attraction": {"en": "Attraction, pull, allurement", "ur": "کشش، جذب، کھنچاؤ", "fa": "کشش، جاذبه، ربایش", "hi": "आकर्षण, कशिश, खिंचाव", "ps": "کشش، جذب، ښکلا", "ar": "الكشش، الجذب، الانجذاب"},
    "kashmala": {"en": "Kashmala; a female given name", "ur": "کشملا (زنانہ نام)", "fa": "کشملا (نام زنانه)", "hi": "कश्मला (स्त्री नाम)", "ps": "کشملا (ښځينه نوم)", "ar": "كَشْمَلَا (اسم علم مؤنث)"},
    "kashmir": {"en": "Kashmir; a region name", "ur": "کشمیر، علاقے کا نام", "fa": "کشمیر، نام منطقه", "hi": "कश्मीर, क्षेत्र का नाम", "ps": "کشمیر، د سیمې نوم", "ar": "كشمير، اسم منطقة"},
    "kasra": {"en": "Kasra; the short 'i' vowel mark", "ur": "کسرہ، زیر", "fa": "کسره، زیر", "hi": "कसरा, ज़ेर", "ps": "کسره، زیر", "ar": "الكسرة، علامة الكسر"},
    "qassab": {"en": "Butcher", "ur": "قصاب، گوشت بیچنے والا", "fa": "قصاب، گوشتفروش", "hi": "क़स्साब, कसाई", "ps": "قصاب، غوښه پلورونکی", "ar": "القصّاب، الجزار"},
    "scribe": {"en": "Scribe, writer, copyist", "ur": "کاتب، لکھنے والا، منشی", "fa": "کاتب، نویسنده، دبیر", "hi": "कातिब, लेखक, मुंशी", "ps": "کاتب، لیکونکی، منشي", "ar": "الكاتب، المحرر، الناسخ"},
    "abundant": {"en": "Abundant, plentiful, numerous", "ur": "کثیر، بہت، زیادہ", "fa": "کثیر، فراوان، بسیار", "hi": "बहुत, कसीर, अधिक", "ps": "ډېر، کثیر، زيات", "ar": "الكثير، الوفير، الجمّ"},
    "kawthar": {"en": "Kawthar; abundance; a Qur'anic sura and river", "ur": "کوثر، کثرت، قرآن کی سورت", "fa": "کوثر، فراوانی، سوره قرآن", "hi": "कौसर, बहुतायत, क़ुरआन की सूरा", "ps": "کوثر، ډېروالی، د قرآن سوره", "ar": "الكوثر، الخير الكثير، سورة قرآنية"},
    "kawah": {"en": "Kawah; a given name", "ur": "کوہ (نام)", "fa": "کوه (نام)", "hi": "कवाह (नाम)", "ps": "کوه (نوم)", "ar": "كَوَة (اسم علم)"},
    "star": {"en": "Star, celestial body", "ur": "کوکب، ستارہ، سیارہ", "fa": "کوکب، ستاره، سیاره", "hi": "सितारा, कौकब, तारा", "ps": "ستوری، کوکب", "ar": "الكوكب، النجم، الجُرم السماوي"},
    "kayan": {"en": "Being, entity, existence (Persian)", "ur": "کیان، وجود، ہستی", "fa": "کیان، هستی، وجود", "hi": "कयान, अस्तित्व, हस्ती", "ps": "کیان، هستي، وجود", "ar": "الكيان، الوجود، الذات (فارسي)"},
    "kayvan": {"en": "Kayvan; Saturn (Persian)", "ur": "کیوان، زحل (فارسی)", "fa": "کیوان، سیاره زحل", "hi": "कैवान, शनि (फ़ारसी)", "ps": "کیوان، زحل (فارسي)", "ar": "كَيوان، زحل (فارسي)"},
    "kaza": {"en": "Kaza; a male given name", "ur": "کازا (مردانہ نام)", "fa": "کازا (نام مردانه)", "hi": "काज़ा (पुरुष नाम)", "ps": "کازا (نر نوم)", "ar": "كَازَا (اسم علم مذكر)"},
    "gazelle": {"en": "Gazelle", "ur": "غزال، ہرن", "fa": "غزال، آهو", "hi": "ग़ज़ल, हिरण", "ps": "غزال، هوسۍ", "ar": "الغزال، الظبي"},
    "qadi": {"en": "Judge, magistrate", "ur": "قاضی، منصف", "fa": "قاضی، داور", "hi": "क़ाज़ी, न्यायाधीश", "ps": "قاضي، قاضي", "ar": "القاضي، الحاكم، المنصف"},
    "kazim": {"en": "Kazim; one who restrains anger", "ur": "کاظم، غصہ پی جانے والا", "fa": "کاظم، فروبرنده خشم", "hi": "काज़िम, क्रोध रोकने वाला", "ps": "کاظم، غصه ځانته ساتونکی", "ar": "الكاظم، الكابت، الحليم"},
    "kedar": {"en": "Kedar; a male given name", "ur": "کیدار (مردانہ نام)", "fa": "کیدار (نام مردانه)", "hi": "केदार (पुरुष नाम)", "ps": "کیدار (نر نوم)", "ar": "كِيدَار (اسم علم مذكر)"},
    "kedma": {"en": "Kedma; a female given name", "ur": "قدمہ (زنانہ نام)", "fa": "قدمه (نام زنانه)", "hi": "क़ेदमा (स्त्री नाम)", "ps": "قدمه (ښځينه نوم)", "ar": "قِدْمَة (اسم علم مؤنث)"},
    "kelia": {"en": "Kelia; a female given name", "ur": "کیلیا (زنانہ نام)", "fa": "کیلیا (نام زنانه)", "hi": "केलिया (स्त्री नाम)", "ps": "کیلیا (ښځينه نوم)", "ar": "كِيلِيَا (اسم علم مؤنث)"},
    "perfect_f": {"en": "Perfect, complete (feminine)", "ur": "کاملہ، مکمل (مؤنث)", "fa": "کامله، کامل (مؤنث)", "hi": "कामिला, पूर्ण (स्त्री)", "ps": "کامله، بشپړه", "ar": "الكَامِلَة، التامة، الكاملة"},
})

CUR = {
 "kadira": ("قديرة", "قدیرہ", "قدیره", "क़ादिरा", "قدیره", "qadira", "Arabic", "Female",
            "Arabic root ق د ر (q-d-r); قَدِيرَة (Qadīra)", False, "high",
            "Kadira is Arabic قَدِيرَة (Qadīra) 'capable, powerful' (feminine), from the root ق د ر (q-d-r). CRITICAL SOURCE ERROR: the source gave كديرة (a different form) and glossed the name 'Eternal, Everlasting'; the correct form is قَدِيرَة. Same name as kadriya."),
 "kadri": ("قدري", "قدری", "قدری", "क़दरी", "قدري", "qadri", "Arabic", "Male",
           "Nisba of قَدْر; قَدْرِيّ (Qadriyy)", False, "medium",
           "Kadri is Arabic قَدْرِيّ (Qadriyy), the nisba of قَدْر (Qadr), meaning 'of destiny; belonging to destiny'. CRITICAL SOURCE ERROR: the source gave كدري (a different form) and glossed the name 'Providence, Generosity'; the correct form is قَدْرِيّ. Same name as kadriya."),
 "kadriya": ("قدرية", "قدریہ", "قدریه", "क़दरिया", "قدریه", "qadriyya", "Arabic", "Female",
             "Nisba of قَدْر; قَدْرِيَّة (Qadriyya)", False, "medium",
             "Kadriya is Arabic قَدْرِيَّة (Qadriyya), the feminine nisba of قَدْر (Qadr), meaning 'of destiny'. CRITICAL SOURCE ERROR: the source gave كدرية (a different form) and glossed the name \"God's Grace\"; the correct form is قَدْرِيَّة. Same name as kadri."),
 "kafayat": ("كفاية", "کفایت", "کفایت", "किफ़ायत", "کفایت", "sufficiency", "Arabic", "Female",
             "Arabic root ك ف ي (k-f-y); كِفَايَة (Kifāya)", False, "high",
             "Kafayat is Arabic كِفَايَة (Kifāya) 'sufficiency, adequacy, enough', from the root ك ف ي (k-f-y); the form كِفَايَت is the Persian/Urdu rendering. The source gloss 'Sufficient, Enough' is consistent."),
 "kafeel": ("كفيل", "کفیل", "کفیل", "कफ़ील", "کفیل", "trustee", "Arabic", "Male",
            "Arabic root ك ف ل (k-f-l); كَفِيل (Kafīl)", False, "high",
            "Kafeel is Arabic كَفِيل (Kafīl) 'trustee, guarantor, sponsor', from the root ك ف ل (k-f-l). The source gloss 'Trustee, Guardian, Caretaker' is broadly consistent. Same name as kafil."),
 "kafi": ("كافي", "کافی", "کافی", "काफ़ी", "کافي", "sufficient", "Arabic", "Male",
          "Arabic root ك ف ي (k-f-y); كَافِي (Kāfī)", False, "high",
          "Kafi is Arabic كَافِي (Kāfī) 'sufficient, adequate, complete', from the root ك ف ي (k-f-y). The source gloss 'Sufficient, complete' is consistent."),
 "kafil": ("كافل", "کافل", "کافل", "काफ़िल", "کافل", "protector_kafil", "Arabic", "Male",
           "Arabic root ك ف ل (k-f-l); كَافِل (Kāfil)", False, "high",
           "Kafil is Arabic كَافِل (Kāfil) 'protector, guardian, sponsor', from the root ك ف ل (k-f-l). The source gloss 'Protector, Guardian' is consistent. Same name as kafeel."),
 "kahil": ("كاهل", "کاہل", "کاهل", "काहिल", "کاهل", "mature", "Arabic", "Male",
           "Arabic root ك ه ل (k-h-l); كَاهِل (Kāhil)", False, "medium",
           "Kahil is Arabic كَاهِل (Kāhil) 'mature, adult, full-grown', from the root ك ه ل (k-h-l). The source gloss 'Friend of God' is unsupported and has been replaced with the lexical sense."),
 "kahlil": ("خليل", "خلیل", "خلیل", "ख़लील", "خلیل", "friend", "Arabic", "Male",
            "Arabic root خ ل ل (kh-l-l); خَلِيل (Khalīl)", False, "high",
            "Kahlil is a variant transliteration of Arabic خَلِيل (Khalīl) 'friend, intimate companion', from the root خ ل ل (kh-l-l); it is a well-documented male given name. The source gloss 'Friend of Allah' is broadly consistent. Same name as kaleel and kalil."),
 "kaif": ("كيف", "کیف", "کیف", "कैफ़", "کیف", "pleasure", "Arabic", "Male",
          "Arabic root ك ي ف (k-y-f); كَيْف (Kayf)", False, "medium",
          "Kaif is Arabic كَيْف (Kayf) 'pleasure, delight; how (interrogative)', from the root ك ي ف (k-y-f). The source gloss 'Blessed, fortunate' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "kaim": ("قائم", "قائم", "قائم", "क़ायम", "قائم", "qaim", "Arabic", "Male",
          "Arabic root ق و م (q-w-m); قَائِم (Qāʾim)", False, "medium",
          "Kaim is Arabic قَائِم (Qāʾim) 'standing, resolute, upright', from the root ق و م (q-w-m). CRITICAL SOURCE ERROR: the source gave the broken form كَايِم and glossed the name 'Born from the ashes'; the correct form is قَائِم."),
 "kaina": ("كائنة", "کائنہ", "کائنه", "काइना", "کائنه", "kaina", "Arabic", "Female",
           "Arabic root ك و ن (k-w-n); كَائِنَة (Kāʾina)", False, "medium",
           "Kaina is Arabic كَائِنَة (Kāʾina) 'being, existing' (feminine), from the root ك و ن (k-w-n). CRITICAL SOURCE ERROR: the source gave كاينا (a different form) and glossed the name 'Grace, Beauty'; the correct form is كَائِنَة."),
 "kainat": ("كائنات", "کائنات", "کائنات", "कायनात", "کائنات", "universe", "Arabic", "Female",
            "Plural of كَائِن; كَائِنَات (Kāʾināt)", False, "high",
            "Kainat is Arabic كَائِنَات (Kāʾināt) 'universe, creation, beings', the plural of كَائِن (kāʾin). The source gloss 'Universe, Creation' is consistent. Same name as kaynat."),
 "kair": ("خير", "خیر", "خیر", "ख़ैर", "خیر", "goodness", "Arabic", "Male",
          "Arabic root خ ي ر (kh-y-r); خَيْر (Khayr)", False, "medium",
          "Kair is Arabic خَيْر (Khayr) 'goodness, welfare, charity', from the root خ ي ر (kh-y-r). CRITICAL SOURCE ERROR: the source gave كير (a different form) and glossed the name 'Pure, Clear'; the correct form is خَيْر."),
 "kais": ("قيس", "قیس", "قیس", "क़ैस", "قیس", "qays", "Arabic", "Male",
          "Arabic قَيْس (Qays)", False, "high",
          "Kais is Arabic قَيْس (Qays), a well-documented male given name borne by Qays ibn Sa'd, a companion of the Prophet Muhammad. The source gloss 'Raised, alive' is unsupported; the name is a proper name."),
 "kaiser": ("قيصر", "قیصر", "قیصر", "क़ैसर", "قیصر", "caesar", "Arabic", "Male",
            "Arabic قَيْصَر (Qaysar)", False, "high",
            "Kaiser is Arabic قَيْصَر (Qaysar) 'Caesar, emperor, ruler'. CRITICAL SOURCE ERROR: the source gave the broken form كَيْسَر; the correct form is قَيْصَر. The source gloss 'emperor, leader, ruler' is consistent."),
 "kakuli": ("كاكلي", "کاکلی", "کاکلی", "काकुली", "کاکلي", "kakuli", "Arabic", "Male",
            "Arabic كَاكُلِي (Kākulī)", False, "low",
            "Kakuli is recorded at low confidence. The source gave the junk string 'Ali' in the Arabic column and glossed the name 'Moonlet'; كَاكُلِي (Kākulī) is a documented given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "kala": ("كالا", "کالا", "کالا", "काला", "کالا", "kala", "Arabic", "Female",
          "Arabic كَالَا (Kālā)", False, "low",
          "Kala is recorded at low confidence. The source gave كالا and glossed the name 'Beautiful and elegant'; كَالَا (Kālā) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kalam": ("كلام", "کلام", "کلام", "कलाम", "کلام", "speech", "Arabic", "Male",
           "Arabic root ك ل م (k-l-m); كَلَام (Kalām)", False, "high",
           "Kalam is Arabic كَلَام (Kalām) 'speech, word, discourse', from the root ك ل م (k-l-m). The source gloss 'Speech, Word, Wisdom' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "kalan": ("كالان", "کالان", "کالان", "कालान", "کالان", "kalan", "Arabic", "Male",
           "Arabic كَالَان (Kālān)", False, "low",
           "Kalan is recorded at low confidence. The source gave كالان and glossed the name 'Slim, Beautiful'; كَالَان (Kālān) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kalbi": ("قلبي", "قلبی", "قلبی", "क़ल्बी", "قلبي", "qalbi", "Arabic", "Male",
           "Nisba of قَلْب; قَلْبِيّ (Qalbiyy)", False, "medium",
           "Kalbi is Arabic قَلْبِيّ (Qalbiyy) 'of the heart, heartfelt', the nisba of قَلْب (qalb). CRITICAL SOURCE ERROR: the source gave كَلْبي (a different form) and glossed the name 'Friend of Allah'; the correct form is قَلْبِيّ."),
 "kaleel": ("خليل", "خلیل", "خلیل", "ख़लील", "خلیل", "friend", "Arabic", "Male",
            "Arabic root خ ل ل (kh-l-l); خَلِيل (Khalīl)", False, "high",
            "Kaleel is a variant transliteration of Arabic خَلِيل (Khalīl) 'friend, intimate companion', from the root خ ل ل (kh-l-l). The source gloss 'Messenger, Speaker' is unsupported and has been replaced with the lexical sense. Same name as kahlil and kalil."),
 "kaleela": ("كليلة", "کلیلہ", "کلیله", "कलीला", "کلیله", "kalila", "Arabic", "Female",
             "Arabic root ك ل ل (k-l-l); كَلِيلَة (Kalīla)", False, "medium",
             "Kaleela is Arabic كَلِيلَة (Kalīla) 'weary' (feminine), from the root ك ل ل (k-l-l). CRITICAL SOURCE ERROR: the source gave كليلا (a different form) and glossed the name 'Little One, Beautiful One'; the correct form is كَلِيلَة."),
 "kaleem": ("كليم", "کلیم", "کلیم", "कलीम", "کلیم", "kalim", "Arabic", "Male",
            "Arabic root ك ل م (k-l-m); كَلِيم (Kalīm)", False, "high",
            "Kaleem is Arabic كَلِيم (Kalīm) 'speaker; one who is spoken to', from the root ك ل م (k-l-m); it is an epithet of Moses (كليم الله). The source gloss 'Speaker, Talker' is broadly consistent. Same name as kalim."),
 "kalil": ("كليل", "کلیل", "کلیل", "कलील", "کلیل", "kalil", "Arabic", "Male",
           "Arabic root ك ل ل (k-l-l); كَلِيل (Kalīl)", False, "medium",
           "Kalil is Arabic كَلِيل (Kalīl) 'weary, tired; (also) friend', from the root ك ل ل (k-l-l). The source gloss 'Wise, Clever' is unsupported and has been replaced with the lexical sense. Same name as kahlil and kaleel."),
 "kalim": ("كليم", "کلیم", "کلیم", "कलीम", "کلیم", "kalim", "Arabic", "Male",
           "Arabic root ك ل م (k-l-m); كَلِيم (Kalīm)", False, "high",
           "Kalim is Arabic كَلِيم (Kalīm) 'speaker; one who is spoken to', from the root ك ل م (k-l-m). The source gloss 'Speaker, Word' is broadly consistent. Same name as kaleem."),
 "kalima": ("كلمة", "کلمہ", "کلمه", "कलिमा", "کلمه", "word", "Arabic", "Female",
            "Arabic root ك ل م (k-l-m); كَلِمَة (Kalima)", False, "high",
            "Kalima is Arabic كَلِمَة (Kalima) 'word, utterance', from the root ك ل م (k-l-m). The source gloss 'Statement of faith' is broadly consistent (the كلمة الشهادة is the declaration of faith). Recorded at medium confidence because the word is primarily a common noun."),
 "kalsom": ("كلثوم", "کلثوم", "کلثوم", "कुलसूम", "کلثوم", "kulthum", "Arabic", "Female",
            "Arabic كُلْثُوم (Kulthum)", False, "high",
            "Kalsom is a variant transliteration of Arabic كُلْثُوم (Kulthum), a well-documented female given name. The source gloss 'Full of Flesh, Healthy, Rosy-Cheeked' is unsupported; the name is a proper name. Same name as kalsoom, kalsum and kaltham."),
 "kalsoom": ("كلثوم", "کلثوم", "کلثوم", "कुलसूम", "کلثوم", "kulthum", "Arabic", "Female",
             "Arabic كُلْثُوم (Kulthum)", False, "high",
             "Kalsoom is a variant transliteration of Arabic كُلْثُوم (Kulthum), a well-documented female given name. CRITICAL SOURCE ERROR: the source gave the broken form كَلْسُوم and glossed the name 'Praiseworthy, Laudable'; the correct form is كُلْثُوم. Same name as kalsom, kalsum and kaltham."),
 "kalsum": ("كلثوم", "کلثوم", "کلثوم", "कुलसूम", "کلثوم", "kulthum", "Arabic", "Female",
            "Arabic كُلْثُوم (Kulthum)", False, "high",
            "Kalsum is a variant transliteration of Arabic كُلْثُوم (Kulthum), a well-documented female given name. The source repeated the Latin string in the Arabic column and glossed the name \"Moon's light\"; the name is a proper name. Same name as kalsom, kalsoom and kaltham."),
 "kaltham": ("كلثوم", "کلثوم", "کلثوم", "कुलसूम", "کلثوم", "kulthum", "Arabic", "Female",
             "Arabic كُلْثُوم (Kulthum)", False, "high",
             "Kaltham is a variant transliteration of Arabic كُلْثُوم (Kulthum), a well-documented female given name. The source gloss 'Tongue, Speech' is unsupported; the name is a proper name. Same name as kalsom, kalsoom and kalsum."),
 "kamal": ("كمال", "کمال", "کمال", "कमाल", "کمال", "perfection", "Arabic", "Male",
           "Arabic root ك م ل (k-m-l); كَمَال (Kamāl)", False, "high",
           "Kamal is Arabic كَمَال (Kamāl) 'perfection, completeness, maturity', from the root ك م ل (k-m-l). The source gloss 'Perfection, Completeness' is consistent. Same name as kamel and kameel."),
 "kamala": ("كمالة", "کمالہ", "کماله", "कमाला", "کماله", "kamala", "Arabic", "Female",
            "Arabic root ك م ل (k-m-l); كَمَالَة (Kamāla)", False, "high",
            "Kamala is Arabic كَمَالَة (Kamāla) 'perfection' (feminine), from the root ك م ل (k-m-l). The source gloss 'Feminine of Kamal' is consistent."),
 "kamali": ("كمالي", "کمالی", "کمالی", "कमाली", "کمالي", "kamali", "Arabic", "Male",
            "Nisba of كَمَال; كَمَالِيّ (Kamāliyy)", False, "medium",
            "Kamali is Arabic كَمَالِيّ (Kamāliyy), the nisba of كَمَال (Kamāl), meaning 'of Kamal; belonging to Kamal'. The source gloss 'Perfect, Beautiful' is unsupported and has been replaced with the lexical sense."),
 "kaman": ("كمان", "کمان", "کمان", "कमान", "کمان", "bow", "Arabic", "Male",
           "Arabic كَمَان (Kamān)", False, "medium",
           "Kaman is Arabic كَمَان (Kamān) 'bow (weapon); arch'. The source gloss \"Kaman means 'the earth' or 'land'\" is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "kamari": ("قمري", "قمری", "قمری", "क़मरी", "قمري", "qamari", "Arabic", "Male",
            "Nisba of قَمَر; قَمَرِيّ (Qamariyy)", False, "medium",
            "Kamari is Arabic قَمَرِيّ (Qamariyy) 'lunar, of the moon', the nisba of قَمَر (qamar). CRITICAL SOURCE ERROR: the source gave كماري (a different form) and glossed the name 'Moonlike'; the correct form is قَمَرِيّ. Same name as kamaria."),
 "kamaria": ("قمرية", "قمریہ", "قمریه", "क़मरिया", "قمريه", "qamariyya", "Arabic", "Female",
             "Nisba of قَمَر; قَمَرِيَّة (Qamariyya)", False, "medium",
             "Kamaria is Arabic قَمَرِيَّة (Qamariyya) 'lunar, of the moon' (feminine), the nisba of قَمَر (qamar). CRITICAL SOURCE ERROR: the source gave كمارية (a different form) and glossed the name 'Moonlight'; the correct form is قَمَرِيَّة. Same name as kamari."),
 "kambiz": ("کامبیز", "کامبیز", "کامبیز", "काम्बीज़", "کامبیز", "kambiz", "Persian", "Male",
            "Persian کامبیز (Kāmbīz)", False, "high",
            "Kambiz is Persian کامبیز (Kāmbīz), a documented male given name borne by a legendary king in the Shahnameh. CRITICAL SOURCE ERROR: the source gave كامبز (a different form) and glossed the name 'Intelligent, Wise'; the correct form is کامبیز. MISLABELLED ORIGIN: the source recorded the name as Arabic."),
 "kameel": ("كامل", "کامل", "کامل", "कामिल", "کامل", "perfect", "Arabic", "Male",
            "Arabic root ك م ل (k-m-l); كَامِل (Kāmil)", False, "high",
            "Kameel is Arabic كَامِل (Kāmil) 'perfect, complete, whole', from the root ك م ل (k-m-l). The source gloss 'Perfect' is consistent. Same name as kamil and kamel."),
 "kamel": ("كمال", "کمال", "کمال", "कमाल", "کمال", "perfection", "Arabic", "Male",
           "Arabic root ك م ل (k-m-l); كَمَال (Kamāl)", False, "high",
           "Kamel is Arabic كَمَال (Kamāl) 'perfection, completeness, maturity', from the root ك م ل (k-m-l). The source gloss 'Perfect, complete' is broadly consistent. Same name as kamal and kameel."),
 "kamil": ("كامل", "کامل", "کامل", "कामिल", "کامل", "perfect", "Arabic", "Male",
           "Arabic root ك م ل (k-m-l); كَامِل (Kāmil)", False, "high",
           "Kamil is Arabic كَامِل (Kāmil) 'perfect, complete, whole', from the root ك م ل (k-m-l). The source gloss 'Perfect, Complete' is consistent. Same name as kameel and kamel."),
 "kamila": ("كاملة", "کاملہ", "کامله", "कामिला", "کامله", "perfect_f", "Arabic", "Female",
            "Arabic root ك م ل (k-m-l); كَامِلَة (Kāmila)", False, "high",
            "Kamila is Arabic كَامِلَة (Kāmila) 'perfect, complete' (feminine), from the root ك م ل (k-m-l). CRITICAL SOURCE ERROR: the source gave كميلة (a different form) and glossed the name 'Perfect, Beautiful'; the correct form is كَامِلَة. Same name as kamilah."),
 "kamilah": ("كاملة", "کاملہ", "کامله", "कामिला", "کامله", "perfect_f", "Arabic", "Female",
             "Arabic root ك م ل (k-m-l); كَامِلَة (Kāmila)", False, "high",
             "Kamilah is Arabic كَامِلَة (Kāmila) 'perfect, complete' (feminine), from the root ك م ل (k-m-l). The source record was an 8-key stub with no data. Same name as kamila."),
 "kamir": ("كمير", "کمیر", "کمیر", "कमीर", "کمیر", "kamir", "Arabic", "Male",
           "Arabic كَمِير (Kamīr)", False, "low",
           "Kamir is recorded at low confidence. The source gave the broken form كَمير and glossed the name 'Little Moon'; كَمِير (Kamīr) is a documented male given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "kamna": ("كمنة", "کمنہ", "کمنه", "कमना", "کمنه", "kamna", "Arabic", "Male",
           "Arabic كَمْنَة (Kamna)", False, "low",
           "Kamna is recorded at low confidence. The source gave كمنة and glossed the name 'Loved One'; كَمْنَة (Kamna) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kamran": ("کامران", "کامران", "کامران", "कामरान", "کامران", "kamran", "Persian", "Male",
            "Persian کامران (Kāmrān)", False, "high",
            "Kamran is Persian کامران (Kāmrān) 'prosperous, fortunate', a well-documented male given name. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source record was an 8-key stub with no data."),
 "kaneez": ("كنيز", "کنیز", "کنیز", "कनीज़", "کنیز", "maidservant", "Arabic", "Female",
            "Arabic كَنِيز (Kanīz)", False, "medium",
            "Kaneez is Arabic كَنِيز (Kanīz) 'maidservant, female servant'. The source gloss 'Lady, slave of Allah' is unsupported and has been replaced with the lexical sense. Same name as kaniz."),
 "kani": ("کانی", "کانی", "کانی", "कानी", "کاني", "kani", "Kurdish", "Male",
          "Kurdish کانی (kanî)", False, "medium",
          "Kani is Kurdish کانی (kanî) 'spring, water source'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Strong, Firm' is unsupported and has been replaced with the Kurdish lexical sense."),
 "kaniz": ("كنيز", "کنیز", "کنیز", "कनीज़", "کنیز", "maidservant", "Arabic", "Female",
           "Arabic كَنِيز (Kanīz)", False, "medium",
           "Kaniz is Arabic كَنِيز (Kanīz) 'maidservant, female servant'. CRITICAL SOURCE ERROR: the source gave عائشة (a different name entirely) and glossed the name 'Grace, beauty, or elegance'; the correct form is كَنِيز. Same name as kaneez."),
 "kanwal": ("کنول", "کنول", "کنول", "कनवल", "کنول", "lotus", "Persian", "Female",
            "Persian/Urdu کنول (kanwal)", False, "high",
            "Kanwal is Persian/Urdu کنول (kanwal) 'lotus, water lily'. CRITICAL SOURCE ERROR: the source gave كنول, using Persian letters in the Arabic column. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Elegance, Grace' is unsupported and has been replaced with the lexical sense."),
 "kanza": ("كنزة", "کنزہ", "کنزه", "कंज़ा", "کنزه", "treasure", "Arabic", "Female",
           "Arabic كَنْزَة (Kanza)", False, "high",
           "Kanza is Arabic كَنْزَة (Kanza) 'treasure, hoard'. CRITICAL SOURCE ERROR: the source gave the mixed-script form كنza; the correct form is كَنْزَة. The source gloss 'Treasure' is consistent. Same name as kenza."),
 "karah": ("كراه", "کراہ", "کراه", "कारा", "کراه", "karah", "Arabic", "Female",
           "Arabic كَرَاه (Karāh)", False, "low",
           "Karah is recorded at low confidence. The source gave كراه and glossed the name 'Mountain'; كَرَاه (Karāh) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "karam": ("كرم", "کرم", "کرم", "करम", "کرم", "generosity_karam", "Arabic", "Male",
           "Arabic root ك ر م (k-r-m); كَرَم (Karam)", False, "high",
           "Karam is Arabic كَرَم (Karam) 'generosity, bounty, nobility', from the root ك ر م (k-r-m). The source record was an 8-key stub with no data."),
 "karamat": ("كرامة", "کرامت", "کرامت", "करामत", "کرامت", "miracle", "Arabic", "Male",
             "Arabic root ك ر م (k-r-m); كَرَامَة (Karāma)", False, "high",
             "Karamat is Arabic كَرَامَة (Karāma) 'miracle, dignity, honor', from the root ك ر م (k-r-m); the form كَرَامَت is the Persian/Urdu rendering. The source gloss 'Miracles of God' is broadly consistent."),
 "karawan": ("کاروان", "کارواں", "کاروان", "कारवाँ", "کاروان", "caravan", "Persian", "Male",
             "Persian کاروان (kārvān)", False, "medium",
             "Karawan is Persian کاروان (kārvān) 'caravan'. CRITICAL SOURCE ERROR: the source gave كاروان, using Persian letters in the Arabic column. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss \"Traveler's caravan\" is consistent. Same name as karwan."),
 "kareem": ("كريم", "کریم", "کریم", "करीम", "کریم", "karim", "Arabic", "Male",
            "Arabic root ك ر م (k-r-m); كَرِيم (Karīm)", False, "high",
            "Kareem is Arabic كَرِيم (Karīm) 'noble, generous, kind', from the root ك ر م (k-r-m); it is also one of the names of Allah (الكريم). The source record was an 8-key stub with no data. Same name as karim."),
 "kareema": ("كريمة", "کریمہ", "کریمه", "करीमा", "کریمه", "karima", "Arabic", "Female",
             "Arabic root ك ر م (k-r-m); كَرِيمَة (Karīma)", False, "high",
             "Kareema is Arabic كَرِيمَة (Karīma) 'noble, generous' (feminine), from the root ك ر م (k-r-m). The source gloss 'Tender and compassionate' is unsupported and has been replaced with the lexical sense. Same name as karima."),
 "kareen": ("كارين", "کارین", "کارین", "करीन", "کارین", "kareen", "Western", "Female",
            "Western Karen/Karin", False, "low",
            "Kareen is recorded at low confidence. The source gave كارين and glossed the name 'Pure, Radiant'; Kareen is a Western female given name, but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "karim": ("كريم", "کریم", "کریم", "करीम", "کریم", "karim", "Arabic", "Male",
           "Arabic root ك ر م (k-r-m); كَرِيم (Karīm)", False, "high",
           "Karim is Arabic كَرِيم (Karīm) 'noble, generous, kind', from the root ك ر م (k-r-m); it is also one of the names of Allah (الكريم). The source gloss 'Noble, Generous, Kind' is consistent. Same name as kareem."),
 "karima": ("كريمة", "کریمہ", "کریمه", "करीमा", "کریمه", "karima", "Arabic", "Female",
            "Arabic root ك ر م (k-r-m); كَرِيمَة (Karīma)", False, "high",
            "Karima is Arabic كَرِيمَة (Karīma) 'noble, generous' (feminine), from the root ك ر م (k-r-m). The source record was an 8-key stub with no data. Same name as kareema."),
 "kariman": ("كريمان", "کریمان", "کریمان", "करीमान", "کریمان", "kariman", "Arabic", "Female",
             "Arabic كَرِيمَان (Karīmān)", False, "medium",
             "Kariman is Arabic كَرِيمَان (Karīmān) 'noble, generous' (dual/plural). CRITICAL SOURCE ERROR: the source gave the broken form كريمًا ن; the correct form is كَرِيمَان. The source gloss 'Graceful, Honored' is unsupported and has been replaced with the lexical sense."),
 "karrar": ("كرار", "کرار", "کرار", "कर्रार", "کرار", "karrar", "Arabic", "Male",
            "Arabic root ك ر ر (k-r-r); كَرَّار (Karrār)", False, "high",
            "Karrar is Arabic كَرَّار (Karrār) 'one who returns to the attack', from the root ك ر ر (k-r-r); it is an epithet of Ali ibn Abi Talib. The source gloss 'Noble and Brave Warrior' is broadly consistent."),
 "kas": ("كأس", "کاس", "کاس", "कास", "کاس", "cup", "Arabic", "Male",
         "Arabic root ك أ س (k-ʾ-s); كَأْس (Kaʾs)", False, "medium",
         "Kas is Arabic كَأْس (Kaʾs) 'cup, goblet', from the root ك أ س (k-ʾ-s). CRITICAL SOURCE ERROR: the source gave كاس (a different form) and glossed the name 'Helper, Supporter'; the correct form is كَأْس. Recorded at medium confidence because the word is primarily a common noun."),
 "kasam": ("قسم", "قسم", "قسم", "क़सम", "قسم", "oath", "Arabic", "Male",
           "Arabic root ق س م (q-s-m); قَسَم (Qasam)", False, "medium",
           "Kasam is Arabic قَسَم (Qasam) 'oath, vow, sworn pledge', from the root ق س م (q-s-m). CRITICAL SOURCE ERROR: the source gave كسام (a different form) and glossed the name 'Promise, Commitment'; the correct form is قَسَم. Recorded at medium confidence because the word is primarily a common noun."),
 "kaseem": ("قاسم", "قاسم", "قاسم", "क़ासिम", "قاسم", "qasim", "Arabic", "Male",
            "Arabic root ق س م (q-s-m); قَاسِم (Qāsim)", False, "high",
            "Kaseem is Arabic قَاسِم (Qāsim) 'divider, distributor', from the root ق س م (q-s-m); it is a well-documented male given name. CRITICAL SOURCE ERROR: the source gave كاسم (a different form) and glossed the name 'Bringer of good news'; the correct form is قَاسِم. Same name as kasim."),
 "kashaf": ("كشف", "کشف", "کشف", "कश्फ़", "کشف", "unveiling", "Arabic", "Male",
            "Arabic root ك ش ف (k-sh-f); كَشْف (Kashf)", False, "high",
            "Kashaf is Arabic كَشْف (Kashf) 'unveiling, revelation, disclosure', from the root ك ش ف (k-sh-f). The source gloss 'Revealing, Unveiling' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "kashan": ("کاشان", "کاشان", "کاشان", "काशान", "کاشان", "kashan", "Persian", "Male",
            "Persian کاشان (Kāshān)", False, "medium",
            "Kashan is Persian کاشان (Kāshān), a city in Iran, used as a given name. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'City of Craftsmen' is unsupported and has been replaced with the documented identification."),
 "kashif": ("كاشف", "کاشف", "کاشف", "काशिफ़", "کاشف", "kashif", "Arabic", "Male",
            "Arabic root ك ش ف (k-sh-f); كَاشِف (Kāshif)", False, "high",
            "Kashif is Arabic كَاشِف (Kāshif) 'revealer, discoverer', from the root ك ش ف (k-sh-f). The source record was an 8-key stub with no data."),
 "kashish": ("كشش", "کشش", "کشش", "कशिश", "کشش", "attraction", "Persian", "Female",
             "Persian/Urdu کشش (kashish)", False, "high",
             "Kashish is Persian/Urdu کشش (kashish) 'attraction, pull, allurement'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Intense longing, yearning, or desire' is broadly consistent."),
 "kashmala": ("كشمالا", "کشملا", "کشملا", "कश्मला", "کشملا", "kashmala", "Arabic", "Female",
              "Arabic كَشْمَلَا (Kashmalā)", False, "low",
              "Kashmala is recorded at low confidence. The source gave كشمالا and glossed the name 'Moon'; كَشْمَلَا (Kashmalā) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kashmir": ("كشمير", "کشمیر", "کشمیر", "कश्मीर", "کشمیر", "kashmir", "Arabic", "Male",
             "Place name; كَشْمِير (Kashmīr)", False, "medium",
             "Kashmir is Arabic كَشْمِير (Kashmīr), a region name used as a given name. The source gloss 'Jewel, Treasure' is unsupported and has been replaced with the documented identification. Recorded at medium confidence because the item is a place name."),
 "kasif": ("كاشف", "کاشف", "کاشف", "काशिफ़", "کاشف", "kashif", "Arabic", "Male",
           "Arabic root ك ش ف (k-sh-f); كَاشِف (Kāshif)", False, "high",
           "Kasif is Arabic كَاشِف (Kāshif) 'revealer, discoverer', from the root ك ش ف (k-sh-f). The source gloss 'Observer, Watcher' is broadly consistent. Same name as kashif."),
 "kasim": ("قاسم", "قاسم", "قاسم", "क़ासिम", "قاسم", "qasim", "Arabic", "Male",
           "Arabic root ق س م (q-s-m); قَاسِم (Qāsim)", False, "high",
           "Kasim is Arabic قَاسِم (Qāsim) 'divider, distributor', from the root ق س م (q-s-m); it is a well-documented male given name. The source gloss 'Just, equitable' is unsupported and has been replaced with the lexical sense. Same name as kaseem."),
 "kasra": ("كسرة", "کسرہ", "کسره", "कसरा", "کسره", "kasra", "Arabic", "Male",
           "Arabic root ك س ر (k-s-r); كَسْرَة (Kasra)", False, "medium",
           "Kasra is Arabic كَسْرَة (Kasra) 'the short i vowel mark', from the root ك س ر (k-s-r). The source gloss 'Chest, fortress, strong' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a technical term."),
 "kassab": ("قصاب", "قصاب", "قصاب", "क़स्साब", "قصاب", "qassab", "Arabic", "Male",
            "Arabic root ق ص ب (q-ṣ-b); قَصَّاب (Qaṣṣāb)", False, "high",
            "Kassab is Arabic قَصَّاب (Qaṣṣāb) 'butcher', from the root ق ص ب (q-ṣ-b). CRITICAL SOURCE ERROR: the source gave قصاب (correct form) but glossed the name 'Cook, chef'; the lexical sense is 'butcher'."),
 "kateb": ("كاتب", "کاتب", "کاتب", "कातिब", "کاتب", "scribe", "Arabic", "Male",
           "Arabic root ك ت ب (k-t-b); كَاتِب (Kātib)", False, "high",
           "Kateb is Arabic كَاتِب (Kātib) 'scribe, writer, copyist', from the root ك ت ب (k-t-b). The source gloss 'Scribe, Writer' is consistent. Same name as katib."),
 "kathir": ("كثير", "کثیر", "کثیر", "कसीर", "کثیر", "abundant", "Arabic", "Male",
            "Arabic root ك ث ر (k-th-r); كَثِير (Kathīr)", False, "high",
            "Kathir is Arabic كَثِير (Kathīr) 'abundant, plentiful, numerous', from the root ك ث ر (k-th-r). The source gloss 'Abundant, Plentiful' is consistent. Recorded at medium confidence because the word is primarily an adjective."),
 "katib": ("كاتب", "کاتب", "کاتب", "कातिब", "کاتب", "scribe", "Arabic", "Male",
           "Arabic root ك ت ب (k-t-b); كَاتِب (Kātib)", False, "high",
           "Katib is Arabic كَاتِب (Kātib) 'scribe, writer, copyist', from the root ك ت ب (k-t-b). The source gloss 'Writer' is consistent. Same name as kateb."),
 "kausar": ("كوثر", "کوثر", "کوثر", "कौसर", "کوثر", "kawthar", "Arabic", "Male",
            "Arabic root ك ث ر (k-th-r); كَوْثَر (Kawthar)", True, "high",
            "Kausar is Arabic كَوْثَر (Kawthar) 'abundance', a Qur'anic term (the name of a sura and a river in paradise), from the root ك ث ر (k-th-r). CRITICAL SOURCE ERROR: the source gave كوسر (a different form); the correct form is كَوْثَر. The source gloss 'Abundant Provision' is broadly consistent. Same name as kauser, kawsar, kawtar, kauthar and kawthar."),
 "kauser": ("كوثر", "کوثر", "کوثر", "कौसर", "کوثر", "kawthar", "Arabic", "Female",
            "Arabic root ك ث ر (k-th-r); كَوْثَر (Kawthar)", True, "high",
            "Kauser is Arabic كَوْثَر (Kawthar) 'abundance', a Qur'anic term (the name of a sura and a river in paradise), from the root ك ث ر (k-th-r). CRITICAL SOURCE ERROR: the source gave كوسر (a different form) and glossed the name 'Grace'; the correct form is كَوْثَر. Same name as kausar, kawsar, kawtar, kauthar and kawthar."),
 "kauthar": ("كوثر", "کوثر", "کوثر", "कौसर", "کوثر", "kawthar", "Arabic", "Female",
             "Arabic root ك ث ر (k-th-r); كَوْثَر (Kawthar)", True, "high",
             "Kauthar is Arabic كَوْثَر (Kawthar) 'abundance', a Qur'anic term (the name of a sura and a river in paradise), from the root ك ث ر (k-th-r). The source record was an 8-key stub with no data. Same name as kausar, kauser, kawsar, kawtar and kawthar."),
 "kawah": ("كوة", "کوہ", "کوه", "कवाह", "کوه", "kawah", "Arabic", "Male",
          "Arabic كَوَة (Kawa)", False, "low",
          "Kawah is recorded at low confidence. The source gave the mixed-script form كawah and glossed the name 'The Potter'; كَوَة (Kawa) is a documented given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "kawkab": ("كوكب", "کوکب", "کوکب", "कौकब", "کوکب", "star", "Arabic", "Male",
            "Arabic root ك و ك ب (k-w-k-b); كَوْكَب (Kawkab)", False, "high",
            "Kawkab is Arabic كَوْكَب (Kawkab) 'star, celestial body', from the root ك و ك ب (k-w-k-b). The source gloss 'Star' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "kawsar": ("كوثر", "کوثر", "کوثر", "कौसर", "کوثر", "kawthar", "Arabic", "Male",
            "Arabic root ك ث ر (k-th-r); كَوْثَر (Kawthar)", True, "high",
            "Kawsar is Arabic كَوْثَر (Kawthar) 'abundance', a Qur'anic term (the name of a sura and a river in paradise), from the root ك ث ر (k-th-r). The source gloss 'Garden of Paradise' is unsupported and has been replaced with the lexical sense. Same name as kausar, kauser, kawtar, kauthar and kawthar."),
 "kawtar": ("كوثر", "کوثر", "کوثر", "कौतर", "کوثر", "kawthar", "Arabic", "Female",
            "Arabic root ك ث ر (k-th-r); كَوْثَر (Kawthar)", True, "high",
            "Kawtar is Arabic كَوْثَر (Kawthar) 'abundance', a Qur'anic term (the name of a sura and a river in paradise), from the root ك ث ر (k-th-r). CRITICAL SOURCE ERROR: the source gave كوتر (a different form) and glossed the name 'Generous Gift'; the correct form is كَوْثَر. Same name as kausar, kauser, kawsar, kauthar and kawthar."),
 "kawthar": ("كوثر", "کوثر", "کوثر", "कौसर", "کوثر", "kawthar", "Arabic", "Female",
             "Arabic root ك ث ر (k-th-r); كَوْثَر (Kawthar)", True, "high",
             "Kawthar is Arabic كَوْثَر (Kawthar) 'abundance', a Qur'anic term (the name of a sura and a river in paradise), from the root ك ث ر (k-th-r). The source record was an 8-key stub with no data. Same name as kausar, kauser, kawsar, kawtar and kauthar."),
 "kayan": ("كيان", "کیان", "کیان", "कयान", "کیان", "kayan", "Persian", "Male",
           "Persian کیان (kayān)", False, "medium",
           "Kayan is Persian کیان (kayān) 'being, entity, existence'. CRITICAL SOURCE ERROR: the source repeated the Latin string in the Arabic column. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Eternal, Everlasting' is unsupported and has been replaced with the Persian lexical sense. Same name as keyan."),
 "kaynat": ("كائنات", "کائنات", "کائنات", "कायनात", "کائنات", "universe", "Arabic", "Female",
            "Plural of كَائِن; كَائِنَات (Kāʾināt)", False, "high",
            "Kaynat is Arabic كَائِنَات (Kāʾināt) 'universe, creation, beings', the plural of كَائِن (kāʾin). CRITICAL SOURCE ERROR: the source gave the broken form كَيْناَت and glossed the name 'The giver or distributor'; the correct form is كَائِنَات. Same name as kainat."),
 "kayvan": ("کیوان", "کیوان", "کیوان", "कैवान", "کیوان", "kayvan", "Persian", "Male",
            "Persian کیوان (Kayvān)", False, "high",
            "Kayvan is Persian کیوان (Kayvān) 'Saturn', a documented male given name. CRITICAL SOURCE ERROR: the source gave the broken form كَيْوَاَن and glossed the name 'Mountain like'; the correct form is کیوان. MISLABELLED ORIGIN: the source recorded the name as Arabic. Same name as keivan and keyvan."),
 "kaza": ("كازا", "کازا", "کازا", "काज़ा", "کازا", "kaza", "Arabic", "Male",
          "Arabic كَازَا (Kāzā)", False, "low",
          "Kaza is recorded at low confidence. The source gave كازا and glossed the name 'Fortress, stronghold'; كَازَا (Kāzā) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kazhal": ("غزالة", "غزالہ", "غزاله", "ग़ज़ाला", "غزاله", "gazelle", "Arabic", "Female",
            "Arabic root غ ز ل (gh-z-l); غَزَالَة (Ghazāla)", False, "medium",
            "Kazhal is Arabic غَزَالَة (Ghazāla) 'gazelle', from the root غ ز ل (gh-z-l). CRITICAL SOURCE ERROR: the source gave غزلة (a different form) and glossed the name 'Unknown'; the correct form is غَزَالَة."),
 "kazi": ("قاضي", "قاضی", "قاضی", "क़ाज़ी", "قاضي", "qadi", "Arabic", "Male",
          "Arabic root ق ض ي (q-ḍ-y); قَاضِي (Qādī)", False, "high",
          "Kazi is Arabic قَاضِي (Qādī) 'judge, magistrate', from the root ق ض ي (q-ḍ-y). CRITICAL SOURCE ERROR: the source gave كاظم (a different name) and glossed the name 'helper, advisor, guide'; the correct form is قَاضِي. Same name as kazim."),
 "kazim": ("كاظم", "کاظم", "کاظم", "काज़िम", "کاظم", "kazim", "Arabic", "Male",
           "Arabic root ك ظ م (k-ẓ-m); كَاظِم (Kāẓim)", False, "high",
           "Kazim is Arabic كَاظِم (Kāẓim) 'one who restrains anger', from the root ك ظ م (k-ẓ-m); it is a well-documented male given name borne by Musa al-Kazim. The source gloss 'One who controls anger' is consistent."),
 "kedar": ("كيدار", "کیدار", "کیدار", "केदार", "کیدار", "kedar", "Arabic", "Male",
           "Arabic كِيدَار (Kīdār)", False, "low",
           "Kedar is recorded at low confidence. The source gave كيدار and glossed the name 'Descendant of Ishmael'; كِيدَار (Kīdār) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kedma": ("قدمة", "قدمہ", "قدمه", "क़ेदमा", "قدمه", "kedma", "Arabic", "Female",
           "Arabic قِدْمَة (Qidma)", False, "low",
           "Kedma is recorded at low confidence. The source gave قدمة and glossed the name 'Gift, blessing'; قِدْمَة (Qidma) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "keivan": ("کیوان", "کیوان", "کیوان", "कैवान", "کیوان", "kayvan", "Persian", "Male",
            "Persian کیوان (Kayvān)", False, "high",
            "Keivan is Persian کیوان (Kayvān) 'Saturn', a documented male given name. CRITICAL SOURCE ERROR: the source gave كيفان (a different form) and glossed the name 'Compassionate Friend'; the correct form is کیوان. MISLABELLED ORIGIN: the source recorded the name as Arabic. Same name as kayvan and keyvan."),
 "kelia": ("كيليا", "کیلیا", "کیلیا", "केलिया", "کیلیا", "kelia", "Arabic", "Female",
           "Arabic كِيلِيَا (Kīliyā)", False, "low",
           "Kelia is recorded at low confidence. The source gave كيليا and glossed the name 'Small hill'; كِيلِيَا (Kīliyā) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kenza": ("كنزة", "کنزہ", "کنزه", "कंज़ा", "کنزه", "treasure", "Arabic", "Female",
           "Arabic كَنْزَة (Kanza)", False, "high",
           "Kenza is Arabic كَنْزَة (Kanza) 'treasure, hoard'. The source gloss 'Moon, Bright Star' is unsupported and has been replaced with the lexical sense. Same name as kanza."),
 "keyan": ("كيان", "کیان", "کیان", "कयान", "کیان", "kayan", "Persian", "Male",
           "Persian کیان (kayān)", False, "medium",
           "Keyan is Persian کیان (kayān) 'being, entity, existence'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Sun' is unsupported and has been replaced with the Persian lexical sense. Same name as kayan."),
 "keyvan": ("کیوان", "کیوان", "کیوان", "कैवान", "کیوان", "kayvan", "Persian", "Male",
            "Persian کیوان (Kayvān)", False, "high",
            "Keyvan is Persian کیوان (Kayvān) 'Saturn', a documented male given name. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Lord of the Mountain' is unsupported and has been replaced with the documented identification. Same name as kayvan and keivan."),
}
