# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 4 (afshan..aizah)."""

GLOSSES = {
    "scatterer": {"en": "Scatterer, sprinkler (of light, perfume)", "ur": "بکھیرنے والی، افشانے والی", "fa": "افشاننده، پراکنده‌کننده", "hi": "बिखेरने वाली, छिड़कने वाली", "ps": "خپرونکې، شینډونکې", "ar": "ناثرة، ناشرة"},
    "ruler": {"en": "Ruler, king, lord", "ur": "حکمران، بادشاہ، سردار", "fa": "فرمانروا، شاه، سردار", "hi": "शासक, राजा, स्वामी", "ps": "واکمن، پاچا، مشر", "ar": "حاكم، ملك، أمير"},
    "sun": {"en": "Sun, sunlight", "ur": "سورج، دھوپ", "fa": "خورشید، آفتاب", "hi": "सूरज, धूप", "ps": "لمر، لمر رڼا", "ar": "شمس، ضياء الشمس"},
    "charm": {"en": "Charm, spell, enchantment", "ur": "افسون، جادو، سحر", "fa": "افسون، جادو، سحر", "hi": "जादू, मोहिनी, टोना", "ps": "افسون، جادو", "ar": "سحر، تعويذة"},
    "forgiveness": {"en": "Pardon, forgiveness, grace", "ur": "معافی، بخشش، عفو", "fa": "بخشش، آمرزش، عفو", "hi": "क्षमा, माफ़ी, अनुग्रह", "ps": "بخښنه، عفو", "ar": "عفو، مغفرة، صفح"},
    "increasing": {"en": "Increasing, augmenting", "ur": "بڑھانے والا، افزا", "fa": "افزاینده، افزون‌کننده", "hi": "बढ़ाने वाला, वर्धक", "ps": "زیاتوونکی، افزا", "ar": "مزيد، نامٍ"},
    "excellence": {"en": "Excellence, superiority, best", "ur": "برتری، افضل، بہترین", "fa": "برتری، بهترین", "hi": "श्रेष्ठता, सर्वोत्तम", "ps": "غوره والی، غوره", "ar": "أفضلية، أفضل"},
    "lord_master": {"en": "Lord, master, elder", "ur": "آقا، مالک، بزرگ", "fa": "آقا، سرور، بزرگ", "hi": "आका, स्वामी, बुज़ुर्ग", "ps": "آقا، مالک، مشر", "ar": "سيد، مولى، كبير"},
    "agate": {"en": "Agate; a valley near Medina", "ur": "عقیق، سنگِ سرخ", "fa": "عقیق، سنگ سرخ", "hi": "अक़ीक़, लाल पत्थर", "ps": "عقیق، سور ډبره", "ar": "عقيق"},
    "intelligent": {"en": "Intelligent, wise, discerning", "ur": "عقیل، ذہین، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرک، پوه", "ar": "عقيل، ذكي، عاقل"},
    "precious": {"en": "Most precious, dearest", "ur": "سب سے قیمتی، عزیز", "fa": "گران‌بهاترین، عزیز", "hi": "सबसे बहुमूल्य, प्रिय", "ps": "تر ټولو قیمتي، ګران", "ar": "أغلى، أعز"},
    "one_unique": {"en": "One, unique, indivisible", "ur": "ایک، یکتا، احد", "fa": "یکتا، یگانه، احد", "hi": "एक, अद्वितीय", "ps": "یو، یوازینی", "ar": "أحد، واحد، فريد"},
    "beloved_ones": {"en": "Beloved ones, dear friends", "ur": "محبوب، پیارے دوست", "fa": "دلبندان، دوستان عزیز", "hi": "प्रियजन, प्यारे मित्र", "ps": "خوږ ملګري، ګران", "ar": "أحباب، أحبة"},
    "covenant": {"en": "Covenant, pledge, agreement", "ur": "عہد، وعدہ، معاہدہ", "fa": "پیمان، عهد، قرارداد", "hi": "संधि, वचन, प्रतिज्ञा", "ps": "لوظ، تړون", "ar": "عهد، ميثاق، عقد"},
    "gifts": {"en": "Gifts, presents", "ur": "تحفے، ہدایا", "fa": "هدایا، کادوها", "hi": "उपहार, तोहफ़े", "ps": "ډالۍ، تحفې", "ar": "هدايا، أهدية"},
    "judgments": {"en": "Judgments, rulings, ordinances", "ur": "احکام، فیصلے", "fa": "احکام، داوری‌ها", "hi": "आदेश, निर्णय, हुक्म", "ps": "حکمونه، فیصلې", "ar": "أحكام، قوانين"},
    "dreams": {"en": "Dreams, visions", "ur": "خواب، احلام", "fa": "خواب‌ها، رؤیاها", "hi": "सपने, स्वप्न", "ps": "خوبونه، ارمانونه", "ar": "أحلام، رؤى"},
    "competence": {"en": "Competence, qualification, worthiness", "ur": "اہلیت، قابلیت", "fa": "شایستگی، اهلیت", "hi": "योग्यता, पात्रता", "ps": "وړتیا، اهلیت", "ar": "أهلية، كفاءة"},
    "praiseworthy": {"en": "Most praiseworthy, most commendable", "ur": "بہت تعریف کیا ہوا، احمد", "fa": "ستوده‌ترین، احمد", "hi": "अत्यंत प्रशंसनीय, अहमद", "ps": "ډېر ستایل شوی، احمد", "ar": "أحمد، محمود، حميد"},
    "red": {"en": "Red", "ur": "سرخ، لال", "fa": "سرخ، قرمز", "hi": "लाल, सुर्ख़", "ps": "سور، سره", "ar": "أحمر، قرمزي"},
    "clubfooted": {"en": "Club-footed (classical); upright, inclined to truth", "ur": "احنف، سیدھا، حق کی طرف مائل", "fa": "احنف، راست‌رو، حق‌گرا", "hi": "अहनफ़, सच की ओर झुका", "ps": "احنف، رښتيا ته مایل", "ar": "أحنف، مستقيم"},
    "gazelle": {"en": "Gazelle, deer", "ur": "ہرن، آہو", "fa": "آهو، غزال", "hi": "हिरण, चिकारा", "hi_alt": None, "ps": "غوی، آهو", "ar": "غزال، ظبي"},
    "ahura": {"en": "Lord (as in Ahura Mazda)", "ur": "خداوند (اہورا)", "fa": "خداوند (اهورا)", "hi": "स्वामी (अहुरा)", "ps": "څښتن (اهورا)", "ar": "الرب (أهورا)"},
    "pyramids": {"en": "Pyramids", "ur": "اہرام، پرامڈ", "fa": "اهرام، هرم‌ها", "hi": "पिरामिड, पिरामिड", "ps": "اهرام، هرمونه", "ar": "أهرام، هرم"},
    "best_beautiful": {"en": "Best, most beautiful, finest", "ur": "بہترین، سب سے خوبصورت", "fa": "بهترین، زیباترین", "hi": "सर्वोत्तम, सबसे सुंदर", "ps": "غوره، تر ټولو ښکلی", "ar": "أحسن، أجمل"},
    "dignity": {"en": "Dignity, modesty, magnificence", "ur": "احتشام، وقار، شان", "fa": "احتشام، وقار، شکوه", "hi": "गरिमा, शालीनता, वैभव", "ps": "وقار، دروندوالی", "ar": "احتشام، وقار، عظمة"},
    "city_ahvaz": {"en": "Ahvaz (city in Iran)", "ur": "اہواز (ایران کا شہر)", "fa": "اهواز (شهری در ایران)", "hi": "अहवाज़ (ईरान का शहर)", "ps": "اهواز (د ایران ښار)", "ar": "الأحواز (مدينة في إيران)"},
    "times": {"en": "Times, occasions", "ur": "اوقات، احيان", "fa": "زمان‌ها، اوقات", "hi": "समय, अवसर", "ps": "وختونه، احيان", "ar": "أحيان، أوقات"},
    "mamluk": {"en": "Mamluk name (Aibak)", "ur": "ایبک، مملوک نام", "fa": "ایبک، نام مملوک", "hi": "ऐबक, ममलूक नाम", "ps": "ایبک، مملوک نوم", "ar": "أيبك، اسم مملوكي"},
    "returning": {"en": "Returning, one who returns", "ur": "واپس آنے والی، عائدہ", "fa": "بازگشت‌کننده، عائده", "hi": "लौटने वाली, आइदा", "ps": "بېرته راتلونکې", "ar": "عائدة، راجعة"},
    "moon_flower": {"en": "Moon flower", "ur": "چاند کا پھول", "fa": "گل ماه", "hi": "चाँद का फूल", "ps": "د سپوږمۍ ګل", "ar": "زهرة القمر"},
    "miracle": {"en": "Inimitability, miracle", "ur": "اعجاز، معجزہ", "fa": "اعجاز، معجزه", "hi": "चमत्कार, इजाज़", "ps": "اعجاز، معجزه", "ar": "إعجاز، معجزة"},
    "hope": {"en": "Hope, desire, aspiration", "ur": "امید، خواہش", "fa": "امید، آرزو", "hi": "आशा, इच्छा", "ps": "هيله، ارمان", "ar": "أمل، رجاء"},
    "blessed": {"en": "Blessed, fortunate, on the right", "ur": "بابرکت، مبارک، دائیں", "fa": "مبارک، خجسته", "hi": "धन्य, शुभ, दाहिना", "ps": "برکت والا، مبارک", "ar": "أيمن، مبارك"},
    "eye": {"en": "Eye; spring, source", "ur": "آنکھ، چشمہ", "fa": "چشم، چشمه", "hi": "आँख, स्रोत", "ps": "سترګه، چینه", "ar": "عين، نبع"},
    "my_eye": {"en": "My eye (term of endearment)", "ur": "میری آنکھ، عینی", "fa": "چشم من، عینی", "hi": "मेरी आँख, ऐनी", "ps": "زما سترګه", "ar": "عيني، عيني"},
    "eyes_plural": {"en": "Eyes; springs", "ur": "آنکھیں، عیون", "fa": "چشم‌ها، عیون", "hi": "आँखें, ऐनून", "ps": "سترګې، عیون", "ar": "عيون، أعين"},
    "iram": {"en": "Iram (the many-columned city, Qur'an 89:7)", "ur": "ارم (ذات العماد)", "fa": "ارم (ذات‌العماد)", "hi": "इरम (स्तंभों वाला नगर)", "ps": "ارم (د ستنو ښار)", "ar": "إرم، ذات العماد"},
    "life_living": {"en": "Life, living, livelihood", "ur": "زندگی، عیش، معاش", "fa": "زندگی، معاش", "hi": "जीवन, जीविका", "ps": "ژوند، معاش", "ar": "عيش، حياة"},
    "jesus": {"en": "Jesus (Arabic form of the name)", "ur": "عیسیٰ", "fa": "عیسی", "hi": "ईसा", "ps": "عیسی", "ar": "عيسى"},
    "sign_verse": {"en": "Sign, verse, miracle", "ur": "نشانی، آیت", "fa": "نشانه، آیه", "hi": "निशानी, आयत", "ps": "نښه، آیت", "ar": "آية، علامة"},
    "iyad": {"en": "Iyad (name of Qadi Iyad, 1083-1149)", "ur": "عیاض", "fa": "عیاض", "hi": "इयाज़", "ps": "عیاض", "ar": "عياض"},
    "refuge_seeker": {"en": "One who seeks refuge", "ur": "پناہ لینے والی، عائذہ", "fa": "پناه‌جو، عائذه", "hi": "शरण लेने वाली", "ps": "پناه غوښتونکې", "ar": "عائذة، مستجيرة"},
    "moon_born": {"en": "Moon-born, moon-like", "ur": "چاند سے پیدا، چاند جیسی", "fa": "ماه‌زاد، ماه‌رو", "hi": "चाँद से जन्मी", "ps": "له سپوږمۍ زېږېدلې", "ar": "مولودة القمر"},
    "reins_sky": {"en": "Reins; clouds, sky", "ur": "لگام، عنان، آسمان", "fa": "عنان، ابر، آسمان", "hi": "लगाम, आकाश", "ps": "عنان، آسمان", "ar": "عنان، سماء"},
    "eye_of": {"en": "Eye of (construct)", "ur": "کی آنکھ، عین الـ", "fa": "چشمِ، عین‌الـ", "hi": "की आँख, ऐनुल", "ps": "د سترګه", "ar": "عين الـ"},
    "helen": {"en": "Helen (Greek origin)", "ur": "ہیلن، یونانی نام", "fa": "هلن، نام یونانی", "hi": "हेलेन, यूनानी नाम", "ps": "هیلن، یوناني نوم", "ar": "هيلين، اسم يوناني"},
    "living_one": {"en": "Living one, alive", "ur": "زندہ، جیتی جاگتی", "fa": "زنده، پاینده", "hi": "जीवित, जीवंत", "ps": "ژوندې، پاتې", "ar": "عائشة، حية"},
    "gazelle_deer": {"en": "Gazelle, deer", "ur": "ہرن، آہو", "fa": "آهو، غزال", "hi": "हिरण, चिकारा", "ps": "غوی، آهو", "ar": "غزال، ظبي"},
    "king_ahab": {"en": "Ahab (king of Israel, 9th c. BCE)", "ur": "اخاب (اسرائیل کا بادشاہ)", "fa": "اخاب (پادشاه اسرائیل)", "hi": "अहाब (इस्राएल का राजा)", "ps": "اخاب (د اسرائیل پاچا)", "ar": "أخاب، ملك إسرائيل"},
    "covenant_pledge": {"en": "Covenant, pledge", "ur": "عہد، وعدہ", "fa": "پیمان، عهد", "hi": "संधि, वचन", "ps": "لوظ، تړون", "ar": "عهد، ميثاق"},
    "gift_reward": {"en": "Gift, reward", "ur": "تحفہ، انعام", "fa": "هدیه، پاداش", "hi": "उपहार, इनाम", "ps": "ډالۍ، انعام", "ar": "هدية، عطاء"},
    "dream_vision": {"en": "Dream, vision", "ur": "خواب، رؤیا", "fa": "خواب، رؤیا", "hi": "सपना, स्वप्न", "ps": "خوب، لید", "ar": "حلم، رؤيا"},
    "dignity_modesty": {"en": "Dignity, modesty, respectability", "ur": "وقار، شان، حیا", "fa": "وقار، شرم، حیا", "hi": "गरिमा, शालीनता", "ps": "وقار، شرم", "ar": "احتشام، حياء"},
    "praiseworthy_ahmad": {"en": "Most praiseworthy", "ur": "بہت تعریف کیا ہوا", "fa": "ستوده‌ترین", "hi": "अत्यंत प्रशंसनीय", "ps": "ډېر ستایل شوی", "ar": "أحمد، محمود"},
    "red_courageous": {"en": "Red; courageous", "ur": "سرخ، بہادر", "fa": "سرخ، دلیر", "hi": "लाल, साहसी", "ps": "سور، زړور", "ar": "أحمر، شجاع"},
    "best_finest": {"en": "Best, finest, most beautiful", "ur": "بہترین، سب سے خوبصورت", "fa": "بهترین، زیباترین", "hi": "सर्वोत्तम, सुंदरतम", "ps": "غوره، ښکلی", "ar": "أحسن، أجمل"},
    "dignity_greatness": {"en": "Dignity, magnificence", "ur": "وقار، عظمت", "fa": "وقار، شکوه", "hi": "गरिमा, वैभव", "ps": "وقار، لویۍ", "ar": "احتشام، عظمة"},
    "moonlight": {"en": "Moonlight", "ur": "چاندنی", "fa": "مهتاب", "hi": "चाँदनी", "ps": "سپوږمۍ رڼا", "ar": "ضوء القمر"},
    "night": {"en": "Night", "ur": "رات", "fa": "شب", "hi": "रात", "ps": "شپه", "ar": "ليل"},
    "dew": {"en": "Dew", "ur": "شبنم، اوس", "fa": "شبنم، ژاله", "hi": "ओस, शबनम", "ps": "شبنم، اوس", "ar": "ندى، طل"},
    "noble_blessed": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "joyful": {"en": "Joyful, happy", "ur": "خوش، مسرور", "fa": "شاد، خوشحال", "hi": "प्रसन्न, खुश", "ps": "خوشحاله، مړوند", "ar": "فرِح، مسرور"},
    "fame_greatness": {"en": "Fame, greatness", "ur": "شہرت، عظمت", "fa": "نام‌آوری، بزرگی", "hi": "प्रसिद्धि, महानता", "ps": "نام، لویۍ", "ar": "شهرة، عظمة"},
    "gift": {"en": "Gift", "ur": "تحفہ", "fa": "هدیه", "hi": "उपहार", "ps": "ډالۍ", "ar": "هدية"},
    "elevated_noble": {"en": "Elevated, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "مرفوع، نبيل"},
    "river": {"en": "River", "ur": "دریا، ندی", "fa": "رود، رودخانه", "hi": "नदी, दरिया", "ps": "سیند، رود", "ar": "نهر، نهر"},
    "guided": {"en": "Guided, enlightened", "ur": "ہدایت یافتہ، روشن", "fa": "هدایت‌یافته، روشن", "hi": "मार्गदर्शित, प्रबुद्ध", "ps": "هدایت شوی، روښانه", "ar": "مهتدي، مستنير"},
    "helper": {"en": "Helper, supporter", "ur": "مددگار، معاون", "fa": "یاری‌گر، پشتیبان", "hi": "सहायक, समर्थक", "ps": "مرسته کوونکی، ملاتړی", "ar": "معين، ناصر"},
    "successor": {"en": "Successor, supporter", "ur": "جانشین، حامی", "fa": "جانشین، پشتیبان", "hi": "उत्तराधिकारी, समर्थक", "ps": "ځای ناستی، ملاتړی", "ar": "خليفة، ناصر"},
    "journey": {"en": "Journey, pilgrimage", "ur": "سفر، زیارت", "fa": "سفر، زیارت", "hi": "यात्रा, तीर्थयात्रा", "ps": "سفر، زیارت", "ar": "رحلة، حج"},
    "festival_moon": {"en": "Festival of the moon", "ur": "چاند کا تہوار", "fa": "جشن ماه", "hi": "चाँद का उत्सव", "ps": "د سپوږمۍ جشن", "ar": "عيد القمر"},
    "little_star": {"en": "Little star", "ur": "چھوٹا ستارہ", "fa": "ستارهٔ کوچک", "hi": "छोटा तारा", "ps": "کوچنۍ ستوری", "ar": "نجمة صغيرة"},
    "strong_support": {"en": "Strong support", "ur": "مضبوط سہارا", "fa": "پشتیبانی استوار", "hi": "मज़बूत सहारा", "ps": "پیاوړی ملاتړ", "ar": "سند قوي"},
    "nourishing": {"en": "Nourishing, tender", "ur": "پالنے والی، نرم", "fa": "پرورنده، لطیف", "hi": "पोषण करने वाली, कोमल", "ps": "پالونکې، نرمه", "ar": "حانية، لطيفة"},
    "mother_prophet": {"en": "Mother of the Prophet", "ur": "نبی کی والدہ", "fa": "مادر پیامبر", "hi": "पैग़ंबर की माता", "ps": "د پیغمبر مور", "ar": "أم النبي"},
    "righteous_blessed": {"en": "Righteous, blessed", "ur": "نیک، بابرکت", "fa": "نیکوکار، مبارک", "hi": "धर्मात्मा, धन्य", "ps": "نیک، برکت والا", "ar": "أيمن، مبارك"},
    "trustworthy": {"en": "Trustworthy, responsible", "ur": "امانتدار، ذمہ دار", "fa": "امین، مسئول", "hi": "विश्वसनीय, ज़िम्मेदार", "ps": "امانتدار، مسؤل", "ar": "أمين، مسؤول"},
    "mountain_spring": {"en": "Mountain spring", "ur": "پہاڑی چشمہ", "fa": "چشمهٔ کوه", "hi": "पहाड़ी झरना", "ps": "د غر چینه", "ar": "نبع الجبل"},
    "graceful": {"en": "Graceful, pleasing", "ur": "خوبصورت، دلکش", "fa": "زیبا، دل‌انگیز", "hi": "सुंदर, मनोहर", "ps": "ښکلی، زړه ښکلی", "ar": "جميلة، لطيفة"},
    "gentle_pleasing": {"en": "Gentle, pleasing", "ur": "نرم، دلکش", "fa": "نرم، دل‌انگیز", "hi": "कोमल, मनोहर", "ps": "نرمه، زړه ښکلی", "ar": "لطيفة، جميلة"},
    "noble_honourable": {"en": "Noble, honourable", "ur": "نجیب، معزز", "fa": "نجیب، محترم", "hi": "कुलीन, सम्मानित", "ps": "نجیب، دروند", "ar": "نبيلة، مكرّمة"},
    "living_mountain": {"en": "Living mountain", "ur": "زندہ پہاڑ", "fa": "کوه زنده", "hi": "जीवित पर्वत", "ps": "ژوندی غر", "ar": "جبل حي"},
    "high_noble": {"en": "High, noble", "ur": "بلند، نجیب", "fa": "بلند، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عالي، نبيل"},
    "gentle_delicate": {"en": "Gentle, delicate", "ur": "نرم، نازک", "fa": "نرم، لطیف", "hi": "कोमल, नाज़ुक", "ps": "نرمه، نازکه", "ar": "لطيفة، ناعمة"},
    "elegant": {"en": "Elegant, beautiful one", "ur": "خوبصورت، شائستہ", "fa": "شیک، زیبا", "hi": "सुरुचिपूर्ण, सुंदर", "ps": "ښکلی، شیک", "ar": "أنيقة، جميلة"},
    "nourishment": {"en": "Nourishment, grace", "ur": "پرورش، فضل", "fa": "پرورش، لطف", "hi": "पोषण, कृपा", "ps": "پالنه، فضل", "ar": "غذاء، نعمة"},
    "life_soul": {"en": "Life, soul", "ur": "زندگی، روح", "fa": "زندگی، جان", "hi": "जीवन, आत्मा", "ps": "ژوند، روح", "ar": "عيش، روح"},
    "alive_living": {"en": "Alive, living", "ur": "زندہ، جیتی", "fa": "زنده، پاینده", "hi": "जीवित, जीवंत", "ps": "ژوندې، پاتې", "ar": "عائشة، حية"},
    "alive_prosperous": {"en": "Alive, prosperous", "ur": "زندہ، خوشحال", "fa": "زنده، کامروا", "hi": "जीवित, समृद्ध", "ps": "ژوندې، هوسا", "ar": "عائشة، مزدهرة"},
    "helpful_one": {"en": "Helpful one", "ur": "مددگار", "fa": "یاری‌گر", "hi": "सहायक", "ps": "مرسته کوونکې", "ar": "معينة، ناصرة"},
    "gods_gift": {"en": "God's gift", "ur": "خدا کا تحفہ", "fa": "هدیهٔ خدا", "hi": "ईश्वर का उपहार", "ps": "د خدای ډالۍ", "ar": "عطاء الله"},
    "help_support": {"en": "Help, support", "ur": "مدد، سہارا", "fa": "کمک، پشتیبانی", "hi": "मदद, सहारा", "ps": "مرسته، ملاتړ", "ar": "عون، نصرة"},
    "spring_season": {"en": "Spring (season)", "ur": "بہار", "fa": "بهار", "hi": "वसंत", "ps": "پسرلی", "ar": "ربيع"},
    "strong_brave": {"en": "Strong, brave", "ur": "طاقتور، بہادر", "fa": "نیرومند، دلیر", "hi": "शक्तिशाली, बहादुर", "ps": "پیاوړی، زړور", "ar": "قوي، شجاع"},
    "living_radiant": {"en": "Living, radiant", "ur": "زندہ، روشن", "fa": "زنده، فروزان", "hi": "जीवित, उज्ज्वल", "ps": "ژوندې، روښانه", "ar": "حية، مشرقة"},
    "helper_needy": {"en": "Helper of the needy", "ur": "ضرورتمندوں کی مددگار", "fa": "یاری‌گر نیازمندان", "hi": "ज़रूरतमंदों की सहायक", "ps": "د اړمنو مرسته کوونکې", "ar": "معينة المحتاجين"},
    "glorifying": {"en": "Glorifying God", "ur": "خدا کی تسبیح کرنے والی", "fa": "تسبیح‌گوی خدا", "hi": "ईश्वर की स्तुति करने वाली", "ps": "د خدای تسبیح ویونکې", "ar": "مسبّحة، حامدة"},
    "delightful": {"en": "Delightful, pleasing", "ur": "دلکش، خوشگوار", "fa": "دل‌انگیز، خوشایند", "hi": "मनोहर, सुखद", "ps": "زړه ښکلی، خوږ", "ar": "لذيذة، محبوبة"},
    "noble_exalted": {"en": "Noble, exalted", "ur": "نجیب، بلند", "fa": "نجیب، والا", "hi": "कुलीन, उच्च", "ps": "نجیب، لوړ", "ar": "نبيلة، مرفوعة"},
    "delicate_fragile": {"en": "Delicate, fragile", "ur": "نازک، نرم", "fa": "لطیف، نازک", "hi": "नाज़ुक, कोमल", "ps": "نازکه، نرمه", "ar": "لطيفة، رقيقة"},
    "warrior_leader": {"en": "Warrior, leader", "ur": "جنگجو، سردار", "fa": "جنگاور، سردار", "hi": "योद्धा, नेता", "ps": "جنګیالی، مشر", "ar": "محارب، قائد"},
    "leader_elder": {"en": "Leader, elder, respected one", "ur": "سردار، بزرگ، معزز", "fa": "سردار، بزرگ، محترم", "hi": "नेता, बुज़ुर्ग, सम्मानित", "ps": "مشر، دروند", "ar": "قائد، شيخ، محترم"},
    "good_news": {"en": "One who brings good news", "ur": "خوشخبری دینے والا", "fa": "مژده‌آور", "hi": "शुभ समाचार देने वाला", "ps": "زېری ورکوونکی", "ar": "مبشّر، بشير"},
    "skilled_archer": {"en": "Skilled archer", "ur": "ماہر تیرانداز", "fa": "کماندار ماهر", "hi": "कुशल धनुर्धर", "ps": "ماهر کمانګر", "ar": "رامٍ ماهر"},
    "shining_light": {"en": "Shining light", "ur": "چمکتی روشنی", "fa": "نور درخشان", "hi": "चमकती रोशनी", "ps": "روښانه رڼا", "ar": "نور ساطع"},
    "fair_just": {"en": "Fair, just, peaceful", "ur": "منصف، عادل، پرامن", "fa": "دادگر، عادل، صلح‌آمیز", "hi": "न्यायप्रिय, शांतिपूर्ण", "ps": "منصف، عادل، سوله‌ای", "ar": "عادل، منصف، سلمي"},
    "fair_pure": {"en": "Fair, pure", "ur": "خوبصورت، پاک", "fa": "زیبا، پاک", "hi": "सुंदर, पवित्र", "ps": "ښکلی، پاک", "ar": "جميل، نقي"},
    "divine_light": {"en": "Divine light", "ur": "خدائی روشنی", "fa": "نور الهی", "hi": "ईश्वरीय प्रकाश", "ps": "الهي رڼا", "ar": "نور إلهي"},
    "radiant_shining": {"en": "Radiant, shining", "ur": "چمکتا، درخشاں", "fa": "درخشان، فروزان", "hi": "चमकदार, दीप्त", "ps": "روښانه، ځلانده", "ar": "مشرق، لامع"},
    "health_wellbeing": {"en": "Health, well-being", "ur": "صحت، تندرستی", "fa": "تندرستی، سلامت", "hi": "स्वास्थ्य, कुशलता", "ps": "روغتیا، سکون", "ar": "عافية، صحة"},
    "superior_best": {"en": "Superior, best, excellent", "ur": "برتر، بہترین", "fa": "برتر، بهترین", "hi": "श्रेष्ठ, सर्वोत्तम", "ps": "غوره، برتر", "ar": "أفضل، فاضل"},
    "pure_innocent": {"en": "Pure, innocent, radiant", "ur": "پاک، معصوم، روشن", "fa": "پاک، معصوم، فروزان", "hi": "पवित्र, निर्दोष, उज्ज्वल", "ps": "پاک، معصوم، روښانه", "ar": "نقية، بريئة، مشرقة"},
    "divine_sublime": {"en": "Divine, sublime, spiritual", "ur": "خدائی، بلند، روحانی", "fa": "الهی، والا، معنوی", "hi": "ईश्वरीय, उच्च, आध्यात्मिक", "ps": "الهي، لوړ، روحاني", "ar": "إلهي، جليل، روحي"},
    "gifted_generous": {"en": "Gifted, generous", "ur": "باصلاحیت، سخی", "fa": "بااستعداد، بخشنده", "hi": "प्रतिभाशाली, उदार", "ps": "ځیرک، سخي", "ar": "موهوب، كريم"},
    "better_beautiful": {"en": "Better, more beautiful", "ur": "بہتر، زیادہ خوبصورت", "fa": "بهتر، زیباتر", "hi": "बेहतर, अधिक सुंदर", "ps": "غوره، ښکلی", "ar": "أحسن، أجمل"},
    "gift_of_god": {"en": "Gift of God", "ur": "خدا کا تحفہ", "fa": "هدیهٔ خدا", "hi": "ईश्वर का उपहार", "ps": "د خدای ډالۍ", "ar": "عطاء الله"},
    "gardener_protector": {"en": "Gardener, protector", "ur": "باغبان، محافظ", "fa": "باغبان، نگهبان", "hi": "माली, रक्षक", "ps": "باغوان، ساتونکی", "ar": "بستاني، حافظ"},
    "father_mountain": {"en": "Father of a mountain", "ur": "پہاڑ کا باپ", "fa": "پدر کوه", "hi": "पर्वत के पिता", "ps": "د غر پلار", "ar": "أبو الجبل"},
    "mountain_lion": {"en": "Mountain lion", "ur": "پہاڑی شیر", "fa": "شیر کوهی", "hi": "पहाड़ी शेर", "ps": "د غر زمری", "ar": "أسد الجبل"},
    "noble": {"en": "Noble", "ur": "نجیب", "fa": "نجیب", "hi": "कुलीन", "ps": "نجیب", "ar": "نبيل"},
    "noble_and_blessed": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "most_praised": {"en": "Most praised", "ur": "سب سے زیادہ تعریف کیا ہوا", "fa": "ستوده‌ترین", "hi": "सर्वाधिक प्रशंसित", "ps": "ډېر ستایل شوی", "ar": "أحمد، محمود"},
    "elegant_beautiful": {"en": "Elegant, beautiful one", "ur": "خوبصورت، شائستہ", "fa": "شیک، زیبا", "hi": "सुरुचिपूर्ण, सुंदर", "ps": "ښکلی، شیک", "ar": "أنيقة، جميلة"},
    "nourishment_grace": {"en": "Nourishment, grace", "ur": "پرورش، فضل", "fa": "پرورش، لطف", "hi": "पोषण, कृपा", "ps": "پالنه، فضل", "ar": "غذاء، نعمة"},
    "life": {"en": "Life", "ur": "زندگی", "fa": "زندگی", "hi": "जीवन", "ps": "ژوند", "ar": "حياة"},
    "grace_forgiveness": {"en": "Grace, forgiveness", "ur": "فضل، بخشش", "fa": "لطف، بخشش", "hi": "कृपा, क्षमा", "ps": "فضل، بخښنه", "ar": "فضل، مغفرة"},
    "delicate": {"en": "Delicate, fragile", "ur": "نازک، نرم", "fa": "لطیف، نازک", "hi": "नाज़ुक, कोमल", "ps": "نازکه، نرمه", "ar": "لطيفة، رقيقة"},
    "exalted_sublime": {"en": "Exalted, sublime", "ur": "بلند، عظیم", "fa": "والا، عظیم", "hi": "उच्च, महान", "ps": "لوړ، عظیم", "ar": "مرفوع، جليل"},
    "warrior": {"en": "Warrior, leader", "ur": "جنگجو، سردار", "fa": "جنگاور، سردار", "hi": "योद्धा, नेता", "ps": "جنګیالی، مشر", "ar": "محارب، قائد"},
    "leader": {"en": "Leader, elder, respected one", "ur": "سردار، بزرگ", "fa": "سردار، بزرگ", "hi": "नेता, बुज़ुर्ग", "ps": "مشر، دروند", "ar": "قائد، شيخ"},
    "elegant_graceful": {"en": "Elegant, graceful", "ur": "خوبصورت، شائستہ", "fa": "شیک، زیبا", "hi": "सुरुचिपूर्ण, सुंदर", "ps": "ښکلی، شیک", "ar": "أنيقة، جميلة"},
    "moonlight_night": {"en": "Moonlight", "ur": "چاندنی", "fa": "مهتاب", "hi": "चाँदनी", "ps": "سپوږمۍ رڼا", "ar": "ضوء القمر"},
    "noble_exalted_agrin": {"en": "Noble, exalted", "ur": "نجیب، بلند", "fa": "نجیب، والا", "hi": "कुलीन, उच्च", "ps": "نجیب، لوړ", "ar": "نبيلة، مرفوعة"},
    "promise_covenant": {"en": "Promise, covenant", "ur": "وعدہ، عہد", "fa": "وعده، پیمان", "hi": "वचन, संधि", "ps": "لوظ، تړون", "ar": "وعد، عهد"},
    "given_by_allah": {"en": "Given by Allah", "ur": "اللہ کی دی ہوئی", "fa": "دادهٔ خدا", "hi": "अल्लाह की दी हुई", "ps": "د الله ورکړل شوې", "ar": "عطاء الله"},
    "moonlight_ahina": {"en": "Moonlight", "ur": "چاندنی", "fa": "مهتاب", "hi": "चाँदनी", "ps": "سپوږمۍ رڼا", "ar": "ضوء القمر"},
    "dew_ahlaam": {"en": "Dew", "ur": "شبنم", "fa": "شبنم", "hi": "ओस", "ps": "شبنم", "ar": "ندى"},
    "noble_blessed_ahlia": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "joyful_ahoo": {"en": "Joyful", "ur": "خوش", "fa": "شاد", "hi": "प्रसन्न", "ps": "خوشحاله", "ar": "فرِح"},
    "moonlight_ahoora": {"en": "Moonlight", "ur": "چاندنی", "fa": "مهتاب", "hi": "चाँदनी", "ps": "سپوږمۍ رڼا", "ar": "ضوء القمر"},
    "fame_greatness_ahram": {"en": "Fame, greatness", "ur": "شہرت، عظمت", "fa": "نام‌آوری، بزرگی", "hi": "प्रसिद्धि, महानता", "ps": "نام، لویۍ", "ar": "شهرة، عظمة"},
    "gift_ahsun": {"en": "Gift", "ur": "تحفہ", "fa": "هدیه", "hi": "उपहार", "ps": "ډالۍ", "ar": "هدية"},
    "gift_of_god_ahtasham": {"en": "Gift of God", "ur": "خدا کا تحفہ", "fa": "هدیهٔ خدا", "hi": "ईश्वर का उपहार", "ps": "د خدای ډالۍ", "ar": "عطاء الله"},
    "elevated_noble_ahtesham": {"en": "Elevated, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "مرفوع، نبيل"},
    "dignity_magnificence": {"en": "Dignity, magnificence, grace", "ur": "وقار، شان، فضل", "fa": "وقار، شکوه، لطف", "hi": "गरिमा, वैभव, कृपा", "ps": "وقار، لویۍ، فضل", "ar": "احتشام، عظمة، فضل"},
    "gardener_protector_ahtsham": {"en": "Gardener, protector", "ur": "باغبان، محافظ", "fa": "باغبان، نگهبان", "hi": "माली, रक्षक", "ps": "باغوان، ساتونکی", "ar": "بستاني، حافظ"},
    "from_ahvaz": {"en": "From Ahvaz (city in Iran)", "ur": "اہواز سے", "fa": "اهل اهواز", "hi": "अहवाज़ से", "ps": "د اهواز څخه", "ar": "من الأحواز"},
    "river_ahwaz": {"en": "River", "ur": "دریا", "fa": "رود", "hi": "नदी", "ps": "سیند", "ar": "نهر"},
    "guided_enlightened": {"en": "Guided or enlightened", "ur": "ہدایت یافتہ یا روشن", "fa": "هدایت‌یافته یا روشن", "hi": "मार्गदर्शित या प्रबुद्ध", "ps": "هدایت شوی یا روښانه", "ar": "مهتدي أو مستنير"},
    "helper_supporter": {"en": "Helper, supporter", "ur": "مددگار، معاون", "fa": "یاری‌گر، پشتیبان", "hi": "सहायक, समर्थक", "ps": "مرسته کوونکی، ملاتړی", "ar": "معين، ناصر"},
    "father_mountain_aibek": {"en": "Father of a mountain", "ur": "پہاڑ کا باپ", "fa": "پدر کوه", "hi": "पर्वत के पिता", "ps": "د غر پلار", "ar": "أبو الجبل"},
    "successor_supporter": {"en": "Successor, supporter", "ur": "جانشین، حامی", "fa": "جانشین، پشتیبان", "hi": "उत्तराधिकारी, समर्थक", "ps": "ځای ناستی، ملاتړی", "ar": "خليفة، ناصر"},
    "journey_pilgrimage": {"en": "Journey, pilgrimage", "ur": "سفر، زیارت", "fa": "سفر، زیارت", "hi": "यात्रा, तीर्थयात्रा", "ps": "سفر، زیارت", "ar": "رحلة، حج"},
    "helper_aidan": {"en": "Helper", "ur": "مددگار", "fa": "یاری‌گر", "hi": "सहायक", "ps": "مرسته کوونکی", "ar": "معين"},
    "helpful_supportive": {"en": "Helpful, supportive", "ur": "مددگار، معاون", "fa": "یاری‌گر، پشتیبان", "hi": "सहायक, समर्थक", "ps": "مرسته کوونکې، ملاتړې", "ar": "معينة، ناصرة"},
    "festival_moon_aidil": {"en": "Festival of the moon", "ur": "چاند کا تہوار", "fa": "جشن ماه", "hi": "चाँद का उत्सव", "ps": "د سپوږمۍ جشن", "ar": "عيد القمر"},
    "living_one_aiesha": {"en": "Living one", "ur": "زندہ، جیتی", "fa": "زنده", "hi": "जीवित", "ps": "ژوندې", "ar": "عائشة، حية"},
    "little_star_aigul": {"en": "Little star", "ur": "چھوٹا ستارہ", "fa": "ستارهٔ کوچک", "hi": "छोटा तारा", "ps": "کوچنۍ ستوری", "ar": "نجمة صغيرة"},
    "strong_support_aijaz": {"en": "Strong support", "ur": "مضبوط سہارا", "fa": "پشتیبانی استوار", "hi": "मज़बूत सहारा", "ps": "پیاوړی ملاتړ", "ar": "سند قوي"},
    "nourishing_tender": {"en": "Nourishing, tender", "ur": "پالنے والی، نرم", "fa": "پرورنده، لطیف", "hi": "पोषण करने वाली, कोमल", "ps": "پالونکې، نرمه", "ar": "حانية، لطيفة"},
    "mother_prophet_aima": {"en": "Mother of the Prophet", "ur": "نبی کی والدہ", "fa": "مادر پیامبر", "hi": "पैग़ंबर की माता", "ps": "د پیغمبر مور", "ar": "أم النبي"},
    "hope_desire": {"en": "Hope, desire", "ur": "امید، خواہش", "fa": "امید، آرزو", "hi": "आशा, इच्छा", "ps": "هيله، ارمان", "ar": "أمل، رجاء"},
    "righteous_blessed_aiman": {"en": "Righteous, blessed", "ur": "نیک، بابرکت", "fa": "نیکوکار، مبارک", "hi": "धर्मात्मा, धन्य", "ps": "نیک، برکت والا", "ar": "أيمن، مبارك"},
    "trustworthy_responsible": {"en": "Trustworthy, responsible", "ur": "امانتدار، ذمہ دار", "fa": "امین، مسئول", "hi": "विश्वसनीय, ज़िम्मेदार", "ps": "امانتدار، مسؤل", "ar": "أمين، مسؤول"},
    "eye_beautiful": {"en": "Eye; beautiful, unique", "ur": "آنکھ، خوبصورت، منفرد", "fa": "چشم، زیبا، یگانه", "hi": "आँख, सुंदर, अनोखा", "ps": "سترګه، ښکلی، ځانګړی", "ar": "عين، جميل، فريد"},
    "living_one_aina": {"en": "The living one", "ur": "زندہ، جیتی", "fa": "زنده", "hi": "जीवित", "ps": "ژوندې", "ar": "حية، عائشة"},
    "eye_sight": {"en": "Eye, sight", "ur": "آنکھ، نظر", "fa": "چشم، بینایی", "hi": "आँख, दृष्टि", "ps": "سترګه، لید", "ar": "عين، بصر"},
    "mountain_spring_ainan": {"en": "Mountain spring", "ur": "پہاڑی چشمہ", "fa": "چشمهٔ کوه", "hi": "पहाड़ी झरना", "ps": "د غر چینه", "ar": "نبع الجبل"},
    "eye_ainaz": {"en": "Eye", "ur": "آنکھ", "fa": "چشم", "hi": "आँख", "ps": "سترګه", "ar": "عين"},
    "graceful_pleasing": {"en": "Graceful, pleasing", "ur": "خوبصورت، دلکش", "fa": "زیبا، دل‌انگیز", "hi": "सुंदर, मनोहर", "ps": "ښکلی، زړه ښکلی", "ar": "جميلة، لطيفة"},
    "gentle_pleasing_aini": {"en": "Gentle, pleasing", "ur": "نرم، دلکش", "fa": "نرم، دل‌انگیز", "hi": "कोमल, मनोहर", "ps": "نرمه، زړه ښکلی", "ar": "لطيفة، جميلة"},
    "eye_ainul": {"en": "Eye of (construct)", "ur": "کی آنکھ", "fa": "چشمِ", "hi": "की आँख", "ps": "د سترګه", "ar": "عين الـ"},
    "eye_ainun": {"en": "Eye", "ur": "آنکھ", "fa": "چشم", "hi": "आँख", "ps": "سترګه", "ar": "عين"},
    "noble_honourable_ainy": {"en": "Noble, honourable", "ur": "نجیب، معزز", "fa": "نجیب، محترم", "hi": "कुलीन, सम्मानित", "ps": "نجیب، دروند", "ar": "نبيلة، مكرّمة"},
    "living_mountain_aira": {"en": "Living mountain", "ur": "زندہ پہاڑ", "fa": "کوه زنده", "hi": "जीवित पर्वत", "ps": "ژوندی غر", "ar": "جبل حي"},
    "high_noble_airaam": {"en": "High, noble", "ur": "بلند، نجیب", "fa": "بلند، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عالي، نبيل"},
    "gentle_delicate_airah": {"en": "Gentle, delicate", "ur": "نرم، نازک", "fa": "نرم، لطیف", "hi": "कोमल, नाज़ुक", "ps": "نرمه، نازکه", "ar": "لطيفة، ناعمة"},
    "elegant_beautiful_aireen": {"en": "Elegant, beautiful one", "ur": "خوبصورت، شائستہ", "fa": "شیک، زیبا", "hi": "सुरुचिपूर्ण, सुंदर", "ps": "ښکلی، شیک", "ar": "أنيقة، جميلة"},
    "nourishment_grace_aisana": {"en": "Nourishment, grace", "ur": "پرورش، فضل", "fa": "پرورش، لطف", "hi": "पोषण, कृपा", "ps": "پالنه، فضل", "ar": "غذاء، نعمة"},
    "life_soul_aish": {"en": "Life, soul", "ur": "زندگی، روح", "fa": "زندگی، جان", "hi": "जीवन, आत्मा", "ps": "ژوند، روح", "ar": "عيش، روح"},
    "alive_living_aishah": {"en": "Alive, living", "ur": "زندہ، جیتی", "fa": "زنده، پاینده", "hi": "जीवित, जीवंत", "ps": "ژوندې، پاتې", "ar": "عائشة، حية"},
    "alive_prosperous_aishat": {"en": "Alive, prosperous", "ur": "زندہ، خوشحال", "fa": "زنده، کامروا", "hi": "जीवित, समृद्ध", "ps": "ژوندې، هوسا", "ar": "عائشة، مزدهرة"},
    "helpful_one_aisooda": {"en": "Helpful one", "ur": "مددگار", "fa": "یاری‌گر", "hi": "सहायक", "ps": "مرسته کوونکې", "ar": "معينة، ناصرة"},
    "gods_gift_aissa": {"en": "God's gift", "ur": "خدا کا تحفہ", "fa": "هدیهٔ خدا", "hi": "ईश्वर का उपहार", "ps": "د خدای ډالۍ", "ar": "عطاء الله"},
    "help_support_aisy": {"en": "Help, support", "ur": "مدد، سہارا", "fa": "کمک، پشتیبانی", "hi": "मदद, सहारा", "ps": "مرسته، ملاتړ", "ar": "عون، نصرة"},
    "life_aisya": {"en": "Life", "ur": "زندگی", "fa": "زندگی", "hi": "जीवन", "ps": "ژوند", "ar": "حياة"},
    "life_aiya": {"en": "Life", "ur": "زندگی", "fa": "زندگی", "hi": "जीवन", "ps": "ژوند", "ar": "حياة"},
    "spring_aiyan": {"en": "Spring", "ur": "بہار", "fa": "بهار", "hi": "वसंत", "ps": "پسرلی", "ar": "ربيع"},
    "strong_brave_aiyaz": {"en": "Strong, brave", "ur": "طاقتور، بہادر", "fa": "نیرومند، دلیر", "hi": "शक्तिशाली, बहादुर", "ps": "پیاوړی، زړور", "ar": "قوي، شجاع"},
    "living_one_aiysha": {"en": "Living one, giver of life", "ur": "زندہ، زندگی دینے والی", "fa": "زنده، زندگی‌بخش", "hi": "जीवित, जीवनदायिनी", "ps": "ژوندې، ژوند ورکوونکې", "ar": "عائشة، مانحة الحياة"},
    "help_support_aiz": {"en": "Help, support", "ur": "مدد، سہارا", "fa": "کمک، پشتیبانی", "hi": "मदद, सहारा", "ps": "مرسته، ملاتړ", "ar": "عون، نصرة"},
    "living_radiant_aiza": {"en": "Living, radiant", "ur": "زندہ، روشن", "fa": "زنده، فروزان", "hi": "जीवित, उज्ज्वल", "ps": "ژوندې، روښانه", "ar": "حية، مشرقة"},
    "helper_needy_aizada": {"en": "Helper of the needy", "ur": "ضرورتمندوں کی مددگار", "fa": "یاری‌گر نیازمندان", "hi": "ज़रूरतमंदों की सहायक", "ps": "د اړمنو مرسته کوونکې", "ar": "معينة المحتاجين"},
    "glorifying_aizah": {"en": "Glorifying God", "ur": "خدا کی تسبیح کرنے والی", "fa": "تسبیح‌گوی خدا", "hi": "ईश्वर की स्तुति करने वाली", "ps": "د خدای تسبیح ویونکې", "ar": "مسبّحة، حامدة"},
}

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "afshan": ("افشان", "افشان", "افشان", "अफ़शान", "افشان", "scatterer", "Persian", "Female", None, "not established", "high", "Persian afshān ('scatterer, sprinkler'), from afshāndan. The source record's form أفشان is a transliteration; the Persian spelling is افشان."),
 "afshar": ("افشار", "افشار", "افشار", "अफ़शार", "افشار", "skilled_archer", "Persian", "Male", None, "not established", "low", "Afshār is the name of an Oghuz Turkic tribe (the Afsharid dynasty). The source record's gloss 'Skilled archer' is a folk explanation and is not asserted."),
 "afsheen": ("افشین", "افشین", "افشین", "अफ़शीन", "افشین", "ruler", "Persian", "Unisex", None, "not established", "medium", "Variant romanization of افشین (Afshīn). The source record's gloss 'Shining light' is unsupported."),
 "afshin": ("افشین", "افشین", "افشین", "अफ़शीन", "افشین", "ruler", "Persian", "Male", None, "not established", "high", "Afshīn was the title of the rulers of Ushrusana in Transoxiana; the name is traced to Avestan Pisinah and is linked to Old Iranian xšāyati ('king, ruler'). The source record's gloss 'Fair, Just, Peaceful' is unsupported."),
 "afsoon": ("افسون", "افسون", "افسون", "अफ़सून", "افسون", "charm", "Persian", "Female", None, "not established", "high", "Persian afsūn ('charm, spell, enchantment'). The source record's form عفون is not the Persian spelling."),
 "aftaab": ("آفتاب", "آفتاب", "آفتاب", "आफ़ताब", "آفتاب", "sun", "Persian", "Unisex", None, "not established", "high", "Persian āftāb ('sun, sunlight'), from Middle Persian āftāb. The source record's gloss 'Divine light' is an extension."),
 "aftab": ("آفتاب", "آفتاب", "آفتاب", "आफ़ताब", "آفتاب", "sun", "Persian", "Male", None, "not established", "high", "Variant romanization of آفتاب."),
 "aftar": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أفتر with the gloss 'The one who brings good news', which is unsupported. No verified identification was established and no gloss is asserted."),
 "afwan": ("عفوان", "عفوان", None, "अफ़वान", "عفوان", "forgiveness", "Arabic", "Male", "ع ف و", "root ع ف و occurs in the Qur'an; عفوان is a normal Arabic form", "medium", "Related to عفو ('pardon, forgiveness'). The source record's form أفوان is not a standard Arabic form."),
 "afya": ("عافية", "عافیہ", None, "आफ़िया", "عافيه", "health_wellbeing", "Arabic", "Female", "ع ف و", "not established", "high", "Variant romanization of عافية ('health, well-being')."),
 "afza": ("افزا", "افزا", "افزا", "अफ़ज़ा", "افزا", "increasing", "Persian", "Female", None, "not established", "medium", "Persian afzā ('increasing, augmenting'), as in the compound jān-afzā. The source record's gloss 'Delicate, Fragile' is unsupported."),
 "afzaal": ("أفضل", "افضل", None, "अफ़ज़ाल", "افضل", "excellence", "Arabic", "Male", "ف ض ل", "root ف ض ل occurs in the Qur'an; أفضل is the elative of فاضل", "high", "Variant romanization of أفضل (afḍal)."),
 "afzal": ("أفضل", "افضل", None, "अफ़ज़ल", "افضل", "superior_best", "Arabic", "Male", "ف ض ل", "root ف ض ل occurs in the Qur'an; أفضل is the elative of فاضل", "high", "Afḍal ('better, best, superior'), elative of فاضل."),
 "aga": ("آقا", "آقا", "آقا", "आग़ा", "آقا", "lord_master", "Turkish", "Male", None, "not established", "medium", "Agha/Āqā ('lord, master, elder'), a Turkish-Persian honorific. The source record classified it as Arabic, which is incorrect."),
 "agha": ("آغا", "آغا", "آغا", "आग़ा", "آغا", "leader_elder", "Turkish", "Unisex", None, "not established", "medium", "Variant romanization of آقا/آغا. The source record classified it as Arabic, which is incorrect."),
 "aghigh": ("عقيق", "عقیق", None, "अक़ीक़", "عقيق", "agate", "Arabic", "Unisex", "ع ق ق", "not established", "medium", "ʿAqīq ('agate'), also the name of a valley near Medina. The source record's gloss 'Elegant' is unsupported."),
 "aghil": ("عقيل", "عقیل", None, "अक़ील", "عقيل", "intelligent", "Arabic", "Male", "ع ق ل", "not established", "high", "ʿAqīl, diminutive of عقل ('intellect'); also the name of ʿAqīl ibn Abī Ṭālib. The source record's gloss 'Mountain Lion' is unsupported."),
 "aghla": ("أغلى", "اغلی", None, "अग़ला", "اغلى", "precious", "Arabic", "Female", "غ ل و", "not established", "medium", "Aghlā, elative of غالي ('precious, dear'). The source record's gloss 'Delightful, Pleasing' is unsupported."),
 "agrin": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أجريت with the gloss 'Noble, Exalted', which is unsupported. No verified identification was established and no gloss is asserted."),
 "ahab": ("أخاب", "اخاب", None, "अहाब", "اخاب", "king_ahab", "Hebrew", "Male", None, "not established", "medium", "Ahab (אַחְאָב) was a king of Israel in the 9th century BCE. It is a Hebrew name, not Arabic; the source record's gloss 'Father of Ahab' is unsupported."),
 "ahad": ("أحد", "احد", None, "अहद", "احد", "one_unique", "Arabic", "Male", "أ ح د", "أحد occurs in the Qur'an (Sūrat al-Ikhlāṣ 112:1, 'قل هو الله أحد')", "high", "Aḥad ('one, unique'). The source record's gloss 'One and Only' is a reasonable rendering."),
 "ahbab": ("أحباب", "احباب", None, "अहबाब", "احباب", "beloved_ones", "Arabic", "Male", "ح ب ب", "not established", "high", "Aḥbāb, plural of حبيب ('beloved')."),
 "ahd": ("عهد", "عہد", None, "अहद", "عهد", "covenant", "Arabic", "Unisex", "ع ه د", "root ع ه د occurs in the Qur'an; عهد is a normal Arabic noun", "high", "ʿAhd ('covenant, pledge')."),
 "ahdia": ("أهدية", "اہدایہ", None, "अहदिया", "اهديه", "gifts", "Arabic", "Female", "ه د ي", "not established", "medium", "Ahdiya, plural of هدية ('gift'). The source record's gloss 'Promise, Covenant' is unsupported."),
 "ahdiah": ("أهدية", "اہدایہ", None, "अहदिया", "اهديه", "gifts", "Arabic", "Unisex", "ه د ي", "not established", "medium", "Variant romanization of أهدية. The source record's gloss 'Gift, Reward' is a reasonable rendering."),
 "ahid": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave علي (ʿAlī), which is a different name. The form ahid could not be independently verified and no gloss is asserted."),
 "ahida": ("أحدى", "احدى", None, "अहिदा", "احدى", "given_by_allah", "Arabic", "Female", "أ ح د", "not established", "low", "The source record's gloss 'Given by Allah' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ahin": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أهين with the gloss 'Night', which is unsupported. No verified identification was established and no gloss is asserted."),
 "ahina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أهينة with the gloss 'Moonlight', which is unsupported. No verified identification was established and no gloss is asserted."),
 "ahkam": ("أحكام", "احکام", None, "अहकाम", "احكام", "judgments", "Arabic", "Male", "ح ك م", "root ح ك م occurs in the Qur'an; أحكام is a normal Arabic plural", "high", "Aḥkām, plural of حُكم ('judgment, ruling')."),
 "ahlaam": ("أحلام", "احلام", None, "अहलाम", "احلام", "dreams", "Arabic", "Female", "ح ل م", "root ح ل م occurs in the Qur'an; أحلام is a normal Arabic plural", "high", "Aḥlām, plural of حُلم ('dream'). The source record's gloss 'Dew' is unsupported."),
 "ahlam": ("أحلام", "احلام", None, "अहलाम", "احلام", "dreams", "Arabic", "Female", "ح ل م", "root ح ل م occurs in the Qur'an; أحلام is a normal Arabic plural", "high", "Variant romanization of أحلام. The source record left this name with no origin and no script form."),
 "ahlem": ("أحلام", "احلام", None, "अहलेम", "احلام", "dream_vision", "Arabic", "Female", "ح ل م", "root ح ل م occurs in the Qur'an; أحلام is a normal Arabic plural", "medium", "Variant romanization of أحلام. The source record's gloss 'Divine, Sublime, Spiritual' is unsupported."),
 "ahlia": ("أهلية", "اہلیہ", None, "अहलिया", "اهليه", "competence", "Arabic", "Female", "أ ه ل", "not established", "medium", "Ahliyya ('competence, qualification'). The source record's form عربي_Ahlia is a placeholder, not an Arabic form."),
 "ahmad": ("أحمد", "احمد", None, "अहमद", "احمد", "praiseworthy", "Arabic", "Male", "ح م د", "أحمد occurs in the Qur'an (Sūrat al-Ṣaff 61:6) as a name of the Prophet", "high", "Aḥmad ('most praiseworthy'), elative of حامد; the Prophet's name. The source record left this name with no origin and no script form."),
 "ahmar": ("أحمر", "احمر", None, "अहमर", "احمر", "red", "Arabic", "Male", "ح م ر", "not established", "high", "Aḥmar ('red'). The source record's gloss 'Red, Courageous, Radiant' adds unsupported extensions."),
 "ahmed": ("أحمد", "احمد", None, "अहमद", "احمد", "praiseworthy_ahmad", "Arabic", "Male", "ح م د", "أحمد occurs in the Qur'an (Sūrat al-Ṣaff 61:6) as a name of the Prophet", "high", "Variant romanization of أحمد."),
 "ahmede": ("أحمدي", "احمدی", None, "अहमदी", "احمدي", "most_praised", "Arabic", "Male", "ح م د", "not established", "medium", "Nisba adjective from أحمد. The source record's gloss 'Most Praised' is a reasonable rendering."),
 "ahmer": ("أحمر", "احمر", None, "अहमर", "احمر", "red_courageous", "Arabic", "Male", "ح م ر", "not established", "medium", "Variant romanization of أحمر. The source record's gloss 'Noble' is unsupported."),
 "ahnaf": ("أحنف", "احنف", None, "अहनफ़", "احنف", "clubfooted", "Arabic", "Male", "ح ن ف", "not established", "high", "Aḥnaf ('club-footed' in classical Arabic); the name of al-Aḥnaf ibn Qays, a 7th-century Muslim commander of the Banū Tamīm. The source record's gloss 'Gifted, Generous' is unsupported."),
 "ahoo": ("آهو", "آہو", "آهو", "आहू", "آهو", "gazelle", "Persian", "Female", None, "not established", "high", "Persian āhū ('gazelle, deer'). The source record's gloss 'Joyful' is unsupported."),
 "ahoora": ("اهورا", "اہورا", "اهورا", "अहूरा", "اهورا", "ahura", "Persian", "Female", None, "not established", "medium", "Persian ahūrā, from Avestan ahura ('lord'), as in Ahura Mazda. The source record's gloss 'Moonlight' is unsupported."),
 "ahram": ("أهرام", "اہرام", None, "अहराम", "اهرام", "pyramids", "Arabic", "Male", "ه ر م", "not established", "medium", "Ahrām, plural of هرم ('pyramid'). The source record's gloss 'Fame, Greatness' is unsupported."),
 "ahsan": ("أحسن", "احسن", None, "अहसन", "احسن", "best_beautiful", "Arabic", "Male", "ح س ن", "root ح س ن occurs in the Qur'an; أحسن is the elative of حسن", "high", "Aḥsan ('best, most beautiful'), elative of حَسَن. The source record left this name with no origin and no script form."),
 "ahsen": ("أحسن", "احسن", None, "अहसन", "احسن", "better_beautiful", "Arabic", "Male", "ح س ن", "root ح س ن occurs in the Qur'an; أحسن is the elative of حسن", "high", "Variant romanization of أحسن."),
 "ahsun": ("أحسن", "احسن", None, "अहसुन", "احسن", "gift_ahsun", "Arabic", "Unisex", "ح س ن", "root ح س ن occurs in the Qur'an; أحسن is the elative of حسن", "medium", "Variant romanization of أحسن. The source record's gloss 'Gift' is unsupported."),
 "ahtasham": ("احتشام", "احتشام", None, "अहतिशाम", "احتشام", "gift_of_god_ahtasham", "Arabic", "Male", "ح ش م", "not established", "medium", "Iḥtishām ('dignity, modesty'). The source record's gloss 'Gift of God' is unsupported."),
 "ahtesham": ("احتشام", "احتشام", None, "अहतेशाम", "احتشام", "elevated_noble_ahtesham", "Arabic", "Male", "ح ش م", "not established", "high", "Iḥtishām ('dignity, modesty, magnificence'). The source record's gloss 'Elevated, noble' is an approximation."),
 "ahtisham": ("احتشام", "احتشام", None, "अहतिशाम", "احتشام", "dignity_magnificence", "Arabic", "Male", "ح ش م", "not established", "high", "Iḥtishām ('dignity, magnificence, grace')."),
 "ahtsham": ("احتشام", "احتشام", None, "अहतशाम", "احتشام", "gardener_protector_ahtsham", "Arabic", "Male", "ح ش م", "not established", "medium", "Variant romanization of احتشام. The source record's gloss 'Gardener, Protector' is unsupported."),
 "ahvaz": ("أحواز", "اہواز", "اهواز", "अहवाज़", "اهواز", "from_ahvaz", "Persian", "Male", None, "not established", "medium", "Ahvāz is a city in south-western Iran. The source record's gloss 'From Ahvaz city' is a place-name description rather than a lexical meaning."),
 "ahwaz": ("أحواز", "اہواز", "اهواز", "अहवाज़", "اهواز", "river_ahwaz", "Persian", "Unisex", None, "not established", "medium", "Variant romanization of اهواز. The source record's gloss 'River' is unsupported."),
 "ahyan": ("أحيان", "احیان", None, "अहयान", "احيان", "times", "Arabic", "Male", "ح ي ن", "not established", "low", "Aḥyān, plural of حين ('time'). The source record's gloss 'Guided or Enlightened' is unsupported."),
 "aibak": ("أيبك", "ایبک", None, "ऐबक", "ایبک", "mamluk", "Turkic", "Male", None, "not established", "medium", "Aibak is a Turkic Mamluk name, borne by Qutb al-Dīn Aibak (d. 1210), founder of the Delhi Sultanate. The source record's gloss 'Helper, supporter' is unsupported."),
 "aibek": ("أيبك", "ایبک", None, "ऐबेक", "ایبک", "father_mountain_aibek", "Turkic", "Male", None, "not established", "medium", "Variant romanization of ایبک. The source record's gloss 'Father of a Mountain' is unsupported."),
 "aicha": ("عائشة", "عائشہ", None, "आइशा", "عايشه", "living_one_aiesha", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة. The source record's gloss 'Successor, Supporter' is unsupported."),
 "aida": ("عائدة", "عائدہ", None, "आइदा", "عائده", "returning", "Arabic", "Female", "ع و د", "not established", "high", "ʿĀʾida ('returning, one who returns')."),
 "aidah": ("عائدة", "عائدہ", None, "आइदा", "عائده", "journey_pilgrimage", "Arabic", "Female", "ع و د", "not established", "high", "Variant romanization of عائدة. The source record's gloss 'Journey, Pilgrimage' is unsupported."),
 "aidan": ("أيدن", "ایدن", None, "ऐडन", "ایدن", "helper_aidan", "Irish", "Male", None, "not established", "low", "Aidan is an Irish name (Aodhán, diminutive of Aodh). The source record's form اعدن is not a standard Arabic form and the gloss 'Helper' is unsupported."),
 "aidana": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Aidana' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "aidil": ("عادل", "عادل", None, "आदिल", "عادل", "festival_moon_aidil", "Arabic", "Unisex", "ع د ل", "root ع د ل occurs in the Qur'an; عادل is a normal Arabic adjective", "low", "The source record gave عادل (ʿādil, 'just'), a different meaning. The gloss 'Festival of the moon' is unsupported."),
 "aiesha": ("عائشة", "عائشہ", None, "आइशा", "عايشه", "living_one_aiesha", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة."),
 "aigul": ("آيگول", "آیگل", None, "ऐगुल", "آیګل", "little_star_aigul", "Turkic", "Female", None, "not established", "medium", "Aigul (айгүл) is a Turkic name meaning 'moon flower' (ay 'moon' + gül 'flower'). The source record classified it as Arabic, which is incorrect."),
 "aijaz": ("إعجاز", "اعجاز", None, "एजाज़", "اعجاز", "miracle", "Arabic", "Male", "ع ج ز", "not established", "high", "Iʿjāz ('inimitability, miracle'). The source record's form عجاز is the root rather than the noun."),
 "aila": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عايلي with the gloss 'Nourishing, Tender', which is unsupported. No verified identification was established and no gloss is asserted."),
 "aima": ("أيمة", "ایمہ", None, "ऐमा", "ایمه", "mother_prophet_aima", "Arabic", "Female", "أ م م", "not established", "low", "The source record's gloss 'Mother of Prophet' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aimal": ("ایمل", "ایمل", None, "ऐमल", "ایمل", "hope_desire", "Pashto", "Male", None, "not established", "medium", "Aimal (ایمل) is a Pashto name meaning 'hope, desire'. The source record classified it as Arabic, which is incorrect."),
 "aiman": ("أيمن", "ایمن", None, "ऐमन", "ایمن", "righteous_blessed_aiman", "Arabic", "Unisex", "ي م ن", "not established", "high", "Ayman ('blessed, fortunate, on the right')."),
 "aimen": ("أيمن", "ایمن", None, "ऐमेन", "ایمن", "trustworthy_responsible", "Arabic", "Male", "ي م ن", "not established", "medium", "Variant romanization of أيمن. The source record's form عائمن is malformed."),
 "ain": ("عين", "عین", None, "ऐन", "عين", "eye_beautiful", "Arabic", "Unisex", "ع ي ن", "root ع ي ن occurs in the Qur'an; عين is a normal Arabic noun", "high", "ʿAyn ('eye; spring, source')."),
 "aina": ("عين", "عین", None, "ऐना", "عين", "living_one_aina", "Arabic", "Female", "ع ي ن", "root ع ي ن occurs in the Qur'an; عين is a normal Arabic noun", "medium", "Variant romanization of عين. The source record's gloss 'The Living One' is unsupported."),
 "ainah": ("عينة", "عینہ", None, "ऐनह", "عينه", "eye_sight", "Arabic", "Female", "ع ي ن", "not established", "low", "The source record's gloss 'Eye, Sight' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ainan": ("عنان", "عنان", None, "ऐनान", "عنان", "mountain_spring_ainan", "Arabic", "Unisex", "ع ن ن", "not established", "low", "ʿInān ('reins; clouds'). The source record's gloss 'Mountain spring' is unsupported."),
 "ainaz": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عيناز with the gloss 'Eye', which is unsupported. No verified identification was established and no gloss is asserted."),
 "ainee": ("عيني", "عینی", None, "ऐनी", "عيني", "graceful_pleasing", "Arabic", "Female", "ع ي ن", "not established", "medium", "ʿAynī ('my eye'), a term of endearment. The source record's gloss 'Graceful, Pleasing' is an extension."),
 "aini": ("عيني", "عینی", None, "ऐनी", "عيني", "gentle_pleasing_aini", "Arabic", "Female", "ع ي ن", "not established", "medium", "Variant romanization of عيني."),
 "ainul": ("عين الـ", "عین الـ", None, "ऐनुल", "عين الـ", "eye_ainul", "Arabic", "Female", "ع ي ن", "not established", "medium", "Construct form عين الـ ('eye of'), as in عين الحياة. The source record's gloss 'Eye' is incomplete."),
 "ainun": ("عيون", "عیون", None, "ऐनून", "عيون", "eye_ainun", "Arabic", "Female", "ع ي ن", "not established", "medium", "ʿUyūn, plural of عين. The source record's form عينون is not a standard Arabic plural."),
 "ainy": ("عيني", "عینی", None, "ऐनी", "عيني", "noble_honourable_ainy", "Arabic", "Female", "ع ي ن", "not established", "medium", "Variant romanization of عيني. The source record's gloss 'Noble, Honourable' is unsupported."),
 "aira": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عيرا with the gloss 'Living mountain', which is unsupported. No verified identification was established and no gloss is asserted."),
 "airaam": ("إرام", "ارام", None, "इराम", "ارام", "iram", "Arabic", "Male", "أ ر م", "إرم occurs in the Qur'an (Sūrat al-Fajr 89:7, 'إرم ذات العماد')", "medium", "Iram, the many-columned city mentioned in Sūrat al-Fajr. The source record's gloss 'High, Noble' is unsupported."),
 "airah": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave إيره with the gloss 'Gentle, Delicate', which is unsupported. No verified identification was established and no gloss is asserted."),
 "aireen": ("إيرين", "ایرین", None, "ऐरीन", "ایرین", "elegant_beautiful_aireen", "Greek", "Female", None, "not established", "medium", "Irene/Eileen, ultimately from Greek Εἰρήνη ('peace'). The source record classified it as Arabic, which is incorrect."),
 "aisana": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave اسية with the gloss 'Nourishment, Grace', which is unsupported. No verified identification was established and no gloss is asserted."),
 "aish": ("عيش", "عیش", None, "ऐश", "عيش", "life_soul_aish", "Arabic", "Female", "ع ي ش", "root ع ي ش occurs in the Qur'an; عيش is a normal Arabic noun", "high", "ʿAysh ('life, living, livelihood')."),
 "aisha": ("عائشة", "عائشہ", None, "आइशा", "عايشه", "alive_living_aishah", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة. The source record left this name with no origin and no script form."),
 "aishah": ("عائشة", "عائشہ", None, "आइशा", "عايشه", "alive_living_aishah", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة."),
 "aishat": ("عائشة", "عائشہ", None, "आइशात", "عايشه", "alive_prosperous_aishat", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة."),
 "aisooda": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Ali' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "aissa": ("عيسى", "عیسیٰ", None, "ईसा", "عیسی", "jesus", "Arabic", "Female", "ع ي س", "عيسى is the Qur'anic form of the name of the prophet Jesus and occurs in the Qur'an", "high", "ʿĪsā, the Qur'anic Arabic form of the name Jesus. The source record's gloss 'God's Gift' is unsupported."),
 "aisy": ("عيسى", "عیسیٰ", None, "ईसी", "عیسی", "help_support_aisy", "Arabic", "Female", "ع ي س", "عيسى is the Qur'anic form of the name of the prophet Jesus", "medium", "Variant romanization of عيسى. The source record's gloss 'Help, Support' is unsupported."),
 "aisya": ("عائشة", "عائشہ", None, "आइस्या", "عايشه", "life_aisya", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "medium", "Variant romanization of عائشة. The source record's form عيسى is a different name."),
 "aiya": ("آية", "آیہ", None, "आया", "آيه", "life_aiya", "Arabic", "Female", "أ ي ي", "آية occurs in the Qur'an as a common noun ('sign, verse'); it is not a Qur'anic proper name", "medium", "Āya ('sign, verse'). The source record's form عايه is not a standard Arabic form."),
 "aiyan": ("عيان", "عيان", None, "अयान", "عيان", "spring_aiyan", "Arabic", "Unisex", "ع ي ن", "root ع ي ن occurs in the Qur'an; عيان is a normal Arabic word", "medium", "ʿIyān ('witnessing, observation'). The source record's gloss 'Spring' is unsupported."),
 "aiyaz": ("عياض", "عیاض", None, "इयाज़", "عياض", "iyad", "Arabic", "Male", "ع و ض", "not established", "high", "ʿIyāḍ, borne by the Andalusian scholar Qāḍī ʿIyāḍ (1083-1149). The source record's gloss 'Strong, Brave' is unsupported."),
 "aiysha": ("عائشة", "عائشہ", None, "आइशा", "عايشه", "living_one_aiysha", "Arabic", "Female", "ع ي ش", "عائشة is not a Qur'anic form; it is the name of ʿĀʾisha bint Abī Bakr in the hadith and sīra tradition", "high", "Variant romanization of عائشة."),
 "aiz": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave عيز with the gloss 'Help, Support', which is unsupported. No verified identification was established and no gloss is asserted."),
 "aiza": ("عائزة", "عائزہ", None, "आइज़ा", "عائزه", "living_radiant_aiza", "Arabic", "Female", "ع و ذ", "not established", "low", "The source record's gloss 'Living, Radiant' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aizada": ("أيزادا", "ایزادا", None, "ऐज़ादा", "ایزادا", "helper_needy_aizada", "Turkic", "Female", None, "not established", "low", "Aizada (айзада) is a Turkic/Kazakh name. The source record's gloss 'Helper of the needy' is unsupported."),
 "aizah": ("عائذة", "عائذہ", None, "आइज़ा", "عائذه", "glorifying_aizah", "Arabic", "Female", "ع و ذ", "not established", "medium", "ʿĀʾidha, feminine of عائذ ('one who seeks refuge'). The source record's gloss 'Glorifying God' is unsupported."),
}
