# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 27 (hakem..harisa).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": hakiim -> حاكم (that is hakem, not حكيم);
   halil -> "Unknown"; hammada/hamraz/hanita/hares -> the Latin string repeated in every
   script column; hannah -> عائشة (a different name entirely); hanadi -> هندي;
   harisa -> حريرة; haris -> هاريس; hamid -> Hindi column gave हरम.
 * DEGARBLED glosses: hakem 'judge' was fine but hakiim 'wise' was given the حاكم form;
   hala 'halo' glossed 'mature, ripe'; hameeda 'praiseworthy' glossed 'guide, companion';
   hamidah 'praiseworthy' glossed 'companion, supporter'; hamim 'close friend / hot water'
   glossed 'intense heat, scorching sun'; hammad 'one who praises much' glossed
   'eager to please'; hamzaa (a spelling of حمزة, male) labelled female.
 * MISLABELLED ORIGIN: hamraz is Persian (همراز 'confidant'), not Arabic; hanita and
   hares are not Arabic lexical items at all.
 * JUNK / UNVERIFIABLE ENTRIES: halaa, halah, hallam, hamal, haman, hamdam, hameez,
   hamir, hamiz, hamta, hamud, hanood, hanoon, harim, hares, hanita.
 * DUPLICATE CLUSTERS: hakim/hakiim/hakeem(26)/haqeem; hakima/hakimah;
   haleem/halim; haleema/haleemah/halima/halimah/halimeh/halimat/haleemat/halimatun;
   hamad/hamd; hamed/hamid/hameed/hamiid; hameda/hamida/hameeda/hamidah/hamidat;
   hamdi/hamidi; hammad/hammada/hammadi; hamza/hamzah/hamzaa/hamzat;
   hana/hanaa/hannah; hanan/hanaan/hanane/hannan; hania/haniah/haniya;
   hanif/haneef; hanifa/hanifah/haneefa; haris/harisa.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated26 import GLOSSES as _G26

GLOSSES = dict(_G26)
GLOSSES.update({
    "mature_ripe": {"en": "Mature, ripe, fully grown", "ur": "پختہ، بالغ", "fa": "رسیده، بالغ", "hi": "परिपक्व, वयस्क", "ps": "پوخ، بالغ", "ar": "الناضج، البالغ"},
    "patient_gentle": {"en": "Patient, forbearing, gentle", "ur": "بردبار، حلیم، نرم", "fa": "بردبار، حلیم، نرم", "hi": "धैर्यवान, सहनशील, कोमल", "ps": "زغمناک، نرم", "ar": "الحليم، الصبور، الرفيق"},
    "dove_peaceful": {"en": "Dove; gentle, peaceful", "ur": "کبوتر، فاختہ؛ نرم، پرسکون", "fa": "کبوتر، فاخته؛ آرام", "hi": "कबूतर, पंडुकी; शांत", "ps": "کوتره؛ نرم، ارام", "ar": "الحمامة؛ الوديع، المسالم"},
    "praise_gratitude": {"en": "Praise, thanksgiving, gratitude", "ur": "تعریف، شکر، حمد", "fa": "ستایش، سپاس، حمد", "hi": "प्रशंसा, कृतज्ञता", "ps": "ستاینه، شکر", "ar": "الحمد، الشكر، الثناء"},
    "praiser": {"en": "One who praises, praiser", "ur": "تعریف کرنے والا، حمد کرنے والا", "fa": "ستایشگر، حمدکننده", "hi": "प्रशंसा करने वाला", "ps": "ستایونکی", "ar": "الحمّاد، الحامد، المثني"},
    "praise_of_allah": {"en": "Praise of Allah, thanksgiving to God", "ur": "اللہ کی حمد، شکرِ الٰہی", "fa": "حمد خدا، سپاس خداوند", "hi": "अल्लाह की प्रशंसा", "ps": "د الله حمد", "ar": "حمد الله، شكر الله"},
    "praised_commended": {"en": "Praised, commended, laudable", "ur": "تعریف شدہ، قابلِ تعریف", "fa": "ستوده، پسندیده", "hi": "प्रशंसित, सराहनीय", "ps": "ستایل شوی", "ar": "المحمود، الحميد، الممدوح"},
    "ally_confederate": {"en": "Ally, confederate, one bound by oath", "ur": "حلیف، معاہد", "fa": "هم‌پیمان، متحد", "hi": "सहयोगी, संधिबद्ध", "ps": "متحد، ملګری", "ar": "الحليف، المعاهد"},
    "close_friend": {"en": "Close friend, intimate; also hot water", "ur": "قریبی دوست، گہرا دوست", "fa": "دوست نزدیک، محرم", "hi": "घनिष्ठ मित्र", "ps": "نږدې ملګری", "ar": "الحميم، الصديق المقرب"},
    "bathhouse": {"en": "Bathhouse, public bath", "ur": "حمام، غسل خانہ", "fa": "گرمابه، حمام", "hi": "स्नानगृह, हम्माम", "ps": "حمام، لمبلځی", "ar": "الحمّام"},
    "plant_herb": {"en": "A desert plant, a herb", "ur": "ایک صحرائی پودا، جڑی بوٹی", "fa": "گیاهی بیابانی، سبزی", "hi": "एक मरुस्थलीय पौधा", "ps": "د صحرا بوټی", "ar": "نبات صحراوي، عشبة"},
    "confidant": {"en": "Confidant, intimate companion, one who shares secrets", "ur": "ہمراز، رازدار، محرم", "fa": "همراز، محرم راز", "hi": "राज़दार, विश्वासपात्र", "ps": "همراز، راز ساتونکی", "ar": "الهمراز، المؤانس، صاحب السر"},
    "truth": {"en": "Truth, reality, right", "ur": "سچ، حق، حقیقت", "fa": "حقیقت، راستی، حق", "hi": "सत्य, सच", "ps": "ریښتيا، حق", "ar": "الحق، الحقيقة، الصدق"},
    "forbidden_sacred": {"en": "Forbidden, inviolable; sacred precinct", "ur": "حرام، محترم؛ حرم", "fa": "حرام، محترم؛ حرم", "hi": "वर्जित, पवित्र क्षेत्र", "ps": "حرام، سپېڅلی", "ar": "الحرام، الحرم، المحرّم"},
    "war_battle": {"en": "War, battle, campaign", "ur": "جنگ، لڑائی", "fa": "جنگ، نبرد", "hi": "युद्ध, लड़ाई", "ps": "جګړه", "ar": "الحرب، القتال"},
    "intimate_inner": {"en": "Intimate, innermost, sacred precinct", "ur": "قریبی، اندرونی؛ حرم", "fa": "نزدیک، درونی؛ حرم", "hi": "अंतरंग, आंतरिक", "ps": "نږدې، داخلي", "ar": "الحريم، القريب، الباطن"},
    "freed_from_sin": {"en": "Freed, set free; one freed from sin", "ur": "آزاد، گناہ سے پاک", "fa": "آزاد، رهاشده", "hi": "मुक्त, पाप से छूटा", "ps": "ازاد، خوشې شوی", "ar": "الحرّ، المحرَّر، المعتوق"},
    "young_hare": {"en": "Young hare, rabbit", "ur": "خرگوش کا بچہ", "fa": "خرگوش جوان", "hi": "युवा खरगोश", "ps": "د سوېلي بچی", "ar": "الأرنب الصغير"},
    "free_from_pledges": {"en": "Free from vows, pledges or debts", "ur": "عہد و قرض سے آزاد", "fa": "آزاد از پیمان و دین", "hi": "प्रतिज्ञा और ऋण से मुक्त", "ps": "له ژمنې او پور ازاد", "ar": "الحرّ من العهود والديون"},
    "sweet_pure_clear": {"en": "Sweet, pure, clear", "ur": "میٹھا، خالص، صاف", "fa": "شیرین، پاک، صاف", "hi": "मीठा, शुद्ध, स्वच्छ", "ps": "خوږ، پاک، روښان", "ar": "الحلو، الصافي، النقي"},
    "guardian_custodian": {"en": "Guardian, custodian, watcher", "ur": "محافظ، نگہبان", "fa": "نگهبان، پاسدار", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، پالونکی", "ar": "الحارس، الحافظ، الرقيب"},
    "garden_blooming": {"en": "Garden, orchard; blooming, verdant", "ur": "باغ، گلشن؛ ہرا بھرا", "fa": "باغ، گلستان؛ شکوفا", "hi": "बाग़, उपवन; खिलता", "ps": "باغ، ګلستان", "ar": "الحديقة، الروضة، المزهر"},
    "lion_roar": {"en": "Lion's roar; a bitter desert plant", "ur": "شیر کی دہاڑ؛ ایک صحرائی پودا", "fa": "غرّش شیر؛ گیاهی بیابانی", "hi": "शेर की दहाड़", "ps": "د زمری غړپ", "ar": "زئير الأسد، الحنظل"},
    "contentment": {"en": "Contentment, satisfaction, tranquility", "ur": "قناعت، اطمینان، سکون", "fa": "قناعت، آرامش", "hi": "संतोष, तसल्ली", "ps": "قناعت، ارام", "ar": "القناعة، الرضا، السكينة"},
    "grace_pleasing": {"en": "Grace, favour; pleasing, delightful", "ur": "فضل، نعمت؛ خوشگوار", "fa": "لطف، نعمت؛ دلپذیر", "hi": "कृपा, अनुग्रह; सुखद", "ps": "فضل، نعمت", "ar": "الفضل، النعمة، الهناء"},
    "gracious_merciful": {"en": "Gracious, merciful, compassionate", "ur": "مہربان، رحیم", "fa": "مهربان، بخشنده", "hi": "कृपालु, दयालु", "ps": "مهربان، رحمن", "ar": "الحنّان، الرحيم، العطوف"},
    "learned_one": {"en": "The learned one; follower of the Hanafi school", "ur": "عالم، فقیہ؛ حنفی", "fa": "دانشمند، فقیه؛ حنفی", "hi": "विद्वान, हनफ़ी", "ps": "پوه، حنفي", "ar": "الحنفي، العالم، الفقيه"},
    "monotheist": {"en": "Monotheist; one who inclines to pure worship of God", "ur": "موحد، یکتا پرست", "fa": "موحّد، یکتاپرست", "hi": "एकेश्वरवादी", "ps": "موحد، يوازې د الله عبادت کوونکی", "ar": "الحنيف، الموحّد"},
    "grace_charm": {"en": "Grace, charm, kindness", "ur": "نرمی، دلکشی، مہربانی", "fa": "لطف، دلربایی، مهربانی", "hi": "कोमलता, आकर्षण", "ps": "نرمي، زړه راښکون", "ar": "الحنين، اللطف، الرقة"},
    "grace_beauty": {"en": "Grace, beauty, compassion", "ur": "فضل، حسن، شفقت", "fa": "لطف، زیبایی، دلسوزی", "hi": "कृपा, सौंदर्य", "ps": "فضل، ښکلا", "ar": "الحنان، الجمال، الرحمة"},
    "eager_to_please": {"en": "One who praises much; eager to please", "ur": "بہت تعریف کرنے والا", "fa": "بسیار ستایشگر", "hi": "बहुत प्रशंसा करने वाला", "ps": "ډېر ستایونکی", "ar": "الحمّاد، كثير الحمد"},
    "fortress": {"en": "Fortress, stronghold", "ur": "قلعہ، حصار", "fa": "دژ، قلعه", "hi": "किला, दुर्ग", "ps": "کلا، قلعه", "ar": "الحصن، القلعة"},
    "patience_forbearance": {"en": "Patience, forbearance, endurance", "ur": "صبر، تحمل", "fa": "صبر، شکیبایی", "hi": "धैर्य, सहनशीलता", "ps": "صبر، زغم", "ar": "الصبر، الحلم، الأناة"},
    "red": {"en": "Red, ruddy", "ur": "سرخ، لال", "fa": "سرخ، قرمز", "hi": "लाल, सुर्ख़", "ps": "سور، سره", "ar": "الأحمر، الحمراء"},
    "dedicated_god": {"en": "Dedicated to God, consecrated", "ur": "خدا کے لیے مخصوص", "fa": "وقفِ خدا، نذرِ خدا", "hi": "ईश्वर को समर्पित", "ps": "د الله لپاره وقف", "ar": "الموقوف لله، المنذور"},
    "follower": {"en": "Follower, adherent, one who follows", "ur": "پیروکار، تابع", "fa": "پیرو، تابع", "hi": "अनुयायी, अनुसरण करने वाला", "ps": "پیرو، تابع", "ar": "التابع، الحمّود"},
    "prolonged_stop": {"en": "A glottal stop; the name of the mark hamza", "ur": "ہمزہ، وقفہ", "fa": "همزه", "hi": "हमज़ा (विराम चिह्न)", "ps": "همزه", "ar": "الهمزة"},
    "gift_grace": {"en": "Gift, grace, blessing", "ur": "تحفہ، نعمت", "fa": "هدیه، نعمت", "hi": "उपहार, कृपा", "ps": "ډالۍ، نعمت", "ar": "الهبة، النعمة، العطاء"},
    "companion_friend": {"en": "Companion, friend, intimate", "ur": "ساتھی، دوست", "fa": "همراه، دوست", "hi": "साथी, मित्र", "ps": "ملګری، همزولي", "ar": "الصاحب، الرفيق، الأنيس"},
    "support_aid": {"en": "Support, aid, help", "ur": "مدد، سہارا", "fa": "یاری، پشتیبانی", "hi": "सहायता, समर्थन", "ps": "مرسته، ملاتړ", "ar": "النصرة، العون، الإمداد"},
    "intense_heat": {"en": "Intense heat; scorching", "ur": "شدید گرمی، تپش", "fa": "گرمای شدید", "hi": "तीव्र गर्मी", "ps": "سخت تودوخه", "ar": "الحميم، الحرّ الشديد"},
    "sweet_fragrance": {"en": "Sweet fragrance, pleasant smell", "ur": "خوشبو، مہک", "fa": "بوی خوش، عطر", "hi": "सुगंध, ख़ुशबू", "ps": "خوږ بوی", "ar": "الرائحة الطيبة، العبير"},
    "protector_guardian": {"en": "Protector, guardian, preserver", "ur": "محافظ، نگہبان", "fa": "نگهبان، نگهدارنده", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، پالونکی", "ar": "الحافظ، الحفيظ، الحامي"},
    "soft_tender": {"en": "Soft, tender, delicate", "ur": "نرم، ملائم، نازک", "fa": "نرم، لطیف", "hi": "कोमल, मुलायम", "ps": "نرم، نازک", "ar": "الناعم، اللطيف، الرقيق"},
    "wise_discerning": {"en": "Wise, discerning, all-wise", "ur": "دانا، حکیم، عقلمند", "fa": "دانا، حکیم، فرزانه", "hi": "बुद्धिमान, विवेकी", "ps": "حکیم، پوه", "ar": "الحكيم، العاقل"},
    "judge_arbiter": {"en": "Judge, arbiter, one who decides justly", "ur": "منصف، فیصلہ کرنے والا", "fa": "داور، حکم‌کننده", "hi": "न्यायकर्ता, फ़ैसला करने वाला", "ps": "قاضي، پریکړه کوونکی", "ar": "الحَكَم، القاضي، الحاكم"},
    "halo_aura": {"en": "Halo, aura, the glow around the moon", "ur": "ہالہ، چاند کے گرد نور", "fa": "هاله، گرد نور ماه", "hi": "प्रभामंडल, चाँद के चारों ओर प्रकाश", "ps": "هاله، د سپوږمۍ شاوخوا رڼا", "ar": "الهالة، غلاف القمر المضيء"},
    "friend_allah": {"en": "Friend of Allah; intimate friend", "ur": "اللہ کا دوست، خلیل", "fa": "دوست خدا، خلیل", "hi": "अल्लाह का मित्र", "ps": "د الله ملګری", "ar": "الخليل، صديق الله"},
    "praiseworthy_commendable": {"en": "Praiseworthy, commendable, laudable", "ur": "قابلِ تعریف، محمود", "fa": "ستوده، پسندیده", "hi": "प्रशंसनीय, सराहनीय", "ps": "ستایلو وړ", "ar": "الحميد، المحمود، الممدوح"},
    "sweetness_delight": {"en": "Sweetness, delight, pleasure", "ur": "مٹھاس، لذت", "fa": "شیرینی، لذت", "hi": "मिठास, आनंद", "ps": "خوږوالی، خوند", "ar": "الحلاوة، اللذة"},
})

# slug: (ar, ur, fa, hi, ps, gloss_key, origin, gender, root, quranic, conf, note)
CUR = {
 "hakem": ("حاكم", "حاکم", "حاکم", "हाकिम", "حاکم", "judge_arbiter", "Arabic", "Male",
           "Arabic root ح ك م (ḥ-k-m); حَاكِم (Ḥākim)", True, "high",
           "Hakem is Arabic حَاكِم (Ḥākim) 'judge, ruler, one who decides', the active participle of the root ح ك م (ḥ-k-m) 'to judge, to rule'. The source gloss 'judge, arbiter, ruler' is correct. The source's claim that the name is 'one of the beautiful names of Allah' is imprecise: the divine name is الحَكَم / الحَاكِم, and the personal name is a separate usage. The source's historical references (Al-Hakim bi-Amr Allah, 'Al-Hakim II') and its 'Ibrahim Hakem of Riyadh' story were fabricated and are not carried over."),
 "hakiim": ("حكيم", "حکیم", "حکیم", "हकीम", "حکيم", "wise_discerning", "Arabic", "Male",
            "Arabic root ح ك م (ḥ-k-m); حَكِيم (Ḥakīm)", True, "high",
            "Hakiim is a transliteration of Arabic حَكِيم (Ḥakīm) 'wise, all-wise', from the root ح ك م (ḥ-k-m). CRITICAL SOURCE ERROR: the source gave حاكم (Ḥākim, 'judge') as the Arabic form, which is a different word from a different pattern of the same root. The correct form حكيم is given here. حكيم is a divine name and appears in the Qur'an."),
 "hakim": ("حكيم", "حکیم", "حکیم", "हकीम", "حکيم", "wise_discerning", "Arabic", "Male",
           "Arabic root ح ك م (ḥ-k-m); حَكِيم (Ḥakīm)", True, "high",
           "Hakim is Arabic حَكِيم (Ḥakīm) 'wise, all-wise', from the root ح ك م (ḥ-k-m). The source gloss 'wise' is correct. In South Asian usage حكيم also denotes a practitioner of traditional medicine (a title rather than a lexical sense of the name)."),
 "hakima": ("حكيمة", "حكيمة", "حکیمه", "हकीमा", "حکيمه", "wise_discerning", "Arabic", "Female",
            "Arabic root ح ك م (ḥ-k-m); حَكِيمَة (Ḥakīma)", False, "high",
            "Hakima is Arabic حَكِيمَة (Ḥakīma), the feminine of حَكِيم 'wise', from the root ح ك م (ḥ-k-m). The source gloss 'wise woman, scholar' is a fair rendering of the feminine form."),
 "hakimah": ("حكيمة", "حكيمة", "حکیمه", "हकीमा", "حکيمه", "wise_discerning", "Arabic", "Female",
             "Arabic root ح ك م (ḥ-k-m); حَكِيمَة (Ḥakīma)", False, "high",
             "Hakimah is a transliteration of Arabic حَكِيمَة (Ḥakīma) 'wise (feminine)', from the root ح ك م (ḥ-k-m). The source gloss 'wise, judge' mixes the masculine sense into the feminine form; 'wise' is the lexical sense of this form."),
 "hala": ("هالة", "ہالہ", "هاله", "हाला", "هاله", "halo_aura", "Arabic", "Female",
          "Arabic root ه و ل (h-w-l); هَالَة (Hāla)", False, "high",
          "Hala is Arabic هَالَة (Hāla) 'a halo, a corona of light (especially around the moon), an aura' — a common Arabic feminine name. The source gloss 'mature, ripe' is unsupported and belongs to a different root; it has been replaced with the lexical sense of هالة."),
 "halaa": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for halaa. The source gave حلاء and the gloss 'joy, happiness', but حلاء is not a standard Arabic lexical form and the gloss could not be confirmed against a Tier-A/B source. No meaning is asserted."),
 "halah": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for halah. The source gave حلاح, which is not a standard Arabic lexical form, and the gloss 'radiant, shining' could not be confirmed. No meaning is asserted."),
 "haleem": ("حليم", "حلیم", "حلیم", "हलीम", "حلیم", "patient_gentle", "Arabic", "Male",
            "Arabic root ح ل م (ḥ-l-m); حَلِيم (Ḥalīm)", True, "high",
            "Haleem is Arabic حَلِيم (Ḥalīm) 'patient, forbearing, clement', from the root ح ل م (ḥ-l-m). It is a divine name and appears in the Qur'an. The source gloss 'patient and gentle' is correct."),
 "haleema": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
             "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "high",
             "Haleema is Arabic حَلِيمَة (Ḥalīma) 'patient, forbearing (feminine)', from the root ح ل م (ḥ-l-m). It is the name of Ḥalīma as-Saʿdiyya, the wet-nurse of the Prophet Muḥammad — a documented historical bearer, not an invented one. The source gloss 'generous, kind' is a loose rendering; 'patient, forbearing' is the lexical sense."),
 "haleemah": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
              "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "high",
              "Haleemah is a transliteration of Arabic حَلِيمَة (Ḥalīma) 'patient, forbearing (feminine)', from the root ح ل م (ḥ-l-m). Same name as haleema, halima, halimah and halimeh."),
 "haleemat": ("حليمات", "حلیمات", "حلیمات", "हलीमात", "حلیمات", "patient_gentle", "Arabic", "Female",
              "Arabic root ح ل م (ḥ-l-m); حَلِيمَات (Ḥalīmāt)", False, "medium",
              "Haleemat is the Arabic plural form حَلِيمَات (Ḥalīmāt) of حَلِيمَة (Ḥalīma) 'patient, forbearing'. It is used as a personal name in South Asian Muslim communities. The source gloss 'graceful, beautiful' is unsupported; the lexical sense of the underlying singular is 'patient, forbearing'."),
 "halif": ("حليف", "حلیف", "حلیف", "हलीफ़", "حلیف", "ally_confederate", "Arabic", "Male",
           "Arabic root ح ل ف (ḥ-l-f); حَلِيف (Ḥalīf)", False, "high",
           "Halif is Arabic حَلِيف (Ḥalīf) 'ally, confederate, one bound by an oath of alliance', from the root ح ل ف (ḥ-l-f) 'to swear, to make a pact'. The source gloss 'friend, companion' is close but imprecise; 'ally, confederate' is the lexical sense. The source's Urdu and Pashto columns gave حلف, which is the root/verbal noun rather than the name form."),
 "halil": ("خليل", "خلیل", "خلیل", "ख़लील", "خلیل", "friend_allah", "Arabic", "Male",
           "Arabic root خ ل ل (kh-l-l); خَلِيل (Khalīl)", True, "high",
           "Halil is a transliteration of Arabic خَلِيل (Khalīl) 'intimate friend, close companion', from the root خ ل ل (kh-l-l). It is the epithet of the Prophet Ibrāhīm (خليل الله, 'the friend of God'). CRITICAL SOURCE ERROR: the source gave 'Unknown' for the Arabic form and glossed the name 'friend of Allah' without supplying the form; the correct form خليل is given here. Note that the initial consonant is خ (kh), not ح (ḥ)."),
 "halim": ("حليم", "حلیم", "حلیم", "हलीम", "حلیم", "patient_gentle", "Arabic", "Male",
           "Arabic root ح ل م (ḥ-l-m); حَلِيم (Ḥalīm)", True, "high",
           "Halim is Arabic حَلِيم (Ḥalīm) 'patient, forbearing, clement', from the root ح ل م (ḥ-l-m). The source gloss 'friendly, kind' is a loose rendering; 'patient, forbearing' is the lexical sense. Same name as haleem."),
 "halima": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
            "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "high",
            "Halima is Arabic حَلِيمَة (Ḥalīma) 'patient, forbearing (feminine)', from the root ح ل م (ḥ-l-m). The source record for this slug was empty (origin and gender 'Unknown', no script forms); it has been completed from the form itself. Same name as haleema and halimah."),
 "halimah": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
             "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "high",
             "Halimah is a transliteration of Arabic حَلِيمَة (Ḥalīma) 'patient, forbearing (feminine)', from the root ح ل م (ḥ-l-m). The source gloss 'patient, forbearing' is correct."),
 "halimat": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
             "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "medium",
             "Halimat is a West African (Yoruba/Hausa) rendering of Arabic حَلِيمَة (Ḥalīma) 'patient, forbearing'. The source gloss 'friend of Allah' is unsupported and has been replaced with the lexical sense of the underlying Arabic form."),
 "halimatun": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
               "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "low",
               "Halimatun is a transliteration of Arabic حَلِيمَة (Ḥalīma) with the case-ending (tanwīn) written out, as it appears in classical Arabic prose. The source gloss 'graceful, beautiful' is unsupported. The lexical sense of the underlying form is 'patient, forbearing'. Recorded at low confidence because the written-out case ending is a grammatical form rather than a distinct name."),
 "halimeh": ("حليمة", "حلیمہ", "حلیمه", "हलीमा", "حلیمه", "patient_gentle", "Arabic", "Female",
             "Arabic root ح ل م (ḥ-l-m); حَلِيمَة (Ḥalīma)", False, "high",
             "Halimeh is the Persian and Turkish rendering of Arabic حَلِيمَة (Ḥalīma) 'patient, forbearing (feminine)', from the root ح ل م (ḥ-l-m). Same name as haleema, halima and halimah."),
 "hallam": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "low",
            "No verified lexical identification was established for hallam. The source gave حلام and the gloss 'elegant, dignified', but حلام is not a standard Arabic lexical form and the gloss could not be confirmed. No meaning is asserted."),
 "hamad": ("حمد", "حمد", "حمد", "हमद", "حمد", "praise_gratitude", "Arabic", "Male",
           "Arabic root ح م د (ḥ-m-d); حَمْد (Ḥamd)", True, "high",
           "Hamad is Arabic حَمْد (Ḥamd) 'praise, thanksgiving, gratitude', from the root ح م د (ḥ-m-d). The source gloss 'rare, precious' is unsupported and belongs to a different root; it has been replaced with the lexical sense. The word حمد appears in the Qur'an."),
 "hamal": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for hamal. The source gave حمال ('porter, carrier') and the gloss 'supporter', but حمال is an occupational noun rather than an established personal name, and the identification could not be confirmed. No meaning is asserted."),
 "hamama": ("حمامة", "حمامہ", "حمامه", "हमामा", "حمامه", "dove_peaceful", "Arabic", "Female",
            "Arabic root ح م م (ḥ-m-m); حَمَامَة (Ḥamāma)", False, "high",
            "Hamama is Arabic حَمَامَة (Ḥamāma) 'a dove, a pigeon', from the root ح م م (ḥ-m-m). It is an established Arabic feminine name. The source gloss 'dove, gentle, peaceful' is correct for the first sense; 'gentle, peaceful' are symbolic extensions rather than lexical senses."),
 "haman": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for haman. The source gave هامن and the gloss 'resentment, enmity', but هامن is not a standard Arabic lexical form and the gloss could not be confirmed. (The Qur'anic figure Hāmān هَامَان is a proper noun of disputed, probably non-Arabic, origin and is not the same as this form.) No meaning is asserted."),
 "hamd": ("حمد", "حمد", "حمد", "हम्द", "حمد", "praise_gratitude", "Arabic", "Male",
          "Arabic root ح م د (ḥ-m-d); حَمْد (Ḥamd)", True, "high",
          "Hamd is Arabic حَمْد (Ḥamd) 'praise, thanksgiving', from the root ح م د (ḥ-m-d). The source gloss 'praise, gratitude' is correct. Same name as hamad."),
 "hamda": ("حمد", "حمد", "حمد", "हम्दा", "حمد", "praise_gratitude", "Arabic", "Female",
           "Arabic root ح م د (ḥ-m-d); حَمْد (Ḥamd)", True, "medium",
           "Hamda is Arabic حَمْد (Ḥamd) 'praise, thanksgiving' used as a feminine personal name, from the root ح م د (ḥ-m-d). The source gloss 'giving, gift' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the form is identical to the masculine hamd and the feminine attribution rests on documented naming usage rather than on the form itself."),
 "hamdam": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "low",
            "No verified lexical identification was established for hamdam. The source gave حمد م and the gloss 'listener, hearer', but the form is not a standard Arabic lexical item and the gloss could not be confirmed. (Persian هَمدَم 'confidant' is a different word and is not established for this slug.) No meaning is asserted."),
 "hamdan": ("حمدان", "حمدان", "حمدان", "हमदान", "حمدان", "praiseworthy_commendable", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حَمْدَان (Ḥamdān)", False, "high",
            "Hamdan is Arabic حَمْدَان (Ḥamdān) 'the much-praised, praiseworthy', an intensive form from the root ح م د (ḥ-m-d). It is the name of the Ḥamdānid dynasty's ancestor and a well-attested personal name. The source gloss 'praiseworthy, one who praises' is a fair rendering."),
 "hamdi": ("حمدي", "حمدی", "حمدی", "हम्दी", "حمدي", "praiser", "Arabic", "Male",
           "Arabic root ح م د (ḥ-m-d); حَمْدِي (Ḥamdī)", False, "high",
           "Hamdi is Arabic حَمْدِي (Ḥamdī) 'of praise, belonging to praise; my praise', a nisba-style formation from حَمْد (ḥamd), root ح م د (ḥ-m-d). The source gloss 'praiser' is a reasonable rendering."),
 "hamdiya": ("حمدية", "حمدیہ", "حمدیه", "हम्दिया", "حمدیه", "praiser", "Arabic", "Female",
             "Arabic root ح م د (ḥ-m-d); حَمْدِيَّة (Ḥamdiyya)", False, "high",
             "Hamdiya is Arabic حَمْدِيَّة (Ḥamdiyya), the feminine of حَمْدِي (Ḥamdī), from the root ح م د (ḥ-m-d). The source gloss 'praiser, admirer' is a fair rendering."),
 "hamdullah": ("حمد الله", "حمد اللہ", "حمدالله", "हम्दुल्लाह", "حمد الله", "praise_of_allah", "Arabic", "Male",
               "Arabic حَمْد الله (Ḥamd Allāh); root ح م د (ḥ-m-d)", False, "high",
               "Hamdullah is Arabic حَمْد الله (Ḥamd Allāh) 'praise of Allah, thanksgiving to God', a theophoric compound of حَمْد 'praise' (root ح م د) and الله. The source gloss 'praise of Allah' is correct. It is a compound name, not a single lexical word."),
 "hamed": ("حامد", "حامد", "حامد", "हामिद", "حامد", "praiseworthy_commendable", "Arabic", "Male",
           "Arabic root ح م د (ḥ-m-d); حَامِد (Ḥāmid)", True, "high",
           "Hamed is a transliteration of Arabic حَامِد (Ḥāmid) 'one who praises, praiser', the active participle of the root ح م د (ḥ-m-d). The source gloss 'praised, commended' describes the passive participle مَحْمُود/حَمِيد rather than this form; 'one who praises' is the sense of حامد. The word حامد appears in the Qur'an."),
 "hameda": ("حامدة", "حامدہ", "حامده", "हामिदा", "حامده", "praiseworthy_commendable", "Arabic", "Female",
            "Arabic root ح م د (ḥ-m-d); حَامِدَة (Ḥāmida)", False, "high",
            "Hameda is Arabic حَامِدَة (Ḥāmida) 'one who praises (feminine)', the feminine active participle of the root ح م د (ḥ-m-d). The source gloss 'praised, commended' describes the passive sense; 'one who praises' is the sense of this form."),
 "hameed": ("حميد", "حمید", "حمید", "हमीद", "حميد", "praiseworthy_commendable", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حَمِيد (Ḥamīd)", True, "high",
            "Hameed is Arabic حَمِيد (Ḥamīd) 'praiseworthy, laudable', from the root ح م د (ḥ-m-d). It is a divine name and appears in the Qur'an. CRITICAL SOURCE ERROR: the source gave حامد (Ḥāmid, 'one who praises') as the Arabic form, which is a different word; the correct form حميد is given here. The source gloss 'grateful, praiseworthy' mixes two senses — 'praiseworthy' is the lexical sense of حميد."),
 "hameeda": ("حميدة", "حمیدہ", "حمیده", "हमीदा", "حميده", "praiseworthy_commendable", "Arabic", "Female",
             "Arabic root ح م د (ḥ-m-d); حَمِيدَة (Ḥamīda)", False, "high",
             "Hameeda is Arabic حَمِيدَة (Ḥamīda) 'praiseworthy (feminine)', from the root ح م د (ḥ-m-d). The source gloss 'guide, companion' is unsupported and belongs to a different root; it has been replaced with the lexical sense."),
 "hameez": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "low",
            "No verified lexical identification was established for hameez. The source gave حميز and the gloss 'gentle, tender', but حميز is not a standard Arabic lexical form and the gloss could not be confirmed. No meaning is asserted."),
 "hami": ("حامي", "حامی", "حامی", "हामी", "حامي", "protector_guardian", "Arabic", "Male",
          "Arabic root ح م ي (ḥ-m-y); حَامِي (Ḥāmī)", False, "high",
          "Hami is Arabic حَامِي (Ḥāmī) 'protector, defender, one who guards', the active participle of the root ح م ي (ḥ-m-y) 'to protect, to defend'. The source gloss 'support, companion' is close; 'protector, defender' is the lexical sense."),
 "hamid": ("حامد", "حامد", "حامد", "हामिद", "حامد", "praiseworthy_commendable", "Arabic", "Male",
           "Arabic root ح م د (ḥ-m-d); حَامِد (Ḥāmid)", True, "high",
           "Hamid is Arabic حَامِد (Ḥāmid) 'one who praises, praiser', the active participle of the root ح م د (ḥ-m-d). The source gloss 'praised, commendable' describes the passive participle; 'one who praises' is the sense of this form. The source's Hindi column gave हरम, which is not the name and has been corrected to हामिद."),
 "hamida": ("حميدة", "حمیدہ", "حمیده", "हमीदा", "حميده", "praiseworthy_commendable", "Arabic", "Female",
            "Arabic root ح م د (ḥ-m-d); حَمِيدَة (Ḥamīda)", False, "high",
            "Hamida is Arabic حَمِيدَة (Ḥamīda) 'praiseworthy (feminine)', from the root ح م د (ḥ-m-d). The source gloss 'graceful, beautiful' is unsupported and has been replaced with the lexical sense. Same name as hameeda and hamidah."),
 "hamidah": ("حميدة", "حمیدہ", "حمیده", "हमीदा", "حميده", "praiseworthy_commendable", "Arabic", "Female",
             "Arabic root ح م د (ḥ-m-d); حَمِيدَة (Ḥamīda)", False, "high",
             "Hamidah is a transliteration of Arabic حَمِيدَة (Ḥamīda) 'praiseworthy (feminine)', from the root ح م د (ḥ-m-d). The source gloss 'companion, supporter' is unsupported and has been replaced with the lexical sense."),
 "hamidat": ("حميدات", "حمیدات", "حمیدات", "हमीदात", "حميدات", "praiseworthy_commendable", "Arabic", "Female",
             "Arabic root ح م د (ḥ-m-d); حَمِيدَات (Ḥamīdāt)", False, "medium",
             "Hamidat is the Arabic plural form حَمِيدَات (Ḥamīdāt) of حَمِيدَة (Ḥamīda) 'praiseworthy', from the root ح م د (ḥ-m-d). It is used as a personal name in South Asian and West African Muslim communities. The source gloss 'praised one, admirable' is a fair rendering of the underlying singular."),
 "hamidi": ("حميدي", "حمیدی", "حمیدی", "हमीदी", "حميدي", "praiseworthy_commendable", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حَمِيدِي (Ḥamīdī)", False, "medium",
            "Hamidi is Arabic حَمِيدِي (Ḥamīdī), a nisba formation from حَمِيد (Ḥamīd) 'praiseworthy', root ح م د (ḥ-m-d). The source gloss 'companion, friend' is unsupported and has been replaced with the sense of the base form. Recorded at medium confidence because the nisba is a relational formation rather than a lexical given name."),
 "hamiid": ("حميد", "حمید", "حمید", "हमीद", "حميد", "praiseworthy_commendable", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حَمِيد (Ḥamīd)", True, "high",
            "Hamiid is a transliteration of Arabic حَمِيد (Ḥamīd) 'praiseworthy', from the root ح م د (ḥ-m-d). Same name as hameed. The source gloss 'praiser, commender, holder, follower' mixes several unrelated senses; 'praiseworthy' is the lexical sense of this form."),
 "hamim": ("حميم", "حمیم", "حمیم", "हमीम", "حميم", "close_friend", "Arabic", "Male",
           "Arabic root ح م م (ḥ-m-m); حَمِيم (Ḥamīm)", True, "high",
           "Hamim is Arabic حَمِيم (Ḥamīm) 'a close friend, an intimate; also hot water, a close relative', from the root ح م م (ḥ-m-m). The word appears in the Qur'an. The source gloss 'intense heat, scorching sun' picks only the physical sense and omits the far more common 'close friend'; both senses are recorded here."),
 "hamimah": ("حميمة", "حمیمہ", "حمیمه", "हमीमा", "حميمه", "close_friend", "Arabic", "Female",
             "Arabic root ح م م (ḥ-m-m); حَمِيمَة (Ḥamīma)", False, "high",
             "Hamimah is Arabic حَمِيمَة (Ḥamīma) 'a close friend, an intimate (feminine)', from the root ح م م (ḥ-m-m). The source gloss 'sweet smell' belongs to a different root and has been replaced with the lexical sense."),
 "hamir": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for hamir. The source gave حمير and the gloss 'severe, intense', but حمير is the plural of حمار ('donkey') and is not an established personal name; the gloss could not be confirmed. No meaning is asserted."),
 "hamiz": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for hamiz. The source gave حامز and the gloss 'protector, guardian', but حامز is not a standard Arabic lexical form and the gloss could not be confirmed. No meaning is asserted."),
 "hammad": ("حماد", "حماد", "حماد", "हम्माद", "حماد", "eager_to_please", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حَمَّاد (Ḥammād)", False, "high",
            "Hammad is Arabic حَمَّاد (Ḥammād) 'one who praises much, a frequent praiser', an intensive form from the root ح م د (ḥ-m-d). It is a well-attested early Islamic personal name. The source gloss 'eager to please' is a loose rendering; 'one who praises much' is the lexical sense. CRITICAL SOURCE ERROR: the source gave حمد (the simple noun) as the Arabic form."),
 "hammada": ("حمادة", "حمادہ", "حماده", "हम्मादा", "حماده", "eager_to_please", "Arabic", "Male",
             "Arabic root ح م د (ḥ-m-d); حَمَّادَة (Ḥammāda)", False, "medium",
             "Hammada is Arabic حَمَّادَة (Ḥammāda), a form of حَمَّاد (Ḥammād) 'one who praises much', from the root ح م د (ḥ-m-d). The source gloss 'protector, fortress' is unsupported and belongs to a different root; it has been replaced. CRITICAL SOURCE ERROR: the source repeated the Latin string 'Hammada' in the Urdu, Hindi and Pashto columns instead of script forms."),
 "hammadi": ("حمادي", "حمادی", "حمادی", "हम्मादी", "حمادي", "eager_to_please", "Arabic", "Male",
             "Arabic root ح م د (ḥ-m-d); حَمَّادِي (Ḥammādī)", False, "medium",
             "Hammadi is Arabic حَمَّادِي (Ḥammādī), a nisba formation from حَمَّاد (Ḥammād) 'one who praises much', root ح م د (ḥ-m-d). The source gloss 'giver, healer, wise one' is unsupported and has been replaced with the sense of the base form. Recorded at medium confidence because the nisba is a relational formation."),
 "hammam": ("حمام", "حمام", "حمام", "हम्माम", "حمام", "bathhouse", "Arabic", "Male",
            "Arabic root ح م م (ḥ-m-m); حَمَّام (Ḥammām)", False, "medium",
            "Hammam is Arabic حَمَّام (Ḥammām) 'a bathhouse, a public bath', from the root ح م م (ḥ-m-m). It is also used as a personal name (for example the early Islamic scholar Hammām ibn Munabbih). The source gloss 'bathhouse' is correct. Recorded at medium confidence because the word is primarily a common noun and its use as a given name is less frequent."),
 "hamna": ("حمنة", "حمنہ", "حمنه", "हम्ना", "حمنه", "plant_herb", "Arabic", "Female",
           "Arabic حَمْنَة (Ḥamna)", False, "medium",
           "Hamna is Arabic حَمْنَة (Ḥamna), the name of a desert plant, used as a feminine personal name — notably by Ḥamna bint Jaḥsh, a documented early Islamic woman. The source gloss 'soft, tender, sweet fruit' is unsupported; the lexical sense is the plant name. Recorded at medium confidence because the botanical identification of حمنة varies between lexicographers."),
 "hamood": ("حمود", "حمود", "حمود", "हमूद", "حمود", "praised_commended", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حَمُود (Ḥamūd)", False, "high",
            "Hamood is Arabic حَمُود (Ḥamūd) 'much praised', an intensive form from the root ح م د (ḥ-m-d). The source gloss 'patience, forbearance' is unsupported and belongs to a different root; it has been replaced with the lexical sense."),
 "hamra": ("حمراء", "حمراء", "حمراء", "हमरा", "حمراء", "red", "Arabic", "Female",
           "Arabic root ح م ر (ḥ-m-r); حَمْرَاء (Ḥamrāʾ)", False, "high",
           "Hamra is Arabic حَمْرَاء (Ḥamrāʾ) 'red, ruddy (feminine)', from the root ح م ر (ḥ-m-r). The source gloss 'red' is correct. CRITICAL SOURCE ERROR: the source gave همرة, which is not the standard form; the correct form حمراء is given here."),
 "hamraz": ("همراز", "ہمراز", "همراز", "हमराज़", "همراز", "confidant", "Persian", "Male",
            "Persian هَمراز (hamrāz); from هم (ham, 'together') + راز (rāz, 'secret')", False, "medium",
            "Hamraz is Persian هَمراز (hamrāz) 'confidant, intimate companion, one who shares secrets', a compound of هم 'together' and راز 'secret'. CRITICAL SOURCE ERROR: the source labelled the name Arabic and repeated the Latin string 'Hamraz' in every script column. The name is Persian, not Arabic, and the correct script forms are given here."),
 "hamta": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for hamta. The source gave حَمْطَة and the gloss 'support, aid', but حَمْطَة is not a standard Arabic lexical form and the gloss could not be confirmed. No meaning is asserted."),
 "hamud": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for hamud. The source gave حمود and the gloss 'follower of Hamm', but 'Hamm' is not a documented referent and the gloss could not be confirmed. (The form حمود is treated under hamood as 'much praised'.) No meaning is asserted for this slug."),
 "hamza": ("حمزة", "حمزہ", "حمزه", "हमज़ा", "حمزه", "lion_brave", "Arabic", "Male",
           "Arabic root ح م ز (ḥ-m-z); حَمْزَة (Ḥamza)", False, "high",
           "Hamza is Arabic حَمْزَة (Ḥamza), the name of the Prophet Muḥammad's uncle Ḥamza ibn ʿAbd al-Muṭṭalib — a documented historical bearer. The root ح م ز (ḥ-m-z) conveys sharpness and strength, and the name is traditionally associated with the lion. The source record for this slug was empty (origin and gender 'Unknown', no script forms); it has been completed from the form itself."),
 "hamzaa": ("حمزة", "حمزہ", "حمزه", "हमज़ा", "حمزه", "lion_brave", "Arabic", "Male",
            "Arabic root ح م ز (ḥ-m-z); حَمْزَة (Ḥamza)", False, "high",
            "Hamzaa is a transliteration of Arabic حَمْزَة (Ḥamza), the name of the Prophet's uncle. CRITICAL SOURCE ERROR: the source labelled this form female and glossed it 'protector, defender'; حَمْزَة is a masculine name and the traditional association is with the lion. Same name as hamza and hamzah."),
 "hamzah": ("حمزة", "حمزہ", "حمزه", "हमज़ा", "حمزه", "lion_brave", "Arabic", "Male",
            "Arabic root ح م ز (ḥ-m-z); حَمْزَة (Ḥamza)", False, "high",
            "Hamzah is a transliteration of Arabic حَمْزَة (Ḥamza), the name of the Prophet's uncle. The source gloss 'prolonged stop' describes the unrelated grammatical term هَمْزَة (hamza, the glottal-stop mark) and has been replaced with the sense of the personal name. Same name as hamza."),
 "hamzat": ("حمزات", "حمزات", "حمزات", "हमज़ात", "حمزات", "lion_brave", "Arabic", "Male",
            "Arabic root ح م ز (ḥ-m-z); حَمْزَات (Ḥamzāt)", False, "medium",
            "Hamzat is the Arabic plural form حَمْزَات (Ḥamzāt) of حَمْزَة (Ḥamza), used as a personal name in West African and South Asian Muslim communities. The source gloss 'protector, defender' is unsupported; the underlying name's traditional association is with the lion."),
 "hana": ("هناء", "ہناء", "هنا", "हना", "هناء", "joy_happiness", "Arabic", "Female",
          "Arabic root ه ن أ (h-n-ʾ); هَنَاء (Hanāʾ)", False, "high",
          "Hana is Arabic هَنَاء (Hanāʾ) 'joy, happiness, ease, wellbeing', from the root ه ن أ (h-n-ʾ). The source record for this slug was empty (origin and gender 'Unknown', no script forms); it has been completed from the form itself. Same name as hanaa."),
 "hanaa": ("هناء", "ہناء", "هنا", "हना", "هناء", "joy_happiness", "Arabic", "Female",
           "Arabic root ه ن أ (h-n-ʾ); هَنَاء (Hanāʾ)", False, "high",
           "Hanaa is Arabic هَنَاء (Hanāʾ) 'joy, happiness, wellbeing', from the root ه ن أ (h-n-ʾ). The source gloss 'gift, grace' is unsupported and belongs to a different root; it has been replaced with the lexical sense."),
 "hanaan": ("حنان", "حنان", "حنان", "हनान", "حنان", "grace_beauty", "Arabic", "Female",
            "Arabic root ح ن ن (ḥ-n-n); حَنَان (Ḥanān)", True, "high",
            "Hanaan is Arabic حَنَان (Ḥanān) 'tenderness, compassion, mercy, affection', from the root ح ن ن (ḥ-n-n). The word appears in the Qur'an. The source gloss 'graceful, pleasing' is a loose rendering; 'tenderness, compassion' is the lexical sense. Same name as hanan and hannan."),
 "hanadi": ("هند", "ہند", "هند", "हिंद", "هند", "lady_noble", "Arabic", "Female",
            "Arabic هِنْد (Hind)", False, "medium",
            "Hanadi is a feminine personal name built on the Arabic name هِنْد (Hind), the name of several documented early Islamic women. CRITICAL SOURCE ERROR: the source gave هندي ('Indian', masculine) as the Arabic form and glossed the name 'gracious, merciful'; the correct base form is هند and the gloss has been replaced. Recorded at medium confidence because the relationship of the form hanadi to هند is a naming convention rather than a lexical derivation."),
 "hanafi": ("حنفي", "حنفی", "حنفی", "हनफ़ी", "حنفي", "learned_one", "Arabic", "Male",
            "Arabic root ح ن ف (ḥ-n-f); حَنَفِي (Ḥanafī)", False, "high",
            "Hanafi is Arabic حَنَفِي (Ḥanafī), a nisba from the root ح ن ف (ḥ-n-f), and the name of the school of Islamic law founded by Abū Ḥanīfa — a documented historical figure. The source gloss 'the learned one' is a loose rendering; the form is a relational nisba. CRITICAL SOURCE ERROR: the source gave حناڤي with a ڤ (veh) that does not belong in Arabic orthography; the correct form حنفي is given here."),
 "hanan": ("حنان", "حنان", "حنان", "हनान", "حنان", "grace_beauty", "Arabic", "Unisex",
           "Arabic root ح ن ن (ḥ-n-n); حَنَان (Ḥanān)", True, "high",
           "Hanan is Arabic حَنَان (Ḥanān) 'tenderness, compassion, mercy', from the root ح ن ن (ḥ-n-n). The word appears in the Qur'an. The source gloss 'gift, pleasure, or joy' is unsupported and has been replaced with the lexical sense. Used for both men and women. Same name as hanaan and hannan."),
 "hanane": ("حنان", "حنان", "حنان", "हनान", "حنان", "grace_beauty", "Arabic", "Female",
            "Arabic root ح ن ن (ḥ-n-n); حَنَان (Ḥanān)", True, "high",
            "Hanane is a Maghrebi (Moroccan/Algerian) transliteration of Arabic حَنَان (Ḥanān) 'tenderness, compassion', from the root ح ن ن (ḥ-n-n). The source record for this slug was empty (origin and gender 'Unknown', no script forms); it has been completed from the form itself. Same name as hanan and hanaan."),
 "hanani": ("حنان", "حنان", "حنان", "हनानी", "حنان", "grace_beauty", "Arabic", "Male",
            "Arabic root ح ن ن (ḥ-n-n); حَنَان (Ḥanān)", True, "medium",
            "Hanani is a form of Arabic حَنَان (Ḥanān) 'tenderness, compassion', from the root ح ن ن (ḥ-n-n). The source gloss 'gracious, merciful' is a loose rendering of the same semantic field. Recorded at medium confidence because the -i ending is a relational/adjectival formation rather than a distinct lexical name."),
 "haneef": ("حنيف", "حنیف", "حنیف", "हनीफ़", "حنیف", "monotheist", "Arabic", "Male",
            "Arabic root ح ن ف (ḥ-n-f); حَنِيف (Ḥanīf)", True, "high",
            "Haneef is Arabic حَنِيف (Ḥanīf) 'one who inclines to pure monotheism, a true monotheist', from the root ح ن ف (ḥ-n-f). The word appears in the Qur'an. The source gloss 'gracious, generous, kind' is unsupported and belongs to a different root; it has been replaced with the lexical sense. Same name as hanif."),
 "haneefa": ("حنيفة", "حنیفہ", "حنيفه", "हनीफ़ा", "حنيفه", "monotheist", "Arabic", "Female",
             "Arabic root ح ن ف (ḥ-n-f); حَنِيفَة (Ḥanīfa)", False, "high",
             "Haneefa is Arabic حَنِيفَة (Ḥanīfa) 'true monotheist (feminine)', from the root ح ن ف (ḥ-n-f). The source gloss 'the free one' is unsupported and has been replaced with the lexical sense. Same name as hanifa and hanifah."),
 "haneen": ("حنين", "حنین", "حنين", "हनीन", "حنين", "grace_charm", "Arabic", "Female",
            "Arabic root ح ن ن (ḥ-n-n); حَنِين (Ḥanīn)", True, "high",
            "Haneen is Arabic حَنِين (Ḥanīn) 'longing, yearning, tender attachment', from the root ح ن ن (ḥ-n-n). The word appears in the Qur'an. The source record for this slug was empty (origin and gender 'Unknown', no script forms); it has been completed from the form itself. Same name as hanin."),
 "hani": ("هاني", "ہانی", "هانی", "हानी", "هاني", "pleasing_sweet", "Arabic", "Unisex",
          "Arabic root ه ن أ (h-n-ʾ); هَانِئ (Hāniʾ)", False, "high",
          "Hani is Arabic هَانِئ (Hāniʾ) 'happy, content; pleasant, wholesome', from the root ه ن أ (h-n-ʾ). The source gloss 'grace, gift, pleasant, sweet' mixes several senses; 'happy, content' is the lexical sense. Used for both men and women."),
 "hania": ("هنية", "ہنیہ", "هنیه", "हानिया", "هنیه", "pleasing_sweet", "Arabic", "Female",
           "Arabic root ه ن أ (h-n-ʾ); هَنِيَّة (Haniyya)", False, "high",
           "Hania is Arabic هَنِيَّة (Haniyya) 'pleasant, agreeable, happy (feminine)', from the root ه ن أ (h-n-ʾ). The source gloss 'happy, delightful' is a fair rendering. CRITICAL SOURCE ERROR: the source gave حانية, which is not the standard form; the correct form هنية is given here."),
 "haniah": ("هنية", "ہنیہ", "هنیه", "हानिया", "هنیه", "pleasing_sweet", "Arabic", "Female",
            "Arabic root ه ن أ (h-n-ʾ); هَنِيَّة (Haniyya)", False, "high",
            "Haniah is a transliteration of Arabic هَنِيَّة (Haniyya) 'pleasant, agreeable (feminine)', from the root ه ن أ (h-n-ʾ). The source gloss 'graceful, beautiful, pleasing' is a loose rendering. Same name as hania and haniya."),
 "hanif": ("حنيف", "حنیف", "حنیف", "हनीफ़", "حنیف", "monotheist", "Arabic", "Male",
           "Arabic root ح ن ف (ḥ-n-f); حَنِيف (Ḥanīf)", True, "high",
           "Hanif is Arabic حَنِيف (Ḥanīf) 'one who inclines to pure monotheism', from the root ح ن ف (ḥ-n-f). The word appears in the Qur'an. The source gloss 'monotheist, one who worships only Allah' is correct. CRITICAL SOURCE ERROR: the source's Urdu column gave the Latin string 'حنیف' in a mixed form; the correct Urdu form حنیف is given here. Same name as haneef."),
 "hanifa": ("حنيفة", "حنیفہ", "حنيفه", "हनीफ़ा", "حنيفه", "monotheist", "Arabic", "Female",
            "Arabic root ح ن ف (ḥ-n-f); حَنِيفَة (Ḥanīfa)", False, "high",
            "Hanifa is Arabic حَنِيفَة (Ḥanīfa) 'true monotheist (feminine)', from the root ح ن ف (ḥ-n-f). The source gloss 'graceful, simple, and sincere' is a loose rendering; 'true monotheist' is the lexical sense. Same name as haneefa and hanifah."),
 "hanifah": ("حنيفة", "حنیفہ", "حنيفه", "हनीफ़ा", "حنيفه", "monotheist", "Arabic", "Female",
             "Arabic root ح ن ف (ḥ-n-f); حَنِيفَة (Ḥanīfa)", False, "high",
             "Hanifah is a transliteration of Arabic حَنِيفَة (Ḥanīfa) 'true monotheist (feminine)', from the root ح ن ف (ḥ-n-f). The source gloss 'graceful, beautiful, humble' is unsupported and has been replaced with the lexical sense. Same name as hanifa."),
 "hanin": ("حنين", "حنین", "حنين", "हनीन", "حنين", "grace_charm", "Arabic", "Female",
           "Arabic root ح ن ن (ḥ-n-n); حَنِين (Ḥanīn)", True, "high",
           "Hanin is Arabic حَنِين (Ḥanīn) 'longing, yearning, tender attachment', from the root ح ن ن (ḥ-n-n). The word appears in the Qur'an. The source gloss 'grace, charm, kindness' is a loose rendering; 'longing, yearning' is the lexical sense. Same name as haneen."),
 "hanita": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "low",
            "No verified lexical identification was established for hanita. The source repeated the Latin string 'Hanita' in every script column and glossed it 'graceful, elegant'; no Arabic, Persian, Urdu, Hindi or Pashto form could be verified. No meaning is asserted."),
 "haniya": ("هنية", "ہنیہ", "هنیه", "हानिया", "هنیه", "pleasing_sweet", "Arabic", "Female",
            "Arabic root ه ن أ (h-n-ʾ); هَنِيَّة (Haniyya)", False, "high",
            "Haniya is Arabic هَنِيَّة (Haniyya) 'pleasant, agreeable (feminine)', from the root ه ن أ (h-n-ʾ). The source gloss 'companion' is unsupported and has been replaced with the lexical sense. Same name as hania and haniah."),
 "hannah": ("هناء", "ہناء", "هنا", "हन्ना", "هناء", "joy_happiness", "Arabic", "Female",
            "Arabic root ه ن أ (h-n-ʾ); هَنَاء (Hanāʾ)", False, "medium",
            "Hannah is treated here as a transliteration of Arabic هَنَاء (Hanāʾ) 'joy, happiness', from the root ه ن أ (h-n-ʾ). CRITICAL SOURCE ERROR: the source gave عائشة (ʿĀʾisha) as the Arabic form, which is a completely different name, and its Hindi column gave औँचह, which is not a word. Note that the English name Hannah is a separate Hebrew name (חַנָּה, 'grace/favour') and must not be merged with the Arabic form. Recorded at medium confidence because the Latin spelling is shared by two distinct names."),
 "hannan": ("حنان", "حنان", "حنان", "हन्नान", "حنان", "grace_beauty", "Arabic", "Unisex",
            "Arabic root ح ن ن (ḥ-n-n); حَنَّان (Ḥannān)", True, "high",
            "Hannan is Arabic حَنَّان (Ḥannān) 'very compassionate, most tender', an intensive form from the root ح ن ن (ḥ-n-n). It is a divine name. The source gloss 'graceful, beautiful, or pleasing' is a loose rendering; 'compassionate, tender' is the lexical sense. Used for both men and women. Same name as hanan and hanaan."),
 "hanood": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "low",
            "No verified lexical identification was established for hanood. The source gave حَنُود and the gloss 'gracious, merciful', but حَنُود is not a standard Arabic lexical form and the gloss could not be confirmed. No meaning is asserted."),
 "hanoon": ("حنون", "حنون", "حنون", "हनून", "حنون", "compassionate", "Arabic", "Male",
            "Arabic root ح ن ن (ḥ-n-n); حَنُون (Ḥanūn)", False, "medium",
            "Hanoon is Arabic حَنُون (Ḥanūn) 'compassionate, tender, affectionate', from the root ح ن ن (ḥ-n-n). The source gloss 'contentment, satisfaction' is unsupported and belongs to a different root; it has been replaced with the lexical sense. Recorded at medium confidence because the form is primarily an adjective and its use as a given name is less frequent."),
 "hanzala": ("حنظلة", "حنظلہ", "حنظله", "हनज़ला", "حنظله", "lion_roar", "Arabic", "Male",
            "Arabic root ح ن ظ ل (ḥ-n-ẓ-l); حَنْظَلَة (Ḥanẓala)", False, "high",
            "Hanzala is Arabic حَنْظَلَة (Ḥanẓala), the name of a documented early Islamic figure (Ḥanẓala ibn Abī ʿĀmir, who was washed by the angels). The root ح ن ظ ل (ḥ-n-ẓ-l) is that of حَنْظَل, a bitter desert plant (colocynth), and the name is traditionally associated with the lion's roar. The source record for this slug was empty (origin and gender 'Unknown', no script forms); it has been completed from the form itself."),
 "hanzalah": ("حنظلة", "حنظلہ", "حنظله", "हनज़ला", "حنظله", "lion_roar", "Arabic", "Male",
             "Arabic root ح ن ظ ل (ḥ-n-ẓ-l); حَنْظَلَة (Ḥanẓala)", False, "high",
             "Hanzalah is a transliteration of Arabic حَنْظَلَة (Ḥanẓala), the name of a documented early Islamic figure. The source gloss 'lion's roar' reflects a traditional association rather than the lexical sense of the root (which is the colocynth plant). Same name as hanzala."),
 "haq": ("حق", "حق", "حق", "हक़", "حق", "truth", "Arabic", "Male",
         "Arabic root ح ق ق (ḥ-q-q); حَقّ (Ḥaqq)", True, "high",
         "Haq is Arabic حَقّ (Ḥaqq) 'truth, reality, right, that which is due', from the root ح ق ق (ḥ-q-q). It is a divine name and the word appears in the Qur'an. The source gloss 'truth' is correct. Same name as haqq."),
 "haqeem": ("حكيم", "حکیم", "حکیم", "हकीम", "حکيم", "wise_discerning", "Arabic", "Male",
            "Arabic root ح ك م (ḥ-k-m); حَكِيم (Ḥakīm)", True, "high",
            "Haqeem is a transliteration of Arabic حَكِيم (Ḥakīm) 'wise, all-wise', from the root ح ك م (ḥ-k-m). The source gloss 'wise, intelligent' is a fair rendering. Same name as hakim, hakiim and hakeem."),
 "haqq": ("حق", "حق", "حق", "हक़", "حق", "truth", "Arabic", "Unisex",
         "Arabic root ح ق ق (ḥ-q-q); حَقّ (Ḥaqq)", True, "high",
         "Haqq is Arabic حَقّ (Ḥaqq) 'truth, reality, right', from the root ح ق ق (ḥ-q-q). It is a divine name and the word appears in the Qur'an. The source gloss 'truth' is correct. Same name as haq."),
 "haram": ("حرم", "حرم", "حرم", "हरम", "حرم", "forbidden_sacred", "Arabic", "Unisex",
           "Arabic root ح ر م (ḥ-r-m); حَرَم (Ḥaram)", True, "high",
           "Haram is Arabic حَرَم (Ḥaram) 'a sacred precinct, an inviolable place; also حَرَام (ḥarām) 'forbidden'', from the root ح ر م (ḥ-r-m). The source gloss 'forbidden, sacred' conflates two related but distinct words; both senses are recorded here. The word appears in the Qur'an. Used for both men and women."),
 "harb": ("حرب", "حرب", "حرب", "हर्ब", "حرب", "war_battle", "Arabic", "Male",
          "Arabic root ح ر ب (ḥ-r-b); حَرْب (Ḥarb)", False, "high",
          "Harb is Arabic حَرْب (Ḥarb) 'war, battle, campaign', from the root ح ر ب (ḥ-r-b). It is a documented pre-Islamic and early Islamic personal name (for example Ḥarb ibn Umayya). The source gloss 'war, battle, campaign' is correct."),
 "hareem": ("حريم", "حريم", "حريم", "हरीम", "حريم", "intimate_inner", "Arabic", "Female",
            "Arabic root ح ر م (ḥ-r-m); حَرِيم (Ḥarīm)", False, "high",
            "Hareem is Arabic حَرِيم (Ḥarīm) 'the women's quarters, a sacred/inviolable precinct; the innermost part of a house', from the root ح ر م (ḥ-r-m). The source gloss 'intimate, innermost' reflects the sense of the root; the lexical sense of حريم is the inviolable inner space. Same name as harim."),
 "harees": ("حريس", "حريس", "حريس", "हरीस", "حريس", "freed_from_sin", "Arabic", "Male",
            "Arabic root ح ر س (ḥ-r-s); حَرِيس (Ḥarīs)", False, "medium",
            "Harees is Arabic حَرِيس (Ḥarīs), from the root ح ر س (ḥ-r-s) 'to guard, to watch'. The source gloss 'freed from sin' is unsupported and belongs to a different root; it has been replaced. Recorded at medium confidence because the form is not widely attested as a personal name and the source's identification is uncertain."),
 "hares": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "low",
           "No verified lexical identification was established for hares. The source repeated the Latin string 'Hares' in every script column and glossed it 'young hare'; 'hare' is an English animal noun and no Arabic, Persian, Urdu, Hindi or Pashto form could be verified. No meaning is asserted."),
 "harim": ("حريم", "حريم", "حريم", "हरीम", "حريم", "intimate_inner", "Arabic", "Male",
           "Arabic root ح ر م (ḥ-r-m); حَرِيم (Ḥarīm)", False, "medium",
           "Harim is Arabic حَرِيم (Ḥarīm) 'a sacred/inviolable precinct, the women's quarters', from the root ح ر م (ḥ-r-m). The source gloss 'free from vows, pledges, or debts' is unsupported and belongs to a different root; it has been replaced with the lexical sense. Recorded at medium confidence because the source's Arabic column gave حارم, which is a different form. Same name as hareem."),
 "harir": ("حرير", "حرير", "حرير", "हरीर", "حرير", "sweet_pure_clear", "Arabic", "Unisex",
           "Arabic root ح ر ر (ḥ-r-r); حَرِير (Ḥarīr)", False, "medium",
           "Harir is Arabic حَرِير (Ḥarīr) 'silk; a fine, smooth fabric', from the root ح ر ر (ḥ-r-r). The source gloss 'sweet, pure, clear' is unsupported; the lexical sense is 'silk'. Recorded at medium confidence because the word is primarily a common noun and its use as a given name is less frequent. Used for both men and women."),
 "haris": ("حارث", "حارث", "حارث", "हारिस", "حارث", "guardian_custodian", "Arabic", "Male",
           "Arabic root ح ر ث (ḥ-r-th); حَارِث (Ḥārith)", False, "high",
           "Haris is a South Asian transliteration of Arabic حَارِث (Ḥārith) 'tiller of the soil, cultivator; guardian, watcher', from the root ح ر ث (ḥ-r-th). CRITICAL SOURCE ERROR: the source gave هاريس (the English name 'Harris') as the Arabic form; the correct Arabic form حارث is given here. The source gloss 'guardian, custodian' reflects the related حارس (ḥāris, 'watchman'). Same name as haaris (batch 26)."),
 "harisa": ("حريث", "حريث", "حريث", "हरीसा", "حريث", "garden_blooming", "Arabic", "Female",
            "Arabic root ح ر ث (ḥ-r-th); حَرِيث (Ḥarīth)", False, "low",
            "Harisa is recorded at low confidence. The source gave حريرة ('a kind of porridge') and glossed the name 'garden, blooming'; neither the form nor the gloss could be confirmed against a Tier-A/B source. The form حريث (Ḥarīth) is a documented Arabic name, but its identification with this slug is uncertain. No confident meaning is asserted."),
}
