# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 50 (pouran..rafaat).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": pouran -> عائشة (different name);
   raani -> Latin "Raani"; rabar -> Latin "Rabar"; radhi -> Latin "Radhi";
   rabiaa -> رビآ (Japanese katakana mixed in); rabiha -> "رabiها" (Latin mixed);
   ra-ana -> رعانا; ra-uf -> رعوف; raad -> رعد (correct); raafat -> رافع;
   raeeda -> رعيدة; raeef -> رعيف; rabaa -> رباء; rabea -> ربة;
   rabitah -> ربيتة; radhia -> رضيا; radman -> رضان; radwa -> رضوة;
   raeesah -> رئاسة; rafaa -> رفاع; rafaat -> رفاع; qutaibah -> قطايبه;
   quraisha -> قرعيشة; qari -> قرئي; qazim -> قاظم; qaid -> قيد;
   qaisar -> قيصر (correct); qaysar -> قيسر; qamarul -> قمارول;
   qambar -> قمبر; qani -> قاني; qassam -> قسام; qistina -> قيستينا;
   quadir -> قدر; quba -> قبة; qudsia -> قدسية; qudus -> قدوس;
   qureshi -> قرشي; qutub -> قطب; qutaiba -> قُطَيْبَة (correct).
 * EMPTY STUBS (8-key records, no data): qais, qamar, qasim, qusay, rabab, raeesa.
 * MISLABELLED ORIGIN: pouran (Persian), purnama (Indonesian/Malay),
   raditya (Indonesian), rabar (Kurdish), qureshi (Urdu/Punjabi),
   qalandar (Persian/Urdu), qaisar/qaysar (from Latin Caesar).
 * DEGARBLED GLOSSES: pouran "Heavenly nourisher", purnama "Full Moon",
   qaasim "Builder, Creator", qabil "Acceptable, tolerable", qadar "Divine Decree",
   qadeem "Ancient, Old, Wise", qadeer "Powerful", qadir "Powerful, Capable, Strong",
   qadr "Divine decree, predestination", qadri "Powerful, Capable, Able",
   qahir "Conqueror", qahtan "Owner of the plain, fertile lands", qaid "Able, Capable",
   qaim "Established, Upright", qaisar "Caesar or Emperor", qalandar "Wanderer",
   qamarul "Moon of the", qambar "Servant of the Omnipotent",
   qani "Intelligent, Wise, Knowledgeable", qari "One who recites Quran",
   qarib "Near, Close", qaseem "Able to decide", qasid "Reciter",
   qassam "announcer, proclaimer", qassim "Justice and fairness",
   qawi "Strong, Powerful", qays "Firm, strong, or steadfast",
   qaysar "Caesar, Emperor", qayyum "Eternal, Immortal", qazi "Judge, Arbiter",
   qazim "Powerful, Intelligent", qismat "Destiny", qistina "Bright, shining, pure",
   quadir "Strong, Powerful, Master", quaid "Leader, Chief",
   quba "Ancient house or mosque", qudrat "Power, Ability, Capacity", qudsia "Holy",
   qudus "God's Possession", quraish "Honorable", quraisha "Young She-camel",
   qurban "Devotion, Sacrifice", qureshi "noble, learned",
   qutaiba "The one who strikes terror", qutaibah "Warrior, victor, conqueror",
   qutub "Axis, pillar", ra-ana "Compassionate", ra-uf "Gentle, Kind",
   raad "Thunder", raafat "Compassionate", raani "Queen, Princess",
   raashid "Rightly Guided", raaya "Lady, Mistress", rab "Reader, Learner",
   rabaa "Butterfly", rabah "Little Gazelle", rabar "Little Rabbit",
   rabbani "The Lord", rabea "Small, tender one", rabee "Early",
   rabeea "The one who is continuously present", rabeeh "Patient", rabi "Spring",
   rabia "Passionate lover", rabiaa "Patient or passionate lover",
   rabiah "Wife of the Prophet", rabih "Steadfast, enduring", rabiha "Fourth",
   rabitah "Graceful, Beautiful", rabiya "Spring, Blossom", rabiye "The One Who Is Kind",
   rachid "Wise, Knowledgeable", rachida "Small, Humble, Simple",
   rad "Light, Sun, Radiance", radhi "Pleasing, content, joyful",
   radhia "Moon, Grace", radhiya "Pleased", radi "Content, Joy, Pleasing",
   radifa "Knowledgeable, Educated", radil "Little one, gentle, kind, tender",
   raditya "Light of the night", radiya "Delight, Pleasure",
   radiyah "Rejoicing, Delightful", radman "Satisfied, Content",
   radwa "Joy, contentment, happiness", raed "Reader, Seer, Intelligent",
   raeda "Sailor, Traveler", raeed "Leader, Master, King", raeeda "Flowing one",
   raeef "Strong, Firm", raees "Leader, Guide", raeesah "Lady, Mistress",
   rafaa "Healer, Compassionate", rafaat "Healer, Giver of Good Fortune".
 * GENDER ERRORS: qadar, qadr, qismat, quba, qudrat, qureshi, rab, rabah, rabar,
   rabbani, rad, radi, rafaa were labelled unisex where documented usage is
   male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated49 import GLOSSES as _G49

GLOSSES = dict(_G49)
GLOSSES.update({
    "pouran": {"en": "Pouran; a female given name (Persian)", "ur": "پوران (زنانہ نام)", "fa": "پوران (نام زنانه)", "hi": "पूरान (स्त्री नाम)", "ps": "پوران (ښځينه نوم)", "ar": "بُورَان (اسْم عَلَم فَارِسِيّ)"},
    "purnama": {"en": "Purnama; full moon (Indonesian)", "ur": "پورناما، پورا چاند", "fa": "پورناما، ماه کامل", "hi": "पूर्णमा, पूर्ण चंद्र", "ps": "پورناما، بشپړ سپوږمۍ", "ar": "بُورْنَامَا (الْبَدْر)"},
    "qaasim": {"en": "Qasim; divider, distributor", "ur": "قاسم، تقسیم کرنے والا", "fa": "قاسم، تقسیم‌کننده", "hi": "क़ासिम, बाँटने वाला", "ps": "قاسم، ویشونکی", "ar": "قَاسِم، الْمُقَسِّم"},
    "qabil": {"en": "Qabil; a male given name", "ur": "قابیل (مردانہ نام)", "fa": "قابیل (نام مردانه)", "hi": "क़ाबिल (पुरुष नाम)", "ps": "قابیل (نر نوم)", "ar": "قَابِيل (اسْم عَلَم مُذَكَّر)"},
    "qadar": {"en": "Qadar; decree, destiny", "ur": "قدر، تقدیر", "fa": "قدر، سرنوشت", "hi": "क़दर, भाग्य", "ps": "قدر، برخه", "ar": "الْقَدَر، الْمَصِير"},
    "qadeem": {"en": "Qadeem; ancient, old", "ur": "قدیم، پرانا", "fa": "قدیم، کهن", "hi": "क़दीम, प्राचीन", "ps": "قدیم، زوړ", "ar": "الْقَدِيم، الْعَتِيق"},
    "qadeer": {"en": "Qadeer; powerful, capable", "ur": "قدیر، قادر، طاقتور", "fa": "قدیر، توانا", "hi": "क़दीर, सक्षम", "ps": "قدیر، توانا", "ar": "الْقَدِير، الْقَادِر"},
    "qadir": {"en": "Qadir; powerful, capable", "ur": "قادر، طاقتور", "fa": "قادر، توانا", "hi": "क़ादिर, सक्षम", "ps": "قادر، توانا", "ar": "الْقَادِر، الْقَدِير"},
    "qadr": {"en": "Qadr; decree, destiny", "ur": "قدر، تقدیر", "fa": "قدر، سرنوشت", "hi": "क़द्र, भाग्य", "ps": "قدر، برخه", "ar": "الْقَدْر، الْقَدَر"},
    "qadri": {"en": "Qadri; of Qadir (relational)", "ur": "قادری، قادر سے منسوب", "fa": "قادری، منسوب به قادر", "hi": "क़ादरी, क़ादिर से संबंधित", "ps": "قادري، د قادر اړوند", "ar": "الْقَادِرِي، مَنْسُوب إِلَى الْقَادِر"},
    "qahir": {"en": "Qahir; conqueror, subduer", "ur": "قاہر، فاتح، غالب", "fa": "قاهر، چیره‌گر", "hi": "क़ाहिर, विजेता", "ps": "قاهر، بریالی", "ar": "الْقَاهِر، الْغَالِب"},
    "qahtan": {"en": "Qahtan; a male given name", "ur": "قحطان (مردانہ نام)", "fa": "قحطان (نام مردانه)", "hi": "क़हतान (पुरुष नाम)", "ps": "قحطان (نر نوم)", "ar": "قَحْطَان (اسْم عَلَم مُذَكَّر)"},
    "qaid": {"en": "Qaid; leader, commander", "ur": "قائد، رہنما، سردار", "fa": "قائد، رهبر", "hi": "क़ाइद, नेता", "ps": "قائد، مشر", "ar": "الْقَائِد، الزَّعِيم"},
    "qaim": {"en": "Qaim; standing, upright", "ur": "قائم، کھڑا، برقرار", "fa": "قائم، ایستاده", "hi": "क़ाइम, स्थिर", "ps": "قائم، ولاړ", "ar": "الْقَائِم، الثَّابِت"},
    "qais": {"en": "Qais; a male given name", "ur": "قیس (مردانہ نام)", "fa": "قیس (نام مردانه)", "hi": "क़ैस (पुरुष नाम)", "ps": "قیس (نر نوم)", "ar": "قَيْس (اسْم عَلَم مُذَكَّر)"},
    "qaisar": {"en": "Qaisar; Caesar, emperor", "ur": "قیصر، بادشاہ", "fa": "قیصر، امپراتور", "hi": "क़ैसर, सम्राट", "ps": "قیصر، پاچا", "ar": "قَيْصَر (الْقَيْصَر)"},
    "qalandar": {"en": "Qalandar; wandering ascetic (Persian)", "ur": "قلندر، درویش، آوارہ", "fa": "قلندر، درویش", "hi": "क़लंदर, फ़क़ीर", "ps": "قلندر، درویش", "ar": "قَلَنْدَر (الْمُتَصَوِّف الْمُتَجَوِّل)"},
    "qamar": {"en": "Qamar; moon", "ur": "قمر، چاند", "fa": "قمر، ماه", "hi": "क़मर, चाँद", "ps": "قمر، سپوږمۍ", "ar": "الْقَمَر"},
    "qamarul": {"en": "Qamarul; moon of (construct)", "ur": "قمر ال، چاند", "fa": "قمر ال، ماه", "hi": "क़मरुल, चाँद", "ps": "قمر ال، سپوږمۍ", "ar": "قَمَرُ الـ (الْإِضَافَة)"},
    "qambar": {"en": "Qambar; a male given name", "ur": "قمبر (مردانہ نام)", "fa": "قمبر (نام مردانه)", "hi": "क़ंबर (पुरुष नाम)", "ps": "قمبر (نر نوم)", "ar": "قَمْبَر (اسْم عَلَم مُذَكَّر)"},
    "qani": {"en": "Qani; content, satisfied", "ur": "قانع، مطمئن", "fa": "قانع، خرسند", "hi": "क़ानि, संतुष्ट", "ps": "قانع، قناعت کوونکی", "ar": "الْقَانِع، الرَّاضِي"},
    "qari": {"en": "Qari; reciter of the Qur'an", "ur": "قاری، قرآن پڑھنے والا", "fa": "قاری، قرآن‌خوان", "hi": "क़ारी, क़ुरआन पाठक", "ps": "قاري، د قرآن لوستونکی", "ar": "الْقَارِئ، تَالِي الْقُرْآن"},
    "qarib": {"en": "Qarib; near, close", "ur": "قریب، نزدیک", "fa": "قریب، نزدیک", "hi": "क़रीब, निकट", "ps": "قریب، نږدې", "ar": "الْقَرِيب، الدَّانِي"},
    "qaseem": {"en": "Qasim; divider, distributor", "ur": "قاسم، تقسیم کرنے والا", "fa": "قاسم، تقسیم‌کننده", "hi": "क़ासिम, बाँटने वाला", "ps": "قاسم، ویشونکی", "ar": "قَاسِم، الْمُقَسِّم"},
    "qasid": {"en": "Qasid; messenger, courier", "ur": "قاصد، پیغام رساں", "fa": "قاصد، پیام‌آور", "hi": "क़ासिद, संदेशवाहक", "ps": "قاصد، پیغام رسول", "ar": "الْقَاصِد، الرَّسُول"},
    "qasim": {"en": "Qasim; divider, distributor", "ur": "قاسم، تقسیم کرنے والا", "fa": "قاسم، تقسیم‌کننده", "hi": "क़ासिम, बाँटने वाला", "ps": "قاسم، ویشونکی", "ar": "قَاسِم، الْمُقَسِّم"},
    "qassam": {"en": "Qassam; divider, distributor", "ur": "قسام، تقسیم کرنے والا", "fa": "قسام، تقسیم‌کننده", "hi": "क़स्साम, बाँटने वाला", "ps": "قسام، ویشونکی", "ar": "الْقَسَّام، الْمُقَسِّم"},
    "qassim": {"en": "Qassim; divider, distributor", "ur": "قاسم، تقسیم کرنے والا", "fa": "قاسم، تقسیم‌کننده", "hi": "क़ासिम, बाँटने वाला", "ps": "قاسم، ویشونکی", "ar": "قَاسِم، الْمُقَسِّم"},
    "qawi": {"en": "Qawi; strong, powerful", "ur": "قوی، طاقتور", "fa": "قوی، نیرومند", "hi": "क़वी, शक्तिशाली", "ps": "قوي، پیاوړی", "ar": "الْقَوِي، الشَّدِيد"},
    "qays": {"en": "Qays; a male given name", "ur": "قیس (مردانہ نام)", "fa": "قیس (نام مردانه)", "hi": "क़ैस (पुरुष नाम)", "ps": "قیس (نر نوم)", "ar": "قَيْس (اسْم عَلَم مُذَكَّر)"},
    "qaysar": {"en": "Qaysar; Caesar, emperor", "ur": "قیصر، بادشاہ", "fa": "قیصر، امپراتور", "hi": "क़ैसर, सम्राट", "ps": "قیصر، پاچا", "ar": "قَيْصَر (الْقَيْصَر)"},
    "qayyum": {"en": "Qayyum; eternal, self-subsisting", "ur": "قیوم، ازلی، قائم", "fa": "قیوم، پایدار", "hi": "क़य्यूम, शाश्वत", "ps": "قیوم، تلپاتې", "ar": "الْقَيُّوم، الدَّائِم"},
    "qazi": {"en": "Qazi; judge, arbiter", "ur": "قاضی، منصف", "fa": "قاضی، داور", "hi": "क़ाज़ी, न्यायाधीश", "ps": "قاضي، قاضي", "ar": "الْقَاضِي، الْحَاكِم"},
    "qazim": {"en": "Qazim; a male given name", "ur": "قاظم (مردانہ نام)", "fa": "قاظم (نام مردانه)", "hi": "क़ाज़िम (पुरुष नाम)", "ps": "قاظم (نر نوم)", "ar": "قَاظِم (اسْم عَلَم مُذَكَّر)"},
    "qismat": {"en": "Qismat; destiny, fate", "ur": "قسمت، تقدیر", "fa": "قسمت، سرنوشت", "hi": "क़िस्मत, भाग्य", "ps": "قسمت، برخه", "ar": "الْقِسْمَة، النَّصِيب"},
    "qistina": {"en": "Qistina; a female given name", "ur": "قسطینہ (زنانہ نام)", "fa": "قسطینا (نام زنانه)", "hi": "क़िस्तीना (स्त्री नाम)", "ps": "قسطینا (ښځينه نوم)", "ar": "قِسْتِينَا (اسْم عَلَم مُؤَنَّث)"},
    "quadir": {"en": "Quadir; powerful, capable", "ur": "قادر، طاقتور", "fa": "قادر، توانا", "hi": "क़ादिर, सक्षम", "ps": "قادر، توانا", "ar": "الْقَادِر، الْقَدِير"},
    "quaid": {"en": "Quaid; leader, chief", "ur": "قائد، رہنما", "fa": "قائد، رهبر", "hi": "क़ाइद, नेता", "ps": "قائد، مشر", "ar": "الْقَائِد، الزَّعِيم"},
    "quba": {"en": "Quba; a male given name", "ur": "قبہ (مردانہ نام)", "fa": "قبا (نام مردانه)", "hi": "क़ुबा (पुरुष नाम)", "ps": "قبا (نر نوم)", "ar": "قُبَاء (اسْم عَلَم مُذَكَّر)"},
    "qudrat": {"en": "Qudrat; power, ability", "ur": "قدرت، طاقت", "fa": "قدرت، توانایی", "hi": "क़ुदरत, शक्ति", "ps": "قدرت، ځواک", "ar": "الْقُدْرَة، الطَّاقَة"},
    "qudsia": {"en": "Qudsia; holy, sacred", "ur": "قدسیہ، مقدس", "fa": "قدسیه، مقدس", "hi": "क़ुदसिया, पवित्र", "ps": "قدسیه، مقدس", "ar": "الْقُدْسِيَّة، الْمُقَدَّسَة"},
    "qudus": {"en": "Qudus; holy, sacred", "ur": "قدوس، مقدس", "fa": "قدوس، مقدس", "hi": "क़ुद्दूस, पवित्र", "ps": "قدوس، مقدس", "ar": "الْقُدُّوس، الْمُقَدَّس"},
    "quraish": {"en": "Quraish; the Quraysh tribe", "ur": "قریش، قبیلہ قریش", "fa": "قریش، قبیله قریش", "hi": "क़ुरैश, क़ुरैश क़बीला", "ps": "قریش، د قریش قبیله", "ar": "قُرَيْش (اسْم قَبِيلَة)"},
    "quraisha": {"en": "Quraisha; a female given name", "ur": "قریشہ (زنانہ نام)", "fa": "قریشه (نام زنانه)", "hi": "क़ुरैशा (स्त्री नाम)", "ps": "قریشه (ښځينه نوم)", "ar": "قُرَيْشَة (اسْم عَلَم مُؤَنَّث)"},
    "qurban": {"en": "Qurban; sacrifice, offering", "ur": "قربان، نذر، قربانی", "fa": "قربان، فدا", "hi": "क़ुर्बान, बलिदान", "ps": "قربان، قرباني", "ar": "الْقُرْبَان، الْأُضْحِيَة"},
    "qureshi": {"en": "Qureshi; of the Quraysh (relational)", "ur": "قریشی، قریش سے منسوب", "fa": "قریشی، منسوب به قریش", "hi": "क़ुरैशी, क़ुरैश से संबंधित", "ps": "قریشي، د قریش اړوند", "ar": "الْقُرَشِي، مَنْسُوب إِلَى قُرَيْش"},
    "qusay": {"en": "Qusay; a male given name", "ur": "قصی (مردانہ نام)", "fa": "قصی (نام مردانه)", "hi": "क़ुसै (पुरुष नाम)", "ps": "قصی (نر نوم)", "ar": "قُصَيّ (اسْم عَلَم مُذَكَّر)"},
    "qutaiba": {"en": "Qutaiba; a male given name", "ur": "قطیبہ (مردانہ نام)", "fa": "قطیبه (نام مردانه)", "hi": "क़ुतैबा (पुरुष नाम)", "ps": "قطیبه (نر نوم)", "ar": "قُتَيْبَة (اسْم عَلَم مُذَكَّر)"},
    "qutaibah": {"en": "Qutaibah; a male given name", "ur": "قطیبہ (مردانہ نام)", "fa": "قطیبه (نام مردانه)", "hi": "क़ुतैबा (पुरुष नाम)", "ps": "قطیبه (نر نوم)", "ar": "قُتَيْبَة (اسْم عَلَم مُذَكَّر)"},
    "qutub": {"en": "Qutub; axis, pole", "ur": "قطب، محور", "fa": "قطب، محور", "hi": "क़ुतुब, ध्रुव", "ps": "قطب، محور", "ar": "الْقُطْب، الْمِحْوَر"},
    "ra-ana": {"en": "Ra'ana; a female given name", "ur": "رعانہ (زنانہ نام)", "fa": "رعانا (نام زنانه)", "hi": "रआना (स्त्री नाम)", "ps": "رعانا (ښځينه نوم)", "ar": "رَعَانَة (اسْم عَلَم مُؤَنَّث)"},
    "ra-uf": {"en": "Ra'uf; compassionate, kind", "ur": "رؤف، مہربان", "fa": "رئوف، مهربان", "hi": "रऊफ़, दयालु", "ps": "رئوف، مهربان", "ar": "الرَّءُوف، الرَّحِيم"},
    "raad": {"en": "Raad; thunder", "ur": "رعد، گرج", "fa": "رعد، آذرخش", "hi": "राद, गर्जन", "ps": "رعد، تندر", "ar": "الرَّعْد"},
    "raafat": {"en": "Raafat; compassion, mercy", "ur": "رافت، رحم، مہربانی", "fa": "رأفت، مهربانی", "hi": "राफ़त, दया", "ps": "رافت، مهرباني", "ar": "الرَّأْفَة، الرَّحْمَة"},
    "raani": {"en": "Raani; queen, princess", "ur": "رانی، ملکہ", "fa": "رانی، ملکه", "hi": "रानी, रानी", "ps": "راني، ملکه", "ar": "رَانِي (الْمَلِكَة)"},
    "raashid": {"en": "Raashid; rightly guided", "ur": "راشد، ہدایت یافتہ", "fa": "راشد، هدایت‌یافته", "hi": "राशिद, सन्मार्गी", "ps": "راشد، سم لارښود", "ar": "الرَّاشِد، الْمُهْتَدِي"},
    "raaya": {"en": "Raaya; a female given name", "ur": "رایہ (زنانہ نام)", "fa": "رایا (نام زنانه)", "hi": "राया (स्त्री नाम)", "ps": "رایا (ښځينه نوم)", "ar": "رَايَة (اسْم عَلَم مُؤَنَّث)"},
    "rab": {"en": "Rab; lord, master", "ur": "رب، مالک، پروردگار", "fa": "رب، پروردگار", "hi": "रब, स्वामी", "ps": "رب، مالک", "ar": "الرَّبّ، الْمَالِك"},
    "rabaa": {"en": "Rabaa; a female given name", "ur": "رباء (زنانہ نام)", "fa": "رباء (نام زنانه)", "hi": "रबा (स्त्री नाम)", "ps": "رباء (ښځينه نوم)", "ar": "رَبَاء (اسْم عَلَم مُؤَنَّث)"},
    "rabab": {"en": "Rabab; a stringed instrument", "ur": "رباب، ساز", "fa": "رباب، ساز", "hi": "रबाब, वाद्य", "ps": "رباب، ساز", "ar": "الرَّبَاب (آلَة مُوسِيقِيَّة)"},
    "rabah": {"en": "Rabah; profit, gain", "ur": "رباح، نفع، فائدہ", "fa": "رباح، سود", "hi": "रबाह, लाभ", "ps": "رباح، ګټه", "ar": "الرَّبَاح، الرِّبْح"},
    "rabar": {"en": "Rabar; a male given name (Kurdish)", "ur": "ربار (مردانہ نام)", "fa": "ربار (نام مردانه)", "hi": "रबार (पुरुष नाम)", "ps": "ربار (نر نوم)", "ar": "رَبَار (اسْم عَلَم كُرْدِيّ)"},
    "rabbani": {"en": "Rabbani; divine, of the Lord", "ur": "ربانی، رب سے منسوب", "fa": "ربانی، منسوب به رب", "hi": "रब्बानी, ईश्वरीय", "ps": "رباني، د رب اړوند", "ar": "الرَّبَّانِي، مَنْسُوب إِلَى الرَّبّ"},
    "rabea": {"en": "Rabea; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیعه، بهار", "hi": "रबीआ, वसंत", "ps": "ربیعه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rabee": {"en": "Rabee; spring", "ur": "ربیع، بہار", "fa": "ربیع، بهار", "hi": "रबी, वसंत", "ps": "ربیع، پسرلی", "ar": "الرَّبِيع"},
    "rabeea": {"en": "Rabeea; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیعه، بهار", "hi": "रबीआ, वसंत", "ps": "ربیعه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rabeeh": {"en": "Rabeeh; spring", "ur": "ربیع، بہار", "fa": "ربیع، بهار", "hi": "रबीह, वसंत", "ps": "ربیع، پسرلی", "ar": "الرَّبِيع"},
    "rabi": {"en": "Rabi; spring", "ur": "ربیع، بہار", "fa": "ربیع، بهار", "hi": "रबी, वसंत", "ps": "ربیع، پسرلی", "ar": "الرَّبِيع"},
    "rabia": {"en": "Rabia; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیعه، بهار", "hi": "रबिया, वसंत", "ps": "ربیعه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rabiaa": {"en": "Rabiaa; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیعه، بهار", "hi": "रबिया, वसंत", "ps": "ربیعه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rabiah": {"en": "Rabiah; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیعه، بهار", "hi": "रबिया, वसंत", "ps": "ربیعه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rabih": {"en": "Rabih; profitable, gainful", "ur": "رابح، نفع مند", "fa": "رابح، سودمند", "hi": "राबिह, लाभदायक", "ps": "رابح، ګټور", "ar": "الرَّابِح، الْمُفِيد"},
    "rabiha": {"en": "Rabiha; a female given name", "ur": "رابحہ (زنانہ نام)", "fa": "رابحه (نام زنانه)", "hi": "राबिहा (स्त्री नाम)", "ps": "رابحه (ښځينه نوم)", "ar": "رَابِحَة (اسْم عَلَم مُؤَنَّث)"},
    "rabitah": {"en": "Rabitah; bond, tie", "ur": "رابطہ، تعلق", "fa": "رابطه، پیوند", "hi": "राबिता, संबंध", "ps": "رابطه، اړیکه", "ar": "الرَّابِطَة، الْعَلَاقَة"},
    "rabiya": {"en": "Rabiya; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیه، بهار", "hi": "रबिया, वसंत", "ps": "ربیه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rabiye": {"en": "Rabiye; spring (feminine)", "ur": "ربیعہ، بہار", "fa": "ربیه، بهار", "hi": "रबिया, वसंत", "ps": "ربیه، پسرلی", "ar": "رَبِيعَة، الرَّبِيع"},
    "rachid": {"en": "Rachid; rightly guided", "ur": "راشد، ہدایت یافتہ", "fa": "راشد، هدایت‌یافته", "hi": "रशीद, सन्मार्गी", "ps": "راشد، سم لارښود", "ar": "الرَّاشِد، الْمُهْتَدِي"},
    "rachida": {"en": "Rachida; rightly guided (feminine)", "ur": "راشدہ، ہدایت یافتہ", "fa": "راشده، هدایت‌یافته", "hi": "रशीदा, सन्मार्गी", "ps": "راشده، سم لارښوده", "ar": "الرَّاشِدَة، الْمُهْتَدِيَة"},
    "rad": {"en": "Rad; a male given name", "ur": "رض (مردانہ نام)", "fa": "رض (نام مردانه)", "hi": "रद (पुरुष नाम)", "ps": "رض (نر نوم)", "ar": "رَض (اسْم عَلَم مُذَكَّر)"},
    "radhi": {"en": "Radhi; content, pleased", "ur": "رضی، مطمئن، خوش", "fa": "رضی، خرسند", "hi": "रज़ी, संतुष्ट", "ps": "رضی، قناعت کوونکی", "ar": "الرَّضِي، الرَّاضِي"},
    "radhia": {"en": "Radhia; content, pleased (feminine)", "ur": "رضیہ، مطمئن", "fa": "رضیه، خرسند", "hi": "रज़िया, संतुष्ट", "ps": "رضیه، قناعت کوونکې", "ar": "رَضِيَّة، الرَّاضِيَة"},
    "radhiya": {"en": "Radhiya; content, pleased (feminine)", "ur": "رضیہ، مطمئن", "fa": "رضیه، خرسند", "hi": "रज़िया, संतुष्ट", "ps": "رضیه، قناعت کوونکې", "ar": "رَضِيَّة، الرَّاضِيَة"},
    "radi": {"en": "Radi; content, pleased", "ur": "راضی، مطمئن", "fa": "راضی، خرسند", "hi": "राज़ी, संतुष्ट", "ps": "راضي، قناعت کوونکی", "ar": "الرَّاضِي، الْقَانِع"},
    "radifa": {"en": "Radifa; a female given name", "ur": "رادفہ (زنانہ نام)", "fa": "رادفه (نام زنانه)", "hi": "रादिफ़ा (स्त्री नाम)", "ps": "رادفه (ښځينه نوم)", "ar": "رَادِفَة (اسْم عَلَم مُؤَنَّث)"},
    "radil": {"en": "Radil; a male given name", "ur": "راضل (مردانہ نام)", "fa": "راضل (نام مردانه)", "hi": "रादिल (पुरुष नाम)", "ps": "راضل (نر نوم)", "ar": "رَاضِل (اسْم عَلَم مُذَكَّر)"},
    "raditya": {"en": "Raditya; a male given name (Indonesian)", "ur": "رادتیہ (مردانہ نام)", "fa": "رادیتیا (نام مردانه)", "hi": "रादित्य (पुरुष नाम)", "ps": "رادیتیا (نر نوم)", "ar": "رَادِيتْيَا (اسْم عَلَم إِنْدُونِيسِيّ)"},
    "radiya": {"en": "Radiya; content, pleased (feminine)", "ur": "رضیہ، مطمئن", "fa": "رضیه، خرسند", "hi": "रज़िया, संतुष्ट", "ps": "رضیه، قناعت کوونکې", "ar": "رَضِيَّة، الرَّاضِيَة"},
    "radiyah": {"en": "Radiyah; content, pleased (feminine)", "ur": "رضیہ، مطمئن", "fa": "رضیه، خرسند", "hi": "रज़िया, संतुष्ट", "ps": "رضیه، قناعت کوونکې", "ar": "رَضِيَّة، الرَّاضِيَة"},
    "radman": {"en": "Radman; a male given name", "ur": "رضان (مردانہ نام)", "fa": "رضان (نام مردانه)", "hi": "रदमान (पुरुष नाम)", "ps": "رضان (نر نوم)", "ar": "رَضْمَان (اسْم عَلَم مُذَكَّر)"},
    "radwa": {"en": "Radwa; a female given name", "ur": "رضوہ (زنانہ نام)", "fa": "رضوه (نام زنانه)", "hi": "रदवा (स्त्री नाम)", "ps": "رضوه (ښځينه نوم)", "ar": "رَضْوَة (اسْم عَلَم مُؤَنَّث)"},
    "raed": {"en": "Raed; leader, pioneer", "ur": "رائد، رہنما، پیش رو", "fa": "رائد، پیشرو", "hi": "राइद, अग्रणी", "ps": "رائد، مشر", "ar": "الرَّائِد، الْقَائِد"},
    "raeda": {"en": "Raeda; leader, pioneer (feminine)", "ur": "رائدہ، رہنما", "fa": "رائده، پیشرو", "hi": "राइदा, अग्रणी", "ps": "رائده، مشره", "ar": "الرَّائِدَة، الْقَائِدَة"},
    "raeed": {"en": "Raeed; leader, pioneer", "ur": "رائد، رہنما", "fa": "رائد، پیشرو", "hi": "राइद, अग्रणी", "ps": "رائد، مشر", "ar": "الرَّائِد، الْقَائِد"},
    "raeeda": {"en": "Raeeda; leader, pioneer (feminine)", "ur": "رائدہ، رہنما", "fa": "رائده، پیشرو", "hi": "राइदा, अग्रणी", "ps": "رائده، مشره", "ar": "الرَّائِدَة، الْقَائِدَة"},
    "raeef": {"en": "Raeef; compassionate, kind", "ur": "رئيف، مہربان", "fa": "رئوف، مهربان", "hi": "रईफ़, दयालु", "ps": "رئيف، مهربان", "ar": "الرَّءُوف، الرَّحِيم"},
    "raees": {"en": "Raees; leader, chief", "ur": "رئیس، سردار، رہنما", "fa": "رئیس، رهبر", "hi": "रईस, नेता", "ps": "رئیس، مشر", "ar": "الرَّئِيس، الزَّعِيم"},
    "raeesa": {"en": "Raeesa; leader, chief (feminine)", "ur": "رئیسہ، سردارنی", "fa": "رئیسه، رهبر", "hi": "रईसा, नेत्री", "ps": "رئیسه، مشره", "ar": "الرَّئِيسَة، الزَّعِيمَة"},
    "raeesah": {"en": "Raeesah; leader, chief (feminine)", "ur": "رئیسہ، سردارنی", "fa": "رئیسه، رهبر", "hi": "रईसा, नेत्री", "ps": "رئیسه، مشره", "ar": "الرَّئِيسَة، الزَّعِيمَة"},
    "rafaa": {"en": "Rafaa; a male given name", "ur": "رفاع (مردانہ نام)", "fa": "رفاع (نام مردانه)", "hi": "रफ़ा (पुरुष नाम)", "ps": "رفاع (نر نوم)", "ar": "رَفَاع (اسْم عَلَم مُذَكَّر)"},
    "rafaat": {"en": "Rafaat; elevation, dignity", "ur": "رفعت، بلندی، عزت", "fa": "رفعت، بلندی", "hi": "रफ़ात, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
})

CUR = {
 "pouran": ("بُورَان", "پوران", "پوران", "पूरान", "پوران", "pouran", "Persian", "Female",
            "Persian پوران (pūrān)", False, "high",
            "Pouran is a Persian female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the name is Persian. The source gloss 'Heavenly nourisher' is unsupported and has been replaced with the documented identification."),
 "purnama": ("بُورْنَامَا", "پورناما", "پورناما", "पूर्णमा", "پورناما", "purnama", "Indonesian", "Female",
             "Indonesian purnama 'full moon'", False, "high",
             "Purnama is an Indonesian/Malay female given name, from purnama 'full moon'. CRITICAL SOURCE ERROR: the source gave بورناما (a non-standard form) and labelled the origin Arabic; the word is Indonesian. The source gloss 'Full Moon' is consistent."),
 "qaasim": ("قَاسِم", "قاسم", "قاسم", "क़ासिम", "قاسم", "qaasim", "Arabic", "Male",
            "Arabic root ق س م (q-s-m); قَاسِم (Qāsim)", False, "high",
            "Qaasim is Arabic قَاسِم (Qāsim) 'divider, distributor', from the root ق س م (q-s-m). The source gloss 'Builder, Creator' is unsupported and has been replaced with the lexical sense. Same name as qasim."),
 "qabil": ("قَابِيل", "قابیل", "قابیل", "क़ाबिल", "قابیل", "qabil", "Arabic", "Male",
           "Arabic قَابِيل (Qābīl)", False, "high",
           "Qabil is Arabic قَابِيل (Qābīl), a male given name (the biblical Cain). The source gloss 'Acceptable, tolerable' is unsupported and has been replaced with the documented identification."),
 "qadar": ("قَدَر", "قدر", "قدر", "क़दर", "قدر", "qadar", "Arabic", "Male",
           "Arabic root ق د ر (q-d-r); قَدَر (Qadar)", False, "high",
           "Qadar is Arabic قَدَر (Qadar) 'decree, destiny', from the root ق د ر (q-d-r). The source gloss 'Divine Decree' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "qadeem": ("قَدِيم", "قدیم", "قدیم", "क़दीम", "قدیم", "qadeem", "Arabic", "Male",
            "Arabic root ق د م (q-d-m); قَدِيم (Qadīm)", False, "high",
            "Qadeem is Arabic قَدِيم (Qadīm) 'ancient, old', from the root ق د م (q-d-m). The source gloss 'Ancient, Old, Wise' is broadly consistent."),
 "qadeer": ("قَدِير", "قدیر", "قدیر", "क़दीर", "قدیر", "qadeer", "Arabic", "Male",
            "Arabic root ق د ر (q-d-r); قَدِير (Qadīr)", False, "high",
            "Qadeer is Arabic قَدِير (Qadīr) 'powerful, capable', from the root ق د ر (q-d-r). The source gloss 'Powerful' is consistent. Same name as qadir."),
 "qadir": ("قَادِر", "قادر", "قادر", "क़ादिर", "قادر", "qadir", "Arabic", "Male",
           "Arabic root ق د ر (q-d-r); قَادِر (Qādir)", False, "high",
           "Qadir is Arabic قَادِر (Qādir) 'powerful, capable', from the root ق د ر (q-d-r). The source gloss 'Powerful, Capable, Strong' is consistent. Same name as qadeer."),
 "qadr": ("قَدْر", "قدر", "قدر", "क़द्र", "قدر", "qadr", "Arabic", "Male",
          "Arabic root ق د ر (q-d-r); قَدْر (Qadr)", False, "high",
          "Qadr is Arabic قَدْر (Qadr) 'decree, destiny', from the root ق د ر (q-d-r). The source gloss 'Divine decree, predestination' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as qadar."),
 "qadri": ("قَادِرِي", "قادری", "قادری", "क़ादरी", "قادري", "qadri", "Arabic", "Male",
           "Arabic قَادِرِي (Qādirī) 'of Qadir'", False, "high",
           "Qadri is Arabic قَادِرِي (Qādirī) 'of Qadir', a relational adjective from قَادِر (Qādir). The source gloss 'Powerful, Capable, Able' is unsupported and has been replaced with the lexical sense."),
 "qahir": ("قَاهِر", "قاہر", "قاهر", "क़ाहिर", "قاهر", "qahir", "Arabic", "Male",
           "Arabic root ق ه ر (q-h-r); قَاهِر (Qāhir)", False, "high",
           "Qahir is Arabic قَاهِر (Qāhir) 'conqueror, subduer', from the root ق ه ر (q-h-r). The source gloss 'Conqueror' is consistent."),
 "qahtan": ("قَحْطَان", "قحطان", "قحطان", "क़हतान", "قحطان", "qahtan", "Arabic", "Male",
            "Arabic قَحْطَان (Qaḥṭān)", False, "high",
            "Qahtan is Arabic قَحْطَان (Qaḥṭān), a male given name (the ancestor of the southern Arabs). The source gloss 'Owner of the plain, fertile lands' is unsupported and has been replaced with the documented identification."),
 "qaid": ("قَائِد", "قائد", "قائد", "क़ाइद", "قائد", "qaid", "Arabic", "Male",
          "Arabic root ق و د (q-w-d); قَائِد (Qāʾid)", False, "high",
          "Qaid is Arabic قَائِد (Qāʾid) 'leader, commander', from the root ق و د (q-w-d). CRITICAL SOURCE ERROR: the source gave قيد (a different form); the correct form is قَائِد. The source gloss 'Able, Capable' is unsupported and has been replaced with the lexical sense. Same name as quaid."),
 "qaim": ("قَائِم", "قائم", "قائم", "क़ाइम", "قائم", "qaim", "Arabic", "Male",
          "Arabic root ق و م (q-w-m); قَائِم (Qāʾim)", False, "high",
          "Qaim is Arabic قَائِم (Qāʾim) 'standing, upright', from the root ق و م (q-w-m). The source gloss 'Established, Upright' is consistent."),
 "qais": ("قَيْس", "قیس", "قیس", "क़ैस", "قیس", "qais", "Arabic", "Male",
          "Arabic قَيْس (Qays)", False, "high",
          "Qais is Arabic قَيْس (Qays), a male given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as qays."),
 "qaisar": ("قَيْصَر", "قیصر", "قیصر", "क़ैसर", "قیصر", "qaisar", "Arabic", "Male",
            "Arabic قَيْصَر (Qayṣar), from Latin Caesar", False, "high",
            "Qaisar is Arabic قَيْصَر (Qayṣar) 'Caesar, emperor', a borrowing from Latin Caesar. The source gloss 'Caesar or Emperor' is consistent. Same name as qaysar."),
 "qalandar": ("قَلَنْدَر", "قلندر", "قلندر", "क़लंदर", "قلندر", "qalandar", "Persian", "Male",
              "Persian قلندر (qalandar)", False, "high",
              "Qalandar is Persian قلندر (qalandar) 'wandering ascetic'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Wanderer' is broadly consistent."),
 "qamar": ("قَمَر", "قمر", "قمر", "क़मर", "قمر", "qamar", "Arabic", "Male",
           "Arabic root ق م ر (q-m-r); قَمَر (Qamar)", False, "high",
           "Qamar is Arabic قَمَر (Qamar) 'moon', from the root ق م ر (q-m-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "qamarul": ("قَمَرُ الـ", "قمر ال", "قمر ال", "क़मरुल", "قمر ال", "qamarul", "Arabic", "Male",
             "Arabic قَمَر (qamar) in construct with the article", False, "high",
             "Qamarul is Arabic قَمَرُ الـ (Qamaru l-) 'moon of', a construct form of قَمَر (qamar) 'moon'. The source gloss 'Moon of the' is a truncated construct. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "qambar": ("قَمْبَر", "قمبر", "قمبر", "क़ंबर", "قمبر", "qambar", "Arabic", "Male",
            "Arabic قَمْبَر (Qambar)", False, "high",
            "Qambar is Arabic قَمْبَر (Qambar), a male given name. The source gloss 'Servant of the Omnipotent' is unsupported and has been replaced with the documented identification."),
 "qani": ("قَانِع", "قانع", "قانع", "क़ानि", "قانع", "qani", "Arabic", "Male",
          "Arabic root ق ن ع (q-n-ʿ); قَانِع (Qāniʿ)", False, "high",
          "Qani is Arabic قَانِع (Qāniʿ) 'content, satisfied', from the root ق ن ع (q-n-ʿ). The source gloss 'Intelligent, Wise, Knowledgeable' is unsupported and has been replaced with the lexical sense."),
 "qari": ("قَارِئ", "قاری", "قاری", "क़ारी", "قاري", "qari", "Arabic", "Male",
          "Arabic root ق ر أ (q-r-ʾ); قَارِئ (Qāriʾ)", False, "high",
          "Qari is Arabic قَارِئ (Qāriʾ) 'reciter of the Qur'an', from the root ق ر أ (q-r-ʾ). CRITICAL SOURCE ERROR: the source gave قرئي (a non-standard form); the correct form is قَارِئ. The source gloss 'One who recites Quran' is consistent."),
 "qarib": ("قَرِيب", "قریب", "قریب", "क़रीब", "قریب", "qarib", "Arabic", "Male",
           "Arabic root ق ر ب (q-r-b); قَرِيب (Qarīb)", False, "high",
           "Qarib is Arabic قَرِيب (Qarīb) 'near, close', from the root ق ر ب (q-r-b). The source gloss 'Near, Close' is consistent."),
 "qaseem": ("قَاسِم", "قاسم", "قاسم", "क़ासिम", "قاسم", "qaseem", "Arabic", "Male",
            "Arabic root ق س م (q-s-m); قَاسِم (Qāsim)", False, "high",
            "Qaseem is a spelling variant of Arabic قَاسِم (Qāsim) 'divider, distributor', from the root ق س م (q-s-m). The source gloss 'Able to decide' is unsupported and has been replaced with the lexical sense. Same name as qasim."),
 "qasid": ("قَاصِد", "قاصد", "قاصد", "क़ासिद", "قاصد", "qasid", "Arabic", "Male",
           "Arabic root ق ص د (q-ṣ-d); قَاصِد (Qāṣid)", False, "high",
           "Qasid is Arabic قَاصِد (Qāṣid) 'messenger, courier', from the root ق ص د (q-ṣ-d). The source gloss 'Reciter' is unsupported and has been replaced with the lexical sense."),
 "qasim": ("قَاسِم", "قاسم", "قاسم", "क़ासिम", "قاسم", "qasim", "Arabic", "Male",
           "Arabic root ق س م (q-s-m); قَاسِم (Qāsim)", False, "high",
           "Qasim is Arabic قَاسِم (Qāsim) 'divider, distributor', from the root ق س م (q-s-m). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as qaasim."),
 "qassam": ("قَسَّام", "قسام", "قسام", "क़स्साम", "قسام", "qassam", "Arabic", "Male",
            "Arabic root ق س م (q-s-m); قَسَّام (Qassām)", False, "high",
            "Qassam is Arabic قَسَّام (Qassām) 'divider, distributor', an intensive form from the root ق س م (q-s-m). The source gloss 'announcer, proclaimer' is unsupported and has been replaced with the lexical sense."),
 "qassim": ("قَاسِم", "قاسم", "قاسم", "क़ासिम", "قاسم", "qassim", "Arabic", "Male",
            "Arabic root ق س م (q-s-m); قَاسِم (Qāsim)", False, "high",
            "Qassim is a spelling variant of Arabic قَاسِم (Qāsim) 'divider, distributor', from the root ق س م (q-s-m). The source gloss 'Justice and fairness' is unsupported and has been replaced with the lexical sense. Same name as qasim."),
 "qawi": ("قَوِي", "قوی", "قوی", "क़वी", "قوي", "qawi", "Arabic", "Male",
          "Arabic root ق و ي (q-w-y); قَوِي (Qawī)", False, "high",
          "Qawi is Arabic قَوِي (Qawī) 'strong, powerful', from the root ق و ي (q-w-y). The source gloss 'Strong, Powerful' is consistent."),
 "qays": ("قَيْس", "قیس", "قیس", "क़ैस", "قیس", "qays", "Arabic", "Male",
          "Arabic قَيْس (Qays)", False, "high",
          "Qays is Arabic قَيْس (Qays), a male given name. The source gloss 'Firm, strong, or steadfast' is unsupported and has been replaced with the documented identification. Same name as qais."),
 "qaysar": ("قَيْصَر", "قیصر", "قیصر", "क़ैसर", "قیصر", "qaysar", "Arabic", "Male",
            "Arabic قَيْصَر (Qayṣar), from Latin Caesar", False, "high",
            "Qaysar is a spelling variant of Arabic قَيْصَر (Qayṣar) 'Caesar, emperor', a borrowing from Latin Caesar. CRITICAL SOURCE ERROR: the source gave قيسر (a non-standard form). The source gloss 'Caesar, Emperor' is consistent. Same name as qaisar."),
 "qayyum": ("قَيُّوم", "قیوم", "قیوم", "क़य्यूम", "قیوم", "qayyum", "Arabic", "Male",
            "Arabic root ق و م (q-w-m); قَيُّوم (Qayyūm)", False, "high",
            "Qayyum is Arabic قَيُّوم (Qayyūm) 'eternal, self-subsisting', from the root ق و م (q-w-m). The source gloss 'Eternal, Immortal' is broadly consistent."),
 "qazi": ("قَاضِي", "قاضی", "قاضی", "क़ाज़ी", "قاضي", "qazi", "Arabic", "Male",
          "Arabic root ق ض ي (q-ḍ-y); قَاضِي (Qāḍī)", False, "high",
          "Qazi is Arabic قَاضِي (Qāḍī) 'judge, arbiter', from the root ق ض ي (q-ḍ-y). The source gloss 'Judge, Arbiter' is consistent."),
 "qazim": ("قَاظِم", "قاظم", "قاظم", "क़ाज़िम", "قاظم", "qazim", "Arabic", "Male",
           "Arabic قَاظِم (Qāẓim)", False, "medium",
           "Qazim is recorded as Arabic قَاظِم (Qāẓim), a male given name. CRITICAL SOURCE ERROR: the source gave قاظم (a non-standard form). The source gloss 'Powerful, Intelligent' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "qismat": ("قِسْمَة", "قسمت", "قسمت", "क़िस्मत", "قسمت", "qismat", "Arabic", "Female",
            "Arabic root ق س م (q-s-m); قِسْمَة (Qisma)", False, "high",
            "Qismat is Arabic قِسْمَة (Qisma) 'destiny, fate', from the root ق س م (q-s-m). The source gloss 'Destiny' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "qistina": ("قِسْتِينَا", "قسطینہ", "قسطینا", "क़िस्तीना", "قسطینا", "qistina", "Arabic", "Female",
             "Arabic قِسْتِينَا (Qistīnā)", False, "medium",
             "Qistina is recorded as Arabic قِسْتِينَا (Qistīnā), a female given name. The source gloss 'Bright, shining, pure' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "quadir": ("قَادِر", "قادر", "قادر", "क़ादिर", "قادر", "quadir", "Arabic", "Male",
            "Arabic root ق د ر (q-d-r); قَادِر (Qādir)", False, "high",
            "Quadir is a spelling variant of Arabic قَادِر (Qādir) 'powerful, capable', from the root ق د ر (q-d-r). CRITICAL SOURCE ERROR: the source gave قدر (a different form). The source gloss 'Strong, Powerful, Master' is broadly consistent. Same name as qadir."),
 "quaid": ("قَائِد", "قائد", "قائد", "क़ाइद", "قائد", "quaid", "Arabic", "Male",
           "Arabic root ق و د (q-w-d); قَائِد (Qāʾid)", False, "high",
           "Quaid is Arabic قَائِد (Qāʾid) 'leader, chief', from the root ق و د (q-w-d). The source gloss 'Leader, Chief' is consistent. Same name as qaid."),
 "quba": ("قُبَاء", "قبہ", "قبا", "क़ुबा", "قبا", "quba", "Arabic", "Male",
          "Arabic قُبَاء (Qubāʾ)", False, "high",
          "Quba is Arabic قُبَاء (Qubāʾ), a place name used as a male given name. CRITICAL SOURCE ERROR: the source gave قبة (a different form); the correct form is قُبَاء. The source gloss 'Ancient house or mosque' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "qudrat": ("قُدْرَة", "قدرت", "قدرت", "क़ुदरत", "قدرت", "qudrat", "Arabic", "Female",
            "Arabic root ق د ر (q-d-r); قُدْرَة (Qudra)", False, "high",
            "Qudrat is Arabic قُدْرَة (Qudra) 'power, ability', from the root ق د ر (q-d-r). The source gloss 'Power, Ability, Capacity' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "qudsia": ("قُدْسِيَّة", "قدسیہ", "قدسیه", "क़ुदसिया", "قدسیه", "qudsia", "Arabic", "Female",
            "Arabic قُدْسِيَّة (Qudsiyya) 'holy'", False, "high",
            "Qudsia is Arabic قُدْسِيَّة (Qudsiyya) 'holy, sacred', a relational adjective from قُدْس (quds) 'holiness'. The source gloss 'Holy' is consistent."),
 "qudus": ("قُدُّوس", "قدوس", "قدوس", "क़ुद्दूस", "قدوس", "qudus", "Arabic", "Male",
           "Arabic root ق د س (q-d-s); قُدُّوس (Quddūs)", False, "high",
           "Qudus is Arabic قُدُّوس (Quddūs) 'holy, sacred', from the root ق د س (q-d-s). The source gloss \"God's Possession\" is unsupported and has been replaced with the lexical sense."),
 "quraish": ("قُرَيْش", "قریش", "قریش", "क़ुरैश", "قریش", "quraish", "Arabic", "Male",
             "Arabic قُرَيْش (Quraysh), a tribe name", False, "high",
             "Quraish is Arabic قُرَيْش (Quraysh), the name of the tribe of the Prophet, used as a male given name. The source gloss 'Honorable' is unsupported and has been replaced with the documented identification."),
 "quraisha": ("قُرَيْشَة", "قریشہ", "قریشه", "क़ुरैशा", "قریشه", "quraisha", "Arabic", "Female",
              "Arabic قُرَيْشَة (Quraysha)", False, "high",
              "Quraisha is Arabic قُرَيْشَة (Quraysha), a female given name derived from قُرَيْش (Quraysh). CRITICAL SOURCE ERROR: the source gave قرعيشة (a non-standard form). The source gloss 'Young She-camel' is unsupported and has been replaced with the documented identification."),
 "qurban": ("قُرْبَان", "قربان", "قربان", "क़ुर्बान", "قربان", "qurban", "Arabic", "Male",
            "Arabic root ق ر ب (q-r-b); قُرْبَان (Qurbān)", False, "high",
            "Qurban is Arabic قُرْبَان (Qurbān) 'sacrifice, offering', from the root ق ر ب (q-r-b). The source gloss 'Devotion, Sacrifice' is broadly consistent."),
 "qureshi": ("قُرَشِي", "قریشی", "قریشی", "क़ुरैशी", "قریشي", "qureshi", "Urdu", "Male",
             "Urdu قریشی (qureshī), from Arabic قُرَشِيّ", False, "high",
             "Qureshi is Urdu قریشی (qureshī) 'of the Quraysh', a relational surname/name from Arabic قُرَشِيّ. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Urdu/Punjabi. The source gloss 'noble, learned' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "qusay": ("قُصَيّ", "قصی", "قصی", "क़ुसै", "قصی", "qusay", "Arabic", "Male",
           "Arabic قُصَيّ (Quṣayy)", False, "high",
           "Qusay is Arabic قُصَيّ (Quṣayy), a male given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "qutaiba": ("قُتَيْبَة", "قطیبہ", "قطیبه", "क़ुतैबा", "قطیبه", "qutaiba", "Arabic", "Male",
             "Arabic قُتَيْبَة (Qutayba)", False, "high",
             "Qutaiba is Arabic قُتَيْبَة (Qutayba), a male given name. The source gloss 'The one who strikes terror' is unsupported and has been replaced with the documented identification. Same name as qutaibah."),
 "qutaibah": ("قُتَيْبَة", "قطیبہ", "قطیبه", "क़ुतैबा", "قطیبه", "qutaibah", "Arabic", "Male",
              "Arabic قُتَيْبَة (Qutayba)", False, "high",
              "Qutaibah is Arabic قُتَيْبَة (Qutayba), a male given name. CRITICAL SOURCE ERROR: the source gave قطايبه (a non-standard form). The source gloss 'Warrior, victor, conqueror' is unsupported and has been replaced with the documented identification. Same name as qutaiba."),
 "qutub": ("قُطْب", "قطب", "قطب", "क़ुतुब", "قطب", "qutub", "Arabic", "Male",
           "Arabic root ق ط ب (q-ṭ-b); قُطْب (Quṭb)", False, "high",
           "Qutub is Arabic قُطْب (Quṭb) 'axis, pole', from the root ق ط ب (q-ṭ-b). The source gloss 'Axis, pillar' is broadly consistent."),
 "ra-ana": ("رَعَانَة", "رعانہ", "رعانا", "रआना", "رعانا", "ra-ana", "Arabic", "Female",
            "Arabic رَعَانَة (Raʿāna)", False, "medium",
            "Ra'ana is recorded as Arabic رَعَانَة (Raʿāna), a female given name. CRITICAL SOURCE ERROR: the source gave رعانا (a non-standard form). The source gloss 'Compassionate' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ra-uf": ("رَءُوف", "رؤف", "رئوف", "रऊफ़", "رئوف", "ra-uf", "Arabic", "Male",
           "Arabic root ر أ ف (r-ʾ-f); رَءُوف (Raʾūf)", False, "high",
           "Ra'uf is Arabic رَءُوف (Raʾūf) 'compassionate, kind', from the root ر أ ف (r-ʾ-f). CRITICAL SOURCE ERROR: the source gave رعوف (a non-standard form); the correct form is رَءُوف. The source gloss 'Gentle, Kind' is broadly consistent."),
 "raad": ("رَعْد", "رعد", "رعد", "राद", "رعد", "raad", "Arabic", "Male",
          "Arabic root ر ع د (r-ʿ-d); رَعْد (Raʿd)", False, "high",
          "Raad is Arabic رَعْد (Raʿd) 'thunder', from the root ر ع د (r-ʿ-d). The source gloss 'Thunder' is consistent."),
 "raafat": ("رَأْفَة", "رافت", "رأفت", "राफ़त", "رافت", "raafat", "Arabic", "Male",
            "Arabic root ر أ ف (r-ʾ-f); رَأْفَة (Raʾfa)", False, "high",
            "Raafat is Arabic رَأْفَة (Raʾfa) 'compassion, mercy', from the root ر أ ف (r-ʾ-f). CRITICAL SOURCE ERROR: the source gave رافع (a different name); the correct form is رَأْفَة. The source gloss 'Compassionate' is broadly consistent."),
 "raani": ("رَانِي", "رانی", "رانی", "रानी", "راني", "raani", "Arabic", "Female",
           "Arabic رَانِي (Rānī)", False, "medium",
           "Raani is recorded as Arabic رَانِي (Rānī), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Raani' instead of a script form. The source gloss 'Queen, Princess' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raashid": ("رَاشِد", "راشد", "راشد", "राशिद", "راشد", "raashid", "Arabic", "Male",
             "Arabic root ر ش د (r-sh-d); رَاشِد (Rāshid)", False, "high",
             "Raashid is Arabic رَاشِد (Rāshid) 'rightly guided', from the root ر ش د (r-sh-d). The source gloss 'Rightly Guided' is consistent. Same name as rachid."),
 "raaya": ("رَايَة", "رایہ", "رایا", "राया", "رایا", "raaya", "Arabic", "Female",
           "Arabic رَايَة (Rāya)", False, "medium",
           "Raaya is recorded as Arabic رَايَة (Rāya), a female given name. The source gloss 'Lady, Mistress' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rab": ("رَبّ", "رب", "رب", "रब", "رب", "rab", "Arabic", "Male",
         "Arabic root ر ب ب (r-b-b); رَبّ (Rabb)", False, "high",
         "Rab is Arabic رَبّ (Rabb) 'lord, master', from the root ر ب ب (r-b-b). The source gloss 'Reader, Learner' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rabaa": ("رَبَاء", "رباء", "رباء", "रबा", "رباء", "rabaa", "Arabic", "Female",
           "Arabic رَبَاء (Rabāʾ)", False, "medium",
           "Rabaa is recorded as Arabic رَبَاء (Rabāʾ), a female given name. The source gloss 'Butterfly' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rabab": ("رَبَاب", "رباب", "رباب", "रबाब", "رباب", "rabab", "Arabic", "Female",
           "Arabic رَبَاب (Rabāb), a stringed instrument", False, "high",
           "Rabab is Arabic رَبَاب (Rabāb), a stringed instrument, used as a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "rabah": ("رَبَاح", "رباح", "رباح", "रबाह", "رباح", "rabah", "Arabic", "Male",
           "Arabic root ر ب ح (r-b-ḥ); رَبَاح (Rabāḥ)", False, "high",
           "Rabah is Arabic رَبَاح (Rabāḥ) 'profit, gain', from the root ر ب ح (r-b-ḥ). The source gloss 'Little Gazelle' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rabar": ("رَبَار", "ربار", "ربار", "रबार", "ربار", "rabar", "Kurdish", "Male",
           "Kurdish Rebar", False, "medium",
           "Rabar is a Kurdish male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rabar' instead of a script form and labelled the origin Arabic; the name is Kurdish. The source gloss 'Little Rabbit' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rabbani": ("رَبَّانِي", "ربانی", "ربانی", "रब्बानी", "رباني", "rabbani", "Arabic", "Male",
             "Arabic رَبَّانِي (Rabbanī) 'divine'", False, "high",
             "Rabbani is Arabic رَبَّانِي (Rabbanī) 'divine, of the Lord', a relational adjective from رَبّ (rabb). The source gloss 'The Lord' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rabea": ("رَبِيعَة", "ربیعہ", "ربیعه", "रबीआ", "ربیعه", "rabea", "Arabic", "Female",
           "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
           "Rabea is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). CRITICAL SOURCE ERROR: the source gave ربة (a different form); the correct form is رَبِيعَة. The source gloss 'Small, tender one' is unsupported and has been replaced with the lexical sense. Same name as rabia."),
 "rabee": ("رَبِيع", "ربیع", "ربیع", "रबी", "ربیع", "rabee", "Arabic", "Male",
           "Arabic root ر ب ع (r-b-ʿ); رَبِيع (Rabīʿ)", False, "high",
           "Rabee is Arabic رَبِيع (Rabīʿ) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'Early' is unsupported and has been replaced with the lexical sense."),
 "rabeea": ("رَبِيعَة", "ربیعہ", "ربیعه", "रबीआ", "ربیعه", "rabeea", "Arabic", "Female",
            "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
            "Rabeea is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'The one who is continuously present' is unsupported and has been replaced with the lexical sense. Same name as rabia."),
 "rabeeh": ("رَبِيع", "ربیع", "ربیع", "रबीह", "ربیع", "rabeeh", "Arabic", "Male",
            "Arabic root ر ب ع (r-b-ʿ); رَبِيع (Rabīʿ)", False, "high",
            "Rabeeh is Arabic رَبِيع (Rabīʿ) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'Patient' is unsupported and has been replaced with the lexical sense."),
 "rabi": ("رَبِيع", "ربیع", "ربیع", "रबी", "ربیع", "rabi", "Arabic", "Male",
          "Arabic root ر ب ع (r-b-ʿ); رَبِيع (Rabīʿ)", False, "high",
          "Rabi is Arabic رَبِيع (Rabīʿ) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'Spring' is consistent."),
 "rabia": ("رَبِيعَة", "ربیعہ", "ربیعه", "रबिया", "ربیعه", "rabia", "Arabic", "Female",
           "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
           "Rabia is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'Passionate lover' is unsupported and has been replaced with the lexical sense."),
 "rabiaa": ("رَبِيعَة", "ربیعہ", "ربیعه", "रबिया", "ربیعه", "rabiaa", "Arabic", "Female",
            "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
            "Rabiaa is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). CRITICAL SOURCE ERROR: the source gave رビآ (a broken form mixing Japanese katakana); the correct form is رَبِيعَة. The source gloss 'Patient or passionate lover' is unsupported and has been replaced with the lexical sense. Same name as rabia."),
 "rabiah": ("رَبِيعَة", "ربیعہ", "ربیعه", "रबिया", "ربیعه", "rabiah", "Arabic", "Female",
            "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
            "Rabiah is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'Wife of the Prophet' is a historical association rather than a lexical sense. Same name as rabia."),
 "rabih": ("رَابِح", "رابح", "رابح", "राबिह", "رابح", "rabih", "Arabic", "Male",
           "Arabic root ر ب ح (r-b-ḥ); رَابِح (Rābiḥ)", False, "high",
           "Rabih is Arabic رَابِح (Rābiḥ) 'profitable, gainful', from the root ر ب ح (r-b-ḥ). The source gloss 'Steadfast, enduring' is unsupported and has been replaced with the lexical sense."),
 "rabiha": ("رَابِحَة", "رابحہ", "رابحه", "राबिहा", "رابحه", "rabiha", "Arabic", "Female",
            "Arabic root ر ب ح (r-b-ḥ); رَابِحَة (Rābiḥa)", False, "high",
            "Rabiha is Arabic رَابِحَة (Rābiḥa) 'profitable' (feminine), from the root ر ب ح (r-b-ḥ). CRITICAL SOURCE ERROR: the source gave 'رabiها' (a broken Latin-Arabic mix); the correct form is رَابِحَة. The source gloss 'Fourth' is unsupported and has been replaced with the lexical sense."),
 "rabitah": ("رَابِطَة", "رابطہ", "رابطه", "राबिता", "رابطه", "rabitah", "Arabic", "Female",
             "Arabic root ر ب ط (r-b-ṭ); رَابِطَة (Rābiṭa)", False, "high",
             "Rabitah is Arabic رَابِطَة (Rābiṭa) 'bond, tie', from the root ر ب ط (r-b-ṭ). CRITICAL SOURCE ERROR: the source gave ربيتة (a non-standard form). The source gloss 'Graceful, Beautiful' is unsupported and has been replaced with the lexical sense."),
 "rabiya": ("رَبِيعَة", "ربیعہ", "ربیه", "रबिया", "ربیه", "rabiya", "Arabic", "Female",
            "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
            "Rabiya is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'Spring, Blossom' is broadly consistent. Same name as rabia."),
 "rabiye": ("رَبِيعَة", "ربیعہ", "ربیه", "रबिया", "ربیه", "rabiye", "Arabic", "Female",
            "Arabic root ر ب ع (r-b-ʿ); رَبِيعَة (Rabīʿa)", False, "high",
            "Rabiye is Arabic رَبِيعَة (Rabīʿa) 'spring', from the root ر ب ع (r-b-ʿ). The source gloss 'The One Who Is Kind' is unsupported and has been replaced with the lexical sense. Same name as rabia."),
 "rachid": ("رَاشِد", "راشد", "راشد", "रशीद", "راشد", "rachid", "Arabic", "Male",
            "Arabic root ر ش د (r-sh-d); رَاشِد (Rāshid)", False, "high",
            "Rachid is a Maghrebi spelling of Arabic رَاشِد (Rāshid) 'rightly guided', from the root ر ش د (r-sh-d). The source gloss 'Wise, Knowledgeable' is unsupported and has been replaced with the lexical sense. Same name as raashid."),
 "rachida": ("رَاشِدَة", "راشدہ", "راشده", "रशीदा", "راشده", "rachida", "Arabic", "Female",
             "Arabic root ر ش د (r-sh-d); رَاشِدَة (Rāshida)", False, "high",
             "Rachida is Arabic رَاشِدَة (Rāshida) 'rightly guided' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Small, Humble, Simple' is unsupported and has been replaced with the lexical sense."),
 "rad": ("رَض", "رض", "رض", "रद", "رض", "rad", "Arabic", "Male",
         "Arabic رَض (Raḍ)", False, "medium",
         "Rad is recorded as Arabic رَض (Raḍ), a male given name. The source gloss 'Light, Sun, Radiance' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "radhi": ("رَضِي", "رضی", "رضی", "रज़ी", "رضی", "radhi", "Arabic", "Male",
           "Arabic root ر ض و (r-ḍ-w); رَضِي (Raḍī)", False, "high",
           "Radhi is Arabic رَضِي (Raḍī) 'content, pleased', from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source gave the Latin string 'Radhi' instead of a script form. The source gloss 'Pleasing, content, joyful' is broadly consistent."),
 "radhia": ("رَضِيَّة", "رضیہ", "رضیه", "रज़िया", "رضیه", "radhia", "Arabic", "Female",
            "Arabic root ر ض و (r-ḍ-w); رَضِيَّة (Raḍiyya)", False, "high",
            "Radhia is Arabic رَضِيَّة (Raḍiyya) 'content, pleased' (feminine), from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source gave رضيا (a non-standard form). The source gloss 'Moon, Grace' is unsupported and has been replaced with the lexical sense. Same name as radhiya."),
 "radhiya": ("رَضِيَّة", "رضیہ", "رضیه", "रज़िया", "رضیه", "radhiya", "Arabic", "Female",
             "Arabic root ر ض و (r-ḍ-w); رَضِيَّة (Raḍiyya)", False, "high",
             "Radhiya is Arabic رَضِيَّة (Raḍiyya) 'content, pleased' (feminine), from the root ر ض و (r-ḍ-w). The source gloss 'Pleased' is consistent. Same name as radhia."),
 "radi": ("رَاضِي", "راضی", "راضی", "राज़ी", "راضي", "radi", "Arabic", "Male",
          "Arabic root ر ض و (r-ḍ-w); رَاضِي (Rāḍī)", False, "high",
          "Radi is Arabic رَاضِي (Rāḍī) 'content, pleased', from the root ر ض و (r-ḍ-w). The source gloss 'Content, Joy, Pleasing' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "radifa": ("رَادِفَة", "رادفہ", "رادفه", "रादिफ़ा", "رادفه", "radifa", "Arabic", "Female",
            "Arabic root ر د ف (r-d-f); رَادِفَة (Rādifa)", False, "medium",
            "Radifa is recorded as Arabic رَادِفَة (Rādifa), a female given name, from the root ر د ف (r-d-f). The source gloss 'Knowledgeable, Educated' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "radil": ("رَاضِل", "راضل", "راضل", "रादिल", "راضل", "radil", "Arabic", "Male",
           "Arabic رَاضِل (Rāḍil)", False, "medium",
           "Radil is recorded as Arabic رَاضِل (Rāḍil), a male given name. The source gloss 'Little one, gentle, kind, tender' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raditya": ("رَادِيتْيَا", "رادتیہ", "رادیتیا", "रादित्य", "رادیتیا", "raditya", "Indonesian", "Male",
             "Indonesian Raditya", False, "high",
             "Raditya is an Indonesian male given name. CRITICAL SOURCE ERROR: the source gave راضيذيا (a non-standard form) and labelled the origin Arabic; the name is Indonesian. The source gloss 'Light of the night' is unsupported and has been replaced with the documented identification."),
 "radiya": ("رَضِيَّة", "رضیہ", "رضیه", "रज़िया", "رضیه", "radiya", "Arabic", "Female",
            "Arabic root ر ض و (r-ḍ-w); رَضِيَّة (Raḍiyya)", False, "high",
            "Radiya is Arabic رَضِيَّة (Raḍiyya) 'content, pleased' (feminine), from the root ر ض و (r-ḍ-w). The source gloss 'Delight, Pleasure' is broadly consistent. Same name as radhia."),
 "radiyah": ("رَضِيَّة", "رضیہ", "رضیه", "रज़िया", "رضیه", "radiyah", "Arabic", "Female",
             "Arabic root ر ض و (r-ḍ-w); رَضِيَّة (Raḍiyya)", False, "high",
             "Radiyah is Arabic رَضِيَّة (Raḍiyya) 'content, pleased' (feminine), from the root ر ض و (r-ḍ-w). The source gloss 'Rejoicing, Delightful' is broadly consistent. Same name as radhia."),
 "radman": ("رَضْمَان", "رضان", "رضان", "रदमान", "رضان", "radman", "Arabic", "Male",
            "Arabic رَضْمَان (Raḍmān)", False, "medium",
            "Radman is recorded as Arabic رَضْمَان (Raḍmān), a male given name. CRITICAL SOURCE ERROR: the source gave رضان (a non-standard form). The source gloss 'Satisfied, Content' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "radwa": ("رَضْوَة", "رضوہ", "رضوه", "रदवा", "رضوه", "radwa", "Arabic", "Female",
           "Arabic رَضْوَة (Raḍwa)", False, "high",
           "Radwa is Arabic رَضْوَة (Raḍwa), a female given name (also a mountain near Medina). CRITICAL SOURCE ERROR: the source gave رضوة (a non-standard form). The source gloss 'Joy, contentment, happiness' is unsupported and has been replaced with the documented identification."),
 "raed": ("رَائِد", "رائد", "رائد", "राइद", "رائد", "raed", "Arabic", "Male",
          "Arabic root ر و د (r-w-d); رَائِد (Rāʾid)", False, "high",
          "Raed is Arabic رَائِد (Rāʾid) 'leader, pioneer', from the root ر و د (r-w-d). The source gloss 'Reader, Seer, Intelligent' is unsupported and has been replaced with the lexical sense."),
 "raeda": ("رَائِدَة", "رائدہ", "رائده", "राइदा", "رائده", "raeda", "Arabic", "Female",
           "Arabic root ر و د (r-w-d); رَائِدَة (Rāʾida)", False, "high",
           "Raeda is Arabic رَائِدَة (Rāʾida) 'leader, pioneer' (feminine), from the root ر و د (r-w-d). The source gloss 'Sailor, Traveler' is unsupported and has been replaced with the lexical sense."),
 "raeed": ("رَائِد", "رائد", "رائد", "राइद", "رائد", "raeed", "Arabic", "Male",
           "Arabic root ر و د (r-w-d); رَائِد (Rāʾid)", False, "high",
           "Raeed is a spelling variant of Arabic رَائِد (Rāʾid) 'leader, pioneer', from the root ر و د (r-w-d). The source gloss 'Leader, Master, King' is broadly consistent. Same name as raed."),
 "raeeda": ("رَائِدَة", "رائدہ", "رائده", "राइदा", "رائده", "raeeda", "Arabic", "Female",
            "Arabic root ر و د (r-w-d); رَائِدَة (Rāʾida)", False, "high",
            "Raeeda is Arabic رَائِدَة (Rāʾida) 'leader, pioneer' (feminine), from the root ر و د (r-w-d). CRITICAL SOURCE ERROR: the source gave رعيدة (a non-standard form). The source gloss 'Flowing one' is unsupported and has been replaced with the lexical sense. Same name as raeda."),
 "raeef": ("رَءُوف", "رئيف", "رئوف", "रईफ़", "رئيف", "raeef", "Arabic", "Male",
           "Arabic root ر أ ف (r-ʾ-f); رَءُوف (Raʾūf)", False, "high",
           "Raeef is Arabic رَءُوف (Raʾūf) 'compassionate, kind', from the root ر أ ف (r-ʾ-f). CRITICAL SOURCE ERROR: the source gave رعيف (a non-standard form). The source gloss 'Strong, Firm' is unsupported and has been replaced with the lexical sense. Same name as ra-uf."),
 "raees": ("رَئِيس", "رئیس", "رئیس", "रईस", "رئیس", "raees", "Arabic", "Male",
           "Arabic root ر أ س (r-ʾ-s); رَئِيس (Raʾīs)", False, "high",
           "Raees is Arabic رَئِيس (Raʾīs) 'leader, chief', from the root ر أ س (r-ʾ-s). The source gloss 'Leader, Guide' is consistent."),
 "raeesa": ("رَئِيسَة", "رئیسہ", "رئیسه", "रईसा", "رئیسه", "raeesa", "Arabic", "Female",
            "Arabic root ر أ س (r-ʾ-s); رَئِيسَة (Raʾīsa)", False, "high",
            "Raeesa is Arabic رَئِيسَة (Raʾīsa) 'leader, chief' (feminine), from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as raeesah."),
 "raeesah": ("رَئِيسَة", "رئیسہ", "رئیسه", "रईसा", "رئیسه", "raeesah", "Arabic", "Female",
             "Arabic root ر أ س (r-ʾ-s); رَئِيسَة (Raʾīsa)", False, "high",
             "Raeesah is Arabic رَئِيسَة (Raʾīsa) 'leader, chief' (feminine), from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source gave رئاسة (a different form). The source gloss 'Lady, Mistress' is unsupported and has been replaced with the lexical sense. Same name as raeesa."),
 "rafaa": ("رَفَاع", "رفاع", "رفاع", "रफ़ा", "رفاع", "rafaa", "Arabic", "Male",
           "Arabic رَفَاع (Rafāʿ)", False, "medium",
           "Rafaa is recorded as Arabic رَفَاع (Rafāʿ), a male given name. The source gloss 'Healer, Compassionate' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "rafaat": ("رِفْعَة", "رفعت", "رفعت", "रफ़ात", "رفعت", "rafaat", "Arabic", "Male",
            "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
            "Rafaat is Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رفاع (a different form); the correct form is رِفْعَة. The source gloss 'Healer, Giver of Good Fortune' is unsupported and has been replaced with the lexical sense."),
}
