# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 5 (aizat..alesha)."""

GLOSSES = {
    "helper_support": {"en": "Support, helper", "ur": "مدد، سہارا، مددگار", "fa": "کمک، پشتیبان", "hi": "मदद, सहायक", "ps": "مرسته، ملاتړ", "ar": "عون، نصير"},
    "noble_blessed": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "glorifier": {"en": "One who glorifies God", "ur": "خدا کی تسبیح کرنے والی", "fa": "تسبیح‌گوی خدا", "hi": "ईश्वर की स्तुति करने वाली", "ps": "د خدای تسبیح ویونکې", "ar": "مسبّحة، حامدة"},
    "exalted_noble": {"en": "Exalted, noble, mighty", "ur": "بلند، نجیب، غالب", "fa": "والا، نجیب، عزیز", "hi": "उच्च, कुलीन, प्रतापी", "ps": "لوړ، نجیب، ځواکمن", "ar": "عزيز، مرفوع، نبيل"},
    "wonder": {"en": "Wonder, amazement, marvel", "ur": "حیرت، تعجب، عجوبہ", "fa": "شگفتی، حیرت", "hi": "आश्चर्य, विस्मय", "ps": "حیرت، تعجب", "ar": "عجب، دهشة"},
    "term": {"en": "Term, appointed time, deadline", "ur": "مدت، مقررہ وقت", "fa": "مهلت، سرآمد", "hi": "अवधि, नियत समय", "ps": "موده، ټاکلی وخت", "ar": "أجل، مدة"},
    "non_arabs": {"en": "Non-Arabs, Persians (collective)", "ur": "عجم، غیر عرب", "fa": "عجم، غیرعرب", "hi": "अजम, ग़ैर-अरब", "ps": "عجم، غیر عرب", "ar": "عجم، أعاجم"},
    "quiet": {"en": "Quiet, calm, still", "ur": "خاموش، پرسکون", "fa": "آرام، ساکت", "hi": "शांत, चुप", "ps": "غلي، آرام", "ar": "هادئ، ساكن"},
    "devout": {"en": "Devout, worshipper", "ur": "عابد، متقی", "fa": "پرهیزگار، پرستشگر", "hi": "भक्त, उपासक", "hi_alt": None, "ps": "عبادت کوونکی، متقي", "ar": "عابد، متعبّد"},
    "strange": {"en": "Strange, wonderful, marvellous", "ur": "عجیب، حیران کن، شاندار", "fa": "شگفت، شگفت‌انگیز", "hi": "अजीब, अद्भुत", "ps": "عجیب، حیرانونکی", "ar": "عجيب، بديع"},
    "swift": {"en": "Swift, quick, hasty", "ur": "تیز، جلدی", "fa": "تند، شتابان", "hi": "तेज़, शीघ्र", "ps": "ګړندی، تیز", "ar": "عجول، سريع"},
    "tranquility": {"en": "Tranquility, calmness", "ur": "سکون، اطمینان", "fa": "آرامش، سکون", "hi": "शांति, सुकून", "ps": "سکون، آرام", "ar": "سكينة، هدوء"},
    "gentle_soft": {"en": "Gentle and soft", "ur": "نرم اور ملائم", "fa": "نرم و لطیف", "hi": "कोमल और मृदु", "ps": "نرمه او ملایمه", "ar": "لطيف، ناعم"},
    "mountain": {"en": "Mountain, hill", "ur": "پہاڑ، ٹیلہ", "fa": "کوه، تپه", "hi": "पर्वत, पहाड़ी", "ps": "غر، غونډۍ", "ar": "جبل، تل"},
    "most_beautiful": {"en": "Most beautiful, most excellent", "ur": "سب سے خوبصورت، بہترین", "fa": "زیباترین، بهترین", "hi": "सबसे सुंदर, सर्वोत्तम", "ps": "تر ټولو ښکلی، غوره", "ar": "أجمل، أحسن"},
    "compassionate": {"en": "Gentle, kind, compassionate", "ur": "نرم، مہربان، رحمدل", "fa": "مهربان، دلسوز", "hi": "कोमल, दयालु, करुणामय", "ps": "مهربان، زړه سواند", "ar": "رحيم، عطوف"},
    "foreigner": {"en": "Foreigner, non-Arab; Persian", "ur": "عجمی، غیر عرب", "fa": "عجمی، غیرعرب", "hi": "अजमी, ग़ैर-अरब", "ps": "عجمي، غیر عرب", "ar": "عجمي، أعجمي"},
    "dates": {"en": "Dates (fruit)", "ur": "کھجور", "fa": "خرما", "hi": "खजूर", "ps": "کجوره", "ar": "تمر، رطب"},
    "graceful_honorable": {"en": "Graceful, honourable, generous", "ur": "خوبصورت، معزز، سخی", "fa": "زیبا، محترم، بخشنده", "hi": "सुंदर, सम्मानित, उदार", "ps": "ښکلی، دروند، سخي", "ar": "أجود، كريم، نبيل"},
    "sky": {"en": "Sky, space, heaven", "ur": "آسمان، فضا", "fa": "آسمان، فضا", "hi": "आकाश, अंतरिक्ष", "ps": "آسمان، فضا", "ar": "سماء، فضاء"},
    "aether": {"en": "Aether, space, sky (Sanskrit ākāśa)", "ur": "آکاش، فضا، ایتھر", "fa": "آکاشا، فضا، اتر", "hi": "आकाश, ईथर, व्योम", "ps": "آکاش، فضا", "ar": "أكاشا، فضاء"},
    "greatest": {"en": "Greatest, most powerful", "ur": "سب سے بڑا، سب سے زبردست", "fa": "بزرگ‌ترین، تواناترین", "hi": "सबसे बड़ा, सर्वशक्तिमान", "ps": "تر ټولو لوی، ځواکمن", "ar": "أكبر، أعظم"},
    "great": {"en": "Great, big, exalted", "ur": "بڑا، عظیم، بلند", "fa": "بزرگ، عظیم", "hi": "बड़ा, महान", "ps": "لوی، عظیم", "ar": "كبير، عظيم"},
    "wise": {"en": "Wise, intelligent, discerning", "ur": "عقیل، دانا، ذہین", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرک، پوه", "ar": "عقيل، حكيم"},
    "intelligent_f": {"en": "Intelligent, wise (feminine)", "ur": "عاقلہ، ذہین، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرکه، پوهه", "ar": "عاقلة، حكيمة"},
    "unique": {"en": "Unique, solitary, independent", "ur": "منفرد، یکتا، خودمختار", "fa": "یگانه، یکتا، مستقل", "hi": "अद्वितीय, अकेला, स्वतंत्र", "ps": "ځانګړی، یوازینی", "ar": "فريد، وحيد"},
    "morals": {"en": "Moral conduct, virtues, character", "ur": "اخلاق، اخلاقیات، کردار", "fa": "اخلاق، منش، خوی", "hi": "नैतिकता, चरित्र, सदाचार", "ps": "اخلاق، ښه خوی", "ar": "أخلاق، مكارم"},
    "sincere": {"en": "Pure, sincere, devoted", "ur": "خالص، مخلص", "fa": "خالص، مخلص", "hi": "शुद्ध, निष्ठावान", "ps": "خالص، مخلص", "ar": "مخلص، خالص"},
    "follower_muhammad": {"en": "Follower of Muhammad", "ur": "محمد کا پیروکار", "fa": "پیرو محمد", "hi": "मुहम्मद का अनुयायी", "ps": "د محمد پیرو", "ar": "أحمد، تابع محمد"},
    "deferred": {"en": "Late, deferred, postponed", "ur": "دیر سے، مؤخر", "fa": "دیر، به‌تعویق‌افتاده", "hi": "देर से, स्थगित", "ps": "ناوخته، ځنډول شوی", "ar": "آخر، مؤخّر"},
    "star": {"en": "Star, bright celestial body", "ur": "ستارہ، اختر", "fa": "ستاره، اختر", "hi": "तारा, नक्षत्र", "ps": "ستوری، اختر", "ar": "نجم، كوكب"},
    "nearest": {"en": "The nearest one", "ur": "قریب ترین", "fa": "نزدیک‌ترین", "hi": "निकटतम", "ps": "تر ټولو نږدې", "ar": "أقرب"},
    "pure_clear": {"en": "Pure, clear, bright", "ur": "پاک، صاف، روشن", "fa": "پاک، روشن", "hi": "पवित्र, स्वच्छ, उज्ज्वल", "ps": "پاک، روښانه", "ar": "أخيار، نقي"},
    "bright": {"en": "Bright, shining", "ur": "روشن، چمکدار", "fa": "روشن، درخشان", "hi": "उज्ज्वल, चमकदार", "ps": "روښانه، ځلانده", "ar": "مضيء، لامع"},
    "truthful": {"en": "Truthful, sincere", "ur": "سچا، مخلص", "fa": "راستگو، مخلص", "hi": "सच्चा, निष्ठावान", "ps": "رښتونی، مخلص", "ar": "صادق، مخلص"},
    "successor": {"en": "Successor, heir", "ur": "جانشین، وارث", "fa": "جانشین، وارث", "hi": "उत्तराधिकारी, वारिस", "ps": "ځای ناستی، وارث", "ar": "عقيب، وارث"},
    "devoted": {"en": "Devoted, focused worshipper", "ur": "مخلص، عبادت میں مصروف", "fa": "فداکار، عبادت‌پیشه", "hi": "समर्पित, तपस्वी", "ps": "مخلص، عبادت کوونکی", "ar": "عاكف، مخلص"},
    "strong_determined": {"en": "Strong and determined woman", "ur": "مضبوط اور پرعزم عورت", "fa": "زنی نیرومند و استوار", "hi": "सशक्त और दृढ़ नारी", "ps": "پیاوړې او ټینګه ښځه", "ar": "قوية، عازمة"},
    "eternal_garden": {"en": "Eternal, garden", "ur": "ابدی، باغ", "fa": "جاودان، باغ", "hi": "शाश्वत, उद्यान", "ps": "ابدي، باغ", "ar": "خالد، حديقة"},
    "understanding": {"en": "Intelligent, wise, understanding", "ur": "ذہین، دانا، سمجھدار", "fa": "خردمند، دانا، فهیم", "hi": "बुद्धिमान, विवेकी, समझदार", "ps": "ځیرک، پوه، پوهاوی لرونکی", "ar": "عقيلة، حكيمة"},
    "ruler_master": {"en": "Ruler, master", "ur": "حاکم، مالک", "fa": "فرمانروا، سرور", "hi": "शासक, स्वामी", "ps": "واکمن، مالک", "ar": "حكيم، مالك"},
    "trustworthy": {"en": "Trustworthy, sincere", "ur": "امانتدار، مخلص", "fa": "امین، مخلص", "hi": "विश्वसनीय, निष्ठावान", "ps": "امانتدار، مخلص", "ar": "أمين، مخلص"},
    "moonlit": {"en": "Moon-lit night", "ur": "چاندنی رات", "fa": "شب مهتابی", "hi": "चाँदनी रात", "ps": "سپوږمۍ شپه", "ar": "ليلة مقمرة"},
    "calm": {"en": "Calm, tranquil", "ur": "پرسکون، خاموش", "fa": "آرام، ساکت", "hi": "शांत, निश्चल", "ps": "آرام، غلي", "ar": "حليم، هادئ"},
    "perfect": {"en": "Perfect, complete, most complete", "ur": "کامل، مکمل", "fa": "کامل، تمام", "hi": "पूर्ण, संपूर्ण", "ps": "بشپړ، کامل", "ar": "أكمل، تام"},
    "generous_noble": {"en": "Generous, noble, most generous", "ur": "سخی، نجیب، کریم", "fa": "بخشنده، نجیب، کریم", "hi": "उदार, कुलीन, करीम", "ps": "سخي، نجیب، کریم", "ar": "أكرم، كريم"},
    "sanctified": {"en": "The sanctified one", "ur": "مقدس، پاک", "fa": "مقدس، پاک", "hi": "पवित्र, पूजित", "ps": "مقدس، پاک", "ar": "مقدّس، مبارك"},
    "helping_hand": {"en": "Helping hand, support", "ur": "مدد کا ہاتھ، سہارا", "fa": "دست یاری، پشتیبانی", "hi": "मदद का हाथ, सहारा", "ps": "د مرستې لاس، ملاتړ", "ar": "يد العون، نصرة"},
    "elixir": {"en": "Elixir, philosopher's stone", "ur": "اکسیر، کیمیا", "fa": "اکسیر، کیمیا", "hi": "अक्सीर, रसायन", "ps": "اکسیر، کیمیا", "ar": "إكسير، كيمياء"},
    "near_one": {"en": "The one who is near", "ur": "قریب، نزدیک", "fa": "نزدیک، قریب", "hi": "निकट, क़रीब", "ps": "نږدې، قریب", "ar": "قريب، دانٍ"},
    "merciful": {"en": "Merciful, compassionate", "ur": "رحم والا، مہربان", "fa": "مهربان، بخشنده", "hi": "दयालु, करुणामय", "ps": "مهربان، رحمن", "ar": "أكثم، رحيم"},
    "exalted_sublime": {"en": "Exalted, sublime, high", "ur": "بلند، عالی، رفیع", "fa": "والا، بلند، عالی", "hi": "उच्च, महान, श्रेष्ठ", "ps": "لوړ، عالي", "ar": "عليّ، رفيع"},
    "nobility_faith": {"en": "Nobility of the faith", "ur": "دین کی عزت", "fa": "شرف دین", "hi": "धर्म की महानता", "ps": "د دین وياړ", "ar": "علاء الدين"},
    "world": {"en": "World, universe; flag", "ur": "عالم، دنیا، جھنڈا", "fa": "عالم، جهان، پرچم", "hi": "संसार, विश्व, ध्वज", "ps": "نړۍ، عالم، بیرغ", "ar": "عالم، راية"},
    "hope": {"en": "Hope, expectation", "ur": "امید، توقع", "fa": "امید، انتظار", "hi": "आशा, अपेक्षा", "ps": "هيله، تمه", "ar": "أمل، رجاء"},
    "signpost": {"en": "Guide, signpost, sign", "ur": "نشانی، راہنما", "fa": "نشان، راهنما", "hi": "चिह्न, मार्गदर्शक", "ps": "نښه، لارښود", "ar": "علامة، دليل"},
    "world_conqueror": {"en": "World-conqueror", "ur": "عالمگیر، جہاں گیر", "fa": "جهانگیر، عالمگیر", "hi": "जगद्विजयी, आलमगीर", "ps": "نړۍ نیوونکی", "ar": "عالمكير، جهانكير"},
    "lion": {"en": "Lion", "ur": "شیر", "fa": "شیر", "hi": "शेर, सिंह", "ps": "زمری، شیر", "ar": "أسد، ليث"},
    "light_religion": {"en": "Light of the religion", "ur": "دین کا نور", "fa": "نور دین", "hi": "धर्म का प्रकाश", "ps": "د دین رڼا", "ar": "علاء الدين، نور الدين"},
    "exalted_high": {"en": "Exalted, high, noble", "ur": "بلند، عالی، نجیب", "fa": "والا، بلند، نجیب", "hi": "उच्च, महान, कुलीन", "ps": "لوړ، عالي، نجیب", "ar": "عليّ، عالٍ"},
    "heavenly": {"en": "Heavenly, exalted", "ur": "آسمانی، بلند", "fa": "آسمانی، والا", "hi": "स्वर्गीय, उच्च", "ps": "آسماني، لوړ", "ar": "علوية، سماوية"},
    "falcon": {"en": "Falcon", "ur": "باز، شاہین", "fa": "باز، شاهین", "hi": "बाज़, शाहीन", "ps": "باز، شاهین", "ar": "باز، صقر"},
    "gentle_radiant": {"en": "Gentle, radiant", "ur": "نرم، روشن", "fa": "نرم، فروزان", "hi": "कोमल, उज्ज्वल", "ps": "نرمه، روښانه", "ar": "لطيفة، مشرقة"},
    "mountain_range": {"en": "Mountain range (Alborz)", "ur": "البرز، پہاڑی سلسلہ", "fa": "البرز، رشته‌کوه", "hi": "अल्बोर्ज़, पर्वत श्रृंखला", "ps": "البرز، د غرونو لړۍ", "ar": "البرز، سلسلة جبال"},
    "noble_exalted_f": {"en": "Noble, exalted (feminine)", "ur": "نجیب، بلند", "fa": "نجیب، والا", "hi": "कुलीन, उच्च", "ps": "نجیبه، لوړه", "ar": "نبيلة، مرفوعة"},
    "letter_alif": {"en": "The letter alif", "ur": "حرف الف", "fa": "حرف الف", "hi": "अक्षर अलिफ़", "ps": "د الف توری", "ar": "حرف الألف"},
    "knowledgeable": {"en": "Knowledgeable, wise, learned", "ur": "عالم، دانا، فاضل", "fa": "دانا، دانشمند", "hi": "ज्ञानी, विद्वान", "ps": "پوه، عالم", "ar": "عليم، عالم"},
    "scholar_f": {"en": "Scholar, learned woman", "ur": "عالمہ، فاضلہ", "fa": "دانشمند، عالمه", "hi": "विदुषी, पंडिता", "ps": "عالمه، پوهه", "ar": "عليمة، عالمة"},
    "soft_hearted": {"en": "Soft-hearted, kind and gentle", "ur": "نرم دل، مہربان", "fa": "نرم‌دل، مهربان", "hi": "कोमल हृदय, दयालु", "ps": "نرم زړه، مهربانه", "ar": "لطيفة، رحيمة"},
    "helpful": {"en": "Helpful, assisting", "ur": "مددگار، معاون", "fa": "یاری‌گر، یاور", "hi": "सहायक, सहयोगी", "ps": "مرسته کوونکې، ملاتړې", "ar": "معينة، ناصرة"},
    "submission": {"en": "Submission (to God)", "ur": "اطاعت، تسلیم", "fa": "تسلیم، اطاعت", "hi": "समर्पण, आज्ञाकारिता", "ps": "تسلیم، اطاعت", "ar": "تسليم، إسلام"},
    "night_born": {"en": "Night-born", "ur": "رات کو پیدا ہونے والی", "fa": "شب‌زاد", "hi": "रात में जन्मी", "ps": "په شپه زېږېدلې", "ar": "مولودة الليل"},
    "joyful": {"en": "Joyful, happy, cheerful", "ur": "خوش، مسرور، شاداں", "fa": "شاد، خوشحال", "hi": "प्रसन्न, खुश, आनंदित", "ps": "خوشحاله، مړوند", "ar": "مبتهجة، فرِحة"},
    "buttercup": {"en": "Buttercup (a flower)", "ur": "آلالہ، ایک پھول", "fa": "آلاله، گلی سرخ", "hi": "अलाले, एक फूल", "ps": "آلاله، یو ګل", "ar": "شقائق النعمان"},
    "exalted_one": {"en": "Exalted one", "ur": "بلند مرتبہ", "fa": "والامقام", "hi": "उच्च, महान", "ps": "لوړ مقام", "ar": "مرفوع، عليّ"},
    "noble_exalted_aleeza": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "exalted_noble_aleezay": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "exalted_noble_aleha": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "exalted_noble_alee": {"en": "Exalted, sublime", "ur": "بلند، عالی", "fa": "والا، بلند", "hi": "उच्च, महान", "ps": "لوړ، عالي", "ar": "عليّ، رفيع"},
    "exalted_noble_aleem": {"en": "Knowledgeable, wise", "ur": "عالم، دانا", "fa": "دانا، دانشمند", "hi": "ज्ञानी, विद्वान", "ps": "پوه، عالم", "ar": "عليم، عالم"},
    "exalted_noble_aleema": {"en": "Scholar, learned woman", "ur": "عالمہ، فاضلہ", "fa": "دانشمند، عالمه", "hi": "विदुषी, पंडिता", "ps": "عالمه، پوهه", "ar": "عليمة، عالمة"},
    "gentle_kind_aleen": {"en": "Gentle, kind", "ur": "نرم، مہربان", "fa": "نرم، مهربان", "hi": "कोमल, दयालु", "ps": "نرمه، مهربانه", "ar": "لطيفة، كريمة"},
    "soft_hearted_aleena": {"en": "Soft-hearted, kind and gentle", "ur": "نرم دل، مہربان", "fa": "نرم‌دل، مهربان", "hi": "कोमल हृदय, दयालु", "ps": "نرم زړه، مهربانه", "ar": "لطيفة، رحيمة"},
    "exalted_noble_aleesa": {"en": "Exalted, sublime, noble", "ur": "بلند، عالی، نجیب", "fa": "والا، بلند، نجیب", "hi": "उच्च, महान, कुलीन", "ps": "لوړ، عالي، نجیب", "ar": "عليّ، رفيع، نبيل"},
    "sublime_high": {"en": "Sublime, exalted, high", "ur": "بلند، عالی، رفیع", "fa": "والا، بلند، عالی", "hi": "उच्च, महान, श्रेष्ठ", "ps": "لوړ، عالي", "ar": "عليا، رفيعة"},
    "exalted_lofty": {"en": "Exalted, sublime, lofty", "ur": "بلند، عالی، رفیع", "fa": "والا، بلند، عالی", "hi": "उच्च, महान, श्रेष्ठ", "ps": "لوړ، عالي", "ar": "عالية، رفيعة"},
    "helpful_assisting": {"en": "Helpful, assisting", "ur": "مددگار، معاون", "fa": "یاری‌گر، یاور", "hi": "सहायक, सहयोगी", "ps": "مرسته کوونکې، ملاتړې", "ar": "معينة، ناصرة"},
    "submission_allah": {"en": "Submission to Allah", "ur": "اللہ کے سامنے تسلیم", "fa": "تسلیم به خدا", "hi": "अल्लाह के प्रति समर्पण", "ps": "د الله تسلیم", "ar": "تسليم لله"},
    "exalted_noble_aleezah": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "exalted_noble_aleezay2": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "exalted_noble_aleha2": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "night_born_alesha": {"en": "Night-born", "ur": "رات کو پیدا ہونے والی", "fa": "شب‌زاد", "hi": "रात में जन्मी", "ps": "په شپه زېږېدلې", "ar": "مولودة الليل"},
    "noble_blessed_aizaz": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "glorifier_aizza": {"en": "Glorifier of God", "ur": "خدا کی تسبیح کرنے والی", "fa": "تسبیح‌گوی خدا", "hi": "ईश्वर की स्तुति करने वाली", "ps": "د خدای تسبیح ویونکې", "ar": "مسبّحة، حامدة"},
    "exalted_noble_aizzah": {"en": "Exalted, noble, mighty", "ur": "بلند، نجیب، غالب", "fa": "والا، نجیب، عزیز", "hi": "उच्च, कुलीन, प्रतापी", "ps": "لوړ، نجیب، ځواکمن", "ar": "عزيز، مرفوع، نبيل"},
    "wonder_ajab": {"en": "Wonder, amazement", "ur": "حیرت، تعجب", "fa": "شگفتی، حیرت", "hi": "आश्चर्य, विस्मय", "ps": "حیرت، تعجب", "ar": "عجب، دهشة"},
    "term_ajal": {"en": "Term, appointed time", "ur": "مدت، مقررہ وقت", "fa": "مهلت، سرآمد", "hi": "अवधि, नियत समय", "ps": "موده، ټاکلی وخت", "ar": "أجل، مدة"},
    "non_arabs_ajam": {"en": "Non-Arabs, Persians", "ur": "عجم، غیر عرب", "fa": "عجم، غیرعرب", "hi": "अजम, ग़ैर-अरब", "ps": "عجم، غیر عرب", "ar": "عجم، أعاجم"},
    "quiet_ajaz": {"en": "Quiet, calm", "ur": "خاموش، پرسکون", "fa": "آرام، ساکت", "hi": "शांत, चुप", "ps": "غلي، آرام", "ar": "هادئ، ساكن"},
    "devout_ajda": {"en": "Devout, worshipper", "ur": "عابد، متقی", "fa": "پرهیزگار، پرستشگر", "hi": "भक्त, उपासक", "ps": "عبادت کوونکی، متقي", "ar": "عابد، متعبّد"},
    "strange_ajeeb": {"en": "Strange, wonderful, marvellous", "ur": "عجیب، حیران کن", "fa": "شگفت، شگفت‌انگیز", "hi": "अजीब, अद्भुत", "ps": "عجیب، حیرانونکی", "ar": "عجيب، بديع"},
    "swift_ajeel": {"en": "Swift, quick", "ur": "تیز، جلدی", "fa": "تند، شتابان", "hi": "तेज़, शीघ्र", "ps": "ګړندی، تیز", "ar": "عجول، سريع"},
    "tranquility_ajia": {"en": "Tranquility, calmness", "ur": "سکون، اطمینان", "fa": "آرامش، سکون", "hi": "शांति, सुकून", "ps": "سکون، آرام", "ar": "سكينة، هدوء"},
    "wonderful_ajib": {"en": "Wonderful, amazing", "ur": "حیران کن، شاندار", "fa": "شگفت‌انگیز، حیرت‌آور", "hi": "अद्भुत, आश्चर्यजनक", "ps": "حیرانونکی، زړه ښکلی", "ar": "عجيب، بديع"},
    "gentle_soft_ajla": {"en": "Gentle and soft", "ur": "نرم اور ملائم", "fa": "نرم و لطیف", "hi": "कोमल और मृदु", "ps": "نرمه او ملایمه", "ar": "لطيف، ناعم"},
    "mountain_ajlan": {"en": "Mountain or hill", "ur": "پہاڑ یا ٹیلہ", "fa": "کوه یا تپه", "hi": "पर्वत या पहाड़ी", "ps": "غر یا غونډۍ", "ar": "جبل، تل"},
    "most_beautiful_ajmal": {"en": "Most beautiful, most excellent", "ur": "سب سے خوبصورت، بہترین", "fa": "زیباترین، بهترین", "hi": "सबसे सुंदर, सर्वोत्तम", "ps": "تر ټولو ښکلی، غوره", "ar": "أجمل، أحسن"},
    "compassionate_ajmar": {"en": "Gentle, kind, compassionate", "ur": "نرم، مہربان، رحمدل", "fa": "مهربان، دلسوز", "hi": "कोमल, दयालु, करुणामय", "ps": "مهربان، زړه سواند", "ar": "رحيم، عطوف"},
    "foreigner_ajmi": {"en": "Foreigner, non-Arab; Persian", "ur": "عجمی، غیر عرب", "fa": "عجمی، غیرعرب", "hi": "अजमी, ग़ैर-अरब", "ps": "عجمي، غیر عرب", "ar": "عجمي، أعجمي"},
    "dates_ajva": {"en": "Dates (fruit)", "ur": "کھجور", "fa": "خرما", "hi": "खजूर", "ps": "کجوره", "ar": "تمر، رطب"},
    "graceful_honorable_ajwad": {"en": "Graceful, honourable, generous", "ur": "خوبصورت، معزز، سخی", "fa": "زیبا، محترم، بخشنده", "hi": "सुंदर, सम्मानित, उदार", "ps": "ښکلی، دروند، سخي", "ar": "أجود، كريم، نبيل"},
    "sky_akaash": {"en": "Sky, space, heaven", "ur": "آسمان، فضا", "fa": "آسمان، فضا", "hi": "आकाश, अंतरिक्ष", "ps": "آسمان، فضا", "ar": "سماء، فضاء"},
    "aether_akasha": {"en": "Aether, space, sky (Sanskrit ākāśa)", "ur": "آکاش، فضا", "fa": "آکاشا، فضا", "hi": "आकाश, ईथर, व्योम", "ps": "آکاش، فضا", "ar": "أكاشا، فضاء"},
    "greatest_akbar": {"en": "Greatest, most powerful", "ur": "سب سے بڑا، سب سے زبردست", "fa": "بزرگ‌ترین، تواناترین", "hi": "सबसे बड़ा, सर्वशक्तिमान", "ps": "تر ټولو لوی، ځواکمن", "ar": "أكبر، أعظم"},
    "great_akbari": {"en": "Great, big", "ur": "بڑا، عظیم", "fa": "بزرگ، عظیم", "hi": "बड़ा, महान", "ps": "لوی، عظیم", "ar": "كبرى، عظيمة"},
    "great_akber": {"en": "Great, exalted", "ur": "بڑا، بلند", "fa": "بزرگ، والا", "hi": "बड़ा, उच्च", "ps": "لوی، لوړ", "ar": "كبير، عظيم"},
    "wise_akeel": {"en": "Wise, intelligent", "ur": "عقیل، دانا، ذہین", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرک، پوه", "ar": "عقيل، حكيم"},
    "intelligent_akeelah": {"en": "Intelligent, wise (feminine)", "ur": "عاقلہ، ذہین", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرکه، پوهه", "ar": "عاقلة، حكيمة"},
    "wise_akeem": {"en": "Wise, intelligent", "ur": "حکیم، دانا", "fa": "حکیم، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "حکیم، پوه", "ar": "حكيم، عليم"},
    "unique_akela": {"en": "Unique, solitary, independent", "ur": "منفرد، یکتا", "fa": "یگانه، یکتا", "hi": "अद्वितीय, अकेला", "ps": "ځانګړی، یوازینی", "ar": "فريد، وحيد"},
    "helper_akhas": {"en": "Helper, supporter", "ur": "مددگار، معاون", "fa": "یاری‌گر، پشتیبان", "hi": "सहायक, समर्थक", "ps": "مرسته کوونکی، ملاتړی", "ar": "معين، ناصر"},
    "helper_akhdan": {"en": "Helper, supporter", "ur": "مددگار، معاون", "fa": "یاری‌گر، پشتیبان", "hi": "सहायक, समर्थक", "ps": "مرسته کوونکی، ملاتړی", "ar": "معين، ناصر"},
    "morals_akhlak": {"en": "Moral conduct, virtues", "ur": "اخلاق، اخلاقیات", "fa": "اخلاق، منش", "hi": "नैतिकता, चरित्र", "ps": "اخلاق، ښه خوی", "ar": "أخلاق، مكارم"},
    "morals_akhlaq": {"en": "Good morals", "ur": "اخلاق، اچھے اخلاق", "fa": "اخلاق نیکو", "hi": "सदाचार, अच्छे नैतिक", "ps": "ښه اخلاق", "ar": "أخلاق، مكارم"},
    "sincere_akhlas": {"en": "Pure, sincere", "ur": "خالص، مخلص", "fa": "خالص، مخلص", "hi": "शुद्ध, निष्ठावान", "ps": "خالص، مخلص", "ar": "مخلص، خالص"},
    "follower_muhammad_akhmad": {"en": "Follower of Muhammad", "ur": "محمد کا پیروکار", "fa": "پیرو محمد", "hi": "मुहम्मद का अनुयायी", "ps": "د محمد پیرو", "ar": "أحمد، تابع محمد"},
    "deferred_akhram": {"en": "Late, deferred", "ur": "دیر سے، مؤخر", "fa": "دیر، به‌تعویق‌افتاده", "hi": "देर से, स्थगित", "ps": "ناوخته، ځنډول شوی", "ar": "آخر، مؤخّر"},
    "star_akhtar": {"en": "Star, bright celestial body", "ur": "ستارہ، اختر", "fa": "ستاره، اختر", "hi": "तारा, नक्षत्र", "ps": "ستوری، اختر", "ar": "نجم، كوكب"},
    "nearest_akhter": {"en": "The nearest one", "ur": "قریب ترین", "fa": "نزدیک‌ترین", "hi": "निकटतम", "ps": "تر ټولو نږدې", "ar": "أقرب"},
    "pure_clear_akhyar": {"en": "Pure, clear, bright", "ur": "پاک، صاف، روشن", "fa": "پاک، روشن", "hi": "पवित्र, स्वच्छ", "ps": "پاک، روښانه", "ar": "أخيار، نقي"},
    "bright_aki": {"en": "Bright, shining", "ur": "روشن، چمکدار", "fa": "روشن، درخشان", "hi": "उज्ज्वल, चमकदार", "ps": "روښانه، ځلانده", "ar": "مضيء، لامع"},
    "truthful_akia": {"en": "Truthful", "ur": "سچی، مخلصہ", "fa": "راستگو، مخلص", "hi": "सच्ची, निष्ठावान", "ps": "رښتونې، مخلصه", "ar": "صادقة، مخلصة"},
    "successor_akib": {"en": "Successor, heir", "ur": "جانشین، وارث", "fa": "جانشین، وارث", "hi": "उत्तराधिकारी, वारिस", "ps": "ځای ناستی، وارث", "ar": "عقيب، وارث"},
    "devoted_akif": {"en": "Devoted, focused worshipper", "ur": "مخلص، عبادت میں مصروف", "fa": "فداکار، عبادت‌پیشه", "hi": "समर्पित, तपस्वी", "ps": "مخلص، عبادت کوونکی", "ar": "عاكف، مخلص"},
    "strong_determined_akifa": {"en": "Strong and determined woman", "ur": "مضبوط اور پرعزم عورت", "fa": "زنی نیرومند و استوار", "hi": "सशक्त और दृढ़ नारी", "ps": "پیاوړې او ټینګه ښځه", "ar": "قوية، عازمة"},
    "eternal_garden_akifah": {"en": "Eternal, garden", "ur": "ابدی، باغ", "fa": "جاودان، باغ", "hi": "शाश्वत, उद्यान", "ps": "ابدي، باغ", "ar": "خالد، حديقة"},
    "wise_akil": {"en": "Intelligent, wise", "ur": "عقیل، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرک، پوه", "ar": "عقيل، حكيم"},
    "understanding_akila": {"en": "Intelligent, wise, understanding", "ur": "ذہین، دانا، سمجھدار", "fa": "خردمند، دانا، فهیم", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرکه، پوهه", "ar": "عقيلة، حكيمة"},
    "wise_akilah": {"en": "Intelligent, wise", "ur": "عاقلہ، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرکه، پوهه", "ar": "عقيلة، حكيمة"},
    "wise_akili": {"en": "Wise, intelligent", "ur": "عقیل، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, विवेकी", "ps": "ځیرک، پوه", "ar": "عقيل، حكيم"},
    "ruler_master_akim": {"en": "Ruler, master", "ur": "حاکم، مالک", "fa": "فرمانروا، سرور", "hi": "शासक, स्वामी", "ps": "واکمن، مالک", "ar": "حكيم، مالك"},
    "trustworthy_akin": {"en": "Trustworthy, sincere", "ur": "امانتدار، مخلص", "fa": "امین، مخلص", "hi": "विश्वसनीय, निष्ठावान", "ps": "امانتدار، مخلص", "ar": "أمين، مخلص"},
    "moonlit_aklima": {"en": "Moon-lit night", "ur": "چاندنی رات", "fa": "شب مهتابی", "hi": "चाँदनी रात", "ps": "سپوږمۍ شپه", "ar": "ليلة مقمرة"},
    "calm_aklimah": {"en": "Calm, tranquil", "ur": "پرسکون، خاموش", "fa": "آرام، ساکت", "hi": "शांत, निश्चल", "ps": "آرام، غلي", "ar": "حليم، هادئ"},
    "perfect_akmal": {"en": "Perfect, complete", "ur": "کامل، مکمل", "fa": "کامل، تمام", "hi": "पूर्ण, संपूर्ण", "ps": "بشپړ، کامل", "ar": "أكمل، تام"},
    "generous_noble_akram": {"en": "Generous, noble, most generous", "ur": "سخی، نجیب، کریم", "fa": "بخشنده، نجیب، کریم", "hi": "उदार, कुलीन, करीम", "ps": "سخي، نجیب، کریم", "ar": "أكرم، كريم"},
    "gracious_noble_akrama": {"en": "Gracious, noble", "ur": "کریم، نجیب", "fa": "بخشنده، نجیب", "hi": "उदार, कुलीन", "ps": "سخي، نجیب", "ar": "أكرم، كريم"},
    "noble_generous_akramat": {"en": "Noble, generous", "ur": "نجیب، سخی", "fa": "نجیب، بخشنده", "hi": "कुलीन, उदार", "ps": "نجیب، سخي", "ar": "أكرم، كريم"},
    "sanctified_aksa": {"en": "The sanctified one", "ur": "مقدس، پاک", "fa": "مقدس، پاک", "hi": "पवित्र, पूजित", "ps": "مقدس، پاک", "ar": "مقدّس، مبارك"},
    "helping_hand_aksana": {"en": "Helping hand, support", "ur": "مدد کا ہاتھ، سہارا", "fa": "دست یاری، پشتیبانی", "hi": "मदद का हाथ, सहारा", "ps": "د مرستې لاس، ملاتړ", "ar": "يد العون، نصرة"},
    "elixir_akseer": {"en": "Elixir, philosopher's stone", "ur": "اکسیر، کیمیا", "fa": "اکسیر، کیمیا", "hi": "अक्सीर, रसायन", "ps": "اکسیر، کیمیا", "ar": "إكسير، كيمياء"},
    "near_one_aksil": {"en": "The one who is near", "ur": "قریب، نزدیک", "fa": "نزدیک، قریب", "hi": "निकट, क़रीब", "ps": "نږدې، قریب", "ar": "قريب، دانٍ"},
    "merciful_aktham": {"en": "Merciful, compassionate", "ur": "رحم والا، مہربان", "fa": "مهربان، بخشنده", "hi": "दयालु, करुणामय", "ps": "مهربان، رحمن", "ar": "أكثم، رحيم"},
    "exalted_sublime_ala": {"en": "Exalted, sublime", "ur": "بلند، عالی", "fa": "والا، بلند", "hi": "उच्च, महान", "ps": "لوړ، عالي", "ar": "علاء، عليّ"},
    "exalted_sublime_alaa": {"en": "Exalted, sublime", "ur": "بلند، عالی", "fa": "والا، بلند", "hi": "उच्च, महान", "ps": "لوړ، عالي", "ar": "علاء، عليّ"},
    "exalted_noble_alaali": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "الأعلى، عليّ"},
    "nobility_faith_aladdin": {"en": "Nobility of the faith", "ur": "دین کی عزت", "fa": "شرف دین", "hi": "धर्म की महानता", "ps": "د دین وياړ", "ar": "علاء الدين"},
    "exalted_sublime_alaia": {"en": "Exalted, sublime", "ur": "بلند، عالی", "fa": "والا، بلند", "hi": "उच्च, महान", "ps": "لوړ، عالي", "ar": "علاء، عليّ"},
    "exalted_one_alala": {"en": "Exalted one", "ur": "بلند مرتبہ", "fa": "والامقام", "hi": "उच्च, महान", "ps": "لوړ مقام", "ar": "مرفوع، عليّ"},
    "buttercup_alaleh": {"en": "Buttercup (a flower)", "ur": "آلالہ، ایک پھول", "fa": "آلاله، گلی سرخ", "hi": "अलाले, एक फूल", "ps": "آلاله، یو ګل", "ar": "شقائق النعمان"},
    "world_alam": {"en": "World, universe; flag", "ur": "عالم، دنیا، جھنڈا", "fa": "عالم، جهان، پرچم", "hi": "संसार, विश्व, ध्वज", "ps": "نړۍ، عالم، بیرغ", "ar": "عالم، راية"},
    "hope_alamal": {"en": "Hope, expectation", "ur": "امید، توقع", "fa": "امید، انتظار", "hi": "आशा, अपेक्षा", "ps": "هيله، تمه", "ar": "أمل، رجاء"},
    "signpost_alamat": {"en": "Guide, signpost, sign", "ur": "نشانی، راہنما", "fa": "نشان، راهنما", "hi": "चिह्न, मार्गदर्शक", "ps": "نښه، لارښود", "ar": "علامة، دليل"},
    "world_conqueror_alamgir": {"en": "World-conqueror", "ur": "عالمگیر، جہاں گیر", "fa": "جهانگیر، عالمگیر", "hi": "जगद्विजयी, आलमगीर", "ps": "نړۍ نیوونکی", "ar": "عالمكير، جهانكير"},
    "lion_alasad": {"en": "The lion", "ur": "شیر", "fa": "شیر", "hi": "शेर, सिंह", "ps": "زمری، شیر", "ar": "الأسد، ليث"},
    "nobility_faith_alauddin": {"en": "Nobility of the faith", "ur": "دین کی عزت", "fa": "شرف دین", "hi": "धर्म की महानता", "ps": "د دین وياړ", "ar": "علاء الدين"},
    "light_religion_alaudeen": {"en": "Light of the religion", "ur": "دین کا نور", "fa": "نور دین", "hi": "धर्म का प्रकाश", "ps": "د دین رڼا", "ar": "علاء الدين، نور الدين"},
    "exalted_high_alawi": {"en": "Exalted, high, noble", "ur": "بلند، عالی، نجیب", "fa": "والا، بلند، نجیب", "hi": "उच्च, महान, कुलीन", "ps": "لوړ، عالي، نجیب", "ar": "علوي، عليّ"},
    "exalted_one_alaya": {"en": "Exalted one", "ur": "بلند مرتبہ", "fa": "والامقام", "hi": "उच्च, महान", "ps": "لوړ مقام", "ar": "عالية، عليا"},
    "heavenly_alayna": {"en": "Heavenly, exalted", "ur": "آسمانی، بلند", "fa": "آسمانی، والا", "hi": "स्वर्गीय, उच्च", "ps": "آسماني، لوړ", "ar": "علوية، سماوية"},
    "exalted_one_albara": {"en": "The exalted one", "ur": "بلند مرتبہ", "fa": "والامقام", "hi": "उच्च, महान", "ps": "لوړ مقام", "ar": "البراء، مرفوع"},
    "falcon_albaz": {"en": "Falcon", "ur": "باز، شاہین", "fa": "باز، شاهین", "hi": "बाज़, शाहीन", "ps": "باز، شاهین", "ar": "باز، صقر"},
    "gentle_radiant_albinaa": {"en": "Gentle, radiant", "ur": "نرم، روشن", "fa": "نرم، فروزان", "hi": "कोमल, उज्ज्वल", "ps": "نرمه، روښانه", "ar": "لطيفة، مشرقة"},
    "mountain_range_alborz": {"en": "Mountain range (Alborz)", "ur": "البرز، پہاڑی سلسلہ", "fa": "البرز، رشته‌کوه", "hi": "अल्बोर्ज़, पर्वत श्रृंखला", "ps": "البرز، د غرونو لړۍ", "ar": "البرز، سلسلة جبال"},
    "noble_exalted_aldina": {"en": "Noble, exalted", "ur": "نجیب، بلند", "fa": "نجیب، والا", "hi": "कुलीन, उच्च", "ps": "نجیبه، لوړه", "ar": "نبيلة، مرفوعة"},
    "exalted_sublime_alee": {"en": "Exalted, sublime", "ur": "بلند، عالی", "fa": "والا، بلند", "hi": "उच्च, महान", "ps": "لوړ، عالي", "ar": "عليّ، رفيع"},
    "letter_alif_aleef": {"en": "The letter alif", "ur": "حرف الف", "fa": "حرف الف", "hi": "अक्षर अलिफ़", "ps": "د الف توری", "ar": "حرف الألف"},
    "knowledgeable_aleem": {"en": "Knowledgeable, wise", "ur": "عالم، دانا", "fa": "دانا، دانشمند", "hi": "ज्ञानी, विद्वान", "ps": "پوه، عالم", "ar": "عليم، عالم"},
    "scholar_aleema": {"en": "Scholar, learned woman", "ur": "عالمہ، فاضلہ", "fa": "دانشمند، عالمه", "hi": "विदुषी, पंडिता", "ps": "عالمه، پوهه", "ar": "عليمة، عالمة"},
    "gentle_kind_aleen": {"en": "Gentle, kind", "ur": "نرم، مہربان", "fa": "نرم، مهربان", "hi": "कोमल, दयालु", "ps": "نرمه، مهربانه", "ar": "لطيفة، كريمة"},
    "soft_hearted_aleena": {"en": "Soft-hearted, kind and gentle", "ur": "نرم دل، مہربان", "fa": "نرم‌دل، مهربان", "hi": "कोमल हृदय, दयालु", "ps": "نرم زړه، مهربانه", "ar": "لطيفة، رحيمة"},
    "exalted_noble_aleesa": {"en": "Exalted, sublime, noble", "ur": "بلند، عالی، نجیب", "fa": "والا، بلند، نجیب", "hi": "उच्च, महान, कुलीन", "ps": "لوړ، عالي، نجیب", "ar": "عليّ، رفيع، نبيل"},
    "sublime_high_aleeya": {"en": "Sublime, exalted, high", "ur": "بلند، عالی، رفیع", "fa": "والا، بلند، عالی", "hi": "उच्च, महान, श्रेष्ठ", "ps": "لوړ، عالي", "ar": "عليا، رفيعة"},
    "exalted_lofty_aleeyah": {"en": "Exalted, sublime, lofty", "ur": "بلند، عالی، رفیع", "fa": "والا، بلند، عالی", "hi": "उच्च, महान, श्रेष्ठ", "ps": "لوړ، عالي", "ar": "عالية، رفيعة"},
    "joyful_aleeza": {"en": "Joyful, happy, cheerful", "ur": "خوش، مسرور، شاداں", "fa": "شاد، خوشحال", "hi": "प्रसन्न, खुश, आनंदित", "ps": "خوشحاله، مړوند", "ar": "مبتهجة، فرِحة"},
    "helpful_assisting_aleezah": {"en": "Helpful, assisting", "ur": "مددگار، معاون", "fa": "یاری‌گر، یاور", "hi": "सहायक, सहयोगी", "ps": "مرسته کوونکې، ملاتړې", "ar": "معينة، ناصرة"},
    "submission_allah_aleezah": {"en": "Submission to Allah", "ur": "اللہ کے سامنے تسلیم", "fa": "تسلیم به خدا", "hi": "अल्लाह के प्रति समर्पण", "ps": "د الله تسلیم", "ar": "تسليم لله"},
    "exalted_noble_aleezay": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "exalted_noble_aleha": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "والا، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "عليّ، نبيل"},
    "night_born_alesha": {"en": "Night-born", "ur": "رات کو پیدا ہونے والی", "fa": "شب‌زاد", "hi": "रात में जन्मी", "ps": "په شپه زېږېدلې", "ar": "مولودة الليل"},
    "support_helper_aizat": {"en": "Support, helper", "ur": "مدد، سہارا", "fa": "کمک، پشتیبان", "hi": "मदद, सहायक", "ps": "مرسته، ملاتړ", "ar": "عون، نصير"},
    "noble_blessed_aizaz": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "glorifier_aizza": {"en": "Glorifier of God", "ur": "خدا کی تسبیح کرنے والی", "fa": "تسبیح‌گوی خدا", "hi": "ईश्वर की स्तुति करने वाली", "ps": "د خدای تسبیح ویونکې", "ar": "مسبّحة، حامدة"},
    "exalted_noble_aizzah": {"en": "Exalted, noble, mighty", "ur": "بلند، نجیب، غالب", "fa": "والا، نجیب، عزیز", "hi": "उच्च, कुलीन, प्रतापी", "ps": "لوړ، نجیب، ځواکمن", "ar": "عزيز، مرفوع، نبيل"},
}

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "aizat": ("عائزة", "عائزہ", None, "आइज़त", "عائزه", "support_helper_aizat", "Arabic", "Female", "ع و ذ", "not established", "medium", "ʿĀʾiza, feminine of عائذ ('one who seeks refuge'). The source record's gloss 'Support, helper' is unsupported."),
 "aizaz": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave the placeholder عربي_Aizaz, which is not an Arabic form. No verified identification was established and no gloss is asserted."),
 "aizza": ("عائزة", "عائزہ", None, "आइज़ा", "عائزه", "glorifier_aizza", "Arabic", "Female", "ع و ذ", "not established", "low", "The source record's gloss 'Glorifier of God' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aizzah": ("عزة", "عزہ", None, "इज़्ज़ा", "عزه", "exalted_noble_aizzah", "Arabic", "Female", "ع ز ز", "root ع ز ز occurs in the Qur'an; عزة is a normal Arabic noun", "high", "ʿIzza ('might, honour, glory'). The source record's form عزة is correct."),
 "ajab": ("عجب", "عجب", None, "अजब", "عجب", "wonder_ajab", "Arabic", "Male", "ع ج ب", "root ع ج ب occurs in the Qur'an; عجب is a normal Arabic noun", "high", "ʿAjab ('wonder, amazement')."),
 "ajal": ("أجل", "اجل", None, "अजल", "اجل", "term_ajal", "Arabic", "Unisex", "أ ج ل", "root أ ج ل occurs in the Qur'an; أجل is a normal Arabic noun", "high", "Ajal ('term, appointed time, deadline'). The source record's gloss 'Present, Transient' is unsupported."),
 "ajam": ("عجم", "عجم", None, "अजम", "عجم", "non_arabs_ajam", "Arabic", "Male", "ع ج م", "not established", "high", "ʿAjam ('non-Arabs, Persians'), a collective term. The source record's gloss 'Persians' is a reasonable rendering."),
 "ajaz": ("عجز", "عجز", None, "अजज़", "عجز", "quiet_ajaz", "Arabic", "Male", "ع ج ز", "root ع ج ز occurs in the Qur'an; عجز is a normal Arabic noun", "low", "ʿAjz ('weakness, inability'). The source record's gloss 'Quiet, calm' is unsupported."),
 "ajda": ("أجدا", "اجدا", None, "अजदा", "اجدا", "devout_ajda", "Arabic", "Female", "ج د و", "not established", "low", "The source record's gloss 'Devout, Worshipper' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ajeeb": ("عجيب", "عجیب", None, "अजीब", "عجيب", "strange_ajeeb", "Arabic", "Unisex", "ع ج ب", "root ع ج ب occurs in the Qur'an; عجيب is a normal Arabic adjective", "high", "ʿAjīb ('strange, wonderful, marvellous')."),
 "ajeel": ("عجيل", "عجیل", None, "अजील", "عجيل", "swift_ajeel", "Arabic", "Male", "ع ج ل", "not established", "medium", "ʿAjīl ('swift, quick, hasty'). The source record's gloss 'Swift, Quick' is a reasonable rendering."),
 "ajia": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Ajia' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "ajib": ("عجيب", "عجیب", None, "अजीब", "عجيب", "wonderful_ajib", "Arabic", "Male", "ع ج ب", "root ع ج ب occurs in the Qur'an; عجيب is a normal Arabic adjective", "high", "Variant romanization of عجيب."),
 "ajla": ("عجلى", "عجلی", None, "अजला", "عجلى", "gentle_soft_ajla", "Arabic", "Female", "ع ج ل", "not established", "low", "The source record's gloss 'Gentle and soft' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ajlan": ("أجلان", "اجلان", None, "अजलान", "اجلان", "mountain_ajlan", "Arabic", "Male", "أ ج ل", "not established", "low", "The source record's gloss 'Mountain or hill' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ajmal": ("أجمل", "اجمل", None, "अजमल", "اجمل", "most_beautiful_ajmal", "Arabic", "Male", "ج م ل", "root ج م ل occurs in the Qur'an; أجمل is the elative of جميل", "high", "Ajmal ('most beautiful'), elative of جميل. The source record's gloss 'Most Beautiful, Exalted' is a reasonable rendering."),
 "ajmar": ("أجمر", "اجمر", None, "अजमर", "اجمر", "compassionate_ajmar", "Arabic", "Male", "ج م ر", "not established", "low", "The source record's gloss 'Gentle, kind, compassionate' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ajmi": ("عجمي", "عجمی", None, "अजमी", "عجمي", "foreigner_ajmi", "Arabic", "Male", "ع ج م", "not established", "medium", "ʿAjamī ('foreigner, non-Arab; Persian'). The source record's gloss 'Traveler, Wanderer' is unsupported."),
 "ajva": ("أجوة", "اجوہ", None, "अजवा", "اجوه", "dates_ajva", "Arabic", "Female", "ج و ي", "not established", "low", "The source record's gloss 'Dates' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "ajwad": ("أجود", "اجود", None, "अजवाद", "اجود", "graceful_honorable_ajwad", "Arabic", "Male", "ج و د", "not established", "medium", "Ajwad, elative of جواد ('generous'). The source record's gloss 'Graceful, Honorable' is an approximation."),
 "akaash": ("أكاش", "آکاش", None, "आकाश", "آکاش", "sky_akaash", "Sanskrit", "Unisex", None, "not established", "high", "Ākāśa (आकाश) is a Sanskrit word meaning 'sky, space, aether'. The source record classified it as Arabic, which is incorrect."),
 "akasha": ("أكاشا", "آکاشا", None, "आकाश", "آکاشا", "aether_akasha", "Sanskrit", "Unisex", None, "not established", "high", "Sanskrit ākāśa (आकाश), the fifth element ('aether') in Hindu cosmology. The source record classified it as Arabic, which is incorrect."),
 "akbar": ("أكبر", "اکبر", None, "अकबर", "اکبر", "greatest_akbar", "Arabic", "Male", "ك ب ر", "root ك ب ر occurs in the Qur'an; أكبر is the elative of كبير", "high", "Akbar ('greatest'), elative of كبير; also the name of the Mughal emperor Akbar (r. 1556-1605)."),
 "akbari": ("أكبرى", "اکبری", None, "अकबरी", "اکبری", "great_akbari", "Arabic", "Female", "ك ب ر", "not established", "medium", "Feminine/nisba form from أكبر. The source record's gloss 'Great, Big' is a reasonable rendering."),
 "akber": ("أكبر", "اکبر", None, "अकबर", "اکبر", "great_akber", "Arabic", "Male", "ك ب ر", "root ك ب ر occurs in the Qur'an; أكبر is the elative of كبير", "high", "Variant romanization of أكبر."),
 "akeel": ("عقيل", "عقیل", None, "अक़ील", "عقيل", "wise_akeel", "Arabic", "Male", "ع ق ل", "not established", "high", "ʿAqīl, diminutive of عقل ('intellect'); also the name of ʿAqīl ibn Abī Ṭālib."),
 "akeelah": ("عاقلة", "عاقلہ", None, "अक़ीला", "عاقله", "intelligent_akeelah", "Arabic", "Female", "ع ق ل", "not established", "high", "Feminine of عاقل ('intelligent, discerning')."),
 "akeem": ("حكيم", "حکیم", None, "हकीम", "حکيم", "wise_akeem", "Arabic", "Male", "ح ك م", "root ح ك م occurs in the Qur'an; حكيم is a normal Arabic adjective and a divine name", "medium", "The source record gave عاقم, which is not a standard Arabic form; the intended name is likely حكيم (Ḥakīm). The identification is uncertain."),
 "akela": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record supplied the Latin-script placeholder 'Akela' rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "akhas": ("أخاس", "اخاس", None, "अख़ास", "اخاس", "helper_akhas", "Arabic", "Male", "خ و ص", "not established", "low", "The source record's gloss 'Helper, Supporter' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akhdan": ("أخدان", "اخدان", None, "अख़दान", "اخدان", "helper_akhdan", "Arabic", "Male", "خ د ن", "not established", "low", "The source record's gloss 'Helper, Supporter' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akhlak": ("أخلاق", "اخلاق", None, "अख़लाक़", "اخلاق", "morals_akhlak", "Arabic", "Unisex", "خ ل ق", "not established", "high", "Akhlāq, plural of خُلُق ('character, moral conduct')."),
 "akhlaq": ("أخلاق", "اخلاق", None, "अख़लाक़", "اخلاق", "morals_akhlaq", "Arabic", "Male", "خ ل ق", "not established", "high", "Variant romanization of أخلاق."),
 "akhlas": ("أخلص", "اخلص", None, "अख़लस", "اخلص", "sincere_akhlas", "Arabic", "Female", "خ ل ص", "root خ ل ص occurs in the Qur'an; أخلص is a normal Arabic verb form", "medium", "Akhlaṣ ('more/most sincere'), from the root خ ل ص. The source record's gloss 'Pure, Sincere' is a reasonable rendering."),
 "akhmad": ("أحمد", "احمد", None, "अख़मद", "احمد", "follower_muhammad_akhmad", "Arabic", "Male", "ح م د", "أحمد occurs in the Qur'an (Sūrat al-Ṣaff 61:6) as a name of the Prophet", "medium", "Variant romanization of أحمد. The source record's gloss 'Follower of Muhammad' is unsupported."),
 "akhram": ("أخرم", "اخرم", None, "अख़रम", "اخرم", "deferred_akhram", "Arabic", "Male", "خ ر م", "not established", "low", "The source record's gloss 'Late, deferred' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akhtar": ("أختر", "اختر", "اختر", "अख़्तर", "اختر", "star_akhtar", "Persian", "Unisex", None, "not established", "high", "Persian akhtar ('star, bright celestial body'), also the name of a flower. The source record classified it as Arabic, which is incorrect."),
 "akhter": ("أختر", "اختر", "اختر", "अख़्तर", "اختر", "nearest_akhter", "Persian", "Female", None, "not established", "medium", "Variant romanization of اختر. The source record's gloss 'The Nearest One' is unsupported."),
 "akhyar": ("أخيار", "اخیار", None, "अख़यार", "اخيار", "pure_clear_akhyar", "Arabic", "Male", "خ ي ر", "not established", "medium", "Akhyār, plural of خيّر ('good, excellent'). The source record's gloss 'Pure, Clear, Bright' is an approximation."),
 "aki": ("أكي", "اکی", None, "अकी", "اکي", "bright_aki", "Arabic", "Unisex", "أ ك ي", "not established", "low", "The source record's gloss 'Bright, Shining' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akia": ("عقيا", "عقیا", None, "अक़िया", "عقيا", "truthful_akia", "Arabic", "Female", "ع ق ي", "not established", "low", "The source record's gloss 'Truthful' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akib": ("عقيب", "عقیب", None, "अक़ीब", "عقيب", "successor_akib", "Arabic", "Male", "ع ق ب", "not established", "medium", "ʿAqīb ('successor, heir'). The source record's gloss 'Successor, Heir' is a reasonable rendering."),
 "akif": ("عاكف", "عاکف", None, "आकिफ़", "عاكف", "devoted_akif", "Arabic", "Male", "ع ك ف", "root ع ك ف occurs in the Qur'an; عاكف is a normal Arabic active participle", "high", "ʿĀkif ('devoted, one who secludes himself in worship')."),
 "akifa": ("عكيفة", "عکیفہ", None, "अकीफ़ा", "عكيفه", "strong_determined_akifa", "Arabic", "Female", "ع ك ف", "not established", "low", "The source record's gloss 'A woman who is strong and determined' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akifah": ("عكيفة", "عکیفہ", None, "अकीफ़ा", "عكيفه", "eternal_garden_akifah", "Arabic", "Female", "ع ك ف", "not established", "low", "The source record's gloss 'Fragile, Eternal, Garden' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akil": ("عقيل", "عقیل", None, "अक़ील", "عقيل", "wise_akil", "Arabic", "Male", "ع ق ل", "not established", "high", "Variant romanization of عقيل. The source record's form أكل is the verb 'to eat', not a name."),
 "akila": ("عقيلة", "عقیلہ", None, "अक़ीला", "عقيله", "understanding_akila", "Arabic", "Female", "ع ق ل", "not established", "high", "Feminine of عقيل. The source record's form أكيلا is not a standard Arabic form."),
 "akilah": ("عقيلة", "عقیلہ", None, "अक़ीला", "عقيله", "wise_akilah", "Arabic", "Female", "ع ق ل", "not established", "high", "Variant romanization of عقيلة."),
 "akili": ("عقيل", "عقیل", None, "अक़ीली", "عقيل", "wise_akili", "Arabic", "Unisex", "ع ق ل", "not established", "medium", "Variant romanization of عقيل."),
 "akim": ("حكيم", "حکیم", None, "हकीम", "حکيم", "ruler_master_akim", "Arabic", "Male", "ح ك م", "root ح ك م occurs in the Qur'an; حكيم is a normal Arabic adjective and a divine name", "low", "The source record gave عكيم, which is not a standard Arabic form. The intended name may be حكيم. The identification is uncertain."),
 "akin": ("أكين", "اکین", None, "अकीन", "اکين", "trustworthy_akin", "Arabic", "Unisex", "أ ك ن", "not established", "low", "The source record's gloss 'Trustworthy, Sincere' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aklima": ("عقليمة", "عقلیمہ", None, "अक़लीमा", "عقليمه", "moonlit_aklima", "Arabic", "Female", "ع ق ل", "not established", "low", "The source record's gloss 'Moon-lit Night' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aklimah": ("أكليمة", "اکلیمہ", None, "अकलीमा", "اكليمه", "calm_aklimah", "Arabic", "Female", "ك ل م", "not established", "low", "The source record's gloss 'Calm' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akmal": ("أكمل", "اکمل", None, "अकमल", "اكمل", "perfect_akmal", "Arabic", "Male", "ك م ل", "root ك م ل occurs in the Qur'an; أكمل is the elative of كامل", "high", "Akmal ('most perfect, most complete'), elative of كامل."),
 "akram": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record left this name with no origin, no script form and no gloss. No verified identification was established and no gloss is asserted."),
 "akrama": ("أكرما", "اکرما", None, "अकरमा", "اکرما", "gracious_noble_akrama", "Arabic", "Male", "ك ر م", "not established", "medium", "Related to أكرم ('most generous'). The source record's gloss 'Gracious, Noble' is a reasonable rendering."),
 "akramat": ("أكرمات", "اکرمات", None, "अकरमात", "اکرمات", "noble_generous_akramat", "Arabic", "Male", "ك ر م", "not established", "low", "The source record's form أكرمات is not a standard Arabic form. The identification is uncertain."),
 "aksa": ("أكسا", "اکسا", None, "अक्सा", "اکسا", "sanctified_aksa", "Arabic", "Female", "ق د س", "not established", "low", "The source record's gloss 'The Sanctified One' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aksana": ("أكسانا", "اکسانا", None, "अक्साना", "اکسانا", "helping_hand_aksana", "Arabic", "Female", "أ ك س", "not established", "low", "The source record's gloss 'Helping hand, support' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akseer": ("إكسير", "اکسیر", "اکسیر", "अक्सीर", "اکسیر", "elixir_akseer", "Arabic", "Male", "ك س ر", "not established", "high", "Al-iksīr ('elixir, philosopher's stone'), from Greek xērion via Arabic alchemy. The source record's gloss 'Conqueror, Victorious' is unsupported."),
 "aksil": ("أكسيل", "اکسیل", None, "अक्सील", "اکسيل", "near_one_aksil", "Arabic", "Male", "أ ك س", "not established", "low", "The source record's gloss 'The One Who Is Near' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aktham": ("أكثم", "اکثم", None, "अकथम", "اكثم", "merciful_aktham", "Arabic", "Male", "ك ث م", "not established", "low", "The source record's gloss 'Merciful' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "akuma": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أكومه with the gloss 'Evil Spirit', which is not a personal-name meaning. No verified identification was established and no gloss is asserted."),
 "akwan": ("أكوان", "اکوان", None, "अकवान", "اکوان", None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave أكوان with the gloss 'Unknown'. No verified identification was established and no gloss is asserted."),
 "ala": ("علاء", "علاء", None, "अला", "علاء", "exalted_sublime_ala", "Arabic", "Unisex", "ع ل و", "root ع ل و occurs in the Qur'an; علاء is a normal Arabic noun", "high", "ʿAlāʾ ('exaltedness, sublimity, highness')."),
 "alaa": ("علاء", "علاء", None, "अला", "علاء", "exalted_sublime_alaa", "Arabic", "Unisex", "ع ل و", "root ع ل و occurs in the Qur'an; علاء is a normal Arabic noun", "high", "Variant romanization of علاء."),
 "alaali": ("الأعلى", "الاعلی", None, "अलाअली", "الاعلی", "exalted_noble_alaali", "Arabic", "Unisex", "ع ل و", "الأعلى occurs in the Qur'an (Sūrat al-Aʿlā 87:1) as a divine name", "medium", "Al-Aʿlā ('the Most High'), a divine name. The source record's form الأعلی is the Persian/Urdu orthography."),
 "aladdin": ("علاء الدين", "علاء الدین", None, "अलाउद्दीन", "علاء الدين", "nobility_faith_aladdin", "Arabic", "Male", "ع ل و", "not established", "high", "ʿAlāʾ al-Dīn ('nobility of the faith'), borne by several historical figures including ʿAlāʾ al-Dīn Khaljī (r. 1296-1316)."),
 "alaia": ("علاء", "علاء", None, "अलाया", "علاء", "exalted_sublime_alaia", "Arabic", "Female", "ع ل و", "root ع ل و occurs in the Qur'an; علاء is a normal Arabic noun", "medium", "Variant romanization of علاء. The source record's form ألعياء is malformed."),
 "alala": ("الأعلى", "الاعلی", None, "अलाला", "الاعلی", "exalted_one_alala", "Arabic", "Male", "ع ل و", "الأعلى occurs in the Qur'an (Sūrat al-Aʿlā 87:1) as a divine name", "low", "The source record's form الا is a definite article rather than a name. The identification is uncertain."),
 "alaleh": ("آلاله", "آلالہ", "آلاله", "अलाले", "آلاله", "buttercup_alaleh", "Persian", "Female", None, "not established", "high", "Persian ālāleh ('buttercup', a flower). The source record classified it as Arabic and glossed it 'Exalted One', both of which are incorrect."),
 "alam": ("عالم", "عالم", None, "आलम", "عالم", "world_alam", "Arabic", "Male", "ع ل م", "root ع ل م occurs in the Qur'an; عالم is a normal Arabic noun", "high", "ʿĀlam ('world, universe'); also ʿalam ('flag, banner')."),
 "alamal": ("الأمل", "الامل", None, "अमल", "الامل", "hope_alamal", "Arabic", "Female", "أ م ل", "not established", "high", "Al-amal ('the hope'). The source record's form الأمـل is the definite form."),
 "alamat": ("علامات", "علامات", None, "अलामात", "علامات", "signpost_alamat", "Arabic", "Male", "ع ل م", "root ع ل م occurs in the Qur'an; علامات is a normal Arabic plural", "medium", "ʿAlāmāt, plural of علامة ('sign, mark'). The source record's gloss 'Guide, Signpost' is a reasonable rendering."),
 "alamgir": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave the placeholder عربي_Alamgir, which is not an Arabic form. ʿĀlamgīr is a Persian compound ('world-conqueror'), the regnal title of the Mughal emperor Aurangzeb. No verified Arabic identification was established."),
 "alasad": ("الأسد", "الاسد", None, "अलअसद", "الاسد", "lion_alasad", "Arabic", "Male", "أ س د", "not established", "high", "Al-asad ('the lion'). The source record's gloss 'The Lion' is a reasonable rendering."),
 "alauddin": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record gave the placeholder عربي_Alauddin, which is not an Arabic form. The correct form is علاء الدين (ʿAlāʾ al-Dīn). No verified identification was established for the placeholder."),
 "alaudeen": ("علاء الدين", "علاء الدین", None, "अलाउद्दीन", "علاء الدين", "light_religion_alaudeen", "Arabic", "Male", "ع ل و", "not established", "medium", "Variant romanization of علاء الدين. The source record's form العذن is malformed and the gloss 'The light of the religion' conflates it with نور الدين."),
 "alawi": ("علوي", "علوی", None, "अलवी", "علوي", "exalted_high_alawi", "Arabic", "Male", "ع ل و", "not established", "high", "ʿAlawī, nisba adjective from علي ('exalted, high'); also the name of a dynasty and a branch of Islam."),
 "alaya": ("عالية", "عالیہ", None, "अलाया", "عاليه", "exalted_one_alaya", "Arabic", "Female", "ع ل و", "not established", "high", "ʿĀliya ('exalted, high'). The source record's form عالية is correct."),
 "alayna": ("علينا", "علینا", None, "अलैना", "علينا", "heavenly_alayna", "Arabic", "Female", "ع ل و", "not established", "low", "The source record's form علينا is a prepositional phrase ('upon us') rather than a personal name. The identification is uncertain."),
 "albara": ("البراء", "البراء", None, "अलबरा", "البراء", "exalted_one_albara", "Arabic", "Male", "ب ر أ", "not established", "low", "Al-barāʾ ('freedom, innocence'). The source record's gloss 'The Exalted One' is unsupported."),
 "albaz": ("الباز", "الباز", None, "अलबाज़", "الباز", "falcon_albaz", "Arabic", "Male", "ب ز ز", "not established", "medium", "Al-bāz ('the falcon'). The source record's gloss 'Falcon' is a reasonable rendering."),
 "albinaa": ("ألبينا", "البینا", None, "अलबीना", "البينا", "gentle_radiant_albinaa", "Arabic", "Female", "ب ي ن", "not established", "low", "The source record's gloss 'Gentle, Radiant' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "alborz": ("البرز", "البرز", "البرز", "अल्बोर्ज़", "البرز", "mountain_range_alborz", "Persian", "Male", None, "not established", "high", "Alborz (البرز) is a mountain range in northern Iran; the name derives from Avestan Hari Barazaiti ('the high guardian'). The source record classified it as Arabic, which is incorrect."),
 "aldina": ("الدينة", "الدینہ", None, "अलदीना", "الدينه", "noble_exalted_aldina", "Arabic", "Female", "د ي ن", "not established", "low", "The source record's form الدينة is not a standard Arabic form. The identification is uncertain."),
 "alee": ("علي", "علی", None, "अली", "علي", "exalted_sublime_alee", "Arabic", "Male", "ع ل و", "root ع ل و occurs in the Qur'an; علي is a normal Arabic adjective and a divine name", "high", "ʿAlī ('exalted, sublime'), also the name of ʿAlī ibn Abī Ṭālib (d. 661)."),
 "aleef": ("أليف", "الیف", None, "अलीफ़", "اليف", "letter_alif_aleef", "Arabic", "Male", "أ ل ف", "not established", "low", "The source record's gloss 'Letter A in Arabic Alphabet' is a description of the letter alif rather than a lexical meaning. The identification is uncertain."),
 "aleem": ("عليم", "علیم", None, "अलीम", "عليم", "knowledgeable_aleem", "Arabic", "Male", "ع ل م", "عليم occurs in the Qur'an as a divine name", "high", "ʿAlīm ('knowledgeable, all-knowing'), a divine name."),
 "aleema": ("عليمة", "علیمہ", None, "अलीमा", "عليمه", "scholar_aleema", "Arabic", "Female", "ع ل م", "not established", "high", "Feminine of عليم ('learned, knowledgeable')."),
 "aleen": ("علين", "علین", None, "अलीन", "علين", "gentle_kind_aleen", "Arabic", "Female", "ع ل ن", "not established", "low", "The source record's gloss 'Gentle, Kind' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
 "aleena": ("ألينا", "الینا", None, "अलीना", "الينا", "soft_hearted_aleena", "Arabic", "Female", "ل ي ن", "not established", "medium", "Related to لين ('softness, gentleness'). The source record's gloss 'Soft-hearted, Kind and Gentle' is a reasonable rendering."),
 "aleesa": ("آليسا", "آلیسا", None, "अलीसा", "آليسا", "exalted_noble_aleesa", "Arabic", "Female", "ع ل و", "not established", "low", "The source record's form آليسا is a transliteration of a European name (Alicia/Alice) rather than an Arabic lexical form. The identification is uncertain."),
 "aleeya": ("عليا", "علیا", None, "अलिया", "عليا", "sublime_high_aleeya", "Arabic", "Female", "ع ل و", "not established", "high", "ʿUlyā ('sublime, exalted, high')."),
 "aleeyah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_lofty_aleeyah", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية."),
 "aleeza": ("عليزة", "علیزہ", None, "अलीज़ा", "عليزه", "joyful_aleeza", "Hebrew", "Female", None, "not established", "medium", "Aleeza is a Hebrew/Urdu name meaning 'joyful, happy' (related to Hebrew עלזה). The source record's gloss 'Helpful, assisting' is unsupported."),
 "aleezah": ("عليزة", "علیزہ", None, "अलीज़ा", "عليزه", "helpful_assisting_aleezah", "Hebrew", "Female", None, "not established", "low", "Variant romanization of عليزة. The source record's gloss 'Submission to Allah' is unsupported."),
 "aleezay": ("عليزة", "علیزہ", None, "अलीज़े", "عليزه", "exalted_noble_aleezay", "Hebrew", "Female", None, "not established", "low", "Variant romanization of عليزة. The source record's gloss 'Exalted, Noble' is unsupported."),
 "aleha": ("عليها", "علیہا", None, "अलेहा", "عليها", "exalted_noble_aleha", "Arabic", "Female", "ع ل و", "not established", "low", "The source record's form عليها is a prepositional phrase ('upon her') rather than a personal name. The identification is uncertain."),
 "alesha": ("عليشا", "علیشا", None, "अलेशा", "عليشا", "night_born_alesha", "Arabic", "Female", "ع ل ش", "not established", "low", "The source record's gloss 'Night-born' could not be matched to a Tier-A/B Arabic lexical source. The identification is uncertain."),
}
