# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 47 (navil..neveen).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": navil -> Latin "Navil"; naweed -> Latin
   "Nawwab"; naznin -> Latin "Naznin"; nazy -> Latin "Nazy"; neelu -> Latin
   "Neelu"; neeya -> Latin "Neeya"; negar -> Latin "Negar"; nelam -> Latin
   "Nelam"; nen -> Latin "Nen"; nehrin -> Latin "Nahr"; nazeera -> "نazeera"
   (broken Latin-Arabic mix); nazrin -> "назрин" (Cyrillic);
   nawroz -> زائنب; nawwaf -> علي; nazgul -> أحمد; neeka -> عائشة;
   nevaeh -> فاطمة; nelofar -> نلفجر; nazeem -> نَذِمَ; nazeeh -> نظيف;
   nazeer -> ناظر; nazeerah -> نظرة; nazif -> نظيف (correct); nazih -> نزيه (correct).
 * EMPTY STUBS (8-key records, no data): nawal, nawwar.
 * MISLABELLED ORIGIN: nawroz (Persian), nawshad/nawshin (Persian),
   nawzad (Persian), nayab (Persian), naz/nazanin/nazneen/naznin (Persian),
   nazli (Turkish), nazrul (Bengali), neeka/negar/nelofar (Persian),
   neelam/neelu (Hindi/Sanskrit), nejat (Turkish), neshat (Persian),
   nevaeh (English), nazgul (Turkish/Kazakh), nazrin (Persian/Azerbaijani).
 * DEGARBLED GLOSSES: nawaal "Gentle Breeze", nawaaz "Restless", nawaf "Rest",
   nawar "Blooming Flower", naweed "Comforter", nawel "Moon",
   nawfal "Successful Trader", nawraa "Gentle Breeze", nawras "Delight, Joy, Pleasure",
   nawshad "Light of guidance", nawshin "Friend of the Intelligent",
   nawwaf "Determined, Steadfast", nawzad "Restorer, Reviver", nay "Delight, Pleasure",
   nayef "Gracious, generous", nayel "Radiant, bright, shining light",
   nayla "Night, Night Journey", nayyar "Guiding", naz "Gazelle", naza "Gazelle",
   nazanin "Joyful, Delightful", nazeef "Gifted, Generous", nazeeh "Adviser, Warning, Reminder",
   nazeeha "Counsel, advice", nazeem "Gentle Breeze", nazeer "Observer, Seer",
   nazeerah "Inspector, observer", nazeh "Watchful, attentive, careful",
   nazer "Noble or Exalted", nazgul "Noble, Radiant, Victorious", nazha "Help",
   nazhan "Fresh, New", nazia "Pride, glory", naziah "Graceful",
   nazifa "Pure, Chaste", nazih "Intelligent, Wise, Advisor", naziha "Graceful, Pleasing",
   nazihah "hidden, secret", nazila "Delight, beauty", nazima "Grace, beauty, adornment",
   nazimah "Gracious, beautiful, or adorned", nazira "Bright, Radiant, One Who Sees Clearly",
   nazirah "Watchful, Vigilant", nazish "Delight, pleasure", nazma "Night sky, star",
   nazmi "Graceful", nazmin "Graceful, Delicate", naznin "Graceful, adorned",
   nazrin "A person who contemplates, reflects, pon", nazy "Joyful, cheerful, happy",
   neba "Clouds, rain", neeka "Gentle, Delicate, Graceful", neelu "Blue Lotus",
   neeya "Gentle, Tender, Delicate", negar "Jewel, Precious", nehad "Graceful, Gentle",
   nehan "Gentle, Tender", nehar "River", nehat "Given by God",
   nehla "Night, Shining Star", nehrin "Light of the moon", neima "Comforting, Consoling",
   nejib "Gifted, Generous", nejla "Young girl", nelam "Light, Radiant",
   nemat "Gem", nen "Grace, beauty", nesma "Awakening, Inspiration",
   nevaeh "Divine gift", neveen "Graceful, Beautiful".
 * GENDER ERRORS: navil, nawar, nayab, nazar, nazha, nazneen, nazrin, nehan,
   nehat, nehrin, nelam were labelled unisex where documented usage is male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated46 import GLOSSES as _G46

GLOSSES = dict(_G46)
GLOSSES.update({
    "naveel": {"en": "Navil; a male given name", "ur": "نویل (مردانہ نام)", "fa": "نویل (نام مردانه)", "hi": "नवील (पुरुष नाम)", "ps": "نویل (نر نوم)", "ar": "نَوِيل (اسْم عَلَم مُذَكَّر)"},
    "deputy": {"en": "Deputy, lord, master (plural of naib)", "ur": "نواب، سردار، حاکم", "fa": "نواب، سرور", "hi": "नवाब, सरदार", "ps": "نواب، مشر", "ar": "النُّوَّاب، السَّيِّد"},
    "gift_bestowal": {"en": "Gift, bestowal, bounty", "ur": "نوال، عطیہ، بخشش", "fa": "نوال، بخشش", "hi": "नवाल, उपहार", "ps": "نوال، بخښنه", "ar": "النَّوَال، الْعَطَاء"},
    "cherishing": {"en": "Cherishing, caressing (Persian suffix)", "ur": "نواز، نوازنے والا", "fa": "نواز، نوازنده", "hi": "नवाज़, प्यार करने वाला", "ps": "نواز، مینه کوونکی", "ar": "نَوَاز (لَاحِقَة فَارِسِيَّة)"},
    "nawwaf": {"en": "Nawwaf; a male given name", "ur": "نواف (مردانہ نام)", "fa": "نواف (نام مردانه)", "hi": "नव्वाफ़ (पुरुष नाम)", "ps": "نواف (نر نوم)", "ar": "نَوَّاف (اسْم عَلَم مُذَكَّر)"},
    "blossoming": {"en": "Blossoming, radiant", "ur": "نوار، کھلتا ہوا، روشن", "fa": "نوار، شکوفا", "hi": "नव्वार, खिलता हुआ", "ps": "نوار، ګل کوونکی", "ar": "النَّوَّار، الْمُزْهِر"},
    "kindness": {"en": "Kindness, favour, caress", "ur": "نوازش، مہربانی، عنایت", "fa": "نوازش، لطف", "hi": "नवाज़िश, कृपा", "ps": "نوازش، مهرباني", "ar": "النَّوَازِش (اللُّطْف)"},
    "nawfal": {"en": "Nawfal; a male given name", "ur": "نوفل (مردانہ نام)", "fa": "نوفل (نام مردانه)", "hi": "नौफ़ल (पुरुष नाम)", "ps": "نوفل (نر نوم)", "ar": "نَوْفَل (اسْم عَلَم مُذَكَّر)"},
    "blossom_light": {"en": "Blossom, light, radiance", "ur": "نورہ، کلی، روشنی", "fa": "نوره، شکوفه، نور", "hi": "नौरा, कली, प्रकाश", "ps": "نوره، ګل، رڼا", "ar": "النَّوْرَة، الْإِشْرَاق"},
    "nawraa": {"en": "Nawraa; a female given name", "ur": "نوراء (زنانہ نام)", "fa": "نوراء (نام زنانه)", "hi": "नौरा (स्त्री नाम)", "ps": "نوراء (ښځينه نوم)", "ar": "نَوْرَاء (اسْم عَلَم مُؤَنَّث)"},
    "seagull": {"en": "Seagull; a young man", "ur": "نورس، سمندری پرندہ", "fa": "نورس، مرغ دریایی", "hi": "नौरस, समुद्री पक्षी", "ps": "نورس، سمندري مرغۍ", "ar": "النَّوْرَس"},
    "nowruz": {"en": "New day; the Persian New Year", "ur": "نوروز، نیا دن", "fa": "نوروز، روز نو", "hi": "नौरोज़, नया दिन", "ps": "نوروز، نوی ورځ", "ar": "النَّيْرُوز، الْيَوْم الْجَدِيد"},
    "naushad2": {"en": "Naushad; happy, joyful", "ur": "نوشاد، خوش، شادمان", "fa": "نوشاد، خوشحال", "hi": "नौशाद, प्रसन्न", "ps": "نوشاد، خوشحاله", "ar": "نَوْشَاد، الْمَسْرُور"},
    "nausheen2": {"en": "Nausheen; sweet, pleasant", "ur": "نوشین، شیریں", "fa": "نوشین، شیرین", "hi": "नौशीन, मधुर", "ps": "نوشین، خوږ", "ar": "نَوْشِين، الْحُلْو"},
    "newborn": {"en": "Newborn, newly born", "ur": "نوزاد، نومولود", "fa": "نوزاد، تازه متولد", "hi": "नौज़ाद, नवजात", "ps": "نوزاد، نوی زېږېدلی", "ar": "النَّوْزَاد (الْمَوْلُود الْجَدِيد)"},
    "reed_flute": {"en": "Reed flute, nay", "ur": "ناي، بانسری", "fa": "نی، نای", "hi": "नाय, बाँसुरी", "ps": "ناي، بانسري", "ar": "النَّاي"},
    "rare_precious": {"en": "Rare, precious, unique", "ur": "نایاب، کمیاب، انمول", "fa": "نایاب، کمیاب", "hi": "नायाब, दुर्लभ", "ps": "نایاب، کم پیدا", "ar": "النَّايَاب (النَّادِر)"},
    "nayef": {"en": "Nayef; high, elevated", "ur": "نایف، بلند، عالی", "fa": "نایف، بلند", "hi": "नायफ़, ऊँचा", "ps": "نایف، لوړ", "ar": "نَايِف، الْعَالِي"},
    "nayel": {"en": "Nayel; obtainer, acquirer", "ur": "نائل، حاصل کرنے والا", "fa": "نائل، به‌دست‌آورنده", "hi": "नाइल, प्राप्त करने वाला", "ps": "نائل، ترلاسه کوونکی", "ar": "النَّائِل، الْحَاصِل"},
    "sleeping": {"en": "Sleeping, resting", "ur": "نائم، سونے والا", "fa": "نائم، خفته", "hi": "नाइम, सोता हुआ", "ps": "نائم، ویده", "ar": "النَّائِم"},
    "nayla": {"en": "Nayla; obtainer (feminine)", "ur": "نائلہ، حاصل کرنے والی", "fa": "نائله، به‌دست‌آورنده", "hi": "नाइला, प्राप्त करने वाली", "ps": "نائله، ترلاسه کوونکې", "ar": "النَّائِلَة، الْحَاصِلَة"},
    "nayyar": {"en": "Nayyar; luminous, brilliant", "ur": "نیار، روشن، تاباں", "fa": "نیار، درخشان", "hi": "नय्यार, प्रकाशमान", "ps": "نیار، روښانه", "ar": "النَّيَّار، الْمُضِيء"},
    "coquetry": {"en": "Coquetry, pride, charm", "ur": "ناز، ادا، نخوت", "fa": "ناز، کرشمه", "hi": "नाज़, अदा", "ps": "ناز، غرور", "ar": "النَّاز (الدَّلَال)"},
    "naza": {"en": "Naza; a female given name", "ur": "نازہ (زنانہ نام)", "fa": "نازا (نام زنانه)", "hi": "नाज़ा (स्त्री नाम)", "ps": "نازه (ښځينه نوم)", "ar": "نَازَة (اسْم عَلَم مُؤَنَّث)"},
    "delicacy": {"en": "Delicacy, refinement, subtlety", "ur": "نزاکت، لطافت، نفاست", "fa": "نزاکت، لطافت", "hi": "नज़ाकत, सूक्ष्मता", "ps": "نزاکت، نرمي", "ar": "النَّزَاكَة، اللَّطَافَة"},
    "beloved_sweet": {"en": "Beloved, sweetheart, darling", "ur": "نازنین، پیاری، محبوبہ", "fa": "نازنین، دلبر", "hi": "नाज़नीन, प्यारी", "ps": "نازنین، ګرانه", "ar": "النَّازَنِين (الْحَبِيبَة)"},
    "observer": {"en": "Observer, overseer, spectator", "ur": "ناظر، دیکھنے والا، نگران", "fa": "ناظر، بیننده", "hi": "नाज़िर, देखने वाला", "ps": "ناظر، کتونکی", "ar": "النَّاظِر، الْمُرَاقِب"},
    "clean_pure": {"en": "Clean, pure, spotless", "ur": "نظیف، صاف، پاک", "fa": "نظیف، پاک", "hi": "नज़ीफ़, साफ़", "ps": "نظیف، پاک", "ar": "النَّظِيف، الطَّاهِر"},
    "honest_virtuous": {"en": "Honest, virtuous, upright", "ur": "نزیہ، نیک، پارسا", "fa": "نزیه، پاکدامن", "hi": "नज़ीह, नेक", "ps": "نزیه، نیک", "ar": "النَّزِيه، الْعَفِيف"},
    "honest_virtuous_f": {"en": "Honest, virtuous (feminine)", "ur": "نزیہہ، نیک (مؤنث)", "fa": "نزیهه، پاکدامن (مؤنث)", "hi": "नज़ीहा, नेक (स्त्री)", "ps": "نزیهه، نیکه", "ar": "النَّزِيهَة، الْعَفِيفَة"},
    "nazeem": {"en": "Nazeem; organizer, arranger", "ur": "نظیم، منظم کرنے والا", "fa": "نظیم، سازمان‌دهنده", "hi": "नज़ीम, व्यवस्थापक", "ps": "نظیم، تنظیم کوونکی", "ar": "النَّظِيم، الْمُنَظِّم"},
    "warner": {"en": "Warner, one who warns", "ur": "نذیر، ڈرانے والا، خبردار کرنے والا", "fa": "نذیر، هشداردهنده", "hi": "नज़ीर, चेतावनी देने वाला", "ps": "نذیر، وېروونکی", "ar": "النَّذِير، الْمُنْذِر"},
    "warner_f": {"en": "Warner (feminine)", "ur": "نذیرہ، خبردار کرنے والی", "fa": "نذیره، هشداردهنده", "hi": "नज़ीरा, चेतावनी देने वाली", "ps": "نذیره، وېروونکې", "ar": "النَّذِيرَة، الْمُنْذِرَة"},
    "nazeh": {"en": "Nazeh; honest, virtuous", "ur": "نزیہ، نیک، پارسا", "fa": "نزیه، پاکدامن", "hi": "नज़ीह, नेक", "ps": "نزیه، نیک", "ar": "النَّزِيه، الْعَفِيف"},
    "nazer": {"en": "Nazer; observer, overseer", "ur": "ناظر، نگران", "fa": "ناظر، بیننده", "hi": "नाज़िर, निरीक्षक", "ps": "ناظر، کتونکی", "ar": "النَّاظِر، الْمُرَاقِب"},
    "nazgul": {"en": "Nazgul; a Turkish/Kazakh female given name", "ur": "نازگل (ترک نام)", "fa": "نازگل (نام ترکی)", "hi": "नाज़गुल (तुर्की नाम)", "ps": "نازګل (ترکي نوم)", "ar": "نَازْگُل (اسْم عَلَم تُرْكِيّ)"},
    "excursion": {"en": "Excursion, outing, promenade", "ur": "نزہہ، سیر، تفریح", "fa": "نزهه، گردش", "hi": "नुज़हा, सैर", "ps": "نزهه، سیر", "ar": "النُّزْهَة، التَّنَزُّه"},
    "nazhan": {"en": "Nazhan; a female given name", "ur": "نظحان (زنانہ نام)", "fa": "نظحان (نام زنانه)", "hi": "नज़हान (स्त्री नाम)", "ps": "نظحان (ښځينه نوم)", "ar": "نَظْحَان (اسْم عَلَم مُؤَنَّث)"},
    "nazia": {"en": "Nazia; pride, glory", "ur": "نازیہ، ناز، فخر", "fa": "نازیه، ناز", "hi": "नाज़िया, गर्व", "ps": "نازیه، ویاړ", "ar": "نَازِيَة، الْفَخْر"},
    "nazifa": {"en": "Nazifa; clean, pure (feminine)", "ur": "نظیفہ، صاف، پاک (مؤنث)", "fa": "نظیفه، پاک", "hi": "नज़ीफ़ा, साफ़ (स्त्री)", "ps": "نظیفه، پاکه", "ar": "النَّظِيفَة، الطَّاهِرَة"},
    "nazih": {"en": "Nazih; honest, virtuous", "ur": "نزیہ، نیک، پارسا", "fa": "نزیه، پاکدامن", "hi": "नज़ीह, नेक", "ps": "نزیه، نیک", "ar": "النَّزِيه، الْعَفِيف"},
    "nazila": {"en": "Nazila; guest; revelation", "ur": "نزیلہ، مہمان؛ نزول", "fa": "نزیله، مهمان", "hi": "नज़ीला, अतिथि", "ps": "نزیله، مېلمه", "ar": "النَّزِيلَة، الضَّيْف"},
    "organizer": {"en": "Organizer, administrator, arranger", "ur": "ناظم، منتظم، ناظمِ امور", "fa": "ناظم، سازمان‌دهنده", "hi": "नाज़िम, प्रबंधक", "ps": "ناظم، تنظیم کوونکی", "ar": "النَّاظِم، الْمُدِير"},
    "nazima": {"en": "Nazima; organizer (feminine)", "ur": "ناظمہ، منتظمہ", "fa": "ناظمه، سازمان‌دهنده", "hi": "नाज़िमा, प्रबंधिका", "ps": "ناظمه، تنظیم کوونکې", "ar": "النَّاظِمَة، الْمُدِيرَة"},
    "nazimah": {"en": "Nazimah; organizer (feminine)", "ur": "نظیمہ، منتظمہ", "fa": "نظیمه، سازمان‌دهنده", "hi": "नज़ीमा, प्रबंधिका", "ps": "نظیمه، تنظیم کوونکې", "ar": "النَّظِيمَة، الْمُنَظِّمَة"},
    "nazir": {"en": "Nazir; warner; observer", "ur": "نذیر/ناظر، خبردار کرنے والا", "fa": "نذیر/ناظر، هشداردهنده", "hi": "नज़ीर, चेतावनी देने वाला", "ps": "نذیر، وېروونکی", "ar": "النَّذِير، الْمُنْذِر"},
    "nazira": {"en": "Nazira; warner (feminine)", "ur": "نذیرہ، خبردار کرنے والی", "fa": "نذیره، هشداردهنده", "hi": "नज़ीरा, चेतावनी देने वाली", "ps": "نذیره، وېروونکې", "ar": "النَّذِيرَة، الْمُنْذِرَة"},
    "counterpart": {"en": "Counterpart, equal, match", "ur": "نظیرہ، ہمسر، برابر", "fa": "نظیره، همانند", "hi": "नज़ीरा, समान", "ps": "نظیره، سیال", "ar": "النَّظِيرَة، الْمِثْل"},
    "nazish": {"en": "Nazish; pride, glory", "ur": "نازش، فخر، ناز", "fa": "نازش، فخر", "hi": "नाज़िश, गर्व", "ps": "نازش، ویاړ", "ar": "النَّازِش (الْفَخْر)"},
    "nazli": {"en": "Nazli; coy, delicate (Turkish)", "ur": "نازلی، نازک، شرمیلی", "fa": "نازلی، نازک", "hi": "नाज़ली, नाज़ुक", "ps": "نازلي، نازک", "ar": "نَازْلِي (اسْم عَلَم تُرْكِيّ)"},
    "nazma": {"en": "Nazma; organizer (feminine)", "ur": "ناظمہ، منتظمہ", "fa": "ناظمه، سازمان‌دهنده", "hi": "नाज़मा, प्रबंधिका", "ps": "ناظمه، تنظیم کوونکې", "ar": "النَّاظِمَة، الْمُدِيرَة"},
    "nazmi": {"en": "Nazmi; of order, of verse", "ur": "نظمی، نظم سے منسوب", "fa": "نظمی، منسوب به نظم", "hi": "नज़मी, काव्य से संबंधित", "ps": "نظمي، د نظم اړوند", "ar": "النَّظْمِي، مَنْسُوب إِلَى النَّظْم"},
    "nazmin": {"en": "Nazmin; a female given name", "ur": "ناظمین (زنانہ نام)", "fa": "ناظمین (نام زنانه)", "hi": "नाज़मीन (स्त्री नाम)", "ps": "ناظمین (ښځينه نوم)", "ar": "نَاظْمِين (اسْم عَلَم مُؤَنَّث)"},
    "nazneen": {"en": "Nazneen; beloved, sweetheart", "ur": "نازنین، پیاری، محبوبہ", "fa": "نازنین، دلبر", "hi": "नाज़नीन, प्यारी", "ps": "نازنین، ګرانه", "ar": "النَّازَنِين (الْحَبِيبَة)"},
    "naznin": {"en": "Naznin; beloved, sweetheart", "ur": "نازنین، پیاری", "fa": "نازنین، دلبر", "hi": "नाज़नीन, प्यारी", "ps": "نازنین، ګرانه", "ar": "النَّازَنِين (الْحَبِيبَة)"},
    "nazrin": {"en": "Nazrin; a female given name", "ur": "نازرین (زنانہ نام)", "fa": "نازرین (نام زنانه)", "hi": "नाज़रीन (स्त्री नाम)", "ps": "نازرین (ښځينه نوم)", "ar": "نَازْرِين (اسْم عَلَم مُؤَنَّث)"},
    "vow": {"en": "Vow, pledge, promise", "ur": "نذر، عہد، وعدہ", "fa": "نذر، پیمان", "hi": "नज़्र, प्रतिज्ञा", "ps": "نذر، ژمنه", "ar": "النَّذْر، الْعَهْد"},
    "nazy": {"en": "Nazy; a female given name", "ur": "نازی (زنانہ نام)", "fa": "نازی (نام زنانه)", "hi": "नाज़ी (स्त्री नाम)", "ps": "نازي (ښځينه نوم)", "ar": "نَازِي (اسْم عَلَم مُؤَنَّث)"},
    "neba": {"en": "Neba; a female given name", "ur": "نبہ (زنانہ نام)", "fa": "نبه (نام زنانه)", "hi": "नेबा (स्त्री नाम)", "ps": "نبه (ښځينه نوم)", "ar": "نَبَة (اسْم عَلَم مُؤَنَّث)"},
    "star_f2": {"en": "Star (feminine)", "ur": "نجمہ، ستارہ", "fa": "نجمه، ستاره", "hi": "नजमा, तारा", "ps": "نجمه، ستوری", "ar": "النَّجْمَة، الْكَوْكَب"},
    "neeka": {"en": "Neeka; good, beautiful (Persian)", "ur": "نیکا، اچھی، خوبصورت", "fa": "نیکا، خوب", "hi": "नीका, अच्छी", "ps": "نیکا، ښه", "ar": "نِيكَا (اسْم عَلَم فَارِسِيّ)"},
    "indigo": {"en": "Indigo; water lily", "ur": "نیلہ، نیل؛ کنول", "fa": "نیله، نیل", "hi": "नीला, नील", "ps": "نیله، نیل", "ar": "النِّيلَة، النِّيلُوفَر"},
    "sapphire": {"en": "Sapphire, blue gem", "ur": "نیلم، نیلے رنگ کا نگ", "fa": "نیلم، یاقوت کبود", "hi": "नीलम, नीलमणि", "ps": "نیلم، نیلي ګاڼه", "ar": "النِّيلَم (الْيَاقُوت الْأَزْرَق)"},
    "neelu": {"en": "Neelu; blue (Hindi)", "ur": "نیلو، نیلا", "fa": "نیلو، آبی", "hi": "नीलू, नीला", "ps": "نیلو، نیلي", "ar": "نِيلُو (اسْم عَلَم هِنْدِيّ)"},
    "blessings": {"en": "Blessings, favours (plural)", "ur": "نعمات، نعمتیں", "fa": "نعمات، نعمت‌ها", "hi": "निअमात, नेमतें", "ps": "نعمات، نعمتونه", "ar": "النِّعْمَات"},
    "neeya": {"en": "Neeya; a female given name", "ur": "نیہ (زنانہ نام)", "fa": "نیه (نام زنانه)", "hi": "नीया (स्त्री नाम)", "ps": "نیه (ښځينه نوم)", "ar": "نِيَة (اسْم عَلَم مُؤَنَّث)"},
    "negar": {"en": "Negar; beloved, picture (Persian)", "ur": "نگار، محبوبہ، تصویر", "fa": "نگار، دلبر، تصویر", "hi": "नेगार, प्यारी", "ps": "نګار، ګرانه", "ar": "نِگَار (اسْم عَلَم فَارِسِيّ)"},
    "nehad": {"en": "Nehad; high ground", "ur": "نہد، بلند زمین", "fa": "نهد، زمین بلند", "hi": "नेहद, ऊँची भूमि", "ps": "نهد، لوړه ځمکه", "ar": "النَّهْد، الْأَرْض الْمُرْتَفِعَة"},
    "nehan": {"en": "Nehan; a female given name", "ur": "نیہان (زنانہ نام)", "fa": "نیهان (نام زنانه)", "hi": "नेहान (स्त्री नाम)", "ps": "نیهان (ښځينه نوم)", "ar": "نِيهَان (اسْم عَلَم مُؤَنَّث)"},
    "daytime": {"en": "Daytime, day", "ur": "نہار، دن", "fa": "نهار، روز", "hi": "नेहार, दिन", "ps": "نهار، ورځ", "ar": "النَّهَار"},
    "nehat": {"en": "Nehat; a male given name", "ur": "نہات (مردانہ نام)", "fa": "نهات (نام مردانه)", "hi": "नेहात (पुरुष नाम)", "ps": "نهات (نر نوم)", "ar": "نَهَات (اسْم عَلَم مُذَكَّر)"},
    "nehla": {"en": "Nehla; a drink, a draught", "ur": "نہلہ، گھونٹ، مشروب", "fa": "نهله، جرعه", "hi": "नेहला, घूँट", "ps": "نهله، څښاک", "ar": "النَّهْلَة، الشَّرْبَة"},
    "nehrin": {"en": "Nehrin; of the river", "ur": "نہرین، نہر سے منسوب", "fa": "نهرین، منسوب به رود", "hi": "नेहरीन, नदी से संबंधित", "ps": "نهرین، د سیند اړوند", "ar": "نَهْرِين، مَنْسُوب إِلَى النَّهْر"},
    "blessing": {"en": "Blessing, favour, grace", "ur": "نعمت، رحمت، بخشش", "fa": "نعمت، بخشش", "hi": "नेमत, आशीर्वाद", "ps": "نعمت، بخښنه", "ar": "النِّعْمَة، الرَّحْمَة"},
    "salvation": {"en": "Salvation, safety, deliverance", "ur": "نجات، سلامتی، چھٹکارا", "fa": "نجات، رهایی", "hi": "नजात, मुक्ति", "ps": "نجات، خلاصون", "ar": "النَّجَاة، الْخَلَاص"},
    "noble_excellent": {"en": "Noble, excellent, generous", "ur": "نجیب، شریف، عالی", "fa": "نجیب، شریف", "hi": "नजीब, कुलीन", "ps": "نجیب، شریف", "ar": "النَّجِيب، الشَّرِيف"},
    "wide_eyed2": {"en": "Wide-eyed, large-eyed (of a gazelle)", "ur": "نجلاء، کشادہ آنکھوں والی", "fa": "نجلاء، فراخ‌چشم", "hi": "नजला, चौड़ी आँखों वाली", "ps": "نجلاء، پراخې سترګې", "ar": "النَّجْلَاء، وَاسِعَة الْعَيْن"},
    "nelam": {"en": "Nelam; a female given name", "ur": "نیلم (زنانہ نام)", "fa": "نیلم (نام زنانه)", "hi": "नेलम (स्त्री नाम)", "ps": "نیلم (ښځينه نوم)", "ar": "نِيلَم (اسْم عَلَم مُؤَنَّث)"},
    "water_lily": {"en": "Water lily, lotus", "ur": "نیلوفر، کنول", "fa": "نیلوفر، نیلوفر آبی", "hi": "नीलोफ़र, कमल", "ps": "نیلوفر، نيلوفر", "ar": "النِّيلُوفَر"},
    "nemat": {"en": "Nemat; blessing, favour", "ur": "نعمت، رحمت", "fa": "نعمت، بخشش", "hi": "नेमत, आशीर्वाद", "ps": "نعمت، بخښنه", "ar": "النِّعْمَة، الرَّحْمَة"},
    "nen": {"en": "Nen; a female given name", "ur": "نین (زنانہ نام)", "fa": "نن (نام زنانه)", "hi": "नेन (स्त्री नाम)", "ps": "نن (ښځينه نوم)", "ar": "نِن (اسْم عَلَم مُؤَنَّث)"},
    "joy_happiness": {"en": "Joy, happiness, liveliness", "ur": "نشاط، خوشی، شادمانی", "fa": "نشاط، شادی", "hi": "नशात, खुशी", "ps": "نشاط، خوښي", "ar": "النَّشَاط، الْفَرَح"},
    "nesma": {"en": "Nesma; a breeze, a breath", "ur": "نسمہ، ہلکی ہوا", "fa": "نسمه، نسیم", "hi": "नसमा, हल्की हवा", "ps": "نسمه، نرمه باد", "ar": "النَّسْمَة، النَّسِيم"},
    "wild_rose": {"en": "Wild rose, narcissus", "ur": "نسرین، جنگلی گلاب", "fa": "نسرین، گل نرگس", "hi": "नसरीन, जंगली गुलाब", "ps": "نسرین، وحشي ګلاب", "ar": "النِّسْرِين"},
    "nevaeh": {"en": "Nevaeh; an English given name", "ur": "نیوایہ (انگریزی نام)", "fa": "نوایه (نام انگلیسی)", "hi": "नेवेया (अंग्रेज़ी नाम)", "ps": "نیوایه (انګلیسي نوم)", "ar": "نِيفَايَة (اسْم عَلَم إِنْجِلِيزِيّ)"},
    "neveen": {"en": "Neveen; beautiful, fair", "ur": "نیوین، خوبصورت", "fa": "نیوین، زیبا", "hi": "नेवीन, सुंदर", "ps": "نیوین، ښکلی", "ar": "نِيفِين، الْجَمِيلَة"},
})

CUR = {
 "navil": ("نَوِيل", "نویل", "نویل", "नवील", "نویل", "naveel", "Arabic", "Male",
           "Arabic نَوِيل (Nawīl)", False, "medium",
           "Navil is recorded as Arabic نَوِيل (Nawīl), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Navil' instead of a script form and labelled the gender unisex. The source gloss 'Journey, voyage, sea' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nawaab": ("نُوَّاب", "نواب", "نواب", "नव्वाब", "نواب", "deputy", "Arabic", "Male",
            "Arabic root ن و ب (n-w-b); نُوَّاب (Nuwwāb)", False, "high",
            "Nawaab is Arabic نُوَّاب (Nuwwāb) 'deputies, lords', the plural of نَائِب (nāʾib), from the root ن و ب (n-w-b). The source gloss 'Lord, Master' is broadly consistent. Same name as nawab."),
 "nawaal": ("نَوَال", "نوال", "نوال", "नवाल", "نوال", "gift_bestowal", "Arabic", "Female",
            "Arabic root ن و ل (n-w-l); نَوَال (Nawāl)", False, "high",
            "Nawaal is Arabic نَوَال (Nawāl) 'gift, bestowal, bounty', from the root ن و ل (n-w-l). The source gloss 'Gentle Breeze' is unsupported and has been replaced with the lexical sense. Same name as nawal."),
 "nawaaz": ("نَوَاز", "نواز", "نواز", "नवाज़", "نواز", "cherishing", "Persian", "Male",
            "Persian نواز (nawāz), a cherishing suffix", False, "high",
            "Nawaaz is Persian نواز (nawāz), a suffix meaning 'cherishing, caressing'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the element is Persian. The source gloss 'Restless' is unsupported and has been replaced with the lexical sense. Same name as nawaz."),
 "nawab": ("نُوَّاب", "نواب", "نواب", "नवाब", "نواب", "deputy", "Arabic", "Male",
           "Arabic root ن و ب (n-w-b); نُوَّاب (Nuwwāb)", False, "high",
           "Nawab is Arabic نُوَّاب (Nuwwāb) 'deputies, lords', the plural of نَائِب (nāʾib), from the root ن و ب (n-w-b). The source gloss 'Prince, Ruler' is broadly consistent. Same name as nawaab."),
 "nawaf": ("نَوَّاف", "نواف", "نواف", "नव्वाफ़", "نواف", "nawwaf", "Arabic", "Male",
           "Arabic نَوَّاف (Nawwāf)", False, "high",
           "Nawaf is Arabic نَوَّاف (Nawwāf), a male given name. CRITICAL SOURCE ERROR: the source gave نوف (a different form); the correct form is نَوَّاف. The source gloss 'Rest' is unsupported; no confident lexical sense is asserted. Same name as nawwaf."),
 "nawal": ("نَوَال", "نوال", "نوال", "नवाल", "نوال", "gift_bestowal", "Arabic", "Female",
           "Arabic root ن و ل (n-w-l); نَوَال (Nawāl)", False, "high",
           "Nawal is Arabic نَوَال (Nawāl) 'gift, bestowal, bounty', from the root ن و ل (n-w-l). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nawaal."),
 "nawar": ("نَوَّار", "نوار", "نوار", "नव्वार", "نوار", "blossoming", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نَوَّار (Nawwār)", False, "high",
           "Nawar is Arabic نَوَّار (Nawwār) 'blossoming, radiant', from the root ن و ر (n-w-r). The source gloss 'Blooming Flower' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "nawaz": ("نَوَاز", "نواز", "نواز", "नवाज़", "نواز", "cherishing", "Persian", "Male",
           "Persian نواز (nawāz), a cherishing suffix", False, "high",
           "Nawaz is Persian نواز (nawāz), a suffix meaning 'cherishing, caressing'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the element is Persian. The source gloss 'Intelligent, Wise' is unsupported and has been replaced with the lexical sense. Same name as nawaaz."),
 "nawazish": ("نَوَازِش", "نوازش", "نوازش", "नवाज़िश", "نوازش", "kindness", "Persian", "Male",
              "Persian نوازش (nawāzish)", False, "high",
              "Nawazish is Persian نوازش (nawāzish) 'kindness, favour, caress'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Gifted, Generous' is broadly consistent."),
 "naweed": ("نَوِيد", "نوید", "نوید", "नवीद", "نوید", "good_news", "Persian", "Male",
            "Persian نوید (navīd)", False, "high",
            "Naweed is Persian نوید (navīd) 'good news, glad tidings'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nawwab' (a different name) and labelled the origin Arabic; the name is Persian. The source gloss 'Comforter' is unsupported and has been replaced with the lexical sense. Same name as naveed."),
 "nawel": ("نَوَال", "نوال", "نوال", "नवाल", "نوال", "gift_bestowal", "Arabic", "Female",
           "Arabic root ن و ل (n-w-l); نَوَال (Nawāl)", False, "high",
           "Nawel is a spelling variant of Arabic نَوَال (Nawāl) 'gift, bestowal', from the root ن و ل (n-w-l). The source gloss 'Moon' is unsupported and has been replaced with the lexical sense. Same name as nawal."),
 "nawfal": ("نَوْفَل", "نوفل", "نوفل", "नौफ़ल", "نوفل", "nawfal", "Arabic", "Male",
            "Arabic نَوْفَل (Nawfal)", False, "high",
            "Nawfal is Arabic نَوْفَل (Nawfal), a male given name borne by a companion of the Prophet. The source gloss 'Successful Trader' is unsupported and has been replaced with the documented identification. Same name as naufal."),
 "nawra": ("نَوْرَة", "نورہ", "نوره", "नौरा", "نوره", "blossom_light", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نَوْرَة (Nawra)", False, "high",
           "Nawra is Arabic نَوْرَة (Nawra) 'blossom, light, radiance', from the root ن و ر (n-w-r). The source gloss 'morning, freshness' is broadly consistent."),
 "nawraa": ("نَوْرَاء", "نوراء", "نوراء", "नौरा", "نوراء", "nawraa", "Arabic", "Female",
            "Arabic نَوْرَاء (Nawrāʾ)", False, "medium",
            "Nawraa is recorded as Arabic نَوْرَاء (Nawrāʾ), a female given name. CRITICAL SOURCE ERROR: the source gave نورا (a non-standard form). The source gloss 'Gentle Breeze' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nawras": ("نَوْرَس", "نورس", "نورس", "नौरस", "نورس", "seagull", "Arabic", "Male",
            "Arabic root ن ر س (n-r-s); نَوْرَس (Nawras)", False, "high",
            "Nawras is Arabic نَوْرَس (Nawras) 'seagull; a young man', from the root ن ر س (n-r-s). The source gloss 'Delight, Joy, Pleasure' is unsupported and has been replaced with the lexical sense."),
 "nawroz": ("نَوْرُوز", "نوروز", "نوروز", "नौरोज़", "نوروز", "nowruz", "Persian", "Male",
            "Persian نوروز (nowrūz)", False, "high",
            "Nawroz is Persian نوروز (nowrūz) 'new day; the Persian New Year'. CRITICAL SOURCE ERROR: the source gave زائنب (a different name) and labelled the origin Arabic; the word is Persian. The source gloss 'New Day' is consistent."),
 "nawshad": ("نَوْشَاد", "نوشاد", "نوشاد", "नौशाद", "نوشاد", "naushad2", "Persian", "Male",
             "Persian نوشاد (naushād)", False, "high",
             "Nawshad is Persian نوشاد (naushād) 'happy, joyful'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Light of guidance' is unsupported and has been replaced with the lexical sense. Same name as naushad."),
 "nawshin": ("نَوْشِين", "نوشین", "نوشین", "नौशीन", "نوشین", "nausheen2", "Persian", "Female",
             "Persian نوشین (naushīn)", False, "high",
             "Nawshin is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Friend of the Intelligent' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as nausheen."),
 "nawwaf": ("نَوَّاف", "نواف", "نواف", "नव्वाफ़", "نواف", "nawwaf", "Arabic", "Male",
            "Arabic نَوَّاف (Nawwāf)", False, "high",
            "Nawwaf is Arabic نَوَّاف (Nawwāf), a male given name. CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is نَوَّاف. The source gloss 'Determined, Steadfast' is unsupported; no confident lexical sense is asserted. Same name as nawaf."),
 "nawwar": ("نَوَّار", "نوار", "نوار", "नव्वार", "نوار", "blossoming", "Arabic", "Female",
            "Arabic root ن و ر (n-w-r); نَوَّار (Nawwār)", False, "high",
            "Nawwar is Arabic نَوَّار (Nawwār) 'blossoming, radiant', from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nawar."),
 "nawzad": ("نَوْزَاد", "نوزاد", "نوزاد", "नौज़ाद", "نوزاد", "newborn", "Persian", "Male",
            "Persian نوزاد (nowzād)", False, "high",
            "Nawzad is Persian نوزاد (nowzād) 'newborn'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Restorer, Reviver' is unsupported and has been replaced with the lexical sense."),
 "nay": ("نَاي", "ناي", "نای", "नाय", "ناي", "reed_flute", "Arabic", "Female",
         "Arabic root ن و ي (n-w-y); نَاي (Nāy)", False, "high",
         "Nay is Arabic نَاي (Nāy) 'reed flute', from the root ن و ي (n-w-y). The source gloss 'Delight, Pleasure' is unsupported and has been replaced with the lexical sense."),
 "nayab": ("نَايَاب", "نایاب", "نایاب", "नायाब", "نایاب", "rare_precious", "Persian", "Female",
           "Persian نایاب (nāyāb)", False, "high",
           "Nayab is Persian نایاب (nāyāb) 'rare, precious, unique'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Precious, Rare, Unique' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "nayef": ("نَايِف", "نایف", "نایف", "नायफ़", "نایف", "nayef", "Arabic", "Male",
           "Arabic root ن ي ف (n-y-f); نَايِف (Nāyif)", False, "high",
           "Nayef is Arabic نَايِف (Nāyif) 'high, elevated', from the root ن ي ف (n-y-f). The source gloss 'Gracious, generous' is unsupported and has been replaced with the lexical sense. Same name as nayif."),
 "nayel": ("نَايِل", "نائل", "نائل", "नाइल", "نائل", "nayel", "Arabic", "Male",
           "Arabic root ن ي ل (n-y-l); نَايِل (Nāyil)", False, "high",
           "Nayel is Arabic نَايِل (Nāyil) 'obtainer, acquirer', from the root ن ي ل (n-y-l). The source gloss 'Radiant, bright, shining light' is unsupported and has been replaced with the lexical sense."),
 "nayem": ("نَائِم", "نائم", "نائم", "नाइम", "نائم", "sleeping", "Arabic", "Male",
           "Arabic root ن و م (n-w-m); نَائِم (Nāʾim)", False, "high",
           "Nayem is Arabic نَائِم (Nāʾim) 'sleeping, resting', from the root ن و م (n-w-m). The source gloss 'Sleeping, resting' is consistent."),
 "nayif": ("نَايِف", "نایف", "نایف", "नायफ़", "نایف", "nayef", "Arabic", "Male",
           "Arabic root ن ي ف (n-y-f); نَايِف (Nāyif)", False, "high",
           "Nayif is Arabic نَايِف (Nāyif) 'high, elevated', from the root ن ي ف (n-y-f). The source gloss 'Delightful, pleasant' is unsupported and has been replaced with the lexical sense. Same name as nayef."),
 "nayla": ("نَايِلَة", "نائلہ", "نائله", "नाइला", "نائله", "nayla", "Arabic", "Female",
           "Arabic root ن ي ل (n-y-l); نَايِلَة (Nāyila)", False, "high",
           "Nayla is Arabic نَايِلَة (Nāyila) 'obtainer' (feminine), from the root ن ي ل (n-y-l). The source gloss 'Night, Night Journey' is unsupported and has been replaced with the lexical sense."),
 "nayyar": ("نَيَّار", "نیار", "نیار", "नय्यार", "نیار", "nayyar", "Arabic", "Male",
            "Arabic نَيَّار (Nayyār)", False, "medium",
            "Nayyar is recorded as Arabic نَيَّار (Nayyār) 'luminous, brilliant', a male given name. The source gloss 'Guiding' is unsupported and has been replaced with the lexical sense. The identification is recorded at medium confidence."),
 "naz": ("نَاز", "ناز", "ناز", "नाज़", "ناز", "coquetry", "Persian", "Female",
         "Persian ناز (nāz)", False, "high",
         "Naz is Persian ناز (nāz) 'coquetry, pride, charm'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Gazelle' is unsupported and has been replaced with the lexical sense."),
 "naza": ("نَازَة", "نازہ", "نازه", "नाज़ा", "نازه", "naza", "Persian", "Female",
          "Persian ناز (nāz) + feminine ending", False, "medium",
          "Naza is recorded as a Persian female given name derived from ناز (nāz) 'coquetry, charm'. CRITICAL SOURCE ERROR: the source gave نَزَا (a non-standard form) and labelled the origin Arabic; the name is Persian. The source gloss 'Gazelle' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nazakat": ("نَزَاكَت", "نزاکت", "نزاکت", "नज़ाकत", "نزاکت", "delicacy", "Urdu", "Female",
             "Urdu نزاکت (nazākat), from Arabic نَزَاهَة", False, "high",
             "Nazakat is Urdu نزاکت (nazākat) 'delicacy, refinement, subtlety'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Urdu. The source gloss 'Purity and delicacy' is broadly consistent."),
 "nazanin": ("نَازَنِين", "نازنین", "نازنین", "नाज़नीन", "نازنین", "beloved_sweet", "Persian", "Female",
             "Persian نازنین (nāzanīn)", False, "high",
             "Nazanin is Persian نازنین (nāzanīn) 'beloved, sweetheart, darling'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Joyful, Delightful' is unsupported and has been replaced with the lexical sense."),
 "nazar": ("نَاظِر", "ناظر", "ناظر", "नाज़िर", "ناظر", "observer", "Arabic", "Male",
           "Arabic root ن ظ ر (n-ẓ-r); نَاظِر (Nāẓir)", False, "high",
           "Nazar is Arabic نَاظِر (Nāẓir) 'observer, overseer, spectator', from the root ن ظ ر (n-ẓ-r). The source gloss 'Observation' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nazeef": ("نَظِيف", "نظیف", "نظیف", "नज़ीफ़", "نظیف", "clean_pure", "Arabic", "Male",
            "Arabic root ن ظ ف (n-ẓ-f); نَظِيف (Naẓīf)", False, "high",
            "Nazeef is Arabic نَظِيف (Naẓīf) 'clean, pure, spotless', from the root ن ظ ف (n-ẓ-f). CRITICAL SOURCE ERROR: the source gave نزيف (a different form); the correct form is نَظِيف. The source gloss 'Gifted, Generous' is unsupported and has been replaced with the lexical sense. Same name as nazif."),
 "nazeeh": ("نَزِيه", "نزیہ", "نزیه", "नज़ीह", "نزیه", "honest_virtuous", "Arabic", "Male",
            "Arabic root ن ز ه (n-z-h); نَزِيه (Nazīh)", False, "high",
            "Nazeeh is Arabic نَزِيه (Nazīh) 'honest, virtuous, upright', from the root ن ز ه (n-z-h). CRITICAL SOURCE ERROR: the source gave نظيف (a different form); the correct form is نَزِيه. The source gloss 'Adviser, Warning, Reminder' is unsupported and has been replaced with the lexical sense. Same name as nazih."),
 "nazeeha": ("نَزِيهَة", "نزیہہ", "نزیهه", "नज़ीहा", "نزیهه", "honest_virtuous_f", "Arabic", "Female",
             "Arabic root ن ز ه (n-z-h); نَزِيهَة (Nazīha)", False, "high",
             "Nazeeha is Arabic نَزِيهَة (Nazīha) 'honest, virtuous' (feminine), from the root ن ز ه (n-z-h). The source gloss 'Counsel, advice' is unsupported and has been replaced with the lexical sense. Same name as naziha."),
 "nazeem": ("نَظِيم", "نظیم", "نظیم", "नज़ीम", "نظیم", "nazeem", "Arabic", "Male",
            "Arabic root ن ظ م (n-ẓ-m); نَظِيم (Naẓīm)", False, "high",
            "Nazeem is Arabic نَظِيم (Naẓīm) 'organizer, arranger', from the root ن ظ م (n-ẓ-m). CRITICAL SOURCE ERROR: the source gave نَذِمَ (a different form); the correct form is نَظِيم. The source gloss 'Gentle Breeze' is unsupported and has been replaced with the lexical sense."),
 "nazeer": ("نَذِير", "نذیر", "نذیر", "नज़ीर", "نذیر", "warner", "Arabic", "Male",
            "Arabic root ن ذ ر (n-dh-r); نَذِير (Nadhīr)", False, "high",
            "Nazeer is Arabic نَذِير (Nadhīr) 'warner, one who warns', from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave ناظر (a different form); the correct form is نَذِير. The source gloss 'Observer, Seer' is unsupported and has been replaced with the lexical sense. Same name as nadheer."),
 "nazeera": ("نَذِيرَة", "نذیرہ", "نذیره", "नज़ीरा", "نذیره", "warner_f", "Arabic", "Female",
             "Arabic root ن ذ ر (n-dh-r); نَذِيرَة (Nadhīra)", False, "high",
             "Nazeera is Arabic نَذِيرَة (Nadhīra) 'warner' (feminine), from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave the broken string 'نazeera' (a Latin-Arabic mix); the correct form is نَذِيرَة. The source gloss 'Warner, One who reminds' is consistent."),
 "nazeerah": ("نَذِيرَة", "نذیرہ", "نذیره", "नज़ीरा", "نذیره", "warner_f", "Arabic", "Female",
              "Arabic root ن ذ ر (n-dh-r); نَذِيرَة (Nadhīra)", False, "high",
              "Nazeerah is Arabic نَذِيرَة (Nadhīra) 'warner' (feminine), from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave نظرة (a different form); the correct form is نَذِيرَة. The source gloss 'Inspector, observer' is unsupported and has been replaced with the lexical sense. Same name as nazeera."),
 "nazeh": ("نَزِيه", "نزیہ", "نزیه", "नज़ीह", "نزیه", "nazeh", "Arabic", "Female",
           "Arabic root ن ز ه (n-z-h); نَزِيه (Nazīh)", False, "high",
           "Nazeh is Arabic نَزِيه (Nazīh) 'honest, virtuous', from the root ن ز ه (n-z-h). CRITICAL SOURCE ERROR: the source gave ناظه (a non-standard form). The source gloss 'Watchful, attentive, careful' is unsupported and has been replaced with the lexical sense. Same name as nazih."),
 "nazer": ("نَاظِر", "ناظر", "ناظر", "नाज़िर", "ناظر", "nazer", "Arabic", "Male",
           "Arabic root ن ظ ر (n-ẓ-r); نَاظِر (Nāẓir)", False, "high",
           "Nazer is a spelling variant of Arabic نَاظِر (Nāẓir) 'observer, overseer', from the root ن ظ ر (n-ẓ-r). The source gloss 'Noble or Exalted' is unsupported and has been replaced with the lexical sense. Same name as nazar."),
 "nazgul": ("نَازْگُل", "نازگل", "نازگل", "नाज़गुल", "نازګل", "nazgul", "Turkish", "Female",
            "Turkish/Kazakh Nazgül, from Persian ناز + گل", False, "high",
            "Nazgul is a Turkish/Kazakh female given name (Nazgül), from Persian ناز (nāz) 'coquetry' + گل (gul) 'flower'. CRITICAL SOURCE ERROR: the source gave أحمد (a different name) and labelled the origin Arabic; the name is Turkish. The source gloss 'Noble, Radiant, Victorious' is unsupported and has been replaced with the documented identification."),
 "nazha": ("نُزْهَة", "نزہہ", "نزهه", "नुज़हा", "نزهه", "excursion", "Arabic", "Female",
           "Arabic root ن ز ه (n-z-h); نُزْهَة (Nuzha)", False, "high",
           "Nazha is Arabic نُزْهَة (Nuzha) 'excursion, outing, promenade', from the root ن ز ه (n-z-h). The source gloss 'Help' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "nazhan": ("نَظْحَان", "نظحان", "نظحان", "नज़हान", "نظحان", "nazhan", "Arabic", "Female",
            "Arabic نَظْحَان (Naẓḥān)", False, "medium",
            "Nazhan is recorded as Arabic نَظْحَان (Naẓḥān), a female given name. The source gloss 'Fresh, New' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nazia": ("نَازِيَة", "نازیہ", "نازیه", "नाज़िया", "نازیه", "nazia", "Urdu", "Female",
           "Urdu نازیہ (nāziya), from Persian ناز", False, "high",
           "Nazia is Urdu نازیہ (nāziya) 'pride, glory', from Persian ناز (nāz). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Urdu. The source gloss 'Pride, glory' is consistent. Same name as naziah."),
 "naziah": ("نَازِيَة", "نازیہ", "نازیه", "नाज़िया", "نازیه", "nazia", "Urdu", "Female",
            "Urdu نازیہ (nāziya), from Persian ناز", False, "high",
            "Naziah is Urdu نازیہ (nāziya) 'pride, glory', from Persian ناز (nāz). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Urdu. The source gloss 'Graceful' is broadly consistent. Same name as nazia."),
 "nazif": ("نَظِيف", "نظیف", "نظیف", "नज़ीफ़", "نظیف", "clean_pure", "Arabic", "Male",
           "Arabic root ن ظ ف (n-ẓ-f); نَظِيف (Naẓīf)", False, "high",
           "Nazif is Arabic نَظِيف (Naẓīf) 'clean, pure, spotless', from the root ن ظ ف (n-ẓ-f). The source gloss 'Pure, clean' is consistent. Same name as nazeef."),
 "nazifa": ("نَظِيفَة", "نظیفہ", "نظیفه", "नज़ीफ़ा", "نظیفه", "nazifa", "Arabic", "Female",
            "Arabic root ن ظ ف (n-ẓ-f); نَظِيفَة (Naẓīfa)", False, "high",
            "Nazifa is Arabic نَظِيفَة (Naẓīfa) 'clean, pure' (feminine), from the root ن ظ ف (n-ẓ-f). CRITICAL SOURCE ERROR: the source gave نازفة (a different form); the correct form is نَظِيفَة. The source gloss 'Pure, Chaste' is broadly consistent."),
 "nazih": ("نَزِيه", "نزیہ", "نزیه", "नज़ीह", "نزیه", "nazih", "Arabic", "Male",
           "Arabic root ن ز ه (n-z-h); نَزِيه (Nazīh)", False, "high",
           "Nazih is Arabic نَزِيه (Nazīh) 'honest, virtuous, upright', from the root ن ز ه (n-z-h). The source gloss 'Intelligent, Wise, Advisor' is unsupported and has been replaced with the lexical sense. Same name as nazeeh."),
 "naziha": ("نَزِيهَة", "نزیہہ", "نزیهه", "नज़ीहा", "نزیهه", "honest_virtuous_f", "Arabic", "Female",
            "Arabic root ن ز ه (n-z-h); نَزِيهَة (Nazīha)", False, "high",
            "Naziha is Arabic نَزِيهَة (Nazīha) 'honest, virtuous' (feminine), from the root ن ز ه (n-z-h). CRITICAL SOURCE ERROR: the source gave نَازِيحَة (a non-standard form); the correct form is نَزِيهَة. The source gloss 'Graceful, Pleasing' is unsupported and has been replaced with the lexical sense. Same name as nazeeha."),
 "nazihah": ("نَزِيهَة", "نزیہہ", "نزیهه", "नज़ीहा", "نزیهه", "honest_virtuous_f", "Arabic", "Female",
             "Arabic root ن ز ه (n-z-h); نَزِيهَة (Nazīha)", False, "high",
             "Nazihah is Arabic نَزِيهَة (Nazīha) 'honest, virtuous' (feminine), from the root ن ز ه (n-z-h). The source gloss 'hidden, secret' is unsupported and has been replaced with the lexical sense. Same name as nazeeha."),
 "nazila": ("نَزِيلَة", "نزیلہ", "نزیله", "नज़ीला", "نزیله", "nazila", "Arabic", "Female",
            "Arabic root ن ز ل (n-z-l); نَزِيلَة (Nazīla)", False, "high",
            "Nazila is Arabic نَزِيلَة (Nazīla) 'guest; revelation', from the root ن ز ل (n-z-l). The source gloss 'Delight, beauty' is unsupported and has been replaced with the lexical sense."),
 "nazim": ("نَاظِم", "ناظم", "ناظم", "नाज़िम", "ناظم", "organizer", "Arabic", "Male",
           "Arabic root ن ظ م (n-ẓ-m); نَاظِم (Nāẓim)", False, "high",
           "Nazim is Arabic نَاظِم (Nāẓim) 'organizer, administrator, arranger', from the root ن ظ م (n-ẓ-m). The source gloss 'Commanding, ruling' is broadly consistent."),
 "nazima": ("نَاظِمَة", "ناظمہ", "ناظمه", "नाज़िमा", "ناظمه", "nazima", "Arabic", "Female",
            "Arabic root ن ظ م (n-ẓ-m); نَاظِمَة (Nāẓima)", False, "high",
            "Nazima is Arabic نَاظِمَة (Nāẓima) 'organizer' (feminine), from the root ن ظ م (n-ẓ-m). The source gloss 'Grace, beauty, adornment' is unsupported and has been replaced with the lexical sense."),
 "nazimah": ("نَظِيمَة", "نظیمہ", "نظیمه", "नज़ीमा", "نظیمه", "nazimah", "Arabic", "Female",
             "Arabic root ن ظ م (n-ẓ-m); نَظِيمَة (Naẓīma)", False, "high",
             "Nazimah is Arabic نَظِيمَة (Naẓīma) 'organizer' (feminine), from the root ن ظ م (n-ẓ-m). The source gloss 'Gracious, beautiful, or adorned' is unsupported and has been replaced with the lexical sense."),
 "nazir": ("نَذِير", "نذیر", "نذیر", "नज़ीर", "نذیر", "nazir", "Arabic", "Male",
           "Arabic root ن ذ ر (n-dh-r); نَذِير (Nadhīr)", False, "high",
           "Nazir is Arabic نَذِير (Nadhīr) 'warner' (also نَاظِر 'observer'), from the root ن ذ ر (n-dh-r). The source gloss 'Warner, Advisor, Observer' is broadly consistent. Same name as nazeer."),
 "nazira": ("نَذِيرَة", "نذیرہ", "نذیره", "नज़ीरा", "نذیره", "nazira", "Arabic", "Female",
            "Arabic root ن ذ ر (n-dh-r); نَذِيرَة (Nadhīra)", False, "high",
            "Nazira is Arabic نَذِيرَة (Nadhīra) 'warner' (feminine), from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave نازرة (a different form); the correct form is نَذِيرَة. The source gloss 'Bright, Radiant, One Who Sees Clearly' is unsupported and has been replaced with the lexical sense. Same name as nazeera."),
 "nazirah": ("نَظِيرَة", "نظیرہ", "نظیره", "नज़ीरा", "نظیره", "counterpart", "Arabic", "Female",
             "Arabic root ن ظ ر (n-ẓ-r); نَظِيرَة (Naẓīra)", False, "high",
             "Nazirah is Arabic نَظِيرَة (Naẓīra) 'counterpart, equal, match', from the root ن ظ ر (n-ẓ-r). The source gloss 'Watchful, Vigilant' is unsupported and has been replaced with the lexical sense."),
 "nazish": ("نَازِش", "نازش", "نازش", "नाज़िश", "نازش", "nazish", "Urdu", "Female",
            "Urdu نازش (nāzish), from Persian ناز", False, "high",
            "Nazish is Urdu نازش (nāzish) 'pride, glory', from Persian ناز (nāz). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Urdu. The source gloss 'Delight, pleasure' is broadly consistent."),
 "nazli": ("نَازْلِي", "نازلی", "نازلی", "नाज़ली", "نازلي", "nazli", "Turkish", "Female",
           "Turkish Nazlı", False, "high",
           "Nazli is Turkish Nazlı 'coy, delicate'. CRITICAL SOURCE ERROR: the source gave نَزْلِي (a non-standard form) and labelled the origin Arabic; the name is Turkish. The source gloss 'Delicate, Tender' is consistent."),
 "nazma": ("نَاظِمَة", "ناظمہ", "ناظمه", "नाज़मा", "ناظمه", "nazma", "Arabic", "Female",
           "Arabic root ن ظ م (n-ẓ-m); نَاظِمَة (Nāẓima)", False, "high",
           "Nazma is Arabic نَاظِمَة (Nāẓima) 'organizer' (feminine), from the root ن ظ م (n-ẓ-m). The source gloss 'Night sky, star' is unsupported and has been replaced with the lexical sense. Same name as nazima."),
 "nazmi": ("نَظْمِي", "نظمی", "نظمی", "नज़मी", "نظمي", "nazmi", "Arabic", "Male",
           "Arabic نَظْمِي (Naẓmī) 'of order, of verse'", False, "high",
           "Nazmi is Arabic نَظْمِي (Naẓmī) 'of order, of verse', a relational adjective from نَظْم (naẓm). The source gloss 'Graceful' is unsupported and has been replaced with the lexical sense."),
 "nazmin": ("نَاظْمِين", "ناظمین", "ناظمین", "नाज़मीन", "ناظمین", "nazmin", "Arabic", "Female",
            "Arabic نَاظْمِين (Nāẓmīn)", False, "medium",
            "Nazmin is recorded as Arabic نَاظْمِين (Nāẓmīn), a female given name. The source gloss 'Graceful, Delicate' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nazneen": ("نَازَنِين", "نازنین", "نازنین", "नाज़नीन", "نازنین", "nazneen", "Persian", "Female",
             "Persian نازنین (nāzanīn)", False, "high",
             "Nazneen is Persian نازنین (nāzanīn) 'beloved, sweetheart'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Delicate, Dainty' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as nazanin."),
 "naznin": ("نَازَنِين", "نازنین", "نازنین", "नाज़नीन", "نازنین", "naznin", "Persian", "Female",
            "Persian نازنین (nāzanīn)", False, "high",
            "Naznin is Persian نازنین (nāzanīn) 'beloved, sweetheart'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Naznin' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Graceful, adorned' is unsupported and has been replaced with the lexical sense. Same name as nazanin."),
 "nazrin": ("نَازْرِين", "نازرین", "نازرین", "नाज़रीन", "نازرین", "nazrin", "Persian", "Female",
            "Persian/Azerbaijani Nazrin", False, "medium",
            "Nazrin is a Persian/Azerbaijani female given name. CRITICAL SOURCE ERROR: the source gave 'назрин' (Cyrillic) instead of an Arabic-script form and labelled the origin Arabic. The source gloss 'A person who contemplates, reflects, pon' is truncated and unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nazrul": ("نَذْرُول", "نذرول", "نذرول", "नज़रुल", "نذرول", "vow", "Bengali", "Male",
            "Bengali নজরুল (nazrul), from Arabic نَذْر (nadhr)", False, "high",
            "Nazrul is a Bengali male given name, from Arabic نَذْر (nadhr) 'vow, pledge'. CRITICAL SOURCE ERROR: the source gave نَزْرُول (a non-standard form) and labelled the origin Arabic; the name as used is Bengali. The source gloss 'Pledge, promise' is broadly consistent."),
 "nazy": ("نَازِي", "نازی", "نازی", "नाज़ी", "نازي", "nazy", "Persian", "Female",
          "Persian نازی (nāzī)", False, "medium",
          "Nazy is a Persian female given name derived from ناز (nāz) 'coquetry, charm'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nazy' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Joyful, cheerful, happy' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "neba": ("نَبَة", "نبہ", "نبه", "नेबा", "نبه", "neba", "Arabic", "Female",
          "Arabic نَبَة (Naba)", False, "medium",
          "Neba is recorded as Arabic نَبَة (Naba), a female given name. CRITICAL SOURCE ERROR: the source gave نَبَ (a non-standard form). The source gloss 'Clouds, rain' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nedjma": ("نَجْمَة", "نجمہ", "نجمه", "नजमा", "نجمه", "star_f2", "Arabic", "Female",
            "Arabic root ن ج م (n-j-m); نَجْمَة (Najma)", False, "high",
            "Nedjma is a Maghrebi spelling of Arabic نَجْمَة (Najma) 'star', from the root ن ج م (n-j-m). The source gloss 'Star, Guiding Light' is consistent. Same name as najma."),
 "neeka": ("نِيكَا", "نیکا", "نیکا", "नीका", "نیکا", "neeka", "Persian", "Female",
           "Persian نیکا (nīkā)", False, "high",
           "Neeka is Persian نیکا (nīkā) 'good, beautiful'. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the name is Persian. The source gloss 'Gentle, Delicate, Graceful' is unsupported and has been replaced with the lexical sense."),
 "neela": ("نِيلَة", "نیلہ", "نیله", "नीला", "نیله", "indigo", "Arabic", "Female",
           "Arabic نِيلَة (Nīla)", False, "high",
           "Neela is Arabic نِيلَة (Nīla) 'indigo; water lily'. The source gloss 'Water lily' is broadly consistent."),
 "neelam": ("نِيلَم", "نیلم", "نیلم", "नीलम", "نیلم", "sapphire", "Hindi", "Female",
            "Hindi नीलम (nīlam), from Sanskrit नील", False, "high",
            "Neelam is Hindi नीलम (nīlam) 'sapphire, blue gem', from Sanskrit नील (nīla) 'blue'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Hindi/Sanskrit. The source gloss 'Jewel, Gem, Pearl' is broadly consistent."),
 "neelu": ("نِيلُو", "نیلو", "نیلو", "नीलू", "نیلو", "neelu", "Hindi", "Female",
           "Hindi नीलू (nīlū), from Sanskrit नील", False, "high",
           "Neelu is Hindi नीलू (nīlū) 'blue', from Sanskrit नील (nīla). CRITICAL SOURCE ERROR: the source gave the Latin string 'Neelu' instead of a script form and labelled the origin Arabic; the word is Hindi. The source gloss 'Blue Lotus' is unsupported and has been replaced with the lexical sense."),
 "neemat": ("نِعْمَات", "نعمات", "نعمات", "निअमात", "نعمات", "blessings", "Arabic", "Female",
            "Arabic root ن ع م (n-ʿ-m); نِعْمَات (Niʿmāt)", False, "high",
            "Neemat is Arabic نِعْمَات (Niʿmāt) 'blessings, favours', the plural of نِعْمَة (niʿma), from the root ن ع م (n-ʿ-m). The source gloss 'Gift, Blessing' is consistent."),
 "neeya": ("نِيَة", "نیہ", "نیه", "नीया", "نیه", "neeya", "Arabic", "Female",
           "Arabic نِيَة (Niya)", False, "medium",
           "Neeya is recorded as Arabic نِيَة (Niya), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Neeya' instead of a script form. The source gloss 'Gentle, Tender, Delicate' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "negar": ("نِگَار", "نگار", "نگار", "नेगार", "نګار", "negar", "Persian", "Female",
           "Persian نگار (negār)", False, "high",
           "Negar is Persian نگار (negār) 'beloved, picture'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Negar' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Jewel, Precious' is unsupported and has been replaced with the lexical sense."),
 "nehad": ("نَهْد", "نہد", "نهد", "नेहद", "نهد", "nehad", "Arabic", "Female",
           "Arabic root ن ه د (n-h-d); نَهْد (Nahd)", False, "high",
           "Nehad is Arabic نَهْد (Nahd) 'high ground', from the root ن ه د (n-h-d). The source gloss 'Graceful, Gentle' is unsupported and has been replaced with the lexical sense."),
 "nehan": ("نِيهَان", "نیہان", "نیهان", "नेहान", "نیهان", "nehan", "Arabic", "Female",
           "Arabic نِيهَان (Nīhān)", False, "medium",
           "Nehan is recorded as Arabic نِيهَان (Nīhān), a female given name. The source gloss 'Gentle, Tender' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "nehar": ("نَهَار", "نہار", "نهار", "नेहार", "نهار", "daytime", "Arabic", "Female",
           "Arabic root ن ه ر (n-h-r); نَهَار (Nahār)", False, "high",
           "Nehar is Arabic نَهَار (Nahār) 'daytime, day', from the root ن ه ر (n-h-r). The source gloss 'River' is unsupported and has been replaced with the lexical sense."),
 "nehat": ("نَهَات", "نہات", "نهات", "नेहात", "نهات", "nehat", "Arabic", "Male",
           "Arabic نَهَات (Nahāt)", False, "medium",
           "Nehat is recorded as Arabic نَهَات (Nahāt), a male given name. CRITICAL SOURCE ERROR: the source gave نهاة (a non-standard form) and labelled the gender unisex. The source gloss 'Given by God' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nehla": ("نَهْلَة", "نہلہ", "نهله", "नेहला", "نهله", "nehla", "Arabic", "Female",
           "Arabic root ن ه ل (n-h-l); نَهْلَة (Nahla)", False, "high",
           "Nehla is Arabic نَهْلَة (Nahla) 'a drink, a draught', from the root ن ه ل (n-h-l). The source gloss 'Night, Shining Star' is unsupported and has been replaced with the lexical sense."),
 "nehrin": ("نَهْرِين", "نہرین", "نهرین", "नेहरीन", "نهرین", "nehrin", "Arabic", "Female",
            "Arabic نَهْر (nahr) + relational ending", False, "high",
            "Nehrin is Arabic نَهْرِين (Nahrīn) 'of the river', from نَهْر (nahr) 'river'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nahr' (a different form) and labelled the gender unisex. The source gloss 'Light of the moon' is unsupported and has been replaced with the lexical sense."),
 "neima": ("نِعْمَة", "نعمہ", "نعمه", "नेमा", "نعمه", "blessing", "Arabic", "Female",
           "Arabic root ن ع م (n-ʿ-m); نِعْمَة (Niʿma)", False, "high",
           "Neima is Arabic نِعْمَة (Niʿma) 'blessing, favour, grace', from the root ن ع م (n-ʿ-m). The source gloss 'Comforting, Consoling' is unsupported and has been replaced with the lexical sense. Same name as nemat."),
 "neimat": ("نِعْمَة", "نعمہ", "نعمه", "नेमत", "نعمه", "blessing", "Arabic", "Female",
            "Arabic root ن ع م (n-ʿ-m); نِعْمَة (Niʿma)", False, "high",
            "Neimat is Arabic نِعْمَة (Niʿma) 'blessing, favour, grace', from the root ن ع م (n-ʿ-m). The source gloss 'Gift, Blessing' is consistent. Same name as neima."),
 "nejat": ("نَجَاة", "نجات", "نجات", "नजात", "نجات", "salvation", "Turkish", "Male",
           "Turkish Necat, from Arabic نَجَاة (najāh)", False, "high",
           "Nejat is the Turkish form of Arabic نَجَاة (najāh) 'salvation, safety, deliverance'. CRITICAL SOURCE ERROR: the source gave نِجَاط (a non-standard form) and labelled the origin Arabic; the name as spelled is Turkish. The source gloss 'Safety, Salvation, Security' is consistent."),
 "nejib": ("نَجِيب", "نجیب", "نجیب", "नजीब", "نجیب", "noble_excellent", "Arabic", "Male",
           "Arabic root ن ج ب (n-j-b); نَجِيب (Najīb)", False, "high",
           "Nejib is Arabic نَجِيب (Najīb) 'noble, excellent, generous', from the root ن ج ب (n-j-b). The source gloss 'Gifted, Generous' is broadly consistent."),
 "nejla": ("نَجْلَاء", "نجلاء", "نجلاء", "नजला", "نجلاء", "wide_eyed2", "Arabic", "Female",
           "Arabic root ن ج ل (n-j-l); نَجْلَاء (Najlāʾ)", False, "high",
           "Nejla is Arabic نَجْلَاء (Najlāʾ) 'wide-eyed, large-eyed', from the root ن ج ل (n-j-l). The source gloss 'Young girl' is unsupported and has been replaced with the lexical sense. Same name as najla."),
 "nelam": ("نِيلَم", "نیلم", "نیلم", "नेलम", "نیلم", "nelam", "Hindi", "Female",
           "Hindi नीलम (nīlam), from Sanskrit नील", False, "high",
           "Nelam is a spelling variant of Hindi नीलम (nīlam) 'sapphire', from Sanskrit नील (nīla) 'blue'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nelam' instead of a script form and labelled the origin Arabic; the word is Hindi. The source gloss 'Light, Radiant' is unsupported and has been replaced with the lexical sense. Same name as neelam."),
 "nelofar": ("نِيلُوفَر", "نیلوفر", "نیلوفر", "नीलोफ़र", "نیلوفر", "water_lily", "Persian", "Female",
             "Persian نیلوفر (nīlūfar)", False, "high",
             "Nelofar is Persian نیلوفر (nīlūfar) 'water lily, lotus'. CRITICAL SOURCE ERROR: the source gave نلفجر (a different form) and labelled the origin Arabic; the word is Persian. The source gloss 'Lotus Flower' is consistent."),
 "nemat": ("نِعْمَة", "نعمہ", "نعمه", "नेमत", "نعمه", "nemat", "Arabic", "Male",
           "Arabic root ن ع م (n-ʿ-m); نِعْمَة (Niʿma)", False, "high",
           "Nemat is Arabic نِعْمَة (Niʿma) 'blessing, favour, grace', from the root ن ع م (n-ʿ-m). CRITICAL SOURCE ERROR: the source labelled the origin Persian; the word is Arabic. The source gloss 'Gem' is unsupported and has been replaced with the lexical sense. Same name as neima."),
 "nen": ("نِن", "نن", "نن", "नेन", "نن", "nen", "Arabic", "Female",
         "Arabic نِن (Nin)", False, "medium",
         "Nen is recorded as Arabic نِن (Nin), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nen' instead of a script form. The source gloss 'Grace, beauty' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "neshat": ("نِشَاط", "نشاط", "نشاط", "नशात", "نشاط", "joy_happiness", "Persian", "Female",
            "Persian نشاط (neshāt), from Arabic نَشَاط", False, "high",
            "Neshat is Persian نشاط (neshāt) 'joy, happiness, liveliness', from Arabic نَشَاط (nashāṭ). CRITICAL SOURCE ERROR: the source gave نِشَات (a non-standard form) and labelled the origin Arabic; the name as used is Persian. The source gloss 'Joy, Happiness' is consistent."),
 "nesma": ("نَسْمَة", "نسمہ", "نسمه", "नसमा", "نسمه", "nesma", "Arabic", "Female",
           "Arabic root ن س م (n-s-m); نَسْمَة (Nasma)", False, "high",
           "Nesma is Arabic نَسْمَة (Nasma) 'a breeze, a breath', from the root ن س م (n-s-m). The source gloss 'Awakening, Inspiration' is unsupported and has been replaced with the lexical sense. Same name as nasma."),
 "nesreen": ("نِسْرِين", "نسرین", "نسرین", "नसरीन", "نسرین", "wild_rose", "Arabic", "Female",
             "Arabic نِسْرِين (Nisrīn)", False, "high",
             "Nesreen is Arabic نِسْرِين (Nisrīn) 'wild rose, narcissus'. CRITICAL SOURCE ERROR: the source gave نسريّن (a non-standard form). The source gloss 'Graceful bloom' is broadly consistent. Same name as nasreen."),
 "nevaeh": ("نِيفَايَة", "نیوایہ", "نوایه", "नेवेया", "نیوایه", "nevaeh", "English", "Female",
            "English Nevaeh ('heaven' reversed)", False, "high",
            "Nevaeh is an English female given name, coined as 'heaven' spelled backwards. CRITICAL SOURCE ERROR: the source gave فاطمة (a different name) and labelled the origin Arabic; the name is English. The source gloss 'Divine gift' is unsupported and has been replaced with the documented identification."),
 "neveen": ("نِيفِين", "نیوین", "نیوین", "नेवीन", "نیوین", "neveen", "Arabic", "Female",
            "Arabic نِيفِين (Nīfīn)", False, "high",
            "Neveen is Arabic نِيفِين (Nīfīn) 'beautiful, fair'. The source gloss 'Graceful, Beautiful' is broadly consistent."),
}
