# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 40 (masjid..mensur).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": mas -> مَصْعُود (should be مَسْعُود) and a
   garbled display name "Mas'ود"; masood -> "عربي_Masood" (placeholder, not Arabic);
   masouda -> "Masouda" (Latin); matia/matina/mausooma/mawadda/meeza/maziar ->
   Latin strings instead of Arabic; mastur -> مَاءسْتَر (garbled); mashel -> احمد
   (a different name entirely); meher -> عائشة (a different name entirely);
   mays -> علي (a different name entirely); masoom -> مَسُوم (should be مَعْصُوم);
   masooma -> مصومة (should be مَعْصُومَة); marziya -> "Muzayyah" (a different name);
   marzieh -> مرزیه (should be مَرْضِيَّة); mashael -> مشعل (should be مَشَاعِل);
   mashari -> ماشاري (should be مَشَارِي); mashkoor -> ماشكور (should be مَشْكُور);
   mashood -> مشود (should be مَشْهُود); mashooq -> ماشوق (should be مَعْشُوق);
   masar -> مسارات (should be مَسَار); masarra -> مسرّة (should be مَسَرَّة);
   masad -> مَسَاد (should be مَسْعَد); mateen -> متيان (should be مَتِين);
   mehdi -> مہدی (should be مَهْدِي); mehmet -> محمد (a different name);
   mehrnoush/mehrsa/mehry -> عائشة (a different name entirely);
   memoona -> أمنية (a different name entirely); mehran -> مهرن (should be مهران);
   mehreen/mehrin -> مهيرين (should be مهرین); mehtab -> ميهتاب (should be مهتاب);
   mehwish -> ميهوش (should be مهویش); mehrtash -> مهارتاش (should be مهرتاش).
 * EMPTY STUBS (8-key records, no data): masuma, mawaddah, maya, maysa, mazin.
 * MISLABELLED ORIGIN: marzieh (Persian), maziar (Persian), mehmet (Turkish),
   melek/meltem (Turkish), medina (place name), masjid (common noun), meem
   (letter name), mehndi (common noun), matlab (common noun), maulana/mawlana
   (title), meena/mehak/mehndi/mehr/mehrab/mehraban/mehrad/mehran/mehreen/mehri/
   mehriban/mehrin/mehrnoush/mehrsa/mehrtash/mehry/mehtab/mehvish/mehwish
   (Persian/Urdu words).
 * DEGARBLED GLOSSES: marzieh "Beloved, Precious" (from a supposed Persian
   'marz'), marziya "Exalted, Noble", marzouq "One who crushes, subdues",
   masad "Stone", masarra "Delicate, Graceful", mashael "A gentle breeze",
   mashar "Traveler on the path to God", mashhood "Wronged, Oppressed",
   mashood "Honored", mashel "Scorpion", masoom "Innocent, Truthful" (gender
   wrong), masooma "Testimonian, Witness", masoud "Lion-like", masouda
   "Helpful, Able", masroor "Firm, Steady, Secure", massoud "Mature, Solider",
   mastan "The Helper", mastur "A Drop of Water", masud "Hope, trust, believer",
   masudi "Wise, Knowledgeable", masun "Sun, Heat", matar "Rain" (ok),
   matee "Gift", mateen "Firm, steadfast" (ok), mathar "Rider, Traveler",
   matia/matina "Gift of Allah", matin "Early", matir "A carrier, supporter",
   matlab "Gift from Allah", matloob "Desiring, yearning", matlub "Desiring",
   maulana "Master, Owner", mausooma "Mother of the Believers", mawadda
   "Love, Compassion", mawar "Abyss, Ocean", mawlana "Our Master", mayada
   "Moon", mayar "Moon", mayed "Luminous", maymun "Beloved", maymuna
   "Moon-like, Pleasing", mays "Mother of Abbas", maysaa "Mother of Dew",
   maysam "Abode of Tranquility", maysan "A sanctuary", maysara "Easy-going",
   maysarah "Abundance of joy", maysoon "Moon", maytham "Compassionate",
   mayyada "Tender, Delicate", mazahir "Manifestations" (ok), mazhar "Light,
   Illumination", maziah "Graceful", maziar "Wise, Intelligent, Brave",
   mazid "Powerful", maznah "Refuge, Shelter", medina "City of the Prophet",
   meem "Letter M", meena "Jasmine flower", meer "Prince, Noble, Leader",
   meera "Prophet's companion", meeran "Gentle, Radiant", meeza "Gift from
   Allah", meezan "Balance, Scale" (ok), meha "Delight, Pleasure", mehak
   "Fragrance of Heaven", mehar "Loving and Kind", mehboob "Beloved, Lover"
   (ok), mehd "Guide, Helper", mehdi "Guided One" (ok), mehek "Glowing,
   Radiant", meher "Bountiful", mehfooz "Protected, Secure, Safe" (ok),
   mehmet "Moon", mehmood "Gift, Generous", mehmud "Praised, Honored" (ok),
   mehnaz "Grace, Delight, Beautiful", mehndi "Henna Design", mehr "Gift",
   mehrab "Prayer Niche or Altar" (ok), mehraban "Kind and loving" (ok),
   mehrad "Radiant, Bright", mehran "Kind, Merciful", mehrana "Radiant,
   shining light", mehreen "Moonlight", mehri "One who shines, glows",
   mehriban "Beloved, dear", mehrin "Filled with love and affection",
   mehrnoush "Light of God", mehrsa "Bountiful, Generous", mehrtash "He who
   illuminates", mehry "Lady, noblewoman", mehtab "Moon, Star, Night",
   mehvish "A gift from God", mehwish "Beautiful, Moon-like", melek "Queen,
   Lady", meltem "Cool breeze", memoona "Beloved", mensur "Measurer".
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated39 import GLOSSES as _G39

GLOSSES = dict(_G39)
GLOSSES.update({
    "mosque": {"en": "Mosque, place of prostration", "ur": "مسجد، عبادت گاہ", "fa": "مسجد، جای سجده", "hi": "मस्जिद, उपासना-स्थल", "ps": "مسجد، د عبادت ځای", "ar": "الْمَسْجِد، مَوْضِع السُّجُود"},
    "innocent": {"en": "Innocent, protected, sinless", "ur": "معصوم، بے گناہ، محفوظ", "fa": "معصوم، بی‌گناه، محفوظ", "hi": "मासूम, निर्दोष, सुरक्षित", "ps": "معصوم، بې ګناه، ساتل شوی", "ar": "الْمَعْصُوم، الْبَرِيء، الْمَحْفُوظ"},
    "innocent_f": {"en": "Innocent, protected, sinless (feminine)", "ur": "معصومہ، بے گناہ، محفوظ (مؤنث)", "fa": "معصومه، بی‌گناه، محفوظ (مؤنث)", "hi": "मासूमा, निर्दोष (स्त्री)", "ps": "معصومه، بې ګناه", "ar": "الْمَعْصُومَة، الْبَرِيئَة، الْمَحْفُوظَة"},
    "fortunate_f": {"en": "Fortunate, happy (feminine)", "ur": "مسعوده، خوش نصیب (مؤنث)", "fa": "مسعوده، خوشبخت (مؤنث)", "hi": "मसूदा, भाग्यशाली (स्त्री)", "ps": "مسعوده، نیکمرغه", "ar": "الْمَسْعُودَة، السَّعِيدَة، الْمَحْظُوظَة"},
    "joyful": {"en": "Joyful, delighted, happy", "ur": "مسرور، خوش، شادمان", "fa": "مسرور، شاد، خوشحال", "hi": "प्रसन्न, मसरूर, आनंदित", "ps": "مسرور، خوشحاله، مینه‌ناک", "ar": "الْمَسْرُور، الْفَرْحَان، الْمَغْبُوط"},
    "helper": {"en": "Helper, supporter, ally", "ur": "مددگار، معاون، حامی", "fa": "یاری‌کننده، یاور، پشتیبان", "hi": "सहायक, मददगार, सहयोगी", "ps": "مرستندوی، ملاتړی", "ar": "الْمُعِين، النَّاصِر، الْحَافِظ"},
    "veiled": {"en": "Veiled, concealed, protected", "ur": "مستور، پردہ پوش، محفوظ", "fa": "مستور، پوشیده، محفوظ", "hi": "पर्दानशीं, छिपा, सुरक्षित", "ps": "پټ، ساتل شوی", "ar": "الْمَسْتُور، الْمَحْجُوب، الْمَصُون"},
    "veiled_f": {"en": "Veiled, concealed, protected (feminine)", "ur": "مستورہ، پردہ پوش، محفوظ (مؤنث)", "fa": "مستوره، پوشیده، محفوظ (مؤنث)", "hi": "मस्तूरा, पर्दानशीं (स्त्री)", "ps": "مستوره، پټه", "ar": "الْمَسْتُورَة، الْمَحْجُوبَة، الْمَصُونَة"},
    "masudi": {"en": "Masudi; of Masud, belonging to Masud", "ur": "مسعودی، مسعود سے منسوب", "fa": "مسعودی، منسوب به مسعود", "hi": "मसूदी, मसूद से", "ps": "مسعودي، د مسعود اړوند", "ar": "الْمَسْعُودِي، مَنْسُوب إِلَى الْمَسْعُود"},
    "protected": {"en": "Protected, guarded, safe", "ur": "محفوظ، محروس، امان میں", "fa": "محفوظ، نگه‌داشته، ایمن", "hi": "सुरक्षित, महफ़ूज़, संरक्षित", "ps": "ساتل شوی، خوندي", "ar": "الْمَحْفُوظ، الْمَصُون، الْآمِن"},
    "rain": {"en": "Rain", "ur": "مطر، بارش", "fa": "مطر، باران", "hi": "वर्षा, मतर, बारिश", "ps": "مطر، باران", "ar": "الْمَطَر، الْغَيْث، الْوَابِل"},
    "gift": {"en": "Gift, present, bestowal", "ur": "عطیہ، تحفہ، بخشش", "fa": "عطیه، هدیه، بخشش", "hi": "उपहार, अता, भेंट", "ps": "ډالۍ، عطیه", "ar": "الْعَطِيَّة، الْهَدِيَّة، الْهِبَة"},
    "firm": {"en": "Firm, steadfast, solid", "ur": "متین، مضبوط، ثابت قدم", "fa": "متین، استوار، پابرجا", "hi": "मतीन, दृढ़, अटल", "ps": "متین، ټینګ، کلک", "ar": "الْمَتِين، الرَّاسِخ، الثَّابِت"},
    "rider": {"en": "Rider, traveler, wayfarer", "ur": "مسافر، راہی، سوار", "fa": "مسافر، رهگذر، سوار", "hi": "यात्री, सवार, पथिक", "ps": "مسافر، سپور", "ar": "الْمُسَافِر، الرَّاكِب، السَّالِك"},
    "gift_allah": {"en": "Gift of God", "ur": "اللہ کا عطیہ، خدا کی بخشش", "fa": "عطیهٔ خدا، بخشش خداوند", "hi": "ईश्वर का उपहार, अल्लाह की अता", "ps": "د الله ډالۍ", "ar": "عَطِيَّة الله، هِبَة الله"},
    "matin": {"en": "Matin; firm, steadfast", "ur": "متین، مضبوط، ثابت قدم", "fa": "متین، استوار، پابرجا", "hi": "मतीन, दृढ़, अटल", "ps": "متین، ټینګ", "ar": "الْمَتِين، الرَّاسِخ، الثَّابِت"},
    "carrier": {"en": "Carrier, supporter, helper", "ur": "حامی، سہارا دینے والا، معاون", "fa": "حامی، پشتیبان، یاور", "hi": "वाहक, सहायक, सहारा देने वाला", "ps": "ملاتړی، مرستندوی", "ar": "الْحَامِل، النَّاصِر، الْمُعِين"},
    "request": {"en": "Request, demand, object sought", "ur": "مطلب، مطالبہ، خواہش", "fa": "مطلب، درخواست، خواسته", "hi": "मतलब, अनुरोध, माँग", "ps": "مطلب، غوښتنه", "ar": "الْمَطْلَب، الطَّلَب، الْمَقْصُود"},
    "sought": {"en": "Sought, desired, wished for", "ur": "مطلوب، خواہشمند، مراد", "fa": "مطلوب، خواسته، مراد", "hi": "मतलूब, वांछित, अभीष्ट", "ps": "مطلوب، غوښتل شوی", "ar": "الْمَطْلُوب، الْمُرَاد، الْمَقْصُود"},
    "master": {"en": "Master, lord, patron", "ur": "مولا، مالک، سرپرست", "fa": "مولا، سرور، صاحب", "hi": "मौला, स्वामी, मालिक", "ps": "مولا، مالک", "ar": "الْمَوْلَى، السَّيِّد، الْمَالِك"},
    "love_mawadda": {"en": "Love, affection, compassion", "ur": "مودت، محبت، شفقت", "fa": "مودت، محبت، مهربانی", "hi": "मोहब्बत, मवद्दत, स्नेह", "ps": "مودت، مینه", "ar": "الْمَوَدَّة، الْمَحَبَّة، الرَّحْمَة"},
    "abyss": {"en": "Abyss, deep water, ocean", "ur": "گہرا پانی، سمندر، اتھاہ", "fa": "دریای عمیق، اقیانوس، ژرفا", "hi": "गहरा जल, सागर, अथाह", "ps": "ژور اوبه، سمندر", "ar": "الْمَوَار، الْبَحْر، الْغَمْر"},
    "moon": {"en": "Moon", "ur": "قمر، چاند", "fa": "ماه، قمر", "hi": "चाँद, क़मर, चंद्र", "ps": "سپوږمۍ، قمر", "ar": "الْقَمَر، الْبَدْر، الْهِلَال"},
    "luminous": {"en": "Luminous, shining, radiant", "ur": "روشن، چمکدار، منور", "fa": "روشن، درخشان، تابان", "hi": "प्रकाशमान, चमकदार, उज्ज्वल", "ps": "روښانه، ځلانده", "ar": "الْمُضِيء، الْمُشْرِق، اللَّامِع"},
    "blessed": {"en": "Blessed, fortunate, auspicious", "ur": "مبارک، بابرکت، خوش نصیب", "fa": "مبارک، فرخنده، خجسته", "hi": "मुबारक, शुभ, भाग्यशाली", "ps": "مبارک، نیکمرغه", "ar": "الْمُبَارَك، الْمَيْمُون، السَّعِيد"},
    "blessed_f": {"en": "Blessed, fortunate, auspicious (feminine)", "ur": "میمونہ، مبارک، خوش نصیب (مؤنث)", "fa": "میمونه، مبارک، فرخنده (مؤنث)", "hi": "मैमूना, मुबारक (स्त्री)", "ps": "میمونه، مبارک", "ar": "الْمَيْمُونَة، الْمُبَارَكَة، السَّعِيدَة"},
    "maysaa": {"en": "Maysaa; a female given name", "ur": "میساء (زنانہ نام)", "fa": "میساء (نام زنانہ)", "hi": "मैसा (स्त्री नाम)", "ps": "میساء (ښځينه نوم)", "ar": "مَيْسَاء (اسم علم مؤنث)"},
    "maysam": {"en": "Maysam; a male given name", "ur": "میثم (مردانہ نام)", "fa": "میثم (نام مردانہ)", "hi": "मैसम (पुरुष नाम)", "ps": "میثم (نر نوم)", "ar": "مَيْثَم (اسم علم مذكر)"},
    "maysan": {"en": "Maysan; a place name and given name", "ur": "میسان (نام و مقام)", "fa": "میسان (نام و مکان)", "hi": "मैसान (नाम व स्थान)", "ps": "میسان (نوم او ځای)", "ar": "مَيْسَان (اسم علم وموضع)"},
    "ease": {"en": "Ease, facility, convenience", "ur": "آسانی، سہولت، آسودگی", "fa": "آسانی، سهولت، راحتی", "hi": "सुगमता, आसानी, सहूलियत", "ps": "اسانتیا، آسودګي", "ar": "الْمَيْسَرَة، السُّهُولَة، الْيُسْر"},
    "maytham": {"en": "Maytham; a male given name", "ur": "میثم (مردانہ نام)", "fa": "میثم (نام مردانہ)", "hi": "मैथम (पुरुष नाम)", "ps": "میثم (نر نوم)", "ar": "مَيْثَم (اسم علم مذكر)"},
    "tender": {"en": "Tender, delicate, soft", "ur": "نازک، ملائم، نرم", "fa": "نازک، لطیف، نرم", "hi": "कोमल, नाज़ुक, मुलायम", "ps": "نازک، نرم", "ar": "اللَّطِيف، النَّاعِم، الرَّقِيق"},
    "manifestations": {"en": "Manifestations, appearances, displays", "ur": "مظاہر، جلوے، نمود", "fa": "مظاهر، جلوه‌ها، نمود", "hi": "अभिव्यक्तियाँ, मज़ाहिर, प्रकट रूप", "ps": "ښکارېدنې، مظاهر", "ar": "الْمَظَاهِر، التَّجَلِّيَات، الْآثَار"},
    "manifestation": {"en": "Manifestation, appearance, display", "ur": "مظہر، جلوہ، نمود", "fa": "مظهر، جلوه، نمود", "hi": "अभिव्यक्ति, मज़हर, प्रकट रूप", "ps": "ښکارېدنه، مظهر", "ar": "الْمَظْهَر، التَّجَلِّي، الْآيَة"},
    "maziah": {"en": "Maziah; a female given name", "ur": "مازیہ (زنانہ نام)", "fa": "مازیه (نام زنانہ)", "hi": "माज़िया (स्त्री नाम)", "ps": "مازیه (ښځينه نوم)", "ar": "مَازِيَة (اسم علم مؤنث)"},
    "maziar": {"en": "Maziar; a Persian male given name", "ur": "مازیار (فارسی نام)", "fa": "مازیار (نام مردانہ)", "hi": "माज़ियार (फ़ारसी नाम)", "ps": "مازیار (فارسي نوم)", "ar": "مَازِيَار (اسم علم مذكر فارسي)"},
    "increase": {"en": "Increase, addition, abundance", "ur": "مزید، اضافہ، زیادتی", "fa": "مزید، افزونی، افزایش", "hi": "वृद्धि, मज़ीद, अधिकता", "ps": "زیاتوالی، اضافه", "ar": "الْمَزِيد، الزِّيَادَة، الْإِضَافَة"},
    "mazin": {"en": "Mazin; a male given name", "ur": "مازن (مردانہ نام)", "fa": "مازن (نام مردانہ)", "hi": "माज़िन (पुरुष नाम)", "ps": "مازن (نر نوم)", "ar": "مَازِن (اسم علم مذكر)"},
    "maznah": {"en": "Maznah; a female given name", "ur": "مزنہ (زنانہ نام)", "fa": "مزنه (نام زنانہ)", "hi": "मज़ना (स्त्री नाम)", "ps": "مزنه (ښځينه نوم)", "ar": "مَزْنَة (اسم علم مؤنث)"},
    "medina": {"en": "Medina; a city in Arabia", "ur": "مدینہ، عرب کا شہر", "fa": "مدینه، شهری در عربستان", "hi": "मदीना, अरब का नगर", "ps": "مدینه، د عربستان ښار", "ar": "الْمَدِينَة، مَدِينَة النَّبِيّ"},
    "meem": {"en": "Meem; the Arabic letter mīm", "ur": "میم، عربی حرف", "fa": "میم، حرف عربی", "hi": "मीम, अरबी अक्षर", "ps": "میم، عربي توری", "ar": "الْمِيم، حَرْف عَرَبِيّ"},
    "meena": {"en": "Meena; a female given name", "ur": "مینا (زنانہ نام)", "fa": "مینا (نام زنانہ)", "hi": "मीना (स्त्री नाम)", "ps": "مینا (ښځينه نوم)", "ar": "مِينَا (اسم علم مؤنث)"},
    "meer": {"en": "Meer; a title and male given name", "ur": "میر، سردار، نام", "fa": "میر، سردار، نام", "hi": "मीर, सरदार, नाम", "ps": "میر، مشر", "ar": "مِير (لقب واسم علم مذكر)"},
    "meera": {"en": "Meera; a female given name", "ur": "میرا (زنانہ نام)", "fa": "میرا (نام زنانہ)", "hi": "मीरा (स्त्री नाम)", "ps": "میرا (ښځينه نوم)", "ar": "مِيرَا (اسم علم مؤنث)"},
    "meeran": {"en": "Meeran; a male given name", "ur": "میران (مردانہ نام)", "fa": "میران (نام مردانہ)", "hi": "मीरान (पुरुष नाम)", "ps": "میران (نر نوم)", "ar": "مِيرَان (اسم علم مذكر)"},
    "meeza": {"en": "Meeza; a female given name", "ur": "میزا (زنانہ نام)", "fa": "میزا (نام زنانہ)", "hi": "मीज़ा (स्त्री नाम)", "ps": "میزا (ښځينه نوم)", "ar": "مِيزَا (اسم علم مؤنث)"},
    "balance": {"en": "Balance, scale, measure", "ur": "میزان، ترازو، پیمانہ", "fa": "میزان، ترازو، سنجه", "hi": "तराज़ू, मीज़ान, संतुलन", "ps": "میزان، تله", "ar": "الْمِيزَان، الْعَدْل، الْقِسْط"},
    "meha": {"en": "Meha; a female given name", "ur": "میہا (زنانہ نام)", "fa": "میهه (نام زنانہ)", "hi": "मीहा (स्त्री नाम)", "ps": "میهه (ښځينه نوم)", "ar": "مِيهَا (اسم علم مؤنث)"},
    "fragrance": {"en": "Fragrance, scent, aroma", "ur": "خوشبو، مہک، عطر", "fa": "خوشبو، رایحه، عطر", "hi": "सुगंध, महक, ख़ुशबू", "ps": "خوږه بوی، عطر", "ar": "الْعِطْر، الْأَرِيج، الشَّذَا"},
    "mehar": {"en": "Mehar; a female given name", "ur": "مہر (زنانہ نام)", "fa": "مهر (نام زنانہ)", "hi": "मेहर (स्त्री नाम)", "ps": "مهر (ښځينه نوم)", "ar": "مِهَار (اسم علم مؤنث)"},
    "beloved_mehboob": {"en": "Beloved, dear, loved one", "ur": "محبوب، پیارا، عزیز", "fa": "محبوب، عزیز، دلدار", "hi": "महबूब, प्रिय, प्यारा", "ps": "محبوب، ګران", "ar": "الْمَحْبُوب، الْحَبِيب، الْعَزِيز"},
    "mehd": {"en": "Mehd; a male given name", "ur": "مہد (مردانہ نام)", "fa": "مهد (نام مردانہ)", "hi": "मेहद (पुरुष नाम)", "ps": "مهد (نر نوم)", "ar": "مَهْد (اسم علم مذكر)"},
    "guided": {"en": "Guided, rightly directed", "ur": "ہدایت یافتہ، رہنمائی شدہ", "fa": "هدایت‌یافته، رهنمون", "hi": "मार्गदर्शित, हिदायत याफ़्ता", "ps": "هدایت شوی، لارښود شوی", "ar": "الْمَهْدِيّ، الْمُهْتَدِي، الرَّشِيد"},
    "mehek": {"en": "Mehek; a female given name", "ur": "مہک (زنانہ نام)", "fa": "مهک (نام زنانہ)", "hi": "मेहक (स्त्री नाम)", "ps": "مهک (ښځينه نوم)", "ar": "مِهَك (اسم علم مؤنث)"},
    "meher": {"en": "Meher; a female given name", "ur": "مہر (زنانہ نام)", "fa": "مهر (نام زنانہ)", "hi": "मेहर (स्त्री नाम)", "ps": "مهر (ښځينه نوم)", "ar": "مِهَر (اسم علم مؤنث)"},
    "mehmet": {"en": "Mehmet; a Turkish male given name", "ur": "محمت (ترکی نام)", "fa": "محمت (نام ترکی)", "hi": "मेहमत (तुर्की नाम)", "ps": "محمت (ترکي نوم)", "ar": "مَحْمَت (اسم علم مذكر تركي)"},
    "praised": {"en": "Praised, commended, laudable", "ur": "محمود، تعریف شدہ، ستودہ", "fa": "محمود، ستوده، پسندیده", "hi": "प्रशंसित, महमूद, सराहा हुआ", "ps": "ستایل شوی، محمود", "ar": "الْمَحْمُود، الْحَمِيد، الْمَشْكُور"},
    "mehnaz": {"en": "Mehnaz; a female given name", "ur": "مہناز (زنانہ نام)", "fa": "مهناز (نام زنانہ)", "hi": "मेहनाज़ (स्त्री नाम)", "ps": "مهناز (ښځينه نوم)", "ar": "مِهْنَاز (اسم علم مؤنث)"},
    "henna": {"en": "Henna, henna design", "ur": "مہندی، حنا", "fa": "حنا، مهدی", "hi": "मेहंदी, हिना", "ps": "مېندي، حنا", "ar": "الْحِنَّاء، الْمِهْنَدِي"},
    "mehr": {"en": "Mehr; sun, love, affection", "ur": "مہر، محبت، سورج", "fa": "مهر، محبت، خورشید", "hi": "मेहर, स्नेह, सूर्य", "ps": "مهر، مینه", "ar": "مِهْر (اسم علم مؤنث فارسي)"},
    "mihrab": {"en": "Prayer niche, mihrab", "ur": "محراب، عبادت گاہ کا طاق", "fa": "محراب، طاق نماز", "hi": "मेहराब, मिहराब", "ps": "محراب", "ar": "الْمِحْرَاب، طَاق الصَّلَاة"},
    "kind": {"en": "Kind, loving, compassionate", "ur": "مہربان، شفیق، رحیم", "fa": "مهربان، دلسوز، بخشنده", "hi": "दयालु, मेहरबान, स्नेही", "ps": "مهربان، زړه سواند", "ar": "الْمِهْرَبَان، الرَّحِيم، الْعَطُوف"},
    "mehrad": {"en": "Mehrad; a Persian male given name", "ur": "مہراد (فارسی نام)", "fa": "مهراد (نام مردانہ)", "hi": "मेहराद (फ़ारसी नाम)", "ps": "مهراد (فارسي نوم)", "ar": "مِهْرَاد (اسم علم مذكر فارسي)"},
    "mehran": {"en": "Mehran; a Persian male given name", "ur": "مہران (فارسی نام)", "fa": "مهران (نام مردانہ)", "hi": "मेहरान (फ़ारसी नाम)", "ps": "مهران (فارسي نوم)", "ar": "مِهْرَان (اسم علم مذكر فارسي)"},
    "mehrana": {"en": "Mehrana; a female given name", "ur": "مہرانہ (زنانہ نام)", "fa": "مهرانه (نام زنانہ)", "hi": "मेहराना (स्त्री नाम)", "ps": "مهرانه (ښځينه نوم)", "ar": "مِهْرَانَة (اسم علم مؤنث)"},
    "mehreen": {"en": "Mehreen; a female given name", "ur": "مہرین (زنانہ نام)", "fa": "مهرین (نام زنانہ)", "hi": "मेहरीन (स्त्री नाम)", "ps": "مهرین (ښځينه نوم)", "ar": "مِهْرِين (اسم علم مؤنث)"},
    "mehri": {"en": "Mehri; a female given name", "ur": "مہری (زنانہ نام)", "fa": "مهری (نام زنانہ)", "hi": "मेहरी (स्त्री नाम)", "ps": "مهری (ښځينه نوم)", "ar": "مِهْرِي (اسم علم مؤنث)"},
    "mehriban": {"en": "Mehriban; a female given name", "ur": "مہربان (زنانہ نام)", "fa": "مهربان (نام زنانہ)", "hi": "मेहरीबान (स्त्री नाम)", "ps": "مهربان (ښځينه نوم)", "ar": "مِهْرِبَان (اسم علم مؤنث)"},
    "mehrin": {"en": "Mehrin; a female given name", "ur": "مہرین (زنانہ نام)", "fa": "مهرین (نام زنانہ)", "hi": "मेहरीन (स्त्री नाम)", "ps": "مهرین (ښځينه نوم)", "ar": "مِهْرِين (اسم علم مؤنث)"},
    "mehrnoush": {"en": "Mehrnoush; a Persian female given name", "ur": "مہرنوش (فارسی نام)", "fa": "مهرنوش (نام زنانہ)", "hi": "मेहरनूश (फ़ारसी नाम)", "ps": "مهرنوش (فارسي نوم)", "ar": "مِهْرْنُوش (اسم علم مؤنث فارسي)"},
    "mehrsa": {"en": "Mehrsa; a Persian female given name", "ur": "مہرسا (فارسی نام)", "fa": "مهراسا (نام زنانہ)", "hi": "मेहरसा (फ़ारसी नाम)", "ps": "مهراسا (فارسي نوم)", "ar": "مِهْرَاسَا (اسم علم مؤنث فارسي)"},
    "mehrtash": {"en": "Mehrtash; a Persian male given name", "ur": "مہرتاش (فارسی نام)", "fa": "مهرتاش (نام مردانہ)", "hi": "मेहरताश (फ़ारसी नाम)", "ps": "مهرتاش (فارسي نوم)", "ar": "مِهْرْتَاش (اسم علم مذكر فارسي)"},
    "mehry": {"en": "Mehry; a female given name", "ur": "مہری (زنانہ نام)", "fa": "مهری (نام زنانہ)", "hi": "मेहरी (स्त्री नाम)", "ps": "مهری (ښځينه نوم)", "ar": "مِهْرِي (اسم علم مؤنث)"},
    "moonlight": {"en": "Moonlight", "ur": "مہتاب، چاندنی", "fa": "مهتاب، مهتابی", "hi": "चाँदनी, मेहताब", "ps": "سپوږمۍ رڼا", "ar": "ضَوْء الْقَمَر، الْمِهْتَاب"},
    "mehvish": {"en": "Mehvish; a female given name", "ur": "مہوش (زنانہ نام)", "fa": "مهویش (نام زنانہ)", "hi": "मेहविश (स्त्री नाम)", "ps": "مهویش (ښځينه نوم)", "ar": "مِهْوِيش (اسم علم مؤنث)"},
    "mehwish": {"en": "Mehwish; a female given name", "ur": "مہوش (زنانہ نام)", "fa": "مهویش (نام زنانہ)", "hi": "मेहविश (स्त्री नाम)", "ps": "مهویش (ښځينه نوم)", "ar": "مِهْوِيش (اسم علم مؤنث)"},
    "melek": {"en": "Melek; a Turkish female given name", "ur": "ملیک (ترکی نام)", "fa": "ملک (نام ترکی)", "hi": "मेलेक (तुर्की नाम)", "ps": "ملیک (ترکي نوم)", "ar": "مَلَك (اسم علم مؤنث تركي)"},
    "angel": {"en": "Angel", "ur": "فرشتہ، ملک", "fa": "فرشته، ملک", "hi": "फ़रिश्ता, मलक", "ps": "پرښته، ملک", "ar": "الْمَلَك، الْمَلَائِكَة"},
    "meltem": {"en": "Meltem; a Turkish female given name", "ur": "میلتیم (ترکی نام)", "fa": "ملتم (نام ترکی)", "hi": "मेल्तेम (तुर्की नाम)", "ps": "میلتیم (ترکي نوم)", "ar": "مِلْتِم (اسم علم مؤنث تركي)"},
    "sea_breeze": {"en": "Sea breeze", "ur": "سمندری ہوا، ٹھنڈی ہوا", "fa": "نسیم دریا، باد ملایم", "hi": "समुद्री हवा, ठंडी बयार", "ps": "د سمندر باد", "ar": "نَسِيم الْبَحْر، الْهَوَاء الْعَلِيل"},
    "memoona": {"en": "Memoona; blessed, fortunate (feminine)", "ur": "میمونہ، مبارک، خوش نصیب (مؤنث)", "fa": "میمونه، مبارک، فرخنده (مؤنث)", "hi": "मैमूना, मुबारक (स्त्री)", "ps": "میمونه، مبارک", "ar": "الْمَيْمُونَة، الْمُبَارَكَة، السَّعِيدَة"},
    "mensur": {"en": "Mensur; a Turkish male given name", "ur": "منصور (ترکی نام)", "fa": "منصور (نام ترکی)", "hi": "मंसूर (तुर्की नाम)", "ps": "منصور (ترکي نوم)", "ar": "مَنْصُور (اسم علم مذكر تركي)"},
})

CUR = {
 "masjid": ("مسجد", "مسجد", "مسجد", "मस्जिद", "مسجد", "mosque", "Arabic", "Unknown",
            "Arabic root س ج د (s-j-d); مَسْجِد (Masjid)", False, "high",
            "Masjid is Arabic مَسْجِد (Masjid) 'mosque, place of prostration', from the root س ج د (s-j-d). The source gloss 'Mosque' is consistent. Recorded as a common noun rather than a personal name; no personal-name gender usage is asserted."),
 "masood": ("مسعود", "مسعود", "مسعود", "मसूद", "مسعود", "masud", "Arabic", "Male",
            "Arabic root س ع د (s-ʿ-d); مَسْعُود (Masʿūd)", False, "high",
            "Masood is Arabic مَسْعُود (Masʿūd) 'fortunate, happy', from the root س ع د (s-ʿ-d). CRITICAL SOURCE ERROR: the source gave placeholder strings such as 'عربي_Masood' instead of an Arabic form; the correct form is مَسْعُود. The source gloss 'Noble and blessed' is broadly consistent. Same name as masud, masoud and massoud."),
 "masoom": ("معصوم", "معصوم", "معصوم", "मासूम", "معصوم", "innocent", "Arabic", "Male",
            "Arabic root ع ص م (ʿ-ṣ-m); مَعْصُوم (Maʿṣūm)", False, "high",
            "Masoom is Arabic مَعْصُوم (Maʿṣūm) 'innocent, protected, sinless', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave مَسُوم (a different form) and recorded the gender as female; the correct form is مَعْصُوم and documented usage is predominantly male. The source gloss 'Innocent, Truthful' is broadly consistent."),
 "masooma": ("معصومة", "معصومہ", "معصومه", "मासूमा", "معصومه", "innocent_f", "Arabic", "Female",
             "Arabic root ع ص م (ʿ-ṣ-m); مَعْصُومَة (Maʿṣūma)", False, "high",
             "Masooma is Arabic مَعْصُومَة (Maʿṣūma) 'innocent, protected, sinless' (feminine), from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave مصومة (a different form) and glossed it 'Testimonian, Witness'; the correct form is مَعْصُومَة and the source gloss is unsupported."),
 "masoud": ("مسعود", "مسعود", "مسعود", "मसूद", "مسعود", "masud", "Arabic", "Male",
            "Arabic root س ع د (s-ʿ-d); مَسْعُود (Masʿūd)", False, "high",
            "Masoud is Arabic مَسْعُود (Masʿūd) 'fortunate, happy', from the root س ع د (s-ʿ-d). The source gloss 'Lion-like' is unsupported and has been replaced with the lexical sense. Same name as masud, masood and massoud."),
 "masouda": ("مسعودة", "مسعوده", "مسعوده", "मसूदा", "مسعوده", "fortunate_f", "Arabic", "Female",
             "Arabic root س ع د (s-ʿ-d); مَسْعُودَة (Masʿūda)", False, "high",
             "Masouda is Arabic مَسْعُودَة (Masʿūda) 'fortunate, happy' (feminine), from the root س ع د (s-ʿ-d). CRITICAL SOURCE ERROR: the source gave the Latin string 'Masouda' instead of an Arabic form and glossed it 'Helpful, Able'; the correct form is مَسْعُودَة and the source gloss is unsupported."),
 "masroor": ("مسرور", "مسرور", "مسرور", "मसरूर", "مسرور", "joyful", "Arabic", "Male",
             "Arabic root س ر ر (s-r-r); مَسْرُور (Masrūr)", False, "high",
             "Masroor is Arabic مَسْرُور (Masrūr) 'joyful, delighted, happy', from the root س ر ر (s-r-r). The source gloss 'Firm, Steady, Secure' is unsupported and has been replaced with the lexical sense. Same name as masrur."),
 "masrur": ("مسرور", "مسرور", "مسرور", "मसरूर", "مسرور", "joyful", "Arabic", "Male",
            "Arabic root س ر ر (s-r-r); مَسْرُور (Masrūr)", False, "high",
            "Masrur is Arabic مَسْرُور (Masrūr) 'joyful, delighted, happy', from the root س ر ر (s-r-r). The source gloss 'Blessed, honored' is broadly consistent. Same name as masroor."),
 "massoud": ("مسعود", "مسعود", "مسعود", "मसूद", "مسعود", "masud", "Arabic", "Male",
             "Arabic root س ع د (s-ʿ-d); مَسْعُود (Masʿūd)", False, "high",
             "Massoud is Arabic مَسْعُود (Masʿūd) 'fortunate, happy', from the root س ع د (s-ʿ-d). The source gloss 'Mature, Solider' is unsupported and has been replaced with the lexical sense. Same name as masud, masood and masoud."),
 "mastan": ("مستان", "مستان", "مستان", "मस्तान", "مستان", "helper", "Arabic", "Male",
            "Arabic مَسْتَان (Mastān)", False, "low",
            "Mastan is recorded at low confidence. The source gloss 'The Helper' is unsupported and no verified Arabic lexical form was established; مَسْتَان (Mastān) is a documented male given name in South Asia, but its derivation could not be confirmed. No confident meaning is asserted."),
 "mastur": ("مستور", "مستور", "مستور", "मस्तूर", "مستور", "veiled", "Arabic", "Male",
            "Arabic root س ت ر (s-t-r); مَسْتُور (Mastūr)", False, "high",
            "Mastur is Arabic مَسْتُور (Mastūr) 'veiled, concealed, protected', from the root س ت ر (s-t-r). CRITICAL SOURCE ERROR: the source gave مَاءسْتَر (a garbled form) and glossed it 'A Drop of Water'; the correct form is مَسْتُور and the source gloss is unsupported."),
 "mastura": ("مستورة", "مستورہ", "مستوره", "मस्तूरा", "مستوره", "veiled_f", "Arabic", "Female",
             "Arabic root س ت ر (s-t-r); مَسْتُورَة (Mastūra)", False, "high",
             "Mastura is Arabic مَسْتُورَة (Mastūra) 'veiled, concealed, protected' (feminine), from the root س ت ر (s-t-r). The source gloss 'Protected, Guarded' is broadly consistent."),
 "masud": ("مسعود", "مسعود", "مسعود", "मसऊद", "مسعود", "masud", "Arabic", "Male",
           "Arabic root س ع د (s-ʿ-d); مَسْعُود (Masʿūd)", False, "high",
           "Masud is Arabic مَسْعُود (Masʿūd) 'fortunate, happy', from the root س ع د (s-ʿ-d). The source gloss 'Hope, trust, believer' is unsupported and has been replaced with the lexical sense. Same name as masood, masoud and massoud."),
 "masudi": ("مسعودي", "مسعودی", "مسعودی", "मसूदी", "مسعودي", "masudi", "Arabic", "Male",
            "Arabic nisba of مَسْعُود; مَسْعُودِي (Masʿūdī)", False, "high",
            "Masudi is Arabic مَسْعُودِي (Masʿūdī), the nisba ('of Masud, belonging to Masud') of مَسْعُود (Masʿūd). The source gloss 'Wise, Knowledgeable' is unsupported and has been replaced with the relational sense."),
 "masum": ("معصوم", "معصوم", "معصوم", "मासूम", "معصوم", "innocent", "Arabic", "Male",
           "Arabic root ع ص م (ʿ-ṣ-m); مَعْصُوم (Maʿṣūm)", False, "high",
           "Masum is Arabic مَعْصُوم (Maʿṣūm) 'innocent, protected, sinless', from the root ع ص م (ʿ-ṣ-m). The source gloss 'Pure, Innocent' is broadly consistent. Same name as masoom."),
 "masuma": ("معصومة", "معصومہ", "معصومه", "मासूमा", "معصومه", "innocent_f", "Arabic", "Female",
            "Arabic root ع ص م (ʿ-ṣ-m); مَعْصُومَة (Maʿṣūma)", False, "high",
            "Masuma is Arabic مَعْصُومَة (Maʿṣūma) 'innocent, protected, sinless' (feminine), from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as masooma."),
 "masun": ("مصون", "مصون", "مصون", "मसूून", "مصون", "protected", "Arabic", "Male",
           "Arabic root ص و ن (ṣ-w-n); مَصُون (Maṣūn)", False, "high",
           "Masun is Arabic مَصُون (Maṣūn) 'protected, guarded, safe', from the root ص و ن (ṣ-w-n). CRITICAL SOURCE ERROR: the source gave مسون (a different form) and glossed it 'Sun, Heat'; the correct form is مَصُون and the source gloss is unsupported."),
 "matar": ("مطر", "مطر", "مطر", "मतर", "مطر", "rain", "Arabic", "Male",
           "Arabic root م ط ر (m-ṭ-r); مَطَر (Maṭar)", False, "high",
           "Matar is Arabic مَطَر (Maṭar) 'rain', from the root م ط ر (m-ṭ-r). The source gloss 'Rain' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "matee": ("معطي", "معطی", "معطی", "मअती", "معطي", "gift", "Arabic", "Male",
           "Arabic root ع ط و (ʿ-ṭ-w); مُعْطِي (Muʿṭī)", False, "medium",
           "Matee is Arabic مُعْطِي (Muʿṭī) 'giver, one who gives', from the root ع ط و (ʿ-ṭ-w). CRITICAL SOURCE ERROR: the source gave ماتي (a different form) and glossed it 'Gift'; the correct form is مُعْطِي. Recorded at medium confidence because the identification is not fully certain."),
 "mateen": ("متين", "متین", "متین", "मतीन", "متین", "firm", "Arabic", "Male",
            "Arabic root م ت ن (m-t-n); مَتِين (Matīn)", False, "high",
            "Mateen is Arabic مَتِين (Matīn) 'firm, steadfast, solid', from the root م ت ن (m-t-n). CRITICAL SOURCE ERROR: the source gave متيان (a different form); the correct form is مَتِين. The source gloss 'Firm, steadfast' is consistent."),
 "mathar": ("مثار", "مثار", "مثار", "मथर", "مثار", "rider", "Arabic", "Male",
            "Arabic مَثَار (Mathār)", False, "low",
            "Mathar is recorded at low confidence. The source gloss 'Rider, Traveler' is unsupported and no verified Arabic lexical form was established; مَثَار (Mathār) is a documented male given name, but its derivation could not be confirmed. No confident meaning is asserted."),
 "matia": ("مطية", "مطیہ", "مطیه", "मतिया", "مطیه", "gift_allah", "Arabic", "Female",
           "Arabic مُعْطِيَة / عَطِيَّة; root ع ط و (ʿ-ṭ-w)", False, "low",
           "Matia is recorded at low confidence. The source gave the Latin string 'Matia' instead of an Arabic form and glossed it 'Gift of Allah'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "matin": ("متين", "متین", "متین", "मतीन", "متین", "matin", "Arabic", "Male",
           "Arabic root م ت ن (m-t-n); مَتِين (Matīn)", False, "high",
           "Matin is Arabic مَتِين (Matīn) 'firm, steadfast, solid', from the root م ت ن (m-t-n). The source gloss 'Early' is unsupported and has been replaced with the lexical sense. Same name as mateen."),
 "matina": ("مطينة", "مطینہ", "مطینه", "मतिना", "مطینه", "gift_allah", "Arabic", "Female",
            "Arabic مُعْطِيَة / عَطِيَّة; root ع ط و (ʿ-ṭ-w)", False, "low",
            "Matina is recorded at low confidence. The source gave the Latin string 'Matina' instead of an Arabic form and glossed it 'Gift from Allah'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "matir": ("ماطر", "ماطر", "ماطر", "मातिर", "ماطر", "carrier", "Arabic", "Male",
           "Arabic مَاطِر (Māṭir)", False, "low",
           "Matir is recorded at low confidence. The source gloss 'A carrier, supporter, helper' is unsupported and no verified Arabic lexical form was established; مَاطِر (Māṭir) is a documented male given name, but its derivation could not be confirmed. No confident meaning is asserted."),
 "matlab": ("مطلب", "مطلب", "مطلب", "मतलब", "مطلب", "request", "Arabic", "Unknown",
            "Arabic root ط ل ب (ṭ-l-b); مَطْلَب (Maṭlab)", False, "high",
            "Matlab is Arabic مَطْلَب (Maṭlab) 'request, demand, object sought', from the root ط ل ب (ṭ-l-b). The source gloss 'Gift from Allah' is unsupported and has been replaced with the lexical sense. Recorded as a common noun rather than a personal name; no personal-name gender usage is asserted."),
 "matloob": ("مطلوب", "مطلوب", "مطلوب", "मतलूब", "مطلوب", "sought", "Arabic", "Male",
             "Arabic root ط ل ب (ṭ-l-b); مَطْلُوب (Maṭlūb)", False, "high",
             "Matloob is Arabic مَطْلُوب (Maṭlūb) 'sought, desired, wished for', from the root ط ل ب (ṭ-l-b). The source gloss 'Desiring, yearning' is broadly consistent. Same name as matlub."),
 "matlub": ("مطلوب", "مطلوب", "مطلوب", "मतलूब", "مطلوب", "sought", "Arabic", "Male",
            "Arabic root ط ل ب (ṭ-l-b); مَطْلُوب (Maṭlūb)", False, "high",
            "Matlub is Arabic مَطْلُوب (Maṭlūb) 'sought, desired, wished for', from the root ط ل ب (ṭ-l-b). The source gloss 'Desiring' is broadly consistent. Same name as matloob."),
 "maulana": ("مولانا", "مولانا", "مولانا", "मौलाना", "مولانا", "master", "Arabic", "Male",
             "Arabic مَوْلَانَا (Mawlānā), from مَوْلَى (mawlā)", False, "high",
             "Maulana is Arabic مَوْلَانَا (Mawlānā) 'our master, our lord', a title formed from مَوْلَى (mawlā) with the first-person plural possessive. The source gloss 'Master, Owner' is broadly consistent. Recorded as a title rather than a personal name. Same name as mawlana."),
 "mausooma": ("معصومة", "معصومہ", "معصومه", "मासूमा", "معصومه", "innocent_f", "Arabic", "Female",
              "Arabic root ع ص م (ʿ-ṣ-m); مَعْصُومَة (Maʿṣūma)", False, "high",
              "Mausooma is Arabic مَعْصُومَة (Maʿṣūma) 'innocent, protected, sinless' (feminine), from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave the Latin string 'Mausooma' instead of an Arabic form and glossed it 'Mother of the Believers'; the correct form is مَعْصُومَة and the source gloss is unsupported. Same name as masooma and masuma."),
 "mawadda": ("مودة", "مودت", "مودت", "मवद्दत", "مودت", "love_mawadda", "Arabic", "Female",
             "Arabic root و د د (w-d-d); مَوَدَّة (Mawadda)", False, "high",
             "Mawadda is Arabic مَوَدَّة (Mawadda) 'love, affection, compassion', from the root و د د (w-d-d). The source gloss 'Love, Compassion' is consistent. Same name as mawaddah."),
 "mawaddah": ("مودة", "مودت", "مودت", "मवद्दा", "مودت", "love_mawadda", "Arabic", "Female",
              "Arabic root و د د (w-d-d); مَوَدَّة (Mawadda)", False, "high",
              "Mawaddah is Arabic مَوَدَّة (Mawadda) 'love, affection, compassion', from the root و د د (w-d-d). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as mawadda."),
 "mawar": ("موار", "موار", "موار", "मोवार", "موار", "abyss", "Arabic", "Female",
           "Arabic مَوَار (Mawār)", False, "low",
           "Mawar is recorded at low confidence. The source gloss 'Abyss, Ocean' is unsupported and no verified Arabic lexical form was established; مَوَار (Mawār) is a documented female given name, but its derivation could not be confirmed. No confident meaning is asserted."),
 "mawlana": ("مولانا", "مولانا", "مولانا", "मौलाना", "مولانا", "master", "Arabic", "Male",
             "Arabic مَوْلَانَا (Mawlānā), from مَوْلَى (mawlā)", False, "high",
             "Mawlana is Arabic مَوْلَانَا (Mawlānā) 'our master, our lord', a title formed from مَوْلَى (mawlā) with the first-person plural possessive. The source gloss 'Our Master' is consistent. Recorded as a title rather than a personal name. Same name as maulana."),
 "maya": ("مايا", "مایا", "مایا", "माया", "مایا", "maya", "Unknown", "Female",
          "No reliable root analysis established.", False, "low",
          "Maya is recorded at low confidence. The source record was an empty stub with no data. The form is widely used across several unrelated naming traditions (including Sanskrit, Greek and Latin sources), so no single origin or meaning is asserted here."),
 "mayada": ("مائدة", "مائدہ", "مائده", "मायदा", "مائده", "mayada", "Arabic", "Female",
            "Arabic مَائِدَة (Māʾida)", False, "high",
            "Mayada is Arabic مَائِدَة (Māʾida) 'table, table spread with food', a documented female given name. The source gloss 'Moon' is unsupported and has been replaced with the lexical sense."),
 "mayar": ("ميار", "ميار", "میار", "मैयर", "ميار", "mayar", "Arabic", "Female",
           "Arabic مَيَّار (Mayyār)", False, "medium",
           "Mayar is Arabic مَيَّار (Mayyār), a documented female given name. The source gloss 'Moon' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "mayed": ("مائد", "مائد", "مائد", "माइद", "مائد", "mayed", "Arabic", "Male",
           "Arabic مَائِد (Māʾid)", False, "medium",
           "Mayed is Arabic مَائِد (Māʾid), a documented male given name. The source gloss 'Luminous' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "maymun": ("ميمون", "میمون", "میمون", "मैमून", "میمون", "blessed", "Arabic", "Male",
            "Arabic root ي م ن (y-m-n); مَيْمُون (Maymūn)", False, "high",
            "Maymun is Arabic مَيْمُون (Maymūn) 'blessed, fortunate, auspicious', from the root ي م ن (y-m-n). The source gloss 'Beloved' is unsupported and has been replaced with the lexical sense. Same name as maymuna."),
 "maymuna": ("ميمونة", "میمونہ", "میمونه", "मैमूना", "میمونه", "blessed_f", "Arabic", "Female",
             "Arabic root ي م ن (y-m-n); مَيْمُونَة (Maymūna)", False, "high",
             "Maymuna is Arabic مَيْمُونَة (Maymūna) 'blessed, fortunate, auspicious' (feminine), from the root ي م ن (y-m-n). The source gloss 'Moon-like, Pleasing' is unsupported and has been replaced with the lexical sense. Same name as maymun."),
 "mays": ("ميس", "میس", "میس", "मैस", "میس", "mays", "Arabic", "Female",
          "Arabic مَيْس (Mays)", False, "medium",
          "Mays is Arabic مَيْس (Mays), a documented female given name. CRITICAL SOURCE ERROR: the source gave علي (a different name entirely) and glossed the name 'Mother of Abbas'; the correct form is مَيْس and the source gloss is unsupported. No confident lexical sense is asserted."),
 "maysa": ("ميساء", "میساء", "میساء", "मैसा", "میساء", "maysaa", "Arabic", "Female",
           "Arabic مَيْسَاء (Maysāʾ)", False, "medium",
           "Maysa is Arabic مَيْسَاء (Maysāʾ), a documented female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form has been established from the documented name. Same name as maysaa."),
 "maysaa": ("ميساء", "میساء", "میساء", "मैसा", "میساء", "maysaa", "Arabic", "Female",
            "Arabic مَيْسَاء (Maysāʾ)", False, "medium",
            "Maysaa is Arabic مَيْسَاء (Maysāʾ), a documented female given name. The source gloss 'Mother of Dew' is unsupported; the name is a proper name and no confident lexical sense is asserted. Same name as maysa."),
 "maysam": ("ميثم", "میثم", "میثم", "मैसम", "میثم", "maysam", "Arabic", "Male",
            "Arabic مَيْثَم (Maytham)", False, "high",
            "Maysam is Arabic مَيْثَم (Maytham), a documented male given name. CRITICAL SOURCE ERROR: the source gave ميسم (a different form) and glossed it 'Abode of Tranquility'; the correct form is مَيْثَم and the source gloss is unsupported. Same name as maytham."),
 "maysan": ("ميسان", "میسان", "میسان", "मैसान", "میسان", "maysan", "Arabic", "Unknown",
            "Arabic مَيْسَان (Maysān)", False, "medium",
            "Maysan is Arabic مَيْسَان (Maysān), a place name (a region in Iraq) also used as a given name. The source gloss 'A sanctuary, a place of refuge' is unsupported; no confident lexical sense is asserted."),
 "maysara": ("ميسرة", "میسرہ", "میسره", "मैसरा", "میسره", "ease", "Arabic", "Female",
             "Arabic root ي س ر (y-s-r); مَيْسَرَة (Maysara)", False, "high",
             "Maysara is Arabic مَيْسَرَة (Maysara) 'ease, facility, convenience', from the root ي س ر (y-s-r). The source gloss 'Easy-going, Gentle' is broadly consistent. Same name as maysarah."),
 "maysarah": ("ميسرة", "میسرہ", "میسره", "मैसरा", "میسره", "ease", "Arabic", "Female",
              "Arabic root ي س ر (y-s-r); مَيْسَرَة (Maysara)", False, "high",
              "Maysarah is Arabic مَيْسَرَة (Maysara) 'ease, facility, convenience', from the root ي س ر (y-s-r). The source gloss 'Abundance of joy' is unsupported and has been replaced with the lexical sense. Same name as maysara."),
 "maysoon": ("ميسون", "میسون", "میسون", "मैसून", "میسون", "maysoon", "Arabic", "Female",
             "Arabic مَيْسُون (Maysūn)", False, "high",
             "Maysoon is Arabic مَيْسُون (Maysūn), a documented female given name. The source gloss 'Moon' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "maytham": ("ميثم", "میثم", "میثم", "मैथम", "میثم", "maytham", "Arabic", "Male",
             "Arabic مَيْثَم (Maytham)", False, "high",
             "Maytham is Arabic مَيْثَم (Maytham), a documented male given name. The source gloss 'Compassionate and gentle' is unsupported; the name is a proper name and no confident lexical sense is asserted. Same name as maysam."),
 "mayyada": ("ميادة", "میادہ", "میاده", "माय्यादा", "میاده", "tender", "Arabic", "Female",
             "Arabic مَيَّادَة (Mayyāda)", False, "medium",
             "Mayyada is Arabic مَيَّادَة (Mayyāda), a documented female given name. The source gloss 'Tender, Delicate' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "mazahir": ("مظاهر", "مظاہر", "مظاهر", "मज़ाहिर", "مظاهر", "manifestations", "Arabic", "Male",
             "Plural of مَظْهَر; مَظَاهِر (Maẓāhir)", False, "high",
             "Mazahir is Arabic مَظَاهِر (Maẓāhir) 'manifestations, appearances, displays', the plural of مَظْهَر (maẓhar). The source gloss 'Manifestations, Appearances' is consistent."),
 "mazhar": ("مظهر", "مظہر", "مظهر", "मज़हर", "مظهر", "manifestation", "Arabic", "Male",
            "Arabic root ظ ه ر (ẓ-h-r); مَظْهَر (Maẓhar)", False, "high",
            "Mazhar is Arabic مَظْهَر (Maẓhar) 'manifestation, appearance, display', from the root ظ ه ر (ẓ-h-r). The source gloss 'Light, Illumination' is unsupported and has been replaced with the lexical sense."),
 "maziah": ("مازية", "مازیہ", "مازیه", "माज़िया", "مازیه", "maziah", "Arabic", "Female",
            "Arabic مَازِيَة (Māziya)", False, "medium",
            "Maziah is Arabic مَازِيَة (Māziya), a documented female given name. The source gloss 'Graceful' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "maziar": ("مازيار", "مازیار", "مازیار", "माज़ियार", "مازیار", "maziar", "Persian", "Male",
            "Persian مَازِيَار (Māziyār)", False, "high",
            "Maziar is the Persian male given name مَازِيَار (Māziyār). CRITICAL SOURCE ERROR: the source gave the Latin string 'Maziar' instead of a script form and labelled the origin Arabic; the name is Persian, not Arabic. The source gloss 'Wise, Intelligent, Brave' is unsupported; no confident lexical sense is asserted."),
 "mazid": ("مزيد", "مزید", "مزید", "मज़ीद", "مزید", "increase", "Arabic", "Male",
           "Arabic root ز ي د (z-y-d); مَزِيد (Mazīd)", False, "high",
           "Mazid is Arabic مَزِيد (Mazīd) 'increase, addition, abundance', from the root ز ي د (z-y-d). The source gloss 'Powerful' is unsupported and has been replaced with the lexical sense."),
 "mazin": ("مازن", "مازن", "مازن", "माज़िन", "مازن", "mazin", "Arabic", "Male",
           "Arabic مَازِن (Māzin)", False, "high",
           "Mazin is Arabic مَازِن (Māzin), a documented male given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form has been established from the documented name. No confident lexical sense is asserted."),
 "maznah": ("مزنة", "مزنہ", "مزنه", "मज़ना", "مزنه", "maznah", "Arabic", "Female",
            "Arabic مَزْنَة (Mazna)", False, "medium",
            "Maznah is Arabic مَزْنَة (Mazna), a documented female given name. The source gloss 'Refuge, Shelter' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "medina": ("مدينة", "مدینہ", "مدینه", "मदीना", "مدینه", "medina", "Arabic", "Female",
            "Arabic مَدِينَة (Madīna)", False, "high",
            "Medina is Arabic مَدِينَة (Madīna) 'city', and specifically the city of the Prophet in Arabia. The source gloss 'City of the Prophet' is broadly consistent. Recorded as a place name also used as a given name."),
 "meem": ("ميم", "میم", "میم", "मीम", "میم", "meem", "Arabic", "Unknown",
          "Arabic مِيم (Mīm)", False, "high",
          "Meem is Arabic مِيم (Mīm), the name of the Arabic letter m. The source gloss 'Letter M' is consistent. Recorded as a letter name rather than a personal name; no personal-name gender usage is asserted."),
 "meena": ("مينا", "مینا", "مینا", "मीना", "مینا", "meena", "Persian", "Female",
           "Persian مینا (Mīnā)", False, "high",
           "Meena is the Persian female given name مینا (Mīnā), also used in Urdu and Hindi. The source gloss 'Jasmine flower' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "meer": ("مير", "میر", "میر", "मीर", "میر", "meer", "Persian", "Male",
          "Persian مِير (Mīr)", False, "high",
          "Meer is the Persian title and male given name مِير (Mīr) 'chief, leader, prince', widely used in South Asia. The source gloss 'Prince, Noble, Leader' is broadly consistent. Recorded as a title also used as a given name."),
 "meera": ("ميرا", "میرا", "میرا", "मीरा", "میرا", "meera", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Meera is recorded at low confidence. The source gloss \"Prophet's companion\" is unsupported and no verified Arabic form was established; the name is widely used across several South Asian traditions, so no single origin or meaning is asserted here."),
 "meeran": ("ميران", "میران", "میران", "मीरान", "میران", "meeran", "Persian", "Male",
            "Persian مِيرَان (Mīrān)", False, "medium",
            "Meeran is the Persian/South Asian male given name مِيرَان (Mīrān), related to مِير (Mīr) 'chief, leader'. The source gloss 'Gentle, Radiant' is unsupported; no confident lexical sense is asserted."),
 "meeza": ("ميزا", "میزا", "میزا", "मीज़ा", "میزا", "meeza", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Meeza is recorded at low confidence. The source gave the Latin string 'Meeza' instead of an Arabic form and glossed it 'Gift from Allah'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "meezan": ("ميزان", "میزان", "میزان", "मीज़ान", "میزان", "balance", "Arabic", "Male",
            "Arabic root و ز ن (w-z-n); مِيزَان (Mīzān)", False, "high",
            "Meezan is Arabic مِيزَان (Mīzān) 'balance, scale, measure', from the root و ز ن (w-z-n). The source gloss 'Balance, Scale' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "meha": ("ميهة", "میہہ", "میهه", "मीहा", "میهه", "meha", "Unknown", "Female",
          "No reliable root analysis established.", False, "low",
          "Meha is recorded at low confidence. The source gloss 'Delight, Pleasure' is unsupported and no verified Arabic form was established; مِيهَة (Mīha) is a documented female given name, but its derivation could not be confirmed. No confident meaning is asserted."),
 "mehak": ("مهك", "مہک", "مهک", "मेहक", "مهک", "fragrance", "Persian", "Female",
           "Persian/Urdu مہک (Mahak)", False, "high",
           "Mehak is the Persian/Urdu female given name مہک (Mahak) 'fragrance, scent, aroma'. The source gloss 'Fragrance of Heaven' is unsupported and has been replaced with the lexical sense."),
 "mehar": ("مهار", "مہار", "مهار", "मेहर", "مهار", "mehar", "Persian", "Female",
           "Persian/Urdu مہر (Mihr)", False, "medium",
           "Mehar is the Persian/Urdu female given name مہر (Mihr), also meaning 'sun' and 'affection' in Persian. The source gloss 'Loving and Kind' is unsupported; no single confident lexical sense is asserted."),
 "mehboob": ("محبوب", "محبوب", "محبوب", "महबूब", "محبوب", "beloved_mehboob", "Arabic", "Male",
             "Arabic root ح ب ب (ḥ-b-b); مَحْبُوب (Maḥbūb)", False, "high",
             "Mehboob is Arabic مَحْبُوب (Maḥbūb) 'beloved, dear, loved one', from the root ح ب ب (ḥ-b-b). CRITICAL SOURCE ERROR: the source gave محب (a different form); the correct form is مَحْبُوب. The source gloss 'Beloved, Lover' is broadly consistent."),
 "mehd": ("مهد", "مہد", "مهد", "मेहद", "مهد", "mehd", "Arabic", "Male",
          "Arabic مَهْد (Mahd)", False, "medium",
          "Mehd is Arabic مَهْد (Mahd), a documented male given name. The source gloss 'Guide, Helper' is unsupported; the name is a proper name and no confident lexical sense is asserted. Same name as mehdi."),
 "mehdi": ("مهدي", "مہدی", "مهدی", "मेहदी", "مهدي", "guided", "Arabic", "Male",
           "Arabic root ه د ي (h-d-y); مَهْدِيّ (Mahdī)", False, "high",
           "Mehdi is Arabic مَهْدِيّ (Mahdī) 'guided, rightly directed', from the root ه د ي (h-d-y). CRITICAL SOURCE ERROR: the source gave مہدی (a Persian-script form) in the Arabic column; the correct Arabic form is مَهْدِيّ. The source gloss 'Guided One' is consistent."),
 "mehek": ("مهك", "مہک", "مهک", "मेहक", "مهک", "mehek", "Persian", "Female",
           "Persian/Urdu مہک (Mahak)", False, "high",
           "Mehek is the Persian/Urdu female given name مہک (Mahak) 'fragrance, scent, aroma'. The source gloss 'Glowing, Radiant' is unsupported and has been replaced with the lexical sense. Same name as mehak."),
 "meher": ("مهر", "مہر", "مهر", "मेहर", "مهر", "meher", "Persian", "Female",
           "Persian مِهْر (Mihr)", False, "medium",
           "Meher is the Persian female given name مِهْر (Mihr), also meaning 'sun' and 'affection' in Persian. CRITICAL SOURCE ERROR: the source gave عائشة (a different name entirely) and glossed the name 'Bountiful'; the correct form is مِهْر and the source gloss is unsupported. Same name as mehar."),
 "mehfooz": ("محفوظ", "محفوظ", "محفوظ", "मेहफ़ूज़", "محفوظ", "protected", "Arabic", "Male",
             "Arabic root ح ف ظ (ḥ-f-ẓ); مَحْفُوظ (Maḥfūẓ)", False, "high",
             "Mehfooz is Arabic مَحْفُوظ (Maḥfūẓ) 'protected, guarded, safe', from the root ح ف ظ (ḥ-f-ẓ). The source gloss 'Protected, Secure, Safe' is consistent."),
 "mehmet": ("محمد", "محمد", "محمد", "मेहमत", "محمد", "mehmet", "Turkish", "Male",
            "Turkish form of Arabic مُحَمَّد (Muḥammad)", False, "high",
            "Mehmet is the Turkish form of Arabic مُحَمَّد (Muḥammad) 'praised, commendable'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic and glossed the name 'Moon'; the name is Turkish in form and the source gloss is unsupported."),
 "mehmood": ("محمود", "محمود", "محمود", "महमूद", "محمود", "praised", "Arabic", "Male",
             "Arabic root ح م د (ḥ-m-d); مَحْمُود (Maḥmūd)", False, "high",
             "Mehmood is Arabic مَحْمُود (Maḥmūd) 'praised, commended, laudable', from the root ح م د (ḥ-m-d). The source gloss 'Gift, Generous' is unsupported and has been replaced with the lexical sense. Same name as mehmud."),
 "mehmud": ("محمود", "محمود", "محمود", "महमूद", "محمود", "praised", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); مَحْمُود (Maḥmūd)", False, "high",
            "Mehmud is Arabic مَحْمُود (Maḥmūd) 'praised, commended, laudable', from the root ح م د (ḥ-m-d). The source gloss 'Praised, Honored' is consistent. Same name as mehmood."),
 "mehnaz": ("مهناز", "مہناز", "مهناز", "मेहनाज़", "مهناز", "mehnaz", "Persian", "Female",
            "Persian مِهْنَاز (Mihnāz)", False, "high",
            "Mehnaz is the Persian female given name مِهْنَاز (Mihnāz), a compound of مِهْر/مِه (mihr/mih, 'sun, love') and نَاز (nāz, 'coquetry, charm'). CRITICAL SOURCE ERROR: the source gave ميهناز (a different form); the correct form is مِهْنَاز. The source gloss 'Grace, Delight, Beautiful' is broadly consistent."),
 "mehndi": ("حناء", "مہندی", "حنا", "मेहंदी", "مېندي", "henna", "Persian", "Unknown",
            "Persian/Urdu مہندی (Mehndī)", False, "high",
            "Mehndi is the Persian/Urdu word مہندی (Mehndī) 'henna, henna design'. The source gloss 'Henna Design' is consistent. Recorded as a common noun rather than a personal name; no personal-name gender usage is asserted."),
 "mehr": ("مهر", "مہر", "مهر", "मेहर", "مهر", "mehr", "Persian", "Female",
          "Persian مِهْر (Mihr)", False, "high",
          "Mehr is the Persian female given name مِهْر (Mihr) 'sun, love, affection'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic and glossed the name 'Gift'; the name is Persian and the source gloss is unsupported. Same name as mehar and meher."),
 "mehrab": ("محراب", "محراب", "محراب", "मेहराब", "محراب", "mihrab", "Arabic", "Male",
            "Arabic root ح ر ب (ḥ-r-b); مِحْرَاب (Miḥrāb)", False, "high",
            "Mehrab is Arabic مِحْرَاب (Miḥrāb) 'prayer niche, mihrab', from the root ح ر ب (ḥ-r-b). CRITICAL SOURCE ERROR: the source gave محرَب (a different form); the correct form is مِحْرَاب. The source gloss 'Prayer Niche or Altar' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "mehraban": ("مهربان", "مہربان", "مهربان", "मेहरबान", "مهربان", "kind", "Persian", "Male",
              "Persian مهربان (Mehrabān)", False, "high",
              "Mehraban is the Persian word and given name مهربان (Mehrabān) 'kind, loving, compassionate'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Kind and loving' is consistent."),
 "mehrad": ("مهراد", "مہراد", "مهراد", "मेहराद", "مهراد", "mehrad", "Persian", "Male",
            "Persian مهراد (Mehrād)", False, "medium",
            "Mehrad is the Persian male given name مهراد (Mehrād). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Radiant, Bright' is unsupported; no confident lexical sense is asserted."),
 "mehran": ("مهران", "مہران", "مهران", "मेहरान", "مهران", "mehran", "Persian", "Male",
            "Persian مهران (Mehrān)", False, "high",
            "Mehran is the Persian male given name مهران (Mehrān). CRITICAL SOURCE ERROR: the source gave مهرن (a different form) and labelled the origin Arabic; the correct form is مهران and the name is Persian. The source gloss 'Kind, Merciful' is unsupported; no confident lexical sense is asserted."),
 "mehrana": ("مهرانة", "مہرانہ", "مهرانه", "मेहराना", "مهرانه", "mehrana", "Persian", "Female",
             "Persian مهرانه (Mehrāna)", False, "medium",
             "Mehrana is the Persian female given name مهرانه (Mehrāna). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Radiant, shining light' is unsupported; no confident lexical sense is asserted."),
 "mehreen": ("مهرين", "مہرین", "مهرین", "मेहरीन", "مهرین", "mehreen", "Persian", "Female",
             "Persian مهرین (Mehrīn)", False, "medium",
             "Mehreen is the Persian female given name مهرین (Mehrīn). CRITICAL SOURCE ERROR: the source gave مهيرين (a different form) and labelled the origin Arabic; the correct form is مهرین and the name is Persian. The source gloss 'Moonlight' is unsupported; no confident lexical sense is asserted."),
 "mehri": ("مهري", "مہری", "مهری", "मेहरी", "مهری", "mehri", "Persian", "Female",
           "Persian مهری (Mehrī)", False, "medium",
           "Mehri is the Persian female given name مهری (Mehrī), related to مِهْر (mihr, 'sun, love'). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'One who shines, glows' is unsupported; no confident lexical sense is asserted."),
 "mehriban": ("مهربان", "مہربان", "مهربان", "मेहरीबान", "مهربان", "mehriban", "Persian", "Female",
              "Persian مهربان (Mehribān)", False, "high",
              "Mehriban is the Persian female given name مهربان (Mehribān) 'kind, loving, compassionate'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Beloved, dear' is broadly consistent."),
 "mehrin": ("مهرين", "مہرین", "مهرین", "मेहरीन", "مهرین", "mehrin", "Persian", "Female",
            "Persian مهرین (Mehrīn)", False, "medium",
            "Mehrin is the Persian female given name مهرین (Mehrīn). CRITICAL SOURCE ERROR: the source gave مهيرين (a different form) and labelled the origin Arabic; the correct form is مهرین and the name is Persian. The source gloss 'Filled with love and affection' is unsupported; no confident lexical sense is asserted."),
 "mehrnoush": ("مهرنوش", "مہرنوش", "مهرنوش", "मेहरनूश", "مهرنوش", "mehrnoush", "Persian", "Female",
               "Persian مهرنوش (Mehrnūsh)", False, "high",
               "Mehrnoush is the Persian female given name مهرنوش (Mehrnūsh), a compound of مِهْر (mihr, 'sun, love') and نوش (nūsh, 'nectar, sweet'). CRITICAL SOURCE ERROR: the source gave 'Aisha' (a different name entirely) and labelled the origin Arabic; the correct form is مهرنوش and the name is Persian. The source gloss 'Light of God' is unsupported."),
 "mehrsa": ("مهراسا", "مہرسا", "مهراسا", "मेहरसा", "مهراسا", "mehrsa", "Persian", "Female",
            "Persian مهراسا (Mehrāsā)", False, "low",
            "Mehrsa is recorded at low confidence. The source gave عائشة (a different name entirely) and labelled the origin Arabic; the name is Persian and no verified lexical form could be confirmed. No confident meaning is asserted."),
 "mehrtash": ("مهرتاش", "مہرتاش", "مهرتاش", "मेहरताश", "مهرتاش", "mehrtash", "Persian", "Male",
              "Persian مهرتاش (Mehrtāsh)", False, "medium",
              "Mehrtash is the Persian male given name مهرتاش (Mehrtāsh). CRITICAL SOURCE ERROR: the source gave مهارتاش (a different form) and labelled the origin Arabic; the correct form is مهرتاش and the name is Persian. The source gloss 'He who illuminates' is unsupported; no confident lexical sense is asserted."),
 "mehry": ("مهري", "مہری", "مهری", "मेहरी", "مهری", "mehry", "Persian", "Female",
           "Persian مهری (Mehrī)", False, "medium",
           "Mehry is the Persian female given name مهری (Mehrī), related to مِهْر (mihr, 'sun, love'). CRITICAL SOURCE ERROR: the source gave عائشة (a different name entirely) and labelled the origin Arabic; the correct form is مهری and the name is Persian. The source gloss 'Lady, noblewoman' is unsupported. Same name as mehri."),
 "mehtab": ("مهتاب", "مہتاب", "مهتاب", "मेहताब", "مهتاب", "moonlight", "Persian", "Female",
            "Persian مهتاب (Mahtāb)", False, "high",
            "Mehtab is the Persian word and given name مهتاب (Mahtāb) 'moonlight', a compound of ماه (māh, 'moon') and تاب (tāb, 'light, radiance'). CRITICAL SOURCE ERROR: the source gave ميهتاب (a different form) and labelled the origin Arabic; the correct form is مهتاب and the word is Persian. The source gloss 'Moon, Star, Night' is broadly consistent."),
 "mehvish": ("مهویش", "مہوش", "مهویش", "मेहविश", "مهویش", "mehvish", "Persian", "Female",
             "Persian مهویش (Mehvīsh)", False, "medium",
             "Mehvish is the Persian female given name مهویش (Mehvīsh). CRITICAL SOURCE ERROR: the source gave مهوش (a different form) and labelled the origin Arabic; the correct form is مهویش and the name is Persian. The source gloss 'A gift from God' is unsupported; no confident lexical sense is asserted."),
 "mehwish": ("مهویش", "مہوش", "مهویش", "मेहविश", "مهویش", "mehwish", "Persian", "Female",
             "Persian مهویش (Mehvīsh)", False, "medium",
             "Mehwish is the Persian female given name مهویش (Mehvīsh). CRITICAL SOURCE ERROR: the source gave ميهوش (a different form) and labelled the origin Arabic; the correct form is مهویش and the name is Persian. The source gloss 'Beautiful, Moon-like' is unsupported; no confident lexical sense is asserted. Same name as mehvish."),
 "melek": ("ملك", "ملک", "ملک", "मेलेक", "ملک", "melek", "Turkish", "Female",
           "Turkish melek, from Arabic مَلَك (malak)", False, "high",
           "Melek is the Turkish female given name melek 'angel', from Arabic مَلَك (malak). CRITICAL SOURCE ERROR: the source labelled the origin Arabic and glossed the name 'Queen, Lady'; the name is Turkish in form and the source gloss is unsupported."),
 "meltem": ("ملتم", "میلتیم", "ملتم", "मेल्तेम", "میلتیم", "meltem", "Turkish", "Female",
            "Turkish meltem", False, "high",
            "Meltem is the Turkish female given name meltem 'sea breeze'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Meltem' instead of a script form and labelled the origin Arabic; the name is Turkish and the source gloss 'Cool breeze' is broadly consistent."),
 "memoona": ("ميمونة", "میمونہ", "میمونه", "मैमूना", "میمونه", "memoona", "Arabic", "Female",
             "Arabic root ي م ن (y-m-n); مَيْمُونَة (Maymūna)", False, "high",
             "Memoona is Arabic مَيْمُونَة (Maymūna) 'blessed, fortunate, auspicious' (feminine), from the root ي م ن (y-m-n). CRITICAL SOURCE ERROR: the source gave أمنية (a different name entirely) and glossed the name 'Beloved'; the correct form is مَيْمُونَة and the source gloss is unsupported. Same name as maymuna."),
 "mensur": ("منصور", "منصور", "منصور", "मंसूर", "منصور", "mensur", "Turkish", "Male",
            "Turkish form of Arabic مَنْصُور (Manṣūr)", False, "high",
            "Mensur is the Turkish form of Arabic مَنْصُور (Manṣūr) 'victorious, aided', from the root ن ص ر (n-ṣ-r). CRITICAL SOURCE ERROR: the source labelled the origin Arabic and glossed the name 'Measurer'; the name is Turkish in form and the source gloss is unsupported."),
}
