# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 46 (najih..navid).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": namik -> Latin "namik"; namiq -> Latin
   "Namiq"; namaa -> "Nāmā" (Latin with diacritics); nardeen -> Latin "Nardeen";
   nareen -> Latin "Nareen"; narina -> Latin "Narina"; nasrin -> Latin "Nasrin";
   nasya -> Latin "Nasya"; nama -> عائشة (a different name);
   nakia -> نجحة; nashaat -> نشرت; nashat -> نشت; nasib -> ناصب;
   nasif -> ناسف; nasifa -> ناصفة; nasim -> نسم; nassima -> ناصيمة;
   nassira -> نصيرة; natheer -> ناثر; naushin -> ناوشين; naveen -> نافين.
 * EMPTY STUBS (8-key records, no data): najwa, naseem, nasir, nashwa.
 * MISLABELLED ORIGIN: narges/nargis/narjis (Persian), nasreen/nasrin (Persian),
   nastaran (Persian), naushad/nausheen/naushin (Persian), naveed/naveen/navid
   (Persian), narmeen/narmin/narmina (Persian), nardeen/nareen/narina (Persian),
   namik/namiq (Turkish), nanaa (a nursery word), nara (Japanese/other).
 * DEGARBLED GLOSSES: najih "Assistant, Helper", najiha "Guide, Helper",
   najihah "Successful", najiya "Guide, Light", najjar "Carrier, transporter",
   najla "Victorious, triumphant", najlaa "Gentle, Beautiful", najmeh "Star in the sky",
   najmu "Star", najwan "Victorious", najya "Victorious", nakia "Sweet",
   nama "Beloved", namaa "Nourishment, Support", namal "Fish", naman "Given by God",
   nameer "Observer, Watcher", namik "Sweet", namiq "Determined, Firm",
   namir "Comforter, Restorer, Consoler", namira "Night", namra "Restless, anxious, or troubled",
   nanaa "Nurse, caregiver", naoum "Comforter, Restorer", naqash "Skilled artist, craftsman",
   naqeeb "Leader, Officer", naqi "Purifier, Cleanser", naqib "Leader, Administrator",
   nara "Light, pleasant, or beautiful", nardeen "Light, Radiant", nareen "Light, Bright",
   narges "Daffodil flower", nargis "Daffodil flower", nariman "Light of the Faith",
   narina "Graceful, Beautiful", narjis "Daffodil flower", narmeen "Light of the moon",
   narmin "Light, Graceful", narmina "Light of the Faith", nasar "helper, supporter, victor",
   naseeb "Portion or Share", naseef "Gentle, Soft", naseera "Deliverer, Helper, Aid",
   naser "Victorious", nasha "Delight, Pleasure, Bliss", nashaat "Growth, Sprouting",
   nashat "Restraint, Prevention", nasheed "Song, Poem, Recitation", nashi "Pure, Chaste",
   nashid "Song, Melody, Recitation", nashida "Gentle whisper", nashir "Announcer, Messenger",
   nashira "Night Shining Star", nashwan "Intelligent, Wise, Knowledgeable",
   nasib "Fate, Destiny", nasiba "A reward, gift, or bounty", nasif "Gentle, Soft, Sensitive",
   nasifa "Given as a gift", nasih "Advice, Warning", nasiim "Gentle Wind", nasim "Wind",
   nasima "Delight, Pleasure", nasimah "Breeze or Zephyr", nasira "Protector, Defender",
   nasirah "Helper, Supporter", nasma "Fragrant Garden",
   nasooh "Given to the Prophet Yusuf (Joseph)", nasra "Victory, Helper, Aid",
   nasrat "Help or Assistance", nasreen "Wild Rose", nasri "Gift, blessing",
   nasrin "Victory, Triumph", nassah "Straight, honest", nassar "Victory, Triumph",
   nassim "Breeze, gentle wind", nassima "Promise, Pledge",
   nassir "Giver, Helper, Helper, Successor", nassira "Deliverer, Savior",
   nastaran "Jewel, treasure", nasuh "Righteous, obedient", nasya "Deliverer",
   natheer "Clear, Announcer", natiq "Speaker, Orator", naufal "Helper, Supporter",
   nauman "Comfort of Night", naureen "Light, Pleasing", naushad "Gifted advisor",
   nausheen "Night Shine", naushin "Helper, Supporter", naveed "Good News",
   naveen "Pure and Clean", navid "New, Delight, Young".
 * GENDER ERRORS: namal, nasib, nasrat, nashid, naushin, nasiim were labelled
   unisex where documented usage is male or the form is a common noun.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated45 import GLOSSES as _G45

GLOSSES = dict(_G45)
GLOSSES.update({
    "successful": {"en": "Successful, prosperous", "ur": "کامیاب، ناجح", "fa": "کامیاب، موفق", "hi": "सफल, कामयाब", "ps": "بریالی، کامیاب", "ar": "النَّاجِح، الْمُوَفَّق"},
    "successful_f": {"en": "Successful, prosperous (feminine)", "ur": "کامیاب (مؤنث)", "fa": "کامیاب (مؤنث)", "hi": "सफल (स्त्री)", "ps": "بریالې", "ar": "النَّاجِحَة، الْمُوَفَّقَة"},
    "carpenter": {"en": "Carpenter, woodworker", "ur": "نجار، بڑھئی", "fa": "نجار، درودگر", "hi": "नज्जार, बढ़ई", "ps": "نجار، ترکاڼ", "ar": "النَّجَّار، الْخَشَّاب"},
    "wide_eyed": {"en": "Wide-eyed, large-eyed (of a gazelle)", "ur": "نجلاء، کشادہ آنکھوں والی", "fa": "نجلاء، فراخ‌چشم", "hi": "नजला, चौड़ी आँखों वाली", "ps": "نجلاء، پراخې سترګې", "ar": "النَّجْلَاء، وَاسِعَة الْعَيْن"},
    "star_f": {"en": "Star (feminine)", "ur": "نجمہ، ستارہ", "fa": "نجمه، ستاره", "hi": "नजमा, तारा", "ps": "نجمه، ستوری", "ar": "النَّجْمَة، الْكَوْكَب"},
    "najwan": {"en": "Najwan; a male given name", "ur": "نجوان (مردانہ نام)", "fa": "نجوان (نام مردانه)", "hi": "नजवान (पुरुष नाम)", "ps": "نجوان (نر نوم)", "ar": "نَجْوَان (اسْم عَلَم مُذَكَّر)"},
    "pure_f": {"en": "Pure, clean (feminine)", "ur": "نقیہ، پاک، صاف", "fa": "نقیه، پاک", "hi": "नक़ीया, पवित्र", "ps": "نقیه، پاکه", "ar": "النَّقِيَّة، الطَّاهِرَة"},
    "growth": {"en": "Growth, increase, development", "ur": "نمو، بڑھوتری، ترقی", "fa": "نمو، رشد", "hi": "नमा, वृद्धि", "ps": "نمو، ودې", "ar": "النَّمَاء، الزِّيَادَة"},
    "ants": {"en": "Ants", "ur": "نمل، چیونٹیاں", "fa": "نمل، مورچگان", "hi": "नमल, चींटियाँ", "ps": "نمل، مېږي", "ar": "النَّمْل"},
    "pure_water": {"en": "Pure water; a panther", "ur": "نمیر، خالص پانی؛ چیتا", "fa": "نمیر، آب پاک", "hi": "नमीर, शुद्ध जल", "ps": "نمیر، پاک اوبه", "ar": "النَّمِير، الْمَاء الصَّافِي"},
    "namik": {"en": "Namik; a Turkish given name", "ur": "نامق (ترک نام)", "fa": "نامق (نام ترکی)", "hi": "नामिक (तुर्की नाम)", "ps": "نامق (ترکي نوم)", "ar": "نَامِق (اسْم عَلَم تُرْكِيّ)"},
    "namiq": {"en": "Namiq; a Turkish given name", "ur": "نامق (ترک نام)", "fa": "نامق (نام ترکی)", "hi": "नामिक़ (तुर्की नाम)", "ps": "نامق (ترکي نوم)", "ar": "نَامِق (اسْم عَلَم تُرْكِيّ)"},
    "namira": {"en": "Namira; a female given name", "ur": "نمیرہ (زنانہ نام)", "fa": "نمیره (نام زنانه)", "hi": "नमीरा (स्त्री नाम)", "ps": "نمیره (ښځينه نوم)", "ar": "نَمِيرَة (اسْم عَلَم مُؤَنَّث)"},
    "namra": {"en": "Namra; a female given name", "ur": "نمرہ (زنانہ نام)", "fa": "نمره (نام زنانه)", "hi": "नमरा (स्त्री नाम)", "ps": "نمره (ښځينه نوم)", "ar": "نَمْرَة (اسْم عَلَم مُؤَنَّث)"},
    "nana": {"en": "Nana; an affectionate name for a grandmother", "ur": "نانا، دادی/نانی کے لیے پیار کا نام", "fa": "نانا، نام محبت‌آمیز برای مادربزرگ", "hi": "नाना, दादी के लिए प्यार का नाम", "ps": "نانا، د انا لپاره د مینې نوم", "ar": "نَانَا (لَقَب تَحْبِيب لِلْجَدَّة)"},
    "naoum": {"en": "Naoum; a male given name", "ur": "نعوم (مردانہ نام)", "fa": "نعوم (نام مردانه)", "hi": "नऊम (पुरुष नाम)", "ps": "نعوم (نر نوم)", "ar": "نَعُوم (اسْم عَلَم مُذَكَّر)"},
    "naqash": {"en": "Naqash; painter, engraver, decorator", "ur": "نقاش، مصور، نقش بنانے والا", "fa": "نقاش، نگارگر", "hi": "नक़्क़ाश, चित्रकार", "ps": "نقاش، انځورګر", "ar": "النَّقَّاش، الْمُزَخْرِف"},
    "naqib": {"en": "Naqib; leader, chief, captain", "ur": "نقیب، سربراہ، سردار", "fa": "نقیب، سرکرده", "hi": "नक़ीब, नेता", "ps": "نقیب، مشر", "ar": "النَّقِيب، الرَّئِيس"},
    "naqi": {"en": "Naqi; pure, clean, clear", "ur": "نقی، پاک، صاف", "fa": "نقی، پاک", "hi": "नक़ी, पवित्र", "ps": "نقي، پاک", "ar": "النَّقِي، الطَّاهِر"},
    "nara": {"en": "Nara; a female given name", "ur": "نارہ (زنانہ نام)", "fa": "نارا (نام زنانه)", "hi": "नारा (स्त्री नाम)", "ps": "نارا (ښځينه نوم)", "ar": "نَارَة (اسْم عَلَم مُؤَنَّث)"},
    "nardeen": {"en": "Nardeen; a female given name", "ur": "نردین (زنانہ نام)", "fa": "نردین (نام زنانه)", "hi": "नर्दीन (स्त्री नाम)", "ps": "نردین (ښځينه نوم)", "ar": "نَرْدِين (اسْم عَلَم مُؤَنَّث)"},
    "nareen": {"en": "Nareen; a female given name", "ur": "نارین (زنانہ نام)", "fa": "نارین (نام زنانه)", "hi": "नारीन (स्त्री नाम)", "ps": "نارین (ښځينه نوم)", "ar": "نَارِين (اسْم عَلَم مُؤَنَّث)"},
    "narcissus": {"en": "Narcissus, daffodil", "ur": "نرگس، گل نرگس", "fa": "نرگس، گل نرگس", "hi": "नर्गिस, नरगिस का फूल", "ps": "نرګس، نرګس ګل", "ar": "النَّرْجِس"},
    "nariman": {"en": "Nariman; a male given name", "ur": "نریمان (مردانہ نام)", "fa": "نریمان (نام مردانه)", "hi": "नरीमान (पुरुष नाम)", "ps": "نریمان (نر نوم)", "ar": "نَرِيمَان (اسْم عَلَم مُذَكَّر)"},
    "narina": {"en": "Narina; a female given name", "ur": "نارینہ (زنانہ نام)", "fa": "نارینا (نام زنانه)", "hi": "नारीना (स्त्री नाम)", "ps": "نارینا (ښځينه نوم)", "ar": "نَارِينَة (اسْم عَلَم مُؤَنَّث)"},
    "narmeen": {"en": "Narmeen; a female given name", "ur": "نرمین (زنانہ نام)", "fa": "نرمین (نام زنانه)", "hi": "नर्मीन (स्त्री नाम)", "ps": "نرمین (ښځينه نوم)", "ar": "نَرْمِين (اسْم عَلَم مُؤَنَّث)"},
    "narmin": {"en": "Narmin; a female given name", "ur": "نارمین (زنانہ نام)", "fa": "نارمین (نام زنانه)", "hi": "नारमीन (स्त्री नाम)", "ps": "نارمین (ښځينه نوم)", "ar": "نَارْمِين (اسْم عَلَم مُؤَنَّث)"},
    "narmina": {"en": "Narmina; a female given name", "ur": "نرمینہ (زنانہ نام)", "fa": "نرمینه (نام زنانه)", "hi": "नर्मीना (स्त्री नाम)", "ps": "نرمینه (ښځينه نوم)", "ar": "نَرْمِينَة (اسْم عَلَم مُؤَنَّث)"},
    "share_portion": {"en": "Share, portion, lot", "ur": "نصیب، حصہ، قسمت", "fa": "نصیب، بهره", "hi": "नसीब, हिस्सा", "ps": "نصیب، برخه", "ar": "النَّصِيب، الْحَظّ"},
    "naseef": {"en": "Naseef; a male given name", "ur": "نصیف (مردانہ نام)", "fa": "نصیف (نام مردانه)", "hi": "नसीफ़ (पुरुष नाम)", "ps": "نصیف (نر نوم)", "ar": "نَصِيف (اسْم عَلَم مُذَكَّر)"},
    "breeze": {"en": "Breeze, gentle wind", "ur": "نسیم، ہلکی ہوا", "fa": "نسیم، باد ملایم", "hi": "नसीम, हल्की हवा", "ps": "نسیم، نرمه باد", "ar": "النَّسِيم، الرِّيح اللَّطِيفَة"},
    "nasha": {"en": "Nasha; a female given name", "ur": "نشا (زنانہ نام)", "fa": "نشا (نام زنانه)", "hi": "नशा (स्त्री नाम)", "ps": "نشا (ښځينه نوم)", "ar": "نَشَا (اسْم عَلَم مُؤَنَّث)"},
    "activity": {"en": "Activity, liveliness, energy", "ur": "نشاط، چستی، پھرتی", "fa": "نشاط، سرزندگی", "hi": "नशात, सक्रियता", "ps": "نشاط، ژوند تېری", "ar": "النَّشَاط، الْحَيَوِيَّة"},
    "anthem": {"en": "Anthem, song, recitation", "ur": "نشید، گیت، ترانہ", "fa": "نشید، سرود", "hi": "नशीद, गीत", "ps": "نشید، سندره", "ar": "النَّشِيد، الْأُنْشُودَة"},
    "nashi": {"en": "Nashi; a male given name", "ur": "ناشی (مردانہ نام)", "fa": "ناشی (نام مردانه)", "hi": "नाशी (पुरुष नाम)", "ps": "ناشي (نر نوم)", "ar": "نَاشِي (اسْم عَلَم مُذَكَّر)"},
    "nashida": {"en": "Nashida; a female given name", "ur": "نشیدہ (زنانہ نام)", "fa": "نشیده (نام زنانه)", "hi": "नशीदा (स्त्री नाम)", "ps": "نشیده (ښځينه نوم)", "ar": "نَشِيدَة (اسْم عَلَم مُؤَنَّث)"},
    "publisher": {"en": "Publisher, spreader, announcer", "ur": "ناشر، پھیلانے والا، اعلان کرنے والا", "fa": "ناشر، پخش‌کننده", "hi": "नाशिर, प्रकाशक", "ps": "ناشر، خپرونکی", "ar": "النَّاشِر، الْمُذِيع"},
    "nashira": {"en": "Nashira; a female given name", "ur": "ناشرہ (زنانہ نام)", "fa": "ناشره (نام زنانه)", "hi": "नाशिरा (स्त्री नाम)", "ps": "ناشره (ښځينه نوم)", "ar": "نَاشِرَة (اسْم عَلَم مُؤَنَّث)"},
    "nashwa": {"en": "Nashwa; ecstasy, elation", "ur": "نشوہ، سرور، مستی", "fa": "نشوه، سرخوشی", "hi": "नशवा, उल्लास", "ps": "نشوه، خوښي", "ar": "النَّشْوَة، الطَّرَب"},
    "nashwan": {"en": "Nashwan; elated, joyful", "ur": "نشوان، سرور میں، خوش", "fa": "نشوان، سرخوش", "hi": "नशवान, प्रसन्न", "ps": "نشوان، خوښ", "ar": "النَّشْوَان، الْمَسْرُور"},
    "nasiba": {"en": "Nasiba; share, portion (feminine)", "ur": "نصیبہ، حصہ (مؤنث)", "fa": "نصیبه، بهره (مؤنث)", "hi": "नसीबा, हिस्सा (स्त्री)", "ps": "نصیبه، برخه", "ar": "النَّصِيبَة، الْحَظّ"},
    "nasif": {"en": "Nasif; just, equitable", "ur": "نصیف، منصف، انصاف والا", "fa": "نصیف، دادگر", "hi": "नसीफ़, न्यायी", "ps": "نصیف، انصاف کوونکی", "ar": "النَّصِيف، الْمُنْصِف"},
    "nasifa": {"en": "Nasifa; just, equitable (feminine)", "ur": "نصیفہ، منصف (مؤنث)", "fa": "نصیفه، دادگر (مؤنث)", "hi": "नसीफ़ा, न्यायी (स्त्री)", "ps": "نصیفه، انصاف کوونکې", "ar": "النَّصِيفَة، الْمُنْصِفَة"},
    "nasima": {"en": "Nasima; breeze, gentle wind (feminine)", "ur": "نسیمہ، ہلکی ہوا (مؤنث)", "fa": "نسیمه، باد ملایم (مؤنث)", "hi": "नसीमा, हल्की हवा (स्त्री)", "ps": "نسیمه، نرمه باد", "ar": "النَّسِيمَة، الرِّيح اللَّطِيفَة"},
    "nasma": {"en": "Nasma; a breeze, a breath", "ur": "نسمہ، ہلکی ہوا", "fa": "نسمه، نسیم", "hi": "नसमा, हल्की हवा", "ps": "نسمه، نرمه باد", "ar": "النَّسْمَة، النَّسِيم"},
    "nasuh": {"en": "Nasuh; sincere, faithful adviser", "ur": "نصوح، مخلص، خیر خواہ", "fa": "نصوح، خیرخواه", "hi": "नसूह, निष्ठावान", "ps": "نصوح، مخلص", "ar": "النَّصُوح، الْمُخْلِص"},
    "victory": {"en": "Victory, triumph, help", "ur": "نصر، فتح، مدد", "fa": "نصر، پیروزی", "hi": "नस्र, विजय", "ps": "نصر، بریا", "ar": "النَّصْر، الْفَتْح"},
    "nasra": {"en": "Nasra; victory, help (feminine)", "ur": "نصرہ، فتح، مدد (مؤنث)", "fa": "نصره، پیروزی (مؤنث)", "hi": "नसरा, विजय (स्त्री)", "ps": "نصره، بریا", "ar": "النَّصْرَة، الْغَوْث"},
    "nasrat": {"en": "Nasrat; help, assistance", "ur": "نصرت، مدد، امداد", "fa": "نصرت، یاری", "hi": "नुसरत, सहायता", "ps": "نصرت، مرسته", "ar": "النُّصْرَة، الْغَوْث"},
    "nasreen": {"en": "Nasreen; wild rose, narcissus", "ur": "نسرین، گل نرگس", "fa": "نسرین، گل نرگس", "hi": "नसरीन, जंगली गुलाब", "ps": "نسرین، نرګس ګل", "ar": "النَّسْرِين"},
    "nasri": {"en": "Nasri; of victory, victorious", "ur": "نصری، فتح سے منسوب", "fa": "نصری، منسوب به پیروزی", "hi": "नसरी, विजय से संबंधित", "ps": "نصري، د بریا اړوند", "ar": "النَّصْرِي، مَنْسُوب إِلَى النَّصْر"},
    "nassah": {"en": "Nassah; sincere adviser", "ur": "نصاح، مخلص مشورہ دینے والا", "fa": "نصاح، خیرخواه", "hi": "नस्साह, निष्ठावान सलाहकार", "ps": "نصاح، مخلص سلاکار", "ar": "النَّصَّاح، النَّاصِح"},
    "nassar": {"en": "Nassar; helper, supporter", "ur": "نصار، مددگار، حامی", "fa": "نصار، یاری‌کننده", "hi": "नस्सार, सहायक", "ps": "نصار، مرستندوی", "ar": "النَّصَّار، النَّاصِر"},
    "nassira": {"en": "Nassira; helper, supporter (feminine)", "ur": "نصیرہ، مددگار (مؤنث)", "fa": "نصیره، یاری‌کننده (مؤنث)", "hi": "नसीरा, सहायिका", "ps": "نصیره، مرستندوې", "ar": "النَّصِيرَة، النَّاصِرَة"},
    "nastaran": {"en": "Nastaran; wild rose", "ur": "نسترن، جنگلی گلاب", "fa": "نسترن، گل سرخ وحشی", "hi": "नस्तरन, जंगली गुलाब", "ps": "نسترن، وحشي ګلاب", "ar": "النَّسْتَرَن (الْوَرْد الْبَرِّيّ)"},
    "nasya": {"en": "Nasya; a female given name", "ur": "ناسیہ (زنانہ نام)", "fa": "ناسیه (نام زنانه)", "hi": "नास्या (स्त्री नाम)", "ps": "ناسیه (ښځينه نوم)", "ar": "نَاسِيَة (اسْم عَلَم مُؤَنَّث)"},
    "speaker": {"en": "Speaker, orator, one who articulates", "ur": "ناطق، بولنے والا، خطیب", "fa": "ناطق، سخنران", "hi": "नातिक़, वक्ता", "ps": "ناطق، ویناوال", "ar": "النَّاطِق، الْخَطِيب"},
    "naufal": {"en": "Naufal; a male given name", "ur": "نوفل (مردانہ نام)", "fa": "نوفل (نام مردانه)", "hi": "नौफ़ल (पुरुष नाम)", "ps": "نوفل (نر نوم)", "ar": "نَوْفَل (اسْم عَلَم مُذَكَّر)"},
    "naureen": {"en": "Naureen; light, luminous", "ur": "نورین، روشن، نور والی", "fa": "نورین، نورانی", "hi": "नौरीन, प्रकाशमान", "ps": "نورین، روښانه", "ar": "نُورِين، الْمُنِيرَة"},
    "naushad": {"en": "Naushad; happy, joyful", "ur": "نوشاد، خوش، شادمان", "fa": "نوشاد، خوشحال", "hi": "नौशाद, प्रसन्न", "ps": "نوشاد، خوشحاله", "ar": "نَوْشَاد، الْمَسْرُور"},
    "nausheen": {"en": "Nausheen; sweet, pleasant", "ur": "نوشین، شیریں، خوشگوار", "fa": "نوشین، شیرین", "hi": "नौशीन, मधुर", "ps": "نوشین، خوږ", "ar": "نَوْشِين، الْحُلْو"},
    "good_news": {"en": "Good news, glad tidings", "ur": "نوید، خوشخبری، بشارت", "fa": "نوید، مژده", "hi": "नवीद, शुभ समाचार", "ps": "نوید، زېری", "ar": "النَّوِيد، الْبُشْرَى"},
    "new_fresh": {"en": "New, fresh, young", "ur": "نیا، تازہ، جوان", "fa": "نو، تازه", "hi": "नया, ताज़ा", "ps": "نوی، تازه", "ar": "الْجَدِيد، الطَّرِيّ"},
})

CUR = {
 "najih": ("نَاجِح", "ناجح", "ناجح", "नाजिह", "ناجح", "successful", "Arabic", "Male",
           "Arabic root ن ج ح (n-j-ḥ); نَاجِح (Nājiḥ)", False, "high",
           "Najih is Arabic نَاجِح (Nājiḥ) 'successful, prosperous', from the root ن ج ح (n-j-ḥ). The source gloss 'Assistant, Helper' is unsupported and has been replaced with the lexical sense. Same name as naajih."),
 "najiha": ("نَاجِحَة", "ناجحہ", "ناجحه", "नाजिहा", "ناجحه", "successful_f", "Arabic", "Female",
            "Arabic root ن ج ح (n-j-ḥ); نَاجِحَة (Nājiḥa)", False, "high",
            "Najiha is Arabic نَاجِحَة (Nājiḥa) 'successful' (feminine), from the root ن ج ح (n-j-ḥ). The source gloss 'Guide, Helper' is unsupported and has been replaced with the lexical sense."),
 "najihah": ("نَاجِحَة", "ناجحہ", "ناجحه", "नाजिहा", "ناجحه", "successful_f", "Arabic", "Female",
             "Arabic root ن ج ح (n-j-ḥ); نَاجِحَة (Nājiḥa)", False, "high",
             "Najihah is Arabic نَاجِحَة (Nājiḥa) 'successful' (feminine), from the root ن ج ح (n-j-ḥ). The source gloss 'Successful' is consistent. Same name as najiha."),
 "najiya": ("نَاجِيَة", "ناجیہ", "ناجیه", "नाजिया", "ناجیه", "najiah", "Arabic", "Female",
            "Arabic root ن ج و (n-j-w); نَاجِيَة (Nājiya)", False, "high",
            "Najiya is Arabic نَاجِيَة (Nājiya) 'one who is saved' (feminine), from the root ن ج و (n-j-w). The source gloss 'Guide, Light' is unsupported and has been replaced with the lexical sense. Same name as najiah."),
 "najjar": ("نَجَّار", "نجار", "نجار", "नज्जार", "نجار", "carpenter", "Arabic", "Male",
            "Arabic root ن ج ر (n-j-r); نَجَّار (Najjār)", False, "high",
            "Najjar is Arabic نَجَّار (Najjār) 'carpenter, woodworker', from the root ن ج ر (n-j-r). The source gloss 'Carrier, transporter' is unsupported and has been replaced with the lexical sense."),
 "najla": ("نَجْلَاء", "نجلاء", "نجلاء", "नजला", "نجلاء", "wide_eyed", "Arabic", "Female",
           "Arabic root ن ج ل (n-j-l); نَجْلَاء (Najlāʾ)", False, "high",
           "Najla is Arabic نَجْلَاء (Najlāʾ) 'wide-eyed, large-eyed (of a gazelle)', from the root ن ج ل (n-j-l). The source gloss 'Victorious, triumphant' is unsupported and has been replaced with the lexical sense. Same name as najlaa."),
 "najlaa": ("نَجْلَاء", "نجلاء", "نجلاء", "नजला", "نجلاء", "wide_eyed", "Arabic", "Female",
            "Arabic root ن ج ل (n-j-l); نَجْلَاء (Najlāʾ)", False, "high",
            "Najlaa is Arabic نَجْلَاء (Najlāʾ) 'wide-eyed, large-eyed', from the root ن ج ل (n-j-l). The source gloss 'Gentle, Beautiful' is unsupported and has been replaced with the lexical sense. Same name as najla."),
 "najm": ("نَجْم", "نجم", "نجم", "नजम", "نجم", "najam", "Arabic", "Male",
          "Arabic root ن ج م (n-j-m); نَجْم (Najm)", False, "high",
          "Najm is Arabic نَجْم (Najm) 'star', from the root ن ج م (n-j-m). The source gloss 'Star' is consistent. Same name as najam."),
 "najma": ("نَجْمَة", "نجمہ", "نجمه", "नजमा", "نجمه", "star_f", "Arabic", "Female",
           "Arabic root ن ج م (n-j-m); نَجْمَة (Najma)", False, "high",
           "Najma is Arabic نَجْمَة (Najma) 'star' (feminine), from the root ن ج م (n-j-m). The source gloss 'Star' is consistent."),
 "najmeh": ("نَجْمَة", "نجمہ", "نجمه", "नजमा", "نجمه", "star_f", "Arabic", "Female",
            "Arabic root ن ج م (n-j-m); نَجْمَة (Najma)", False, "high",
            "Najmeh is a Persian-influenced spelling of Arabic نَجْمَة (Najma) 'star', from the root ن ج م (n-j-m). The source gloss 'Star in the sky' is broadly consistent. Same name as najma."),
 "najmu": ("نَجْم", "نجم", "نجم", "नजम", "نجم", "najam", "Arabic", "Male",
           "Arabic root ن ج م (n-j-m); نَجْم (Najm)", False, "high",
           "Najmu is a spelling variant of Arabic نَجْم (Najm) 'star', from the root ن ج م (n-j-m). The source gloss 'Star' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as najm."),
 "najwa": ("نَجْوَى", "نجویٰ", "نجوا", "नजवा", "نجوا", "nagwa", "Arabic", "Female",
           "Arabic root ن ج و (n-j-w); نَجْوَى (Najwā)", False, "high",
           "Najwa is Arabic نَجْوَى (Najwā) 'secret conversation, whispering', from the root ن ج و (n-j-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nagwa."),
 "najwan": ("نَجْوَان", "نجوان", "نجوان", "नजवान", "نجوان", "najwan", "Arabic", "Male",
            "Arabic نَجْوَان (Najwān)", False, "medium",
            "Najwan is recorded as Arabic نَجْوَان (Najwān), a male given name. The source gloss 'Victorious' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "najya": ("نَجِيَّة", "نجیہ", "نجیه", "नजया", "نجیه", "najiah", "Arabic", "Female",
           "Arabic root ن ج و (n-j-w); نَجِيَّة (Najiyya)", False, "high",
           "Najya is Arabic نَجِيَّة (Najiyya) 'one who is saved' (feminine), from the root ن ج و (n-j-w). The source gloss 'Victorious' is unsupported and has been replaced with the lexical sense. Same name as najiah."),
 "nakia": ("نَقِيَّة", "نقیہ", "نقیه", "नक़ीया", "نقیه", "pure_f", "Arabic", "Female",
           "Arabic root ن ق و (n-q-w); نَقِيَّة (Naqiyya)", False, "high",
           "Nakia is Arabic نَقِيَّة (Naqiyya) 'pure, clean' (feminine), from the root ن ق و (n-q-w). CRITICAL SOURCE ERROR: the source gave نجحة (a different form); the correct form is نَقِيَّة. The source gloss 'Sweet' is unsupported and has been replaced with the lexical sense."),
 "nama": ("نَمَاء", "نماء", "نماء", "नमा", "نماء", "growth", "Arabic", "Female",
          "Arabic root ن م و (n-m-w); نَمَاء (Namāʾ)", False, "high",
          "Nama is recorded here as Arabic نَمَاء (Namāʾ) 'growth, increase', from the root ن م و (n-m-w). CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and glossed the name 'Beloved'; the source gloss is unsupported. Same name as namaa."),
 "namaa": ("نَمَاء", "نماء", "نماء", "नमा", "نماء", "growth", "Arabic", "Female",
           "Arabic root ن م و (n-m-w); نَمَاء (Namāʾ)", False, "high",
           "Namaa is Arabic نَمَاء (Namāʾ) 'growth, increase, development', from the root ن م و (n-m-w). CRITICAL SOURCE ERROR: the source gave 'Nāmā' (Latin with diacritics) instead of a script form. The source gloss 'Nourishment, Support' is unsupported and has been replaced with the lexical sense. Same name as nama."),
 "namal": ("نَمْل", "نمل", "نمل", "नमल", "نمل", "ants", "Arabic", "Male",
           "Arabic root ن م ل (n-m-l); نَمْل (Naml)", False, "high",
           "Namal is Arabic نَمْل (Naml) 'ants', from the root ن م ل (n-m-l); it is a Qur'anic sura name. The source gloss 'Fish' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "naman": ("نُعْمَان", "نعمان", "نعمان", "नअमान", "نعمان", "naaman", "Arabic", "Male",
           "Arabic نُعْمَان (Nuʿmān)", False, "high",
           "Naman is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. The source gloss 'Given by God' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "nameer": ("نَمِير", "نمیر", "نمیر", "नमीर", "نمیر", "pure_water", "Arabic", "Male",
            "Arabic root ن م ر (n-m-r); نَمِير (Namīr)", False, "high",
            "Nameer is Arabic نَمِير (Namīr) 'pure water; a panther', from the root ن م ر (n-m-r). The source gloss 'Observer, Watcher' is unsupported and has been replaced with the lexical sense. Same name as namir."),
 "namik": ("نَامِق", "نامق", "نامق", "नामिक", "نامق", "namik", "Turkish", "Male",
           "Turkish Nâmık, from Arabic نَامِق (Nāmiq)", False, "high",
           "Namik is the Turkish form of Arabic نَامِق (Nāmiq), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'namik' instead of a script form and labelled the origin Arabic; the name as spelled is Turkish. The source gloss 'Sweet' is unsupported; no confident lexical sense is asserted. Same name as namiq."),
 "namiq": ("نَامِق", "نامق", "نامق", "नामिक़", "نامق", "namiq", "Turkish", "Male",
           "Turkish Nâmık, from Arabic نَامِق (Nāmiq)", False, "high",
           "Namiq is the Turkish form of Arabic نَامِق (Nāmiq), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Namiq' instead of a script form and labelled the origin Arabic; the name as spelled is Turkish. The source gloss 'Determined, Firm' is unsupported; no confident lexical sense is asserted. Same name as namik."),
 "namir": ("نَمِير", "نمیر", "نمیر", "नमीर", "نمیر", "pure_water", "Arabic", "Male",
           "Arabic root ن م ر (n-m-r); نَمِير (Namīr)", False, "high",
           "Namir is Arabic نَمِير (Namīr) 'pure water; a panther', from the root ن م ر (n-m-r). The source gloss 'Comforter, Restorer, Consoler' is unsupported and has been replaced with the lexical sense. Same name as nameer."),
 "namira": ("نَمِيرَة", "نمیرہ", "نمیره", "नमीरा", "نمیره", "namira", "Arabic", "Female",
            "Arabic نَمِيرَة (Namīra)", False, "medium",
            "Namira is recorded as Arabic نَمِيرَة (Namīra), a female given name. CRITICAL SOURCE ERROR: the source gave ناميرة (a non-standard form). The source gloss 'Night' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "namra": ("نَمْرَة", "نمرہ", "نمره", "नमरा", "نمره", "namra", "Arabic", "Female",
           "Arabic نَمْرَة (Namra)", False, "medium",
           "Namra is recorded as Arabic نَمْرَة (Namra), a female given name. CRITICAL SOURCE ERROR: the source gave نامرة (a non-standard form). The source gloss 'Restless, anxious, or troubled' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nanaa": ("نَانَا", "نانا", "نانا", "नाना", "نانا", "nana", "Arabic", "Female",
           "Arabic نَانَا (Nānā), an affectionate name", False, "medium",
           "Nanaa is recorded as Arabic نَانَا (Nānā), an affectionate name for a grandmother. The source gloss 'Nurse, caregiver' is broadly consistent. Recorded as a term of endearment rather than a lexical given name."),
 "naoum": ("نَعُوم", "نعوم", "نعوم", "नऊम", "نعوم", "naoum", "Arabic", "Male",
           "Arabic نَعُوم (Naʿūm)", False, "medium",
           "Naoum is recorded as Arabic نَعُوم (Naʿūm), a male given name. The source gloss 'Comforter, Restorer' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "naqash": ("نَقَّاش", "نقاش", "نقاش", "नक़्क़ाश", "نقاش", "naqash", "Arabic", "Male",
            "Arabic root ن ق ش (n-q-sh); نَقَّاش (Naqqāsh)", False, "high",
            "Naqash is Arabic نَقَّاش (Naqqāsh) 'painter, engraver, decorator', from the root ن ق ش (n-q-sh). The source gloss 'Skilled artist, craftsman' is broadly consistent."),
 "naqeeb": ("نَقِيب", "نقیب", "نقیب", "नक़ीब", "نقیب", "naqib", "Arabic", "Male",
            "Arabic root ن ق ب (n-q-b); نَقِيب (Naqīb)", False, "high",
            "Naqeeb is Arabic نَقِيب (Naqīb) 'leader, chief, captain', from the root ن ق ب (n-q-b). The source gloss 'Leader, Officer' is consistent. Same name as naqib."),
 "naqi": ("نَقِي", "نقی", "نقی", "नक़ी", "نقي", "naqi", "Arabic", "Male",
          "Arabic root ن ق و (n-q-w); نَقِي (Naqī)", False, "high",
          "Naqi is Arabic نَقِي (Naqī) 'pure, clean, clear', from the root ن ق و (n-q-w). The source gloss 'Purifier, Cleanser' is broadly consistent."),
 "naqib": ("نَقِيب", "نقیب", "نقیب", "नक़ीब", "نقیب", "naqib", "Arabic", "Male",
           "Arabic root ن ق ب (n-q-b); نَقِيب (Naqīb)", False, "high",
           "Naqib is Arabic نَقِيب (Naqīb) 'leader, chief, captain', from the root ن ق ب (n-q-b). The source gloss 'Leader, Administrator' is consistent. Same name as naqeeb."),
 "nara": ("نَارَة", "نارہ", "ناره", "नारा", "ناره", "nara", "Arabic", "Female",
          "Arabic نَارَة (Nāra)", False, "medium",
          "Nara is recorded as Arabic نَارَة (Nāra), a female given name. The source gloss 'Light, pleasant, or beautiful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nardeen": ("نَرْدِين", "نردین", "نردین", "नर्दीन", "نردین", "nardeen", "Persian", "Female",
             "Persian نردین (nardīn)", False, "medium",
             "Nardeen is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nardeen' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Light, Radiant' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nareen": ("نَارِين", "نارین", "نارین", "नारीन", "نارین", "nareen", "Persian", "Female",
            "Persian نارین (nārīn)", False, "medium",
            "Nareen is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nareen' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Light, Bright' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "narges": ("نَرْگِس", "نرگس", "نرگس", "नर्गिस", "نرګس", "narcissus", "Persian", "Female",
            "Persian نرگس (narges)", False, "high",
            "Narges is Persian نرگس (narges) 'narcissus, daffodil'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Daffodil flower' is consistent. Same name as nargis."),
 "nargis": ("نَرْجِس", "نرگس", "نرگس", "नर्गिस", "نرګس", "narcissus", "Persian", "Female",
            "Persian نرگس (narges); Arabic نَرْجِس (narjis)", False, "high",
            "Nargis is Persian نرگس (narges) / Arabic نَرْجِس (narjis) 'narcissus, daffodil'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian in origin. The source gloss 'Daffodil flower' is consistent. Same name as narges."),
 "nariman": ("نَرِيمَان", "نریمان", "نریمان", "नरीमान", "نریمان", "nariman", "Persian", "Male",
             "Persian نریمان (narīmān)", False, "high",
             "Nariman is Persian نریمان (narīmān), a male given name borne by a hero of the Shahnameh. CRITICAL SOURCE ERROR: the source labelled the origin Arabic. The source gloss 'Light of the Faith' is unsupported and has been replaced with the documented identification."),
 "narina": ("نَارِينَة", "نارینہ", "نارینا", "नारीना", "نارینا", "narina", "Persian", "Female",
            "Persian نارین (nārīn) + feminine ending", False, "medium",
            "Narina is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Narina' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Graceful, Beautiful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "narjis": ("نَرْجِس", "نرگس", "نرگس", "नर्जिस", "نرګس", "narcissus", "Persian", "Female",
            "Persian نرگس (narges); Arabic نَرْجِس (narjis)", False, "high",
            "Narjis is Arabic نَرْجِس (narjis) / Persian نرگس (narges) 'narcissus, daffodil'. The source gloss 'Daffodil flower' is consistent. Same name as nargis."),
 "narmeen": ("نَرْمِين", "نرمین", "نرمین", "नर्मीन", "نرمین", "narmeen", "Persian", "Female",
             "Persian نرمین (narmīn)", False, "medium",
             "Narmeen is a Persian female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Light of the moon' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "narmin": ("نَارْمِين", "نارمین", "نارمین", "नारमीन", "نارمین", "narmin", "Persian", "Female",
            "Persian نارمین (nārmīn)", False, "medium",
            "Narmin is a Persian female given name. CRITICAL SOURCE ERROR: the source gave نارمين (a non-standard form) and labelled the origin Arabic; the name is Persian. The source gloss 'Light, Graceful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as narmeen."),
 "narmina": ("نَرْمِينَة", "نرمینہ", "نرمینه", "नर्मीना", "نرمینه", "narmina", "Persian", "Female",
             "Persian نرمین (narmīn) + feminine ending", False, "medium",
             "Narmina is a Persian female given name. CRITICAL SOURCE ERROR: the source gave نرمينة (a non-standard form) and labelled the origin Arabic; the name is Persian. The source gloss 'Light of the Faith' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nasar": ("نَصْر", "نصر", "نصر", "नसर", "نصر", "victory", "Arabic", "Male",
           "Arabic root ن ص ر (n-ṣ-r); نَصْر (Naṣr)", False, "high",
           "Nasar is a spelling variant of Arabic نَصْر (Naṣr) 'victory, triumph', from the root ن ص ر (n-ṣ-r). CRITICAL SOURCE ERROR: the source gave نسر (a different form); the correct form is نَصْر. The source gloss 'helper, supporter, victor' is broadly consistent. Same name as nasr."),
 "naseeb": ("نَصِيب", "نصیب", "نصیب", "नसीब", "نصیب", "share_portion", "Arabic", "Male",
            "Arabic root ن ص ب (n-ṣ-b); نَصِيب (Naṣīb)", False, "high",
            "Naseeb is Arabic نَصِيب (Naṣīb) 'share, portion, lot', from the root ن ص ب (n-ṣ-b). The source gloss 'Portion or Share' is consistent. Same name as nasib."),
 "naseef": ("نَصِيف", "نصیف", "نصیف", "नसीफ़", "نصیف", "naseef", "Arabic", "Male",
            "Arabic root ن ص ف (n-ṣ-f); نَصِيف (Naṣīf)", False, "high",
            "Naseef is Arabic نَصِيف (Naṣīf) 'just, equitable', from the root ن ص ف (n-ṣ-f). The source gloss 'Gentle, Soft' is unsupported and has been replaced with the lexical sense. Same name as nasif."),
 "naseem": ("نَسِيم", "نسیم", "نسیم", "नसीम", "نسیم", "breeze", "Arabic", "Male",
            "Arabic root ن س م (n-s-m); نَسِيم (Nasīm)", False, "high",
            "Naseem is Arabic نَسِيم (Nasīm) 'breeze, gentle wind', from the root ن س م (n-s-m). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nasim."),
 "naseer": ("نَاصِر", "ناصر", "ناصر", "नासिर", "ناصر", "naasir", "Arabic", "Male",
            "Arabic root ن ص ر (n-ṣ-r); نَاصِر (Nāṣir)", False, "high",
            "Naseer is Arabic نَاصِر (Nāṣir) 'helper, supporter', from the root ن ص ر (n-ṣ-r). The source gloss 'Helper, supporter' is consistent. Same name as naasir."),
 "naseera": ("نَاصِرَة", "ناصرہ", "ناصره", "नासिरा", "ناصره", "nacira", "Arabic", "Female",
            "Arabic root ن ص ر (n-ṣ-r); نَاصِرَة (Nāṣira)", False, "high",
            "Naseera is Arabic نَاصِرَة (Nāṣira) 'helper, supporter' (feminine), from the root ن ص ر (n-ṣ-r). The source gloss 'Deliverer, Helper, Aid' is broadly consistent. Same name as nacira."),
 "naser": ("نَاصِر", "ناصر", "ناصر", "नासिर", "ناصر", "naasir", "Arabic", "Male",
           "Arabic root ن ص ر (n-ṣ-r); نَاصِر (Nāṣir)", False, "high",
           "Naser is Arabic نَاصِر (Nāṣir) 'helper, supporter', from the root ن ص ر (n-ṣ-r). The source gloss 'Victorious' is broadly consistent. Same name as naasir."),
 "nasha": ("نَشَا", "نشا", "نشا", "नशा", "نشا", "nasha", "Arabic", "Female",
           "Arabic نَشَا (Nashā)", False, "medium",
           "Nasha is recorded as Arabic نَشَا (Nashā), a female given name. The source gloss 'Delight, Pleasure, Bliss' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nashaat": ("نَشَاط", "نشاط", "نشاط", "नशात", "نشاط", "activity", "Arabic", "Female",
             "Arabic root ن ش ط (n-sh-ṭ); نَشَاط (Nashāṭ)", False, "high",
             "Nashaat is Arabic نَشَاط (Nashāṭ) 'activity, liveliness, energy', from the root ن ش ط (n-sh-ṭ). CRITICAL SOURCE ERROR: the source gave نشرت (a different form); the correct form is نَشَاط. The source gloss 'Growth, Sprouting' is unsupported and has been replaced with the lexical sense. Same name as nashat."),
 "nashat": ("نَشَاط", "نشاط", "نشاط", "नशात", "نشاط", "activity", "Arabic", "Male",
            "Arabic root ن ش ط (n-sh-ṭ); نَشَاط (Nashāṭ)", False, "high",
            "Nashat is Arabic نَشَاط (Nashāṭ) 'activity, liveliness, energy', from the root ن ش ط (n-sh-ṭ). CRITICAL SOURCE ERROR: the source gave نشت (a different form); the correct form is نَشَاط. The source gloss 'Restraint, Prevention' is unsupported and has been replaced with the lexical sense. Same name as nashaat."),
 "nasheed": ("نَشِيد", "نشید", "نشید", "नशीद", "نشید", "anthem", "Arabic", "Male",
             "Arabic root ن ش د (n-sh-d); نَشِيد (Nashīd)", False, "high",
             "Nasheed is Arabic نَشِيد (Nashīd) 'anthem, song, recitation', from the root ن ش د (n-sh-d). The source gloss 'Song, Poem, Recitation' is consistent. Same name as nashid."),
 "nashi": ("نَاشِي", "ناشی", "ناشی", "नाशी", "ناشي", "nashi", "Arabic", "Male",
           "Arabic نَاشِي (Nāshī)", False, "medium",
           "Nashi is recorded as Arabic نَاشِي (Nāshī), a male given name. The source gloss 'Pure, Chaste' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nashid": ("نَشِيد", "نشید", "نشید", "नशीद", "نشید", "anthem", "Arabic", "Male",
            "Arabic root ن ش د (n-sh-d); نَشِيد (Nashīd)", False, "high",
            "Nashid is Arabic نَشِيد (Nashīd) 'anthem, song, recitation', from the root ن ش د (n-sh-d). The source gloss 'Song, Melody, Recitation' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as nasheed."),
 "nashida": ("نَشِيدَة", "نشیدہ", "نشیده", "नशीदा", "نشیده", "nashida", "Arabic", "Female",
             "Arabic root ن ش د (n-sh-d); نَشِيدَة (Nashīda)", False, "high",
             "Nashida is Arabic نَشِيدَة (Nashīda) 'song, recitation' (feminine), from the root ن ش د (n-sh-d). The source gloss 'Gentle whisper' is unsupported and has been replaced with the lexical sense."),
 "nashir": ("نَاشِر", "ناشر", "ناشر", "नाशिर", "ناشر", "publisher", "Arabic", "Male",
            "Arabic root ن ش ر (n-sh-r); نَاشِر (Nāshir)", False, "high",
            "Nashir is Arabic نَاشِر (Nāshir) 'publisher, spreader, announcer', from the root ن ش ر (n-sh-r). The source gloss 'Announcer, Messenger' is broadly consistent."),
 "nashira": ("نَاشِرَة", "ناشرہ", "ناشره", "नाशिरा", "ناشره", "nashira", "Arabic", "Female",
             "Arabic root ن ش ر (n-sh-r); نَاشِرَة (Nāshira)", False, "high",
             "Nashira is Arabic نَاشِرَة (Nāshira) 'publisher, spreader' (feminine), from the root ن ش ر (n-sh-r). The source gloss 'Night Shining Star' is unsupported and has been replaced with the lexical sense."),
 "nashwa": ("نَشْوَة", "نشوہ", "نشوه", "नशवा", "نشوه", "nashwa", "Arabic", "Female",
            "Arabic root ن ش و (n-sh-w); نَشْوَة (Nashwa)", False, "high",
            "Nashwa is Arabic نَشْوَة (Nashwa) 'ecstasy, elation', from the root ن ش و (n-sh-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "nashwan": ("نَشْوَان", "نشوان", "نشوان", "नशवान", "نشوان", "nashwan", "Arabic", "Male",
             "Arabic root ن ش و (n-sh-w); نَشْوَان (Nashwān)", False, "high",
             "Nashwan is Arabic نَشْوَان (Nashwān) 'elated, joyful', from the root ن ش و (n-sh-w). The source gloss 'Intelligent, Wise, Knowledgeable' is unsupported and has been replaced with the lexical sense."),
 "nasib": ("نَصِيب", "نصیب", "نصیب", "नसीब", "نصیب", "share_portion", "Arabic", "Male",
           "Arabic root ن ص ب (n-ṣ-b); نَصِيب (Naṣīb)", False, "high",
           "Nasib is Arabic نَصِيب (Naṣīb) 'share, portion, lot', from the root ن ص ب (n-ṣ-b). CRITICAL SOURCE ERROR: the source gave ناصب (a different form); the correct form is نَصِيب. The source gloss 'Fate, Destiny' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as naseeb."),
 "nasiba": ("نَصِيبَة", "نصیبہ", "نصیبه", "नसीबा", "نصیبه", "nasiba", "Arabic", "Female",
            "Arabic root ن ص ب (n-ṣ-b); نَصِيبَة (Naṣība)", False, "high",
            "Nasiba is Arabic نَصِيبَة (Naṣība) 'share, portion' (feminine), from the root ن ص ب (n-ṣ-b). The source gloss 'A reward, gift, or bounty' is broadly consistent."),
 "nasif": ("نَصِيف", "نصیف", "نصیف", "नसीफ़", "نصیف", "nasif", "Arabic", "Male",
           "Arabic root ن ص ف (n-ṣ-f); نَصِيف (Naṣīf)", False, "high",
           "Nasif is Arabic نَصِيف (Naṣīf) 'just, equitable', from the root ن ص ف (n-ṣ-f). CRITICAL SOURCE ERROR: the source gave ناسف (a different form); the correct form is نَصِيف. The source gloss 'Gentle, Soft, Sensitive' is unsupported and has been replaced with the lexical sense. Same name as naseef."),
 "nasifa": ("نَصِيفَة", "نصیفہ", "نصیفه", "नसीफ़ा", "نصیفه", "nasifa", "Arabic", "Female",
            "Arabic root ن ص ف (n-ṣ-f); نَصِيفَة (Naṣīfa)", False, "high",
            "Nasifa is Arabic نَصِيفَة (Naṣīfa) 'just, equitable' (feminine), from the root ن ص ف (n-ṣ-f). CRITICAL SOURCE ERROR: the source gave ناصفة (a different form); the correct form is نَصِيفَة. The source gloss 'Given as a gift' is unsupported and has been replaced with the lexical sense."),
 "nasih": ("نَاصِح", "ناصح", "ناصح", "नासिह", "ناصح", "naasih", "Arabic", "Male",
           "Arabic root ن ص ح (n-ṣ-ḥ); نَاصِح (Nāṣiḥ)", False, "high",
           "Nasih is Arabic نَاصِح (Nāṣiḥ) 'advisor, sincere counsellor', from the root ن ص ح (n-ṣ-ḥ). The source gloss 'Advice, Warning' is broadly consistent. Same name as naasih."),
 "nasiim": ("نَسِيم", "نسیم", "نسیم", "नसीम", "نسیم", "breeze", "Arabic", "Male",
            "Arabic root ن س م (n-s-m); نَسِيم (Nasīm)", False, "high",
            "Nasiim is a spelling variant of Arabic نَسِيم (Nasīm) 'breeze, gentle wind', from the root ن س م (n-s-m). The source gloss 'Gentle Wind' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as naseem."),
 "nasim": ("نَسِيم", "نسیم", "نسیم", "नसीम", "نسیم", "breeze", "Arabic", "Male",
           "Arabic root ن س م (n-s-m); نَسِيم (Nasīm)", False, "high",
           "Nasim is Arabic نَسِيم (Nasīm) 'breeze, gentle wind', from the root ن س م (n-s-m). CRITICAL SOURCE ERROR: the source gave نسم (a different form); the correct form is نَسِيم. The source gloss 'Wind' is broadly consistent. Same name as naseem."),
 "nasima": ("نَسِيمَة", "نسیمہ", "نسیمه", "नसीमा", "نسیمه", "nasima", "Arabic", "Female",
            "Arabic root ن س م (n-s-m); نَسِيمَة (Nasīma)", False, "high",
            "Nasima is Arabic نَسِيمَة (Nasīma) 'breeze, gentle wind' (feminine), from the root ن س م (n-s-m). The source gloss 'Delight, Pleasure' is unsupported and has been replaced with the lexical sense. Same name as nasimah."),
 "nasimah": ("نَسِيمَة", "نسیمہ", "نسیمه", "नसीमा", "نسیمه", "nasima", "Arabic", "Female",
             "Arabic root ن س م (n-s-m); نَسِيمَة (Nasīma)", False, "high",
             "Nasimah is Arabic نَسِيمَة (Nasīma) 'breeze, gentle wind' (feminine), from the root ن س م (n-s-m). The source gloss 'Breeze or Zephyr' is consistent. Same name as nasima."),
 "nasir": ("نَاصِر", "ناصر", "ناصر", "नासिर", "ناصر", "naasir", "Arabic", "Male",
           "Arabic root ن ص ر (n-ṣ-r); نَاصِر (Nāṣir)", False, "high",
           "Nasir is Arabic نَاصِر (Nāṣir) 'helper, supporter', from the root ن ص ر (n-ṣ-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as naasir."),
 "nasira": ("نَاصِرَة", "ناصرہ", "ناصره", "नासिरा", "ناصره", "nacira", "Arabic", "Female",
            "Arabic root ن ص ر (n-ṣ-r); نَاصِرَة (Nāṣira)", False, "high",
            "Nasira is Arabic نَاصِرَة (Nāṣira) 'helper, supporter' (feminine), from the root ن ص ر (n-ṣ-r). The source gloss 'Protector, Defender' is broadly consistent. Same name as nacira."),
 "nasirah": ("نَاصِرَة", "ناصرہ", "ناصره", "नासिरा", "ناصره", "nacira", "Arabic", "Female",
             "Arabic root ن ص ر (n-ṣ-r); نَاصِرَة (Nāṣira)", False, "high",
             "Nasirah is Arabic نَاصِرَة (Nāṣira) 'helper, supporter' (feminine), from the root ن ص ر (n-ṣ-r). The source gloss 'Helper, Supporter' is consistent. Same name as nacira."),
 "nasma": ("نَسْمَة", "نسمہ", "نسمه", "नसमा", "نسمه", "nasma", "Arabic", "Female",
           "Arabic root ن س م (n-s-m); نَسْمَة (Nasma)", False, "high",
           "Nasma is Arabic نَسْمَة (Nasma) 'a breeze, a breath', from the root ن س م (n-s-m). The source gloss 'Fragrant Garden' is unsupported and has been replaced with the lexical sense."),
 "nasooh": ("نَصُوح", "نصوح", "نصوح", "नसूह", "نصوح", "nasuh", "Arabic", "Male",
            "Arabic root ن ص ح (n-ṣ-ḥ); نَصُوح (Naṣūḥ)", False, "high",
            "Nasooh is Arabic نَصُوح (Naṣūḥ) 'sincere, faithful adviser', from the root ن ص ح (n-ṣ-ḥ). The source gloss 'Given to the Prophet Yusuf (Joseph)' is a historical association rather than a lexical sense. Same name as nasuh."),
 "nasr": ("نَصْر", "نصر", "نصر", "नस्र", "نصر", "victory", "Arabic", "Male",
          "Arabic root ن ص ر (n-ṣ-r); نَصْر (Naṣr)", False, "high",
          "Nasr is Arabic نَصْر (Naṣr) 'victory, triumph, help', from the root ن ص ر (n-ṣ-r). The source gloss 'Victory' is consistent."),
 "nasra": ("نَصْرَة", "نصرہ", "نصره", "नसरा", "نصره", "nasra", "Arabic", "Female",
           "Arabic root ن ص ر (n-ṣ-r); نَصْرَة (Naṣra)", False, "high",
           "Nasra is Arabic نَصْرَة (Naṣra) 'victory, help' (feminine), from the root ن ص ر (n-ṣ-r). The source gloss 'Victory, Helper, Aid' is broadly consistent."),
 "nasrat": ("نُصْرَة", "نصرت", "نصرت", "नुसरत", "نصرت", "nasrat", "Arabic", "Male",
            "Arabic root ن ص ر (n-ṣ-r); نُصْرَة (Nuṣra)", False, "high",
            "Nasrat is Arabic نُصْرَة (Nuṣra) 'help, assistance', from the root ن ص ر (n-ṣ-r). The source gloss 'Help or Assistance' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nasreen": ("نَسْرِين", "نسرین", "نسرین", "नसरीन", "نسرین", "nasreen", "Persian", "Female",
             "Persian نسرین (nasrīn)", False, "high",
             "Nasreen is Persian نسرین (nasrīn) 'wild rose, narcissus'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Wild Rose' is consistent. Same name as nasrin."),
 "nasri": ("نَصْرِي", "نصری", "نصری", "नसरी", "نصري", "nasri", "Arabic", "Male",
           "Arabic نَصْرِي (Naṣrī) 'of victory'", False, "high",
           "Nasri is Arabic نَصْرِي (Naṣrī) 'of victory, victorious', a relational adjective from نَصْر (naṣr). The source gloss 'Gift, blessing' is unsupported and has been replaced with the lexical sense."),
 "nasrin": ("نَسْرِين", "نسرین", "نسرین", "नसरीन", "نسرین", "nasreen", "Persian", "Female",
            "Persian نسرین (nasrīn)", False, "high",
            "Nasrin is Persian نسرین (nasrīn) 'wild rose, narcissus'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nasrin' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Victory, Triumph' is unsupported and has been replaced with the lexical sense. Same name as nasreen."),
 "nassah": ("نَصَّاح", "نصاح", "نصاح", "नस्साह", "نصاح", "nassah", "Arabic", "Female",
            "Arabic root ن ص ح (n-ṣ-ḥ); نَصَّاح (Naṣṣāḥ)", False, "high",
            "Nassah is Arabic نَصَّاح (Naṣṣāḥ) 'sincere adviser', from the root ن ص ح (n-ṣ-ḥ). The source gloss 'Straight, honest' is broadly consistent."),
 "nassar": ("نَصَّار", "نصار", "نصار", "नस्सार", "نصار", "nassar", "Arabic", "Male",
            "Arabic root ن ص ر (n-ṣ-r); نَصَّار (Naṣṣār)", False, "high",
            "Nassar is Arabic نَصَّار (Naṣṣār) 'helper, supporter', from the root ن ص ر (n-ṣ-r). CRITICAL SOURCE ERROR: the source gave نصر (a different form); the correct form is نَصَّار. The source gloss 'Victory, Triumph' is unsupported and has been replaced with the lexical sense."),
 "nassim": ("نَسِيم", "نسیم", "نسیم", "नसीम", "نسیم", "breeze", "Arabic", "Male",
            "Arabic root ن س م (n-s-m); نَسِيم (Nasīm)", False, "high",
            "Nassim is a spelling variant of Arabic نَسِيم (Nasīm) 'breeze, gentle wind', from the root ن س م (n-s-m). The source gloss 'Breeze, gentle wind' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender female; documented usage is predominantly male. Same name as naseem."),
 "nassima": ("نَسِيمَة", "نسیمہ", "نسیمه", "नसीमा", "نسیمه", "nasima", "Arabic", "Female",
             "Arabic root ن س م (n-s-m); نَسِيمَة (Nasīma)", False, "high",
             "Nassima is a spelling variant of Arabic نَسِيمَة (Nasīma) 'breeze' (feminine), from the root ن س م (n-s-m). CRITICAL SOURCE ERROR: the source gave ناصيمة (a different form); the correct form is نَسِيمَة. The source gloss 'Promise, Pledge' is unsupported and has been replaced with the lexical sense. Same name as nasima."),
 "nassir": ("نَاصِر", "ناصر", "ناصر", "नासिर", "ناصر", "naasir", "Arabic", "Male",
            "Arabic root ن ص ر (n-ṣ-r); نَاصِر (Nāṣir)", False, "high",
            "Nassir is a spelling variant of Arabic نَاصِر (Nāṣir) 'helper, supporter', from the root ن ص ر (n-ṣ-r). The source gloss 'Giver, Helper, Helper, Successor' is partly consistent. Same name as naasir."),
 "nassira": ("نَصِيرَة", "نصیرہ", "نصیره", "नसीरा", "نصیره", "nassira", "Arabic", "Female",
             "Arabic root ن ص ر (n-ṣ-r); نَصِيرَة (Naṣīra)", False, "high",
             "Nassira is Arabic نَصِيرَة (Naṣīra) 'helper, supporter' (feminine), from the root ن ص ر (n-ṣ-r). The source gloss 'Deliverer, Savior' is broadly consistent."),
 "nastaran": ("نَسْتَرَن", "نسترن", "نسترن", "नस्तरन", "نسترن", "nastaran", "Persian", "Female",
              "Persian نسترن (nastaran)", False, "high",
              "Nastaran is Persian نسترن (nastaran) 'wild rose'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Jewel, treasure' is unsupported and has been replaced with the lexical sense."),
 "nasuh": ("نَصُوح", "نصوح", "نصوح", "नसूह", "نصوح", "nasuh", "Arabic", "Male",
           "Arabic root ن ص ح (n-ṣ-ḥ); نَصُوح (Naṣūḥ)", False, "high",
           "Nasuh is Arabic نَصُوح (Naṣūḥ) 'sincere, faithful adviser', from the root ن ص ح (n-ṣ-ḥ). The source gloss 'Righteous, obedient' is broadly consistent. Same name as nasooh."),
 "nasya": ("نَاسِيَة", "ناسیہ", "ناسیه", "नास्या", "ناسیه", "nasya", "Arabic", "Female",
           "Arabic نَاسِيَة (Nāsiya)", False, "medium",
           "Nasya is recorded as Arabic نَاسِيَة (Nāsiya), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nasya' instead of a script form. The source gloss 'Deliverer' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "natheer": ("نَذِير", "نذیر", "نذیر", "नज़ीर", "نذیر", "nadheer", "Arabic", "Male",
             "Arabic root ن ذ ر (n-dh-r); نَذِير (Nadhīr)", False, "high",
             "Natheer is a spelling variant of Arabic نَذِير (Nadhīr) 'warner, one who warns', from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave ناثر (a different form); the correct form is نَذِير. The source gloss 'Clear, Announcer' is unsupported and has been replaced with the lexical sense. Same name as nadheer."),
 "natiq": ("نَاطِق", "ناطق", "ناطق", "नातिक़", "ناطق", "speaker", "Arabic", "Male",
           "Arabic root ن ط ق (n-ṭ-q); نَاطِق (Nāṭiq)", False, "high",
           "Natiq is Arabic نَاطِق (Nāṭiq) 'speaker, orator, one who articulates', from the root ن ط ق (n-ṭ-q). The source gloss 'Speaker, Orator' is consistent."),
 "naufal": ("نَوْفَل", "نوفل", "نوفل", "नौफ़ल", "نوفل", "naufal", "Arabic", "Male",
            "Arabic نَوْفَل (Nawfal)", False, "high",
            "Naufal is Arabic نَوْفَل (Nawfal), a male given name borne by a companion of the Prophet. The source gloss 'Helper, Supporter' is unsupported and has been replaced with the documented identification."),
 "nauman": ("نُعْمَان", "نعمان", "نعمان", "नौमान", "نعمان", "naaman", "Arabic", "Male",
            "Arabic نُعْمَان (Nuʿmān)", False, "high",
            "Nauman is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. The source gloss 'Comfort of Night' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "naureen": ("نُورِين", "نورین", "نورین", "नौरीन", "نورین", "naureen", "Arabic", "Female",
             "Arabic نُور (nūr) + feminine ending", False, "high",
             "Naureen is Arabic نُورِين (Nūrīn) 'light, luminous', from نُور (nūr) 'light'. The source gloss 'Light, Pleasing' is broadly consistent."),
 "naushad": ("نَوْشَاد", "نوشاد", "نوشاد", "नौशाद", "نوشاد", "naushad", "Persian", "Male",
             "Persian نوشاد (naushād)", False, "high",
             "Naushad is Persian نوشاد (naushād) 'happy, joyful'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Gifted advisor' is unsupported and has been replaced with the lexical sense."),
 "nausheen": ("نَوْشِين", "نوشین", "نوشین", "नौशीन", "نوشین", "nausheen", "Persian", "Female",
              "Persian نوشین (naushīn)", False, "high",
              "Nausheen is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source gave نوشين (a non-standard form) and labelled the origin Arabic; the name is Persian. The source gloss 'Night Shine' is unsupported and has been replaced with the lexical sense. Same name as naushin."),
 "naushin": ("نَوْشِين", "نوشین", "نوشین", "नौशीन", "نوشین", "nausheen", "Persian", "Female",
             "Persian نوشین (naushīn)", False, "high",
             "Naushin is Persian نوشین (naushīn) 'sweet, pleasant'. CRITICAL SOURCE ERROR: the source gave ناوشين (a non-standard form) and labelled the origin Arabic; the name is Persian. The source gloss 'Helper, Supporter' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as nausheen."),
 "naveed": ("نَوِيد", "نوید", "نوید", "नवीद", "نوید", "good_news", "Persian", "Male",
            "Persian نوید (navīd)", False, "high",
            "Naveed is Persian نوید (navīd) 'good news, glad tidings'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Good News' is consistent. Same name as navid."),
 "naveen": ("نَوِين", "نوین", "نوین", "नवीन", "نوین", "new_fresh", "Persian", "Male",
            "Persian نوین (navīn)", False, "high",
            "Naveen is Persian نوین (navīn) 'new, fresh, young'. CRITICAL SOURCE ERROR: the source gave نافين (a different form) and labelled the origin Arabic; the word is Persian. The source gloss 'Pure and Clean' is unsupported and has been replaced with the lexical sense."),
 "navid": ("نَوِيد", "نوید", "نوید", "नवीद", "نوید", "good_news", "Persian", "Male",
           "Persian نوید (navīd)", False, "high",
           "Navid is Persian نوید (navīd) 'good news, glad tidings'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'New, Delight, Young' is partly unsupported and has been replaced with the lexical sense. Same name as naveed."),
}
