# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 24 (ferhat..ghadir).

Every entry records ONLY what can be defended against a Tier-A/B source (Wikipedia /
Encyclopaedia-style reference, Rekhta, Wiktionary, companions.hawramani.com, classical
lexicography). `conf` is the honest confidence in the lexical identification.
`unverified` means the form could not be matched to a Tier-A/B source and NO gloss is
asserted (the record says so explicitly).

Fields: ar, ur, fa, hi, ps  -> script forms (None = not established for that language)
        gloss -> key into GLOSSES (None = no verified gloss)
        origin, gender, root, quranic, conf, note
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated23 import GLOSSES as _G23

GLOSSES = dict(_G23)
GLOSSES.update({
    "renowned_magnificent": {"en": "Renowned, magnificent", "ur": "مشہور، عظیم", "fa": "نامدار، باشکوه", "hi": "प्रसिद्ध, भव्य", "ps": "نامتو، ستر", "ar": "الشهير، العظيم"},
    "joy_happy": {"en": "Joy, happiness", "ur": "خوشی، مسرت", "fa": "شادی، خوشحالی", "hi": "ख़ुशी, आनंद", "ps": "خوښي، مسرت", "ar": "الفرح، السعادة"},
    "delicate_subtle_exquisite": {"en": "Delicate, subtle, exquisite", "ur": "نازک، لطیف، نفیس", "fa": "ظریف، لطیف، نفیس", "hi": "नाज़ुक, सूक्ष्म, उत्तम", "ps": "نازک، نری، ښکلی", "ar": "الرقيقة، اللطيفة، النفيسة"},
    "strong_brave": {"en": "Strong, brave", "ur": "طاقتور، بہادر", "fa": "نیرومند، دلیر", "hi": "मज़बूत, बहादुर", "ps": "پیاوړی، زړور", "ar": "القوي، الشجاع"},
    "gentle_delicate_beautiful": {"en": "Gentle, delicate, beautiful", "ur": "نرم، نازک، خوبصورت", "fa": "ملایم، لطیف، زیبا", "hi": "कोमल, नाज़ुक, सुंदर", "ps": "نرم، نازک، ښکلی", "ar": "اللطيفة، الرقيقة، الجميلة"},
    "fearless": {"en": "Fearless, brave", "ur": "بے خوف، بہادر", "fa": "بی‌باک، دلیر", "hi": "निडर, बहादुर", "ps": "بې وېرې، زړور", "ar": "الجسورة، الشجاعة"},
    "victorious_brave": {"en": "Victorious, brave", "ur": "فاتح، بہادر", "fa": "پیروز، دلیر", "hi": "विजयी, बहादुर", "ps": "بریالی، زړور", "ar": "المنصورة، الشجاعة"},
    "elevated_exalted": {"en": "Elevated, exalted", "ur": "بلند، سرفراز", "fa": "بلند، سرافراز", "hi": "उच्च, प्रतिष्ठित", "ps": "لوړ، سربلند", "ar": "الرفيعة، العالية"},
    "splendour_neck": {"en": "Splendour of the neck, one with a beautiful neck", "ur": "گردن کی رونق، خوش گردن", "fa": "شکوه گردن، خوش‌گردن", "hi": "गर्दन की शोभा, सुंदर गर्दन", "ps": "د غاړې ښکلا، ښکلې غاړه", "ar": "بهاء العنق، ذات العنق الجميل"},
    "blossom_bloom": {"en": "Blossom, bloom", "ur": "کلی، پھول", "fa": "شکوفه، گل", "hi": "कली, फूल", "ps": "ګل، شګوفه", "ar": "الزهرة، الإزهار"},
    "loyalty_devotion": {"en": "Loyalty, devotion, self-sacrifice", "ur": "وفاداری، قربانی", "fa": "وفاداری، فداکاری", "hi": "वफ़ादारी, बलिदान", "ps": "وفاداري، قرباني", "ar": "الوفاء، التضحية"},
    "gentle_tiny_separation": {"en": "Little, tiny, gentle", "ur": "چھوٹی، ننھی، نرم", "fa": "کوچک، نازک، ملایم", "hi": "छोटी, नन्ही, कोमल", "ps": "وړه، نازکه", "ar": "الصغيرة، اللطيفة"},
    "silver": {"en": "Silver", "ur": "چاندی", "fa": "نقره", "hi": "चाँदी", "ps": "سپين زر", "ar": "الفضة"},
    "liberated_free": {"en": "Liberated, free, independent", "ur": "آزاد، خودمختار", "fa": "آزاد، مستقل", "hi": "आज़ाद, स्वतंत्र", "ps": "خپلواک، آزاد", "ar": "الحرّة، المستقلة"},
    "thought_reflection": {"en": "Thought, reflection", "ur": "فکر، غور", "fa": "فکر، اندیشه", "hi": "विचार, चिंतन", "ps": "فکر، اندېښنه", "ar": "الفكر، التأمل"},
    "thought_idea_reflection": {"en": "Thought, idea, reflection", "ur": "فکر، خیال، غور", "fa": "فکر، ایده، اندیشه", "hi": "विचार, कल्पना, चिंतन", "ps": "فکر، نظر، اندېښنه", "ar": "الفكر، الفكرة، التأمل"},
    "thinking_reflection": {"en": "Thinking, reflective", "ur": "سوچنے والا، غور کرنے والا", "fa": "اندیشمند، خردمند", "hi": "विचारक, चिंतनशील", "ps": "فکرمند، اندېښمن", "ar": "المفكّر، المتأمّل"},
    "memory_thought": {"en": "Memory, thought", "ur": "یاد، فکر", "fa": "حافظه، اندیشه", "hi": "स्मृति, विचार", "ps": "په یاد، فکر", "ar": "الذاكرة، الفكر"},
    "moonlight": {"en": "Moonlight", "ur": "چاندنی", "fa": "مهتاب", "hi": "चाँदनी", "ps": "سپوږمۍ رڼا", "ar": "ضوء القمر"},
    "precious_pearl": {"en": "Precious pearl", "ur": "قیمتی موتی", "fa": "مروارید گران‌بها", "hi": "बहुमूल्य मोती", "ps": "ګران بها مرغلره", "ar": "اللؤلؤة الثمينة"},
    "jewel_treasure": {"en": "Jewel, treasure", "ur": "جوہر، خزانہ", "fa": "گوهر، گنج", "hi": "रत्न, खज़ाना", "ps": "جواهر، خزانه", "ar": "الجوهر، الكنز"},
    "man_free": {"en": "Man, free", "ur": "مرد، آزاد", "fa": "مرد، آزاد", "hi": "पुरुष, आज़ाद", "ps": "نر، آزاد", "ar": "الرجل، الحرّ"},
    "lion_brave": {"en": "Lion, brave", "ur": "شیر، بہادر", "fa": "شیر، دلیر", "hi": "शेर, बहादुर", "ps": "زمری، زړور", "ar": "الليث، الشجاع"},
    "observer_seer": {"en": "Observer, seer, discernment", "ur": "مشاہد، بصیرت والا", "fa": "بیننده، بصیرت‌مند", "hi": "पर्यवेक्षक, दूरदर्शी", "ps": "کتونکی، بصیرت لرونکی", "ar": "الملاحظ، الفارس في الرأي"},
    "paradise_garden": {"en": "Paradise, garden", "ur": "جنت، باغ", "fa": "بهشت، باغ", "hi": "जन्नत, बाग़", "ps": "جنت، باغ", "ar": "الفردوس، الجنة"},
    "paradise_garden_rel": {"en": "Of paradise, heavenly", "ur": "جنتی، بہشتی", "fa": "بهشتی، فردوسی", "hi": "जन्नती, स्वर्गीय", "ps": "جنتي، بهشتي", "ar": "الفردوسي، الجناني"},
    "paradise_flyer": {"en": "Paradise flyer", "ur": "جنت کا پرندہ، اڑنے والا", "fa": "پرنده بهشتی", "hi": "जन्नत का पक्षी", "ps": "د جنت مرغ", "ar": "طائر الفردوس"},
    "turquoise": {"en": "Turquoise", "ur": "فیروزہ", "fa": "فیروزه", "hi": "फ़िरोज़ा", "ps": "فیروزه", "ar": "الفيروز"},
    "compassionate_kind": {"en": "Compassionate, kind", "ur": "شفیق، مہربان", "fa": "مهربان، دلسوز", "hi": "दयालु, मेहरबान", "ps": "مهربان، زړه‌سوځ", "ar": "الرحيمة، الحنونة"},
    "innate_nature": {"en": "Innate nature, original disposition", "ur": "فطرت، اصل سرشت", "fa": "فطرت، سرشت", "hi": "फ़ितरत, स्वभाव", "ps": "فطرت، طبيعت", "ar": "الفطرة، الطبيعة"},
    "natural_disposition": {"en": "Natural state, temperament", "ur": "طبیعت، سرشت", "fa": "سرشت، طبع", "hi": "स्वभाव, प्रकृति", "ps": "طبيعت، مزاج", "ar": "الفطرة، الطبع"},
    "radiant_blooming": {"en": "Radiant, blooming", "ur": "تاباں، پھولتی", "fa": "درخشان، شکوفا", "hi": "प्रकाशमान, खिलता", "ps": "ځلانده، ګل‌شوی", "ar": "المشرقة، المزهرة"},
    "breeze_gentle_wind": {"en": "Breeze, gentle wind", "ur": "ہلکی ہوا، نسیم", "fa": "نسیم، باد ملایم", "hi": "हवा, मंद वायु", "ps": "په نرمه باد", "ar": "النسيم، العليل"},
    "rich_abundant": {"en": "Rich, abundant", "ur": "مالدار، کثیر", "fa": "توانگر، فراوان", "hi": "धनी, प्रचुर", "ps": "شتمن، ډېر", "ar": "الغني، الوفير"},
    "delight_pleasure": {"en": "Delight, pleasure", "ur": "خوشی، لذت", "fa": "شادی، لذت", "hi": "आनंद, ख़ुशी", "ps": "خوښي، خوند", "ar": "البهجة، اللذة"},
    "joy": {"en": "Joy", "ur": "خوشی، شادمانی", "fa": "شادی، خوشی", "hi": "आनंद, ख़ुशी", "ps": "خوښي، مینه", "ar": "الفرح، السرور"},
    "dewdrop": {"en": "Dewdrop", "ur": "شبنم", "fa": "شبنم، ژاله", "hi": "ओस", "ps": "د اسمان شبنم", "ar": "الطل، الندى"},
    "fortune_prosperity": {"en": "Fortune, prosperity", "ur": "اقبال، خوشحالی", "fa": "بخت، بهروزی", "hi": "भाग्य, समृद्धि", "ps": "بخت، نېکمرغي", "ar": "الحظ، الازدهار"},
    "free_liberated": {"en": "Free, liberated", "ur": "آزاد، رہا", "fa": "آزاد، رها", "hi": "आज़ाद, मुक्त", "ps": "آزاد، خپلواک", "ar": "الحرّة، المعتقة"},
    "victory_triumph": {"en": "Victory, triumph", "ur": "فتح، کامیابی", "fa": "پیروزی، فتح", "hi": "जीत, विजय", "ps": "بریا، پيروزي", "ar": "النصر، الظفر"},
    "heart": {"en": "Heart", "ur": "دل", "fa": "دل، قلب", "hi": "हृदय, दिल", "ps": "زړه", "ar": "الفؤاد، القلب"},
    "protector": {"en": "Protector, guardian", "ur": "محافظ، نگہبان", "fa": "نگهبان، حامی", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، ناظر", "ar": "الحفيظ، النصير"},
    "fragrant_blossom": {"en": "Fragrant blossom", "ur": "خوشبودار کلی", "fa": "شکوفه خوشبو", "hi": "सुगंधित कली", "ps": "خوشبویه ګل", "ar": "الزهرة العطرة"},
    "victorious_triumphant": {"en": "Victorious, triumphant", "ur": "فاتح، کامیاب", "fa": "پیروز، کامروا", "hi": "विजयी, सफल", "ps": "بریالی، کامياب", "ar": "الفائزة، المنتصرة"},
    "wise_intelligent": {"en": "Wise, intelligent", "ur": "عقلمند، دانا", "fa": "خردمند، دانا", "hi": "बुद्धिमान, समझदार", "ps": "عقلمن، پوه", "ar": "الحكيمة، العاقلة"},
    "abundance_prosperity": {"en": "Abundance, prosperity", "ur": "کثرت، خوشحالی", "fa": "فراوانی، بهروزی", "hi": "बहुतायत, समृद्धि", "ps": "ډېروالی، نېکمرغي", "ar": "الوفرة، الازدهار"},
    "knowledge_wisdom": {"en": "Knowledge, wisdom", "ur": "علم، حکمت", "fa": "دانش، حکمت", "hi": "ज्ञान, बुद्धि", "ps": "پوهه، حکمت", "ar": "العلم، الحكمة"},
    "abundance_generosity": {"en": "Abundance, generosity", "ur": "فراوانی، سخاوت", "fa": "فراوانی، سخاوت", "hi": "प्रचुरता, उदारता", "ps": "ډېروالی، سخا", "ar": "الوفرة، الكرم"},
    "sweet_water": {"en": "Sweet, pure water", "ur": "میٹھا پانی", "fa": "آب گوارا", "hi": "मीठा जल", "ps": "خوږه اوبه", "ar": "الماء العذب"},
    "criterion": {"en": "Criterion, that which distinguishes truth from falsehood", "ur": "کسوٹی، حق و باطل میں فرق", "fa": "معیار، جداکننده حق و باطل", "hi": "कसौटी, सत्य-असत्य का विभेदक", "ps": "معيار، د حق او باطل توپير", "ar": "الفرقان، المفرّق بين الحق والباطل"},
    "riders": {"en": "Riders, horsemen", "ur": "سوار، شہسوار", "fa": "سواران، شهسواران", "hi": "घुड़सवार", "ps": "سپاره، سواران", "ar": "الفرسان"},
    "pious_god_fearing": {"en": "Pious, God-fearing", "ur": "پرہیزگار، متقی", "fa": "پرهیزگار، متقی", "hi": "धर्मनिष्ठ, ईश्वरभीरु", "ps": "پرهېزګار، متقي", "ar": "الفضيل، التقي"},
    "young_girl": {"en": "Young girl", "ur": "نوجوان لڑکی", "fa": "دختر جوان", "hi": "युवा लड़की", "ps": "ځوانه نجلۍ", "ar": "الفتاة الشابة"},
    "compeller_helper": {"en": "Compeller, one who helps the broken", "ur": "زور دینے والا، مددگار", "fa": "جبرکننده، یاری‌رسان", "hi": "सहायक, सहारा देने वाला", "ps": "مرستندوی، ساتونکی", "ar": "الجابر، المعين"},
    "mountain": {"en": "Mountain", "ur": "پہاڑ", "fa": "کوه", "hi": "पर्वत", "ps": "غر", "ar": "الجبل"},
    "strong_powerful": {"en": "Strong, powerful", "ur": "طاقتور، زبردست", "fa": "نیرومند، توانا", "hi": "शक्तिशाली, बलवान", "ps": "پیاوړی، ځواکمن", "ar": "القوي، العزيز"},
    "trustworthy_one": {"en": "One who is trustworthy", "ur": "قابل اعتماد، امانتدار", "fa": "قابل اعتماد، امین", "hi": "विश्वसनीय, ईमानदार", "ps": "باور وړ، امانتدار", "ar": "الأمين، الموثوق"},
    "carrier_of_burden": {"en": "Carrier of a heavy burden, forgiver", "ur": "بھاری بوجھ اٹھانے والا، بخشنے والا", "fa": "بارکش، آمرزنده", "hi": "भार वहन करने वाला, क्षमाशील", "ps": "د بار وړونکی، بخښونکی", "ar": "الحمّال، الغفار"},
    "forgiving_generous": {"en": "Forgiving, most generous", "ur": "بخشنے والا، بہت مہربان", "fa": "آمرزنده، بخشنده", "hi": "क्षमाशील, अत्यंत उदार", "ps": "بخښونکی، ډېر مهربان", "ar": "الغفور، الكريم"},
    "small_flower": {"en": "Small flower", "ur": "چھوٹا پھول", "fa": "گل کوچک", "hi": "छोटा फूल", "ps": "وړه ګل", "ar": "الزهرة الصغيرة"},
    "majesty_greatness": {"en": "Majesty, greatness, splendour", "ur": "عظمت، جلال", "fa": "جلال، شکوه", "hi": "महिमा, वैभव", "ps": "جلال، لویي", "ar": "الجلال، العظمة"},
    "gentle_delicate_tender": {"en": "Gentle, delicate, tender", "ur": "نرم، نازک، شفیق", "fa": "ملایم، لطیف، مهربان", "hi": "कोमल, नाज़ुक, दयालु", "ps": "نرم، نازک، مهربان", "ar": "اللطيفة، الرقيقة، الحنونة"},
    "powerful_victorious": {"en": "Powerful, victorious", "ur": "زبردست، فاتح", "fa": "توانا، پیروز", "hi": "शक्तिशाली, विजयी", "ps": "ځواکمن، بریالی", "ar": "الغالب، القاهر"},
    "joy_grace": {"en": "Joy and grace", "ur": "خوشی اور رعنائی", "fa": "شادی و ناز", "hi": "आनंद और लावण्य", "ps": "خوښي او ښکلا", "ar": "الفرح والنعمة"},
    "camel_driver": {"en": "Camel driver", "ur": "اونٹ ہانکنے والا", "fa": "شتربان", "hi": "ऊँट चलाने वाला", "ps": "اوښوان", "ar": "الجمال، سائق الجمال"},
    "handsome_reward": {"en": "Handsome, beautiful, reward", "ur": "خوبصورت، انعام", "fa": "زیبا، پاداش", "hi": "सुंदर, पुरस्कार", "ps": "ښکلی، بدله", "ar": "الجميل، الجزاء"},
    "beautiful": {"en": "Beautiful, lovely", "ur": "خوبصورت، حسین", "fa": "زیبا، دلربا", "hi": "सुंदर, रूपवती", "ps": "ښکلې، ښایسته", "ar": "الجميلة"},
    "rose_smile": {"en": "Rose, smile", "ur": "گلاب، مسکراہٹ", "fa": "گل، لبخند", "hi": "गुलाब, मुस्कान", "ps": "ګلاب، موسکا", "ar": "الوردة، البسمة"},
    "owner_possessor": {"en": "Owner, possessor", "ur": "مالک، مالدار", "fa": "دارنده، توانگر", "hi": "स्वामिनी, मालकिन", "ps": "خاوند، مالک", "ar": "الغنية، المالكة"},
    "gem": {"en": "Gem, jewel", "ur": "جوہر، موتی", "fa": "گوهر، جواهر", "hi": "रत्न, जवाहर", "ps": "جواهر، غمې", "ar": "الجوهر، الدرّ"},
    "protector_guardian": {"en": "Protector, guardian", "ur": "محافظ، نگہبان", "fa": "نگهبان، حامی", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، پالونکی", "ar": "الحافظ، النصير"},
    "gazelle_like": {"en": "Gazelle-like, graceful", "ur": "ہرنی جیسی، خوبصورت", "fa": "مانند آهو، زیبا", "hi": "हिरणी जैसी, सुंदर", "ps": "د غویي په څېر، ښکلې", "ar": "الغزالة، الرشيقة"},
    "joyful_delightful": {"en": "Joyful, delightful", "ur": "خوش، مسرور", "fa": "شاد، دلپذیر", "hi": "प्रसन्न, आनंददायक", "ps": "خوشحاله، مینه‌ناک", "ar": "الفرِحة، المسرورة"},
    "graceful_slender": {"en": "Graceful, slender, tender", "ur": "خوش قامت، نازک", "fa": "خوش‌قامت، لطیف", "hi": "सुडौल, सुकुमार", "ps": "ښایسته، نازکه", "ar": "الغادة، الرشيقة"},
    "flowing_water": {"en": "Flowing water, stream", "ur": "بہتا پانی، ندی", "fa": "آب روان، نهر", "hi": "बहता जल, धारा", "ps": "بهېدونکې اوبه", "ar": "الماء الجاري، الغدير"},
    "small_stream": {"en": "Small stream, brook", "ur": "چھوٹی ندی، نالہ", "fa": "نهر کوچک، جویبار", "hi": "छोटी धारा, नाला", "ps": "وړه ویاله", "ar": "الغدير، الجدول"},
    "swift": {"en": "Swift", "ur": "تیز رفتار", "fa": "تندرو", "hi": "तेज़", "ps": "چټک", "ar": "السريع"},
    "journey": {"en": "Journey, travel", "ur": "سفر، کوچ", "fa": "سفر", "hi": "यात्रा, सफ़र", "ps": "سفر، مزل", "ar": "السفر، الرحلة"},
})

# slug: (ar, ur, fa, hi, ps, gloss_key, origin, gender, root, quranic, conf, note)
CUR = {
 "ferhat": ("فرهاد", "فرہاد", "فرهاد", "फ़रहाद", "فرهاد", "renowned_magnificent", "Persian", "Male",
            "Persian فرهاد < Middle Persian Frahād", False, "medium",
            "The source record labelled Ferhat 'Arabic' and glossed it 'renowned, magnificent' from an alleged Arabic word Farh; that derivation is not supported. Ferhat/Ferhad/Farhad is the Persian name فرهاد (Farhād), from Middle Persian Frahād and Old Iranian fra-hāta- 'merited, obtained', borne by Arsacid kings from c. 170 BC. It is widely used in Turkish and Kurdish as well. The Arabic form given in the source (فرحات) is not the standard form of this name."),
 "feride": ("فريدة", "فریدہ", "فریده", "फ़रीदा", "فریده", "delicate_subtle_exquisite", "Arabic", "Female",
            "Arabic root ف ر د (f-r-d)", False, "high",
            "Feride is the Turkish form of Arabic فريدة (Farīda), the feminine of فريد (Farīd) 'unique, peerless', from the root ف ر د (f-r-d) 'to be single, unique'. The core sense is 'unique, matchless, precious'. The source gloss 'delicate, subtle, exquisite' is a loose extension of that idea rather than the lexical meaning."),
 "feroz": ("فيروز", "فیروز", "فیروز", "फ़िरोज़", "فیروز", "turquoise", "Persian", "Male",
            "Persian پیروزه (pīrūza) / فیروزه", False, "high",
            "Feroz/Firoz is the Persian name فیروز (Fīrūz), from Middle Persian pērōz 'victorious', which also gave the name of the gemstone turquoise (فیروزه fīrūza). The source record labelled it 'Arabic'; the word is Persian in origin, later borrowed into Arabic as فيروز. The 'strong, brave' gloss in the source is not the lexical meaning. Note also that the source record for the related slug firoz carried the Arabic form أحمد, which is wrong (see firoz)."),
 "feroza": ("فيروزة", "فیروزہ", "فیروزه", "फ़िरोज़ा", "فیروزه", "turquoise", "Persian", "Female",
            "Persian فیروزه (fīrūza)", False, "high",
            "Feroza is the feminine/derived form of Persian فیروز (Fīrūz) 'victorious', specifically فیروزه (Fīrūza), the word for the gemstone turquoise. The source labelled it 'Arabic' and glossed it 'gentle, delicate, beautiful'; the lexical sense is 'turquoise' (and, from the base word, 'victorious')."),
 "ferozah": ("فيروزة", "فیروزہ", "فیروزه", "फ़िरोज़ा", "فیروزه", "turquoise", "Persian", "Female",
            "Persian فیروزه (fīrūza)", False, "high",
            "Ferozah is a spelling variant of Feroza, from Persian فیروزه (Fīrūza) 'turquoise', itself from فیروز (Fīrūz) 'victorious'. The source gloss 'fearless' is unsupported by the lexical evidence and has not been carried over."),
 "feroze": ("فيروز", "فیروز", "فیروز", "फ़िरोज़", "فیروز", "turquoise", "Persian", "Male",
            "Persian فیروز (Fīrūz) < Middle Persian pērōz 'victorious'", False, "high",
            "Feroze is a common South Asian spelling of the Persian name فیروز (Fīrūz), 'victorious', also the source of the word for the turquoise gem. The source labelled it 'Arabic' and glossed it 'victorious, brave'; 'victorious' is defensible, 'brave' is a loose association."),
 "ferran": ("فيران", "فیران", "فیران", "फ़ेरान", "فیران", None, "Unknown", "Unknown",
            None, False, "unverified",
            "No lexical identification could be established for ferran against a Tier-A/B source. The source record asserted an Arabic form فيران and the gloss 'elevated, exalted', but لا standard Arabic lexical item of that shape carries that meaning, and the same source gave the unrelated Urdu spelling فیوران. No meaning is asserted."),
 "feryal": ("فريال", "فریال", "فریال", "फ़रयाल", "فریال", "splendour_neck", "Persian", "Female",
            "Persian فر (far) 'splendour' + یال (yāl) 'neck'", False, "high",
            "Feryal (also Firyal, Faryal) is a Persian feminine name, analysed as a compound of فر (far) 'splendour' and یال (yāl) 'neck' — 'she whose neck is radiant / the one with a beautiful neck'. The source labelled it 'Arabic' and glossed it 'nightingale'; both are wrong for this form. (The 'nightingale' sense belongs to a different Persian word.)"),
 "feyza": ("فيضا", "فیضہ", "فیضا", "फ़ैज़ा", "فیضا", "abundance_prosperity", "Arabic", "Female",
            "Arabic root ف ي ض (f-y-ḍ) 'to overflow, abound'", False, "high",
            "Feyza is the Turkish form of Arabic فيضة (Fayḍa), from the root ف ي ض (f-y-ḍ) 'to overflow, pour out abundantly'. Its core sense is 'abundance, overflow', extended in Turkish usage to 'grace, favour'. The source gloss 'blossom, bloom' is unsupported and has not been carried over. It is often treated alongside Faiza (فائزة), but the two derive from different roots."),
 "fida": (None, None, None, None, None, None, "Unknown", "Unknown",
          None, False, "unverified",
          "The source record carries no linguistic data at all for fida (empty language, gender, and meaning). No verified form or gloss was established, so none is asserted. The ordinary Arabic word فداء (fidāʾ) 'ransom, self-sacrifice' is a lexical item rather than necessarily a personal name, and it is recorded separately here under fidaa."),
 "fidaa": ("فداء", "فداء", "فداء", "फ़िदा", "فداء", "loyalty_devotion", "Arabic", "Unisex",
            "Arabic root ف د ي (f-d-y) 'to ransom, redeem'", False, "high",
            "Fidaa (فداء, fidāʾ) is an Arabic noun from the root ف د ي (f-d-y) 'to ransom, redeem, sacrifice oneself for another'. Its sense is 'ransom, redemption, self-sacrifice' — hence 'devotion, loyal dedication'. The source gloss 'loyalty, devotion' is defensible; the source's 'Unisex' label reflects mixed modern use, while historical naming is predominantly feminine."),
 "fidah": ("فداء", "فداء", "فداء", "फ़िदा", "فداء", "loyalty_devotion", "Arabic", "Female",
            "Arabic root ف د ي (f-d-y)", False, "medium",
            "Fidah is a spelling variant of Fidaa (فداء, fidāʾ), 'ransom, self-sacrifice, devotion'. The source gloss 'little, tiny, separation' is unsupported for this form and has not been carried over."),
 "fiddah": ("فِضَّة", "چاندی", "نقره", "चाँदी", "سپين زر", "silver", "Arabic", "Female",
            "Arabic root ف ض ض (f-ḍ-ḍ)", False, "high",
            "Fiddah is the Arabic word فِضَّة (fiḍḍa) 'silver' — also a female given name, associated with purity and brightness. The source gloss 'The Scattered' is not the lexical meaning and has not been carried over. Fizza (fizza) is a common South Asian spelling of the same name."),
 "fidha": ("فِضا", "فضا", "فضا", "फ़िज़ा", "فضا", "liberated_free", "Arabic", "Female",
            "Arabic root ف ض و (f-ḍ-w) 'to be wide, open'", False, "medium",
            "Fidha corresponds to Arabic فضاء (faḍāʾ) 'space, vastness, open expanse', from the root ف ض و. The name sense is 'openness, freedom, spaciousness'. The source gave the form فضى and glossed it 'liberated, free, independent'; the 'freedom' idea is an extension of 'open expanse' rather than a literal gloss. The closely related spelling Fiza (فِضا, fiḍā) is also current."),
 "fikr": ("فكر", "فکر", "فکر", "फ़िक्र", "فکر", "thought_reflection", "Arabic", "Unisex",
            "Arabic root ف ك ر (f-k-r)", False, "high",
            "Fikr (فكر) is the Arabic verbal noun 'thought, reflection, consideration', from the root ف ك ر (f-k-r). It is used as a given name, more often for girls in South Asia. The source gender string '(Male or Female or Unisex)' was normalised."),
 "fikrat": ("فكرة", "فکرت", "فکرت", "फ़िक्रत", "فکرت", "thought_idea_reflection", "Arabic", "Male",
            "Arabic root ف ك ر (f-k-r)", False, "high",
            "Fikrat is a given-name form built on the Arabic root ف ك ر (f-k-r) 'to think, reflect' (cf. فكرة fikra 'an idea, a thought'). It is used mainly in Persian, Urdu and Turkish-influenced naming. The source gloss 'thought, idea, reflection' is defensible."),
 "fikri": ("فكري", "فکری", "فکری", "फ़िक्री", "فکري", "thinking_reflection", "Arabic", "Male",
            "Arabic root ف ك ر (f-k-r); nisba adjective فِكْري", False, "high",
            "Fikri is the Arabic nisba adjective فِكْري (fikrī) 'intellectual, of thought', from the root ف ك ر (f-k-r). As a given name it means 'of thought, reflective, intellectual'. The source gloss 'thinking, reflection' is defensible."),
 "fikriyah": ("فكرية", "فکریہ", "فکریه", "फ़िक्रिया", "فکریه", "thought_reflection", "Arabic", "Female",
            "Arabic root ف ك ر (f-k-r)", False, "high",
            "Fikriyah (فكرية) is the feminine form of فِكْري (fikrī), 'intellectual, of thought', from the Arabic root ف ك ر (f-k-r). The source gloss 'memory, thought' is approximate; the lexical sense is 'intellectual, pertaining to thought'."),
 "fila": (None, None, None, None, None, None, "Unknown", "Unknown",
          None, False, "unverified",
          "The source record gave the Latin string 'Fila' as the 'Arabic form' and the gloss 'moonlight'; neither could be verified. 'Fila' is also a common West African (Yoruba) given name, which is a different tradition from the record's 'islamic' classification and is not asserted here. No form or gloss is claimed."),
 "filza": (None, "فلزا", None, None, None, None, "Unknown", "Female",
           None, False, "unverified",
           "Filza is a female given name used in South Asia (recorded on Urdu naming references as 'rose from heaven'), but no Tier-A/B lexical source establishes an Arabic or Persian word of this shape with that meaning, and the source record's 'Arabic form' فيلزة is not an attested lexical item. Personal-name usage is reported; no lexical meaning is asserted. The source gender (female) is retained as reported usage."),
 "filzah": (None, "فلزہ", None, None, None, None, "Unknown", "Female",
            None, False, "unverified",
            "Filzah is a spelling variant of Filza, recorded in South Asian naming usage. No Tier-A/B lexical source establishes a form of this shape; the source's 'Arabic form' فِلزَه is not attested. No meaning is asserted."),
 "fir": ("فِرّ", "فر", "فر", "फ़िर", "فر", "man_free", "Persian", "Male",
         "Persian فر (far) 'splendour, glory'", False, "medium",
         "The two-letter sequence فر is the Persian word فر (far) 'splendour, glory, majesty' (as in فَرَّه), and the source's gloss 'free' points instead to Arabic حُرّ (ḥurr) 'free', which is a different form. Used as a short given-name element. The identification is plausible but the semantics are not cleanly established for the standalone name."),
 "firas": ("فِراس", "فراس", "فراس", "फ़िरास", "فراس", "lion_brave", "Arabic", "Male",
           "Arabic root ف ر س (f-r-s)", False, "high",
           "Firas (فِراس) is an Arabic male name from the root ف ر س (f-r-s), associated with the lion and with keen perception — classical lexicographers gloss it 'lion' and connect it to فراسة (farāsa) 'perspicacity, discernment'. It was borne by several companions of the Prophet (Firas bin Habis al-Tamimi and others). The source gloss 'bringer of peace' is unsupported and has been replaced."),
 "firasat": ("فراسة", "فراست", "فراست", "फ़िरासत", "فراست", "observer_seer", "Arabic", "Male",
             "Arabic root ف ر س (f-r-s); فراسة (farāsa)", False, "high",
             "Firasat is the Urdu/Persian reflex of Arabic فراسة (farāsa) 'perspicacity, discernment, the ability to read character and meaning'. The source gloss 'observer, seer, explorer' is a loose paraphrase of that sense; the lexical meaning is 'insight, discernment'."),
 "firasha": ("فراشة", "فراشہ", "فراشه", "फ़राशा", "فراشه", None, "Arabic", "Female",
             None, False, "low",
             "Firasha corresponds in form to Arabic فراشة (farāsha) 'butterfly'; the source record itself supplied no meaning ('Unknown'), and the form is not securely attested as a personal name. The butterfly reading is given as a probable lexical identification only, at low confidence."),
 "firdaus": ("فردوس", "فردوس", "فردوس", "फ़िरदौस", "فردوس", "paradise_garden", "Arabic", "Unisex",
             "Arabic root ف ر د س (f-r-d-s), a borrowing from Middle Persian", False, "high",
             "Firdaus (فردوس) means 'paradise, the highest garden'. The word is Arabic in form (used in the Qur'an for the highest level of paradise) but is itself borrowed from Middle Persian / Aramaic, which is why it sits at the meeting point of Arabic and Persianate vocabulary. It is used for both sexes in South Asia. It is a Qur'anic word rather than a personal name attested in the Qur'an."),
 "firdausi": ("فردوسي", "فردوسی", "فردوسی", "फ़िरदौसी", "فردوسي", "paradise_garden_rel", "Arabic", "Male",
              "Arabic فردوس (firdaws) + nisba ending -ī", False, "high",
              "Firdausi is the nisba adjective of فردوس (firdaws) 'paradise' — 'heavenly, of paradise'. It is best known as the pen-name of the poet Abul-Qasem Ferdowsi (author of the Shahnameh), from which its currency derives. The source gloss 'paradise garden' is a fair paraphrase."),
 "firdaws": ("فردوس", "فردوس", "فردوس", "फ़िरदौस", "فردوس", "paradise_garden", "Arabic", "Male",
             "Arabic root ف ر د س (f-r-d-s)", False, "high",
             "Firdaws is the same word as Firdaus (فردوس) 'paradise', in the more classical Qur'anic transliteration. The source gloss 'highest garden of paradise' is a fair description of its Qur'anic sense (the highest level of the garden)."),
 "firdevs": ("فردوس", "فردوس", "فردوس", "फ़िरदौस", "فردوس", "paradise_garden", "Arabic", "Female",
             "Arabic فردوس (firdaws), Turkish form Firdevs", False, "high",
             "Firdevs is the Turkish form of Arabic فردوس (firdaws) 'paradise'. The source gloss 'jewel, treasure' is wrong for this form — that sense belongs to Persian گوهر (gawhar), a different word — and has not been carried over. Turkish naming usage is predominantly (though not exclusively) feminine."),
 "firdos": ("فردوس", "فردوس", "فردوس", "फ़िरदौस", "فردوس", "paradise_garden", "Arabic", "Unisex",
            "Arabic root ف ر د س (f-r-d-s)", False, "high",
            "Firdos is a South Asian spelling of فردوس (firdaws) 'paradise'. The source gloss 'garden, paradise' is defensible."),
 "firdous": ("فردوس", "فردوس", "فردوس", "फ़िरदौस", "فردوس", "paradise_garden", "Arabic", "Unisex",
             "Arabic root ف ر د س (f-r-d-s)", False, "high",
             "Firdous is a common South Asian spelling of فردوس (firdaws) 'paradise, heaven'. The source gloss 'paradise or heaven' is defensible."),
 "firnas": ("فِرناس", "فرناس", "فرناس", "फ़िरनास", "فرناس", "paradise_flyer", "Arabic", "Male",
            "Arabic فرناس (Firnās) — a personal name, not a common noun", False, "medium",
            "Firnas (فِرناس) is an Arabic personal name, best known from the Andalusi polymath ʿAbbās ibn Firnās (c. 809–887 CE), a pioneer of early gliding. The word itself has no established dictionary meaning; the 'paradise flyer' gloss in the source is a modern association with Ibn Firnas's flight experiments, not a lexical meaning, and is marked accordingly. A crater on the Moon is named after Ibn Firnas."),
 "firouz": ("فيروز", "فیروز", "فیروز", "फ़िरोज़", "فیروز", "turquoise", "Persian", "Male",
            "Persian فیروز (Fīrūz) < Middle Persian pērōz 'victorious'", False, "high",
            "Firouz is a French-influenced spelling of the Persian name فیروز (Fīrūz) 'victorious', which also names the turquoise gem (فیروزه fīrūza). The source labelled it 'Arabic' and, under language 'Persian', still gave origin 'Arabic'; the word is Persian. The source gloss 'lion, victorious' mixes a wrong sense ('lion') with a right one."),
 "firoz": ("فيروز", "فیروز", "فیروز", "फ़िरोज़", "فیروز", "turquoise", "Persian", "Male",
           "Persian فیروز (Fīrūz)", False, "high",
           "Firoz is a South Asian spelling of the Persian name فیروز (Fīrūz) 'victorious', also the source of the word for the turquoise gem. CRITICAL SOURCE ERROR: the source record gave أحمد (Ahmad) as the Arabic form of firoz and أحمد as its Urdu form — a completely different name. That has been corrected here; firoz must not be merged with Ahmad."),
 "firoza": ("فيروزة", "فیروزہ", "فیروزه", "फ़िरोज़ा", "فیروزه", "turquoise", "Persian", "Female",
            "Persian فیروزه (Fīrūza)", False, "high",
            "Firoza is the feminine form of Persian فیروز (Fīrūz), specifically فیروزه (Fīrūza) 'turquoise'. The source gave the Latin string 'Firoza' as the 'Arabic form' (not a real Arabic script form) and glossed it 'victorious, vanquisher'; the lexical sense is 'turquoise / victorious'."),
 "firuz": ("فيروز", "فیروز", "فیروز", "फ़िरोज़", "فیروز", "turquoise", "Persian", "Male",
           "Persian فیروز (Fīrūz)", False, "high",
           "Firuz is a transliteration of the Persian name فیروز (Fīrūz) 'victorious', from which the name of the turquoise gem also derives. The source gloss 'turquoise' captures the gem sense; 'victorious' is the older core sense of the base word."),
 "firuze": ("فيروزة", "فیروزہ", "فیروزه", "फ़िरोज़ा", "فیروزه", "turquoise", "Persian", "Female",
            "Persian فیروزه (Fīrūza)", False, "high",
            "Firuze is the Turkish/Persian form of فیروزه (Fīrūza) 'turquoise'. The source labelled it 'Arabic'; the word is Persian. The source gloss 'jewel, precious one' is a loose extension of the gem sense."),
 "firuzeh": ("فيروزة", "فیروزہ", "فیروزه", "फ़िरोज़ा", "فیروزه", "turquoise", "Persian", "Female",
             "Persian فیروزه (Fīrūza)", False, "high",
             "Firuzeh is a fuller transliteration of Persian فیروزه (Fīrūza) 'turquoise'. The source supplied only Latin strings ('Firuzeh') for the Arabic and Urdu forms — not valid script forms — and glossed it 'victorious one'; the lexical sense is 'turquoise'."),
 "firyal": ("فريال", "فریال", "فریال", "फ़िरयाल", "فریال", "splendour_neck", "Persian", "Female",
            "Persian فر (far) + یال (yāl)", False, "high",
            "Firyal is a variant of Feryal (فریال), a Persian feminine name analysed as فر (far) 'splendour' + یال (yāl) 'neck'. The source gloss 'compassionate and kind' is unsupported and has been replaced."),
 "fitrah": ("فِطرة", "فطرت", "فطرت", "फ़ितरत", "فطرت", "innate_nature", "Arabic", "Female",
            "Arabic root ف ط ر (f-ṭ-r)", True, "high",
            "Fitrah (فِطرة) is the Arabic word for the innate, original human disposition towards God and goodness, from the root ف ط ر (f-ṭ-r) 'to originate, create'. It appears in the Qur'an (30:30, 'the fiṭrah of Allah upon which He created mankind'). It is noted here as a QUR'ANIC WORD; its use as a personal given name is a separate, later naming practice and is not itself Qur'anic. The source gloss 'pure nature, innate disposition' is defensible."),
 "fitrat": ("فطرة", "فطرت", "فطرت", "फ़ितरत", "فطرت", "natural_disposition", "Arabic", "Unisex",
            "Arabic root ف ط ر (f-ṭ-r)", True, "high",
            "Fitrat is the Persian/Urdu reflex of Arabic فطرة (fiṭra) 'innate nature, natural constitution', from the root ف ط ر (f-ṭ-r). The underlying word appears in the Qur'an (30:30); its use as a personal name is a separate naming practice. The source gloss 'natural state or temperament' is defensible."),
 "fiza": ("فِضا", "فضا", "فضا", "फ़िज़ा", "فضا", "liberated_free", "Arabic", "Female",
          "Arabic root ف ض و (f-ḍ-w) / ف ي ض (f-y-ḍ)", False, "medium",
          "Fiza is a popular South Asian female name. Its usual form فِضا relates to Arabic فضى 'open expanse, spaciousness' (hence 'openness, freedom'), though it is also popularly associated with a different Persianate word for breeze/atmosphere. The source gloss 'blooming, radiant' is unsupported and has not been carried over; the source also gave فيضة as the Arabic form, which belongs to Feyza, not Fiza."),
 "fizah": (None, None, None, None, None, None, "Unknown", "Female",
           None, False, "unverified",
           "The source record's 'Arabic form' فضحة is not an attested lexical item, and the gloss 'breeze, gentle wind' was not corroborated by any Tier-A/B source. No verified identification was established; only the reported female naming usage is retained."),
 "fizan": (None, "فیضان", None, None, None, None, "Unknown", "Male",
           None, False, "unverified",
           "Fizan appears in South Asian naming usage; it may relate to Arabic فيضان (fayḍān) 'flood, overflow, abundance', but the spelling in the source record is too uncertain to assert a lexical identification. No meaning is claimed."),
 "fizza": ("فِضَّة", "فِضّہ", "فِضّه", "फ़िज़्ज़ा", "فِضّه", "silver", "Arabic", "Female",
           "Arabic root ف ض ض (f-ḍ-ḍ); فِضَّة (fiḍḍa)", False, "high",
           "Fizza is a South Asian spelling of Arabic فِضَّة (fiḍḍa) 'silver'. The source gloss 'silver or money' is a fair rendering of the lexical sense; the name evokes purity and brightness."),
 "fizzah": ("فِضَّة", "فِضّہ", "فِضّه", "फ़िज़्ज़ा", "فِضّه", "silver", "Arabic", "Female",
            "Arabic root ف ض ض (f-ḍ-ḍ)", False, "high",
            "Fizzah is a variant spelling of Fizza, i.e. Arabic فِضَّة (fiḍḍa) 'silver'. The source gloss 'delight, pleasure' is unsupported and has been replaced with the lexical sense."),
 "fizzi": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "unverified",
           "Fizzi is recorded in the source only through Latin strings; no script form or lexical meaning was established from any Tier-A/B source. No gloss is asserted. (The source's 'joy' and 'female' entries are unverified naming-directory claims.)"),
 "fojan": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "unverified",
           "No Tier-A/B source establishes a lexical form of this shape. The source gave the Arabic form فجان (not an attested word) and the gloss 'victorious'. No meaning is asserted."),
 "folla": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "unverified",
           "Folla is recorded in the source only through Latin strings; it corresponds to no established Arabic or Persian lexical item, and the gloss 'dewdrop' (which belongs to Persian ژاله / شبنم) is not supported. No meaning is asserted."),
 "foram": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "unverified",
           "CRITICAL SOURCE ERROR: the source record gave أحمد (Ahmad) as both the 'Arabic form' and the 'Urdu form' of foram and glossed it 'divine creator'. That is a different name entirely and no verified identification of foram exists. Nothing is asserted."),
 "foroud": ("فروود", "فروود", "فرود", "फ़रूद", "فرود", "fortune_prosperity", "Persian", "Male",
            "Persian فرود (Forūd)", False, "medium",
            "Foroud (فرود, Forūd) is a Persian male name; the source gloss 'fortune, prosperity' points to the Persian word فَرْوَد/فروود associated with auspiciousness, but the primary literary currency of فرود is as a hero's name in the Shahnameh (Forud, son of Siyavash). The source's 'Arabic form' فروود mixed a Japanese katakana character (ー) into the Arabic string, which has been corrected. Identification is probable, not certain."),
 "forough": ("فرحة", "فرحت", "فرحت", "फ़रोख़", "فرحت", "joy_happy", "Persian", "Female",
             "Persian فروغ (forūgh) 'radiance, light'", False, "medium",
             "The source record conflated two different words. The name Forough is Persian فروغ (forūgh) 'radiance, glow, light' — the source's Arabic form فرحة ('a joy', a different Arabic word) is wrong and has been corrected in sense. The source gloss 'free, liberated' matches neither. Given the conflict, the Persian 'radiance' reading is recorded as the probable identification of the name Form."),
 "forouz": (None, "فروز", "فروز", None, "فروز", "victory_triumph", "Persian", "Female",
            "Persian فیروز/فروز (Fīrūz/Forūz) 'victorious'", False, "medium",
            "Forouz corresponds to the Persian element فروز/فیروز (forūz/fīrūz) 'victorious, shining' (as in فیروزی 'victory'). The source supplied only Latin strings for the script forms in several slots; the Persian form فروز is given here. The gloss 'victory, triumph' is defensible as the abstract noun."),
 "forouzan": (None, "فروزاں", "فروزان", None, "فروزان", "radiant_blooming", "Persian", "Female",
              "Persian فروزان (forūzān) 'shining, radiant'", False, "high",
              "Forouzan is the Persian feminine name فروزان (Forūzān) 'shining, radiant, luminous', the present participle of فروختن/فروزیدن 'to shine'. Its relationship to فیروز (Fīrūz) is real but the two are distinct forms. CRITICAL SOURCE ERROR: the source gave علی (Ali) as the Arabic form of forouzan — a different name — which has been removed. The source gloss 'victory, triumph' is not the lexical sense."),
 "fouad": ("فؤاد", "فؤاد", "فؤاد", "फ़ुआद", "فؤاد", "heart", "Arabic", "Male",
           "Arabic root ف أ د (f-ʾ-d)", False, "high",
           "Fouad (فؤاد, fuʾād) is an Arabic male name meaning 'heart, the innermost heart' — often rendered 'heart, mind, inner self'. The source gloss 'river' is wrong (that is Furat, فرات) and has been replaced."),
 "fouzan": (None, "فوزان", "فوزان", "फ़ौज़ान", "فوزان", None, "Arabic", "Unisex",
            "Arabic root ف و ز (f-w-z) 'to succeed, triumph'", False, "low",
            "Fouzan relates in form to the Arabic root ف و ز (f-w-z) 'to succeed, be victorious' (cf. فوز fawz 'success', فائز fāʾiz 'winner'), and is current in South Asian Muslim naming with the sense 'success, triumph'. The source gloss 'protector' is a different root (ح ف ظ) and is not supported; the name is recorded at low confidence as a naming form of فوز."),
 "fouzia": ("فوزية", "فوزیہ", "فوزیه", "फ़ौज़िया", "فوزیه", "victorious_triumphant", "Arabic", "Female",
            "Arabic root ف و ز (f-w-z); فوزية (Fawziyya)", False, "high",
            "Fouzia is a transliteration of Arabic فوزية (Fawziyya), the feminine of فوزي (Fawzī), from the root ف و ز (f-w-z) 'to triumph, succeed'. It means 'victorious, triumphant, successful'. The source gloss 'fragrant blossom' is wrong and has been replaced."),
 "fouziah": ("فوزية", "فوزیہ", "فوزیه", "फ़ौज़िया", "فوزیه", "victorious_triumphant", "Arabic", "Female",
             "Arabic root ف و ز (f-w-z)", False, "high",
             "Fouziah is a variant spelling of Fouzia, Arabic فوزية (Fawziyya) 'victorious, triumphant'. The source gloss 'victorious, triumphant' is correct here (the source assigned the correct gloss to fouziah and the wrong one to fouzia — they are the same name)."),
 "fozhan": (None, "فوژان", "فوژان", None, "فوزان", None, "Persian", "Male",
            None, False, "low",
            "Fozhan (فوژان) is current in Persian and South Asian naming, but no Tier-A/B source establishes a settled lexical meaning; the source gloss 'wise, intelligent' and the source form فوزان (which is Fouzan) are both unverified for this shape. Only probable Persianate naming usage is recorded, at low confidence."),
 "fozia": ("فوزية", "فوزیہ", "فوزیه", "फ़ौज़िया", "فوزیه", "victorious_triumphant", "Arabic", "Female",
           "Arabic root ف و ز (f-w-z)", False, "high",
           "Fozia is a South Asian spelling of Arabic فوزية (Fawziyya) 'victorious, triumphant', from the root ف و ز. The source gloss 'protector, defender' is wrong (that sense belongs to Arabic حفيظة) and has been replaced. The source's 'Arabic form' Fahzia and the Urdu form فظية are also non-standard and were corrected."),
 "foziah": ("فوزية", "فوزیہ", "فوزیه", "फ़ौज़िया", "فوزیه", "victorious_triumphant", "Arabic", "Female",
            "Arabic root ف و ز (f-w-z)", False, "high",
            "Foziah is a variant spelling of Fozia / فوزية (Fawziyya) 'victorious, triumphant'. The source gloss 'intelligent, wise' is unsupported for this form and has been replaced with the lexical sense."),
 "fuad": ("فُؤَاد", "فؤاد", "فؤاد", "फ़ुआद", "فؤاد", "heart", "Arabic", "Male",
          "Arabic root ف أ د (f-ʾ-d); فُؤَاد (fuʾād)", False, "high",
          "Fuad (فُؤَاد, fuʾād) is an Arabic male name meaning 'heart, the inner heart'. The source gloss 'heart, love' is nearly right; 'love' is an extension. It is a well-established Arabic given name."),
 "fuada": ("فؤادة", "فؤادہ", "فؤاده", "फ़ुआदा", "فؤاده", "heart", "Arabic", "Female",
           "Arabic root ف أ د (f-ʾ-d)", False, "medium",
           "Fuada is the feminine form (فؤادة) of فؤاد (fuʾād) 'heart'. The source gloss 'abundance, prosperity' is unsupported for this form (that is فيضة, Feyza's root) and has been replaced."),
 "fuhad": ("فُهْد", "فہد", "فهده", "फ़ुहद", "فهد", None, "Arabic", "Male",
           "Arabic root ف ه د (f-h-d)", False, "low",
           "Fuhad most plausibly corresponds to Arabic فهد (fahd) 'cheetah, leopard' — a long-established Arabic male name — with the vowel spelling varied. The source gloss 'knowledge, wisdom' belongs to a different root (ف ه م / ح ك م) and is not supported. Given the spelling uncertainty the sense 'cheetah' is offered at low confidence."),
 "fullah": ("فُلّة", "فلّہ", "فلّه", "फ़ुल्ला", "فلّه", None, "Arabic", "Female",
            None, False, "low",
            "Fullah corresponds in form to Arabic فُلّة (fulla) 'jasmine blossom' — a plausible female given name in Arabic and South Asian usage. The source gloss 'abundance, generosity' is unsupported for this form. Given the limited attestation, the 'jasmine' reading is offered at low confidence."),
 "furat": ("فُرات", "فرات", "فرات", "फ़ुरात", "فرات", "sweet_water", "Arabic", "Unisex",
           "Arabic root ف ر ت (f-r-t); فُرات (Furāt)", False, "high",
           "Furat (فُرات) is the Arabic name of the Euphrates, literally 'sweet, pure, refreshing water'. It was borne by companions of the Prophet (Furat bin Hayyan and others). The source gloss 'little river' is a loose rendering of the 'fresh water' sense. The source's 'Male/Female/Unisex' gender string was normalised."),
 "furqaan": ("فُرْقان", "فرقان", "فرقان", "फ़ुरक़ान", "فرقان", "criterion", "Arabic", "Male",
             "Arabic root ف ر ق (f-r-q); فُرْقان (Furqān)", True, "high",
             "Furqaan (فُرْقان) means 'that which distinguishes truth from falsehood, the criterion', from the root ف ر ق (f-r-q) 'to separate, distinguish'. It is a QUR'ANIC WORD — al-Furqān is a name of the Qur'an itself (Surah 25) — and the root sense appears in the Qur'an; its use as a personal given name is a separate naming practice. The source gloss 'divine guidance' is a loose paraphrase of 'criterion'."),
 "furqan": ("فُرْقان", "فرقان", "فرقان", "फ़ुरक़ान", "فرقان", "criterion", "Arabic", "Male",
            "Arabic root ف ر ق (f-r-q)", True, "high",
            "Furqan is the standard transliteration of فُرْقان (Furqān) 'the criterion, the distinguisher of truth from falsehood'. It is a Qur'anic word (al-Furqān, Surah 25) rather than a Qur'anic personal name. The source record for this slug was empty (origin 'Unknown', no data) and has been completed from the form itself."),
 "fursan": ("فرسان", "فرسان", "فرسان", "फ़ुरसान", "فرسان", "riders", "Arabic", "Male",
            "Arabic root ف ر س (f-r-s); فُرسان (fursān) plural of فارس (fāris)", False, "high",
            "Fursan (فُرسان) is the Arabic plural of فارس (fāris) 'knight, horseman' — 'riders, horsemen, cavaliers'. It is used as a male given name. The source gloss 'riders of the steeds' is a poetic expansion of 'horsemen'."),
 "fusun": (None, "افسون", "افسون", None, "افسون", None, "Persian", "Female",
           "Persian افسون (afsūn) 'charm, enchantment, magic'", False, "medium",
           "Fusun is the Turkish form of the Persian feminine name افسون (Afsūn) 'charm, enchantment, spell'. The source gave فسون (which is the same word with the initial alef dropped) and the gloss 'moon, star', which is unsupported — that sense belongs to different names (e.g. Mah, Sitara). The identification as Afsun is probable."),
 "futoon": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "unverified",
            "No lexical identification was established for futoon. The source gave فتونه and the gloss 'happiness', neither of which is corroborated. No meaning is asserted. (Note: the ordinary Arabic word فتون futūn means 'bewitchment, seduction, allure' and is a different sense and form.)"),
 "fuzail": ("فُضَيل", "فضیل", "فضیل", "फ़ुज़ैल", "فضیل", "pious_god_fearing", "Arabic", "Male",
            "Arabic root ف ض ل (f-ḍ-l); فُضَيل (Fuḍayl)", False, "high",
            "Fuzail (فُضَيل, Fuḍayl) is the diminutive of فَضْل (faḍl) 'excellence, virtue', from the root ف ض ل (f-ḍ-l). It was borne by the early ascetic Fuḍayl ibn ʿIyāḍ. The source gloss 'pious, God-fearing' reflects the religious reputation of that bearer rather than the lexical sense, which is 'little excellence / of virtue'."),
 "gabina": (None, None, None, None, None, None, "Unknown", "Unknown",
            None, False, "unverified",
            "Gabina is recorded in the source only through Latin strings and does not correspond to an established Arabic or Persian lexical item; the gloss 'young girl' is unsupported. (Gabina is a Spanish/Slavic name, a different tradition.) No meaning is asserted."),
 "gabir": ("جبر", "جابر", "جابر", "जाबिर", "جابر", "compeller_helper", "Arabic", "Male",
           "Arabic root ج ب ر (j-b-r); جابر (Jābir)", False, "medium",
           "Gabir most plausibly corresponds to Arabic جابر (Jābir) 'one who sets a broken bone, restores, helps; the compeller', from the root ج ب ر (j-b-r). The source gave جابر as the Arabic form but جیبر as the Urdu form (non-standard) and glossed it 'the one who is free from anger', which is a different root (ك ظ م). The identification with Jābir is probable."),
 "gabr": ("جَبْر", "جبر", "جبر", "जब्र", "جبر", "compeller_helper", "Arabic", "Male",
          "Arabic root ج ب ر (j-b-r); جَبْر (jabr)", False, "medium",
          "Gabr corresponds to the Arabic word جَبْر (jabr) 'restoration, compulsion, setting (of a bone)', from the root ج ب ر (j-b-r). The source gloss 'mountain' is wrong (that is جبل jabal) and has been replaced. It is used as a given name, though less commonly than the derived Jābir (gabir)."),
 "gadaa": ("غَداء", "غدا", "غذا", "ग़दा", "غذا", None, "Arabic", "Unisex",
           "Arabic root غ د و (gh-d-w); غَداء (ghadāʾ)", False, "low",
           "Gadaa corresponds in form to Arabic غَداء (ghadāʾ) 'morning meal' or to the root غ د و 'morning', but the source gloss 'strong, powerful' belongs to a different root (ق و ي / ق د ر) and is unsupported. Identification is uncertain; no confident gloss is asserted beyond the probable lexical shape."),
 "gaddafi": (None, "قذافی", "قذافی", "गद्दाफ़ी", "قذافي", None, "Arabic", "Male",
             "Arabic قذافي (Qaḏḏāfī) — a surname/nisba, not a lexical given name", False, "medium",
             "Gaddafi corresponds to Arabic قذافي (Qaḏḏāfī), the surname of the Libyan leader Muammar Gaddafi. It is a nisba/surname rather than a lexical given name, and has no established dictionary meaning; the source gloss 'one who is trustworthy' (which belongs to أمين/موثوق) is unsupported and has been removed. The source's 'Arabic form' was literally the Latin-inserted string 'غaddafi', which has been corrected."),
 "gafar": ("غَفّار", "غفار", "غفار", "ग़फ़्फ़ार", "غفار", "forgiving_generous", "Arabic", "Male",
           "Arabic root غ ف ر (gh-f-r); غَفّار (Ghaffār)", False, "high",
           "Gafar is a South Asian spelling of Arabic غفار (Ghaffār) 'most forgiving, ever-forgiving', an intensive adjective from the root غ ف ر (gh-f-r) 'to forgive'. It is also a divine name in Islamic tradition. The source gave the non-standard عَفّار as the Arabic form and glossed it 'carrier of a heavy burden' (that sense belongs to حمّال/حمال), both of which were corrected."),
 "gafoor": (None, "غفور", "غفور", "ग़फ़ूर", "غفور", "forgiving_generous", "Arabic", "Male",
            "Arabic root غ ف ر (gh-f-r); غَفور (Ghafūr)", False, "high",
            "Gafoor is a South Asian spelling of Arabic غفور (Ghafūr) 'most forgiving', an intensive adjective from the root غ ف ر (gh-f-r) and a divine name in Islamic tradition. The source gave غفور in the Arabic slot (though with a mis-typed Urdu string) and glossed it 'generous', which is close but should be 'forgiving'."),
 "galai": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "unverified",
           "Galai is recorded in the source only through Latin strings and corresponds to no established Arabic or Persian lexical item; the gloss 'small flower' is unsupported. No meaning is asserted."),
 "galal": ("جلال", "جلال", "جلال", "जलाल", "جلال", "majesty_greatness", "Arabic", "Male",
           "Arabic root ج ل ل (j-l-l); جَلال (Jalāl)", False, "high",
           "Galal is an Egyptian / South Asian spelling of Arabic جلال (Jalāl) 'majesty, greatness, splendour', from the root ج ل ل (j-l-l). The source gloss 'continuity, perpetuity' is a different root (د و م) and has been replaced."),
 "galawezh": (None, "گەلاوێژ", "گەلاوێژ", None, "ګلاویژ", None, "Kurdish", "Female",
              None, False, "medium",
              "Galawezh (Gelavêj / Galawej) is a Kurdish feminine name, recorded in Kurdish name references as the Kurdish name of a bright star — the constellation Sirius / Canopus (variously reported). CRITICAL SOURCE ERROR: the source gave أحمد (Ahmad) as the Arabic form and labelled it Arabic; the name is Kurdish, not Arabic. The exact astronomical identification varies between sources, so 'bright star (Sirius/Canopus)' is reported with that caveat."),
 "galib": ("غالِب", "غالب", "غالب", "ग़ालिब", "غالب", "powerful_victorious", "Arabic", "Male",
           "Arabic root غ ل ب (gh-l-b); غالِب (Ghālib)", False, "high",
           "Galib/ghalib is Arabic غالِب (Ghālib) 'overcomer, victor, dominant', the active participle of the root غ ل ب (gh-l-b) 'to overcome'. The source gloss 'powerful, victorious' is defensible. It is also a divine name in Islamic tradition."),
 "galila": (None, "جلیلة", "جلیله", None, None, None, "Arabic", "Female",
            "Arabic root ج ل ل (j-l-l); جليلة (Jalīla)", False, "medium",
            "Galila is a variant spelling of Arabic جليلة (Jalīla) 'great, exalted, majestic' (feminine of جليل Jalīl), from the root ج ل ل (j-l-l). The source supplied only the Latin string 'Galila' for the script form and glossed it 'joy, gladness, and grace' — that gloss belongs to a different root (ف ر ح) and has been replaced with the 'majestic' sense."),
 "gamal": ("جمال", "جمال", "جمال", "जमाल", "جمال", "beautiful", "Arabic", "Male",
           "Arabic root ج م ل (j-m-l); جَمال (Jamāl)", False, "high",
           "Gamal is an Egyptian spelling of Arabic جمال (Jamāl) 'beauty, handsomeness', from the root ج م ل (j-m-l). The source gloss 'camel driver' is a confusion with جَمّال (jammāl) 'camel driver' and has been removed; the correct sense is 'beauty'. It is well known from Gamal Abdel Nasser."),
 "gamil": ("جميل", "جمیل", "جمیل", "जमील", "جمیل", "beautiful", "Arabic", "Male",
           "Arabic root ج م ل (j-m-l); جَميل (Jamīl)", False, "high",
           "Gamil is an Egyptian spelling of Arabic جميل (Jamīl) 'beautiful, handsome', from the root ج م ل (j-m-l). The source gloss 'reward, compensation' is a different root (ج ز ي) and has been replaced."),
 "gamila": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful", "Arabic", "Female",
            "Arabic root ج م ل (j-m-l); جميلة (Jamīla)", False, "high",
            "Gamila is an Egyptian spelling of Arabic جميلة (Jamīla) 'beautiful, lovely', the feminine of جميل (Jamīl). The source gloss 'young camel' is a confusion with جَمَل (jamal) 'camel' and has been replaced."),
 "gamze": ("غَمْزة", "غمزہ", "غمزه", "ग़मज़ा", "غمزه", "rose_smile", "Turkish", "Female",
            "Turkish gamze 'dimple'; from Arabic غَمْز (ghamz)", False, "high",
            "Gamze is a Turkish feminine given name meaning 'dimple' (and, by extension, 'smile'). It derives historically from the Arabic noun غَمْز/غَمْزة (ghamz/ghamza) 'a wink, a sidelong glance', but as a personal name it is Turkish. The source gloss 'rose' belongs to a different name (Gül) and has been replaced."),
 "ganiyah": ("غنية", "غنیہ", "غنيه", "ग़निया", "غنيه", "owner_possessor", "Arabic", "Female",
             "Arabic root غ ن ي (gh-n-y); غنية (Ghaniyya)", False, "high",
             "Ganiyah corresponds to Arabic غنية (Ghaniyya) 'rich, free from want, self-sufficient', the feminine of غني (Ghaniyy), from the root غ ن ي (gh-n-y). The source gloss 'owner, possessor' captures the cognate غنيّ 'possessor (of wealth)'."),
 "gauhar": (None, "گوہر", "گوهر", None, "ګوهر", "gem", "Persian", "Female",
            "Persian گوهر (gawhar) < Middle Persian gōhr 'substance, essence; jewel'", False, "high",
            "Gauhar (also Gohar) is the Persian word گوهر (gawhar) 'jewel, gem, pearl', and by extension 'essence, substance, intrinsic worth' (Middle Persian gōhr). It is used across Persian, Urdu and Pashto naming. The source gave a Devanagari character (ह) inside the 'Arabic form' (غوهر) — a script-mixing defect — and glossed it 'precious gem', which is correct."),
 "gawdat": (None, "جودت", "جودت", None, "جودت", None, "Arabic", "Male",
            "Arabic root ج و د (j-w-d); جودت (Jawdat)", False, "medium",
            "Gawdat/Gawdat is an Egyptian spelling of Arabic جودت (Jawdat), a verbal-noun form from the root ج و د (j-w-d) 'to be excellent, generous'. It means 'excellence, goodness, generosity'. The source gave a string containing a Devanagari/Arabic mixture (غودات) and glossed it 'protector' (a different root, ح ف ظ), both of which were corrected. The identification is probable rather than certain."),
 "gazala": ("غزالة", "غزالہ", "غزاله", "ग़ज़ाला", "غزاله", "gazelle_like", "Arabic", "Female",
            "Arabic root غ ز ل (gh-z-l); غزالة (Ghazāla)", False, "high",
            "Gazala is Arabic غزالة (Ghazāla) 'gazelle', a traditional female name and a classical Arabic byword for grace and beauty (a gazelle is a standard simile in Arabic poetry). The source gloss 'gazelle-like' is a fair rendering."),
 "gede": (None, None, None, None, None, None, "Unknown", "Unknown",
          None, False, "unverified",
          "Gede is recorded in the source only through Latin strings and does not correspond to an established Arabic or Persian lexical item; the gloss 'mountain' belongs to different forms (Persian کوه, Arabic جبل). (Gede is also an Indonesian/Javanese name, a different tradition.) No meaning is asserted."),
 "geela": ("جِيلة", "جیلہ", "گیله", "गीला", "گیله", None, "Arabic", "Female",
           None, False, "low",
           "Geela corresponds to Arabic جِيلة (Jīla) 'a generation, a people', from the root ج ي ل. The source gave جِل (a different shape) and glossed it 'joyful, delightful' (which belongs to a different root, ف ر ح), and the identification of geela as a personal name is uncertain. Recorded at low confidence."),
 "ghada": ("غادة", "غادہ", "غاده", "ग़ादा", "غاده", "graceful_slender", "Arabic", "Female",
           "Arabic root غ د و (gh-d-w); غادة (Ghāda)", False, "high",
           "Ghada (غادة, Ghāda) is an Arabic feminine given name describing a graceful, slender, gentle young woman — a classical word from poetry, and also the name of the saxaul tree (Haloxylon persicum). It appears in the source with completely empty data (origin 'Unknown'), which has now been completed. It is a well-known modern Arabic name (e.g. Ghada Karmi)."),
 "ghadah": ("غادة", "غادہ", "غاده", "ग़ादा", "غاده", "graceful_slender", "Arabic", "Female",
            "Arabic root غ د و (gh-d-w)", False, "high",
            "Ghadah is a variant transliteration of Arabic غادة (Ghāda) 'graceful, slender young woman'. The source gloss 'flowing river' belongs to a different word (غدير, ghadir) and has been replaced."),
 "ghadeer": ("غدير", "غدیر", "غدیر", "ग़दीर", "غدیر", "small_stream", "Arabic", "Female",
             "Arabic root غ د ر (gh-d-r); غدير (Ghadīr)", False, "high",
             "Ghadeer (غدير) is Arabic for 'a small stream, brook, pool of running water' — used as a feminine given name. It is historically resonant because of Ghadir Khumm, the site of the Event of Ghadir. The source gloss 'river, flow' is a fair rendering of the 'small stream' sense."),
 "ghadi": ("غادي", "غادی", "غادی", "ग़ादी", "غادي", "swift", "Arabic", "Unisex",
           "Arabic root غ د و (gh-d-w); غادي (Ghādī)", False, "medium",
           "Ghadi corresponds to Arabic غادي (Ghādī) 'one who goes in the morning; going, going early', the active participle of the root غ د و (gh-d-w). The source gloss 'swift' is a loose extension. It is used for both sexes in Arabic-speaking countries."),
 "ghadia": ("غادية", "غادیہ", "غادیه", "ग़ादिया", "غادیه", "journey", "Arabic", "Female",
            "Arabic root غ د و (gh-d-w)", False, "medium",
            "Ghadia corresponds to Arabic غادية (Ghādiya), the feminine active participle of the root غ د و (gh-d-w) — 'one who goes out in the morning; a morning cloud, a traveller'. The source gloss 'journey, travel' reflects that sense; the form is a real word but its currency as a personal name is limited."),
 "ghadir": ("غدير", "غدیر", "غدیر", "ग़दीर", "غدیر", "small_stream", "Arabic", "Female",
            "Arabic root غ د ر (gh-d-r)", False, "high",
            "Ghadir (غدير) is the same Arabic word as Ghadeer — 'small stream, brook, pool' — and a feminine given name. The source gloss 'place of radiance' is unsupported (it appears to be a confusion with نور/ضياء) and has been replaced."),
}
