# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 33 (jawahar..kadir).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": jazi -> "جazi" (mixed Latin); jazib ->
   جازيب with a Cyrillic а (junk); jeelan -> جیلان (Persian letters); jehanzeb ->
   جهـانزێب (Kurdish letter); jena -> عائشة (a different name entirely);
   jibran -> "عربي_Jibran" (junk); jidah -> "Jidah" (Latin); jivan -> "Jivan"
   (Latin); johi -> "Johi" (Latin); juda -> "Juda" (Latin); junna -> "Junna"
   (Latin); jibreel/jouri/jumana/jumanah/jun/junaid/jwan -> None (missing);
   ka-b -> كعب (should be كعب, ok); kader -> كدر (should be قادر);
   kadeer -> قادر (should be قدير); kadeem -> قديم (should be كريم? no, قديم ok);
   kaddour -> كادور (should be قدور); kadeen -> كادين (should be كادين, ok).
 * DEGARBLED / WRONG glosses: jawaher 'Jewels' (should be 'jewels', ok);
   jawahir 'Pearls' (should be 'jewels'); jawaid 'Generous, Benefactor' (should
   be 'eternal', Persian); jawara 'Gentle, Kind' (unsupported); jawdat 'Generous'
   (should be 'excellence'); jawhari 'Pearl' (should be nisba of jawhar);
   jawid 'Continuous, Everlasting' (should be 'eternal', Persian); jaya
   'Victory, Triumph' (should be 'victory', Sanskrit); jayed 'Prosperous, Rich'
   (should be 'good'); jazi 'Gift' (unsupported); jazib 'A name that means dark
   or night' (should be 'attractive, alluring'); jazlaan 'Glowing Gem'
   (unsupported); jazmin 'Giver of Jasmine' (should be 'jasmine'); jeelan
   'Gentle, Delicate, Beautiful' (should be 'Gilan', Persian place); jeevan
   'Life, Soul, Living' (should be 'life', Sanskrit); jehad 'Struggle in the way
   of Allah' (correct); jehan "God's gift" (should be 'world', Persian);
   jehanzeb 'Beauty of the World' (correct, Persian); jemina 'Gentle, beautiful'
   (unsupported); jena 'Daughter of Janah or beautiful' (should be 'paradise');
   jennah 'Garden' (correct); jeroen 'Light, bright, shining' (should be a Dutch
   name); jian 'Surname: Simple, plain' (should be a Chinese name); jibal
   'Mountain, Elevated' (should be 'mountains'); jibrail 'Gentle, Compassionate,
   Noble' (should be the angel Gabriel); jibran 'Noble and blessed' (should be
   'Jubran'); jibriil 'The most generous one' (should be the angel Gabriel);
   jibril 'Angel Gabriel' (correct); jidah 'traveller, pilgrim' (unsupported);
   jigar 'Heart, Soul' (should be 'liver', Persian); jihaad 'Struggle, Jihad'
   (correct); jihad 'Struggle, striving, effort' (correct); jihan 'Heavenly
   Paradise' (should be 'world', Persian); jilan 'Gentle, Graceful, Beautiful
   Tree' (should be 'Gilan', Persian place); jilani 'Gentle, gracious' (should be
   nisba of Jilan); jina 'Born of great virtue' (unsupported); jinan 'Gentle flow
   of water' (should be 'gardens'); jirah 'Peaceful' (unsupported); jivan
   'Living, Eternal Life' (should be 'life', Sanskrit); jiyan 'Living' (should be
   'life', Kurdish); johar 'Grain, seed' (should be 'jewel'); johara 'Graceful,
   generous' (should be 'jewel', fem); johi 'Gift from God' (unsupported); jonah
   'Dove' (should be the prophet Yunus); jood 'Grapes' (should be 'generosity');
   joodi 'Gentle, Beautiful' (should be 'of Judi', the mountain); josha "God's
   Gift" (unsupported); joud 'Generosity, abundance' (correct); jubair 'Gatherer,
   Owner' (should be diminutive of Jabir); jubran 'Good, Virtuous' (should be
   'Jubran'); jud 'Given' (should be 'generosity'); juda 'Praise, Hymn, Giving
   thanks' (unsupported); juday 'Unknown' (unsupported); jul 'Short, little,
   young' (unsupported); jumaa 'Friday, Congregation' (correct); jumaat
   'Gathering, Friday' (correct); jumadi 'Follower of the moon' (should be
   'Jumada', a month); jumah 'Assembly or Congregation' (correct); juman 'Gentle,
   Gracious' (should be 'pearls'); jumman 'Plentiful, Rich' (should be 'pearls');
   junaida 'Given by God' (should be 'Junayd, fem'); junaidah 'Gracious' (should
   be 'Junayd, fem'); junaina 'Gracious, gentle woman' (should be diminutive of
   janna); junainah 'Mature, adorned with grace' (should be diminutive of janna);
   junayd 'Religious devotee' (should be 'Junayd', a name); juni 'Moonlight'
   (unsupported); junna 'Grace, Gentleness' (should be 'garden'); juwairiya
   'Companion in Paradise' (should be the name Juwayriyya); juwan 'Yellow'
   (unsupported); juyal 'Gentle and Joyful' (unsupported); juzar 'Tiger' (should
   be 'butcher', Persian); juzer 'Abundance of Flowers' (should be 'butcher',
   Persian); ka-b 'Apostle of Allah' (should be the name Ka'b); kaab 'A grave,
   tomb, or burial place' (should be the name Ka'b); kaamil 'Perfect, Complete'
   (correct); kabeer 'Great, Big' (correct); kabir 'Great, Grand' (correct);
   kabira 'Great, Large' (correct, fem); kadar 'Capacity, Ability, Power'
   (should be 'destiny, decree'); kaddour 'Servant of God' (should be 'Qaddur');
   kadeem 'Ancient, Everlasting' (should be 'Qadim'); kadeen 'Pure, Innocent,
   Beautiful' (unsupported); kadeer 'Generous, Magnificent' (should be 'Qadir');
   kader 'Provider, Provider, Helper, Guardian' (should be 'Qadir'); kadin
   'Servant, helper' (unsupported); kadir 'Capable, Able' (correct).
 * MISLABELLED ORIGIN: jawaid (Persian), jawid (Persian), jaya (Sanskrit),
   jeevan (Sanskrit), jehan (Persian), jehanzeb (Persian), jeroen (Dutch),
   jian (Chinese), jigar (Persian), jihan (Persian), jilan (Persian),
   jivan (Sanskrit), jiyan (Kurdish), juzar (Persian), juzer (Persian),
   jonah (Hebrew/Arabic Yunus).
 * GENDER ERRORS: jawaher, jawahir, jawdat, jawid, jaya, jayed, jazi, jazib,
   jazlaan, jeevan, jibal, jibrail, jibriil, jigar, jirah, jivan, jiyan, johar,
   johi, jood, josha, jud, juda, juday, jul, jumaa, jumaat, jumah, juman, jumman,
   juyal, kaab, kadar, kaddour, kadeem, kader, kadin were labelled female or
   unisex where documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: jibreel, jouri, jumana, jumanah, jun, junaid,
   jwan (8-key stubs); jazi, jazib, jazlaan, jemina, jeroen, jian, jidah, jina,
   jirah, johi, josha, juda, juday, jul, jumadi, juni, junna, juwan, juyal,
   ka-b, kadeen, kadin.
 * DUPLICATE CLUSTERS: jawahar/jawaher/jawahir/jawhar/johar;
   jawhara/jawharat/johara; jawid/jawaid; jawwad/jawad/jawaad;
   jehad/jihaad/jihad; jehan/jihan; jehanzeb/jahanzeb;
   jibrail/jibreel/jibriil/jibril; jibran/jubran; jinan/janan;
   jood/joud/jud; jumaa/jumah/jumaat; juman/jumman/jaman;
   junaid/junayd; junaida/junaidah; junaina/junainah;
   juwairiya/juwayriyya/javeria; juzar/juzer;
   kaab/ka-b; kabeer/kabir; kadeer/kadir/kader/kadar;
   kadeem/kadim.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated32 import GLOSSES as _G32

GLOSSES = dict(_G32)
GLOSSES.update({
    "jewel": {"en": "Jewel, gem, precious stone", "ur": "جوہر، نگ، قیمتی پتھر", "fa": "گوهر، جواهر، سنگ قیمتی", "hi": "रत्न, जौहर, बहुमूल्य पत्थर", "ps": "غمه، جوهر، قیمتي ډبره", "ar": "الجوهر، الجوهرة، الحجر الكريم"},
    "jewel_f": {"en": "Jewel, gem (feminine)", "ur": "جوہرہ، نگینہ", "fa": "گوهره، جواهر (مؤنث)", "hi": "रत्न (स्त्री)", "ps": "غمه (ښځينه)", "ar": "الجوهرة، الجوهر (مؤنث)"},
    "jawhari": {"en": "Jawhari; of the jewel, jeweller", "ur": "جواہری، جوہری، سنار", "fa": "جواهری، گوهرشناس", "hi": "जौहरी, रत्नकार", "ps": "جوهري، غمې پلورونکی", "ar": "الجَوْهَرِيّ، بائع الجواهر"},
    "excellence_jawdat": {"en": "Excellence, quality, merit", "ur": "جودت، عمدگی، اچھائی", "fa": "جودت، کیفیت، برتری", "hi": "उत्कृष्टता, गुणवत्ता", "ps": "جودت، ښېګڼه، کیفیت", "ar": "الجودة، الإتقان، الحسن"},
    "jaya": {"en": "Jaya; victory (Sanskrit)", "ur": "جیا، فتح (سنسکرت)", "fa": "جایا، پیروزی (سانسکریت)", "hi": "जया, विजय (संस्कृत)", "ps": "جایا، بریا (سانسکریت)", "ar": "جايا، النصر (سنسكريتية)"},
    "good_excellent": {"en": "Good, excellent, fine", "ur": "جید، اچھا، بہتر", "fa": "جید، خوب، نیکو", "hi": "अच्छा, उत्तम, जय्यद", "ps": "ښه، غوره، جید", "ar": "الجيد، الحسن، الطيب"},
    "island": {"en": "Island, peninsula", "ur": "جزیرہ، ٹاپو", "fa": "جزیره، شبهجزیره", "hi": "द्वीप, टापू", "ps": "جزیره، ټاپو", "ar": "الجزيرة، شبه الجزيرة"},
    "attractive": {"en": "Attractive, alluring, charming", "ur": "جاذب، دلکش، موہ لینے والا", "fa": "جاذب، دلربا، فریبنده", "hi": "आकर्षक, मोहक, जाज़िब", "ps": "جاذب، زړه ښکلوونکی", "ar": "الجاذب، الجالب، الفاتن"},
    "jazlaan": {"en": "Jazlaan; a male given name", "ur": "جزلان (مردانہ نام)", "fa": "جزلان (نام مردانه)", "hi": "जज़लान (पुरुष नाम)", "ps": "جزلان (نر نوم)", "ar": "جَزْلَان (اسم علم مذكر)"},
    "gilan": {"en": "Gilan; a region of Iran (Persian)", "ur": "گیلان، ایران کا علاقہ", "fa": "گیلان، استان گیلان", "hi": "गीलान, ईरान का प्रांत", "ps": "گیلان، د ایران سیمه", "ar": "جيلان، إقليم في إيران (فارسي)"},
    "life_sanskrit": {"en": "Life, living, soul (Sanskrit)", "ur": "جیون، زندگی، روح (سنسکرت)", "fa": "جیوان، زندگی، جان (سانسکریت)", "hi": "जीवन, प्राण, जीव", "ps": "ژوند، ژوندون، روح", "ar": "الحياة، الروح (سنسكريتية)"},
    "struggle": {"en": "Struggle, striving, effort", "ur": "جہاد، کوشش، جدوجہد", "fa": "جهاد، کوشش، تلاش", "hi": "जिहाद, संघर्ष, प्रयास", "ps": "جهاد، هڅه، مبارزه", "ar": "الجهاد، الكفاح، السعي"},
    "world_jehan": {"en": "World, universe (Persian)", "ur": "جہان، دنیا، عالم", "fa": "جهان، دنیا، عالم", "hi": "दुनिया, जहान, विश्व", "ps": "جهان، نړۍ، عالم", "ar": "الجهان، العالم، الكون (فارسي)"},
    "jemina": {"en": "Jemina; a female given name", "ur": "جمینہ (زنانہ نام)", "fa": "جمینه (نام زنانه)", "hi": "जेमिना (स्त्री नाम)", "ps": "جمینه (ښځينه نوم)", "ar": "جَمِينَة (اسم علم مؤنث)"},
    "jeroen": {"en": "Jeroen; a Dutch male given name", "ur": "جیرون (ڈچ نام)", "fa": "یرون (نام هلندی)", "hi": "जेरून (डच नाम)", "ps": "جیرون (هالینډي نوم)", "ar": "يِرون (اسم علم مذكر هولندي)"},
    "jian": {"en": "Jian; a Chinese given name", "ur": "جیان (چینی نام)", "fa": "جیان (نام چینی)", "hi": "जियान (चीनी नाम)", "ps": "جیان (چینایي نوم)", "ar": "جيان (اسم علم صيني)"},
    "mountains": {"en": "Mountains, mounts", "ur": "جبال، پہاڑ", "fa": "جبال، کوهها", "hi": "पहाड़, जिबाल", "ps": "غرونه، جبال", "ar": "الجبال، جمع جبل"},
    "jibran": {"en": "Jibran; a male given name", "ur": "جبران (مردانہ نام)", "fa": "جبران (نام مردانه)", "hi": "जिब्रान (पुरुष नाम)", "ps": "جبران (نر نوم)", "ar": "جِبْرَان (اسم علم مذكر)"},
    "jidah": {"en": "Jidah; a female given name", "ur": "جدہ (زنانہ نام)", "fa": "جده (نام زنانه)", "hi": "जिदा (स्त्री नाम)", "ps": "جده (ښځينه نوم)", "ar": "جِدَة (اسم علم مؤنث)"},
    "liver": {"en": "Liver; (figuratively) heart, courage (Persian)", "ur": "جگر، کلیجہ، دل", "fa": "جگر، دل، قلب", "hi": "जिगर, कलेजा, दिल", "ps": "جګر، زړه، ځيګر", "ar": "الجگر، الكبد، القلب (فارسي)"},
    "jilani": {"en": "Jilani; of Gilan, belonging to Gilan", "ur": "گیلانی، گیلان سے منسوب", "fa": "گیلانی، منسوب به گیلان", "hi": "गीलानी, गीलान से", "ps": "گیلاني، د گیلان اړوند", "ar": "الجِيلَانِيّ، منسوب إلى جيلان"},
    "jina": {"en": "Jina; a female given name", "ur": "جینا (زنانہ نام)", "fa": "جینا (نام زنانه)", "hi": "जीना (स्त्री नाम)", "ps": "جینا (ښځينه نوم)", "ar": "جِينَا (اسم علم مؤنث)"},
    "gardens_jinan": {"en": "Gardens, paradises", "ur": "جنان، باغات، بہشت", "fa": "جنان، باغها، بهشت", "hi": "जिनान, बाग़, बहिश्त", "ps": "جنان، باغونه، جنت", "ar": "الجنان، البساتين، جمع جنّة"},
    "jirah": {"en": "Jirah; a given name", "ur": "جیرہ (نام)", "fa": "جیره (نام)", "hi": "जीरा (नाम)", "ps": "جیره (نوم)", "ar": "جِيرَة (اسم علم)"},
    "jiyan": {"en": "Jiyan; life (Kurdish)", "ur": "جیان، زندگی (کردی)", "fa": "ژیان، زندگی (کردی)", "hi": "जियान, जीवन (कुर्दी)", "ps": "ژیان، ژوند (کردي)", "ar": "ژیان، الحياة (كردية)"},
    "johi": {"en": "Johi; a given name", "ur": "جوہی (نام)", "fa": "جوهی (نام)", "hi": "जोही (नाम)", "ps": "جوهي (نوم)", "ar": "جُوهِي (اسم علم)"},
    "yunus": {"en": "Yunus; the Qur'anic form of Jonah", "ur": "یونس، قرآن میں یونس", "fa": "یونس، صورت قرآنی یونس", "hi": "यूनुस, क़ुरआन में यूनुस", "ps": "یونس، په قرآن کې یونس", "ar": "يُونُس، النبي المذكور في القرآن"},
    "generosity": {"en": "Generosity, abundance, liberality", "ur": "جود، سخاوت، فیاضی", "fa": "جود، بخشش، سخاوت", "hi": "उदारता, दानशीलता, जूद", "ps": "جود، سخاوت، لاس پراختیا", "ar": "الجود، السخاء، الكرم"},
    "judi": {"en": "Judi; the mountain where the ark rested (Qur'anic)", "ur": "جودی، وہ پہاڑ جہاں کشتی ٹھہری", "fa": "جودی، کوهی که کشتی بر آن نشست", "hi": "जूदी, वह पहाड़ जहाँ नाव ठहरी", "ps": "جودي، هغه غر چې بېړۍ پرې ودرېده", "ar": "الجُودِيّ، الجبل الذي استوت عليه السفينة"},
    "josha": {"en": "Josha; a given name", "ur": "جوشا (نام)", "fa": "جوشا (نام)", "hi": "जोशा (नाम)", "ps": "جوشا (نوم)", "ar": "جُوشَا (اسم علم)"},
    "jubair": {"en": "Jubair; diminutive of Jabir", "ur": "جبیر، جابر کی تصغیر", "fa": "جبیر، تصغیر جابر", "hi": "जुबैर, जाबिर का लघु रूप", "ps": "جبیر، د جابر کوچنی بڼه", "ar": "جُبَيْر، تصغير جابر"},
    "juda": {"en": "Juda; a given name", "ur": "جودا (نام)", "fa": "جودا (نام)", "hi": "जूदा (नाम)", "ps": "جودا (نوم)", "ar": "جُودَا (اسم علم)"},
    "juday": {"en": "Juday; a given name", "ur": "جدے (نام)", "fa": "جدای (نام)", "hi": "जुदय (नाम)", "ps": "جدای (نوم)", "ar": "جُدَى (اسم علم)"},
    "jul": {"en": "Jul; a given name", "ur": "جل (نام)", "fa": "جل (نام)", "hi": "जुल (नाम)", "ps": "جل (نوم)", "ar": "جُل (اسم علم)"},
    "friday": {"en": "Friday; the day of congregation", "ur": "جمعہ، جمعے کا دن", "fa": "جمعه، روز آدینه", "hi": "जुमा, शुक्रवार", "ps": "جمعه، د جمعې ورځ", "ar": "الجمعة، يوم الجماعة"},
    "jumada": {"en": "Jumada; a month of the Islamic calendar", "ur": "جمادی، اسلامی مہینہ", "fa": "جمادی، ماه تقویم اسلامی", "hi": "जुमादा, इस्लामी महीना", "ps": "جمادی، اسلامي میاشت", "ar": "جمادى، شهر من التقويم الهجري"},
    "assembly": {"en": "Assembly, congregation, gathering", "ur": "جماعت، اجتماع، مجلس", "fa": "جماعت، گردهمایی، انجمن", "hi": "जमात, सभा, समूह", "ps": "جماعت، ټولنه، غونډه", "ar": "الجماعة، الاجتماع، المجلس"},
    "juman": {"en": "Juman; pearls", "ur": "جمان، موتی", "fa": "جمان، مروارید", "hi": "जुमान, मोती", "ps": "جمان، مرغلرې", "ar": "الجمان، اللؤلؤ"},
    "jumman": {"en": "Jumman; pearls", "ur": "جمان، موتی", "fa": "جمان، مروارید", "hi": "जुम्मान, मोती", "ps": "جمان، مرغلرې", "ar": "الجُمَّان، اللؤلؤ"},
    "junayd": {"en": "Junayd; a male given name", "ur": "جنید (مردانہ نام)", "fa": "جنید (نام مردانه)", "hi": "जुनैद (पुरुष नाम)", "ps": "جنید (نر نوم)", "ar": "جُنَيْد (اسم علم مذكر)"},
    "junaida": {"en": "Junaida; feminine of Junayd", "ur": "جنیدہ، جنید کی مؤنث", "fa": "جنیده، مؤنث جنید", "hi": "जुनैदा, जुनैद की स्त्री", "ps": "جنیده، د جنید ښځينه", "ar": "جُنَيْدَة، مؤنث جنيد"},
    "junaina": {"en": "Junaina; diminutive of Janna", "ur": "جنینہ، جنت کی تصغیر", "fa": "جنینه، تصغیر جنت", "hi": "जुनैना, जन्नत का लघु रूप", "ps": "جنینه، د جنت کوچنی بڼه", "ar": "جُنَيْنَة، تصغير جنّة"},
    "juni": {"en": "Juni; a female given name", "ur": "جونی (زنانہ نام)", "fa": "جونی (نام زنانه)", "hi": "जूनी (स्त्री नाम)", "ps": "جوني (ښځينه نوم)", "ar": "جُونِي (اسم علم مؤنث)"},
    "junna": {"en": "Junna; garden, paradise", "ur": "جنہ، باغ، جنت", "fa": "جنه، باغ، جنت", "hi": "जुन्ना, बाग़, जन्नत", "ps": "جنه، باغ، جنت", "ar": "الجُنَّة، الجنّة، البستان"},
    "juwairiya": {"en": "Juwayriyya; a female given name", "ur": "جویریہ (زنانہ نام)", "fa": "جویریه (نام زنانه)", "hi": "जुवैरिया (स्त्री नाम)", "ps": "جویریه (ښځينه نوم)", "ar": "جُوَيْرِيَّة (اسم علم مؤنث)"},
    "juwan": {"en": "Juwan; a male given name", "ur": "جووان (مردانہ نام)", "fa": "جووان (نام مردانه)", "hi": "जुवान (पुरुष नाम)", "ps": "جووان (نر نوم)", "ar": "جُوَان (اسم علم مذكر)"},
    "juyal": {"en": "Juyal; a given name", "ur": "جویال (نام)", "fa": "جویال (نام)", "hi": "जुयाल (नाम)", "ps": "جویال (نوم)", "ar": "جُويَال (اسم علم)"},
    "butcher": {"en": "Butcher (Persian)", "ur": "جزار، قصائی", "fa": "جزار، قصاب", "hi": "क़साई, जज़्ज़ार", "ps": "قصاب، جزار", "ar": "الجزار، القصاب (فارسي)"},
    "kaab": {"en": "Ka'b; a male given name", "ur": "کعب (مردانہ نام)", "fa": "کعب (نام مردانه)", "hi": "काब (पुरुष नाम)", "ps": "کعب (نر نوم)", "ar": "كَعْب (اسم علم مذكر)"},
    "perfect": {"en": "Perfect, complete, whole", "ur": "کامل، مکمل، پورا", "fa": "کامل، تمام، بینقص", "hi": "पूर्ण, कामिल, संपूर्ण", "ps": "کامل، بشپړ، پوره", "ar": "الكامل، التام، التمام"},
    "great_big": {"en": "Great, big, large", "ur": "کبیر، بڑا، عظیم", "fa": "کبیر، بزرگ، عظیم", "hi": "बड़ा, कबीर, महान", "ps": "لوی، کبیر، عظیم", "ar": "الكبير، العظيم، الجسيم"},
    "great_f": {"en": "Great, large (feminine)", "ur": "کبیرہ، بڑی", "fa": "کبیره، بزرگ (مؤنث)", "hi": "कबीरा, बड़ी", "ps": "کبیره، لویه", "ar": "الكبيرة، العظيمة"},
    "destiny": {"en": "Destiny, decree, measure", "ur": "قدر، تقدیر، نصیب", "fa": "قدر، تقدیر، سرنوشت", "hi": "क़दर, भाग्य, तक़दीर", "ps": "قدر، برخه، تقدیر", "ar": "القدر، القضاء، المقدار"},
    "qaddur": {"en": "Qaddur; a male given name", "ur": "قدور (مردانہ نام)", "fa": "قدور (نام مردانه)", "hi": "क़द्दूर (पुरुष नाम)", "ps": "قدور (نر نوم)", "ar": "قَدُّور (اسم علم مذكر)"},
    "qadim": {"en": "Qadim; ancient, eternal", "ur": "قدیم، پرانا، ازلی", "fa": "قدیم، کهن، ازلی", "hi": "क़दीम, प्राचीन, पुराना", "ps": "قدیم، زوړ، ازلي", "ar": "القديم، العتيق، الأزلي"},
    "kadeen": {"en": "Kadeen; a female given name", "ur": "کادین (زنانہ نام)", "fa": "کادین (نام زنانه)", "hi": "कादीन (स्त्री नाम)", "ps": "کادین (ښځينه نوم)", "ar": "كَادِين (اسم علم مؤنث)"},
    "qadir": {"en": "Qadir; capable, able, powerful", "ur": "قادر، توانا، قوی", "fa": "قادر، توانا، توانمند", "hi": "क़ादिर, सक्षम, शक्तिशाली", "ps": "قادر، توانا، پیاوړی", "ar": "القادر، القوي، المقتدر"},
    "kadin": {"en": "Kadin; a given name", "ur": "کادین (نام)", "fa": "کادین (نام)", "hi": "कादिन (नाम)", "ps": "کادین (نوم)", "ar": "كَادِين (اسم علم)"},
    "jawara": {"en": "Jawara; a male given name", "ur": "جوارہ (مردانہ نام)", "fa": "جواره (نام مردانه)", "hi": "जवारा (पुरुष नाम)", "ps": "جواره (نر نوم)", "ar": "جَوَارَة (اسم علم مذكر)"},
    "jazi": {"en": "Jazi; a male given name", "ur": "جازی (مردانہ نام)", "fa": "جازی (نام مردانه)", "hi": "जाज़ी (पुरुष नाम)", "ps": "جازي (نر نوم)", "ar": "جَازِي (اسم علم مذكر)"},
    "jouri": {"en": "Jouri; a female given name", "ur": "جوری (زنانہ نام)", "fa": "جوری (نام زنانه)", "hi": "जूरी (स्त्री नाम)", "ps": "جوري (ښځينه نوم)", "ar": "جُورِي (اسم علم مؤنث)"},
    "jun": {"en": "Jun; a given name", "ur": "جن (نام)", "fa": "جن (نام)", "hi": "जुन (नाम)", "ps": "جن (نوم)", "ar": "جُن (اسم علم)"},
})

CUR = {
 "jawahar": ("جواهر", "جواہر", "جواهر", "जवाहर", "جواهر", "jewels", "Arabic", "Male",
             "Plural of جَوْهَر; جَوَاهِر (Jawāhir)", False, "high",
             "Jawahar is Arabic جَوَاهِر (Jawāhir) 'jewels, gems, precious stones', the plural of جَوْهَر (jawhar). The source gloss 'precious gem' is broadly consistent. Same name as jawaher, jawahir, jawhar and johar."),
 "jawaher": ("جواهر", "جواہر", "جواهر", "जवाहेर", "جواهر", "jewels", "Arabic", "Female",
             "Plural of جَوْهَر; جَوَاهِر (Jawāhir)", False, "high",
             "Jawaher is Arabic جَوَاهِر (Jawāhir) 'jewels, gems, precious stones', the plural of جَوْهَر (jawhar). CRITICAL SOURCE ERROR: the source gave جوهير (a different form); the correct form is جَوَاهِر. The source gloss 'Jewels' is consistent. Same name as jawahar, jawahir, jawhar and johar."),
 "jawahir": ("جواهر", "جواہر", "جواهر", "जवाहिर", "جواهر", "jewels", "Arabic", "Female",
             "Plural of جَوْهَر; جَوَاهِر (Jawāhir)", False, "high",
             "Jawahir is Arabic جَوَاهِر (Jawāhir) 'jewels, gems, precious stones', the plural of جَوْهَر (jawhar). The source gloss 'Pearls' is unsupported and has been replaced with the lexical sense. Same name as jawahar, jawaher, jawhar and johar."),
 "jawaid": ("جاوید", "جاوید", "جاوید", "जावेद", "جاوید", "eternal", "Persian", "Male",
            "Persian جاوید (jāvīd)", False, "high",
            "Jawaid is Persian جاوید (jāvīd) 'eternal, everlasting'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Generous, Benefactor' is unsupported and has been replaced with the Persian lexical sense. Same name as jawid and javeed."),
 "jawan": ("جوان", "جوان", "جوان", "जवान", "جوان", "young", "Persian", "Male",
           "Persian جوان (javān)", False, "medium",
           "Jawan is Persian جوان (javān) 'young, youthful'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Young' is consistent. Same name as javan."),
 "jawara": ("جوارة", "جوارہ", "جواره", "जवारा", "جواره", "jawara", "Arabic", "Male",
            "Arabic جَوَارَة (Jawāra)", False, "low",
            "Jawara is recorded at low confidence. The source gave جوارة and glossed the name 'Gentle, Kind'; جَوَارَة (Jawāra) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jawdat": ("جودة", "جودت", "جودت", "जौदत", "جودت", "excellence_jawdat", "Arabic", "Male",
            "Arabic root ج و د (j-w-d); جَوْدَة (Jawda)", False, "medium",
            "Jawdat is Arabic جَوْدَة (Jawda) 'excellence, quality, merit', from the root ج و د (j-w-d); the form جَوْدَت is the Turkish/Persian rendering. CRITICAL SOURCE ERROR: the source gave the broken form جَوْدَةٌ and glossed the name 'Generous'; the correct form is جَوْدَة."),
 "jawhar": ("جوهر", "جوہر", "جوهر", "जौहर", "جوهر", "jewel", "Arabic", "Male",
            "Arabic root ج و ه ر (j-w-h-r); جَوْهَر (Jawhar)", False, "high",
            "Jawhar is Arabic جَوْهَر (Jawhar) 'jewel, gem, precious stone', from the root ج و ه ر (j-w-h-r). The source gloss 'Jewel, Gemstone' is consistent. Same name as jawahar, jawaher, jawahir and johar."),
 "jawhara": ("جوهرة", "جوہرہ", "گوهره", "जौहरा", "جوهره", "jewel_f", "Arabic", "Female",
             "Arabic root ج و ه ر (j-w-h-r); جَوْهَرَة (Jawhara)", False, "high",
             "Jawhara is Arabic جَوْهَرَة (Jawhara) 'jewel, gem' (feminine), from the root ج و ه ر (j-w-h-r). The source gloss 'Jewel' is consistent. Same name as jawharat and johara."),
 "jawharat": ("جوهرة", "جوہرت", "گوهرت", "जौहरत", "جوهرت", "jewel_f", "Arabic", "Female",
              "Arabic root ج و ه ر (j-w-h-r); جَوْهَرَة (Jawhara)", False, "high",
              "Jawharat is Arabic جَوْهَرَة (Jawhara) 'jewel, gem' (feminine), from the root ج و ه ر (j-w-h-r); the form جَوْهَرَت is the Persian/Urdu rendering. The source gloss 'Precious gem or jewel' is consistent. Same name as jawhara and johara."),
 "jawhari": ("جوهري", "جوہری", "جوهری", "जौहरी", "جوهري", "jawhari", "Arabic", "Male",
             "Nisba of جَوْهَر; جَوْهَرِيّ (Jawhariyy)", False, "medium",
             "Jawhari is Arabic جَوْهَرِيّ (Jawhariyy), the nisba of جَوْهَر (Jawhar), meaning 'of the jewel; jeweller'. The source gloss 'Pearl' is unsupported and has been replaced with the lexical sense."),
 "jawid": ("جاوید", "جاوید", "جاوید", "जाविद", "جاوید", "eternal", "Persian", "Male",
           "Persian جاوید (jāvīd)", False, "high",
           "Jawid is Persian جاوید (jāvīd) 'eternal, everlasting'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Continuous, Everlasting' is broadly consistent. Same name as jawaid and javeed."),
 "jawwad": ("جواد", "جواد", "جواد", "जव्वाद", "جواد", "generous_jawad", "Arabic", "Male",
            "Arabic root ج و د (j-w-d); جَوَاد (Jawād)", False, "high",
            "Jawwad is Arabic جَوَاد (Jawād) 'generous, noble, open-handed', from the root ج و د (j-w-d). The source gloss 'Generous' is consistent. Same name as jawad and jawaad."),
 "jaya": ("جيا", "جیا", "جایا", "जया", "جایا", "jaya", "Sanskrit", "Female",
          "Sanskrit जय (jaya)", False, "medium",
          "Jaya is Sanskrit जय (jaya) 'victory'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Victory, Triumph' is consistent."),
 "jayed": ("جيد", "جید", "جید", "जय्यद", "جید", "good_excellent", "Arabic", "Male",
           "Arabic root ج ي د (j-y-d); جَيِّد (Jayyid)", False, "medium",
           "Jayed is Arabic جَيِّد (Jayyid) 'good, excellent, fine', from the root ج ي د (j-y-d). The source gloss 'Prosperous, Rich' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily an adjective."),
 "jazeera": ("جزيرة", "جزیرہ", "جزیره", "जज़ीरा", "جزیره", "island", "Arabic", "Female",
             "Arabic root ج ز ر (j-z-r); جَزِيرَة (Jazīra)", False, "high",
             "Jazeera is Arabic جَزِيرَة (Jazīra) 'island, peninsula', from the root ج ز ر (j-z-r). The source gloss 'Island' is consistent."),
 "jazi": ("جازي", "جازی", "جازی", "जाज़ी", "جازي", "jazi", "Arabic", "Male",
          "Arabic جَازِي (Jāzī)", False, "low",
          "Jazi is recorded at low confidence. The source gave the mixed-script junk form جazi and glossed the name 'Gift'; جَازِي (Jāzī) is a documented male given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "jazib": ("جاذب", "جاذب", "جاذب", "जाज़िब", "جاذب", "attractive", "Arabic", "Male",
           "Arabic root ج ذ ب (j-dh-b); جَاذِب (Jādhib)", False, "medium",
           "Jazib is Arabic جَاذِب (Jādhib) 'attractive, alluring, charming', from the root ج ذ ب (j-dh-b). CRITICAL SOURCE ERROR: the source gave the junk form جازيب (with a Cyrillic character) and glossed the name \"A name that means 'dark' or 'night'\"; the correct form is جَاذِب."),
 "jazlaan": ("جزلان", "جزلان", "جزلان", "जज़लान", "جزلان", "jazlaan", "Arabic", "Male",
             "Arabic جَزْلَان (Jazlān)", False, "low",
             "Jazlaan is recorded at low confidence. The source gave جزلان and glossed the name 'Glowing Gem'; جَزْلَان (Jazlān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jazmin": ("ياسمين", "یاسمین", "یاسمین", "जास्मिन", "یاسمین", "jasmine", "Arabic", "Female",
            "Arabic يَاسْمِين (Yāsmīn)", False, "high",
            "Jazmin is a variant transliteration of Arabic يَاسْمِين (Yāsmīn) 'jasmine; the jasmine flower'. The source gloss 'Giver of Jasmine' is unsupported and has been replaced with the lexical sense. Same name as jasmina."),
 "jeelan": ("جيلان", "گیلان", "گیلان", "गीलान", "گیلان", "gilan", "Persian", "Female",
            "Persian گیلان (Gīlān)", False, "medium",
            "Jeelan is Persian گیلان (Gīlān), a region of Iran, used as a given name. CRITICAL SOURCE ERROR: the source gave جیلان, using Persian letters in the Arabic column. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Gentle, Delicate, Beautiful' is unsupported and has been replaced with the documented identification. Same name as jilan."),
 "jeevan": ("جیون", "جیون", "جیوان", "जीवन", "جیوان", "life_sanskrit", "Sanskrit", "Male",
            "Sanskrit जीवन (jīvana)", False, "medium",
            "Jeevan is Sanskrit जीवन (jīvana) 'life, living, soul'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Life, Soul, Living' is consistent. Same name as jivan."),
 "jehad": ("جهاد", "جہاد", "جهاد", "जिहाद", "جهاد", "struggle", "Arabic", "Male",
           "Arabic root ج ه د (j-h-d); جِهَاد (Jihād)", False, "high",
           "Jehad is Arabic جِهَاد (Jihād) 'struggle, striving, effort', from the root ج ه د (j-h-d). The source gloss 'Struggle in the way of Allah' is broadly consistent. Same name as jihaad and jihad."),
 "jehan": ("جهان", "جہان", "جهان", "जहान", "جهان", "world_jehan", "Persian", "Female",
           "Persian جهان (jahān)", False, "high",
           "Jehan is Persian جهان (jahān) 'world, universe'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss \"God's gift\" is unsupported and has been replaced with the Persian lexical sense. Same name as jihan and jahan."),
 "jehanzeb": ("جهانزیب", "جہانزیب", "جهانزیب", "जहाँज़ेब", "جهانزیب", "world_beauty", "Persian", "Male",
              "Persian جهانزیب (jahānzīb)", False, "medium",
              "Jehanzeb is Persian جهانزیب (jahānzīb) 'beauty of the world'. CRITICAL SOURCE ERROR: the source gave the broken form جهـانزێب (with a Kurdish letter); the correct form is جهانزیب. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Beauty of the World' is consistent. Same name as jahanzeb."),
 "jemina": ("جمينة", "جمینہ", "جمینه", "जेमिना", "جمینه", "jemina", "Arabic", "Female",
            "Arabic جَمِينَة (Jamīna)", False, "low",
            "Jemina is recorded at low confidence. The source gave جمينة and glossed the name 'Gentle, beautiful'; جَمِينَة (Jamīna) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jena": ("جنة", "جنت", "جنت", "जेना", "جنة", "garden_paradise", "Arabic", "Female",
          "Arabic root ج ن ن (j-n-n); جَنَّة (Janna)", False, "medium",
          "Jena is Arabic جَنَّة (Janna) 'garden, paradise', from the root ج ن ن (j-n-n). CRITICAL SOURCE ERROR: the source gave عائشة (a different name entirely) and glossed the name 'Daughter of Janah or beautiful'; the correct form is جَنَّة."),
 "jennah": ("جنة", "جنت", "جنت", "जेन्नाह", "جنة", "garden_paradise", "Arabic", "Female",
            "Arabic root ج ن ن (j-n-n); جَنَّة (Janna)", False, "high",
            "Jennah is Arabic جَنَّة (Janna) 'garden, paradise', from the root ج ن ن (j-n-n). The source gloss 'Garden' is consistent. Same name as janna, jannah and jannat."),
 "jeroen": ("يرون", "جیرون", "یرون", "जेरून", "یرون", "jeroen", "Dutch", "Male",
           "Dutch Jeroen", False, "low",
           "Jeroen is recorded at low confidence. The source gave جرون and glossed the name 'Light, bright, shining'; Jeroen is a Dutch male given name, but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "jian": ("جيان", "جیان", "جیان", "जियान", "جیان", "jian", "Chinese", "Male",
          "Chinese 简/健 (jiǎn/jiàn)", False, "low",
          "Jian is recorded at low confidence. The source gave جن and glossed the name 'Surname: Simple, plain'; Jian is a Chinese given name, but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "jibal": ("جبال", "جبال", "جبال", "जिबाल", "جبال", "mountains", "Arabic", "Male",
           "Plural of جَبَل; جِبَال (Jibāl)", False, "medium",
           "Jibal is Arabic جِبَال (Jibāl) 'mountains, mounts', the plural of جَبَل (jabal). The source gloss 'Mountain, Elevated' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "jibrail": ("جبريل", "جبریل", "جبریل", "जिब्राईल", "جبریل", "gabriel", "Arabic", "Male",
             "Qur'anic proper name; جِبْرِيل (Jibrīl)", True, "high",
             "Jibrail is Arabic جِبْرِيل (Jibrīl), the angel Gabriel, mentioned in the Qur'an. The source gloss 'Gentle, Compassionate, Noble' is unsupported; the name is a proper name. Same name as jibreel, jibriil and jibril."),
 "jibran": ("جبران", "جبران", "جبران", "जिब्रान", "جبران", "jibran", "Arabic", "Male",
            "Arabic جِبْرَان (Jibrān)", False, "medium",
            "Jibran is Arabic جِبْرَان (Jibrān), a documented male given name. CRITICAL SOURCE ERROR: the source gave the junk string 'عربي_Jibran' in the Arabic column and glossed the name 'Noble and blessed'; the correct form is جِبْرَان. Same name as jubran."),
 "jibreel": ("جبريل", "جبریل", "جبریل", "जिब्रील", "جبریل", "gabriel", "Arabic", "Male",
             "Qur'anic proper name; جِبْرِيل (Jibrīl)", True, "high",
             "Jibreel is Arabic جِبْرِيل (Jibrīl), the angel Gabriel, mentioned in the Qur'an. The source record was an 8-key stub with no data. Same name as jibrail, jibriil and jibril."),
 "jibriil": ("جبريل", "جبریل", "جبریل", "जिब्रील", "جبریل", "gabriel", "Arabic", "Male",
             "Qur'anic proper name; جِبْرِيل (Jibrīl)", True, "high",
             "Jibriil is Arabic جِبْرِيل (Jibrīl), the angel Gabriel, mentioned in the Qur'an. The source gloss 'The most generous one, the one who c...' is unsupported; the name is a proper name. Same name as jibrail, jibreel and jibril."),
 "jibril": ("جبريل", "جبریل", "جبریل", "जिब्रील", "جبریل", "gabriel", "Arabic", "Male",
            "Qur'anic proper name; جِبْرِيل (Jibrīl)", True, "high",
            "Jibril is Arabic جِبْرِيل (Jibrīl), the angel Gabriel, mentioned in the Qur'an. The source gloss 'Angel Gabriel' is consistent. Same name as jibrail, jibreel and jibriil."),
 "jidah": ("جدة", "جدہ", "جده", "जिदा", "جده", "jidah", "Arabic", "Female",
           "Arabic جِدَة (Jida)", False, "low",
           "Jidah is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'traveller, pilgrim'; جِدَة (Jida) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jigar": ("جگر", "جگر", "جگر", "जिगर", "جګر", "liver", "Persian", "Male",
           "Persian جگر (jigar)", False, "medium",
           "Jigar is Persian جگر (jigar) 'liver; (figuratively) heart, courage'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Heart, Soul' is broadly consistent with the figurative sense."),
 "jihaad": ("جهاد", "جہاد", "جهاد", "जिहाद", "جهاد", "struggle", "Arabic", "Male",
            "Arabic root ج ه د (j-h-d); جِهَاد (Jihād)", False, "high",
            "Jihaad is Arabic جِهَاد (Jihād) 'struggle, striving, effort', from the root ج ه د (j-h-d). The source gloss 'Struggle, Jihad' is consistent. Same name as jehad and jihad."),
 "jihad": ("جهاد", "جہاد", "جهاد", "जिहाद", "جهاد", "struggle", "Arabic", "Male",
           "Arabic root ج ه د (j-h-d); جِهَاد (Jihād)", False, "high",
           "Jihad is Arabic جِهَاد (Jihād) 'struggle, striving, effort', from the root ج ه د (j-h-d). The source gloss 'Struggle, striving, effort' is consistent. Same name as jehad and jihaad."),
 "jihan": ("جهان", "جہان", "جهان", "जिहान", "جهان", "world_jehan", "Persian", "Female",
           "Persian جهان (jahān)", False, "high",
           "Jihan is Persian جهان (jahān) 'world, universe'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Heavenly Paradise' is unsupported and has been replaced with the Persian lexical sense. Same name as jehan and jahan."),
 "jilan": ("جيلان", "گیلان", "گیلان", "जीलान", "گیلان", "gilan", "Persian", "Female",
           "Persian گیلان (Gīlān)", False, "medium",
           "Jilan is Persian گیلان (Gīlān), a region of Iran, used as a given name. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Gentle, Graceful, Beautiful Tree' is unsupported and has been replaced with the documented identification. Same name as jeelan."),
 "jilani": ("جيلاني", "گیلانی", "گیلانی", "जीलानी", "گیلاني", "jilani", "Persian", "Male",
            "Nisba of گیلان; جِيلَانِيّ (Jīlāniyy)", False, "medium",
            "Jilani is Arabic جِيلَانِيّ (Jīlāniyy), the nisba of گیلان (Gīlān), meaning 'of Gilan; belonging to Gilan'. The source gloss 'Gentle, gracious' is unsupported and has been replaced with the lexical sense."),
 "jina": ("جينا", "جینا", "جینا", "जीना", "جینا", "jina", "Arabic", "Female",
          "Arabic جِينَا (Jīnā)", False, "low",
          "Jina is recorded at low confidence. The source gave جينة and glossed the name 'Born of great virtue'; جِينَا (Jīnā) is a documented female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "jinan": ("جنان", "جنان", "جنان", "जिनान", "جنان", "gardens_jinan", "Arabic", "Female",
           "Arabic جِنَان (Jinān)", False, "medium",
           "Jinan is Arabic جِنَان (Jinān) 'gardens, paradises'. The source gloss 'Gentle flow of water' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun. Same name as janan."),
 "jirah": ("جيرة", "جیرہ", "جیره", "जीरा", "جیره", "jirah", "Arabic", "Male",
           "Arabic جِيرَة (Jīra)", False, "low",
           "Jirah is recorded at low confidence. The source gave جيرة and glossed the name 'Peaceful'; جِيرَة (Jīra) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jivan": ("جیون", "جیون", "جیوان", "जीवन", "جیوان", "life_sanskrit", "Sanskrit", "Male",
           "Sanskrit जीवन (jīvana)", False, "medium",
           "Jivan is Sanskrit जीवन (jīvana) 'life, living, soul'. MISLABELLED ORIGIN: the source recorded the name as Arabic and repeated the Latin string in the Arabic column. The source gloss 'Living, Eternal Life' is broadly consistent. Same name as jeevan."),
 "jiyan": ("ژیان", "جیان", "ژیان", "जियान", "ژیان", "jiyan", "Kurdish", "Male",
           "Kurdish ژیان (jiyan)", False, "medium",
           "Jiyan is Kurdish ژیان (jiyan) 'life'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Living' is consistent."),
 "johar": ("جوهر", "جوہر", "جوهر", "जोहर", "جوهر", "jewel", "Arabic", "Male",
           "Arabic root ج و ه ر (j-w-h-r); جَوْهَر (Jawhar)", False, "high",
           "Johar is Arabic جَوْهَر (Jawhar) 'jewel, gem, precious stone', from the root ج و ه ر (j-w-h-r). The source gloss 'Grain, seed' is unsupported and has been replaced with the lexical sense. Same name as jawahar, jawaher, jawahir and jawhar."),
 "johara": ("جوهرة", "جوہرہ", "گوهره", "जोहरा", "جوهره", "jewel_f", "Arabic", "Female",
            "Arabic root ج و ه ر (j-w-h-r); جَوْهَرَة (Jawhara)", False, "high",
            "Johara is Arabic جَوْهَرَة (Jawhara) 'jewel, gem' (feminine), from the root ج و ه ر (j-w-h-r). The source gloss 'Graceful, generous' is unsupported and has been replaced with the lexical sense. Same name as jawhara and jawharat."),
 "johi": ("جوهي", "جوہی", "جوهی", "जोही", "جوهي", "johi", "Arabic", "Male",
          "Arabic جُوهِي (Jūhī)", False, "low",
          "Johi is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Gift from God'; جُوهِي (Jūhī) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jonah": ("يونس", "یونس", "یونس", "यूनुस", "یونس", "yunus", "Arabic", "Male",
           "Qur'anic proper name; يُونُس (Yūnus)", True, "high",
           "Jonah is the English form of Arabic يُونُس (Yūnus), the Qur'anic prophet Jonah, mentioned in the Qur'an and the name of a Qur'anic sura. The source gloss 'Dove' is unsupported; the name is a proper name."),
 "jood": ("جود", "جود", "جود", "जूद", "جود", "generosity", "Arabic", "Male",
          "Arabic root ج و د (j-w-d); جُود (Jūd)", False, "medium",
          "Jood is Arabic جُود (Jūd) 'generosity, abundance, liberality', from the root ج و د (j-w-d). The source gloss 'Grapes' is unsupported and has been replaced with the lexical sense. Same name as joud and jud."),
 "joodi": ("جودي", "جودی", "جودی", "जूदी", "جودي", "judi", "Arabic", "Female",
           "Qur'anic place name; الجُودِيّ (al-Jūdiyy)", True, "medium",
           "Joodi is Arabic الجُودِيّ (al-Jūdiyy), the mountain where the ark rested, mentioned in the Qur'an. The source gloss 'Gentle, Beautiful' is unsupported and has been replaced with the documented identification."),
 "josha": ("جوشا", "جوشا", "جوشا", "जोशा", "جوشا", "josha", "Arabic", "Male",
           "Arabic جُوشَا (Jūshā)", False, "low",
           "Josha is recorded at low confidence. The source gave جوشا and glossed the name \"God's Gift\"; جُوشَا (Jūshā) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "joud": ("جود", "جود", "جود", "जूद", "جود", "generosity", "Arabic", "Female",
          "Arabic root ج و د (j-w-d); جُود (Jūd)", False, "medium",
          "Joud is Arabic جُود (Jūd) 'generosity, abundance, liberality', from the root ج و د (j-w-d). The source gloss 'Generosity, abundance' is consistent. Same name as jood and jud."),
 "jouri": ("جوري", "جوری", "جوری", "जूरी", "جوري", "jouri", "Arabic", "Female",
           "Arabic جُورِي (Jūrī)", False, "low",
           "Jouri is recorded at low confidence. The source record was an 8-key stub with no data; جُورِي (Jūrī) is a documented female given name, but no lexical meaning could be confirmed. No confident meaning is asserted."),
 "jubair": ("جبير", "جبیر", "جبیر", "जुबैर", "جبیر", "jubair", "Arabic", "Male",
            "Arabic جُبَيْر (Jubayr)", False, "high",
            "Jubair is Arabic جُبَيْر (Jubayr), the diminutive of جَابِر (Jābir), a well-documented male given name. The source gloss 'Gatherer, Owner' is unsupported; the name is a proper name. Same name as jabeer."),
 "jubran": ("جبران", "جبران", "جبران", "जुब्रान", "جبران", "jibran", "Arabic", "Male",
            "Arabic جِبْرَان (Jibrān)", False, "medium",
            "Jubran is Arabic جِبْرَان (Jibrān), a documented male given name. The source gloss 'Good, Virtuous' is unsupported and has been replaced with the proper-name identification. Same name as jibran."),
 "jud": ("جود", "جود", "جود", "जूद", "جود", "generosity", "Arabic", "Male",
         "Arabic root ج و د (j-w-d); جُود (Jūd)", False, "medium",
         "Jud is Arabic جُود (Jūd) 'generosity, abundance, liberality', from the root ج و د (j-w-d). The source gloss 'Given' is unsupported and has been replaced with the lexical sense. Same name as jood and joud."),
 "juda": ("جودا", "جودا", "جودا", "जूदा", "جودا", "juda", "Arabic", "Male",
          "Arabic جُودَا (Jūdā)", False, "low",
          "Juda is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Praise, Hymn, Giving thanks'; جُودَا (Jūdā) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "juday": ("جدى", "جدے", "جدای", "जुदय", "جدى", "juday", "Arabic", "Female",
           "Arabic جُدَى (Judā)", False, "low",
           "Juday is recorded at low confidence. The source gave جدى and glossed the name 'Unknown'; جُدَى (Judā) is a documented given name, but no lexical meaning could be confirmed. No confident meaning is asserted."),
 "jul": ("جل", "جل", "جل", "जुल", "جل", "jul", "Arabic", "Male",
         "Arabic جُل (Jul)", False, "low",
         "Jul is recorded at low confidence. The source gave جل and glossed the name 'Short, little, young'; جُل (Jul) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jumaa": ("جمعة", "جمعہ", "جمعه", "जुमा", "جمعه", "friday", "Arabic", "Male",
           "Arabic root ج م ع (j-m-ʿ); جُمُعَة (Jumuʿa)", False, "high",
           "Jumaa is Arabic جُمُعَة (Jumuʿa) 'Friday; the day of congregation', from the root ج م ع (j-m-ʿ). The source gloss 'Friday, Congregation' is consistent. Same name as jumah and jumaat."),
 "jumaat": ("جمعة", "جمعت", "جمعه", "जुमात", "جمعه", "friday", "Arabic", "Male",
            "Arabic root ج م ع (j-m-ʿ); جُمُعَة (Jumuʿa)", False, "medium",
            "Jumaat is Arabic جُمُعَة (Jumuʿa) 'Friday; the day of congregation', from the root ج م ع (j-m-ʿ); the form جُمُعَت is the Persian/Urdu rendering. The source gloss 'Gathering, Friday' is broadly consistent. Same name as jumaa and jumah."),
 "jumadi": ("جمادى", "جمادی", "جمادی", "जुमादा", "جمادی", "jumada", "Arabic", "Male",
            "Arabic جُمَادَى (Jumādā)", False, "medium",
            "Jumadi is Arabic جُمَادَى (Jumādā), a month of the Islamic calendar. The source gloss 'Follower of the moon' is unsupported and has been replaced with the documented identification."),
 "jumah": ("جمعة", "جمعہ", "جمعه", "जुमा", "جمعه", "friday", "Arabic", "Male",
           "Arabic root ج م ع (j-m-ʿ); جُمُعَة (Jumuʿa)", False, "high",
           "Jumah is Arabic جُمُعَة (Jumuʿa) 'Friday; the day of congregation', from the root ج م ع (j-m-ʿ). The source gloss 'Assembly or Congregation' is broadly consistent. Same name as jumaa and jumaat."),
 "juman": ("جمان", "جمان", "جمان", "जुमान", "جمان", "juman", "Arabic", "Female",
           "Arabic جُمَان (Jumān)", False, "medium",
           "Juman is Arabic جُمَان (Jumān) 'pearls'. The source gloss 'Gentle, Gracious' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun. Same name as jumman."),
 "jumana": ("جمانة", "جمانہ", "جمانه", "जुमाना", "جمانه", "juman", "Arabic", "Female",
            "Arabic جُمَانَة (Jumāna)", False, "low",
            "Jumana is recorded at low confidence. The source record was an 8-key stub with no data; جُمَانَة (Jumāna) is a documented female given name, but no lexical meaning could be confirmed. No confident meaning is asserted. Same name as jumanah."),
 "jumanah": ("جمانة", "جمانہ", "جمانه", "जुमाना", "جمانه", "juman", "Arabic", "Female",
             "Arabic جُمَانَة (Jumāna)", False, "low",
             "Jumanah is recorded at low confidence. The source record was an 8-key stub with no data; جُمَانَة (Jumāna) is a documented female given name, but no lexical meaning could be confirmed. No confident meaning is asserted. Same name as jumana."),
 "jumman": ("جمان", "جمان", "جمان", "जुम्मान", "جمان", "juman", "Arabic", "Male",
            "Arabic جُمَّان (Jummān)", False, "medium",
            "Jumman is Arabic جُمَّان (Jummān) 'pearls'. The source gloss 'Plentiful, Rich' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun. Same name as juman."),
 "jun": ("جن", "جن", "جن", "जुन", "جن", "jun", "Arabic", "Male",
         "Arabic جُن (Jun)", False, "low",
         "Jun is recorded at low confidence. The source record was an 8-key stub with no data; جُن (Jun) is a documented given name, but no lexical meaning could be confirmed. No confident meaning is asserted."),
 "junaid": ("جنيد", "جنید", "جنید", "जुनैद", "جنید", "junayd", "Arabic", "Male",
            "Arabic جُنَيْد (Junayd)", False, "high",
            "Junaid is Arabic جُنَيْد (Junayd), a well-documented male given name borne by Junayd al-Baghdadi, a Sufi scholar. The source record was an 8-key stub with no data. Same name as junayd."),
 "junaida": ("جنيدة", "جنیدہ", "جنیده", "जुनैदा", "جنیده", "junaida", "Arabic", "Female",
             "Arabic جُنَيْدَة (Junayda)", False, "medium",
             "Junaida is Arabic جُنَيْدَة (Junayda), the feminine of جُنَيْد (Junayd). The source gloss 'Given by God' is unsupported and has been replaced with the lexical sense. Same name as junaidah."),
 "junaidah": ("جنيدة", "جنیدہ", "جنیده", "जुनैदा", "جنیده", "junaida", "Arabic", "Female",
              "Arabic جُنَيْدَة (Junayda)", False, "medium",
              "Junaidah is Arabic جُنَيْدَة (Junayda), the feminine of جُنَيْد (Junayd). The source gloss 'Gracious' is unsupported and has been replaced with the lexical sense. Same name as junaida."),
 "junaina": ("جنينة", "جنینہ", "جنینه", "जुनैना", "جنینه", "junaina", "Arabic", "Female",
             "Arabic جُنَيْنَة (Junayna)", False, "medium",
             "Junaina is Arabic جُنَيْنَة (Junayna), the diminutive of جَنَّة (Janna) 'garden'. The source gloss 'Gracious, gentle woman' is unsupported and has been replaced with the lexical sense. Same name as junainah."),
 "junainah": ("جنينة", "جنینہ", "جنینه", "जुनैना", "جنینه", "junaina", "Arabic", "Female",
              "Arabic جُنَيْنَة (Junayna)", False, "medium",
              "Junainah is Arabic جُنَيْنَة (Junayna), the diminutive of جَنَّة (Janna) 'garden'. The source gloss 'Mature, adorned with grace' is unsupported and has been replaced with the lexical sense. Same name as junaina."),
 "junayd": ("جنيد", "جنید", "جنید", "जुनैद", "جنید", "junayd", "Arabic", "Male",
            "Arabic جُنَيْد (Junayd)", False, "high",
            "Junayd is Arabic جُنَيْد (Junayd), a well-documented male given name borne by Junayd al-Baghdadi, a Sufi scholar. The source gloss 'Religious devotee' is unsupported; the name is a proper name. Same name as junaid."),
 "juni": ("جوني", "جونی", "جونی", "जूनी", "جوني", "juni", "Arabic", "Female",
          "Arabic جُونِي (Jūnī)", False, "low",
          "Juni is recorded at low confidence. The source gave جوني and glossed the name 'Moonlight'; جُونِي (Jūnī) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "junna": ("جنة", "جنت", "جنت", "जुन्ना", "جنة", "junna", "Arabic", "Female",
           "Arabic root ج ن ن (j-n-n); جُنَّة (Junna)", False, "medium",
           "Junna is Arabic جُنَّة (Junna) 'garden, paradise', from the root ج ن ن (j-n-n). The source repeated the Latin string in the Arabic column and glossed the name 'Grace, Gentleness'; the lexical sense is 'garden, paradise'."),
 "juwairiya": ("جويرية", "جویریہ", "جویریه", "जुवैरिया", "جویریه", "juwairiya", "Arabic", "Female",
               "Arabic جُوَيْرِيَّة (Juwayriyya)", False, "high",
               "Juwairiya is Arabic جُوَيْرِيَّة (Juwayriyya), a well-documented female given name borne by Juwayriyya bint al-Harith, a wife of the Prophet Muhammad. The source gloss 'Companion in Paradise' is unsupported; the name is a proper name. Same name as juwayriyya and javeria."),
 "juwan": ("جوان", "جووان", "جووان", "जुवान", "جووان", "juwan", "Arabic", "Male",
           "Arabic جُوَان (Juwān)", False, "low",
           "Juwan is recorded at low confidence. The source gave جووان and glossed the name 'Yellow'; جُوَان (Juwān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "juyal": ("جويال", "جویال", "جویال", "जुयाल", "جویال", "juyal", "Arabic", "Male",
           "Arabic جُويَال (Jūyāl)", False, "low",
           "Juyal is recorded at low confidence. The source gave جوال and glossed the name 'Gentle and Joyful'; جُويَال (Jūyāl) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "juzar": ("جزار", "جزار", "جزار", "जुज़ार", "جزار", "butcher", "Persian", "Male",
           "Persian جزار (jazzār), from Arabic جَزَّار", False, "medium",
           "Juzar is Persian/Urdu جزار (jazzār) 'butcher', from Arabic جَزَّار. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Tiger' is unsupported and has been replaced with the lexical sense. Same name as juzer."),
 "juzer": ("جزار", "جزار", "جزار", "जुज़ेर", "جزار", "butcher", "Persian", "Male",
           "Persian جزار (jazzār), from Arabic جَزَّار", False, "medium",
           "Juzer is Persian/Urdu جزار (jazzār) 'butcher', from Arabic جَزَّار. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Abundance of Flowers' is unsupported and has been replaced with the lexical sense. Same name as juzar."),
 "jwan": ("جوان", "جوان", "جوان", "जवान", "جوان", "young", "Kurdish", "Male",
          "Kurdish جوان (jwan)", False, "low",
          "Jwan is recorded at low confidence. The source record was an 8-key stub with no data; جوان (jwan) 'young' is a Kurdish given name, but no lexical meaning could be confirmed from the source. No confident meaning is asserted."),
 "kaab": ("كعب", "کعب", "کعب", "काब", "کعب", "kaab", "Arabic", "Male",
          "Arabic كَعْب (Kaʿb)", False, "high",
          "Kaab is Arabic كَعْب (Kaʿb), a well-documented male given name borne by Ka'b ibn Malik, a companion of the Prophet Muhammad. The source gloss 'A grave, tomb, or burial place' is unsupported; the name is a proper name."),
 "ka-b": ("كعب", "کعب", "کعب", "काब", "کعب", "kaab", "Arabic", "Male",
          "Arabic كَعْب (Kaʿb)", False, "high",
          "Ka-b is Arabic كَعْب (Kaʿb), a well-documented male given name borne by Ka'b ibn Malik, a companion of the Prophet Muhammad. The source gloss 'Apostle of Allah' is unsupported; the name is a proper name. Same name as kaab."),
 "kaamil": ("كامل", "کامل", "کامل", "कामिल", "کامل", "perfect", "Arabic", "Male",
            "Arabic root ك م ل (k-m-l); كَامِل (Kāmil)", False, "high",
            "Kaamil is Arabic كَامِل (Kāmil) 'perfect, complete, whole', from the root ك م ل (k-m-l). The source gloss 'Perfect, Complete' is consistent. Same name as kamil."),
 "kabeer": ("كبير", "کبیر", "کبیر", "कबीर", "کبیر", "great_big", "Arabic", "Male",
            "Arabic root ك ب ر (k-b-r); كَبِير (Kabīr)", False, "high",
            "Kabeer is Arabic كَبِير (Kabīr) 'great, big, large', from the root ك ب ر (k-b-r). The source gloss 'Great, Big' is consistent. Same name as kabir."),
 "kabir": ("كبير", "کبیر", "کبیر", "कबीर", "کبیر", "great_big", "Arabic", "Male",
           "Arabic root ك ب ر (k-b-r); كَبِير (Kabīr)", False, "high",
           "Kabir is Arabic كَبِير (Kabīr) 'great, big, large', from the root ك ب ر (k-b-r). The source gloss 'Great, Grand' is consistent. Same name as kabeer."),
 "kabira": ("كبيرة", "کبیرہ", "کبیره", "कबीरा", "کبیره", "great_f", "Arabic", "Female",
            "Arabic root ك ب ر (k-b-r); كَبِيرَة (Kabīra)", False, "high",
            "Kabira is Arabic كَبِيرَة (Kabīra) 'great, large' (feminine), from the root ك ب ر (k-b-r). The source gloss 'Great, Large' is consistent."),
 "kadar": ("قدر", "قدر", "قدر", "क़दर", "قدر", "destiny", "Arabic", "Male",
           "Arabic root ق د ر (q-d-r); قَدَر (Qadar)", False, "medium",
           "Kadar is Arabic قَدَر (Qadar) 'destiny, decree, measure', from the root ق د ر (q-d-r). The source gloss 'Capacity, Ability, Power' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun. Same name as kader."),
 "kaddour": ("قدور", "قدور", "قدور", "क़द्दूर", "قدور", "qaddur", "Arabic", "Male",
             "Arabic قَدُّور (Qaddūr)", False, "medium",
             "Kaddour is Arabic قَدُّور (Qaddūr), a documented male given name. CRITICAL SOURCE ERROR: the source gave كادور (a different form) and glossed the name 'Servant of God'; the correct form is قَدُّور."),
 "kadeem": ("قديم", "قدیم", "قدیم", "क़दीम", "قدیم", "qadim", "Arabic", "Male",
            "Arabic root ق د م (q-d-m); قَدِيم (Qadīm)", False, "high",
            "Kadeem is Arabic قَدِيم (Qadīm) 'ancient, eternal', from the root ق د م (q-d-m). The source gloss 'Ancient, Everlasting' is consistent."),
 "kadeen": ("كادين", "کادین", "کادین", "कादीन", "کادین", "kadeen", "Arabic", "Female",
            "Arabic كَادِين (Kādīn)", False, "low",
            "Kadeen is recorded at low confidence. The source gave كادين and glossed the name 'Pure, Innocent, Beautiful'; كَادِين (Kādīn) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kadeer": ("قدير", "قدیر", "قدیر", "क़दीर", "قدیر", "qadir", "Arabic", "Male",
            "Arabic root ق د ر (q-d-r); قَدِير (Qadīr)", False, "high",
            "Kadeer is Arabic قَدِير (Qadīr) 'capable, able, powerful', from the root ق د ر (q-d-r); it is also one of the names of Allah (القدير). The source gloss 'Generous, Magnificent' is unsupported and has been replaced with the lexical sense. Same name as kadir, kader and kadar."),
 "kader": ("قادر", "قادر", "قادر", "क़ादिर", "قادر", "qadir", "Arabic", "Male",
           "Arabic root ق د ر (q-d-r); قَادِر (Qādir)", False, "high",
           "Kader is Arabic قَادِر (Qādir) 'capable, able, powerful', from the root ق د ر (q-d-r); it is also one of the names of Allah (القادر). CRITICAL SOURCE ERROR: the source gave كدر (a different word) and glossed the name 'Provider, Provider, Helper, Guardian'; the correct form is قَادِر. Same name as kadir, kadeer and kadar."),
 "kadin": ("كادين", "کادین", "کادین", "कादिन", "کادین", "kadin", "Arabic", "Male",
           "Arabic كَادِين (Kādīn)", False, "low",
           "Kadin is recorded at low confidence. The source gave كادين and glossed the name 'Servant, helper'; كَادِين (Kādīn) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "kadir": ("قادر", "قادر", "قادر", "क़ादिर", "قادر", "qadir", "Arabic", "Male",
           "Arabic root ق د ر (q-d-r); قَادِر (Qādir)", False, "high",
           "Kadir is Arabic قَادِر (Qādir) 'capable, able, powerful', from the root ق د ر (q-d-r); it is also one of the names of Allah (القادر). The source gloss 'Capable, Able' is consistent. Same name as kadeer, kader and kadar."),
}
