# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 53 (raza..rohana).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": razhan -> Latin "Razhan";
   reem -> empty; rehan -> empty; resha -> زينب; resham -> عائشة;
   rifa -> Latin "Rifa"; rifai -> "عربي_Rifai" (placeholder prefix);
   riha -> Latin "Riha"; rima -> empty; rimal -> ريمــال (tatweel padding);
   rimas -> empty; rimsha -> "عربي_Rimsha" (placeholder prefix);
   rizwan -> empty; rizwana -> "رazwana" (Latin mixed in);
   razaan -> رزأن; razak -> رزاق; razan -> رزان; razaq -> رازق;
   razeen -> رزین (Persian yeh); razi -> رضي; razia -> راضية;
   raziah -> راضيه; razik -> رازق; razin -> رازن; razina -> رازينا;
   raziq -> رزاق; raziya -> راضيه; razwan -> رزوان; razzak -> رزاق;
   razzaq -> رزاق; reda -> رضا; reeham -> رضيم; reema -> ريم;
   reet -> ريت; rehaam -> رحام; rehaan -> ريحان; rehab -> رِهاب;
   reham -> رحم; rehana -> رُهانَة; rehena -> عائشة; rehma -> رحمة;
   rehman -> الرحمن; rehmat -> رحمة; rehnuma -> رهنماء; reja -> رضا;
   rejab -> رجب; renana -> رنانة; resa -> ريسا; reyan -> ريان;
   reyhan -> ريحان; reyhana -> ريحانة; reza -> رضا; riad -> رياض;
   riaz -> رياض; rida -> رضا; ridda -> رضا; ridha -> رضا; ridhaa -> رضا;
   ridhwaan -> رضوان; ridhwan -> رضوان; ridwaan -> رضوان; ridwan -> رضوان;
   rifaa -> رفعة; rifaat -> رفات; rifah -> رفحة; rifal -> رفل;
   rifaqat -> رفاقت; rifat -> رفات; rifaya -> رفاء; riffat -> رفات;
   rifqah -> رفقة; rifqi -> رفقي; rihab -> ريحاب; riham -> ريحم;
   rihan -> ريهان; rihana -> ريحانة; rija -> ريجا; rim -> ريم;
   rina -> رينة; rinad -> رند; rishan -> ريش ان; riswana -> ريسوانة;
   riyaad -> رياض; riyad -> رياض; riyadh -> رياض; riyah -> رياح;
   riyasat -> رياسات; riyaz -> رياض; riyazul -> رياضول; riza -> رزا;
   rizq -> رزق; rizvan -> رضوان; rizvi -> رضوي; rizwaan -> رضوان;
   rochdi -> رَوْشِدِيّ; roha -> رُحة; rohaan -> روهان; rohail -> روهيل;
   rohana -> روحانا.
 * EMPTY STUBS (8-key records, no data): reem, rehan, rima, rimas, rizwan.
 * MISLABELLED ORIGIN: rehnuma (Urdu), resham (Persian/Urdu), reyhan (Turkish),
   rizvi (Persian/Urdu), rohana (Malay), razhan (Kurdish).
 * DEGARBLED GLOSSES: raza "Satisfaction Contentment", razaan "Jewel, Precious One",
   razak "Thankful, Grateful", razan "Rain, Small Raindrop", razaq "God's bounty, provision",
   razeen "Peaceful", razhan "Intelligent, Powerful", razi "Guided, enlightened",
   razia "Right-minded or just", raziah "Garden of God", razik "Wise, Intelligent",
   razin "Delight, Pleasure", razina "Pure, Chaste", raziq "Provider, Sustainer",
   raziya "Happiness, Joy", razwan "Moon Glow", razzak "The Provider",
   razzaq "The Provider", reda "Red, Ready", reeham "Stream", reema "Stream",
   reet "Gentleness, compassion", rehaam "Content, Satisfied, Contented",
   rehaan "Content, Satisfied", rehab "Path to Paradise",
   reham "Content, Pleasing, Satiated", rehana "Noble, Content",
   rehena "Contentment, Satisfaction", rehma "Mercy, Grace, Compassion",
   rehman "Benevolent, Merciful, Kind", rehmat "Mercy",
   rehnuma "Comfort, Love, Calmness", reja "Moon, bright, glowing",
   rejab "First month", renana "Joy, happiness, contentment",
   resa "Leader, Chief", resha "Fish", resham "Silk",
   reyan "Gates of Heaven, Blessed, Luxuriant", reyhan "Lady of the garden",
   reyhana "Tender, Delicate", reza "Helper", riad "garden",
   riaz "Frequent rain", rida "Pleasing, Acceptable, Joyful",
   ridda "Contentment, Satisfaction", ridha "Pleasing to God",
   ridhaa "Contentment, pleasure", ridhwaan "Contentment, Satisfaction, Favor",
   ridhwan "The One Who is Ever Content and Satisfied", ridwaan "Favor, Blessing, Satisfaction",
   ridwan "Welcomed with pleasure", rifa "Soft, gentle, pure",
   rifaa "Gentle, Kind", rifaat "Elevated, Exalted, or Lofty",
   rifah "Garden, Paradise", rifai "Noble and blessed", rifal "Gentle Wave",
   rifaqat "Companionship, Friendship", rifat "Traveler, Wanderer",
   rifaya "Gracious, Merciful", riffat "Soft, gentle, graceful",
   rifqah "Comfort, Consolation, Safety", rifqi "Comfort, Consolation, Peace",
   riha "Flowing, River", rihab "A refuge, a shelter", riham "Soft Rain",
   rihan "Path, Way", rihana "Lady, Mistress", rija "Little Stream",
   rim "A variant of the name Rahim, meaning 'compassionate'",
   rimal "Little Ripe Fruit", rimsha "Noble and blessed", rina "Joyful, content",
   rinad "Melodious", rishan "Joyful", riswana "Garden, bloom",
   riyaad "Gardener, Traveler", riyad "garden, meadow, paradise",
   riyadh "Gardens, meadows, or open country", riyah "Contentment, Satisfaction",
   riyasat "Government, Administration", riyaz "Gardener, Scholar, Learner",
   riyazul "Gardener of the Reality", riza "Contentment, Pleasure, Gladness",
   rizq "Provision, Sustenance", rizvan "God's Promise", rizvi "wise protector",
   rizwaan "Protector, Guardian, Supporter", rizwana "Blessed with kindness",
   rochdi "Gifted, Rich", roha "Contentment, happiness",
   rohaan "Content, Contented", rohail "Guide, One who leads with wisdom",
   rohana "Mountain".
 * GENDER ERRORS: raza, razeen, reda, rehmat, resa, rida, ridda, ridha, ridhaa,
   rifaqat, rim, rimal, riyadh, riyasat, riza, rizq were labelled unisex where
   documented usage is male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated52 import GLOSSES as _G52

GLOSSES = dict(_G52)
GLOSSES.update({
    "raza": {"en": "Raza; satisfaction, contentment", "ur": "رضا، رضامندی، قناعت", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "razaan": {"en": "Razaan; a female given name", "ur": "رزان (زنانہ نام)", "fa": "رزان (نام زنانه)", "hi": "रज़ान (स्त्री नाम)", "ps": "رزان (ښځينه نوم)", "ar": "رَزَان (اسْم عَلَم مُؤَنَّث)"},
    "razak": {"en": "Razak; provider, sustainer", "ur": "رزاق، رزق دینے والا", "fa": "رزاق، روزی‌دهنده", "hi": "रज़्ज़ाक़, रोज़ी देने वाला", "ps": "رزاق، روزي ورکوونکی", "ar": "الرَّزَّاق، الرَّازِق"},
    "razan": {"en": "Razan; a female given name", "ur": "رزان (زنانہ نام)", "fa": "رزان (نام زنانه)", "hi": "रज़ान (स्त्री नाम)", "ps": "رزان (ښځينه نوم)", "ar": "رَزَان (اسْم عَلَم مُؤَنَّث)"},
    "razaq": {"en": "Razaq; provider, sustainer", "ur": "رازق، رزق دینے والا", "fa": "رازق، روزی‌دهنده", "hi": "राज़िक़, रोज़ी देने वाला", "ps": "رازق، روزي ورکوونکی", "ar": "الرَّازِق، الرَّزَّاق"},
    "razeen": {"en": "Razeen; dignified, serious", "ur": "رزین، باوقار، سنجیدہ", "fa": "رزین، باوقار", "hi": "रज़ीन, गंभीर", "ps": "رزین، باوقار", "ar": "الرَّزِين، الْوَقُور"},
    "razhan": {"en": "Razhan; a male given name (Kurdish)", "ur": "رازھان (مردانہ نام)", "fa": "راژان (نام مردانه)", "hi": "राज़हान (पुरुष नाम)", "ps": "راژان (نر نوم)", "ar": "رَازْهَان (اسْم عَلَم كُرْدِيّ)"},
    "razi": {"en": "Razi; content, satisfied", "ur": "رضی، مطمئن", "fa": "رضی، خرسند", "hi": "रज़ी, संतुष्ट", "ps": "رضی، قناعت کوونکی", "ar": "الرَّضِي، الرَّاضِي"},
    "razia": {"en": "Razia; content, satisfied (feminine)", "ur": "راضیہ، مطمئن", "fa": "راضیه، خرسند", "hi": "राज़िया, संतुष्ट", "ps": "راضیه، قناعت کوونکې", "ar": "رَاضِيَة، الرَّاضِيَة"},
    "raziah": {"en": "Raziah; content, satisfied (feminine)", "ur": "راضیہ، مطمئن", "fa": "راضیه، خرسند", "hi": "राज़िया, संतुष्ट", "ps": "راضیه، قناعت کوونکې", "ar": "رَاضِيَة، الرَّاضِيَة"},
    "razik": {"en": "Razik; provider, sustainer", "ur": "رازق، رزق دینے والا", "fa": "رازق، روزی‌دهنده", "hi": "राज़िक़, रोज़ी देने वाला", "ps": "رازق، روزي ورکوونکی", "ar": "الرَّازِق، الرَّزَّاق"},
    "razin": {"en": "Razin; dignified, serious", "ur": "رازن، باوقار", "fa": "رازن، باوقار", "hi": "राज़िन, गंभीर", "ps": "رازن، باوقار", "ar": "الرَّازِن، الرَّزِين"},
    "razina": {"en": "Razina; a female given name", "ur": "رازینہ (زنانہ نام)", "fa": "رازینا (نام زنانه)", "hi": "राज़ीना (स्त्री नाम)", "ps": "رازینا (ښځينه نوم)", "ar": "رَازِينَا (اسْم عَلَم مُؤَنَّث)"},
    "raziq": {"en": "Raziq; provider, sustainer", "ur": "رازق، رزق دینے والا", "fa": "رازق، روزی‌دهنده", "hi": "राज़िक़, रोज़ी देने वाला", "ps": "رازق، روزي ورکوونکی", "ar": "الرَّازِق، الرَّزَّاق"},
    "raziya": {"en": "Raziya; content, satisfied (feminine)", "ur": "راضیہ، مطمئن", "fa": "راضیه، خرسند", "hi": "राज़िया, संतुष्ट", "ps": "راضیه، قناعت کوونکې", "ar": "رَاضِيَة، الرَّاضِيَة"},
    "razwan": {"en": "Razwan; a male given name", "ur": "رضوان (مردانہ نام)", "fa": "رضوان (نام مردانه)", "hi": "रज़वान (पुरुष नाम)", "ps": "رضوان (نر نوم)", "ar": "رِضْوَان (اسْم عَلَم مُذَكَّر)"},
    "razzak": {"en": "Razzak; the Provider", "ur": "رزاق، رزق دینے والا", "fa": "رزاق، روزی‌دهنده", "hi": "रज़्ज़ाक़, रोज़ी देने वाला", "ps": "رزاق، روزي ورکوونکی", "ar": "الرَّزَّاق، الرَّازِق"},
    "razzaq": {"en": "Razzaq; the Provider", "ur": "رزاق، رزق دینے والا", "fa": "رزاق، روزی‌دهنده", "hi": "रज़्ज़ाक़, रोज़ी देने वाला", "ps": "رزاق، روزي ورکوونکی", "ar": "الرَّزَّاق، الرَّازِق"},
    "reda": {"en": "Reda; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "reeham": {"en": "Reeham; a female given name", "ur": "ریم (زنانہ نام)", "fa": "ریم (نام زنانه)", "hi": "रीम (स्त्री नाम)", "ps": "ریم (ښځينه نوم)", "ar": "رِيم (اسْم عَلَم مُؤَنَّث)"},
    "reem": {"en": "Reem; a female given name", "ur": "ریم (زنانہ نام)", "fa": "ریم (نام زنانه)", "hi": "रीम (स्त्री नाम)", "ps": "ریم (ښځينه نوم)", "ar": "رِيم (اسْم عَلَم مُؤَنَّث)"},
    "reema": {"en": "Reema; a female given name", "ur": "ریما (زنانہ نام)", "fa": "ریما (نام زنانه)", "hi": "रीमा (स्त्री नाम)", "ps": "ریما (ښځينه نوم)", "ar": "رِيمَا (اسْم عَلَم مُؤَنَّث)"},
    "reet": {"en": "Reet; a female given name", "ur": "ریت (زنانہ نام)", "fa": "ریت (نام زنانه)", "hi": "रीत (स्त्री नाम)", "ps": "ریت (ښځينه نوم)", "ar": "رِيت (اسْم عَلَم مُؤَنَّث)"},
    "rehaam": {"en": "Rehaam; a male given name", "ur": "رحام (مردانہ نام)", "fa": "رحام (نام مردانه)", "hi": "रहाम (पुरुष नाम)", "ps": "رحام (نر نوم)", "ar": "رَحَام (اسْم عَلَم مُذَكَّر)"},
    "rehaan": {"en": "Rehaan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "rehab": {"en": "Rehab; a female given name", "ur": "رہاب (زنانہ نام)", "fa": "رهاب (نام زنانه)", "hi": "रिहाब (स्त्री नाम)", "ps": "رهاب (ښځينه نوم)", "ar": "رِهَاب (اسْم عَلَم مُؤَنَّث)"},
    "reham": {"en": "Reham; mercy, compassion", "ur": "رحم، رحمت", "fa": "رحم، رحمت", "hi": "रहम, दया", "ps": "رحم، رحمت", "ar": "الرَّحْم، الرَّحْمَة"},
    "rehan": {"en": "Rehan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "rehana": {"en": "Rehana; a female given name", "ur": "رہانہ (زنانہ نام)", "fa": "رهانه (نام زنانه)", "hi": "रिहाना (स्त्री नाम)", "ps": "رهانه (ښځينه نوم)", "ar": "رُهَانَة (اسْم عَلَم مُؤَنَّث)"},
    "rehena": {"en": "Rehena; a female given name", "ur": "رہینہ (زنانہ نام)", "fa": "رهینه (نام زنانه)", "hi": "रहीना (स्त्री नाम)", "ps": "رهینه (ښځينه نوم)", "ar": "رَهِينَة (اسْم عَلَم مُؤَنَّث)"},
    "rehma": {"en": "Rehma; mercy, compassion", "ur": "رحمہ، رحمت", "fa": "رحمه، رحمت", "hi": "रहमा, दया", "ps": "رحمه، رحمت", "ar": "الرَّحْمَة"},
    "rehman": {"en": "Rehman; the Most Merciful", "ur": "رحمان، بے حد مہربان", "fa": "رحمان، بخشنده", "hi": "रहमान, दयालु", "ps": "رحمان، مهربان", "ar": "الرَّحْمَان"},
    "rehmat": {"en": "Rehmat; mercy, compassion", "ur": "رحمت، مہربانی", "fa": "رحمت، بخشش", "hi": "रहमत, दया", "ps": "رحمت، مهرباني", "ar": "الرَّحْمَة"},
    "rehnuma": {"en": "Rehnuma; guide, leader (Urdu)", "ur": "رہنما، رہبر", "fa": "رهنما، رهبر", "hi": "रहनुमा, मार्गदर्शक", "ps": "رهنما، لارښود", "ar": "رَهْنُمَا (الْمُرْشِد)"},
    "reja": {"en": "Reja; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "rejab": {"en": "Rejab; the seventh Islamic month", "ur": "رجب، اسلامی مہینہ", "fa": "رجب، ماه اسلامی", "hi": "रजब, इस्लामी महीना", "ps": "رجب، اسلامي میاشت", "ar": "رَجَب (شَهْر هِجْرِيّ)"},
    "renana": {"en": "Renana; a female given name", "ur": "رنانہ (زنانہ نام)", "fa": "رنانه (نام زنانه)", "hi": "रनाना (स्त्री नाम)", "ps": "رنانه (ښځينه نوم)", "ar": "رَنَانَة (اسْم عَلَم مُؤَنَّث)"},
    "resa": {"en": "Resa; leader, chief", "ur": "ریسا، سردار", "fa": "ریسا، رهبر", "hi": "रेसा, नेता", "ps": "ریسا، مشر", "ar": "رِيسَا (الزَّعِيم)"},
    "resha": {"en": "Resha; a female given name", "ur": "ریشا (زنانہ نام)", "fa": "ریشا (نام زنانه)", "hi": "रीशा (स्त्री नाम)", "ps": "ریشا (ښځينه نوم)", "ar": "رِيشَا (اسْم عَلَم مُؤَنَّث)"},
    "resham": {"en": "Resham; silk (Persian/Urdu)", "ur": "ریشم، ریشم", "fa": "ابریشم، ریشم", "hi": "रेशम, रेशम", "ps": "ریشم، ورېښم", "ar": "رِيشَم (الْحَرِير)"},
    "reyan": {"en": "Reyan; sated, refreshed", "ur": "ریان، سیراب", "fa": "ریان، سیراب", "hi": "रैयान, तृप्त", "ps": "ریان، سیراب", "ar": "الرَّيَّان، الْمُرْتَوِي"},
    "reyhan": {"en": "Reyhan; fragrant herb, basil (Turkish)", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "reyhana": {"en": "Reyhana; fragrant herb, basil (feminine)", "ur": "ریحانہ، خوشبودار پودا", "fa": "ریحانه، سبزی خوشبو", "hi": "रैहाना, तुलसी", "ps": "ریحانه، خوږ بوټی", "ar": "رَيْحَانَة، الرَّيْحَان"},
    "reza": {"en": "Reza; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "riad": {"en": "Riad; gardens, meadows", "ur": "ریاض، باغات", "fa": "ریاض، باغ‌ها", "hi": "रियाज़, बाग़ात", "ps": "ریاض، باغونه", "ar": "الرِّيَاض، الْحَدَائِق"},
    "riaz": {"en": "Riaz; gardens, meadows", "ur": "ریاض، باغات", "fa": "ریاض، باغ‌ها", "hi": "रियाज़, बाग़ात", "ps": "ریاض، باغونه", "ar": "الرِّيَاض، الْحَدَائِق"},
    "rida": {"en": "Rida; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "ridaa": {"en": "Ridaa; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "ridha": {"en": "Ridha; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "ridhaa": {"en": "Ridhaa; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "ridhwaan": {"en": "Ridhwaan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "ridhwan": {"en": "Ridhwan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "ridwaan": {"en": "Ridwaan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "ridwan": {"en": "Ridwan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "rifa": {"en": "Rifa; a female given name", "ur": "رفا (زنانہ نام)", "fa": "رفا (نام زنانه)", "hi": "रिफ़ा (स्त्री नाम)", "ps": "رفا (ښځينه نوم)", "ar": "رِفَا (اسْم عَلَم مُؤَنَّث)"},
    "rifaa": {"en": "Rifaa; elevation, dignity", "ur": "رفعت، بلندی", "fa": "رفعت، بلندی", "hi": "रिफ़ा, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
    "rifaat": {"en": "Rifaat; elevation, dignity", "ur": "رفعت، بلندی", "fa": "رفعت، بلندی", "hi": "रिफ़ात, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
    "rifah": {"en": "Rifah; a female given name", "ur": "رفحہ (زنانہ نام)", "fa": "رفحه (نام زنانه)", "hi": "रिफ़ाह (स्त्री नाम)", "ps": "رفحه (ښځينه نوم)", "ar": "رِفْحَة (اسْم عَلَم مُؤَنَّث)"},
    "rifai": {"en": "Rifai; of the Rifa'i order (relational)", "ur": "رفاعی، رفاعی سلسلہ", "fa": "رفاعی، منسوب به رفاعی", "hi": "रिफ़ाई, रिफ़ाई सिलसिला", "ps": "رفاعي، د رفاعي اړوند", "ar": "الرِّفَاعِي، مَنْسُوب إِلَى الرِّفَاعِيَّة"},
    "rifal": {"en": "Rifal; a male given name", "ur": "رفل (مردانہ نام)", "fa": "رفل (نام مردانه)", "hi": "रिफ़ल (पुरुष नाम)", "ps": "رفل (نر نوم)", "ar": "رِفَل (اسْم عَلَم مُذَكَّر)"},
    "rifaqat": {"en": "Rifaqat; companionship, fellowship", "ur": "رفاقت، دوستی", "fa": "رفاقت، همراهی", "hi": "रिफ़ाक़त, साथ", "ps": "رفاقت، ملګرتیا", "ar": "الرِّفَاقَة، الصُّحْبَة"},
    "rifat": {"en": "Rifat; elevation, dignity", "ur": "رفعت، بلندی", "fa": "رفعت، بلندی", "hi": "रिफ़ात, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
    "rifaya": {"en": "Rifaya; a female given name", "ur": "رفاء (زنانہ نام)", "fa": "رفاء (نام زنانه)", "hi": "रिफ़ाया (स्त्री नाम)", "ps": "رفاء (ښځينه نوم)", "ar": "رِفَاءَة (اسْم عَلَم مُؤَنَّث)"},
    "riffat": {"en": "Riffat; elevation, dignity", "ur": "رفعت، بلندی", "fa": "رفعت، بلندی", "hi": "रिफ़्फ़त, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
    "rifqah": {"en": "Rifqah; gentleness, kindness (feminine)", "ur": "رفقہ، نرمی، مہربانی", "fa": "رفقه، نرمی", "hi": "रिफ़्क़ा, कोमलता", "ps": "رفقه، نرمي", "ar": "رِفْقَة، الرِّفْق"},
    "rifqi": {"en": "Rifqi; of gentleness (relational)", "ur": "رفقی، نرمی سے منسوب", "fa": "رفقی، منسوب به رفق", "hi": "रिफ़्क़ी, कोमलता से संबंधित", "ps": "رفقي، د رفق اړوند", "ar": "الرِّفْقِي، مَنْسُوب إِلَى الرِّفْق"},
    "riha": {"en": "Riha; a female given name", "ur": "ریحا (زنانہ نام)", "fa": "ریحا (نام زنانه)", "hi": "रीहा (स्त्री नाम)", "ps": "ریحا (ښځينه نوم)", "ar": "رِيحَا (اسْم عَلَم مُؤَنَّث)"},
    "rihab": {"en": "Rihab; a female given name", "ur": "ریحاب (زنانہ نام)", "fa": "ریحاب (نام زنانه)", "hi": "रीहाब (स्त्री नाम)", "ps": "ریحاب (ښځينه نوم)", "ar": "رِيحَاب (اسْم عَلَم مُؤَنَّث)"},
    "riham": {"en": "Riham; a female given name", "ur": "ریحم (زنانہ نام)", "fa": "ریحم (نام زنانه)", "hi": "रीहम (स्त्री नाम)", "ps": "ریحم (ښځينه نوم)", "ar": "رِيحَم (اسْم عَلَم مُؤَنَّث)"},
    "rihan": {"en": "Rihan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "rihana": {"en": "Rihana; fragrant herb, basil (feminine)", "ur": "ریحانہ، خوشبودار پودا", "fa": "ریحانه، سبزی خوشبو", "hi": "रैहाना, तुलसी", "ps": "ریحانه، خوږ بوټی", "ar": "رَيْحَانَة، الرَّيْحَان"},
    "rija": {"en": "Rija; a female given name", "ur": "ریجا (زنانہ نام)", "fa": "ریجا (نام زنانه)", "hi": "रीजा (स्त्री नाम)", "ps": "ریجا (ښځينه نوم)", "ar": "رِيجَا (اسْم عَلَم مُؤَنَّث)"},
    "rim": {"en": "Rim; a female given name", "ur": "ریم (زنانہ نام)", "fa": "ریم (نام زنانه)", "hi": "रीम (स्त्री नाम)", "ps": "ریم (ښځينه نوم)", "ar": "رِيم (اسْم عَلَم مُؤَنَّث)"},
    "rima": {"en": "Rima; a female given name", "ur": "ریما (زنانہ نام)", "fa": "ریما (نام زنانه)", "hi": "रीमा (स्त्री नाम)", "ps": "ریما (ښځينه نوم)", "ar": "رِيمَا (اسْم عَلَم مُؤَنَّث)"},
    "rimal": {"en": "Rimal; sands (plural)", "ur": "رمال، ریت", "fa": "رمال، ریگ‌ها", "hi": "रिमाल, रेत", "ps": "رمال، شګې", "ar": "الرِّمَال، الرَّمْل"},
    "rimas": {"en": "Rimas; a female given name", "ur": "رماس (زنانہ نام)", "fa": "رماس (نام زنانه)", "hi": "रिमास (स्त्री नाम)", "ps": "رماس (ښځينه نوم)", "ar": "رِمَاس (اسْم عَلَم مُؤَنَّث)"},
    "rimsha": {"en": "Rimsha; a female given name", "ur": "رمشا (زنانہ نام)", "fa": "رمشا (نام زنانه)", "hi": "रिमशा (स्त्री नाम)", "ps": "رمشا (ښځينه نوم)", "ar": "رِمْشَا (اسْم عَلَم مُؤَنَّث)"},
    "rina": {"en": "Rina; a female given name", "ur": "رینہ (زنانہ نام)", "fa": "رینا (نام زنانه)", "hi": "रीना (स्त्री नाम)", "ps": "رینا (ښځينه نوم)", "ar": "رِينَة (اسْم عَلَم مُؤَنَّث)"},
    "rinad": {"en": "Rinad; a female given name", "ur": "رند (زنانہ نام)", "fa": "رند (نام زنانه)", "hi": "रिनाद (स्त्री नाम)", "ps": "رند (ښځينه نوم)", "ar": "رِنَاد (اسْم عَلَم مُؤَنَّث)"},
    "rishan": {"en": "Rishan; a male given name", "ur": "ریشان (مردانہ نام)", "fa": "ریشان (نام مردانه)", "hi": "रीशान (पुरुष नाम)", "ps": "ریشان (نر نوم)", "ar": "رِيشَان (اسْم عَلَم مُذَكَّر)"},
    "riswana": {"en": "Riswana; a female given name", "ur": "ریسوانہ (زنانہ نام)", "fa": "ریسوانا (نام زنانه)", "hi": "रीसवाना (स्त्री नाम)", "ps": "ریسوانا (ښځينه نوم)", "ar": "رِيسْوَانَة (اسْم عَلَم مُؤَنَّث)"},
    "riyaad": {"en": "Riyaad; gardens, meadows", "ur": "ریاض، باغات", "fa": "ریاض، باغ‌ها", "hi": "रियाज़, बाग़ात", "ps": "ریاض، باغونه", "ar": "الرِّيَاض، الْحَدَائِق"},
    "riyad": {"en": "Riyad; gardens, meadows", "ur": "ریاض، باغات", "fa": "ریاض، باغ‌ها", "hi": "रियाज़, बाग़ात", "ps": "ریاض، باغونه", "ar": "الرِّيَاض، الْحَدَائِق"},
    "riyadh": {"en": "Riyadh; gardens, meadows", "ur": "ریاض، باغات", "fa": "ریاض، باغ‌ها", "hi": "रियाज़, बाग़ात", "ps": "ریاض، باغونه", "ar": "الرِّيَاض، الْحَدَائِق"},
    "riyah": {"en": "Riyah; winds (plural)", "ur": "ریاح، ہوائیں", "fa": "ریاح، بادها", "hi": "रियाह, हवाएँ", "ps": "ریاح، بادونه", "ar": "الرِّيَاح، الْأَرْوَاح"},
    "riyasat": {"en": "Riyasat; government, administration", "ur": "ریاست، حکومت", "fa": "ریاست، حکومت", "hi": "रियासत, शासन", "ps": "ریاست، حکومت", "ar": "الرِّيَاسَة، الْحُكُومَة"},
    "riyaz": {"en": "Riyaz; gardens, meadows", "ur": "ریاض، باغات", "fa": "ریاض، باغ‌ها", "hi": "रियाज़, बाग़ात", "ps": "ریاض، باغونه", "ar": "الرِّيَاض، الْحَدَائِق"},
    "riyazul": {"en": "Riyazul; gardens of (construct)", "ur": "ریاض ال، باغات", "fa": "ریاض ال، باغ‌ها", "hi": "रियाज़ुल, बाग़ात", "ps": "ریاض ال، باغونه", "ar": "رِيَاضُ الـ (الْإِضَافَة)"},
    "riza": {"en": "Riza; satisfaction, contentment", "ur": "رضا، رضامندی", "fa": "رضا، خشنودی", "hi": "रिज़ा, संतोष", "ps": "رضا، قناعت", "ar": "الرِّضَا، الْقَنَاعَة"},
    "rizq": {"en": "Rizq; provision, sustenance", "ur": "رزق، روزی", "fa": "رزق، روزی", "hi": "रिज़्क़, रोज़ी", "ps": "رزق، روزي", "ar": "الرِّزْق، الرَّزَّاق"},
    "rizvan": {"en": "Rizvan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "rizvi": {"en": "Rizvi; of Rida (relational, Urdu)", "ur": "رضوی، رضا سے منسوب", "fa": "رضوی، منسوب به رضا", "hi": "रिज़वी, रिज़ा से संबंधित", "ps": "رضوي، د رضا اړوند", "ar": "الرِّضْوِي، مَنْسُوب إِلَى الرِّضَا"},
    "rizwaan": {"en": "Rizwaan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "rizwan": {"en": "Rizwan; pleasure, good favour", "ur": "رضوان، خوشنودی", "fa": "رضوان، خشنودی", "hi": "रिज़वान, प्रसन्नता", "ps": "رضوان، خوښي", "ar": "الرِّضْوَان، الرِّضَا"},
    "rizwana": {"en": "Rizwana; pleasure, good favour (feminine)", "ur": "رضوانہ، خوشنودی", "fa": "رضوانه، خشنودی", "hi": "रिज़वाना, प्रसन्नता", "ps": "رضوانه، خوښي", "ar": "رِضْوَانَة، الرِّضْوَان"},
    "rochdi": {"en": "Rochdi; a male given name (Maghrebi)", "ur": "رشدی (مردانہ نام)", "fa": "رشدی (نام مردانه)", "hi": "रोशदी (पुरुष नाम)", "ps": "رشدي (نر نوم)", "ar": "رُشْدِي (اسْم عَلَم مُذَكَّر)"},
    "roha": {"en": "Roha; a female given name", "ur": "روحہ (زنانہ نام)", "fa": "روحه (نام زنانه)", "hi": "रोहा (स्त्री नाम)", "ps": "روحه (ښځينه نوم)", "ar": "رُوحَة (اسْم عَلَم مُؤَنَّث)"},
    "rohaan": {"en": "Rohaan; a male given name", "ur": "روہان (مردانہ نام)", "fa": "روهان (نام مردانه)", "hi": "रोहान (पुरुष नाम)", "ps": "روهان (نر نوم)", "ar": "رُوهَان (اسْم عَلَم مُذَكَّر)"},
    "rohail": {"en": "Rohail; a male given name", "ur": "روہیل (مردانہ نام)", "fa": "روهیل (نام مردانه)", "hi": "रोहैल (पुरुष नाम)", "ps": "روهیل (نر نوم)", "ar": "رُوهَيْل (اسْم عَلَم مُذَكَّر)"},
    "rohana": {"en": "Rohana; a female given name (Malay)", "ur": "روحانا (زنانہ نام)", "fa": "روهانا (نام زنانه)", "hi": "रोहाना (स्त्री नाम)", "ps": "روهانا (ښځينه نوم)", "ar": "رُوهَانَا (اسْم عَلَم مَلَايُوِيّ)"},
})

CUR = {
 "raza": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "raza", "Arabic", "Male",
          "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
          "Raza is Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Satisfaction Contentment' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "razaan": ("رَزَان", "رزان", "رزان", "रज़ान", "رزان", "razaan", "Arabic", "Female",
            "Arabic رَزَان (Razān)", False, "high",
            "Razaan is Arabic رَزَان (Razān), a female given name. CRITICAL SOURCE ERROR: the source gave رزأن (a non-standard form). The source gloss 'Jewel, Precious One' is unsupported and has been replaced with the documented identification. Same name as razan."),
 "razak": ("رَزَّاق", "رزاق", "رزاق", "रज़्ज़ाक़", "رزاق", "razak", "Arabic", "Male",
           "Arabic root ر ز ق (r-z-q); رَزَّاق (Razzāq)", False, "high",
           "Razak is Arabic رَزَّاق (Razzāq) 'provider, sustainer', an intensive form from the root ر ز ق (r-z-q). The source gloss 'Thankful, Grateful' is unsupported and has been replaced with the lexical sense. Same name as razzaq."),
 "razan": ("رَزَان", "رزان", "رزان", "रज़ान", "رزان", "razan", "Arabic", "Female",
           "Arabic رَزَان (Razān)", False, "high",
           "Razan is Arabic رَزَان (Razān), a female given name. The source gloss 'Rain, Small Raindrop' is unsupported and has been replaced with the documented identification."),
 "razaq": ("رَازِق", "رازق", "رازق", "राज़िक़", "رازق", "razaq", "Arabic", "Male",
           "Arabic root ر ز ق (r-z-q); رَازِق (Rāziq)", False, "high",
           "Razaq is Arabic رَازِق (Rāziq) 'provider, sustainer', from the root ر ز ق (r-z-q). The source gloss \"God's bounty, provision\" is broadly consistent. Same name as raziq."),
 "razeen": ("رَزِين", "رزین", "رزین", "रज़ीन", "رزین", "razeen", "Arabic", "Male",
            "Arabic root ر ز ن (r-z-n); رَزِين (Razīn)", False, "high",
            "Razeen is Arabic رَزِين (Razīn) 'dignified, serious', from the root ر ز ن (r-z-n). CRITICAL SOURCE ERROR: the source gave رزین (a non-standard form using Persian yeh). The source gloss 'Peaceful' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "razhan": ("رَازْهَان", "رازھان", "راژان", "राज़हान", "راژان", "razhan", "Kurdish", "Male",
            "Kurdish ڕاژان (Razhan)", False, "medium",
            "Razhan is a Kurdish male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Razhan' instead of a script form and labelled the origin Arabic; the name is Kurdish. The source gloss 'Intelligent, Powerful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "razi": ("رَضِي", "رضی", "رضی", "रज़ी", "رضی", "razi", "Arabic", "Male",
          "Arabic root ر ض و (r-ḍ-w); رَضِي (Raḍī)", False, "high",
          "Razi is Arabic رَضِي (Raḍī) 'content, satisfied', from the root ر ض و (r-ḍ-w). The source gloss 'Guided, enlightened' is unsupported and has been replaced with the lexical sense. Same name as radhi."),
 "razia": ("رَاضِيَة", "راضیہ", "راضیه", "राज़िया", "راضیه", "razia", "Arabic", "Female",
           "Arabic root ر ض و (r-ḍ-w); رَاضِيَة (Rāḍiya)", False, "high",
           "Razia is Arabic رَاضِيَة (Rāḍiya) 'content, satisfied' (feminine), from the root ر ض و (r-ḍ-w). The source gloss 'Right-minded or just' is unsupported and has been replaced with the lexical sense. Same name as raziya."),
 "raziah": ("رَاضِيَة", "راضیہ", "راضیه", "राज़िया", "راضیه", "raziah", "Arabic", "Female",
            "Arabic root ر ض و (r-ḍ-w); رَاضِيَة (Rāḍiya)", False, "high",
            "Raziah is Arabic رَاضِيَة (Rāḍiya) 'content, satisfied' (feminine), from the root ر ض و (r-ḍ-w). The source gloss 'Garden of God' is unsupported and has been replaced with the lexical sense. Same name as raziya."),
 "razik": ("رَازِق", "رازق", "رازق", "राज़िक़", "رازق", "razik", "Arabic", "Male",
           "Arabic root ر ز ق (r-z-q); رَازِق (Rāziq)", False, "high",
           "Razik is a spelling variant of Arabic رَازِق (Rāziq) 'provider, sustainer', from the root ر ز ق (r-z-q). The source gloss 'Wise, Intelligent' is unsupported and has been replaced with the lexical sense. Same name as raziq."),
 "razin": ("رَازِن", "رازن", "رازن", "राज़िन", "رازن", "razin", "Arabic", "Male",
           "Arabic root ر ز ن (r-z-n); رَازِن (Rāzin)", False, "high",
           "Razin is Arabic رَازِن (Rāzin) 'dignified, serious', from the root ر ز ن (r-z-n). The source gloss 'Delight, Pleasure' is unsupported and has been replaced with the lexical sense. Same name as razeen."),
 "razina": ("رَازِينَا", "رازینہ", "رازینا", "राज़ीना", "رازینا", "razina", "Arabic", "Female",
            "Arabic رَازِينَا (Rāzīnā)", False, "medium",
            "Razina is recorded as Arabic رَازِينَا (Rāzīnā), a female given name. The source gloss 'Pure, Chaste' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raziq": ("رَازِق", "رازق", "رازق", "राज़िक़", "رازق", "raziq", "Arabic", "Male",
           "Arabic root ر ز ق (r-z-q); رَازِق (Rāziq)", False, "high",
           "Raziq is Arabic رَازِق (Rāziq) 'provider, sustainer', from the root ر ز ق (r-z-q). The source gloss 'Provider, Sustainer' is consistent."),
 "raziya": ("رَاضِيَة", "راضیہ", "راضیه", "राज़िया", "راضیه", "raziya", "Arabic", "Female",
            "Arabic root ر ض و (r-ḍ-w); رَاضِيَة (Rāḍiya)", False, "high",
            "Raziya is Arabic رَاضِيَة (Rāḍiya) 'content, satisfied' (feminine), from the root ر ض و (r-ḍ-w). The source gloss 'Happiness, Joy' is broadly consistent. Same name as razia."),
 "razwan": ("رِضْوَان", "رضوان", "رضوان", "रज़वान", "رضوان", "razwan", "Arabic", "Male",
            "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
            "Razwan is a spelling variant of Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source gave رزوان (a non-standard form). The source gloss 'Moon Glow' is unsupported and has been replaced with the lexical sense. Same name as ridwan."),
 "razzak": ("رَزَّاق", "رزاق", "رزاق", "रज़्ज़ाक़", "رزاق", "razzak", "Arabic", "Male",
            "Arabic root ر ز ق (r-z-q); رَزَّاق (Razzāq)", False, "high",
            "Razzak is Arabic رَزَّاق (Razzāq) 'the Provider', an intensive form from the root ر ز ق (r-z-q). The source gloss 'The Provider' is consistent. Same name as razzaq."),
 "razzaq": ("رَزَّاق", "رزاق", "رزاق", "रज़्ज़ाक़", "رزاق", "razzaq", "Arabic", "Male",
            "Arabic root ر ز ق (r-z-q); رَزَّاق (Razzāq)", False, "high",
            "Razzaq is Arabic رَزَّاق (Razzāq) 'the Provider', an intensive form from the root ر ز ق (r-z-q). The source gloss 'The Provider' is consistent."),
 "reda": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "reda", "Arabic", "Male",
          "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
          "Reda is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Red, Ready' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raza."),
 "reeham": ("رِيم", "ریم", "ریم", "रीम", "ریم", "reeham", "Arabic", "Female",
            "Arabic رِيم (Rīm)", False, "high",
            "Reeham is a spelling variant of Arabic رِيم (Rīm), a female given name. CRITICAL SOURCE ERROR: the source gave رضيم (a different form); the correct form is رِيم. The source gloss 'Stream' is unsupported and has been replaced with the documented identification. Same name as reem."),
 "reem": ("رِيم", "ریم", "ریم", "रीम", "ریم", "reem", "Arabic", "Female",
          "Arabic رِيم (Rīm)", False, "high",
          "Reem is Arabic رِيم (Rīm), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "reema": ("رِيمَا", "ریما", "ریما", "रीमा", "ریما", "reema", "Arabic", "Female",
           "Arabic رِيمَا (Rīmā)", False, "high",
           "Reema is Arabic رِيمَا (Rīmā), a female given name. CRITICAL SOURCE ERROR: the source gave ريم (a different form); the correct form is رِيمَا. The source gloss 'Stream' is unsupported and has been replaced with the documented identification. Same name as reem."),
 "reet": ("رِيت", "ریت", "ریت", "रीत", "ریت", "reet", "Arabic", "Female",
          "Arabic رِيت (Rīt)", False, "medium",
          "Reet is recorded as Arabic رِيت (Rīt), a female given name. The source gloss 'Gentleness, compassion' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rehaam": ("رَحَام", "رحام", "رحام", "रहाम", "رحام", "rehaam", "Arabic", "Male",
            "Arabic رَحَام (Raḥām)", False, "medium",
            "Rehaam is recorded as Arabic رَحَام (Raḥām), a male given name. The source gloss 'Content, Satisfied, Contented' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rehaan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "rehaan", "Arabic", "Male",
            "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
            "Rehaan is a spelling variant of Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). The source gloss 'Content, Satisfied' is unsupported and has been replaced with the lexical sense. Same name as raihan."),
 "rehab": ("رِهَاب", "رہاب", "رهاب", "रिहाब", "رهاب", "rehab", "Arabic", "Female",
           "Arabic رِهَاب (Rihāb)", False, "high",
           "Rehab is Arabic رِهَاب (Rihāb), a female given name. The source gloss 'Path to Paradise' is unsupported and has been replaced with the documented identification."),
 "reham": ("رَحْم", "رحم", "رحم", "रहम", "رحم", "reham", "Arabic", "Female",
           "Arabic root ر ح م (r-ḥ-m); رَحْم (Raḥm)", False, "high",
           "Reham is Arabic رَحْم (Raḥm) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Content, Pleasing, Satiated' is unsupported and has been replaced with the lexical sense."),
 "rehan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "rehan", "Arabic", "Male",
           "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
           "Rehan is Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as raihan."),
 "rehana": ("رُهَانَة", "رہانہ", "رهانه", "रिहाना", "رهانه", "rehana", "Arabic", "Female",
            "Arabic رُهَانَة (Ruhāna)", False, "medium",
            "Rehana is recorded as Arabic رُهَانَة (Ruhāna), a female given name. The source gloss 'Noble, Content' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rehena": ("رَهِينَة", "رہینہ", "رهینه", "रहीना", "رهینه", "rehena", "Arabic", "Female",
            "Arabic رَهِينَة (Rahīna)", False, "medium",
            "Rehena is recorded as Arabic رَهِينَة (Rahīna), a female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name); the correct form is رَهِينَة. The source gloss 'Contentment, Satisfaction' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rehma": ("رَحْمَة", "رحمہ", "رحمه", "रहमा", "رحمه", "rehma", "Arabic", "Female",
           "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
           "Rehma is a spelling variant of Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Mercy, Grace, Compassion' is consistent. Same name as rahma."),
 "rehman": ("رَحْمَان", "رحمان", "رحمان", "रहमान", "رحمان", "rehman", "Arabic", "Male",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَان (Raḥmān)", False, "high",
            "Rehman is a spelling variant of Arabic رَحْمَان (Raḥmān) 'the Most Merciful', from the root ر ح م (r-ḥ-m). The source gloss 'Benevolent, Merciful, Kind' is broadly consistent. Same name as rahman."),
 "rehmat": ("رَحْمَة", "رحمت", "رحمت", "रहमत", "رحمت", "rehmat", "Arabic", "Male",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
            "Rehmat is a spelling variant of Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Mercy' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as rahmat."),
 "rehnuma": ("رَهْنُمَا", "رہنما", "رهنما", "रहनुमा", "رهنما", "rehnuma", "Urdu", "Female",
             "Urdu رہنما (rehnumā), from Persian رهنما", False, "high",
             "Rehnuma is Urdu رہنما (rehnumā) 'guide, leader', from Persian رهنما. CRITICAL SOURCE ERROR: the source gave رهنماء (a non-standard form) and labelled the origin Arabic; the name as used is Urdu. The source gloss 'Comfort, Love, Calmness' is unsupported and has been replaced with the lexical sense."),
 "reja": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "reja", "Arabic", "Female",
          "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
          "Reja is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Moon, bright, glowing' is unsupported and has been replaced with the lexical sense. Same name as raza."),
 "rejab": ("رَجَب", "رجب", "رجب", "रजब", "رجب", "rejab", "Arabic", "Male",
           "Arabic رَجَب (Rajab), the seventh Islamic month", False, "high",
           "Rejab is a spelling variant of Arabic رَجَب (Rajab), the seventh month of the Islamic calendar, used as a male given name. The source gloss 'First month' is incorrect; the month is the seventh. Same name as rajab."),
 "renana": ("رَنَانَة", "رنانہ", "رنانه", "रनाना", "رنانه", "renana", "Arabic", "Female",
            "Arabic رَنَانَة (Ranāna)", False, "medium",
            "Renana is recorded as Arabic رَنَانَة (Ranāna), a female given name. The source gloss 'Joy, happiness, contentment' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "resa": ("رِيسَا", "ریسا", "ریسا", "रेसा", "ریسا", "resa", "Arabic", "Female",
          "Arabic رِيسَا (Rīsā)", False, "medium",
          "Resa is recorded as Arabic رِيسَا (Rīsā), a female given name. The source gloss 'Leader, Chief' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "resha": ("رِيشَا", "ریشا", "ریشا", "रीशा", "ریشا", "resha", "Arabic", "Female",
           "Arabic رِيشَا (Rīshā)", False, "medium",
           "Resha is recorded as Arabic رِيشَا (Rīshā), a female given name. CRITICAL SOURCE ERROR: the source gave زينب (a different name); the correct form is رِيشَا. The source gloss 'Fish' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "resham": ("رِيشَم", "ریشم", "ریشم", "रेशम", "ریشم", "resham", "Persian", "Female",
            "Persian ریشم (resham) 'silk'", False, "high",
            "Resham is Persian/Urdu ریشم (resham) 'silk', used as a female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the word is Persian/Urdu. The source gloss 'Silk' is consistent."),
 "reyan": ("رَيَّان", "ریان", "ریان", "रैयान", "ریان", "reyan", "Arabic", "Male",
           "Arabic root ر و ي (r-w-y); رَيَّان (Rayyān)", False, "high",
           "Reyan is a spelling variant of Arabic رَيَّان (Rayyān) 'sated, refreshed', from the root ر و ي (r-w-y). The source gloss 'Gates of Heaven, Blessed, Luxuriant' is unsupported and has been replaced with the lexical sense. Same name as rayan."),
 "reyhan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "reyhan", "Turkish", "Female",
            "Turkish Reyhan, from Arabic رَيْحَان", False, "high",
            "Reyhan is the Turkish form of Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', used as a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Turkish. The source gloss 'Lady of the garden' is unsupported and has been replaced with the lexical sense."),
 "reyhana": ("رَيْحَانَة", "ریحانہ", "ریحانه", "रैहाना", "ریحانه", "reyhana", "Arabic", "Female",
             "Arabic root ر و ح (r-w-ḥ); رَيْحَانَة (Rayḥāna)", False, "high",
             "Reyhana is a spelling variant of Arabic رَيْحَانَة (Rayḥāna) 'fragrant herb, basil' (feminine), from the root ر و ح (r-w-ḥ). The source gloss 'Tender, Delicate' is unsupported and has been replaced with the lexical sense. Same name as raihana."),
 "reza": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "reza", "Persian", "Male",
          "Persian رضا (rezā), from Arabic رِضَا", False, "high",
          "Reza is the Persian form of Arabic رِضَا (Riḍā) 'satisfaction, contentment', used as a male given name. The source gloss 'Helper' is unsupported and has been replaced with the lexical sense. Same name as raza."),
 "riad": ("رِيَاض", "ریاض", "ریاض", "रियाज़", "ریاض", "riad", "Arabic", "Male",
          "Arabic root ر و ض (r-w-ḍ); رِيَاض (Riyāḍ)", False, "high",
          "Riad is Arabic رِيَاض (Riyāḍ) 'gardens, meadows', the plural of رَوْضَة (rauḍa). The source gloss 'garden' is broadly consistent. Same name as riyad."),
 "riaz": ("رِيَاض", "ریاض", "ریاض", "रियाज़", "ریاض", "riaz", "Arabic", "Male",
          "Arabic root ر و ض (r-w-ḍ); رِيَاض (Riyāḍ)", False, "high",
          "Riaz is a spelling variant of Arabic رِيَاض (Riyāḍ) 'gardens, meadows', the plural of رَوْضَة (rauḍa). The source gloss 'Frequent rain' is unsupported and has been replaced with the lexical sense. Same name as riyad."),
 "rida": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "rida", "Arabic", "Male",
          "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
          "Rida is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Pleasing, Acceptable, Joyful' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raza."),
 "ridaa": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "ridaa", "Arabic", "Male",
           "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
           "Ridaa is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Contentment, Satisfaction' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raza."),
 "ridha": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "ridha", "Arabic", "Male",
           "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
           "Ridha is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Pleasing to God' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raza."),
 "ridhaa": ("رِضَا", "رضا", "رضا", "रज़ा", "رضا", "ridhaa", "Arabic", "Male",
            "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
            "Ridhaa is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). The source gloss 'Contentment, pleasure' is consistent. Same name as raza."),
 "ridhwaan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "ridhwaan", "Arabic", "Male",
              "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
              "Ridhwaan is Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). The source gloss 'Contentment, Satisfaction, Favor' is broadly consistent. Same name as ridwan."),
 "ridhwan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "ridhwan", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
             "Ridhwan is Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). The source gloss 'The One Who is Ever Content and Satisfied' is a truncated gloss. Same name as ridwan."),
 "ridwaan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "ridwaan", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
             "Ridwaan is Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). The source gloss 'Favor, Blessing, Satisfaction' is broadly consistent. Same name as ridwan."),
 "ridwan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "ridwan", "Arabic", "Male",
            "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
            "Ridwan is Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). The source gloss 'Welcomed with pleasure' is broadly consistent."),
 "rifa": ("رِفَا", "رفا", "رفا", "रिफ़ा", "رفا", "rifa", "Arabic", "Female",
          "Arabic رِفَا (Rifā)", False, "medium",
          "Rifa is recorded as Arabic رِفَا (Rifā), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rifa' instead of a script form. The source gloss 'Soft, gentle, pure' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rifaa": ("رِفْعَة", "رفعت", "رفعت", "रिफ़ा", "رفعت", "rifaa", "Arabic", "Female",
           "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
           "Rifaa is Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). The source gloss 'Gentle, Kind' is unsupported and has been replaced with the lexical sense. Same name as rifaat."),
 "rifaat": ("رِفْعَة", "رفعت", "رفعت", "रिफ़ात", "رفعت", "rifaat", "Arabic", "Male",
            "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
            "Rifaat is Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رفات (a non-standard form). The source gloss 'Elevated, Exalted, or Lofty' is broadly consistent."),
 "rifah": ("رِفْحَة", "رفحہ", "رفحه", "रिफ़ाह", "رفحه", "rifah", "Arabic", "Female",
           "Arabic رِفْحَة (Rifḥa)", False, "medium",
           "Rifah is recorded as Arabic رِفْحَة (Rifḥa), a female given name. The source gloss 'Garden, Paradise' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rifai": ("رِفَاعِي", "رفاعی", "رفاعی", "रिफ़ाई", "رفاعي", "rifai", "Arabic", "Male",
           "Arabic رِفَاعِي (Rifāʿī) 'of the Rifa'i order'", False, "high",
           "Rifai is Arabic رِفَاعِي (Rifāʿī) 'of the Rifa'i order', a relational name. CRITICAL SOURCE ERROR: the source gave 'عربي_Rifai' (a placeholder prefix); the correct form is رِفَاعِي. The source gloss 'Noble and blessed' is unsupported and has been replaced with the lexical sense."),
 "rifal": ("رِفَل", "رفل", "رفل", "रिफ़ल", "رفل", "rifal", "Arabic", "Male",
           "Arabic رِفَل (Rifal)", False, "medium",
           "Rifal is recorded as Arabic رِفَل (Rifal), a male given name. The source gloss 'Gentle Wave' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rifaqat": ("رِفَاقَة", "رفاقت", "رفاقت", "रिफ़ाक़त", "رفاقت", "rifaqat", "Arabic", "Male",
             "Arabic root ر ف ق (r-f-q); رِفَاقَة (Rifāqa)", False, "high",
             "Rifaqat is Arabic رِفَاقَة (Rifāqa) 'companionship, fellowship', from the root ر ف ق (r-f-q). The source gloss 'Companionship, Friendship' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rifat": ("رِفْعَة", "رفعت", "رفعت", "रिफ़ात", "رفعت", "rifat", "Arabic", "Male",
           "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
           "Rifat is a spelling variant of Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رفات (a non-standard form). The source gloss 'Traveler, Wanderer' is unsupported and has been replaced with the lexical sense. Same name as rifaat."),
 "rifaya": ("رِفَاءَة", "رفاء", "رفاء", "रिफ़ाया", "رفاء", "rifaya", "Arabic", "Female",
            "Arabic رِفَاءَة (Rifāʾa)", False, "medium",
            "Rifaya is recorded as Arabic رِفَاءَة (Rifāʾa), a female given name. The source gloss 'Gracious, Merciful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "riffat": ("رِفْعَة", "رفعت", "رفعت", "रिफ़्फ़त", "رفعت", "riffat", "Arabic", "Female",
            "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
            "Riffat is a spelling variant of Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رفات (a non-standard form). The source gloss 'Soft, gentle, graceful' is unsupported and has been replaced with the lexical sense. Same name as rifaat."),
 "rifqah": ("رِفْقَة", "رفقہ", "رفقه", "रिफ़्क़ा", "رفقه", "rifqah", "Arabic", "Female",
            "Arabic root ر ف ق (r-f-q); رِفْقَة (Rifqa)", False, "high",
            "Rifqah is Arabic رِفْقَة (Rifqa) 'gentleness, kindness' (feminine), from the root ر ف ق (r-f-q). The source gloss 'Comfort, Consolation, Safety' is unsupported and has been replaced with the lexical sense."),
 "rifqi": ("رِفْقِي", "رفقی", "رفقی", "रिफ़्क़ी", "رفقي", "rifqi", "Arabic", "Male",
           "Arabic رِفْقِي (Rifqī) 'of gentleness'", False, "high",
           "Rifqi is Arabic رِفْقِي (Rifqī) 'of gentleness', a relational adjective from رِفْق (rifq). The source gloss 'Comfort, Consolation, Peace' is unsupported and has been replaced with the lexical sense."),
 "riha": ("رِيحَا", "ریحا", "ریحا", "रीहा", "ریحا", "riha", "Arabic", "Female",
          "Arabic رِيحَا (Rīḥā)", False, "medium",
          "Riha is recorded as Arabic رِيحَا (Rīḥā), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Riha' instead of a script form. The source gloss 'Flowing, River' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rihab": ("رِيحَاب", "ریحاب", "ریحاب", "रीहाब", "ریحاب", "rihab", "Arabic", "Female",
           "Arabic رِيحَاب (Rīḥāb)", False, "high",
           "Rihab is Arabic رِيحَاب (Rīḥāb), a female given name. The source gloss 'A refuge, a shelter' is unsupported and has been replaced with the documented identification."),
 "riham": ("رِيحَم", "ریحم", "ریحم", "रीहम", "ریحم", "riham", "Arabic", "Female",
           "Arabic رِيحَم (Rīḥam)", False, "medium",
           "Riham is recorded as Arabic رِيحَم (Rīḥam), a female given name. The source gloss 'Soft Rain' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rihan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "rihan", "Arabic", "Male",
           "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
           "Rihan is a spelling variant of Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). CRITICAL SOURCE ERROR: the source gave ريهان (a non-standard form). The source gloss 'Path, Way' is unsupported and has been replaced with the lexical sense. Same name as raihan."),
 "rihana": ("رَيْحَانَة", "ریحانہ", "ریحانه", "रैहाना", "ریحانه", "rihana", "Arabic", "Female",
            "Arabic root ر و ح (r-w-ḥ); رَيْحَانَة (Rayḥāna)", False, "high",
            "Rihana is a spelling variant of Arabic رَيْحَانَة (Rayḥāna) 'fragrant herb, basil' (feminine), from the root ر و ح (r-w-ḥ). The source gloss 'Lady, Mistress' is unsupported and has been replaced with the lexical sense. Same name as raihana."),
 "rija": ("رِيجَا", "ریجا", "ریجا", "रीजा", "ریجا", "rija", "Arabic", "Female",
          "Arabic رِيجَا (Rījā)", False, "medium",
          "Rija is recorded as Arabic رِيجَا (Rījā), a female given name. The source gloss 'Little Stream' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rim": ("رِيم", "ریم", "ریم", "रीम", "ریم", "rim", "Arabic", "Female",
         "Arabic رِيم (Rīm)", False, "high",
         "Rim is Arabic رِيم (Rīm), a female given name. The source gloss \"A variant of the name Rahim, meaning 'compassionate'\" is incorrect; the name is unrelated to Rahim. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as reem."),
 "rima": ("رِيمَا", "ریما", "ریما", "रीमा", "ریما", "rima", "Arabic", "Female",
          "Arabic رِيمَا (Rīmā)", False, "high",
          "Rima is Arabic رِيمَا (Rīmā), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as reema."),
 "rimal": ("رِمَال", "رمال", "رمال", "रिमाल", "رمال", "rimal", "Arabic", "Female",
           "Arabic root ر م ل (r-m-l); رِمَال (Rimāl)", False, "high",
           "Rimal is Arabic رِمَال (Rimāl) 'sands', the plural of رَمْل (raml). CRITICAL SOURCE ERROR: the source gave ريمــال (a form padded with tatweel). The source gloss 'Little Ripe Fruit' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "rimas": ("رِمَاس", "رماس", "رماس", "रिमास", "رماس", "rimas", "Arabic", "Female",
           "Arabic رِمَاس (Rimās)", False, "high",
           "Rimas is Arabic رِمَاس (Rimās), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "rimsha": ("رِمْشَا", "رمشا", "رمشا", "रिमशा", "رمشا", "rimsha", "Arabic", "Female",
            "Arabic رِمْشَا (Rimshā)", False, "high",
            "Rimsha is Arabic رِمْشَا (Rimshā), a female given name. CRITICAL SOURCE ERROR: the source gave 'عربي_Rimsha' (a placeholder prefix); the correct form is رِمْشَا. The source gloss 'Noble and blessed' is unsupported and has been replaced with the documented identification."),
 "rina": ("رِينَة", "رینہ", "رینا", "रीना", "رینا", "rina", "Arabic", "Female",
          "Arabic رِينَة (Rīna)", False, "medium",
          "Rina is recorded as Arabic رِينَة (Rīna), a female given name. The source gloss 'Joyful, content' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rinad": ("رِنَاد", "رند", "رند", "रिनाद", "رند", "rinad", "Arabic", "Female",
           "Arabic رِنَاد (Rinād)", False, "medium",
           "Rinad is recorded as Arabic رِنَاد (Rinād), a female given name. CRITICAL SOURCE ERROR: the source gave رند (a non-standard form). The source gloss 'Melodious' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rishan": ("رِيشَان", "ریشان", "ریشان", "रीशान", "ریشان", "rishan", "Arabic", "Male",
            "Arabic رِيشَان (Rīshān)", False, "medium",
            "Rishan is recorded as Arabic رِيشَان (Rīshān), a male given name. CRITICAL SOURCE ERROR: the source gave ريش ان (a broken form). The source gloss 'Joyful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "riswana": ("رِيسْوَانَة", "ریسوانہ", "ریسوانا", "रीसवाना", "ریسوانا", "riswana", "Arabic", "Female",
             "Arabic رِيسْوَانَة (Rīswāna)", False, "medium",
             "Riswana is recorded as Arabic رِيسْوَانَة (Rīswāna), a female given name. The source gloss 'Garden, bloom' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "riyaad": ("رِيَاض", "ریاض", "ریاض", "रियाज़", "ریاض", "riyaad", "Arabic", "Male",
            "Arabic root ر و ض (r-w-ḍ); رِيَاض (Riyāḍ)", False, "high",
            "Riyaad is Arabic رِيَاض (Riyāḍ) 'gardens, meadows', the plural of رَوْضَة (rauḍa). The source gloss 'Gardener, Traveler' is unsupported and has been replaced with the lexical sense. Same name as riyad."),
 "riyad": ("رِيَاض", "ریاض", "ریاض", "रियाज़", "ریاض", "riyad", "Arabic", "Male",
           "Arabic root ر و ض (r-w-ḍ); رِيَاض (Riyāḍ)", False, "high",
           "Riyad is Arabic رِيَاض (Riyāḍ) 'gardens, meadows', the plural of رَوْضَة (rauḍa). The source gloss 'garden, meadow, paradise' is broadly consistent."),
 "riyadh": ("رِيَاض", "ریاض", "ریاض", "रियाज़", "ریاض", "riyadh", "Arabic", "Male",
            "Arabic root ر و ض (r-w-ḍ); رِيَاض (Riyāḍ)", False, "high",
            "Riyadh is Arabic رِيَاض (Riyāḍ) 'gardens, meadows', the plural of رَوْضَة (rauḍa). The source gloss 'Gardens, meadows, or open country' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as riyad."),
 "riyah": ("رِيَاح", "ریاح", "ریاح", "रियाह", "ریاح", "riyah", "Arabic", "Female",
           "Arabic root ر و ح (r-w-ḥ); رِيَاح (Riyāḥ)", False, "high",
           "Riyah is Arabic رِيَاح (Riyāḥ) 'winds', the plural of رِيح (rīḥ). The source gloss 'Contentment, Satisfaction' is unsupported and has been replaced with the lexical sense."),
 "riyasat": ("رِيَاسَة", "ریاست", "ریاست", "रियासत", "ریاست", "riyasat", "Arabic", "Female",
             "Arabic root ر أ س (r-ʾ-s); رِيَاسَة (Riyāsa)", False, "high",
             "Riyasat is Arabic رِيَاسَة (Riyāsa) 'government, administration', from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source gave رياسات (a non-standard form). The source gloss 'Government, Administration' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "riyaz": ("رِيَاض", "ریاض", "ریاض", "रियाज़", "ریاض", "riyaz", "Arabic", "Male",
           "Arabic root ر و ض (r-w-ḍ); رِيَاض (Riyāḍ)", False, "high",
           "Riyaz is a spelling variant of Arabic رِيَاض (Riyāḍ) 'gardens, meadows', the plural of رَوْضَة (rauḍa). The source gloss 'Gardener, Scholar, Learner' is unsupported and has been replaced with the lexical sense. Same name as riyad."),
 "riyazul": ("رِيَاضُ الـ", "ریاض ال", "ریاض ال", "रियाज़ुल", "ریاض ال", "riyazul", "Arabic", "Male",
             "Arabic رِيَاض (riyāḍ) in construct with the article", False, "high",
             "Riyazul is Arabic رِيَاضُ الـ (Riyāḍu l-) 'gardens of', a construct form of رِيَاض (riyāḍ). The source gloss 'Gardener of the Reality' is unsupported and has been replaced with the lexical sense."),
 "riza": ("رِضَا", "رضا", "رضا", "रिज़ा", "رضا", "riza", "Arabic", "Male",
          "Arabic root ر ض و (r-ḍ-w); رِضَا (Riḍā)", False, "high",
          "Riza is a spelling variant of Arabic رِضَا (Riḍā) 'satisfaction, contentment', from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source gave رزا (a non-standard form). The source gloss 'Contentment, Pleasure, Gladness' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raza."),
 "rizq": ("رِزْق", "رزق", "رزق", "रिज़्क़", "رزق", "rizq", "Arabic", "Male",
          "Arabic root ر ز ق (r-z-q); رِزْق (Rizq)", False, "high",
          "Rizq is Arabic رِزْق (Rizq) 'provision, sustenance', from the root ر ز ق (r-z-q). The source gloss 'Provision, Sustenance' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rizvan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "rizvan", "Arabic", "Male",
            "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
            "Rizvan is a spelling variant of Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). The source gloss \"God's Promise\" is unsupported and has been replaced with the lexical sense. Same name as ridwan."),
 "rizvi": ("رِضْوِي", "رضوی", "رضوی", "रिज़वी", "رضوي", "rizvi", "Urdu", "Male",
           "Urdu رضوی (rizvī), from Arabic رِضْوِي", False, "high",
           "Rizvi is Urdu رضوی (rizvī) 'of Rida', a relational surname/name from Arabic رِضْوِي. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Persian/Urdu. The source gloss 'wise protector' is unsupported and has been replaced with the lexical sense."),
 "rizwaan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "rizwaan", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
             "Rizwaan is Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). The source gloss 'Protector, Guardian, Supporter' is unsupported and has been replaced with the lexical sense. Same name as ridwan."),
 "rizwan": ("رِضْوَان", "رضوان", "رضوان", "रिज़वान", "رضوان", "rizwan", "Arabic", "Male",
            "Arabic root ر ض و (r-ḍ-w); رِضْوَان (Riḍwān)", False, "high",
            "Rizwan is Arabic رِضْوَان (Riḍwān) 'pleasure, good favour', from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as ridwan."),
 "rizwana": ("رِضْوَانَة", "رضوانہ", "رضوانه", "रिज़वाना", "رضوانه", "rizwana", "Arabic", "Female",
             "Arabic root ر ض و (r-ḍ-w); رِضْوَانَة (Riḍwāna)", False, "high",
             "Rizwana is Arabic رِضْوَانَة (Riḍwāna) 'pleasure, good favour' (feminine), from the root ر ض و (r-ḍ-w). CRITICAL SOURCE ERROR: the source gave 'رazwana' (a broken Latin-Arabic mix); the correct form is رِضْوَانَة. The source gloss 'Blessed with kindness' is unsupported and has been replaced with the lexical sense."),
 "rochdi": ("رُشْدِي", "رشدی", "رشدی", "रोशदी", "رشدي", "rochdi", "Arabic", "Male",
            "Arabic رُشْدِي (Rushdī) 'of right guidance'", False, "high",
            "Rochdi is a Maghrebi spelling of Arabic رُشْدِي (Rushdī) 'of right guidance', a relational adjective from رُشْد (rushd). CRITICAL SOURCE ERROR: the source gave رَوْشِدِيّ (a non-standard form). The source gloss 'Gifted, Rich' is unsupported and has been replaced with the lexical sense."),
 "roha": ("رُوحَة", "روحہ", "روحه", "रोहा", "روحه", "roha", "Arabic", "Female",
          "Arabic رُوحَة (Rūḥa)", False, "medium",
          "Roha is recorded as Arabic رُوحَة (Rūḥa), a female given name. CRITICAL SOURCE ERROR: the source gave رُحة (a non-standard form). The source gloss 'Contentment, happiness' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rohaan": ("رُوهَان", "روہان", "روهان", "रोहान", "روهان", "rohaan", "Arabic", "Male",
            "Arabic رُوهَان (Rūhān)", False, "medium",
            "Rohaan is recorded as Arabic رُوهَان (Rūhān), a male given name. The source gloss 'Content, Contented' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rohail": ("رُوهَيْل", "روہیل", "روهیل", "रोहैल", "روهیل", "rohail", "Arabic", "Male",
            "Arabic رُوهَيْل (Rūhayl)", False, "medium",
            "Rohail is recorded as Arabic رُوهَيْل (Rūhayl), a male given name. The source gloss 'Guide, One who leads with wisdom' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rohana": ("رُوهَانَا", "روحانا", "روهانا", "रोहाना", "روهانا", "rohana", "Malay", "Female",
            "Malay Rohana", False, "medium",
            "Rohana is a Malay female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Malay. The source gloss 'Mountain' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
}
