# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 26 (haadee..hakeema).

Source defects found in this batch:
 * ORIGIN MISLABEL: hakan is Turkish (the raw record's own language column admits Turkish)
   though the origin column says Arabic; haimi is a Hebrew 'life' name (Chaim), not aromatic.
 * WRONG / PLACEHOLDER "Arabic forms": haimi -> أحمد; hair -> شعر ("hair"); haida/hadiyah ->
   a different name (hadiyya); haadiyah -> حَدِيَة; hafeez -> حفيظ.
 * DEGARBLED glosses: haadi 'guide' was glossed 'delight'; haadiya 'guide' glossed
   'gift'; hafiz 'guardian' glossed 'wisdom'; habat 'seed' glossed 'gift';
   haddad 'smith' glossed 'wise'; hadeel ('dove's cooing') glossed 'garden'.
 * JUNK ENTRY: hahah (hasahah) is not a name in any Tier-A/B source.
 * DUPLICATE CLUSTERS: haajar/hagir/hajir/hajira; habib/habeeb; hadiya/hadiah/hadiyah/
   hadiyyah/hadya/hadaya; hafsa/hafsah; hajja/hajjah/haji/haji; hajra/hajrah.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated25 import GLOSSES as _G25

GLOSSES = dict(_G25)
GLOSSES.update({
    "guide_leader": {"en": "Guide, leader", "ur": "راہ دکھانے والا، قائد", "fa": "رهنما، رهبر", "hi": "मार्गदर्शक, नेता", "ps": "لارښود، مشر", "ar": "الهادي، القائد"},
    "delight_pleasure": {"en": "Delight, pleasure", "ur": "خوشی، لذت", "fa": "شادی، لذت", "hi": "आनंद, ख़ुशी", "ps": "خوښي، خوند", "ar": "البهجة، اللذة"},
    "gift_grace": {"en": "Gift, grace, blessing", "ur": "تحفہ، نعمت", "fa": "هدیه، نعمت", "hi": "उपहार, कृपा", "ps": "ډالۍ، نعمت", "ar": "الهدية، النعمة"},
    "protector_guardian": {"en": "Protector, guardian, preserver", "ur": "محافظ، نگہبان", "fa": "نگهبان، نگاه‌دارنده", "hi": "रक्षक, संरक्षक", "ps": "ساتونکی، پالونکی", "ar": "الحافظ، الحفيظ"},
    "lion_brave": {"en": "Lion; brave, courageous", "ur": "شیر، بہادر", "fa": "شیر، دلیر", "hi": "शेर, बहादुर", "ps": "زمری، زړور", "ar": "الأسد، الليث، الشجاع"},
    "goal_aim": {"en": "Goal, aim, target", "ur": "مقصد، ہدف", "fa": "هدف، مقصود", "hi": "लक्ष्य, उद्देश्य", "ps": "هدف، موخه", "ar": "الهدف، الغاية"},
    "pilgrim": {"en": "Pilgrim (one who performs the Hajj)", "ur": "حاجی، زیارت کرنے والا", "fa": "حاجی، زیارت‌گزار", "hi": "हाजी, तीर्थयात्री", "ps": "حاجي، زيارت کوونکی", "ar": "الحاج، الحاجّ"},
    "pilgrims": {"en": "Pilgrims (plural of hajj)", "ur": "حاجی (جمع)", "fa": "حاجیان", "hi": "हाजी (बहुवचन)", "ps": "حاجيان", "ar": "الحجّاج، الحاجّون"},
    "pleasing_sweet": {"en": "Pleasant, sweet, delightful", "ur": "خوشگوار، شیریں", "fa": "دلپذیر، شیرین", "hi": "सुखद, मधुर", "ps": "خوږ، خوښ", "ar": "الهانئ، اللذيذ، السارّ"},
    "halo_aura": {"en": "Halo, aura, the glow around the moon", "ur": "ہالہ، چاند کے گرد نور", "fa": "هاله، گرد نور ماه", "hi": "प्रभामंडल, चाँद के चारों ओर प्रकाश", "ps": "هاله، د سپوږمۍ شاوخوا رڼا", "ar": "الهالة، غلاف القمر المضيء"},
    "guardian_haris": {"en": "Guardian, watcher; tiller of the soil", "ur": "نگہبان، محافظ؛ کاشتکار", "fa": "نگهبان، پاسدار؛ کشاورز", "hi": "रक्षक, पहरेदार; कृषक", "ps": "ساتونکی، څارونکی; بزګر", "ar": "الحارس، الحارث"},
    "hashim_crusher": {"en": "Hashim; one who crushes (bread for the people)", "ur": "ہاشم، روٹی چورنے والا", "fa": "هاشم، خردکننده نان برای مردم", "hi": "हाशिम, रोटी तोड़ने वाला", "ps": "هاشم، ډوډۍ ماتوونکی", "ar": "هاشم، الذي يهشم الخبز لقومه"},
    "generous_giver": {"en": "Generous giver, open-handed", "ur": "سخی، عطا کرنے والا", "fa": "بخشنده، دست‌ودل‌باز", "hi": "उदार, देने वाला", "ps": "سخي، ورکوونکی", "ar": "المعطي، الجواد"},
    "skilful_astute": {"en": "Skilful, astute, proficient", "ur": "ہوشیار، ماہر، دانا", "fa": "ماهر، زیرک، دانا", "hi": "कुशल, चतुर, दक्ष", "ps": "ماهر، ځیرک", "ar": "الحاذق، الماهر"},
    "abyssinian": {"en": "Abyssinian (from Habasha, i.e. Ethiopia)", "ur": "حبشی، حبشہ سے", "fa": "حبشی، از حبشه", "hi": "हबशी, हबशा से", "ps": "حبشي، د حبشې", "ar": "الحبشي، من الحبشة"},
    "abyssinian_woman": {"en": "Abyssinian woman (of Habasha)", "ur": "حبشی عورت، حبشہ کی", "fa": "زن حبشی، از حبشه", "hi": "हबशी महिला", "ps": "حبشۍ ښځه", "ar": "الحبشية، من الحبشة"},
    "seed_grain": {"en": "A seed, a grain; also a term of endearment", "ur": "دانہ، بیج؛ پیار کا لفظ", "fa": "دانه، بذر؛ لفظ محبت", "hi": "दाना, बीज; प्यार का शब्द", "ps": "دانه، تخم; د مینې کلمه", "ar": "الحبّة، الحبّ"},
    "beloved": {"en": "Beloved, dear one", "ur": "محبوب، پیارا", "fa": "محبوب، عزیز", "hi": "प्रिय, प्यारा", "ps": "خوږ، مینه‌ن", "ar": "الحبيب، المحبوب"},
    "abel": {"en": "Abel (Habīl / Hābīl, son of Adam)", "ur": "ہابیل، آدم علیہ السلام کا بیٹا", "fa": "هابیل، پسر آدم", "hi": "हाबील, आदम के पुत्र", "ps": "هابیل، د آدم زوی", "ar": "هابيل، ابن آدم"},
    "iron_smith": {"en": "Iron; smith, ironworker", "ur": "لوہا؛ لوہار", "fa": "آهن؛ آهنگر", "hi": "लोहा; लोहार", "ps": "اوسپنه؛ اوسپن‌کار", "ar": "الحديد؛ الحدّاد"},
    "smith": {"en": "Smith, craftsman, blacksmith", "ur": "لوہار، دستکار", "fa": "آهنگر، صنعتگر", "hi": "लोहार, कारीगर", "ps": "اوسپن‌کار، هنرمند", "ar": "الحدّاد، الصانع"},
    "cooing_dove": {"en": "The cooing of a dove; melodious sound", "ur": "کبوتر کی کوک، سریلی آواز", "fa": "آواز کبوتر، نوای خوش", "hi": "कबूतर की कूक, मधुर ध्वनि", "ps": "د کوترې غږ، خوږ آواز", "ar": "هديل الحمام، الصوت الرقيق"},
    "rumble_roar": {"en": "Rumbling, roaring sound (of water, waves)", "ur": "گڑگڑاہٹ، پانی کی گرج", "fa": "غرش، صدای خروشان آب", "hi": "गर्जन, जल की गड़गड़ाहट", "ps": "ږغ، د اوبو غړپ", "ar": "هدير الماء، صوت الأمواج"},
    "narration_hadith": {"en": "Narration, report, hadith (the Prophet's sayings)", "ur": "حدیث، روایت", "fa": "حدیث، روایت", "hi": "हदीस, वृत्तांत", "ps": "حديث، روايت", "ar": "الحديث، الخبر، الرواية"},
    "iron": {"en": "Iron", "ur": "لوہا", "fa": "آهن", "hi": "लोहा", "ps": "اوسپنه", "ar": "الحديد"},
    "present_attending": {"en": "Present, attending; one who is there", "ur": "حاضر، موجود", "fa": "حاضر، موجود", "hi": "उपस्थित, मौजूद", "ps": "حاضر، موجود", "ar": "الحاضر، الموجود"},
    "barefoot_hospitality": {"en": "Barefoot; the welcoming of a barefoot guest (Arab custom)", "ur": "ننگے پاؤں؛ خیر مقدم", "fa": "پابرهنه؛ خوش‌آمدگویی", "hi": "नंगे पाँव; स्वागत", "ps": "پښې لوڅ؛ ښه راغلاست", "ar": "الحافي، إكرام الضيف الحافي"},
    "abounding_full": {"en": "Abounding, full, crowded", "ur": "بھرا ہوا، کثیر", "fa": "پر، پرشده", "hi": "भरपूर, परिपूर्ण", "ps": "ډک، ډېر", "ar": "الحافل، الممتلئ"},
    "gracious_solicitous": {"en": "Gracious, kindly, solicitous", "ur": "مہربان، خیرخواہ", "fa": "مهربان، خیرخواه", "hi": "कृपालु, प्रेमालु", "ps": "مهربان، غمخوار", "ar": "الحفيّ، اللطيف"},
    "serving_aiding": {"en": "One who serves, hastens to help", "ur": "خدمت کرنے والا، مدد کو دوڑنے والا", "fa": "خدمت‌گزار، شتابنده به یاری", "hi": "सेवा करने वाला, सहाय", "ps": "خدمت کوونکی، مرستې ته منډه وهونکی", "ar": "الحافد، الخادم المعين"},
    "granddaughter": {"en": "Granddaughter", "ur": "پوتی، نواسی", "fa": "نوه (دختر)", "hi": "पोती, नातिन", "ps": "لمسۍ، نواسۍ", "ar": "الحفيدة"},
    "light_gentle_rustle": {"en": "Light, delicate; the rustle of leaves", "ur": "ہلکا، نازک؛ پتوں کی سرسراہٹ", "fa": "سبک، لطیف؛ خش‌خش برگ", "hi": "हल्का, कोमल; पत्तों की सरसराहट", "ps": "سپک، نازک؛ د پاڼو شړشړ", "ar": "الخفيف، حفيف الأوراق"},
    "lioness_cub": {"en": "Young lioness, lion cub", "ur": "شیرنی، شیر کا بچہ", "fa": "شیرزن، بچه‌شیر", "hi": "शेरनी, सिंहनी", "ps": "زمرۍ، د زمري بچی", "ar": "الحفصة، شبل الأسد"},
    "laughter": {"en": "Laughter", "ur": "ہنسی، قہقہہ", "fa": "خنده، قهقهه", "hi": "हँसी, ठहाका", "ps": "خندل، قهقهه", "ar": "الضحك، القهقهة"},
    "awe_dignity": {"en": "Awe, dignity, majesty, reverence", "ur": "رعب، دبدبہ، وقار", "fa": "هیبت، شکوه، وقار", "hi": "रोब, गरिमा, प्रताप", "ps": "هيبت، وقار", "ar": "الهيبة، الوقار، الجلال"},
    "of_haidar": {"en": "Of Haidar (the lion); nisba", "ur": "حیدر سے منسوب", "fa": "منسوب به حیدر", "hi": "हैदर से संबंधित", "ps": "د حیدر", "ar": "الحيدري، منسوب إلى حيدر"},
    "haifa_city": {"en": "Haifa (a coastal city); a pleasant, slender place", "ur": "حیفہ (شہر)", "fa": "حیفا (شهر)", "hi": "हैफ़ा (नगर)", "ps": "حیفا (ښار)", "ar": "حيفا (المدينة)"},
    "temple_sanctuary": {"en": "Temple, sanctuary, shrine", "ur": "ہیکل، مقدس مقام", "fa": "هیکل، معبد، جایگاه مقدس", "hi": "मंदिर, पवित्र स्थान", "ps": "هیکل، سپېڅلی ځای", "ar": "الهيكل، المعبد، المحراب"},
    "life": {"en": "Life, living", "ur": "زندگی، حیات", "fa": "زندگی، حیات", "hi": "जीवन, ज़िंदगी", "ps": "ژوند، حيات", "ar": "الحياة"},
    "stone_rock": {"en": "Stone, rock; also the name Hajar", "ur": "پتھر، حجر", "fa": "سنگ، حجر", "hi": "पत्थर, शिला", "ps": "ډبره، تیږه", "ar": "الحجر، الصخر"},
    "hijra_emigration": {"en": "Emigration, migration, departure", "ur": "ہجرت، کوچ", "fa": "هجرت، کوچ", "hi": "हिजरत, प्रवास", "ps": "هجرت، کډوالي", "ar": "الهجرة، الرحيل"},
    "judge_arbiter": {"en": "Judge, arbiter, one who decides justly", "ur": "منصف، فیصلہ کرنے والا", "fa": "داور، حکم‌کننده", "hi": "न्यायकर्ता, फ़ैसला करने वाला", "ps": "قاضي، پریکړه کوونکی", "ar": "الحَكَم، القاضي، الحاكم"},
    "ruler_sovereign": {"en": "Ruler, sovereign (khagan, khan of khans)", "ur": "حاکم، بادشاہ، خان", "fa": "فرمانروا، شاه، خان", "hi": "शासक, सम्राट", "ps": "واکمن، پاچا", "ar": "الحاكم، الخاقان"},
    "wise_discerning": {"en": "Wise, discerning, all-wise", "ur": "دانا، حکیم، عقلمند", "fa": "دانا، حکیم، فرزانه", "hi": "बुद्धिमान, विवेकी", "ps": "حکیم، پوه", "ar": "الحكيم، العاقل"},
    "hagar_emigrant": {"en": "Hagar; she who emigrated, one who migrates", "ur": "ہاجرہ؛ ہجرت کرنے والی", "fa": "هاجر؛ مهاجرت‌کننده", "hi": "हाजिरा; प्रवास करने वाली", "ps": "هاجر؛ کډواله", "ar": "هاجر؛ المهاجرة"},
})

# slug: (ar, ur, fa, hi, ps, gloss_key, origin, gender, root, quranic, conf, note)
CUR = {
 "haadee": ("هادي", "ہادی", "هادی", "हादी", "هادي", "guide_leader", "Arabic", "Male",
            "Arabic root ه د ي (h-d-y); هادٍ (hādī)", True, "medium",
            "Haadee is Arabic هادي (Hādī) 'guide, one who guides aright', from the root ه د ي (h-d-y). The source glossed it 'delightful, beautiful, pleasing' — that belongs to a different root — and labelled it female; both were corrected. The word هادٍ appears in the Qur'an (e.g. 25:31) and al-Hādī is used of God."),
 "haadi": ("هادي", "ہادی", "هادی", "हादी", "هادي", "guide_leader", "Arabic", "Male",
           "Arabic root ه د ي (h-d-y); هادٍ (hādī)", True, "high",
           "Haadi is Arabic هادي (Hādī) 'guide, leader'. The source supplied only the Latin string 'Haadi' for the script columns; the correct script forms are given here. The gloss 'guide, leader' is correct."),
 "haadii": ("هادي", "ہادی", "هادی", "हादी", "هادي", "guide_leader", "Arabic", "Unisex",
            "Arabic root ه د ي (h-d-y); هادٍ (hādī)", True, "medium",
            "Haadii is a transliteration of Arabic هادي (Hādī) 'guide'. The source's own gloss 'delight, pleasure' is not the sense of this form (it was carried over from the unrelated هُدَى/هدية family); the guiding sense belongs to ه د ي. Same name as haadi and haadee."),
 "haadiya": ("هادية", "ہادیہ", "هادیه", "हादिया", "هادیه", "guide_leader", "Arabic", "Female",
             "Arabic root ه د ي (h-d-y); هادية (Hādiya)", True, "high",
             "Haadiya is Arabic هادية (Hādiya) 'she who guides, guide (feminine)', from the root ه د ي. The source gloss 'guiding to righteousness' is a fair rendering."),
 "haadiyah": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
              "Arabic root ه د ي (h-d-y); هدية (Hadiyya)", False, "high",
              "Haadiyah is Arabic هدية (Hadiyya) 'a gift, present', from the root ه د ي (the same root yields both 'guidance' and 'a gift'). The source gloss 'gift, present' is correct, but its Arabic column gave حَدِيَة, which is not the word; the correct form هدية is given here."),
 "haafiz": ("حافظ", "حافظ", "حافظ", "हाफ़िज़", "حافظ", "protector_guardian", "Arabic", "Male",
            "Arabic root ح ف ظ (ḥ-f-ẓ); حافظ (Ḥāfiẓ)", True, "high",
            "Haafiz is Arabic حافظ (Ḥāfiẓ) 'guardian, preserver, keeper', the active participle of the root ح ف ظ (ḥ-f-ẓ) 'to guard, preserve'. It is a divine name (al-Ḥafīẓ) and, in Muslim usage, the title of one who has memorised the whole Qur'an. The word حفيظ appears in the Qur'an (e.g. 12:64); the use as a title for a Qur'an-memoriser is a later usage, noted as such."),
 "haajar": ("هاجر", "ہاجرہ", "هاجر", "हाजिरा", "هاجر", "hagar_emigrant", "Arabic", "Female",
            "Arabic root ه ج ر (h-j-r); هاجر (Hājar)", False, "high",
            "Haajar is Arabic هاجر (Hājar), the name of Hagar, mother of Ismāʿīl — from the root ه ج ر 'to emigrate', so 'she who emigrated'. The source gloss 'the one who perseveres' reflects her story rather than the lexical sense. CRITICAL SOURCE ERROR: the source gave حجر ('stone') as the Persian form of this name."),
 "haaji": ("حاجي", "حاجی", "حاجی", "हाजी", "حاجي", "pilgrim", "Arabic", "Male",
           "Arabic root ح ج ج (ḥ-j-j); حاجّ (ḥājj)", False, "high",
           "Haaji is Arabic حاجّ / حاجي (Ḥājj) 'pilgrim, one who has performed the Hajj', from the root ح ج ج (ḥ-j-j). The word is not the same as حجر 'stone'. It is used as an acquired title after the pilgrimage and as an element of personal names."),
 "haala": ("هالة", "ہالہ", "هاله", "हाला", "هاله", "halo_aura", "Arabic", "Female",
           "Arabic root ه و ل (h-w-l); هالة (Hāla)", False, "high",
           "Haala is Arabic هالة (Hāla) 'a halo, a corona of light (especially around the moon), an aura' — a common Arabic feminine name. The source gloss 'blooming, flourishing' is unsupported; its Arabic column gave حلا which is a different word."),
 "haami": ("حامي", "حامی", "حامی", "हामी", "حامي", "protector_guardian", "Arabic", "Male",
           "Arabic root ح م ي (ḥ-m-y); حامٍ (ḥāmī)", False, "high",
           "Haami is Arabic حامي (Ḥāmī) 'protector, defender, one who guards', the active participle of the root ح م ي (ḥ-m-y). The source gloss 'helper' is close; 'protector' is the lexical sense."),
 "haani": ("هاني", "ہانی", "هانی", "हानी", "هاني", "pleasing_sweet", "Arabic", "Unisex",
           "Arabic root ه ن أ (h-n-ʾ); هانئ (Hāniʾ)", False, "high",
           "Haani is Arabic هانئ (Hāniʾ) 'happy, content; pleasant, wholesome', from the root ه ن أ (h-n-ʾ). The source gloss 'given by God' is unsupported and has been replaced with the lexical sense."),
 "haaris": ("حارث", "حارث", "حارث", "हारिस", "حارث", "guardian_haris", "Arabic", "Male",
            "Arabic root ح ر ث (ḥ-r-th); حارث (Ḥārith)", False, "medium",
            "Haaris corresponds to Arabic حارث (Ḥārith) 'tiller of the soil, cultivator; guardian, watcher' (compare حارس ḥāris 'guard, watchman'). The source record for this slug was empty and has been completed from the form itself. The two senses (cultivator / guardian) are both current; the name is recorded at medium confidence because of that overlap."),
 "haashim": (None, "ہاشم", "هاشم", "हाशिम", "هاشم", "hashim_crusher", "Arabic", "Male",
             "Arabic root ه ش م (h-sh-m); هاشم (Hāshim)", False, "high",
             "Haashim is Arabic هاشم (Hāshim), the byname of ʿAmr ibn ʿAbd Manāf, great-grandfather of the Prophet, and the ancestor of the Hāshimite clan. The traditional explanation is 'one who crushes bread for the people (during famine)', from the root ه ش م 'to crumble, break'. The source gloss 'destroyer of evil' is unsupported and has been replaced."),
 "haatim": ("حاتم", "حاتم", "حاتم", "हातिम", "حاتم", "generous_giver", "Arabic", "Male",
            "Arabic حاتم (Ḥātim); from the root ح ت م 'to decide'", False, "high",
            "Haatim is Arabic حاتم (Ḥātim). Its currency comes overwhelmingly from Ḥātim al-Ṭāʾī, the pre-Islamic Arab paragon of generosity, so that 'Ḥātim' functions almost as a byword for an open-handed giver. The source gloss 'the giver' reflects that association rather than a lexical meaning of the root (which means 'to judge, decide, make obligatory')."),
 "haaziq": ("حاذق", "حاذق", "حاذق", "हाज़िक़", "حاذق", "skilful_astute", "Arabic", "Male",
            "Arabic root ح ذ ق (ḥ-dh-q); حاذق (Ḥādhiq)", False, "high",
            "Haaziq is Arabic حاذق (Ḥādhiq) 'skilful, proficient, astute', from the root ح ذ ق (ḥ-dh-q). The source gloss 'seeker, questioner' belongs to a different root (س أ ل / ط ل ب) and has been replaced."),
 "habash": ("حبش", "حبش", "حبش", "हबश", "حبش", "abyssinian", "Arabic", "Male",
           "Arabic حبش (Ḥabash); nisba حبشي (Ḥabashī)", False, "high",
           "Habash is Arabic حبش (Ḥabash) 'Abyssinia' (Habasha, i.e. Ethiopia), used as a name and the base of the nisba حبشي 'Abyssinian'. The source gloss 'from Habasha (Abyssinian)' is correct. It is an ethnonym/nisba rather than a lexical given name."),
 "habat": ("حبة", "حبة", "حبه", "हब्बा", "حبه", "seed_grain", "Arabic", "Female",
           "Arabic root ح ب ب (ḥ-b-b); حبة (ḥabba)", False, "medium",
           "Habat corresponds to Arabic حبة (ḥabba) 'a single grain, a seed' — and, from the same root ح ب ب, 'a beloved one, a dear little thing' used as a term of endearment. The source gloss 'gift, blessing' is unsupported and has been replaced. The spelling habat reflects South Asian pronunciation of حبة."),
 "habeeb": ("حبيب", "حبیب", "حبیب", "हबीब", "حبيب", "beloved", "Arabic", "Male",
            "Arabic root ح ب ب (ḥ-b-b); حبيب (Ḥabīb)", False, "high",
            "Habeeb is Arabic حبيب (Ḥabīb) 'beloved, darling', from the root ح ب ب (ḥ-b-b). The source gloss 'beloved or loved one' is correct. It is the same name as habib in this batch."),
 "habeeba": ("حبيبة", "حبیبہ", "حبیبه", "हबीबा", "حبیبه", "beloved", "Arabic", "Female",
             "Arabic root ح ب ب (ḥ-b-b); حبيبة (Ḥabība)", False, "high",
             "Habeeba is Arabic حبيبة (Ḥabība) 'beloved (feminine)', the feminine of حبيب (Ḥabīb). The source gloss 'beloved' is correct. Same name as habiba, habibah, habibeh."),
 "habeel": ("هابيل", "ہابیل", "هابیل", "हाबील", "هابیل", "abel", "Arabic", "Male",
            "Arabic هابيل (Hābīl) < Hebrew הֶבֶל (Hevel)", False, "medium",
            "Habeel is the Arabic form هابيل (Hābīl) of the biblical name Abel, son of Adam. The name is Hebrew in ultimate origin and appears in Islamic tradition (Abel and Cain, the two sons of Adam); it is not itself the lexical sense 'powerful' that the source asserted. The source gave the Latin string 'Habeel' as the Urdu form."),
 "habib": ("حبيب", "حبیب", "حبیب", "हबीब", "حبيب", "beloved", "Arabic", "Male",
           "Arabic root ح ب ب (ḥ-b-b); حبيب (Ḥabīb)", False, "high",
           "Habib is Arabic حبيب (Ḥabīb) 'beloved'. The source record for this slug was empty and has been completed from the form itself. Same name as habeeb."),
 "habiba": ("حبيبة", "حبیبہ", "حبیبه", "हबीबा", "حبیبه", "beloved", "Arabic", "Female",
            "Arabic root ح ب ب (ḥ-b-b); حبيبة (Ḥabība)", False, "high",
            "Habiba is Arabic حبيبة (Ḥabība) 'beloved (feminine)'. The source record for this slug was empty and has been completed from the form itself. Same name as habeeba and habibah."),
 "habibah": ("حبيبة", "حبیبہ", "حبیبه", "हबीबा", "حبیبه", "beloved", "Arabic", "Female",
             "Arabic root ح ب ب (ḥ-b-b)", False, "high",
             "Habibah is a transliteration of Arabic حبيبة (Ḥabība) 'beloved'. The source gloss 'beloved' is correct."),
 "habibeh": ("حبيبة", "حبیبہ", "حبیبه", "हबीबा", "حبیبه", "beloved", "Arabic", "Female",
             "Arabic root ح ب ب (ḥ-b-b)", False, "high",
             "Habibeh is the Persian-influenced transliteration of Arabic حبيبة (Ḥabība) 'beloved one'. The source gloss 'beloved one' is correct."),
 "habil": ("هابيل", "ہابیل", "هابیل", "हाबील", "هابیل", "abel", "Arabic", "Male",
           "Arabic هابيل (Hābīl) < Hebrew הֶבֶל (Hevel)", False, "medium",
           "Habil is a transliteration of هابيل (Hābīl), the Arabic form of the name Abel. The source gloss claimed the sense 'Abel's brother' — in fact Hābīl IS Abel, and his brother is Qābīl (Cain); the gloss has been corrected. Same name as habeel."),
 "habis": (None, None, None, None, None, None, "Unknown", "Male",
           None, False, "unverified",
           "The source gave حبيس as the Arabic form and the gloss 'blessed'. حبيس (ḥabīs) means 'confined, imprisoned; a prisoner' — the opposite of 'blessed' — and is a lexical word rather than an attested personal name. No identification was established, so no gloss is asserted."),
 "habshah": ("حبشة", "حبشہ", "حبشه", "हबशा", "حبشه", "abyssinian_woman", "Arabic", "Female",
             "Arabic حبشة (Ḥabasha) 'Abyssinia'; feminine nisba حبشية", False, "medium",
             "Habshah is the Arabic name حبشة (Ḥabasha) for Abyssinia used as a feminine name — 'the Abyssinian woman'. The source gloss 'African woman' is a loose modern paraphrase of the same idea."),
 "hada": ("هدى", "ہدیٰ", "هدی", "हुदा", "هدی", "guide_leader", "Arabic", "Female",
          "Arabic root ه د ي (h-d-y); هدى (hudā)", True, "medium",
          "Hada corresponds to Arabic هدى (hudā) 'guidance, the right way' — a central Qur'anic term — used as a name (most visibly in the Turkish form Hüda). The source gloss 'gift, present' belongs to the related but distinct word هدية (hadiyya) and has been replaced."),
 "hadad": ("حداد", "حداد", "حداد", "हदाद", "حداد", "iron_smith", "Arabic", "Male",
           "Arabic root ح د د (ḥ-d-d); حدّاد (Ḥaddād)", False, "high",
           "Hadad is Arabic حدّاد (Ḥaddād) 'blacksmith, ironworker' (from حديد 'iron'). The source gloss 'thunder' belongs to the Semitic storm-god Hadad (a different, ancient Near-Eastern name) — a plausible confusion, but not the Arabic word; the 'smith' sense is recorded for this form. Same name as haddad."),
 "hadaf": ("هدف", "ہدف", "هدف", "हदफ़", "هدف", "goal_aim", "Arabic", "Unisex",
           "Arabic root ه د ف (h-d-f); هدف (hadaf)", False, "high",
           "Hadaf is Arabic هدف (hadaf) 'target, goal, aim'. The source gloss 'target, goal, aim' is correct. The source's '(Male or Female or Unisex)' gender string was normalised; its documented use is largely masculine."),
 "hadaya": ("هدايا", "ہدایا", "هدایا", "हदाया", "هدایا", "gift_grace", "Arabic", "Female",
            "Arabic root ه د ي (h-d-y); plural هدايا (hadāyā)", False, "high",
            "Hadaya is Arabic هدايا (hadāyā), the plural of هدية (hadiyya) 'gift' — 'gifts, presents'. The source's Arabic column gave the singular هداية; the plural form هدايا is the correct match for this spelling."),
 "haddad": ("حداد", "حداد", "حداد", "हदाद", "حداد", "smith", "Arabic", "Male",
          "Arabic root ح د د (ḥ-d-d); حدّاد (Ḥaddād)", False, "high",
          "Haddad is Arabic حدّاد (Ḥaddād) 'smith, blacksmith, craftsman'. The source gloss 'smith, craftsman' is correct. Same name as hadad."),
 "hadee": ("حادي", "حادی", "حادی", "हादी", "حادي", "guide_leader", "Arabic", "Male",
           "Arabic root ه د ي (h-d-y); هادٍ / حادي (hādī)", True, "medium",
           "Hadee is Arabic هادٍ (hādī) 'guide', written with the initial letter ح in South Asian usage (حادي — the form also used of someone who urges camels on with song). The source gloss 'guide, helper' is substantially correct. The word هادٍ occurs in the Qur'an (e.g. 25:31)."),
 "hadeel": ("هديل", "ہدیل", "هدیل", "हदील", "هدیل", "cooing_dove", "Arabic", "Female",
           "Arabic root ه د ل (h-d-l); هديل (Hadīl)", False, "high",
           "Hadeel is Arabic هديل (Hadīl) 'the cooing of a dove; a soft, melodious sound', used as a feminine name. The source gloss 'garden, blooming tree' is unsupported and has been replaced; its Arabic column gave حدير, a different word."),
 "hadeer": ("هدير", "ہدیر", "هدیر", "हदीर", "هدیر", "rumble_roar", "Arabic", "Female",
            "Arabic root ه د ر (h-d-r); هدير (Hadīr)", False, "high",
            "Hadeer is Arabic هدير (Hadīr) 'a rumbling, roaring sound — of water, of waves, of a crowd', from the root ه د ر. The source gloss 'garden, blooming tree' is unsupported and has been replaced; its Arabic column gave حدير, which is a different word."),
 "hadees": ("حديث", "حدیث", "حدیث", "हदीस", "حدیث", "narration_hadith", "Arabic", "Unisex",
            "Arabic root ح د ث (ḥ-d-th); حديث (ḥadīth)", False, "high",
            "Hadees is Arabic حديث (ḥadīth) 'a narration, report, account' — in Islamic usage the recorded sayings and actions of the Prophet. The source gloss 'guide, teacher, guide to the right path' is a loose extrapolation of that; the lexical sense is 'narration, report'."),
 "hadi": ("هادي", "ہادی", "هادی", "हादी", "هادي", "guide_leader", "Arabic", "Male",
          "Arabic root ه د ي (h-d-y); هادٍ (hādī)", True, "high",
          "Hadi is Arabic هادي (Hādī) 'guide'. The source record for this slug was empty and has been completed from the form itself. Same name as haadi, haadee, haadii, hadee."),
 "hadia": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
           "Arabic root ه د ي (h-d-y); هدية (hadiyya)", False, "high",
           "Hadia is a South Asian spelling of Arabic هدية (hadiyya) 'gift, present'. The source gloss 'guide, leader' belongs to the different word هادي (hādī, 'guide') and has been replaced with the gift sense, which is what هدية actually means. Same name as hadiyah, hadiah, hadiya, hadiyyah, hadya."),
 "hadiah": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
            "Arabic root ه د ي (h-d-y); هدية (hadiyya)", False, "high",
            "Hadiah is Arabic هدية (hadiyya) 'a gift'. The source gloss 'gift' is correct."),
 "hadid": ("حديد", "حدید", "حدید", "हदीद", "حديد", "iron", "Arabic", "Male",
           "Arabic root ح د د (ḥ-d-d); حديد (ḥadīd)", False, "high",
           "Hadid is Arabic حديد (ḥadīd) 'iron'; it is also the title of Surah 57 (al-Ḥadīd, 'Iron'). The source gloss 'iron, robust' captures the sense, 'robust' being an allusion to iron."),
 "hadil": ("هديل", "ہدیل", "هدیل", "हदील", "هدیل", "cooing_dove", "Arabic", "Female",
           "Arabic root ه د ل (h-d-l); هديل (Hadīl)", False, "high",
           "Hadil is a transliteration of Arabic هديل (Hadīl) 'the cooing of a dove; a gentle melodious sound'. The source gloss 'delicate, tender, agile' is an extrapolation of the dove image rather than the lexical meaning; same word as hadeel."),
 "hadir": ("حاضر", "حاضر", "حاضر", "हाज़िर", "حاضر", "present_attending", "Arabic", "Male",
           "Arabic root ح ض ر (ḥ-ḍ-r); حاضر (ḥāḍir)", False, "high",
           "Hadir is Arabic حاضر (ḥāḍir) 'present, attending, at hand', the active participle of the root ح ض ر. The source gloss 'present, presence' is substantially correct, though its Arabic column gave هادِر (a different word). The source recorded it as feminine; the form is grammatically masculine and its documented name use is male."),
 "hadis": ("حديث", "حدیث", "حدیث", "हदीस", "حدیث", "narration_hadith", "Arabic", "Unisex",
           "Arabic root ح د ث (ḥ-d-th); حديث (ḥadīth)", False, "high",
           "Hadis is a transliteration of Arabic حديث (ḥadīth) 'narration, report; a hadith' — the same word as hadees. The source gloss 'story teller, speaker' describes a person, not the word; the lexical sense is 'narration'."),
 "hadiya": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
            "Arabic root ه د ي (h-d-y); هدية (hadiyya)", False, "high",
            "Hadiya is Arabic هدية (hadiyya) 'gift, present, reward'. The source gloss 'gift, reward' is correct. The source's Arabic column spelled it هديه (a Persian-style spelling); the standard form is هدية."),
 "hadiyah": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
             "Arabic root ه د ي (h-d-y); هدية (hadiyya)", False, "high",
             "Hadiyah is Arabic هدية (hadiyya) 'a gift'. The source record for this slug was empty and has been completed from the form itself."),
 "hadiyyah": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
              "Arabic root ه د ي (h-d-y); هدية (hadiyya)", False, "high",
              "Hadiyyah is the full transliteration of Arabic هدية (hadiyya) 'gift'. The source gloss 'gift' is correct."),
 "hadjara": (None, None, None, None, None, None, "Unknown", "Female",
             None, False, "unverified",
             "The source gave هجرة (hijra, 'emigration') as the Arabic form and the gloss 'traveller, pilgrim', together with the Urdu form هاجرة. The letters do not correspond to a single attested name: هجرة is the noun 'emigration' and هاجرة is a different word. Because the identification is genuinely uncertain, no form or gloss is asserted; only reported female use of the spelling is retained. Compare hajra/hajrah, which ARE recorded as هجرة."),
 "hadya": ("هدية", "ہدیہ", "هدیه", "हदिया", "هدیه", "gift_grace", "Arabic", "Female",
           "Arabic root ه د ي (h-d-y); هدية (hadiyya)", False, "high",
           "Hadya is Arabic هدية (hadiyya) 'gift'. The source supplied only the Latin string 'Hadya' for the script columns; the correct script form is given here. Same name as hadia, hadiya, hadiyah."),
 "hafa": (None, "حفا", "حفا", None, "حفا", "barefoot_hospitality", "Arabic", "Female",
          "Arabic root ح ف و (ḥ-f-w); حافي (ḥāfī) 'barefoot'", False, "low",
          "Hafa relates to the Arabic root ح ف و: حافي 'barefoot', and the classical Arab virtue of honouring 'the barefoot guest'. The source gloss 'gentle wind' is unsupported (that sense belongs to a different word) and its Arabic column gave هفى; the form is recorded at low confidence."),
 "hafeel": ("حافل", "حافل", "حافل", "हाफ़िल", "حافل", "abounding_full", "Arabic", "Male",
            "Arabic root ح ف ل (ḥ-f-l); حافل (ḥāfil)", False, "low",
            "Hafeel corresponds to Arabic حافل (ḥāfil) 'abounding, full, crowded; a large gathering'. The source gloss 'protector, guardian' belongs to a different root (ح ف ظ) and is not supported; the 'abounding/full' reading is recorded at low confidence, since the word is not common as a personal name. The source supplied only the Latin string 'Hafeel' for the Urdu column."),
 "hafeez": ("حفيظ", "حفیظ", "حفیظ", "हफ़ीज़", "حفيظ", "protector_guardian", "Arabic", "Male",
            "Arabic root ح ف ظ (ḥ-f-ẓ); حفيظ (Ḥafīẓ)", True, "high",
            "Hafeez is Arabic حفيظ (Ḥafīẓ) 'guardian, preserver' — an intensive form of the root ح ف ظ and a divine name (al-Ḥafīẓ). The word appears in the Qur'an (12:64: 'فَاللَّهُ خَيْرٌ حَافِظًا'). The source gloss 'guardian, custodian' is correct."),
 "hafeeza": ("حفيظة", "حفیظہ", "حفیظه", "हफ़ीज़ा", "حفیظه", "protector_guardian", "Arabic", "Female",
             "Arabic root ح ف ظ (ḥ-f-ẓ); حفيظة (Ḥafīẓa)", True, "high",
             "Hafeeza is Arabic حفيظة (Ḥafīẓa) 'she who guards, preserves (feminine of Ḥafīẓ)'. The source gloss 'memorizer of the Qur'an' describes the bearer of the masculine title ḥāfiẓ rather than the lexical sense; the 'guardian/preserver' sense is the lexical one and the Qur'an-memoriser association is noted as usage. هفيظة (the source's spelling) was corrected to حفيظة."),
 "hafeezah": ("حفيظة", "حفیظہ", "حفیظه", "हफ़ीज़ा", "حفیظه", "protector_guardian", "Arabic", "Female",
              "Arabic root ح ف ظ (ḥ-f-ẓ); حفيظة (Ḥafīẓa)", True, "high",
              "Hafeezah is Arabic حفيظة (Ḥafīẓa) 'guardian, preserver (feminine)'. The source gloss 'protector, preserver' is correct."),
 "hafi": ("حفي", "حفی", "حفی", "हफ़ी", "حفي", "gracious_solicitous", "Arabic", "Male",
          "Arabic root ح ف و (ḥ-f-w); حفيّ (Ḥafiyy)", False, "medium",
          "Hafi is Arabic حفيّ (Ḥafiyy) 'gracious, kindly, solicitous (about someone's welfare)'. The source gloss 'keeper, guardian' belongs to a different root (ح ف ظ) and has been replaced. The source's '(Male)' string was normalised."),
 "hafid": ("حافد", "حافد", "حافد", "हाफ़िद", "حافد", "serving_aiding", "Arabic", "Male",
           "Arabic root ح ف د (ḥ-f-d); حافد (Ḥāfid)", False, "low",
           "Hafid corresponds to Arabic حافد (ḥāfid), active participle of ح ف د 'to serve, to hasten to help'. The source gloss 'wise, knowledgeable' belongs to a different root (ع ل م / ح ك م) and is not supported; the 'serving, aiding' reading is recorded at low confidence because the word is rare as a personal name."),
 "hafida": ("حفيدة", "حفیدہ", "حفیده", "हफ़ीदा", "حفیده", "granddaughter", "Arabic", "Female",
            "Arabic root ح ف د (ḥ-f-d); حفيدة (ḥafīda)", False, "low",
            "Hafida most plausibly corresponds to Arabic حفيدة (ḥafīda) 'granddaughter' — a common term of affection used as a name. The source gave هافدة and glossed it 'preserver, protector, guardian' (which belongs to ح ف ظ); the granddaughter reading is recorded at low confidence, with the caveat that حفيظة (cf. hafeeza) is the 'guardian' word."),
 "hafifah": ("حفيفة", "حفیفہ", "حفیفه", "हफ़ीफ़ा", "حفیفه", "light_gentle_rustle", "Arabic", "Female",
             "Arabic root ح ف ف (ḥ-f-f); حفيف (ḥafīf) 'rustle'", False, "medium",
             "Hafifah relates to Arabic حفيف (ḥafīf) 'the rustle of leaves, a light swishing sound' — حفيفة 'light, delicate'. The source gave هفيقة and glossed it 'graceful, delicate'; the 'light/delicate' core is retained while the source's Arabic spelling was corrected. Recorded at medium confidence."),
 "hafiz": ("حافظ", "حافظ", "حافظ", "हाफ़िज़", "حافظ", "protector_guardian", "Arabic", "Male",
           "Arabic root ح ف ظ (ḥ-f-ẓ); حافظ (Ḥāfiẓ)", True, "high",
           "Hafiz is Arabic حافظ (Ḥāfiẓ) 'guardian, preserver' — and, in Muslim usage, the title of one who has memorised the entire Qur'an. The source gloss 'memorizer' reflects that usage; the lexical sense is 'guardian, preserver'. The word حفيظ appears in the Qur'an (12:64)."),
 "hafiza": ("حفيظة", "حفیظہ", "حفیظه", "हफ़ीज़ा", "حفیظه", "protector_guardian", "Arabic", "Female",
            "Arabic root ح ف ظ (ḥ-f-ẓ); حفيظة (Ḥafīẓa)", True, "high",
            "Hafiza is Arabic حفيظة (Ḥafīẓa) 'guardian, preserver (feminine)'. The source record for this slug was empty and has been completed from the form itself."),
 "hafizah": ("حفيظة", "حفیظہ", "حفیظه", "हफ़ीज़ा", "حفیظه", "protector_guardian", "Arabic", "Female",
             "Arabic root ح ف ظ (ḥ-f-ẓ); حفيظة (Ḥafīẓa)", True, "high",
             "Hafizah is Arabic حفيظة (Ḥafīẓa) 'guardian, preserver (feminine)'. The source gloss 'guardian of the Quran' mixes the lexical sense with the usage title; both are recorded."),
 "hafizh": ("حفيظ", "حفیظ", "حفیظ", "हफ़ीज़", "حفيظ", "protector_guardian", "Arabic", "Male",
            "Arabic root ح ف ظ (ḥ-f-ẓ); حفيظ (Ḥafīẓ)", True, "high",
            "Hafizh is a spelling variant of Arabic حفيظ (Ḥafīẓ) 'guardian, preserver'. The source gloss 'memory keeper, memorizer' reflects the ḥāfiẓ title; the lexical sense is 'guardian'."),
 "hafs": ("حفص", "حفص", "حفص", "हफ़्स", "حفص", None, "Arabic", "Male",
          "Arabic حفص (Ḥafṣ) — a personal name, further etymology uncertain", False, "low",
          "Hafs (حفص) is the name of a well-known early authority, Ḥafṣ ibn ʿUmar. Its etymology is not securely established: the source gloss 'preserver, guardian' belongs to ح ف ظ, a different root. No gloss is asserted; the name is recorded as an attested Arabic personal name at low confidence."),
 "hafsa": ("حفصة", "حفصہ", "حفصه", "हफ़्सा", "حفصه", "lioness_cub", "Arabic", "Female",
          "Arabic حفصة (Ḥafṣa) — traditionally connected with 'young lioness'", False, "high",
          "Hafsa (حفصة) is a prominent Arabic feminine name, borne by Ḥafṣa bint ʿUmar, a wife of the Prophet. It is traditionally glossed 'young lioness' (compare the lion-name family). The source record for this slug was empty and has been completed from the form itself."),
 "hafsah": ("حفصة", "حفصہ", "حفصه", "हफ़्सा", "حفصه", "lioness_cub", "Arabic", "Female",
            "Arabic حفصة (Ḥafṣa); traditionally 'young lioness'", False, "high",
            "Hafsah is the fuller transliteration of حفصة (Ḥafṣa), traditionally 'young lioness'. The source gloss 'young lioness' is correct. Same name as hafsa."),
 "hafza": ("حافظة", "حافظہ", "حافظه", "हाफ़िज़ा", "حافظه", "protector_guardian", "Arabic", "Female",
           "Arabic root ح ف ظ (ḥ-f-ẓ); حافظة (Ḥāfiẓa)", True, "medium",
           "Hafza corresponds to Arabic حافظة (Ḥāfiẓa) — the feminine active participle of ح ف ظ, 'she who guards, preserves, remembers'. The source gloss 'preserver, memorizer' is defensible in that sense."),
 "hagir": ("هاجر", "ہاجر", "هاجر", "हाजिर", "هاجر", "hagar_emigrant", "Arabic", "Female",
           "Arabic root ه ج ر (h-j-r); هاجر (Hājar)", False, "high",
           "Hagir is a spelling variant of هاجر (Hājar), the Arabic form of Hagar — 'she who emigrated'. The source gloss 'patient, enduring' reflects her story, not the lexical sense. Same name as haajar, hajir, hajira."),
 "hahah": (None, None, None, None, None, None, "Unknown", "Unknown",
           None, False, "unverified",
           "NOT A NAME: hahah is recorded in the source with the Arabic form حاحاه and the gloss 'laughter'. It is an onomatopoeic rendering of laughing, not an attested Arabic personal name in any Tier-A/B source. It is retained with no gloss and no origin because it appears in the source list; it should be treated as junk data."),
 "haibat": ("هيبة", "ہیبت", "هیبت", "हैबत", "هيبت", "awe_dignity", "Arabic", "Female",
            "Arabic root ه ي ب (h-y-b); هيبة (hayba)", False, "high",
            "Haibat is Arabic هيبة (hayba) 'awe, dignity, majesty, reverential fear' — an abstract noun used as a name. The source gloss 'protected, beloved' is unsupported and has been replaced."),
 "haida": ("هادية", "ہادیہ", "هادیه", "हादिया", "هادیه", "guide_leader", "Arabic", "Female",
           "Arabic root ه د ي (h-d-y); هادية (Hādiya)", True, "medium",
           "Haida is best identified with هادية (Hādiya) 'she who guides'. The source's gloss 'guide, helper, companion' and its Arabic column (هادية) support that reading, but the spelling 'haida' could equally reflect a contraction of other forms, so it is recorded at medium confidence."),
 "haidar": ("حيدر", "حیدر", "حیدر", "हैदर", "حيدر", "lion_brave", "Arabic", "Male",
            "Arabic حيدر (Ḥaydar) 'lion'", False, "high",
            "Haidar (حيدر) is an Arabic name meaning 'lion' — famously borne as a title of ʿAlī ibn Abī Ṭālib. The source gloss 'the lion' is correct. The source's Arabic column gave هيْدر, a spelling variant of the same name. Same name as haider."),
 "haidarah": (None, None, None, None, None, None, "Unknown", "Female",
              None, False, "unverified",
              "The source gave هادرة as the Arabic form and the gloss 'the one who makes the way clear'. هادرة is not an attested name or lexical item of that shape, and the gloss is uncorroborated. No identification was established, so no form or gloss is asserted."),
 "haidari": ("حيدري", "حیدری", "حیدری", "हैदरी", "حيدري", "of_haidar", "Arabic", "Male",
             "Arabic nisba of حيدر (Ḥaydar)", False, "high",
             "Haidari is the nisba (relational) form of حيدر (Ḥaydar) 'lion' — 'leonine, of Ḥaydar'. The source gloss 'gardener, gardener's helper' is unsupported (it may confuse it with the unrelated Persian گلکار) and has been replaced."),
 "haider": ("حيدر", "حیدر", "حیدر", "हैदर", "حيدر", "lion_brave", "Arabic", "Male",
            "Arabic حيدر (Ḥaydar) 'lion'", False, "high",
            "Haider is Arabic حيدر (Ḥaydar) 'lion, brave, courageous'. The source gloss 'lion, brave, courageous' is correct."),
 "haif": (None, None, None, None, None, None, "Unknown", "Unisex",
          None, False, "unverified",
          "The source gave حيف as the Arabic form and the gloss 'riverbank'. حيف (ḥayf) actually means 'injustice, iniquity' — not 'riverbank' — and is not attested as a personal name. Since the source's gloss is wrong and the word is a poor naming candidate, no gloss is asserted."),
 "haifa": ("حيفا", "حیفہ", "حیفا", "हैफ़ा", "حیفا", "haifa_city", "Arabic", "Female",
           "Arabic حيفا (Ḥayfā) — the coastal city", False, "medium",
           "Haifa is the Arabic name حيفا of the coastal city (Hebrew חֵיפָה). As a given name it recalls the city rather than a lexical root; the source gloss 'gardens' is unsupported and has been replaced. Some relate the place-name to حفا 'barefoot' or to the root ح ي ف 'to be slender', but neither is settled."),
 "haikal": ("هيكل", "ہیکل", "هیکل", "हैकल", "هيكل", "temple_sanctuary", "Arabic", "Male",
            "Arabic هيكل (haykal) 'temple, sanctuary; structure'", False, "high",
            "Haikal is Arabic هيكل (haykal) 'temple, sanctuary, shrine; a large structure'. The source gloss 'temple, sanctuary' is correct. The source's '(Male)' string was normalised."),
 "haimi": (None, None, None, None, None, "life", "Hebrew", "Unisex",
           "Hebrew חַיִּים (Ḥayyīm) 'life'; diminutive/variant Haimi", False, "medium",
           "Haimi is best explained as a form of the Hebrew name חַיִּים (Ḥayyīm / Chaim) 'life', cognate with Arabic حياة (ḥayāh). CRITICAL SOURCE ERROR: the record's Arabic column gave أحمد ('Ahmad'), and the gloss 'fragrant' is unsupported. A separate tradition reports 'Haimi' as a Nepali name meaning 'golden'; that is a different, unrelated name. Because the dataset carries both Arabic and Hebrew in its language column, this is recorded as the Hebrew 'life' name at medium confidence."),
 "haiqa": (None, None, None, None, None, None, "Unknown", "Female",
           None, False, "unverified",
           "The source gave حيقة as the Arabic form and the gloss 'gathering, assembly, congregation'. No Tier-A/B source establishes حيقة as a word or name with that meaning. No identification was established, so no gloss is asserted."),
 "hair": (None, None, None, None, None, None, "Unknown", "Unknown",
          None, False, "unverified",
          "NOT A NAME: the source lists 'hair' with the Arabic column شعر ('hair, poetry') and the Urdu column بال ('hair') — i.e. the English common noun, not a name. No personal name of this form is attested; nothing is asserted."),
 "haiza": (None, None, None, None, None, None, "Unknown", "Female",
           None, False, "unverified",
           "No reliable identification was established for haiza. Name directories give mutually inconsistent glosses ('royalty', 'gift of Allah'), and the one Arabic word of this shape in common use, حائض/حائضة, means 'a menstruating woman' — which no directory intends. Because the sources conflict and none is authoritative, no script form or gloss is asserted; only reported female usage is retained."),
 "hajar": ("حجر", "حجر", "حجر", "हजर", "حجر", "stone_rock", "Arabic", "Female",
           "Arabic root ح ج ر (ḥ-j-r); حجر (ḥajar) 'stone'", False, "medium",
           "Hajar is Arabic حجر (ḥajar) 'a stone, rock'. It is also a spelling of the name of Hagar (usually هاجر, Hājar) — the two are distinct words, and the earlier slug haajar covers the Hājar form. The source record for this slug was empty and has been completed from the form itself; the 'stone/rock' sense is the lexical one for حجر."),
 "hajarah": ("حجرة", "حجرہ", "حجره", "हजरा", "حجره", "stone_rock", "Arabic", "Female",
             "Arabic root ح ج ر (ḥ-j-r); حجرة (ḥujra) 'room, chamber'", False, "medium",
             "Hajarah corresponds to Arabic حجرة (ḥujra) 'a room, chamber' (also حَجَرة 'a stone'). The source gloss 'stone, rock' is consistent with the حجر root. Because the vocalisation is ambiguous between 'stone' and 'room', it is recorded at medium confidence."),
 "haji": ("حاجي", "حاجی", "حاجی", "हाजी", "حاجي", "pilgrim", "Arabic", "Male",
          "Arabic root ح ج ج (ḥ-j-j); حاجّ (ḥājj)", False, "high",
          "Haji is Arabic حاجّ / حاجي (Ḥājj) 'one who has performed the Hajj' — a title of respect that has become a given name. The source gloss 'traveller' is a loose rendering; the pilgrimage sense is the specific one."),
 "hajib": ("حاجب", "حاجب", "حاجب", "हाजिब", "حاجب", "protector_guardian", "Arabic", "Male",
           "Arabic root ح ج ب (ḥ-j-b); حاجب (ḥājib)", False, "high",
           "Hajib is Arabic حاجب (ḥājib) 'a doorkeeper, chamberlain, guardian; also the eyebrow' (from ح ج ب 'to screen, veil'). The source gloss 'guardian or protector' is a reasonable rendering of the chamberlain/guardian sense."),
 "hajiba": (None, None, None, None, None, None, "Unknown", "Female",
            None, False, "unverified",
            "The source gave حاجبة as the Arabic form and the gloss 'servant of God'. حاجبة is not an attested name, and 'servant of God' (عبد الله / أمة الله) belongs to an entirely different construction. No identification was established, so no gloss is asserted."),
 "hajidah": (None, None, None, None, None, None, "Unknown", "Female",
             None, False, "unverified",
             "The source gave حاجدة as the Arabic form and the gloss 'successful one'. No such Arabic word or name is established, and the gloss belongs to the different root ف و ز / ن ج ح. No identification was established, so no gloss is asserted."),
 "hajir": ("حاجر", "حاجر", "حاجر", "हाजिर", "حاجر", "hagar_emigrant", "Arabic", "Male",
           "Arabic root ه ج ر (h-j-r); هاجر (Hājar) / حاجر", False, "medium",
           "Hajir is recorded as a variant of هاجر (Hājar) 'she who emigrated', used as a male name. The source gloss 'migrator to the righteous path' is a religious gloss on the same root sense. Recorded at medium confidence because the spelling حاجر (with ح) can also belong to the root ح ج ر 'to prevent'."),
 "hajira": ("هاجرة", "ہاجرہ", "هاجره", "हाजिरा", "هاجره", "hagar_emigrant", "Arabic", "Female",
            "Arabic root ه ج ر (h-j-r); هاجرة (hājira)", False, "high",
            "Hajira is the feminine form هاجرة (hājira) from the root ه ج ر 'to emigrate' — 'she who emigrates; one who has made the Hijra'. The source gloss 'emigrant or companion' captures the sense. Same name family as haajar, hagir, hajir."),
 "hajiyah": ("حاجية", "حاجیہ", "حاجیه", "हाजिया", "حاجیه", "pilgrim", "Arabic", "Female",
             "Arabic root ح ج ج (ḥ-j-j); حاجية (ḥājiya)", False, "high",
             "Hajiyah is the feminine of حاجّ — حاجية (ḥājiya) 'a woman who has performed the Hajj'. The source gloss 'pilgrim, traveler' is a fair rendering."),
 "hajja": ("حجة", "حجہ", "حجه", "हज्जा", "حجه", "pilgrim", "Arabic", "Female",
           "Arabic root ح ج ج (ḥ-j-j); حاجة / حاجّة (ḥājja)", False, "medium",
           "Hajja is the colloquial feminine of حاجّ — a woman who has performed the Hajj (also frequently written حاجة). The source gave the form حجة, which is really the noun 'a ḥujja (proof, argument)'; the intended sense is the pilgrim title."),
 "hajjah": ("حاجة", "حاجہ", "حاجه", "हज्जा", "حاجه", "pilgrim", "Arabic", "Female",
            "Arabic root ح ج ج (ḥ-j-j); حاجّة (ḥājja)", False, "medium",
            "Hajjah is the feminine pilgrim title حاجّة (ḥājja) 'she who has performed the Hajj'. The source gave حجة, which is the different noun 'proof, argument'; corrected here. Same usage as hajja."),
 "hajjaj": ("حجاج", "حجاج", "حجاج", "हज्जाज", "حجاج", "pilgrims", "Arabic", "Male",
            "Arabic root ح ج ج (ḥ-j-j); plural حُجّاج (ḥujjāj)", False, "medium",
            "Hajjaj is Arabic حُجّاج (ḥujjāj), the plural of حاجّ 'pilgrim' — 'pilgrims'. The source gloss 'pilgrim' is a reasonable rendering of the singular sense, but the form is plural. It is also well known as the name of al-Ḥajjāj ibn Yūsuf (a different vocalisation, Ḥajjāj, an intensive 'much-performing-the-Hajj' form)."),
 "hajna": (None, None, None, None, None, None, "Unknown", "Female",
           None, False, "unverified",
           "The source gave هاجنة as the Arabic form and the gloss 'graceful'. No such word or name is established in Arabic. No identification was established, so no gloss is asserted."),
 "hajra": ("هجرة", "ہجرہ", "هجره", "हिजरा", "هجره", "hijra_emigration", "Arabic", "Female",
           "Arabic root ه ج ر (h-j-r); هجرة (hijra)", False, "high",
           "Hajra is Arabic هجرة (hijra) 'emigration, departure' — in Islamic history, the migration of the Prophet from Mecca to Medina. Used as a feminine name. The source gloss 'departure or emigration' is correct; its Arabic column gave حجرا, which was corrected to هجرة."),
 "hajrah": ("هجرة", "ہجرہ", "هجره", "हिजरा", "هجره", "hijra_emigration", "Arabic", "Female",
            "Arabic root ه ج ر (h-j-r); هجرة (hijra)", False, "high",
            "Hajrah is Arabic هجرة (hijra) 'emigration'. The source gloss \"a pilgrim's stone\" appears to be a mistaken reading of حجر 'stone' rather than هجر 'emigration'; the 'emigration' sense is recorded as the correct one for هجرة."),
 "hajrat": (None, None, None, None, None, None, "Unknown", "Female",
            None, False, "unverified",
            "The source gave حجرت as the Arabic form and the gloss 'respected one'. No such Arabic form is established (the honorific حَضْرَة is unrelated, and حجرة means 'room'). No identification was established, so no gloss is asserted."),
 "hakam": ("حَكَم", "حکم", "حکم", "हकम", "حکم", "judge_arbiter", "Arabic", "Male",
           "Arabic root ح ك م (ḥ-k-m); حَكَم (ḥakam)", True, "high",
           "Hakam is Arabic حَكَم (ḥakam) 'a judge, arbiter, one who decides'; the root ح ك م 'to judge, decide' is central to the Qur'anic vocabulary. The source gloss 'just judge' is defensible."),
 "hakan": ("hakan", "ہاکان", "هاکان", "हाकान", "هاکان", "ruler_sovereign", "Turkish", "Male",
           "Turkish Hakan < Old Turkic qaɣan (khagan) 'supreme ruler'", False, "high",
           "Hakan is a Turkish male name — the Turkish reflex of the Old Turkic title qaɣan (khagan), 'supreme ruler, khan of khans', used in the Ottoman imperial style. CRITICAL SOURCE ERROR: the record labels it 'Arabic' (its own language column says Turkish) and gives حاكان as the Arabic form; the name is Turkic, not Arabic. The source gloss 'brave, strong, powerful' is not the etymological sense."),
 "hakeem": ("حكيم", "حکیم", "حکیم", "हकीम", "حكيم", "wise_discerning", "Arabic", "Male",
            "Arabic root ح ك م (ḥ-k-m); حكيم (Ḥakīm)", True, "high",
            "Hakeem is Arabic حكيم (Ḥakīm) 'wise, discerning; all-wise' — an intensive adjective from the root ح ك م and one of the divine names (al-Ḥakīm). The source gloss 'all-knowing' is close but should be 'all-wise' (the 'all-knowing' name is al-ʿAlīm, a different word). Hakeem is also used in South Asia for a physician."),
 "hakeema": ("حكيمة", "حکیمہ", "حکیمه", "हकीमा", "حكيمه", "wise_discerning", "Arabic", "Female",
             "Arabic root ح ك م (ḥ-k-m); حكيمة (Ḥakīma)", True, "high",
             "Hakeema is Arabic حكيمة (Ḥakīma) 'wise, discerning (feminine of Ḥakīm)'. The source gloss 'wise, intelligent' is correct, though its Arabic column gave هكيمة, which was corrected to حكيمة."),
}
