# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 51 (rafah..raki).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": rafan -> Latin "Rafan"; raghd -> علي;
   ragheed -> Latin "Raghib"; rahaa -> Latin "Rahaa"; rahal -> Latin "Rahal";
   rahm -> Latin "Rahm"; raji -> Latin "Raji"; rajwa -> Latin "Rajwa";
   raki -> Latin "Raki"; raghd -> علي; rajah -> علي; rafayet -> أحمد;
   rafraf -> أحمد; raid -> رعد; rafeh -> رفح; rafi -> رَفِي; rafid -> رَفِيظ;
   rafik -> رافك; rafiya -> رفيا; raghid -> راغد; rahi -> رحى; rahid -> راحد;
   rahik -> رحيك; rahmi -> رحمي; rai -> رائي; raida -> رايدة; raiha -> ريحا;
   raika -> رايكا; raima -> ريماء; raimah -> رائم ة; raiq -> رائق;
   rais -> رائس; raisa -> رايسة; raisah -> رائس ة; raisha -> رايشة;
   raiya -> راية; raiyan -> ريان; raja -> راجا; rajaa -> رَجَاء;
   rajeh -> راجح; rajiya -> راجية; rakan -> راكان; rakeeb -> رقيب;
   rakeem -> رکیم (Persian kaf); rafah -> رَفَاح; rafaqat -> رفاقة;
   rafat -> رفات; rafee -> رفيع; rafeek -> رفيق; rafeq -> رفيق;
   rafia -> رافية; rafiah -> رافية; rafidah -> رَافِدَة; rafif -> رفيف;
   rafiq -> رَفِيق; rafiqah -> رفيقه; rafique -> رفيق; raghad -> رغد;
   raghda -> رغدة; raghdah -> رغدة; ragheb -> راغب; raghib -> راغب;
   raha -> رها; rahana -> راهانة; rahat -> راحة; rahbar -> رهبر;
   raheel -> رحيل; raheela -> راحيلة; raheema -> رحيمة; raheemah -> رحيمة;
   raheesh -> راهيش; rahema -> رحمة; rahf -> رَهف; rahib -> راهب;
   rahil -> رحيل; rahila -> راحيلة; rahim -> رحيم; rahima -> رحيمة;
   rahimaa -> رحيمة; rahimah -> رحيمة; rahime -> رحيمة; rahmaa -> رحمة;
   rahmah -> رحمة; rahman -> رحمن; rahmat -> رَحْمَة; rahmath -> رحمة.
 * EMPTY STUBS (8-key records, no data): rafay, rahaf, raheem, rahma.
 * MISLABELLED ORIGIN: rahbar (Persian), raha (Persian), raghid (Arabic),
   rai (Arabic), raja (Sanskrit/Hindi), raki (Turkish/Greek).
 * DEGARBLED GLOSSES: rafah "Soft and gentle", rafan "Noble, exalted one",
   rafaqat "Pious, God-fearing", rafat "Exalted, Lofty", rafayet "Rain Giver",
   rafee "Elevated, Exalted", rafeek "Healer", rafeeq "Kind and Compassionate",
   rafeh "Healing, Compassionate", rafeq "Friend, Companion",
   rafi "Exalted, Elevated", rafia "Garden of God", rafiah "Compassionate, Merciful",
   rafid "One who is concealed or hidden", rafidah "Pious, Devout",
   rafif "Rare, precious", rafik "Friend, companion", rafiq "Friend, Companion",
   rafiqah "Friend, Companion", rafique "Graceful", rafiya "Exalted One",
   rafraf "Rain, Thunder", ragab "Young Goat", raghad "blossom, flower",
   raghd "Contentment, Satisfaction, Joy", raghda "Contentment, Satisfaction",
   raghdah "Tender Mercy", ragheb "Melodic, Singer", ragheed "Regard, Prestige, Pride",
   raghib "Desiring or longing for", raghid "Traveler", raha "Content, Happy, Joyful",
   rahaa "Contentment, Satisfaction", rahal "Traveler", raham "Most Merciful",
   rahana "joyful, content, satisfied", rahat "Comfort, Ease", rahbar "Guide, Leader",
   raheel "Companion of the Prophet", raheela "Path, Way", raheema "Merciful",
   raheemah "Compassionate", raheesh "Shepherd", rahema "Merciful One",
   rahf "Gentle Rain", rahi "Traveler", rahib "One who is merciful",
   rahid "Liberator, Free", rahik "Traveler, Wayfarer", rahil "Traveler, Nomad",
   rahila "Traveler", rahim "Compassionate, Merciful, Loving", rahima "Merciful, Compassionate",
   rahimaa "Merciful One", rahimah "Compassionate and Merciful", rahime "Compassionate",
   rahm "Mercy, Compassion, Womb", rahmaa "Grace, Compassion", rahmah "Mercy",
   rahman "Compassionate, Merciful", rahmat "Mercy, Compassion",
   rahmath "Mercy, Compassion", rahmi "Mercy, compassion", rai "Sun, Light",
   raid "Thunder", raida "Rider, Traveler", raidah "Journey, Travel",
   raif "Joy, gladness, pleasure", raifa "Little one", raiha "Gentle, kind, beautiful",
   raihaan "Gardener of Paradise", raihan "Fragrant, Sweet-Smelling",
   raihana "Garden of Paradise", raihanah "Fragrance of Paradise",
   raika "Little Princess", raima "Gentle, delicate, beautiful", raimah "Garden",
   raiq "thunderbolt", rais "Master, Leader", raisa "Garden", raisah "Gentle",
   raisha "Little Princess", raiya "Hopeful guardian", raiyan "Gazer",
   raja "ruler, king", rajaa "The One who is Returned",
   rajab "Seventh month of the Islamic calendar", rajah "King, Ruler",
   rajeh "Victorious", raji "Content, Satisfied", rajiya "Gentle",
   rajwa "Little Rain", rakan "Helper", rakeeb "Protector, Defender",
   rakeem "Strong, capable", raki "Contentment, happiness".
 * GENDER ERRORS: rafah, rafat, rahat, raheel, rahi, rahil, rahm, rahmat, rahmi,
   rai, raid, raja, raji, raki were labelled unisex where documented usage is
   male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated50 import GLOSSES as _G50

GLOSSES = dict(_G50)
GLOSSES.update({
    "rafah": {"en": "Rafah; a female given name", "ur": "رفاح (زنانہ نام)", "fa": "رفاح (نام زنانه)", "hi": "रफ़ाह (स्त्री नाम)", "ps": "رفاح (ښځينه نوم)", "ar": "رَفَاح (اسْم عَلَم مُؤَنَّث)"},
    "rafan": {"en": "Rafan; a male given name", "ur": "رفان (مردانہ نام)", "fa": "رفان (نام مردانه)", "hi": "रफ़ान (पुरुष नाम)", "ps": "رفان (نر نوم)", "ar": "رَفَان (اسْم عَلَم مُذَكَّر)"},
    "rafaqat": {"en": "Rafaqat; companionship, fellowship", "ur": "رفاقت، دوستی، ساتھ", "fa": "رفاقت، همراهی", "hi": "रफ़ाक़त, साथ", "ps": "رفاقت، ملګرتیا", "ar": "الرِّفَاقَة، الصُّحْبَة"},
    "rafat": {"en": "Rafat; elevation, dignity", "ur": "رفعت، بلندی", "fa": "رفعت، بلندی", "hi": "रफ़ात, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
    "rafay": {"en": "Rafay; a male given name", "ur": "رفیع (مردانہ نام)", "fa": "رفیع (نام مردانه)", "hi": "रफ़ै (पुरुष नाम)", "ps": "رفیع (نر نوم)", "ar": "رَفِيع (اسْم عَلَم مُذَكَّر)"},
    "rafayet": {"en": "Rafayet; elevation, dignity", "ur": "رفعت، بلندی", "fa": "رفعت، بلندی", "hi": "रफ़ायत, उन्नति", "ps": "رفعت، لوړوالی", "ar": "الرِّفْعَة، الْعُلُوّ"},
    "rafee": {"en": "Rafee; elevated, exalted", "ur": "رفیع، بلند", "fa": "رفیع، بلند", "hi": "रफ़ी, उन्नत", "ps": "رفیع، لوړ", "ar": "الرَّفِيع، الْعَلِيّ"},
    "rafeek": {"en": "Rafeeq; companion, friend", "ur": "رفیق، ساتھی، دوست", "fa": "رفیق، همراه", "hi": "रफ़ीक़, साथी", "ps": "رفیق، ملګری", "ar": "الرَّفِيق، الصَّاحِب"},
    "rafeeq": {"en": "Rafeeq; companion, friend", "ur": "رفیق، ساتھی، دوست", "fa": "رفیق، همراه", "hi": "रफ़ीक़, साथी", "ps": "رفیق، ملګری", "ar": "الرَّفِيق، الصَّاحِب"},
    "rafeh": {"en": "Rafeh; a male given name", "ur": "رفح (مردانہ نام)", "fa": "رفح (نام مردانه)", "hi": "रफ़ेह (पुरुष नाम)", "ps": "رفح (نر نوم)", "ar": "رَفَح (اسْم عَلَم مُذَكَّر)"},
    "rafeq": {"en": "Rafiq; companion, friend", "ur": "رفیق، ساتھی", "fa": "رفیق، همراه", "hi": "रफ़ीक़, साथी", "ps": "رفیق، ملګری", "ar": "الرَّفِيق، الصَّاحِب"},
    "rafi": {"en": "Rafi; elevated, exalted", "ur": "رفیع، بلند", "fa": "رفیع، بلند", "hi": "रफ़ी, उन्नत", "ps": "رفیع، لوړ", "ar": "الرَّفِيع، الْعَلِيّ"},
    "rafia": {"en": "Rafia; elevated, exalted (feminine)", "ur": "رافعہ، بلند", "fa": "رافعه، بلند", "hi": "राफ़िया, उन्नत", "ps": "رافعه، لوړه", "ar": "رَافِيَة، الرَّفِيعَة"},
    "rafiah": {"en": "Rafiah; elevated, exalted (feminine)", "ur": "رافعہ، بلند", "fa": "رافعه، بلند", "hi": "राफ़िया, उन्नत", "ps": "رافعه، لوړه", "ar": "رَافِيَة، الرَّفِيعَة"},
    "rafid": {"en": "Rafid; a male given name", "ur": "رافد (مردانہ نام)", "fa": "رافد (نام مردانه)", "hi": "राफ़िद (पुरुष नाम)", "ps": "رافد (نر نوم)", "ar": "رَافِد (اسْم عَلَم مُذَكَّر)"},
    "rafidah": {"en": "Rafidah; a female given name", "ur": "رافدہ (زنانہ نام)", "fa": "رافده (نام زنانه)", "hi": "राफ़िदा (स्त्री नाम)", "ps": "رافده (ښځينه نوم)", "ar": "رَافِدَة (اسْم عَلَم مُؤَنَّث)"},
    "rafif": {"en": "Rafif; a female given name", "ur": "رفیف (زنانہ نام)", "fa": "رفیف (نام زنانه)", "hi": "रफ़ीफ़ (स्त्री नाम)", "ps": "رفیف (ښځينه نوم)", "ar": "رَفِيف (اسْم عَلَم مُؤَنَّث)"},
    "rafik": {"en": "Rafik; companion, friend", "ur": "رفیق، ساتھی", "fa": "رفیق، همراه", "hi": "रफ़ीक़, साथी", "ps": "رفیق، ملګری", "ar": "الرَّفِيق، الصَّاحِب"},
    "rafiq": {"en": "Rafiq; companion, friend", "ur": "رفیق، ساتھی، دوست", "fa": "رفیق، همراه", "hi": "रफ़ीक़, साथी", "ps": "رفیق، ملګری", "ar": "الرَّفِيق، الصَّاحِب"},
    "rafiqah": {"en": "Rafiqah; companion, friend (feminine)", "ur": "رفیقہ، ساتھی", "fa": "رفیقه، همراه", "hi": "रफ़ीक़ा, साथी", "ps": "رفیقه، ملګرې", "ar": "رَفِيقَة، الصَّاحِبَة"},
    "rafique": {"en": "Rafique; companion, friend", "ur": "رفیق، ساتھی", "fa": "رفیق، همراه", "hi": "रफ़ीक़, साथी", "ps": "رفیق، ملګری", "ar": "الرَّفِيق، الصَّاحِب"},
    "rafiya": {"en": "Rafiya; elevated, exalted (feminine)", "ur": "رفیعہ، بلند", "fa": "رفیعه، بلند", "hi": "रफ़िया, उन्नत", "ps": "رفیعه، لوړه", "ar": "رَفِيعَة، الرَّفِيعَة"},
    "rafraf": {"en": "Rafraf; a female given name", "ur": "رفرف (زنانہ نام)", "fa": "رفرف (نام زنانه)", "hi": "रफ़रफ़ (स्त्री नाम)", "ps": "رفرف (ښځينه نوم)", "ar": "رَفْرَف (اسْم عَلَم مُؤَنَّث)"},
    "ragab": {"en": "Ragab; a male given name", "ur": "رجب (مردانہ نام)", "fa": "رجب (نام مردانه)", "hi": "रजब (पुरुष नाम)", "ps": "رجب (نر نوم)", "ar": "رَجَب (اسْم عَلَم مُذَكَّر)"},
    "raghad": {"en": "Raghad; a female given name", "ur": "رغد (زنانہ نام)", "fa": "رغد (نام زنانه)", "hi": "रग़द (स्त्री नाम)", "ps": "رغد (ښځينه نوم)", "ar": "رَغَد (اسْم عَلَم مُؤَنَّث)"},
    "raghd": {"en": "Raghd; a female given name", "ur": "رغد (زنانہ نام)", "fa": "رغد (نام زنانه)", "hi": "रग़द (स्त्री नाम)", "ps": "رغد (ښځينه نوم)", "ar": "رَغْد (اسْم عَلَم مُؤَنَّث)"},
    "raghda": {"en": "Raghda; a female given name", "ur": "رغدہ (زنانہ نام)", "fa": "رغده (نام زنانه)", "hi": "रग़दा (स्त्री नाम)", "ps": "رغده (ښځينه نوم)", "ar": "رَغْدَة (اسْم عَلَم مُؤَنَّث)"},
    "raghdah": {"en": "Raghdah; a female given name", "ur": "رغدہ (زنانہ نام)", "fa": "رغده (نام زنانه)", "hi": "रग़दा (स्त्री नाम)", "ps": "رغده (ښځينه نوم)", "ar": "رَغْدَة (اسْم عَلَم مُؤَنَّث)"},
    "ragheb": {"en": "Ragheb; desiring, longing", "ur": "راغب، خواہشمند", "fa": "راغب، مشتاق", "hi": "राग़िब, इच्छुक", "ps": "راغب، هیله مند", "ar": "الرَّاغِب، الْمُشْتَاق"},
    "ragheed": {"en": "Ragheed; desiring, longing", "ur": "راغب، خواہشمند", "fa": "راغب، مشتاق", "hi": "राग़ीद, इच्छुक", "ps": "راغب، هیله مند", "ar": "الرَّاغِب، الْمُشْتَاق"},
    "raghib": {"en": "Raghib; desiring, longing", "ur": "راغب، خواہشمند", "fa": "راغب، مشتاق", "hi": "राग़िब, इच्छुक", "ps": "راغب، هیله مند", "ar": "الرَّاغِب، الْمُشْتَاق"},
    "raghid": {"en": "Raghid; a male given name", "ur": "راغد (مردانہ نام)", "fa": "راغد (نام مردانه)", "hi": "राग़िद (पुरुष नाम)", "ps": "راغد (نر نوم)", "ar": "رَاغِد (اسْم عَلَم مُذَكَّر)"},
    "raha": {"en": "Raha; a female given name (Persian)", "ur": "رہا (زنانہ نام)", "fa": "رها (نام زنانه)", "hi": "रहा (स्त्री नाम)", "ps": "رها (ښځينه نوم)", "ar": "رَهَا (اسْم عَلَم فَارِسِيّ)"},
    "rahaa": {"en": "Rahaa; a female given name", "ur": "رہا (زنانہ نام)", "fa": "رها (نام زنانه)", "hi": "रहा (स्त्री नाम)", "ps": "رها (ښځينه نوم)", "ar": "رَهَا (اسْم عَلَم مُؤَنَّث)"},
    "rahaf": {"en": "Rahaf; a female given name", "ur": "رہف (زنانہ نام)", "fa": "رهف (نام زنانه)", "hi": "रहफ़ (स्त्री नाम)", "ps": "رهف (ښځينه نوم)", "ar": "رَهَف (اسْم عَلَم مُؤَنَّث)"},
    "rahal": {"en": "Rahal; a male given name", "ur": "رحال (مردانہ نام)", "fa": "رحال (نام مردانه)", "hi": "रहाल (पुरुष नाम)", "ps": "رحال (نر نوم)", "ar": "رَحَّال (اسْم عَلَم مُذَكَّر)"},
    "raham": {"en": "Raham; mercy, compassion", "ur": "رحم، مہربانی", "fa": "رحم، مهربانی", "hi": "रहम, दया", "ps": "رحم، مهرباني", "ar": "الرَّحْم، الرَّحْمَة"},
    "rahana": {"en": "Rahana; a female given name", "ur": "راہانہ (زنانہ نام)", "fa": "راهانه (نام زنانه)", "hi": "राहाना (स्त्री नाम)", "ps": "راهانه (ښځينه نوم)", "ar": "رَاهَانَة (اسْم عَلَم مُؤَنَّث)"},
    "rahat": {"en": "Rahat; comfort, ease", "ur": "راحت، آرام، سکون", "fa": "راحت، آسایش", "hi": "राहत, आराम", "ps": "راحت، آرام", "ar": "الرَّاحَة، السُّكُون"},
    "rahbar": {"en": "Rahbar; guide, leader (Persian)", "ur": "رہبر، رہنما", "fa": "رهبر، پیشوا", "hi": "रहबर, नेता", "ps": "رهبر، مشر", "ar": "رَهْبَر (الْقَائِد)"},
    "raheel": {"en": "Raheel; departure, journey", "ur": "رحیل، سفر، کوچ", "fa": "رحیل، سفر", "hi": "रहील, यात्रा", "ps": "رحیل، سفر", "ar": "الرَّحِيل، السَّفَر"},
    "raheela": {"en": "Raheela; a female given name", "ur": "راحیلہ (زنانہ نام)", "fa": "راحيله (نام زنانه)", "hi": "राहीला (स्त्री नाम)", "ps": "راحيله (ښځينه نوم)", "ar": "رَاحِيلَة (اسْم عَلَم مُؤَنَّث)"},
    "raheem": {"en": "Raheem; merciful, compassionate", "ur": "رحیم، مہربان", "fa": "رحیم، مهربان", "hi": "रहीम, दयालु", "ps": "رحیم، مهربان", "ar": "الرَّحِيم، الرَّحْمَان"},
    "raheema": {"en": "Raheema; merciful, compassionate (feminine)", "ur": "رحیمہ، مہربان", "fa": "رحیمه، مهربان", "hi": "रहीमा, दयालु", "ps": "رحیمه، مهربانه", "ar": "رَحِيمَة، الرَّحِيمَة"},
    "raheemah": {"en": "Raheemah; merciful, compassionate (feminine)", "ur": "رحیمہ، مہربان", "fa": "رحیمه، مهربان", "hi": "रहीमा, दयालु", "ps": "رحیمه، مهربانه", "ar": "رَحِيمَة، الرَّحِيمَة"},
    "raheesh": {"en": "Raheesh; a male given name", "ur": "راہیش (مردانہ نام)", "fa": "راهیش (نام مردانه)", "hi": "राहीश (पुरुष नाम)", "ps": "راهیش (نر نوم)", "ar": "رَاهِيش (اسْم عَلَم مُذَكَّر)"},
    "rahema": {"en": "Rahema; mercy, compassion", "ur": "رحمہ، رحمت", "fa": "رحمه، رحمت", "hi": "रहमा, दया", "ps": "رحمه، رحمت", "ar": "الرَّحْمَة، الرَّحْمَن"},
    "rahf": {"en": "Rahf; a male given name", "ur": "رہف (مردانہ نام)", "fa": "رهف (نام مردانه)", "hi": "रहफ़ (पुरुष नाम)", "ps": "رهف (نر نوم)", "ar": "رَهْف (اسْم عَلَم مُذَكَّر)"},
    "rahi": {"en": "Rahi; traveler, wayfarer", "ur": "راہی، مسافر", "fa": "راهی، مسافر", "hi": "राही, यात्री", "ps": "راهي، مسافر", "ar": "الرَّاهِي، الْمُسَافِر"},
    "rahib": {"en": "Rahib; monk, ascetic", "ur": "راہب، راہب، تارک الدنیا", "fa": "راهب، تارک دنیا", "hi": "राहिब, भिक्षु", "ps": "راهب، زاهد", "ar": "الرَّاهِب، الزَّاهِد"},
    "rahid": {"en": "Rahid; a male given name", "ur": "راحد (مردانہ نام)", "fa": "راحد (نام مردانه)", "hi": "राहिद (पुरुष नाम)", "ps": "راحد (نر نوم)", "ar": "رَاحِد (اسْم عَلَم مُذَكَّر)"},
    "rahik": {"en": "Rahik; a male given name", "ur": "رحیک (مردانہ نام)", "fa": "رحیک (نام مردانه)", "hi": "रहीक (पुरुष नाम)", "ps": "رحیک (نر نوم)", "ar": "رَحِيك (اسْم عَلَم مُذَكَّر)"},
    "rahil": {"en": "Rahil; departure, journey", "ur": "رحیل، سفر", "fa": "رحیل، سفر", "hi": "रहील, यात्रा", "ps": "رحیل، سفر", "ar": "الرَّحِيل، السَّفَر"},
    "rahila": {"en": "Rahila; a female given name", "ur": "راحیلہ (زنانہ نام)", "fa": "راحيله (نام زنانه)", "hi": "राहीला (स्त्री नाम)", "ps": "راحيله (ښځينه نوم)", "ar": "رَاحِيلَة (اسْم عَلَم مُؤَنَّث)"},
    "rahim": {"en": "Rahim; merciful, compassionate", "ur": "رحیم، مہربان", "fa": "رحیم، مهربان", "hi": "रहीम, दयालु", "ps": "رحیم، مهربان", "ar": "الرَّحِيم، الرَّحْمَان"},
    "rahima": {"en": "Rahima; merciful, compassionate (feminine)", "ur": "رحیمہ، مہربان", "fa": "رحیمه، مهربان", "hi": "रहीमा, दयालु", "ps": "رحیمه، مهربانه", "ar": "رَحِيمَة، الرَّحِيمَة"},
    "rahimaa": {"en": "Rahimaa; merciful, compassionate (feminine)", "ur": "رحیمہ، مہربان", "fa": "رحیمه، مهربان", "hi": "रहीमा, दयालु", "ps": "رحیمه، مهربانه", "ar": "رَحِيمَة، الرَّحِيمَة"},
    "rahimah": {"en": "Rahimah; merciful, compassionate (feminine)", "ur": "رحیمہ، مہربان", "fa": "رحیمه، مهربان", "hi": "रहीमा, दयालु", "ps": "رحیمه، مهربانه", "ar": "رَحِيمَة، الرَّحِيمَة"},
    "rahime": {"en": "Rahime; merciful, compassionate (feminine)", "ur": "رحیمہ، مہربان", "fa": "رحیمه، مهربان", "hi": "रहीमा, दयालु", "ps": "رحیمه، مهربانه", "ar": "رَحِيمَة، الرَّحِيمَة"},
    "rahm": {"en": "Rahm; mercy, compassion", "ur": "رحم، مہربانی", "fa": "رحم، مهربانی", "hi": "रहम, दया", "ps": "رحم، مهرباني", "ar": "الرَّحْم، الرَّحْمَة"},
    "rahma": {"en": "Rahma; mercy, compassion", "ur": "رحمہ، رحمت", "fa": "رحمه، رحمت", "hi": "रहमा, दया", "ps": "رحمه، رحمت", "ar": "الرَّحْمَة"},
    "rahmaa": {"en": "Rahmaa; mercy, compassion", "ur": "رحمہ، رحمت", "fa": "رحمه، رحمت", "hi": "रहमा, दया", "ps": "رحمه، رحمت", "ar": "الرَّحْمَة"},
    "rahmah": {"en": "Rahmah; mercy, compassion", "ur": "رحمہ، رحمت", "fa": "رحمه، رحمت", "hi": "रहमा, दया", "ps": "رحمه، رحمت", "ar": "الرَّحْمَة"},
    "rahman": {"en": "Rahman; the Most Merciful", "ur": "رحمان، بے حد مہربان", "fa": "رحمان، بخشنده", "hi": "रहमान, दयालु", "ps": "رحمان، مهربان", "ar": "الرَّحْمَان"},
    "rahmat": {"en": "Rahmat; mercy, compassion", "ur": "رحمت، مہربانی", "fa": "رحمت، بخشش", "hi": "रहमत, दया", "ps": "رحمت، مهرباني", "ar": "الرَّحْمَة"},
    "rahmath": {"en": "Rahmath; mercy, compassion", "ur": "رحمت، مہربانی", "fa": "رحمت، بخشش", "hi": "रहमत, दया", "ps": "رحمت، مهرباني", "ar": "الرَّحْمَة"},
    "rahmi": {"en": "Rahmi; of mercy (relational)", "ur": "رحمی، رحم سے منسوب", "fa": "رحمی، منسوب به رحم", "hi": "रहमी, दया से संबंधित", "ps": "رحمي، د رحم اړوند", "ar": "الرَّحْمِي، مَنْسُوب إِلَى الرَّحْمَة"},
    "rai": {"en": "Rai; a male given name", "ur": "رائی (مردانہ نام)", "fa": "رائی (نام مردانه)", "hi": "राई (पुरुष नाम)", "ps": "رائی (نر نوم)", "ar": "رَائِي (اسْم عَلَم مُذَكَّر)"},
    "raid": {"en": "Raid; thunder", "ur": "رعد، گرج", "fa": "رعد، آذرخش", "hi": "राद, गर्जन", "ps": "رعد، تندر", "ar": "الرَّعْد"},
    "raida": {"en": "Raida; leader, pioneer (feminine)", "ur": "رائدہ، رہنما", "fa": "رائده، پیشرو", "hi": "राइदा, अग्रणी", "ps": "رائده، مشره", "ar": "الرَّائِدَة، الْقَائِدَة"},
    "raidah": {"en": "Raidah; leader, pioneer (feminine)", "ur": "رائدہ، رہنما", "fa": "رائده، پیشرو", "hi": "राइदा, अग्रणी", "ps": "رائده، مشره", "ar": "الرَّائِدَة، الْقَائِدَة"},
    "raif": {"en": "Raif; compassionate, kind", "ur": "رئيف، مہربان", "fa": "رئوف، مهربان", "hi": "रईफ़, दयालु", "ps": "رئيف، مهربان", "ar": "الرَّءُوف، الرَّحِيم"},
    "raifa": {"en": "Raifa; compassionate, kind (feminine)", "ur": "رئيفہ، مہربان", "fa": "رئوفه، مهربان", "hi": "रईफ़ा, दयालु", "ps": "رئيفه، مهربانه", "ar": "رَئِيفَة، الرَّءُوفَة"},
    "raiha": {"en": "Raiha; fragrance, scent", "ur": "رائحہ، خوشبو", "fa": "رایحه، بو", "hi": "राइहा, सुगंध", "ps": "رایحه، بوی", "ar": "الرَّائِحَة، الْعِطْر"},
    "raihaan": {"en": "Raihan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "raihan": {"en": "Raihan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "raihana": {"en": "Raihana; fragrant herb, basil (feminine)", "ur": "ریحانہ، خوشبودار پودا", "fa": "ریحانه، سبزی خوشبو", "hi": "रैहाना, तुलसी", "ps": "ریحانه، خوږ بوټی", "ar": "رَيْحَانَة، الرَّيْحَان"},
    "raihanah": {"en": "Raihanah; fragrant herb, basil (feminine)", "ur": "ریحانہ، خوشبودار پودا", "fa": "ریحانه، سبزی خوشبو", "hi": "रैहाना, तुलसी", "ps": "ریحانه، خوږ بوټی", "ar": "رَيْحَانَة، الرَّيْحَان"},
    "raika": {"en": "Raika; a female given name", "ur": "رائیکا (زنانہ نام)", "fa": "رایکا (نام زنانه)", "hi": "राइका (स्त्री नाम)", "ps": "رایکا (ښځينه نوم)", "ar": "رَايِكَة (اسْم عَلَم مُؤَنَّث)"},
    "raima": {"en": "Raima; a female given name", "ur": "ریمہ (زنانہ نام)", "fa": "ریما (نام زنانه)", "hi": "रैमा (स्त्री नाम)", "ps": "ریمه (ښځينه نوم)", "ar": "رَيْمَة (اسْم عَلَم مُؤَنَّث)"},
    "raimah": {"en": "Raimah; a female given name", "ur": "رائمہ (زنانہ نام)", "fa": "رائمه (نام زنانه)", "hi": "राइमा (स्त्री नाम)", "ps": "رائمه (ښځينه نوم)", "ar": "رَائِمَة (اسْم عَلَم مُؤَنَّث)"},
    "raiq": {"en": "Raiq; clear, pure", "ur": "رائق، صاف، خالص", "fa": "رائق، پاک", "hi": "राइक़, शुद्ध", "ps": "رائق، پاک", "ar": "الرَّائِق، الصَّافِي"},
    "rais": {"en": "Rais; leader, chief", "ur": "رئیس، سردار", "fa": "رئیس، رهبر", "hi": "रईस, नेता", "ps": "رئیس، مشر", "ar": "الرَّئِيس، الزَّعِيم"},
    "raisa": {"en": "Raisa; leader, chief (feminine)", "ur": "رئیسہ، سردارنی", "fa": "رئیسه، رهبر", "hi": "रईसा, नेत्री", "ps": "رئیسه، مشره", "ar": "الرَّئِيسَة، الزَّعِيمَة"},
    "raisah": {"en": "Raisah; leader, chief (feminine)", "ur": "رئیسہ، سردارنی", "fa": "رئیسه، رهبر", "hi": "रईसा, नेत्री", "ps": "رئیسه، مشره", "ar": "الرَّئِيسَة، الزَّعِيمَة"},
    "raisha": {"en": "Raisha; a female given name", "ur": "رایشہ (زنانہ نام)", "fa": "رایشا (نام زنانه)", "hi": "राइशा (स्त्री नाम)", "ps": "رایشا (ښځينه نوم)", "ar": "رَايِشَة (اسْم عَلَم مُؤَنَّث)"},
    "raiya": {"en": "Raiya; a female given name", "ur": "رایہ (زنانہ نام)", "fa": "رایا (نام زنانه)", "hi": "राया (स्त्री नाम)", "ps": "رایا (ښځينه نوم)", "ar": "رَايَة (اسْم عَلَم مُؤَنَّث)"},
    "raiyan": {"en": "Raiyan; a male given name", "ur": "ریان (مردانہ نام)", "fa": "ریان (نام مردانه)", "hi": "रैयान (पुरुष नाम)", "ps": "ریان (نر نوم)", "ar": "رَيَّان (اسْم عَلَم مُذَكَّر)"},
    "raja": {"en": "Raja; king, ruler (Sanskrit)", "ur": "راجہ، بادشاہ", "fa": "راجا، پادشاه", "hi": "राजा, राजा", "ps": "راجا، پاچا", "ar": "رَاجَا (الْمَلِك)"},
    "rajaa": {"en": "Rajaa; hope, expectation", "ur": "رجاء، امید", "fa": "رجاء، امید", "hi": "रजा, आशा", "ps": "رجاء، هیله", "ar": "الرَّجَاء، الْأَمَل"},
    "rajab": {"en": "Rajab; the seventh Islamic month", "ur": "رجب، اسلامی مہینہ", "fa": "رجب، ماه اسلامی", "hi": "रजब, इस्लामी महीना", "ps": "رجب، اسلامي میاشت", "ar": "رَجَب (شَهْر هِجْرِيّ)"},
    "rajah": {"en": "Rajah; king, ruler (Sanskrit)", "ur": "راجہ، بادشاہ", "fa": "راجا، پادشاه", "hi": "राजा, राजा", "ps": "راجا، پاچا", "ar": "رَاجَا (الْمَلِك)"},
    "rajeh": {"en": "Rajeh; preponderant, likely", "ur": "راجح، غالب", "fa": "راجح، برتر", "hi": "राजिह, प्रबल", "ps": "راجح، غالبه", "ar": "الرَّاجِح، الْأَرْجَح"},
    "raji": {"en": "Raji; hoping, expectant", "ur": "راجی، امیدوار", "fa": "راجی، امیدوار", "hi": "राजी, आशावान", "ps": "راجي، هیله مند", "ar": "الرَّاجِي، الْآمِل"},
    "rajiya": {"en": "Rajiya; hoping, expectant (feminine)", "ur": "راجیہ، امیدوار", "fa": "راجیه، امیدوار", "hi": "राजिया, आशावान", "ps": "راجیه، هیله منده", "ar": "رَاجِيَة، الْآمِلَة"},
    "rajwa": {"en": "Rajwa; hope, expectation", "ur": "رجوہ، امید", "fa": "رجوا، امید", "hi": "रजवा, आशा", "ps": "رجوا، هیله", "ar": "الرَّجْوَة، الرَّجَاء"},
    "rakan": {"en": "Rakan; firm, steady", "ur": "رکان، مضبوط، مستحکم", "fa": "رکان، استوار", "hi": "रकान, दृढ़", "ps": "رکان، ټینګ", "ar": "الرَّكَان، الرَّصِين"},
    "rakeeb": {"en": "Rakeeb; watcher, guardian", "ur": "رقیب، نگہبان", "fa": "رقیب، نگهبان", "hi": "रक़ीब, रक्षक", "ps": "رقیب، ساتونکی", "ar": "الرَّقِيب، الْحَافِظ"},
    "rakeem": {"en": "Rakeem; a male given name", "ur": "رکیم (مردانہ نام)", "fa": "رکیم (نام مردانه)", "hi": "रकीम (पुरुष नाम)", "ps": "رکیم (نر نوم)", "ar": "رَكِيم (اسْم عَلَم مُذَكَّر)"},
    "raki": {"en": "Raki; a male given name", "ur": "راکی (مردانہ نام)", "fa": "راکی (نام مردانه)", "hi": "राकी (पुरुष नाम)", "ps": "راکی (نر نوم)", "ar": "رَاكِي (اسْم عَلَم مُذَكَّر)"},
})

CUR = {
 "rafah": ("رَفَاح", "رفاح", "رفاح", "रफ़ाह", "رفاح", "rafah", "Arabic", "Female",
           "Arabic رَفَاح (Rafāḥ)", False, "medium",
           "Rafah is recorded as Arabic رَفَاح (Rafāḥ), a female given name. The source gloss 'Soft and gentle' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "rafan": ("رَفَان", "رفان", "رفان", "रफ़ान", "رفان", "rafan", "Arabic", "Male",
           "Arabic رَفَان (Rafān)", False, "medium",
           "Rafan is recorded as Arabic رَفَان (Rafān), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rafan' instead of a script form. The source gloss 'Noble, exalted one' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rafaqat": ("رِفَاقَة", "رفاقت", "رفاقت", "रफ़ाक़त", "رفاقت", "rafaqat", "Arabic", "Male",
             "Arabic root ر ف ق (r-f-q); رِفَاقَة (Rifāqa)", False, "high",
             "Rafaqat is Arabic رِفَاقَة (Rifāqa) 'companionship, fellowship', from the root ر ف ق (r-f-q). CRITICAL SOURCE ERROR: the source gave رفاقة (a non-standard form). The source gloss 'Pious, God-fearing' is unsupported and has been replaced with the lexical sense."),
 "rafat": ("رِفْعَة", "رفعت", "رفعت", "रफ़ात", "رفعت", "rafat", "Arabic", "Male",
           "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
           "Rafat is Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رفات (a non-standard form). The source gloss 'Exalted, Lofty' is broadly consistent. Same name as rafaat."),
 "rafay": ("رَفِيع", "رفیع", "رفیع", "रफ़ै", "رفیع", "rafay", "Arabic", "Male",
           "Arabic root ر ف ع (r-f-ʿ); رَفِيع (Rafīʿ)", False, "high",
           "Rafay is Arabic رَفِيع (Rafīʿ) 'elevated, exalted', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as rafi."),
 "rafayet": ("رِفْعَة", "رفعت", "رفعت", "रफ़ायत", "رفعت", "rafayet", "Arabic", "Male",
             "Arabic root ر ف ع (r-f-ʿ); رِفْعَة (Rifʿa)", False, "high",
             "Rafayet is a spelling variant of Arabic رِفْعَة (Rifʿa) 'elevation, dignity', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave أحمد (a different name); the correct form is رِفْعَة. The source gloss 'Rain Giver' is unsupported and has been replaced with the lexical sense. Same name as rafaat."),
 "rafee": ("رَفِيع", "رفیع", "رفیع", "रफ़ी", "رفیع", "rafee", "Arabic", "Male",
           "Arabic root ر ف ع (r-f-ʿ); رَفِيع (Rafīʿ)", False, "high",
           "Rafee is Arabic رَفِيع (Rafīʿ) 'elevated, exalted', from the root ر ف ع (r-f-ʿ). The source gloss 'Elevated, Exalted' is consistent. Same name as rafi."),
 "rafeek": ("رَفِيق", "رفیق", "رفیق", "रफ़ीक़", "رفیق", "rafeek", "Arabic", "Male",
            "Arabic root ر ف ق (r-f-q); رَفِيق (Rafīq)", False, "high",
            "Rafeeq is Arabic رَفِيق (Rafīq) 'companion, friend', from the root ر ف ق (r-f-q). The source gloss 'Healer' is unsupported and has been replaced with the lexical sense. Same name as rafiq."),
 "rafeeq": ("رَفِيق", "رفیق", "رفیق", "रफ़ीक़", "رفیق", "rafeeq", "Arabic", "Male",
            "Arabic root ر ف ق (r-f-q); رَفِيق (Rafīq)", False, "high",
            "Rafeeq is Arabic رَفِيق (Rafīq) 'companion, friend', from the root ر ف ق (r-f-q). The source gloss 'Kind and Compassionate' is unsupported and has been replaced with the lexical sense. Same name as rafiq."),
 "rafeh": ("رَفَح", "رفح", "رفح", "रफ़ेह", "رفح", "rafeh", "Arabic", "Male",
           "Arabic رَفَح (Rafaḥ)", False, "medium",
           "Rafeh is recorded as Arabic رَفَح (Rafaḥ), a male given name. CRITICAL SOURCE ERROR: the source gave رفح (a non-standard form). The source gloss 'Healing, Compassionate' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rafeq": ("رَفِيق", "رفیق", "رفیق", "रफ़ीक़", "رفیق", "rafeq", "Arabic", "Male",
           "Arabic root ر ف ق (r-f-q); رَفِيق (Rafīq)", False, "high",
           "Rafeq is a spelling variant of Arabic رَفِيق (Rafīq) 'companion, friend', from the root ر ف ق (r-f-q). The source gloss 'Friend, Companion' is consistent. Same name as rafiq."),
 "rafi": ("رَفِيع", "رفیع", "رفیع", "रफ़ी", "رفیع", "rafi", "Arabic", "Male",
          "Arabic root ر ف ع (r-f-ʿ); رَفِيع (Rafīʿ)", False, "high",
          "Rafi is Arabic رَفِيع (Rafīʿ) 'elevated, exalted', from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رَفِي (a non-standard form). The source gloss 'Exalted, Elevated' is consistent."),
 "rafia": ("رَافِيَة", "رافعہ", "رافعه", "राफ़िया", "رافعه", "rafia", "Arabic", "Female",
           "Arabic root ر ف ع (r-f-ʿ); رَافِيَة (Rāfiya)", False, "high",
           "Rafia is Arabic رَافِيَة (Rāfiya) 'elevated, exalted' (feminine), from the root ر ف ع (r-f-ʿ). The source gloss 'Garden of God' is unsupported and has been replaced with the lexical sense. Same name as rafiah."),
 "rafiah": ("رَافِيَة", "رافعہ", "رافعه", "राफ़िया", "رافعه", "rafiah", "Arabic", "Female",
            "Arabic root ر ف ع (r-f-ʿ); رَافِيَة (Rāfiya)", False, "high",
            "Rafiah is Arabic رَافِيَة (Rāfiya) 'elevated, exalted' (feminine), from the root ر ف ع (r-f-ʿ). The source gloss 'Compassionate, Merciful' is unsupported and has been replaced with the lexical sense. Same name as rafia."),
 "rafid": ("رَافِد", "رافد", "رافد", "राफ़िद", "رافد", "rafid", "Arabic", "Male",
           "Arabic root ر ف د (r-f-d); رَافِد (Rāfid)", False, "high",
           "Rafid is Arabic رَافِد (Rāfid) 'supporter, tributary', from the root ر ف د (r-f-d). CRITICAL SOURCE ERROR: the source gave رَفِيظ (a different form); the correct form is رَافِد. The source gloss 'One who is concealed or hidden' is unsupported and has been replaced with the lexical sense."),
 "rafidah": ("رَافِدَة", "رافدہ", "رافده", "राफ़िदा", "رافده", "rafidah", "Arabic", "Female",
             "Arabic root ر ف د (r-f-d); رَافِدَة (Rāfida)", False, "high",
             "Rafidah is Arabic رَافِدَة (Rāfida) 'supporter' (feminine), from the root ر ف د (r-f-d). The source gloss 'Pious, Devout' is unsupported and has been replaced with the lexical sense."),
 "rafif": ("رَفِيف", "رفیف", "رفیف", "रफ़ीफ़", "رفیف", "rafif", "Arabic", "Female",
           "Arabic root ر ف ف (r-f-f); رَفِيف (Rafīf)", False, "high",
           "Rafif is Arabic رَفِيف (Rafīf) 'a gentle rustle, shimmer', from the root ر ف ف (r-f-f). The source gloss 'Rare, precious' is unsupported and has been replaced with the lexical sense."),
 "rafik": ("رَفِيق", "رفیق", "رفیق", "रफ़ीक़", "رفیق", "rafik", "Arabic", "Male",
           "Arabic root ر ف ق (r-f-q); رَفِيق (Rafīq)", False, "high",
           "Rafik is a spelling variant of Arabic رَفِيق (Rafīq) 'companion, friend', from the root ر ف ق (r-f-q). CRITICAL SOURCE ERROR: the source gave رافك (a non-standard form). The source gloss 'Friend, companion' is consistent. Same name as rafiq."),
 "rafiq": ("رَفِيق", "رفیق", "رفیق", "रफ़ीक़", "رفیق", "rafiq", "Arabic", "Male",
           "Arabic root ر ف ق (r-f-q); رَفِيق (Rafīq)", False, "high",
           "Rafiq is Arabic رَفِيق (Rafīq) 'companion, friend', from the root ر ف ق (r-f-q). The source gloss 'Friend, Companion' is consistent."),
 "rafiqah": ("رَفِيقَة", "رفیقہ", "رفیقه", "रफ़ीक़ा", "رفیقه", "rafiqah", "Arabic", "Female",
             "Arabic root ر ف ق (r-f-q); رَفِيقَة (Rafīqa)", False, "high",
             "Rafiqah is Arabic رَفِيقَة (Rafīqa) 'companion, friend' (feminine), from the root ر ف ق (r-f-q). CRITICAL SOURCE ERROR: the source gave رفيقه (a non-standard form). The source gloss 'Friend, Companion' is consistent."),
 "rafique": ("رَفِيق", "رفیق", "رفیق", "रफ़ीक़", "رفیق", "rafique", "Arabic", "Male",
             "Arabic root ر ف ق (r-f-q); رَفِيق (Rafīq)", False, "high",
             "Rafique is a spelling variant of Arabic رَفِيق (Rafīq) 'companion, friend', from the root ر ف ق (r-f-q). The source gloss 'Graceful' is unsupported and has been replaced with the lexical sense. Same name as rafiq."),
 "rafiya": ("رَفِيعَة", "رفیعہ", "رفیعه", "रफ़िया", "رفیعه", "rafiya", "Arabic", "Female",
            "Arabic root ر ف ع (r-f-ʿ); رَفِيعَة (Rafīʿa)", False, "high",
            "Rafiya is Arabic رَفِيعَة (Rafīʿa) 'elevated, exalted' (feminine), from the root ر ف ع (r-f-ʿ). CRITICAL SOURCE ERROR: the source gave رفيا (a non-standard form). The source gloss 'Exalted One' is broadly consistent."),
 "rafraf": ("رَفْرَف", "رفرف", "رفرف", "रफ़रफ़", "رفرف", "rafraf", "Arabic", "Female",
            "Arabic رَفْرَف (Rafraf)", False, "medium",
            "Rafraf is recorded as Arabic رَفْرَف (Rafraf), a female given name. CRITICAL SOURCE ERROR: the source gave أحمد (a different name); the correct form is رَفْرَف. The source gloss 'Rain, Thunder' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "ragab": ("رَجَب", "رجب", "رجب", "रजब", "رجب", "ragab", "Arabic", "Male",
           "Arabic رَجَب (Rajab), the seventh Islamic month", False, "high",
           "Ragab is a spelling variant of Arabic رَجَب (Rajab), the seventh month of the Islamic calendar, used as a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Ragab' instead of a script form. The source gloss 'Young Goat' is unsupported and has been replaced with the documented identification. Same name as rajab."),
 "raghad": ("رَغَد", "رغد", "رغد", "रग़द", "رغد", "raghad", "Arabic", "Female",
            "Arabic root ر غ د (r-gh-d); رَغَد (Raghad)", False, "high",
            "Raghad is Arabic رَغَد (Raghad) 'a life of ease and plenty', from the root ر غ د (r-gh-d). The source gloss 'blossom, flower' is unsupported and has been replaced with the lexical sense."),
 "raghd": ("رَغْد", "رغد", "رغد", "रग़द", "رغد", "raghd", "Arabic", "Female",
           "Arabic root ر غ د (r-gh-d); رَغْد (Raghd)", False, "high",
           "Raghd is Arabic رَغْد (Raghd) 'a life of ease and plenty', from the root ر غ د (r-gh-d). CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is رَغْد. The source gloss 'Contentment, Satisfaction, Joy' is broadly consistent. Same name as raghad."),
 "raghda": ("رَغْدَة", "رغدہ", "رغده", "रग़दा", "رغده", "raghda", "Arabic", "Female",
            "Arabic root ر غ د (r-gh-d); رَغْدَة (Raghda)", False, "high",
            "Raghda is Arabic رَغْدَة (Raghda) 'a life of ease and plenty', from the root ر غ د (r-gh-d). The source gloss 'Contentment, Satisfaction' is broadly consistent. Same name as raghdah."),
 "raghdah": ("رَغْدَة", "رغدہ", "رغده", "रग़दा", "رغده", "raghdah", "Arabic", "Female",
             "Arabic root ر غ د (r-gh-d); رَغْدَة (Raghda)", False, "high",
             "Raghdah is Arabic رَغْدَة (Raghda) 'a life of ease and plenty', from the root ر غ د (r-gh-d). The source gloss 'Tender Mercy' is unsupported and has been replaced with the lexical sense. Same name as raghda."),
 "ragheb": ("رَاغِب", "راغب", "راغب", "राग़िब", "راغب", "ragheb", "Arabic", "Male",
            "Arabic root ر غ ب (r-gh-b); رَاغِب (Rāghib)", False, "high",
            "Ragheb is Arabic رَاغِب (Rāghib) 'desiring, longing', from the root ر غ ب (r-gh-b). The source gloss 'Melodic, Singer' is unsupported and has been replaced with the lexical sense. Same name as raghib."),
 "ragheed": ("رَاغِب", "راغب", "راغب", "राग़ीद", "راغب", "ragheed", "Arabic", "Male",
             "Arabic root ر غ ب (r-gh-b); رَاغِب (Rāghib)", False, "high",
             "Ragheed is a spelling variant of Arabic رَاغِب (Rāghib) 'desiring, longing', from the root ر غ ب (r-gh-b). CRITICAL SOURCE ERROR: the source gave the Latin string 'Raghib' instead of a script form. The source gloss 'Regard, Prestige, Pride' is unsupported and has been replaced with the lexical sense. Same name as raghib."),
 "raghib": ("رَاغِب", "راغب", "راغب", "राग़िब", "راغب", "raghib", "Arabic", "Male",
            "Arabic root ر غ ب (r-gh-b); رَاغِب (Rāghib)", False, "high",
            "Raghib is Arabic رَاغِب (Rāghib) 'desiring, longing', from the root ر غ ب (r-gh-b). The source gloss 'Desiring or longing for' is consistent."),
 "raghid": ("رَاغِد", "راغد", "راغد", "राग़िद", "راغد", "raghid", "Arabic", "Male",
            "Arabic root ر غ د (r-gh-d); رَاغِد (Rāghid)", False, "high",
            "Raghid is Arabic رَاغِد (Rāghid) 'living in ease and plenty', from the root ر غ د (r-gh-d). CRITICAL SOURCE ERROR: the source gave راغد (a non-standard form). The source gloss 'Traveler' is unsupported and has been replaced with the lexical sense."),
 "raha": ("رَهَا", "رہا", "رها", "रहा", "رها", "raha", "Persian", "Female",
          "Persian رها (rahā)", False, "high",
          "Raha is Persian رها (rahā) 'free, liberated'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Content, Happy, Joyful' is unsupported and has been replaced with the lexical sense."),
 "rahaa": ("رَهَا", "رہا", "رها", "रहा", "رها", "rahaa", "Persian", "Female",
           "Persian رها (rahā)", False, "high",
           "Rahaa is a spelling variant of Persian رها (rahā) 'free, liberated'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rahaa' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Contentment, Satisfaction' is unsupported and has been replaced with the lexical sense. Same name as raha."),
 "rahaf": ("رَهَف", "رہف", "رهف", "रहफ़", "رهف", "rahaf", "Arabic", "Female",
           "Arabic رَهَف (Rahaf)", False, "high",
           "Rahaf is Arabic رَهَف (Rahaf), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "rahal": ("رَحَّال", "رحال", "رحال", "रहाल", "رحال", "rahal", "Arabic", "Male",
           "Arabic root ر ح ل (r-ḥ-l); رَحَّال (Raḥḥāl)", False, "high",
           "Rahal is Arabic رَحَّال (Raḥḥāl) 'great traveler', an intensive form from the root ر ح ل (r-ḥ-l). CRITICAL SOURCE ERROR: the source gave the Latin string 'Rahal' instead of a script form. The source gloss 'Traveler' is broadly consistent."),
 "raham": ("رَحْم", "رحم", "رحم", "रहम", "رحم", "raham", "Arabic", "Male",
           "Arabic root ر ح م (r-ḥ-m); رَحْم (Raḥm)", False, "high",
           "Raham is Arabic رَحْم (Raḥm) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Most Merciful' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rahana": ("رَاهَانَة", "راہانہ", "راهانه", "राहाना", "راهانه", "rahana", "Arabic", "Female",
            "Arabic رَاهَانَة (Rāhāna)", False, "medium",
            "Rahana is recorded as Arabic رَاهَانَة (Rāhāna), a female given name. The source gloss 'joyful, content, satisfied' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rahat": ("رَاحَة", "راحت", "راحت", "राहत", "راحت", "rahat", "Arabic", "Female",
           "Arabic root ر و ح (r-w-ḥ); رَاحَة (Rāḥa)", False, "high",
           "Rahat is Arabic رَاحَة (Rāḥa) 'comfort, ease', from the root ر و ح (r-w-ḥ). The source gloss 'Comfort, Ease' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "rahbar": ("رَهْبَر", "رہبر", "رهبر", "रहबर", "رهبر", "rahbar", "Persian", "Male",
            "Persian رهبر (rahbar)", False, "high",
            "Rahbar is Persian رهبر (rahbar) 'guide, leader'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Guide, Leader' is consistent."),
 "raheel": ("رَحِيل", "رحیل", "رحیل", "रहील", "رحیل", "raheel", "Arabic", "Female",
            "Arabic root ر ح ل (r-ḥ-l); رَحِيل (Raḥīl)", False, "high",
            "Raheel is Arabic رَحِيل (Raḥīl) 'departure, journey', from the root ر ح ل (r-ḥ-l). The source gloss 'Companion of the Prophet' is a historical association rather than a lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "raheela": ("رَاحِيلَة", "راحیلہ", "راحيله", "राहीला", "راحيله", "raheela", "Arabic", "Female",
             "Arabic رَاحِيلَة (Rāḥīla)", False, "medium",
             "Raheela is recorded as Arabic رَاحِيلَة (Rāḥīla), a female given name. The source gloss 'Path, Way' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raheem": ("رَحِيم", "رحیم", "رحیم", "रहीम", "رحیم", "raheem", "Arabic", "Male",
            "Arabic root ر ح م (r-ḥ-m); رَحِيم (Raḥīm)", False, "high",
            "Raheem is Arabic رَحِيم (Raḥīm) 'merciful, compassionate', from the root ر ح م (r-ḥ-m). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as rahim."),
 "raheema": ("رَحِيمَة", "رحیمہ", "رحیمه", "रहीमा", "رحیمه", "raheema", "Arabic", "Female",
             "Arabic root ر ح م (r-ḥ-m); رَحِيمَة (Raḥīma)", False, "high",
             "Raheema is Arabic رَحِيمَة (Raḥīma) 'merciful, compassionate' (feminine), from the root ر ح م (r-ḥ-m). The source gloss 'Merciful' is consistent. Same name as rahima."),
 "raheemah": ("رَحِيمَة", "رحیمہ", "رحیمه", "रहीमा", "رحیمه", "raheemah", "Arabic", "Female",
              "Arabic root ر ح م (r-ḥ-m); رَحِيمَة (Raḥīma)", False, "high",
              "Raheemah is Arabic رَحِيمَة (Raḥīma) 'merciful, compassionate' (feminine), from the root ر ح م (r-ḥ-m). The source gloss 'Compassionate' is consistent. Same name as rahima."),
 "raheesh": ("رَاهِيش", "راہیش", "راهیش", "राहीश", "راهیش", "raheesh", "Arabic", "Male",
             "Arabic رَاهِيش (Rāhīsh)", False, "medium",
             "Raheesh is recorded as Arabic رَاهِيش (Rāhīsh), a male given name. The source gloss 'Shepherd' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rahema": ("رَحْمَة", "رحمہ", "رحمه", "रहमा", "رحمه", "rahema", "Arabic", "Female",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
            "Rahema is Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Merciful One' is broadly consistent. Same name as rahma."),
 "rahf": ("رَهْف", "رہف", "رهف", "रहफ़", "رهف", "rahf", "Arabic", "Male",
          "Arabic رَهْف (Rahf)", False, "medium",
          "Rahf is recorded as Arabic رَهْف (Rahf), a male given name. The source gloss 'Gentle Rain' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rahi": ("رَاهِي", "راہی", "راهی", "राही", "راهي", "rahi", "Arabic", "Male",
          "Arabic root ر و ح (r-w-ḥ); رَاهِي (Rāhī)", False, "high",
          "Rahi is Arabic رَاهِي (Rāhī) 'traveler, wayfarer', from the root ر و ح (r-w-ḥ). CRITICAL SOURCE ERROR: the source gave رحى (a different form). The source gloss 'Traveler' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rahib": ("رَاهِب", "راہب", "راهب", "राहिब", "راهب", "rahib", "Arabic", "Male",
           "Arabic root ر ه ب (r-h-b); رَاهِب (Rāhib)", False, "high",
           "Rahib is Arabic رَاهِب (Rāhib) 'monk, ascetic', from the root ر ه ب (r-h-b). The source gloss 'One who is merciful' is unsupported and has been replaced with the lexical sense."),
 "rahid": ("رَاحِد", "راحد", "راحد", "राहिद", "راحد", "rahid", "Arabic", "Male",
           "Arabic رَاحِد (Rāḥid)", False, "medium",
           "Rahid is recorded as Arabic رَاحِد (Rāḥid), a male given name. CRITICAL SOURCE ERROR: the source gave راحد (a non-standard form). The source gloss 'Liberator, Free' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rahik": ("رَحِيك", "رحیک", "رحیک", "रहीक", "رحیک", "rahik", "Arabic", "Male",
           "Arabic رَحِيك (Raḥīk)", False, "medium",
           "Rahik is recorded as Arabic رَحِيك (Raḥīk), a male given name. CRITICAL SOURCE ERROR: the source gave رحيك (a non-standard form). The source gloss 'Traveler, Wayfarer' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rahil": ("رَحِيل", "رحیل", "رحیل", "रहील", "رحیل", "rahil", "Arabic", "Male",
           "Arabic root ر ح ل (r-ḥ-l); رَحِيل (Raḥīl)", False, "high",
           "Rahil is Arabic رَحِيل (Raḥīl) 'departure, journey', from the root ر ح ل (r-ḥ-l). The source gloss 'Traveler, Nomad' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raheel."),
 "rahila": ("رَاحِيلَة", "راحیلہ", "راحيله", "राहीला", "راحيله", "rahila", "Arabic", "Female",
            "Arabic رَاحِيلَة (Rāḥīla)", False, "medium",
            "Rahila is recorded as Arabic رَاحِيلَة (Rāḥīla), a female given name. The source gloss 'Traveler' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as raheela."),
 "rahim": ("رَحِيم", "رحیم", "رحیم", "रहीम", "رحیم", "rahim", "Arabic", "Male",
           "Arabic root ر ح م (r-ḥ-m); رَحِيم (Raḥīm)", False, "high",
           "Rahim is Arabic رَحِيم (Raḥīm) 'merciful, compassionate', from the root ر ح م (r-ḥ-m). The source gloss 'Compassionate, Merciful, Loving' is broadly consistent."),
 "rahima": ("رَحِيمَة", "رحیمہ", "رحیمه", "रहीमा", "رحیمه", "rahima", "Arabic", "Female",
            "Arabic root ر ح م (r-ḥ-m); رَحِيمَة (Raḥīma)", False, "high",
            "Rahima is Arabic رَحِيمَة (Raḥīma) 'merciful, compassionate' (feminine), from the root ر ح م (r-ḥ-m). The source gloss 'Merciful, Compassionate' is consistent."),
 "rahimaa": ("رَحِيمَة", "رحیمہ", "رحیمه", "रहीमा", "رحیمه", "rahimaa", "Arabic", "Female",
             "Arabic root ر ح م (r-ḥ-m); رَحِيمَة (Raḥīma)", False, "high",
             "Rahimaa is a spelling variant of Arabic رَحِيمَة (Raḥīma) 'merciful, compassionate' (feminine), from the root ر ح م (r-ḥ-m). The source gloss 'Merciful One' is broadly consistent. Same name as rahima."),
 "rahimah": ("رَحِيمَة", "رحیمہ", "رحیمه", "रहीमा", "رحیمه", "rahimah", "Arabic", "Female",
             "Arabic root ر ح م (r-ḥ-m); رَحِيمَة (Raḥīma)", False, "high",
             "Rahimah is Arabic رَحِيمَة (Raḥīma) 'merciful, compassionate' (feminine), from the root ر ح م (r-ḥ-m). The source gloss 'Compassionate and Merciful' is consistent. Same name as rahima."),
 "rahime": ("رَحِيمَة", "رحیمہ", "رحیمه", "रहीमा", "رحیمه", "rahime", "Arabic", "Female",
            "Arabic root ر ح م (r-ḥ-m); رَحِيمَة (Raḥīma)", False, "high",
            "Rahime is a Turkish spelling of Arabic رَحِيمَة (Raḥīma) 'merciful, compassionate' (feminine), from the root ر ح م (r-ḥ-m). The source gloss 'Compassionate' is consistent. Same name as rahima."),
 "rahm": ("رَحْم", "رحم", "رحم", "रहम", "رحم", "rahm", "Arabic", "Male",
          "Arabic root ر ح م (r-ḥ-m); رَحْم (Raḥm)", False, "high",
          "Rahm is Arabic رَحْم (Raḥm) 'mercy, compassion', from the root ر ح م (r-ḥ-m). CRITICAL SOURCE ERROR: the source gave the Latin string 'Rahm' instead of a script form. The source gloss 'Mercy, Compassion, Womb' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rahma": ("رَحْمَة", "رحمہ", "رحمه", "रहमा", "رحمه", "rahma", "Arabic", "Female",
           "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
           "Rahma is Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "rahmaa": ("رَحْمَة", "رحمہ", "رحمه", "रहमा", "رحمه", "rahmaa", "Arabic", "Female",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
            "Rahmaa is a spelling variant of Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Grace, Compassion' is broadly consistent. Same name as rahma."),
 "rahmah": ("رَحْمَة", "رحمہ", "رحمه", "रहमा", "رحمه", "rahmah", "Arabic", "Female",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
            "Rahmah is Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Mercy' is consistent. Same name as rahma."),
 "rahman": ("رَحْمَان", "رحمان", "رحمان", "रहमान", "رحمان", "rahman", "Arabic", "Male",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَان (Raḥmān)", False, "high",
            "Rahman is Arabic رَحْمَان (Raḥmān) 'the Most Merciful', from the root ر ح م (r-ḥ-m). CRITICAL SOURCE ERROR: the source gave رحمن (a non-standard form). The source gloss 'Compassionate, Merciful' is consistent."),
 "rahmat": ("رَحْمَة", "رحمت", "رحمت", "रहमत", "رحمت", "rahmat", "Arabic", "Male",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
            "Rahmat is Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Mercy, Compassion' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rahmath": ("رَحْمَة", "رحمت", "رحمت", "रहमत", "رحمت", "rahmath", "Arabic", "Female",
             "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
             "Rahmath is a spelling variant of Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Mercy, Compassion' is consistent. Same name as rahmat."),
 "rahmi": ("رَحْمِي", "رحمی", "رحمی", "रहमी", "رحمي", "rahmi", "Arabic", "Male",
           "Arabic رَحْمِي (Raḥmī) 'of mercy'", False, "high",
           "Rahmi is Arabic رَحْمِي (Raḥmī) 'of mercy', a relational adjective from رَحْمَة (raḥma). CRITICAL SOURCE ERROR: the source gave رحمي (a non-standard form). The source gloss 'Mercy, compassion' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rai": ("رَائِي", "رائی", "رائی", "राई", "رائی", "rai", "Arabic", "Male",
         "Arabic رَائِي (Rāʾī)", False, "medium",
         "Rai is recorded as Arabic رَائِي (Rāʾī), a male given name. CRITICAL SOURCE ERROR: the source gave رائي (a non-standard form). The source gloss 'Sun, Light' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "raid": ("رَعْد", "رعد", "رعد", "राद", "رعد", "raid", "Arabic", "Male",
          "Arabic root ر ع د (r-ʿ-d); رَعْد (Raʿd)", False, "high",
          "Raid is a spelling variant of Arabic رَعْد (Raʿd) 'thunder', from the root ر ع د (r-ʿ-d). CRITICAL SOURCE ERROR: the source gave رعد (a non-standard form). The source gloss 'Thunder' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as raad."),
 "raida": ("رَائِدَة", "رائدہ", "رائده", "राइदा", "رائده", "raida", "Arabic", "Female",
           "Arabic root ر و د (r-w-d); رَائِدَة (Rāʾida)", False, "high",
           "Raida is Arabic رَائِدَة (Rāʾida) 'leader, pioneer' (feminine), from the root ر و د (r-w-d). CRITICAL SOURCE ERROR: the source gave رايدة (a non-standard form). The source gloss 'Rider, Traveler' is unsupported and has been replaced with the lexical sense. Same name as raeda."),
 "raidah": ("رَائِدَة", "رائدہ", "رائده", "राइदा", "رائده", "raidah", "Arabic", "Female",
            "Arabic root ر و د (r-w-d); رَائِدَة (Rāʾida)", False, "high",
            "Raidah is Arabic رَائِدَة (Rāʾida) 'leader, pioneer' (feminine), from the root ر و د (r-w-d). The source gloss 'Journey, Travel' is unsupported and has been replaced with the lexical sense. Same name as raeda."),
 "raif": ("رَءُوف", "رئيف", "رئوف", "रईफ़", "رئيف", "raif", "Arabic", "Male",
          "Arabic root ر أ ف (r-ʾ-f); رَءُوف (Raʾūf)", False, "high",
          "Raif is Arabic رَءُوف (Raʾūf) 'compassionate, kind', from the root ر أ ف (r-ʾ-f). CRITICAL SOURCE ERROR: the source gave رَئِف (a non-standard form). The source gloss 'Joy, gladness, pleasure' is unsupported and has been replaced with the lexical sense. Same name as ra-uf."),
 "raifa": ("رَئِيفَة", "رئيفہ", "رئوفه", "रईफ़ा", "رئيفه", "raifa", "Arabic", "Female",
           "Arabic root ر أ ف (r-ʾ-f); رَئِيفَة (Raʾīfa)", False, "high",
           "Raifa is Arabic رَئِيفَة (Raʾīfa) 'compassionate, kind' (feminine), from the root ر أ ف (r-ʾ-f). The source gloss 'Little one' is unsupported and has been replaced with the lexical sense."),
 "raiha": ("رَائِحَة", "رائحہ", "رایحه", "राइहा", "رایحه", "raiha", "Arabic", "Female",
           "Arabic root ر و ح (r-w-ḥ); رَائِحَة (Rāʾiḥa)", False, "high",
           "Raiha is Arabic رَائِحَة (Rāʾiḥa) 'fragrance, scent', from the root ر و ح (r-w-ḥ). CRITICAL SOURCE ERROR: the source gave ريحا (a non-standard form). The source gloss 'Gentle, kind, beautiful' is unsupported and has been replaced with the lexical sense."),
 "raihaan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "raihaan", "Arabic", "Male",
             "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
             "Raihaan is Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). The source gloss 'Gardener of Paradise' is unsupported and has been replaced with the lexical sense. Same name as raihan."),
 "raihan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "raihan", "Arabic", "Male",
            "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
            "Raihan is Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). The source gloss 'Fragrant, Sweet-Smelling' is broadly consistent."),
 "raihana": ("رَيْحَانَة", "ریحانہ", "ریحانه", "रैहाना", "ریحانه", "raihana", "Arabic", "Female",
             "Arabic root ر و ح (r-w-ḥ); رَيْحَانَة (Rayḥāna)", False, "high",
             "Raihana is Arabic رَيْحَانَة (Rayḥāna) 'fragrant herb, basil' (feminine), from the root ر و ح (r-w-ḥ). The source gloss 'Garden of Paradise' is unsupported and has been replaced with the lexical sense. Same name as raihanah."),
 "raihanah": ("رَيْحَانَة", "ریحانہ", "ریحانه", "रैहाना", "ریحانه", "raihanah", "Arabic", "Female",
              "Arabic root ر و ح (r-w-ḥ); رَيْحَانَة (Rayḥāna)", False, "high",
              "Raihanah is Arabic رَيْحَانَة (Rayḥāna) 'fragrant herb, basil' (feminine), from the root ر و ح (r-w-ḥ). The source gloss 'Fragrance of Paradise' is unsupported and has been replaced with the lexical sense. Same name as raihana."),
 "raika": ("رَايِكَة", "رائیکا", "رایکا", "राइका", "رایکا", "raika", "Arabic", "Female",
           "Arabic رَايِكَة (Rāyika)", False, "medium",
           "Raika is recorded as Arabic رَايِكَة (Rāyika), a female given name. CRITICAL SOURCE ERROR: the source gave رايكا (a non-standard form). The source gloss 'Little Princess' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raima": ("رَيْمَة", "ریمہ", "ریما", "रैमा", "ریمه", "raima", "Arabic", "Female",
           "Arabic رَيْمَة (Rayma)", False, "high",
           "Raima is Arabic رَيْمَة (Rayma), a female given name. CRITICAL SOURCE ERROR: the source gave ريماء (a non-standard form). The source gloss 'Gentle, delicate, beautiful' is unsupported and has been replaced with the documented identification."),
 "raimah": ("رَائِمَة", "رائمہ", "رائمه", "राइमा", "رائمه", "raimah", "Arabic", "Female",
            "Arabic رَائِمَة (Rāʾima)", False, "medium",
            "Raimah is recorded as Arabic رَائِمَة (Rāʾima), a female given name. CRITICAL SOURCE ERROR: the source gave رائم ة (a broken form). The source gloss 'Garden' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raiq": ("رَائِق", "رائق", "رائق", "राइक़", "رائق", "raiq", "Arabic", "Male",
          "Arabic root ر و ق (r-w-q); رَائِق (Rāʾiq)", False, "high",
          "Raiq is Arabic رَائِق (Rāʾiq) 'clear, pure', from the root ر و ق (r-w-q). CRITICAL SOURCE ERROR: the source gave رائق (a non-standard form). The source gloss 'thunderbolt' is unsupported and has been replaced with the lexical sense."),
 "rais": ("رَئِيس", "رئیس", "رئیس", "रईस", "رئیس", "rais", "Arabic", "Male",
          "Arabic root ر أ س (r-ʾ-s); رَئِيس (Raʾīs)", False, "high",
          "Rais is Arabic رَئِيس (Raʾīs) 'leader, chief', from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source gave رائس (a non-standard form). The source gloss 'Master, Leader' is broadly consistent. Same name as raees."),
 "raisa": ("رَئِيسَة", "رئیسہ", "رئیسه", "रईसा", "رئیسه", "raisa", "Arabic", "Female",
           "Arabic root ر أ س (r-ʾ-s); رَئِيسَة (Raʾīsa)", False, "high",
           "Raisa is Arabic رَئِيسَة (Raʾīsa) 'leader, chief' (feminine), from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source gave رايسة (a non-standard form). The source gloss 'Garden' is unsupported and has been replaced with the lexical sense. Same name as raeesa."),
 "raisah": ("رَئِيسَة", "رئیسہ", "رئیسه", "रईसा", "رئیسه", "raisah", "Arabic", "Female",
            "Arabic root ر أ س (r-ʾ-s); رَئِيسَة (Raʾīsa)", False, "high",
            "Raisah is Arabic رَئِيسَة (Raʾīsa) 'leader, chief' (feminine), from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source gave رائس ة (a broken form). The source gloss 'Gentle' is unsupported and has been replaced with the lexical sense. Same name as raeesa."),
 "raisha": ("رَايِشَة", "رایشہ", "رایشا", "राइशा", "رایشا", "raisha", "Arabic", "Female",
            "Arabic رَايِشَة (Rāyisha)", False, "medium",
            "Raisha is recorded as Arabic رَايِشَة (Rāyisha), a female given name. CRITICAL SOURCE ERROR: the source gave رايشة (a non-standard form). The source gloss 'Little Princess' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raiya": ("رَايَة", "رایہ", "رایا", "राया", "رایا", "raiya", "Arabic", "Female",
           "Arabic رَايَة (Rāya)", False, "medium",
           "Raiya is recorded as Arabic رَايَة (Rāya), a female given name. The source gloss 'Hopeful guardian' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as raaya."),
 "raiyan": ("رَيَّان", "ریان", "ریان", "रैयान", "ریان", "raiyan", "Arabic", "Male",
            "Arabic root ر و ي (r-w-y); رَيَّان (Rayyān)", False, "high",
            "Raiyan is Arabic رَيَّان (Rayyān) 'sated, refreshed', from the root ر و ي (r-w-y). CRITICAL SOURCE ERROR: the source gave ريان (a non-standard form). The source gloss 'Gazer' is unsupported and has been replaced with the lexical sense."),
 "raja": ("رَاجَا", "راجہ", "راجا", "राजा", "راجا", "raja", "Sanskrit", "Male",
          "Sanskrit राजन् (rājan) 'king'", False, "high",
          "Raja is a male given name from Sanskrit राजन् (rājan) 'king'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Sanskrit/Hindi. The source gloss 'ruler, king' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rajaa": ("رَجَاء", "رجاء", "رجاء", "रजा", "رجاء", "rajaa", "Arabic", "Female",
           "Arabic root ر ج و (r-j-w); رَجَاء (Rajāʾ)", False, "high",
           "Rajaa is Arabic رَجَاء (Rajāʾ) 'hope, expectation', from the root ر ج و (r-j-w). The source gloss 'The One who is Returned' is unsupported and has been replaced with the lexical sense."),
 "rajab": ("رَجَب", "رجب", "رجب", "रजब", "رجب", "rajab", "Arabic", "Male",
           "Arabic رَجَب (Rajab), the seventh Islamic month", False, "high",
           "Rajab is Arabic رَجَب (Rajab), the seventh month of the Islamic calendar, used as a male given name. The source gloss 'Seventh month of the Islamic calendar' is consistent."),
 "rajah": ("رَاجَا", "راجہ", "راجا", "राजा", "راجا", "rajah", "Sanskrit", "Male",
           "Sanskrit राजन् (rājan) 'king'", False, "high",
           "Rajah is a male given name from Sanskrit राजन् (rājan) 'king'. CRITICAL SOURCE ERROR: the source gave علي (a different name) and labelled the origin Arabic; the word is Sanskrit/Hindi. The source gloss 'King, Ruler' is consistent. Same name as raja."),
 "rajeh": ("رَاجِح", "راجح", "راجح", "राजिह", "راجح", "rajeh", "Arabic", "Male",
           "Arabic root ر ج ح (r-j-ḥ); رَاجِح (Rājiḥ)", False, "high",
           "Rajeh is Arabic رَاجِح (Rājiḥ) 'preponderant, likely', from the root ر ج ح (r-j-ḥ). The source gloss 'Victorious' is unsupported and has been replaced with the lexical sense."),
 "raji": ("رَاجِي", "راجی", "راجی", "राजी", "راجي", "raji", "Arabic", "Male",
          "Arabic root ر ج و (r-j-w); رَاجِي (Rājī)", False, "high",
          "Raji is Arabic رَاجِي (Rājī) 'hoping, expectant', from the root ر ج و (r-j-w). CRITICAL SOURCE ERROR: the source gave the Latin string 'Raji' instead of a script form. The source gloss 'Content, Satisfied' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rajiya": ("رَاجِيَة", "راجیہ", "راجیه", "राजिया", "راجیه", "rajiya", "Arabic", "Female",
            "Arabic root ر ج و (r-j-w); رَاجِيَة (Rājiya)", False, "high",
            "Rajiya is Arabic رَاجِيَة (Rājiya) 'hoping, expectant' (feminine), from the root ر ج و (r-j-w). The source gloss 'Gentle' is unsupported and has been replaced with the lexical sense."),
 "rajwa": ("رَجْوَة", "رجوہ", "رجوا", "रजवा", "رجوا", "rajwa", "Arabic", "Female",
           "Arabic root ر ج و (r-j-w); رَجْوَة (Rajwa)", False, "high",
           "Rajwa is Arabic رَجْوَة (Rajwa) 'hope, expectation', from the root ر ج و (r-j-w). CRITICAL SOURCE ERROR: the source gave the Latin string 'Rajwa' instead of a script form. The source gloss 'Little Rain' is unsupported and has been replaced with the lexical sense."),
 "rakan": ("رَكَان", "رکان", "رکان", "रकान", "رکان", "rakan", "Arabic", "Male",
           "Arabic root ر ك ن (r-k-n); رَكَان (Rakān)", False, "high",
           "Rakan is Arabic رَكَان (Rakān) 'firm, steady', from the root ر ك ن (r-k-n). CRITICAL SOURCE ERROR: the source gave راكان (a non-standard form). The source gloss 'Helper' is unsupported and has been replaced with the lexical sense."),
 "rakeeb": ("رَقِيب", "رقیب", "رقیب", "रक़ीब", "رقیب", "rakeeb", "Arabic", "Male",
            "Arabic root ر ق ب (r-q-b); رَقِيب (Raqīb)", False, "high",
            "Rakeeb is Arabic رَقِيب (Raqīb) 'watcher, guardian', from the root ر ق ب (r-q-b). CRITICAL SOURCE ERROR: the source gave رقيب (a non-standard form). The source gloss 'Protector, Defender' is broadly consistent."),
 "rakeem": ("رَكِيم", "رکیم", "رکیم", "रकीम", "رکیم", "rakeem", "Arabic", "Male",
            "Arabic رَكِيم (Rakīm)", False, "medium",
            "Rakeem is recorded as Arabic رَكِيم (Rakīm), a male given name. CRITICAL SOURCE ERROR: the source gave رکیم (a non-standard form using Persian kāf). The source gloss 'Strong, capable' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raki": ("رَاكِي", "راکی", "راکی", "राकी", "راکی", "raki", "Arabic", "Male",
          "Arabic رَاكِي (Rākī)", False, "medium",
          "Raki is recorded as Arabic رَاكِي (Rākī), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Raki' instead of a script form. The source gloss 'Contentment, happiness' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
}
