# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 30 (huthayfa..inan).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": iba -> "Iba" (Latin); ibad -> عبد (should be
   عباد); ibrat -> إبرات (should be عبرة); ibtihaj -> ابتھاج (Urdu letters);
   ibtihal -> ابتھال (Urdu letters); id -> عد (should be عيد); ifra -> إفراء
   (should be عفراء); ifrah -> إفرح (should be إفراح); ihab -> إحب (should be إهاب);
   iham -> أح م (broken); ihtisham -> أيثم (a different word); ijaaz -> إجاز
   (should be إجازة); ijaz -> إياز (should be إجاز); ikhlaq -> إخلاق (should be
   أخلاق); ikra -> إكرا (should be إكرام); ilam -> إسلام (should be إعلام);
   ilhaan -> إلهان (should be إلهام); ilhem -> إلهم (should be إلهام);
   iliya -> علية (should be إليا); ilma -> إلما; ilman -> إلمأن (broken);
   iltaf -> إلطف (should be ألطاف); imaad -> إِمَاعُد (broken, should be عماد);
   imen -> إيمن (should be إيمان); imra -> عميرة; imrana -> إمرانة;
   imtithal -> إمثال (should be امتثال); imtiyaz -> امتیاز (Urdu letters);
   inaaya -> عيناية (should be عناية); inam -> إِنَام (should be إنعام);
   inan -> إنان (should be عنان); ilana/imram -> Latin in the Arabic column.
 * DEGARBLED / WRONG glosses: huthayfa 'Friend of the Prophet' (proper name);
   huzaif 'Successor, Supporter' (proper name); huzaifa 'Graceful Lion' (proper
   name); huzefa 'Friend of Prophet Husain' (proper name); hyder 'Successor, Guide'
   (should be 'lion'); ibaa 'Mother, Lady' (should be 'refusal, disdain');
   ibtesam 'Astonishment, Surprise, Marvel' (should be 'smile'); ibtihaj 'Pioneer,
   Initiator' (should be 'joy, delight'); ibtihal 'To search, explore, discover'
   (should be 'supplication'); ibtissem 'Gift from Allah' (should be 'smile');
   id 'Power, Lord, Master' (should be 'festival'); idrees 'Servant of Allah'
   (proper name); ied 'Night' (should be 'festival'); iffah 'Exempt, Free'
   (should be 'chastity'); ifrah 'Growth' (should be 'rejoicing'); ihab 'Given by
   Allah' (should be 'leather, hide'); ijlal 'gentle wind' (should be
   'glorification'); ikha 'Gift, Reward' (should be 'brotherhood'); ikhlaq 'Gift,
   Reward' (should be 'morals, character'); iklil 'Precious one, treasure'
   (should be 'crown, wreath'); ikra 'Raisin' (unsupported); ilaf 'Rain, shower'
   (should be 'familiarity, covenant'); ilam 'Light, Illumination' (should be
   'informing'); ilan 'Sunlight' (should be 'announcement'); imara 'Prosperity,
   growth' (should be 'architecture'); imdad 'Gift, Bounty' (should be 'aid,
   support'); imtithal 'Preservation, Protection' (should be 'compliance');
   inaaya 'Innovative Gift' (should be 'care, providence'); inam 'Leader,
   Commander' (should be 'granting, bestowal'); inan 'Gift, Blessing' (should be
   'reins'); ilhan 'First Cry of a Newborn' (unsupported); ilhem 'Heavenly,
   celestial' (unsupported); imed 'Reward, Gift' (unsupported).
 * MISLABELLED ORIGIN: ilana (Hebrew), ilhan (Turkish), imram (English/unknown).
 * GENDER ERRORS: ibad, ibn, ibr, ibrah, ibrat, id, idrak, ihab, ihtisham, ijaaz,
   ijaz, ikhlaq, ikhwan, ikraam, ilan, ilhaam, ilhaan, ilham, ilhan, ilias, iliya,
   ilman, ilmi, iltaf, imaad, imad, imam, imra, imraan, imram, imtiaaz, imtithal,
   inab, inam, inan were labelled female or unisex where documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: ibrahim, ibtisam, idris, iffat, ilyas, imane,
   imran, inaam (8-key stubs); iba, ibr, ibrat, ifra, ifran, iftin, iham, ihsana,
   ijaz, ikra, ilana, ilhaan, ilhem, ilman, ilyan, ilyana, imana, imed, imen,
   imra, imram, imrana, inan.
 * DUPLICATE CLUSTERS: huthayfa/huzaif/huzaifa/huzaifah/huzefa;
   ibtesam/ibtisam/ibtissem; idrees/idris; ihsaan/ihsan/ihsana;
   ijaaz/ijaz; ikraam/ikram; ilhaam/ilham; ilhaan/ilhan/ilhem;
   ilias/iliya/ilya/ilyas; imaad/imad; imaan/iman/imane/imani;
   imraan/imran/imrana; imtiaaz/imtiaz/imtiyaz; inaam/inam.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated29 import GLOSSES as _G29

GLOSSES = dict(_G29)
GLOSSES.update({
    "hudhayfa": {"en": "Hudhayfa (male given name)", "ur": "حذیفہ (مردانہ نام)", "fa": "حذیفه (نام مردانه)", "hi": "हुज़ैफ़ा (पुरुष नाम)", "ps": "حذیفه (نر نوم)", "ar": "حُذَيْفَة (اسم علم مذكر)"},
    "huwaida": {"en": "Huwaida; a female given name", "ur": "ہویدہ (زنانہ نام)", "fa": "هویدا (نام زنانه)", "hi": "हुवैदा (स्त्री नाम)", "ps": "هویده (ښځينه نوم)", "ar": "حُوَيْدَة (اسم علم مؤنث)"},
    "huzayma": {"en": "Huzayma; a female given name", "ur": "حزیمہ (زنانہ نام)", "fa": "حزیمه (نام زنانه)", "hi": "हुज़ैमा (स्त्री नाम)", "ps": "حزیمه (ښځينه نوم)", "ar": "حُزَيْمَة (اسم علم مؤنث)"},
    "refusal": {"en": "Refusal, disdain, aversion", "ur": "انکار، نفرت، گریز", "fa": "امتناع، بیزاری، سرپیچی", "hi": "इनकार, घृणा, विरक्ति", "ps": "انکار، کرکه، ډډه", "ar": "الإباء، الرفض، النفور"},
    "servants": {"en": "Servants, worshippers (plural of ʿabd)", "ur": "بندے، عبادت کرنے والے", "fa": "بندگان، پرستندگان", "hi": "बंदे, उपासक", "ps": "بندګان، عبادت کوونکي", "ar": "العباد، جمع عبد"},
    "son_of": {"en": "Son of (used in patronymics, not a given name)", "ur": "ابن، بیٹا (نام کا جزو)", "fa": "پسرِ (در نام پدری)", "hi": "पुत्र (नाम का अंश)", "ps": "د ... زوی (په نوم کې)", "ar": "ابن، جزء في النسب"},
    "ibrahim": {"en": "Ibrahim; the Qur'anic form of Abraham", "ur": "ابراہیم، قرآن میں ابراہیم", "fa": "ابراهیم، صورت قرآنی ابراهیم", "hi": "इब्राहीम, क़ुरआन में इब्राहीम", "ps": "ابراهیم، په قرآن کې ابراهیم", "ar": "إِبْرَاهِيم، النبي المذكور في القرآن"},
    "righteousness": {"en": "Righteousness, virtuous deed, piety", "ur": "نیکی، بھلائی، تقویٰ", "fa": "نیکوکاری، احسان، پرهیزگاری", "hi": "नेकी, सदाचार, पुण्य", "ps": "نیکي، ښېګڼه، تقوا", "ar": "الإبرار، البرّ، الصلاح"},
    "lesson": {"en": "Lesson, warning, admonition", "ur": "عبرت، سبق، نصیحت", "fa": "عبرت، پند، درس", "hi": "सबक़, शिक्षा, नसीहत", "ps": "عبرت، درس، نصیحت", "ar": "العبرة، الموعظة، الدرس"},
    "smile": {"en": "Smile, smiling", "ur": "مسکراہٹ، تبسم", "fa": "لبخند، تبسم", "hi": "मुस्कान, स्मित", "ps": "مسکا، تبسم", "ar": "الابتسام، التبسم"},
    "joy_delight": {"en": "Joy, delight, gladness", "ur": "خوشی، شادمانی، مسرت", "fa": "شادی، خوشحالی، سرور", "hi": "खुशी, आनंद, प्रसन्नता", "ps": "خوښي، مېله، مسرت", "ar": "الابتهاج، الفرح، السرور"},
    "supplication": {"en": "Supplication, humble prayer", "ur": "دعا، التجا، مناجات", "fa": "نیایش، دعا، تضرع", "hi": "प्रार्थना, दुआ, विनती", "ps": "دعا، مناجات، زاري", "ar": "الابتهال، الدعاء، التضرع"},
    "festival": {"en": "Festival, feast, celebration", "ur": "عید، تہوار، جشن", "fa": "عید، جشن، جشنواره", "hi": "ईद, त्योहार, उत्सव", "ps": "عید، اختر، جشن", "ar": "العيد، الاحتفال، المهرجان"},
    "idris": {"en": "Idris; a prophet mentioned in the Qur'an", "ur": "ادریس، قرآن میں مذکور نبی", "fa": "ادریس، پیامبر مذکور در قرآن", "hi": "इदरीस, क़ुरआन में उल्लिखित पैगंबर", "ps": "ادریس، په قرآن کې ذکر شوی پیغمبر", "ar": "إِدْرِيس، نبي مذكور في القرآن"},
    "comprehension": {"en": "Comprehension, perception, realization", "ur": "ادراک، سمجھ، فہم", "fa": "ادراک، فهم، دریافت", "hi": "बोध, समझ, ज्ञान", "ps": "ادراک، پوهه، فهم", "ar": "الإدراك، الفهم، الوعي"},
    "jesus": {"en": "Jesus; the Qur'anic form of the name", "ur": "عیسیٰ، قرآن میں عیسیٰ", "fa": "عیسی، صورت قرآنی عیسی", "hi": "ईसा, क़ुरआन में ईसा", "ps": "عیسی، په قرآن کې عیسی", "ar": "عِيسَى، النبي المذكور في القرآن"},
    "chastity": {"en": "Chastity, virtue, self-restraint", "ur": "عفت، پاکدامنی، پرہیزگاری", "fa": "عفت، پاکدامنی، پارسایی", "hi": "सतीत्व, पवित्रता, संयम", "ps": "عفت، پاکدامني، ځان ساتنه", "ar": "العفّة، الطهارة، الامتناع"},
    "rejoicing": {"en": "Rejoicing, making glad, delight", "ur": "خوشی دینا، شادمانی", "fa": "شادکردن، شادمانی", "hi": "प्रसन्न करना, आनंद", "ps": "خوښول، مېله", "ar": "الإفراح، الإسعاد، الفرح"},
    "pride_glory": {"en": "Pride, glory, distinction", "ur": "افتخار، فخر، شان", "fa": "افتخار، سرافرازی، جلال", "hi": "गौरव, गर्व, प्रतिष्ठा", "ps": "افتخار، ویاړ، شان", "ar": "الافتخار، الفخر، العزّ"},
    "leather": {"en": "Leather, hide, skin", "ur": "چمڑا، کھال", "fa": "چرم، پوست", "hi": "चमड़ा, खाल", "ps": "څرمن، پوستکی", "ar": "الإهاب، الجلد، المسك"},
    "excellence": {"en": "Excellence, perfection, benevolence", "ur": "احسان، بھلائی، کمال", "fa": "احسان، نیکوکاری، کمال", "hi": "इहसान, भलाई, उत्कृष्टता", "ps": "احسان، ښېګڼه، بشپړتيا", "ar": "الإحسان، الكمال، البرّ"},
    "modesty_decorum": {"en": "Modesty, decorum, dignified restraint", "ur": "احتشام، وقار، شرم", "fa": "احتشام، وقار، آزرم", "hi": "शालीनता, गरिमा, संकोच", "ps": "احتشام، وقار، شرم", "ar": "الاحتشام، الوقار، الحياء"},
    "permission": {"en": "Permission, authorization, license", "ur": "اجازت، منظوری، سند", "fa": "اجازه، پروانه، رخصت", "hi": "अनुमति, इजाज़त, लाइसेंस", "ps": "اجازه، منظوري، رخصت", "ar": "الإجازة، الإذن، الرخصة"},
    "glorification": {"en": "Glorification, honor, exaltation", "ur": "اجلال، تعظیم، بزرگی", "fa": "اجلال، بزرگداشت، تعظیم", "hi": "महिमा, सम्मान, प्रतिष्ठा", "ps": "اجلال، درناوی، لویي", "ar": "الإجلال، التعظيم، التبجيل"},
    "brotherhood": {"en": "Brotherhood, fraternity", "ur": "اخوت، بھائی چارہ", "fa": "برادری، اخوت", "hi": "भाईचारा, बंधुत्व", "ps": "ورورولي، اخوت", "ar": "الإخاء، الأخوّة، الصحبة"},
    "morals": {"en": "Morals, character, ethics", "ur": "اخلاق، کردار، سیرت", "fa": "اخلاق، خوی، منش", "hi": "नैतिकता, चरित्र, आचरण", "ps": "اخلاق، کرکټر، سیرت", "ar": "الأخلاق، السجايا، الطبع"},
    "sincerity": {"en": "Sincerity, purity of intention", "ur": "اخلاص، سچائی، خلوص", "fa": "اخلاص، پاکدلی، صداقت", "hi": "निष्ठा, सच्चाई, शुद्धता", "ps": "اخلاص، رښتيا، پاک زړه", "ar": "الإخلاص، الصفاء، النقاء"},
    "brothers": {"en": "Brothers, brethren", "ur": "بھائی، اخوان", "fa": "برادران، اخوان", "hi": "भाई, बंधु", "ps": "وڼده، وروڼه", "ar": "الإخوان، الأخوة، الأصحاب"},
    "crown": {"en": "Crown, wreath, diadem", "ur": "تاج، اکلیرا، سہرا", "fa": "تاج، افسر، اکلیل", "hi": "मुकुट, ताज, सेहरा", "ps": "تاج، اکرا", "ar": "الإكليل، التاج، العصابة"},
    "honoring": {"en": "Honoring, generosity, respect", "ur": "اکرام، عزت، احترام", "fa": "اکرام، بزرگداشت، احترام", "hi": "सम्मान, आदर, उदारता", "ps": "اکرام، درناوی، عزت", "ar": "الإكرام، التكريم، الاحترام"},
    "familiarity": {"en": "Familiarity, covenant, safe conduct", "ur": "مانوسیت، عہد، امان", "fa": "انس، پیمان، امان", "hi": "परिचय, संधि, अभय", "ps": "انس، تړون، امان", "ar": "الإيلاف، الأنس، العهد"},
    "announcement": {"en": "Announcement, proclamation", "ur": "اعلان، اشتہار، منادی", "fa": "اعلان، اعلامیه، آگهی", "hi": "घोषणा, ऐलान, सूचना", "ps": "اعلان، اعلانونه، خبرتیا", "ar": "الإعلان، الإعلام، النداء"},
    "inspiration": {"en": "Inspiration, divine prompting", "ur": "الہام، وحی، فیضان", "fa": "الهام، وحی، فیض", "hi": "प्रेरणा, इलहाम, वही", "ps": "الهام، وحي، الهام", "ar": "الإلهام، الوحي، الفيض"},
    "elijah": {"en": "Ilyas; the Qur'anic form of Elijah", "ur": "الیاس، قرآن میں الیاس", "fa": "الیاس، صورت قرآنی الیاس", "hi": "इल्यास, क़ुरआन में इल्यास", "ps": "الیاس، په قرآن کې الیاس", "ar": "إِلْيَاس، النبي المذكور في القرآن"},
    "scholarly": {"en": "Of knowledge; scholarly, scientific", "ur": "علمی، علمیاتی، دانشورانہ", "fa": "علمی، دانشی، علمیاتی", "hi": "ज्ञान संबंधी, वैज्ञानिक", "ps": "علمي، پوهنیز", "ar": "العلمي، المنسوب إلى العلم"},
    "kindnesses": {"en": "Kindnesses, favors, gentle treatment", "ur": "الطاف، مہربانیاں، نوازشیں", "fa": "الطاف، مهربانیها، لطفها", "hi": "कृपाएँ, मेहरबानियाँ", "ps": "الطاف، مهربانۍ", "ar": "الألطاف، اللطف، الإحسان"},
    "pillar": {"en": "Pillar, support, mainstay", "ur": "ستون، سہارا، عماد", "fa": "ستون، پشتیبان، عماد", "hi": "स्तंभ, सहारा, आधार", "ps": "ستون، ملاتړ، سهار", "ar": "العماد، السند، الدعامة"},
    "faith": {"en": "Faith, belief, trust", "ur": "ایمان، یقین، عقیدہ", "fa": "ایمان، باور، اعتقاد", "hi": "ईमान, विश्वास, आस्था", "ps": "ایمان، باور، عقیده", "ar": "الإيمان، الاعتقاد، اليقين"},
    "leader_prayer": {"en": "Leader; prayer leader, model", "ur": "امام، پیشوا، رہنما", "fa": "امام، پیشوا، رهبر", "hi": "इमाम, नेता, पेशवा", "ps": "امام، مشر، لارښود", "ar": "الإمام، القائد، القدوة"},
    "architecture": {"en": "Architecture, building, construction", "ur": "عمارت، تعمیر، معماری", "fa": "معماری، ساختمان، بنا", "hi": "वास्तुकला, निर्माण, इमारत", "ps": "معماري، ودانۍ، جوړښت", "ar": "العمارة، البناء، التشييد"},
    "aid": {"en": "Aid, support, reinforcement", "ur": "امداد، مدد، سہارا", "fa": "امداد، کمک، پشتیبانی", "hi": "सहायता, मदद, समर्थन", "ps": "مرسته، ملاتړ، امداد", "ar": "الإمداد، العون، الدعم"},
    "imran": {"en": "Imran; a Qur'anic name, father of Maryam", "ur": "عمران، قرآنی نام، مریم کے والد", "fa": "عمران، نام قرآنی، پدر مریم", "hi": "इमरान, क़ुरआनी नाम, मरयम के पिता", "ps": "عمران، قرآني نوم، د مریم پلار", "ar": "عِمْرَان، اسم قرآني، والد مريم"},
    "distinction": {"en": "Distinction, excellence, privilege", "ur": "امتیاز، برتری، خصوصیت", "fa": "امتیاز، برتری، ویژگی", "hi": "विशिष्टता, श्रेष्ठता, विशेषाधिकार", "ps": "امتیاز، غوره والی، ځانګړتيا", "ar": "الامتياز، التفضيل، الخصوصية"},
    "compliance": {"en": "Compliance, obedience, conformity", "ur": "امتثال، اطاعت، فرمانبرداری", "fa": "امتثال، اطاعت، فرمانبرداری", "hi": "अनुपालन, आज्ञाकारिता", "ps": "امتثال، اطاعت، غاړه ایښودنه", "ar": "الامتثال، الطاعة، الانقياد"},
    "care": {"en": "Care, providence, solicitude", "ur": "عنانایت، دیکھ بھال، پروا", "fa": "عناایت، مراقبت، پروا", "hi": "देखभाल, कृपा, परवाह", "ps": "پاملرنه، عنایت، پروا", "ar": "العناية، الرعاية، الاهتمام"},
    "grape": {"en": "Grape; a grapevine", "ur": "انگور، عنب", "fa": "انگور، عنب", "hi": "अंगूर, द्राक्षा", "ps": "انګور، عنب", "ar": "العنب، الثمرة والكرمة"},
    "bestowal": {"en": "Bestowal, granting, gift", "ur": "انعام، عطا، بخشش", "fa": "انعام، بخشش، عطا", "hi": "इनाम, दान, प्रदान", "ps": "انعام، بخښنه، عطا", "ar": "الإنعام، العطاء، الإحسان"},
    "reins": {"en": "Reins, halter; control", "ur": "عنان، لگام، قابو", "fa": "عنان، افسار، مهار", "hi": "लगाम, बागडोर, नियंत्रण", "ps": "عنان، لګام، کنټرول", "ar": "العنان، اللجام، الزمام"},
    "ilana": {"en": "Ilana (Hebrew name meaning 'tree')", "ur": "ایلانا (عبرانی نام، معنی 'درخت')", "fa": "ایلانا (نام عبری، به معنای 'درخت')", "hi": "इलाना (इब्रानी नाम, अर्थ 'वृक्ष')", "ps": "ایلانا (عبري نوم، مانا 'ونه')", "ar": "إيلانا (اسم عبري بمعنى 'شجرة')"},
    "ilhan": {"en": "Ilhan (Turkish given name)", "ur": "الہان (ترکی نام)", "fa": "الهان (نام ترکی)", "hi": "इलहान (तुर्की नाम)", "ps": "الهان (ترکي نوم)", "ar": "إلهان (اسم تركي)"},
    "ibrahim_name": {"en": "Ibrahim; the Qur'anic form of Abraham", "ur": "ابراہیم، قرآن میں ابراہیم", "fa": "ابراهیم، صورت قرآنی ابراهیم", "hi": "इब्राहीम, क़ुरआन में इब्राहीम", "ps": "ابراهیم، په قرآن کې ابراهیم", "ar": "إِبْرَاهِيم، النبي المذكور في القرآن"},
})

CUR = {
 "huthayfa": ("حذيفة", "حذیفہ", "حذیفه", "हुज़ैफ़ा", "حذیفه", "hudhayfa", "Arabic", "Male",
              "Arabic حُذَيْفَة (Ḥudhayfa)", False, "high",
              "Huthayfa is Arabic حُذَيْفَة (Ḥudhayfa), a well-documented male given name borne by Hudhayfa ibn al-Yaman, a companion of the Prophet Muhammad. The source gloss 'Friend of the Prophet' is unsupported; the name is a proper name. Same name as huzaif, huzaifa, huzaifah and huzefa."),
 "huwaida": ("هويدة", "ہویدہ", "هویدا", "हुवैदा", "هویده", "huwaida", "Arabic", "Female",
             "Arabic حُوَيْدَة (Ḥuwayda)", False, "low",
             "Huwaida is recorded at low confidence. The source gave هويدة and glossed the name 'Compassionate'; حُوَيْدَة (Ḥuwayda) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "huzaif": ("حذيفة", "حذیفہ", "حذیفه", "हुज़ैफ़", "حذیفه", "hudhayfa", "Arabic", "Male",
            "Arabic حُذَيْفَة (Ḥudhayfa)", False, "medium",
            "Huzaif is Arabic حُذَيْفَة (Ḥudhayfa), a well-documented male given name. CRITICAL SOURCE ERROR: the source gave حذيف (truncated) and glossed the name 'Successor, Supporter'; the correct form is حُذَيْفَة. Same name as huthayfa, huzaifa, huzaifah and huzefa."),
 "huzaifa": ("حذيفة", "حذیفہ", "حذیفه", "हुज़ैफ़ा", "حذیفه", "hudhayfa", "Arabic", "Male",
             "Arabic حُذَيْفَة (Ḥudhayfa)", False, "high",
             "Huzaifa is Arabic حُذَيْفَة (Ḥudhayfa), a well-documented male given name borne by Hudhayfa ibn al-Yaman. The source gloss 'Graceful Lion' is unsupported; the name is a proper name. The source labelled the name unisex; documented usage is predominantly male. Same name as huthayfa, huzaif, huzaifah and huzefa."),
 "huzaifah": ("حذيفة", "حذیفہ", "حذیفه", "हुज़ैफ़ा", "حذیفه", "hudhayfa", "Arabic", "Male",
              "Arabic حُذَيْفَة (Ḥudhayfa)", False, "high",
              "Huzaifah is Arabic حُذَيْفَة (Ḥudhayfa), a well-documented male given name borne by Hudhayfa ibn al-Yaman. The source gloss 'The Prophet's Companion' is unsupported; the name is a proper name. Same name as huthayfa, huzaif, huzaifa and huzefa."),
 "huzaimah": ("حزيمة", "حزیمہ", "حزیمه", "हुज़ैमा", "حزیمه", "huzayma", "Arabic", "Female",
              "Arabic حُزَيْمَة (Ḥuzayma)", False, "low",
              "Huzaimah is recorded at low confidence. The source gave حزامة (a different word) and glossed the name 'Blooming, Abundant'; حُزَيْمَة (Ḥuzayma) is a documented female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "huzefa": ("حذيفة", "حذیفہ", "حذیفه", "हुज़ैफ़ा", "حذیفه", "hudhayfa", "Arabic", "Male",
            "Arabic حُذَيْفَة (Ḥudhayfa)", False, "medium",
            "Huzefa is Arabic حُذَيْفَة (Ḥudhayfa), a well-documented male given name. The source gloss 'Friend of Prophet Husain' is unsupported; the name is a proper name. Same name as huthayfa, huzaif, huzaifa and huzaifah."),
 "hyder": ("حيدر", "حیدر", "حیدر", "हैदर", "حیدر", "lion", "Arabic", "Male",
           "Arabic حَيْدَر (Ḥaydar)", False, "high",
           "Hyder is a variant transliteration of Arabic حَيْدَر (Ḥaydar) 'lion; brave, bold', a well-documented Arabic personal name and an epithet of Ali ibn Abi Talib. The source gloss 'Successor, Guide' is unsupported and has been replaced with the lexical sense. Same name as haydar, hayder and heydar."),
 "iba": ("إبا", "ابا", "ابا", "इबा", "ابا", "refusal", "Arabic", "Female",
         "Arabic إِبَاء (Ibāʾ)", False, "low",
         "Iba is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Exalted, Sublime'; إِبَاء (Ibāʾ) 'refusal, disdain' is a documented Arabic word, but its use as a given name and the source gloss could not be confirmed. No confident meaning is asserted. Same name as ibaa."),
 "ibaa": ("إباء", "اباء", "اباء", "इबा", "اباء", "refusal", "Arabic", "Female",
          "Arabic إِبَاء (Ibāʾ)", False, "medium",
          "Ibaa is Arabic إِبَاء (Ibāʾ) 'refusal, disdain, aversion'. The source gloss 'Mother, Lady' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun. Same name as iba."),
 "ibad": ("عباد", "عباد", "عباد", "इबाद", "عباد", "servants", "Arabic", "Male",
          "Plural of عَبْد (ʿabd); عِبَاد (ʿIbād)", False, "medium",
          "Ibad is Arabic عِبَاد (ʿIbād) 'servants, worshippers', the plural of عَبْد (ʿabd). CRITICAL SOURCE ERROR: the source gave عبد (the singular, a different form) and glossed the name 'Servant'; the correct form is عِبَاد. Recorded at medium confidence because the word is primarily a common noun."),
 "ibn": ("ابن", "ابن", "ابن", "इब्न", "ابن", "son_of", "Arabic", "Male",
         "Arabic اِبْن (ibn)", False, "low",
         "Ibn is Arabic اِبْن (ibn) 'son of', a patronymic particle used in Arabic naming, not a given name. The source gloss 'Son of' is consistent, but the item is a naming particle rather than a personal name. No personal-name meaning is asserted."),
 "ibr": ("إبر", "ابر", "ابر", "इब्र", "ابر", "ibrahim_name", "Arabic", "Male",
         "Short form of إِبْرَاهِيم (Ibrāhīm)", False, "low",
         "Ibr is recorded at low confidence. The source gave إبر and glossed the name 'Exalted'; the form is a short form of إِبْرَاهِيم (Ibrāhīm), but the source gloss is unsupported. No confident meaning is asserted."),
 "ibrah": ("إبراهيم", "ابراہیم", "ابراهیم", "इब्राहीम", "ابراهیم", "ibrahim_name", "Arabic", "Male",
           "Qur'anic proper name; إِبْرَاهِيم (Ibrāhīm)", True, "high",
           "Ibrah is a short form of Arabic إِبْرَاهِيم (Ibrāhīm), the Qur'anic form of Abraham, a prophet and the name of a Qur'anic sura. The source gloss 'Friend of Allah' is unsupported; the name is a proper name. Same name as ibraheem, ibrahem, ibrahim and ibrhim."),
 "ibraheem": ("إبراهيم", "ابراہیم", "ابراهیم", "इब्राहीम", "ابراهیم", "ibrahim_name", "Arabic", "Male",
              "Qur'anic proper name; إِبْرَاهِيم (Ibrāhīm)", True, "high",
              "Ibraheem is Arabic إِبْرَاهِيم (Ibrāhīm), the Qur'anic form of Abraham, a prophet and the name of a Qur'anic sura. The source gloss 'Father of Nations' is unsupported; the name is a proper name. Same name as ibrah, ibrahem, ibrahim and ibrhim."),
 "ibrahem": ("إبراهيم", "ابراہیم", "ابراهیم", "इब्राहीम", "ابراهیم", "ibrahim_name", "Arabic", "Male",
             "Qur'anic proper name; إِبْرَاهِيم (Ibrāhīm)", True, "high",
             "Ibrahem is a variant transliteration of Arabic إِبْرَاهِيم (Ibrāhīm), the Qur'anic form of Abraham. The source gloss 'Father of many nations' is unsupported; the name is a proper name. Same name as ibrah, ibraheem, ibrahim and ibrhim."),
 "ibrahim": ("إبراهيم", "ابراہیم", "ابراهیم", "इब्राहीम", "ابراهیم", "ibrahim_name", "Arabic", "Male",
             "Qur'anic proper name; إِبْرَاهِيم (Ibrāhīm)", True, "high",
             "Ibrahim is Arabic إِبْرَاهِيم (Ibrāhīm), the Qur'anic form of Abraham, a prophet and the name of a Qur'anic sura. The source record was an 8-key stub with no data. Same name as ibrah, ibraheem, ibrahem and ibrhim."),
 "ibrar": ("إبرار", "ابرار", "ابرار", "इब्रार", "ابرار", "righteousness", "Arabic", "Male",
           "Arabic root ب ر ر (b-r-r); إِبْرَار (Ibrār)", False, "medium",
           "Ibrar is Arabic إِبْرَار (Ibrār) 'righteousness, virtuous deed, piety', from the root ب ر ر (b-r-r). The source gloss 'Virtuous, Righteous Deed' is consistent."),
 "ibrat": ("عبرة", "عبرت", "عبرت", "इब्रत", "عبرت", "lesson", "Arabic", "Male",
           "Arabic root ع ب ر (ʿ-b-r); عِبْرَة (ʿIbra)", False, "low",
           "Ibrat is recorded at low confidence. The source gave إبرات (a different form) and glossed the name 'Warning, reminder'; عِبْرَة (ʿIbra) 'lesson, warning' is a documented Arabic word, but the source's form and its use as a given name could not be confirmed. No confident meaning is asserted."),
 "ibrhim": ("إبراهيم", "ابراہیم", "ابراهیم", "इब्राहीम", "ابراهیم", "ibrahim_name", "Arabic", "Male",
            "Qur'anic proper name; إِبْرَاهِيم (Ibrāhīm)", True, "medium",
            "Ibrhim is a variant transliteration of Arabic إِبْرَاهِيم (Ibrāhīm), the Qur'anic form of Abraham. The source gloss 'Father of many nations' is unsupported; the name is a proper name. Same name as ibrah, ibraheem, ibrahem and ibrahim."),
 "ibtesam": ("ابتسام", "ابتسام", "ابتسام", "इब्तिसाम", "ابتسام", "smile", "Arabic", "Female",
             "Arabic root ب س م (b-s-m); اِبْتِسَام (Ibtisām)", False, "high",
             "Ibtesam is Arabic اِبْتِسَام (Ibtisām) 'smile, smiling', from the root ب س م (b-s-m). The source gloss 'Astonishment, Surprise, Marvel' is unsupported and has been replaced with the lexical sense. Same name as ibtisam and ibtissem."),
 "ibtihaj": ("ابتهاج", "ابہتاج", "ابتهاج", "इब्तिहाज", "ابتهاج", "joy_delight", "Arabic", "Female",
             "Arabic root ب ه ج (b-h-j); اِبْتِهَاج (Ibtihāj)", False, "medium",
             "Ibtihaj is Arabic اِبْتِهَاج (Ibtihāj) 'joy, delight, gladness', from the root ب ه ج (b-h-j). CRITICAL SOURCE ERROR: the source gave ابتھاج, using Urdu letters in the Arabic column; the correct Arabic form is اِبْتِهَاج. The source gloss 'Pioneer, Initiator' is unsupported and has been replaced with the lexical sense."),
 "ibtihal": ("ابتهال", "ابہتال", "ابتهال", "इब्तिहाल", "ابتهال", "supplication", "Arabic", "Female",
             "Arabic root ب ه ل (b-h-l); اِبْتِهَال (Ibtihāl)", False, "medium",
             "Ibtihal is Arabic اِبْتِهَال (Ibtihāl) 'supplication, humble prayer', from the root ب ه ل (b-h-l). CRITICAL SOURCE ERROR: the source gave ابتھال, using Urdu letters in the Arabic column; the correct Arabic form is اِبْتِهَال. The source gloss 'To search, explore, discover' is unsupported and has been replaced with the lexical sense."),
 "ibtisam": ("ابتسام", "ابتسام", "ابتسام", "इब्तिसाम", "ابتسام", "smile", "Arabic", "Female",
             "Arabic root ب س م (b-s-m); اِبْتِسَام (Ibtisām)", False, "high",
             "Ibtisam is Arabic اِبْتِسَام (Ibtisām) 'smile, smiling', from the root ب س م (b-s-m). The source record was an 8-key stub with no data. Same name as ibtesam and ibtissem."),
 "ibtissem": ("ابتسام", "ابتسام", "ابتسام", "इब्तिसाम", "ابتسام", "smile", "Arabic", "Female",
              "Arabic root ب س م (b-s-m); اِبْتِسَام (Ibtisām)", False, "medium",
              "Ibtissem is a North African transliteration of Arabic اِبْتِسَام (Ibtisām) 'smile, smiling', from the root ب س م (b-s-m). CRITICAL SOURCE ERROR: the source gave ابتسم (a different form) and glossed the name 'Gift from Allah'; the correct form is اِبْتِسَام. Same name as ibtesam and ibtisam."),
 "id": ("عيد", "عید", "عید", "ईद", "عید", "festival", "Arabic", "Male",
        "Arabic root ع و د (ʿ-w-d); عِيد (ʿĪd)", False, "medium",
        "Id is Arabic عِيد (ʿĪd) 'festival, feast, celebration', from the root ع و د (ʿ-w-d). CRITICAL SOURCE ERROR: the source gave عد (a different word) and glossed the name 'Power, Lord, Master'; the correct form is عِيد. Same name as ied."),
 "idrak": ("إدراك", "ادراک", "ادراک", "इदराक", "ادراک", "comprehension", "Arabic", "Male",
           "Arabic root د ر ك (d-r-k); إِدْرَاك (Idrāk)", False, "medium",
           "Idrak is Arabic إِدْرَاك (Idrāk) 'comprehension, perception, realization', from the root د ر ك (d-r-k). The source gloss 'Knowledge, comprehension' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "idrees": ("إدريس", "ادریس", "ادریس", "इदरीस", "ادریس", "idris", "Arabic", "Male",
            "Qur'anic proper name; إِدْرِيس (Idrīs)", True, "high",
            "Idrees is Arabic إِدْرِيس (Idrīs), a prophet mentioned in the Qur'an. The source gloss 'Servant of Allah' is unsupported; the name is a proper name. Same name as idris."),
 "idris": ("إدريس", "ادریس", "ادریس", "इदरीस", "ادریس", "idris", "Arabic", "Male",
           "Qur'anic proper name; إِدْرِيس (Idrīs)", True, "high",
           "Idris is Arabic إِدْرِيس (Idrīs), a prophet mentioned in the Qur'an. The source record was an 8-key stub with no data. Same name as idrees."),
 "ied": ("عيد", "عید", "عید", "ईद", "عید", "festival", "Arabic", "Male",
         "Arabic root ع و د (ʿ-w-d); عِيد (ʿĪd)", False, "medium",
         "Ied is Arabic عِيد (ʿĪd) 'festival, feast, celebration', from the root ع و د (ʿ-w-d). The source gloss 'Night' is unsupported and has been replaced with the lexical sense. Same name as id."),
 "iesa": ("عيسى", "عیسیٰ", "عیسی", "ईसा", "عیسی", "jesus", "Arabic", "Male",
          "Qur'anic proper name; عِيسَى (ʿĪsā)", True, "high",
          "Iesa is Arabic عِيسَى (ʿĪsā), the Qur'anic form of Jesus, a prophet mentioned in the Qur'an. The source gloss 'God's Name, Jesus' is partly unsupported; the name is a proper name."),
 "iffah": ("عفة", "عفت", "عفت", "इफ़्फ़ा", "عفت", "chastity", "Arabic", "Female",
           "Arabic root ع ف ف (ʿ-f-f); عِفَّة (ʿIffa)", False, "high",
           "Iffah is Arabic عِفَّة (ʿIffa) 'chastity, virtue, self-restraint', from the root ع ف ف (ʿ-f-f). The source gloss 'Exempt, Free' is unsupported and has been replaced with the lexical sense. Same name as iffat."),
 "iffat": ("عفة", "عفت", "عفت", "इफ़्फ़त", "عفت", "chastity", "Arabic", "Female",
           "Arabic root ع ف ف (ʿ-f-f); عِفَّة (ʿIffa)", False, "high",
           "Iffat is Arabic عِفَّة (ʿIffa) 'chastity, virtue, self-restraint', from the root ع ف ف (ʿ-f-f); the form عِفَّت is the Persian/Urdu rendering. The source record was an 8-key stub with no data. Same name as iffah."),
 "ifra": ("عفراء", "عفرا", "عفرا", "इफ़रा", "عفرا", "chastity", "Arabic", "Female",
          "Arabic عَفْرَاء (ʿAfrāʾ)", False, "low",
          "Ifra is recorded at low confidence. The source gave إفراء and glossed the name 'First Ray of Sun'; the intended form is likely عَفْرَاء (ʿAfrāʾ), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "ifrah": ("إفراح", "افراح", "افراح", "इफ़राह", "افراح", "rejoicing", "Arabic", "Female",
           "Arabic root ف ر ح (f-r-ḥ); إِفْرَاح (Ifrāḥ)", False, "medium",
           "Ifrah is Arabic إِفْرَاح (Ifrāḥ) 'rejoicing, making glad, delight', from the root ف ر ح (f-r-ḥ). CRITICAL SOURCE ERROR: the source gave إفرح (a different form) and glossed the name 'Growth'; the correct form is إِفْرَاح."),
 "ifran": ("عفران", "عفران", "عفران", "इफ़रान", "عفران", "chastity", "Arabic", "Male",
           "Arabic عَفْرَان (ʿAfrān)", False, "low",
           "Ifran is recorded at low confidence. The source gave إفران and glossed the name 'Free, Sincere'; the form عَفْرَان (ʿAfrān) is a documented male given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "iftikhar": ("إفتخار", "افتخار", "افتخار", "इफ़्तिख़ार", "افتخار", "pride_glory", "Arabic", "Male",
              "Arabic root ف خ ر (f-kh-r); اِفْتِخَار (Iftikhār)", False, "high",
              "Iftikhar is Arabic اِفْتِخَار (Iftikhār) 'pride, glory, distinction', from the root ف خ ر (f-kh-r). The source gloss 'Glory, Honor' is broadly consistent."),
 "iftin": ("إفتين", "افتین", "افتین", "इफ़्तीन", "افتین", "chastity", "Arabic", "Female",
           "Arabic اِفْتِين (Iftīn)", False, "low",
           "Iftin is recorded at low confidence. The source gave إفتين and glossed the name 'Moon, Bright'; the form اِفْتِين (Iftīn) is a documented Somali female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "ihab": ("إهاب", "اہاب", "اهاب", "इहाब", "اهاب", "leather", "Arabic", "Male",
          "Arabic إِهَاب (Ihāb)", False, "low",
          "Ihab is recorded at low confidence. The source gave إحب (a different form) and glossed the name 'Given by Allah'; إِهَاب (Ihāb) 'leather, hide' is a documented Arabic word, but the source's form and gloss could not be confirmed. No confident meaning is asserted."),
 "iham": ("إهام", "اہام", "اهام", "इहाम", "اهام", "inspiration", "Arabic", "Female",
          "Arabic إِهَام (Ihām)", False, "low",
          "Iham is recorded at low confidence. The source gave the broken form أح م and glossed the name 'gift, present'; the form إِهَام (Ihām) is not a well-attested Arabic personal name and the gloss is unsupported. No confident meaning is asserted."),
 "ihsaan": ("إحسان", "احسان", "احسان", "इहसान", "احسان", "excellence", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); إِحْسَان (Iḥsān)", False, "high",
            "Ihsaan is Arabic إِحْسَان (Iḥsān) 'excellence, perfection, benevolence', from the root ح س ن (ḥ-s-n). The source gloss 'Excellence, Grace, Beauty' is broadly consistent. Same name as ihsan and ihsana."),
 "ihsan": ("إحسان", "احسان", "احسان", "इहसान", "احسان", "excellence", "Arabic", "Male",
           "Arabic root ح س ن (ḥ-s-n); إِحْسَان (Iḥsān)", False, "high",
           "Ihsan is Arabic إِحْسَان (Iḥsān) 'excellence, perfection, benevolence', from the root ح س ن (ḥ-s-n). The source gloss 'Perfection, Excellence' is consistent. Same name as ihsaan and ihsana."),
 "ihsana": ("إحسانة", "احسانہ", "احسانه", "इहसाना", "احسانه", "excellence", "Arabic", "Female",
            "Arabic root ح س ن (ḥ-s-n); إِحْسَانَة (Iḥsāna)", False, "low",
            "Ihsana is recorded at low confidence. The source gave إحسانا and glossed the name 'Goodness, Grace'; إِحْسَانَة (Iḥsāna) is the feminine of إِحْسَان (Iḥsān), but the source's form and its independent attestation could not be confirmed. No confident meaning is asserted. Same name as ihsaan and ihsan."),
 "ihtisham": ("احتشام", "احتشام", "احتشام", "इहतिशाम", "احتشام", "modesty_decorum", "Arabic", "Male",
              "Arabic root ح ش م (ḥ-sh-m); اِحْتِشَام (Iḥtishām)", False, "medium",
              "Ihtisham is Arabic اِحْتِشَام (Iḥtishām) 'modesty, decorum, dignified restraint', from the root ح ش م (ḥ-sh-m). CRITICAL SOURCE ERROR: the source gave أيثم (a different word) and glossed the name 'Respect, Reverence, Dedication'; the correct form is اِحْتِشَام."),
 "ijaaz": ("إجازة", "اجازہ", "اجازه", "इजाज़ा", "اجازه", "permission", "Arabic", "Male",
           "Arabic root ج و ز (j-w-z); إِجَازَة (Ijāza)", False, "medium",
           "Ijaaz is Arabic إِجَازَة (Ijāza) 'permission, authorization, license', from the root ج و ز (j-w-z). CRITICAL SOURCE ERROR: the source gave إجاز (truncated) and glossed the name 'Permission, Approval'; the correct form is إِجَازَة. Same name as ijaz."),
 "ijaz": ("إجازة", "اجازہ", "اجازه", "इजाज़", "اجازه", "permission", "Arabic", "Male",
          "Arabic root ج و ز (j-w-z); إِجَازَة (Ijāza)", False, "low",
          "Ijaz is recorded at low confidence. The source gave إياز (a different form) and glossed the name 'Permission, Authorization'; the intended form is likely إِجَازَة (Ijāza), but the source's Arabic column could not be confirmed. No confident meaning is asserted. Same name as ijaaz."),
 "ijlal": ("إجلال", "اجلال", "اجلال", "इजलाल", "اجلال", "glorification", "Arabic", "Male",
           "Arabic root ج ل ل (j-l-l); إِجْلَال (Ijlāl)", False, "medium",
           "Ijlal is Arabic إِجْلَال (Ijlāl) 'glorification, honor, exaltation', from the root ج ل ل (j-l-l). The source gloss 'gentle wind' is unsupported and has been replaced with the lexical sense."),
 "ikha": ("إخاء", "اخاء", "اخاء", "इखा", "اخاء", "brotherhood", "Arabic", "Female",
          "Arabic root أ خ و (ʾ-kh-w); إِخَاء (Ikhāʾ)", False, "medium",
          "Ikha is Arabic إِخَاء (Ikhāʾ) 'brotherhood, fraternity', from the root أ خ و (ʾ-kh-w). The source gloss 'Gift, Reward' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "ikhlaq": ("أخلاق", "اخلاق", "اخلاق", "इख़लाक़", "اخلاق", "morals", "Arabic", "Male",
            "Arabic root خ ل ق (kh-l-q); أَخْلَاق (Akhlāq)", False, "medium",
            "Ikhlaq is Arabic أَخْلَاق (Akhlāq) 'morals, character, ethics', the plural of خُلُق (khuluq), from the root خ ل ق (kh-l-q). CRITICAL SOURCE ERROR: the source gave إخلاق (a different form) and glossed the name 'Gift, Reward'; the correct form is أَخْلَاق."),
 "ikhlas": ("إخلاص", "اخلاص", "اخلاص", "इख़लास", "اخلاص", "sincerity", "Arabic", "Female",
            "Arabic root خ ل ص (kh-l-ṣ); إِخْلَاص (Ikhlāṣ)", False, "high",
            "Ikhlas is Arabic إِخْلَاص (Ikhlāṣ) 'sincerity, purity of intention', from the root خ ل ص (kh-l-ṣ); it is also the title of a Qur'anic sura. The source gloss 'Sincerity' is consistent."),
 "ikhwan": ("إخوان", "اخوان", "اخوان", "इख़वान", "اخوان", "brothers", "Arabic", "Male",
            "Plural of أَخ (akh); إِخْوَان (Ikhwān)", False, "medium",
            "Ikhwan is Arabic إِخْوَان (Ikhwān) 'brothers, brethren', the plural of أَخ (akh). The source gloss 'Brotherhood' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "iklil": ("إكليل", "اکلیل", "اکلیل", "इकलील", "اکلیل", "crown", "Arabic", "Female",
           "Arabic root ك ل ل (k-l-l); إِكْلِيل (Iklīl)", False, "medium",
           "Iklil is Arabic إِكْلِيل (Iklīl) 'crown, wreath, diadem', from the root ك ل ل (k-l-l). The source gloss 'Precious one, treasure' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "ikra": ("إكرام", "اکرام", "اکرام", "इकरा", "اکرام", "honoring", "Arabic", "Female",
          "Arabic root ك ر م (k-r-m); إِكْرَام (Ikrām)", False, "low",
          "Ikra is recorded at low confidence. The source gave إكرا and glossed the name 'Raisin'; the intended form is likely إِكْرَام (Ikrām), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as ikraam and ikram."),
 "ikraam": ("إكرام", "اکرام", "اکرام", "इकराम", "اکرام", "honoring", "Arabic", "Male",
            "Arabic root ك ر م (k-r-m); إِكْرَام (Ikrām)", False, "high",
            "Ikraam is Arabic إِكْرَام (Ikrām) 'honoring, generosity, respect', from the root ك ر م (k-r-m). The source gloss 'Honor, respect, compassion' is broadly consistent. Same name as ikra and ikram."),
 "ikram": ("إكرام", "اکرام", "اکرام", "इकराम", "اکرام", "honoring", "Arabic", "Male",
           "Arabic root ك ر م (k-r-m); إِكْرَام (Ikrām)", False, "high",
           "Ikram is Arabic إِكْرَام (Ikrām) 'honoring, generosity, respect', from the root ك ر م (k-r-m). The source gloss 'Generosity, kindness' is broadly consistent. Same name as ikra and ikraam."),
 "ilaf": ("إيلاف", "ایلاف", "ایلاف", "इलाफ़", "ایلاف", "familiarity", "Arabic", "Female",
          "Arabic root أ ل ف (ʾ-l-f); إِيلَاف (Īlāf)", False, "medium",
          "Ilaf is Arabic إِيلَاف (Īlāf) 'familiarity, covenant, safe conduct', from the root أ ل ف (ʾ-l-f); it occurs in the Qur'an (Sūrat Quraysh). The source gloss 'Rain, shower' is unsupported and has been replaced with the lexical sense."),
 "ilam": ("إعلام", "اعلام", "اعلام", "इलाम", "اعلام", "announcement", "Arabic", "Female",
          "Arabic root ع ل م (ʿ-l-m); إِعْلَام (Iʿlām)", False, "low",
          "Ilam is recorded at low confidence. The source gave إسلام (a different word) and glossed the name 'Light, Illumination'; the intended form is likely إِعْلَام (Iʿlām), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "ilan": ("إيلان", "ایلان", "ایلان", "इलान", "ایلان", "announcement", "Arabic", "Male",
          "Arabic إِيلَان (Īlān)", False, "low",
          "Ilan is recorded at low confidence. The source gave إيلان and glossed the name 'Sunlight'; إِيلَان (Īlān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "ilana": ("אילנה", "ایلانا", "ایلانا", "इलाना", "ایلانا", "ilana", "Hebrew", "Female",
           "Hebrew אִילָנָה (Ilanah)", False, "medium",
           "Ilana is Hebrew אִילָנָה (Ilanah) 'tree', a documented Jewish female given name. MISLABELLED ORIGIN: the source recorded the name as Arabic and repeated the Latin string in the Arabic column. The source gloss 'Joy, delight' is unsupported and has been replaced with the Hebrew lexical sense."),
 "ilhaam": ("إلهام", "الہام", "الهام", "इलहाम", "الهام", "inspiration", "Arabic", "Female",
            "Arabic root ل ه م (l-h-m); إِلْهَام (Ilhām)", False, "high",
            "Ilhaam is Arabic إِلْهَام (Ilhām) 'inspiration, divine prompting', from the root ل ه م (l-h-m). The source gloss 'A divine inspiration or revelation' is broadly consistent. Same name as ilham."),
 "ilhaan": ("إلهام", "الہام", "الهام", "इलहान", "الهام", "inspiration", "Arabic", "Female",
            "Arabic root ل ه م (l-h-m); إِلْهَام (Ilhām)", False, "low",
            "Ilhaan is recorded at low confidence. The source gave إلهان (a different form) and glossed the name 'Inner Light'; the intended form is likely إِلْهَام (Ilhām), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as ilhaam and ilham."),
 "ilham": ("إلهام", "الہام", "الهام", "इलहाम", "الهام", "inspiration", "Arabic", "Female",
           "Arabic root ل ه م (l-h-m); إِلْهَام (Ilhām)", False, "high",
           "Ilham is Arabic إِلْهَام (Ilhām) 'inspiration, divine prompting', from the root ل ه م (l-h-m). The source gloss 'Inspiration or intuition' is broadly consistent. Same name as ilhaam."),
 "ilhan": ("إلهان", "الہان", "الهان", "इलहान", "الهان", "ilhan", "Turkish", "Male",
           "Turkish İlhan", False, "low",
           "Ilhan is recorded at low confidence. The source gave إلهان and glossed the name 'First Cry of a Newborn'; İlhan is a Turkish male given name, but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "ilhem": ("إلهام", "الہام", "الهام", "इलहेम", "الهام", "inspiration", "Arabic", "Female",
           "Arabic root ل ه م (l-h-m); إِلْهَام (Ilhām)", False, "low",
           "Ilhem is recorded at low confidence. The source gave إلهم (a different form) and glossed the name 'Heavenly, celestial'; the intended form is likely إِلْهَام (Ilhām), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as ilhaam and ilham."),
 "ilias": ("إلياس", "الیاس", "الیاس", "इल्यास", "الیاس", "elijah", "Arabic", "Male",
           "Qur'anic proper name; إِلْيَاس (Ilyās)", True, "high",
           "Ilias is Arabic إِلْيَاس (Ilyās), the Qur'anic form of Elijah, a prophet mentioned in the Qur'an. The source gloss 'God is my helper' is unsupported; the name is a proper name. Same name as ilya and ilyas."),
 "iliya": ("إليا", "الیا", "الیا", "इलिया", "الیا", "elijah", "Arabic", "Male",
           "Qur'anic proper name; إِلْيَاس (Ilyās)", True, "low",
           "Iliya is recorded at low confidence. The source gave علية (a different name) and glossed the name 'God's Grace'; the intended form is likely إِلْيَاس (Ilyās), but the source's Arabic column could not be confirmed. No confident meaning is asserted. Same name as ilias and ilya."),
 "ilma": ("علم", "علم", "علم", "इल्मा", "علم", "scholarly", "Arabic", "Female",
          "Arabic root ع ل م (ʿ-l-m); عِلْم (ʿIlm)", False, "low",
          "Ilma is recorded at low confidence. The source gave إلما and glossed the name 'Knowledge, Information'; the form is related to عِلْم (ʿIlm) 'knowledge', but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "ilman": ("إلمام", "المام", "المام", "इलमान", "المام", "scholarly", "Arabic", "Male",
           "Arabic root ع ل م (ʿ-l-m); إِلْمَام (Ilmām)", False, "low",
           "Ilman is recorded at low confidence. The source gave the broken form إلمأن and glossed the name 'Knowledge, Guidance'; the form is uncertain and the gloss is unsupported. No confident meaning is asserted."),
 "ilmi": ("علمي", "علمی", "علمی", "इल्मी", "علمي", "scholarly", "Arabic", "Male",
          "Arabic root ع ل م (ʿ-l-m); عِلْمِيّ (ʿIlmiyy)", False, "medium",
          "Ilmi is Arabic عِلْمِيّ (ʿIlmiyy) 'of knowledge; scholarly, scientific', from the root ع ل م (ʿ-l-m). The source gloss 'Knowledge' is broadly consistent. Recorded at medium confidence because the word is primarily an adjective."),
 "iltaf": ("ألطاف", "الطاف", "الطاف", "इलताफ़", "الطاف", "kindnesses", "Arabic", "Male",
           "Plural of لُطْف (luṭf); أَلْطَاف (Alṭāf)", False, "medium",
           "Iltaf is Arabic أَلْطَاف (Alṭāf) 'kindnesses, favors, gentle treatment', the plural of لُطْف (luṭf). CRITICAL SOURCE ERROR: the source gave إلطف (a different form) and glossed the name 'Gentle, kind, soft'; the correct form is أَلْطَاف."),
 "ilya": ("إلياس", "الیاس", "الیاس", "इल्या", "الیاس", "elijah", "Arabic", "Male",
          "Qur'anic proper name; إِلْيَاس (Ilyās)", True, "medium",
          "Ilya is a short form of Arabic إِلْيَاس (Ilyās), the Qur'anic form of Elijah. The source gloss 'God is near' is unsupported; the name is a proper name. Same name as ilias and ilyas."),
 "ilyan": ("إليان", "الیان", "الیان", "इल्यान", "الیان", "elijah", "Arabic", "Male",
           "Arabic إِلْيَان (Ilyān)", False, "low",
           "Ilyan is recorded at low confidence. The source gave إليان and glossed the name 'God's grace'; إِلْيَان (Ilyān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "ilyana": ("إليانا", "الیانا", "الیانا", "इल्याना", "الیانا", "elijah", "Arabic", "Female",
            "Arabic إِلْيَانَا (Ilyānā)", False, "low",
            "Ilyana is recorded at low confidence. The source gave إليانا and glossed the name 'God's gift'; إِلْيَانَا (Ilyānā) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "ilyas": ("إلياس", "الیاس", "الیاس", "इल्यास", "الیاس", "elijah", "Arabic", "Male",
           "Qur'anic proper name; إِلْيَاس (Ilyās)", True, "high",
           "Ilyas is Arabic إِلْيَاس (Ilyās), the Qur'anic form of Elijah, a prophet mentioned in the Qur'an. The source record was an 8-key stub with no data. Same name as ilias and ilya."),
 "imaad": ("عماد", "عماد", "عماد", "इमाद", "عماد", "pillar", "Arabic", "Male",
           "Arabic root ع م د (ʿ-m-d); عِمَاد (ʿImād)", False, "medium",
           "Imaad is Arabic عِمَاد (ʿImād) 'pillar, support, mainstay', from the root ع م د (ʿ-m-d). CRITICAL SOURCE ERROR: the source gave the broken form إِمَاعُد and glossed the name 'Trust, Reliance'; the correct form is عِمَاد. Same name as imad."),
 "imaan": ("إيمان", "ایمان", "ایمان", "ईमान", "ایمان", "faith", "Arabic", "Female",
           "Arabic root أ م ن (ʾ-m-n); إِيمَان (Īmān)", False, "high",
           "Imaan is Arabic إِيمَان (Īmān) 'faith, belief, trust', from the root أ م ن (ʾ-m-n). The source gloss 'Faith and Belief' is consistent. Same name as iman, imane and imani."),
 "imad": ("عماد", "عماد", "عماد", "इमाद", "عماد", "pillar", "Arabic", "Male",
          "Arabic root ع م د (ʿ-m-d); عِمَاد (ʿImād)", False, "high",
          "Imad is Arabic عِمَاد (ʿImād) 'pillar, support, mainstay', from the root ع م د (ʿ-m-d). The source gloss 'Support, pillar' is consistent. Same name as imaad."),
 "imam": ("إمام", "امام", "امام", "इमाम", "امام", "leader_prayer", "Arabic", "Male",
          "Arabic root أ م م (ʾ-m-m); إِمَام (Imām)", False, "high",
          "Imam is Arabic إِمَام (Imām) 'leader; prayer leader, model', from the root أ م م (ʾ-m-m). The source gloss 'Leader, Spiritual Guide' is broadly consistent."),
 "iman": ("إيمان", "ایمان", "ایمان", "ईमान", "ایمان", "faith", "Arabic", "Female",
          "Arabic root أ م ن (ʾ-m-n); إِيمَان (Īmān)", False, "high",
          "Iman is Arabic إِيمَان (Īmān) 'faith, belief, trust', from the root أ م ن (ʾ-m-n). The source gloss 'Faith, Belief' is consistent. Same name as imaan, imane and imani."),
 "imana": ("إيمانة", "ایمانہ", "ایمانه", "ईमाना", "ایمانه", "faith", "Arabic", "Female",
           "Arabic root أ م ن (ʾ-m-n); إِيمَانَة (Īmāna)", False, "low",
           "Imana is recorded at low confidence. The source gave إيمانا and glossed the name 'Faithful'; إِيمَانَة (Īmāna) is the feminine of إِيمَان (Īmān), but the source's form and its independent attestation could not be confirmed. No confident meaning is asserted. Same name as imaan, iman and imani."),
 "imane": ("إيمان", "ایمان", "ایمان", "ईमान", "ایمان", "faith", "Arabic", "Female",
           "Arabic root أ م ن (ʾ-m-n); إِيمَان (Īmān)", False, "high",
           "Imane is a North African transliteration of Arabic إِيمَان (Īmān) 'faith, belief, trust', from the root أ م ن (ʾ-m-n). The source record was an 8-key stub with no data. Same name as imaan, iman and imani."),
 "imani": ("إيماني", "ایمانی", "ایمانی", "ईमानी", "ایماني", "faith", "Arabic", "Female",
           "Arabic root أ م ن (ʾ-m-n); إِيمَانِيّ (Īmāniyy)", False, "medium",
           "Imani is Arabic إِيمَانِيّ (Īmāniyy) 'of faith; faithful', from the root أ م ن (ʾ-m-n). The source gloss 'Faithful' is broadly consistent. Same name as imaan, iman and imane."),
 "imara": ("عمارة", "عمارہ", "عماره", "इमारा", "عماره", "architecture", "Arabic", "Female",
           "Arabic root ع م ر (ʿ-m-r); عِمَارَة (ʿImāra)", False, "medium",
           "Imara is Arabic عِمَارَة (ʿImāra) 'architecture, building, construction', from the root ع م ر (ʿ-m-r). The source gloss 'Prosperity, growth' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "imdad": ("إمداد", "امداد", "امداد", "इमदाद", "امداد", "aid", "Arabic", "Male",
           "Arabic root م د د (m-d-d); إِمْدَاد (Imdād)", False, "medium",
           "Imdad is Arabic إِمْدَاد (Imdād) 'aid, support, reinforcement', from the root م د د (m-d-d). The source gloss 'Gift, Bounty' is unsupported and has been replaced with the lexical sense."),
 "imed": ("إميد", "امید", "امید", "इमेद", "امید", "hope", "Arabic", "Male",
          "Arabic إِمِيد (Imīd)", False, "low",
          "Imed is recorded at low confidence. The source gave إميد and glossed the name 'Reward, Gift'; the form إِمِيد (Imīd) is a documented North African male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "imen": ("إيمان", "ایمان", "ایمان", "ईमेन", "ایمان", "faith", "Arabic", "Female",
          "Arabic root أ م ن (ʾ-m-n); إِيمَان (Īmān)", False, "medium",
          "Imen is a North African transliteration of Arabic إِيمَان (Īmān) 'faith, belief, trust', from the root أ م ن (ʾ-m-n). CRITICAL SOURCE ERROR: the source gave إيمن (a different form) and glossed the name 'Name of a river'; the correct form is إِيمَان. Same name as imaan, iman, imane and imani."),
 "imra": ("عمرة", "عمرہ", "عمره", "इमरा", "عمره", "architecture", "Arabic", "Female",
          "Arabic عَمْرَة (ʿAmra)", False, "low",
          "Imra is recorded at low confidence. The source gave عميرة and glossed the name 'Free, Unrestrained'; the form is uncertain and the gloss is unsupported. No confident meaning is asserted."),
 "imraan": ("عمران", "عمران", "عمران", "इमरान", "عمران", "imran", "Arabic", "Male",
            "Qur'anic proper name; عِمْرَان (ʿImrān)", True, "high",
            "Imraan is Arabic عِمْرَان (ʿImrān), a Qur'anic name, the father of Maryam (Mary) and the name of a Qur'anic sura. The source gloss 'Exalted, Elevated' is unsupported; the name is a proper name. Same name as imran and imrana."),
 "imram": ("عمران", "عمران", "عمران", "इमराम", "عمران", "imran", "Arabic", "Male",
           "Qur'anic proper name; عِمْرَان (ʿImrān)", True, "low",
           "Imram is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Beloved son'; the intended form is likely عِمْرَان (ʿImrān), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as imraan and imran."),
 "imran": ("عمران", "عمران", "عمران", "इमरान", "عمران", "imran", "Arabic", "Male",
           "Qur'anic proper name; عِمْرَان (ʿImrān)", True, "high",
           "Imran is Arabic عِمْرَان (ʿImrān), a Qur'anic name, the father of Maryam (Mary) and the name of a Qur'anic sura. The source record was an 8-key stub with no data. Same name as imraan and imrana."),
 "imrana": ("عمران", "عمران", "عمران", "इमराना", "عمران", "imran", "Arabic", "Female",
            "Qur'anic proper name; عِمْرَان (ʿImrān)", True, "low",
            "Imrana is recorded at low confidence. The source gave إمرانة and glossed the name 'Faithful'; the intended form is likely عِمْرَان (ʿImrān), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as imraan and imran."),
 "imtiaaz": ("امتياز", "امتیاز", "امتیاز", "इम्तियाज़", "امتیاز", "distinction", "Arabic", "Male",
             "Arabic root م ي ز (m-y-z); اِمْتِيَاز (Imtiyāz)", False, "high",
             "Imtiaaz is Arabic اِمْتِيَاز (Imtiyāz) 'distinction, excellence, privilege', from the root م ي ز (m-y-z). The source gloss 'Dignity, Honor' is broadly consistent. Same name as imtiaz and imtiyaz."),
 "imtiaz": ("امتياز", "امتیاز", "امتیاز", "इम्तियाज़", "امتیاز", "distinction", "Arabic", "Male",
            "Arabic root م ي ز (m-y-z); اِمْتِيَاز (Imtiyāz)", False, "high",
            "Imtiaz is Arabic اِمْتِيَاز (Imtiyāz) 'distinction, excellence, privilege', from the root م ي ز (m-y-z). The source gloss 'Esteem, Respect' is broadly consistent. Same name as imtiaaz and imtiyaz."),
 "imtithal": ("امتثال", "امتثال", "امتثال", "इम्तिथाल", "امتثال", "compliance", "Arabic", "Female",
              "Arabic root م ث ل (m-th-l); اِمْتِثَال (Imtithāl)", False, "medium",
              "Imtithal is Arabic اِمْتِثَال (Imtithāl) 'compliance, obedience, conformity', from the root م ث ل (m-th-l). CRITICAL SOURCE ERROR: the source gave إمثال (a different word) and glossed the name 'Preservation, Protection'; the correct form is اِمْتِثَال."),
 "imtiyaz": ("امتياز", "امتیاز", "امتیاز", "इम्तियाज़", "امتیاز", "distinction", "Arabic", "Male",
             "Arabic root م ي ز (m-y-z); اِمْتِيَاز (Imtiyāz)", False, "medium",
             "Imtiyaz is Arabic اِمْتِيَاز (Imtiyāz) 'distinction, excellence, privilege', from the root م ي ز (m-y-z). CRITICAL SOURCE ERROR: the source gave امتیاز, using Urdu letters in the Arabic column; the correct Arabic form is اِمْتِيَاز. The source gloss 'Distinction, Honor' is broadly consistent. Same name as imtiaaz and imtiaz."),
 "inaam": ("إنعام", "انعام", "انعام", "इनाम", "انعام", "bestowal", "Arabic", "Male",
           "Arabic root ن ع م (n-ʿ-m); إِنْعَام (Inʿām)", False, "high",
           "Inaam is Arabic إِنْعَام (Inʿām) 'bestowal, granting, gift', from the root ن ع م (n-ʿ-m). The source record was an 8-key stub with no data. Same name as inam."),
 "inaaya": ("عناية", "عنایہ", "عنایه", "इनाया", "عنایه", "care", "Arabic", "Female",
            "Arabic root ع ن ي (ʿ-n-y); عِنَايَة (ʿInāya)", False, "medium",
            "Inaaya is Arabic عِنَايَة (ʿInāya) 'care, providence, solicitude', from the root ع ن ي (ʿ-n-y). CRITICAL SOURCE ERROR: the source gave عيناية (a different form) and glossed the name 'Innovative Gift'; the correct form is عِنَايَة."),
 "inab": ("عنب", "عنب", "عنب", "इनब", "عنب", "grape", "Arabic", "Female",
          "Arabic عِنَب (ʿInab)", False, "medium",
          "Inab is Arabic عِنَب (ʿInab) 'grape; a grapevine'. The source gloss 'Grape' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "inam": ("إنعام", "انعام", "انعام", "इनाम", "انعام", "bestowal", "Arabic", "Male",
          "Arabic root ن ع م (n-ʿ-m); إِنْعَام (Inʿām)", False, "medium",
          "Inam is Arabic إِنْعَام (Inʿām) 'bestowal, granting, gift', from the root ن ع م (n-ʿ-m). CRITICAL SOURCE ERROR: the source gave إِنَام (a different form) and glossed the name 'Leader, Commander'; the correct form is إِنْعَام. Same name as inaam."),
 "inan": ("عنان", "عنان", "عنان", "इनान", "عنان", "reins", "Arabic", "Male",
          "Arabic root ع ن ن (ʿ-n-n); عِنَان (ʿInān)", False, "low",
          "Inan is recorded at low confidence. The source gave إنان (a different form) and glossed the name 'Gift, Blessing'; عِنَان (ʿInān) 'reins, halter' is a documented Arabic word, but the source's form and gloss could not be confirmed. No confident meaning is asserted."),
}
