# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 28 (harisah..helai).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": harisah -> حريزة ('silk', a different word);
   hariz -> حارز (non-standard); haseen -> حسن (that is hasan); hashan -> حسن;
   hasib -> حاصب (should be حاسب/حسيب); hasiba -> حسينة (should be حسيبة);
   hasina -> حسنا (should be حسينة); hasin -> حسن (should be حصين);
   hatem -> هاتم (should be حاتم); hawah -> هوآه (should be حواء);
   hawari -> هواري (should be حواري); haya -> حيى (should be حياء/حياة);
   haydara -> هايدارا (should be حيدرة); hayet -> هيئة (should be حياة);
   haysam -> حيسم (should be هيثم); haytham -> حييثم (should be هيثم);
   haziq -> حزيق (should be حاذق); haziqah -> هزيقة (should be حاذقة);
   hazirah -> حاذرة (should be حاضرة); heba -> حبة (should be هبة);
   hebba -> حبة (should be هبة); helai -> هلاء (non-standard);
   hassnain -> ھسناین (Urdu letters in the Arabic column).
 * DEGARBLED / WRONG glosses: hariz 'Gardener' (should be 'strong, fortified');
   haseem 'Generous, Magnificent' (should be 'decisive'); hasif 'Gifted, Generous'
   (should be 'regretful'); hasim 'Gift, Present' (should be 'decisive');
   hasin 'Joyful, content' (should be 'fortified'); hatem 'Hater' (should be 'seal');
   haula 'Easy going, simple' (should be 'power, change'); hawra 'Garden, fertile land'
   (should be 'fair-skinned, beautiful'); hayfa 'Glorious, Radiant' (should be 'slender');
   hayfaa 'Joy, Happiness' (should be 'slender'); hayl 'Life, Existence' (should be
   'elevated'); haysam 'Alive, living' (should be 'brave lion'); haytham 'Successful
   seller' (should be 'young eagle'); haza 'Gift, Treasure' (should be 'conveyance');
   hazal 'Flower' (should be 'emaciation'); hazar 'Thousands' (should be 'caution');
   hazeem 'Vigilant, Watchful' (should be 'resolute'); haziq 'Glowing, Radiant'
   (should be 'skilled'); haziqah 'Gift, Treasure' (should be 'skilled'); hazra
   'Blessed one' (should be 'piety'); hazwan 'Gift, blessing' (should be 'joy');
   heba 'Breath, Heart, Split' (should be 'gift'); hebba 'Young lady' (should be
   'gift'); hedi 'Contentment, Satisfaction' (should be 'gift'); heela 'Light, Moon'
   (should be 'stratagem'); helai 'Light, Moon' (should be 'new, fresh').
 * MISLABELLED ORIGIN: hashmat and hasrat are Persian/Urdu, not Arabic lexical items;
   haziran is a Syriac/Aramaic month name used in the Levant, not an Arabic given name.
 * GENDER ERRORS: hasbi, haseena, hasina, hasiba, hassiba, hassina, hassnain, hashan,
   hashir, hasif, hasil, hasim, hasoun, hassam, hassib, hatem, hattab, hawari, hayal,
   hayam, hayl, haysam, haytham, haza, hazal, hazar, hazeem, haziq, hazir, hazrat,
   hazwan, hedi were labelled female or unisex where documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: harun, hassan, hawa (8-key stubs with no data);
   hasoun, hasrat, haula, hawla, hayal, hayam, hayl, haza, hazal, hazar, hazirah,
   haziran, hazra, hazwan, helai.
 * DUPLICATE CLUSTERS: haroon/haroun/harun; hasan/hassan/hasaan; hasana/hasna/hasnaa/
   hasnah/hassana; hasanain/hasnain/hassnain; hasanat/hasnat; haseeb/hasib/hassib;
   haseem/hasim; haseen/hasin/hasoun/hassun; haseena/hasina/hasinah/hassina;
   hashim/hashimah/hashimi; hatam/hatem/hatim; hawa/hawah/hawwa/hawwaa;
   haula/hawla; hawra/hawraa; haya/hayaa/hayaat/hayat/hayati/hayet;
   haydar/hayder/haydara; hayfa/hayfaa; haysam/haytham; hazem/hazim/hazm;
   haziq/haziqah; hazir/hazirah; heba/hebba.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated27 import GLOSSES as _G27

GLOSSES = dict(_G27)
GLOSSES.update({
    "striving_goodness": {"en": "One who strives for goodness and righteousness", "ur": "خیر و صلاح کی کوشش کرنے والی", "fa": "کوشنده در راه نیکی و صلاح", "hi": "भलाई और नेकी की इच्छा रखने वाली", "ps": "د خیر او صلاح لپاره کوښښ کوونکې", "ar": "الساعية إلى الخير والصلاح"},
    "cultivator": {"en": "Cultivator, tiller of the soil, farmer", "ur": "کسان، زمین کاشت کرنے والا", "fa": "کشاورز، برزگر", "hi": "किसान, भूमि जोतने वाला", "ps": "بزګر، د ځمکې کرونکی", "ar": "الحارث، الفلاح، من يحرث الأرض"},
    "strong_fortified": {"en": "Strong, fortified, well-guarded", "ur": "مضبوط، محفوظ، نگہبان", "fa": "نیرومند، استوار، نگهبان", "hi": "मजबूत, सुरक्षित, रक्षक", "ps": "پیاوړی، خوندي، ساتونکی", "ar": "الحريز، القوي، الحصين"},
    "prophet_aaron": {"en": "Aaron, brother of Moses, prophet", "ur": "ہارون، موسیٰ کے بھائی، نبی", "fa": "هارون، برادر موسی، پیامبر", "hi": "हारून, मूसा के भाई, पैगंबर", "ps": "هارون، د موسی ورور، پیغمبر", "ar": "هارون، أخو موسى، نبي"},
    "good_beautiful": {"en": "Good, beautiful, virtuous, excellent", "ur": "اچھا، خوبصورت، نیک", "fa": "نیک، زیبا، پسندیده", "hi": "अच्छा, सुंदर, नेक", "ps": "ښه، ښکلی، نیک", "ar": "الحسن، الجميل، الخيّر"},
    "patience_generous": {"en": "Patience, forbearance; generous", "ur": "صبر، برداشت؛ سخی", "fa": "شکیبایی، بردباری؛ بخشنده", "hi": "धैर्य, सहनशीलता; उदार", "ps": "صبر، زغم؛ سخي", "ar": "الهشام، الصبر، الكرم"},
    "dignity_honor": {"en": "Dignity, honor, prestige, grandeur", "ur": "عزت، وقار، شان", "fa": "شکوه، عزت، جلال", "hi": "गरिमा, सम्मान, प्रतिष्ठा", "ps": "وقار، عزت، شان", "ar": "الحشمة، الوقار، العزّ"},
    "reckoner": {"en": "Reckoner, one who accounts, keeper of accounts", "ur": "حساب کرنے والا، محاسب", "fa": "حسابگر، محاسب", "hi": "हिसाब रखने वाला, लेखाकार", "ps": "حساب کوونکی، محاسب", "ar": "الحسيب، المحاسب، من يحسب"},
    "decisive": {"en": "Decisive, resolute, sharp", "ur": "فیصلہ کن، مضبوط، تیز", "fa": "قاطع، استوار، تیز", "hi": "निर्णायक, दृढ़, तीक्ष्ण", "ps": "قاطع، پیاوړی، تېز", "ar": "الحاسم، القاطع، الماضي"},
    "seal_concluder": {"en": "Seal, concluder, finisher", "ur": "مہر، خاتم، فیصلہ کرنے والا", "fa": "مهر، خاتم، پایانبخش", "hi": "मुहर, समाप्त करने वाला", "ps": "مهر، پای کوونکی", "ar": "الخاتم، الحاتم، من يختم"},
    "woodcutter": {"en": "Woodcutter, gatherer of firewood", "ur": "لکڑہارا، ایندھن جمع کرنے والا", "fa": "هیزمشکن، چوبگردآور", "hi": "लकड़हारा, ईंधन बटोरने वाला", "ps": "د لرګیو وهونکی", "ar": "الحطّاب، جامع الحطب"},
    "power_change": {"en": "Power, change, transformation", "ur": "طاقت، تبدیلی، گردش", "fa": "قدرت، دگرگونی، گردش", "hi": "शक्ति, परिवर्तन, रूपांतरण", "ps": "ځواک، بدلون، ګردش", "ar": "الحولة، القدرة، التحوّل"},
    "eve_first_woman": {"en": "Eve, the first woman", "ur": "حوا، پہلی عورت", "fa": "حوا، نخستین زن", "hi": "हव्वा, प्रथम स्त्री", "ps": "حوا، لومړنۍ ښځه", "ar": "حوّاء، أول امرأة"},
    "disciple_helper": {"en": "Disciple, helper, supporter", "ur": "حواری، مددگار، ساتھی", "fa": "حواری، یاور، یار", "hi": "शिष्य, सहायक, साथी", "ps": "حواري، مرستیال، ملګری", "ar": "الحواري، الناصر، الصاحب"},
    "senses": {"en": "The five senses; faculties of perception", "ur": "حواس، پانچ حسیں", "fa": "حواس، پنج حس", "hi": "इंद्रियाँ, पाँच ज्ञानेंद्रियाँ", "ps": "حواس، پنځه حسي", "ar": "الحواسّ، الخمس"},
    "beautiful_white": {"en": "Beautiful; fair-skinned, bright", "ur": "خوبصورت، گوری، روشن", "fa": "زیبا، سفیدرو، روشن", "hi": "सुंदर, गोरी, उजली", "ps": "ښکلې، سپينه، روښانه", "ar": "الحوراء، الجميلة، البيضاء"},
    "life": {"en": "Life, existence, vitality", "ur": "زندگی، حیات، وجود", "fa": "زندگی، حیات، هستی", "hi": "जीवन, अस्तित्व, प्राण", "ps": "ژوند، حیات، شتون", "ar": "الحياة، الوجود، الحيوية"},
    "modesty": {"en": "Modesty, shyness, sense of shame", "ur": "حیا، شرم، پاکدامنی", "fa": "حیا، شرم، پاکدامنی", "hi": "लज्जा, शर्म, संकोच", "ps": "حیا، شرم، پاکدامني", "ar": "الحياء، الخجل، العفّة"},
    "lion": {"en": "Lion; brave, bold", "ur": "شیر، بہادر", "fa": "شیر، دلیر", "hi": "शेर, वीर", "ps": "زمری، زړور", "ar": "الحيدر، الأسد، الشجاع"},
    "gazelle": {"en": "Gazelle; slender, graceful", "ur": "ہرن، خوبصورت", "fa": "آهو، زیبا", "hi": "हिरणी, सुंदर", "ps": "غوی، ښکلې", "ar": "الحيدرة، الغزال، الرشيقة"},
    "slender": {"en": "Slender, graceful, slim", "ur": "پتلی، نازک، خوبصورت", "fa": "باریک، نازک، زیبا", "hi": "पतली, सुंदर, नाजुक", "ps": "نری، نازک، ښکلې", "ar": "الحيفاء، النحيلة، الرشيقة"},
    "brave_lion": {"en": "Brave; young lion", "ur": "بہادر، شیر", "fa": "دلیر، شیر", "hi": "वीर, शेर", "ps": "زړور، زمری", "ar": "الهيثم، الشجاع، الأسد"},
    "young_eagle": {"en": "Young eagle; brave", "ur": "عقاب، بہادر", "fa": "عقاب، دلیر", "hi": "चील, वीर", "ps": "عقاب، زړور", "ar": "الهيثم، العقاب، الشجاع"},
    "living": {"en": "Living, alive, ever-living", "ur": "زندہ، حیات والا", "fa": "زنده، حیّ", "hi": "जीवित, जीवंत", "ps": "ژوندی، حی", "ar": "الحيّان، الحيّ، ذو الحياة"},
    "treasure": {"en": "Treasure, precious possession", "ur": "خزانہ، نایاب شے", "fa": "گنج، شیء گرانبها", "hi": "खज़ाना, बहुमूल्य वस्तु", "ps": "خزانه، ګران شی", "ar": "الكنز، الذخيرة، النفيس"},
    "flower": {"en": "Flower, blossom", "ur": "پھول، کلی", "fa": "گل، شکوفه", "hi": "फूल, कली", "ps": "ګل، غوړېدنه", "ar": "الزهرة، النوّار"},
    "thousand": {"en": "Thousand; many", "ur": "ہزار، بہت", "fa": "هزار، بسیار", "hi": "हज़ार, अनेक", "ps": "زر، ډېر", "ar": "الألف، الكثير"},
    "resolute": {"en": "Resolute, determined, firm of purpose", "ur": "مضبوط، فیصلہ کن، پختہ", "fa": "استوار، قاطع، مصمم", "hi": "दृढ़, निर्णायक, अटल", "ps": "پیاوړی، قاطع، ټینګ", "ar": "الحازم، الحزم، القاطع"},
    "skilled": {"en": "Skilled, proficient, adept", "ur": "ماہر، ہنرمند", "fa": "ماهر، کاردان", "hi": "कुशल, निपुण", "ps": "ماهر، پوه", "ar": "الحاذق، الماهر، البارع"},
    "present_ready": {"en": "Present, ready, at hand", "ur": "حاضر، تیار، موجود", "fa": "حاضر، آماده، موجود", "hi": "उपस्थित, तैयार, मौजूद", "ps": "حاضر، چمتو، موجود", "ar": "الحاضر، المهيّأ، الموجود"},
    "piety": {"en": "Piety, God-consciousness, reverence", "ur": "تقویٰ، پرہیزگاری", "fa": "پرهیزگاری، تقوا", "hi": "परहेज़गारी, ईशभक्ति", "ps": "تقوا، پرهېزګاري", "ar": "التقوى، الورع، الخشية"},
    "presence_reverence": {"en": "Presence, reverence, respectful address", "ur": "حضور، ادب، تعظیم", "fa": "حضور، ادب، احترام", "hi": "उपस्थिति, आदर, सम्मान", "ps": "حضور، ادب، درناوی", "ar": "الحضرة، الحضور، التوقير"},
    "joy": {"en": "Joy, happiness, delight", "ur": "خوشی، فرحت، مسرت", "fa": "شادی، خوشی، سرور", "hi": "खुशी, आनंद, प्रसन्नता", "ps": "خوښي، فرحت، مسرت", "ar": "الفرح، السرور، البهجة"},
    "gift": {"en": "Gift, present, offering", "ur": "تحفہ، عطیہ، ہدیہ", "fa": "هدیه، عطیه، بخشش", "hi": "उपहार, भेंट, दान", "ps": "ډالۍ، تحفه، عطیه", "ar": "الهدية، العطية، الهبة"},
    "guidance": {"en": "Guidance, direction to the right path", "ur": "ہدایت، رہنمائی، راستہ دکھانا", "fa": "هدایت، راهنمایی، ارشاد", "hi": "मार्गदर्शन, हिदायत, राह दिखाना", "ps": "هدایت، لارښوونه، سمه لار", "ar": "الهداية، الإرشاد، الدلالة على الطريق"},
    "stratagem": {"en": "Stratagem, device, clever plan", "ur": "حیلہ، تدبیر، چالاکی", "fa": "حیله، تدبیر، چاره", "hi": "उपाय, युक्ति, चतुराई", "ps": "حیله، تدبیر، چل", "ar": "الحيلة، التدبير، المكيدة"},
    "new_fresh": {"en": "New, fresh, lovely, excellent", "ur": "نیا، تازہ، عمدہ", "fa": "نو، تازه، نیکو", "hi": "नया, ताज़ा, उत्तम", "ps": "نوی، تازه، ښه", "ar": "الجديد، الطريّ، الحسن"},
    "regretful": {"en": "Regretful, sorrowful, grieved", "ur": "افسوس کرنے والا، غمگین", "fa": "افسوسخور، اندوهگین", "hi": "पछताने वाला, दुखी", "ps": "افسوس کوونکی، غمجن", "ar": "الحاسف، الأسيف، المتحسّر"},
    "outcome": {"en": "Outcome, result, yield, fruit", "ur": "نتیجہ، حاصل، پھل", "fa": "نتیجه، حاصل، بهره", "hi": "परिणाम, उपज, फल", "ps": "پایله، حاصل، مېوه", "ar": "الحاصل، النتيجة، الثمرة"},
    "elevated": {"en": "Elevated, high, lofty, noble", "ur": "بلند، عالی، رفیع", "fa": "بلند، عالی، رفیع", "hi": "ऊँचा, उच्च, श्रेष्ठ", "ps": "لوړ، عالي، پورته", "ar": "العالی، الرفيع، المرتفع"},
    "conveyance": {"en": "Conveyance, mode of transport", "ur": "سواری، ذریعہ سفر", "fa": "مرکب، وسیله نقلیه", "hi": "वाहन, सवारी", "ps": "سواری، د تګ وسیله", "ar": "الحازة، المركب، وسيلة النقل"},
    "emaciation": {"en": "Emaciation, leanness, wasting", "ur": "دبلاپن، لاغری", "fa": "لاغری، نحیفی", "hi": "दुबलापन, क्षीणता", "ps": "نرۍ، لاغري", "ar": "الهزال، النحول، الضمور"},
    "caution": {"en": "Caution, prudence, wariness", "ur": "احتیاط، ہوشیاری", "fa": "احتیاط، هوشیاری", "hi": "सावधानी, सतर्कता", "ps": "احتیاط، پاملرنه", "ar": "الحذر، الاحتياط، التيقّظ"},
    "month_six": {"en": "Name of a month (June in the Levantine calendar)", "ur": "ایک مہینے کا نام (شامی کیلنڈر میں جون)", "fa": "نام ماهی در گاهشمار شامی (ژوئن)", "hi": "एक महीने का नाम (लेवांत कैलेंडर में जून)", "ps": "د یوې میاشتې نوم (شامي کال کې جون)", "ar": "حزيران، اسم شهر في التقويم الشامي"},
    "honorific": {"en": "Honorific title of respect; presence", "ur": "حضرت، تعظیمی لقب، حضور", "fa": "حضرت، لقب احترام، حضور", "hi": "हज़रत, आदरसूचक उपाधि", "ps": "حضرت، د درناوي لقب", "ar": "الحضرة، لقب التوقير، الحضور"},
})

CUR = {
 "harisah": ("حارثة", "حارثة", "حارثة", "हारिसा", "حارثة", "striving_goodness", "Arabic", "Female",
             "Arabic root ح ر ث (ḥ-r-th); حَارِثَة (Ḥāritha)", False, "low",
             "Harisah is recorded at low confidence. The source gave حريزة ('silk', a different word) and glossed the name 'Gifted, Generous'; neither the form nor the gloss could be confirmed. The form حَارِثَة (Ḥāritha) is the documented feminine of حَارِث (Ḥārith), but its identification with this slug is uncertain. No confident meaning is asserted."),
 "harith": ("حارث", "حارث", "حارث", "हारिथ", "حارث", "cultivator", "Arabic", "Male",
            "Arabic root ح ر ث (ḥ-r-th); حَارِث (Ḥārith)", False, "high",
            "Harith is Arabic حَارِث (Ḥārith) 'tiller of the soil, cultivator, farmer', from the root ح ر ث (ḥ-r-th). It is a well-documented pre-Islamic and early Islamic Arabic personal name. The source gloss 'Blooming, flourishing' is unsupported and has been replaced with the lexical sense. Same name as haris (batch 27)."),
 "haritha": ("حارثة", "حارثة", "حارثة", "हारिथा", "حارثة", "cultivator", "Arabic", "Female",
             "Arabic root ح ر ث (ḥ-r-th); حَارِثَة (Ḥāritha)", False, "medium",
             "Haritha is Arabic حَارِثَة (Ḥāritha), the feminine form of حَارِث (Ḥārith) 'tiller of the soil, cultivator', from the root ح ر ث (ḥ-r-th). The source gloss 'Blooming Flower' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the name is more commonly attested in its masculine form."),
 "hariz": ("حريز", "حريز", "حريز", "हरीज़", "حريز", "strong_fortified", "Arabic", "Male",
           "Arabic root ح ر ز (ḥ-r-z); حَرِيز (Ḥarīz)", False, "medium",
           "Hariz is Arabic حَرِيز (Ḥarīz) 'strong, fortified, well-guarded', from the root ح ر ز (ḥ-r-z). The source gave حارز (non-standard) and glossed the name 'Gardener', which is unsupported; the lexical sense is 'fortified, well-guarded'. Recorded at medium confidence because the source's Arabic column was non-standard."),
 "haroon": ("هارون", "ہارون", "هارون", "हारून", "هارون", "prophet_aaron", "Arabic", "Male",
            "Qur'anic proper name; هَارُون (Hārūn)", True, "high",
            "Haroon is Arabic هَارُون (Hārūn), the Qur'anic form of the prophet Aaron, brother of Moses. It is a Qur'anic proper name and is widely used as a male given name. The source gloss 'Highness, Exaltation' is unsupported; the name is a proper name rather than a descriptive lexical item. Same name as haroun and harun."),
 "haroun": ("هارون", "ہارون", "هارون", "हारून", "هارون", "prophet_aaron", "Arabic", "Male",
            "Qur'anic proper name; هَارُون (Hārūn)", True, "high",
            "Haroun is an alternative transliteration of Arabic هَارُون (Hārūn), the Qur'anic form of the prophet Aaron. The source gloss 'The Successor' and the claim that it means 'the just ruler' are unsupported; the name is a proper name. Same name as haroon and harun."),
 "harun": ("هارون", "ہارون", "هارون", "हारून", "هارون", "prophet_aaron", "Arabic", "Male",
           "Qur'anic proper name; هَارُون (Hārūn)", True, "high",
           "Harun is the standard transliteration of Arabic هَارُون (Hārūn), the Qur'anic form of the prophet Aaron. The source record was an 8-key stub with no data and glossed the name 'Mountain of Strength', which is unsupported. Same name as haroon and haroun."),
 "hasan": ("حسن", "حسن", "حسن", "हसन", "حسن", "good_beautiful", "Arabic", "Male",
           "Arabic root ح س ن (ḥ-s-n); حَسَن (Ḥasan)", False, "high",
           "Hasan is Arabic حَسَن (Ḥasan) 'good, beautiful, virtuous, excellent', from the root ح س ن (ḥ-s-n). It is a very well-documented Arabic personal name, borne by Hasan ibn Ali, grandson of the Prophet Muhammad. The source gloss is consistent with the lexical sense."),
 "hasana": ("حسنة", "حسنة", "حسنة", "हसना", "حسنة", "good_beautiful", "Arabic", "Female",
            "Arabic root ح س ن (ḥ-s-n); حَسَنَة (Ḥasana)", False, "medium",
            "Hasana is Arabic حَسَنَة (Ḥasana) 'good deed; good, beautiful', from the root ح س ن (ḥ-s-n). The source gave حسنا and glossed the name 'Graceful, Beautiful, Pleasing', which is broadly consistent. Recorded at medium confidence because the source's Arabic column omitted the final ة."),
 "hasanain": ("حسنين", "حسنین", "حسنین", "हसनैन", "حسنین", "good_beautiful", "Arabic", "Male",
              "Dual form of حَسَن (Ḥasan); حَسَنَيْن (Ḥasanayn)", False, "high",
              "Hasanain is Arabic حَسَنَيْن (Ḥasanayn), the dual form of حَسَن (Ḥasan), literally 'the two Hasans', referring to Hasan and Husayn, the grandsons of the Prophet Muhammad. The source gloss 'Two Hasans' is consistent. Same name as hasnain and hassnain."),
 "hasanat": ("حسنات", "حسنات", "حسنات", "हसनात", "حسنات", "good_beautiful", "Arabic", "Female",
             "Plural of حَسَنَة (ḥasana); حَسَنَات (Ḥasanāt)", False, "medium",
             "Hasanat is Arabic حَسَنَات (Ḥasanāt), the plural of حَسَنَة (ḥasana) 'good deed', meaning 'good deeds, virtues, righteous acts'. The source gloss 'Generous, Benevolent' is unsupported and has been replaced with the lexical sense. Same name as hasnat."),
 "hasbi": ("حسبي", "حسبی", "حسبی", "हस्बी", "حسبي", "reckoner", "Arabic", "Male",
           "Arabic root ح س ب (ḥ-s-b); حَسْبِي (Ḥasbī)", False, "medium",
           "Hasbi is Arabic حَسْبِي (Ḥasbī) 'sufficient for me', from the root ح س ب (ḥ-s-b), as in the phrase حَسْبِيَ اللَّهُ 'Allah is sufficient for me'. The source gloss 'Helper' is unsupported and has been replaced with the lexical sense. The source labelled the name female; documented usage is predominantly male."),
 "haseeb": ("حسيب", "حسیب", "حسیب", "हसीब", "حسيب", "reckoner", "Arabic", "Male",
            "Arabic root ح س ب (ḥ-s-b); حَسِيب (Ḥasīb)", False, "high",
            "Haseeb is Arabic حَسِيب (Ḥasīb) 'reckoner, one who accounts, keeper of accounts', from the root ح س ب (ḥ-s-b). It is also one of the names of Allah (الحسيب). The source gloss 'Gift from God' is unsupported and has been replaced with the lexical sense. Same name as hasib and hassib."),
 "haseem": ("حسيم", "حسیم", "حسیم", "हसीम", "حسيم", "decisive", "Arabic", "Male",
            "Arabic root ح س م (ḥ-s-m); حَسِيم (Ḥasīm)", False, "low",
            "Haseem is recorded at low confidence. The source gave حسيم and glossed the name 'Generous, Magnificent'; the form حَسِيم (Ḥasīm) is not a well-attested Arabic lexical item, and the related root ح س م (ḥ-s-m) yields حَاسِم (Ḥāsim) 'decisive'. No confident meaning is asserted. Same name as hasim."),
 "haseen": ("حصين", "حصین", "حصین", "हसीन", "حصين", "strong_fortified", "Arabic", "Male",
            "Arabic root ح ص ن (ḥ-ṣ-n); حَصِين (Ḥaṣīn)", False, "medium",
            "Haseen is Arabic حَصِين (Ḥaṣīn) 'fortified, well-protected, impregnable', from the root ح ص ن (ḥ-ṣ-n). CRITICAL SOURCE ERROR: the source gave حسن (that is hasan) as the Arabic form and glossed the name 'Beautiful, handsomeness'; the correct form is حَصِين (Ḥaṣīn). Recorded at medium confidence because the source's Arabic column was wrong."),
 "haseena": ("حسينة", "حسینہ", "حسینه", "हसीना", "حسینه", "good_beautiful", "Arabic", "Female",
             "Arabic root ح س ن (ḥ-s-n); حَسِينَة (Ḥasīna)", False, "medium",
             "Haseena is Arabic حَسِينَة (Ḥasīna) 'beautiful, good-natured', from the root ح س ن (ḥ-s-n). The source gloss 'Beauty, attractive' is broadly consistent. The source labelled the name female, which matches documented usage. Same name as hasina, hasinah and hassina."),
 "hasham": ("هشام", "ہشام", "هشام", "हशाम", "هشام", "patience_generous", "Arabic", "Male",
            "Arabic root ه ش م (h-sh-m); هِشَام (Hishām)", False, "high",
            "Hasham is a South Asian transliteration of Arabic هِشَام (Hishām), a well-documented male given name borne by Hisham ibn Abd al-Malik, an Umayyad caliph. The source gloss 'Given by God' is unsupported; the name is a proper name rather than a descriptive lexical item."),
 "hashan": ("هشان", "ہشان", "هشان", "हशान", "هشان", "good_beautiful", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); حَسَّان (Ḥassān)", False, "low",
            "Hashan is recorded at low confidence. The source gave حسن (that is hasan) and glossed the name 'Happy'; the intended form is uncertain and may be حَسَّان (Ḥassān). No confident meaning is asserted."),
 "hashim": ("هاشم", "ہاشم", "هاشم", "हाशिम", "هاشم", "good_beautiful", "Arabic", "Male",
            "Arabic root ه ش م (h-sh-m); هَاشِم (Hāshim)", False, "high",
            "Hashim is Arabic هَاشِم (Hāshim), a well-documented male given name borne by Hashim ibn Abd Manaf, great-grandfather of the Prophet Muhammad, and the eponym of the Banu Hashim clan. The source gloss 'Bringer of Peace' is unsupported; the name is a proper name. Same root as hashimi."),
 "hashimah": ("هشيمة", "ہشیمہ", "هشیمه", "हशीमा", "هشیمه", "good_beautiful", "Arabic", "Female",
              "Arabic root ه ش م (h-sh-m); هَشِيمَة (Hashīma)", False, "low",
              "Hashimah is recorded at low confidence. The source gave هشيمة and glossed the name 'Follower of Hashim'; the form هَشِيمَة (Hashīma) is not a well-attested Arabic lexical item and the gloss is unsupported. No confident meaning is asserted."),
 "hashimi": ("هاشمي", "ہاشمی", "هاشمی", "हाशिमी", "هاشمي", "good_beautiful", "Arabic", "Male",
             "Nisba of هَاشِم (Hāshim); هَاشِمِيّ (Hāshimī)", False, "medium",
             "Hashimi is Arabic هَاشِمِيّ (Hāshimī), the nisba (relational adjective) of هَاشِم (Hāshim), denoting descent from or connection to the Banu Hashim clan. The source gloss 'The Giver' is unsupported and has been replaced with the lexical sense. The source labelled the name unisex; documented usage is predominantly male."),
 "hashir": ("حشير", "حشیر", "حشیر", "हशीर", "حشير", "good_beautiful", "Arabic", "Male",
            "Arabic root ح ش ر (ḥ-sh-r); حَشِير (Ḥashīr)", False, "low",
            "Hashir is recorded at low confidence. The source gave حشير and glossed the name 'Traveler, Messenger'; the form حَشِير (Ḥashīr) is not a well-attested Arabic personal name, and the related root ح ش ر (ḥ-sh-r) means 'to gather, to assemble'. No confident meaning is asserted."),
 "hashmat": ("حشمت", "حشمت", "حشمت", "हशमत", "حشمت", "dignity_honor", "Persian", "Male",
             "Persian حشمت (hashmat), from Arabic حَشْمَة", False, "medium",
             "Hashmat is Persian حشمت (hashmat) 'dignity, honor, prestige, grandeur', a Persian formation related to Arabic حَشْمَة. MISLABELLED ORIGIN: the source recorded the name as Arabic; it is a Persian/Urdu lexical item. The source gloss is consistent with the Persian sense. Recorded at medium confidence because the word is primarily a common noun."),
 "hasib": ("حسيب", "حسیب", "حسیب", "हसीब", "حسيب", "reckoner", "Arabic", "Male",
           "Arabic root ح س ب (ḥ-s-b); حَسِيب (Ḥasīb)", False, "medium",
           "Hasib is Arabic حَسِيب (Ḥasīb) 'reckoner, one who accounts', from the root ح س ب (ḥ-s-b). CRITICAL SOURCE ERROR: the source gave حاصب (a different word, 'pebble-bearing wind') and glossed the name 'Calculator, Reckoner'; the correct form is حَسِيب (Ḥasīb). Same name as haseeb and hassib."),
 "hasiba": ("حسيبة", "حسیبہ", "حسیبه", "हसीबा", "حسیبه", "reckoner", "Arabic", "Female",
            "Arabic root ح س ب (ḥ-s-b); حَسِيبَة (Ḥasība)", False, "low",
            "Hasiba is recorded at low confidence. The source gave حسينة (that is haseena) and glossed the name 'Blossoming, Giving'; the intended form is likely حَسِيبَة (Ḥasība), the feminine of حَسِيب (Ḥasīb). The identification is uncertain and no confident meaning is asserted."),
 "hasif": ("حاسف", "حاسف", "حاسف", "हासिफ़", "حاسف", "regretful", "Arabic", "Male",
           "Arabic root ح س ف (ḥ-s-f); حَاسِف (Ḥāsif)", False, "low",
           "Hasif is recorded at low confidence. The source gave حاسف and glossed the name 'Gifted, Generous'; the form حَاسِف (Ḥāsif) is not a well-attested Arabic personal name, and the related root ح س ف (ḥ-s-f) means 'to regret, to sorrow'. No confident meaning is asserted."),
 "hasil": ("حاصل", "حاصل", "حاصل", "हासिल", "حاصل", "outcome", "Arabic", "Male",
           "Arabic root ح ص ل (ḥ-ṣ-l); حَاصِل (Ḥāṣil)", False, "medium",
           "Hasil is Arabic حَاصِل (Ḥāṣil) 'outcome, result, yield, fruit', from the root ح ص ل (ḥ-ṣ-l). The source gloss 'Fruit, Reward' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun and its use as a given name is less frequent."),
 "hasim": ("حاسم", "حاسم", "حاسم", "हासिम", "حاسم", "decisive", "Arabic", "Male",
           "Arabic root ح س م (ḥ-s-m); حَاسِم (Ḥāsim)", False, "medium",
           "Hasim is Arabic حَاسِم (Ḥāsim) 'decisive, resolute, sharp', from the root ح س م (ḥ-s-m). The source gloss 'Gift, Present' is unsupported and has been replaced with the lexical sense. Same name as haseem."),
 "hasin": ("حصين", "حصین", "حصین", "हसीन", "حصين", "strong_fortified", "Arabic", "Male",
           "Arabic root ح ص ن (ḥ-ṣ-n); حَصِين (Ḥaṣīn)", False, "medium",
           "Hasin is Arabic حَصِين (Ḥaṣīn) 'fortified, well-protected', from the root ح ص ن (ḥ-ṣ-n). CRITICAL SOURCE ERROR: the source gave حسن (that is hasan) and glossed the name 'Joyful, content, pleased'; the correct form is حَصِين (Ḥaṣīn). Same name as haseen."),
 "hasina": ("حسينة", "حسینہ", "حسینه", "हसीना", "حسینه", "good_beautiful", "Arabic", "Female",
            "Arabic root ح س ن (ḥ-s-n); حَسِينَة (Ḥasīna)", False, "medium",
            "Hasina is Arabic حَسِينَة (Ḥasīna) 'beautiful, good-natured', from the root ح س ن (ḥ-s-n). CRITICAL SOURCE ERROR: the source gave حسنا (that is hasna) and glossed the name 'Sweet, Delightful'; the correct form is حَسِينَة (Ḥasīna). Same name as haseena, hasinah and hassina."),
 "hasinah": ("حسينة", "حسینہ", "حسینه", "हसीना", "حسینه", "good_beautiful", "Arabic", "Female",
             "Arabic root ح س ن (ḥ-s-n); حَسِينَة (Ḥasīna)", False, "medium",
             "Hasinah is Arabic حَسِينَة (Ḥasīna) 'beautiful, good-natured', from the root ح س ن (ḥ-s-n). The source gloss 'Beautiful, adorned one' is broadly consistent. Same name as haseena, hasina and hassina."),
 "hasna": ("حسنا", "حسنا", "حسنا", "हसना", "حسنا", "good_beautiful", "Arabic", "Female",
           "Arabic root ح س ن (ḥ-s-n); حُسْنَى (Ḥusnā)", False, "medium",
           "Hasna is Arabic حُسْنَى (Ḥusnā) 'most beautiful, best', the feminine elative of حَسَن (ḥasan), from the root ح س ن (ḥ-s-n). The source gloss 'Beautiful, Good, Graceful' is broadly consistent. Same name as hasnaa and hasnah."),
 "hasnaa": ("حسناء", "حسناء", "حسناء", "हसना", "حسناء", "good_beautiful", "Arabic", "Female",
            "Arabic root ح س ن (ḥ-s-n); حَسْنَاء (Ḥasnāʾ)", False, "medium",
            "Hasnaa is Arabic حَسْنَاء (Ḥasnāʾ) 'beautiful, graceful', from the root ح س ن (ḥ-s-n). The source gloss 'Graceful, Beautiful, or Delightful' is broadly consistent. Same name as hasna and hasnah."),
 "hasnah": ("حسنة", "حسنہ", "حسنه", "हसना", "حسنه", "good_beautiful", "Arabic", "Female",
            "Arabic root ح س ن (ḥ-s-n); حَسَنَة (Ḥasana)", False, "medium",
            "Hasnah is Arabic حَسَنَة (Ḥasana) 'good, beautiful; good deed', from the root ح س ن (ḥ-s-n). The source gloss 'Graceful, Gentle' is broadly consistent. Same name as hasna and hasnaa."),
 "hasnain": ("حسنين", "حسنین", "حسنین", "हसनैन", "حسنین", "good_beautiful", "Arabic", "Male",
             "Dual form of حَسَن (Ḥasan); حَسَنَيْن (Ḥasanayn)", False, "high",
             "Hasnain is Arabic حَسَنَيْن (Ḥasanayn), the dual of حَسَن (Ḥasan), 'the two Hasans', referring to Hasan and Husayn. The source gloss 'Handsome, Good, Two Beauties' is broadly consistent. Same name as hasanain and hassnain."),
 "hasnat": ("حسنات", "حسنات", "حسنات", "हसनात", "حسنات", "good_beautiful", "Arabic", "Male",
            "Plural of حَسَنَة (ḥasana); حَسَنَات (Ḥasanāt)", False, "medium",
            "Hasnat is Arabic حَسَنَات (Ḥasanāt), the plural of حَسَنَة (ḥasana) 'good deed', meaning 'good deeds, virtues'. The source gloss 'Good Nature, Virtue' is broadly consistent. Same name as hasanat."),
 "hasoun": ("حسون", "حسون", "حسون", "हसून", "حسون", "good_beautiful", "Arabic", "Male",
            "Diminutive of حَسَن (Ḥasan); حَسُّون (Ḥassūn)", False, "low",
            "Hasoun is recorded at low confidence. The source gave حسون and glossed the name 'Gift, Blessing'; حَسُّون (Ḥassūn) is a diminutive of حَسَن (Ḥasan) used in some Arabic dialects, but its status as a standard given name and the source gloss could not be confirmed. No confident meaning is asserted."),
 "hasrat": ("حسرت", "حسرت", "حسرت", "हसरत", "حسرت", "regretful", "Persian", "Male",
            "Persian/Urdu حسرت (hasrat), from Arabic حَسْرَة", False, "medium",
            "Hasrat is Persian/Urdu حسرت (hasrat) 'longing, yearning, regret', from Arabic حَسْرَة. MISLABELLED ORIGIN: the source recorded the name as Arabic; it is a Persian/Urdu lexical item. The source gloss 'Desire or Wish' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "hassaan": ("حسان", "حسان", "حسان", "हस्सान", "حسان", "good_beautiful", "Arabic", "Male",
             "Arabic root ح س ن (ḥ-s-n); حَسَّان (Ḥassān)", False, "high",
             "Hassaan is Arabic حَسَّان (Ḥassān) 'very good, very beautiful', an intensive form from the root ح س ن (ḥ-s-n). It is a well-documented Arabic personal name, borne by the poet Hassan ibn Thabit. The source gloss 'Good, Handsome' is broadly consistent. Same name as hassan."),
 "hassam": ("حسام", "حسام", "حسام", "हस्साम", "حسام", "decisive", "Arabic", "Male",
            "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "medium",
            "Hassam is Arabic حُسَام (Ḥusām) 'a sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'To Strike, To Attack, To Protect' is unsupported and has been replaced with the lexical sense. The source labelled the name male, which matches documented usage."),
 "hassan": ("حسان", "حسان", "حسان", "हसन", "حسان", "good_beautiful", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); حَسَّان (Ḥassān)", False, "high",
            "Hassan is Arabic حَسَّان (Ḥassān) 'very good, very beautiful', an intensive form from the root ح س ن (ḥ-s-n), and is also widely used as a spelling of حَسَن (Ḥasan). The source record was an 8-key stub with no data. Same name as hassaan and hasan."),
 "hassana": ("حسنة", "حسنہ", "حسنه", "हसना", "حسنه", "good_beautiful", "Arabic", "Female",
             "Arabic root ح س ن (ḥ-s-n); حَسَنَة (Ḥasana)", False, "medium",
             "Hassana is Arabic حَسَنَة (Ḥasana) 'good, beautiful; good deed', from the root ح س ن (ḥ-s-n). The source gloss 'Graceful, Beautiful, Radiant' is broadly consistent. Same name as hasana, hasna and hasnah."),
 "hassib": ("حسيب", "حسیب", "حسیب", "हसीब", "حسيب", "reckoner", "Arabic", "Male",
            "Arabic root ح س ب (ḥ-s-b); حَسِيب (Ḥasīb)", False, "medium",
            "Hassib is Arabic حَسِيب (Ḥasīb) 'reckoner, one who accounts', from the root ح س ب (ḥ-s-b). The source gloss 'Generous, Magnificent' is unsupported and has been replaced with the lexical sense. Same name as haseeb and hasib."),
 "hassiba": ("حسيبة", "حسیبہ", "حسیبه", "हसीबा", "حسیبه", "reckoner", "Arabic", "Female",
             "Arabic root ح س ب (ḥ-s-b); حَسِيبَة (Ḥasība)", False, "low",
             "Hassiba is recorded at low confidence. The source gave حسيبة and glossed the name 'Gifted one'; حَسِيبَة (Ḥasība) is the feminine of حَسِيب (Ḥasīb), but the source gloss is unsupported and the name's independent attestation could not be confirmed. No confident meaning is asserted."),
 "hassina": ("حسينة", "حسینہ", "حسینه", "हसीना", "حسینه", "good_beautiful", "Arabic", "Female",
             "Arabic root ح س ن (ḥ-s-n); حَسِينَة (Ḥasīna)", False, "medium",
             "Hassina is Arabic حَسِينَة (Ḥasīna) 'beautiful, good-natured', from the root ح س ن (ḥ-s-n). The source gloss 'A charming one' is broadly consistent. Same name as haseena, hasina and hasinah."),
 "hassnain": ("حسنين", "حسنین", "حسنین", "हसनैन", "حسنین", "good_beautiful", "Arabic", "Male",
              "Dual form of حَسَن (Ḥasan); حَسَنَيْن (Ḥasanayn)", False, "medium",
              "Hassnain is Arabic حَسَنَيْن (Ḥasanayn), the dual of حَسَن (Ḥasan), 'the two Hasans'. CRITICAL SOURCE ERROR: the source gave ھسناین, using Urdu letters in the Arabic column; the correct Arabic form is حَسَنَيْن. The source gloss 'Handsome, Beautiful' is broadly consistent. Same name as hasanain and hasnain."),
 "hassun": ("حسن", "حسن", "حسن", "हसून", "حسن", "good_beautiful", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); حَسَن (Ḥasan)", False, "low",
            "Hassun is recorded at low confidence. The source gave حسن and glossed the name 'Gift'; the form is likely a diminutive of حَسَن (Ḥasan), but the source gloss is unsupported and the identification could not be confirmed. No confident meaning is asserted."),
 "hatam": ("حاتم", "حاتم", "حاتم", "हातिम", "حاتم", "seal_concluder", "Arabic", "Male",
           "Arabic root خ ت م (kh-t-m); حَاتِم (Ḥātim)", False, "high",
           "Hatam is a variant transliteration of Arabic حَاتِم (Ḥātim) 'seal, concluder, finisher', from the root خ ت م (kh-t-m). It is a well-documented Arabic personal name, borne by Hatim al-Ta'i, famed for his generosity. The source gloss 'Gifted, Generous' reflects the cultural association rather than the lexical sense. Same name as hatem and hatim."),
 "hatem": ("حاتم", "حاتم", "حاتم", "हातिम", "حاتم", "seal_concluder", "Arabic", "Male",
           "Arabic root خ ت م (kh-t-m); حَاتِم (Ḥātim)", False, "medium",
           "Hatem is a variant transliteration of Arabic حَاتِم (Ḥātim) 'seal, concluder, finisher'. CRITICAL SOURCE ERROR: the source gave هاتم (non-standard) and glossed the name 'Hater', which is a mistranslation; the correct form is حَاتِم. Same name as hatam and hatim."),
 "hatim": ("حاتم", "حاتم", "حاتم", "हातिम", "حاتم", "seal_concluder", "Arabic", "Male",
           "Arabic root خ ت م (kh-t-m); حَاتِم (Ḥātim)", False, "high",
           "Hatim is Arabic حَاتِم (Ḥātim) 'seal, concluder, finisher', from the root خ ت م (kh-t-m). It is a well-documented Arabic personal name, borne by Hatim al-Ta'i. The source gloss 'Judgment, Wise' is unsupported and has been replaced with the lexical sense. Same name as hatam and hatem."),
 "hattab": ("حطاب", "حطاب", "حطاب", "हत्ताब", "حطاب", "woodcutter", "Arabic", "Male",
            "Arabic root ح ط ب (ḥ-ṭ-b); حَطَّاب (Ḥaṭṭāb)", False, "medium",
            "Hattab is Arabic حَطَّاب (Ḥaṭṭāb) 'woodcutter, gatherer of firewood', from the root ح ط ب (ḥ-ṭ-b). The source gloss 'Horseman' is unsupported and has been replaced with the lexical sense. The source labelled the name male, which matches documented usage."),
 "haula": ("حولة", "حولہ", "حوله", "हौला", "حوله", "power_change", "Arabic", "Female",
           "Arabic root ح و ل (ḥ-w-l); حَوْلَة (Ḥawla)", False, "low",
           "Haula is recorded at low confidence. The source gave حولة and glossed the name 'Easy going, simple'; حَوْلَة (Ḥawla) is related to the root ح و ل (ḥ-w-l) 'power, change', but the source gloss is unsupported and the name's independent attestation could not be confirmed. No confident meaning is asserted. Same name as hawla."),
 "hawa": ("حواء", "حوا", "حوا", "हव्वा", "حوا", "eve_first_woman", "Arabic", "Female",
          "Qur'anic proper name; حَوَّاء (Ḥawwāʾ)", True, "high",
          "Hawa is Arabic حَوَّاء (Ḥawwāʾ), the name of Eve, the first woman, a Qur'anic proper name. The source record was an 8-key stub with no data. Same name as hawah, hawwa and hawwaa."),
 "hawah": ("حواء", "حوا", "حوا", "हव्वा", "حوا", "eve_first_woman", "Arabic", "Female",
           "Qur'anic proper name; حَوَّاء (Ḥawwāʾ)", True, "medium",
           "Hawah is Arabic حَوَّاء (Ḥawwāʾ), the name of Eve, the first woman. CRITICAL SOURCE ERROR: the source gave هوآه (non-standard) and glossed the name 'First woman, created from Adam's rib', which is a narrative gloss rather than a lexical meaning. Same name as hawa, hawwa and hawwaa."),
 "hawari": ("حواري", "حواری", "حواری", "हवारी", "حواري", "disciple_helper", "Arabic", "Male",
            "Arabic حَوَارِيّ (Ḥawāriyy)", False, "medium",
            "Hawari is Arabic حَوَارِيّ (Ḥawāriyy) 'disciple, helper, supporter', a term used in the Qur'an for the disciples of Jesus. CRITICAL SOURCE ERROR: the source gave هواري (non-standard); the correct form is حَوَارِيّ. The source gloss 'Guide, Helper' is broadly consistent. The source labelled the name unisex; documented usage is predominantly male."),
 "hawas": ("حواس", "حواس", "حواس", "हवास", "حواس", "senses", "Arabic", "Female",
           "Plural of حَاسَّة (ḥāssa); حَوَاسّ (Ḥawāss)", False, "medium",
           "Hawas is Arabic حَوَاسّ (Ḥawāss), the plural of حَاسَّة (ḥāssa) 'sense', meaning 'the five senses'. The source gloss 'Grace, Beauty' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "hawla": ("حولة", "حولہ", "حوله", "हौला", "حوله", "power_change", "Arabic", "Female",
           "Arabic root ح و ل (ḥ-w-l); حَوْلَة (Ḥawla)", False, "low",
           "Hawla is recorded at low confidence. The source gave هولة and glossed the name 'Revolving, continuous'; the form is uncertain and the gloss is unsupported. No confident meaning is asserted. Same name as haula."),
 "hawra": ("حوراء", "حوراء", "حوراء", "हौरा", "حوراء", "beautiful_white", "Arabic", "Female",
           "Arabic root ح و ر (ḥ-w-r); حَوْرَاء (Ḥawrāʾ)", False, "medium",
           "Hawra is Arabic حَوْرَاء (Ḥawrāʾ) 'fair-skinned, beautiful', from the root ح و ر (ḥ-w-r), related to the Qur'anic حُور (ḥūr). The source gloss 'Garden, fertile land' is unsupported and has been replaced with the lexical sense. Same name as hawraa."),
 "hawraa": ("حوراء", "حوراء", "حوراء", "हौरा", "حوراء", "beautiful_white", "Arabic", "Female",
            "Arabic root ح و ر (ḥ-w-r); حَوْرَاء (Ḥawrāʾ)", False, "medium",
            "Hawraa is Arabic حَوْرَاء (Ḥawrāʾ) 'fair-skinned, beautiful', from the root ح و ر (ḥ-w-r). The source gloss 'Fair Skinned Lady' is broadly consistent. Same name as hawra."),
 "hawwa": ("حواء", "حوا", "حوا", "हव्वा", "حوا", "eve_first_woman", "Arabic", "Female",
           "Qur'anic proper name; حَوَّاء (Ḥawwāʾ)", True, "high",
           "Hawwa is Arabic حَوَّاء (Ḥawwāʾ), the name of Eve, the first woman, a Qur'anic proper name. The source gloss 'First woman' is consistent. Same name as hawa, hawah and hawwaa."),
 "hawwaa": ("حواء", "حوا", "حوا", "हव्वा", "حوا", "eve_first_woman", "Arabic", "Female",
            "Qur'anic proper name; حَوَّاء (Ḥawwāʾ)", True, "high",
            "Hawwaa is Arabic حَوَّاء (Ḥawwāʾ), the name of Eve, the first woman, a Qur'anic proper name. The source gloss 'Eve' is consistent. Same name as hawa, hawah and hawwa."),
 "haya": ("حياء", "حیا", "حیا", "हया", "حیا", "modesty", "Arabic", "Female",
          "Arabic root ح ي ي (ḥ-y-y); حَيَاء (Ḥayāʾ)", False, "medium",
          "Haya is Arabic حَيَاء (Ḥayāʾ) 'modesty, shyness, sense of shame', from the root ح ي ي (ḥ-y-y). CRITICAL SOURCE ERROR: the source gave حيى (non-standard) and glossed the name 'Life, existence'; the correct form is حَيَاء. Same name as hayaa."),
 "hayaa": ("حياء", "حیا", "حیا", "हया", "حیا", "modesty", "Arabic", "Female",
           "Arabic root ح ي ي (ḥ-y-y); حَيَاء (Ḥayāʾ)", False, "medium",
           "Hayaa is Arabic حَيَاء (Ḥayāʾ) 'modesty, shyness, sense of shame', from the root ح ي ي (ḥ-y-y). The source gloss 'Shame, modesty, morality' is broadly consistent. Same name as haya."),
 "hayaat": ("حياة", "حیات", "حیات", "हयात", "حیات", "life", "Arabic", "Female",
            "Arabic root ح ي ي (ḥ-y-y); حَيَاة (Ḥayāh)", False, "high",
            "Hayaat is Arabic حَيَاة (Ḥayāh) 'life, existence', from the root ح ي ي (ḥ-y-y). The source gloss 'Life, Existence' is consistent. Same name as hayat and hayati."),
 "hayal": ("هيال", "ہیال", "هیال", "हयाल", "هیال", "life", "Arabic", "Female",
           "Arabic root ح ي ي (ḥ-y-y); خَيَال (Khayāl)", False, "low",
           "Hayal is recorded at low confidence. The source gave هيال and glossed the name 'Imagination'; the form is uncertain and may reflect خَيَال (khayāl, 'imagination') rather than a name from the root ح ي ي. No confident meaning is asserted."),
 "hayam": ("هيام", "ہیام", "هیام", "हयाम", "هیام", "life", "Arabic", "Female",
           "Arabic root ه ي م (h-y-m); هُيَام (Huyām)", False, "low",
           "Hayam is recorded at low confidence. The source gave no Arabic form and glossed the name 'Life, Existence'; the form هُيَام (Huyām) 'intense passion' is a documented Arabic word, but its identification with this slug and the source gloss could not be confirmed. No confident meaning is asserted."),
 "hayat": ("حياة", "حیات", "حیات", "हयात", "حیات", "life", "Arabic", "Female",
           "Arabic root ح ي ي (ḥ-y-y); حَيَاة (Ḥayāh)", False, "high",
           "Hayat is Arabic حَيَاة (Ḥayāh) 'life, existence', from the root ح ي ي (ḥ-y-y). The source gloss 'Life' is consistent. Same name as hayaat and hayati."),
 "hayati": ("حياتي", "حیاتی", "حیاتی", "हयाती", "حیاتي", "life", "Arabic", "Female",
            "Arabic root ح ي ي (ḥ-y-y); حَيَاتِي (Ḥayātī)", False, "medium",
            "Hayati is Arabic حَيَاتِي (Ḥayātī) 'my life', from the root ح ي ي (ḥ-y-y), an affectionate form of حَيَاة (Ḥayāh). The source gloss 'Life, Existence' is broadly consistent. Same name as hayaat and hayat."),
 "haydar": ("حيدر", "حیدر", "حیدر", "हैदर", "حیدر", "lion", "Arabic", "Male",
            "Arabic حَيْدَر (Ḥaydar)", False, "high",
            "Haydar is Arabic حَيْدَر (Ḥaydar) 'lion; brave, bold', a well-documented Arabic personal name and an epithet of Ali ibn Abi Talib. The source gloss 'Lion-like' is consistent. Same name as hayder."),
 "haydara": ("حيدرة", "حیدرہ", "حیدره", "हैदरा", "حیدره", "gazelle", "Arabic", "Female",
             "Arabic حَيْدَرَة (Ḥaydara)", False, "low",
             "Haydara is recorded at low confidence. The source gave هايدارا (non-standard) and glossed the name 'Gazelle'; the form حَيْدَرَة (Ḥaydara) is the feminine of حَيْدَر (Ḥaydar, 'lion'), not 'gazelle'. The source gloss is unsupported and no confident meaning is asserted."),
 "hayder": ("حيدر", "حیدر", "حیدر", "हैदर", "حیدر", "lion", "Arabic", "Male",
            "Arabic حَيْدَر (Ḥaydar)", False, "high",
            "Hayder is a variant transliteration of Arabic حَيْدَر (Ḥaydar) 'lion; brave, bold'. The source gloss 'Successor, Brave Sword' is unsupported and has been replaced with the lexical sense. Same name as haydar."),
 "hayet": ("حياة", "حیات", "حیات", "हयात", "حیات", "life", "Arabic", "Female",
           "Arabic root ح ي ي (ḥ-y-y); حَيَاة (Ḥayāh)", False, "medium",
           "Hayet is a North African transliteration of Arabic حَيَاة (Ḥayāh) 'life, existence'. CRITICAL SOURCE ERROR: the source gave هيئة ('form, appearance', a different word); the correct form is حَيَاة. Same name as hayaat, hayat and hayati."),
 "hayfa": ("حيفاء", "حیفاء", "حیفاء", "हैफ़ा", "حیفاء", "slender", "Arabic", "Female",
           "Arabic حَيْفَاء (Ḥayfāʾ)", False, "medium",
           "Hayfa is Arabic حَيْفَاء (Ḥayfāʾ) 'slender, graceful', a documented Arabic female given name. The source gloss 'Glorious, Radiant' is unsupported and has been replaced with the lexical sense. Same name as hayfaa."),
 "hayfaa": ("حيفاء", "حیفاء", "حیفاء", "हैफ़ा", "حیفاء", "slender", "Arabic", "Female",
            "Arabic حَيْفَاء (Ḥayfāʾ)", False, "medium",
            "Hayfaa is Arabic حَيْفَاء (Ḥayfāʾ) 'slender, graceful'. The source gloss 'Joy, Happiness' is unsupported and has been replaced with the lexical sense. Same name as hayfa."),
 "hayl": ("هيل", "ہیل", "هیل", "हैल", "هیل", "elevated", "Arabic", "Female",
          "Arabic root ه ي ل (h-y-l); هَيْل (Hayl)", False, "low",
          "Hayl is recorded at low confidence. The source gave هيل and glossed the name 'Life, Existence'; the form هَيْل (Hayl) is not a well-attested Arabic personal name and the gloss is unsupported. No confident meaning is asserted."),
 "haysam": ("هيثم", "ہیثم", "هیثم", "हैसम", "هیثم", "brave_lion", "Arabic", "Male",
            "Arabic هَيْثَم (Haytham)", False, "medium",
            "Haysam is a South Asian transliteration of Arabic هَيْثَم (Haytham) 'young eagle; brave'. CRITICAL SOURCE ERROR: the source gave حيسم (non-standard) and glossed the name 'Alive, living'; the correct form is هَيْثَم. Same name as haytham."),
 "haytham": ("هيثم", "ہیثم", "هیثم", "हैथम", "هیثم", "young_eagle", "Arabic", "Male",
             "Arabic هَيْثَم (Haytham)", False, "high",
             "Haytham is Arabic هَيْثَم (Haytham) 'young eagle; brave', a well-documented Arabic male given name. CRITICAL SOURCE ERROR: the source gave حييثم (non-standard) and glossed the name 'Successful seller'; the correct form is هَيْثَم. Same name as haysam."),
 "hayyan": ("حيان", "حیان", "حیان", "हय्यान", "حیان", "living", "Arabic", "Male",
            "Arabic root ح ي ي (ḥ-y-y); حَيَّان (Ḥayyān)", False, "medium",
            "Hayyan is Arabic حَيَّان (Ḥayyān) 'living, alive, ever-living', an intensive form from the root ح ي ي (ḥ-y-y). The source gloss 'Alive, Living' is broadly consistent. The source labelled the name unisex; documented usage is predominantly male."),
 "haza": ("حازة", "حازہ", "حازه", "हाज़ा", "حازه", "conveyance", "Arabic", "Female",
          "Arabic root ح و ز (ḥ-w-z); حَازَة (Ḥāza)", False, "low",
          "Haza is recorded at low confidence. The source gave حز and glossed the name 'Gift, Treasure'; the form is uncertain and the gloss is unsupported. No confident meaning is asserted."),
 "hazal": ("هزال", "ہزال", "هزال", "हज़ाल", "هزال", "emaciation", "Arabic", "Female",
           "Arabic root ه ز ل (h-z-l); هُزَال (Huzāl)", False, "low",
           "Hazal is recorded at low confidence. The source gave هزال and glossed the name 'Flower'; the form هُزَال (Huzāl) means 'emaciation, leanness', which is not a positive naming sense, and the source gloss is unsupported. No confident meaning is asserted."),
 "hazar": ("حذر", "حذر", "حذر", "हज़र", "حذر", "caution", "Arabic", "Male",
           "Arabic root ح ذ ر (ḥ-dh-r); حَذَر (Ḥadhar)", False, "low",
           "Hazar is recorded at low confidence. The source gave هازر and glossed the name 'Thousands'; the form حَذَر (Ḥadhar) 'caution, prudence' is a documented Arabic word, but its identification with this slug and the source gloss could not be confirmed. No confident meaning is asserted."),
 "hazeem": ("حزيم", "حزیم", "حزیم", "हज़ीम", "حزيم", "resolute", "Arabic", "Male",
            "Arabic root ح ز م (ḥ-z-m); حَزِيم (Ḥazīm)", False, "low",
            "Hazeem is recorded at low confidence. The source gave حزيم and glossed the name 'Vigilant, Watchful, Protective'; the form حَزِيم (Ḥazīm) is not a well-attested Arabic personal name, and the related root ح ز م (ḥ-z-m) yields حَازِم (Ḥāzim) 'resolute'. No confident meaning is asserted. Same name as hazem and hazim."),
 "hazem": ("حازم", "حازم", "حازم", "हाज़िम", "حازم", "resolute", "Arabic", "Male",
           "Arabic root ح ز م (ḥ-z-m); حَازِم (Ḥāzim)", False, "high",
           "Hazem is Arabic حَازِم (Ḥāzim) 'resolute, determined, firm of purpose', from the root ح ز م (ḥ-z-m). The source gloss 'Strong, Brave, Powerful' is broadly consistent. Same name as hazim and hazm."),
 "hazim": ("حازم", "حازم", "حازم", "हाज़िम", "حازم", "resolute", "Arabic", "Male",
           "Arabic root ح ز م (ḥ-z-m); حَازِم (Ḥāzim)", False, "high",
           "Hazim is Arabic حَازِم (Ḥāzim) 'resolute, determined, decisive', from the root ح ز م (ḥ-z-m). The source gloss 'Determined, Resolute' is consistent. Same name as hazem and hazm."),
 "haziq": ("حاذق", "حاذق", "حاذق", "हाज़िक़", "حاذق", "skilled", "Arabic", "Male",
           "Arabic root ح ذ ق (ḥ-dh-q); حَاذِق (Ḥādhiq)", False, "medium",
           "Haziq is Arabic حَاذِق (Ḥādhiq) 'skilled, proficient, adept', from the root ح ذ ق (ḥ-dh-q). CRITICAL SOURCE ERROR: the source gave حزيق (non-standard) and glossed the name 'Glowing, Radiant'; the correct form is حَاذِق. Same name as haziqah."),
 "haziqah": ("حاذقة", "حاذقہ", "حاذقه", "हाज़िक़ा", "حاذقه", "skilled", "Arabic", "Female",
             "Arabic root ح ذ ق (ḥ-dh-q); حَاذِقَة (Ḥādhiqa)", False, "medium",
             "Haziqah is Arabic حَاذِقَة (Ḥādhiqa) 'skilled, proficient', the feminine of حَاذِق (Ḥādhiq), from the root ح ذ ق (ḥ-dh-q). CRITICAL SOURCE ERROR: the source gave هزيقة (non-standard) and glossed the name 'Gift, Treasure'; the correct form is حَاذِقَة. Same name as haziq."),
 "hazir": ("حاضر", "حاضر", "حاضر", "हाज़िर", "حاضر", "present_ready", "Arabic", "Male",
           "Arabic root ح ض ر (ḥ-ḍ-r); حَاضِر (Ḥāḍir)", False, "medium",
           "Hazir is Arabic حَاضِر (Ḥāḍir) 'present, ready, at hand', from the root ح ض ر (ḥ-ḍ-r). The source gloss 'Present, Ready' is consistent. The source labelled the name male, which matches documented usage. Same name as hazirah."),
 "hazirah": ("حاضرة", "حاضرہ", "حاضره", "हाज़िरा", "حاضره", "present_ready", "Arabic", "Female",
             "Arabic root ح ض ر (ḥ-ḍ-r); حَاضِرَة (Ḥāḍira)", False, "low",
             "Hazirah is recorded at low confidence. The source gave حاذرة (non-standard) and glossed the name 'Ready, Prepared'; the intended form is likely حَاضِرَة (Ḥāḍira), the feminine of حَاضِر (Ḥāḍir), but the identification is uncertain. No confident meaning is asserted."),
 "haziran": ("حزيران", "حزیران", "حزیران", "हज़ीरान", "حزیران", "month_six", "Arabic", "Female",
             "Syriac/Aramaic month name; حَزِيرَان (Ḥazīrān)", False, "low",
             "Haziran is recorded at low confidence. حَزِيرَان (Ḥazīrān) is the name of a month (June) in the Levantine Syriac-derived calendar, not a personal name. MISLABELLED: the source recorded it as a female given name. No personal-name meaning is asserted."),
 "hazm": ("حزم", "حزم", "حزم", "हज़्म", "حزم", "resolute", "Arabic", "Male",
          "Arabic root ح ز م (ḥ-z-m); حَزْم (Ḥazm)", False, "medium",
          "Hazm is Arabic حَزْم (Ḥazm) 'firmness, determination, resoluteness', from the root ح ز م (ḥ-z-m). The source gloss 'Wisdom and Insight' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun. Same name as hazem and hazim."),
 "hazra": ("حزرى", "حزری", "حزری", "हज़रा", "حزری", "piety", "Arabic", "Female",
           "Arabic root ح ذ ر (ḥ-dh-r); حَذْرَى (Ḥadhrā)", False, "low",
           "Hazra is recorded at low confidence. The source gave حزرى and glossed the name 'Blessed one'; the form is uncertain and the gloss is unsupported. No confident meaning is asserted."),
 "hazrat": ("حضرة", "حضرت", "حضرت", "हज़रत", "حضرت", "honorific", "Arabic", "Male",
            "Arabic حَضْرَة (Ḥaḍra)", False, "medium",
            "Hazrat is Arabic حَضْرَة (Ḥaḍra) 'presence; an honorific title of respect', used before the names of revered figures. The source gloss 'Presence, Attributes of God' is partly unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily an honorific rather than a given name."),
 "hazwan": ("حزوان", "حزوان", "حزوان", "हज़वान", "حزوان", "joy", "Arabic", "Male",
            "Arabic root ح ز ن (ḥ-z-n); حَزْوَان (Ḥazwān)", False, "low",
            "Hazwan is recorded at low confidence. The source gave حزوان and glossed the name 'Gift, blessing'; the form حَزْوَان (Ḥazwān) is not a well-attested Arabic personal name, and the related root ح ز ن (ḥ-z-n) means 'sorrow' rather than 'joy'. No confident meaning is asserted."),
 "heba": ("هبة", "ہبہ", "هبه", "हिबा", "هبه", "gift", "Arabic", "Female",
          "Arabic root و ه ب (w-h-b); هِبَة (Hiba)", False, "high",
          "Heba is Arabic هِبَة (Hiba) 'gift, present, offering', from the root و ه ب (w-h-b). CRITICAL SOURCE ERROR: the source gave حبة ('a grain, a seed', a different word) and glossed the name 'Breath, Heart, Split'; the correct form is هِبَة. Same name as hebba."),
 "hebba": ("هبة", "ہبہ", "هبه", "हिबा", "هبه", "gift", "Arabic", "Female",
           "Arabic root و ه ب (w-h-b); هِبَة (Hiba)", False, "medium",
           "Hebba is Arabic هِبَة (Hiba) 'gift, present, offering', from the root و ه ب (w-h-b). CRITICAL SOURCE ERROR: the source gave حبة ('a grain, a seed') and glossed the name 'Young lady'; the correct form is هِبَة. Same name as heba."),
 "hedaya": ("هداية", "ہدایہ", "هدایه", "हिदाया", "هدایه", "guidance", "Arabic", "Female",
            "Arabic root ه د ي (h-d-y); هِدَايَة (Hidāya)", False, "high",
            "Hedaya is Arabic هِدَايَة (Hidāya) 'guidance, direction to the right path', from the root ه د ي (h-d-y). The source gloss 'Guiding, Enlightening' is broadly consistent. Same name as hedayat."),
 "hedayat": ("هداية", "ہدایت", "هدایت", "हिदायत", "هدایت", "guidance", "Arabic", "Female",
             "Arabic root ه د ي (h-d-y); هِدَايَة (Hidāya)", False, "medium",
             "Hedayat is Arabic هِدَايَة (Hidāya) 'guidance, direction to the right path', from the root ه د ي (h-d-y); the form هِدَايَت is the Persian/Urdu rendering. The source gloss 'Guiding Path, Enlightenment' is broadly consistent. Same name as hedaya."),
 "hedi": ("هدي", "ہدی", "هدی", "हेदी", "هدی", "gift", "Arabic", "Male",
          "Arabic root ه د ي (h-d-y); هَدْي (Hady)", False, "medium",
          "Hedi is Arabic هَدْي (Hady) 'gift, offering; guidance', from the root ه د ي (h-d-y). The source gloss 'Contentment, Satisfaction' is unsupported and has been replaced with the lexical sense. The source labelled the name female; documented usage is predominantly male."),
 "heela": ("حيلة", "حیلہ", "حیله", "हीला", "حیله", "stratagem", "Arabic", "Female",
           "Arabic root ح ي ل (ḥ-y-l); حِيلَة (Ḥīla)", False, "medium",
           "Heela is Arabic حِيلَة (Ḥīla) 'stratagem, device, clever plan', from the root ح ي ل (ḥ-y-l). The source gloss 'Light, Moon' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "helai": ("هلاء", "ہلاء", "هلاء", "हेलाई", "هلاء", "new_fresh", "Arabic", "Female",
           "Arabic root ه ل و (h-l-w); هَلَاء (Halāʾ)", False, "low",
           "Helai is recorded at low confidence. The source gave هلاء and glossed the name 'Light, Moon'; the form هَلَاء (Halāʾ) is not a well-attested Arabic personal name and the gloss is unsupported. No confident meaning is asserted."),
}
