# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 29 (hemin..hutaf).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": hena -> حنة (should be حِنَّاء); hessa -> حسا
   (should be حصة); hewad -> هود (Pashto هېواد, not Arabic); hichem -> هشيم (should be
   هشام); hidaya -> هِدَayah (broken); hila -> عائشة (that is Aisha, a different name);
   hilal -> ھلال (Urdu letters); hilmi -> ھلمي (Urdu letters); hindun -> ھندن (Urdu
   letters); hira -> ھیرا (Urdu letters); hisam -> حصام (should be حسام); hisyam ->
   حسيا م (broken); hoshyar -> حشير (a different word); houshang -> "Ali" (junk);
   hudaifa -> هديفة (should be حذيفة); humaira -> حمیرا (Urdu letters); humera ->
   حومرة (should be حميراء); husnain/hussnain -> حسنین (Urdu letters); hussein ->
   حسین (Urdu letters); hina -> "عربي_Hina" (junk); hoshang/homa/hooman/houman/
   houshang/hurmuz/hutaf -> Latin string repeated in the Arabic column.
 * DEGARBLED / WRONG glosses: hesam/hisam/hosaam/houssam/husaam/husam/hussam
   'Guardian/Protector/Excellence/Dedication/Awe-inspiring/One adorned with stones'
   (all should be 'sharp sword'); heydar 'Watchful, vigilant' (should be 'lion');
   heyam/hiyam/hoyam 'Life'/'Veil, Hidden'/'Young camel' (should be 'intense passion');
   hila 'Joyful, radiant' (should be 'stratagem'); hilali 'Rainmaker' (should be
   'of Hilal'); hosni 'Rich, Wealthy' (should be 'of Husayn'); hub 'A center or source'
   (should be 'love'); huma 'Life, existence' (Persian 'Homa bird'); humair 'Lion-like'
   (should be 'little donkey'); humam 'Companion' (should be 'brave, generous');
   husain/husein 'Graceful, Generous' (should be 'diminutive of Hasan'); hussam
   'One adorned with stones, gems' (should be 'sharp sword'); hutaf 'Sacred bond,
   connection' (should be 'cheering'); hood 'Enclosed Place, Hideaway' (should be
   the prophet Hud); hicham/hishaam 'Gift from Allah'/'Generous, Open-handed'
   (proper name Hisham); hesham 'Given by God' (proper name).
 * MISLABELLED ORIGIN (Persian, not Arabic): hemin, hoshang, hoshmand, hoshyar,
   houman, houshang, hurmuz, hoda, homa, hooman, humaun, humayn, humayun, hiwa.
   (Pashto: hewad. Somali: hodan. Hebrew: hilel.)
 * GENDER ERRORS: hemin, hesham, hewad, heydar, hicham, hichem, hidayat, hilali,
   hilel, hilmi, hisam, hishaam, hisyam, hood, houd, hud, humaid, humair, humam,
   humaun, humayn, humayun, humza, husaam, husain, husam, husayn, husein, husnain,
   husni, husnu, hussain, hussam, hussein, hussnain, hussni, hoyam, hukam were
   labelled female or unisex where documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: hiba, hind, hisham, hoor, hooria, huda, husna,
   hussain (8-key stubs); hemin, hessa, hewad, hifza, hina, hindun, hisyam, hiwa,
   hodan, hub, huba, hubba, humair, humayn, husnu, husnul, hutaf.
 * DUPLICATE CLUSTERS: hesam/hisam/hosaam/houssam/husaam/husam/hussam;
   hesham/hicham/hichem/hishaam/hisham/hisyam; hiba/hibah/hibat/hibba;
   hidaya/hidayah/hidayat; hikma/hikmah/hikmat; hila/hilya;
   hilal/hilali; hind/hindun; hoda/hooda/houda/huda;
   hood/houd/hud; hoor/hooria/horia; humaira/humairaa/humairah/humayra/humera/
   humeyra; humaun/humayn/humayun; husain/husayn/husein/hussain/hussein;
   husnain/hussnain; husni/hussni; husam/hussam.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated28 import GLOSSES as _G28

GLOSSES = dict(_G28)
GLOSSES.update({
    "sword": {"en": "Sharp sword; decisive", "ur": "تیز تلوار، فیصلہ کن", "fa": "شمشیر تیز، قاطع", "hi": "तेज़ तलवार, निर्णायक", "ps": "تیزه توره، قاطع", "ar": "الحسام، السيف القاطع"},
    "hisham": {"en": "Hisham (male given name)", "ur": "ہشام (مردانہ نام)", "fa": "هشام (نام مردانه)", "hi": "हिशाम (पुरुष नाम)", "ps": "هشام (نر نوم)", "ar": "هِشَام (اسم علم مذكر)"},
    "henna": {"en": "Henna; the henna plant and its dye", "ur": "حنا، مہندی", "fa": "حنا، وسمه", "hi": "मेहंदी, हिना", "ps": "حنا، مهندي", "ar": "الحِنَّاء، نبات الحناء وصبغته"},
    "hessa": {"en": "Hessa (female given name)", "ur": "حصہ (زنانہ نام)", "fa": "حصه (نام زنانه)", "hi": "हेस्सा (स्त्री नाम)", "ps": "حصه (ښځينه نوم)", "ar": "حِصَّة (اسم علم مؤنث)"},
    "homeland": {"en": "Homeland, native country", "ur": "وطن، آبائی ملک", "fa": "میهن، سرزمین مادری", "hi": "मातृभूमि, वतन", "ps": "هېواد، پلرنی ټاټوبی", "ar": "الوطن، البلد الأم"},
    "passion": {"en": "Intense passion, ardent love", "ur": "شدید عشق، سوز", "fa": "عشق شدید، شور", "hi": "तीव्र प्रेम, जुनून", "ps": "سخت مینه، اور", "ar": "الهيام، العشق الشديد"},
    "hisham_name": {"en": "Hisham (male given name)", "ur": "ہشام (مردانہ نام)", "fa": "هشام (نام مردانه)", "hi": "हिशाम (पुरुष नाम)", "ps": "هشام (نر نوم)", "ar": "هِشَام (اسم علم مذكر)"},
    "veil": {"en": "Veil, cover, screen", "ur": "پردہ، حجاب، اوٹ", "fa": "پرده، حجاب، پوشش", "hi": "पर्दा, आवरण, ओट", "ps": "پرده، حجاب، پټوالی", "ar": "الحجاب، الستر، الغطاء"},
    "hijaz": {"en": "Of the Hijaz; from the Hijaz region", "ur": "حجازی، حجاز سے منسوب", "fa": "حجازی، اهل حجاز", "hi": "हिजाज़ी, हिजाज़ से", "ps": "حجازي، د حجاز اړوند", "ar": "الحجازي، منسوب إلى الحجاز"},
    "migration": {"en": "Migration, emigration, journey", "ur": "ہجرت، نقل مکانی", "fa": "هجرت، کوچ", "hi": "हिजरत, प्रवास", "ps": "هجرت، کډوالي", "ar": "الهجرة، الانتقال، الرحيل"},
    "wisdom": {"en": "Wisdom, sound judgment", "ur": "حکمت، دانائی", "fa": "حکمت، خرد", "hi": "बुद्धिमत्ता, ज्ञान", "ps": "حکمت، پوهه", "ar": "الحكمة، الرأي السديد"},
    "crescent": {"en": "Crescent moon; new moon", "ur": "ہلال، نیا چاند", "fa": "هلال، ماه نو", "hi": "हिलाल, नया चाँद", "ps": "هلال، نوی سپوږمۍ", "ar": "الهلال، القمر الجديد"},
    "of_hilal": {"en": "Of Hilal; belonging to Hilal", "ur": "ہلالی، ہلال سے منسوب", "fa": "هلالی، منسوب به هلال", "hi": "हिलाली, हिलाल से", "ps": "هلالي، د هلال اړوند", "ar": "الهلالي، منسوب إلى هلال"},
    "hillel": {"en": "Hillel (Hebrew name meaning 'he has praised')", "ur": "ہلیل (عبرانی نام، معنی 'اس نے تعریف کی')", "fa": "هیلل (نام عبری، به معنای 'ستایش کرد')", "hi": "हिलेल (इब्रानी नाम, अर्थ 'उसने स्तुति की')", "ps": "هیلل (عبري نوم، مانا 'ستاینه یې وکړه')", "ar": "هيلل (اسم عبري بمعنى 'قد سبّح')"},
    "forbearance": {"en": "Forbearance, patience, clemency", "ur": "برداشت، حلم، رواداری", "fa": "بردباری، حلم، شکیبایی", "hi": "सहनशीलता, क्षमा, धैर्य", "ps": "زغم، حلم، برداشت", "ar": "الحلم، الأناة، الصبر"},
    "adornment": {"en": "Adornment, ornament, jewelry", "ur": "زیور، آرائش، سنگھار", "fa": "زیور، آرایش، پیرایه", "hi": "आभूषण, श्रृंगार", "ps": "ګاڼه، سینګار", "ar": "الحلية، الزينة، الجواهر"},
    "protection": {"en": "Protection, guardianship, safeguard", "ur": "حفاظت، نگہبانی، امان", "fa": "حمایت، نگهبانی، پاسداری", "hi": "सुरक्षा, रक्षा, संरक्षण", "ps": "ساتنه، پاملرنه، امان", "ar": "الحماية، الرعاية، الصيانة"},
    "hind": {"en": "Hind (female given name)", "ur": "ہند (زنانہ نام)", "fa": "هند (نام زنانه)", "hi": "हिंद (स्त्री नाम)", "ps": "هند (ښځينه نوم)", "ar": "هِنْد (اسم علم مؤنث)"},
    "hira_cave": {"en": "Hira; the cave where the Qur'anic revelation began", "ur": "حرا، وہ غار جہاں وحی کا آغاز ہوا", "fa": "حرا، غاری که وحی در آن آغاز شد", "hi": "हिरा, वह गुफा जहाँ वही आरंभ हुई", "ps": "حرا، هغه غار چې وحي پکې پیل شوه", "ar": "حِرَاء، الغار الذي بدأ فيه الوحي"},
    "hud_prophet": {"en": "Hud, a prophet mentioned in the Qur'an", "ur": "ہود، قرآن میں مذکور نبی", "fa": "هود، پیامبری که در قرآن ذکر شده", "hi": "हूद, क़ुरआन में उल्लिखित पैगंबर", "ps": "هود، په قرآن کې ذکر شوی پیغمبر", "ar": "هُود، نبي مذكور في القرآن"},
    "hudhayfa": {"en": "Hudhayfa (male given name)", "ur": "حذیفہ (مردانہ نام)", "fa": "حذیفه (نام مردانه)", "hi": "हुज़ैफ़ा (पुरुष नाम)", "ps": "حذیفه (نر نوم)", "ar": "حُذَيْفَة (اسم علم مذكر)"},
    "judgment": {"en": "Judgment, ruling, decision", "ur": "حکم، فیصلہ، عدل", "fa": "حکم، داوری، قضاوت", "hi": "निर्णय, फ़ैसला, हुक्म", "ps": "حکم، فیصله، قضاوت", "ar": "الحكم، القضاء، الفصل"},
    "homa_bird": {"en": "Homa; a mythical bird of Persian tradition", "ur": "ہما، فارسی روایت کا افسانوی پرندہ", "fa": "هما، پرنده افسانهای سنت ایرانی", "hi": "होमा, फ़ारसी परंपरा का पौराणिक पक्षी", "ps": "هما، د فارسي دود افسانوي مرغه", "ar": "هما، طائر أسطوري في التراث الفارسي"},
    "praiseworthy_dim": {"en": "Praiseworthy; diminutive of Hamid", "ur": "قابل تعریف، حمید کی تصغیر", "fa": "ستوده، تصغیر حمید", "hi": "प्रशंसनीय, हमीद का लघु रूप", "ps": "د ستاینې وړ، د حمید کوچنی بڼه", "ar": "الحميد، تصغير حامد"},
    "humayra": {"en": "Humayra; little reddish-brown one, a byname of Aisha", "ur": "حمیرا، سرخی مائل، عائشہ کا لقب", "fa": "حمیرا، سرخگون، لقب عایشه", "hi": "हुमैरा, लालिमायुक्त, आइशा की उपाधि", "ps": "حمیرا، سور رنګه، د عایشې لقب", "ar": "الحميراء، تصغير الحمراء، لقب عائشة"},
    "brave_generous": {"en": "Brave, generous, noble", "ur": "بہادر، سخی، شریف", "fa": "دلیر، بخشنده، نجیب", "hi": "वीर, उदार, कुलीन", "ps": "زړور، سخي، نجیب", "ar": "الهمام، الشجاع، الكريم"},
    "humayun": {"en": "Humayun; auspicious, fortunate (Persian)", "ur": "ہمایوں، مبارک، خوش قسمت", "fa": "همایون، فرخنده، نیکبخت", "hi": "हुमायूँ, शुभ, भाग्यशाली", "ps": "همایون، مبارک، نیکمرغه", "ar": "همايون، مبارك، سعيد (فارسي)"},
    "hamza": {"en": "Hamza; a male given name, also a glottal stop in Arabic", "ur": "حمزہ، مردانہ نام", "fa": "حمزه، نام مردانه", "hi": "हमज़ा, पुरुष नाम", "ps": "حمزه، نر نوم", "ar": "حَمْزَة (اسم علم مذكر)"},
    "hormuz": {"en": "Hormuz; a Persian name and place name", "ur": "ہرمز، فارسی نام اور مقام", "fa": "هرمز، نام و جاینام فارسی", "hi": "होर्मुज़, फ़ारसी नाम और स्थान", "ps": "هرمز، فارسي نوم او ځای", "ar": "هرمز، اسم ومكان فارسي"},
    "husayn": {"en": "Husayn; diminutive of Hasan", "ur": "حسین، حسن کی تصغیر", "fa": "حسین، تصغیر حسن", "hi": "हुसैन, हसन का लघु रूप", "ps": "حسین، د حسن کوچنی بڼه", "ar": "الحسين، تصغير الحسن"},
    "husnain": {"en": "Husnain; dual of Hasan, 'the two Hasans'", "ur": "حسنین، حسن کی تثنیہ", "fa": "حسنین، تثنیه حسن", "hi": "हुस्नैन, हसन का द्विवचन", "ps": "حسنین، د حسن دوهګون", "ar": "الحسنين، مثنى الحسن"},
    "husni": {"en": "Husni; of Husayn, belonging to Husayn", "ur": "حسنی، حسین سے منسوب", "fa": "حسنی، منسوب به حسین", "hi": "हुस्नी, हुसैन से", "ps": "حسني، د حسین اړوند", "ar": "الحسني، منسوب إلى حسين"},
    "beauty_goodness": {"en": "Beauty, goodness, excellence", "ur": "حسن، خوبی، بھلائی", "fa": "حسن، نیکویی، زیبایی", "hi": "सौंदर्य, भलाई, उत्कृष्टता", "ps": "ښکلا، ښېګڼه، غوره والی", "ar": "الحسن، الجمال، الخير"},
    "cheering": {"en": "Cheering, acclamation, applause", "ur": "نعرے، تالیاں، خوش آوازی", "fa": "هلهله، تشویق، آفرین", "hi": "जयकार, तालियाँ, प्रशंसा", "ps": "نارې، چکچکې، ستاینه", "ar": "الهتاف، التصفيق، التشجيع"},
    "hodan": {"en": "Hodan (Somali name meaning 'wealth, prosperity')", "ur": "ہودان (صومالی نام، معنی 'دولت، خوشحالی')", "fa": "هودان (نام سومالیایی، به معنای 'ثروت، رفاه')", "hi": "होदान (सोमाली नाम, अर्थ 'धन, समृद्धि')", "ps": "هودان (سومالیایي نوم، مانا 'شتمني، هوساینه')", "ar": "هودان (اسم صومالي بمعنى 'الثروة والرخاء')"},
    "hina_name": {"en": "Hina (female given name)", "ur": "ہنا (زنانہ نام)", "fa": "هینا (نام زنانه)", "hi": "हीना (स्त्री नाम)", "ps": "هینا (ښځينه نوم)", "ar": "هينا (اسم علم مؤنث)"},
    "hifza": {"en": "Hifza; preservation, safeguarding", "ur": "حفظہ، حفاظت، نگہداشت", "fa": "حفظه، نگهداری، پاسداشت", "hi": "हिफ़्ज़ा, संरक्षण, सुरक्षा", "ps": "حفظه، ساتنه، پاملرنه", "ar": "الحفظة، الصيانة، الرعاية"},
    "hiwa": {"en": "Hiwa (Kurdish name meaning 'hope')", "ur": "ہیوا (کردی نام، معنی 'امید')", "fa": "هیوا (نام کردی، به معنای 'امید')", "hi": "हीवा (कुर्दी नाम, अर्थ 'आशा')", "ps": "هیوا (کردي نوم، مانا 'هیله')", "ar": "هيوا (اسم كردي بمعنى 'الأمل')"},
    "huba": {"en": "Huba; a female given name", "ur": "حبہ (زنانہ نام)", "fa": "حبه (نام زنانه)", "hi": "हुबा (स्त्री नाम)", "ps": "حبه (ښځينه نوم)", "ar": "حُبَة (اسم علم مؤنث)"},
    "hubba": {"en": "Hubba; beloved, affectionate", "ur": "حبہ، محبوب، پیارا", "fa": "حبه، محبوب، دوستداشتنی", "hi": "हुब्बा, प्रिय, स्नेही", "ps": "حبه، خوږ، مینه ناک", "ar": "الحبّة، المحبوب، الودود"},
    "love": {"en": "Love, affection, attachment", "ur": "محبت، پیار، عشق", "fa": "عشق، محبت، دلبستگی", "hi": "प्रेम, स्नेह, मोहब्बत", "ps": "مینه، محبت، زړه تړاو", "ar": "الحب، المودة، العشق"},
    "little_donkey": {"en": "Little donkey; diminutive form", "ur": "چھوٹا گدھا، تصغیر", "fa": "الاغ کوچک، تصغیر", "hi": "छोटा गधा, लघु रूप", "ps": "کوچنی خر، کوچنی بڼه", "ar": "الحمير، تصغير الحمار"},
    "hushang": {"en": "Hushang; a Persian name of legendary kings", "ur": "ہوشنگ، فارسی نام", "fa": "هوشنگ، نامی در شاهنامه", "hi": "होशंग, फ़ारसी नाम", "ps": "هوشنګ، فارسي نوم", "ar": "هوشنك، اسم فارسي"},
    "wise_persian": {"en": "Wise, intelligent (Persian)", "ur": "دانا، عقلمند", "fa": "خردمند، دانا", "hi": "बुद्धिमान, समझदार", "ps": "پوه، عاقل", "ar": "الحكيم، العاقل (فارسي)"},
    "vigilant_persian": {"en": "Vigilant, alert (Persian)", "ur": "ہوشیار، چوکس", "fa": "هوشیار، بیدار", "hi": "सतर्क, चौकस", "ps": "هوښیار، ویښ", "ar": "اليقظ، المتيقظ (فارسي)"},
    "homa_name": {"en": "Homa; a Persian female given name", "ur": "ہما، فارسی زنانہ نام", "fa": "هما، نام زنانه فارسی", "hi": "होमा, फ़ारसी स्त्री नाम", "ps": "هما، فارسي ښځينه نوم", "ar": "هما، اسم علم مؤنث فارسي"},
    "hooman": {"en": "Hooman; a Persian male given name", "ur": "ہومن، فارسی مردانہ نام", "fa": "هومن، نام مردانه فارسی", "hi": "हूमन, फ़ारसी पुरुष नाम", "ps": "هومن، فارسي نر نوم", "ar": "هومن، اسم علم مذكر فارسي"},
    "houri": {"en": "Houri; a maiden of paradise in Islamic tradition", "ur": "حوری، جنت کی حسینہ", "fa": "حوری، پری بهشتی", "hi": "हूरी, जन्नत की अप्सरा", "ps": "حوري، د جنت پېری", "ar": "الحوراء، الحورية، من حور الجنة"},
    "hud_name": {"en": "Hud; a prophet mentioned in the Qur'an", "ur": "ہود، قرآن میں مذکور نبی", "fa": "هود، پیامبر مذکور در قرآن", "hi": "हूद, क़ुरआन में उल्लिखित पैगंबर", "ps": "هود، په قرآن کې ذکر شوی پیغمبر", "ar": "هُود، نبي مذكور في القرآن"},
    "guidance_f": {"en": "Guidance, direction to the right path", "ur": "ہدایت، رہنمائی", "fa": "هدایت، راهنمایی", "hi": "मार्गदर्शन, हिदायत", "ps": "هدایت، لارښوونه", "ar": "الهداية، الإرشاد"},
    "humaun": {"en": "Humaun; a Persian name meaning 'auspicious'", "ur": "ہمایوں، مبارک", "fa": "همایون، فرخنده", "hi": "हुमायूँ, शुभ", "ps": "همایون، مبارک", "ar": "همايون، مبارك (فارسي)"},
    "humayn": {"en": "Humayn; a male given name", "ur": "ہمین، مردانہ نام", "fa": "همین، نام مردانه", "hi": "हुमैन, पुरुष नाम", "ps": "همین، نر نوم", "ar": "هُمَيْن (اسم علم مذكر)"},
    "husnu": {"en": "Husnu; beauty, goodness", "ur": "حسن، خوبی", "fa": "حسن، نیکویی", "hi": "हुस्न, सौंदर्य", "ps": "حسن، ښکلا", "ar": "الحسن، الجمال"},
    "husnul": {"en": "Husn al-; 'the beauty of', a compound name element", "ur": "حسن الـ، ترکیبی نام کا جزو", "fa": "حسن الـ، جزء نام مرکب", "hi": "हुस्नुल-, संयुक्त नाम का अंश", "ps": "حسن الـ، د مرکب نوم برخه", "ar": "حسن الـ، عنصر في اسم مركب"},
    "hemin": {"en": "Hemin; a Persian male given name", "ur": "ہمین، فارسی مردانہ نام", "fa": "همین، نام مردانه فارسی", "hi": "हेमिन, फ़ारसी पुरुष नाम", "ps": "هیمن، فارسي نر نوم", "ar": "هيمن، اسم علم مذكر فارسي"},
    "hisyam": {"en": "Hisham (male given name)", "ur": "ہشام (مردانہ نام)", "fa": "هشام (نام مردانه)", "hi": "हिशाम (पुरुष नाम)", "ps": "هشام (نر نوم)", "ar": "هِشَام (اسم علم مذكر)"},
})

CUR = {
 "hemin": ("هیمن", "ہیمن", "هیمن", "हेमिन", "هیمن", "hemin", "Persian", "Male",
           "Persian هیمن (Hemin)", False, "low",
           "Hemin is recorded at low confidence. The source gave همين and glossed the name 'Exalted, Noble'; هیمن (Hemin) is a Kurdish/Persian male given name, but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "hena": ("حناء", "حنا", "حنا", "हिना", "حنا", "henna", "Arabic", "Female",
          "Arabic حِنَّاء (Ḥinnāʾ)", False, "medium",
          "Hena is Arabic حِنَّاء (Ḥinnāʾ) 'henna; the henna plant and its dye'. CRITICAL SOURCE ERROR: the source gave حنة (a different word) and glossed the name 'Graceful'; the correct form is حِنَّاء. Recorded at medium confidence because the word is primarily a common noun."),
 "hesam": ("حسام", "حسام", "حسام", "हुसाम", "حسام", "sword", "Arabic", "Male",
           "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "high",
           "Hesam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'Guardian, Protector' is unsupported and has been replaced with the lexical sense. Same name as hisam, hosaam, houssam, husaam, husam and hussam."),
 "hesham": ("هشام", "ہشام", "هشام", "हिशाम", "هشام", "hisham_name", "Arabic", "Male",
            "Arabic هِشَام (Hishām)", False, "high",
            "Hesham is Arabic هِشَام (Hishām), a well-documented male given name borne by Hisham ibn Abd al-Malik, an Umayyad caliph. The source gloss 'Given by God' is unsupported; the name is a proper name rather than a descriptive lexical item. Same name as hicham, hichem, hishaam, hisham and hisyam."),
 "hessa": ("حصة", "حصہ", "حصه", "हेस्सा", "حصه", "hessa", "Arabic", "Female",
           "Arabic حِصَّة (Ḥiṣṣa)", False, "low",
           "Hessa is recorded at low confidence. The source gave حسا and glossed the name 'Gentle, Soft'; حِصَّة (Ḥiṣṣa) is a documented Gulf female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "hewad": ("هېواد", "ہیواد", "هیواد", "हेबाद", "هېواد", "homeland", "Pashto", "Male",
           "Pashto هېواد (hewād)", False, "medium",
           "Hewad is Pashto هېواد (hewād) 'homeland, native country'. MISLABELLED ORIGIN: the source recorded the name as Arabic and gave هود (that is the prophet Hud, a different name). The source gloss 'Gift' is unsupported and has been replaced with the Pashto lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "heyam": ("هيام", "ہیام", "هیام", "हयाम", "هیام", "passion", "Arabic", "Female",
           "Arabic root ه ي م (h-y-m); هُيَام (Huyām)", False, "medium",
           "Heyam is Arabic هُيَام (Huyām) 'intense passion, ardent love', from the root ه ي م (h-y-m). The source gloss 'Life' is unsupported and has been replaced with the lexical sense. Same name as hiyam and hoyam."),
 "heydar": ("حيدر", "حیدر", "حیدر", "हैदर", "حیدر", "lion", "Arabic", "Male",
            "Arabic حَيْدَر (Ḥaydar)", False, "high",
            "Heydar is a variant transliteration of Arabic حَيْدَر (Ḥaydar) 'lion; brave, bold', a well-documented Arabic personal name and an epithet of Ali ibn Abi Talib. The source gloss 'Watchful, vigilant' is unsupported and has been replaced with the lexical sense. Same name as haydar and hayder."),
 "hiba": ("هبة", "ہبہ", "هبه", "हिबा", "هبه", "gift", "Arabic", "Female",
          "Arabic root و ه ب (w-h-b); هِبَة (Hiba)", False, "high",
          "Hiba is Arabic هِبَة (Hiba) 'gift, present, offering', from the root و ه ب (w-h-b). The source record was an 8-key stub with no data. Same name as hibah, hibat and hibba."),
 "hibah": ("هبة", "ہبہ", "هبه", "हिबा", "هبه", "gift", "Arabic", "Female",
           "Arabic root و ه ب (w-h-b); هِبَة (Hiba)", False, "high",
           "Hibah is Arabic هِبَة (Hiba) 'gift, present, offering', from the root و ه ب (w-h-b). The source gloss 'Gift' is consistent. Same name as hiba, hibat and hibba."),
 "hibat": ("هبة", "ہبہ", "هبه", "हिबा", "هبه", "gift", "Arabic", "Female",
           "Arabic root و ه ب (w-h-b); هِبَة (Hiba)", False, "medium",
           "Hibat is Arabic هِبَة (Hiba) 'gift, present, offering', from the root و ه ب (w-h-b). CRITICAL SOURCE ERROR: the source gave ھِبَات, using Urdu letters in the Arabic column; the correct Arabic form is هِبَة. The source gloss 'Gift' is consistent. Same name as hiba, hibah and hibba."),
 "hibba": ("هبة", "ہبہ", "هبه", "हिबा", "هبه", "gift", "Arabic", "Female",
           "Arabic root و ه ب (w-h-b); هِبَة (Hiba)", False, "medium",
           "Hibba is Arabic هِبَة (Hiba) 'gift, present, offering', from the root و ه ب (w-h-b). The source gloss 'Gift, Present' is consistent. Same name as hiba, hibah and hibat."),
 "hicham": ("هشام", "ہشام", "هشام", "हिशाम", "هشام", "hisham_name", "Arabic", "Male",
            "Arabic هِشَام (Hishām)", False, "high",
            "Hicham is a North African transliteration of Arabic هِشَام (Hishām), a well-documented male given name. The source gloss 'Gift from Allah' is unsupported; the name is a proper name. Same name as hesham, hichem, hishaam, hisham and hisyam."),
 "hichem": ("هشام", "ہشام", "هشام", "हिशाम", "هشام", "hisham_name", "Arabic", "Male",
            "Arabic هِشَام (Hishām)", False, "medium",
            "Hichem is a North African transliteration of Arabic هِشَام (Hishām). CRITICAL SOURCE ERROR: the source gave هشيم (a different word) and glossed the name 'Wise, Intelligent'; the correct form is هِشَام. Same name as hesham, hicham, hishaam, hisham and hisyam."),
 "hidaya": ("هداية", "ہدایہ", "هدایه", "हिदाया", "هدایه", "guidance_f", "Arabic", "Female",
            "Arabic root ه د ي (h-d-y); هِدَايَة (Hidāya)", False, "medium",
            "Hidaya is Arabic هِدَايَة (Hidāya) 'guidance, direction to the right path', from the root ه د ي (h-d-y). CRITICAL SOURCE ERROR: the source gave هِدَayah (a broken mixed-script form); the correct form is هِدَايَة. The source gloss 'Guiding, leading' is broadly consistent. Same name as hidayah and hidayat."),
 "hidayah": ("هداية", "ہدایہ", "هدایه", "हिदाया", "هدایه", "guidance_f", "Arabic", "Female",
             "Arabic root ه د ي (h-d-y); هِدَايَة (Hidāya)", False, "high",
             "Hidayah is Arabic هِدَايَة (Hidāya) 'guidance, direction to the right path', from the root ه د ي (h-d-y). The source gloss 'Guidance from Allah' is broadly consistent. Same name as hidaya and hidayat."),
 "hidayat": ("هداية", "ہدایت", "هدایت", "हिदायत", "هدایت", "guidance_f", "Arabic", "Male",
             "Arabic root ه د ي (h-d-y); هِدَايَة (Hidāya)", False, "medium",
             "Hidayat is Arabic هِدَايَة (Hidāya) 'guidance, direction to the right path', from the root ه د ي (h-d-y); the form هِدَايَت is the Persian/Urdu rendering. The source gloss 'Right guidance' is broadly consistent. The source labelled the name male, which matches South Asian usage. Same name as hidaya and hidayah."),
 "hifza": ("حفظة", "حفظہ", "حفظه", "हिफ़्ज़ा", "حفظه", "hifza", "Arabic", "Female",
           "Arabic root ح ف ظ (ḥ-f-ẓ); حِفْظَة (Ḥifẓa)", False, "low",
           "Hifza is recorded at low confidence. The source gave حِفْظَة and glossed the name 'Preservation, Protection'; the form حِفْظَة (Ḥifẓa) is related to the root ح ف ظ (ḥ-f-ẓ) 'to preserve, to guard', but its status as a standard given name could not be confirmed. No confident meaning is asserted."),
 "hijab": ("حجاب", "حجاب", "حجاب", "हिजाब", "حجاب", "veil", "Arabic", "Female",
           "Arabic root ح ج ب (ḥ-j-b); حِجَاب (Ḥijāb)", False, "medium",
           "Hijab is Arabic حِجَاب (Ḥijāb) 'veil, cover, screen', from the root ح ج ب (ḥ-j-b). The source gloss 'Cover, veil' is consistent. Recorded at medium confidence because the word is primarily a common noun. The source labelled the name unisex; documented usage is predominantly female."),
 "hijazi": ("حجازي", "حجازی", "حجازی", "हिजाज़ी", "حجازي", "hijaz", "Arabic", "Male",
            "Nisba of الحجاز; حِجَازِيّ (Ḥijāziyy)", False, "medium",
            "Hijazi is Arabic حِجَازِيّ (Ḥijāziyy), the nisba of الحجاز (al-Ḥijāz), meaning 'of the Hijaz; from the Hijaz region'. The source gloss 'From Hijaz' is consistent. The source labelled the name unisex; documented usage is predominantly male."),
 "hijrah": ("هجرة", "ہجرت", "هجرت", "हिजरत", "هجرت", "migration", "Arabic", "Female",
            "Arabic root ه ج ر (h-j-r); هِجْرَة (Hijra)", False, "medium",
            "Hijrah is Arabic هِجْرَة (Hijra) 'migration, emigration, journey', from the root ه ج ر (h-j-r); it also denotes the migration of the Prophet Muhammad from Mecca to Medina. The source gloss 'Migration, Journey' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "hikma": ("حكمة", "حکمت", "حکمت", "हिकमा", "حکمت", "wisdom", "Arabic", "Female",
           "Arabic root ح ك م (ḥ-k-m); حِكْمَة (Ḥikma)", False, "high",
           "Hikma is Arabic حِكْمَة (Ḥikma) 'wisdom, sound judgment', from the root ح ك م (ḥ-k-m). The source gloss 'Wisdom' is consistent. Same name as hikmah and hikmat."),
 "hikmah": ("حكمة", "حکمت", "حکمت", "हिकमा", "حکمت", "wisdom", "Arabic", "Female",
            "Arabic root ح ك م (ḥ-k-m); حِكْمَة (Ḥikma)", False, "high",
            "Hikmah is Arabic حِكْمَة (Ḥikma) 'wisdom, sound judgment', from the root ح ك م (ḥ-k-m). The source gloss 'Wisdom' is consistent. Same name as hikma and hikmat."),
 "hikmat": ("حكمة", "حکمت", "حکمت", "हिकमत", "حکمت", "wisdom", "Arabic", "Male",
            "Arabic root ح ك م (ḥ-k-m); حِكْمَة (Ḥikma)", False, "medium",
            "Hikmat is Arabic حِكْمَة (Ḥikma) 'wisdom, sound judgment', from the root ح ك م (ḥ-k-m); the form حِكْمَت is the Persian/Urdu rendering. The source gloss 'Wisdom' is consistent. The source labelled the name unisex; documented usage is predominantly male in South Asia. Same name as hikma and hikmah."),
 "hila": ("حيلة", "حیلہ", "حیله", "हीला", "حیله", "stratagem", "Arabic", "Female",
          "Arabic root ح ي ل (ḥ-y-l); حِيلَة (Ḥīla)", False, "medium",
          "Hila is Arabic حِيلَة (Ḥīla) 'stratagem, device, clever plan', from the root ح ي ل (ḥ-y-l). CRITICAL SOURCE ERROR: the source gave عائشة (that is Aisha, a different name) and glossed the name 'Joyful, radiant'; the correct form is حِيلَة. Same name as heela."),
 "hilal": ("هلال", "ہلال", "هلال", "हिलाल", "هلال", "crescent", "Arabic", "Male",
           "Arabic root ه ل ل (h-l-l); هِلَال (Hilāl)", False, "high",
           "Hilal is Arabic هِلَال (Hilāl) 'crescent moon; new moon', from the root ه ل ل (h-l-l). CRITICAL SOURCE ERROR: the source gave ھلال, using Urdu letters in the Arabic column; the correct Arabic form is هِلَال. The source gloss 'Crescent Moon' is consistent. The source labelled the name unisex; documented usage is predominantly male."),
 "hilali": ("هلالي", "ہلالی", "هلالی", "हिलाली", "هلالي", "of_hilal", "Arabic", "Male",
            "Nisba of هِلَال; هِلَالِيّ (Hilāliyy)", False, "medium",
            "Hilali is Arabic هِلَالِيّ (Hilāliyy), the nisba of هِلَال (Hilāl), meaning 'of Hilal; belonging to Hilal'. The source gloss 'Rainmaker' is unsupported and has been replaced with the lexical sense. The source labelled the name male, which matches documented usage."),
 "hilel": ("הלל", "ہلیل", "هیلل", "हिलेल", "هیلل", "hillel", "Hebrew", "Male",
           "Hebrew הִלֵּל (Hillel)", False, "medium",
           "Hilel is Hebrew הִלֵּל (Hillel) 'he has praised', a documented Jewish male given name. MISLABELLED ORIGIN: the source recorded the name as Arabic and gave حِليل. The source gloss 'He whom God revealed' is unsupported and has been replaced with the Hebrew lexical sense."),
 "hilmi": ("حلمي", "حلمی", "حلمی", "हिल्मी", "حلمي", "forbearance", "Arabic", "Male",
           "Arabic root ح ل م (ḥ-l-m); حِلْمِيّ (Ḥilmiyy)", False, "medium",
           "Hilmi is Arabic حِلْمِيّ (Ḥilmiyy) 'of forbearance, clement', from the root ح ل م (ḥ-l-m). CRITICAL SOURCE ERROR: the source gave ھلمي, using Urdu letters in the Arabic column; the correct Arabic form is حِلْمِيّ. The source gloss 'Wise, Knowledgeable' is unsupported and has been replaced with the lexical sense."),
 "hilya": ("حلية", "حلیہ", "حلیه", "हिल्या", "حلیه", "adornment", "Arabic", "Female",
           "Arabic root ح ل ي (ḥ-l-y); حِلْيَة (Ḥilya)", False, "medium",
           "Hilya is Arabic حِلْيَة (Ḥilya) 'adornment, ornament, jewelry', from the root ح ل ي (ḥ-l-y). The source gloss 'Grace' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "himayat": ("حماية", "حمایت", "حمایت", "हिमायत", "حمایت", "protection", "Arabic", "Female",
             "Arabic root ح م ي (ḥ-m-y); حِمَايَة (Ḥimāya)", False, "medium",
             "Himayat is Arabic حِمَايَة (Ḥimāya) 'protection, guardianship, safeguard', from the root ح م ي (ḥ-m-y). The source gloss 'Protection, Guardianship' is consistent. Recorded at medium confidence because the word is primarily a common noun. The source labelled the name unisex; documented usage is predominantly female."),
 "hina": ("هينا", "ہینا", "هینا", "हीना", "هینا", "hina_name", "Arabic", "Female",
          "Arabic هِينَا (Hīnā)", False, "low",
          "Hina is recorded at low confidence. The source gave the junk string 'عربي_Hina' in the Arabic column and glossed the name 'Noble and blessed'; the form هِينَا (Hīnā) is a documented female given name in South Asia, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "hind": ("هند", "ہند", "هند", "हिंद", "هند", "hind", "Arabic", "Female",
          "Arabic هِنْد (Hind)", False, "high",
          "Hind is Arabic هِنْد (Hind), a well-documented female given name borne by Hind bint Utba, a companion of the Prophet Muhammad. The source record was an 8-key stub with no data. Same name as hindun."),
 "hindun": ("هند", "ہند", "هند", "हिंद", "هند", "hind", "Arabic", "Female",
            "Arabic هِنْد (Hind)", False, "medium",
            "Hindun is Arabic هِنْد (Hind), a well-documented female given name. CRITICAL SOURCE ERROR: the source gave ھندن, using Urdu letters in the Arabic column; the correct Arabic form is هِنْد. The source gloss 'Peaceful and serene' is unsupported and has been replaced with the proper-name identification. Same name as hind."),
 "hira": ("حراء", "حرا", "حرا", "हिरा", "حرا", "hira_cave", "Arabic", "Female",
          "Arabic حِرَاء (Ḥirāʾ)", False, "medium",
          "Hira is Arabic حِرَاء (Ḥirāʾ), the name of the cave where the Qur'anic revelation began; it is also used as a female given name. CRITICAL SOURCE ERROR: the source gave ھیرا, using Urdu letters in the Arabic column; the correct Arabic form is حِرَاء. The source gloss 'Diamond, Name of the cave where Quran...' is partly unsupported and has been replaced with the documented identification."),
 "hisam": ("حسام", "حسام", "حسام", "हुसाम", "حسام", "sword", "Arabic", "Male",
           "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "medium",
           "Hisam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). CRITICAL SOURCE ERROR: the source gave حصام (a different word) and glossed the name 'Protector, Guardian'; the correct form is حُسَام. Same name as hesam, hosaam, houssam, husaam, husam and hussam."),
 "hishaam": ("هشام", "ہشام", "هشام", "हिशाम", "هشام", "hisham_name", "Arabic", "Male",
             "Arabic هِشَام (Hishām)", False, "high",
             "Hishaam is Arabic هِشَام (Hishām), a well-documented male given name. The source gloss 'Generous, Open-handed' is unsupported; the name is a proper name. Same name as hesham, hicham, hichem, hisham and hisyam."),
 "hisham": ("هشام", "ہشام", "هشام", "हिशाम", "هشام", "hisham_name", "Arabic", "Male",
            "Arabic هِشَام (Hishām)", False, "high",
            "Hisham is Arabic هِشَام (Hishām), a well-documented male given name borne by Hisham ibn Abd al-Malik, an Umayyad caliph. The source record was an 8-key stub with no data. Same name as hesham, hicham, hichem, hishaam and hisyam."),
 "hisyam": ("هشام", "ہشام", "هشام", "हिशाम", "هشام", "hisyam", "Arabic", "Male",
            "Arabic هِشَام (Hishām)", False, "low",
            "Hisyam is recorded at low confidence. The source gave the broken form حسيا م and glossed the name 'Gift, Grace, Blessing'; the intended form is likely هِشَام (Hishām), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as hesham, hicham, hichem, hishaam and hisham."),
 "hiwa": ("هیوا", "ہیوا", "هیوا", "हीवा", "هیوا", "hiwa", "Kurdish", "Female",
          "Kurdish هیوا (Hiwa)", False, "low",
          "Hiwa is recorded at low confidence. The source gave هيوا and glossed the name 'Life, Living'; هیوا (Hiwa) is a Kurdish name meaning 'hope', but the source's gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "hiyam": ("هيام", "ہیام", "هیام", "हयाम", "هیام", "passion", "Arabic", "Female",
           "Arabic root ه ي م (h-y-m); هُيَام (Huyām)", False, "medium",
           "Hiyam is Arabic هُيَام (Huyām) 'intense passion, ardent love', from the root ه ي م (h-y-m). The source gloss 'Veil, Hidden' is unsupported and has been replaced with the lexical sense. Same name as heyam and hoyam."),
 "hoda": ("هدی", "ہدی", "هدی", "होदा", "هدی", "guidance_f", "Persian", "Female",
          "Persian هدی (Hodā), from Arabic هُدَى", False, "medium",
          "Hoda is Persian هدی (Hodā) 'guidance', from Arabic هُدَى (Hudā). MISLABELLED ORIGIN: the source recorded the name as Arabic; the form هدی is the Persian rendering. The source gloss 'Guiding' is broadly consistent. Same name as hooda, houda and huda."),
 "hodan": ("هودان", "ہودان", "هودان", "होदान", "هودان", "hodan", "Somali", "Female",
           "Somali Hodan", False, "low",
           "Hodan is recorded at low confidence. The source gave حُدان and glossed the name 'Grace, Generosity, Gift'; Hodan is a Somali female given name meaning 'wealth, prosperity', but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "homa": ("هما", "ہما", "هما", "होमा", "هما", "homa_name", "Persian", "Female",
           "Persian هما (Homā)", False, "medium",
           "Homa is Persian هما (Homā), a female given name and the name of a mythical bird of Persian tradition. MISLABELLED ORIGIN: the source recorded the name as Arabic and repeated the Latin string in the Arabic column. The source gloss 'Blooming' is unsupported and has been replaced with the documented identification."),
 "hood": ("هود", "ہود", "هود", "हूद", "هود", "hud_name", "Arabic", "Male",
          "Qur'anic proper name; هُود (Hūd)", True, "high",
          "Hood is a transliteration of Arabic هُود (Hūd), a prophet mentioned in the Qur'an and the name of a Qur'anic sura. The source gloss 'Enclosed Place, Hideaway' is unsupported and has been replaced with the documented identification. Same name as houd and hud."),
 "hooda": ("هدی", "ہدی", "هدی", "हुदा", "هدی", "guidance_f", "Arabic", "Female",
           "Arabic root ه د ي (h-d-y); هُدَى (Hudā)", False, "medium",
           "Hooda is Arabic هُدَى (Hudā) 'guidance, direction to the right path', from the root ه د ي (h-d-y). The source gloss 'Guide, Leader' is broadly consistent. Same name as hoda, houda and huda."),
 "hooman": ("هومن", "ہومن", "هومن", "हूमन", "هومن", "hooman", "Persian", "Male",
            "Persian هومن (Hūman)", False, "low",
            "Hooman is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Meaning not available'; هومن (Hūman) is a Persian male given name, but no lexical meaning could be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "hoor": ("حور", "حور", "حور", "हूर", "حور", "houri", "Arabic", "Female",
          "Arabic root ح و ر (ḥ-w-r); حُور (Ḥūr)", False, "high",
          "Hoor is Arabic حُور (Ḥūr), the plural of حَوْرَاء (Ḥawrāʾ), denoting the maidens of paradise in Islamic tradition. The source record was an 8-key stub with no data. Same name as hooria and horia."),
 "hooria": ("حورية", "حوریہ", "حوریه", "हूरिया", "حوریه", "houri", "Arabic", "Female",
            "Arabic root ح و ر (ḥ-w-r); حُورِيَّة (Ḥūriyya)", False, "high",
            "Hooria is Arabic حُورِيَّة (Ḥūriyya) 'houri; a maiden of paradise in Islamic tradition', from the root ح و ر (ḥ-w-r). The source record was an 8-key stub with no data. Same name as hoor and horia."),
 "horia": ("حورية", "حوریہ", "حوریه", "हूरिया", "حوریه", "houri", "Arabic", "Female",
           "Arabic root ح و ر (ḥ-w-r); حُورِيَّة (Ḥūriyya)", False, "medium",
           "Horia is Arabic حُورِيَّة (Ḥūriyya) 'houri; a maiden of paradise in Islamic tradition', from the root ح و ر (ḥ-w-r). The source gloss 'Light, Radiance' is unsupported and has been replaced with the lexical sense. Same name as hoor and hooria."),
 "hosaam": ("حسام", "حسام", "حسام", "हुसाम", "حسام", "sword", "Arabic", "Male",
            "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "medium",
            "Hosaam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'Excellence, Distinction' is unsupported and has been replaced with the lexical sense. Same name as hesam, hisam, houssam, husaam, husam and hussam."),
 "hoshang": ("هوشنگ", "ہوشنگ", "هوشنگ", "होशंग", "هوشنګ", "hushang", "Persian", "Male",
             "Persian هوشنگ (Hūshang)", False, "medium",
             "Hoshang is Persian هوشنگ (Hūshang), a male given name borne by legendary kings in the Shahnameh. MISLABELLED ORIGIN: the source recorded the name as Arabic and repeated the Latin string in the Arabic column. The source gloss 'Shining, Bright' is unsupported and has been replaced with the documented identification."),
 "hoshmand": ("هوشمند", "ہوشمند", "هوشمند", "होशमंद", "هوشمند", "wise_persian", "Persian", "Male",
              "Persian هوشمند (hūshmand)", False, "medium",
              "Hoshmand is Persian هوشمند (hūshmand) 'wise, intelligent'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Luminous, Radiant, Shining' is unsupported and has been replaced with the Persian lexical sense. Recorded at medium confidence because the word is primarily an adjective."),
 "hoshyar": ("هوشیار", "ہوشیار", "هوشیار", "होशियार", "هوښیار", "vigilant_persian", "Persian", "Male",
             "Persian هوشیار (hūshyār)", False, "medium",
             "Hoshyar is Persian هوشیار (hūshyār) 'vigilant, alert'. CRITICAL SOURCE ERROR: the source gave حشير (a different word) and glossed the name 'Victorious, conqueror'; the correct form is هوشیار. MISLABELLED ORIGIN: the source recorded the name as Arabic. Recorded at medium confidence because the word is primarily an adjective."),
 "hosna": ("حسنى", "حسنی", "حسنی", "हुस्ना", "حسنی", "beauty_goodness", "Arabic", "Female",
           "Arabic root ح س ن (ḥ-s-n); حُسْنَى (Ḥusnā)", False, "medium",
           "Hosna is Arabic حُسْنَى (Ḥusnā) 'most beautiful, best', the feminine elative of حَسَن (ḥasan), from the root ح س ن (ḥ-s-n). The source gave حُسْن and glossed the name 'Pure, Hallowed, Precious', which is unsupported; the lexical sense is 'most beautiful, best'. Same name as husna."),
 "hosni": ("حسني", "حسنی", "حسنی", "हुस्नी", "حسني", "husni", "Arabic", "Male",
           "Nisba of حُسَيْن; حُسْنِيّ (Ḥusniyy)", False, "medium",
           "Hosni is Arabic حُسْنِيّ (Ḥusniyy), the nisba of حُسَيْن (Ḥusayn), meaning 'of Husayn; belonging to Husayn'. The source gloss 'Rich, Wealthy' is unsupported and has been replaced with the lexical sense. Same name as husni and hussni."),
 "houd": ("هود", "ہود", "هود", "हूद", "هود", "hud_name", "Arabic", "Male",
          "Qur'anic proper name; هُود (Hūd)", True, "high",
          "Houd is a transliteration of Arabic هُود (Hūd), a prophet mentioned in the Qur'an. The source gloss 'Help, Support' is unsupported and has been replaced with the documented identification. Same name as hood and hud."),
 "houda": ("هدی", "ہدی", "هدی", "हुदा", "هدی", "guidance_f", "Arabic", "Female",
           "Arabic root ه د ي (h-d-y); هُدَى (Hudā)", False, "high",
           "Houda is Arabic هُدَى (Hudā) 'guidance, direction to the right path', from the root ه د ي (h-d-y). The source gloss 'Guide, Path, or Direction' is broadly consistent. Same name as hoda, hooda and huda."),
 "houman": ("هومن", "ہومن", "هومن", "हूमन", "هومن", "hooman", "Persian", "Male",
            "Persian هومن (Hūman)", False, "low",
            "Houman is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Man of wisdom'; هومن (Hūman) is a Persian male given name, but the source gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "houshang": ("هوشنگ", "ہوشنگ", "هوشنگ", "होशंग", "هوشنګ", "hushang", "Persian", "Male",
              "Persian هوشنگ (Hūshang)", False, "medium",
              "Houshang is Persian هوشنگ (Hūshang), a male given name borne by legendary kings in the Shahnameh. CRITICAL SOURCE ERROR: the source gave the junk string 'Ali' in the Arabic column and glossed the name 'House builder'; the correct form is هوشنگ. MISLABELLED ORIGIN: the source recorded the name as Arabic."),
 "houssam": ("حسام", "حسام", "حسام", "हुसाम", "حسام", "sword", "Arabic", "Male",
             "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "high",
             "Houssam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'Dedication, Commitment' is unsupported and has been replaced with the lexical sense. Same name as hesam, hisam, hosaam, husaam, husam and hussam."),
 "hoyam": ("هيام", "ہیام", "هیام", "हयाम", "هیام", "passion", "Arabic", "Female",
           "Arabic root ه ي م (h-y-m); هُيَام (Huyām)", False, "medium",
           "Hoyam is Arabic هُيَام (Huyām) 'intense passion, ardent love', from the root ه ي م (h-y-m). The source gloss 'Young camel' is unsupported and has been replaced with the lexical sense. The source labelled the name male; documented usage is predominantly female. Same name as heyam and hiyam."),
 "hub": ("حب", "حب", "حب", "हुब", "حب", "love", "Arabic", "Male",
         "Arabic root ح ب ب (ḥ-b-b); حُبّ (Ḥubb)", False, "low",
         "Hub is recorded at low confidence. The source gave حوب and glossed the name 'A center or source'; حُبّ (Ḥubb) 'love' is a documented Arabic word, but its use as a given name and the source gloss could not be confirmed. No confident meaning is asserted."),
 "huba": ("حبة", "حبہ", "حبه", "हुबा", "حبه", "huba", "Arabic", "Female",
          "Arabic حُبَة (Ḥuba)", False, "low",
          "Huba is recorded at low confidence. The source gave حبة and glossed the name 'Bright, Shining'; حُبَة (Ḥuba) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "hubba": ("حبة", "حبہ", "حبه", "हुब्बा", "حبه", "hubba", "Arabic", "Female",
           "Arabic root ح ب ب (ḥ-b-b); حُبَّة (Ḥubba)", False, "low",
           "Hubba is recorded at low confidence. The source gave حبة and glossed the name 'Beloved, Affectionate'; حُبَّة (Ḥubba) is related to the root ح ب ب (ḥ-b-b) 'to love', but the source gloss could not be confirmed. No confident meaning is asserted."),
 "hud": ("هود", "ہود", "هود", "हूद", "هود", "hud_name", "Arabic", "Male",
         "Qur'anic proper name; هُود (Hūd)", True, "high",
         "Hud is Arabic هُود (Hūd), a prophet mentioned in the Qur'an and the name of a Qur'anic sura. CRITICAL SOURCE ERROR: the source gave ھود, using Urdu letters in the Arabic column; the correct Arabic form is هُود. The source gloss 'Guide or Prophet' is broadly consistent. Same name as hood and houd."),
 "huda": ("هدی", "ہدی", "هدی", "हुदा", "هدی", "guidance_f", "Arabic", "Female",
          "Arabic root ه د ي (h-d-y); هُدَى (Hudā)", False, "high",
          "Huda is Arabic هُدَى (Hudā) 'guidance, direction to the right path', from the root ه د ي (h-d-y). The source record was an 8-key stub with no data. Same name as hoda, hooda and houda."),
 "hudaifa": ("حذيفة", "حذیفہ", "حذیفه", "हुज़ैफ़ा", "حذیفه", "hudhayfa", "Arabic", "Male",
             "Arabic حُذَيْفَة (Ḥudhayfa)", False, "medium",
             "Hudaifa is Arabic حُذَيْفَة (Ḥudhayfa), a well-documented male given name borne by Hudhayfa ibn al-Yaman, a companion of the Prophet Muhammad. CRITICAL SOURCE ERROR: the source gave هديفة (a different word) and glossed the name 'Old Arabic name'; the correct form is حُذَيْفَة."),
 "hukam": ("حكم", "حکم", "حکم", "हुकम", "حکم", "judgment", "Arabic", "Male",
           "Arabic root ح ك م (ḥ-k-m); حُكْم (Ḥukm)", False, "medium",
           "Hukam is Arabic حُكْم (Ḥukm) 'judgment, ruling, decision', from the root ح ك م (ḥ-k-m). The source gloss 'Judge, Ruler' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "huma": ("هما", "ہما", "هما", "हुमा", "هما", "homa_bird", "Persian", "Female",
          "Persian هما (Homā)", False, "medium",
          "Huma is Persian هما (Homā), a female given name and the name of a mythical bird of Persian tradition. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Life, existence' is unsupported and has been replaced with the documented identification. Same name as homa."),
 "humaid": ("حميد", "حمید", "حمید", "हुमैद", "حمید", "praiseworthy_dim", "Arabic", "Male",
            "Arabic root ح م د (ḥ-m-d); حُمَيْد (Ḥumayd)", False, "medium",
            "Humaid is Arabic حُمَيْد (Ḥumayd) 'praiseworthy', the diminutive of حَامِد (Ḥāmid), from the root ح م د (ḥ-m-d). The source gloss 'Praiser of God' is broadly consistent."),
 "humair": ("حمير", "حمیر", "حمیر", "हुमैर", "حمیر", "little_donkey", "Arabic", "Male",
            "Arabic root ح م ر (ḥ-m-r); حُمَيْر (Ḥumayr)", False, "low",
            "Humair is recorded at low confidence. The source gave حُمَيْر and glossed the name 'Lion-like'; حُمَيْر (Ḥumayr) is the diminutive of حِمَار (ḥimār, 'donkey'), which is not a positive naming sense, and the source gloss is unsupported. No confident meaning is asserted."),
 "humaira": ("حميراء", "حمیرا", "حمیرا", "हुमैरा", "حمیرا", "humayra", "Arabic", "Female",
             "Arabic root ح م ر (ḥ-m-r); حُمَيْرَاء (Ḥumayrāʾ)", False, "medium",
             "Humaira is Arabic حُمَيْرَاء (Ḥumayrāʾ) 'little reddish-brown one', a byname of Aisha, from the root ح م ر (ḥ-m-r). CRITICAL SOURCE ERROR: the source gave حمیرا, using Urdu letters in the Arabic column; the correct Arabic form is حُمَيْرَاء. The source gloss 'Glowing' is unsupported and has been replaced with the lexical sense. Same name as humairaa, humairah, humayra, humera and humeyra."),
 "humairaa": ("حميراء", "حمیراء", "حمیراء", "हुमैरा", "حمیراء", "humayra", "Arabic", "Female",
              "Arabic root ح م ر (ḥ-m-r); حُمَيْرَاء (Ḥumayrāʾ)", False, "medium",
              "Humairaa is Arabic حُمَيْرَاء (Ḥumayrāʾ) 'little reddish-brown one', a byname of Aisha, from the root ح م ر (ḥ-m-r). The source gloss 'Fair-skinned' is broadly consistent. Same name as humaira, humairah, humayra, humera and humeyra."),
 "humairah": ("حميراء", "حمیراء", "حمیراء", "हुमैरा", "حمیراء", "humayra", "Arabic", "Female",
              "Arabic root ح م ر (ḥ-m-r); حُمَيْرَاء (Ḥumayrāʾ)", False, "medium",
              "Humairah is Arabic حُمَيْرَاء (Ḥumayrāʾ) 'little reddish-brown one', a byname of Aisha, from the root ح م ر (ḥ-m-r). The source gloss 'Reddish-brown complexion' is broadly consistent. Same name as humaira, humairaa, humayra, humera and humeyra."),
 "humam": ("همام", "ہمام", "همام", "हुमाम", "همام", "brave_generous", "Arabic", "Male",
           "Arabic root ه م م (h-m-m); هُمَام (Humām)", False, "medium",
           "Humam is Arabic هُمَام (Humām) 'brave, generous, noble', from the root ه م م (h-m-m). The source gloss 'Companion' is unsupported and has been replaced with the lexical sense."),
 "humaun": ("همایون", "ہمایوں", "همایون", "हुमायूँ", "همایون", "humaun", "Persian", "Male",
            "Persian همایون (Humāyūn)", False, "medium",
            "Humaun is Persian همایون (Humāyūn) 'auspicious, fortunate', a male given name borne by the Mughal emperor Humayun. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Handsome, Generous' is unsupported and has been replaced with the Persian lexical sense. Same name as humayn and humayun."),
 "humayn": ("همایون", "ہمایوں", "همایون", "हुमायूँ", "همایون", "humayn", "Persian", "Male",
            "Persian همایون (Humāyūn)", False, "low",
            "Humayn is recorded at low confidence. The source gave همین and glossed the name 'A beautiful and kind person'; the intended form is likely همایون (Humāyūn), but the source's Arabic column and gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted. Same name as humaun and humayun."),
 "humayra": ("حميراء", "حمیراء", "حمیراء", "हुमैरा", "حمیراء", "humayra", "Arabic", "Female",
             "Arabic root ح م ر (ḥ-m-r); حُمَيْرَاء (Ḥumayrāʾ)", False, "high",
             "Humayra is Arabic حُمَيْرَاء (Ḥumayrāʾ) 'little reddish-brown one', a byname of Aisha, from the root ح م ر (ḥ-m-r). The source gloss 'Golden' is unsupported and has been replaced with the lexical sense. Same name as humaira, humairaa, humairah, humera and humeyra."),
 "humayun": ("همایون", "ہمایوں", "همایون", "हुमायूँ", "همایون", "humayun", "Persian", "Male",
             "Persian همایون (Humāyūn)", False, "high",
             "Humayun is Persian همایون (Humāyūn) 'auspicious, fortunate', a male given name borne by the Mughal emperor Humayun. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Sovereign, Ruler' is unsupported and has been replaced with the Persian lexical sense. Same name as humaun and humayn."),
 "humera": ("حميراء", "حمیراء", "حمیراء", "हुमैरा", "حمیراء", "humayra", "Arabic", "Female",
            "Arabic root ح م ر (ḥ-m-r); حُمَيْرَاء (Ḥumayrāʾ)", False, "medium",
            "Humera is Arabic حُمَيْرَاء (Ḥumayrāʾ) 'little reddish-brown one', a byname of Aisha, from the root ح م ر (ḥ-m-r). CRITICAL SOURCE ERROR: the source gave حومرة (a different word) and glossed the name 'Light, Radiant Moon'; the correct form is حُمَيْرَاء. Same name as humaira, humairaa, humairah, humayra and humeyra."),
 "humeyra": ("حميراء", "حمیراء", "حمیراء", "हुमैरा", "حمیراء", "humayra", "Arabic", "Female",
             "Arabic root ح م ر (ḥ-m-r); حُمَيْرَاء (Ḥumayrāʾ)", False, "medium",
             "Humeyra is a Turkish transliteration of Arabic حُمَيْرَاء (Ḥumayrāʾ) 'little reddish-brown one', a byname of Aisha, from the root ح م ر (ḥ-m-r). The source gloss 'Moonlight' is unsupported and has been replaced with the lexical sense. Same name as humaira, humairaa, humairah, humayra and humera."),
 "humza": ("حمزة", "حمزہ", "حمزه", "हमज़ा", "حمزه", "hamza", "Arabic", "Male",
           "Arabic حَمْزَة (Ḥamza)", False, "high",
           "Humza is a variant transliteration of Arabic حَمْزَة (Ḥamza), a well-documented male given name borne by Hamza ibn Abd al-Muttalib, uncle of the Prophet Muhammad. The source gloss 'Steadfast and Resolute' is unsupported; the name is a proper name. Same name as hamza."),
 "hurmuz": ("هرمز", "ہرمز", "هرمز", "होर्मुज़", "هرمز", "hormuz", "Persian", "Male",
            "Persian هرمز (Hormoz)", False, "low",
            "Hurmuz is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Shining Light'; هرمز (Hormoz) is a Persian name and place name, but the source gloss could not be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "husaam": ("حسام", "حسام", "حسام", "हुसाम", "حسام", "sword", "Arabic", "Male",
            "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "medium",
            "Husaam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'Awe-inspiring, fearsome' is unsupported and has been replaced with the lexical sense. Same name as hesam, hisam, hosaam, houssam, husam and hussam."),
 "husain": ("حسين", "حسین", "حسین", "हुसैन", "حسین", "husayn", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); حُسَيْن (Ḥusayn)", False, "high",
            "Husain is Arabic حُسَيْن (Ḥusayn), the diminutive of حَسَن (Ḥasan), from the root ح س ن (ḥ-s-n); it is a well-documented male given name borne by Husayn ibn Ali, grandson of the Prophet Muhammad. The source gloss 'Graceful, Generous' is unsupported and has been replaced with the lexical sense. Same name as husayn, husein, hussain and hussein."),
 "husam": ("حسام", "حسام", "حسام", "हुसाम", "حسام", "sword", "Arabic", "Male",
           "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "high",
           "Husam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'Sword of Allah' is unsupported and has been replaced with the lexical sense. The source labelled the name unisex; documented usage is predominantly male. Same name as hesam, hisam, hosaam, houssam, husaam and hussam."),
 "husayn": ("حسين", "حسین", "حسین", "हुसैन", "حسین", "husayn", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); حُسَيْن (Ḥusayn)", False, "high",
            "Husayn is Arabic حُسَيْن (Ḥusayn), the diminutive of حَسَن (Ḥasan), from the root ح س ن (ḥ-s-n); it is a well-documented male given name borne by Husayn ibn Ali. The source gloss 'Little Beauty' is broadly consistent. Same name as husain, husein, hussain and hussein."),
 "husein": ("حسين", "حسین", "حسین", "हुसैन", "حسین", "husayn", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); حُسَيْن (Ḥusayn)", False, "high",
            "Husein is a variant transliteration of Arabic حُسَيْن (Ḥusayn), the diminutive of حَسَن (Ḥasan). The source gloss 'Graceful, Generous' is unsupported and has been replaced with the lexical sense. Same name as husain, husayn, hussain and hussein."),
 "husna": ("حسنى", "حسنی", "حسنی", "हुस्ना", "حسنی", "beauty_goodness", "Arabic", "Female",
           "Arabic root ح س ن (ḥ-s-n); حُسْنَى (Ḥusnā)", False, "high",
           "Husna is Arabic حُسْنَى (Ḥusnā) 'most beautiful, best', the feminine elative of حَسَن (ḥasan), from the root ح س ن (ḥ-s-n). The source record was an 8-key stub with no data. Same name as hosna."),
 "husnain": ("حسنين", "حسنین", "حسنین", "हुस्नैन", "حسنین", "husnain", "Arabic", "Male",
             "Dual form of حَسَن (Ḥasan); حُسْنَيْن (Ḥusnayn)", False, "medium",
             "Husnain is Arabic حُسْنَيْن (Ḥusnayn), the dual of حَسَن (Ḥasan), 'the two Hasans', referring to Hasan and Husayn. CRITICAL SOURCE ERROR: the source gave حسنین, using Urdu letters in the Arabic column; the correct Arabic form is حُسْنَيْن. The source gloss 'Beauty in abundance' is broadly consistent. Same name as hussnain."),
 "husni": ("حسني", "حسنی", "حسنی", "हुस्नी", "حسني", "husni", "Arabic", "Male",
           "Nisba of حُسَيْن; حُسْنِيّ (Ḥusniyy)", False, "medium",
           "Husni is Arabic حُسْنِيّ (Ḥusniyy), the nisba of حُسَيْن (Ḥusayn), meaning 'of Husayn; belonging to Husayn'. The source gloss 'Goodness, Beauty' is unsupported and has been replaced with the lexical sense. Same name as hosni and hussni."),
 "husnu": ("حسن", "حسن", "حسن", "हुस्नु", "حسن", "husnu", "Arabic", "Male",
           "Arabic root ح س ن (ḥ-s-n); حُسْن (Ḥusn)", False, "low",
           "Husnu is recorded at low confidence. The source gave حسنو and glossed the name 'Beauty, Goodness'; حُسْن (Ḥusn) 'beauty, goodness' is a documented Arabic word, but the form حسنو and its use as a given name could not be confirmed. No confident meaning is asserted."),
 "husnul": ("حسن الـ", "حسن الـ", "حسن الـ", "हुस्नुल", "حسن الـ", "husnul", "Arabic", "Male",
            "Compound element حسن الـ (Ḥusn al-)", False, "low",
            "Husnul is recorded at low confidence. The source gave حسنل and glossed the name 'Beauty, Grace'; the form is a compound element (حسن الـ, 'the beauty of') used in names such as حسن الاخلاق, but the source's form and gloss could not be confirmed. No confident meaning is asserted."),
 "hussain": ("حسين", "حسین", "حسین", "हुसैन", "حسین", "husayn", "Arabic", "Male",
             "Arabic root ح س ن (ḥ-s-n); حُسَيْن (Ḥusayn)", False, "high",
             "Hussain is Arabic حُسَيْن (Ḥusayn), the diminutive of حَسَن (Ḥasan), from the root ح س ن (ḥ-s-n); it is a well-documented male given name borne by Husayn ibn Ali. The source record was an 8-key stub with no data. Same name as husain, husayn, husein and hussein."),
 "hussam": ("حسام", "حسام", "حسام", "हुस्साम", "حسام", "sword", "Arabic", "Male",
            "Arabic root ح س م (ḥ-s-m); حُسَام (Ḥusām)", False, "medium",
            "Hussam is Arabic حُسَام (Ḥusām) 'sharp sword; decisive', from the root ح س م (ḥ-s-m). The source gloss 'One adorned with stones, gems' is unsupported and has been replaced with the lexical sense. Same name as hesam, hisam, hosaam, houssam, husaam and husam."),
 "hussein": ("حسين", "حسین", "حسین", "हुसैन", "حسین", "husayn", "Arabic", "Male",
             "Arabic root ح س ن (ḥ-s-n); حُسَيْن (Ḥusayn)", False, "high",
             "Hussein is a variant transliteration of Arabic حُسَيْن (Ḥusayn), the diminutive of حَسَن (Ḥasan). CRITICAL SOURCE ERROR: the source gave حسین, using Urdu letters in the Arabic column; the correct Arabic form is حُسَيْن. The source gloss 'Magnificent, Good, Generous' is unsupported and has been replaced with the lexical sense. Same name as husain, husayn, husein and hussain."),
 "hussnain": ("حسنين", "حسنین", "حسنین", "हुस्नैन", "حسنین", "husnain", "Arabic", "Male",
              "Dual form of حَسَن (Ḥasan); حُسْنَيْن (Ḥusnayn)", False, "medium",
              "Hussnain is Arabic حُسْنَيْن (Ḥusnayn), the dual of حَسَن (Ḥasan), 'the two Hasans'. CRITICAL SOURCE ERROR: the source gave حسنین, using Urdu letters in the Arabic column; the correct Arabic form is حُسْنَيْن. The source gloss 'Good, Handsome' is broadly consistent. Same name as husnain."),
 "hussni": ("حسني", "حسنی", "حسنی", "हुस्नी", "حسني", "husni", "Arabic", "Male",
            "Nisba of حُسَيْن; حُسْنِيّ (Ḥusniyy)", False, "medium",
            "Hussni is Arabic حُسْنِيّ (Ḥusniyy), the nisba of حُسَيْن (Ḥusayn), meaning 'of Husayn; belonging to Husayn'. The source gloss 'Good, Excellent, Superior' is unsupported and has been replaced with the lexical sense. Same name as hosni and husni."),
 "hutaf": ("هتاف", "ہتاف", "هتاف", "हुताफ़", "هتاف", "cheering", "Arabic", "Female",
           "Arabic root ه ت ف (h-t-f); هُتَاف (Hutāf)", False, "low",
           "Hutaf is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Sacred bond, connection'; هُتَاف (Hutāf) 'cheering, acclamation' is a documented Arabic word, but its use as a given name and the source gloss could not be confirmed. No confident meaning is asserted."),
}
