# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 54 (rohi..sabahat).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": roshan -> Latin "roshan";
   rouza -> Latin "Rouza"; rowan -> empty; rozha -> Latin "Rozha";
   rozhin -> Latin "Rozhin"; ruksana -> Latin "Ruksana";
   runak -> Latin "Runak"; ruqaya -> empty; ruqayah -> روقayah (Latin mixed);
   ruqayyah -> empty; rusydi -> Latin "Rusydi"; sa -> Latin "Sa";
   saad -> empty; saba -> "عربي_Saba" (placeholder prefix);
   sabahat -> "سبahat" (Latin mixed); romana -> عائشة; ruhama -> رحمة;
   rukayah -> روكايه (Russian kaf); rustum -> ر سطم; ruba -> ربى;
   ruban -> ربي ن; rubee -> روبی; rubi -> روبي; rubina -> روبينا;
   rubiya -> ربيعة; rufaida -> رفيدة; ruha -> روح; ruhan -> روحان;
   ruhana -> روحانة; ruhani -> روحاني; ruhena -> روحينة; ruhi -> روحي;
   ruhiya -> روحية; ruhul -> روحل; rukaiya -> رُقَيَّة; rukan -> رُكُون;
   rukayat -> ركيات; rukayya -> رُكَيَّة; rukhsaana -> رخسنة;
   rukhsar -> روخسر; ruma -> روما; rumaisa -> رميساء; ruman -> رومان;
   rumana -> رومانا; rumi -> رومي; rumman -> رمان; ruqaiya -> رقيه;
   ruqayya -> رقية; rushan -> روشان; rushda -> رشدة; rushdi -> رشدي;
   rustam -> رستم; rustom -> رستم; rusul -> رسول; ruth -> روث;
   ruwaida -> روئيدة; ruwayda -> رويدة; ruwaydah -> رويضة; ruya -> رويا;
   rya -> رياء; sa-d -> صَعد; sa-idah -> سعيدة; saabir -> صابر;
   saabit -> سعبت; saadah -> سعدة; saadan -> سعدان; saadat -> سعادَت;
   saadi -> سعدي; saadia -> سعدية; saadiq -> صادق; saadiya -> سعدية;
   saaed -> سعيد; saaf -> صاف; saaid -> سعيد; saaida -> سعيدة;
   saalim -> سالم; saami -> سَامِي; saara -> صَارَة; saarah -> سارة;
   saat -> ساعة; sabaa -> سبأ; sabah -> صباح.
 * EMPTY STUBS (8-key records, no data): rowan, ruqaya, ruqayyah, saad.
 * MISLABELLED ORIGIN: roshan (Persian), roshani (Urdu/Persian),
   roshna (Persian), rozhin (Persian), rozina (Persian), ruban (Malay/Tamil),
   rubi (Bengali/Hindi), rubina (Urdu/Persian), rukhsana (Persian/Urdu),
   ruksana (Urdu), rumi (Persian/Turkish), rustam/rustom/rustum (Persian),
   ruth (Hebrew), ruya (Turkish), roya (Persian), roni (Hebrew),
   rohi (Urdu), rohina (Urdu), rohul (Urdu), ruhul (Urdu).
 * DEGARBLED GLOSSES: rohi "Traveler, Pathfinder", rohina "Ascended to heaven",
   rohul "Spirit of God", romaisa "Moon-born, Little Moon",
   romana "The Roman One", roni "Joy, Delight", rooh "Soul",
   roohi "Spirit, Soul", roqaya "Peaceful, calming, serene",
   roshaan "Radiant, Shining", roshan "Sun, Bright, Radiant",
   roshani "Guide, Light", roshna "Radiant, shining", rouza "Rose",
   rowa "Flow", rowel "Little One", roya "Princess, Lady", rozha "Rose",
   rozhan "Jasmine flower", rozhin "Rose Garden", rozina "Beautiful Rose",
   ruaa "Call, Cry", ruba "Butterfly", rubab "Bringer of peace",
   ruban "Silk, thread, jewel", rubee "Ruby", rubi "Ruby",
   rubina "Luminous, Glowing", rubiya "Ruby", rufaida "Mother of the Poor",
   ruha "Spirit, Soul", ruhama "Highly Exalted", ruhan "Compassionate",
   ruhana "Spirit", ruhani "Soul, Spirit", ruhena "Moon, Rain",
   ruhi "Spirit, Soul, Wisdom", ruhiya "Spirit, Soul, Wisdom", ruhul "Spirit",
   rukaiya "Exalted, Lofty", rukan "Crown, ring", rukayah "Elevation, Exaltation",
   rukayat "Rest", rukayya "Merciful", rukhsana "Face Brightened",
   rukhsar "Light in the darkness", ruksana "Elegant, Beautiful, Delicate",
   ruma "Companion", rumaisa "Small and Delicate", ruman "rain, red",
   rumana "Grace", rumi "Ode to the Prophet", rumman "Pomegranate",
   runak "Jasmine flower", ruqaiya "Quencher of Thirst",
   ruqayah "Seeker of healing", ruqayya "Seeking refuge",
   rushan "Moon, radiant, bright", rushda "Guide, Leader",
   rushdi "Rightly Guided", rustam "Strong and mighty",
   rustom "Brave warrior", rustum "Strong Warrior, Hero", rusul "Messenger",
   rusydi "Little Wise One", ruth "Companion, Friend, Vision of Beauty",
   ruwaida "Gazelle", ruwayda "Contentment, Satisfaction",
   ruwaydah "Little Gardener", ruya "Dream, Vision", rya "Content, Satisfied",
   sa "Live, Existence, Being, Said", sa-d "Happiness, Luck", sa-idah "Happy",
   saabir "Patient, Enduring", saabit "Firm, Trustworthy",
   saadah "Happiness, contentment", saadan "Happy, Joyous",
   saadat "Happiness, Bliss", saadi "Fortunate, Happy", saadia "Lucky, fortunate",
   saadiq "Truthful, Sincere", saadiya "Happy", saaed "Happy",
   saaf "Clean, Pure", saaid "Helper, Support", saaida "Delighted, Pleased",
   saalim "Successful, Lucky", saami "Calm, Peaceful", saara "Gentle Breeze",
   saarah "Leader or princess", saat "Time", saba "Noble and blessed",
   sabaa "Sixth", sabah "Morning", sabahat "Morning, Dawn".
 * GENDER ERRORS: rohi, rooh, rubab, ruban, rubee, rubi, ruhama, ruhul, rukan,
   rukhsar, ruma, rumman, runak, rushan, rusul, sa, sa-idah, saadat, saadi,
   saaf, saami, saat were labelled unisex where documented usage is male or
   female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated53 import GLOSSES as _G53

GLOSSES = dict(_G53)
GLOSSES.update({
    "rohi": {"en": "Rohi; a male given name (Urdu)", "ur": "روحی (مردانہ نام)", "fa": "روحی (نام مردانه)", "hi": "रोही (पुरुष नाम)", "ps": "روحي (نر نوم)", "ar": "رُوحِي (اسْم عَلَم مُذَكَّر)"},
    "rohina": {"en": "Rohina; a female given name (Urdu)", "ur": "روہینا (زنانہ نام)", "fa": "روهینا (نام زنانه)", "hi": "रोहीना (स्त्री नाम)", "ps": "روهینا (ښځينه نوم)", "ar": "رُوهِينَا (اسْم عَلَم مُؤَنَّث)"},
    "rohul": {"en": "Rohul; spirit (construct form)", "ur": "روح ال، روح", "fa": "روح ال، روح", "hi": "रोहुल, आत्मा", "ps": "روح ال، روح", "ar": "رُوحُ الـ (الْإِضَافَة)"},
    "romaisa": {"en": "Romaisa; a female given name", "ur": "رمیصہ (زنانہ نام)", "fa": "رمیصه (نام زنانه)", "hi": "रुमैसा (स्त्री नाम)", "ps": "رمیصه (ښځينه نوم)", "ar": "رُمَيْصَة (اسْم عَلَم مُؤَنَّث)"},
    "romana": {"en": "Romana; a female given name", "ur": "رومانہ (زنانہ نام)", "fa": "رومانا (نام زنانه)", "hi": "रोमाना (स्त्री नाम)", "ps": "رومانا (ښځينه نوم)", "ar": "رُومَانَا (اسْم عَلَم مُؤَنَّث)"},
    "roni": {"en": "Roni; a male given name (Hebrew)", "ur": "رونی (مردانہ نام)", "fa": "رونی (نام مردانه)", "hi": "रोनी (पुरुष नाम)", "ps": "روني (نر نوم)", "ar": "رُونِي (اسْم عَلَم عِبْرِيّ)"},
    "rooh": {"en": "Rooh; soul, spirit", "ur": "روح، جان", "fa": "روح، جان", "hi": "रूह, आत्मा", "ps": "روح، روح", "ar": "الرُّوح، النَّفْس"},
    "roohi": {"en": "Roohi; spiritual, of the soul (feminine)", "ur": "روحی، روح سے منسوب", "fa": "روحی، منسوب به روح", "hi": "रूही, आत्मा से संबंधित", "ps": "روحي، د روح اړوند", "ar": "رُوحِيَّة، مَنْسُوب إِلَى الرُّوح"},
    "roqaya": {"en": "Roqaya; a female given name", "ur": "رقایہ (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "roshaan": {"en": "Roshaan; radiant, bright", "ur": "روشن، منور", "fa": "روشن، درخشان", "hi": "रौशन, प्रकाशित", "ps": "روشن، روښانه", "ar": "رَوْشَن (الْمُضِيء)"},
    "roshan": {"en": "Roshan; bright, radiant (Persian)", "ur": "روشن، منور", "fa": "روشن، درخشان", "hi": "रौशन, प्रकाशित", "ps": "روشن، روښانه", "ar": "رَوْشَن (الْمُضِيء)"},
    "roshani": {"en": "Roshani; light, brightness (Urdu)", "ur": "روشنی، نور", "fa": "روشنی، نور", "hi": "रौशनी, प्रकाश", "ps": "روښانه، رڼا", "ar": "رَوْشَنِي (النُّور)"},
    "roshna": {"en": "Roshna; bright, radiant (Persian)", "ur": "روشنا، منور", "fa": "روشنا، درخشان", "hi": "रौशना, प्रकाशित", "ps": "روښانه، روښانه", "ar": "رَوْشَنَا (الْمُضِيء)"},
    "rouza": {"en": "Rouza; garden, meadow", "ur": "روضہ، باغ", "fa": "روضه، باغ", "hi": "रौज़ा, बाग़", "ps": "روضه، باغ", "ar": "الرَّوْضَة، الْحَدِيقَة"},
    "rowa": {"en": "Rowa; a female given name", "ur": "روا (زنانہ نام)", "fa": "روا (نام زنانه)", "hi": "रवा (स्त्री नाम)", "ps": "روا (ښځينه نوم)", "ar": "رَوَا (اسْم عَلَم مُؤَنَّث)"},
    "rowan": {"en": "Rowan; a male given name", "ur": "روان (مردانہ نام)", "fa": "روان (نام مردانه)", "hi": "रोवन (पुरुष नाम)", "ps": "روان (نر نوم)", "ar": "رُوَان (اسْم عَلَم مُذَكَّر)"},
    "rowel": {"en": "Rowel; a male given name", "ur": "رویل (مردانہ نام)", "fa": "رویل (نام مردانه)", "hi": "रोवेल (पुरुष नाम)", "ps": "رویل (نر نوم)", "ar": "رُوَيْل (اسْم عَلَم مُذَكَّر)"},
    "roya": {"en": "Roya; dream, vision (Persian)", "ur": "رویا، خواب", "fa": "رویا، خواب", "hi": "रोया, सपना", "ps": "رویا، خوب", "ar": "رُويَا (الرُّؤْيَا)"},
    "rozha": {"en": "Rozha; a female given name (Kurdish)", "ur": "روژہ (زنانہ نام)", "fa": "روژه (نام زنانه)", "hi": "रोज़ा (स्त्री नाम)", "ps": "روژه (ښځينه نوم)", "ar": "رُوژَا (اسْم عَلَم كُرْدِيّ)"},
    "rozhan": {"en": "Rozhan; a female given name (Kurdish)", "ur": "روژان (زنانہ نام)", "fa": "روژان (نام زنانه)", "hi": "रोज़हान (स्त्री नाम)", "ps": "روژان (ښځينه نوم)", "ar": "رُوژَان (اسْم عَلَم كُرْدِيّ)"},
    "rozhin": {"en": "Rozhin; a female given name (Kurdish)", "ur": "روژین (زنانہ نام)", "fa": "روژین (نام زنانه)", "hi": "रोज़हीन (स्त्री नाम)", "ps": "روژین (ښځينه نوم)", "ar": "رُوژِين (اسْم عَلَم كُرْدِيّ)"},
    "rozina": {"en": "Rozina; a female given name (Persian)", "ur": "روزینہ (زنانہ نام)", "fa": "روزینا (نام زنانه)", "hi": "रोज़ीना (स्त्री नाम)", "ps": "روزینا (ښځينه نوم)", "ar": "رُوزِينَا (اسْم عَلَم فَارِسِيّ)"},
    "ruaa": {"en": "Ruaa; visions (plural)", "ur": "رؤاء، خواب", "fa": "رؤاء، رؤیاها", "hi": "रुआ, दर्शन", "ps": "رؤاء، خوبونه", "ar": "الرُّؤَاء، الرُّؤْيَا"},
    "ruba": {"en": "Ruba; a female given name", "ur": "ربی (زنانہ نام)", "fa": "ربی (نام زنانه)", "hi": "रुबा (स्त्री नाम)", "ps": "ربی (ښځينه نوم)", "ar": "رُبَى (اسْم عَلَم مُؤَنَّث)"},
    "rubab": {"en": "Rubab; a female given name", "ur": "رباب (زنانہ نام)", "fa": "رباب (نام زنانه)", "hi": "रुबाब (स्त्री नाम)", "ps": "رباب (ښځينه نوم)", "ar": "رُبَاب (اسْم عَلَم مُؤَنَّث)"},
    "ruban": {"en": "Ruban; a male given name (Tamil/Malay)", "ur": "روبن (مردانہ نام)", "fa": "روبن (نام مردانه)", "hi": "रुबन (पुरुष नाम)", "ps": "روبن (نر نوم)", "ar": "رُوبَن (اسْم عَلَم تَامِيلِيّ)"},
    "rubee": {"en": "Rubee; ruby (gemstone)", "ur": "روبی، یاقوت", "fa": "روبی، یاقوت", "hi": "रूबी, याकूत", "ps": "روبي، یاقوت", "ar": "رُوبِي (الْيَاقُوت)"},
    "rubi": {"en": "Rubi; ruby (gemstone)", "ur": "روبی، یاقوت", "fa": "روبی، یاقوت", "hi": "रूबी, याकूत", "ps": "روبي، یاقوت", "ar": "رُوبِي (الْيَاقُوت)"},
    "rubina": {"en": "Rubina; a female given name (Urdu)", "ur": "روبینہ (زنانہ نام)", "fa": "روبینا (نام زنانه)", "hi": "रुबीना (स्त्री नाम)", "ps": "روبینا (ښځينه نوم)", "ar": "رُوبِينَا (اسْم عَلَم مُؤَنَّث)"},
    "rubiya": {"en": "Rubiya; a female given name", "ur": "ربیعہ (زنانہ نام)", "fa": "ربیه (نام زنانه)", "hi": "रुबिया (स्त्री नाम)", "ps": "ربیه (ښځينه نوم)", "ar": "رُبَيْعَة (اسْم عَلَم مُؤَنَّث)"},
    "rufaida": {"en": "Rufaida; a female given name", "ur": "رفیدہ (زنانہ نام)", "fa": "رفیده (نام زنانه)", "hi": "रुफ़ैदा (स्त्री नाम)", "ps": "رفیده (ښځينه نوم)", "ar": "رُفَيْدَة (اسْم عَلَم مُؤَنَّث)"},
    "ruha": {"en": "Ruha; soul, spirit", "ur": "روح، جان", "fa": "روح، جان", "hi": "रूह, आत्मा", "ps": "روح، روح", "ar": "الرُّوح، النَّفْس"},
    "ruhama": {"en": "Ruhama; mercy, compassion", "ur": "رحمہ، رحمت", "fa": "رحمه، رحمت", "hi": "रहमा, दया", "ps": "رحمه، رحمت", "ar": "الرَّحْمَة"},
    "ruhan": {"en": "Ruhan; spiritual, of the soul", "ur": "روحان، روحانی", "fa": "روحان، روحانی", "hi": "रूहान, आध्यात्मिक", "ps": "روحان، روحاني", "ar": "رُوحَان (الرُّوحَانِي)"},
    "ruhana": {"en": "Ruhana; a female given name", "ur": "روحانہ (زنانہ نام)", "fa": "روحانه (نام زنانه)", "hi": "रूहाना (स्त्री नाम)", "ps": "روحانه (ښځينه نوم)", "ar": "رُوحَانَة (اسْم عَلَم مُؤَنَّث)"},
    "ruhani": {"en": "Ruhani; spiritual (feminine)", "ur": "روحانی، روح سے منسوب", "fa": "روحانی، منسوب به روح", "hi": "रूहानी, आध्यात्मिक", "ps": "روحاني، روحاني", "ar": "رُوحَانِيَّة، مَنْسُوب إِلَى الرُّوح"},
    "ruhena": {"en": "Ruhena; a female given name", "ur": "روحینہ (زنانہ نام)", "fa": "روهینه (نام زنانه)", "hi": "रुहीना (स्त्री नाम)", "ps": "روحینه (ښځينه نوم)", "ar": "رُوحِينَة (اسْم عَلَم مُؤَنَّث)"},
    "ruhi": {"en": "Ruhi; spiritual, of the soul", "ur": "روحی، روح سے منسوب", "fa": "روحی، منسوب به روح", "hi": "रूही, आत्मा से संबंधित", "ps": "روحي، د روح اړوند", "ar": "رُوحِي، مَنْسُوب إِلَى الرُّوح"},
    "ruhiya": {"en": "Ruhiya; spiritual (feminine)", "ur": "روحیہ، روح سے منسوب", "fa": "روحیه، منسوب به روح", "hi": "रूहिया, आध्यात्मिक", "ps": "روحیه، د روح اړوند", "ar": "رُوحِيَّة، مَنْسُوب إِلَى الرُّوح"},
    "ruhul": {"en": "Ruhul; spirit (construct form)", "ur": "روح ال، روح", "fa": "روح ال، روح", "hi": "रूहुल, आत्मा", "ps": "روح ال، روح", "ar": "رُوحُ الـ (الْإِضَافَة)"},
    "rukaiya": {"en": "Rukaiya; a female given name", "ur": "رقیه (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "rukan": {"en": "Rukan; a male given name", "ur": "رکن (مردانہ نام)", "fa": "رکن (نام مردانه)", "hi": "रुकन (पुरुष नाम)", "ps": "رکن (نر نوم)", "ar": "رُكْن (اسْم عَلَم مُذَكَّر)"},
    "rukayah": {"en": "Rukayah; a female given name", "ur": "رقایہ (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "rukayat": {"en": "Rukayat; a female given name", "ur": "رکیت (زنانہ نام)", "fa": "رکیت (نام زنانه)", "hi": "रुकयात (स्त्री नाम)", "ps": "رکیت (ښځينه نوم)", "ar": "رُكَيَّات (اسْم عَلَم مُؤَنَّث)"},
    "rukayya": {"en": "Rukayya; a female given name", "ur": "رقیه (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "rukhsana": {"en": "Rukhsana; a female given name (Persian/Urdu)", "ur": "رخسانہ (زنانہ نام)", "fa": "رخسانه (نام زنانه)", "hi": "रुख़साना (स्त्री नाम)", "ps": "رخسانه (ښځينه نوم)", "ar": "رُخْسَانَة (اسْم عَلَم مُؤَنَّث)"},
    "rukhsar": {"en": "Rukhsar; cheek, face (Persian)", "ur": "رخسار، رخ", "fa": "رخسار، چهره", "hi": "रुख़सार, चेहरा", "ps": "رخسار، مخ", "ar": "رُخْسَار (الْوَجْه)"},
    "ruksana": {"en": "Ruksana; a female given name (Urdu)", "ur": "رخسانہ (زنانہ نام)", "fa": "رخسانه (نام زنانه)", "hi": "रुख़साना (स्त्री नाम)", "ps": "رخسانه (ښځينه نوم)", "ar": "رُخْسَانَة (اسْم عَلَم مُؤَنَّث)"},
    "ruma": {"en": "Ruma; a female given name", "ur": "روما (زنانہ نام)", "fa": "روما (نام زنانه)", "hi": "रूमा (स्त्री नाम)", "ps": "روما (ښځينه نوم)", "ar": "رُومَا (اسْم عَلَم مُؤَنَّث)"},
    "rumaisa": {"en": "Rumaisa; a female given name", "ur": "رمیساء (زنانہ نام)", "fa": "رمیساء (نام زنانه)", "hi": "रुमैसा (स्त्री नाम)", "ps": "رمیساء (ښځينه نوم)", "ar": "رُمَيْسَاء (اسْم عَلَم مُؤَنَّث)"},
    "ruman": {"en": "Ruman; a male given name", "ur": "رومان (مردانہ نام)", "fa": "رومان (نام مردانه)", "hi": "रूमान (पुरुष नाम)", "ps": "رومان (نر نوم)", "ar": "رُومَان (اسْم عَلَم مُذَكَّر)"},
    "rumana": {"en": "Rumana; a female given name", "ur": "رومانہ (زنانہ نام)", "fa": "رومانا (نام زنانه)", "hi": "रूमाना (स्त्री नाम)", "ps": "رومانا (ښځينه نوم)", "ar": "رُومَانَا (اسْم عَلَم مُؤَنَّث)"},
    "rumi": {"en": "Rumi; of Rum, Anatolian (Persian)", "ur": "رومی، روم سے منسوب", "fa": "رومی، منسوب به روم", "hi": "रूमी, रूम से संबंधित", "ps": "رومي، د روم اړوند", "ar": "الرُّومِي، مَنْسُوب إِلَى الرُّوم"},
    "rumman": {"en": "Rumman; pomegranate", "ur": "رمان، انار", "fa": "رمان، انار", "hi": "रुम्मान, अनार", "ps": "رمان، انار", "ar": "الرُّمَّان"},
    "runak": {"en": "Runak; a female given name", "ur": "رونک (زنانہ نام)", "fa": "رونک (نام زنانه)", "hi": "रूनक (स्त्री नाम)", "ps": "رونک (ښځينه نوم)", "ar": "رُونَك (اسْم عَلَم مُؤَنَّث)"},
    "ruqaiya": {"en": "Ruqaiya; a female given name", "ur": "رقیه (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "ruqaya": {"en": "Ruqaya; a female given name", "ur": "رقایہ (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "ruqayah": {"en": "Ruqayah; a female given name", "ur": "رقایہ (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "ruqayya": {"en": "Ruqayya; a female given name", "ur": "رقیه (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "ruqayyah": {"en": "Ruqayyah; a female given name", "ur": "رقیه (زنانہ نام)", "fa": "رقیه (نام زنانه)", "hi": "रुक़ैया (स्त्री नाम)", "ps": "رقیه (ښځينه نوم)", "ar": "رُقَيَّة (اسْم عَلَم مُؤَنَّث)"},
    "rushan": {"en": "Rushan; bright, radiant (Persian)", "ur": "روشن، منور", "fa": "روشن، درخشان", "hi": "रौशन, प्रकाशित", "ps": "روشن، روښانه", "ar": "رَوْشَن (الْمُضِيء)"},
    "rushda": {"en": "Rushda; right guidance (feminine)", "ur": "رشدہ، ہدایت", "fa": "رشده، هدایت", "hi": "रुशदा, मार्गदर्शन", "ps": "رشده، لارښوونه", "ar": "رُشْدَة، الرُّشْد"},
    "rushdi": {"en": "Rushdi; of right guidance (relational)", "ur": "رشدی، ہدایت سے منسوب", "fa": "رشدی، منسوب به رشد", "hi": "रुशदी, मार्गदर्शन से संबंधित", "ps": "رشدي، د رشد اړوند", "ar": "الرُّشْدِي، مَنْسُوب إِلَى الرُّشْد"},
    "rustam": {"en": "Rustam; a male given name (Persian)", "ur": "رستم (مردانہ نام)", "fa": "رستم (نام مردانه)", "hi": "रुस्तम (पुरुष नाम)", "ps": "رستم (نر نوم)", "ar": "رُسْتَم (اسْم عَلَم فَارِسِيّ)"},
    "rustom": {"en": "Rustom; a male given name (Persian)", "ur": "رستم (مردانہ نام)", "fa": "رستم (نام مردانه)", "hi": "रुस्तम (पुरुष नाम)", "ps": "رستم (نر نوم)", "ar": "رُسْتَم (اسْم عَلَم فَارِسِيّ)"},
    "rustum": {"en": "Rustum; a male given name (Persian)", "ur": "رستم (مردانہ نام)", "fa": "رستم (نام مردانه)", "hi": "रुस्तुम (पुरुष नाम)", "ps": "رستم (نر نوم)", "ar": "رُسْتَم (اسْم عَلَم فَارِسِيّ)"},
    "rusul": {"en": "Rusul; messengers (plural)", "ur": "رسل، پیغام رساں", "fa": "رسل، پیام‌آوران", "hi": "रुसुल, संदेशवाहक", "ps": "رسل، پیغام رسولان", "ar": "الرُّسُل، الْمُرْسَلُون"},
    "rusydi": {"en": "Rusydi; of right guidance (relational)", "ur": "رشدی، ہدایت سے منسوب", "fa": "رشدی، منسوب به رشد", "hi": "रुशदी, मार्गदर्शन से संबंधित", "ps": "رشدي، د رشد اړوند", "ar": "الرُّشْدِي، مَنْسُوب إِلَى الرُّشْد"},
    "ruth": {"en": "Ruth; a female given name (Hebrew)", "ur": "روت (زنانہ نام)", "fa": "روت (نام زنانه)", "hi": "रूथ (स्त्री नाम)", "ps": "روت (ښځينه نوم)", "ar": "رُوث (اسْم عَلَم عِبْرِيّ)"},
    "ruwaida": {"en": "Ruwaida; a female given name", "ur": "روئیدہ (زنانہ نام)", "fa": "روئیده (نام زنانه)", "hi": "रुवैदा (स्त्री नाम)", "ps": "روئیده (ښځينه نوم)", "ar": "رُوَيْدَة (اسْم عَلَم مُؤَنَّث)"},
    "ruwayda": {"en": "Ruwayda; a female given name", "ur": "رویدہ (زنانہ نام)", "fa": "رویده (نام زنانه)", "hi": "रुवैदा (स्त्री नाम)", "ps": "رویده (ښځينه نوم)", "ar": "رُوَيْدَة (اسْم عَلَم مُؤَنَّث)"},
    "ruwaydah": {"en": "Ruwaydah; a female given name", "ur": "رویضہ (زنانہ نام)", "fa": "رویضه (نام زنانه)", "hi": "रुवैदा (स्त्री नाम)", "ps": "رویضه (ښځينه نوم)", "ar": "رُوَيْضَة (اسْم عَلَم مُؤَنَّث)"},
    "ruya": {"en": "Ruya; dream, vision (Turkish)", "ur": "رویا، خواب", "fa": "رویا، خواب", "hi": "रूया, सपना", "ps": "رویا، خوب", "ar": "رُؤْيَا (الرُّؤْيَا)"},
    "rya": {"en": "Rya; a female given name", "ur": "ریا (زنانہ نام)", "fa": "ریا (نام زنانه)", "hi": "रिया (स्त्री नाम)", "ps": "ریا (ښځينه نوم)", "ar": "رِيَا (اسْم عَلَم مُؤَنَّث)"},
    "sa": {"en": "Sa; a male given name", "ur": "سا (مردانہ نام)", "fa": "سا (نام مردانه)", "hi": "सा (पुरुष नाम)", "ps": "سا (نر نوم)", "ar": "سَا (اسْم عَلَم مُذَكَّر)"},
    "sa-d": {"en": "Sa'd; good fortune, happiness", "ur": "سعد، خوش نصیبی", "fa": "سعد، خوشبختی", "hi": "साद, सौभाग्य", "ps": "سعد، نیکمرغی", "ar": "سَعْد، السَّعَادَة"},
    "sa-idah": {"en": "Sa'idah; happy, fortunate (feminine)", "ur": "سعیدہ، خوش نصیب", "fa": "سعیده، خوشبخت", "hi": "सईदा, प्रसन्न", "ps": "سعیده، خوشحاله", "ar": "سَعِيدَة، السَّعِيدَة"},
    "saabir": {"en": "Saabir; patient, enduring", "ur": "صابر، صبر کرنے والا", "fa": "صابر، شکیبا", "hi": "साबिर, धैर्यवान", "ps": "صابر، صبر کوونکی", "ar": "الصَّابِر، الصَّبُور"},
    "saabit": {"en": "Saabit; firm, steadfast", "ur": "ثابت، مضبوط", "fa": "ثابت، استوار", "hi": "साबित, दृढ़", "ps": "ثابت، ټینګ", "ar": "الثَّابِت، الرَّاسِخ"},
    "saad": {"en": "Saad; good fortune, happiness", "ur": "سعد، خوش نصیبی", "fa": "سعد، خوشبختی", "hi": "साद, सौभाग्य", "ps": "سعد، نیکمرغی", "ar": "سَعْد، السَّعَادَة"},
    "saadah": {"en": "Saadah; happiness, contentment", "ur": "سعادہ، خوشی", "fa": "سعاده، خوشبختی", "hi": "सआदा, प्रसन्नता", "ps": "سعاده، خوښي", "ar": "السَّعَادَة"},
    "saadan": {"en": "Saadan; happy, joyous", "ur": "سعدان، خوش", "fa": "سعدان، شاد", "hi": "सादान, प्रसन्न", "ps": "سعدان، خوشحاله", "ar": "سَعْدَان، السَّعِيد"},
    "saadat": {"en": "Saadat; happiness, bliss", "ur": "سعادت، خوش نصیبی", "fa": "سعادت، خوشبختی", "hi": "सआदत, सौभाग्य", "ps": "سعادت، نیکمرغی", "ar": "السَّعَادَة"},
    "saadi": {"en": "Saadi; fortunate, happy", "ur": "سعدی، خوش نصیب", "fa": "سعدی، خوشبخت", "hi": "सादी, भाग्यशाली", "ps": "سعدي، نیکمرغه", "ar": "السَّعْدِي، السَّعِيد"},
    "saadia": {"en": "Saadia; happy, fortunate (feminine)", "ur": "سعدیہ، خوش نصیب", "fa": "سعدیه، خوشبخت", "hi": "सादिया, प्रसन्न", "ps": "سعدیه، خوشحاله", "ar": "سَعْدِيَّة، السَّعِيدَة"},
    "saadiq": {"en": "Saadiq; truthful, sincere", "ur": "صادق، سچا", "fa": "صادق، راستگو", "hi": "सादिक़, सच्चा", "ps": "صادق، رښتونی", "ar": "الصَّادِق، الصِّدْق"},
    "saadiya": {"en": "Saadiya; happy, fortunate (feminine)", "ur": "سعدیہ، خوش نصیب", "fa": "سعدیه، خوشبخت", "hi": "सादिया, प्रसन्न", "ps": "سعدیه، خوشحاله", "ar": "سَعْدِيَّة، السَّعِيدَة"},
    "saaed": {"en": "Saaed; happy, fortunate", "ur": "سعید، خوش نصیب", "fa": "سعید، خوشبخت", "hi": "सईद, प्रसन्न", "ps": "سعید، خوشحاله", "ar": "السَّعِيد، السَّعَادَة"},
    "saaf": {"en": "Saaf; pure, clear", "ur": "صاف، خالص", "fa": "صاف، پاک", "hi": "साफ़, शुद्ध", "ps": "صاف، پاک", "ar": "الصَّافِي، النَّقِيّ"},
    "saaid": {"en": "Saaid; happy, fortunate", "ur": "سعید، خوش نصیب", "fa": "سعید، خوشبخت", "hi": "सईद, प्रसन्न", "ps": "سعید، خوشحاله", "ar": "السَّعِيد، السَّعَادَة"},
    "saaida": {"en": "Saaida; happy, fortunate (feminine)", "ur": "سعیدہ، خوش نصیب", "fa": "سعیده، خوشبخت", "hi": "सईदा, प्रसन्न", "ps": "سعیده، خوشحاله", "ar": "سَعِيدَة، السَّعِيدَة"},
    "saalim": {"en": "Saalim; safe, sound", "ur": "سالم، محفوظ", "fa": "سالم، تندرست", "hi": "सालिम, सुरक्षित", "ps": "سالم، روغ", "ar": "السَّالِم، السَّلِيم"},
    "saami": {"en": "Saami; elevated, sublime", "ur": "سامی، بلند", "fa": "سامی، بلند", "hi": "सामी, उच्च", "ps": "سامي، لوړ", "ar": "السَّامِي، الْعَلِيّ"},
    "saara": {"en": "Saara; a female given name", "ur": "سارہ (زنانہ نام)", "fa": "سارا (نام زنانه)", "hi": "सारा (स्त्री नाम)", "ps": "سارا (ښځينه نوم)", "ar": "سَارَة (اسْم عَلَم مُؤَنَّث)"},
    "saarah": {"en": "Saarah; a female given name", "ur": "سارہ (زنانہ نام)", "fa": "سارا (نام زنانه)", "hi": "सारा (स्त्री नाम)", "ps": "سارا (ښځينه نوم)", "ar": "سَارَة (اسْم عَلَم مُؤَنَّث)"},
    "saat": {"en": "Saat; hour, time", "ur": "ساعت، وقت", "fa": "ساعت، زمان", "hi": "साअत, समय", "ps": "ساعت، وخت", "ar": "السَّاعَة، الْوَقْت"},
    "saba": {"en": "Saba; a female given name", "ur": "سبا (زنانہ نام)", "fa": "سبا (نام زنانه)", "hi": "सबा (स्त्री नाम)", "ps": "سبا (ښځينه نوم)", "ar": "سَبَا (اسْم عَلَم مُؤَنَّث)"},
    "sabaa": {"en": "Sabaa; Sheba (ancient kingdom)", "ur": "سبا، ملکہ سبا", "fa": "سبا، ملکه سبا", "hi": "सबा, शेबा", "ps": "سبا، د سبا ملکه", "ar": "سَبَأ (الْمَمْلَكَة الْقَدِيمَة)"},
    "sabah": {"en": "Sabah; morning", "ur": "صبح، صبح کا وقت", "fa": "صبح، بامداد", "hi": "सुबह, प्रभात", "ps": "سهار، سهار", "ar": "الصَّبَاح"},
    "sabahat": {"en": "Sabahat; beauty, grace (Turkish/Urdu)", "ur": "صباحت، خوبصورتی", "fa": "صباحت، زیبایی", "hi": "सबाहत, सुंदरता", "ps": "صباحت، ښکلا", "ar": "الصَّبَاحَة (الْجَمَال)"},
})

CUR = {
 "rohi": ("رُوحِي", "روحی", "روحی", "रोही", "روحي", "rohi", "Urdu", "Male",
          "Urdu روحی (rūhī), from Arabic رُوحِي", False, "high",
          "Rohi is Urdu روحی (rūhī) 'spiritual, of the soul', from Arabic رُوحِي. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Urdu. The source gloss 'Traveler, Pathfinder' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rohina": ("رُوهِينَا", "روہینا", "روهینا", "रोहीना", "روهینا", "rohina", "Urdu", "Female",
            "Urdu روہینا (rohīnā)", False, "medium",
            "Rohina is recorded as Urdu روہینا (rohīnā), a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Urdu. The source gloss 'Ascended to heaven' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rohul": ("رُوحُ الـ", "روح ال", "روح ال", "रोहुल", "روح ال", "rohul", "Urdu", "Male",
           "Urdu روح ال (rūh-ul), from Arabic رُوح in construct", False, "high",
           "Rohul is Urdu روح ال (rūh-ul) 'spirit of', a construct form of Arabic رُوح (rūḥ). CRITICAL SOURCE ERROR: the source gave روح (a truncated form) and labelled the origin Arabic; the name as used is Urdu. The source gloss 'Spirit of God' is unsupported and has been replaced with the lexical sense."),
 "romaisa": ("رُمَيْصَة", "رمیصہ", "رمیصه", "रुमैसा", "رمیصه", "romaisa", "Arabic", "Female",
             "Arabic رُمَيْصَة (Rumaiṣa)", False, "high",
             "Romaisa is Arabic رُمَيْصَة (Rumaiṣa), a female given name. The source gloss 'Moon-born, Little Moon' is unsupported and has been replaced with the documented identification. Same name as rumaisa."),
 "romana": ("رُومَانَا", "رومانہ", "رومانا", "रोमाना", "رومانا", "romana", "Arabic", "Female",
            "Arabic رُومَانَا (Rūmānā)", False, "medium",
            "Romana is recorded as Arabic رُومَانَا (Rūmānā), a female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name); the correct form is رُومَانَا. The source gloss 'The Roman One' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "roni": ("رُونِي", "رونی", "رونی", "रोनी", "روني", "roni", "Hebrew", "Male",
          "Hebrew רוני (Roni)", False, "high",
          "Roni is a Hebrew male given name, רוני (Roni). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Hebrew. The source gloss 'Joy, Delight' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rooh": ("رُوح", "روح", "روح", "रूह", "روح", "rooh", "Arabic", "Female",
          "Arabic root ر و ح (r-w-ḥ); رُوح (Rūḥ)", False, "high",
          "Rooh is Arabic رُوح (Rūḥ) 'soul, spirit', from the root ر و ح (r-w-ḥ). The source gloss 'Soul' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "roohi": ("رُوحِيَّة", "روحی", "روحی", "रूही", "روحيه", "roohi", "Arabic", "Female",
           "Arabic رُوحِيَّة (Rūḥiyya) 'spiritual'", False, "high",
           "Roohi is Arabic رُوحِيَّة (Rūḥiyya) 'spiritual, of the soul' (feminine), a relational adjective from رُوح (rūḥ). The source gloss 'Spirit, Soul' is broadly consistent."),
 "roqaya": ("رُقَيَّة", "رقایہ", "رقیه", "रुक़ैया", "رقیه", "roqaya", "Arabic", "Female",
            "Arabic رُقَيَّة (Ruqayya)", False, "high",
            "Roqaya is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. The source gloss 'Peaceful, calming, serene' is unsupported and has been replaced with the documented identification. Same name as ruqayya."),
 "roshaan": ("رَوْشَن", "روشن", "روشن", "रौशन", "روشن", "roshaan", "Persian", "Male",
             "Persian روشن (raushan)", False, "high",
             "Roshaan is a spelling variant of Persian روشن (raushan) 'bright, radiant'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Radiant, Shining' is consistent. Same name as roshan."),
 "roshan": ("رَوْشَن", "روشن", "روشن", "रौशन", "روشن", "roshan", "Persian", "Male",
            "Persian روشن (raushan)", False, "high",
            "Roshan is Persian روشن (raushan) 'bright, radiant'. CRITICAL SOURCE ERROR: the source gave the Latin string 'roshan' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Sun, Bright, Radiant' is broadly consistent."),
 "roshani": ("رَوْشَنِي", "روشنی", "روشنی", "रौशनी", "روشني", "roshani", "Urdu", "Female",
             "Urdu روشنی (roshanī), from Persian روشن", False, "high",
             "Roshani is Urdu روشنی (roshanī) 'light, brightness', from Persian روشن. CRITICAL SOURCE ERROR: the source gave رشاني (a non-standard form) and labelled the origin Arabic; the name as used is Urdu/Persian. The source gloss 'Guide, Light' is broadly consistent."),
 "roshna": ("رَوْشَنَا", "روشنا", "روشنا", "रौशना", "روشنا", "roshna", "Persian", "Female",
            "Persian روشنا (raushanā)", False, "high",
            "Roshna is Persian روشنا (raushanā) 'bright, radiant'. CRITICAL SOURCE ERROR: the source gave رشنا (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Radiant, shining' is consistent."),
 "rouza": ("رَوْضَة", "روضہ", "روضه", "रौज़ा", "روضه", "rouza", "Arabic", "Female",
           "Arabic root ر و ض (r-w-ḍ); رَوْضَة (Rauḍa)", False, "high",
           "Rouza is a spelling variant of Arabic رَوْضَة (Rauḍa) 'garden, meadow', from the root ر و ض (r-w-ḍ). CRITICAL SOURCE ERROR: the source gave the Latin string 'Rouza' instead of a script form. The source gloss 'Rose' is unsupported and has been replaced with the lexical sense. Same name as rawda."),
 "rowa": ("رَوَا", "روا", "روا", "रवा", "روا", "rowa", "Arabic", "Female",
          "Arabic رَوَا (Rawā)", False, "medium",
          "Rowa is recorded as Arabic رَوَا (Rawā), a female given name. The source gloss 'Flow' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rowan": ("رُوَان", "روان", "روان", "रोवन", "روان", "rowan", "Arabic", "Male",
           "Arabic رُوَان (Ruwān)", False, "medium",
           "Rowan is recorded as Arabic رُوَان (Ruwān), a male given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. The identification is recorded at medium confidence."),
 "rowel": ("رُوَيْل", "رویل", "رویل", "रोवेल", "رویل", "rowel", "Arabic", "Male",
           "Arabic رُوَيْل (Ruwail)", False, "medium",
           "Rowel is recorded as Arabic رُوَيْل (Ruwail), a male given name. The source gloss 'Little One' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "roya": ("رُويَا", "رویا", "رویا", "रोया", "رویا", "roya", "Persian", "Female",
          "Persian رویا (royā) 'dream, vision'", False, "high",
          "Roya is Persian رویا (royā) 'dream, vision', used as a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Princess, Lady' is unsupported and has been replaced with the lexical sense."),
 "rozha": ("رُوژَا", "روژہ", "روژه", "रोज़ा", "روژه", "rozha", "Kurdish", "Female",
           "Kurdish ڕۆژا (Rojā)", False, "medium",
           "Rozha is a Kurdish female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rozha' instead of a script form and labelled the origin Arabic; the name is Kurdish. The source gloss 'Rose' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rozhan": ("رُوژَان", "روژان", "روژان", "रोज़हान", "روژان", "rozhan", "Kurdish", "Female",
            "Kurdish ڕۆژان (Rojan)", False, "medium",
            "Rozhan is a Kurdish female given name. CRITICAL SOURCE ERROR: the source gave رزها ن (a broken form) and labelled the origin Arabic; the name is Kurdish. The source gloss 'Jasmine flower' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rozhin": ("رُوژِين", "روژین", "روژین", "रोज़हीन", "روژین", "rozhin", "Kurdish", "Female",
            "Kurdish ڕۆژین (Rojin)", False, "medium",
            "Rozhin is a Kurdish female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rozhin' instead of a script form and labelled the origin Arabic; the name is Kurdish. The source gloss 'Rose Garden' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rozina": ("رُوزِينَا", "روزینہ", "روزینا", "रोज़ीना", "روزینا", "rozina", "Persian", "Female",
            "Persian روزینا (Rozinā)", False, "medium",
            "Rozina is a female given name from Persian روزینا (Rozinā). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Beautiful Rose' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ruaa": ("رُؤَاء", "رؤاء", "رؤاء", "रुआ", "رؤاء", "ruaa", "Arabic", "Female",
          "Arabic root ر أ ي (r-ʾ-y); رُؤَاء (Ruʾāʾ)", False, "high",
          "Ruaa is Arabic رُؤَاء (Ruʾāʾ) 'visions', from the root ر أ ي (r-ʾ-y). The source gloss 'Call, Cry' is unsupported and has been replaced with the lexical sense."),
 "ruba": ("رُبَى", "ربى", "ربی", "रुबा", "ربی", "ruba", "Arabic", "Female",
          "Arabic رُبَى (Rubā)", False, "high",
          "Ruba is Arabic رُبَى (Rubā), a female given name. The source gloss 'Butterfly' is unsupported and has been replaced with the documented identification."),
 "rubab": ("رُبَاب", "رباب", "رباب", "रुबाब", "رباب", "rubab", "Arabic", "Female",
           "Arabic رُبَاب (Rubāb)", False, "high",
           "Rubab is Arabic رُبَاب (Rubāb), a female given name. The source gloss 'Bringer of peace' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "ruban": ("رُوبَن", "روبن", "روبن", "रुबन", "روبن", "ruban", "Tamil", "Male",
           "Tamil ரூபன் (Rūpaṉ)", False, "medium",
           "Ruban is a Tamil/Malay male given name. CRITICAL SOURCE ERROR: the source gave ربي ن (a broken form) and labelled the origin Arabic; the name as used is Tamil/Malay. The source gloss 'Silk, thread, jewel' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "rubee": ("رُوبِي", "روبی", "روبی", "रूबी", "روبي", "rubee", "Arabic", "Female",
           "Arabic رُوبِي (Rūbī) 'ruby'", False, "high",
           "Rubee is a spelling variant of Arabic رُوبِي (Rūbī) 'ruby', a gemstone name used as a female given name. CRITICAL SOURCE ERROR: the source gave روبی (a non-standard form). The source gloss 'Ruby' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as rubi."),
 "rubi": ("رُوبِي", "روبی", "روبی", "रूबी", "روبي", "rubi", "Arabic", "Female",
          "Arabic رُوبِي (Rūbī) 'ruby'", False, "high",
          "Rubi is Arabic رُوبِي (Rūbī) 'ruby', a gemstone name used as a female given name. The source gloss 'Ruby' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "rubina": ("رُوبِينَا", "روبینہ", "روبینا", "रुबीना", "روبینا", "rubina", "Urdu", "Female",
            "Urdu روبینہ (rubīnā)", False, "high",
            "Rubina is Urdu روبینہ (rubīnā), a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Urdu/Persian. The source gloss 'Luminous, Glowing' is unsupported and has been replaced with the documented identification."),
 "rubiya": ("رُبَيْعَة", "ربیعہ", "ربیه", "रुबिया", "ربیه", "rubiya", "Arabic", "Female",
            "Arabic رُبَيْعَة (Rubaiʿa)", False, "high",
            "Rubiya is Arabic رُبَيْعَة (Rubaiʿa), a female given name. The source gloss 'Ruby' is unsupported and has been replaced with the documented identification."),
 "rufaida": ("رُفَيْدَة", "رفیدہ", "رفیده", "रुफ़ैदा", "رفیده", "rufaida", "Arabic", "Female",
             "Arabic رُفَيْدَة (Rufaida)", False, "high",
             "Rufaida is Arabic رُفَيْدَة (Rufaida), a female given name. The source gloss 'Mother of the Poor' is unsupported and has been replaced with the documented identification."),
 "ruha": ("رُوح", "روح", "روح", "रूह", "روح", "ruha", "Arabic", "Female",
          "Arabic root ر و ح (r-w-ḥ); رُوح (Rūḥ)", False, "high",
          "Ruha is Arabic رُوح (Rūḥ) 'soul, spirit', from the root ر و ح (r-w-ḥ). The source gloss 'Spirit, Soul' is consistent. Same name as rooh."),
 "ruhama": ("رَحْمَة", "رحمہ", "رحمه", "रहमा", "رحمه", "ruhama", "Arabic", "Female",
            "Arabic root ر ح م (r-ḥ-m); رَحْمَة (Raḥma)", False, "high",
            "Ruhama is a spelling variant of Arabic رَحْمَة (Raḥma) 'mercy, compassion', from the root ر ح م (r-ḥ-m). The source gloss 'Highly Exalted' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as rahma."),
 "ruhan": ("رُوحَان", "روحان", "روحان", "रूहान", "روحان", "ruhan", "Arabic", "Male",
           "Arabic رُوحَان (Rūḥān)", False, "high",
           "Ruhan is Arabic رُوحَان (Rūḥān) 'spiritual, of the soul'. The source gloss 'Compassionate' is unsupported and has been replaced with the lexical sense."),
 "ruhana": ("رُوحَانَة", "روحانہ", "روحانه", "रूहाना", "روحانه", "ruhana", "Arabic", "Female",
            "Arabic رُوحَانَة (Rūḥāna)", False, "high",
            "Ruhana is Arabic رُوحَانَة (Rūḥāna), a female given name. The source gloss 'Spirit' is broadly consistent."),
 "ruhani": ("رُوحَانِيَّة", "روحانی", "روحانی", "रूहानी", "روحانيه", "ruhani", "Arabic", "Female",
            "Arabic رُوحَانِيَّة (Rūḥāniyya) 'spiritual'", False, "high",
            "Ruhani is Arabic رُوحَانِيَّة (Rūḥāniyya) 'spiritual' (feminine), a relational adjective from رُوح (rūḥ). The source gloss 'Soul, Spirit' is broadly consistent."),
 "ruhena": ("رُوحِينَة", "روحینہ", "روهینه", "रुहीना", "روحینه", "ruhena", "Arabic", "Female",
            "Arabic رُوحِينَة (Rūḥīna)", False, "medium",
            "Ruhena is recorded as Arabic رُوحِينَة (Rūḥīna), a female given name. The source gloss 'Moon, Rain' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ruhi": ("رُوحِي", "روحی", "روحی", "रूही", "روحي", "ruhi", "Arabic", "Female",
          "Arabic رُوحِي (Rūḥī) 'spiritual'", False, "high",
          "Ruhi is Arabic رُوحِي (Rūḥī) 'spiritual, of the soul', a relational adjective from رُوح (rūḥ). The source gloss 'Spirit, Soul, Wisdom' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "ruhiya": ("رُوحِيَّة", "روحیہ", "روحیه", "रूहिया", "روحيه", "ruhiya", "Arabic", "Female",
            "Arabic رُوحِيَّة (Rūḥiyya) 'spiritual'", False, "high",
            "Ruhiya is Arabic رُوحِيَّة (Rūḥiyya) 'spiritual' (feminine), a relational adjective from رُوح (rūḥ). The source gloss 'Spirit, Soul, Wisdom' is broadly consistent. Same name as ruhi."),
 "ruhul": ("رُوحُ الـ", "روح ال", "روح ال", "रूहुल", "روح ال", "ruhul", "Arabic", "Male",
           "Arabic رُوح (rūḥ) in construct with the article", False, "high",
           "Ruhul is Arabic رُوحُ الـ (Rūḥu l-) 'spirit of', a construct form of رُوح (rūḥ). CRITICAL SOURCE ERROR: the source gave روحل (a broken form). The source gloss 'Spirit' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rukaiya": ("رُقَيَّة", "رقیه", "رقیه", "रुक़ैया", "رقیه", "rukaiya", "Arabic", "Female",
             "Arabic رُقَيَّة (Ruqayya)", False, "high",
             "Rukaiya is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. The source gloss 'Exalted, Lofty' is unsupported and has been replaced with the documented identification. Same name as ruqayya."),
 "rukan": ("رُكْن", "رکن", "رکن", "रुकन", "رکن", "rukan", "Arabic", "Male",
           "Arabic root ر ك ن (r-k-n); رُكْن (Rukn)", False, "high",
           "Rukan is Arabic رُكْن (Rukn) 'pillar, support', from the root ر ك ن (r-k-n). CRITICAL SOURCE ERROR: the source gave رُكُون (a different form). The source gloss 'Crown, ring' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rukayah": ("رُقَيَّة", "رقایہ", "رقیه", "रुक़ैया", "رقیه", "rukayah", "Arabic", "Female",
             "Arabic رُقَيَّة (Ruqayya)", False, "high",
             "Rukayah is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. CRITICAL SOURCE ERROR: the source gave روكايه (a form using a Russian kaf). The source gloss 'Elevation, Exaltation' is unsupported and has been replaced with the documented identification. Same name as ruqayya."),
 "rukayat": ("رُكَيَّات", "رکیت", "رکیت", "रुकयात", "رکیت", "rukayat", "Arabic", "Female",
             "Arabic رُكَيَّات (Rukayyāt)", False, "medium",
             "Rukayat is recorded as Arabic رُكَيَّات (Rukayyāt), a female given name. The source gloss 'Rest' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rukayya": ("رُقَيَّة", "رقیه", "رقیه", "रुक़ैया", "رقیه", "rukayya", "Arabic", "Female",
             "Arabic رُقَيَّة (Ruqayya)", False, "high",
             "Rukayya is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. CRITICAL SOURCE ERROR: the source gave رُكَيَّة (a non-standard form). The source gloss 'Merciful' is unsupported and has been replaced with the documented identification. Same name as ruqayya."),
 "rukhsana": ("رُخْسَانَة", "رخسانہ", "رخسانه", "रुख़साना", "رخسانه", "rukhsana", "Persian", "Female",
              "Persian رخسانه (rukhsāna)", False, "high",
              "Rukhsana is a female given name from Persian رخسانه (rukhsāna). CRITICAL SOURCE ERROR: the source gave رخسنة (a non-standard form) and labelled the origin Arabic; the name is Persian/Urdu. The source gloss 'Face Brightened' is unsupported and has been replaced with the documented identification. Same name as ruksana."),
 "rukhsar": ("رُخْسَار", "رخسار", "رخسار", "रुख़सार", "رخسار", "rukhsar", "Persian", "Female",
             "Persian رخسار (rukhsār) 'cheek, face'", False, "high",
             "Rukhsar is Persian رخسار (rukhsār) 'cheek, face', used as a female given name. CRITICAL SOURCE ERROR: the source gave روخسر (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Light in the darkness' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "ruksana": ("رُخْسَانَة", "رخسانہ", "رخسانه", "रुख़साना", "رخسانه", "ruksana", "Urdu", "Female",
             "Urdu رخسانہ (rukhsānā), from Persian", False, "high",
             "Ruksana is Urdu رخسانہ (rukhsānā), a female given name from Persian. CRITICAL SOURCE ERROR: the source gave the Latin string 'Ruksana' instead of a script form and labelled the origin Arabic; the name as used is Urdu. The source gloss 'Elegant, Beautiful, Delicate' is unsupported and has been replaced with the documented identification. Same name as rukhsana."),
 "ruma": ("رُومَا", "روما", "روما", "रूमा", "روما", "ruma", "Arabic", "Female",
          "Arabic رُومَا (Rūmā)", False, "medium",
          "Ruma is recorded as Arabic رُومَا (Rūmā), a female given name. The source gloss 'Companion' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "rumaisa": ("رُمَيْسَاء", "رمیساء", "رمیساء", "रुमैसा", "رمیساء", "rumaisa", "Arabic", "Female",
             "Arabic رُمَيْسَاء (Rumaisāʾ)", False, "high",
             "Rumaisa is Arabic رُمَيْسَاء (Rumaisāʾ), a female given name. The source gloss 'Small and Delicate' is unsupported and has been replaced with the documented identification. Same name as romaisa."),
 "ruman": ("رُومَان", "رومان", "رومان", "रूमान", "رومان", "ruman", "Arabic", "Male",
           "Arabic رُومَان (Rūmān)", False, "medium",
           "Ruman is recorded as Arabic رُومَان (Rūmān), a male given name. The source gloss 'rain, red' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rumana": ("رُومَانَا", "رومانہ", "رومانا", "रूमाना", "رومانا", "rumana", "Arabic", "Female",
            "Arabic رُومَانَا (Rūmānā)", False, "medium",
            "Rumana is recorded as Arabic رُومَانَا (Rūmānā), a female given name. The source gloss 'Grace' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rumi": ("رُومِي", "رومی", "رومی", "रूमी", "رومي", "rumi", "Persian", "Male",
          "Persian رومی (rūmī) 'of Rum'", False, "high",
          "Rumi is Persian رومی (rūmī) 'of Rum, Anatolian', a relational name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian/Turkish. The source gloss 'Ode to the Prophet' is unsupported and has been replaced with the lexical sense."),
 "rumman": ("رُمَّان", "رمان", "رمان", "रुम्मान", "رمان", "rumman", "Arabic", "Female",
            "Arabic root ر م ن (r-m-n); رُمَّان (Rummān)", False, "high",
            "Rumman is Arabic رُمَّان (Rummān) 'pomegranate'. The source gloss 'Pomegranate' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "runak": ("رُونَك", "رونک", "رونک", "रूनक", "رونک", "runak", "Arabic", "Female",
           "Arabic رُونَك (Rūnak)", False, "medium",
           "Runak is recorded as Arabic رُونَك (Rūnak), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Runak' instead of a script form. The source gloss 'Jasmine flower' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "ruqaiya": ("رُقَيَّة", "رقیه", "رقیه", "रुक़ैया", "رقیه", "ruqaiya", "Arabic", "Female",
             "Arabic رُقَيَّة (Ruqayya)", False, "high",
             "Ruqaiya is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. CRITICAL SOURCE ERROR: the source gave رقيه (a non-standard form). The source gloss 'Quencher of Thirst' is unsupported and has been replaced with the documented identification. Same name as ruqayya."),
 "ruqaya": ("رُقَيَّة", "رقایہ", "رقیه", "रुक़ैया", "رقیه", "ruqaya", "Arabic", "Female",
            "Arabic رُقَيَّة (Ruqayya)", False, "high",
            "Ruqaya is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as ruqayya."),
 "ruqayah": ("رُقَيَّة", "رقایہ", "رقیه", "रुक़ैया", "رقیه", "ruqayah", "Arabic", "Female",
             "Arabic رُقَيَّة (Ruqayya)", False, "high",
             "Ruqayah is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. CRITICAL SOURCE ERROR: the source gave روقayah (a broken Latin-Arabic mix). The source gloss 'Seeker of healing' is unsupported and has been replaced with the documented identification. Same name as ruqayya."),
 "ruqayya": ("رُقَيَّة", "رقیه", "رقیه", "रुक़ैया", "رقیه", "ruqayya", "Arabic", "Female",
             "Arabic رُقَيَّة (Ruqayya)", False, "high",
             "Ruqayya is Arabic رُقَيَّة (Ruqayya), a female given name. The source gloss 'Seeking refuge' is unsupported and has been replaced with the documented identification."),
 "ruqayyah": ("رُقَيَّة", "رقیه", "رقیه", "रुक़ैया", "رقیه", "ruqayyah", "Arabic", "Female",
              "Arabic رُقَيَّة (Ruqayya)", False, "high",
              "Ruqayyah is a spelling variant of Arabic رُقَيَّة (Ruqayya), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as ruqayya."),
 "rushan": ("رَوْشَن", "روشن", "روشن", "रौशन", "روشن", "rushan", "Persian", "Male",
            "Persian روشن (raushan)", False, "high",
            "Rushan is a spelling variant of Persian روشن (raushan) 'bright, radiant'. CRITICAL SOURCE ERROR: the source gave روشان (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Moon, radiant, bright' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as roshan."),
 "rushda": ("رُشْدَة", "رشدہ", "رشده", "रुशदा", "رشده", "rushda", "Arabic", "Female",
            "Arabic root ر ش د (r-sh-d); رُشْدَة (Rushda)", False, "high",
            "Rushda is Arabic رُشْدَة (Rushda) 'right guidance' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Guide, Leader' is unsupported and has been replaced with the lexical sense."),
 "rushdi": ("رُشْدِي", "رشدی", "رشدی", "रुशदी", "رشدي", "rushdi", "Arabic", "Male",
            "Arabic رُشْدِي (Rushdī) 'of right guidance'", False, "high",
            "Rushdi is Arabic رُشْدِي (Rushdī) 'of right guidance', a relational adjective from رُشْد (rushd). The source gloss 'Rightly Guided' is broadly consistent. Same name as rochdi."),
 "rustam": ("رُسْتَم", "رستم", "رستم", "रुस्तम", "رستم", "rustam", "Persian", "Male",
            "Persian رستم (Rustam)", False, "high",
            "Rustam is a Persian male given name, رستم (Rustam), the hero of the Shahnameh. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Strong and mighty' is unsupported and has been replaced with the documented identification."),
 "rustom": ("رُسْتَم", "رستم", "رستم", "रुस्तम", "رستم", "rustom", "Persian", "Male",
            "Persian رستم (Rustam)", False, "high",
            "Rustom is a spelling variant of Persian رستم (Rustam), a male given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian/Urdu. The source gloss 'Brave warrior' is unsupported and has been replaced with the documented identification. Same name as rustam."),
 "rustum": ("رُسْتَم", "رستم", "رستم", "रुस्तुम", "رستم", "rustum", "Persian", "Male",
            "Persian رستم (Rustam)", False, "high",
            "Rustum is a spelling variant of Persian رستم (Rustam), a male given name. CRITICAL SOURCE ERROR: the source gave ر سطم (a broken form) and labelled the origin Arabic; the name is Persian. The source gloss 'Strong Warrior, Hero' is unsupported and has been replaced with the documented identification. Same name as rustam."),
 "rusul": ("رُسُل", "رسل", "رسل", "रुसुल", "رسل", "rusul", "Arabic", "Male",
           "Arabic root ر س ل (r-s-l); رُسُل (Rusul)", False, "high",
           "Rusul is Arabic رُسُل (Rusul) 'messengers', the plural of رَسُول (rasūl). The source gloss 'Messenger' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rusydi": ("رُشْدِي", "رشدی", "رشدی", "रुशदी", "رشدي", "rusydi", "Arabic", "Male",
            "Arabic رُشْدِي (Rushdī) 'of right guidance'", False, "high",
            "Rusydi is a spelling variant of Arabic رُشْدِي (Rushdī) 'of right guidance', a relational adjective from رُشْد (rushd). CRITICAL SOURCE ERROR: the source gave the Latin string 'Rusydi' instead of a script form. The source gloss 'Little Wise One' is unsupported and has been replaced with the lexical sense. Same name as rushdi."),
 "ruth": ("رُوث", "روت", "روت", "रूथ", "روت", "ruth", "Hebrew", "Female",
          "Hebrew רות (Rut)", False, "high",
          "Ruth is a Hebrew female given name, רות (Rut). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Hebrew. The source gloss 'Companion, Friend, Vision of Beauty' is unsupported and has been replaced with the documented identification."),
 "ruwaida": ("رُوَيْدَة", "روئیدہ", "روئیده", "रुवैदा", "روئیده", "ruwaida", "Arabic", "Female",
             "Arabic رُوَيْدَة (Ruwāida)", False, "high",
             "Ruwaida is Arabic رُوَيْدَة (Ruwāida), a female given name. The source gloss 'Gazelle' is unsupported and has been replaced with the documented identification. Same name as ruwayda."),
 "ruwayda": ("رُوَيْدَة", "رویدہ", "رویده", "रुवैदा", "رویده", "ruwayda", "Arabic", "Female",
             "Arabic رُوَيْدَة (Ruwāida)", False, "high",
             "Ruwayda is a spelling variant of Arabic رُوَيْدَة (Ruwāida), a female given name. The source gloss 'Contentment, Satisfaction' is unsupported and has been replaced with the documented identification. Same name as ruwaida."),
 "ruwaydah": ("رُوَيْضَة", "رویضہ", "رویضه", "रुवैदा", "رویضه", "ruwaydah", "Arabic", "Female",
              "Arabic رُوَيْضَة (Ruwaiḍa)", False, "medium",
              "Ruwaydah is recorded as Arabic رُوَيْضَة (Ruwaiḍa), a female given name. The source gloss 'Little Gardener' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ruya": ("رُؤْيَا", "رویا", "رویا", "रूया", "رویا", "ruya", "Turkish", "Female",
          "Turkish Rüya, from Arabic رُؤْيَا", False, "high",
          "Ruya is the Turkish form of Arabic رُؤْيَا (Ruʾyā) 'dream, vision', used as a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Turkish. The source gloss 'Dream, Vision' is consistent."),
 "rya": ("رِيَا", "ریا", "ریا", "रिया", "ریا", "rya", "Arabic", "Female",
         "Arabic رِيَا (Riyā)", False, "medium",
         "Rya is recorded as Arabic رِيَا (Riyā), a female given name. CRITICAL SOURCE ERROR: the source gave رياء (a different form). The source gloss 'Content, Satisfied' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sa": ("سَا", "سا", "سا", "सा", "سا", "sa", "Arabic", "Male",
        "Arabic سَا (Sā)", False, "medium",
        "Sa is recorded as Arabic سَا (Sā), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Sa' instead of a script form. The source gloss 'Live, Existence, Being, Said' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "sa-d": ("سَعْد", "سعد", "سعد", "साद", "سعد", "sa-d", "Arabic", "Male",
          "Arabic root س ع د (s-ʿ-d); سَعْد (Saʿd)", False, "high",
          "Sa'd is Arabic سَعْد (Saʿd) 'good fortune, happiness', from the root س ع د (s-ʿ-d). The source gloss 'Happiness, Luck' is consistent."),
 "sa-idah": ("سَعِيدَة", "سعیدہ", "سعیده", "सईदा", "سعیده", "sa-idah", "Arabic", "Female",
             "Arabic root س ع د (s-ʿ-d); سَعِيدَة (Saʿīda)", False, "high",
             "Sa'idah is Arabic سَعِيدَة (Saʿīda) 'happy, fortunate' (feminine), from the root س ع د (s-ʿ-d). The source gloss 'Happy' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "saabir": ("صَابِر", "صابر", "صابر", "साबिर", "صابر", "saabir", "Arabic", "Male",
            "Arabic root ص ب ر (ṣ-b-r); صَابِر (Ṣābir)", False, "high",
            "Saabir is Arabic صَابِر (Ṣābir) 'patient, enduring', from the root ص ب ر (ṣ-b-r). The source gloss 'Patient, Enduring' is consistent."),
 "saabit": ("ثَابِت", "ثابت", "ثابت", "साबित", "ثابت", "saabit", "Arabic", "Male",
            "Arabic root ث ب ت (th-b-t); ثَابِت (Thābit)", False, "high",
            "Saabit is a spelling variant of Arabic ثَابِت (Thābit) 'firm, steadfast', from the root ث ب ت (th-b-t). CRITICAL SOURCE ERROR: the source gave سعبت (a different form). The source gloss 'Firm, Trustworthy' is broadly consistent. Same name as thabit."),
 "saad": ("سَعْد", "سعد", "سعد", "साद", "سعد", "saad", "Arabic", "Male",
          "Arabic root س ع د (s-ʿ-d); سَعْد (Saʿd)", False, "high",
          "Saad is Arabic سَعْد (Saʿd) 'good fortune, happiness', from the root س ع د (s-ʿ-d). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as sa-d."),
 "saadah": ("سَعَادَة", "سعادہ", "سعاده", "सआदा", "سعاده", "saadah", "Arabic", "Female",
            "Arabic root س ع د (s-ʿ-d); سَعَادَة (Saʿāda)", False, "high",
            "Saadah is Arabic سَعَادَة (Saʿāda) 'happiness, contentment', from the root س ع د (s-ʿ-d). The source gloss 'Happiness, contentment' is consistent."),
 "saadan": ("سَعْدَان", "سعدان", "سعدان", "सादान", "سعدان", "saadan", "Arabic", "Male",
            "Arabic root س ع د (s-ʿ-d); سَعْدَان (Saʿdān)", False, "high",
            "Saadan is Arabic سَعْدَان (Saʿdān) 'happy, joyous', from the root س ع د (s-ʿ-d). The source gloss 'Happy, Joyous' is consistent."),
 "saadat": ("سَعَادَة", "سعادت", "سعادت", "सआदत", "سعادت", "saadat", "Arabic", "Male",
            "Arabic root س ع د (s-ʿ-d); سَعَادَة (Saʿāda)", False, "high",
            "Saadat is a spelling variant of Arabic سَعَادَة (Saʿāda) 'happiness, bliss', from the root س ع د (s-ʿ-d). The source gloss 'Happiness, Bliss' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "saadi": ("سَعْدِي", "سعدی", "سعدی", "सादी", "سعدي", "saadi", "Arabic", "Male",
           "Arabic سَعْدِي (Saʿdī) 'fortunate'", False, "high",
           "Saadi is Arabic سَعْدِي (Saʿdī) 'fortunate, happy', a relational adjective from سَعْد (saʿd). The source gloss 'Fortunate, Happy' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "saadia": ("سَعْدِيَّة", "سعدیہ", "سعدیه", "सादिया", "سعديه", "saadia", "Arabic", "Female",
            "Arabic سَعْدِيَّة (Saʿdiyya) 'fortunate' (feminine)", False, "high",
            "Saadia is Arabic سَعْدِيَّة (Saʿdiyya) 'happy, fortunate' (feminine), a relational adjective from سَعْد (saʿd). The source gloss 'Lucky, fortunate' is consistent. Same name as saadiya."),
 "saadiq": ("صَادِق", "صادق", "صادق", "सादिक़", "صادق", "saadiq", "Arabic", "Male",
            "Arabic root ص د ق (ṣ-d-q); صَادِق (Ṣādiq)", False, "high",
            "Saadiq is Arabic صَادِق (Ṣādiq) 'truthful, sincere', from the root ص د ق (ṣ-d-q). The source gloss 'Truthful, Sincere' is consistent."),
 "saadiya": ("سَعْدِيَّة", "سعدیہ", "سعدیه", "सादिया", "سعديه", "saadiya", "Arabic", "Female",
             "Arabic سَعْدِيَّة (Saʿdiyya) 'fortunate' (feminine)", False, "high",
             "Saadiya is Arabic سَعْدِيَّة (Saʿdiyya) 'happy, fortunate' (feminine), a relational adjective from سَعْد (saʿd). The source gloss 'Happy' is consistent. Same name as saadia."),
 "saaed": ("سَعِيد", "سعید", "سعید", "सईद", "سعید", "saaed", "Arabic", "Male",
           "Arabic root س ع د (s-ʿ-d); سَعِيد (Saʿīd)", False, "high",
           "Saaed is a spelling variant of Arabic سَعِيد (Saʿīd) 'happy, fortunate', from the root س ع د (s-ʿ-d). The source gloss 'Happy' is consistent. Same name as said."),
 "saaf": ("صَافِي", "صاف", "صاف", "साफ़", "صافي", "saaf", "Arabic", "Male",
          "Arabic root ص ف و (ṣ-f-w); صَافِي (Ṣāfī)", False, "high",
          "Saaf is a spelling variant of Arabic صَافِي (Ṣāfī) 'pure, clear', from the root ص ف و (ṣ-f-w). The source gloss 'Clean, Pure' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "saaid": ("سَعِيد", "سعید", "سعید", "सईद", "سعید", "saaid", "Arabic", "Male",
           "Arabic root س ع د (s-ʿ-d); سَعِيد (Saʿīd)", False, "high",
           "Saaid is a spelling variant of Arabic سَعِيد (Saʿīd) 'happy, fortunate', from the root س ع د (s-ʿ-d). The source gloss 'Helper, Support' is unsupported and has been replaced with the lexical sense. Same name as said."),
 "saaida": ("سَعِيدَة", "سعیدہ", "سعیده", "सईदा", "سعیده", "saaida", "Arabic", "Female",
            "Arabic root س ع د (s-ʿ-d); سَعِيدَة (Saʿīda)", False, "high",
            "Saaida is Arabic سَعِيدَة (Saʿīda) 'happy, fortunate' (feminine), from the root س ع د (s-ʿ-d). The source gloss 'Delighted, Pleased' is broadly consistent. Same name as sa-idah."),
 "saalim": ("سَالِم", "سالم", "سالم", "सालिम", "سالم", "saalim", "Arabic", "Male",
            "Arabic root س ل م (s-l-m); سَالِم (Sālim)", False, "high",
            "Saalim is Arabic سَالِم (Sālim) 'safe, sound', from the root س ل م (s-l-m). The source gloss 'Successful, Lucky' is unsupported and has been replaced with the lexical sense."),
 "saami": ("سَامِي", "سامی", "سامی", "सामी", "سامي", "saami", "Arabic", "Male",
           "Arabic root س م و (s-m-w); سَامِي (Sāmī)", False, "high",
           "Saami is Arabic سَامِي (Sāmī) 'elevated, sublime', from the root س م و (s-m-w). The source gloss 'Calm, Peaceful' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "saara": ("سَارَة", "سارہ", "سارا", "सारा", "سارا", "saara", "Arabic", "Female",
           "Arabic سَارَة (Sāra)", False, "high",
           "Saara is a spelling variant of Arabic سَارَة (Sāra), a female given name. The source gloss 'Gentle Breeze' is unsupported and has been replaced with the documented identification. Same name as saarah."),
 "saarah": ("سَارَة", "سارہ", "سارا", "सारा", "سارا", "saarah", "Arabic", "Female",
            "Arabic سَارَة (Sāra)", False, "high",
            "Saarah is Arabic سَارَة (Sāra), a female given name. The source gloss 'Leader or princess' is unsupported and has been replaced with the documented identification."),
 "saat": ("سَاعَة", "ساعت", "ساعت", "साअत", "ساعت", "saat", "Arabic", "Female",
          "Arabic root س و ع (s-w-ʿ); سَاعَة (Sāʿa)", False, "high",
          "Saat is Arabic سَاعَة (Sāʿa) 'hour, time'. The source gloss 'Time' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "saba": ("سَبَا", "سبا", "سبا", "सबा", "سبا", "saba", "Arabic", "Female",
          "Arabic سَبَا (Sabā)", False, "high",
          "Saba is Arabic سَبَا (Sabā), a female given name. CRITICAL SOURCE ERROR: the source gave 'عربي_Saba' (a placeholder prefix); the correct form is سَبَا. The source gloss 'Noble and blessed' is unsupported and has been replaced with the documented identification."),
 "sabaa": ("سَبَأ", "سبا", "سبا", "सबा", "سبا", "sabaa", "Arabic", "Female",
           "Arabic سَبَأ (Sabaʾ), the ancient kingdom of Sheba", False, "high",
           "Sabaa is Arabic سَبَأ (Sabaʾ), the ancient kingdom of Sheba, used as a female given name. The source gloss 'Sixth' is unsupported and has been replaced with the documented identification."),
 "sabah": ("صَبَاح", "صبح", "صبح", "सुबह", "صباح", "sabah", "Arabic", "Female",
           "Arabic root ص ب ح (ṣ-b-ḥ); صَبَاح (Ṣabāḥ)", False, "high",
           "Sabah is Arabic صَبَاح (Ṣabāḥ) 'morning', from the root ص ب ح (ṣ-b-ḥ). The source gloss 'Morning' is consistent."),
 "sabahat": ("صَبَاحَة", "صباحت", "صباحت", "सबाहत", "صباحه", "sabahat", "Turkish", "Female",
             "Turkish Sabahat, from Arabic صَبَاحَة", False, "high",
             "Sabahat is the Turkish/Urdu form of Arabic صَبَاحَة (Ṣabāḥa) 'beauty, grace'. CRITICAL SOURCE ERROR: the source gave 'سبahat' (a broken Latin-Arabic mix) and labelled the origin Arabic; the name as used is Turkish/Urdu. The source gloss 'Morning, Dawn' is unsupported and has been replaced with the lexical sense."),
}
