# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 32 (jabeen..jawadi).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": jabeen -> جبيب ن (broken, should be جبین);
   jabeer -> جابر (should be جبير); jabin -> جابين (should be جبين); jad -> جاد
   (should be جاد, ok); jadallah -> جدالل ه (broken); jahangeer -> جہانگیر (Urdu
   letters); jahangir -> جهاؠیر (broken); jahanzaib -> جھانزیب (Urdu letters);
   jahanzeb -> جَهَانزَب (broken); jahara -> جَهَارَة (should be جهراء);
   jaheem -> جهيم (should be جحيم); jahfar -> جهفر (should be جعفر);
   jahida -> جاهدة (should be جاهدة, ok); jahir -> ظاهر (a different name);
   jahra -> جَحْرَاءَ (should be جهراء); jaida -> جَيْدَاء (should be جيداء);
   jair -> جائر (should be جائر, ok); jala -> "Jala" (Latin); jameela ->
   "عربي_Jameela" (junk); jamshaid/jamshed -> جمشید (Persian letters);
   jamsheed -> جمشيد; jan -> "jan" (Latin); janis -> جَانِيس (should be جانيس);
   jannatul -> جنتول (should be جنة الـ); jareer -> "Jareer" (Latin);
   jaseena -> "Jaseena" (Latin); jassim -> "Jassim" (Latin); jawa -> "Jawa"
   (Latin); javier -> "javier" (Latin); jawaad -> جوااد (broken).
 * DEGARBLED / WRONG glosses: jabeen 'Jasmine, Fragrant' (should be 'forehead');
   jabeer 'Companion, Partner' (should be diminutive of Jabir); jabin 'Given'
   (should be 'forehead'); jabr 'Firmness, Compulsion, Determination' (should be
   'compulsion, force'); jabran 'Great, Mighty' (should be 'Jabran'); jad 'Gem'
   (should be 'generous'); jada 'Gentle, Fragrant' (should be 'grandmother' or
   'Jada'); jadida 'New, Fresh' (correct); jadir 'Strong, Firm, Victorious'
   (unsupported); jafar 'Small Stream, Rivulet' (proper name Ja'far); jaffar
   'Friend, companion' (proper name); jaffer 'Stream or River' (proper name);
   jafran 'Born from the earth' (unsupported); jafri 'Pure, Handsome' (should be
   nisba of Ja'far); jafur 'Given by God' (unsupported); jah 'Gift from God'
   (should be 'rank, dignity'); jahan 'World, Universe' (correct, Persian);
   jahangeer 'Victorious, conqueror' (should be 'world-conqueror'); jahanzaib
   'Victorious, Gift of God' (should be 'beauty of the world'); jahara 'Gift of
   God' (unsupported); jaheem 'Gatherer' (should be 'hellfire'); jaheer 'Hunter'
   (should be 'open, public'); jahfar 'Concealer, Protector' (proper name);
   jahid 'Struggler, fighter' (correct); jahida 'Guide, Leader' (should be
   'female striver'); jahir 'Glory, Radiant' (should be 'open, public'); jahra
   'Gardener' (unsupported); jaida 'Gentle, beautiful, radiant' (should be
   'good, excellent'); jair 'Blessed, Helper' (unsupported); jaish 'Warrior,
   Soldier, Army' (should be 'army'); jal 'Gentle, kind' (should be 'great,
   majestic'); jala 'Gentle' (should be 'clarity, deliverance'); jalaa
   'Deliverance, Liberation, Elevation' (correct); jaleel 'Majestic, Radiant'
   (correct); jaleela 'Soft, Gentle, Beautiful' (should be 'majestic, fem');
   jalil 'Sublime, Exalted' (correct); jalila 'Noble and Beautiful' (should be
   'majestic, fem'); jamaal 'Adornment' (should be 'beauty'); jaman 'Morning'
   (should be 'pearls'); jameel 'Beautiful, handsomely adorned' (correct);
   jameela 'Noble and blessed' (should be 'beautiful, fem'); jami 'Beauty'
   (should be 'gatherer'); jamia 'Gathering, assembly' (should be 'university');
   jamir 'Gatherer, Sustainer' (unsupported); jamshaid 'Bright, Shining King'
   (proper name Jamshid); jamshed 'King of Justice' (proper name); jamsheed
   'King, Ruler' (proper name); jamshid 'Glory of the Sun' (proper name);
   jan 'God is gracious' (should be 'soul, life', Persian); janan 'Life, Soul'
   (should be 'hearts, souls'); janis 'God is merciful' (unsupported); janna
   'Garden of Paradise' (correct); jannah 'Garden of Paradise' (correct);
   jannatul 'Paradise' (compound element); jarah 'Gentle Gardener' (should be
   'neighbour, fem'); jaran 'Gentle' (unsupported); jareer 'The caller, the one
   who invites' (proper name Jarir); jari 'Gentle, Soft' (should be 'flowing');
   jarir 'Abundance' (proper name); jaseem 'Given by the moon' (proper name
   Jasim); jaseena 'Gentle, Gracious' (unsupported); jaseer 'Helpful' (should be
   'bold'); jaser 'Healer, Helper' (should be 'bold'); jashan 'Feast,
   celebration' (correct, Persian); jasim 'Strong, Powerful' (proper name);
   jasir 'Firm, Steadfast' (should be 'bold'); jasmina 'Jasmine flower'
   (correct); jassim 'Strong and Just' (proper name); jasur "God's helper"
   (should be 'bold, daring'); jauhar 'Glowing, Radiant' (should be 'jewel,
   essence'); jaun 'Yellow' (unsupported); javan 'Golden, Yellow' (should be
   'young', Persian); javeed 'Jewel, Precious' (should be 'eternal', Persian);
   javeria 'Radiant, Shining Light' (proper name Juwayriyya); javier 'Javier'
   (Spanish name); jawa 'Youth, Vigor' (unsupported); jawaad 'Gentle, Kind,
   Honest' (should be 'generous'); jawaahir 'Gems, Jewels' (correct); jawad
   'Generous, Noble' (correct); jawadi 'Eternal, Everlasting' (should be nisba
   of Jawad).
 * MISLABELLED ORIGIN: jabeen (Persian/Urdu), jahan/jahangeer/jahangir/
   jahanzaib/jahanzeb (Persian), jamshaid/jamshed/jamsheed/jamshid (Persian),
   jan (Persian), jashan (Persian), javan (Persian), javeed (Persian),
   javier (Spanish), jawaahir (Arabic, ok).
 * GENDER ERRORS: jabeer, jabin, jabr, jabran, jabri, jabril, jad, jadallah,
   jadir, jafran, jafri, jafur, jah, jaheem, jaheer, jahfar, jahid, jahir, jair,
   jaish, jal, jami, jamir, jareer, jari, jaseem, jaseer, jaser, jasim, jasir,
   jasur, jauhar, jaun, jawa, jawaahir were labelled female or unisex where
   documented usage is male.
 * JUNK / UNVERIFIABLE ENTRIES: jabir, jalal, jamal, jamila, jana, jannat
   (8-key stubs); jabin, jadir, jafran, jafur, jah, jahara, jahfar, jahra, jair,
   jala, jaman, jamir, jana, janis, jaran, jaseena, jaun, jawa, javier.
 * DUPLICATE CLUSTERS: jabeer/jaber/jabir; jafar/jaffar/jaffer/jahfar;
   jahangeer/jahangir; jahanzaib/jahanzeb; jaleel/jalil; jaleela/jalila/
   jalilah; jamaal/jamal; jameel/jamil; jameela/jameelah/jamilaa/jamilah/
   jamillah; jamshaid/jamshed/jamsheed/jamshid; janaat/janat/jannat;
   janna/jannah; jareer/jarir; jaseem/jasim/jassim; jaseer/jaser/jasir;
   jauhar/jawaahir; jawaad/jawad; jawa/javan.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated31 import GLOSSES as _G31

GLOSSES = dict(_G31)
GLOSSES.update({
    "forehead": {"en": "Forehead, brow", "ur": "جبین، پیشانی، ماتھا", "fa": "جبین، پیشانی", "hi": "माथा, ललाट, जबीन", "ps": "جبین، تندي", "ar": "الجبين، الجبهة"},
    "jubayr": {"en": "Jubayr; diminutive of Jabir", "ur": "جبیر، جابر کی تصغیر", "fa": "جبیر، تصغیر جابر", "hi": "जुबैर, जाबिर का लघु रूप", "ps": "جبیر، د جابر کوچنی بڼه", "ar": "جُبَيْر، تصغير جابر"},
    "jabir": {"en": "Jabir; comforter, one who sets bones", "ur": "جابر، تسلی دینے والا", "fa": "جابر، تسلیدهنده", "hi": "जाबिर, सांत्वना देने वाला", "ps": "جابر، تسلي ورکوونکی", "ar": "جَابِر، الذي يجبر الكسر ويواسي"},
    "compulsion": {"en": "Compulsion, force, coercion", "ur": "جبر، زبردستی، مجبوری", "fa": "جبر، زور، اجبار", "hi": "जबर, दबाव, मजबूरी", "ps": "جبر، زور، مجبوري", "ar": "الجبر، القهر، الإكراه"},
    "jabran": {"en": "Jabran; a male given name", "ur": "جبران (مردانہ نام)", "fa": "جبران (نام مردانه)", "hi": "जब्रान (पुरुष नाम)", "ps": "جبران (نر نوم)", "ar": "جَبْرَان (اسم علم مذكر)"},
    "jabri": {"en": "Jabri; of Jabr, belonging to Jabr", "ur": "جبری، جبر سے منسوب", "fa": "جبری، منسوب به جبر", "hi": "जबरी, जबर से", "ps": "جبري، د جبر اړوند", "ar": "الجَبْرِيّ، منسوب إلى جبر"},
    "gabriel": {"en": "Jibril; the angel Gabriel in Islamic tradition", "ur": "جبریل، فرشتہ جبرائیل", "fa": "جبریل، فرشته جبرئیل", "hi": "जिब्रील, फ़रिश्ता जिब्राईल", "ps": "جبریل، پرښته جبرائیل", "ar": "جِبْرِيل، الملك المذكور في القرآن"},
    "generous_jad": {"en": "Generous, bountiful, excellent", "ur": "جاد، سخی، بہترین", "fa": "جاد، بخشنده، نیکو", "hi": "उदार, दानवीर, उत्तम", "ps": "جاد، سخي، غوره", "ar": "الجَاد، الكريم، الجواد"},
    "jada": {"en": "Jada; a female given name", "ur": "جدا (زنانہ نام)", "fa": "جدا (نام زنانه)", "hi": "जाडा (स्त्री नाम)", "ps": "جدا (ښځينه نوم)", "ar": "جَادَة (اسم علم مؤنث)"},
    "jadallah": {"en": "Jadallah; 'the generosity of God'", "ur": "جداللہ، 'اللہ کی سخاوت'", "fa": "جدالله، 'بخشش خدا'", "hi": "जदअल्लाह, 'अल्लाह की उदारता'", "ps": "جدالله، 'د الله سخاوت'", "ar": "جَدَالله، 'جود الله وكرمه'"},
    "new_fresh": {"en": "New, fresh, recent", "ur": "جدید، نیا، تازہ", "fa": "جدید، نو، تازه", "hi": "नया, ताज़ा, नवीन", "ps": "نوی، تازه، جدید", "ar": "الجديد، الحديث، الطري"},
    "jadir": {"en": "Jadir; a male given name", "ur": "جادر (مردانہ نام)", "fa": "جادیر (نام مردانه)", "hi": "जादिर (पुरुष नाम)", "ps": "جادیر (نر نوم)", "ar": "جَادِر (اسم علم مذكر)"},
    "jafar": {"en": "Ja'far; a male given name", "ur": "جعفر (مردانہ نام)", "fa": "جعفر (نام مردانه)", "hi": "जाफ़र (पुरुष नाम)", "ps": "جعفر (نر نوم)", "ar": "جَعْفَر (اسم علم مذكر)"},
    "jafari": {"en": "Ja'fari; of Ja'far, belonging to Ja'far", "ur": "جعفری، جعفر سے منسوب", "fa": "جعفری، منسوب به جعفر", "hi": "जाफ़री, जाफ़र से", "ps": "جعفري، د جعفر اړوند", "ar": "الجَعْفَرِيّ، منسوب إلى جعفر"},
    "jafran": {"en": "Jafran; a male given name", "ur": "جفران (مردانہ نام)", "fa": "جفران (نام مردانه)", "hi": "जफ़रान (पुरुष नाम)", "ps": "جفران (نر نوم)", "ar": "جَفْرَان (اسم علم مذكر)"},
    "jafur": {"en": "Jafur; a male given name", "ur": "جعفور (مردانہ نام)", "fa": "جعفور (نام مردانه)", "hi": "जफ़ूर (पुरुष नाम)", "ps": "جعفور (نر نوم)", "ar": "جَعْفُور (اسم علم مذكر)"},
    "rank_jah": {"en": "Rank, dignity, standing", "ur": "جاہ، مرتبہ، وقار", "fa": "جاه، مرتبه، وقار", "hi": "पद, प्रतिष्ठा, मर्यादा", "ps": "جاه، مرتبه، وقار", "ar": "الجَاه، المنزلة، القدر"},
    "world": {"en": "World, universe (Persian)", "ur": "جہان، دنیا، عالم", "fa": "جهان، دنیا، عالم", "hi": "दुनिया, जहान, विश्व", "ps": "جهان، نړۍ، عالم", "ar": "الجهان، العالم، الكون (فارسي)"},
    "world_conqueror": {"en": "World-conqueror (Persian)", "ur": "جہانگیر، دنیا کا فاتح", "fa": "جهانگیر، فاتح جهان", "hi": "जहाँगीर, विश्व विजेता", "ps": "جهانگیر، د نړۍ فاتح", "ar": "جهانكير، فاتح العالم (فارسي)"},
    "world_beauty": {"en": "Beauty of the world (Persian)", "ur": "جہانزیب، دنیا کی زینت", "fa": "جهانزیب، زیبایی جهان", "hi": "जहाँज़ेब, दुनिया की शोभा", "ps": "جهانزیب، د نړۍ ښکلا", "ar": "جهانزيب، زينة العالم (فارسي)"},
    "jahara": {"en": "Jahara; a female given name", "ur": "جہارہ (زنانہ نام)", "fa": "جهاره (نام زنانه)", "hi": "जहारा (स्त्री नाम)", "ps": "جهاره (ښځينه نوم)", "ar": "جَهَارَة (اسم علم مؤنث)"},
    "hellfire": {"en": "Hellfire, blazing fire", "ur": "جحیم، بھڑکتی آگ", "fa": "جحیم، آتش سوزان", "hi": "जहीम, प्रज्वलित अग्नि", "ps": "جحیم، بلېدونکې اور", "ar": "الجحيم، النار الموقدة"},
    "open_public": {"en": "Open, public, manifest", "ur": "جاہر، ظاہر، کھلا", "fa": "جاهر، آشکار، علنی", "hi": "प्रकट, खुला, ज़ाहिर", "ps": "ښکاره، جاهر، پرانیستی", "ar": "الجاهر، الظاهر، العلني"},
    "striver": {"en": "Striver, one who struggles", "ur": "جاہد، کوشش کرنے والا", "fa": "جاهد، کوشنده", "hi": "जाहिद, प्रयास करने वाला", "ps": "جاهد، هڅوونکی", "ar": "الجاهد، المجتهد، الساعي"},
    "jahida": {"en": "Jahida; female striver", "ur": "جاہدہ، کوشش کرنے والی", "fa": "جاهده، کوشنده (زن)", "hi": "जाहिदा, प्रयास करने वाली", "ps": "جاهده، هڅوونکې", "ar": "الجاهدة، المجتهدة"},
    "jahra": {"en": "Jahra; a female given name", "ur": "جہرہ (زنانہ نام)", "fa": "جهره (نام زنانه)", "hi": "जहरा (स्त्री नाम)", "ps": "جهره (ښځينه نوم)", "ar": "جَهْرَاء (اسم علم مؤنث)"},
    "jaida": {"en": "Jaida; good, excellent", "ur": "جیداء، اچھی، بہترین", "fa": "جیداء، خوب، نیکو", "hi": "जैदा, अच्छी, उत्तम", "ps": "جیداء، ښه، غوره", "ar": "الجَيْدَاء، الجيدة، الحسنة"},
    "jair": {"en": "Jair; a male given name", "ur": "جائر (مردانہ نام)", "fa": "جائر (نام مردانه)", "hi": "जाइर (पुरुष नाम)", "ps": "جائر (نر نوم)", "ar": "جَائِر (اسم علم مذكر)"},
    "army": {"en": "Army, troops, host", "ur": "جیش، فوج، لشکر", "fa": "جیش، ارتش، لشکر", "hi": "सेना, फ़ौज, लश्कर", "ps": "جیش، پوځ، لښکر", "ar": "الجيش، العسكر، الحشد"},
    "jal": {"en": "Jal; great, majestic", "ur": "جل، بزرگ، جلیل", "fa": "جل، بزرگ، جلیل", "hi": "जल, महान, विशाल", "ps": "جل، لوی، جلیل", "ar": "الجَلّ، العظيم، الجليل"},
    "clarity": {"en": "Clarity, deliverance, liberation", "ur": "جلاء، صفائی، رہائی", "fa": "جلاء، روشنی، رهایی", "hi": "स्पष्टता, मुक्ति, निर्मलता", "ps": "جلاء، روښانتيا، خلاصون", "ar": "الجلاء، الصفاء، الخلاص"},
    "majesty": {"en": "Majesty, grandeur, glory", "ur": "جلال، عظمت، شان", "fa": "جلال، شکوه، عظمت", "hi": "जलाल, महिमा, वैभव", "ps": "جلال، لویي، شان", "ar": "الجلال، العظمة، البهاء"},
    "majestic": {"en": "Majestic, exalted, sublime", "ur": "جلیل، عظیم، بلند", "fa": "جلیل، عظیم، والا", "hi": "जलील, महान, उदात्त", "ps": "جلیل، لوی، اوچت", "ar": "الجليل، العظيم، الرفيع"},
    "majestic_f": {"en": "Majestic, exalted (feminine)", "ur": "جلیلہ، عظیمہ، بلند", "fa": "جلیله، عظیمه، والا", "hi": "जलीला, महान (स्त्री)", "ps": "جلیله، لویه، اوچته", "ar": "الجليلة، العظيمة، الرفيعة"},
    "beauty_jamal": {"en": "Beauty, comeliness, grace", "ur": "جمال، حسن، خوبصورتی", "fa": "جمال، زیبایی، حسن", "hi": "सौंदर्य, जमाल, सुंदरता", "ps": "جمال، ښکلا، حسن", "ar": "الجمال، الحسن، البهاء"},
    "pearls": {"en": "Pearls, small pearls", "ur": "جمان، موتی، موندی", "fa": "جمان، مروارید", "hi": "मोती, जुमान", "ps": "جمان، مرغلرې", "ar": "الجمان، اللؤلؤ الصغير"},
    "beautiful": {"en": "Beautiful, handsome, comely", "ur": "جمیل، خوبصورت، حسین", "fa": "جمیل، زیبا، نیکو", "hi": "सुंदर, जमील, हसीन", "ps": "جمیل، ښکلی، حسین", "ar": "الجميل، الحسن، الوسيم"},
    "beautiful_f": {"en": "Beautiful, comely (feminine)", "ur": "جمیلہ، خوبصورت", "fa": "جمیله، زیبا", "hi": "जमीला, सुंदर (स्त्री)", "ps": "جمیله، ښکلې", "ar": "الجميلة، الحسنة، الوسيمة"},
    "gatherer": {"en": "Gatherer, collector, unifier", "ur": "جامع، جمع کرنے والا", "fa": "جامع، گردآورنده", "hi": "संग्रहकर्ता, जामी", "ps": "جامع، راټولوونکی", "ar": "الجامع، الجمع، الحاوي"},
    "university": {"en": "University; gathering, assembly", "ur": "جامعہ، یونیورسٹی، اجتماع", "fa": "دانشگاه، گردهمایی", "hi": "विश्वविद्यालय, जमाव", "ps": "پوهنتون، ټولنه", "ar": "الجامعة، المجمع، الاجتماع"},
    "jamir": {"en": "Jamir; a male given name", "ur": "جمیر (مردانہ نام)", "fa": "جمیر (نام مردانه)", "hi": "जमीर (पुरुष नाम)", "ps": "جمیر (نر نوم)", "ar": "جَمِير (اسم علم مذكر)"},
    "jamshid": {"en": "Jamshid; a Persian name of legendary kings", "ur": "جمشید، فارسی نام", "fa": "جمشید، نامی در شاهنامه", "hi": "जमशीद, फ़ारसी नाम", "ps": "جمشید، فارسي نوم", "ar": "جمشيد، اسم فارسي"},
    "soul_life": {"en": "Soul, life, dear one (Persian)", "ur": "جان، روح، زندگی", "fa": "جان، روح، زندگی", "hi": "जान, आत्मा, जीवन", "ps": "جان، روح، ژوند", "ar": "الجان، الروح، الحياة (فارسي)"},
    "jana": {"en": "Jana; a female given name", "ur": "جانا (زنانہ نام)", "fa": "جانا (نام زنانه)", "hi": "जाना (स्त्री नाम)", "ps": "جانا (ښځينه نوم)", "ar": "جَانَا (اسم علم مؤنث)"},
    "gardens": {"en": "Gardens; gardens of paradise", "ur": "جنات، باغات، بہشت", "fa": "جنات، باغها، بهشت", "hi": "जन्नतें, बाग़, बहिश्त", "ps": "جنات، باغونه، جنت", "ar": "الجنات، البساتين، جمع جنّة"},
    "hearts": {"en": "Hearts, souls, inner selves", "ur": "جنان، دل، قلوب", "fa": "جنان، دلها، قلوب", "hi": "दिल, हृदय, जिनान", "ps": "جنان، زړونه، قلوب", "ar": "الجنان، القلوب، جمع جنان"},
    "janis": {"en": "Janis; a female given name", "ur": "جانيس (زنانہ نام)", "fa": "جانيس (نام زنانه)", "hi": "जानिस (स्त्री नाम)", "ps": "جانيس (ښځينه نوم)", "ar": "جَانِيس (اسم علم مؤنث)"},
    "garden_paradise": {"en": "Garden, paradise", "ur": "جنت، باغ، بہشت", "fa": "جنت، باغ، بهشت", "hi": "जन्नत, बाग़, स्वर्ग", "ps": "جنت، باغ، هسک", "ar": "الجنّة، البستان، الفردوس"},
    "jannatul": {"en": "Jannat al-; 'the garden of', a compound name element", "ur": "جنت الـ، ترکیبی نام کا جزو", "fa": "جنت الـ، جزء نام مرکب", "hi": "जन्नतुल-, संयुक्त नाम का अंश", "ps": "جنت الـ، د مرکب نوم برخه", "ar": "جنّة الـ، عنصر في اسم مركب"},
    "neighbour_f": {"en": "Neighbour (feminine)", "ur": "جارہ، پڑوسن", "fa": "جاره، همسایه (زن)", "hi": "पड़ोसन, जारा", "ps": "ګاونډې، جاره", "ar": "الجارة، المجاورة"},
    "jaran": {"en": "Jaran; a given name", "ur": "جاران (نام)", "fa": "جاران (نام)", "hi": "जारान (नाम)", "ps": "جاران (نوم)", "ar": "جَارَان (اسم علم)"},
    "jarir": {"en": "Jarir; a male given name", "ur": "جریر (مردانہ نام)", "fa": "جریر (نام مردانه)", "hi": "जरीर (पुरुष नाम)", "ps": "جریر (نر نوم)", "ar": "جَرِير (اسم علم مذكر)"},
    "flowing": {"en": "Flowing, running, current", "ur": "جاری، بہتا، رواں", "fa": "جاری، روان، رونده", "hi": "बहता, प्रवाहित, जारी", "ps": "بهیدونکی، روان، جاري", "ar": "الجاري، الساري، الماضي"},
    "jasim": {"en": "Jasim; a male given name", "ur": "جاسم (مردانہ نام)", "fa": "جاسم (نام مردانه)", "hi": "जासिम (पुरुष नाम)", "ps": "جاسم (نر نوم)", "ar": "جَاسِم (اسم علم مذكر)"},
    "jaseena": {"en": "Jaseena; a female given name", "ur": "جاسینا (زنانہ نام)", "fa": "جاسینا (نام زنانه)", "hi": "जसीना (स्त्री नाम)", "ps": "جاسینا (ښځينه نوم)", "ar": "جَاسِينَا (اسم علم مؤنث)"},
    "bold": {"en": "Bold, daring, courageous", "ur": "جسور، بہادر، دلیر", "fa": "جسور، دلیر، بیباک", "hi": "साहसी, निडर, बहादुर", "ps": "زړور، ننډر، بې باکه", "ar": "الجسور، الجريء، الشجاع"},
    "jashan": {"en": "Jashan; celebration, festival (Persian)", "ur": "جشن، تہوار، خوشی", "fa": "جشن، جشنواره، شادی", "hi": "जश्न, उत्सव, त्योहार", "ps": "جشن، اختر، مېله", "ar": "الجشن، الاحتفال، المهرجان (فارسي)"},
    "jasmine": {"en": "Jasmine; the jasmine flower", "ur": "یاسمین، چمیلی، جیسمین", "fa": "یاسمن، یاسمین", "hi": "चमेली, यासमीन", "ps": "یاسمین، چمیلي", "ar": "الياسمين، زهرة الياسمين"},
    "jauhar": {"en": "Jewel, essence, substance", "ur": "جوہر، گوہر، اصل", "fa": "جوهر، گوهر، ذات", "hi": "रत्न, जौहर, सार", "ps": "جوهر، غمې، اصل", "ar": "الجوهر، الجوهرة، الذات"},
    "jaun": {"en": "Jaun; a given name", "ur": "جون (نام)", "fa": "جون (نام)", "hi": "जौन (नाम)", "ps": "جون (نوم)", "ar": "جَوْن (اسم علم)"},
    "young": {"en": "Young, youthful (Persian)", "ur": "جوان، نوجوان", "fa": "جوان، نوجوان", "hi": "जवान, युवा", "ps": "ځوان، پیاوړی", "ar": "الجوان، الشاب، الفتي (فارسي)"},
    "eternal": {"en": "Eternal, everlasting (Persian)", "ur": "جاوید، ابدی، ہمیشہ", "fa": "جاوید، ابدی، همیشگی", "hi": "जावेद, शाश्वत, अमर", "ps": "جاوید، ابدي، تلپاتې", "ar": "الجاويد، الأبدي، الخالد (فارسي)"},
    "juwayriyya": {"en": "Juwayriyya; a female given name", "ur": "جویریہ (زنانہ نام)", "fa": "جویریه (نام زنانه)", "hi": "जुवैरिया (स्त्री नाम)", "ps": "جویریه (ښځينه نوم)", "ar": "جُوَيْرِيَّة (اسم علم مؤنث)"},
    "javier": {"en": "Javier; a Spanish male given name", "ur": "جیویر (ہسپانوی نام)", "fa": "خاویر (نام اسپانیایی)", "hi": "हावियेर (स्पेनी नाम)", "ps": "جاویر (هسپانوي نوم)", "ar": "خافيير (اسم علم مذكر إسباني)"},
    "jawa": {"en": "Jawa; a given name", "ur": "جوا (نام)", "fa": "جوا (نام)", "hi": "जवा (नाम)", "ps": "جوا (نوم)", "ar": "جَوَا (اسم علم)"},
    "generous_jawad": {"en": "Generous, noble, open-handed", "ur": "جواد، سخی، کریم", "fa": "جواد، بخشنده، کریم", "hi": "जवाद, उदार, दानवीर", "ps": "جواد، سخي، کریم", "ar": "الجواد، الكريم، السخي"},
    "jewels": {"en": "Jewels, gems, precious stones", "ur": "جواہر، نگ، قیمتی پتھر", "fa": "جواهر، گوهر، سنگهای قیمتی", "hi": "रत्न, जवाहर, बहुमूल्य पत्थर", "ps": "جواهر، غمې، قیمتي ډبرې", "ar": "الجواهر، الأحجار الكريمة، النفائس"},
    "jawadi": {"en": "Jawadi; of Jawad, belonging to Jawad", "ur": "جوادی، جواد سے منسوب", "fa": "جوادی، منسوب به جواد", "hi": "जवादी, जवाद से", "ps": "جوادي، د جواد اړوند", "ar": "الجَوَادِيّ، منسوب إلى جواد"},
})

CUR = {
 "jabeen": ("جبین", "جبین", "جبین", "जबीन", "جبین", "forehead", "Persian", "Female",
            "Persian/Urdu جبین (jabīn), from Arabic جَبِين", False, "medium",
            "Jabeen is Persian/Urdu جبین (jabīn) 'forehead, brow', from Arabic جَبِين. MISLABELLED ORIGIN: the source recorded the name as Arabic. CRITICAL SOURCE ERROR: the source gave the broken form جبيب ن and glossed the name 'Jasmine, Fragrant'; the correct form is جبین and the lexical sense is 'forehead'."),
 "jabeer": ("جبير", "جبیر", "جبیر", "जुबैर", "جبیر", "jubayr", "Arabic", "Male",
            "Arabic جُبَيْر (Jubayr)", False, "medium",
            "Jabeer is Arabic جُبَيْر (Jubayr), the diminutive of جَابِر (Jābir). CRITICAL SOURCE ERROR: the source gave جابر (the base form) and glossed the name 'Companion, Partner'; the correct form is جُبَيْر. Same name as jaber and jabir."),
 "jaber": ("جابر", "جابر", "جابر", "जाबिर", "جابر", "jabir", "Arabic", "Male",
           "Arabic root ج ب ر (j-b-r); جَابِر (Jābir)", False, "high",
           "Jaber is Arabic جَابِر (Jābir) 'comforter, one who sets bones', from the root ج ب ر (j-b-r); it is a well-documented male given name borne by Jabir ibn Abd Allah, a companion of the Prophet Muhammad. The source gloss 'The Generous' is unsupported and has been replaced with the lexical sense. Same name as jabeer and jabir."),
 "jabin": ("جبين", "جبین", "جبین", "जबीन", "جبین", "forehead", "Arabic", "Male",
           "Arabic جَبِين (Jabīn)", False, "low",
           "Jabin is recorded at low confidence. The source gave جابين and glossed the name 'Given'; جَبِين (Jabīn) 'forehead' is a documented Arabic word, but the source's form and gloss could not be confirmed. No confident meaning is asserted. Same name as jabeen."),
 "jabir": ("جابر", "جابر", "جابر", "जाबिर", "جابر", "jabir", "Arabic", "Male",
           "Arabic root ج ب ر (j-b-r); جَابِر (Jābir)", False, "high",
           "Jabir is Arabic جَابِر (Jābir) 'comforter, one who sets bones', from the root ج ب ر (j-b-r); it is a well-documented male given name borne by Jabir ibn Abd Allah. The source record was an 8-key stub with no data. Same name as jabeer and jaber."),
 "jabr": ("جبر", "جبر", "جبر", "जब्र", "جبر", "compulsion", "Arabic", "Male",
          "Arabic root ج ب ر (j-b-r); جَبْر (Jabr)", False, "medium",
          "Jabr is Arabic جَبْر (Jabr) 'compulsion, force, coercion', from the root ج ب ر (j-b-r). The source gloss 'Firmness, Compulsion, Determination' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "jabran": ("جبران", "جبران", "جبران", "जब्रान", "جبران", "jabran", "Arabic", "Male",
            "Arabic جَبْرَان (Jabrān)", False, "medium",
            "Jabran is Arabic جَبْرَان (Jabrān), a documented male given name. The source gloss 'Great, Mighty' is unsupported and has been replaced with the proper-name identification."),
 "jabri": ("جبري", "جبری", "جبری", "जबरी", "جبري", "jabri", "Arabic", "Male",
           "Nisba of جَبْر; جَبْرِيّ (Jabriyy)", False, "medium",
           "Jabri is Arabic جَبْرِيّ (Jabriyy), the nisba of جَبْر (Jabr), meaning 'of Jabr; belonging to Jabr'. The source gloss 'Firm, steadfast' is unsupported and has been replaced with the lexical sense."),
 "jabril": ("جبريل", "جبریل", "جبریل", "जिब्रील", "جبریل", "gabriel", "Arabic", "Male",
            "Qur'anic proper name; جِبْرِيل (Jibrīl)", True, "high",
            "Jabril is Arabic جِبْرِيل (Jibrīl), the angel Gabriel, mentioned in the Qur'an. The source gloss 'Gabriel' is consistent."),
 "jad": ("جاد", "جاد", "جاد", "जाद", "جاد", "generous_jad", "Arabic", "Male",
         "Arabic root ج و د (j-w-d); جَاد (Jād)", False, "medium",
         "Jad is Arabic جَاد (Jād) 'generous, bountiful, excellent', from the root ج و د (j-w-d). The source gloss 'Gem' is unsupported and has been replaced with the lexical sense. Same name as jaad."),
 "jada": ("جادة", "جادہ", "جاده", "जाडा", "جاده", "jada", "Arabic", "Female",
          "Arabic جَادَة (Jāda)", False, "low",
          "Jada is recorded at low confidence. The source gave جدة and glossed the name 'Gentle, Fragrant'; جَادَة (Jāda) is a documented female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted."),
 "jadallah": ("جدالله", "جداللہ", "جدالله", "जदअल्लाह", "جدالله", "jadallah", "Arabic", "Male",
              "Compound name; جَدَالله (Jadallāh)", False, "medium",
              "Jadallah is Arabic جَدَالله (Jadallāh), a compound name meaning 'the generosity of God'. CRITICAL SOURCE ERROR: the source gave the broken form جدالل ه and glossed the name 'Gentle, Kind'; the correct form is جَدَالله."),
 "jadida": ("جديدة", "جدیدہ", "جدیده", "जदीदा", "جدیده", "new_fresh", "Arabic", "Female",
            "Arabic root ج د د (j-d-d); جَدِيدَة (Jadīda)", False, "medium",
            "Jadida is Arabic جَدِيدَة (Jadīda) 'new, fresh, recent', from the root ج د د (j-d-d). The source gloss 'New, Fresh' is consistent. Recorded at medium confidence because the word is primarily an adjective."),
 "jadir": ("جادِر", "جادر", "جادر", "जादिर", "جادر", "jadir", "Arabic", "Male",
           "Arabic جَادِر (Jādir)", False, "low",
           "Jadir is recorded at low confidence. The source gave جادر and glossed the name 'Strong, Firm, Victorious'; جَادِر (Jādir) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jafar": ("جعفر", "جعفر", "جعفر", "जाफ़र", "جعفر", "jafar", "Arabic", "Male",
           "Arabic جَعْفَر (Jaʿfar)", False, "high",
           "Jafar is Arabic جَعْفَر (Jaʿfar), a well-documented male given name borne by Ja'far ibn Abi Talib, a companion of the Prophet Muhammad. The source gloss 'Small Stream, Rivulet' is unsupported; the name is a proper name. Same name as jaffar, jaffer and jaafar."),
 "jaffar": ("جعفر", "جعفر", "جعفر", "जाफ़र", "جعفر", "jafar", "Arabic", "Male",
            "Arabic جَعْفَر (Jaʿfar)", False, "high",
            "Jaffar is Arabic جَعْفَر (Jaʿfar), a well-documented male given name. The source gloss 'Friend, companion' is unsupported; the name is a proper name. Same name as jafar, jaffer and jaafar."),
 "jaffer": ("جعفر", "جعفر", "جعفر", "जाफ़र", "جعفر", "jafar", "Arabic", "Male",
            "Arabic جَعْفَر (Jaʿfar)", False, "high",
            "Jaffer is a South Asian transliteration of Arabic جَعْفَر (Jaʿfar), a well-documented male given name. The source gloss 'Stream or River' is unsupported; the name is a proper name. Same name as jafar, jaffar and jaafar."),
 "jafran": ("جفران", "جفران", "جفران", "जफ़रान", "جفران", "jafran", "Arabic", "Male",
            "Arabic جَفْرَان (Jafrān)", False, "low",
            "Jafran is recorded at low confidence. The source gave جفران and glossed the name 'Born from the earth'; جَفْرَان (Jafrān) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jafri": ("جعفري", "جعفری", "جعفری", "जाफ़री", "جعفري", "jafari", "Arabic", "Male",
           "Nisba of جَعْفَر; جَعْفَرِيّ (Jaʿfariyy)", False, "medium",
           "Jafri is Arabic جَعْفَرِيّ (Jaʿfariyy), the nisba of جَعْفَر (Jaʿfar), meaning 'of Ja'far; belonging to Ja'far'. The source gloss 'Pure, Handsome' is unsupported and has been replaced with the lexical sense."),
 "jafur": ("جعفور", "جعفور", "جعفور", "जफ़ूर", "جعفور", "jafur", "Arabic", "Male",
           "Arabic جَعْفُور (Jaʿfūr)", False, "low",
           "Jafur is recorded at low confidence. The source gave جعفور and glossed the name 'Given by God'; جَعْفُور (Jaʿfūr) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jah": ("جاه", "جاہ", "جاه", "जाह", "جاه", "rank_jah", "Arabic", "Male",
         "Arabic root ج و ه (j-w-h); جَاه (Jāh)", False, "low",
         "Jah is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Gift from God'; جَاه (Jāh) 'rank, dignity' is a documented Arabic word, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as jaah."),
 "jahan": ("جهان", "جہان", "جهان", "जहान", "جهان", "world", "Persian", "Male",
           "Persian جهان (jahān)", False, "high",
           "Jahan is Persian جهان (jahān) 'world, universe'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'World, Universe' is consistent."),
 "jahangeer": ("جهانگیر", "جہانگیر", "جهانگیر", "जहाँगीर", "جهانگیر", "world_conqueror", "Persian", "Male",
               "Persian جهانگیر (jahāngīr)", False, "high",
               "Jahangeer is Persian جهانگیر (jahāngīr) 'world-conqueror', a male given name borne by the Mughal emperor Jahangir. CRITICAL SOURCE ERROR: the source gave جہانگیر, using Urdu letters in the Arabic column; the correct Persian form is جهانگیر. MISLABELLED ORIGIN: the source recorded the name as Arabic. Same name as jahangir."),
 "jahangir": ("جهانگیر", "جہانگیر", "جهانگیر", "जहाँगीर", "جهانگیر", "world_conqueror", "Persian", "Male",
              "Persian جهانگیر (jahāngīr)", False, "high",
              "Jahangir is Persian جهانگیر (jahāngīr) 'world-conqueror', a male given name borne by the Mughal emperor Jahangir. CRITICAL SOURCE ERROR: the source gave the broken form جهاؠیر; the correct form is جهانگیر. MISLABELLED ORIGIN: the source recorded the name as Arabic. Same name as jahangeer."),
 "jahanzaib": ("جهانزیب", "جہانزیب", "جهانزیب", "जहाँज़ेब", "جهانزیب", "world_beauty", "Persian", "Male",
               "Persian جهانزیب (jahānzīb)", False, "medium",
               "Jahanzaib is Persian جهانزیب (jahānzīb) 'beauty of the world'. CRITICAL SOURCE ERROR: the source gave جھانزیب, using Urdu letters in the Arabic column; the correct Persian form is جهانزیب. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Victorious, Gift of God' is unsupported and has been replaced with the lexical sense. Same name as jahanzeb."),
 "jahanzeb": ("جهانزیب", "جہانزیب", "جهانزیب", "जहाँज़ेब", "جهانزیب", "world_beauty", "Persian", "Male",
              "Persian جهانزیب (jahānzīb)", False, "medium",
              "Jahanzeb is Persian جهانزیب (jahānzīb) 'beauty of the world'. CRITICAL SOURCE ERROR: the source gave the broken form جَهَانزَب; the correct form is جهانزیب. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Majestic, Generous, Gifted' is unsupported and has been replaced with the lexical sense. Same name as jahanzaib."),
 "jahara": ("جهراء", "جہراء", "جهراء", "जहरा", "جهراء", "jahara", "Arabic", "Female",
            "Arabic جَهْرَاء (Jahrāʾ)", False, "low",
            "Jahara is recorded at low confidence. The source gave the broken form جَهَارَة and glossed the name 'Gift of God'; جَهْرَاء (Jahrāʾ) is a documented female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as jahra."),
 "jaheem": ("جحيم", "جحیم", "جحیم", "जहीम", "جحیم", "hellfire", "Arabic", "Male",
            "Arabic root ج ح م (j-ḥ-m); جَحِيم (Jaḥīm)", False, "medium",
            "Jaheem is Arabic جَحِيم (Jaḥīm) 'hellfire, blazing fire', from the root ج ح م (j-ḥ-m). CRITICAL SOURCE ERROR: the source gave جهيم (a different form) and glossed the name 'Gatherer'; the correct form is جَحِيم. Recorded at medium confidence because the word is primarily a common noun."),
 "jaheer": ("جاهر", "جاہر", "جاهر", "जाहिर", "جاهر", "open_public", "Arabic", "Male",
            "Arabic root ج ه ر (j-h-r); جَاهِر (Jāhir)", False, "medium",
            "Jaheer is Arabic جَاهِر (Jāhir) 'open, public, manifest', from the root ج ه ر (j-h-r). The source gloss 'Hunter' is unsupported and has been replaced with the lexical sense. Same name as jahir."),
 "jahfar": ("جعفر", "جعفر", "جعفر", "जहफ़र", "جعفر", "jafar", "Arabic", "Male",
            "Arabic جَعْفَر (Jaʿfar)", False, "low",
            "Jahfar is recorded at low confidence. The source gave جهفر (a different form) and glossed the name 'Concealer, Protector'; the intended form is likely جَعْفَر (Jaʿfar), but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as jafar, jaffar and jaffer."),
 "jahid": ("جاهد", "جاہد", "جاهد", "जाहिद", "جاهد", "striver", "Arabic", "Male",
           "Arabic root ج ه د (j-h-d); جَاهِد (Jāhid)", False, "high",
           "Jahid is Arabic جَاهِد (Jāhid) 'striver, one who struggles', from the root ج ه د (j-h-d). The source gloss 'Struggler, fighter' is consistent."),
 "jahida": ("جاهدة", "جاہدہ", "جاهده", "जाहिदा", "جاهده", "jahida", "Arabic", "Female",
            "Arabic root ج ه د (j-h-d); جَاهِدَة (Jāhida)", False, "medium",
            "Jahida is Arabic جَاهِدَة (Jāhida) 'female striver', from the root ج ه د (j-h-d). The source gloss 'Guide, Leader' is unsupported and has been replaced with the lexical sense."),
 "jahir": ("جاهر", "جاہر", "جاهر", "जाहिर", "جاهر", "open_public", "Arabic", "Male",
           "Arabic root ج ه ر (j-h-r); جَاهِر (Jāhir)", False, "medium",
           "Jahir is Arabic جَاهِر (Jāhir) 'open, public, manifest', from the root ج ه ر (j-h-r). CRITICAL SOURCE ERROR: the source gave ظاهر (a different name) and glossed the name 'Glory, Radiant'; the correct form is جَاهِر. Same name as jaheer."),
 "jahra": ("جهراء", "جہراء", "جهراء", "जहरा", "جهراء", "jahra", "Arabic", "Female",
           "Arabic جَهْرَاء (Jahrāʾ)", False, "low",
           "Jahra is recorded at low confidence. The source gave the broken form جَحْرَاءَ and glossed the name 'Gardener'; جَهْرَاء (Jahrāʾ) is a documented female given name, but the source's Arabic column and gloss could not be confirmed. No confident meaning is asserted. Same name as jahara."),
 "jaida": ("جيداء", "جیداء", "جیداء", "जैदा", "جیداء", "jaida", "Arabic", "Female",
           "Arabic جَيْدَاء (Jaydāʾ)", False, "medium",
           "Jaida is Arabic جَيْدَاء (Jaydāʾ) 'good, excellent'. CRITICAL SOURCE ERROR: the source gave the broken form جَيْدَاء and glossed the name 'Gentle, beautiful, radiant'; the correct form is جَيْدَاء and the lexical sense is 'good, excellent'."),
 "jair": ("جائر", "جائر", "جائر", "जाइर", "جائر", "jair", "Arabic", "Male",
          "Arabic جَائِر (Jāʾir)", False, "low",
          "Jair is recorded at low confidence. The source gave جائر and glossed the name 'Blessed, Helper'; جَائِر (Jāʾir) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jaish": ("جيش", "جیش", "جیش", "जैश", "جیش", "army", "Arabic", "Male",
           "Arabic root ج ي ش (j-y-sh); جَيْش (Jaysh)", False, "medium",
           "Jaish is Arabic جَيْش (Jaysh) 'army, troops, host', from the root ج ي ش (j-y-sh). The source gloss 'Warrior, Soldier, Army' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "jal": ("جل", "جل", "جل", "जल", "جل", "jal", "Arabic", "Male",
         "Arabic root ج ل ل (j-l-l); جَلّ (Jall)", False, "medium",
         "Jal is Arabic جَلّ (Jall) 'great, majestic', from the root ج ل ل (j-l-l). The source gloss 'Gentle, kind' is unsupported and has been replaced with the lexical sense."),
 "jala": ("جلاء", "جلاء", "جلاء", "जला", "جلاء", "clarity", "Arabic", "Female",
          "Arabic root ج ل و (j-l-w); جَلَاء (Jalāʾ)", False, "medium",
          "Jala is Arabic جَلَاء (Jalāʾ) 'clarity, deliverance, liberation', from the root ج ل و (j-l-w). The source repeated the Latin string in the Arabic column and glossed the name 'Gentle'; the lexical sense is 'clarity, deliverance'. Same name as jalaa."),
 "jalaa": ("جلاء", "جلاء", "جلاء", "जला", "جلاء", "clarity", "Arabic", "Female",
           "Arabic root ج ل و (j-l-w); جَلَاء (Jalāʾ)", False, "medium",
           "Jalaa is Arabic جَلَاء (Jalāʾ) 'clarity, deliverance, liberation', from the root ج ل و (j-l-w). The source gloss 'Deliverance, Liberation, Elevation' is broadly consistent. Same name as jala."),
 "jalal": ("جلال", "جلال", "جلال", "जलाल", "جلال", "majesty", "Arabic", "Male",
           "Arabic root ج ل ل (j-l-l); جَلَال (Jalāl)", False, "high",
           "Jalal is Arabic جَلَال (Jalāl) 'majesty, grandeur, glory', from the root ج ل ل (j-l-l). The source record was an 8-key stub with no data."),
 "jaleel": ("جليل", "جلیل", "جلیل", "जलील", "جلیل", "majestic", "Arabic", "Male",
            "Arabic root ج ل ل (j-l-l); جَلِيل (Jalīl)", False, "high",
            "Jaleel is Arabic جَلِيل (Jalīl) 'majestic, exalted, sublime', from the root ج ل ل (j-l-l). The source gloss 'Majestic, Radiant' is broadly consistent. Same name as jalil."),
 "jaleela": ("جليلة", "جلیلہ", "جلیله", "जलीला", "جلیله", "majestic_f", "Arabic", "Female",
             "Arabic root ج ل ل (j-l-l); جَلِيلَة (Jalīla)", False, "high",
             "Jaleela is Arabic جَلِيلَة (Jalīla) 'majestic, exalted' (feminine), from the root ج ل ل (j-l-l). The source gloss 'Soft, Gentle, Beautiful' is unsupported and has been replaced with the lexical sense. Same name as jalila and jalilah."),
 "jalil": ("جليل", "جلیل", "جلیل", "जलील", "جلیل", "majestic", "Arabic", "Male",
           "Arabic root ج ل ل (j-l-l); جَلِيل (Jalīl)", False, "high",
           "Jalil is Arabic جَلِيل (Jalīl) 'majestic, exalted, sublime', from the root ج ل ل (j-l-l). The source gloss 'Sublime, Exalted' is consistent. Same name as jaleel."),
 "jalila": ("جليلة", "جلیلہ", "جلیله", "जलीला", "جلیله", "majestic_f", "Arabic", "Female",
            "Arabic root ج ل ل (j-l-l); جَلِيلَة (Jalīla)", False, "high",
            "Jalila is Arabic جَلِيلَة (Jalīla) 'majestic, exalted' (feminine), from the root ج ل ل (j-l-l). The source gloss 'Noble and Beautiful' is unsupported and has been replaced with the lexical sense. Same name as jaleela and jalilah."),
 "jalilah": ("جليلة", "جلیلہ", "جلیله", "जलीला", "جلیله", "majestic_f", "Arabic", "Female",
             "Arabic root ج ل ل (j-l-l); جَلِيلَة (Jalīla)", False, "high",
             "Jalilah is Arabic جَلِيلَة (Jalīla) 'majestic, exalted' (feminine), from the root ج ل ل (j-l-l). The source gloss 'Majestic, Exalted' is consistent. Same name as jaleela and jalila."),
 "jamaal": ("جمال", "جمال", "جمال", "जमाल", "جمال", "beauty_jamal", "Arabic", "Male",
            "Arabic root ج م ل (j-m-l); جَمَال (Jamāl)", False, "high",
            "Jamaal is Arabic جَمَال (Jamāl) 'beauty, comeliness, grace', from the root ج م ل (j-m-l). The source gloss 'Adornment' is broadly consistent. Same name as jamal."),
 "jamal": ("جمال", "جمال", "جمال", "जमाल", "جمال", "beauty_jamal", "Arabic", "Male",
           "Arabic root ج م ل (j-m-l); جَمَال (Jamāl)", False, "high",
           "Jamal is Arabic جَمَال (Jamāl) 'beauty, comeliness, grace', from the root ج م ل (j-m-l). The source record was an 8-key stub with no data. Same name as jamaal."),
 "jaman": ("جمان", "جمان", "جمان", "जमान", "جمان", "pearls", "Arabic", "Female",
           "Arabic جُمَان (Jumān)", False, "medium",
           "Jaman is Arabic جُمَان (Jumān) 'pearls, small pearls'. The source gloss 'Morning' is unsupported and has been replaced with the lexical sense. Recorded at medium confidence because the word is primarily a common noun."),
 "jameel": ("جميل", "جمیل", "جمیل", "जमील", "جمیل", "beautiful", "Arabic", "Male",
            "Arabic root ج م ل (j-m-l); جَمِيل (Jamīl)", False, "high",
            "Jameel is Arabic جَمِيل (Jamīl) 'beautiful, handsome, comely', from the root ج م ل (j-m-l). The source gloss 'Beautiful, handsomely adorned' is broadly consistent. Same name as jamil."),
 "jameela": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful_f", "Arabic", "Female",
             "Arabic root ج م ل (j-m-l); جَمِيلَة (Jamīla)", False, "high",
             "Jameela is Arabic جَمِيلَة (Jamīla) 'beautiful, comely' (feminine), from the root ج م ل (j-m-l). CRITICAL SOURCE ERROR: the source gave the junk string 'عربي_Jameela' in the Arabic column and glossed the name 'Noble and blessed'; the correct form is جَمِيلَة. Same name as jameelah, jamilaa, jamilah and jamillah."),
 "jameelah": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful_f", "Arabic", "Female",
              "Arabic root ج م ل (j-m-l); جَمِيلَة (Jamīla)", False, "high",
              "Jameelah is Arabic جَمِيلَة (Jamīla) 'beautiful, comely' (feminine), from the root ج م ل (j-m-l). The source gloss 'Beautiful' is consistent. Same name as jameela, jamilaa, jamilah and jamillah."),
 "jami": ("جامع", "جامع", "جامع", "जामी", "جامع", "gatherer", "Arabic", "Male",
          "Arabic root ج م ع (j-m-ʿ); جَامِع (Jāmiʿ)", False, "medium",
          "Jami is Arabic جَامِع (Jāmiʿ) 'gatherer, collector, unifier', from the root ج م ع (j-m-ʿ). The source gloss 'Beauty' is unsupported and has been replaced with the lexical sense."),
 "jamia": ("جامعة", "جامعہ", "جامعه", "जामिया", "جامعه", "university", "Arabic", "Female",
           "Arabic root ج م ع (j-m-ʿ); جَامِعَة (Jāmiʿa)", False, "medium",
           "Jamia is Arabic جَامِعَة (Jāmiʿa) 'university; gathering, assembly', from the root ج م ع (j-m-ʿ). The source gloss 'Gathering, assembly' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "jamil": ("جميل", "جمیل", "جمیل", "जमील", "جمیل", "beautiful", "Arabic", "Male",
           "Arabic root ج م ل (j-m-l); جَمِيل (Jamīl)", False, "high",
           "Jamil is Arabic جَمِيل (Jamīl) 'beautiful, handsome, comely', from the root ج م ل (j-m-l). The source gloss 'Beautiful, Handsome' is consistent. Same name as jameel."),
 "jamila": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful_f", "Arabic", "Female",
            "Arabic root ج م ل (j-m-l); جَمِيلَة (Jamīla)", False, "high",
            "Jamila is Arabic جَمِيلَة (Jamīla) 'beautiful, comely' (feminine), from the root ج م ل (j-m-l). The source record was an 8-key stub with no data. Same name as jameela, jameelah, jamilaa and jamillah."),
 "jamilaa": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful_f", "Arabic", "Female",
             "Arabic root ج م ل (j-m-l); جَمِيلَة (Jamīla)", False, "high",
             "Jamilaa is Arabic جَمِيلَة (Jamīla) 'beautiful, comely' (feminine), from the root ج م ل (j-m-l). The source gloss 'Beautiful' is consistent. Same name as jameela, jameelah, jamilah and jamillah."),
 "jamilah": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful_f", "Arabic", "Female",
             "Arabic root ج م ل (j-m-l); جَمِيلَة (Jamīla)", False, "high",
             "Jamilah is Arabic جَمِيلَة (Jamīla) 'beautiful, comely' (feminine), from the root ج م ل (j-m-l). The source gloss 'Beautiful' is consistent. Same name as jameela, jameelah, jamilaa and jamillah."),
 "jamillah": ("جميلة", "جمیلہ", "جمیله", "जमीला", "جمیله", "beautiful_f", "Arabic", "Female",
              "Arabic root ج م ل (j-m-l); جَمِيلَة (Jamīla)", False, "high",
              "Jamillah is Arabic جَمِيلَة (Jamīla) 'beautiful, comely' (feminine), from the root ج م ل (j-m-l). The source gloss 'Beautiful, lovely, gracious' is broadly consistent. Same name as jameela, jameelah, jamilaa and jamilah."),
 "jamir": ("جمير", "جمیر", "جمیر", "जमीर", "جمیر", "jamir", "Arabic", "Male",
           "Arabic جَمِير (Jamīr)", False, "low",
           "Jamir is recorded at low confidence. The source gave جمير and glossed the name 'Gatherer, Sustainer'; جَمِير (Jamīr) is a documented male given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jamshaid": ("جمشید", "جمشید", "جمشید", "जमशीद", "جمشید", "jamshid", "Persian", "Male",
              "Persian جمشید (Jamshīd)", False, "high",
              "Jamshaid is Persian جمشید (Jamshīd), a male given name borne by a legendary king in the Shahnameh. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Bright, Shining King' is unsupported and has been replaced with the documented identification. Same name as jamshed, jamsheed and jamshid."),
 "jamshed": ("جمشید", "جمشید", "جمشید", "जमशेद", "جمشید", "jamshid", "Persian", "Male",
             "Persian جمشید (Jamshīd)", False, "high",
             "Jamshed is Persian جمشید (Jamshīd), a male given name borne by a legendary king in the Shahnameh. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'King of Justice' is unsupported and has been replaced with the documented identification. Same name as jamshaid, jamsheed and jamshid."),
 "jamsheed": ("جمشید", "جمشید", "جمشید", "जमशीद", "جمشید", "jamshid", "Persian", "Male",
              "Persian جمشید (Jamshīd)", False, "high",
              "Jamsheed is Persian جمشید (Jamshīd), a male given name borne by a legendary king in the Shahnameh. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'King, Ruler' is unsupported and has been replaced with the documented identification. Same name as jamshaid, jamshed and jamshid."),
 "jamshid": ("جمشید", "جمشید", "جمشید", "जमशीद", "جمشید", "jamshid", "Persian", "Male",
             "Persian جمشید (Jamshīd)", False, "high",
             "Jamshid is Persian جمشید (Jamshīd), a male given name borne by a legendary king in the Shahnameh. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Glory of the Sun' is unsupported and has been replaced with the documented identification. Same name as jamshaid, jamshed and jamsheed."),
 "jan": ("جان", "جان", "جان", "जान", "جان", "soul_life", "Persian", "Male",
         "Persian جان (jān)", False, "high",
         "Jan is Persian جان (jān) 'soul, life, dear one'. MISLABELLED ORIGIN: the source recorded the name as Arabic and repeated the Latin string in the Arabic column. The source gloss 'God is gracious' is unsupported and has been replaced with the Persian lexical sense."),
 "jana": ("جانا", "جانا", "جانا", "जाना", "جانا", "jana", "Arabic", "Female",
          "Arabic جَانَا (Jānā)", False, "low",
          "Jana is recorded at low confidence. The source gave جانا and no meaning; جَانَا (Jānā) is a documented female given name, but no lexical meaning could be confirmed. No confident meaning is asserted."),
 "janaat": ("جنات", "جنات", "جنات", "जन्नात", "جنات", "gardens", "Arabic", "Female",
            "Plural of جَنَّة; جَنَّات (Jannāt)", False, "high",
            "Janaat is Arabic جَنَّات (Jannāt) 'gardens; gardens of paradise', the plural of جَنَّة (janna). The source gloss 'Garden of Paradise' is broadly consistent. Same name as janat and jannat."),
 "janan": ("جنان", "جنان", "جنان", "जनान", "جنان", "hearts", "Arabic", "Female",
           "Arabic جَنَان (Janān)", False, "medium",
           "Janan is Arabic جَنَان (Janān) 'hearts, souls, inner selves'. The source gloss 'Life, Soul' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "janat": ("جنات", "جنات", "جنات", "जन्नत", "جنات", "gardens", "Arabic", "Female",
           "Plural of جَنَّة; جَنَّات (Jannāt)", False, "high",
           "Janat is Arabic جَنَّات (Jannāt) 'gardens; gardens of paradise', the plural of جَنَّة (janna). The source gloss 'Garden of Paradise' is broadly consistent. Same name as janaat and jannat."),
 "janis": ("جانيس", "جانيس", "جانيس", "जानिस", "جانيس", "janis", "Arabic", "Female",
           "Arabic جَانِيس (Jānīs)", False, "low",
           "Janis is recorded at low confidence. The source gave the broken form جَانِيس and glossed the name 'God is merciful'; جَانِيس (Jānīs) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "janna": ("جنة", "جنت", "جنت", "जन्ना", "جنة", "garden_paradise", "Arabic", "Female",
           "Arabic root ج ن ن (j-n-n); جَنَّة (Janna)", False, "high",
           "Janna is Arabic جَنَّة (Janna) 'garden, paradise', from the root ج ن ن (j-n-n). The source gloss 'Garden of Paradise' is consistent. Same name as jannah."),
 "jannah": ("جنة", "جنت", "جنت", "जन्नाह", "جنة", "garden_paradise", "Arabic", "Female",
            "Arabic root ج ن ن (j-n-n); جَنَّة (Janna)", False, "high",
            "Jannah is Arabic جَنَّة (Janna) 'garden, paradise', from the root ج ن ن (j-n-n). The source gloss 'Garden of Paradise' is consistent. Same name as janna."),
 "jannat": ("جنة", "جنت", "جنت", "जन्नत", "جنة", "garden_paradise", "Arabic", "Female",
            "Arabic root ج ن ن (j-n-n); جَنَّة (Janna)", False, "high",
            "Jannat is Arabic جَنَّة (Janna) 'garden, paradise', from the root ج ن ن (j-n-n); the form جَنَّت is the Persian/Urdu rendering. The source record was an 8-key stub with no data. Same name as janna and jannah."),
 "jannatul": ("جنة الـ", "جنت الـ", "جنت الـ", "जन्नतुल", "جنت الـ", "jannatul", "Arabic", "Female",
              "Compound element جنّة الـ (Jannat al-)", False, "low",
              "Jannatul is recorded at low confidence. The source gave جنتول and glossed the name 'Paradise'; the form is a compound element (جنّة الـ, 'the garden of') used in names such as جنة الفردوس, but the source's form and gloss could not be confirmed. No confident meaning is asserted."),
 "jarah": ("جارة", "جارہ", "جاره", "जारा", "جاره", "neighbour_f", "Arabic", "Female",
           "Arabic root ج و ر (j-w-r); جَارَة (Jāra)", False, "medium",
           "Jarah is Arabic جَارَة (Jāra) 'neighbour' (feminine), from the root ج و ر (j-w-r). The source gloss 'Gentle Gardener' is unsupported and has been replaced with the lexical sense."),
 "jaran": ("جاران", "جاران", "جاران", "जारान", "جاران", "jaran", "Arabic", "Male",
           "Arabic جَارَان (Jārān)", False, "low",
           "Jaran is recorded at low confidence. The source gave جاران and glossed the name 'Gentle'; جَارَان (Jārān) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jareer": ("جرير", "جریر", "جریر", "जरीर", "جریر", "jarir", "Arabic", "Male",
            "Arabic جَرِير (Jarīr)", False, "high",
            "Jareer is Arabic جَرِير (Jarīr), a well-documented male given name borne by the poet Jarir ibn Atiyah. The source repeated the Latin string in the Arabic column and glossed the name 'The caller, the one who invites'; the name is a proper name. Same name as jarir."),
 "jari": ("جاري", "جاری", "جاری", "जारी", "جاري", "flowing", "Arabic", "Male",
          "Arabic root ج ر ي (j-r-y); جَارِي (Jārī)", False, "medium",
          "Jari is Arabic جَارِي (Jārī) 'flowing, running, current', from the root ج ر ي (j-r-y). The source gloss 'Gentle, Soft' is unsupported and has been replaced with the lexical sense."),
 "jarir": ("جرير", "جریر", "جریر", "जरीर", "جریر", "jarir", "Arabic", "Male",
           "Arabic جَرِير (Jarīr)", False, "high",
           "Jarir is Arabic جَرِير (Jarīr), a well-documented male given name borne by the poet Jarir ibn Atiyah. The source gloss 'Abundance' is unsupported; the name is a proper name. Same name as jareer."),
 "jaseem": ("جاسم", "جاسم", "جاسم", "जासिम", "جاسم", "jasim", "Arabic", "Male",
            "Arabic جَاسِم (Jāsim)", False, "high",
            "Jaseem is Arabic جَاسِم (Jāsim), a well-documented male given name. The source gloss 'Given by the moon' is unsupported; the name is a proper name. Same name as jasim and jassim."),
 "jaseena": ("جاسينا", "جاسینا", "جاسینا", "जसीना", "جاسینا", "jaseena", "Arabic", "Female",
             "Arabic جَاسِينَا (Jāsīnā)", False, "low",
             "Jaseena is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Gentle, Gracious'; جَاسِينَا (Jāsīnā) is a documented female given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jaseer": ("جاسر", "جاسر", "جاسر", "जासिर", "جاسر", "bold", "Arabic", "Male",
            "Arabic root ج س ر (j-s-r); جَاسِر (Jāsir)", False, "medium",
            "Jaseer is Arabic جَاسِر (Jāsir) 'bold, daring, courageous', from the root ج س ر (j-s-r). The source gloss 'Helpful' is unsupported and has been replaced with the lexical sense. Same name as jaser and jasir."),
 "jaser": ("جاسر", "جاسر", "جاسر", "जासेर", "جاسر", "bold", "Arabic", "Male",
           "Arabic root ج س ر (j-s-r); جَاسِر (Jāsir)", False, "medium",
           "Jaser is Arabic جَاسِر (Jāsir) 'bold, daring, courageous', from the root ج س ر (j-s-r). The source gloss 'Healer, Helper' is unsupported and has been replaced with the lexical sense. Same name as jaseer and jasir."),
 "jashan": ("جشن", "جشن", "جشن", "जश्न", "جشن", "jashan", "Persian", "Male",
            "Persian جشن (jashn)", False, "medium",
            "Jashan is Persian جشن (jashn) 'celebration, festival'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Feast, celebration' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "jasim": ("جاسم", "جاسم", "جاسم", "जासिम", "جاسم", "jasim", "Arabic", "Male",
           "Arabic جَاسِم (Jāsim)", False, "high",
           "Jasim is Arabic جَاسِم (Jāsim), a well-documented male given name. The source gloss 'Strong, Powerful' is unsupported; the name is a proper name. Same name as jaseem and jassim."),
 "jasir": ("جاسر", "جاسر", "جاسر", "जासिर", "جاسر", "bold", "Arabic", "Male",
           "Arabic root ج س ر (j-s-r); جَاسِر (Jāsir)", False, "medium",
           "Jasir is Arabic جَاسِر (Jāsir) 'bold, daring, courageous', from the root ج س ر (j-s-r). The source gloss 'Firm, Steadfast' is unsupported and has been replaced with the lexical sense. Same name as jaseer and jaser."),
 "jasmina": ("ياسمين", "یاسمین", "یاسمین", "जास्मिना", "یاسمین", "jasmine", "Arabic", "Female",
             "Arabic يَاسْمِين (Yāsmīn)", False, "high",
             "Jasmina is Arabic يَاسْمِين (Yāsmīn) 'jasmine; the jasmine flower'. The source gloss 'Jasmine flower' is consistent."),
 "jassim": ("جاسم", "جاسم", "جاسم", "जासिम", "جاسم", "jasim", "Arabic", "Male",
            "Arabic جَاسِم (Jāsim)", False, "high",
            "Jassim is Arabic جَاسِم (Jāsim), a well-documented male given name. The source repeated the Latin string in the Arabic column and glossed the name 'Strong and Just'; the name is a proper name. Same name as jaseem and jasim."),
 "jasur": ("جسور", "جسور", "جسور", "जसूर", "جسور", "bold", "Arabic", "Male",
           "Arabic root ج س ر (j-s-r); جَسُور (Jasūr)", False, "medium",
           "Jasur is Arabic جَسُور (Jasūr) 'bold, daring, courageous', from the root ج س ر (j-s-r). The source gloss \"God's helper\" is unsupported and has been replaced with the lexical sense."),
 "jauhar": ("جوهر", "جوہر", "جوهر", "जौहर", "جوهر", "jauhar", "Arabic", "Male",
            "Arabic root ج و ه ر (j-w-h-r); جَوْهَر (Jawhar)", False, "high",
            "Jauhar is Arabic جَوْهَر (Jawhar) 'jewel, essence, substance', from the root ج و ه ر (j-w-h-r). The source gloss 'Glowing, Radiant' is unsupported and has been replaced with the lexical sense. Same name as jawaahir."),
 "jaun": ("جون", "جون", "جون", "जौन", "جون", "jaun", "Arabic", "Male",
          "Arabic جَوْن (Jawn)", False, "low",
          "Jaun is recorded at low confidence. The source gave جون and glossed the name 'Yellow'; جَوْن (Jawn) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "javan": ("جوان", "جوان", "جوان", "जवान", "جوان", "young", "Persian", "Male",
           "Persian جوان (javān)", False, "medium",
           "Javan is Persian جوان (javān) 'young, youthful'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Golden, Yellow' is unsupported and has been replaced with the Persian lexical sense. Recorded at medium confidence because the word is primarily an adjective."),
 "javeed": ("جاوید", "جاوید", "جاوید", "जावेद", "جاوید", "eternal", "Persian", "Male",
            "Persian جاوید (jāvīd)", False, "high",
            "Javeed is Persian جاوید (jāvīd) 'eternal, everlasting'. MISLABELLED ORIGIN: the source recorded the name as Arabic. The source gloss 'Jewel, Precious' is unsupported and has been replaced with the Persian lexical sense."),
 "javeria": ("جویریه", "جویریہ", "جویریه", "जुवैरिया", "جویریه", "juwayriyya", "Arabic", "Female",
             "Arabic جُوَيْرِيَّة (Juwayriyya)", False, "high",
             "Javeria is Arabic جُوَيْرِيَّة (Juwayriyya), a well-documented female given name borne by Juwayriyya bint al-Harith, a wife of the Prophet Muhammad. The source gloss 'Radiant, Shining Light' is unsupported; the name is a proper name."),
 "javier": ("خافيير", "جیویر", "خاویر", "हावियेर", "جاویر", "javier", "Spanish", "Male",
            "Spanish Javier", False, "low",
            "Javier is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Javier'; Javier is a Spanish male given name, but no lexical meaning could be confirmed. MISLABELLED ORIGIN: the source recorded the name as Arabic. No confident meaning is asserted."),
 "jawa": ("جوا", "جوا", "جوا", "जवा", "جوا", "jawa", "Arabic", "Male",
          "Arabic جَوَا (Jawā)", False, "low",
          "Jawa is recorded at low confidence. The source repeated the Latin string in the Arabic column and glossed the name 'Youth, Vigor'; جَوَا (Jawā) is a documented given name, but the source gloss could not be confirmed. No confident meaning is asserted."),
 "jawaad": ("جواد", "جواد", "جواد", "जवाद", "جواد", "generous_jawad", "Arabic", "Male",
            "Arabic root ج و د (j-w-d); جَوَاد (Jawād)", False, "high",
            "Jawaad is Arabic جَوَاد (Jawād) 'generous, noble, open-handed', from the root ج و د (j-w-d). CRITICAL SOURCE ERROR: the source gave the broken form جوااد and glossed the name 'Gentle, Kind, Honest'; the correct form is جَوَاد. Same name as jawad."),
 "jawaahir": ("جواهر", "جواہر", "جواهر", "जवाहर", "جواهر", "jewels", "Arabic", "Male",
              "Plural of جَوْهَر; جَوَاهِر (Jawāhir)", False, "high",
              "Jawaahir is Arabic جَوَاهِر (Jawāhir) 'jewels, gems, precious stones', the plural of جَوْهَر (jawhar). The source gloss 'Gems, Jewels' is consistent. Same name as jauhar."),
 "jawad": ("جواد", "جواد", "جواد", "जवाद", "جواد", "generous_jawad", "Arabic", "Male",
           "Arabic root ج و د (j-w-d); جَوَاد (Jawād)", False, "high",
           "Jawad is Arabic جَوَاد (Jawād) 'generous, noble, open-handed', from the root ج و د (j-w-d). The source gloss 'Generous, Noble' is consistent. Same name as jawaad."),
 "jawadi": ("جوادي", "جوادی", "جوادی", "जवादी", "جوادي", "jawadi", "Arabic", "Male",
            "Nisba of جَوَاد; جَوَادِيّ (Jawādiyy)", False, "medium",
            "Jawadi is Arabic جَوَادِيّ (Jawādiyy), the nisba of جَوَاد (Jawād), meaning 'of Jawad; belonging to Jawad'. The source gloss 'Eternal, Everlasting' is unsupported and has been replaced with the lexical sense."),
}
