# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 52 (ramadan..raz).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": rambod -> Latin "Rambod";
   rameez -> empty; ramez -> "عربي_Ramez" (placeholder prefix); rami -> empty;
   ramish -> علي; ramza -> علي; rana -> empty; rand -> Latin "Rand";
   randah -> عائشة; rane -> علي; raneem -> empty; rania -> empty;
   ranin -> عائشة; rasha -> empty; rashaa -> Latin "Rashaa";
   rashid -> empty; rasima -> "Razan" (different name); raunak -> "Ali";
   ravan -> Latin "Ravan"; rawa -> Latin "Rawa"; rawan -> empty;
   rayan -> "RAYAN"; rayhan -> "عربي_Rayhan" (placeholder prefix);
   rayyan -> empty; ramadan -> رمضان; ramadhan -> رمضان; ramazan -> رمضان;
   ramzan -> رمضان; ramin -> رامين; ramina -> رامينا; ramir -> رَمِير;
   ramiya -> رامية; ramiz -> رامز; ramiza -> رميزة; ramla -> رملة;
   ramlah -> رَمَلَة; ramlat -> رملة; ramsha -> رَمْشَة; ramz -> رمز;
   ramzi -> رَمْزِي; ramzia -> رمضية; ranaa -> رنا; raniah -> رانية;
   ranim -> رانيم; raniya -> رانيا; ranya -> رانيا; raoof -> رؤوف;
   raouf -> رَأوف; raqeeb -> رَقِيب; raqib -> رَقِيب; rasa -> رسا;
   rashad -> رشاد; rashawn -> راشون; rashda -> رشدة; rashdan -> رشدان;
   rashed -> راشد; rasheed -> رشيد; rasheeda -> رشيدة; rasheedah -> راشدة;
   rashida -> رشيدة; rashidah -> راشدة; rashidat -> رشيدات; rasif -> راسف;
   rasil -> راسل; rasim -> راسيم; rasin -> راسين; rasool -> رسول;
   rasul -> رَسُول; rasyid -> رشيد; ratib -> رتب; ratiba -> رتبة;
   raudah -> رَوْضَة; raudhah -> رَوْضَة; raufa -> رؤفة; raushan -> روشن;
   rawaa -> رَوَاءَة; rawah -> رَوَاحَ; rawda -> روضة; rawdah -> روضة;
   rawdha -> روضة; rawia -> روية; rawiya -> راوية; rawya -> روية;
   raya -> راية; rayaan -> ريان; rayah -> راية; rayana -> ريانة;
   rayann -> ريان; rayees -> رايس; rayhaan -> ريحان; rayhanat -> ريحانة;
   rayn -> رين; rayna -> رينا; rayya -> رَيَّا; raz -> راز.
 * EMPTY STUBS (8-key records, no data): rameez, rami, rana, raneem, rania,
   rasha, rashid, rawan, rayyan.
 * MISLABELLED ORIGIN: rambod (Persian), ramin (Persian), ravan (Persian),
   raunak (Hindi/Urdu), rasim (Turkish), rand (English), raja-like raunak.
 * DEGARBLED GLOSSES: ramadan "Month of fasting", ramadhan "The Ninth Month",
   raman "A radiant light", ramazan "Month of Fasting", rambod "Royal",
   rameen "Joyful, Obedient, Rescuer", rameesh "One who is gentle and kind",
   rameez "Noble and blessed", ramez "Noble and blessed", ramia "Pomegranate",
   ramiar "High, Sublime", ramin "lover, friend", ramina "Joyful",
   ramir "High, Exalted", ramish "Rainy", ramiya "Beautiful, Graceful",
   ramiz "Exalted, Noble, Precious", ramiza "Jasmine", ramla "Small valley",
   ramlah "Palmyra", ramlat "Desert", ramsha "Fragrance, Light, Beauty",
   ramz "Exalted One", ramza "Jasmine", ramzan "Month of fasting",
   ramzi "Rare, Precious", ramzia "Exalted One", ranaa "Moon",
   rand "Little One, Small One", randah "Contentment", rane "crow",
   raniah "Content, Happy, Peaceful", ranim "Jasmine", ranin "Jasmine flower",
   raniya "Joyful One", ranya "Jasmine", raoof "High, Noble", raouf "Radiant",
   raqeeb "Watchman", raqib "Watcher", rasa "Taste, Love, Sweetness",
   rashaa "Contentment, satisfaction", rashad "Rightly guided",
   rashawn "Rightly guided", rashda "Rightly Guided One",
   rashdan "Powerful, Wise", rashed "Righteous Guide",
   rasheed "Guided, Rightly Guided", rasheeda "Head of the good or righteous",
   rasheedah "Rightly Guided", rashida "Rightly Guided",
   rashidah "Rightly Guided", rashidat "Rightly Guided",
   rasif "Wise, Knowledgeable", rasil "Messenger, Emissary",
   rasim "Contentment", rasima "Moon", rasin "Pomegranate",
   rasool "Messenger", rasul "Messenger", rasyid "Owner, master, possessor",
   ratib "One who is grateful", ratiba "Progress, Steps",
   raudah "Garden of Paradise", raudhah "Garden of Paradise", raufa "Exalted",
   raunak "Joy", raushan "Illuminated, Enlightened", ravan "Sky, Heaven",
   rawa "Flowing river", rawaa "Contentment, satisfaction",
   rawah "Guide, gentle one", rawda "garden", rawdah "Garden", rawdha "Garden",
   rawia "Joyful", rawiya "Reader, Scholar", rawya "Gently flowing stream",
   raya "Joy, happiness, brightness", rayaan "Watered, Luxuriant",
   rayah "contentment, joy", rayan "River of life, flowing water, or abundant",
   rayana "Filled with knowledge and wisdom", rayann "Mountain of joy",
   rayees "Guardian, Protector", rayhaan "Fragrant, Sweet Scent",
   rayhan "Noble and blessed", rayhanat "Fragrant flowers", rayn "rain",
   rayna "Joy, contentment", rayya "Content, Satisfied, Joyful",
   raz "Secret, Mystery".
 * GENDER ERRORS: ramadan, rameen, ramiya, rand, rane, rasa, rasin, raushan,
   rayan, rayann, rayn were labelled unisex where documented usage is male or
   female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated51 import GLOSSES as _G51

GLOSSES = dict(_G51)
GLOSSES.update({
    "ramadan": {"en": "Ramadan; the ninth Islamic month of fasting", "ur": "رمضان، روزوں کا مہینہ", "fa": "رمضان، ماه روزه", "hi": "रमज़ान, रोज़े का महीना", "ps": "رمضان، د روژې میاشت", "ar": "رَمَضَان (شَهْر هِجْرِيّ)"},
    "ramadhan": {"en": "Ramadhan; the ninth Islamic month of fasting", "ur": "رمضان، روزوں کا مہینہ", "fa": "رمضان، ماه روزه", "hi": "रमज़ान, रोज़े का महीना", "ps": "رمضان، د روژې میاشت", "ar": "رَمَضَان (شَهْر هِجْرِيّ)"},
    "raman": {"en": "Raman; a male given name", "ur": "رمن (مردانہ نام)", "fa": "رمن (نام مردانه)", "hi": "रमन (पुरुष नाम)", "ps": "رمن (نر نوم)", "ar": "رَمَان (اسْم عَلَم مُذَكَّر)"},
    "ramazan": {"en": "Ramazan; Ramadan (Turkish/Persian form)", "ur": "رمضان، روزوں کا مہینہ", "fa": "رمضان، ماه روزه", "hi": "रमज़ान, रोज़े का महीना", "ps": "رمضان، د روژې میاشت", "ar": "رَمَضَان (شَهْر هِجْرِيّ)"},
    "rambod": {"en": "Rambod; a male given name (Persian)", "ur": "رمبود (مردانہ نام)", "fa": "رمبود (نام مردانه)", "hi": "रम्बोद (पुरुष नाम)", "ps": "رمبود (نر نوم)", "ar": "رَمْبُود (اسْم عَلَم فَارِسِيّ)"},
    "rameen": {"en": "Rameen; a female given name", "ur": "رامین (زنانہ نام)", "fa": "رامین (نام زنانه)", "hi": "रामीन (स्त्री नाम)", "ps": "رامین (ښځينه نوم)", "ar": "رَامِين (اسْم عَلَم مُؤَنَّث)"},
    "rameesh": {"en": "Rameesh; a male given name", "ur": "رمیش (مردانہ نام)", "fa": "رمیش (نام مردانه)", "hi": "रमीश (पुरुष नाम)", "ps": "رمیش (نر نوم)", "ar": "رَمِيش (اسْم عَلَم مُذَكَّر)"},
    "rameez": {"en": "Rameez; a male given name", "ur": "رمیز (مردانہ نام)", "fa": "رمیز (نام مردانه)", "hi": "रमीज़ (पुरुष नाम)", "ps": "رمیز (نر نوم)", "ar": "رَمِيز (اسْم عَلَم مُذَكَّر)"},
    "ramez": {"en": "Ramez; a male given name", "ur": "رامز (مردانہ نام)", "fa": "رامز (نام مردانه)", "hi": "रामेज़ (पुरुष नाम)", "ps": "رامز (نر نوم)", "ar": "رَامِز (اسْم عَلَم مُذَكَّر)"},
    "rami": {"en": "Rami; thrower, archer", "ur": "رامی، تیر انداز", "fa": "رامی، تیرانداز", "hi": "रामी, धनुर्धर", "ps": "رامي، غشي ويشتونکی", "ar": "الرَّامِي، رَامِي السِّهَام"},
    "ramia": {"en": "Ramia; thrower, archer (feminine)", "ur": "رامیہ، تیر انداز", "fa": "رامیه، تیرانداز", "hi": "रामिया, धनुर्धर", "ps": "رامیه، غشي ويشتونکې", "ar": "رَامِيَة، الرَّامِيَة"},
    "ramiar": {"en": "Ramiar; a male given name", "ur": "رمیار (مردانہ نام)", "fa": "رمیار (نام مردانه)", "hi": "रमियार (पुरुष नाम)", "ps": "رمیار (نر نوم)", "ar": "رَمْيَار (اسْم عَلَم مُذَكَّر)"},
    "ramin": {"en": "Ramin; a male given name (Persian)", "ur": "رامین (مردانہ نام)", "fa": "رامین (نام مردانه)", "hi": "रामिन (पुरुष नाम)", "ps": "رامین (نر نوم)", "ar": "رَامِين (اسْم عَلَم فَارِسِيّ)"},
    "ramina": {"en": "Ramina; a female given name", "ur": "رامینہ (زنانہ نام)", "fa": "رامینا (نام زنانه)", "hi": "रामीना (स्त्री नाम)", "ps": "رامینا (ښځينه نوم)", "ar": "رَامِينَا (اسْم عَلَم مُؤَنَّث)"},
    "ramir": {"en": "Ramir; a male given name", "ur": "رمیر (مردانہ نام)", "fa": "رمیر (نام مردانه)", "hi": "रमीर (पुरुष नाम)", "ps": "رمیر (نر نوم)", "ar": "رَمِير (اسْم عَلَم مُذَكَّر)"},
    "ramish": {"en": "Ramish; a male given name", "ur": "رمیش (مردانہ نام)", "fa": "رمیش (نام مردانه)", "hi": "रमीश (पुरुष नाम)", "ps": "رمیش (نر نوم)", "ar": "رَمِيش (اسْم عَلَم مُذَكَّر)"},
    "ramiya": {"en": "Ramiya; thrower, archer (feminine)", "ur": "رامیہ، تیر انداز", "fa": "رامیه، تیرانداز", "hi": "रामिया, धनुर्धर", "ps": "رامیه، غشي ويشتونکې", "ar": "رَامِيَة، الرَّامِيَة"},
    "ramiz": {"en": "Ramiz; a male given name", "ur": "رامز (مردانہ نام)", "fa": "رامز (نام مردانه)", "hi": "रामिज़ (पुरुष नाम)", "ps": "رامز (نر نوم)", "ar": "رَامِز (اسْم عَلَم مُذَكَّر)"},
    "ramiza": {"en": "Ramiza; a female given name", "ur": "رمیزہ (زنانہ نام)", "fa": "رمیزه (نام زنانه)", "hi": "रमीज़ा (स्त्री नाम)", "ps": "رمیزه (ښځينه نوم)", "ar": "رَمِيزَة (اسْم عَلَم مُؤَنَّث)"},
    "ramla": {"en": "Ramla; sand (feminine)", "ur": "رملہ، ریت", "fa": "رمله، ریگ", "hi": "रमला, रेत", "ps": "رمله، شګه", "ar": "رَمْلَة، الرَّمْل"},
    "ramlah": {"en": "Ramlah; sand (feminine)", "ur": "رملہ، ریت", "fa": "رمله، ریگ", "hi": "रमला, रेत", "ps": "رمله، شګه", "ar": "رَمْلَة، الرَّمْل"},
    "ramlat": {"en": "Ramlat; sand (feminine)", "ur": "رملت، ریت", "fa": "رملت، ریگ", "hi": "रमलत, रेत", "ps": "رملت، شګه", "ar": "رَمْلَة، الرَّمْل"},
    "ramsha": {"en": "Ramsha; a female given name", "ur": "رمشہ (زنانہ نام)", "fa": "رمشه (نام زنانه)", "hi": "रमशा (स्त्री नाम)", "ps": "رمشه (ښځينه نوم)", "ar": "رَمْشَة (اسْم عَلَم مُؤَنَّث)"},
    "ramz": {"en": "Ramz; sign, symbol", "ur": "رمز، نشان، اشارہ", "fa": "رمز، نشانه", "hi": "रम्ज़, संकेत", "ps": "رمز، نښه", "ar": "الرَّمْز، الْإِشَارَة"},
    "ramza": {"en": "Ramza; a female given name", "ur": "رمزہ (زنانہ نام)", "fa": "رمزه (نام زنانه)", "hi": "रमज़ा (स्त्री नाम)", "ps": "رمزه (ښځينه نوم)", "ar": "رَمْزَة (اسْم عَلَم مُؤَنَّث)"},
    "ramzan": {"en": "Ramzan; Ramadan (South Asian form)", "ur": "رمضان، روزوں کا مہینہ", "fa": "رمضان، ماه روزه", "hi": "रमज़ान, रोज़े का महीना", "ps": "رمضان، د روژې میاشت", "ar": "رَمَضَان (شَهْر هِجْرِيّ)"},
    "ramzi": {"en": "Ramzi; symbolic, of the sign", "ur": "رمزی، علامتی", "fa": "رمزی، نمادین", "hi": "रमज़ी, प्रतीकात्मक", "ps": "رمزي، سمبوليک", "ar": "الرَّمْزِي، مَنْسُوب إِلَى الرَّمْز"},
    "ramzia": {"en": "Ramzia; a female given name", "ur": "رمزیہ (زنانہ نام)", "fa": "رمضیه (نام زنانه)", "hi": "रमज़िया (स्त्री नाम)", "ps": "رمضیه (ښځينه نوم)", "ar": "رَمْضِيَة (اسْم عَلَم مُؤَنَّث)"},
    "rana": {"en": "Rana; a female given name", "ur": "رنا (زنانہ نام)", "fa": "رنا (نام زنانه)", "hi": "रना (स्त्री नाम)", "ps": "رنا (ښځينه نوم)", "ar": "رَنَا (اسْم عَلَم مُؤَنَّث)"},
    "ranaa": {"en": "Ranaa; a female given name", "ur": "رنا (زنانہ نام)", "fa": "رنا (نام زنانه)", "hi": "रना (स्त्री नाम)", "ps": "رنا (ښځينه نوم)", "ar": "رَنَا (اسْم عَلَم مُؤَنَّث)"},
    "rand": {"en": "Rand; a female given name", "ur": "رند (زنانہ نام)", "fa": "رند (نام زنانه)", "hi": "रंद (स्त्री नाम)", "ps": "رند (ښځينه نوم)", "ar": "رَنْد (اسْم عَلَم مُؤَنَّث)"},
    "randah": {"en": "Randah; a female given name", "ur": "رندہ (زنانہ نام)", "fa": "رنده (نام زنانه)", "hi": "रंदा (स्त्री नाम)", "ps": "رنده (ښځينه نوم)", "ar": "رَنْدَة (اسْم عَلَم مُؤَنَّث)"},
    "rane": {"en": "Rane; a female given name", "ur": "رانے (زنانہ نام)", "fa": "رانه (نام زنانه)", "hi": "राने (स्त्री नाम)", "ps": "رانه (ښځينه نوم)", "ar": "رَانَة (اسْم عَلَم مُؤَنَّث)"},
    "raneem": {"en": "Raneem; a female given name", "ur": "رنیم (زنانہ نام)", "fa": "رنیم (نام زنانه)", "hi": "रनीम (स्त्री नाम)", "ps": "رنیم (ښځينه نوم)", "ar": "رَنِيم (اسْم عَلَم مُؤَنَّث)"},
    "rania": {"en": "Rania; a female given name", "ur": "رانیہ (زنانہ نام)", "fa": "رانیا (نام زنانه)", "hi": "रानिया (स्त्री नाम)", "ps": "رانیا (ښځينه نوم)", "ar": "رَانِيَة (اسْم عَلَم مُؤَنَّث)"},
    "raniah": {"en": "Raniah; a female given name", "ur": "رانیہ (زنانہ نام)", "fa": "رانیه (نام زنانه)", "hi": "रानिया (स्त्री नाम)", "ps": "رانیه (ښځينه نوم)", "ar": "رَانِيَة (اسْم عَلَم مُؤَنَّث)"},
    "ranim": {"en": "Ranim; a female given name", "ur": "رانیم (زنانہ نام)", "fa": "رانیم (نام زنانه)", "hi": "रानीम (स्त्री नाम)", "ps": "رانیم (ښځينه نوم)", "ar": "رَانِيم (اسْم عَلَم مُؤَنَّث)"},
    "ranin": {"en": "Ranin; a female given name", "ur": "رنین (زنانہ نام)", "fa": "رنین (نام زنانه)", "hi": "रनीन (स्त्री नाम)", "ps": "رنین (ښځينه نوم)", "ar": "رَنِين (اسْم عَلَم مُؤَنَّث)"},
    "raniya": {"en": "Raniya; a female given name", "ur": "رانیہ (زنانہ نام)", "fa": "رانیا (نام زنانه)", "hi": "रानिया (स्त्री नाम)", "ps": "رانیا (ښځينه نوم)", "ar": "رَانِيَة (اسْم عَلَم مُؤَنَّث)"},
    "ranya": {"en": "Ranya; a female given name", "ur": "رانیہ (زنانہ نام)", "fa": "رانیا (نام زنانه)", "hi": "रान्या (स्त्री नाम)", "ps": "رانیا (ښځينه نوم)", "ar": "رَانِيَة (اسْم عَلَم مُؤَنَّث)"},
    "raoof": {"en": "Raoof; compassionate, kind", "ur": "رؤف، مہربان", "fa": "رئوف، مهربان", "hi": "रऊफ़, दयालु", "ps": "رئوف، مهربان", "ar": "الرَّءُوف، الرَّحِيم"},
    "raouf": {"en": "Raouf; compassionate, kind", "ur": "رؤف، مہربان", "fa": "رئوف، مهربان", "hi": "रऊफ़, दयालु", "ps": "رئوف، مهربان", "ar": "الرَّءُوف، الرَّحِيم"},
    "raqeeb": {"en": "Raqeeb; watcher, guardian", "ur": "رقیب، نگہبان", "fa": "رقیب، نگهبان", "hi": "रक़ीब, रक्षक", "ps": "رقیب، ساتونکی", "ar": "الرَّقِيب، الْحَافِظ"},
    "raqib": {"en": "Raqib; watcher, guardian", "ur": "رقیب، نگہبان", "fa": "رقیب، نگهبان", "hi": "रक़ीब, रक्षक", "ps": "رقیب، ساتونکی", "ar": "الرَّقِيب، الْحَافِظ"},
    "rasa": {"en": "Rasa; a female given name", "ur": "رسا (زنانہ نام)", "fa": "رسا (نام زنانه)", "hi": "रसा (स्त्री नाम)", "ps": "رسا (ښځينه نوم)", "ar": "رَسَا (اسْم عَلَم مُؤَنَّث)"},
    "rasha": {"en": "Rasha; a female given name", "ur": "رشا (زنانہ نام)", "fa": "رشا (نام زنانه)", "hi": "रशा (स्त्री नाम)", "ps": "رشا (ښځينه نوم)", "ar": "رَشَا (اسْم عَلَم مُؤَنَّث)"},
    "rashaa": {"en": "Rashaa; a female given name", "ur": "رشا (زنانہ نام)", "fa": "رشا (نام زنانه)", "hi": "रशा (स्त्री नाम)", "ps": "رشا (ښځينه نوم)", "ar": "رَشَا (اسْم عَلَم مُؤَنَّث)"},
    "rashad": {"en": "Rashad; right guidance", "ur": "رشاد، ہدایت", "fa": "رشاد، هدایت", "hi": "रशाद, मार्गदर्शन", "ps": "رشاد، لارښوونه", "ar": "الرَّشَاد، الْهُدَى"},
    "rashawn": {"en": "Rashawn; a male given name", "ur": "راشون (مردانہ نام)", "fa": "راشون (نام مردانه)", "hi": "राशॉन (पुरुष नाम)", "ps": "راشون (نر نوم)", "ar": "رَاشُون (اسْم عَلَم مُذَكَّر)"},
    "rashda": {"en": "Rashda; right guidance (feminine)", "ur": "رشدہ، ہدایت یافتہ", "fa": "رشده، هدایت‌یافته", "hi": "रशदा, सन्मार्गी", "ps": "رشده، سم لارښوده", "ar": "رَشْدَة، الرَّاشِدَة"},
    "rashdan": {"en": "Rashdan; right guidance", "ur": "رشدان، ہدایت", "fa": "رشدان، هدایت", "hi": "रशदान, मार्गदर्शन", "ps": "رشدان، لارښوونه", "ar": "الرَّشْدَان، الرَّشَاد"},
    "rashed": {"en": "Rashed; rightly guided", "ur": "راشد، ہدایت یافتہ", "fa": "راشد، هدایت‌یافته", "hi": "राशिद, सन्मार्गी", "ps": "راشد، سم لارښود", "ar": "الرَّاشِد، الْمُهْتَدِي"},
    "rasheed": {"en": "Rasheed; rightly guided", "ur": "رشید، ہدایت یافتہ", "fa": "رشید، هدایت‌یافته", "hi": "रशीद, सन्मार्गी", "ps": "رشید، سم لارښود", "ar": "الرَّشِيد، الْمُهْتَدِي"},
    "rasheeda": {"en": "Rasheeda; rightly guided (feminine)", "ur": "رشیدہ، ہدایت یافتہ", "fa": "رشیده، هدایت‌یافته", "hi": "रशीदा, सन्मार्गी", "ps": "رشیده، سم لارښوده", "ar": "رَشِيدَة، الرَّاشِدَة"},
    "rasheedah": {"en": "Rasheedah; rightly guided (feminine)", "ur": "رشیدہ، ہدایت یافتہ", "fa": "رشیده، هدایت‌یافته", "hi": "रशीदा, सन्मार्गी", "ps": "رشیده، سم لارښوده", "ar": "رَشِيدَة، الرَّاشِدَة"},
    "rashid": {"en": "Rashid; rightly guided", "ur": "راشد، ہدایت یافتہ", "fa": "راشد، هدایت‌یافته", "hi": "राशिद, सन्मार्गी", "ps": "راشد، سم لارښود", "ar": "الرَّاشِد، الْمُهْتَدِي"},
    "rashida": {"en": "Rashida; rightly guided (feminine)", "ur": "رشیدہ، ہدایت یافتہ", "fa": "رشیده، هدایت‌یافته", "hi": "रशीदा, सन्मार्गी", "ps": "رشیده، سم لارښوده", "ar": "رَشِيدَة، الرَّاشِدَة"},
    "rashidah": {"en": "Rashidah; rightly guided (feminine)", "ur": "رشیدہ، ہدایت یافتہ", "fa": "رشیده، هدایت‌یافته", "hi": "रशीदा, सन्मार्गी", "ps": "رشیده، سم لارښوده", "ar": "رَشِيدَة، الرَّاشِدَة"},
    "rashidat": {"en": "Rashidat; rightly guided (feminine)", "ur": "رشیدات، ہدایت یافتہ", "fa": "رشیدات، هدایت‌یافته", "hi": "रशीदात, सन्मार्गी", "ps": "رشیدات، سم لارښوده", "ar": "رَشِيدَات، الرَّاشِدَات"},
    "rasif": {"en": "Rasif; a male given name", "ur": "راسف (مردانہ نام)", "fa": "راسف (نام مردانه)", "hi": "रासिफ़ (पुरुष नाम)", "ps": "راسف (نر نوم)", "ar": "رَاسِف (اسْم عَلَم مُذَكَّر)"},
    "rasil": {"en": "Rasil; messenger, emissary", "ur": "رسل، پیغام رساں", "fa": "رسل، پیام‌آور", "hi": "रसील, संदेशवाहक", "ps": "رسل، پیغام رسول", "ar": "الرَّسِيل، الرَّسُول"},
    "rasim": {"en": "Rasim; a male given name (Turkish)", "ur": "راسم (مردانہ نام)", "fa": "راسم (نام مردانه)", "hi": "रासिम (पुरुष नाम)", "ps": "راسم (نر نوم)", "ar": "رَاسِم (اسْم عَلَم تُرْكِيّ)"},
    "rasima": {"en": "Rasima; a female given name", "ur": "راسمہ (زنانہ نام)", "fa": "راسما (نام زنانه)", "hi": "रासिमा (स्त्री नाम)", "ps": "راسما (ښځينه نوم)", "ar": "رَاسِمَة (اسْم عَلَم مُؤَنَّث)"},
    "rasin": {"en": "Rasin; a male given name", "ur": "راسین (مردانہ نام)", "fa": "راسین (نام مردانه)", "hi": "रासीन (पुरुष नाम)", "ps": "راسین (نر نوم)", "ar": "رَاسِين (اسْم عَلَم مُذَكَّر)"},
    "rasool": {"en": "Rasool; messenger, apostle", "ur": "رسول، پیغام رساں", "fa": "رسول، پیام‌آور", "hi": "रसूल, संदेशवाहक", "ps": "رسول، پیغام رسول", "ar": "الرَّسُول، الْمُرْسَل"},
    "rasul": {"en": "Rasul; messenger, apostle", "ur": "رسول، پیغام رساں", "fa": "رسول، پیام‌آور", "hi": "रसूल, संदेशवाहक", "ps": "رسول، پیغام رسول", "ar": "الرَّسُول، الْمُرْسَل"},
    "rasyid": {"en": "Rasyid; rightly guided", "ur": "رشید، ہدایت یافتہ", "fa": "رشید، هدایت‌یافته", "hi": "रशीद, सन्मार्गी", "ps": "رشید، سم لارښود", "ar": "الرَّشِيد، الْمُهْتَدِي"},
    "ratib": {"en": "Ratib; a male given name", "ur": "رتب (مردانہ نام)", "fa": "رتب (نام مردانه)", "hi": "रतिब (पुरुष नाम)", "ps": "رتب (نر نوم)", "ar": "رَاتِب (اسْم عَلَم مُذَكَّر)"},
    "ratiba": {"en": "Ratiba; a female given name", "ur": "رتبہ (زنانہ نام)", "fa": "رتبه (نام زنانه)", "hi": "रतीबा (स्त्री नाम)", "ps": "رتبه (ښځينه نوم)", "ar": "رَتِيبَة (اسْم عَلَم مُؤَنَّث)"},
    "raudah": {"en": "Raudah; garden, meadow", "ur": "روضہ، باغ", "fa": "روضه، باغ", "hi": "रौज़ा, बाग़", "ps": "روضه، باغ", "ar": "الرَّوْضَة، الْحَدِيقَة"},
    "raudhah": {"en": "Raudhah; garden, meadow", "ur": "روضہ، باغ", "fa": "روضه، باغ", "hi": "रौज़ा, बाग़", "ps": "روضه، باغ", "ar": "الرَّوْضَة، الْحَدِيقَة"},
    "raufa": {"en": "Raufa; compassionate, kind (feminine)", "ur": "رؤفہ، مہربان", "fa": "رئوفه، مهربان", "hi": "रऊफ़ा, दयालु", "ps": "رئوفه، مهربانه", "ar": "رَءُوفَة، الرَّءُوفَة"},
    "raunak": {"en": "Raunak; splendour, lustre (Urdu/Hindi)", "ur": "رونق، چمک، رونق", "fa": "رونق، درخشش", "hi": "रौनक़, चमक", "ps": "رونق، ځلا", "ar": "رَوْنَق (الْبَهَاء)"},
    "raushan": {"en": "Raushan; illuminated, bright (Persian)", "ur": "روشن، منور", "fa": "روشن، درخشان", "hi": "रौशन, प्रकाशित", "ps": "روشن، روښانه", "ar": "رَوْشَن (الْمُضِيء)"},
    "ravan": {"en": "Ravan; a male given name (Persian)", "ur": "روان (مردانہ نام)", "fa": "روان (نام مردانه)", "hi": "रवान (पुरुष नाम)", "ps": "روان (نر نوم)", "ar": "رَوَان (اسْم عَلَم فَارِسِيّ)"},
    "rawa": {"en": "Rawa; a female given name", "ur": "روا (زنانہ نام)", "fa": "روا (نام زنانه)", "hi": "रवा (स्त्री नाम)", "ps": "روا (ښځينه نوم)", "ar": "رَوَا (اسْم عَلَم مُؤَنَّث)"},
    "rawaa": {"en": "Rawaa; a female given name", "ur": "رواء (زنانہ نام)", "fa": "رواء (نام زنانه)", "hi": "रवा (स्त्री नाम)", "ps": "رواء (ښځينه نوم)", "ar": "رَوَاءَة (اسْم عَلَم مُؤَنَّث)"},
    "rawah": {"en": "Rawah; a female given name", "ur": "رواح (زنانہ نام)", "fa": "رواح (نام زنانه)", "hi": "रवाह (स्त्री नाम)", "ps": "رواح (ښځينه نوم)", "ar": "رَوَاحَة (اسْم عَلَم مُؤَنَّث)"},
    "rawan": {"en": "Rawan; a female given name", "ur": "روان (زنانہ نام)", "fa": "روان (نام زنانه)", "hi": "रवान (स्त्री नाम)", "ps": "روان (ښځينه نوم)", "ar": "رَوَان (اسْم عَلَم مُؤَنَّث)"},
    "rawda": {"en": "Rawda; garden, meadow", "ur": "روضہ، باغ", "fa": "روضه، باغ", "hi": "रौज़ा, बाग़", "ps": "روضه، باغ", "ar": "الرَّوْضَة، الْحَدِيقَة"},
    "rawdah": {"en": "Rawdah; garden, meadow", "ur": "روضہ، باغ", "fa": "روضه، باغ", "hi": "रौज़ा, बाग़", "ps": "روضه، باغ", "ar": "الرَّوْضَة، الْحَدِيقَة"},
    "rawdha": {"en": "Rawdha; garden, meadow", "ur": "روضہ، باغ", "fa": "روضه، باغ", "hi": "रौज़ा, बाग़", "ps": "روضه، باغ", "ar": "الرَّوْضَة، الْحَدِيقَة"},
    "rawia": {"en": "Rawia; narrator, transmitter (feminine)", "ur": "راویہ، روایت کرنے والی", "fa": "راویه، روایت‌کننده", "hi": "राविया, वर्णनकर्ता", "ps": "راویه، روایت کوونکې", "ar": "رَاوِيَة، الرَّاوِيَة"},
    "rawiya": {"en": "Rawiya; narrator, transmitter (feminine)", "ur": "راویہ، روایت کرنے والی", "fa": "راویه، روایت‌کننده", "hi": "राविया, वर्णनकर्ता", "ps": "راویه، روایت کوونکې", "ar": "رَاوِيَة، الرَّاوِيَة"},
    "rawya": {"en": "Rawya; narrator, transmitter (feminine)", "ur": "راویہ، روایت کرنے والی", "fa": "راویه، روایت‌کننده", "hi": "राविया, वर्णनकर्ता", "ps": "راویه، روایت کوونکې", "ar": "رَاوِيَة، الرَّاوِيَة"},
    "raya": {"en": "Raya; banner, flag", "ur": "رایہ، پرچم", "fa": "رایه، پرچم", "hi": "राया, झंडा", "ps": "رایه، بیرغ", "ar": "الرَّايَة، الْعَلَم"},
    "rayaan": {"en": "Rayaan; sated, refreshed", "ur": "ریان، سیراب", "fa": "ریان، سیراب", "hi": "रैयान, तृप्त", "ps": "ریان، سیراب", "ar": "الرَّيَّان، الْمُرْتَوِي"},
    "rayah": {"en": "Rayah; banner, flag", "ur": "رایہ، پرچم", "fa": "رایه، پرچم", "hi": "राया, झंडा", "ps": "رایه، بیرغ", "ar": "الرَّايَة، الْعَلَم"},
    "rayan": {"en": "Rayan; sated, refreshed", "ur": "ریان، سیراب", "fa": "ریان، سیراب", "hi": "रैयान, तृप्त", "ps": "ریان، سیراب", "ar": "الرَّيَّان، الْمُرْتَوِي"},
    "rayana": {"en": "Rayana; sated, refreshed (feminine)", "ur": "ریانہ، سیراب", "fa": "ریانه، سیراب", "hi": "रैयाना, तृप्त", "ps": "ریانه، سیرابه", "ar": "رَيَّانَة، الرَّيَّانَة"},
    "rayann": {"en": "Rayann; sated, refreshed", "ur": "ریان، سیراب", "fa": "ریان، سیراب", "hi": "रैयान, तृप्त", "ps": "ریان، سیراب", "ar": "الرَّيَّان، الْمُرْتَوِي"},
    "rayees": {"en": "Rayees; leader, chief", "ur": "رئیس، سردار", "fa": "رئیس، رهبر", "hi": "रईस, नेता", "ps": "رئیس، مشر", "ar": "الرَّئِيس، الزَّعِيم"},
    "rayhaan": {"en": "Rayhaan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "rayhan": {"en": "Rayhan; fragrant herb, basil", "ur": "ریحان، خوشبودار پودا", "fa": "ریحان، سبزی خوشبو", "hi": "रैहान, तुलसी", "ps": "ریحان، خوږ بوټی", "ar": "الرَّيْحَان"},
    "rayhanat": {"en": "Rayhanat; fragrant herbs (plural)", "ur": "ریحانات، خوشبودار پودے", "fa": "ریحانات، سبزی‌های خوشبو", "hi": "रैहानात, सुगंधित पौधे", "ps": "ریحانات، خوږ بوټي", "ar": "رَيْحَانَات، الرَّيَاحِين"},
    "rayn": {"en": "Rayn; a female given name", "ur": "رین (زنانہ نام)", "fa": "رین (نام زنانه)", "hi": "रैन (स्त्री नाम)", "ps": "رین (ښځينه نوم)", "ar": "رَيْن (اسْم عَلَم مُؤَنَّث)"},
    "rayna": {"en": "Rayna; a female given name", "ur": "رینا (زنانہ نام)", "fa": "رینا (نام زنانه)", "hi": "रैना (स्त्री नाम)", "ps": "رینا (ښځينه نوم)", "ar": "رَيْنَا (اسْم عَلَم مُؤَنَّث)"},
    "rayya": {"en": "Rayya; sated, refreshed (feminine)", "ur": "ریا، سیراب", "fa": "ریا، سیراب", "hi": "रैया, तृप्त", "ps": "ریا، سیرابه", "ar": "رَيَّا، الرَّيَّانَة"},
    "rayyan": {"en": "Rayyan; sated, refreshed", "ur": "ریان، سیراب", "fa": "ریان، سیراب", "hi": "रैयान, तृप्त", "ps": "ریان، سیراب", "ar": "الرَّيَّان، الْمُرْتَوِي"},
    "raz": {"en": "Raz; secret, mystery (Persian)", "ur": "راز، بھید", "fa": "راز، سر", "hi": "राज़, रहस्य", "ps": "راز، پټ", "ar": "رَاز (السِّرّ)"},
})

CUR = {
 "ramadan": ("رَمَضَان", "رمضان", "رمضان", "रमज़ान", "رمضان", "ramadan", "Arabic", "Male",
             "Arabic رَمَضَان (Ramaḍān), the ninth Islamic month", False, "high",
             "Ramadan is Arabic رَمَضَان (Ramaḍān), the ninth month of the Islamic calendar, used as a male given name. The source gloss 'Month of fasting' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender neutral; documented usage is predominantly male."),
 "ramadhan": ("رَمَضَان", "رمضان", "رمضان", "रमज़ान", "رمضان", "ramadhan", "Arabic", "Male",
              "Arabic رَمَضَان (Ramaḍān), the ninth Islamic month", False, "high",
              "Ramadhan is a spelling variant of Arabic رَمَضَان (Ramaḍān), the ninth month of the Islamic calendar, used as a male given name. The source gloss 'The Ninth Month' is broadly consistent. Same name as ramadan."),
 "raman": ("رَمَان", "رمن", "رمن", "रमन", "رمن", "raman", "Arabic", "Male",
           "Arabic رَمَان (Ramān)", False, "medium",
           "Raman is recorded as Arabic رَمَان (Ramān), a male given name. The source gloss 'A radiant light' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ramazan": ("رَمَضَان", "رمضان", "رمضان", "रमज़ान", "رمضان", "ramazan", "Turkish", "Male",
             "Turkish Ramazan, from Arabic رَمَضَان", False, "high",
             "Ramazan is the Turkish/Persian form of Arabic رَمَضَان (Ramaḍān), the ninth month of the Islamic calendar, used as a male given name. The source gloss 'Month of Fasting' is broadly consistent. Same name as ramadan."),
 "rambod": ("رَمْبُود", "رمبود", "رمبود", "रम्बोद", "رمبود", "rambod", "Persian", "Male",
            "Persian رمبود (Rambod)", False, "medium",
            "Rambod is a Persian male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rambod' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Royal' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rameen": ("رَامِين", "رامین", "رامین", "रामीन", "رامین", "rameen", "Persian", "Female",
            "Persian رامین (Rāmīn)", False, "high",
            "Rameen is a female given name from Persian رامین (Rāmīn). The source gloss 'Joyful, Obedient, Rescuer' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as ramin."),
 "rameesh": ("رَمِيش", "رمیش", "رمیش", "रमीश", "رمیش", "rameesh", "Arabic", "Male",
             "Arabic رَمِيش (Ramīsh)", False, "medium",
             "Rameesh is recorded as Arabic رَمِيش (Ramīsh), a male given name. The source gloss 'One who is gentle and kind' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rameez": ("رَمِيز", "رمیز", "رمیز", "रमीज़", "رمیز", "rameez", "Arabic", "Male",
            "Arabic رَمِيز (Ramīz)", False, "high",
            "Rameez is Arabic رَمِيز (Ramīz), a male given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "ramez": ("رَامِز", "رامز", "رامز", "रामेज़", "رامز", "ramez", "Arabic", "Male",
           "Arabic رَامِز (Rāmiz)", False, "high",
           "Ramez is Arabic رَامِز (Rāmiz), a male given name. CRITICAL SOURCE ERROR: the source gave 'عربي_Ramez' (a placeholder prefix); the correct form is رَامِز. The source gloss 'Noble and blessed' is unsupported and has been replaced with the documented identification. Same name as ramiz."),
 "rami": ("رَامِي", "رامی", "رامی", "रामी", "رامي", "rami", "Arabic", "Male",
          "Arabic root ر م ي (r-m-y); رَامِي (Rāmī)", False, "high",
          "Rami is Arabic رَامِي (Rāmī) 'thrower, archer', from the root ر م ي (r-m-y). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "ramia": ("رَامِيَة", "رامیہ", "رامیه", "रामिया", "رامیه", "ramia", "Arabic", "Female",
           "Arabic root ر م ي (r-m-y); رَامِيَة (Rāmiya)", False, "high",
           "Ramia is Arabic رَامِيَة (Rāmiya) 'thrower, archer' (feminine), from the root ر م ي (r-m-y). The source gloss 'Pomegranate' is unsupported and has been replaced with the lexical sense. Same name as ramiya."),
 "ramiar": ("رَمْيَار", "رمیار", "رمیار", "रमियार", "رمیار", "ramiar", "Arabic", "Male",
            "Arabic رَمْيَار (Ramyār)", False, "medium",
            "Ramiar is recorded as Arabic رَمْيَار (Ramyār), a male given name. The source gloss 'High, Sublime' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ramin": ("رَامِين", "رامین", "رامین", "रामिन", "رامین", "ramin", "Persian", "Male",
           "Persian رامین (Rāmīn)", False, "high",
           "Ramin is a Persian male given name, رامین (Rāmīn). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'lover, friend' is unsupported and has been replaced with the documented identification."),
 "ramina": ("رَامِينَا", "رامینہ", "رامینا", "रामीना", "رامینا", "ramina", "Persian", "Female",
            "Persian رامینا (Rāmīnā)", False, "medium",
            "Ramina is a female given name from Persian رامینا (Rāmīnā). The source gloss 'Joyful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ramir": ("رَمِير", "رمیر", "رمیر", "रमीर", "رمیر", "ramir", "Arabic", "Male",
           "Arabic رَمِير (Ramīr)", False, "medium",
           "Ramir is recorded as Arabic رَمِير (Ramīr), a male given name. The source gloss 'High, Exalted' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ramish": ("رَمِيش", "رمیش", "رمیش", "रमीश", "رمیش", "ramish", "Arabic", "Male",
            "Arabic رَمِيش (Ramīsh)", False, "medium",
            "Ramish is recorded as Arabic رَمِيش (Ramīsh), a male given name. CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is رَمِيش. The source gloss 'Rainy' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as rameesh."),
 "ramiya": ("رَامِيَة", "رامیہ", "رامیه", "रामिया", "رامیه", "ramiya", "Arabic", "Female",
            "Arabic root ر م ي (r-m-y); رَامِيَة (Rāmiya)", False, "high",
            "Ramiya is Arabic رَامِيَة (Rāmiya) 'thrower, archer' (feminine), from the root ر م ي (r-m-y). The source gloss 'Beautiful, Graceful' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as ramia."),
 "ramiz": ("رَامِز", "رامز", "رامز", "रामिज़", "رامز", "ramiz", "Arabic", "Male",
           "Arabic رَامِز (Rāmiz)", False, "high",
           "Ramiz is Arabic رَامِز (Rāmiz), a male given name. The source gloss 'Exalted, Noble, Precious' is unsupported and has been replaced with the documented identification."),
 "ramiza": ("رَمِيزَة", "رمیزہ", "رمیزه", "रमीज़ा", "رمیزه", "ramiza", "Arabic", "Female",
            "Arabic رَمِيزَة (Ramīza)", False, "high",
            "Ramiza is Arabic رَمِيزَة (Ramīza), a female given name. The source gloss 'Jasmine' is unsupported and has been replaced with the documented identification."),
 "ramla": ("رَمْلَة", "رملہ", "رمله", "रमला", "رمله", "ramla", "Arabic", "Female",
           "Arabic root ر م ل (r-m-l); رَمْلَة (Ramla)", False, "high",
           "Ramla is Arabic رَمْلَة (Ramla) 'sand', from the root ر م ل (r-m-l). The source gloss 'Small valley' is unsupported and has been replaced with the lexical sense. Same name as ramlah."),
 "ramlah": ("رَمْلَة", "رملہ", "رمله", "रमला", "رمله", "ramlah", "Arabic", "Female",
            "Arabic root ر م ل (r-m-l); رَمْلَة (Ramla)", False, "high",
            "Ramlah is Arabic رَمْلَة (Ramla) 'sand', from the root ر م ل (r-m-l). The source gloss 'Palmyra' is unsupported and has been replaced with the lexical sense. Same name as ramla."),
 "ramlat": ("رَمْلَة", "رملت", "رملت", "रमलत", "رملت", "ramlat", "Arabic", "Female",
            "Arabic root ر م ل (r-m-l); رَمْلَة (Ramla)", False, "high",
            "Ramlat is a spelling variant of Arabic رَمْلَة (Ramla) 'sand', from the root ر م ل (r-m-l). The source gloss 'Desert' is broadly consistent. Same name as ramla."),
 "ramsha": ("رَمْشَة", "رمشہ", "رمشه", "रमशा", "رمشه", "ramsha", "Arabic", "Female",
            "Arabic رَمْشَة (Ramsha)", False, "high",
            "Ramsha is Arabic رَمْشَة (Ramsha), a female given name. The source gloss 'Fragrance, Light, Beauty' is unsupported and has been replaced with the documented identification."),
 "ramz": ("رَمْز", "رمز", "رمز", "रम्ज़", "رمز", "ramz", "Arabic", "Male",
          "Arabic root ر م ز (r-m-z); رَمْز (Ramz)", False, "high",
          "Ramz is Arabic رَمْز (Ramz) 'sign, symbol', from the root ر م ز (r-m-z). The source gloss 'Exalted One' is unsupported and has been replaced with the lexical sense."),
 "ramza": ("رَمْزَة", "رمزہ", "رمزه", "रमज़ा", "رمزه", "ramza", "Arabic", "Female",
           "Arabic root ر م ز (r-m-z); رَمْزَة (Ramza)", False, "high",
           "Ramza is Arabic رَمْزَة (Ramza), a female given name from the root ر م ز (r-m-z). CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is رَمْزَة. The source gloss 'Jasmine' is unsupported and has been replaced with the documented identification."),
 "ramzan": ("رَمَضَان", "رمضان", "رمضان", "रमज़ान", "رمضان", "ramzan", "Urdu", "Male",
            "Urdu رمضان (ramzān), from Arabic رَمَضَان", False, "high",
            "Ramzan is the South Asian (Urdu/Pashto) form of Arabic رَمَضَان (Ramaḍān), the ninth month of the Islamic calendar, used as a male given name. The source gloss 'Month of fasting' is broadly consistent. Same name as ramadan."),
 "ramzi": ("رَمْزِي", "رمزی", "رمزی", "रमज़ी", "رمزي", "ramzi", "Arabic", "Male",
           "Arabic رَمْزِي (Ramzī) 'of the sign'", False, "high",
           "Ramzi is Arabic رَمْزِي (Ramzī) 'symbolic, of the sign', a relational adjective from رَمْز (ramz). The source gloss 'Rare, Precious' is unsupported and has been replaced with the lexical sense."),
 "ramzia": ("رَمْضِيَة", "رمزیہ", "رمضیه", "रमज़िया", "رمضیه", "ramzia", "Arabic", "Female",
            "Arabic رَمْضِيَة (Ramḍiya)", False, "medium",
            "Ramzia is recorded as Arabic رَمْضِيَة (Ramḍiya), a female given name. CRITICAL SOURCE ERROR: the source gave رمضية (a non-standard form). The source gloss 'Exalted One' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rana": ("رَنَا", "رنا", "رنا", "रना", "رنا", "rana", "Arabic", "Female",
          "Arabic رَنَا (Ranā)", False, "high",
          "Rana is Arabic رَنَا (Ranā), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "ranaa": ("رَنَا", "رنا", "رنا", "रना", "رنا", "ranaa", "Arabic", "Female",
           "Arabic رَنَا (Ranā)", False, "high",
           "Ranaa is a spelling variant of Arabic رَنَا (Ranā), a female given name. The source gloss 'Moon' is unsupported and has been replaced with the documented identification. Same name as rana."),
 "rand": ("رَنْد", "رند", "رند", "रंद", "رند", "rand", "Arabic", "Female",
          "Arabic رَنْد (Rand)", False, "high",
          "Rand is Arabic رَنْد (Rand), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rand' instead of a script form and labelled the origin English; the name is Arabic. The source gloss 'Little One, Small One' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "randah": ("رَنْدَة", "رندہ", "رنده", "रंदा", "رنده", "randah", "Arabic", "Female",
            "Arabic رَنْدَة (Randa)", False, "high",
            "Randah is Arabic رَنْدَة (Randa), a female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name); the correct form is رَنْدَة. The source gloss 'Contentment' is unsupported and has been replaced with the documented identification."),
 "rane": ("رَانَة", "رانے", "رانه", "राने", "رانه", "rane", "Arabic", "Female",
          "Arabic رَانَة (Rāna)", False, "medium",
          "Rane is recorded as Arabic رَانَة (Rāna), a female given name. CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is رَانَة. The source gloss 'crow' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "raneem": ("رَنِيم", "رنیم", "رنیم", "रनीम", "رنیم", "raneem", "Arabic", "Female",
            "Arabic رَنِيم (Ranīm)", False, "high",
            "Raneem is Arabic رَنِيم (Ranīm), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "rania": ("رَانِيَة", "رانیہ", "رانیا", "रानिया", "رانیا", "rania", "Arabic", "Female",
           "Arabic رَانِيَة (Rāniya)", False, "high",
           "Rania is Arabic رَانِيَة (Rāniya), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as raniya."),
 "raniah": ("رَانِيَة", "رانیہ", "رانیه", "रानिया", "رانیه", "raniah", "Arabic", "Female",
            "Arabic رَانِيَة (Rāniya)", False, "high",
            "Raniah is Arabic رَانِيَة (Rāniya), a female given name. The source gloss 'Content, Happy, Peaceful' is unsupported and has been replaced with the documented identification. Same name as raniya."),
 "ranim": ("رَانِيم", "رانیم", "رانیم", "रानीम", "رانیم", "ranim", "Arabic", "Female",
           "Arabic رَانِيم (Rānīm)", False, "medium",
           "Ranim is recorded as Arabic رَانِيم (Rānīm), a female given name. The source gloss 'Jasmine' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ranin": ("رَنِين", "رنین", "رنین", "रनीन", "رنین", "ranin", "Arabic", "Female",
           "Arabic رَنِين (Ranīn)", False, "high",
           "Ranin is Arabic رَنِين (Ranīn), a female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name); the correct form is رَنِين. The source gloss 'Jasmine flower' is unsupported and has been replaced with the documented identification."),
 "raniya": ("رَانِيَة", "رانیہ", "رانیا", "रानिया", "رانیا", "raniya", "Arabic", "Female",
            "Arabic رَانِيَة (Rāniya)", False, "high",
            "Raniya is Arabic رَانِيَة (Rāniya), a female given name. The source gloss 'Joyful One' is unsupported and has been replaced with the documented identification."),
 "ranya": ("رَانِيَة", "رانیہ", "رانیا", "रान्या", "رانیا", "ranya", "Arabic", "Female",
           "Arabic رَانِيَة (Rāniya)", False, "high",
           "Ranya is a spelling variant of Arabic رَانِيَة (Rāniya), a female given name. The source gloss 'Jasmine' is unsupported and has been replaced with the documented identification. Same name as raniya."),
 "raoof": ("رَءُوف", "رؤف", "رئوف", "रऊफ़", "رئوف", "raoof", "Arabic", "Male",
           "Arabic root ر أ ف (r-ʾ-f); رَءُوف (Raʾūf)", False, "high",
           "Raoof is Arabic رَءُوف (Raʾūf) 'compassionate, kind', from the root ر أ ف (r-ʾ-f). The source gloss 'High, Noble' is unsupported and has been replaced with the lexical sense. Same name as ra-uf."),
 "raouf": ("رَءُوف", "رؤف", "رئوف", "रऊफ़", "رئوف", "raouf", "Arabic", "Male",
           "Arabic root ر أ ف (r-ʾ-f); رَءُوف (Raʾūf)", False, "high",
           "Raouf is a spelling variant of Arabic رَءُوف (Raʾūf) 'compassionate, kind', from the root ر أ ف (r-ʾ-f). CRITICAL SOURCE ERROR: the source gave رَأوف (a non-standard form). The source gloss 'Radiant' is unsupported and has been replaced with the lexical sense. Same name as ra-uf."),
 "raqeeb": ("رَقِيب", "رقیب", "رقیب", "रक़ीब", "رقیب", "raqeeb", "Arabic", "Male",
            "Arabic root ر ق ب (r-q-b); رَقِيب (Raqīb)", False, "high",
            "Raqeeb is Arabic رَقِيب (Raqīb) 'watcher, guardian', from the root ر ق ب (r-q-b). The source gloss 'Watchman' is broadly consistent. Same name as raqib."),
 "raqib": ("رَقِيب", "رقیب", "رقیب", "रक़ीब", "رقیب", "raqib", "Arabic", "Male",
           "Arabic root ر ق ب (r-q-b); رَقِيب (Raqīb)", False, "high",
           "Raqib is Arabic رَقِيب (Raqīb) 'watcher, guardian', from the root ر ق ب (r-q-b). The source gloss 'Watcher' is consistent."),
 "rasa": ("رَسَا", "رسا", "رسا", "रसा", "رسا", "rasa", "Arabic", "Female",
          "Arabic رَسَا (Rasā)", False, "medium",
          "Rasa is recorded as Arabic رَسَا (Rasā), a female given name. The source gloss 'Taste, Love, Sweetness' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "rasha": ("رَشَا", "رشا", "رشا", "रशा", "رشا", "rasha", "Arabic", "Female",
           "Arabic رَشَا (Rashā)", False, "high",
           "Rasha is Arabic رَشَا (Rashā), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "rashaa": ("رَشَا", "رشا", "رشا", "रशा", "رشا", "rashaa", "Arabic", "Female",
            "Arabic رَشَا (Rashā)", False, "high",
            "Rashaa is a spelling variant of Arabic رَشَا (Rashā), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rashaa' instead of a script form. The source gloss 'Contentment, satisfaction' is unsupported and has been replaced with the documented identification. Same name as rasha."),
 "rashad": ("رَشَاد", "رشاد", "رشاد", "रशाद", "رشاد", "rashad", "Arabic", "Male",
            "Arabic root ر ش د (r-sh-d); رَشَاد (Rashād)", False, "high",
            "Rashad is Arabic رَشَاد (Rashād) 'right guidance', from the root ر ش د (r-sh-d). The source gloss 'Rightly guided' is broadly consistent."),
 "rashawn": ("رَاشُون", "راشون", "راشون", "राशॉन", "راشون", "rashawn", "Arabic", "Male",
             "Arabic رَاشُون (Rāshūn)", False, "medium",
             "Rashawn is recorded as Arabic رَاشُون (Rāshūn), a male given name. The source gloss 'Rightly guided' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rashda": ("رَشْدَة", "رشدہ", "رشده", "रशदा", "رشده", "rashda", "Arabic", "Female",
            "Arabic root ر ش د (r-sh-d); رَشْدَة (Rashda)", False, "high",
            "Rashda is Arabic رَشْدَة (Rashda) 'right guidance' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Rightly Guided One' is broadly consistent."),
 "rashdan": ("رَشْدَان", "رشدان", "رشدان", "रशदान", "رشدان", "rashdan", "Arabic", "Male",
             "Arabic root ر ش د (r-sh-d); رَشْدَان (Rashdān)", False, "high",
             "Rashdan is Arabic رَشْدَان (Rashdān) 'right guidance', from the root ر ش د (r-sh-d). The source gloss 'Powerful, Wise' is unsupported and has been replaced with the lexical sense."),
 "rashed": ("رَاشِد", "راشد", "راشد", "राशिद", "راشد", "rashed", "Arabic", "Male",
            "Arabic root ر ش د (r-sh-d); رَاشِد (Rāshid)", False, "high",
            "Rashed is a spelling variant of Arabic رَاشِد (Rāshid) 'rightly guided', from the root ر ش د (r-sh-d). The source gloss 'Righteous Guide' is broadly consistent. Same name as rashid."),
 "rasheed": ("رَشِيد", "رشید", "رشید", "रशीद", "رشید", "rasheed", "Arabic", "Male",
             "Arabic root ر ش د (r-sh-d); رَشِيد (Rashīd)", False, "high",
             "Rasheed is Arabic رَشِيد (Rashīd) 'rightly guided', from the root ر ش د (r-sh-d). The source gloss 'Guided, Rightly Guided' is consistent."),
 "rasheeda": ("رَشِيدَة", "رشیدہ", "رشیده", "रशीदा", "رشیده", "rasheeda", "Arabic", "Female",
              "Arabic root ر ش د (r-sh-d); رَشِيدَة (Rashīda)", False, "high",
              "Rasheeda is Arabic رَشِيدَة (Rashīda) 'rightly guided' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Head of the good or righteous' is unsupported and has been replaced with the lexical sense. Same name as rashida."),
 "rasheedah": ("رَشِيدَة", "رشیدہ", "رشیده", "रशीदा", "رشیده", "rasheedah", "Arabic", "Female",
               "Arabic root ر ش د (r-sh-d); رَشِيدَة (Rashīda)", False, "high",
               "Rasheedah is Arabic رَشِيدَة (Rashīda) 'rightly guided' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Rightly Guided' is consistent. Same name as rashida."),
 "rashid": ("رَاشِد", "راشد", "راشد", "राशिद", "راشد", "rashid", "Arabic", "Male",
            "Arabic root ر ش د (r-sh-d); رَاشِد (Rāshid)", False, "high",
            "Rashid is Arabic رَاشِد (Rāshid) 'rightly guided', from the root ر ش د (r-sh-d). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "rashida": ("رَشِيدَة", "رشیدہ", "رشیده", "रशीदा", "رشیده", "rashida", "Arabic", "Female",
             "Arabic root ر ش د (r-sh-d); رَشِيدَة (Rashīda)", False, "high",
             "Rashida is Arabic رَشِيدَة (Rashīda) 'rightly guided' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Rightly Guided' is consistent."),
 "rashidah": ("رَشِيدَة", "رشیدہ", "رشیده", "रशीदा", "رشیده", "rashidah", "Arabic", "Female",
              "Arabic root ر ش د (r-sh-d); رَشِيدَة (Rashīda)", False, "high",
              "Rashidah is Arabic رَشِيدَة (Rashīda) 'rightly guided' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Rightly Guided' is consistent. Same name as rashida."),
 "rashidat": ("رَشِيدَات", "رشیدات", "رشیدات", "रशीदात", "رشیدات", "rashidat", "Arabic", "Female",
              "Arabic root ر ش د (r-sh-d); رَشِيدَات (Rashīdāt)", False, "high",
              "Rashidat is Arabic رَشِيدَات (Rashīdāt), the plural of رَشِيدَة (Rashīda) 'rightly guided', used as a female given name. The source gloss 'Rightly Guided' is broadly consistent."),
 "rasif": ("رَاسِف", "راسف", "راسف", "रासिफ़", "راسف", "rasif", "Arabic", "Male",
           "Arabic رَاسِف (Rāsif)", False, "medium",
           "Rasif is recorded as Arabic رَاسِف (Rāsif), a male given name. The source gloss 'Wise, Knowledgeable' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rasil": ("رَسِيل", "رسل", "رسل", "रसील", "رسل", "rasil", "Arabic", "Male",
           "Arabic root ر س ل (r-s-l); رَسِيل (Rasīl)", False, "high",
           "Rasil is Arabic رَسِيل (Rasīl) 'messenger, emissary', from the root ر س ل (r-s-l). The source gloss 'Messenger, Emissary' is consistent."),
 "rasim": ("رَاسِم", "راسم", "راسم", "रासिम", "راسم", "rasim", "Turkish", "Male",
           "Turkish Rasim, from Arabic رَاسِم", False, "high",
           "Rasim is a Turkish male given name, from Arabic رَاسِم (Rāsim). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is Turkish. The source gloss 'Contentment' is unsupported and has been replaced with the documented identification."),
 "rasima": ("رَاسِمَة", "راسمہ", "راسما", "रासिमा", "راسما", "rasima", "Arabic", "Female",
            "Arabic رَاسِمَة (Rāsima)", False, "medium",
            "Rasima is recorded as Arabic رَاسِمَة (Rāsima), a female given name. CRITICAL SOURCE ERROR: the source gave 'Razan' (a different name); the correct form is رَاسِمَة. The source gloss 'Moon' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rasin": ("رَاسِين", "راسین", "راسین", "रासीन", "راسین", "rasin", "Arabic", "Male",
           "Arabic رَاسِين (Rāsīn)", False, "medium",
           "Rasin is recorded as Arabic رَاسِين (Rāsīn), a male given name. The source gloss 'Pomegranate' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "rasool": ("رَسُول", "رسول", "رسول", "रसूल", "رسول", "rasool", "Arabic", "Male",
            "Arabic root ر س ل (r-s-l); رَسُول (Rasūl)", False, "high",
            "Rasool is Arabic رَسُول (Rasūl) 'messenger, apostle', from the root ر س ل (r-s-l). The source gloss 'Messenger' is consistent. Same name as rasul."),
 "rasul": ("رَسُول", "رسول", "رسول", "रसूल", "رسول", "rasul", "Arabic", "Male",
           "Arabic root ر س ل (r-s-l); رَسُول (Rasūl)", False, "high",
           "Rasul is Arabic رَسُول (Rasūl) 'messenger, apostle', from the root ر س ل (r-s-l). The source gloss 'Messenger' is consistent. Same name as rasool."),
 "rasyid": ("رَشِيد", "رشید", "رشید", "रशीद", "رشید", "rasyid", "Arabic", "Male",
            "Arabic root ر ش د (r-sh-d); رَشِيد (Rashīd)", False, "high",
            "Rasyid is a spelling variant of Arabic رَشِيد (Rashīd) 'rightly guided', from the root ر ش د (r-sh-d). The source gloss 'Owner, master, possessor' is unsupported and has been replaced with the lexical sense. Same name as rasheed."),
 "ratib": ("رَاتِب", "رتب", "رتب", "रतिब", "رتب", "ratib", "Arabic", "Male",
           "Arabic رَاتِب (Rātib)", False, "medium",
           "Ratib is recorded as Arabic رَاتِب (Rātib), a male given name. CRITICAL SOURCE ERROR: the source gave رتب (a non-standard form). The source gloss 'One who is grateful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "ratiba": ("رَتِيبَة", "رتبہ", "رتبه", "रतीबा", "رتبه", "ratiba", "Arabic", "Female",
            "Arabic رَتِيبَة (Ratība)", False, "medium",
            "Ratiba is recorded as Arabic رَتِيبَة (Ratība), a female given name. CRITICAL SOURCE ERROR: the source gave رتبة (a non-standard form). The source gloss 'Progress, Steps' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "raudah": ("رَوْضَة", "روضہ", "روضه", "रौज़ा", "روضه", "raudah", "Arabic", "Female",
            "Arabic root ر و ض (r-w-ḍ); رَوْضَة (Rauḍa)", False, "high",
            "Raudah is Arabic رَوْضَة (Rauḍa) 'garden, meadow', from the root ر و ض (r-w-ḍ). The source gloss 'Garden of Paradise' is broadly consistent. Same name as rawdah."),
 "raudhah": ("رَوْضَة", "روضہ", "روضه", "रौज़ा", "روضه", "raudhah", "Arabic", "Female",
             "Arabic root ر و ض (r-w-ḍ); رَوْضَة (Rauḍa)", False, "high",
             "Raudhah is Arabic رَوْضَة (Rauḍa) 'garden, meadow', from the root ر و ض (r-w-ḍ). The source gloss 'Garden of Paradise' is broadly consistent. Same name as rawdah."),
 "raufa": ("رَءُوفَة", "رؤفہ", "رئوفه", "रऊफ़ा", "رئوفه", "raufa", "Arabic", "Female",
           "Arabic root ر أ ف (r-ʾ-f); رَءُوفَة (Raʾūfa)", False, "high",
           "Raufa is Arabic رَءُوفَة (Raʾūfa) 'compassionate, kind' (feminine), from the root ر أ ف (r-ʾ-f). The source gloss 'Exalted' is unsupported and has been replaced with the lexical sense."),
 "raunak": ("رَوْنَق", "رونق", "رونق", "रौनक़", "رونق", "raunak", "Urdu", "Male",
            "Urdu رونق (raunaq), from Arabic رَوْنَق", False, "high",
            "Raunak is Urdu رونق (raunaq) 'splendour, lustre', from Arabic رَوْنَق. CRITICAL SOURCE ERROR: the source gave 'Ali' (a different name) and labelled the origin Arabic; the name as used is Urdu/Hindi. The source gloss 'Joy' is unsupported and has been replaced with the lexical sense."),
 "raushan": ("رَوْشَن", "روشن", "روشن", "रौशन", "روشن", "raushan", "Persian", "Male",
             "Persian روشن (raushan)", False, "high",
             "Raushan is Persian روشن (raushan) 'illuminated, bright'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Illuminated, Enlightened' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "ravan": ("رَوَان", "روان", "روان", "रवान", "روان", "ravan", "Persian", "Male",
           "Persian روان (ravān)", False, "high",
           "Ravan is Persian روان (ravān) 'soul, spirit; flowing'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Ravan' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Sky, Heaven' is unsupported and has been replaced with the lexical sense."),
 "rawa": ("رَوَا", "روا", "روا", "रवा", "روا", "rawa", "Arabic", "Female",
          "Arabic رَوَا (Rawā)", False, "medium",
          "Rawa is recorded as Arabic رَوَا (Rawā), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Rawa' instead of a script form. The source gloss 'Flowing river' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rawaa": ("رَوَاءَة", "رواء", "رواء", "रवा", "رواء", "rawaa", "Arabic", "Female",
           "Arabic رَوَاءَة (Rawāʾa)", False, "medium",
           "Rawaa is recorded as Arabic رَوَاءَة (Rawāʾa), a female given name. CRITICAL SOURCE ERROR: the source gave رَوَاءَة (a non-standard form). The source gloss 'Contentment, satisfaction' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rawah": ("رَوَاحَة", "رواح", "رواح", "रवाह", "رواح", "rawah", "Arabic", "Female",
           "Arabic رَوَاحَة (Rawāḥa)", False, "medium",
           "Rawah is recorded as Arabic رَوَاحَة (Rawāḥa), a female given name. CRITICAL SOURCE ERROR: the source gave رَوَاحَ (a non-standard form). The source gloss 'Guide, gentle one' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rawan": ("رَوَان", "روان", "روان", "रवान", "روان", "rawan", "Arabic", "Female",
           "Arabic رَوَان (Rawān)", False, "high",
           "Rawan is Arabic رَوَان (Rawān), a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "rawda": ("رَوْضَة", "روضہ", "روضه", "रौज़ा", "روضه", "rawda", "Arabic", "Female",
           "Arabic root ر و ض (r-w-ḍ); رَوْضَة (Rauḍa)", False, "high",
           "Rawda is Arabic رَوْضَة (Rauḍa) 'garden, meadow', from the root ر و ض (r-w-ḍ). The source gloss 'garden' is consistent. Same name as rawdah."),
 "rawdah": ("رَوْضَة", "روضہ", "روضه", "रौज़ा", "روضه", "rawdah", "Arabic", "Female",
            "Arabic root ر و ض (r-w-ḍ); رَوْضَة (Rauḍa)", False, "high",
            "Rawdah is Arabic رَوْضَة (Rauḍa) 'garden, meadow', from the root ر و ض (r-w-ḍ). The source gloss 'Garden' is consistent. Same name as rawda."),
 "rawdha": ("رَوْضَة", "روضہ", "روضه", "रौज़ा", "روضه", "rawdha", "Arabic", "Female",
            "Arabic root ر و ض (r-w-ḍ); رَوْضَة (Rauḍa)", False, "high",
            "Rawdha is a spelling variant of Arabic رَوْضَة (Rauḍa) 'garden, meadow', from the root ر و ض (r-w-ḍ). The source gloss 'Garden' is consistent. Same name as rawda."),
 "rawia": ("رَاوِيَة", "راویہ", "راویه", "राविया", "راویه", "rawia", "Arabic", "Female",
           "Arabic root ر و ي (r-w-y); رَاوِيَة (Rāwiya)", False, "high",
           "Rawia is Arabic رَاوِيَة (Rāwiya) 'narrator, transmitter' (feminine), from the root ر و ي (r-w-y). The source gloss 'Joyful' is unsupported and has been replaced with the lexical sense. Same name as rawiya."),
 "rawiya": ("رَاوِيَة", "راویہ", "راویه", "राविया", "راویه", "rawiya", "Arabic", "Female",
            "Arabic root ر و ي (r-w-y); رَاوِيَة (Rāwiya)", False, "high",
            "Rawiya is Arabic رَاوِيَة (Rāwiya) 'narrator, transmitter' (feminine), from the root ر و ي (r-w-y). The source gloss 'Reader, Scholar' is broadly consistent."),
 "rawya": ("رَاوِيَة", "راویہ", "راویه", "राविया", "راویه", "rawya", "Arabic", "Female",
           "Arabic root ر و ي (r-w-y); رَاوِيَة (Rāwiya)", False, "high",
           "Rawya is a spelling variant of Arabic رَاوِيَة (Rāwiya) 'narrator, transmitter' (feminine), from the root ر و ي (r-w-y). The source gloss 'Gently flowing stream' is unsupported and has been replaced with the lexical sense. Same name as rawiya."),
 "raya": ("رَايَة", "رایہ", "رایه", "राया", "رایه", "raya", "Arabic", "Female",
          "Arabic رَايَة (Rāya) 'banner, flag'", False, "high",
          "Raya is Arabic رَايَة (Rāya) 'banner, flag'. The source gloss 'Joy, happiness, brightness' is unsupported and has been replaced with the lexical sense. Same name as raya."),
 "rayaan": ("رَيَّان", "ریان", "ریان", "रैयान", "ریان", "rayaan", "Arabic", "Male",
            "Arabic root ر و ي (r-w-y); رَيَّان (Rayyān)", False, "high",
            "Rayaan is Arabic رَيَّان (Rayyān) 'sated, refreshed', from the root ر و ي (r-w-y). The source gloss 'Watered, Luxuriant' is broadly consistent. Same name as rayan."),
 "rayah": ("رَايَة", "رایہ", "رایه", "राया", "رایه", "rayah", "Arabic", "Female",
           "Arabic رَايَة (Rāya) 'banner, flag'", False, "high",
           "Rayah is Arabic رَايَة (Rāya) 'banner, flag'. The source gloss 'contentment, joy' is unsupported and has been replaced with the lexical sense. Same name as raya."),
 "rayan": ("رَيَّان", "ریان", "ریان", "रैयान", "ریان", "rayan", "Arabic", "Male",
           "Arabic root ر و ي (r-w-y); رَيَّان (Rayyān)", False, "high",
           "Rayan is Arabic رَيَّان (Rayyān) 'sated, refreshed', from the root ر و ي (r-w-y). CRITICAL SOURCE ERROR: the source gave 'RAYAN' (a Latin string) instead of a script form. The source gloss 'River of life, flowing water, or abundant' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "rayana": ("رَيَّانَة", "ریانہ", "ریانه", "रैयाना", "ریانه", "rayana", "Arabic", "Female",
            "Arabic root ر و ي (r-w-y); رَيَّانَة (Rayyāna)", False, "high",
            "Rayana is Arabic رَيَّانَة (Rayyāna) 'sated, refreshed' (feminine), from the root ر و ي (r-w-y). The source gloss 'Filled with knowledge and wisdom' is unsupported and has been replaced with the lexical sense."),
 "rayann": ("رَيَّان", "ریان", "ریان", "रैयान", "ریان", "rayann", "Arabic", "Male",
            "Arabic root ر و ي (r-w-y); رَيَّان (Rayyān)", False, "high",
            "Rayann is a spelling variant of Arabic رَيَّان (Rayyān) 'sated, refreshed', from the root ر و ي (r-w-y). The source gloss 'Mountain of joy' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as rayan."),
 "rayees": ("رَئِيس", "رئیس", "رئیس", "रईस", "رئیس", "rayees", "Arabic", "Male",
            "Arabic root ر أ س (r-ʾ-s); رَئِيس (Raʾīs)", False, "high",
            "Rayees is a spelling variant of Arabic رَئِيس (Raʾīs) 'leader, chief', from the root ر أ س (r-ʾ-s). CRITICAL SOURCE ERROR: the source gave رايس (a non-standard form). The source gloss 'Guardian, Protector' is unsupported and has been replaced with the lexical sense. Same name as raees."),
 "rayhaan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "rayhaan", "Arabic", "Male",
             "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
             "Rayhaan is Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). The source gloss 'Fragrant, Sweet Scent' is broadly consistent. Same name as raihan."),
 "rayhan": ("رَيْحَان", "ریحان", "ریحان", "रैहान", "ریحان", "rayhan", "Arabic", "Male",
            "Arabic root ر و ح (r-w-ḥ); رَيْحَان (Rayḥān)", False, "high",
            "Rayhan is Arabic رَيْحَان (Rayḥān) 'fragrant herb, basil', from the root ر و ح (r-w-ḥ). CRITICAL SOURCE ERROR: the source gave 'عربي_Rayhan' (a placeholder prefix); the correct form is رَيْحَان. The source gloss 'Noble and blessed' is unsupported and has been replaced with the lexical sense. Same name as raihan."),
 "rayhanat": ("رَيْحَانَات", "ریحانات", "ریحانات", "रैहानात", "ریحانات", "rayhanat", "Arabic", "Female",
              "Arabic root ر و ح (r-w-ḥ); رَيْحَانَات (Rayḥānāt)", False, "high",
              "Rayhanat is Arabic رَيْحَانَات (Rayḥānāt), the plural of رَيْحَانَة (Rayḥāna) 'fragrant herb', used as a female given name. The source gloss 'Fragrant flowers' is broadly consistent."),
 "rayn": ("رَيْن", "رین", "رین", "रैन", "رین", "rayn", "Arabic", "Female",
          "Arabic رَيْن (Rayn)", False, "medium",
          "Rayn is recorded as Arabic رَيْن (Rayn), a female given name. The source gloss 'rain' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "rayna": ("رَيْنَا", "رینا", "رینا", "रैना", "رینا", "rayna", "Arabic", "Female",
           "Arabic رَيْنَا (Raynā)", False, "medium",
           "Rayna is recorded as Arabic رَيْنَا (Raynā), a female given name. The source gloss 'Joy, contentment' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "rayya": ("رَيَّا", "ریا", "ریا", "रैया", "ریا", "rayya", "Arabic", "Female",
           "Arabic root ر و ي (r-w-y); رَيَّا (Rayyā)", False, "high",
           "Rayya is Arabic رَيَّا (Rayyā) 'sated, refreshed' (feminine), from the root ر و ي (r-w-y). The source gloss 'Content, Satisfied, Joyful' is broadly consistent."),
 "rayyan": ("رَيَّان", "ریان", "ریان", "रैयान", "ریان", "rayyan", "Arabic", "Male",
            "Arabic root ر و ي (r-w-y); رَيَّان (Rayyān)", False, "high",
            "Rayyan is Arabic رَيَّان (Rayyān) 'sated, refreshed', from the root ر و ي (r-w-y). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as rayan."),
 "raz": ("رَاز", "راز", "راز", "राज़", "راز", "raz", "Persian", "Male",
         "Persian راز (rāz)", False, "high",
         "Raz is Persian راز (rāz) 'secret, mystery'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Secret, Mystery' is consistent."),
}
