# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 6 (alev..amaal)."""

GLOSSES = {
    "flame": {"en": "Flame, blaze", "ur": "شعلہ، لَو", "fa": "شعله، آتش", "hi": "लौ, ज्वाला", "ps": "لمبه، اور", "ar": "لهب، شعلة"},
    "exalted_sublime": {"en": "Exalted, sublime, high", "ur": "بلند، عالی، رفیع", "fa": "والا، بلند، عالی", "hi": "उच्च, महान, श्रेष्ठ", "ps": "لوړ، عالي", "ar": "عليّ، رفيع"},
    "words": {"en": "Words, terms, articulate sounds", "ur": "الفاظ، کلمات", "fa": "واژه‌ها، الفاظ", "hi": "शब्द, अल्फ़ाज़", "ps": "الفاظ، کلمې", "ar": "ألفاظ، كلمات"},
    "distinguisher": {"en": "The distinguisher, the one who separates truth from falsehood", "ur": "فاروق، حق و باطل میں فرق کرنے والا", "fa": "فاروق، جداکنندهٔ حق از باطل", "hi": "फ़ारूक़, सत्य-असत्य में भेद करने वाला", "ps": "فاروق، د حق او باطل جلا کوونکی", "ar": "الفاروق، الذي يفرق بين الحق والباطل"},
    "opener": {"en": "The opener, the conqueror", "ur": "فتاح، کھولنے والا", "fa": "فتاح، گشاینده", "hi": "फ़त्ताह, खोलने वाला", "ps": "فتاح، پرانیستونکی", "ar": "الفتاح، الذي يفتح"},
    "conqueror": {"en": "The conqueror, the opener", "ur": "فاتح، فتح کرنے والا", "fa": "فاتح، گشاینده", "hi": "फ़ातिह, विजेता", "ps": "فاتح، فتح کوونکی", "ar": "الفاتح، الذي يفتح"},
    "guide": {"en": "The guide", "ur": "ہادی، راہنما", "fa": "هادی، راهنما", "hi": "हादी, मार्गदर्शक", "ps": "هادي، لارښود", "ar": "الهادي، الذي يهدي"},
    "preserver": {"en": "The preserver, the protector", "ur": "حافظ، محافظ", "fa": "حافظ، نگهبان", "hi": "हाफ़िज़, रक्षक", "ps": "حافظ، ساتونکی", "ar": "الحافظ، الذي يحفظ"},
    "pilgrim": {"en": "The pilgrim (one who has performed the Hajj)", "ur": "حاجی، حج کرنے والا", "fa": "حاجی، زیارت‌کنندهٔ خانهٔ خدا", "hi": "हाजी, हज करने वाला", "ps": "حاجي، د حج کوونکی", "ar": "الحاج، الذي أدى الحج"},
    "praise": {"en": "Praise, gratitude", "ur": "حمد، شکر", "fa": "حمد، سپاس", "hi": "प्रशंसा, स्तुति", "ps": "حمد، مننه", "ar": "الحمد، شكر"},
    "praise_god": {"en": "Praise to God", "ur": "اللہ کی حمد", "fa": "حمد خدا", "hi": "ईश्वर की स्तुति", "ps": "د خدای حمد", "ar": "الحمد لله"},
    "cultivator": {"en": "The cultivator, the ploughman", "ur": "حارث، کاشتکار", "fa": "حارث، کشاورز", "hi": "हारिस, कृषक", "ps": "حارث، کروندګر", "ar": "الحارث، الذي يحرث"},
    "handsome": {"en": "Handsome, good, benefactor", "ur": "حسن، خوبصورت، نیک", "fa": "حسن، زیبا، نیکوکار", "hi": "हसन, सुंदर, भला", "ps": "حسن، ښکلی، ښه", "ar": "الحسن، الجميل، المحسن"},
    "life": {"en": "Life", "ur": "حیات، زندگی", "fa": "حیات، زندگی", "hi": "जीवन, हयात", "ps": "ژوند، حیات", "ar": "الحياة، العيش"},
    "sorrowful": {"en": "The sorrowful, the grieving", "ur": "حزین، غمگین", "fa": "حزین، اندوهگین", "hi": "हज़ीन, दुखी", "ps": "حزین، غمجن", "ar": "الحزين، المكتئب"},
    "hussein": {"en": "Diminutive of Ḥasan; grandson of the Prophet Muhammad", "ur": "حسین، حسن کی تصغیر", "fa": "حسین، تصغیر حسن", "hi": "हुसैन, हसन का लघु रूप", "ps": "حسین، د حسن کوچنی", "ar": "الحسين، تصغير الحسن"},
    "exalted_ali": {"en": "Exalted, sublime, high", "ur": "علی، بلند، عالی", "fa": "علی، والا، بلند", "hi": "अली, उच्च, महान", "ps": "علي، لوړ، عالي", "ar": "عليّ، رفيع"},
    "exalted_f": {"en": "Exalted, sublime (feminine)", "ur": "علیا، بلند، عالی", "fa": "علیا، والا، بلند", "hi": "अलिया, उच्च, महान", "ps": "عليا، لوړه، عاليه", "ar": "عليا، رفيعة"},
    "letter_alif": {"en": "The letter alif (first letter of the Arabic alphabet)", "ur": "حرف الف", "fa": "حرف الف", "hi": "अक्षर अलिफ़", "ps": "د الف توری", "ar": "حرف الألف"},
    "excellence": {"en": "Excellence, beautiful character, doing good", "ur": "احسان، نیکی، حسن سلوک", "fa": "احسان، نیکوکاری", "hi": "एहसान, भलाई, सदाचार", "ps": "احسان، ښېګڼه", "ar": "الإحسان، إتقان العمل"},
    "learned": {"en": "Learned, scholar, one who knows", "ur": "عالم، دانا، فاضل", "fa": "دانا، دانشمند", "hi": "ज्ञानी, विद्वान", "ps": "پوه، عالم", "ar": "عليم، عالم"},
    "learned_f": {"en": "Learned woman, scholar", "ur": "عالمہ، فاضلہ", "fa": "دانشمند، عالمه", "hi": "विदुषी, पंडिता", "ps": "عالمه، پوهه", "ar": "عليمة، عالمة"},
    "very_learned": {"en": "Very learned, most knowledgeable", "ur": "علام، بہت دانا", "fa": "علام، بسیار دانا", "hi": "अल्लाम, अत्यंत विद्वान", "ps": "علام، ډېر پوه", "ar": "علّام، كثير العلم"},
    "great_scholar": {"en": "Great scholar, authority", "ur": "علامہ، بڑا عالم", "fa": "علامه، دانشمند بزرگ", "hi": "अल्लामा, महाविद्वान", "ps": "علامه، لوی عالم", "ar": "علّامة، عالم كبير"},
    "joyful": {"en": "Joyful, happy, cheerful", "ur": "خوش، مسرور، شاداں", "fa": "شاد، خوشحال", "hi": "प्रसन्न, खुश, आनंदित", "ps": "خوشحاله، مړوند", "ar": "مبتهجة، فرِحة"},
    "diamond": {"en": "Diamond", "ur": "الماس، ہیرا", "fa": "الماس", "hi": "हीरा, अलमास", "ps": "الماس، الماس", "ar": "ألماس، ماس"},
    "guided_one": {"en": "The guided one (al-Mahdī)", "ur": "مہدی، ہدایت یافتہ", "fa": "مهدی، هدایت‌یافته", "hi": "महदी, मार्गदर्शित", "ps": "مهدي، هدایت شوی", "ar": "المهدي، الذي هداه الله"},
    "princess": {"en": "The princess, the noble lady", "ur": "امیرہ، شہزادی", "fa": "امیره، شاهزاده خانم", "hi": "अमीरा, राजकुमारी", "ps": "امیره، شهزادګۍ", "ar": "الأميرة، السيدة النبيلة"},
    "young_lion": {"en": "Young lion, brave warrior", "ur": "جواں شیر، بہادر", "fa": "شیر جوان، دلیر", "hi": "युवा शेर, वीर", "ps": "ځوان زمری، زړور", "ar": "شبل، شجاع"},
    "pure_safi": {"en": "The pure, the clear, the sincere", "ur": "صافی، پاک، خالص", "fa": "صافی، پاک، خالص", "hi": "साफ़ी, पवित्र, निर्मल", "ps": "صافي، پاک، خالص", "ar": "الصافي، النقي"},
    "kindnesses": {"en": "Kindnesses, favours, graces", "ur": "الطاف، مہربانیاں", "fa": "الطاف، لطف‌ها", "hi": "अलताफ़, कृपाएँ", "ps": "الطاف، مهربانۍ", "ar": "ألطاف، لطف"},
    "flyer": {"en": "The flyer, the one who flies", "ur": "طائر، اڑنے والا", "fa": "طائر، پرنده", "hi": "ताइर, उड़ने वाला", "ps": "طائر، الوتونکی", "ar": "الطائر، الذي يطير"},
    "iltutmish": {"en": "Turkish name of Iltutmish, third Sultan of Delhi", "ur": "التتمش، دہلی کا سلطان", "fa": "التتمش، سلطان دهلی", "hi": "इल्तुतमिश, दिल्ली का सुल्तान", "ps": "التتمش، د دهلي سلطان", "ar": "إلتتمش، سلطان دلهي"},
    "gold": {"en": "Gold, golden", "ur": "التون، سونا، سنہری", "fa": "آلتین، طلا، زرین", "hi": "अल्तिन, सोना, स्वर्ण", "ps": "التون، سره زر", "ar": "ذهب، ذهبي"},
    "alvand": {"en": "Alvand (a mountain range in Iran); Avestan 'swift, steed'", "ur": "الوند، ایران کا پہاڑی سلسلہ", "fa": "الوند، رشته‌کوه در ایران", "hi": "अलवंद, ईरान की पर्वत श्रृंखला", "ps": "الوند، د ایران د غرونو لړۍ", "ar": "الوند، سلسلة جبال في إيران"},
    "alawi": {"en": "Alawī, of/relating to ʿAlī", "ur": "علوی، علی سے منسوب", "fa": "علوی، منسوب به علی", "hi": "अलवी, अली से संबंधित", "ps": "علوي، د علي اړوند", "ar": "علوي، منسوب إلى علي"},
    "colors": {"en": "Colours", "ur": "الوان، رنگ", "fa": "الوان، رنگ‌ها", "hi": "अलवान, रंग", "ps": "الوان، رنګونه", "ar": "ألوان، صبغات"},
    "radiant": {"en": "The radiant, the luminous (al-Zahrāʾ)", "ur": "زہراء، روشن، چمکدار", "fa": "زهرا، درخشان", "hi": "ज़हरा, उज्ज्वल, दीप्तिमान", "ps": "زهرا، روښانه", "ar": "الزهراء، المشرقة"},
    "pillar": {"en": "Pillar, support, mainstay", "ur": "عماد، ستون، سہارا", "fa": "عماد، ستون، پشتیبان", "hi": "इमाद, स्तंभ, सहारा", "ps": "عماد، ستن، ملاتړ", "ar": "عماد، دعامة"},
    "hopes": {"en": "Hopes, aspirations", "ur": "آمال، امیدیں", "fa": "آمال، امیدها", "hi": "आमाल, आशाएँ", "ps": "آمال، هیلې", "ar": "آمال، أماني"},
    "noble_exalted": {"en": "Noble, exalted", "ur": "نجیب، بلند", "fa": "نجیب، والا", "hi": "कुलीन, उच्च", "ps": "نجیب، لوړ", "ar": "نبيل، مرفوع"},
    "noble_blessed": {"en": "Noble and blessed", "ur": "نجیب اور بابرکت", "fa": "نجیب و مبارک", "hi": "कुलीन और धन्य", "ps": "نجیب او برکت والا", "ar": "نبيل ومبارك"},
    "nourisher": {"en": "Nourisher, sustainer", "ur": "پالنے والی، رزق دینے والی", "fa": "پرورنده، روزی‌دهنده", "hi": "पोषक, पालने वाली", "ps": "پالونکې، روزي ورکوونکې", "ar": "المربية، الرازقة"},
    "light": {"en": "Light", "ur": "نور، روشنی", "fa": "نور، روشنایی", "hi": "प्रकाश, नूर", "ps": "رڼا، نور", "ar": "نور، ضياء"},
    "high": {"en": "High, elevated", "ur": "بلند، اونچا", "fa": "بلند، والا", "hi": "ऊँचा, उच्च", "ps": "لوړ، اوچت", "ar": "عالي، مرتفع"},
    "night_clouds": {"en": "Night and clouds", "ur": "رات اور بادل", "fa": "شب و ابر", "hi": "रात और बादल", "ps": "شپه او ورېځې", "ar": "ليل وسحاب"},
    "soft_gentle": {"en": "Soft, gentle, kind", "ur": "نرم، مہربان", "fa": "نرم، مهربان", "hi": "कोमल, दयालु", "ps": "نرم، مهربان", "ar": "لطيف، رحيم"},
    "protection": {"en": "Protection, shelter", "ur": "حفاظت، پناہ", "fa": "حفاظت، پناه", "hi": "सुरक्षा, आश्रय", "ps": "ساتنه، پناه", "ar": "حماية، ملجأ"},
    "brave_strong": {"en": "Brave and strong", "ur": "بہادر اور مضبوط", "fa": "دلیر و نیرومند", "hi": "वीर और बलवान", "ps": "زړور او پیاوړی", "ar": "شجاع، قوي"},
    "friend": {"en": "Friend, companion", "ur": "دوست، ساتھی", "fa": "دوست، همراه", "hi": "मित्र, साथी", "ps": "ملګری، مل", "ar": "صديق، رفيق"},
    "powerful": {"en": "Powerful, strong", "ur": "طاقتور، مضبوط", "fa": "توانا، نیرومند", "hi": "शक्तिशाली, बलवान", "ps": "ځواکمن، پیاوړی", "ar": "قوي، عزيز"},
    "gentle_soft_f": {"en": "Gentle, soft", "ur": "نرم، ملائم", "fa": "نرم، لطیف", "hi": "कोमल, मृदु", "ps": "نرمه، ملایمه", "ar": "لطيفة، ناعمة"},
    "majestic": {"en": "Majestic, radiant", "ur": "جلیل، روشن", "fa": "باشکوه، فروزان", "hi": "भव्य, उज्ज्वल", "ps": "لوی، روښانه", "ar": "جليل، مشرق"},
    "kind_devoted": {"en": "Kind, devoted", "ur": "مہربان، مخلص", "fa": "مهربان، فداکار", "hi": "दयालु, समर्पित", "ps": "مهربانه، مخلصه", "ar": "كريمة، مخلصة"},
    "gift_allah": {"en": "Gift from Allah", "ur": "اللہ کا تحفہ", "fa": "هدیهٔ خدا", "hi": "अल्लाह का उपहार", "ps": "د الله ډالۍ", "ar": "هدية من الله"},
    "light_allah": {"en": "Light of Allah", "ur": "اللہ کا نور", "fa": "نور خدا", "hi": "अल्लाह का प्रकाश", "ps": "د الله رڼا", "ar": "نور الله"},
    "night_dark": {"en": "Night, the dark one", "ur": "رات، تاریک", "fa": "شب، تاریک", "hi": "रात, अंधकार", "ps": "شپه، تیاره", "ar": "ليل، مظلم"},
    "night_ascending": {"en": "Night ascending", "ur": "چڑھتی رات", "fa": "شب برآینده", "hi": "चढ़ती रात", "ps": "خوځنده شپه", "ar": "ليل صاعد"},
    "support_exalted": {"en": "Support, exalted", "ur": "سہارا، بلند", "fa": "پشتیبان، والا", "hi": "सहारा, उच्च", "ps": "ملاتړ، لوړ", "ar": "نصرة، مرفوع"},
    "mother_ibrahim": {"en": "Mother of the prophet Ibrahim (a title)", "ur": "ابراہیم کی والدہ", "fa": "مادر ابراهیم", "hi": "इब्राहीम की माता", "ps": "د ابراهیم مور", "ar": "أم إبراهيم"},
    "father_many": {"en": "Father of many", "ur": "بہت لوگوں کا باپ", "fa": "پدر بسیاری", "hi": "अनेकों का पिता", "ps": "د ډېرو پلار", "ar": "أبو الجماهير"},
    "support_help": {"en": "Support, help", "ur": "مدد، سہارا", "fa": "کمک، پشتیبانی", "hi": "मदद, सहारा", "ps": "مرسته، ملاتړ", "ar": "عون، نصرة"},
    "unique_precious": {"en": "Unique, precious, rare", "ur": "منفرد، قیمتی، نایاب", "fa": "یگانه، گران‌بها، کمیاب", "hi": "अद्वितीय, बहुमूल्य, दुर्लभ", "ps": "ځانګړې، قیمتي، کمې", "ar": "فريدة، نفيسة"},
    "truth_knowledge": {"en": "Truth, knowledge", "ur": "سچ، علم", "fa": "حقیقت، دانش", "hi": "सत्य, ज्ञान", "ps": "رښتیا، پوهه", "ar": "حقيقة، علم"},
    "trustee": {"en": "The trustee, the guardian", "ur": "امین، نگہبان", "fa": "امین، نگهبان", "hi": "अमीन, संरक्षक", "ps": "امین، ساتونکی", "ar": "الأمين، الحفيظ"},
    "noble_bright": {"en": "Noble, bright", "ur": "نجیب، روشن", "fa": "نجیب، درخشان", "hi": "कुलीन, उज्ज्वल", "ps": "نجیبه، روښانه", "ar": "نبيلة، مشرقة"},
    "exalted_lofty": {"en": "Exalted, lofty, noble", "ur": "بلند، عالی، نجیب", "fa": "والا، بلند، نجیب", "hi": "उच्च, महान, कुलीन", "ps": "لوړ، عالي، نجیب", "ar": "عليّ، رفيع، نبيل"},
    "noble_exalted_born": {"en": "Noble, exalted, noble-born", "ur": "نجیب، بلند، نجیب زادہ", "fa": "نجیب، والا، نجیب‌زاده", "hi": "कुलीन, उच्च, कुलीन जन्मा", "ps": "نجیبه، لوړه، نجیبه زېږېدلې", "ar": "نبيلة، مرفوعة، كريمة الأصل"},
    "god_light": {"en": "God's light", "ur": "خدا کا نور", "fa": "نور خدا", "hi": "ईश्वर का प्रकाश", "ps": "د خدای رڼا", "ar": "نور الله"},
    "god_gift": {"en": "God's gift", "ur": "خدا کا تحفہ", "fa": "هدیهٔ خدا", "hi": "ईश्वर का उपहार", "ps": "د خدای ډالۍ", "ar": "عطية الله"},
    "pearl": {"en": "Pearl of great price", "ur": "بیش قیمت موتی", "fa": "مروارید گران‌بها", "hi": "बहुमूल्य मोती", "ps": "ګران‌بها مرغلره", "ar": "لؤلؤة ثمينة"},
    "righteous_wise": {"en": "Righteous, wise", "ur": "صالح، دانا", "fa": "صالح، دانا", "hi": "सालिह, बुद्धिमान", "ps": "صالح، پوه", "ar": "الصافي، الصالح"},
    "noble_handsome": {"en": "Noble, handsome", "ur": "نجیب، خوبصورت", "fa": "نجیب، زیبا", "hi": "कुलीन, सुंदर", "ps": "نجیب، ښکلی", "ar": "نبيل، وسيم"},
    "guide_messenger": {"en": "Guide, messenger", "ur": "راہنما، پیغام رساں", "fa": "راهنما، پیام‌آور", "hi": "मार्गदर्शक, संदेशवाहक", "ps": "لارښود، پیغام رسوونکی", "ar": "دليل، رسول"},
    "gifted_noble": {"en": "Gifted, noble", "ur": "باصلاحیت، نجیب", "fa": "بااستعداد، نجیب", "hi": "प्रतिभाशाली, कुलीन", "ps": "ځیرک، نجیب", "ar": "موهوب، نبيل"},
    "flowering": {"en": "The flowering one, the radiant", "ur": "زہراء، کھلنے والی", "fa": "زهرا، شکوفا", "hi": "ज़हरा, खिलने वाली", "ps": "زهرا، ګل کوونکې", "ar": "الزهراء، المزهرة"},
}

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "alev": ("آلو", "آلو", "آلو", "आलेव", "آلو", "flame", "Turkish", "Unisex", None, "not established", "high", "Turkish alev ('flame, blaze'). The source record's gloss 'Nightingale' is unsupported (the Turkish word for nightingale is bülbül)."),
 "aleya": ("عليا", "علیا", None, "अलिया", "عليا", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "ʿUlyā ('sublime, exalted')."),
 "aleyah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية."),
 "alfaaz": ("ألفاظ", "الفاظ", None, "अल्फ़ाज़", "الفاظ", "words", "Arabic", "Male", "ل ف ظ", "not established", "high", "Alfāẓ, plural of لفظ ('word, utterance'); widely used in Urdu. The source record's gloss 'Words and language' is a reasonable rendering."),
 "alfani": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Wise, Intellectual' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alfarooq": ("الفاروق", "فاروق", None, "फ़ारूक़", "فاروق", "distinguisher", "Arabic", "Male", "ف ر ق", "not established", "high", "Al-Fārūq ('the distinguisher'), the epithet of ʿUmar ibn al-Khaṭṭāb (d. 644)."),
 "alfatah": ("الفتاح", "فتاح", None, "फ़त्ताह", "فتاح", "opener", "Arabic", "Male", "ف ت ح", "root ف ت ح occurs in the Qur'an; الفتاح is a divine name", "high", "Al-Fattāḥ ('the opener'), a divine name."),
 "alfatih": ("الفاتح", "فاتح", None, "फ़ातिह", "فاتح", "conqueror", "Arabic", "Male", "ف ت ح", "not established", "high", "Al-Fātiḥ ('the conqueror, the opener'); also the title of Sultan Mehmed II (r. 1451-1481)."),
 "alfaz": ("ألفاظ", "الفاظ", None, "अल्फ़ाज़", "الفاظ", "words", "Arabic", "Male", "ل ف ظ", "not established", "high", "Variant romanization of ألفاظ. The source record's gloss 'Knowledge, Wisdom' is unsupported."),
 "alfiyaa": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Thriving, Flourishing, Prosperous' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alhadi": ("الهادي", "ہادی", None, "हादी", "هادي", "guide", "Arabic", "Male", "ه د ي", "root ه د ي occurs in the Qur'an; الهادي is a divine name", "high", "Al-Hādī ('the guide'), a divine name."),
 "alhafiz": ("الحافظ", "حافظ", None, "हाफ़िज़", "حافظ", "preserver", "Arabic", "Male", "ح ف ظ", "root ح ف ظ occurs in the Qur'an; الحافظ is a divine name", "high", "Al-Ḥāfiẓ ('the preserver'), a divine name; also a title for one who has memorised the Qur'an."),
 "alhaij": ("الحاج", "حاجی", None, "हाजी", "حاجي", "pilgrim", "Arabic", "Male", "ح ج ج", "not established", "high", "Al-ḥājj ('the pilgrim'), a title for one who has performed the Hajj. The source record's spelling is a variant romanization."),
 "alhajj": ("الحاج", "حاج", None, "हज", "حاج", "pilgrim", "Arabic", "Male", "ح ج ج", "not established", "high", "Al-ḥajj ('the pilgrimage'); as a title, al-ḥājj ('the pilgrim')."),
 "alhamd": ("الحمد", "حمد", None, "हम्द", "حمد", "praise", "Arabic", "Male", "ح م د", "الحمد occurs in the Qur'an (Sūrat al-Fātiḥa 1:2)", "high", "Al-ḥamd ('praise, gratitude')."),
 "alhamdu": ("الحمد", "الحمد", None, "अलहम्दु", "الحمد", "praise_god", "Arabic", "Unisex", "ح م د", "الحمد لله occurs in the Qur'an (Sūrat al-Fātiḥa 1:2)", "high", "Al-ḥamdu ('the praise'), as in al-ḥamdu li-llāh."),
 "alhan": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'The One Giving Grace' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alharith": ("الحارث", "حارث", None, "हारिस", "حارث", "cultivator", "Arabic", "Male", "ح ر ث", "not established", "high", "Al-Ḥārith ('the cultivator, ploughman'), a pre-Islamic and early Islamic personal name. The source record's gloss 'The One Sustained by Allah' is unsupported."),
 "alhasan": ("الحسن", "حسن", None, "हसन", "حسن", "handsome", "Arabic", "Male", "ح س ن", "root ح س ن occurs in the Qur'an; الحسن is a normal Arabic adjective", "high", "Al-Ḥasan ('the handsome, the good'), grandson of the Prophet Muhammad (d. 670)."),
 "alhayat": ("الحياة", "حیات", None, "हयात", "حيات", "life", "Arabic", "Female", "ح ي ي", "الحياة occurs in the Qur'an as a normal Arabic noun", "high", "Al-ḥayāt ('life')."),
 "alhazin": ("الحزين", "حزین", None, "हज़ीन", "حزين", "sorrowful", "Arabic", "Male", "ح ز ن", "not established", "high", "Al-ḥazīn ('the sorrowful, the grieving'). The source record's gloss 'The Victorious' is unsupported."),
 "alhusain": ("الحسين", "حسین", None, "हुसैन", "حسين", "hussein", "Arabic", "Male", "ح س ن", "not established", "high", "Al-Ḥusayn, diminutive of al-Ḥasan; grandson of the Prophet Muhammad (d. 680)."),
 "alhussein": ("الحسين", "حسین", None, "हुसैन", "حسين", "hussein", "Arabic", "Male", "ح س ن", "not established", "high", "Variant romanization of الحسين."),
 "ali": ("علي", "علی", None, "अली", "علي", "exalted_ali", "Arabic", "Male", "ع ل و", "root ع ل و occurs in the Qur'an; علي is a normal Arabic adjective and a divine name", "high", "ʿAlī ('exalted, sublime'), also the name of ʿAlī ibn Abī Ṭālib (d. 661). The source record left origin and gender blank."),
 "alia": ("عليا", "علیا", None, "अलिया", "عليا", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "ʿUlyā ('sublime, exalted')."),
 "aliaa": ("علياء", "علیاء", None, "अलिया", "علياء", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "ʿAlyāʾ ('sublimity, exaltedness')."),
 "aliah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية."),
 "alif": ("ألف", "الف", None, "अलिफ़", "الف", "letter_alif", "Arabic", "Male", "أ ل ف", "not established", "medium", "Alif, the first letter of the Arabic alphabet. The source record's gloss 'First letter of the Arabic alphabet' is a description of the letter rather than a lexical meaning."),
 "alifa": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble, Exalted, Intelligent' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alih": ("علي", "علی", None, "अली", "علي", "exalted_ali", "Arabic", "Male", "ع ل و", "root ع ل و occurs in the Qur'an; علي is a normal Arabic adjective and a divine name", "medium", "Variant romanization of علي."),
 "aliha": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Exalted One' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alihsan": ("الإحسان", "احسان", None, "एहसान", "احسان", "excellence", "Arabic", "Male", "ح س ن", "root ح س ن occurs in the Qur'an; الإحسان is a normal Arabic noun", "high", "Al-iḥsān ('excellence, doing good, beautiful character')."),
 "alika": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Unique, Precious, Rare' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alim": ("عليم", "علیم", None, "अलीम", "عليم", "learned", "Arabic", "Male", "ع ل م", "عليم occurs in the Qur'an as a divine name", "high", "ʿAlīm ('learned, all-knowing'), a divine name."),
 "alima": ("عليمة", "علیمہ", None, "अलीमा", "عليمه", "learned_f", "Arabic", "Female", "ع ل م", "not established", "high", "Feminine of عليم. The source record's gloss 'Truth, Knowledge' is an approximation."),
 "alimah": ("عليمة", "علیمہ", None, "अलीमा", "عليمه", "learned_f", "Arabic", "Female", "ع ل م", "not established", "high", "Variant romanization of عليمة."),
 "aliman": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'The Trustee, The Guardian' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alimani": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'The learned one' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble, Bright' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "aliq": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Exalted, Sublime' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alir": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Exalted, Sublime' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alisa": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble, Exalted' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alishba": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble and blessed' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "aliya": ("عليا", "علیا", None, "अलिया", "عليا", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "ʿUlyā ('sublime, exalted')."),
 "aliyah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية."),
 "aliyan": ("عليان", "علیان", None, "अलियान", "عليان", "exalted_lofty", "Arabic", "Male", "ع ل و", "not established", "medium", "Related to علي ('exalted'). The source record's gloss 'Exalted, lofty, noble' is a reasonable rendering."),
 "aliyat": ("عليات", "علیات", None, "अलियात", "عليات", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "medium", "Plural/derived form from عليا. The source record's gloss 'Exalted, Sublime, High, Noble' is a reasonable rendering."),
 "aliyya": ("عليا", "علیا", None, "अलिया", "عليا", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عليا."),
 "aliyyah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية."),
 "aliza": ("عليزة", "علیزہ", None, "अलीज़ा", "عليزه", "joyful", "Hebrew", "Female", None, "not established", "medium", "Aliza is a Hebrew name meaning 'joyful' (עליזה). The source record's gloss 'Noble, exalted' is unsupported."),
 "alizah": ("عليزة", "علیزہ", None, "अलीज़ा", "عليزه", "joyful", "Hebrew", "Female", None, "not established", "medium", "Variant romanization of عليزة."),
 "alizeh": ("عليزة", "علیزہ", None, "अलीज़े", "عليزه", "joyful", "Hebrew", "Female", None, "not established", "medium", "Variant romanization of عليزة. The source record's gloss 'Noble, Exalted, Noble Born' is unsupported."),
 "allal": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'God's Light' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "allam": ("علّام", "علام", None, "अल्लाम", "علام", "very_learned", "Arabic", "Male", "ع ل م", "not established", "medium", "ʿAllām ('very learned'), an intensive form of عليم. The source record's gloss 'Exalted, Sublime' is unsupported."),
 "allama": ("علّامة", "علامہ", None, "अल्लामा", "علامه", "great_scholar", "Arabic", "Male", "ع ل م", "not established", "high", "ʿAllāma ('great scholar, authority'), a title used for eminent scholars."),
 "alleyah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية."),
 "alliyah": ("عالية", "عالیہ", None, "अलिया", "عاليه", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "Variant romanization of عالية. The source record's gloss 'God's Gift' is unsupported."),
 "alma": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Nourisher, Sustainer' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "almaas": ("ألماس", "الماس", "الماس", "अलमास", "الماس", "diamond", "Persian", "Unisex", None, "not established", "high", "Persian almās ('diamond'), from Greek adamas. The source record classified it as Arabic, which is incorrect."),
 "almahdi": ("المهدي", "مہدی", None, "महदी", "مهدي", "guided_one", "Arabic", "Male", "ه د ي", "not established", "high", "Al-Mahdī ('the guided one'), an eschatological figure in Islamic tradition."),
 "alman": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Exalted, noble' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "almas": ("ألماس", "الماس", "الماس", "अलमास", "الماس", "diamond", "Persian", "Female", None, "not established", "high", "Persian almās ('diamond'). The source record classified it as Arabic, which is incorrect."),
 "almasa": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'The Light' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "almash": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "almasi": ("ألماسي", "الماسی", "الماسی", "अलमासी", "الماسي", "diamond", "Persian", "Unisex", None, "not established", "medium", "Nisba adjective from Persian almās ('diamond'). The source record classified it as Arabic, which is incorrect."),
 "almaz": ("ألماس", "الماس", "الماس", "अलमाज़", "الماس", "diamond", "Persian", "Unisex", None, "not established", "medium", "Persian almās ('diamond'); also an Amharic name meaning 'diamond'. The source record's gloss 'Help from Allah' is unsupported."),
 "almeera": ("الأميرة", "امیرہ", None, "अमीरा", "اميره", "princess", "Arabic", "Female", "أ م ر", "not established", "high", "Al-amīra ('the princess')."),
 "almir": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'High' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "almira": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble and blessed' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "aloosh": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Night and clouds' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alperen": ("آلبرن", "آلپرن", "آلپرن", "अल्पेरेन", "آلپرن", "young_lion", "Turkish", "Male", None, "not established", "high", "Turkish alperen ('young lion, brave warrior'), from alp ('hero') + eren ('saint, warrior'). The source record classified it as Arabic, which is incorrect."),
 "alsafi": ("الصافي", "صافی", None, "साफ़ी", "صافي", "pure_safi", "Arabic", "Male", "ص ف و", "not established", "high", "Al-ṣāfī ('the pure, the clear, the sincere')."),
 "alshan": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble, handsomeness' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "altaaf": ("ألطاف", "الطاف", None, "अलताफ़", "الطاف", "kindnesses", "Arabic", "Male", "ل ط ف", "not established", "high", "Altāf, plural of لطف ('kindness, favour'). The source record's gloss 'Guide, Messenger' is unsupported."),
 "altaf": ("ألطاف", "الطاف", None, "अलताफ़", "الطاف", "kindnesses", "Arabic", "Male", "ل ط ف", "not established", "high", "Variant romanization of ألطاف."),
 "altair": ("الطائر", "طائر", None, "ताइर", "طائر", "flyer", "Arabic", "Male", "ط ي ر", "not established", "medium", "Al-ṭāʾir ('the flyer'); also the name of the star Altair (from Arabic al-nasr al-ṭāʾir)."),
 "altamash": ("إلتتمش", "التتمش", None, "इल्तुतमिश", "التتمش", "iltutmish", "Turkish", "Male", None, "not established", "high", "Altamash/Iltutmish, the Turkish name of Shams al-Dīn Iltutmish (d. 1236), third Sultan of Delhi and effective founder of the Delhi Sultanate. The source record's gloss 'Gifted, Noble' is unsupported."),
 "althaf": ("ألطاف", "الطاف", None, "अलताफ़", "الطاف", "kindnesses", "Arabic", "Male", "ل ط ف", "not established", "high", "Variant romanization of ألطاف. The source record's gloss 'Protection, Shelter' is unsupported."),
 "altin": ("آلتين", "التین", "آلتین", "अल्तिन", "آلتين", "gold", "Turkish", "Unisex", None, "not established", "high", "Turkish altın ('gold, golden'). The source record classified it as Arabic, which is incorrect."),
 "altun": ("آلتون", "التون", "آلتون", "अल्तुन", "آلتون", "gold", "Turkish", "Male", None, "not established", "high", "Turkish altun, a variant of altın ('gold'). The source record classified it as Arabic, which is incorrect."),
 "alvand": ("الوند", "الوند", "الوند", "अलवंद", "الوند", "alvand", "Persian", "Male", None, "not established", "high", "Alvand (الوند), a mountain range in western Iran; from Avestan Aurvañt ('swift, steed, warrior'). The source record classified it as Arabic, which is incorrect."),
 "alvi": ("علوي", "علوی", None, "अलवी", "علوي", "alawi", "Arabic", "Male", "ع ل و", "not established", "high", "ʿAlawī, nisba adjective from علي. The source record's gloss 'Friend, Companion' is unsupported."),
 "alvian": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Powerful, Strong' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alvina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Gentle, Soft' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alvira": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Noble and blessed' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alwan": ("ألوان", "الوان", None, "अलवान", "الوان", "colors", "Arabic", "Male", "ل و ن", "not established", "high", "Alwān, plural of لون ('colour'). The source record's gloss 'Majestic, Radiant' is unsupported."),
 "alwand": ("الوند", "الوند", "الوند", "अलवंद", "الوند", "alvand", "Persian", "Male", None, "not established", "high", "Variant romanization of الوند. The source record classified it as Arabic, which is incorrect."),
 "alwina": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Kind, Devoted' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alya": ("عليا", "علیا", None, "अलिया", "عليا", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "ʿUlyā ('sublime, exalted')."),
 "alyaa": ("علياء", "علیاء", None, "अलिया", "علياء", "exalted_f", "Arabic", "Female", "ع ل و", "not established", "high", "ʿAlyāʾ ('sublimity, exaltedness')."),
 "alyaan": ("عليان", "علیان", None, "अलियान", "عليان", "gift_allah", "Arabic", "Male", "ع ل و", "not established", "low", "The source record's gloss 'Gift from Allah' could not be matched to a Tier-A/B lexical source. The form is related to علي ('exalted'). The identification is uncertain."),
 "alyan": ("عليان", "علیان", None, "अलियान", "عليان", "light_allah", "Arabic", "Unisex", "ع ل و", "not established", "low", "The source record's gloss 'Light of Allah' could not be matched to a Tier-A/B lexical source. The form is related to علي ('exalted'). The identification is uncertain."),
 "alyana": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Night, dark one' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alyas": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Night ascending' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alyazia": ("العزيزية", "العزیزیہ", None, "अलयाज़िया", "العزيزيه", "noble_exalted", "Arabic", "Female", "ع ز ز", "not established", "low", "The source record's gloss 'Noble, Exalted' could not be matched to a Tier-A/B lexical source. The form resembles العزيزية. The identification is uncertain."),
 "alza": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Support, Exalted' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "alzahra": ("الزهراء", "زہراء", None, "ज़हरा", "زهرا", "radiant", "Arabic", "Female", "ز ه ر", "not established", "high", "Al-Zahrāʾ ('the radiant, the luminous'), the epithet of Fāṭima, daughter of the Prophet Muhammad. The source record's gloss 'The Flowering One' is an approximation."),
 "ama": (None, None, None, None, None, None, "Unknown", "Unknown", None, "not established", "unverified", "The source record's gloss 'Mother of prophet Ibrahim' could not be matched to a Tier-A/B lexical source and no script form was supplied. No gloss is asserted."),
 "amaad": ("عماد", "عماد", None, "इमाद", "عماد", "pillar", "Arabic", "Male", "ع م د", "not established", "high", "ʿImād ('pillar, support, mainstay'). The source record's gloss 'Father of many' is unsupported."),
 "amaal": ("آمال", "آمال", None, "आमाल", "آمال", "hopes", "Arabic", "Female", "أ م ل", "not established", "high", "Āmāl, plural of أمل ('hope'). The source record's gloss 'Support, Help' is unsupported."),
}
