# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 41 (meraj..mona).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": meraj -> ميراج (should be مِعْرَاج);
   merwa -> فاطمة (a different name entirely); meryem -> مرئم (should be مَرْيَم);
   midhat -> مِذْهَات (should be مِدْحَت); mifzal -> أحمد (a different name);
   mihad -> ميهاد (should be مِهَاد); mihran -> ميهران (should be مِهْرَان);
   mika -> Latin "mika"; misba -> مصبى (should be مِصْبَاح); misbah -> placeholder
   "عربي_Misbah"; moin -> placeholder "عربي_Moin"; mohga -> علي (a different name);
   mohib -> موهب (should be مُحِبّ); mohid -> موحيد (should be مُوحِد);
   moeez -> مؤيز (should be مُعِزّ); moez -> مؤذ (should be مُعِزّ);
   moemen -> معمن (should be مُؤْمِن); moein -> موئن (should be مُعِين);
   moktar -> مُكْتَار (should be مُخْتَار); momina -> مُمِنَة (should be مُؤْمِنَة);
   miftahul -> مفتاحل (should be مِفْتَاحُ الْـ); miran -> ميرا (should be مِيرَان);
   mirwais -> مرويس (should be مِيرْوَيْس); mirza -> مرزا (should be مِيرْزَا);
   mirzali -> مرزالي (should be مِيرْزَا عَلِي); misaq -> مساق (should be مِيثَاق);
   mishkat -> ميشكات (should be مِشْكَاة); mizanur -> ميزانور (should be مِيزَانُور);
   mizna -> ميزنة (should be مِزْنَة); modassir -> مدثر (should be مُدَّثِّر);
   moeed -> مؤيد (should be مُؤَيَّد); moazzam/moazzem -> معظم (should be مُعَظَّم);
   mokbul -> مكبول (should be مَقْبُول); mokhtar -> مُخْتَار (ok); miqdad ok.
 * EMPTY STUBS (8-key records, no data): misk, mona.
 * MISLABELLED ORIGIN: meral (Turkish), meryem (Turkish), mikhail (Russian/Greek),
   misha (Russian/Hebrew), mishael (Hebrew), mishka (Russian), mitra (Persian),
   mirza (Persian), mirwais (Pashto), minoo (Persian), modupe (Yoruba),
   mika (Latin/European), mir (Persian), mihran/mihri (Persian).
 * DEGARBLED GLOSSES: meraj "Journey to the Heights", meral "Bright, clear,
   shining", meriem "Beloved", mersiha "Thankful, Grateful", merwa "Desirable,
   Precious", meryem "Beloved", meshaal "Guide, Aide, Companion", mesk "Small
   fish", miad "River", midhat "Grace, Beauty, Generosity", midlaj "Delicate,
   tender, gentle", miesha "Moon Goddess", mifrah "A place of learning and
   guidance", mifzal "A fortress, a stronghold", mihad "Deliverer, Guide",
   mihran "Kind and Just", mihri "Seeker of water", mika "Small",
   mikail "Like Allah", milad "Birthday, Birth" (ok), mina "Intensive labor or
   struggle", minaa "Love and Affection", minah "Gift from Allah" (ok),
   minahil "Delightful, Gracious", minal "Light, Delight", minha "Delicate,
   Tender", minhaj "A guide, a path" (ok), minhal "Gift from God", minna
   "Tender, Gracious", minnat "Love, affection", minoo "Gift of God",
   miqdad "Companion of the Prophet", mir "Moon, Light", miradi "Bright,
   radiant", mirah "Guiding Light", miraj "The Night Journey" (ok), miral
   "Star, Light, Guiding", miran "Gift of God", mirsad "Guide, Leader",
   mirwais "Master of the nobles", mirza "Prince or Noble Born" (ok),
   mirzali "Prince's Heir", misal "Sample, Model, Example" (ok), misam
   "Seeker, explorer", misaq "Covenant, agreement" (ok), misba "Guide,
   Companion", misbaah "Guide, Light", misbah "Noble and blessed", misha
   "Who is like God?", mishaal "Torch, Lamp" (ok), mishael "Who is like God?",
   mishal "Gift from God", mishel "Moon-like", mishka "Gift from God",
   mishkat "Arabic: A place where medicines are kept", miski "Honeycomb",
   misri "Egyptian" (ok), mitra "Mythological goddess of covenants", mizan
   "Justice, Balance" (ok), mizanur "Balance, Scales", mizna "Delight, Joy,
   Happiness", moaz "Brightness, Light", moazzam "Glory, Honour", moazzem
   "Warner", mobarak "Blessed" (ok), mobeen "Present, Existent", mobin
   "Intelligent, Wise", modassir "Achiever, Victorious", modupe "Gift from
   God", moeed "Traveler", moeen "Soft, gentle", moeez "Guide, Leader",
   moein "Gifted, Gracious", moemen "Believer, one who trusts and relies on
   God" (ok), moez "Guide, Leader", mohabbat "Love, Affection" (ok),
   mohga "Blessed, Pure", mohib "Lover, admirer" (ok), mohid "Beloved",
   mohsin "Benefactor, Doer of good" (ok), moin "Noble and blessed",
   moiz "Desirable, Precious", mojtaba "Guided", mokbul "Gift, Blessing",
   mokhtar "Chosen One, Elect" (ok), moktar "Powerful, Capable", momin
   "Faithful, Believer" (ok), momina "Beloved, Dear One".
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated40 import GLOSSES as _G40

GLOSSES = dict(_G40)
GLOSSES.update({
    "ascension": {"en": "Ascension, night journey", "ur": "معراج، آسمان کی سیر", "fa": "معراج، سفر آسمانی", "hi": "मेराज, आकाश-यात्रा", "ps": "معراج، آسماني سفر", "ar": "الْمِعْرَاج، الصُّعُود، الْعُرُوج"},
    "mary": {"en": "Mary; a female given name", "ur": "مریم (زنانہ نام)", "fa": "مریم (نام زنانہ)", "hi": "मरियम (स्त्री नाम)", "ps": "مریم (ښځينه نوم)", "ar": "مَرْيَم (اسم علم مؤنث)"},
    "marwa": {"en": "Marwa; a hill in Mecca", "ur": "مروہ، مکہ کی پہاڑی", "fa": "مروه، تپه‌ای در مکه", "hi": "मरवा, मक्का की पहाड़ी", "ps": "مروه، د مکې غونډۍ", "ar": "الْمَرْوَة، تَلّ فِي مَكَّة"},
    "lamp": {"en": "Lamp, light, lantern", "ur": "چراغ، روشنی، مصباح", "fa": "چراغ، نور، مصباح", "hi": "दीपक, प्रकाश, मिस्बाह", "ps": "څراغ، رڼا", "ar": "الْمِصْبَاح، السِّرَاج، النُّور"},
    "torch": {"en": "Torch, flame, light", "ur": "مشعل، شعلہ، روشنی", "fa": "مشعل، شعله، نور", "hi": "मशाल, ज्वाला, प्रकाश", "ps": "مشعل، اور", "ar": "الْمِشْعَل، الشُّعْلَة، النُّور"},
    "musk": {"en": "Musk", "ur": "مشک، خوشبو", "fa": "مشک، خوشبو", "hi": "कस्तूरी, मुश्क", "ps": "مشک، خوږه بوی", "ar": "الْمِسْك، الطِّيب، الْعِطْر"},
    "appointment": {"en": "Appointment, promise, fixed time", "ur": "میعاد، وعدہ، مقررہ وقت", "fa": "میعاد، وعده، زمان معین", "hi": "मीयाद, वादा, नियत समय", "ps": "میعاد، وعده", "ar": "الْمِيعَاد، الْوَعْد، الْوَقْت الْمُعَيَّن"},
    "praise_midhat": {"en": "Praise, commendation", "ur": "مدحت، تعریف، ستائش", "fa": "مدحت، ستایش، تحسین", "hi": "मिदहत, प्रशंसा, स्तुति", "ps": "مدحت، ستاینه", "ar": "الْمِدْحَة، الثَّنَاء، الْمَدْح"},
    "key": {"en": "Key, opener", "ur": "چابی، کلید، مفتاح", "fa": "کلید، مفتاح", "hi": "चाबी, कुंजी, मिफ़्ताह", "ps": "کیلي، مفتاح", "ar": "الْمِفْتَاح، الْفَاتِح"},
    "generous_mifdal": {"en": "Very generous, bountiful", "ur": "بہت سخی، فیاض", "fa": "بسیار بخشنده، سخاوتمند", "hi": "अति उदार, दानवीर", "ps": "ډېر سخي، فیاض", "ar": "الْمِفْضَال، الْكَرِيم، الْجَوَاد"},
    "cradle": {"en": "Cradle, bed, resting place", "ur": "بستر، پالنا، آرام گاہ", "fa": "گهواره، بستر، آرامگاه", "hi": "पालना, शय्या, विश्राम-स्थल", "ps": "بستر، زانگو", "ar": "الْمِهَاد، الْفِرَاش، الْمَهْد"},
    "mihran": {"en": "Mihran; a Persian male given name", "ur": "مہران (فارسی نام)", "fa": "مهران (نام مردانہ)", "hi": "मिहरान (फ़ारसी नाम)", "ps": "مهران (فارسي نوم)", "ar": "مِهْرَان (اسم علم مذكر فارسي)"},
    "mihri": {"en": "Mihri; a Persian female given name", "ur": "مہری (فارسی نام)", "fa": "مهری (نام زنانہ)", "hi": "मिहरी (फ़ारसी नाम)", "ps": "مهری (فارسي نوم)", "ar": "مِهْرِي (اسم علم مؤنث فارسي)"},
    "michael": {"en": "Michael; an archangel's name", "ur": "میکائیل، فرشتہ", "fa": "میکائیل، فرشته", "hi": "मीकाईल, फ़रिश्ता", "ps": "میکائیل، پرښته", "ar": "مِيكَائِيل، الْمَلَك"},
    "birth": {"en": "Birth, nativity", "ur": "میلاد، پیدائش، ولادت", "fa": "میلاد، زادروز، تولد", "hi": "मीलाद, जन्म, जन्मदिन", "ps": "میلاد، زوکړه", "ar": "الْمِيلَاد، الْوِلَادَة، الْمَوْلِد"},
    "mina_place": {"en": "Mina; a place near Mecca", "ur": "منیٰ، مکہ کے قریب مقام", "fa": "منی، مکانی نزدیک مکه", "hi": "मिना, मक्का के निकट स्थान", "ps": "منی، د مکې نږدې ځای", "ar": "مِنَى، مَوْضِع قُرْب مَكَّة"},
    "grant": {"en": "Gift, grant, bestowal", "ur": "منحت، عطیہ، بخشش", "fa": "منحت، عطیه، بخشش", "hi": "अनुदान, उपहार, अता", "ps": "منحت، ډالۍ", "ar": "الْمِنْحَة، الْعَطِيَّة، الْهِبَة"},
    "attainment": {"en": "Attainment, achievement, acquisition", "ur": "منال، حصول، کامیابی", "fa": "منال، دستیابی، کامیابی", "hi": "मनाल, प्राप्ति, उपलब्धि", "ps": "منال، لاسته راوړنه", "ar": "الْمَنَال، الْحُصُول، الْإِدْرَاك"},
    "method": {"en": "Path, method, program", "ur": "منہاج، راستہ، طریقہ", "fa": "منهاج، راه، روش", "hi": "मिन्हाज, मार्ग, पद्धति", "ps": "منهاج، لار، طریقه", "ar": "الْمِنْهَاج، الطَّرِيق، الْمَسْلَك"},
    "spring": {"en": "Spring, watering place", "ur": "منہل، چشمہ، آبشخور", "fa": "منهل، چشمه، آبشخور", "hi": "मिन्हल, स्रोत, जलाशय", "ps": "منهل، چینه", "ar": "الْمِنْهَل، الْعَيْن، الْمَوْرِد"},
    "favour": {"en": "Favour, grace, kindness", "ur": "منت، احسان، مہربانی", "fa": "منت، لطف، احسان", "hi": "मिन्नत, कृपा, एहसान", "ps": "منت، لطف", "ar": "الْمِنَّة، الْفَضْل، الْإِحْسَان"},
    "minoo": {"en": "Minoo; a Persian female given name", "ur": "مینو (فارسی نام)", "fa": "مینو (نام زنانہ)", "hi": "मीनू (फ़ारसी नाम)", "ps": "مینو (فارسي نوم)", "ar": "مِينُو (اسم علم مؤنث فارسي)"},
    "paradise": {"en": "Paradise, heaven", "ur": "جنت، بہشت، فردوس", "fa": "بهشت، فردوس، جنت", "hi": "स्वर्ग, बहिश्त, जन्नत", "ps": "جنت، فردوس", "ar": "الْجَنَّة، الْفِرْدَوْس، النَّعِيم"},
    "miqdad": {"en": "Miqdad; a male given name", "ur": "مقداد (مردانہ نام)", "fa": "مقداد (نام مردانہ)", "hi": "मिक़दाद (पुरुष नाम)", "ps": "مقداد (نر نوم)", "ar": "مِقْدَاد (اسم علم مذكر)"},
    "mir": {"en": "Mir; a title and male given name", "ur": "میر، سردار، نام", "fa": "میر، سردار، نام", "hi": "मीर, सरदार, नाम", "ps": "میر، مشر", "ar": "مِير (لقب واسم علم مذكر)"},
    "muradi": {"en": "Muradi; of Murad, belonging to Murad", "ur": "مرادی، مراد سے منسوب", "fa": "مرادی، منسوب به مراد", "hi": "मुरादी, मुराद से", "ps": "مرادي، د مراد اړوند", "ar": "الْمُرَادِي، مَنْسُوب إِلَى الْمُرَاد"},
    "miraj": {"en": "Miraj; ascension, night journey", "ur": "معراج، آسمان کی سیر", "fa": "معراج، سفر آسمانی", "hi": "मिराज, आकाश-यात्रा", "ps": "معراج، آسماني سفر", "ar": "الْمِعْرَاج، الصُّعُود، الْعُرُوج"},
    "miran": {"en": "Miran; a male given name", "ur": "میران (مردانہ نام)", "fa": "میران (نام مردانہ)", "hi": "मीरान (पुरुष नाम)", "ps": "میران (نر نوم)", "ar": "مِيرَان (اسم علم مذكر)"},
    "watchtower": {"en": "Watchtower, lookout, ambush", "ur": "مرصد، نگاہ گاہ، گھات", "fa": "مرصد، دیده‌بانی، کمین", "hi": "मिरसाद, प्रहरी-स्थल, घात", "ps": "مرصد، کتنځی", "ar": "الْمِرْصَاد، الْمَرْقَب، الْمَكْمَن"},
    "mirwais": {"en": "Mirwais; a Pashto male given name", "ur": "میرویس (پشتو نام)", "fa": "میرویس (نام پشتو)", "hi": "मीरवैस (पश्तो नाम)", "ps": "میرویس (پښتو نوم)", "ar": "مِيرْوَيْس (اسم علم مذكر بشتوني)"},
    "mirza": {"en": "Mirza; a Persian title and given name", "ur": "مرزا، خطاب و نام", "fa": "میرزا، لقب و نام", "hi": "मिर्ज़ा, उपाधि व नाम", "ps": "میرزا، لقب او نوم", "ar": "مِيرْزَا (لقب واسم علم مذكر فارسي)"},
    "mirzali": {"en": "Mirzali; Mirza Ali", "ur": "مرزاعلی، مرزا علی", "fa": "میرزاعلی", "hi": "मिर्ज़ा अली", "ps": "میرزا علي", "ar": "مِيرْزَا عَلِي (اسم علم مذكر)"},
    "example": {"en": "Example, model, instance", "ur": "مثال، نمونہ، نمونہ", "fa": "مثال، نمونه، الگو", "hi": "मिसाल, उदाहरण, नमूना", "ps": "مثال، بېلګه", "ar": "الْمِثَال، النَّمُوذَج، الْقُدْوَة"},
    "misam": {"en": "Misam; a male given name", "ur": "میسم (مردانہ نام)", "fa": "میسم (نام مردانہ)", "hi": "मीसाम (पुरुष नाम)", "ps": "میسم (نر نوم)", "ar": "مِيسَم (اسم علم مذكر)"},
    "covenant": {"en": "Covenant, agreement, pact", "ur": "میثاق، عہد، معاہدہ", "fa": "میثاق، پیمان، عهد", "hi": "मीसाक़, अनुबंध, संधि", "ps": "میثاق، تړون", "ar": "الْمِيثَاق، الْعَهْد، الْمِيثَاق"},
    "misha": {"en": "Misha; a Russian/Hebrew given name", "ur": "میشا (روسی/عبرانی نام)", "fa": "میشا (نام روسی/عبری)", "hi": "मीशा (रूसी/हिब्रू नाम)", "ps": "میشا (روسي/عبري نوم)", "ar": "مِيشَا (اسم علم روسي/عبري)"},
    "mishael": {"en": "Mishael; a Hebrew male given name", "ur": "میشائیل (عبرانی نام)", "fa": "میشائیل (نام عبری)", "hi": "मीशाएल (हिब्रू नाम)", "ps": "میشائیل (عبري نوم)", "ar": "مِيشَائِيل (اسم علم مذكر عبري)"},
    "mishal": {"en": "Mishal; a unisex given name", "ur": "میشال (نام)", "fa": "میشال (نام)", "hi": "मीशाल (नाम)", "ps": "میشال (نوم)", "ar": "مِيشَال (اسم علم)"},
    "mishel": {"en": "Mishel; a female given name", "ur": "میشیل (زنانہ نام)", "fa": "میشیل (نام زنانہ)", "hi": "मीशेल (स्त्री नाम)", "ps": "میشیل (ښځينه نوم)", "ar": "مِيشِيل (اسم علم مؤنث)"},
    "mishka": {"en": "Mishka; a Russian given name", "ur": "میشکا (روسی نام)", "fa": "میشکا (نام روسی)", "hi": "मीश्का (रूसी नाम)", "ps": "میشکا (روسي نوم)", "ar": "مِيشْكَا (اسم علم روسي)"},
    "niche": {"en": "Niche, lamp niche", "ur": "مشکاۃ، طاق، چراغ دان", "fa": "مشکات، طاق، چراغدان", "hi": "मिश्कात, ताक़, दीप-स्थल", "ps": "مشکات، طاق", "ar": "الْمِشْكَاة، الطَّاق، مَوْضِع الْمِصْبَاح"},
    "miski": {"en": "Miski; musky, of musk", "ur": "مسکی، مشک سے منسوب", "fa": "مسکی، منسوب به مشک", "hi": "मिस्की, मुश्क से", "ps": "مسکي، د مشک اړوند", "ar": "الْمِسْكِي، مَنْسُوب إِلَى الْمِسْك"},
    "egyptian": {"en": "Egyptian", "ur": "مصری، مصر سے منسوب", "fa": "مصری، منسوب به مصر", "hi": "मिस्री, मिस्र से", "ps": "مصري، د مصر اړوند", "ar": "الْمِصْرِي، مَنْسُوب إِلَى مِصْر"},
    "mitra": {"en": "Mitra; a Persian given name", "ur": "مترا (فارسی نام)", "fa": "میترا (نام زنانہ)", "hi": "मित्रा (फ़ारसी नाम)", "ps": "میترا (فارسي نوم)", "ar": "مِيتْرَا (اسم علم فارسي)"},
    "mizan": {"en": "Mizan; balance, scale", "ur": "میزان، ترازو، عدل", "fa": "میزان، ترازو، عدل", "hi": "मीज़ान, तराज़ू, न्याय", "ps": "میزان، تله", "ar": "الْمِيزَان، الْعَدْل، الْقِسْط"},
    "mizanur": {"en": "Mizanur; balance of the Merciful", "ur": "میزانور، رحمان کا ترازو", "fa": "میزانور، ترازوی رحمان", "hi": "मीज़ानुर, रहमान का तराज़ू", "ps": "میزانور، د رحمان تله", "ar": "مِيزَانُ الرَّحْمَن، مِيزَانُور"},
    "rain_cloud": {"en": "Rain cloud", "ur": "مزنہ، بارش کا بادل", "fa": "مزنه، ابر باران‌زا", "hi": "मिज़ना, वर्षा-मेघ", "ps": "مزنه، باراني ورېځ", "ar": "الْمِزْنَة، السَّحَابَة الْمُمْطِرَة"},
    "moaz": {"en": "Moaz; a male given name", "ur": "معاذ (مردانہ نام)", "fa": "معاذ (نام مردانہ)", "hi": "मुआज़ (पुरुष नाम)", "ps": "معاذ (نر نوم)", "ar": "مُعَاذ (اسم علم مذكر)"},
    "exalted": {"en": "Exalted, magnified, honoured", "ur": "معظم، بلند، بزرگ", "fa": "معظم، بزرگ، سرفراز", "hi": "मुअज़्ज़म, महान, प्रतिष्ठित", "ps": "معظم، لوی", "ar": "الْمُعَظَّم، الْجَلِيل، الْمُبَجَّل"},
    "blessed_mubarak": {"en": "Blessed, fortunate", "ur": "مبارک، بابرکت", "fa": "مبارک، فرخنده", "hi": "मुबारक, शुभ", "ps": "مبارک، نیکمرغه", "ar": "الْمُبَارَك، الْمَيْمُون"},
    "manifest": {"en": "Clear, manifest, evident", "ur": "مبین، واضح، آشکار", "fa": "مبین، روشن، آشکار", "hi": "मुबीन, स्पष्ट, प्रकट", "ps": "مبین، ښکاره", "ar": "الْمُبِين، الْوَاضِح، الظَّاهِر"},
    "modassir": {"en": "Modassir; wrapped in a cloak", "ur": "مدثر، چادر اوڑھنے والا", "fa": "مدثر، جامه‌پوش", "hi": "मुदस्सिर, चादर ओढ़ने वाला", "ps": "مدثر، کملی غوړېدونکی", "ar": "الْمُدَّثِّر، الْمُتَدَثِّر"},
    "modupe": {"en": "Modupe; a Yoruba female given name", "ur": "مودوپے (یوروبا نام)", "fa": "مودوپه (نام یوروبا)", "hi": "मोदुपे (योरूबा नाम)", "ps": "مودوپې (یوروبا نوم)", "ar": "مُودُوبِي (اسم علم مؤنث يوروبي)"},
    "supported": {"en": "Supported, aided, strengthened", "ur": "مؤید، تائید شدہ، مدد یافتہ", "fa": "مؤید، تأییدشده، یاری‌شده", "hi": "मुअय्यद, समर्थित, सहायता-प्राप्त", "ps": "مؤید، ملاتړ شوی", "ar": "الْمُؤَيَّد، الْمَنْصُور، الْمُعَان"},
    "moeen": {"en": "Moeen; helper, assistant", "ur": "معین، مددگار، معاون", "fa": "معین، یاری‌کننده، یاور", "hi": "मोईन, सहायक, मददगार", "ps": "معین، مرستندوی", "ar": "الْمُعِين، النَّاصِر، الْحَافِظ"},
    "honourer": {"en": "One who honours, giver of honour", "ur": "معز، عزت دینے والا", "fa": "معز، عزت‌بخش", "hi": "मुइज़्ज़, सम्मान देने वाला", "ps": "معز، عزت ورکوونکی", "ar": "الْمُعِزّ، الْمُكْرِم، الْمُعَظِّم"},
    "believer": {"en": "Believer, one who has faith", "ur": "مؤمن، ایمان والا", "fa": "مؤمن، باایمان", "hi": "मोमिन, ईमानवाला", "ps": "مؤمن، ایمان لرونکی", "ar": "الْمُؤْمِن، صَاحِب الْإِيمَان"},
    "believer_f": {"en": "Believer, one who has faith (feminine)", "ur": "مؤمنہ، ایمان والی (مؤنث)", "fa": "مؤمنه، باایمان (مؤنث)", "hi": "मोमिना, ईमानवाली (स्त्री)", "ps": "مؤمنه، ایمان لرونکې", "ar": "الْمُؤْمِنَة، صَاحِبَة الْإِيمَان"},
    "love_mohabbat": {"en": "Love, affection", "ur": "محبت، پیار، الفت", "fa": "محبت، عشق، الفت", "hi": "मोहब्बत, प्रेम, स्नेह", "ps": "محبت، مینه", "ar": "الْمَحَبَّة، الْعِشْق، الْوُدّ"},
    "muhammad": {"en": "Praised, commendable", "ur": "محمد، تعریف شدہ، ستودہ", "fa": "محمد، ستوده، پسندیده", "hi": "मुहम्मद, प्रशंसित", "ps": "محمد، ستایل شوی", "ar": "مُحَمَّد، الْمَحْمُود، الْحَمِيد"},
    "lover": {"en": "Lover, one who loves", "ur": "محب، عاشق، محبت کرنے والا", "fa": "محب، عاشق، دوستدار", "hi": "मुहिब, प्रेमी, आशिक़", "ps": "محب، مینه‌ناک", "ar": "الْمُحِبّ، الْعَاشِق، الْوَدُود"},
    "mohid": {"en": "Mohid; a male given name", "ur": "موحد (مردانہ نام)", "fa": "موحد (نام مردانہ)", "hi": "मोहिद (पुरुष नाम)", "ps": "موحد (نر نوم)", "ar": "مُوحِد (اسم علم مذكر)"},
    "benefactor": {"en": "Benefactor, doer of good", "ur": "محسن، نیکی کرنے والا", "fa": "محسن، نیکوکار", "hi": "मोहसिन, उपकारी, नेक", "ps": "محسن، ښیګڼه کوونکی", "ar": "الْمُحْسِن، الْبَارّ، فَاعِل الْخَيْر"},
    "moiz": {"en": "Moiz; one who honours", "ur": "معز، عزت دینے والا", "fa": "معز، عزت‌بخش", "hi": "मोइज़, सम्मान देने वाला", "ps": "معز، عزت ورکوونکی", "ar": "الْمُعِزّ، الْمُكْرِم"},
    "chosen": {"en": "Chosen, selected, elected", "ur": "مجتبیٰ، منتخب، چنا ہوا", "fa": "مجتبی، برگزیده، منتخب", "hi": "मुज्तबा, चुना हुआ, निर्वाचित", "ps": "مجتبی، غوره شوی", "ar": "الْمُجْتَبَى، الْمُخْتَار، الْمُصْطَفَى"},
    "accepted": {"en": "Accepted, approved, received", "ur": "مقبول، قبول شدہ، پسندیدہ", "fa": "مقبول، پذیرفته، پسندیده", "hi": "मक़बूल, स्वीकृत, पसंदीदा", "ps": "مقبول، منل شوی", "ar": "الْمَقْبُول، الْمَرْضِيّ، الْمُعْتَمَد"},
    "mukhtar": {"en": "Chosen, elected, authorised", "ur": "مختار، چنا ہوا، اختیار یافتہ", "fa": "مختار، برگزیده، صاحب‌اختیار", "hi": "मुख़्तार, चुना हुआ, अधिकार-प्राप्त", "ps": "مختار، غوره شوی", "ar": "الْمُخْتَار، الْمُصْطَفَى، الْمُنْتَخَب"},
    "momin": {"en": "Momin; believer, faithful", "ur": "مومن، ایمان والا", "fa": "مومن، باایمان", "hi": "मोमिन, ईमानवाला", "ps": "مومن، ایمان لرونکی", "ar": "الْمُؤْمِن، صَاحِب الْإِيمَان"},
    "momina": {"en": "Momina; believing (feminine)", "ur": "مومنہ، ایمان والی (مؤنث)", "fa": "مومنه، باایمان (مؤنث)", "hi": "मोमिना, ईमानवाली (स्त्री)", "ps": "مومنه، ایمان لرونکې", "ar": "الْمُؤْمِنَة، صَاحِبَة الْإِيمَان"},
    "mona": {"en": "Mona; wishes, desires", "ur": "منیٰ، آرزوئیں، خواہشیں", "fa": "منی، آرزوها، خواسته‌ها", "hi": "मुना, इच्छाएँ, आरज़ू", "ps": "منی، هیلې", "ar": "الْمُنَى، الْأَمَانِي، الرَّغَائِب"},
})

CUR = {
 "meraj": ("معراج", "معراج", "معراج", "मेराज", "معراج", "ascension", "Arabic", "Male",
           "Arabic root ع ر ج (ʿ-r-j); مِعْرَاج (Miʿrāj)", False, "high",
           "Meraj is Arabic مِعْرَاج (Miʿrāj) 'ascension, night journey', from the root ع ر ج (ʿ-r-j); it is the Qur'anic term for the Prophet's night journey. CRITICAL SOURCE ERROR: the source gave ميراج (a different form); the correct form is مِعْرَاج. The source gloss 'Journey to the Heights' is broadly consistent. Same name as miraj."),
 "meral": ("ميرال", "میرال", "میرال", "मेराल", "میرال", "meral", "Turkish", "Female",
           "Turkish meral", False, "medium",
           "Meral is the Turkish female given name meral. CRITICAL SOURCE ERROR: the source gave the Latin string 'Meral' instead of a script form and labelled the origin Arabic; the name is Turkish. The source gloss 'Bright, clear, shining' is unsupported; no confident lexical sense is asserted."),
 "meriem": ("مريم", "مریم", "مریم", "मरियम", "مریم", "mary", "Arabic", "Female",
            "Arabic مَرْيَم (Maryam)", False, "high",
            "Meriem is Arabic مَرْيَم (Maryam), the name of Mary, mother of Jesus, and a Qur'anic figure. The source gloss 'Beloved' is unsupported and has been replaced with the documented identification. Same name as meryam, meryem and maryam."),
 "mersiha": ("مرسية", "مرسیہ", "مرسیه", "मेरसिहा", "مرسیه", "mersiha", "Unknown", "Female",
             "No reliable root analysis established.", False, "low",
             "Mersiha is recorded at low confidence. The source gave ميرسيهار (a garbled form) and glossed the name 'Thankful, Grateful'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "merwa": ("مروة", "مروہ", "مروه", "मरवा", "مروه", "marwa", "Arabic", "Female",
           "Arabic مَرْوَة (Marwa)", False, "high",
           "Merwa is Arabic مَرْوَة (Marwa), the name of a hill in Mecca associated with the pilgrimage rites. CRITICAL SOURCE ERROR: the source gave فاطمة (a different name entirely) and glossed the name 'Desirable, Precious'; the correct form is مَرْوَة and the source gloss is unsupported. Same name as marwa."),
 "meryam": ("مريم", "مریم", "مریم", "मरियम", "مریم", "mary", "Arabic", "Female",
            "Arabic مَرْيَم (Maryam)", False, "high",
            "Meryam is Arabic مَرْيَم (Maryam), the name of Mary, mother of Jesus, and a Qur'anic figure. The source gloss 'Mary, Mother of Jesus' is consistent. Same name as meriem and meryem."),
 "meryem": ("مريم", "مریم", "مریم", "मरियम", "مریم", "mary", "Turkish", "Female",
            "Turkish form of Arabic مَرْيَم (Maryam)", False, "high",
            "Meryem is the Turkish form of Arabic مَرْيَم (Maryam), the name of Mary, mother of Jesus. CRITICAL SOURCE ERROR: the source gave مرئم (a different form) and glossed the name 'Beloved'; the correct form is مَرْيَم and the source gloss is unsupported. Same name as meriem and meryam."),
 "mesbah": ("مصباح", "مصباح", "مصباح", "मिस्बाह", "مصباح", "lamp", "Arabic", "Unknown",
            "Arabic root ص ب ح (ṣ-b-ḥ); مِصْبَاح (Miṣbāḥ)", False, "high",
            "Mesbah is Arabic مِصْبَاح (Miṣbāḥ) 'lamp, light, lantern', from the root ص ب ح (ṣ-b-ḥ). The source gloss 'Lamp' is consistent. Recorded as a common noun also used as a given name; no single personal-name gender usage is asserted."),
 "meshaal": ("مشعل", "مشعل", "مشعل", "मशअल", "مشعل", "torch", "Arabic", "Unknown",
             "Arabic root ش ع ل (sh-ʿ-l); مِشْعَل (Mishʿal)", False, "high",
             "Meshaal is Arabic مِشْعَل (Mishʿal) 'torch, flame, light', from the root ش ع ل (sh-ʿ-l). The source gloss 'Guide, Aide, Companion' is unsupported and has been replaced with the lexical sense. Same name as mishaal and mashal."),
 "mesk": ("مسك", "مسک", "مسک", "मिस्क", "مسک", "musk", "Arabic", "Unknown",
          "Arabic root م س ك (m-s-k); مِسْك (Misk)", False, "high",
          "Mesk is Arabic مِسْك (Misk) 'musk', from the root م س ك (m-s-k). The source gloss 'Small fish' is unsupported and has been replaced with the lexical sense. Recorded as a common noun rather than a personal name; no personal-name gender usage is asserted. Same name as misk."),
 "miad": ("ميعاد", "میعاد", "میعاد", "मीयाद", "میعاد", "appointment", "Arabic", "Unknown",
          "Arabic root و ع د (w-ʿ-d); مِيعَاد (Mīʿād)", False, "high",
          "Miad is Arabic مِيعَاد (Mīʿād) 'appointment, promise, fixed time', from the root و ع د (w-ʿ-d). The source gloss 'River' is unsupported and has been replaced with the lexical sense. Recorded as a common noun also used as a given name."),
 "midhat": ("مدحت", "مدحت", "مدحت", "मिदहत", "مدحت", "praise_midhat", "Arabic", "Male",
            "Arabic root م د ح (m-d-ḥ); مِدْحَت (Midḥat)", False, "high",
            "Midhat is Arabic مِدْحَت (Midḥat) 'praise, commendation', from the root م د ح (m-d-ḥ). CRITICAL SOURCE ERROR: the source gave مِذْهَات (a different form); the correct form is مِدْحَت. The source gloss 'Grace, Beauty, Generosity' is unsupported and has been replaced with the lexical sense."),
 "midlaj": ("مدلج", "مدلج", "مدلج", "मिदलज", "مدلج", "midlaj", "Arabic", "Male",
            "Arabic مِدْلَج (Midlaj)", False, "low",
            "Midlaj is recorded at low confidence. The source gave ميدلج (a different form) and glossed the name 'Delicate, tender, gentle'; no verified lexical sense could be confirmed. No confident meaning is asserted."),
 "miesha": ("ميشة", "میشہ", "میشه", "मीशा", "میشه", "miesha", "Unknown", "Female",
            "No reliable root analysis established.", False, "low",
            "Miesha is recorded at low confidence. The source gloss 'Moon Goddess' is unsupported and no verified Arabic form was established; the name is used across several unrelated traditions, so no single origin or meaning is asserted here."),
 "mifrah": ("مفراح", "مفراح", "مفراح", "मिफ़राह", "مفراح", "mifrah", "Arabic", "Unknown",
            "Arabic مِفْرَاح (Mifrāḥ)", False, "low",
            "Mifrah is recorded at low confidence. The source gave مِفْرَح (a different form) and glossed the name 'A place of learning and guidance'; no verified lexical sense could be confirmed. No confident meaning is asserted."),
 "miftah": ("مفتاح", "مفتاح", "مفتاح", "मिफ़्ताह", "مفتاح", "key", "Arabic", "Male",
            "Arabic root ف ت ح (f-t-ḥ); مِفْتَاح (Miftāḥ)", False, "high",
            "Miftah is Arabic مِفْتَاح (Miftāḥ) 'key, opener', from the root ف ت ح (f-t-ḥ). The source gloss 'Key' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "miftahul": ("مفتاح الـ", "مفتاح الـ", "مفتاح الـ", "मिफ़्ताहुल", "مفتاح الـ", "key", "Arabic", "Male",
              "Arabic مِفْتَاحُ الْـ (Miftāḥ al-), construct of مِفْتَاح", False, "high",
              "Miftahul is Arabic مِفْتَاحُ الْـ (Miftāḥ al-), the construct form of مِفْتَاح (miftāḥ) 'key' with the definite article, used in compound names such as Miftahul Ulum. CRITICAL SOURCE ERROR: the source gave مفتاحل (a different form); the correct form is مِفْتَاحُ الْـ. The source gloss 'Key, Opener' is broadly consistent."),
 "mifzal": ("مفضال", "مفضال", "مفضال", "मिफ़ज़ाल", "مفضال", "generous_mifdal", "Arabic", "Male",
            "Arabic root ف ض ل (f-ḍ-l); مِفْضَال (Mifḍāl)", False, "high",
            "Mifzal is Arabic مِفْضَال (Mifḍāl) 'very generous, bountiful', from the root ف ض ل (f-ḍ-l). CRITICAL SOURCE ERROR: the source gave أحمد (a different name entirely) and glossed the name 'A fortress, a stronghold'; the correct form is مِفْضَال and the source gloss is unsupported."),
 "mihad": ("مهاد", "مہاد", "مهاد", "मिहाद", "مهاد", "cradle", "Arabic", "Male",
           "Arabic root م ه د (m-h-d); مِهَاد (Mihād)", False, "high",
           "Mihad is Arabic مِهَاد (Mihād) 'cradle, bed, resting place', from the root م ه د (m-h-d). CRITICAL SOURCE ERROR: the source gave ميهاد (a different form) and glossed the name 'Deliverer, Guide'; the correct form is مِهَاد and the source gloss is unsupported."),
 "mihran": ("مهران", "مہران", "مهران", "मिहरान", "مهران", "mihran", "Persian", "Male",
            "Persian مهران (Mihrān)", False, "high",
            "Mihran is the Persian male given name مهران (Mihrān). CRITICAL SOURCE ERROR: the source gave ميهران (a different form) and labelled the origin Arabic; the correct form is مهران and the name is Persian. The source gloss 'Kind and Just' is unsupported; no confident lexical sense is asserted."),
 "mihri": ("مهري", "مہری", "مهری", "मिहरी", "مهری", "mihri", "Persian", "Female",
           "Persian مهری (Mehrī)", False, "high",
           "Mihri is the Persian female given name مهری (Mehrī), related to مِهْر (mihr, 'sun, love'). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Seeker of water' is unsupported; no confident lexical sense is asserted. Same name as mehri."),
 "mika": ("ميكا", "میکا", "میکا", "मीका", "میکا", "mika", "Unknown", "Female",
          "No reliable root analysis established.", False, "low",
          "Mika is recorded at low confidence. The source gave the Latin string 'mika' instead of a script form and glossed the name 'Small'; no verified origin or lexical sense could be confirmed. No confident meaning is asserted."),
 "mikaeel": ("ميكائيل", "میکائیل", "میکائیل", "मीकाईल", "میکائیل", "michael", "Arabic", "Male",
             "Arabic مِيكَائِيل (Mīkāʾīl)", False, "high",
             "Mikaeel is Arabic مِيكَائِيل (Mīkāʾīl), the name of the archangel Michael, mentioned in the Qur'an. The source gloss 'Who is like God?' is the traditional Hebrew etymology of the name and is broadly consistent. Same name as mikail."),
 "mikail": ("ميكائيل", "میکائیل", "میکائیل", "मीकाईल", "میکائیل", "michael", "Arabic", "Male",
            "Arabic مِيكَائِيل (Mīkāʾīl)", False, "high",
            "Mikail is Arabic مِيكَائِيل (Mīkāʾīl), the name of the archangel Michael, mentioned in the Qur'an. The source gloss 'Like Allah' is a loose rendering of the traditional Hebrew etymology; the documented identification is the archangel. Same name as mikaeel."),
 "mikal": ("ميكال", "میکال", "میکال", "मीकाल", "میکال", "michael", "Arabic", "Male",
           "Arabic مِيكَال (Mīkāl), a Qur'anic variant of مِيكَائِيل", False, "high",
           "Mikal is Arabic مِيكَال (Mīkāl), a Qur'anic variant form of مِيكَائِيل (Mīkāʾīl), the archangel Michael. The source gloss 'Who is like God?' is the traditional Hebrew etymology and is broadly consistent."),
 "mikhail": ("ميخائيل", "میخائیل", "میخائیل", "मिखाईल", "میخائیل", "michael", "Russian", "Male",
             "Russian Михаил, from Greek Μιχαήλ", False, "high",
             "Mikhail is the Russian form (Михаил) of the Greek Μιχαήλ, the archangel Michael. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Russian/Greek in form. The source gloss 'Who is like God?' is the traditional Hebrew etymology and is broadly consistent."),
 "milad": ("ميلاد", "میلاد", "میلاد", "मीलाद", "میلاد", "birth", "Arabic", "Male",
           "Arabic root و ل د (w-l-d); مِيلَاد (Mīlād)", False, "high",
           "Milad is Arabic مِيلَاد (Mīlād) 'birth, nativity', from the root و ل د (w-l-d). The source gloss 'Birthday, Birth' is consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "mina": ("منى", "منیٰ", "منی", "मिना", "منی", "mina_place", "Arabic", "Female",
          "Arabic مِنَى (Minā)", False, "high",
          "Mina is Arabic مِنَى (Minā), the name of a place near Mecca associated with the pilgrimage, also used as a female given name. The source gloss 'Intensive labor or struggle' is unsupported and has been replaced with the documented identification."),
 "minaa": ("منى", "منیٰ", "منی", "मिना", "منی", "mina_place", "Arabic", "Female",
           "Arabic مِنَى (Minā)", False, "high",
           "Minaa is Arabic مِنَى (Minā), the name of a place near Mecca associated with the pilgrimage, also used as a female given name. The source gloss 'Love and Affection' is unsupported and has been replaced with the documented identification. Same name as mina."),
 "minah": ("منحة", "منحہ", "منحه", "मिनहा", "منحه", "grant", "Arabic", "Female",
           "Arabic root م ن ح (m-n-ḥ); مِنْحَة (Minḥa)", False, "high",
           "Minah is Arabic مِنْحَة (Minḥa) 'gift, grant, bestowal', from the root م ن ح (m-n-ḥ). The source gloss 'Gift from Allah' is broadly consistent."),
 "minahil": ("مناهيل", "مناهیل", "مناهیل", "मिनाहिल", "مناهیل", "minahil", "Unknown", "Female",
             "No reliable root analysis established.", False, "low",
             "Minahil is recorded at low confidence. The source gave مِينَاهِيل (a garbled form) and glossed the name 'Delightful, Gracious'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "minal": ("منال", "منال", "منال", "मिनाल", "منال", "attainment", "Arabic", "Unknown",
           "Arabic root ن ي ل (n-y-l); مَنَال (Manāl)", False, "high",
           "Minal is Arabic مَنَال (Manāl) 'attainment, achievement, acquisition', from the root ن ي ل (n-y-l). The source gloss 'Light, Delight' is unsupported and has been replaced with the lexical sense. Recorded as a common noun also used as a given name."),
 "minha": ("منها", "منہا", "منها", "मिनहा", "منها", "minha", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Minha is recorded at low confidence. The source gloss 'Delicate, Tender' is unsupported and no verified lexical form was established; the form is a common Arabic function word, so no confident name meaning is asserted."),
 "minhaj": ("منهاج", "منہاج", "منهاج", "मिन्हाज", "منهاج", "method", "Arabic", "Male",
            "Arabic root ن ه ج (n-h-j); مِنْهَاج (Minhāj)", False, "high",
            "Minhaj is Arabic مِنْهَاج (Minhāj) 'path, method, program', from the root ن ه ج (n-h-j). The source gloss 'A guide, a path' is broadly consistent. Recorded at medium confidence because the word is primarily a common noun."),
 "minhal": ("منهل", "منہل", "منهل", "मिन्हल", "منهل", "spring", "Arabic", "Male",
            "Arabic root ن ه ل (n-h-l); مِنْهَل (Minhal)", False, "high",
            "Minhal is Arabic مِنْهَل (Minhal) 'spring, watering place', from the root ن ه ل (n-h-l). The source gloss 'Gift from God' is unsupported and has been replaced with the lexical sense."),
 "minna": ("منى", "منیٰ", "منی", "मिन्ना", "منی", "mina_place", "Arabic", "Female",
           "Arabic مِنَى (Minā)", False, "high",
           "Minna is Arabic مِنَى (Minā), the name of a place near Mecca associated with the pilgrimage, also used as a female given name. The source gloss 'Tender, Gracious' is unsupported and has been replaced with the documented identification. Same name as mina and minaa."),
 "minnat": ("منة", "منت", "منت", "मिन्नत", "منت", "favour", "Arabic", "Female",
            "Arabic root م ن ن (m-n-n); مِنَّة (Minna)", False, "high",
            "Minnat is Arabic مِنَّة (Minna) 'favour, grace, kindness', from the root م ن ن (m-n-n). CRITICAL SOURCE ERROR: the source gave منات (a different form); the correct form is مِنَّة. The source gloss 'Love, affection' is unsupported and has been replaced with the lexical sense."),
 "minoo": ("مینو", "مینو", "مینو", "मीनू", "مینو", "minoo", "Persian", "Female",
           "Persian مینو (Mīnū)", False, "high",
           "Minoo is the Persian female given name مینو (Mīnū) 'paradise, heaven'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Minoo' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Gift of God' is unsupported and has been replaced with the lexical sense."),
 "miqdad": ("مقداد", "مقداد", "مقداد", "मिक़दाद", "مقداد", "miqdad", "Arabic", "Male",
            "Arabic مِقْدَاد (Miqdād)", False, "high",
            "Miqdad is Arabic مِقْدَاد (Miqdād), a documented male given name borne by a companion of the Prophet. The source gloss 'Companion of the Prophet' is broadly consistent."),
 "mir": ("مير", "میر", "میر", "मीर", "میر", "mir", "Persian", "Male",
         "Persian مِير (Mīr)", False, "high",
         "Mir is the Persian title and male given name مِير (Mīr) 'chief, leader, prince', widely used in South Asia. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Moon, Light' is unsupported and has been replaced with the documented sense. Same name as meer."),
 "miradi": ("مرادي", "مرادی", "مرادی", "मुरादी", "مرادي", "muradi", "Arabic", "Unknown",
            "Arabic nisba of مُرَاد; مُرَادِي (Murādī)", False, "high",
            "Miradi is Arabic مُرَادِي (Murādī), the nisba ('of Murad, belonging to Murad') of مُرَاد (Murād). The source gloss 'Bright, radiant' is unsupported and has been replaced with the relational sense."),
 "mirah": ("ميرة", "میرہ", "میره", "मीरा", "میره", "mirah", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Mirah is recorded at low confidence. The source gave ميراه (a garbled form) and glossed the name 'Guiding Light'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "miraj": ("معراج", "معراج", "معراج", "मिराज", "معراج", "miraj", "Arabic", "Male",
           "Arabic root ع ر ج (ʿ-r-j); مِعْرَاج (Miʿrāj)", False, "high",
           "Miraj is Arabic مِعْرَاج (Miʿrāj) 'ascension, night journey', from the root ع ر ج (ʿ-r-j); it is the Qur'anic term for the Prophet's night journey. CRITICAL SOURCE ERROR: the source gave مِرَاج (a different form); the correct form is مِعْرَاج. The source gloss 'The Night Journey' is consistent. Same name as meraj."),
 "miral": ("ميرال", "میرال", "میرال", "मीराल", "میرال", "miral", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Miral is recorded at low confidence. The source gloss 'Star, Light, Guiding' is unsupported and no verified Arabic form was established; مِرْيَال (Miryāl) is a documented female given name, but its derivation could not be confirmed. No confident meaning is asserted."),
 "miran": ("ميران", "میران", "میران", "मीरान", "میران", "miran", "Persian", "Male",
           "Persian مِيرَان (Mīrān)", False, "high",
           "Miran is the Persian male given name مِيرَان (Mīrān), related to مِير (Mīr) 'chief, leader'. CRITICAL SOURCE ERROR: the source gave ميرا (a different form) and labelled the origin Arabic; the correct form is مِيرَان and the name is Persian. The source gloss 'Gift of God' is unsupported. Same name as meeran."),
 "mirsad": ("مرصاد", "مرصاد", "مرصاد", "मिरसाद", "مرصاد", "watchtower", "Arabic", "Male",
            "Arabic root ر ص د (r-ṣ-d); مِرْصَاد (Mirṣād)", False, "high",
            "Mirsad is Arabic مِرْصَاد (Mirṣād) 'watchtower, lookout, ambush', from the root ر ص د (r-ṣ-d). The source gloss 'Guide, Leader' is unsupported and has been replaced with the lexical sense."),
 "mirwais": ("ميرويس", "میرویس", "میرویس", "मीरवैस", "میرویس", "mirwais", "Pashto", "Male",
             "Pashto مِيرْوَيْس (Mīrwais)", False, "high",
             "Mirwais is the Pashto male given name مِيرْوَيْس (Mīrwais), borne by the historical Afghan ruler Mirwais Hotak. CRITICAL SOURCE ERROR: the source gave مرويس (a different form) and labelled the origin Arabic; the correct form is مِيرْوَيْس and the name is Pashto. The source gloss 'Master of the nobles' is unsupported."),
 "mirza": ("ميرزا", "مرزا", "میرزا", "मिर्ज़ा", "میرزا", "mirza", "Persian", "Male",
           "Persian مِيرْزَا (Mīrzā)", False, "high",
           "Mirza is the Persian title and male given name مِيرْزَا (Mīrzā) 'prince, noble-born', widely used in South Asia. CRITICAL SOURCE ERROR: the source gave مرزا (a different form) and labelled the origin Arabic; the correct form is مِيرْزَا and the name is Persian. The source gloss 'Prince or Noble Born' is broadly consistent."),
 "mirzali": ("ميرزا علي", "مرزاعلی", "میرزاعلی", "मिर्ज़ा अली", "میرزا علي", "mirzali", "Persian", "Male",
             "Persian مِيرْزَا عَلِي (Mīrzā ʿAlī)", False, "high",
             "Mirzali is the Persian compound name مِيرْزَا عَلِي (Mīrzā ʿAlī), combining the title مِيرْزَا (Mīrzā) 'prince' with the name عَلِي (ʿAlī). CRITICAL SOURCE ERROR: the source gave مرزالي (a different form) and labelled the origin Arabic; the correct form is مِيرْزَا عَلِي and the name is Persian. The source gloss \"Prince's Heir\" is unsupported."),
 "misal": ("مثال", "مثال", "مثال", "मिसाल", "مثال", "example", "Arabic", "Unknown",
           "Arabic root م ث ل (m-th-l); مِثَال (Mithāl)", False, "high",
           "Misal is Arabic مِثَال (Mithāl) 'example, model, instance', from the root م ث ل (m-th-l). The source gloss 'Sample, Model, Example' is consistent. Recorded as a common noun also used as a given name."),
 "misam": ("ميسام", "میسام", "میسام", "मीसाम", "میسام", "misam", "Arabic", "Male",
           "Arabic مِيسَم (Mīsam)", False, "medium",
           "Misam is Arabic مِيسَم (Mīsam), a documented male given name. The source gloss 'Seeker, explorer' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "misaq": ("ميثاق", "میثاق", "میثاق", "मीसाक़", "میثاق", "covenant", "Arabic", "Unknown",
           "Arabic root و ث ق (w-th-q); مِيثَاق (Mīthāq)", False, "high",
           "Misaq is Arabic مِيثَاق (Mīthāq) 'covenant, agreement, pact', from the root و ث ق (w-th-q). CRITICAL SOURCE ERROR: the source gave مساق (a different form); the correct form is مِيثَاق. The source gloss 'Covenant, agreement' is consistent. Recorded as a common noun also used as a given name."),
 "misba": ("مصبا", "مصبا", "مصبا", "मिस्बा", "مصبا", "misba", "Arabic", "Female",
           "Arabic مِصْبَاح (Miṣbāḥ); root ص ب ح (ṣ-b-ḥ)", False, "low",
           "Misba is recorded at low confidence. The source gave مصبى (a different form) and glossed the name 'Guide, Companion'; the form is a shortened form of مِصْبَاح (miṣbāḥ) 'lamp', but the source gloss could not be confirmed. No confident meaning is asserted."),
 "misbaah": ("مصباح", "مصباح", "مصباح", "मिस्बाह", "مصباح", "lamp", "Arabic", "Female",
             "Arabic root ص ب ح (ṣ-b-ḥ); مِصْبَاح (Miṣbāḥ)", False, "high",
             "Misbaah is Arabic مِصْبَاح (Miṣbāḥ) 'lamp, light, lantern', from the root ص ب ح (ṣ-b-ḥ). The source gloss 'Guide, Light' is broadly consistent. Same name as mesbah and misbah."),
 "misbah": ("مصباح", "مصباح", "مصباح", "मिस्बाह", "مصباح", "lamp", "Arabic", "Female",
            "Arabic root ص ب ح (ṣ-b-ḥ); مِصْبَاح (Miṣbāḥ)", False, "high",
            "Misbah is Arabic مِصْبَاح (Miṣbāḥ) 'lamp, light, lantern', from the root ص ب ح (ṣ-b-ḥ). CRITICAL SOURCE ERROR: the source gave placeholder strings such as 'عربي_Misbah' instead of an Arabic form; the correct form is مِصْبَاح. The source gloss 'Noble and blessed' is unsupported and has been replaced with the lexical sense. Same name as mesbah and misbaah."),
 "misha": ("ميشا", "میشا", "میشا", "मीशा", "میشا", "misha", "Russian", "Unknown",
           "Russian Миша, a diminutive of Михаил", False, "high",
           "Misha is the Russian given name Миша, a diminutive of Михаил (Mikhail). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Russian in form. The source gloss 'Who is like God?' is the traditional Hebrew etymology of the underlying name and is broadly consistent."),
 "mishaal": ("مشعل", "مشعل", "مشعل", "मिशाल", "مشعل", "torch", "Arabic", "Unknown",
             "Arabic root ش ع ل (sh-ʿ-l); مِشْعَل (Mishʿal)", False, "high",
             "Mishaal is Arabic مِشْعَل (Mishʿal) 'torch, flame, light', from the root ش ع ل (sh-ʿ-l). The source gloss 'Torch, Lamp' is consistent. Same name as meshaal and mashal."),
 "mishael": ("ميشائيل", "میشائیل", "میشائیل", "मीशाएल", "میشائیل", "mishael", "Hebrew", "Male",
             "Hebrew מִישָׁאֵל (Mishael)", False, "high",
             "Mishael is the Hebrew male given name מִישָׁאֵל (Mishael), borne by a figure in the Book of Daniel. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Hebrew. The source gloss 'Who is like God?' is the traditional etymology of the related name Michael and is broadly consistent."),
 "mishal": ("ميشال", "میشال", "میشال", "मीशाल", "میشال", "mishal", "Arabic", "Unknown",
            "Arabic مِيشَال (Mīshāl)", False, "medium",
            "Mishal is Arabic مِيشَال (Mīshāl), a documented given name used for both men and women. The source gloss 'Gift from God' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "mishel": ("ميشيل", "میشیل", "میشیل", "मीशेल", "میشیل", "mishel", "Arabic", "Female",
            "Arabic مِيشِيل (Mīshīl), from French Michelle", False, "high",
            "Mishel is Arabic مِيشِيل (Mīshīl), the Arabic rendering of the French female name Michelle. The source gloss 'Moon-like' is unsupported; the name is a proper name and no confident lexical sense is asserted."),
 "mishka": ("ميشكا", "میشکا", "میشکا", "मीश्का", "میشکا", "mishka", "Russian", "Unknown",
            "Russian Мишка, a diminutive of Михаил", False, "high",
            "Mishka is the Russian given name Мишка, a diminutive of Михаил (Mikhail). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Russian in form. The source gloss 'Gift from God' is unsupported; no confident lexical sense is asserted."),
 "mishkat": ("مشكاة", "مشکاۃ", "مشکات", "मिश्कात", "مشکات", "niche", "Arabic", "Unknown",
             "Arabic root ش ك و (sh-k-w); مِشْكَاة (Mishkāt)", False, "high",
             "Mishkat is Arabic مِشْكَاة (Mishkāt) 'niche, lamp niche', from the root ش ك و (sh-k-w); it occurs in the Qur'an in the Light Verse. CRITICAL SOURCE ERROR: the source gave ميشكات (a different form) and glossed it 'A place where medicines are kept'; the correct form is مِشْكَاة and the source gloss is unsupported."),
 "misk": ("مسك", "مسک", "مسک", "मिस्क", "مسک", "musk", "Arabic", "Unknown",
          "Arabic root م س ك (m-s-k); مِسْك (Misk)", False, "high",
          "Misk is Arabic مِسْك (Misk) 'musk', from the root م س ك (m-s-k). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Recorded as a common noun rather than a personal name. Same name as mesk."),
 "miski": ("مسكي", "مسکی", "مسکی", "मिस्की", "مسکي", "miski", "Arabic", "Female",
           "Arabic nisba of مِسْك; مِسْكِي (Miskī)", False, "high",
           "Miski is Arabic مِسْكِي (Miskī) 'musky, of musk', the nisba of مِسْك (misk). CRITICAL SOURCE ERROR: the source gave المسكي (a different form); the correct form is مِسْكِي. The source gloss 'Honeycomb' is unsupported and has been replaced with the relational sense."),
 "misri": ("مصري", "مصری", "مصری", "मिस्री", "مصري", "egyptian", "Arabic", "Male",
           "Arabic nisba of مِصْر; مِصْرِي (Miṣrī)", False, "high",
           "Misri is Arabic مِصْرِي (Miṣrī) 'Egyptian', the nisba of مِصْر (Miṣr, Egypt). The source gloss 'Egyptian' is consistent."),
 "mitra": ("میترا", "میترا", "میترا", "मित्रा", "میترا", "mitra", "Persian", "Female",
           "Persian میترا (Mītrā)", False, "high",
           "Mitra is the Persian female given name میترا (Mītrā), from the name of the ancient Iranian deity Mithra. CRITICAL SOURCE ERROR: the source gave the Latin string 'Mitra' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Mythological goddess of covenants' is broadly consistent."),
 "mizan": ("ميزان", "میزان", "میزان", "मीज़ान", "میزان", "mizan", "Arabic", "Male",
           "Arabic root و ز ن (w-z-n); مِيزَان (Mīzān)", False, "high",
           "Mizan is Arabic مِيزَان (Mīzān) 'balance, scale, justice', from the root و ز ن (w-z-n). The source gloss 'Justice, Balance' is consistent. Recorded at medium confidence because the word is primarily a common noun. Same name as meezan."),
 "mizanur": ("ميزان الرحمن", "میزانور", "میزانور", "मीज़ानुर", "میزانور", "mizanur", "Arabic", "Male",
             "Arabic مِيزَانُ الرَّحْمَن (Mīzān al-Raḥmān)", False, "high",
             "Mizanur is Arabic مِيزَانُ الرَّحْمَن (Mīzān al-Raḥmān) 'balance of the Merciful', a compound of مِيزَان (mīzān, 'balance') and الرَّحْمَن (al-Raḥmān). CRITICAL SOURCE ERROR: the source gave ميزانور (a different form); the correct form is مِيزَانُ الرَّحْمَن. The source gloss 'Balance, Scales' is broadly consistent."),
 "mizna": ("مزنة", "مزنہ", "مزنه", "मिज़ना", "مزنه", "rain_cloud", "Arabic", "Female",
           "Arabic root م ز ن (m-z-n); مِزْنَة (Mizna)", False, "high",
           "Mizna is Arabic مِزْنَة (Mizna) 'rain cloud', from the root م ز ن (m-z-n). CRITICAL SOURCE ERROR: the source gave ميزنة (a different form); the correct form is مِزْنَة. The source gloss 'Delight, Joy, Happiness' is unsupported and has been replaced with the lexical sense."),
 "moaz": ("معاذ", "معاذ", "معاذ", "मुआज़", "معاذ", "moaz", "Arabic", "Male",
          "Arabic root ع و ذ (ʿ-w-dh); مُعَاذ (Muʿādh)", False, "high",
          "Moaz is Arabic مُعَاذ (Muʿādh) 'protected, sheltered', from the root ع و ذ (ʿ-w-dh); it is a documented male given name borne by a companion of the Prophet. The source gloss 'Brightness, Light' is unsupported and has been replaced with the lexical sense."),
 "moazzam": ("معظم", "معظم", "معظم", "मुअज़्ज़म", "معظم", "exalted", "Arabic", "Male",
             "Arabic root ع ظ م (ʿ-ẓ-m); مُعَظَّم (Muʿaẓẓam)", False, "high",
             "Moazzam is Arabic مُعَظَّم (Muʿaẓẓam) 'exalted, magnified, honoured', from the root ع ظ م (ʿ-ẓ-m). CRITICAL SOURCE ERROR: the source gave معظم (an unvocalised form); the correct vocalised form is مُعَظَّم. The source gloss 'Glory, Honour' is broadly consistent. Same name as moazzem."),
 "moazzem": ("معظم", "معظم", "معظم", "मुअज़्ज़म", "معظم", "exalted", "Arabic", "Male",
             "Arabic root ع ظ م (ʿ-ẓ-m); مُعَظَّم (Muʿaẓẓam)", False, "high",
             "Moazzem is Arabic مُعَظَّم (Muʿaẓẓam) 'exalted, magnified, honoured', from the root ع ظ م (ʿ-ẓ-m). The source gloss 'Warner' is unsupported and has been replaced with the lexical sense. Same name as moazzam."),
 "mobarak": ("مبارك", "مبارک", "مبارک", "मुबारक", "مبارک", "blessed_mubarak", "Arabic", "Male",
             "Arabic root ب ر ك (b-r-k); مُبَارَك (Mubārak)", False, "high",
             "Mobarak is Arabic مُبَارَك (Mubārak) 'blessed, fortunate', from the root ب ر ك (b-r-k). The source gloss 'Blessed' is consistent. Same name as mubarak."),
 "mobeen": ("مبين", "مبین", "مبین", "मुबीन", "مبین", "manifest", "Arabic", "Male",
            "Arabic root ب ي ن (b-y-n); مُبِين (Mubīn)", False, "high",
            "Mobeen is Arabic مُبِين (Mubīn) 'clear, manifest, evident', from the root ب ي ن (b-y-n). The source gloss 'Present, Existent' is unsupported and has been replaced with the lexical sense. Same name as mobin."),
 "mobin": ("مبين", "مبین", "مبین", "मुबीन", "مبین", "manifest", "Arabic", "Male",
           "Arabic root ب ي ن (b-y-n); مُبِين (Mubīn)", False, "high",
           "Mobin is Arabic مُبِين (Mubīn) 'clear, manifest, evident', from the root ب ي ن (b-y-n). CRITICAL SOURCE ERROR: the source gave موبين (a different form); the correct form is مُبِين. The source gloss 'Intelligent, Wise' is unsupported and has been replaced with the lexical sense. Same name as mobeen."),
 "modassir": ("مدثر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
              "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
              "Modassir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is the title of a Qur'anic sura. CRITICAL SOURCE ERROR: the source gave مدثر (an unvocalised form); the correct vocalised form is مُدَّثِّر. The source gloss 'Achiever, Victorious' is unsupported and has been replaced with the lexical sense."),
 "modupe": ("مودوپي", "مودوپے", "مودوپه", "मोदुपे", "مودوپې", "modupe", "Yoruba", "Female",
            "Yoruba Modupe", False, "high",
            "Modupe is the Yoruba female given name Modupe, meaning 'I give thanks'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Yoruba. The source gloss 'Gift from God' is unsupported and has been replaced with the documented sense."),
 "moeed": ("مؤيد", "مؤید", "مؤید", "मुअय्यद", "مؤید", "supported", "Arabic", "Male",
           "Arabic root أ ي د (ʾ-y-d); مُؤَيَّد (Muʾayyad)", False, "high",
           "Moeed is Arabic مُؤَيَّد (Muʾayyad) 'supported, aided, strengthened', from the root أ ي د (ʾ-y-d). CRITICAL SOURCE ERROR: the source gave مؤيد (an unvocalised form); the correct vocalised form is مُؤَيَّد. The source gloss 'Traveler' is unsupported and has been replaced with the lexical sense."),
 "moeen": ("معين", "معین", "معین", "मोईन", "معین", "moeen", "Arabic", "Male",
           "Arabic root ع و ن (ʿ-w-n); مُعِين (Muʿīn)", False, "high",
           "Moeen is Arabic مُعِين (Muʿīn) 'helper, assistant', from the root ع و ن (ʿ-w-n). The source gloss 'Soft, gentle' is unsupported and has been replaced with the lexical sense. Same name as moein and moin."),
 "moeez": ("معز", "معز", "معز", "मुइज़्ज़", "معز", "honourer", "Arabic", "Male",
           "Arabic root ع ز ز (ʿ-z-z); مُعِزّ (Muʿizz)", False, "high",
           "Moeez is Arabic مُعِزّ (Muʿizz) 'one who honours, giver of honour', from the root ع ز ز (ʿ-z-z). CRITICAL SOURCE ERROR: the source gave مؤيز (a different form); the correct form is مُعِزّ. The source gloss 'Guide, Leader' is unsupported and has been replaced with the lexical sense. Same name as moez and moiz."),
 "moein": ("معين", "معین", "معین", "मोइन", "معین", "moeen", "Arabic", "Male",
           "Arabic root ع و ن (ʿ-w-n); مُعِين (Muʿīn)", False, "high",
           "Moein is Arabic مُعِين (Muʿīn) 'helper, assistant', from the root ع و ن (ʿ-w-n). CRITICAL SOURCE ERROR: the source gave موئن (a different form); the correct form is مُعِين. The source gloss 'Gifted, Gracious' is unsupported and has been replaced with the lexical sense. Same name as moeen and moin."),
 "moemen": ("مؤمن", "مؤمن", "مؤمن", "मोमिन", "مؤمن", "believer", "Arabic", "Male",
            "Arabic root أ م ن (ʾ-m-n); مُؤْمِن (Muʾmin)", False, "high",
            "Moemen is Arabic مُؤْمِن (Muʾmin) 'believer, one who has faith', from the root أ م ن (ʾ-m-n). CRITICAL SOURCE ERROR: the source gave معمن (a different form); the correct form is مُؤْمِن. The source gloss 'Believer, one who trusts and relies on God' is broadly consistent. Same name as momin."),
 "moez": ("معز", "معز", "معز", "मोइज़", "معز", "honourer", "Arabic", "Male",
          "Arabic root ع ز ز (ʿ-z-z); مُعِزّ (Muʿizz)", False, "high",
          "Moez is Arabic مُعِزّ (Muʿizz) 'one who honours, giver of honour', from the root ع ز ز (ʿ-z-z). CRITICAL SOURCE ERROR: the source gave مؤذ (a different form); the correct form is مُعِزّ. The source gloss 'Guide, Leader' is unsupported and has been replaced with the lexical sense. Same name as moeez and moiz."),
 "mohabbat": ("محبة", "محبت", "محبت", "मोहब्बत", "محبت", "love_mohabbat", "Arabic", "Female",
              "Arabic root ح ب ب (ḥ-b-b); مَحَبَّة (Maḥabba)", False, "high",
              "Mohabbat is Arabic مَحَبَّة (Maḥabba) 'love, affection', from the root ح ب ب (ḥ-b-b); محبت is the Persian/Urdu rendering. The source gloss 'Love, Affection' is consistent."),
 "mohammad": ("محمد", "محمد", "محمد", "मुहम्मद", "محمد", "muhammad", "Arabic", "Male",
              "Arabic root ح م د (ḥ-m-d); مُحَمَّد (Muḥammad)", False, "high",
              "Mohammad is Arabic مُحَمَّد (Muḥammad) 'praised, commendable', from the root ح م د (ḥ-m-d); it is the name of the Prophet of Islam. CRITICAL SOURCE ERROR: the source gave محمد (an unvocalised form); the correct vocalised form is مُحَمَّد. The source gloss 'Praised One' is consistent. Same name as mohammed and mohd."),
 "mohammed": ("محمد", "محمد", "محمد", "मुहम्मद", "محمد", "muhammad", "Arabic", "Male",
              "Arabic root ح م د (ḥ-m-d); مُحَمَّد (Muḥammad)", False, "high",
              "Mohammed is Arabic مُحَمَّد (Muḥammad) 'praised, commendable', from the root ح م د (ḥ-m-d); it is the name of the Prophet of Islam. The source gloss 'Praised' is consistent. Same name as mohammad and mohd."),
 "mohd": ("محمد", "محمد", "محمد", "मुहम्मद", "محمد", "muhammad", "Arabic", "Male",
          "Arabic root ح م د (ḥ-m-d); مُحَمَّد (Muḥammad)", False, "high",
          "Mohd is a common abbreviated spelling of Arabic مُحَمَّد (Muḥammad) 'praised, commendable', from the root ح م د (ḥ-m-d). The source gloss 'Mohammad' is consistent. Same name as mohammad and mohammed."),
 "mohga": ("محجة", "محجہ", "محجه", "मोहगा", "محجه", "mohga", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Mohga is recorded at low confidence. The source gave علي (a different name entirely) and glossed the name 'Blessed, Pure'; no verified Arabic form could be confirmed for this spelling. No confident meaning is asserted."),
 "mohib": ("محب", "محب", "محب", "मुहिब", "محب", "lover", "Arabic", "Male",
           "Arabic root ح ب ب (ḥ-b-b); مُحِبّ (Muḥibb)", False, "high",
           "Mohib is Arabic مُحِبّ (Muḥibb) 'lover, one who loves', from the root ح ب ب (ḥ-b-b). CRITICAL SOURCE ERROR: the source gave موهب (a different form); the correct form is مُحِبّ. The source gloss 'Lover, admirer' is broadly consistent."),
 "mohid": ("موحد", "موحد", "موحد", "मोहिद", "موحد", "mohid", "Arabic", "Male",
           "Arabic root و ح د (w-ḥ-d); مُوحِد (Mūḥid)", False, "medium",
           "Mohid is Arabic مُوحِد (Mūḥid) 'one who affirms the oneness of God', from the root و ح د (w-ḥ-d). CRITICAL SOURCE ERROR: the source gave موحيد (a different form); the correct form is مُوحِد. The source gloss 'Beloved' is unsupported and has been replaced with the lexical sense."),
 "mohsin": ("محسن", "محسن", "محسن", "मोहसिन", "محسن", "benefactor", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); مُحْسِن (Muḥsin)", False, "high",
            "Mohsin is Arabic مُحْسِن (Muḥsin) 'benefactor, doer of good', from the root ح س ن (ḥ-s-n). The source gloss 'Benefactor, Doer of good' is consistent."),
 "moin": ("معين", "معین", "معین", "मोईन", "معین", "moeen", "Arabic", "Male",
          "Arabic root ع و ن (ʿ-w-n); مُعِين (Muʿīn)", False, "high",
          "Moin is Arabic مُعِين (Muʿīn) 'helper, assistant', from the root ع و ن (ʿ-w-n). CRITICAL SOURCE ERROR: the source gave placeholder strings such as 'عربي_Moin' instead of an Arabic form; the correct form is مُعِين. The source gloss 'Noble and blessed' is unsupported and has been replaced with the lexical sense. Same name as moeen and moein."),
 "moiz": ("معز", "معز", "معز", "मोइज़", "معز", "moiz", "Arabic", "Male",
          "Arabic root ع ز ز (ʿ-z-z); مُعِزّ (Muʿizz)", False, "high",
          "Moiz is Arabic مُعِزّ (Muʿizz) 'one who honours, giver of honour', from the root ع ز ز (ʿ-z-z). The source gloss 'Desirable, Precious' is unsupported and has been replaced with the lexical sense. Same name as moeez and moez."),
 "mojtaba": ("مجتبى", "مجتبیٰ", "مجتبی", "मुज्तबा", "مجتبی", "chosen", "Arabic", "Male",
             "Arabic root ج ب ي (j-b-y); مُجْتَبَى (Mujtabā)", False, "high",
             "Mojtaba is Arabic مُجْتَبَى (Mujtabā) 'chosen, selected', from the root ج ب ي (j-b-y). CRITICAL SOURCE ERROR: the source gave مجتبی (a Persian-script form); the correct Arabic form is مُجْتَبَى. The source gloss 'Guided' is unsupported and has been replaced with the lexical sense."),
 "mokbul": ("مقبول", "مقبول", "مقبول", "मक़बूल", "مقبول", "accepted", "Arabic", "Male",
            "Arabic root ق ب ل (q-b-l); مَقْبُول (Maqbūl)", False, "high",
            "Mokbul is Arabic مَقْبُول (Maqbūl) 'accepted, approved, received', from the root ق ب ل (q-b-l). CRITICAL SOURCE ERROR: the source gave مكبول (a different form); the correct form is مَقْبُول. The source gloss 'Gift, Blessing' is unsupported and has been replaced with the lexical sense."),
 "mokhtar": ("مختار", "مختار", "مختار", "मुख़्तार", "مختار", "mukhtar", "Arabic", "Male",
             "Arabic root خ ي ر (kh-y-r); مُخْتَار (Mukhtār)", False, "high",
             "Mokhtar is Arabic مُخْتَار (Mukhtār) 'chosen, elected, authorised', from the root خ ي ر (kh-y-r). The source gloss 'Chosen One, Elect' is consistent. Same name as moktar."),
 "moktar": ("مختار", "مختار", "مختار", "मुख़्तार", "مختار", "mukhtar", "Arabic", "Male",
            "Arabic root خ ي ر (kh-y-r); مُخْتَار (Mukhtār)", False, "high",
            "Moktar is Arabic مُخْتَار (Mukhtār) 'chosen, elected, authorised', from the root خ ي ر (kh-y-r). CRITICAL SOURCE ERROR: the source gave مُكْتَار (a different form); the correct form is مُخْتَار. The source gloss 'Powerful, Capable' is unsupported and has been replaced with the lexical sense. Same name as mokhtar."),
 "momin": ("مؤمن", "مومن", "مومن", "मोमिन", "مومن", "momin", "Arabic", "Male",
           "Arabic root أ م ن (ʾ-m-n); مُؤْمِن (Muʾmin)", False, "high",
           "Momin is Arabic مُؤْمِن (Muʾmin) 'believer, faithful', from the root أ م ن (ʾ-m-n). The source gloss 'Faithful, Believer' is consistent. Same name as moemen."),
 "momina": ("مؤمنة", "مومنہ", "مومنه", "मोमिना", "مومنه", "momina", "Arabic", "Female",
            "Arabic root أ م ن (ʾ-m-n); مُؤْمِنَة (Muʾmina)", False, "high",
            "Momina is Arabic مُؤْمِنَة (Muʾmina) 'believing' (feminine), from the root أ م ن (ʾ-m-n). CRITICAL SOURCE ERROR: the source gave مُمِنَة (a different form); the correct form is مُؤْمِنَة. The source gloss 'Beloved, Dear One' is unsupported and has been replaced with the lexical sense."),
 "mona": ("منى", "منیٰ", "منی", "मुना", "منی", "mona", "Arabic", "Female",
          "Arabic root م ن ي (m-n-y); مُنَى (Munā)", False, "high",
          "Mona is Arabic مُنَى (Munā) 'wishes, desires', from the root م ن ي (m-n-y). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as muna."),
}
