# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 25 (ghaffar..guzel).

The dominant source defect in this batch is ORIGIN MISLABELLING: the raw records label
almost every Persian گل/گلـ (gol-/gul-, 'flower/rose') name and every Turkish form as
"Arabic". Where the record's own script columns contradict its origin column, the script
column is the reliable evidence. Several records also carried placeholder or plainly wrong
"Arabic forms" (e.g. golala -> علی "Ali", golfam -> Aisha, guda -> أحمد, gufran -> a literal
placeholder string) and Arabic words whose letters do not spell the name (giath -> جث).

Fields: ar, ur, fa, hi, ps  -> script forms (None = not established for that language)
        gloss -> key into GLOSSES (None = no verified gloss)
        origin, gender, root, quranic, conf, note
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated24 import GLOSSES as _G24

GLOSSES = dict(_G24)
GLOSSES.update({
    "forgiving_ever": {"en": "Ever-forgiving, most forgiving", "ur": "بہت بخشنے والا، غفار", "fa": "بسیار آمرزنده، غفار", "hi": "अत्यंत क्षमाशील", "ps": "ډېر بخښونکی", "ar": "الغفار، كثير المغفرة"},
    "forgiving_one": {"en": "Forgiving", "ur": "بخشنے والا", "fa": "آمرزنده", "hi": "क्षमा करने वाला", "ps": "بخښونکی", "ar": "الغافر، الغفور"},
    "forgiveness": {"en": "Forgiveness, pardon", "ur": "بخشش، معافی", "fa": "آمرزش، بخشایش", "hi": "क्षमा, माफ़ी", "ps": "بخښنه، معافي", "ar": "الغفران، العفو"},
    "of_ghaffar": {"en": "Of Ghaffar (the ever-forgiving)", "ur": "غفار سے منسوب", "fa": "منسوب به غفار", "hi": "ग़फ़्फ़ार से संबंधित", "ps": "د غفار", "ar": "منسوب إلى الغفار"},
    "gainer_acquire": {"en": "One who gains, acquires", "ur": "حاصل کرنے والا، کمانے والا", "fa": "بهره‌مند، به‌دست‌آورنده", "hi": "प्राप्त करने वाला", "ps": "ګټونکی، ترلاسه کوونکی", "ar": "الغانم، الكاسب"},
    "shepherd": {"en": "Shepherd, keeper of sheep", "ur": "چرواہا، گلہ بان", "fa": "چوپان، گله‌بان", "hi": "चरवाहा, गड़रिया", "ps": "شپون، مالدار", "ar": "الراعي، الغنّام"},
    "traveler_wanderer": {"en": "Traveller, wanderer", "ur": "مسافر، سیاح", "fa": "مسافر، سیاح", "hi": "यात्री, घुमक्कड़", "ps": "مسافر، ګرځندوی", "ar": "المسافر، الجوّال"},
    "guide_leader": {"en": "Guide, leader", "ur": "راہ دکھانے والا، قائد", "fa": "رهنما، رهبر", "hi": "मार्गदर्शक, नेता", "ps": "لارښود، مشر", "ar": "الهادي، القائد"},
    "helper_supporter": {"en": "Helper, supporter", "ur": "مددگار، حامی", "fa": "یاری‌رسان، پشتیبان", "hi": "सहायक, समर्थक", "ps": "مرستندوی، ملاتړی", "ar": "المعين، النصير"},
    "gentle_kind": {"en": "Gentle, kind", "ur": "نرم، مہربان", "fa": "ملایم، مهربان", "hi": "कोमल, दयालु", "ps": "نرم، مهربان", "ar": "اللطيف، الكريم"},
    "precious_dear": {"en": "Precious, dear, expensive", "ur": "قیمتی، عزیز", "fa": "گران‌بها، عزیز", "hi": "कीमती, प्रिय", "ps": "ګران، ګران‌بها", "ar": "الغالي، العزيز"},
    "sweetness_delight": {"en": "Sweetness, delight", "ur": "مٹھاس، لذت", "fa": "شیرینی، لذت", "hi": "मिठास, आनंद", "ps": "خوږوالی، خوند", "ar": "الحلاوة، اللذة"},
    "protection_safety": {"en": "Protection, safety", "ur": "حفاظت، سلامتی", "fa": "نگهبانی، ایمنی", "hi": "सुरक्षा, हिफ़ाज़त", "ps": "ساتنه، امنیت", "ar": "الحماية، السلامة"},
    "conqueror_victor": {"en": "Conqueror, victor", "ur": "فاتح، غالب", "fa": "فاتح، پیروز", "hi": "विजेता, विजयी", "ps": "فاتح، بریالی", "ar": "الغالب، المنتصر"},
    "kind_gentle_beautiful": {"en": "Kind, gentle, beautiful", "ur": "مہربان، نرم، خوبصورت", "fa": "مهربان، لطیف، زیبا", "hi": "दयालु, कोमल, सुंदर", "ps": "مهربانه، نرمه، ښکلې", "ar": "اللطيفة، الحنونة، الجميلة"},
    "gracious_generous": {"en": "Gracious, generous", "ur": "کریم، مہربان", "fa": "بخشنده، کریم", "hi": "उदार, कृपालु", "ps": "سخي، مهربان", "ar": "الكريم، اللطيف"},
    "wealthy_rich": {"en": "Wealthy, rich, self-sufficient", "ur": "مالدار، خود کفیل", "fa": "توانگر، بی‌نیاز", "hi": "धनी, समृद्ध", "ps": "شتمن، بې‌نیاز", "ar": "الغني، الثري"},
    "gift_grace": {"en": "Gift, grace, blessing", "ur": "تحفہ، نعمت", "fa": "هدیه، نعمت", "hi": "उपहार, कृपा", "ps": "ډالۍ، نعمت", "ar": "الهدية، النعمة"},
    "love_passion": {"en": "Love, passion, intense desire", "ur": "عشق، شدید خواہش", "fa": "عشق، اشتیاق", "hi": "प्रेम, तीव्र इच्छा", "ps": "مینه، سخت هیله", "ar": "الغرام، العشق"},
    "stranger_foreigner": {"en": "Stranger, foreigner", "ur": "اجنبی، پردیسی", "fa": "بیگانه، غریب", "hi": "अजनबी, परदेसी", "ps": "بېګانه، پردی", "ar": "الغريب، الأجنبي"},
    "strong_firm": {"en": "Strong, firm", "ur": "مضبوط، قوی", "fa": "استوار، نیرومند", "hi": "मज़बूत, दृढ़", "ps": "پیاوړی، ټینګ", "ar": "القوي، الراسخ"},
    "fine_handsome": {"en": "Fine, handsome", "ur": "خوبصورت، خوش شکل", "fa": "خوش‌رو، زیبا", "hi": "सुंदर, रूपवान", "ps": "ښکلی، ښایسته", "ar": "الوسيم، الجميل"},
    "goal_aim": {"en": "Goal, aim, desire", "ur": "مقصد، ہدف", "fa": "هدف، مقصود", "hi": "लक्ष्य, उद्देश्य", "ps": "هدف، موخه", "ar": "الغاية، الهدف"},
    "graceful_tender": {"en": "Graceful, tender, slender", "ur": "نازک، خوبصورت", "fa": "ناز، لطیف", "hi": "कोमल, सुकुमार", "ps": "نازکه، ښکلې", "ar": "الغيداء، الرقيقة"},
    "of_wooded_valley": {"en": "Of the wooded valley", "ur": "جنگلی وادی کا، گھنے درختوں والا", "fa": "از دره جنگلی", "hi": "वन-घाटी का", "ps": "د ځنګلي درې", "ar": "الغيلان، ذو الغابة"},
    "zealous_honour": {"en": "Zealous for honour, protective jealousy", "ur": "غیرت والا، حمیت والا", "fa": "غیرتمند", "hi": "ग़ैरतमंद", "ps": "غيرتمن", "ar": "الغيور، ذو الغيرة"},
    "rain_succour": {"en": "Rain, succour, relief", "ur": "بارش، امداد", "fa": "باران، فریادرسی", "hi": "वर्षा, सहायता", "ps": "باران، مرسته", "ar": "الغيث، النجدة"},
    "gazelle": {"en": "Gazelle", "ur": "ہرن، غزال", "fa": "آهو، غزال", "hi": "हिरण, ग़ज़ाल", "ps": "غوی، غزال", "ar": "الغزال"},
    "gazelles": {"en": "Gazelles (plural)", "ur": "ہرنیں، غزالان", "fa": "آهوان", "hi": "हिरण (बहुवचन)", "ps": "غویان", "ar": "الغزلان"},
    "elegant_verse": {"en": "Elegant verse, ghazal poetry", "ur": "غزل، خوبصورت شعر", "fa": "غزل، شعر دلنشین", "hi": "ग़ज़ल, सुंदर पद्य", "ps": "غزل، ښکلې شعر", "ar": "الغزل، الشعر الرقيق"},
    "warrior_god": {"en": "Warrior for the cause of God", "ur": "اللہ کی راہ کا مجاہد", "fa": "جنگاور در راه خدا", "hi": "ईश्वर-मार्ग का योद्धा", "ps": "د الله په لار جنګیالی", "ar": "الغازي، المجاهد"},
    "fighter_warrior": {"en": "Fighter, warrior", "ur": "جنگجو، لڑنے والا", "fa": "جنگاور، نبردآور", "hi": "योद्धा, लड़ाकू", "ps": "جنګیالی، جنګاوښتی", "ar": "المقاتل، المحارب"},
    "expedition": {"en": "Military expedition, campaign", "ur": "جنگی مہم، غزوہ", "fa": "لشکرکشی، غزوه", "hi": "सैन्य अभियान", "ps": "جګړیزه مبارزه", "ar": "الغزوة، الحملة"},
    "song_singing": {"en": "Song, singing", "ur": "گیت، گانا", "fa": "آواز، سرود", "hi": "गीत, गाना", "ps": "سندره، ویل", "ar": "الغناء، الغنّاء"},
    "support_aid": {"en": "Succour, aid, relief", "ur": "امداد، مدد", "fa": "فریادرسی، کمک", "hi": "सहायता, राहत", "ps": "مرسته، لازموالی", "ar": "الغوث، الغياث"},
    "forgiveness_pardon": {"en": "Forgiveness, pardon, absolution", "ur": "معافی، بخشش", "fa": "آمرزش، بخشایش", "hi": "क्षमा, माफ़ी", "ps": "بخښنه، معافي", "ar": "الغفران، الصفح"},
    "servant_god": {"en": "Servant, young man; servant (of God)", "ur": "غلام، خادم", "fa": "غلام، خدمتگزار", "hi": "ग़ुलाम, सेवक", "ps": "غلام، خدمتګار", "ar": "الغلام، الخادم"},
    "bud_rosebud": {"en": "Bud, rosebud", "ur": "کلی، غنچہ", "fa": "غنچه، شکوفه", "hi": "कली, गुलमुखी", "ps": "ګونچه، شګوفه", "ar": "البرعم، الزهرة الناشئة"},
    "blossoms_branches": {"en": "Blossoming branches, boughs", "ur": "پھولتی شاخیں، ٹہنیاں", "fa": "شاخه‌های شکوفا", "hi": "खिलती डालियाँ", "ps": "ګل‌شوي ښاخونه", "ar": "الغصون، الأغصان"},
    "of_gilan": {"en": "Of Gilan (a region in Iran)", "ur": "گیلان کا، گیلان سے", "fa": "گیلانی، از گیلان", "hi": "गीलान का", "ps": "د ګيلان", "ar": "الجيلاني، من جيلان"},
    "of_ghazni": {"en": "Of Ghazni (a city)", "ur": "غزنی کا، غزنی سے", "fa": "غزنی، از غزنی", "hi": "ग़ज़नी का", "ps": "د غزني", "ar": "الغزنوي، من غزنة"},
    "of_ghazala": {"en": "Of Ghazala (a nisba / place-name)", "ur": "غزالہ کا، غزالہ سے منسوب", "fa": "منسوب به غزاله", "hi": "ग़ज़ाला से संबंधित", "ps": "د غزاله", "ar": "الغزالي، منسوب إلى غزالة"},
    "of_ghazanfar": {"en": "Of Ghazanfar (the lion)", "ur": "غضنفر سے منسوب", "fa": "منسوب به غضنفر", "hi": "ग़ज़नफ़र से संबंधित", "ps": "د غضنفر", "ar": "منسوب إلى غضنفر"},
    "gem": {"en": "Gem, jewel, essence", "ur": "جوہر، موتی، اصل", "fa": "گوهر، جواهر، اصل", "hi": "रत्न, जवाहर, सार", "ps": "جواهر، غمې، اصل", "ar": "الجوهر، الدرّ"},
    "rosewater": {"en": "Rosewater", "ur": "عرقِ گلاب", "fa": "گلاب", "hi": "गुलाबजल", "ps": "د ګلاب اوبه", "ar": "ماء الورد"},
    "rose": {"en": "Rose, flower", "ur": "گلاب، پھول", "fa": "گل، گل سرخ", "hi": "गुलाब, फूल", "ps": "ګلاب، ګل", "ar": "الوردة، الزهرة"},
    "flower_garden": {"en": "Flower garden, rose garden", "ur": "گلشن، گلستان", "fa": "گلستان، گلشن", "hi": "गुलशन, फूलों का बाग़", "ps": "ګلستان، ګلشن", "ar": "الحديقة، الروضة"},
    "pomegranate_flower": {"en": "Pomegranate flower", "ur": "انار کا پھول", "fa": "گل انار", "hi": "अनार का फूल", "ps": "د انار ګل", "ar": "زهرة الرمان"},
    "rose_petal": {"en": "Rose petal, rose-leaf", "ur": "گلبرگ، گلاب کی پتی", "fa": "گلبرگ", "hi": "गुलाब की पंखुड़ी", "ps": "د ګلاب پاڼه", "ar": "ورقة الورد"},
    "rose_faced": {"en": "Rose-faced, of rose countenance", "ur": "گل رخ، گلاب جیسا چہرہ", "fa": "گلرخ، گل‌چهره", "hi": "गुलरुख़, गुलाब-सा चेहरा", "ps": "ګلرخ، د ګلاب مخ", "ar": "ذو الوجه الوردي"},
    "flower_adorned": {"en": "Flower-adorned, decorated with flowers", "ur": "پھولوں سے سجا", "fa": "گل‌آرا، آراسته به گل", "hi": "फूलों से सजा", "ps": "په ګلونو سينګار شوی", "ar": "المزخرف بالزهور"},
    "delicate_rose": {"en": "Delicate rose, charming rose", "ur": "نازک گلاب، ناز والا پھول", "fa": "گل ناز، گل دلربا", "hi": "नाज़ुक गुलाब", "ps": "نازکه ګلاب", "ar": "الوردة الناعمة"},
    "flower_nectar": {"en": "Flower of nectar, sweet flower", "ur": "شہد کا پھول، شیریں پھول", "fa": "گل‌نوش، گل نوشین", "hi": "मधुर फूल", "ps": "د شهد ګل", "ar": "زهرة الرحيق"},
    "scattering_flowers": {"en": "Scattering flowers, strewing blossoms", "ur": "پھول بکھیرنے والا", "fa": "گل‌افشان، گل‌ریز", "hi": "फूल बिखेरने वाला", "ps": "ګل تویونکی", "ar": "ناثر الزهور"},
    "joyful_rose": {"en": "Joyful rose, rose of gladness", "ur": "خوش گلاب، شاد پھول", "fa": "گل‌شاد، گل خوشحال", "hi": "प्रसन्न गुलाब", "ps": "خوشحاله ګلاب", "ar": "الوردة الفرِحة"},
    "flower_gatherer": {"en": "Flower-gatherer, one who selects flowers", "ur": "پھول چننے والا", "fa": "گل‌چین", "hi": "फूल चुनने वाला", "ps": "ګل ټولونکی", "ar": "جامع الزهور"},
    "brave_hero": {"en": "Brave, hero", "ur": "بہادر، پہلوان", "fa": "دلیر، گرد", "hi": "बहादुर, वीर", "ps": "زړور، اتل", "ar": "الشجاع، البطل"},
    "mending_strength": {"en": "Mending, healing, strength", "ur": "مرمت، شفا، قوت", "fa": "ترمیم، شفا، توان", "hi": "सुधार, उपचार, शक्ति", "ps": "ترميم، شفا، ځواک", "ar": "الجبر، الإصلاح، القوة"},
    "angel_gabriel": {"en": "Gabriel, the angel of revelation", "ur": "جبرائیل، وحی کا فرشتہ", "fa": "جبرئیل، فرشته وحی", "hi": "जिब्रील, प्रकाशना का दूत", "ps": "جبرائيل، د وحي څښتن", "ar": "جبريل، الروح الأمين"},
    "rose_like": {"en": "Rose-like, rosebud", "ur": "گلاب جیسا، کلی", "fa": "گل‌مانند، غنچه", "hi": "गुलाब जैसा, कली", "ps": "د ګلاب په څېر", "ar": "كالوردة، برعم"},
    "jasmine_flower": {"en": "Jasmine flower", "ur": "چنبیلی کا پھول", "fa": "گل یاس", "hi": "चमेली का फूल", "ps": "د یاس ګل", "ar": "زهرة الياسمين"},
})

CUR = {
 "ghaffar": ("غفار", "غفار", "غفار", "ग़फ़्फ़ार", "غفار", "forgiving_ever", "Arabic", "Male",
             "Arabic root غ ف ر (gh-f-r); intensive غَفّار (Ghaffār)", False, "high",
             "Ghaffar is Arabic غَفّار (Ghaffār), the intensive form of the root غ ف ر (gh-f-r) 'to forgive' — 'most forgiving, ever-forgiving'. It is one of the divine names in Islamic tradition. The source form غفار (without the shadda) is a normal unvocalised spelling of the same word."),
 "ghaffari": ("غفاري", "غفاری", "غفاری", "ग़फ़्फ़ारी", "غفاري", "of_ghaffar", "Arabic", "Female",
              "Arabic nisba of غَفّار (Ghaffār)", False, "medium",
              "Ghaffari is a nisba (relational) form of غفار (Ghaffār) 'most forgiving', i.e. 'of Ghaffar'. The source gloss 'traveller, wanderer' belongs to a different root (س ف ر / ط و ف) and is not supported. The source records it as feminine; nisba forms are not intrinsically gendered."),
 "ghafir": ("غافر", "غافر", "غافر", "ग़ाफ़िर", "غافر", "forgiving_one", "Arabic", "Male",
            "Arabic root غ ف ر (gh-f-r); active participle غافِر (Ghāfir)", False, "high",
            "Ghafir is Arabic غافر (Ghāfir) 'the forgiving one', the active participle of the root غ ف ر (gh-f-r) 'to forgive'; it is also a divine name and the title of Surah 40 (al-Ghāfir, 'The Forgiver'). The source gloss 'the one who forgives' is correct."),
 "ghafoor": ("غفور", "غفور", "غفور", "ग़फ़ूर", "غفور", "forgiving_ever", "Arabic", "Male",
             "Arabic root غ ف ر (gh-f-r); intensive غَفور (Ghafūr)", False, "high",
             "Ghafoor is Arabic غفور (Ghafūr), an intensive adjective from the root غ ف ر (gh-f-r) meaning 'very forgiving, most forgiving' — a divine name in Islamic tradition. It is the same word already recorded under the earlier slug gafoor, in a different transliteration."),
 "ghafur": ("غفور", "غفور", "غفور", "ग़फ़ूर", "غفور", "forgiving_ever", "Arabic", "Male",
            "Arabic root غ ف ر (gh-f-r); غَفور (Ghafūr)", False, "high",
            "Ghafur is a transliteration of Arabic غفور (Ghafūr) 'most forgiving'. The same word appears in this batch as ghafoor and in the previous batch as gafoor."),
 "ghaida": (None, None, None, None, None, None, "Unknown", "Female",
            None, False, "unverified",
            "The source record gave the Arabic form غَذَاء — which is Arabic for 'nourishment, food' (from غ ذ و) and does not correspond to this name — together with the gloss 'guide, leader'. No Tier-A/B source establishes a name 'ghaida' with those letters and that meaning. Only reported female usage is retained; no form or gloss is asserted."),
 "ghaidaa": ("غيداء", "غیداء", "غیداء", "ग़ैदा", "غيداء", "graceful_tender", "Arabic", "Female",
             "Arabic root غ ي د (gh-y-d); غيداء (Ghaydāʾ)", False, "high",
             "Ghaidaa (غيداء, Ghaydāʾ) is an Arabic feminine name from the root غ ي د (gh-y-d), describing a young woman who is graceful, soft and slender — a classical poetic image likening her to a young gazelle. The source gloss 'guide, pathfinder' is wrong and has been replaced (it belongs to هدى/دلّ)."),
 "ghais": ("غيث", "غیس", "غیس", "ग़ैस", "غیس", "rain_succour", "Arabic", "Male",
           "Arabic root غ ي ث (gh-y-th); غيث (Ghayth)", False, "medium",
           "Ghais is best identified with غيث (Ghayth) 'rain; succour, relief', the rain that rescues a parched land — an established Arabic male name. The source gave غيس in the script columns and glossed it 'helper, supporter', which fits the 'succour' sense of غيث. The source's 'helper, supporter' gloss and the spelling غيس are both non-standard for the word."),
 "ghaisan": (None, "غیسان", "غیسان", None, "غیسان", None, "Arabic", "Male",
             "Arabic root غ ي س? (not established)", False, "low",
             "Ghaisan appears in South Asian naming usage, but no Tier-A/B source establishes a lexical form or settled meaning; the source gloss 'gentle, kind' is uncorroborated. Recorded at low confidence as a naming form only."),
 "ghaith": ("غيث", "غیث", "غیث", "ग़ैथ", "غیث", "rain_succour", "Arabic", "Male",
            "Arabic root غ ي ث (gh-y-th); غيث (Ghayth)", False, "high",
            "Ghaith (غيث) is an Arabic male name meaning 'rain' and, by extension, 'succour, relief' (rain being the classic image of deliverance in Arabic). The source record for this slug was completely empty (origin 'Unknown', no data) and has been completed from the form itself. It is the same name as ghais and ghayth in this batch."),
 "ghali": ("غالي", "غالی", "غالی", "ग़ाली", "غالي", "precious_dear", "Arabic", "Unisex",
           "Arabic root غ ل و (gh-l-w); غالي (Ghālī)", False, "high",
           "Ghali is Arabic غالي (Ghālī) 'dear, precious, expensive', from the root غ ل و (gh-l-w) 'to be high, exceed'. The source gloss 'heavy, burdensome, generous' conflates it with unrelated words (ثقل 'heaviness', كرم 'generosity') and has been replaced. The source records it as unisex; its better-attested usage is masculine."),
 "ghalia": ("غالية", "غالیہ", "غالیه", "ग़ालिया", "غالیه", "precious_dear", "Arabic", "Female",
            "Arabic root غ ل و (gh-l-w); غالية (Ghāliya)", False, "high",
            "Ghalia is Arabic غالية (Ghāliya) 'precious, dear (feminine)' — and also the name of a classical aromatic compound/perfume (ghāliya). The source gave only the Latin string 'Ghalia' for the script form and glossed it 'sweetness, delight'; the lexical sense is 'precious, dear'."),
 "ghaliah": ("غالية", "غالیہ", "غالیه", "ग़ालिया", "غالیه", "precious_dear", "Arabic", "Female",
             "Arabic root غ ل و (gh-l-w)", False, "high",
             "Ghaliah is a variant transliteration of Arabic غالية (Ghāliya) 'precious, dear'. The source gloss 'protection, safety' belongs to a different root (ح ف ظ / س ل م) and has been replaced."),
 "ghalib": ("غالب", "غالب", "غالب", "ग़ालिब", "غالب", "conqueror_victor", "Arabic", "Male",
            "Arabic root غ ل ب (gh-l-b); غالِب (Ghālib)", False, "high",
            "Ghalib is Arabic غالِب (Ghālib) 'conqueror, victor, dominant', the active participle of the root غ ل ب (gh-l-b) 'to overcome'. The source gloss 'conqueror, victor' is correct. It is a divine name in Islamic tradition and the pen-name of the Urdu poet Mirza Ghalib."),
 "ghaliya": ("غالية", "غالیہ", "غالیه", "ग़ालिया", "غالیه", "precious_dear", "Arabic", "Female",
             "Arabic root غ ل و (gh-l-w)", False, "high",
             "Ghaliya is a third transliteration of Arabic غالية (Ghāliya) 'precious, dear'. The source gloss 'kind, gentle, beautiful' is unsupported for this form and has been replaced."),
 "ghanem": ("غانم", "غانم", "غانم", "ग़ानिम", "غانم", "gainer_acquire", "Arabic", "Male",
            "Arabic root غ ن م (gh-n-m); غانِم (Ghānim)", False, "high",
            "Ghanem is Arabic غانم (Ghānim) 'one who gains, acquires; successful', the active participle of the root غ ن م (gh-n-m). The source gloss 'gracious, generous' belongs to a different root (ك ر م) and has been replaced."),
 "ghani": ("غني", "غنی", "غنی", "ग़नी", "غني", "wealthy_rich", "Arabic", "Male",
           "Arabic root غ ن ي (gh-n-y); غَنيّ (Ghaniyy)", False, "high",
           "Ghani is Arabic غنيّ (Ghaniyy) 'rich, wealthy, self-sufficient, free from want' — also one of the divine names (al-Ghaniyy). The source gloss 'handsome, generous' is wrong for this word and has been replaced."),
 "ghania": ("غنية", "غنیہ", "غنيه", "ग़निया", "غنيه", "wealthy_rich", "Arabic", "Female",
            "Arabic root غ ن ي (gh-n-y); غنية (Ghaniyya)", False, "high",
            "Ghania is the feminine of غنيّ — غنية (Ghaniyya) 'rich, self-sufficient, free from want'. The source gloss 'gift, grace, blessing' is unsupported for this form and has been replaced."),
 "ghanim": ("غنيم", "غانم", "غانم", "ग़नीम", "غانم", "gainer_acquire", "Arabic", "Male",
            "Arabic root غ ن م (gh-n-m)", False, "medium",
            "Ghanim relates to the root غ ن م (gh-n-m): غانِم (Ghānim) 'one who gains, acquires' and its diminutive غُنَيم (Ghunaym). The source mixed the two (Arabic form غَنِيم, Urdu form غانم) and glossed it 'generous, provision, rich', which belongs to different roots; the 'gainer, acquirer' sense is recorded here."),
 "ghaniya": ("غنية", "غنیہ", "غنيه", "ग़निया", "غنيه", "wealthy_rich", "Arabic", "Female",
             "Arabic root غ ن ي (gh-n-y)", False, "high",
             "Ghaniya is Arabic غنية (Ghaniyya) 'rich, free from want (feminine)'. The source gloss 'the grateful one' confuses غنيّ 'rich' with شاكرة 'grateful' and has been replaced. It is effectively the same name as ghania, recorded under a separate slug."),
 "ghannam": ("غنام", "غنام", "غنام", "ग़न्नाम", "غنام", "shepherd", "Arabic", "Male",
             "Arabic root غ ن م (gh-n-m); غنّام (Ghannām)", False, "medium",
             "Ghannam is Arabic غنّام (Ghannām) 'shepherd, keeper of sheep', from غنم (ghanam) 'sheep, livestock'. The source gloss 'traveller, journey' belongs to a different root (س ف ر) and has been replaced."),
 "gharam": ("غرام", "غرام", "غرام", "ग़राम", "غرام", "love_passion", "Arabic", "Female",
            "Arabic root غ ر م (gh-r-m); غرام (Gharām)", False, "high",
            "Gharam is Arabic غرام (Gharām) 'passionate love, infatuation, ardour' (the root غ ر م also yields 'debt, penalty'). The source gloss 'love, passion, intense desire' is correct. The source records it as feminine."),
 "ghareeb": ("غريب", "غریب", "غريب", "ग़रीब", "غريب", "stranger_foreigner", "Arabic", "Male",
             "Arabic root غ ر ب (gh-r-b); غريب (Gharīb)", False, "high",
             "Ghareeb is Arabic غريب (Gharīb) 'stranger, foreigner, one far from home', from the root غ ر ب (gh-r-b). The source gloss 'stranger, foreigner' is correct. It is the same name as gharib in this batch."),
 "gharib": ("غريب", "غریب", "غريب", "ग़रीब", "غريب", "stranger_foreigner", "Arabic", "Male",
            "Arabic root غ ر ب (gh-r-b); غريب (Gharīb)", False, "high",
            "Gharib is a transliteration of Arabic غريب (Gharīb) 'stranger, foreigner'. Same name as ghareeb."),
 "ghasaan": ("غسان", "غسان", "غسان", "ग़स्सान", "غسان", "strong_firm", "Arabic", "Male",
             "Arabic غسّان (Ghassān) — tribal name; further etymology disputed", False, "medium",
             "Ghasaan is a spelling variant of غسّان (Ghassān), the name of the Ghassanid Arab tribe and kingdom. Its deeper etymology is not securely established; the source gloss 'strong, firm' is one traditional explanation but is not confirmed by a Tier-A reference, so it is recorded at medium confidence."),
 "ghassan": ("غسان", "غسان", "غسان", "ग़स्सान", "غسان", "fine_handsome", "Arabic", "Male",
             "Arabic غسّان (Ghassān)", False, "medium",
             "Ghassan is the standard transliteration of غسّان (Ghassān), the Ghassanid tribal name. The source gloss 'fine, handsome' and the sibling record's 'strong, firm' are two different traditional explanations of a name whose deeper etymology is disputed; this is recorded at medium confidence and neither gloss should be treated as settled."),
 "ghaya": ("غاية", "غایہ", "غايه", "ग़ाया", "غايه", "goal_aim", "Arabic", "Female",
           "Arabic root غ ي ي (gh-y-y); غاية (Ghāya)", False, "high",
           "Ghaya is Arabic غاية (Ghāya) 'goal, aim, end, purpose', from the root غ ي ي. The source gloss 'goal, aim, desire' is correct."),
 "ghayda": (None, "غیدہ", "غیده", "ग़ैदा", None, None, "Arabic", "Female",
            "Arabic root غ ي د (gh-y-d)", False, "medium",
            "Ghayda corresponds to the feminine form of غيداء (Ghaydāʾ) — غيد (Ghayd) — describing a graceful, slender young woman, from the root غ ي د. The source gave the unrelated غيضة ('thicket') and the gloss 'guide, leader', neither of which belongs to this name. The 'graceful' reading is recorded at medium confidence given the source's conflicting columns."),
 "ghaydaa": ("غيداء", "غیداء", "غیداء", "ग़ैदा", "غيداء", "graceful_tender", "Arabic", "Female",
             "Arabic root غ ي د (gh-y-d); غيداء (Ghaydāʾ)", False, "high",
             "Ghaydaa (غيداء, Ghaydāʾ) is an Arabic feminine name meaning graceful, soft, tender — classically used of a slender young woman or a young gazelle. The source gave the unrelated غايضة in the script column and the gloss 'guide, pilot, leader'; both have been replaced."),
 "ghaylan": ("غيلان", "غیلان", "غيلان", "ग़ैलान", "غيلان", "of_wooded_valley", "Arabic", "Male",
             "Arabic غيلان (Ghaylān), from غيل (ghayl) 'a valley with trees and water'", False, "medium",
             "Ghaylan (غيلان) is an established Arabic male name, borne for example by the pre-Islamic figure Ghaylan ibn Salamah. It relates to غيل (ghayl) 'a valley densely wooded with water' — hence 'of the wooded valley'. The source gloss 'mountainous' is not the attested sense. Because the exact derivation is not settled, this is recorded at medium confidence."),
 "ghayoor": ("غيور", "غیور", "غیور", "ग़यूर", "غیور", "zealous_honour", "Arabic", "Male",
             "Arabic root غ ي ر (gh-y-r); غيور (Ghayūr)", False, "high",
             "Ghayoor is Arabic غيور (Ghayūr) 'zealous for honour, protective of what is sacred, jealous in the honourable sense', an intensive adjective from the root غ ي ر (gh-y-r). The source gloss 'light, radiant' belongs to a different root (ن و ر) and has been replaced."),
 "ghays": ("غيث", "غیس", "غیس", "ग़ैस", "غیس", "rain_succour", "Arabic", "Male",
           "Arabic root غ ي ث (gh-y-th)", False, "medium",
           "Ghays is best identified with غيث (Ghayth) 'rain; succour'. The source gave غيس and glossed it 'stranger, traveller', which belongs to a different root (غ ر ب); the 'rain/succour' reading is recorded at medium confidence. It is the same name as ghais and ghaith."),
 "ghaysaa": ("غيثة", "غیثہ", "غيثه", "ग़ैसा", "غيثه", "rain_succour", "Arabic", "Female",
             "Arabic root غ ي ث (gh-y-th); غيثة (Ghaytha)", False, "medium",
             "Ghaysaa corresponds to غيثة (Ghaytha), the feminine of غيث (Ghayth) 'rain, succour'. The source gloss 'seeking refuge' is close to the 'succour/rescue' sense of the root and is retained in that sense."),
 "ghayth": ("غيث", "غیث", "غيث", "ग़ैथ", "غيث", "rain_succour", "Arabic", "Male",
            "Arabic root غ ي ث (gh-y-th); غيث (Ghayth)", False, "high",
            "Ghayth (غيث) is an Arabic male name meaning 'rain' and 'succour, relief'. The source gloss 'intense rain' is a fair rendering. Same name as ghaith and ghais."),
 "ghayur": ("غيور", "غیور", "غیور", "ग़यूर", "غیور", "zealous_honour", "Arabic", "Male",
            "Arabic root غ ي ر (gh-y-r); غيور (Ghayūr)", False, "high",
            "Ghayur is a transliteration of Arabic غيور (Ghayūr) 'zealous for honour'. The source gloss 'exalted, sublime' belongs to a different root (ع ل و) and has been replaced. Same name as ghayoor."),
 "ghazaal": ("غزال", "غزال", "غزال", "ग़ज़ाल", "غزال", "gazelle", "Arabic", "Female",
             "Arabic root غ ز ل (gh-z-l); غزال (Ghazāl)", False, "high",
             "Ghazaal is Arabic غزال (Ghazāl) 'gazelle' — a standard Arabic image of grace and beauty. The source gloss 'delight, pleasure' is unsupported and has been replaced. (Compare غزل ghazal, which is the love-poetry form — a different word.)"),
 "ghazal": ("غزل", "غزل", "غزل", "ग़ज़ल", "غزل", "elegant_verse", "Arabic", "Female",
            "Arabic root غ ز ل (gh-z-l); غزل (ghazal)", False, "medium",
            "Ghazal (غزل) is properly the Arabic/Persian/Urdu word for the ghazal poetic form ('amatory verse'), from the root غ ز ل; the gazelle word is غزال (ghazāl), with a long ā. The name Ghazal is popularly given with the sense 'gazelle', so both the poetic and the gazelle associations are recorded. The source record for this slug was empty and has been completed from the form itself."),
 "ghazala": ("غزالة", "غزالہ", "غزاله", "ग़ज़ाला", "غزاله", "gazelle", "Arabic", "Female",
             "Arabic root غ ز ل (gh-z-l); غزالة (Ghazāla)", False, "high",
             "Ghazala is Arabic غزالة (Gazāla) 'gazelle' — a classical Arabic female name and a byword for grace and beauty in Arabic poetry. The source gloss 'gazelle, deer' is a fair rendering."),
 "ghazalat": ("غزالات", "غزالات", "غزالات", "ग़ज़ालात", "غزالات", "gazelles", "Arabic", "Female",
              "Arabic root غ ز ل (gh-z-l); plural of غزالة (Ghazāla)", False, "medium",
              "Ghazalat (غزالات) is the plural of غزالة (ghazāla) 'gazelle' — 'gazelles'. The source gloss 'elegant verse, poem' confuses it with غزل (ghazal, the poetic form); the 'gazelles' sense is the correct lexical reading of this shape."),
 "ghazali": (None, "غزالی", "غزالی", "ग़ज़ाली", "غزالي", "of_ghazala", "Arabic", "Male",
             "Arabic nisba الغزالي (al-Ghazālī)", False, "medium",
             "Ghazali is the nisba (relational surname) al-Ghazālī, borne by the celebrated scholar Abū Ḥāmid al-Ghazālī; it means 'of Ghazāla' (a place-name), or is connected with غزال 'spinner/gazelle'. It is a surname/nisba rather than a lexical given name. The source record for this slug was empty and has been completed from the form itself."),
 "ghazanfar": ("غضنفر", "غضنفر", "غضنفر", "ग़ज़नफ़र", "غضنفر", "lion_brave", "Arabic", "Male",
               "Arabic غضنفر (Ghaḍanfar) — an epithet of the lion", False, "high",
               "Ghazanfar (غضنفر, Ghaḍanfar) is a classical Arabic personal name and one of the Arabic epithets for the lion — 'brave lion'; it was also used as a title of Caliph Ali. The source gloss 'victorious warrior' is a loose paraphrase of the lion-epithet sense."),
 "ghazanfari": (None, "غضنفری", "غضنفری", "ग़ज़नफ़री", "غضنفري", "of_ghazanfar", "Arabic", "Male",
                "Arabic nisba of غضنفر (Ghaḍanfar)", False, "medium",
                "Ghazanfari is the nisba (relational) form of غضنفر (Ghaḍanfar) 'lion' — 'leonine, of the lion'. The source gloss 'military commander, warrior' is an extension of the lion-epithet rather than a lexical meaning."),
 "ghazi": ("غازي", "غازی", "غازی", "ग़ाज़ी", "غازي", "warrior_god", "Arabic", "Male",
           "Arabic root غ ز و (gh-z-w); غازي (Ghāzī)", False, "high",
           "Ghazi (غازي) is Arabic for 'one who takes part in a ghazw (expedition), a warrior for the faith', the active participle of the root غ ز و (gh-z-w). The source gloss 'warrior for the cause of God' captures its standard sense. The source's '(Male/Female/Unisex)' gender string was normalised; documented usage is overwhelmingly masculine."),
 "ghazni": (None, "غزنی", "غزنی", "ग़ज़नी", "غزني", "of_ghazni", "Arabic", "Unisex",
            "Arabic nisba غزنوي (Ghaznawī) 'of Ghazni'", False, "medium",
            "Ghazni is properly a place-name (the Afghan city) and a nisba, 'of Ghazni' — the same element seen in the Ghaznavid dynasty. The source gloss 'warrior or victorious' mixes in the sense of ghāzī (a different word); the place/nisba sense is recorded here."),
 "ghazwa": ("غزوة", "غزوہ", "غزوه", "ग़ज़वा", "غزوه", "expedition", "Arabic", "Female",
            "Arabic root غ ز و (gh-z-w); غزوة (Ghazwa)", False, "medium",
            "Ghazwa (غزوة) is Arabic for 'a military expedition or campaign'; in Islamic history it denotes a campaign in which the Prophet himself took part. The source gloss 'military raid, conquest' is a fair rendering. It is a lexical noun; its use as a female personal name is reported but uncommon."),
 "ghazwan": ("غزوان", "غزوان", "غزوان", "ग़ज़वान", "غزوان", "fighter_warrior", "Arabic", "Male",
             "Arabic root غ ز و (gh-z-w); غزوان (Ghazwān)", False, "high",
             "Ghazwan (غزوان) is an Arabic male name from the root غ ز و (gh-z-w) 'to set out for battle', meaning 'fighter, warrior'. The source gloss 'fighter, warrior' is correct."),
 "ghina": ("غناء", "غناء", "غناء", "ग़िना", "غناء", "song_singing", "Arabic", "Female",
           "Arabic root غ ن ي (gh-n-y); غناء (ghināʾ)", False, "high",
           "Ghina is Arabic غناء (ghināʾ) 'song, singing', from the root غ ن ي. The source gloss 'joyful, delightful' is unsupported (and appears to conflate it with غنى 'wealth' or with ghinā in its 'sufficiency' sense); the lexical sense 'song, singing' is recorded here."),
 "ghiyas": ("غياث", "غیاث", "غیاث", "ग़ियास", "غیاث", "support_aid", "Arabic", "Male",
            "Arabic root غ و ث (gh-w-th); غياث (Ghiyāth)", False, "high",
            "Ghiyas is a South Asian spelling of Arabic غياث (Ghiyāth) 'succour, aid, rescue', from the root غ و ث (gh-w-th). The source gloss 'support, strength' is close; 'succour/aid' is the lexical sense. Its '(Male/Female/Unisex)' gender string was normalised to reported male usage."),
 "ghiyath": ("غياث", "غیاث", "غیاث", "ग़ियास", "غیاث", "support_aid", "Arabic", "Male",
             "Arabic root غ و ث (gh-w-th); غياث (Ghiyāth)", False, "high",
             "Ghiyath is a transliteration of Arabic غياث (Ghiyāth) 'succour, aid'. The source gloss 'help, aid' is correct. The source's Arabic column mistakenly gave غيث (Ghayth, 'rain'); both derive from adjacent senses of relief and are closely related names."),
 "ghizlan": ("غزلان", "غزلان", "غزلان", "ग़िज़लान", "غزلان", "gazelles", "Arabic", "Female",
             "Arabic root غ ز ل (gh-z-l); plural غزلان (ghizlān)", False, "high",
             "Ghizlan (غزلان) is the plural of غزال (ghazāl) 'gazelle' — 'gazelles'. The source gloss 'steadfast, determined' is unsupported and has been replaced with the actual lexical sense."),
 "ghofran": ("غفران", "غفران", "غفران", "ग़ुफ़रान", "غفران", "forgiveness_pardon", "Arabic", "Female",
             "Arabic root غ ف ر (gh-f-r); غفران (Ghufrān)", False, "high",
             "Ghofran is a transliteration of Arabic غفران (Ghufrān) 'forgiveness, pardon, absolution', from the root غ ف ر. The source gloss 'pure, clean, beautiful' is unsupported and has been replaced. It is the same word as ghufran in this batch."),
 "ghorzang": (None, "غورزنگ", "غورزنگ", None, "غورزنگ", None, "Pashto", "Male",
              None, False, "low",
              "Ghorzang is a Pashto male name and place-name (Ghorzang is a locality in Kabul). No Tier-A/B source establishes its lexical meaning; the source gloss 'warrior of God' is not corroborated, and the record laboured under an 'Arabic' origin that the script column contradicts. Recorded at low confidence as a Pashto naming form."),
 "ghufran": ("غفران", "غفران", "غفران", "ग़ुफ़रान", "غفران", "forgiveness_pardon", "Arabic", "Unisex",
             "Arabic root غ ف ر (gh-f-r); غفران (Ghufrān)", False, "high",
             "Ghufran (غفران) is Arabic for 'forgiveness, pardon, absolution' — an established given name as well as a religious concept word. The source gloss 'forgiveness pardon' is correct. The source's 'Unisex' label reflects mixed modern use; it is used for both sexes."),
 "ghulam": ("غُلام", "غلام", "غلام", "ग़ुलाम", "غلام", "servant_god", "Arabic", "Male",
            "Arabic root غ ل م (gh-l-m); غُلام (Ghulām)", False, "high",
            "Ghulam (غُلام) is Arabic for 'boy, young man, servant, slave', from the root غ ل م (gh-l-m). In naming it is overwhelmingly used as the first element of a compound, e.g. غلام محمد 'servant of Muhammad'. The source gloss 'servant of God' reflects that compound pattern rather than the meaning of the bare word; it is not by itself a divine-name theophoric."),
 "ghuncha": ("غنچه", "غنچہ", "غنچه", "ग़ुंचा", "غنچه", "bud_rosebud", "Persian", "Female",
             "Persian غنچه (ghonche) 'bud'", False, "high",
             "Ghuncha is the Persian word غنچه (ghonche) 'bud, flower bud — specifically a rosebud', used as a feminine given name across Persian, Urdu and Turkic cultures. The source labelled it 'Arabic' and glossed it 'bright, shining light'; the script column (غنچه) is the reliable evidence and the gloss has been replaced."),
 "ghusoon": (None, "غصون", "غصون", None, "غصون", "blossoms_branches", "Arabic", "Female",
             "Arabic root غ ص ن (gh-ṣ-n); plural غصون (ghuṣūn)", False, "medium",
             "Ghusoon corresponds to Arabic غصون (ghuṣūn), the plural of غصن (ghuṣn) 'branch, bough' — 'branches'. The source gloss 'protection, guardianship' belongs to a different root (ح ف ظ) and has been replaced."),
 "ghusoun": (None, "غصون", "غصون", None, "غصون", "blossoms_branches", "Arabic", "Female",
             "Arabic root غ ص ن (gh-ṣ-n)", False, "medium",
             "Ghusoun is a spelling variant of Ghusoon (غصون) 'branches, boughs'. The source gloss 'delicacy, fragility' is unsupported for this form and has been replaced."),
 "ghusun": ("غُصون", "غصون", "غصون", "ग़ुसून", "غصون", "blossoms_branches", "Arabic", "Female",
            "Arabic root غ ص ن (gh-ṣ-n); غُصون (ghuṣūn)", False, "medium",
            "Ghusun (غُصون) is the plural of غصن (ghuṣn) 'branch' — 'branches, boughs'. The source gloss 'blossoming branch' is a fair approximation of the image. Same word as ghusoon and ghusoun."),
 "giath": ("غياث", "غیاث", "غیاث", "ग़ियास", "غیاث", "support_aid", "Arabic", "Male",
           "Arabic root غ و ث (gh-w-th); غياث (Ghiyāth)", False, "medium",
           "Giath is best identified with غياث (Ghiyāth) 'succour, aid' — the same name as ghiyas/ghiyath in this batch. The source gave جث (a bare root fragment, not the name) and glossed it 'powerful, valiant', neither of which matches; both were corrected. The identification is recorded at medium confidence because the source columns are corrupt."),
 "gibran": ("جبران", "جبران", "جبران", "जिब्रान", "جبران", "mending_strength", "Arabic", "Male",
            "Arabic root ج ب ر (j-b-r); جبران (Jibrān / Jubrān)", False, "high",
            "Gibran is Arabic جبران (Jibrān / Jubrān), from the root ج ب ر (j-b-r) 'to mend, set right, restore; to be strong' — hence 'mending, healing, strength'. It is the name made famous in the West by the poet Kahlil Gibran. The source gloss 'powerful, generous' captures the 'strength' element but drops the primary 'mending/healing' sense."),
 "gibril": ("جبريل", "جبریل", "جبريل", "जिब्रील", "جبرائيل", "angel_gabriel", "Hebrew", "Male",
            "Hebrew גַּבְרִיאֵל (Gaḇrīʾēl) 'man of God, strength of God'", True, "high",
            "Gibril is the Arabic form جبريل (Jibrīl) of the name of the archangel Gabriel, from Hebrew גַּבְרִיאֵל Gaḇrīʾēl ('man of God / strength of God'). In Islam Jibrīl is the angel of revelation and is named in the Qur'an (2:97, 2:98, 66:4). The linguistic origin of the name is Hebrew; the Arabic جبريل is its Qur'anic form. CRITICAL SOURCE ERROR: the source gave غبريل (with غ, a different letter) — the correct form is جبريل."),
 "gilani": ("جيلاني", "گیلانی", "گیلانی", "गीलानी", "ګيلاني", "of_gilan", "Arabic", "Unisex",
            "Arabic nisba جيلاني (Jīlānī) 'of Gilan'", False, "medium",
            "Gilani is the Arabic nisba جيلاني (Jīlānī) 'of Gilan' — the Caspian province of Iran (Persian گیلان). It is best known through the Sufi saint ʿAbd al-Qādir al-Jīlānī. The source gloss 'from the garden' is a folk etymology (reading gol 'flower' into the place-name); the correct relational sense is 'of Gilan'."),
 "gohar": ("جوهر", "گوہر", "گوهر", "गोहर", "ګوهر", "gem", "Persian", "Female",
           "Persian گوهر (gawhar) < Middle Persian gōhr", False, "high",
           "Gohar is the Persian گوهر (gawhar) 'jewel, gem, pearl' and, by extension, 'essence, intrinsic worth' (Middle Persian gōhr 'substance, essence'). It is the same name recorded as gauhar in the previous batch. The source labelled it 'Arabic' and glossed it 'light, radiance'; the word is Persian and its sense is 'gem/essence'."),
 "golab": ("گلاب", "گلاب", "گلاب", "गुलाब", "ګلاب", "rosewater", "Persian", "Unisex",
           "Persian گلاب (golāb) 'rosewater', from گل (gol) + آب (āb)", False, "high",
           "Golab is the Persian compound گلاب (golāb) 'rosewater' (گل 'flower/rose' + آب 'water'), used as a given name in Persian, Urdu and Pashto communities. The source supplied only the Latin string 'Golab' for the script columns and labelled it 'Arabic'; the word is Persian."),
 "golala": (None, "گلالہ", "گلاله", None, None, None, "Unknown", "Female",
            None, False, "unverified",
            "CRITICAL SOURCE ERROR: the source record gave علی ('Ali') as this name's Arabic form and Urdu form — a completely different name — and labelled the record 'Arabic'. No verified lexical form was established for golala itself. Only reported female usage in Persianate naming is retained; nothing is asserted about its meaning."),
 "golan": (None, "گولان", "گولان", None, "ګولان", None, "Unknown", "Male",
           None, False, "unverified",
           "Golan is chiefly a place-name (the Golan Heights); the source's Arabic form جَلان and the gloss 'hill, elevated land' are not corroborated for this shape, and the 'Arabic' origin label contradicts the script column. No lexical identification was established, so no gloss is asserted."),
 "golara": (None, "گل آرا", "گل‌آرا", None, "ګل آرا", "flower_adorned", "Persian", "Female",
            "Persian گل‌آرا (gol-ārā) 'flower-adorned'", False, "medium",
            "Golara is the Persian گلآرا (gol-ārā) 'flower-adorned, decorated with flowers' (گل 'flower' + آرا 'adorning'), used as a feminine name. The source gave the meaningless غلرة as the 'Arabic form' and glossed it 'golden flower'; both were corrected."),
 "golbarg": (None, "گلبرگ", "گلبرگ", None, "ګلبرګ", "rose_petal", "Persian", "Female",
             "Persian گلبرگ (golbarg) 'rose petal', from گل (gol) + برگ (barg) 'leaf'", False, "high",
             "Golbarg is the Persian گلبرگ (golbarg) 'rose petal' (گل 'flower' + برگ 'leaf, petal'), a feminine name. The source supplied only the Latin string and labelled it 'Arabic' with the gloss 'jewel'; the word is Persian and means 'rose petal'."),
 "golestan": (None, "گلستان", "گلستان", None, "ګلستان", "flower_garden", "Persian", "Female",
              "Persian گلستان (golestān) 'land of flowers, rose garden'", False, "high",
              "Golestan is the Persian گلستان (golestān) — گل 'flower' + the place-suffix ـستان — 'land of flowers, rose garden'. It is the title of Saʿdi's celebrated prose-and-verse work and the name of a province of Iran, and is used as a given name. The source supplied only Latin strings and mislabelled it 'Arabic'."),
 "golfam": (None, "گلفام", "گلفام", None, None, None, "Unknown", "Female",
            None, False, "unverified",
            "CRITICAL SOURCE ERROR: the source record gave عائشة ('Aisha') as this name's Arabic form and Urdu form — a completely different name. Golfam (Persian گلفام) appears in Persianate naming, but no Tier-A/B source establishes a settled lexical meaning for it. No gloss is asserted."),
 "golnar": (None, "گلنار", "گلنار", None, "ګلنار", "pomegranate_flower", "Persian", "Female",
            "Persian گلنار (golnār) 'pomegranate flower', from گل (gol) + نار (nār) 'pomegranate'", False, "high",
            "Golnar is the Persian گلنار (golnār) 'pomegranate flower' (گل 'flower' + نار 'pomegranate'), a well-established feminine name in Persian, Urdu, Azerbaijani and Turkish usage. The source supplied only Latin strings, labelled it 'Arabic' and glossed it 'light, bright'; the word is Persian and means 'pomegranate flower'."),
 "golnaz": (None, "گلناز", "گلناز", None, "ګلناز", "delicate_rose", "Persian", "Female",
            "Persian گلناز (golnāz) 'delicate/charming rose', from گل + ناز 'coquetry, charm'", False, "medium",
            "Golnaz is the Persian گلناز (golnāz) — گل 'flower' + ناز 'coquetry, allure' — 'a rose of charm, a delicate rose'. It is a common feminine name in Persian and Urdu usage. CRITICAL SOURCE ERROR: the source gave عائشة ('Aisha') as this name's Arabic form; that has been removed."),
 "golnoush": (None, "گلنوش", "گلنوش", None, "ګلنوش", "flower_nectar", "Persian", "Female",
              "Persian گلنوش (golnush) 'flower of nectar', from گل + نوش 'nectar'", False, "medium",
              "Golnoush is the Persian گلنوش (golnush) — گل 'flower' + نوش 'nectar' — 'flower of nectar, sweet flower', a feminine name. The source supplied only Latin strings and mislabelled it 'Arabic' while glossing it 'golden light'; the compound reading is recorded at medium confidence."),
 "golpar": (None, "گلپر", "گلپر", None, None, None, "Persian", "Unisex",
            "Persian گلپر (golpar) — a plant name", False, "low",
            "Golpar is a Persian word for a plant (golpar, used as a spice); it appears as a given name in Persianate usage but no Tier-A/B source establishes a personal-name meaning. The source gloss 'golden fruit' is unsupported. Recorded at low confidence."),
 "golrokh": (None, "گلرخ", "گلرخ", None, "ګلرخ", "rose_faced", "Persian", "Female",
             "Persian گلرخ (golrokh) 'rose-faced', from گل + رخ 'face'", False, "high",
             "Golrokh is the Persian گلرخ (golrokh) — گل 'flower' + رخ 'face, countenance' — 'rose-faced, of rose countenance'. The source gave the meaningless غُلرُخ and mislabelled it 'Arabic' while glossing it 'rose garden'; both were corrected."),
 "golsa": (None, "گلسا", "گلسا", None, "ګلسا", "rose_like", "Persian", "Female",
           "Persian گل‌سا (golsā) 'rose-like'", False, "low",
           "Golsa is the Persian گل‌سا (golsā) 'rose-like, resembling a rose', a modern feminine name. The source gave the meaningless غلسة and glossed it 'rosebud'. Because the formation is recent and not carried in standard dictionaries, it is recorded at low confidence."),
 "golshan": (None, "گلشن", "گلشن", None, "ګلشن", "flower_garden", "Persian", "Female",
             "Persian گلشن (golshan) 'rose garden'", False, "high",
             "Golshan is the Persian گلشن (golshan) 'rose garden, flower garden'. The source supplied only Latin strings and mislabelled it 'Arabic'. It is the same word as gulshan in this batch."),
 "golzar": (None, "گلزار", "گلزار", None, "ګلزار", "flower_garden", "Persian", "Female",
            "Persian گلزار (golzār) 'rose garden, flower bed', from گل + زار", False, "high",
            "Golzar is the Persian گلزار (golzār) 'rose garden, flower bed' (گل 'flower' + زار 'place of'). The source gave the meaningless غزر as the 'Arabic form' and glossed it 'jewel, treasure'; both were corrected."),
 "gonca": ("gonca", "گونجہ", "گلنچه", "गोंजा", "ګونجه", "bud_rosebud", "Turkish", "Female",
           "Turkish gonca 'bud, blossom' < Persian غنچه (ghonche)", False, "high",
           "Gonca is the Turkish feminine name gonca 'bud, unopened flower, blossom', borrowed from Persian غنچه (ghonche), the same word recorded as ghuncha above. The source gave عونقة (a different Arabic word) as the form and glossed it 'joyful, happy'; the name is Turkish and its sense is 'bud'."),
 "gord": (None, "گرد", "گرد", None, "ګرد", "brave_hero", "Persian", "Unisex",
          "Persian گُرد (gord) 'brave, hero, champion' (also گرد gerd 'round')", False, "low",
          "Gord appears in Persian naming and epic vocabulary as گُرد (gord) 'brave, hero, champion' (the Shahnameh uses it of warriors); the homograph گرد (gerd) 'round' is a different word. The source supplied only Latin strings, labelled it Arabic, and glossed it 'mountain' — none of which is supported. Recorded at low confidence."),
 "guda": (None, None, None, None, None, None, "Unknown", "Unknown",
          None, False, "unverified",
          "CRITICAL SOURCE ERROR: the source record gave أحمد ('Ahmad') as this name's Arabic form and Urdu form — a different name entirely. No verified identification of guda was established, so no form, meaning or gender is asserted."),
 "gufran": ("غفران", "غفران", "غفران", "ग़ुफ़रान", "غفران", "forgiveness_pardon", "Arabic", "Male",
            "Arabic root غ ف ر (gh-f-r); غفران (Ghufrān)", False, "medium",
            "Gufran is a transliteration of Arabic غفران (Ghufrān) 'forgiveness, pardon' — the same word as ghufran and ghofran in this batch. CRITICAL SOURCE ERROR: the source record's Arabic and Urdu columns contained literal placeholder strings ('عربي_Gufran', 'اردو_Gufran') rather than script forms; these have been replaced with the correct form. The source gloss 'noble and blessed' is unsupported for this word."),
 "gul": ("غول", "گل", "گل", "गुल", "ګل", "rose", "Persian", "Female",
         "Persian گل (gol) 'flower, rose'", False, "high",
         "Gul is the Persian/Urdu گل (gol/gul) 'flower, rose' — one of the commonest name elements in Persianate and South Asian naming (as in Gulzar, Gulshan, Gulnar). The source gave غول (which is the unrelated Arabic ghūl 'ghoul') as the Arabic form; the correct form is گل. The record's 'Arabic' label is also wrong — the word is Persian."),
 "gulala": (None, "گلالہ", "گلاله", None, "ګلاله", "bud_rosebud", "Persian", "Female",
            "Persian گل + آله/لاله — 'rosebud, tulip-flower' (formation not securely documented)", False, "low",
            "Gulala appears in South Asian Persianate naming with the reported sense 'rosebud', plausibly گل 'flower' with a diminutive or with لاله 'tulip'. The source gave the meaningless غلالة and supplied only a Latin string for Urdu; because the formation is not carried in standard dictionaries it is recorded at low confidence."),
 "gulali": (None, "گلالی", "گلالی", None, "ګلالی", "bud_rosebud", "Persian", "Female",
            "Persian گل + diminutive -الی", False, "low",
            "Gulali is a variant of gulala in South Asian naming, reported as 'rosebud'. The source gave the meaningless غلالي; the formation is not documented in standard dictionaries, so it is recorded at low confidence."),
 "gulchin": (None, "گلچین", "گلچین", None, "ګلچین", "flower_gatherer", "Persian", "Female",
             "Persian گلچین (golchin) 'flower-gatherer, flower-picker'", False, "medium",
             "Gulchin is the Persian گلچین (golchin) — گل 'flower' + چین 'gatherer/selector' — 'flower-gatherer, one who selects flowers', used as a feminine name. The source supplied only Latin strings and glossed it 'rose garden'; the 'flower-gatherer' sense is the correct reading."),
 "gulfam": (None, "گلفام", "گلفام", None, "ګلفام", "jasmine_flower", "Persian", "Female",
            "Persian گلفام (golfām) — گل + فام 'colour/hue'; popularly 'jasmine flower'", False, "low",
            "Gulfam appears in South Asian Persianate naming, popularly explained as 'jasmine flower' or as گل 'flower' + فام 'colour, hue'. The source gave the meaningless غلفام and labelled the record 'Arabic'. Because the exact formation is not carried in standard dictionaries it is recorded at low confidence."),
 "gulistan": (None, "گلستان", "گلستان", None, "ګلستان", "flower_garden", "Persian", "Unisex",
              "Persian گلستان (gulistān) 'rose garden, land of flowers'", False, "high",
              "Gulistan is the Persian گلستان (gulistān) 'rose garden, land of flowers' (گل 'flower' + the place-suffix ـستان). It is the title of Saʿdi's famous work and a common Persianate toponym and given name. The source labelled it 'Arabic'; the word is Persian. Same name as golestan."),
 "gulnar": (None, "گلنار", "گلنار", None, "ګلنار", "pomegranate_flower", "Persian", "Female",
            "Persian گلنار (golnār) 'pomegranate flower'", False, "high",
            "Gulnar is the Persian گلنار (gulnār) 'pomegranate flower' (گل + نار 'pomegranate'), a well-established feminine name in Persian, Urdu, Azerbaijani and Turkish usage. The source gave the meaningless جلنر and mislabelled it 'Arabic'; both were corrected. Same name as golnar."),
 "gulnaz": (None, "گلناز", "گلناز", None, "ګلناز", "delicate_rose", "Persian", "Female",
            "Persian گلناز (golnāz) 'delicate/charming rose'", False, "medium",
            "Gulnaz is the Persian گلناز (gulnāz) — گل 'flower' + ناز 'coquetry, allure' — 'a rose of charm'. The source gave غولناز and glossed it 'rose'; the compound sense is more precise. Same name as golnaz."),
 "gulnaza": (None, "گلنازہ", "گلنازه", None, "ګلنازه", "delicate_rose", "Persian", "Female",
             "Persian گلناز (golnāz) + -a", False, "medium",
             "Gulnaza is an extended form of گلناز (gulnāz) 'delicate/charming rose'. The source gloss 'jewel of the night' is unsupported and has been replaced."),
 "gulnisa": (None, "گلنیسا", "گلنیسا", None, "ګلنیسا", None, "Persian", "Female",
             None, False, "low",
             "Gulnisa appears in Persianate and South Asian naming (گل 'flower' with a second element that is not securely documented). The source gave the meaningless غُلنيسا and glossed it 'rose garden'. No verified lexical meaning was established, so no gloss is asserted beyond the floral element, at low confidence."),
 "gulraiz": (None, "گلریز", "گلریز", None, "ګلریز", "scattering_flowers", "Persian", "Male",
             "Persian گلریز (golrīz) 'scattering flowers', from گل + ریختن 'to scatter'", False, "medium",
             "Gulraiz is the Persian گلریز (golrīz) 'scattering flowers, strewing blossoms' (گل 'flower' + ریختن 'to scatter'). The source gave غولرايز and glossed it 'servant of the exalted'; both were corrected."),
 "gulrez": (None, "گلریز", "گلریز", None, "ګلریز", "scattering_flowers", "Persian", "Female",
            "Persian گلریز (golrīz) 'scattering flowers'", False, "medium",
            "Gulrez is the Persian گلریز (golrīz) 'scattering flowers', used as a given name. The source supplied only a Latin string and glossed it 'rose garden'; the 'scattering flowers' sense is the correct reading. Same name as gulraiz."),
 "gulsan": (None, "گلشن", "گلشن", None, "ګلشن", "flower_garden", "Persian", "Female",
            "Persian گلشن (golshan) 'rose garden'", False, "medium",
            "Gulsan corresponds to گلشن (golshan) 'rose garden, flower garden'. The source gave the meaningless غلسان and labelled the record 'Urdu, Persian' while an earlier sibling was labelled Arabic; the word is Persian. Same name as gulshan and golshan."),
 "gulsana": (None, "گلسانہ", "گلسانه", None, "ګلسانه", "flower_garden", "Persian", "Female",
             "Persian گلشن/گلستان + -a", False, "low",
             "Gulsana is an extended form in the گل 'flower' family, reported with the sense 'rose garden'. The source gave جلسانة (a different word) as the Arabic form and glossed it 'rose garden'. Because the precise formation is not documented, it is recorded at low confidence."),
 "gulshad": (None, "گلشاد", "گلشاد", None, "ګلشاد", "joyful_rose", "Persian", "Unisex",
             "Persian گلشاد (golshād) 'joyful rose', from گل + شاد 'glad'", False, "medium",
             "Gulshad is the Persian گلشاد (golshād) — گل 'flower' + شاد 'glad, happy' — 'joyful rose, rose of gladness', used as a given name. The source gave غولشاد and labelled the record 'Arabic'; the word is Persian."),
 "gulshan": (None, "گلشن", "گلشن", None, "ګلشن", "flower_garden", "Persian", "Unisex",
             "Persian گلشن (golshan) 'rose garden'", False, "high",
             "Gulshan is the Persian گلشن (gulshan) 'rose garden, flower garden', a long-established given name and toponym across Persianate South Asia (compare the Gulshan neighbourhoods of Karachi and Dhaka). The source gave غولشان and mislabelled it 'Arabic'."),
 "gulzar": (None, "گلزار", "گلزار", None, "ګلزار", "flower_garden", "Persian", "Unisex",
            "Persian گلزار (golzār) 'rose garden, flower bed'", False, "high",
            "Gulzar is the Persian گلزار (gulzār) 'rose garden, flower bed' (گل 'flower' + زار 'place of'), a common given name and surname in South Asia (for example the poet and film-maker Gulzar). The source gave غولزار and mislabelled it 'Arabic'."),
 "guzel": (None, "گوزل", "گوزل", "गुज़ेल", "ګوزل", "beautiful", "Turkish", "Female",
           "Turkish güzel 'beautiful, lovely'", False, "high",
           "Guzel is the Turkish feminine name güzel 'beautiful, lovely'. The source gave جوزل (not a word) and labelled it 'Arabic'; the name is Turkish. The gloss 'beautiful, precious' is substantially correct."),
}
