# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 42 (aabid..mudasser).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": aahoo -> Latin "Aahoo"; aaisha -> Latin "Aa'ishah";
   monera -> Latin "Monera"; mouti -> Latin "Mouti"; mubaraka -> Latin "Mubaraka";
   muhab -> Latin "Muhab"; mulazim -> Latin "Mulazim"; munaza -> Latin "Munaza";
   munna -> Latin "Munna"; musan -> Latin "Musan"; musawir -> Latin "Musawir";
   musli -> Latin "Musli"; mutalib -> Latin "Mutalib"; mutia -> Latin "Mutia";
   naaman -> Latin "Na'aman"; nabiha -> Latin "Nabiha"; nacira -> "Ali" (a different name);
   nadeen -> "N/A"; nadi -> Latin "Nadi"; nadyne -> Latin "Nadyne"; naef -> Latin "Naef";
   naib -> "Nabi" (a different word); nail -> Latin "Nail"; najee -> Latin "Najee";
   namaa -> Latin "Namaa"; namik -> Latin "namik"; namiq -> Latin "Namiq".
 * EMPTY STUBS (8-key records, no data): mudassir, muhammad, munira, musa, mustafa,
   nabeel, nada, nadia, nadim, nafisa, nahla, najat, najwa.
 * MISLABELLED ORIGIN: aahoo (Persian), aafreen (Persian), aaftab (Persian),
   aaina (Persian/Urdu), mozhgan (Persian), morvarid (Persian), moomin (the source
   listed Finnish/Swedish), mosa (the source gave a Devanagari form under Arabic).
 * DEGARBLED GLOSSES: aabir "The Last", aabish "Father of the spring",
   aadhil "Close friend", aaf "Given by Allah", aafak "Unknown, hidden",
   aafiya "Healer, curer", aahil "Prince, Great Ruler", aaida "Guide, helper",
   aaima "Mother of Aisha", aaira "Respectful, Noble, Admirable",
   aaiz "Helpful, Assisting", aakifah "Grower, Cultivator", aala "Mountain",
   aalif "Letter A", aamaal "Support, Aid", aameen "Trustworthy, Reliable",
   aamer "Sleeper, Dreamer", moncef "Gifted", moneeb "Giver, Seeker",
   monera "Precious gem", monis "Advisor, Guide", morvarid "Pearl" (ok),
   mosleh "Guide", motasim "Agrees, Assents, Consents", motaz "Determined, Decisive",
   moufida "Gifted one", mouhib "Lover, Affectionate, Kind", moujib "Gift, Blessing",
   mounia "Gift from Allah", mounir "Guardian, Protector", mounira "Protector, Guardian",
   mourad "Servant of the Lord", moutasim "Agrees, accepts", moutaz "harvested, withheld",
   mouzam "One who records, remembers", mozhgan "Gift from God", muaath "Seeker of Truth",
   muad "Desired, Loved", muadh "Companion of the Prophet", muadz "Awakener",
   mualla "Desirable, Priceless", muammar "Commander of an army",
   muammer "Desired, Wished for", muath "Deadly, Fierce",
   muawiya "One who causes harmony", muayid "Support, Aid", muaz "Helper, Assistant",
   mubariz "Brave and courageous", mubasher "Announcer, Herald",
   mubina "Pure, Chaste", mubshir "Bringer of Good News", mudar "Abode or Dweller",
   mudasir "Inviter, Companion, Helper", mudassar "Covered with blessings",
   mudasser "Helper, supporter".
 * GENDER ERRORS: aaf, aafreen, aali, aaliah, aalif, aamaal, aamal, moomin, muaz,
   mualla, mouri were labelled unisex or female where documented usage is male or
   the form is a common noun with no personal-name gender.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated41 import GLOSSES as _G41

GLOSSES = dict(_G41)
GLOSSES.update({
    "passerby": {"en": "Passer-by, one who crosses", "ur": "گزرنے والا، راہگیر", "fa": "گذرنده، رهگذر", "hi": "गुज़रने वाला, राहगीर", "ps": "تېرېدونکی", "ar": "الْعَابِر، الْمَارّ"},
    "adam": {"en": "Adam; the first man", "ur": "آدم، پہلا انسان", "fa": "آدم، نخستین انسان", "hi": "आदम, प्रथम मनुष्य", "ps": "آدم، لومړنی انسان", "ar": "آدَم، أَبُو الْبَشَر"},
    "just": {"en": "Just, fair, upright", "ur": "عادل، منصف، راست", "fa": "عادل، دادگر، درست", "hi": "आदिल, न्यायी, सच्चा", "ps": "عادل، انصاف کوونکی", "ar": "الْعَادِل، الْمُنْصِف، الْمُسْتَقِيم"},
    "just_f": {"en": "Just, fair (feminine)", "ur": "عادلہ، منصف (مؤنث)", "fa": "عادله، دادگر (مؤنث)", "hi": "आदिला, न्यायी (स्त्री)", "ps": "عادله، انصاف کوونکې", "ar": "الْعَادِلَة، الْمُنْصِفَة"},
    "horizons": {"en": "Horizons, far regions", "ur": "آفاق، کنارے، دور دراز علاقے", "fa": "آفاق، کرانه‌ها", "hi": "आफ़ाक़, क्षितिज", "ps": "آفاق، افقونه", "ar": "الْآفَاق، النَّوَاحِي"},
    "health_wellbeing": {"en": "Health, well-being, soundness", "ur": "عافیت، صحت، تندرستی", "fa": "عافیت، سلامت، تندرستی", "hi": "आफ़ियत, स्वास्थ्य, कुशलता", "ps": "عافیت، روغتیا", "ar": "الْعَافِيَة، الصِّحَّة، السَّلَامَة"},
    "praise_bravo": {"en": "Praise, bravo, well done", "ur": "آفرین، شاباش، تعریف", "fa": "آفرین، تحسین", "hi": "आफ़रीन, शाबाश, प्रशंसा", "ps": "آفرین، ښه کار", "ar": "أَحْسَنْت، الثَّنَاء"},
    "family_people": {"en": "Family, people, kin", "ur": "اہل، خاندان، لوگ", "fa": "اهل، خانواده، مردم", "hi": "अहल, परिवार, लोग", "ps": "اهل، کورنۍ", "ar": "الْأَهْل، الْعَائِلَة، النَّاس"},
    "swimmer_f": {"en": "Swimmer, one who swims (feminine)", "ur": "عائمہ، تیرنے والی", "fa": "عائمه، شناگر (مؤنث)", "hi": "आइमा, तैरने वाली", "ps": "لامبو وهونکې", "ar": "الْعَائِمَة، السَّابِحَة"},
    "mirror": {"en": "Mirror, looking-glass", "ur": "آئینہ، شیشہ", "fa": "آینه، شیشه", "hi": "आईना, दर्पण", "ps": "هينداره، آينه", "ar": "الْمِرْآة"},
    "seeking_refuge": {"en": "One who seeks refuge, sheltering", "ur": "پناہ لینے والا، عائذ", "fa": "پناه‌جو، عائذ", "hi": "आइज़, पनाह लेने वाला", "ps": "پناه غوښتونکی", "ar": "الْعَائِذ، الْمُسْتَجِير"},
    "devoted_worshipper_f": {"en": "Devoted worshipper (feminine)", "ur": "عاکفہ، عبادت میں مشغول (مؤنث)", "fa": "عاکفه، عبادت‌گزار (مؤنث)", "hi": "आकिफ़ा, तपस्विनी", "ps": "عاکفه، عبادت کوونکې", "ar": "الْعَاكِفَة، الْمُتَعَبِّدَة"},
    "exalted_f": {"en": "Exalted, high (feminine)", "ur": "عالیہ، بلند (مؤنث)", "fa": "عالیه، بلند (مؤنث)", "hi": "आलिया, उच्च (स्त्री)", "ps": "عالیه، لوړه", "ar": "الْعَالِيَة، الرَّفِيعَة"},
    "alif_letter": {"en": "Alif; the first letter of the Arabic alphabet", "ur": "الف، عربی حروف کا پہلا حرف", "fa": "الف، نخستین حرف الفبا", "hi": "अलिफ़, अरबी वर्णमाला का पहला अक्षर", "ps": "الف، د عربي الفبا لومړی توری", "ar": "الْأَلِف، أَوَّل حُرُوف الْهِجَاء"},
    "scholar": {"en": "Scholar, learned person, knower", "ur": "عالم، دانشمند", "fa": "عالم، دانشمند", "hi": "आलिम, विद्वान", "ps": "عالم، پوهاند", "ar": "الْعَالِم، الْفَقِيه"},
    "scholar_f": {"en": "Scholar, learned woman (feminine)", "ur": "عالمہ، دانشمند خاتون", "fa": "عالمه، دانشمند (مؤنث)", "hi": "आलिमा, विदुषी", "ps": "عالمه، پوهانده", "ar": "الْعَالِمَة، الْفَقِيهَة"},
    "amen": {"en": "Amen; so be it", "ur": "آمین، ایسا ہی ہو", "fa": "آمین، چنین باد", "hi": "आमीन, ऐसा ही हो", "ps": "آمین، داسې وې", "ar": "آمِين، اللَّهُمَّ اسْتَجِبْ"},
    "moses": {"en": "Moses; a prophet", "ur": "موسیٰ، ایک پیغمبر", "fa": "موسی، پیامبر", "hi": "मूसा, एक पैग़ंबर", "ps": "موسی، یو پیغمبر", "ar": "مُوسَى، نَبِيّ"},
    "holding_fast": {"en": "One who holds fast, clings firmly", "ur": "معتصم، مضبوطی سے تھامنے والا", "fa": "معتصم، چنگ‌زننده", "hi": "मोतसिम, मज़बूती से थामने वाला", "ps": "معتصم، کلک نیول", "ar": "الْمُعْتَصِم، الْمُمْسِك"},
    "glorified": {"en": "Glorified, honoured, proud", "ur": "معتز، معزز، فخر کرنے والا", "fa": "معتز، سربلند", "hi": "मोताज़, गौरवान्वित", "ps": "معتز، ویاړلی", "ar": "الْمُعْتَزّ، الْمُكَرَّم"},
    "lover": {"en": "Lover, one who loves", "ur": "محب، عاشق، محبت کرنے والا", "fa": "محب، دوستدار", "hi": "मुहिब, प्रेमी", "ps": "محب، مینه وال", "ar": "الْمُحِبّ، الْعَاشِق"},
    "cause": {"en": "Cause, occasion, reason", "ur": "موجب، سبب، باعث", "fa": "موجب، سبب", "hi": "मूजिब, कारण", "ps": "موجب، سبب", "ar": "الْمُوجِب، السَّبَب"},
    "eyelashes": {"en": "Eyelashes", "ur": "مژگاں، پلکیں", "fa": "مژگان، مژه‌ها", "hi": "मोज़गान, पलकें", "ps": "مژگان، باڼه", "ar": "الْأَهْدَاب"},
    "long_lived": {"en": "Long-lived, one granted a long life", "ur": "معمّر، طویل عمر والا", "fa": "معمر، درازعمر", "hi": "मुअम्मर, दीर्घायु", "ps": "معمر، اوږد عمر", "ar": "الْمُعَمَّر، طَوِيل الْعُمْر"},
    "muawiya": {"en": "Muawiya; a male given name", "ur": "معاویہ (مردانہ نام)", "fa": "معاویه (نام مردانه)", "hi": "मुआविया (पुरुष नाम)", "ps": "معاویه (نر نوم)", "ar": "مُعَاوِيَة (اسْم عَلَم مُذَكَّر)"},
    "supporter": {"en": "Supporter, backer, helper", "ur": "معاون، مددگار، حامی", "fa": "معاون، پشتیبان", "hi": "मुआविन, सहायक", "ps": "معاون، ملاتړی", "ar": "الْمُعَاوِن، النَّاصِر"},
    "manifest_f": {"en": "Clear, manifest (feminine)", "ur": "مبینہ، واضح (مؤنث)", "fa": "مبینه، آشکار (مؤنث)", "hi": "मुबीना, स्पष्ट (स्त्री)", "ps": "مبینه، ښکاره", "ar": "الْمُبِينَة، الْوَاضِحَة"},
    "mudar": {"en": "Mudar; a male given name", "ur": "مضر (مردانہ نام)", "fa": "مضر (نام مردانه)", "hi": "मुदर (पुरुष नाम)", "ps": "مضر (نر نوم)", "ar": "مُضَر (اسْم عَلَم مُذَكَّر)"},
})

CUR = {
 "aabid": ("عابد", "عابد", "عابد", "आबिद", "عابد", "servant_god", "Arabic", "Male",
           "Arabic root ع ب د (ʿ-b-d); عَابِد (ʿĀbid)", False, "high",
           "Aabid is Arabic عَابِد (ʿĀbid) 'worshipper, one who serves God', the active participle of the root ع ب د (ʿ-b-d). The source gloss 'Servant of God' is broadly consistent; the precise lexical sense is 'worshipper'."),
 "aabida": ("عابدة", "عابدہ", "عابده", "आबिदा", "عابده", "worshipper", "Arabic", "Female",
            "Arabic root ع ب د (ʿ-b-d); عَابِدَة (ʿĀbida)", False, "high",
            "Aabida is Arabic عَابِدَة (ʿĀbida) 'worshipper, one who serves God' (feminine), from the root ع ب د (ʿ-b-d). The source gloss 'Worshipper of God' is consistent."),
 "aabir": ("عابر", "عابر", "عابر", "आबिर", "عابر", "passerby", "Arabic", "Male",
           "Arabic root ع ب ر (ʿ-b-r); عَابِر (ʿĀbir)", False, "high",
           "Aabir is Arabic عَابِر (ʿĀbir) 'passer-by, one who crosses', from the root ع ب ر (ʿ-b-r). The source gloss 'The Last' is unsupported and has been replaced with the lexical sense."),
 "aabish": ("عابش", "عابش", "عابش", "आबिश", "عابش", "uncertain_form", "Unknown", "Unknown",
            "No reliable root analysis established.", False, "low",
            "Aabish is recorded at low confidence. The source gave عابش and glossed the name 'Father of the spring'; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "aadam": ("آدم", "آدم", "آدم", "आदम", "آدم", "adam", "Arabic", "Male",
           "Arabic آدَم (Ādam)", False, "high",
           "Aadam is Arabic آدَم (Ādam), the name of Adam, the first man, a figure named in the Qur'an. The source gloss 'First man created by Allah' is consistent."),
 "aadhil": ("عادل", "عادل", "عادل", "आदिल", "عادل", "just", "Arabic", "Male",
            "Arabic root ع د ل (ʿ-d-l); عَادِل (ʿĀdil)", False, "high",
            "Aadhil is Arabic عَادِل (ʿĀdil) 'just, fair, upright', from the root ع د ل (ʿ-d-l). The source gloss 'Close friend' is unsupported and has been replaced with the lexical sense. Same name as aadil."),
 "aadil": ("عادل", "عادل", "عادل", "आदिल", "عادل", "just", "Arabic", "Male",
           "Arabic root ع د ل (ʿ-d-l); عَادِل (ʿĀdil)", False, "high",
           "Aadil is Arabic عَادِل (ʿĀdil) 'just, fair, upright', from the root ع د ل (ʿ-d-l). The source gloss 'Just, Fair, Upright' is consistent. Same name as aadhil."),
 "aadila": ("عادلة", "عادلہ", "عادله", "आदिला", "عادله", "just_f", "Arabic", "Female",
            "Arabic root ع د ل (ʿ-d-l); عَادِلَة (ʿĀdila)", False, "high",
            "Aadila is Arabic عَادِلَة (ʿĀdila) 'just, fair' (feminine), from the root ع د ل (ʿ-d-l). The source gloss 'Just and Fair' is consistent."),
 "aadilah": ("عادلة", "عادلہ", "عادله", "आदिला", "عادله", "just_f", "Arabic", "Female",
             "Arabic root ع د ل (ʿ-d-l); عَادِلَة (ʿĀdila)", False, "high",
             "Aadilah is Arabic عَادِلَة (ʿĀdila) 'just, fair' (feminine), from the root ع د ل (ʿ-d-l). The source gloss 'Just and Fair' is consistent. Same name as aadila."),
 "aaf": ("عائشة", "عائشہ", "عایشه", "आइशा", "عایشه", "aisha", "Arabic", "Female",
         "Arabic عَائِشَة (ʿĀʾisha)", False, "high",
         "Aaf is recorded here as a short spelling of Arabic عَائِشَة (ʿĀʾisha), the name of the Prophet's wife. CRITICAL SOURCE ERROR: the source gloss 'Given by Allah' is unsupported and the gender was given as unisex; documented usage is female. Same name as aaisha and aisha."),
 "aafak": ("آفاق", "آفاق", "آفاق", "आफ़ाक़", "آفاق", "horizons", "Arabic", "Male",
           "Arabic root أ ف ق (ʾ-f-q); آفَاق (Āfāq)", False, "high",
           "Aafak is Arabic آفَاق (Āfāq) 'horizons, far regions', the plural of أُفُق (ufuq), from the root أ ف ق (ʾ-f-q). The source gloss 'Unknown, hidden' is unsupported and has been replaced with the lexical sense. Same name as aafaq."),
 "aafaq": ("آفاق", "آفاق", "آفاق", "आफ़ाक़", "آفاق", "horizons", "Arabic", "Male",
           "Arabic root أ ف ق (ʾ-f-q); آفَاق (Āfāq)", False, "high",
           "Aafaq is Arabic آفَاق (Āfāq) 'horizons, far regions', the plural of أُفُق (ufuq), from the root أ ف ق (ʾ-f-q). The source gloss 'Heavens' is broadly consistent. Same name as aafak."),
 "aafiya": ("عافية", "عافیہ", "عافیه", "आफ़िया", "عافیه", "health_wellbeing", "Arabic", "Female",
            "Arabic root ع ف و (ʿ-f-w); عَافِيَة (ʿĀfiya)", False, "high",
            "Aafiya is Arabic عَافِيَة (ʿĀfiya) 'health, well-being, soundness', from the root ع ف و (ʿ-f-w). The source gloss 'Healer, curer' is unsupported and has been replaced with the lexical sense."),
 "aafreen": ("آفرين", "آفرین", "آفرین", "आफ़रीन", "آفرین", "praise_bravo", "Persian", "Female",
             "Persian آفرین (āfarīn)", False, "high",
             "Aafreen is Persian آفرین (āfarīn) 'praise, bravo, well done'. CRITICAL SOURCE ERROR: the source gave عفرى (a different form) and labelled the origin Arabic; the name is Persian. The source gloss 'Brave, Encouragement, Praise' is partly unsupported; the lexical sense is 'praise'."),
 "aaftab": ("آفتاب", "آفتاب", "آفتاب", "आफ़ताब", "آفتاب", "sun", "Persian", "Male",
            "Persian آفتاب (āftāb)", False, "high",
            "Aaftab is Persian آفتاب (āftāb) 'sun, sunlight'. CRITICAL SOURCE ERROR: the source gave عاطب (a different form) and labelled the origin Arabic; the name is Persian. The source gloss 'Radiant, Shining' is broadly consistent with the lexical sense."),
 "aahil": ("أهل", "اہل", "اهل", "अहल", "اهل", "family_people", "Arabic", "Male",
           "Arabic root أ ه ل (ʾ-h-l); أَهْل (Ahl)", False, "high",
           "Aahil is Arabic أَهْل (Ahl) 'family, people, kin'. CRITICAL SOURCE ERROR: the source gave أاهل (a non-standard form); the correct form is أَهْل. The source gloss 'Prince, Great Ruler' is unsupported and has been replaced with the lexical sense."),
 "aahoo": ("آهو", "آہو", "آهو", "आहू", "آهو", "gazelle", "Persian", "Female",
           "Persian آهو (āhū)", False, "high",
           "Aahoo is Persian آهو (āhū) 'gazelle'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Aahoo' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Jasmine' is unsupported and has been replaced with the lexical sense."),
 "aaida": ("عائدة", "عائدہ", "عائده", "आइदा", "عائده", "returning_f", "Arabic", "Female",
           "Arabic root ع و د (ʿ-w-d); عَائِدَة (ʿĀʾida)", False, "high",
           "Aaida is Arabic عَائِدَة (ʿĀʾida) 'returning, one who returns' (feminine), from the root ع و د (ʿ-w-d). The source gloss 'Guide, helper' is unsupported and has been replaced with the lexical sense."),
 "aaima": ("عائمة", "عائمہ", "عائمه", "आइमा", "عائمه", "swimmer_f", "Arabic", "Female",
           "Arabic root ع و م (ʿ-w-m); عَائِمَة (ʿĀʾima)", False, "high",
           "Aaima is Arabic عَائِمَة (ʿĀʾima) 'swimmer, one who swims' (feminine), from the root ع و م (ʿ-w-m). The source gloss 'Mother of Aisha' is unsupported and has been replaced with the lexical sense."),
 "aaina": ("آئینہ", "آئینہ", "آینه", "आईना", "آینه", "mirror", "Persian", "Female",
           "Persian آینه (āyina); Urdu آئینہ (āʾīna)", False, "high",
           "Aaina is Persian آینه (āyina) / Urdu آئینہ (āʾīna) 'mirror'. CRITICAL SOURCE ERROR: the source gave عاينة (a different form) and labelled the origin Arabic; the word is Persian/Urdu. The source gloss 'Mirror' is consistent."),
 "aaira": ("عائرة", "عائرہ", "عائره", "आइरा", "عائره", "uncertain_form", "Unknown", "Female",
           "No reliable root analysis established.", False, "low",
           "Aaira is recorded at low confidence. The source gave عائرة and glossed the name 'Respectful, Noble, Admirable'; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "aaisha": ("عائشة", "عائشہ", "عایشه", "आइशा", "عایشه", "aisha", "Arabic", "Female",
            "Arabic عَائِشَة (ʿĀʾisha)", False, "high",
            "Aaisha is Arabic عَائِشَة (ʿĀʾisha), the name of the Prophet's wife. CRITICAL SOURCE ERROR: the source gave the Latin string \"Aa'ishah\" instead of a script form. The source gloss 'Female helper, wife of Prophet Muhammad' is partly unsupported; the documented identification is the name itself. Same name as aaf and aisha."),
 "aaiz": ("عائذ", "عائذ", "عائذ", "आइज़", "عائذ", "seeking_refuge", "Arabic", "Male",
          "Arabic root ع و ذ (ʿ-w-dh); عَائِذ (ʿĀʾidh)", False, "high",
          "Aaiz is Arabic عَائِذ (ʿĀʾidh) 'one who seeks refuge, sheltering', from the root ع و ذ (ʿ-w-dh). The source gloss 'Helpful, Assisting' is unsupported and has been replaced with the lexical sense."),
 "aakif": ("عاكف", "عاکف", "عاکف", "आकिफ़", "عاکف", "devoted_worshipper", "Arabic", "Male",
           "Arabic root ع ك ف (ʿ-k-f); عَاكِف (ʿĀkif)", False, "high",
           "Aakif is Arabic عَاكِف (ʿĀkif) 'devoted, one who stays in worship', from the root ع ك ف (ʿ-k-f). The source gloss 'Persevering, Continuous' is broadly consistent."),
 "aakifah": ("عاكفة", "عاکفہ", "عاکفه", "आकिफ़ा", "عاکفه", "devoted_worshipper_f", "Arabic", "Female",
             "Arabic root ع ك ف (ʿ-k-f); عَاكِفَة (ʿĀkifa)", False, "high",
             "Aakifah is Arabic عَاكِفَة (ʿĀkifa) 'devoted, one who stays in worship' (feminine), from the root ع ك ف (ʿ-k-f). The source gloss 'Grower, Cultivator' is unsupported and has been replaced with the lexical sense."),
 "aakil": ("عاقل", "عاقل", "عاقل", "आक़िल", "عاقل", "wise_intelligent", "Arabic", "Male",
           "Arabic root ع ق ل (ʿ-q-l); عَاقِل (ʿĀqil)", False, "high",
           "Aakil is Arabic عَاقِل (ʿĀqil) 'wise, intelligent, discerning', from the root ع ق ل (ʿ-q-l). The source gloss 'Wise, Intelligent, Discerning' is consistent."),
 "aala": ("عالية", "عالیہ", "عالیه", "आला", "عالیه", "exalted_f", "Arabic", "Female",
          "Arabic root ع ل و (ʿ-l-w); عَالِيَة (ʿĀliya)", False, "high",
          "Aala is recorded here as Arabic عَالِيَة (ʿĀliya) 'exalted, high' (feminine), from the root ع ل و (ʿ-l-w). CRITICAL SOURCE ERROR: the source gave عالى and glossed the name 'Mountain'; the source gloss is unsupported and has been replaced with the lexical sense. Same name as aalia and aaliya."),
 "aalaa": ("علاء", "علاء", "علاء", "अला", "علاء", "exalted", "Arabic", "Female",
           "Arabic root ع ل و (ʿ-l-w); عَلَاء (ʿAlāʾ)", False, "high",
           "Aalaa is Arabic عَلَاء (ʿAlāʾ) 'exaltedness, highness', from the root ع ل و (ʿ-l-w). The source gloss 'Heavenly, Sublime' is broadly consistent."),
 "aalam": ("عالم", "عالم", "عالم", "आलम", "عالم", "world", "Arabic", "Male",
           "Arabic root ع ل م (ʿ-l-m); عَالَم (ʿĀlam)", False, "high",
           "Aalam is Arabic عَالَم (ʿĀlam) 'world', from the root ع ل م (ʿ-l-m). The source gloss 'World' is consistent. Recorded as a common noun also used as a given name."),
 "aalee": ("علي", "علی", "علی", "अली", "علي", "exalted", "Arabic", "Male",
           "Arabic root ع ل و (ʿ-l-w); عَلِيّ (ʿAlī)", False, "high",
           "Aalee is Arabic عَلِيّ (ʿAlī) 'exalted, high', from the root ع ل و (ʿ-l-w). The source gloss 'Exalted, Sublime' is consistent. Same name as ali."),
 "aali": ("عالي", "عالی", "عالی", "आली", "عالي", "exalted", "Arabic", "Male",
          "Arabic root ع ل و (ʿ-l-w); عَالِي (ʿĀlī)", False, "high",
          "Aali is Arabic عَالِي (ʿĀlī) 'exalted, high', from the root ع ل و (ʿ-l-w). The source gloss 'Exalted, Noble' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male."),
 "aalia": ("عالية", "عالیہ", "عالیه", "आलिया", "عالیه", "exalted_f", "Arabic", "Female",
           "Arabic root ع ل و (ʿ-l-w); عَالِيَة (ʿĀliya)", False, "high",
           "Aalia is Arabic عَالِيَة (ʿĀliya) 'exalted, high' (feminine), from the root ع ل و (ʿ-l-w). The source gloss 'Exalted, Noble, High-ranking' is consistent. Same name as aala and aaliya."),
 "aaliah": ("عالية", "عالیہ", "عالیه", "आलिया", "عالیه", "exalted_f", "Arabic", "Female",
            "Arabic root ع ل و (ʿ-l-w); عَالِيَة (ʿĀliya)", False, "high",
            "Aaliah is Arabic عَالِيَة (ʿĀliya) 'exalted, high' (feminine), from the root ع ل و (ʿ-l-w). The source gloss 'High, Exalted' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is female. Same name as aalia."),
 "aalif": ("أَلِف", "الف", "الف", "अलिफ़", "الف", "alif_letter", "Arabic", "Unknown",
           "Arabic أَلِف (Alif)", False, "high",
           "Aalif is Arabic أَلِف (Alif), the name of the first letter of the Arabic alphabet. The source gloss 'Letter A' is broadly consistent. Recorded as a letter name rather than a personal name; no personal-name gender usage is asserted."),
 "aalim": ("عالم", "عالم", "عالم", "आलिम", "عالم", "scholar", "Arabic", "Male",
           "Arabic root ع ل م (ʿ-l-m); عَالِم (ʿĀlim)", False, "high",
           "Aalim is Arabic عَالِم (ʿĀlim) 'scholar, learned person, knower', from the root ع ل م (ʿ-l-m). The source gloss 'Scholar, Learned Man' is consistent."),
 "aalima": ("عالمة", "عالمہ", "عالمه", "आलिमा", "عالمه", "scholar_f", "Arabic", "Female",
            "Arabic root ع ل م (ʿ-l-m); عَالِمَة (ʿĀlima)", False, "high",
            "Aalima is Arabic عَالِمَة (ʿĀlima) 'scholar, learned woman' (feminine), from the root ع ل م (ʿ-l-m). The source gloss 'Knowledgeable, Scholar' is consistent."),
 "aaliya": ("عالية", "عالیہ", "عالیه", "आलिया", "عالیه", "exalted_f", "Arabic", "Female",
            "Arabic root ع ل و (ʿ-l-w); عَالِيَة (ʿĀliya)", False, "high",
            "Aaliya is Arabic عَالِيَة (ʿĀliya) 'exalted, lofty' (feminine), from the root ع ل و (ʿ-l-w). The source gloss 'Exalted, Lofty, High-ranking' is consistent. Same name as aalia."),
 "aaliyah": ("علية", "علیہ", "علیه", "आलिया", "علیه", "exalted_f", "Arabic", "Female",
             "Arabic root ع ل و (ʿ-l-w); عَلِيَّة (ʿAliyya)", False, "high",
             "Aaliyah is Arabic عَلِيَّة (ʿAliyya) 'exalted, high, noble' (feminine), from the root ع ل و (ʿ-l-w). The source gloss 'High, Exalted, Noble' is consistent."),
 "aamaal": ("آمال", "آمال", "آمال", "आमाल", "آمال", "hope", "Arabic", "Female",
            "Arabic root أ م ل (ʾ-m-l); آمَال (Āmāl)", False, "high",
            "Aamaal is Arabic آمَال (Āmāl) 'hopes, aspirations', the plural of أَمَل (amal), from the root أ م ل (ʾ-m-l). The source gloss 'Support, Aid' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender male; documented usage is female. Same name as aamal."),
 "aamal": ("آمال", "آمال", "آمال", "आमाल", "آمال", "hope", "Arabic", "Female",
           "Arabic root أ م ل (ʾ-m-l); آمَال (Āmāl)", False, "high",
           "Aamal is Arabic آمَال (Āmāl) 'hopes, aspirations', the plural of أَمَل (amal), from the root أ م ل (ʾ-m-l). The source gloss 'Hope' is consistent. Same name as aamaal."),
 "aameen": ("آمين", "آمین", "آمین", "आमीन", "آمین", "amen", "Arabic", "Male",
            "Arabic آمِين (Āmīn)", False, "high",
            "Aameen is Arabic آمِين (Āmīn) 'amen; so be it', a liturgical response. The source gloss 'Trustworthy, Reliable' is unsupported and has been replaced with the lexical sense. Recorded as a liturgical word also used as a given name."),
 "aamer": ("عامر", "عامر", "عامر", "आमिर", "عامر", "flourishing", "Arabic", "Male",
           "Arabic root ع م ر (ʿ-m-r); عَامِر (ʿĀmir)", False, "high",
           "Aamer is Arabic عَامِر (ʿĀmir) 'inhabited, flourishing, populous', from the root ع م ر (ʿ-m-r). The source gloss 'Sleeper, Dreamer' is unsupported and has been replaced with the lexical sense. Same name as aamir."),
 "aamil": ("عامل", "عامل", "عامل", "आमिल", "عامل", "labourer_doer", "Arabic", "Male",
           "Arabic root ع م ل (ʿ-m-l); عَامِل (ʿĀmil)", False, "high",
           "Aamil is Arabic عَامِل (ʿĀmil) 'worker, doer, agent', from the root ع م ل (ʿ-m-l). The source gloss 'Worker, laborer, craftsman' is consistent."),
 "moncef": ("منصف", "منصف", "منصف", "मुन्सिफ़", "منصف", "fairness", "Arabic", "Male",
            "Arabic root ن ص ف (n-ṣ-f); مُنْصِف (Munṣif)", False, "high",
            "Moncef is Arabic مُنْصِف (Munṣif) 'fair, just, equitable', from the root ن ص ف (n-ṣ-f). The source gloss 'Gifted' is unsupported and has been replaced with the lexical sense."),
 "moneeb": ("منيب", "منیب", "منیب", "मुनीब", "منیب", "returning_god", "Arabic", "Male",
            "Arabic root ن و ب (n-w-b); مُنِيب (Munīb)", False, "high",
            "Moneeb is Arabic مُنِيب (Munīb) 'one who turns to God, repentant', from the root ن و ب (n-w-b). The source gloss 'Giver, Seeker' is unsupported and has been replaced with the lexical sense."),
 "monera": ("منيرة", "منیرہ", "منیره", "मुनीरा", "منیره", "luminous", "Arabic", "Female",
            "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
            "Monera is Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source gave the Latin string 'Monera' instead of a script form. The source gloss 'Precious gem' is unsupported and has been replaced with the lexical sense. Same name as munira."),
 "monis": ("مؤنس", "مونس", "مونس", "मोनिस", "مونس", "companion_friendly", "Arabic", "Male",
           "Arabic root أ ن س (ʾ-n-s); مُؤْنِس (Muʾnis)", False, "high",
           "Monis is Arabic مُؤْنِس (Muʾnis) 'companion, friendly, sociable', from the root أ ن س (ʾ-n-s). The source gloss 'Advisor, Guide' is unsupported and has been replaced with the lexical sense."),
 "moomin": ("مؤمن", "مومن", "مومن", "मोमिन", "مومن", "believer", "Arabic", "Male",
            "Arabic root أ م ن (ʾ-m-n); مُؤْمِن (Muʾmin)", False, "high",
            "Moomin is Arabic مُؤْمِن (Muʾmin) 'believer, one who has faith', from the root أ م ن (ʾ-m-n). CRITICAL SOURCE ERROR: the source listed the languages as Finnish/Swedish and glossed the name 'Finnish mythological figure'; the form is Arabic. The source gloss is unsupported. Same name as moumin and momin."),
 "moomina": ("مؤمنة", "مومنہ", "مومنه", "मोमिना", "مومنه", "believer_f", "Arabic", "Female",
             "Arabic root أ م ن (ʾ-m-n); مُؤْمِنَة (Muʾmina)", False, "high",
             "Moomina is Arabic مُؤْمِنَة (Muʾmina) 'believing' (feminine), from the root أ م ن (ʾ-m-n). The source gloss 'Believer, Follower' is consistent. Same name as moumina and momina."),
 "moosa": ("موسى", "موسیٰ", "موسی", "मूसा", "موسی", "moses", "Arabic", "Male",
           "Arabic مُوسَى (Mūsā)", False, "high",
           "Moosa is Arabic مُوسَى (Mūsā), the name of Moses, a prophet named in the Qur'an. The source gloss 'Moses' is consistent. Same name as musa."),
 "morvarid": ("مروارید", "مروارید", "مروارید", "मोरवारिद", "مروارید", "pearl", "Persian", "Female",
              "Persian مروارید (morvārīd)", False, "high",
              "Morvarid is Persian مروارید (morvārīd) 'pearl'. CRITICAL SOURCE ERROR: the source gave مرواريد and labelled the origin Arabic; the word is Persian. The source gloss 'Pearl' is consistent."),
 "mosa": ("موسى", "موسیٰ", "موسی", "मूसा", "موسی", "moses", "Arabic", "Male",
          "Arabic مُوسَى (Mūsā)", False, "high",
          "Mosa is Arabic مُوسَى (Mūsā), the name of Moses, a prophet named in the Qur'an. CRITICAL SOURCE ERROR: the source gave a Devanagari form (मूसى) in the Arabic field and glossed the name 'Saved from the water'; the source gloss is unsupported. Same name as moosa and musa."),
 "mosleh": ("مصلح", "مصلح", "مصلح", "मुस्लिह", "مصلح", "reform", "Arabic", "Male",
            "Arabic root ص ل ح (ṣ-l-ḥ); مُصْلِح (Muṣliḥ)", False, "high",
            "Mosleh is Arabic مُصْلِح (Muṣliḥ) 'reformer, one who sets things right', from the root ص ل ح (ṣ-l-ḥ). CRITICAL SOURCE ERROR: the source gave موسله (a non-standard form); the correct form is مُصْلِح. The source gloss 'Guide' is unsupported and has been replaced with the lexical sense."),
 "mostafa": ("مصطفى", "مصطفیٰ", "مصطفی", "मुस्तफ़ा", "مصطفی", "chosen", "Arabic", "Male",
             "Arabic root ص ف و (ṣ-f-w); مُصْطَفَى (Muṣṭafā)", False, "high",
             "Mostafa is Arabic مُصْطَفَى (Muṣṭafā) 'chosen, selected', from the root ص ف و (ṣ-f-w); it is an epithet of the Prophet. The source gloss 'Well-chosen, well-pleased' is broadly consistent. Same name as mustafa."),
 "motasim": ("معتصم", "معتصم", "معتصم", "मोतसिम", "معتصم", "holding_fast", "Arabic", "Male",
             "Arabic root ع ص م (ʿ-ṣ-m); مُعْتَصِم (Muʿtaṣim)", False, "high",
             "Motasim is Arabic مُعْتَصِم (Muʿtaṣim) 'one who holds fast, clings firmly', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave متسم (a non-standard form); the correct form is مُعْتَصِم. The source gloss 'Agrees, Assents, Consents' is unsupported and has been replaced with the lexical sense. Same name as moutasim."),
 "motaz": ("معتز", "معتز", "معتز", "मोताज़", "معتز", "glorified", "Arabic", "Male",
           "Arabic root ع ز ز (ʿ-z-z); مُعْتَزّ (Muʿtazz)", False, "high",
           "Motaz is Arabic مُعْتَزّ (Muʿtazz) 'glorified, honoured, proud', from the root ع ز ز (ʿ-z-z). CRITICAL SOURCE ERROR: the source gave متز (a non-standard form); the correct form is مُعْتَزّ. The source gloss 'Determined, Decisive' is unsupported and has been replaced with the lexical sense. Same name as moutaz."),
 "moufida": ("مفيدة", "مفیدہ", "مفیده", "मुफ़ीदा", "مفیده", "useful", "Arabic", "Female",
             "Arabic root ف ي د (f-y-d); مُفِيدَة (Mufīda)", False, "high",
             "Moufida is Arabic مُفِيدَة (Mufīda) 'useful, beneficial' (feminine), from the root ف ي د (f-y-d). The source gloss 'Gifted one' is unsupported and has been replaced with the lexical sense."),
 "mouhib": ("محب", "محب", "محب", "मुहिब", "محب", "lover", "Arabic", "Male",
            "Arabic root ح ب ب (ḥ-b-b); مُحِبّ (Muḥibb)", False, "high",
            "Mouhib is Arabic مُحِبّ (Muḥibb) 'lover, one who loves', from the root ح ب ب (ḥ-b-b). CRITICAL SOURCE ERROR: the source gave موهب (a non-standard form); the correct form is مُحِبّ. The source gloss 'Lover, Affectionate, Kind' is partly consistent."),
 "moujib": ("موجب", "موجب", "موجب", "मूजिब", "موجب", "cause", "Arabic", "Male",
            "Arabic root و ج ب (w-j-b); مُوجِب (Mūjib)", False, "high",
            "Moujib is Arabic مُوجِب (Mūjib) 'cause, occasion, reason', from the root و ج ب (w-j-b). The source gloss 'Gift, Blessing' is unsupported and has been replaced with the lexical sense."),
 "moumin": ("مؤمن", "مومن", "مومن", "मोमिन", "مومن", "believer", "Arabic", "Male",
            "Arabic root أ م ن (ʾ-m-n); مُؤْمِن (Muʾmin)", False, "high",
            "Moumin is Arabic مُؤْمِن (Muʾmin) 'believer, one who has faith', from the root أ م ن (ʾ-m-n). The source gloss 'Believer' is consistent. Same name as moomin and momin."),
 "moumina": ("مؤمنة", "مومنہ", "مومنه", "मोमिना", "مومنه", "believer_f", "Arabic", "Female",
             "Arabic root أ م ن (ʾ-m-n); مُؤْمِنَة (Muʾmina)", False, "high",
             "Moumina is Arabic مُؤْمِنَة (Muʾmina) 'believing' (feminine), from the root أ م ن (ʾ-m-n). The source gloss 'Faithful believer' is consistent. Same name as moomina and momina."),
 "mounia": ("منية", "منیہ", "منیه", "मुनिया", "منیه", "wish_desire", "Arabic", "Female",
            "Arabic root م ن ي (m-n-y); مُنْيَة (Munyah)", False, "high",
            "Mounia is Arabic مُنْيَة (Munyah) 'wish, desire', from the root م ن ي (m-n-y). The source gloss 'Gift from Allah' is unsupported and has been replaced with the lexical sense. Same name as munya."),
 "mounir": ("منير", "منیر", "منیر", "मुनीर", "منیر", "luminous", "Arabic", "Male",
            "Arabic root ن و ر (n-w-r); مُنِير (Munīr)", False, "high",
            "Mounir is Arabic مُنِير (Munīr) 'luminous, illuminating', from the root ن و ر (n-w-r). The source gloss 'Guardian, Protector' is unsupported and has been replaced with the lexical sense."),
 "mounira": ("منيرة", "منیرہ", "منیره", "मुनीरा", "منیره", "luminous", "Arabic", "Female",
             "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
             "Mounira is Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). The source gloss 'Protector, Guardian' is unsupported and has been replaced with the lexical sense. Same name as monera and munira."),
 "mourad": ("مراد", "مراد", "مراد", "मुराद", "مراد", "desired", "Arabic", "Male",
            "Arabic root ر و د (r-w-d); مُرَاد (Murād)", False, "high",
            "Mourad is Arabic مُرَاد (Murād) 'wished-for, desired', from the root ر و د (r-w-d). The source gloss 'Servant of the Lord' is unsupported and has been replaced with the lexical sense. Same name as murad."),
 "mouri": ("موري", "موری", "موری", "मौरी", "موري", "uncertain_form", "Unknown", "Unknown",
           "No reliable root analysis established.", False, "low",
           "Mouri is recorded at low confidence. The source gave موري and glossed the name 'Unknown'; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "moutasim": ("معتصم", "معتصم", "معتصم", "मोतसिम", "معتصم", "holding_fast", "Arabic", "Male",
              "Arabic root ع ص م (ʿ-ṣ-m); مُعْتَصِم (Muʿtaṣim)", False, "high",
              "Moutasim is Arabic مُعْتَصِم (Muʿtaṣim) 'one who holds fast, clings firmly', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave موتسيم (a non-standard form); the correct form is مُعْتَصِم. The source gloss 'Agrees, accepts' is unsupported and has been replaced with the lexical sense. Same name as motasim."),
 "moutaz": ("معتز", "معتز", "معتز", "मोताज़", "معتز", "glorified", "Arabic", "Male",
            "Arabic root ع ز ز (ʿ-z-z); مُعْتَزّ (Muʿtazz)", False, "high",
            "Moutaz is Arabic مُعْتَزّ (Muʿtazz) 'glorified, honoured, proud', from the root ع ز ز (ʿ-z-z). CRITICAL SOURCE ERROR: the source gave موطز (a non-standard form); the correct form is مُعْتَزّ. The source gloss 'harvested, withheld, delayed' is unsupported and has been replaced with the lexical sense. Same name as motaz."),
 "mouti": ("معطي", "معطی", "معطی", "मोती", "معطي", "giver_gifts", "Arabic", "Male",
           "Arabic root ع ط و (ʿ-ṭ-w); مُعْطِي (Muʿṭī)", False, "high",
           "Mouti is Arabic مُعْطِي (Muʿṭī) 'giver, one who gives', from the root ع ط و (ʿ-ṭ-w). CRITICAL SOURCE ERROR: the source gave the Latin string 'Mouti' instead of a script form and glossed the name 'Gift from God'; the source gloss is unsupported and has been replaced with the lexical sense."),
 "mouzam": ("معظم", "معظم", "معظم", "मुअज़्ज़म", "معظم", "exalted", "Arabic", "Male",
            "Arabic root ع ظ م (ʿ-ẓ-m); مُعَظَّم (Muʿaẓẓam)", False, "high",
            "Mouzam is Arabic مُعَظَّم (Muʿaẓẓam) 'greatly esteemed, exalted', from the root ع ظ م (ʿ-ẓ-m). CRITICAL SOURCE ERROR: the source gave موزم (a non-standard form); the correct form is مُعَظَّم. The source gloss 'One who records, remembers' is unsupported and has been replaced with the lexical sense. Same name as muazzam."),
 "mozhgan": ("مژگان", "مژگاں", "مژگان", "मोज़गान", "مژگان", "eyelashes", "Persian", "Female",
             "Persian مژگان (mozhgān)", False, "high",
             "Mozhgan is Persian مژگان (mozhgān) 'eyelashes'. CRITICAL SOURCE ERROR: the source gave مظهنة (a different form) and labelled the origin Arabic; the word is Persian. The source gloss 'Gift from God' is unsupported and has been replaced with the lexical sense."),
 "muaath": ("معاذ", "معاذ", "معاذ", "मुआज़", "معاذ", "protected", "Arabic", "Male",
            "Arabic root ع و ذ (ʿ-w-dh); مُعَاذ (Muʿādh)", False, "high",
            "Muaath is Arabic مُعَاذ (Muʿādh) 'one who is protected, refuge', from the root ع و ذ (ʿ-w-dh). The source gloss 'Seeker of Truth' is unsupported and has been replaced with the lexical sense. Same name as muadh and muaz."),
 "muaaz": ("مُعَاذ", "معاذ", "معاذ", "मुआज़", "معاذ", "protected", "Arabic", "Male",
           "Arabic root ع و ذ (ʿ-w-dh); مُعَاذ (Muʿādh)", False, "high",
           "Muaaz is Arabic مُعَاذ (Muʿādh) 'one who is protected, refuge', from the root ع و ذ (ʿ-w-dh). The source gloss 'Striving, Seeking, or Struggling' is unsupported and has been replaced with the lexical sense. Same name as muaath."),
 "muad": ("معد", "معد", "معد", "मुआद", "معد", "maad", "Arabic", "Male",
          "Arabic مَعَدّ (Maʿadd)", False, "high",
          "Muad is Arabic مَعَدّ (Maʿadd), an ancient Arab tribal name. The source gloss 'Desired, Loved' is unsupported and has been replaced with the documented identification."),
 "muadh": ("مُعاذ", "معاذ", "معاذ", "मुआज़", "معاذ", "protected", "Arabic", "Male",
           "Arabic root ع و ذ (ʿ-w-dh); مُعَاذ (Muʿādh)", False, "high",
           "Muadh is Arabic مُعَاذ (Muʿādh) 'one who is protected, refuge', from the root ع و ذ (ʿ-w-dh); it is the name of a companion of the Prophet. The source gloss 'Companion of the Prophet' is a historical association rather than a lexical sense. Same name as muaath."),
 "muadz": ("معاذ", "معاذ", "معاذ", "मुआज़", "معاذ", "protected", "Arabic", "Male",
           "Arabic root ع و ذ (ʿ-w-dh); مُعَاذ (Muʿādh)", False, "high",
           "Muadz is Arabic مُعَاذ (Muʿādh) 'one who is protected, refuge', from the root ع و ذ (ʿ-w-dh). The source gloss 'Awakener' is unsupported and has been replaced with the lexical sense. Same name as muaath."),
 "mualla": ("مُعَلَّى", "معلیٰ", "معلی", "मुअल्ला", "معلی", "exalted_f", "Arabic", "Female",
            "Arabic root ع ل و (ʿ-l-w); مُعَلَّى (Muʿallā)", False, "high",
            "Mualla is Arabic مُعَلَّى (Muʿallā) 'exalted, raised high', from the root ع ل و (ʿ-l-w). The source gloss 'Desirable, Priceless' is unsupported and has been replaced with the lexical sense."),
 "muammar": ("معمّر", "معمّر", "معمر", "मुअम्मर", "معمر", "long_lived", "Arabic", "Male",
             "Arabic root ع م ر (ʿ-m-r); مُعَمَّر (Muʿammar)", False, "high",
             "Muammar is Arabic مُعَمَّر (Muʿammar) 'long-lived, one granted a long life', from the root ع م ر (ʿ-m-r). The source gloss 'Commander of an army' is unsupported and has been replaced with the lexical sense. Same name as muammer."),
 "muammer": ("مُعَمِّر", "معمّر", "معمر", "मुअम्मर", "معمر", "long_lived", "Arabic", "Male",
             "Arabic root ع م ر (ʿ-m-r); مُعَمِّر (Muʿammir)", False, "high",
             "Muammer is Arabic مُعَمِّر (Muʿammir) 'one who grants long life, long-lived', from the root ع م ر (ʿ-m-r). The source gloss 'Desired, Wished for' is unsupported and has been replaced with the lexical sense. Same name as muammar."),
 "muath": ("معاذ", "معاذ", "معاذ", "मुआज़", "معاذ", "protected", "Arabic", "Male",
           "Arabic root ع و ذ (ʿ-w-dh); مُعَاذ (Muʿādh)", False, "high",
           "Muath is Arabic مُعَاذ (Muʿādh) 'one who is protected, refuge', from the root ع و ذ (ʿ-w-dh). The source gloss 'Deadly, Fierce' is unsupported and has been replaced with the lexical sense. Same name as muaath."),
 "muawiya": ("معاوية", "معاویہ", "معاویه", "मुआविया", "معاویه", "muawiya", "Arabic", "Male",
             "Arabic root ع و ي (ʿ-w-y); مُعَاوِيَة (Muʿāwiya)", False, "high",
             "Muawiya is Arabic مُعَاوِيَة (Muʿāwiya), a male given name borne by the first Umayyad caliph. The source gloss 'One who causes harmony' is unsupported and has been replaced with the documented identification."),
 "muayid": ("معايد", "معاید", "معاید", "मुआयिद", "معاید", "supporter", "Arabic", "Male",
            "Arabic root ع و ن (ʿ-w-n); مُعَايِد (Muʿāyid)", False, "medium",
            "Muayid is recorded as Arabic مُعَايِد (Muʿāyid) 'supporter, helper', from the root ع و ن (ʿ-w-n). The source gloss 'Support, Aid' is broadly consistent. The identification is recorded at medium confidence. Same name as muayyad."),
 "muayyad": ("مُعَيَّد", "مؤید", "مؤید", "मुअय्यद", "مؤید", "supported", "Arabic", "Male",
             "Arabic root أ ي د (ʾ-y-d); مُؤَيَّد (Muʾayyad)", False, "high",
             "Muayyad is Arabic مُؤَيَّد (Muʾayyad) 'supported, aided, strengthened', from the root أ ي د (ʾ-y-d). The source gloss 'Helped or supported' is consistent."),
 "muaz": ("معز", "معز", "معز", "मुआज़", "معز", "honourer", "Arabic", "Male",
          "Arabic root ع ز ز (ʿ-z-z); مُعِزّ (Muʿizz)", False, "high",
          "Muaz is recorded here as Arabic مُعِزّ (Muʿizz) 'one who honours, giver of honour', from the root ع ز ز (ʿ-z-z). The source gloss 'Helper, Assistant, Companion' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male."),
 "muazzam": ("مُعَظَّم", "معظم", "معظم", "मुअज़्ज़म", "معظم", "exalted", "Arabic", "Male",
             "Arabic root ع ظ م (ʿ-ẓ-m); مُعَظَّم (Muʿaẓẓam)", False, "high",
             "Muazzam is Arabic مُعَظَّم (Muʿaẓẓam) 'greatly esteemed, exalted', from the root ع ظ م (ʿ-ẓ-m). The source gloss 'Greatly esteemed' is consistent. Same name as mouzam."),
 "mubarak": ("مبارك", "مبارک", "مبارک", "मुबारक", "مبارک", "blessed_mubarak", "Arabic", "Male",
             "Arabic root ب ر ك (b-r-k); مُبَارَك (Mubārak)", False, "high",
             "Mubarak is Arabic مُبَارَك (Mubārak) 'blessed, fortunate', from the root ب ر ك (b-r-k). The source gloss 'Blessed or fortunate' is consistent."),
 "mubaraka": ("مباركة", "مبارکہ", "مبارکه", "मुबारका", "مبارکه", "blessed_f", "Arabic", "Female",
              "Arabic root ب ر ك (b-r-k); مُبَارَكَة (Mubāraka)", False, "high",
              "Mubaraka is Arabic مُبَارَكَة (Mubāraka) 'blessed' (feminine), from the root ب ر ك (b-r-k). CRITICAL SOURCE ERROR: the source gave the Latin string 'Mubaraka' instead of a script form. The source gloss 'Blessed' is consistent."),
 "mubarik": ("مبارك", "مبارک", "مبارک", "मुबारिक", "مبارک", "blessed_mubarak", "Arabic", "Male",
             "Arabic root ب ر ك (b-r-k); مُبَارَك (Mubārak)", False, "high",
             "Mubarik is Arabic مُبَارَك (Mubārak) 'blessed, fortunate', from the root ب ر ك (b-r-k). The source gloss 'Blessed, fortunate' is consistent. Same name as mubarak."),
 "mubariz": ("مبارز", "مبارز", "مبارز", "मुबारिज़", "مبارز", "warrior", "Arabic", "Male",
             "Arabic root ب ر ز (b-r-z); مُبَارِز (Mubāriz)", False, "high",
             "Mubariz is Arabic مُبَارِز (Mubāriz) 'warrior, fighter, one who duels', from the root ب ر ز (b-r-z). The source gloss 'Brave and courageous' is broadly consistent."),
 "mubasher": ("مبشر", "مبشر", "مبشر", "मुबश्शिर", "مبشر", "bringer_of_good_news", "Arabic", "Male",
              "Arabic root ب ش ر (b-sh-r); مُبَشِّر (Mubashshir)", False, "high",
              "Mubasher is Arabic مُبَشِّر (Mubashshir) 'bringer of good news, announcer', from the root ب ش ر (b-sh-r). The source gloss 'Announcer, Herald' is broadly consistent. Same name as mubasshir."),
 "mubasshir": ("مُبَشِّر", "مبشر", "مبشر", "मुबश्शिर", "مبشر", "bringer_of_good_news", "Arabic", "Male",
               "Arabic root ب ش ر (b-sh-r); مُبَشِّر (Mubashshir)", False, "high",
               "Mubasshir is Arabic مُبَشِّر (Mubashshir) 'bringer of good news', from the root ب ش ر (b-sh-r). The source gloss 'Bearer of good news' is consistent. Same name as mubasher."),
 "mubassir": ("مبشر", "مبصر", "مبصر", "मुबस्सिर", "مبصر", "bringer_of_good_news", "Arabic", "Male",
              "Arabic root ب ش ر (b-sh-r); مُبَشِّر (Mubashshir)", False, "high",
              "Mubassir is recorded here as Arabic مُبَشِّر (Mubashshir) 'bringer of good news', from the root ب ش ر (b-sh-r). The source gloss 'Announcer, Preacher, Speaker' is partly unsupported and has been replaced with the lexical sense. Same name as mubasher."),
 "mubeen": ("مبين", "مبین", "مبین", "मुबीन", "مبین", "manifest", "Arabic", "Male",
            "Arabic root ب ي ن (b-y-n); مُبِين (Mubīn)", False, "high",
            "Mubeen is Arabic مُبِين (Mubīn) 'clear, evident, manifest', from the root ب ي ن (b-y-n). The source gloss 'Clear, Evident, Manifest' is consistent. Same name as mubin."),
 "mubin": ("مبين", "مبین", "مبین", "मुबीन", "مبین", "manifest", "Arabic", "Male",
           "Arabic root ب ي ن (b-y-n); مُبِين (Mubīn)", False, "high",
           "Mubin is Arabic مُبِين (Mubīn) 'clear, distinct, manifest', from the root ب ي ن (b-y-n). The source gloss 'Clear, distinct, explained' is consistent. Same name as mubeen."),
 "mubina": ("مبينة", "مبینہ", "مبینه", "मुबीना", "مبینه", "manifest_f", "Arabic", "Female",
            "Arabic root ب ي ن (b-y-n); مُبِينَة (Mubīna)", False, "high",
            "Mubina is Arabic مُبِينَة (Mubīna) 'clear, manifest' (feminine), from the root ب ي ن (b-y-n). The source gloss 'Pure, Chaste' is unsupported and has been replaced with the lexical sense."),
 "mubshir": ("مبشر", "مبشر", "مبشر", "मुबश्शिर", "مبشر", "bringer_of_good_news", "Arabic", "Male",
             "Arabic root ب ش ر (b-sh-r); مُبَشِّر (Mubashshir)", False, "high",
             "Mubshir is Arabic مُبَشِّر (Mubashshir) 'bringer of good news', from the root ب ش ر (b-sh-r). CRITICAL SOURCE ERROR: the source gave البشر (a different form); the correct form is مُبَشِّر. The source gloss 'Bringer of Good News' is consistent. Same name as mubasher."),
 "mudar": ("مضر", "مضر", "مضر", "मुदर", "مضر", "mudar", "Arabic", "Male",
           "Arabic مُضَر (Muḍar)", False, "high",
           "Mudar is Arabic مُضَر (Muḍar), an ancient Arab tribal name. CRITICAL SOURCE ERROR: the source gave مُدَرْ (a non-standard form); the correct form is مُضَر. The source gloss 'Abode or Dweller' is unsupported and has been replaced with the documented identification."),
 "mudasir": ("مُدَسِّر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
             "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
             "Mudasir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. The source gloss 'Inviter, Companion, Helper' is unsupported and has been replaced with the lexical sense. Same name as mudassir and mudasser."),
 "mudassar": ("مدثر", "مدثر", "مدثر", "मुदस्सर", "مدثر", "modassir", "Arabic", "Male",
              "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
              "Mudassar is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. The source gloss 'Covered with blessings' is unsupported and has been replaced with the lexical sense. Same name as mudasir."),
 "mudasser": ("مدثر", "مدثر", "مدثر", "मुदस्सर", "مدثر", "modassir", "Arabic", "Male",
              "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
              "Mudasser is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. CRITICAL SOURCE ERROR: the source gave مضاصر (a non-standard form); the correct form is مُدَّثِّر. The source gloss 'Helper, supporter' is unsupported and has been replaced with the lexical sense. Same name as mudasir."),
}
