# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 43 (mudassir..murshida).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": muddassir -> مُدَassis (Latin mixed into the
   Arabic field); muhab -> Latin "Muhab"; mulazim -> Latin "Mulazim";
   munaza -> Latin "Munaza"; munna -> Latin "Munna"; munzir -> مُنْजिِر (Devanagari
   mixed into the Arabic field); muqtada -> مقtADA (Latin mixed in);
   muqtadir -> المقتدر (definite article, not the name form);
   muneerah -> مُنۈرَة (non-standard); muhit -> منحيت (a different form);
   muhid -> مهد (a different form); muhanned -> محمد (a different name);
   mujibur -> موجب (a different form); muraad -> موراد (non-standard);
   munerat -> منيرة (ok); munerah -> منرة (non-standard).
 * EMPTY STUBS (8-key records, no data): mudassir, muhammad, munira, musa.
 * MISLABELLED ORIGIN: mulan (Mandarin/Cantonese, not Arabic), muir (English/Scottish),
   muharrem (Turkish form of Muharram), multan (a place name).
 * DEGARBLED GLOSSES: mudathir "Warner, One who gives a warning",
   muddasir "Gardener, One who guards", muddassir "Observer, Watcher",
   muddathir "One who covers or protects", mudrik "Divine Blessing",
   mueen "Trustworthy, faithful", mufaddal "Helper, Assistant",
   mufid "Giver, Benefactor", mufida "Generous one", muhaimin "Protector",
   muhammadi "Lover of Muhammad", muhanad "Steadfast in Faith",
   muhanna "Warrior, Fighter", muhanned "Given by Allah", muharrem "Sacred, Invincible",
   muhid "Seeker of knowledge", muhit "Protector, Defender", muid "Helpful, Aid",
   muir "Little river", muiz "Reviver, Reformer", muizz "One who Glorifies",
   mujammil "Well-covered, clothed", mujeeb "Responding to prayer",
   mujib "Granted, Achieved, Powerful", mujibur "Grantor, Provider",
   mukhtiar "Granter of Freedom", mulan "Magnolia flower", mulham "Soldier, Warrior",
   mulla "My lord", multan "City of Light", muna "Consoler, Supporter",
   munaf "Forbearing, Patient", munar "Moon", munawar "Beloved, Adored",
   munawara "Lit up, radiant", munawarah "The one who is adorned",
   munaza "One who is helped", munazir "Debater", munazza "Beautiful and lovely",
   mundi "Intelligent, Wise", muneeb "Consoler, Helper", muneer "Guide, teacher, leader",
   muneera "The Light-Giver", muneerah "Guide, Light", munerah "A light-giving one",
   munia "Jewel, Precious Stone", munib "Obliging", munif "Forgiving, Generous",
   munim "Protector, Guardian", munirat "redeemer, savior, protector",
   munisa "Pious, Godly", munna "Protector", muntaha "Goal, Aim, Summit, Peak",
   muntasir "Desirer of Victory", muntazir "One who withholds, patiently endures",
   munya "Comfort, Consolation", munzir "The Victor", muqadas "Honored, Pious, Sacred",
   muqtada "Ordered, Directed, Guided", muqtadir "Determined, Firm, Decisive",
   muraad "Desire, Wish", murah "Bitter, Astringent", murazi "Helper, Assistant",
   murid "One who desires", mursal "Asker", mursalin "The one who brings the message",
   murshad "Guide, Teacher", murshida "Guide, Helper".
 * GENDER ERRORS: muhammadi, muhib, mujahid, mumin, mumtaz, munazir, munis, munya,
   mursal were labelled unisex where documented usage is male or the form is a
   common noun with no personal-name gender.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated42 import GLOSSES as _G42

GLOSSES = dict(_G42)
GLOSSES.update({
    "warner": {"en": "Warner, one who warns", "ur": "ڈرانے والا، خبردار کرنے والا", "fa": "هشداردهنده، بیم‌دهنده", "hi": "चेतावनी देने वाला, डराने वाला", "ps": "خبردار کوونکی", "ar": "الْمُنْذِر، الْمُحَذِّر"},
    "covered": {"en": "Covered, wrapped, concealed", "ur": "ڈھکا ہوا، لپٹا ہوا", "fa": "پوشیده، پوشانده", "hi": "ढका हुआ, आवृत", "ps": "پټ، پوښل شوی", "ar": "الْمُدَثِّر، الْمُتَغَشِّي"},
    "perceiver": {"en": "Perceiver, one who grasps, attainder", "ur": "ادراک کرنے والا، سمجھنے والا", "fa": "درک‌کننده، دریابنده", "hi": "समझने वाला, ग्रहण करने वाला", "ps": "پوهېدونکی", "ar": "الْمُدْرِك، الْمُدْرِك"},
    "mueen": {"en": "Mueen; helper, assistant", "ur": "معین، مددگار، معاون", "fa": "معین، یاری‌کننده", "hi": "मोईन, सहायक", "ps": "معین، مرستندوی", "ar": "الْمُعِين، النَّاصِر"},
    "favoured": {"en": "Favoured, preferred, distinguished", "ur": "مفضل، برگزیدہ، ممتاز", "fa": "مفضل، برگزیده", "hi": "मुफ़ज़्ज़ल, वरीय", "ps": "مفضل، غوره شوی", "ar": "الْمُفَضَّل، الْمُخْتَار"},
    "beneficial": {"en": "Beneficial, useful, helpful", "ur": "مفید، نفع بخش، کارآمد", "fa": "مفید، سودمند", "hi": "मुफ़ीद, लाभदायक", "ps": "مفید، ګټور", "ar": "الْمُفِيد، النَّافِع"},
    "beneficial_f": {"en": "Beneficial, useful (feminine)", "ur": "مفیدہ، نفع بخش (مؤنث)", "fa": "مفیده، سودمند (مؤنث)", "hi": "मुफ़ीदा, लाभदायक (स्त्री)", "ps": "مفیده، ګټوره", "ar": "الْمُفِيدَة، النَّافِعَة"},
    "mufti": {"en": "Mufti; a jurist who issues rulings", "ur": "مفتی، شرعی فتویٰ دینے والا", "fa": "مفتی، فتوا‌دهنده", "hi": "मुफ़्ती, फ़तवा देने वाला", "ps": "مفتي، فتوا ورکوونکی", "ar": "الْمُفْتِي، الْفَقِيه"},
    "muhammad": {"en": "Muhammad; the praised one", "ur": "محمد، بہت تعریف کیا گیا", "fa": "محمد، بسیار ستوده", "hi": "मुहम्मद, अत्यंत प्रशंसित", "ps": "محمد، ډېر ستایل شوی", "ar": "مُحَمَّد، الْكَثِير الْحَمْد"},
    "muhammadi": {"en": "Muhammadi; of Muhammad", "ur": "محمدی، محمد سے منسوب", "fa": "محمدی، منسوب به محمد", "hi": "मुहम्मदी, मुहम्मद से संबंधित", "ps": "محمدي، د محمد اړوند", "ar": "الْمُحَمَّدِي، مَنْسُوب إِلَى مُحَمَّد"},
    "muhaimin": {"en": "Muhaimin; guardian, protector", "ur": "مہیمن، نگہبان، محافظ", "fa": "مهیمن، نگهبان", "hi": "मुहैमिन, रक्षक", "ps": "مهیمن، ساتونکی", "ar": "الْمُهَيْمِن، الْحَافِظ"},
    "muhanad": {"en": "Muhanad; a male given name", "ur": "محند (مردانہ نام)", "fa": "محند (نام مردانه)", "hi": "मुहनद (पुरुष नाम)", "ps": "محند (نر نوم)", "ar": "مُحَنَّد (اسْم عَلَم مُذَكَّر)"},
    "muhannad": {"en": "Muhannad; a sword, a male given name", "ur": "مہند، تلوار (مردانہ نام)", "fa": "مهند، شمشیر", "hi": "मुहन्नद, तलवार", "ps": "مهند، توره", "ar": "مُهَنَّد، السَّيْف"},
    "muharram": {"en": "Muharram; the first month of the Islamic calendar", "ur": "محرم، اسلامی سال کا پہلا مہینہ", "fa": "محرم، نخستین ماه سال قمری", "hi": "मुहर्रम, इस्लामी वर्ष का पहला महीना", "ps": "محرم، د اسلامي کال لومړی میاشت", "ar": "الْمُحَرَّم، أَوَّل شُهُور السَّنَة الْهِجْرِيَّة"},
    "muhib": {"en": "Loving, affectionate, fond", "ur": "محب، محبت کرنے والا", "fa": "محب، دوستدار", "hi": "मुहिब, प्रेम करने वाला", "ps": "محب، مینه وال", "ar": "الْمُحِبّ، الْوَدُود"},
    "muhit": {"en": "Muhit; encompassing, surrounding", "ur": "محیط، گھیرنے والا، احاطہ کرنے والا", "fa": "محیط، فراگیر", "hi": "मुहीत, व्यापक", "ps": "محیط، هر اړخیز", "ar": "الْمُحِيط، الشَّامِل"},
    "muhsin": {"en": "Muhsin; benefactor, doer of good", "ur": "محسن، نیکی کرنے والا", "fa": "محسن، نیکوکار", "hi": "मुहसिन, उपकारी", "ps": "محسن، ښېګړه کوونکی", "ar": "الْمُحْسِن، فَاعِل الْخَيْر"},
    "muhsina": {"en": "Muhsina; virtuous, doer of good (feminine)", "ur": "محسنہ، نیکی کرنے والی", "fa": "محسنه، نیکوکار (مؤنث)", "hi": "मुहसिना, उपकारिणी", "ps": "محسنه، ښېګړه کوونکې", "ar": "الْمُحْسِنَة، فَاعِلَة الْخَيْر"},
    "muid": {"en": "Muid; one who restores, returns", "ur": "معید، لوٹانے والا، بحال کرنے والا", "fa": "معید، بازگرداننده", "hi": "मुईद, लौटाने वाला", "ps": "معید، بېرته راوستونکی", "ar": "الْمُعِيد، الرَّاجِع"},
    "muin": {"en": "Muin; helper, supporter", "ur": "معین، مددگار، معاون", "fa": "معین، یاری‌کننده", "hi": "मुईन, सहायक", "ps": "معین، مرستندوی", "ar": "الْمُعِين، النَّاصِر"},
    "muir": {"en": "Muir; a Scottish surname and given name", "ur": "موئر (سکاٹش نام)", "fa": "مویر (نام اسکاتلندی)", "hi": "मुइर (स्कॉटिश नाम)", "ps": "مویر (سکاټلنډي نوم)", "ar": "مُويِر (اسْم عَلَم إِسْكُتْلَنْدِيّ)"},
    "muiz": {"en": "Muiz; one who honours, giver of honour", "ur": "معز، عزت دینے والا", "fa": "معز، عزت‌بخش", "hi": "मुइज़्ज़, सम्मान देने वाला", "ps": "معز، عزت ورکوونکی", "ar": "الْمُعِزّ، الْمُكْرِم"},
    "muizz": {"en": "Muizz; one who honours, giver of honour", "ur": "معز، عزت دینے والا", "fa": "معز، عزت‌بخش", "hi": "मुइज़्ज़, सम्मान देने वाला", "ps": "معز، عزت ورکوونکی", "ar": "الْمُعِزّ، الْمُكْرِم"},
    "mujahid": {"en": "Mujahid; one who strives, fighter", "ur": "مجاہد، جدوجہد کرنے والا", "fa": "مجاهد، کوشنده", "hi": "मुजाहिद, संघर्ष करने वाला", "ps": "مجاهد، هڅه کوونکی", "ar": "الْمُجَاهِد، الْمُكَافِح"},
    "mujammil": {"en": "Mujammil; one wrapped in a cloak", "ur": "مجمل، چادر اوڑھنے والا", "fa": "مجمل، جامه‌پوش", "hi": "मुजम्मिल, चादर ओढ़ने वाला", "ps": "مجمل، کملی غوړېدونکی", "ar": "الْمُزَّمِّل، الْمُتَزَمِّل"},
    "mujeeb": {"en": "Mujeeb; one who answers, responsive", "ur": "مجیب، جواب دینے والا، قبول کرنے والا", "fa": "مجیب، پاسخ‌دهنده", "hi": "मुजीब, उत्तर देने वाला", "ps": "مجیب، ځواب ورکوونکی", "ar": "الْمُجِيب، الْمُسْتَجِيب"},
    "mujib": {"en": "Mujib; one who answers, responsive", "ur": "مجیب، جواب دینے والا", "fa": "مجیب، پاسخ‌دهنده", "hi": "मुजीब, उत्तर देने वाला", "ps": "مجیب، ځواب ورکوونکی", "ar": "الْمُجِيب، الْمُسْتَجِيب"},
    "mujibur": {"en": "Mujibur; answerer of prayers", "ur": "مجیب الرحمٰن، دعائیں قبول کرنے والا", "fa": "مجیب، اجابت‌کننده دعا", "hi": "मुजीबुर, दुआ क़बूल करने वाला", "ps": "مجیب، دعا قبلوونکی", "ar": "مُجِيبُ الرَّحْمَن، الْمُجِيب"},
    "mujtaba": {"en": "Mujtaba; chosen, selected", "ur": "مجتبیٰ، چنا ہوا، منتخب", "fa": "مجتبی، برگزیده", "hi": "मुज्तबा, चुना हुआ", "ps": "مجتبی، غوره شوی", "ar": "الْمُجْتَبَى، الْمُخْتَار"},
    "mukarram": {"en": "Mukarram; honoured, respected", "ur": "مکرم، معزز، محترم", "fa": "مکرم، گرامی", "hi": "मुकर्रम, सम्मानित", "ps": "مکرم، درناوی", "ar": "الْمُكَرَّم، الْمُحْتَرَم"},
    "mukhlis": {"en": "Mukhlis; sincere, devoted", "ur": "مخلص، وفادار، مخلص", "fa": "مخلص، بااخلاص", "hi": "मुख़लिस, निष्ठावान", "ps": "مخلص، وفادار", "ar": "الْمُخْلِص، الصَّادِق"},
    "mukhtar": {"en": "Mukhtar; chosen, elected", "ur": "مختار، چنا ہوا، منتخب", "fa": "مختار، برگزیده", "hi": "मुख़्तार, चुना हुआ", "ps": "مختار، غوره شوی", "ar": "الْمُخْتَار، الْمُنْتَخَب"},
    "mulan": {"en": "Mulan; a Chinese given name", "ur": "مولان (چینی نام)", "fa": "مولان (نام چینی)", "hi": "मूलान (चीनी नाम)", "ps": "مولان (چینایي نوم)", "ar": "مُولَان (اسْم عَلَم صِينِيّ)"},
    "mulazim": {"en": "Mulazim; officer, one who clings", "ur": "ملازم، افسر، وابستہ", "fa": "ملازم، افسر", "hi": "मुलाज़िम, अफ़सर", "ps": "ملازم، افسر", "ar": "الْمُلَازِم، الضَّابِط"},
    "mulham": {"en": "Mulham; inspired, one given inspiration", "ur": "ملہم، الہام پانے والا", "fa": "ملهم، الهام‌یافته", "hi": "मुलहम, प्रेरणा पाने वाला", "ps": "ملهم، الهام موندونکی", "ar": "الْمُلْهَم، الْمُوحَى إِلَيْهِ"},
    "mulla": {"en": "Mulla; a title for a learned man", "ur": "ملا، عالم کا لقب", "fa": "ملا، لقب عالم", "hi": "मुल्ला, विद्वान की उपाधि", "ps": "ملا، د عالم لقب", "ar": "الْمُلَّا، الْعَالِم"},
    "multan": {"en": "Multan; a city in Pakistan", "ur": "مultan، پاکستان کا شہر", "fa": "مولتان، شهری در پاکستان", "hi": "मुल्तान, पाकिस्तान का शहर", "ps": "ملتان، د پاکستان ښار", "ar": "مُلْتَان، مَدِينَة فِي بَاكِسْتَان"},
    "mumin": {"en": "Mumin; believer, one who has faith", "ur": "مومن، ایمان والا", "fa": "مؤمن، باایمان", "hi": "मोमिन, ईमानवाला", "ps": "مؤمن، ایمان لرونکی", "ar": "الْمُؤْمِن، صَاحِب الْإِيمَان"},
    "mumtaz": {"en": "Mumtaz; distinguished, excellent", "ur": "ممتاز، نمایاں، اعلیٰ", "fa": "ممتاز، برجسته", "hi": "मुमताज़, विशिष्ट", "ps": "ممتاز، ځانګړی", "ar": "الْمُمْتَاز، الْمُتَمَيِّز"},
    "muna": {"en": "Muna; wishes, desires", "ur": "منیٰ، خواہشات، آرزوئیں", "fa": "منی، آرزوها", "hi": "मुना, इच्छाएँ", "ps": "منی، هیلې", "ar": "الْمُنَى، الْأَمَانِي"},
    "munaf": {"en": "Munaf; a male given name", "ur": "مناف (مردانہ نام)", "fa": "مناف (نام مردانه)", "hi": "मुनाफ़ (पुरुष नाम)", "ps": "مناف (نر نوم)", "ar": "مُنَاف (اسْم عَلَم مُذَكَّر)"},
    "munar": {"en": "Munar; lighthouse, place of light", "ur": "منار، روشنی کا مینار", "fa": "منار، جای نور", "hi": "मुनार, प्रकाश-स्तंभ", "ps": "منار، د رڼا ځای", "ar": "الْمَنَار، مَوْضِع النُّور"},
    "munawar": {"en": "Munawar; illuminated, radiant", "ur": "منور، روشن، نور والا", "fa": "منور، نورانی", "hi": "मुनव्वर, प्रकाशित", "ps": "منور، روښانه", "ar": "الْمُنَوَّر، الْمُضِيء"},
    "munawara": {"en": "Munawara; illuminated, radiant (feminine)", "ur": "منورہ، روشن (مؤنث)", "fa": "منوره، نورانی (مؤنث)", "hi": "मुनव्वरा, प्रकाशित (स्त्री)", "ps": "منوره، روښانه", "ar": "الْمُنَوَّرَة، الْمُضِيئَة"},
    "munazir": {"en": "Munazir; one who debates, disputant", "ur": "مناظر، مباحثہ کرنے والا", "fa": "مناظر، بحث‌کننده", "hi": "मुनाज़िर, वाद-विवाद करने वाला", "ps": "مناظر، بحث کوونکی", "ar": "الْمُنَاظِر، الْمُجَادِل"},
    "munazza": {"en": "Munazza; purified, free from fault", "ur": "منزہ، پاک، بے عیب", "fa": "منزه، پاک", "hi": "मुनज़्ज़ा, पवित्र", "ps": "منزه، پاک", "ar": "الْمُنَزَّهَة، الْبَرِيئَة"},
    "mundi": {"en": "Mundi; a male given name", "ur": "مندی (مردانہ نام)", "fa": "مندی (نام مردانه)", "hi": "मुंदी (पुरुष नाम)", "ps": "مندي (نر نوم)", "ar": "مُنْدِي (اسْم عَلَم مُذَكَّر)"},
    "muneeb": {"en": "Muneeb; one who turns to God, repentant", "ur": "منیب، رجوع کرنے والا، توبہ کرنے والا", "fa": "منیب، بازگشت‌کننده", "hi": "मुनीब, लौटने वाला", "ps": "منیب، بېرته راتلونکی", "ar": "الْمُنِيب، الرَّاجِع إِلَى اللَّه"},
    "muneer": {"en": "Muneer; luminous, illuminating", "ur": "منیر، روشن، نور دینے والا", "fa": "منیر، نورافشان", "hi": "मुनीर, प्रकाशमान", "ps": "منیر، روښانه", "ar": "الْمُنِير، الْمُضِيء"},
    "muneera": {"en": "Muneera; luminous, illuminating (feminine)", "ur": "منیرہ، روشن (مؤنث)", "fa": "منیره، نورافشان (مؤنث)", "hi": "मुनीरा, प्रकाशमान (स्त्री)", "ps": "منیره، روښانه", "ar": "الْمُنِيرَة، الْمُضِيئَة"},
    "munia": {"en": "Munia; wish, desire", "ur": "منیا، خواہش، آرزو", "fa": "منیا، آرزو", "hi": "मुनिया, इच्छा", "ps": "منیا، هيله", "ar": "مُنْيَة، الْأُمْنِيَة"},
    "munib": {"en": "Munib; one who turns to God, repentant", "ur": "منیب، رجوع کرنے والا", "fa": "منیب، بازگشت‌کننده", "hi": "मुनीब, लौटने वाला", "ps": "منیب، بېرته راتلونکی", "ar": "الْمُنِيب، الرَّاجِع"},
    "munif": {"en": "Munif; elevated, lofty, high", "ur": "منیف، بلند، اونچا", "fa": "منیف، بلند", "hi": "मुनीफ़, ऊँचा", "ps": "منیف، لوړ", "ar": "الْمُنِيف، الْعَالِي"},
    "munim": {"en": "Munim; benefactor, bestower of favours", "ur": "منعم، نعمت دینے والا", "fa": "منعم، نعمت‌بخش", "hi": "मुनिम, उपकारी", "ps": "منعم، نعمت ورکوونکی", "ar": "الْمُنْعِم، صَاحِب النِّعْمَة"},
    "munir": {"en": "Munir; luminous, radiant, illuminating", "ur": "منیر، روشن، نورانی", "fa": "منیر، نورافشان", "hi": "मुनीर, प्रकाशमान", "ps": "منیر، روښانه", "ar": "الْمُنِير، الْمُضِيء"},
    "munirah": {"en": "Munirah; luminous, shining light (feminine)", "ur": "منیرہ، روشن، نور والی", "fa": "منیره، نورافشان", "hi": "मुनीरा, प्रकाशमान", "ps": "منیره، روښانه", "ar": "الْمُنِيرَة، الْمُضِيئَة"},
    "munis": {"en": "Munis; companion, friendly, sociable", "ur": "مونس، ساتھی، مانوس", "fa": "مونس، همدم", "hi": "मूनिस, साथी", "ps": "مونس، ملګری", "ar": "الْمُونِس، الْأَنِيس"},
    "munisa": {"en": "Munisa; companion, friendly (feminine)", "ur": "مونیسہ، ساتھی (مؤنث)", "fa": "مونیسه، همدم (مؤنث)", "hi": "मुनीसा, साथी (स्त्री)", "ps": "مونیسه، ملګرې", "ar": "الْمُونِسَة، الْأَنِيسَة"},
    "munsif": {"en": "Munsif; fair, just, equitable", "ur": "منصف، انصاف کرنے والا", "fa": "منصف، دادگر", "hi": "मुन्सिफ़, न्यायी", "ps": "منصف، انصاف کوونکی", "ar": "الْمُنْصِف، الْعَادِل"},
    "muntaha": {"en": "Muntaha; the utmost limit, endpoint", "ur": "منتہیٰ، آخری حد، انتہا", "fa": "منتهی، نهایت", "hi": "मुंतहा, अंतिम सीमा", "ps": "منتهی، پای", "ar": "الْمُنْتَهَى، الْغَايَة"},
    "muntasir": {"en": "Muntasir; victorious, one who triumphs", "ur": "منتصر، فتح پانے والا", "fa": "منتصر، پیروز", "hi": "मुंतसिर, विजयी", "ps": "منتصر، بریالی", "ar": "الْمُنْتَصِر، الْغَالِب"},
    "muntazir": {"en": "Muntazir; one who waits, expectant", "ur": "منتظر، انتظار کرنے والا", "fa": "منتظر، چشم‌براه", "hi": "मुंतज़िर, प्रतीक्षारत", "ps": "منتظر، انتظار کوونکی", "ar": "الْمُنْتَظِر، الْمُتَرَقِّب"},
    "munya": {"en": "Munya; wish, desire", "ur": "منیہ، خواہش، آرزو", "fa": "منیه، آرزو", "hi": "मुनिया, इच्छा", "ps": "منیه، هيله", "ar": "مُنْيَة، الْأُمْنِيَة"},
    "munzir": {"en": "Munzir; warner, one who warns", "ur": "منذر، ڈرانے والا، خبردار کرنے والا", "fa": "منذر، هشداردهنده", "hi": "मुन्ज़िर, चेतावनी देने वाला", "ps": "منذر، خبردار کوونکی", "ar": "الْمُنْذِر، الْمُحَذِّر"},
    "muqadas": {"en": "Muqadas; sacred, holy, pure", "ur": "مقدس، پاک، متبرک", "fa": "مقدس، پاک", "hi": "मुक़द्दस, पवित्र", "ps": "مقدس، پاک", "ar": "الْمُقَدَّس، الطَّاهِر"},
    "muqtada": {"en": "Muqtada; one who is followed, leader", "ur": "مقتدیٰ، جس کی پیروی کی جائے", "fa": "مقتدی، پیشوا", "hi": "मुक़्तदा, अनुसरण किया जाने वाला", "ps": "مقتدی، پيروونکی", "ar": "الْمُقْتَدَى، الْمَتْبُوع"},
    "muqtadir": {"en": "Muqtadir; powerful, capable, able", "ur": "مقتدر، قادر، طاقتور", "fa": "مقتدر، توانا", "hi": "मुक़्तदिर, सामर्थ्यवान", "ps": "مقتدر، واکمن", "ar": "الْمُقْتَدِر، الْقَادِر"},
    "murad": {"en": "Murad; wished-for, desired", "ur": "مراد، خواہش، مطلوب", "fa": "مراد، آرزو", "hi": "मुराद, इच्छित", "ps": "مراد، هيله", "ar": "الْمُرَاد، الْمَطْلُوب"},
    "murah": {"en": "Murah; a male given name", "ur": "مراح (مردانہ نام)", "fa": "مراح (نام مردانه)", "hi": "मुराह (पुरुष नाम)", "ps": "مراح (نر نوم)", "ar": "مُرَاح (اسْم عَلَم مُذَكَّر)"},
    "murazi": {"en": "Murazi; a male given name", "ur": "مراضی (مردانہ نام)", "fa": "مراضی (نام مردانه)", "hi": "मुराज़ी (पुरुष नाम)", "ps": "مراضي (نر نوم)", "ar": "مُرَاضِي (اسْم عَلَم مُذَكَّر)"},
    "murid": {"en": "Murid; disciple, one who desires", "ur": "مرید، شاگرد، خواہشمند", "fa": "مرید، شاگرد", "hi": "मुरीद, शिष्य", "ps": "مرید، شاګرد", "ar": "الْمُرِيد، التَّابِع"},
    "mursal": {"en": "Mursal; sent, messenger", "ur": "مرسل، بھیجا ہوا، پیغامبر", "fa": "مرسل، فرستاده", "hi": "मुरसल, भेजा हुआ", "ps": "مرسل، لېږل شوی", "ar": "الْمُرْسَل، الْمُبْعَث"},
    "mursaleen": {"en": "Mursaleen; messengers (plural)", "ur": "مرسلین، پیغامبران", "fa": "مرسلین، فرستادگان", "hi": "मुरसलीन, संदेशवाहक", "ps": "مرسلین، پیغمبران", "ar": "الْمُرْسَلِين، الرُّسُل"},
    "mursalin": {"en": "Mursalin; messengers (plural)", "ur": "مرسلین، پیغامبران", "fa": "مرسلین، فرستادگان", "hi": "मुरसलीन, संदेशवाहक", "ps": "مرسلین، پیغمبران", "ar": "الْمُرْسَلِين، الرُّسُل"},
    "murshid": {"en": "Murshid; guide, teacher, master", "ur": "مرشد، رہنما، استاد", "fa": "مرشد، راهنما", "hi": "मुर्शिद, मार्गदर्शक", "ps": "مرشد، لارښود", "ar": "الْمُرْشِد، الْهَادِي"},
    "murshida": {"en": "Murshida; guide, teacher (feminine)", "ur": "مرشدہ، رہنما (مؤنث)", "fa": "مرشده، راهنما (مؤنث)", "hi": "मुर्शिदा, मार्गदर्शिका", "ps": "مرشده، لارښوده", "ar": "الْمُرْشِدَة، الْهَادِيَة"},
})

CUR = {
 "mudassir": ("مدثر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
              "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
              "Mudassir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as mudasir and mudasser."),
 "mudathir": ("مُدَّثِّر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
              "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
              "Mudathir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. The source gloss 'Warner, One who gives a warning' is unsupported and has been replaced with the lexical sense. Same name as mudassir."),
 "muddasir": ("مُدَّثِّر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
              "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
              "Muddasir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. CRITICAL SOURCE ERROR: the source gave مدسّر (a non-standard form); the correct form is مُدَّثِّر. The source gloss 'Gardener, One who guards' is unsupported and has been replaced with the lexical sense. Same name as mudassir."),
 "muddassir": ("مُدَّثِّر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
               "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
               "Muddassir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. CRITICAL SOURCE ERROR: the source gave مُدَassis (Latin characters mixed into the Arabic field); the correct form is مُدَّثِّر. The source gloss 'Observer, Watcher' is unsupported and has been replaced with the lexical sense. Same name as mudassir."),
 "muddathir": ("مُدَّثِّر", "مدثر", "مدثر", "मुदस्सिर", "مدثر", "modassir", "Arabic", "Male",
               "Arabic root د ث ر (d-th-r); مُدَّثِّر (Muddaththir)", False, "high",
               "Muddathir is Arabic مُدَّثِّر (Muddaththir) 'wrapped in a cloak', from the root د ث ر (d-th-r); it is a Qur'anic sura name. The source gloss 'One who covers or protects' is broadly consistent with the lexical sense. Same name as mudassir."),
 "mudrik": ("مُدْرِك", "مدرک", "مدرک", "मुदरिक", "مدرک", "perceiver", "Arabic", "Male",
            "Arabic root د ر ك (d-r-k); مُدْرِك (Mudrik)", False, "high",
            "Mudrik is Arabic مُدْرِك (Mudrik) 'perceiver, one who grasps, attainder', from the root د ر ك (d-r-k). The source gloss 'Divine Blessing' is unsupported and has been replaced with the lexical sense."),
 "mueen": ("معين", "معین", "معین", "मोईन", "معین", "mueen", "Arabic", "Male",
           "Arabic root ع و ن (ʿ-w-n); مُعِين (Muʿīn)", False, "high",
           "Mueen is Arabic مُعِين (Muʿīn) 'helper, assistant', from the root ع و ن (ʿ-w-n). The source gloss 'Trustworthy, faithful' is unsupported and has been replaced with the lexical sense. Same name as muin."),
 "mufaddal": ("مُفَضَّل", "مفضل", "مفضل", "मुफ़ज़्ज़ल", "مفضل", "favoured", "Arabic", "Male",
              "Arabic root ف ض ل (f-ḍ-l); مُفَضَّل (Mufaḍḍal)", False, "high",
              "Mufaddal is Arabic مُفَضَّل (Mufaḍḍal) 'favoured, preferred, distinguished', from the root ف ض ل (f-ḍ-l). The source gloss 'Helper, Assistant' is unsupported and has been replaced with the lexical sense."),
 "mufeed": ("مفيد", "مفید", "مفید", "मुफ़ीद", "مفید", "beneficial", "Arabic", "Male",
            "Arabic root ف ي د (f-y-d); مُفِيد (Mufīd)", False, "high",
            "Mufeed is Arabic مُفِيد (Mufīd) 'beneficial, useful, helpful', from the root ف ي د (f-y-d). The source gloss 'Beneficial, helpful' is consistent. Same name as mufid."),
 "mufeeda": ("مفيدة", "مفیدہ", "مفیده", "मुफ़ीदा", "مفیده", "beneficial_f", "Arabic", "Female",
             "Arabic root ف ي د (f-y-d); مُفِيدَة (Mufīda)", False, "high",
             "Mufeeda is Arabic مُفِيدَة (Mufīda) 'beneficial, useful' (feminine), from the root ف ي د (f-y-d). The source gloss 'Helpful, Beneficial' is consistent. Same name as mufida."),
 "mufid": ("مفيد", "مفید", "مفید", "मुफ़ीद", "مفید", "beneficial", "Arabic", "Male",
           "Arabic root ف ي د (f-y-d); مُفِيد (Mufīd)", False, "high",
           "Mufid is Arabic مُفِيد (Mufīd) 'beneficial, useful', from the root ف ي د (f-y-d). The source gloss 'Giver, Benefactor' is unsupported and has been replaced with the lexical sense. Same name as mufeed."),
 "mufida": ("مفيدة", "مفیدہ", "مفیده", "मुफ़ीदा", "مفیده", "beneficial_f", "Arabic", "Female",
            "Arabic root ف ي د (f-y-d); مُفِيدَة (Mufīda)", False, "high",
            "Mufida is Arabic مُفِيدَة (Mufīda) 'beneficial, useful' (feminine), from the root ف ي د (f-y-d). The source gloss 'Generous one' is unsupported and has been replaced with the lexical sense. Same name as mufeeda."),
 "mufti": ("مفتي", "مفتی", "مفتی", "मुफ़्ती", "مفتي", "mufti", "Arabic", "Male",
           "Arabic root ف ت ي (f-t-y); مُفْتِي (Muftī)", False, "high",
           "Mufti is Arabic مُفْتِي (Muftī) 'a jurist who issues rulings', from the root ف ت ي (f-t-y). The source gloss 'Jurisconsult' is consistent. Recorded as a title also used as a given name."),
 "muhaammad": ("مُحَمَّد", "محمد", "محمد", "मुहम्मद", "محمد", "muhammad", "Arabic", "Male",
               "Arabic root ح م د (ḥ-m-d); مُحَمَّد (Muḥammad)", False, "high",
               "Muhaammad is a spelling variant of Arabic مُحَمَّد (Muḥammad) 'the praised one', from the root ح م د (ḥ-m-d). The source gloss 'Praiseworthy' is consistent. Same name as muhammad and muhammed."),
 "muhab": ("محب", "محب", "محب", "मुहब", "محب", "muhib", "Arabic", "Male",
           "Arabic root ح ب ب (ḥ-b-b); مُحِبّ (Muḥibb)", False, "high",
           "Muhab is recorded here as Arabic مُحِبّ (Muḥibb) 'loving, affectionate', from the root ح ب ب (ḥ-b-b). CRITICAL SOURCE ERROR: the source gave the Latin string 'Muhab' instead of a script form. The source gloss 'Lover, Friend' is partly consistent. Same name as muhib."),
 "muhabbat": ("محبة", "محبت", "محبت", "मुहब्बत", "محبت", "love_mohabbat", "Arabic", "Female",
              "Arabic root ح ب ب (ḥ-b-b); مَحَبَّة (Maḥabba)", False, "high",
              "Muhabbat is Arabic مَحَبَّة (Maḥabba) 'love, affection', from the root ح ب ب (ḥ-b-b). The source gloss 'Love, affection' is consistent. Recorded as a common noun also used as a given name."),
 "muhaimin": ("مُهَيْمِن", "مہیمن", "مهیمن", "मुहैमिन", "مهیمن", "muhaimin", "Arabic", "Male",
              "Arabic root ه ي م ن (h-y-m-n); مُهَيْمِن (Muhaymin)", False, "high",
              "Muhaimin is Arabic مُهَيْمِن (Muhaymin) 'guardian, protector', from the root ه ي م ن (h-y-m-n). The source gloss 'Protector' is consistent."),
 "muhammad": ("محمد", "محمد", "محمد", "मुहम्मद", "محمد", "muhammad", "Arabic", "Male",
              "Arabic root ح م د (ḥ-m-d); مُحَمَّد (Muḥammad)", False, "high",
              "Muhammad is Arabic مُحَمَّد (Muḥammad) 'the praised one', from the root ح م د (ḥ-m-d); it is the name of the Prophet of Islam. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as muhammed."),
 "muhammadi": ("محمدی", "محمدی", "محمدی", "मुहम्मदी", "محمدي", "muhammadi", "Arabic", "Male",
               "Arabic مُحَمَّدِي (Muḥammadī)", False, "high",
               "Muhammadi is Arabic مُحَمَّدِي (Muḥammadī) 'of Muhammad, pertaining to Muhammad'. The source gloss 'Lover of Muhammad' is unsupported and has been replaced with the documented relational sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male."),
 "muhammed": ("محمد", "محمد", "محمد", "मुहम्मद", "محمد", "muhammad", "Arabic", "Male",
              "Arabic root ح م د (ḥ-m-d); مُحَمَّد (Muḥammad)", False, "high",
              "Muhammed is a spelling variant of Arabic مُحَمَّد (Muḥammad) 'the praised one', from the root ح م د (ḥ-m-d). The source gloss 'Praiseworthy, Glorified, Commended' is consistent. Same name as muhammad."),
 "muhanad": ("مُحَنَّد", "محند", "محند", "मुहनद", "محند", "muhanad", "Arabic", "Male",
             "Arabic مُحَنَّد (Muḥannad)", False, "medium",
             "Muhanad is recorded as Arabic مُحَنَّد (Muḥannad), a male given name. The source gloss 'Steadfast in Faith' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "muhanna": ("محنا", "محنا", "محنا", "मुहन्ना", "محنا", "uncertain_form", "Unknown", "Unknown",
             "No reliable root analysis established.", False, "low",
             "Muhanna is recorded at low confidence. The source gave محنا and glossed the name 'Warrior, Fighter'; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "muhannad": ("مُهَنَّد", "مہند", "مهند", "मुहन्नद", "مهند", "muhannad", "Arabic", "Male",
              "Arabic مُهَنَّد (Muhannad) 'a sword'", False, "high",
              "Muhannad is Arabic مُهَنَّد (Muhannad) 'a sword, an Indian blade', also used as a male given name. The source gloss 'Warrior' is broadly consistent with the association of the word."),
 "muhanned": ("مُهَنَّد", "مہند", "مهند", "मुहन्नद", "مهند", "muhannad", "Arabic", "Male",
              "Arabic مُهَنَّد (Muhannad) 'a sword'", False, "high",
              "Muhanned is Arabic مُهَنَّد (Muhannad) 'a sword', also used as a male given name. CRITICAL SOURCE ERROR: the source gave محمد (a different name) and glossed the name 'Given by Allah'; the source gloss is unsupported. Same name as muhannad."),
 "muharrem": ("محرم", "محرم", "محرم", "मुहर्रम", "محرم", "muharram", "Turkish", "Male",
              "Turkish muharrem, from Arabic مُحَرَّم (Muḥarram)", False, "high",
              "Muharrem is the Turkish form of Arabic مُحَرَّم (Muḥarram), the first month of the Islamic calendar. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as spelled is Turkish. The source gloss 'Sacred, Invincible' is partly consistent (the root sense is 'forbidden, sacred')."),
 "muhib": ("محب", "محب", "محب", "मुहिब", "محب", "muhib", "Arabic", "Male",
           "Arabic root ح ب ب (ḥ-b-b); مُحِبّ (Muḥibb)", False, "high",
           "Muhib is Arabic مُحِبّ (Muḥibb) 'loving, affectionate, fond', from the root ح ب ب (ḥ-b-b). The source gloss 'Loving, Affectionate' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male. Same name as muhab."),
 "muhid": ("مُوحِد", "موحد", "موحد", "मुवह्हिद", "موحد", "monotheist", "Arabic", "Male",
           "Arabic root و ح د (w-ḥ-d); مُوحِد (Mūḥid)", False, "high",
           "Muhid is Arabic مُوحِد (Mūḥid) 'monotheist, one who affirms God's oneness', from the root و ح د (w-ḥ-d). CRITICAL SOURCE ERROR: the source gave مهد (a different form); the correct form is مُوحِد. The source gloss 'Seeker of knowledge' is unsupported and has been replaced with the lexical sense."),
 "muhit": ("محيط", "محيط", "محيط", "मुहीत", "محيط", "muhit", "Arabic", "Male",
           "Arabic root ح و ط (ḥ-w-ṭ); مُحِيط (Muḥīṭ)", False, "high",
           "Muhit is Arabic مُحِيط (Muḥīṭ) 'encompassing, surrounding; ocean', from the root ح و ط (ḥ-w-ṭ). CRITICAL SOURCE ERROR: the source gave منحيت (a different form); the correct form is مُحِيط. The source gloss 'Protector, Defender' is unsupported and has been replaced with the lexical sense."),
 "muhsin": ("محسن", "محسن", "محسن", "मुहसिन", "محسن", "muhsin", "Arabic", "Male",
            "Arabic root ح س ن (ḥ-s-n); مُحْسِن (Muḥsin)", False, "high",
            "Muhsin is Arabic مُحْسِن (Muḥsin) 'benefactor, doer of good', from the root ح س ن (ḥ-s-n). The source gloss 'The Benefactor' is consistent."),
 "muhsina": ("محسنة", "محسنہ", "محسنه", "मुहसिना", "محسنه", "muhsina", "Arabic", "Female",
             "Arabic root ح س ن (ḥ-s-n); مُحْسِنَة (Muḥsina)", False, "high",
             "Muhsina is Arabic مُحْسِنَة (Muḥsina) 'virtuous, doer of good' (feminine), from the root ح س ن (ḥ-s-n). The source gloss 'Virtuous, good doer' is consistent."),
 "muid": ("مُعِيد", "معید", "معید", "मुईद", "معید", "muid", "Arabic", "Male",
          "Arabic root ع و د (ʿ-w-d); مُعِيد (Muʿīd)", False, "high",
          "Muid is Arabic مُعِيد (Muʿīd) 'one who restores, returns', from the root ع و د (ʿ-w-d). The source gloss 'Helpful, Aid' is unsupported and has been replaced with the lexical sense."),
 "muin": ("مُعِين", "معین", "معین", "मुईन", "معین", "muin", "Arabic", "Male",
          "Arabic root ع و ن (ʿ-w-n); مُعِين (Muʿīn)", False, "high",
          "Muin is Arabic مُعِين (Muʿīn) 'helper, supporter', from the root ع و ن (ʿ-w-n). The source gloss 'Support, Helper' is consistent. Same name as mueen."),
 "muir": ("موير", "موئر", "مویر", "मुइर", "مویر", "muir", "English", "Unknown",
          "Scottish Gaelic muir 'sea'", False, "medium",
          "Muir is a Scottish surname and given name, from Scottish Gaelic muir 'sea'. CRITICAL SOURCE ERROR: the source gave مور and labelled the origin Arabic; the name is not Arabic. The source gloss 'Little river' is unsupported; the documented element means 'sea'. Recorded as a surname-derived name; no single personal-name gender usage is asserted."),
 "muiz": ("مُعِزّ", "معز", "معز", "मुइज़्ज़", "معز", "muiz", "Arabic", "Male",
          "Arabic root ع ز ز (ʿ-z-z); مُعِزّ (Muʿizz)", False, "high",
          "Muiz is Arabic مُعِزّ (Muʿizz) 'one who honours, giver of honour', from the root ع ز ز (ʿ-z-z). The source gloss 'Reviver, Reformer' is unsupported and has been replaced with the lexical sense. Same name as muizz."),
 "muizz": ("مُعِزّ", "معز", "معز", "मुइज़्ज़", "معز", "muizz", "Arabic", "Male",
           "Arabic root ع ز ز (ʿ-z-z); مُعِزّ (Muʿizz)", False, "high",
           "Muizz is Arabic مُعِزّ (Muʿizz) 'one who honours, giver of honour', from the root ع ز ز (ʿ-z-z). The source gloss 'One who Glorifies' is broadly consistent. Same name as muiz."),
 "mujaahid": ("مجاهد", "مجاہد", "مجاهد", "मुजाहिद", "مجاهد", "mujahid", "Arabic", "Male",
              "Arabic root ج ه د (j-h-d); مُجَاهِد (Mujāhid)", False, "high",
              "Mujaahid is Arabic مُجَاهِد (Mujāhid) 'one who strives, fighter', from the root ج ه د (j-h-d). The source gloss 'Striving in the path of Allah' is a religious application of the lexical sense. Same name as mujahid."),
 "mujahid": ("مجاهد", "مجاہد", "مجاهد", "मुजाहिद", "مجاهد", "mujahid", "Arabic", "Male",
             "Arabic root ج ه د (j-h-d); مُجَاهِد (Mujāhid)", False, "high",
             "Mujahid is Arabic مُجَاهِد (Mujāhid) 'one who strives, fighter', from the root ج ه د (j-h-d). The source gloss 'Warrior, Fighter' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male. Same name as mujaahid."),
 "mujammil": ("مُزَّمِّل", "مزمل", "مزمل", "मुज़म्मिल", "مزمل", "mujammil", "Arabic", "Male",
              "Arabic root ز م ل (z-m-l); مُزَّمِّل (Muzzammil)", False, "high",
              "Mujammil is Arabic مُزَّمِّل (Muzzammil) 'one wrapped in a cloak', from the root ز م ل (z-m-l); it is a Qur'anic sura name. The source gloss 'Well-covered, clothed' is broadly consistent."),
 "mujeeb": ("مُجِيب", "مجیب", "مجیب", "मुजीब", "مجیب", "mujeeb", "Arabic", "Male",
            "Arabic root ج و ب (j-w-b); مُجِيب (Mujīb)", False, "high",
            "Mujeeb is Arabic مُجِيب (Mujīb) 'one who answers, responsive', from the root ج و ب (j-w-b). The source gloss 'Responding to prayer' is a religious application of the lexical sense. Same name as mujib."),
 "mujib": ("مُجِيب", "مجیب", "مجیب", "मुजीब", "مجیب", "mujib", "Arabic", "Male",
           "Arabic root ج و ب (j-w-b); مُجِيب (Mujīb)", False, "high",
           "Mujib is Arabic مُجِيب (Mujīb) 'one who answers, responsive', from the root ج و ب (j-w-b). The source gloss 'Granted, Achieved, Powerful' is unsupported and has been replaced with the lexical sense. Same name as mujeeb."),
 "mujibur": ("مُجِيبُ الرَّحْمَن", "مجیب الرحمٰن", "مجیب‌الرحمن", "मुजीबुर", "مجیب الرحمن", "mujibur", "Arabic", "Male",
             "Arabic مُجِيبُ الرَّحْمَن (Mujīb al-Raḥmān)", False, "high",
             "Mujibur is Arabic مُجِيبُ الرَّحْمَن (Mujīb al-Raḥmān) 'answerer of the Most Merciful', a compound name. CRITICAL SOURCE ERROR: the source gave موجب (a different form); the correct form is مُجِيبُ الرَّحْمَن. The source gloss 'Grantor, Provider' is unsupported and has been replaced with the documented compound."),
 "mujtaba": ("مُجْتَبَى", "مجتبیٰ", "مجتبی", "मुज्तबा", "مجتبی", "mujtaba", "Arabic", "Male",
             "Arabic root ج ب ي (j-b-y); مُجْتَبَى (Mujtabā)", False, "high",
             "Mujtaba is Arabic مُجْتَبَى (Mujtabā) 'chosen, selected', from the root ج ب ي (j-b-y). The source gloss 'Chosen One, the Selected' is consistent."),
 "mukarram": ("مُكَرَّم", "مکرم", "مکرم", "मुकर्रम", "مکرم", "mukarram", "Arabic", "Male",
              "Arabic root ك ر م (k-r-m); مُكَرَّم (Mukarram)", False, "high",
              "Mukarram is Arabic مُكَرَّم (Mukarram) 'honoured, respected', from the root ك ر م (k-r-m). The source gloss 'Honored, Respected' is consistent."),
 "mukhlis": ("مُخْلِص", "مخلص", "مخلص", "मुख़लिस", "مخلص", "mukhlis", "Arabic", "Male",
             "Arabic root خ ل ص (kh-l-ṣ); مُخْلِص (Mukhliṣ)", False, "high",
             "Mukhlis is Arabic مُخْلِص (Mukhliṣ) 'sincere, devoted', from the root خ ل ص (kh-l-ṣ). The source gloss 'Dedicated, Devoted' is consistent."),
 "mukhtaar": ("مختار", "مختار", "مختار", "मुख़्तार", "مختار", "mukhtar", "Arabic", "Male",
              "Arabic root خ ي ر (kh-y-r); مُخْتَار (Mukhtār)", False, "high",
              "Mukhtaar is Arabic مُخْتَار (Mukhtār) 'chosen, elected', from the root خ ي ر (kh-y-r). The source gloss 'Chosen One, Ruler' is partly consistent. Same name as mukhtar."),
 "mukhtar": ("مختار", "مختار", "مختار", "मुख़्तार", "مختار", "mukhtar", "Arabic", "Male",
             "Arabic root خ ي ر (kh-y-r); مُخْتَار (Mukhtār)", False, "high",
             "Mukhtar is Arabic مُخْتَار (Mukhtār) 'chosen, elected', from the root خ ي ر (kh-y-r). The source gloss 'Chosen One' is consistent. Same name as mukhtaar."),
 "mukhtiar": ("مختار", "مختار", "مختار", "मुख़्तार", "مختار", "mukhtar", "Arabic", "Male",
              "Arabic root خ ي ر (kh-y-r); مُخْتَار (Mukhtār)", False, "high",
              "Mukhtiar is a spelling variant of Arabic مُخْتَار (Mukhtār) 'chosen, elected', from the root خ ي ر (kh-y-r). The source gloss 'Granter of Freedom' is unsupported and has been replaced with the lexical sense. Same name as mukhtar."),
 "mulan": ("مولان", "مولان", "مولان", "मूलान", "مولان", "mulan", "Chinese", "Female",
           "Chinese 木兰 (Mùlán)", False, "medium",
           "Mulan is a Chinese given name (木兰, Mùlán), historically associated with the legendary figure Hua Mulan. CRITICAL SOURCE ERROR: the source gave مُلَان and labelled the origin Arabic; the name is Chinese. The source gloss 'Magnolia flower' is broadly consistent with the Chinese element 兰 (orchid/magnolia)."),
 "mulazim": ("مُلَازِم", "ملازم", "ملازم", "मुलाज़िम", "ملازم", "mulazim", "Arabic", "Male",
             "Arabic root ل ز م (l-z-m); مُلَازِم (Mulāzim)", False, "high",
             "Mulazim is Arabic مُلَازِم (Mulāzim) 'officer, one who clings, attached', from the root ل ز م (l-z-m). CRITICAL SOURCE ERROR: the source gave the Latin string 'Mulazim' instead of a script form. The source gloss 'Commander, Leader' is unsupported and has been replaced with the lexical sense."),
 "mulham": ("مُلْهَم", "ملہم", "ملهم", "मुलहम", "ملهم", "mulham", "Arabic", "Male",
            "Arabic root ل ه م (l-h-m); مُلْهَم (Mulham)", False, "high",
            "Mulham is Arabic مُلْهَم (Mulham) 'inspired, one given inspiration', from the root ل ه م (l-h-m). The source gloss 'Soldier, Warrior' is unsupported and has been replaced with the lexical sense."),
 "mulla": ("مُلَّا", "ملا", "ملا", "मुल्ला", "ملا", "mulla", "Arabic", "Male",
           "Arabic مَوْلَى (Mawlā) / مُلَّا (Mullā)", False, "high",
           "Mulla is Arabic مُلَّا (Mullā), a title for a learned man, ultimately from مَوْلَى (mawlā). The source gloss 'My lord' is broadly consistent with the root sense. Recorded as a title also used as a given name."),
 "multan": ("مُلْتَان", "ملتان", "مولتان", "मुल्तान", "ملتان", "multan", "Unknown", "Unknown",
            "Place name; no lexical root analysis established.", False, "medium",
            "Multan is the name of a city in Pakistan, used occasionally as a personal name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic and glossed the name 'City of Light'; the source gloss is unsupported. Recorded as a place name; no personal-name gender usage is asserted."),
 "mumin": ("مُؤْمِن", "مومن", "مومن", "मोमिन", "مومن", "mumin", "Arabic", "Male",
           "Arabic root أ م ن (ʾ-m-n); مُؤْمِن (Muʾmin)", False, "high",
           "Mumin is Arabic مُؤْمِن (Muʾmin) 'believer, one who has faith', from the root أ م ن (ʾ-m-n). The source gloss 'Faithful, Believer' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male. Same name as momin and moumin."),
 "mumtaz": ("مُمْتَاز", "ممتاز", "ممتاز", "मुमताज़", "ممتاز", "mumtaz", "Arabic", "Male",
            "Arabic root م ي ز (m-y-z); مُمْتَاز (Mumtāz)", False, "high",
            "Mumtaz is Arabic مُمْتَاز (Mumtāz) 'distinguished, excellent', from the root م ي ز (m-y-z). The source gloss 'Exalted, Distinguished, Resplendent' is partly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "muna": ("مُنَى", "منیٰ", "منی", "मुना", "منی", "muna", "Arabic", "Female",
          "Arabic root م ن ي (m-n-y); مُنَى (Munā)", False, "high",
          "Muna is Arabic مُنَى (Munā) 'wishes, desires', from the root م ن ي (m-n-y). The source gloss 'Consoler, Supporter' is unsupported and has been replaced with the lexical sense. Same name as mona and munya."),
 "munaf": ("مُنَاف", "مناف", "مناف", "मुनाफ़", "مناف", "munaf", "Arabic", "Male",
           "Arabic مُنَاف (Munāf)", False, "medium",
           "Munaf is recorded as Arabic مُنَاف (Munāf), a male given name. The source gloss 'Forbearing, Patient' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "munar": ("مَنَار", "منار", "منار", "मुनार", "منار", "munar", "Arabic", "Male",
           "Arabic root ن و ر (n-w-r); مَنَار (Manār)", False, "high",
           "Munar is Arabic مَنَار (Manār) 'lighthouse, place of light', from the root ن و ر (n-w-r). The source gloss 'Moon' is unsupported and has been replaced with the lexical sense. Same name as manar."),
 "munawar": ("مُنَوَّر", "منور", "منور", "मुनव्वर", "منور", "munawar", "Arabic", "Male",
             "Arabic root ن و ر (n-w-r); مُنَوَّر (Munawwar)", False, "high",
             "Munawar is Arabic مُنَوَّر (Munawwar) 'illuminated, radiant', from the root ن و ر (n-w-r). The source gloss 'Beloved, Adored' is unsupported and has been replaced with the lexical sense."),
 "munawara": ("مُنَوَّرَة", "منورہ", "منوره", "मुनव्वरा", "منوره", "munawara", "Arabic", "Female",
              "Arabic root ن و ر (n-w-r); مُنَوَّرَة (Munawwara)", False, "high",
              "Munawara is Arabic مُنَوَّرَة (Munawwara) 'illuminated, radiant' (feminine), from the root ن و ر (n-w-r). The source gloss 'Lit up, radiant' is consistent."),
 "munawarah": ("مُنَوَّرَة", "منورہ", "منوره", "मुनव्वरा", "منوره", "munawara", "Arabic", "Female",
               "Arabic root ن و ر (n-w-r); مُنَوَّرَة (Munawwara)", False, "high",
               "Munawarah is Arabic مُنَوَّرَة (Munawwara) 'illuminated, radiant' (feminine), from the root ن و ر (n-w-r). The source gloss 'The one who is adorned' is unsupported and has been replaced with the lexical sense. Same name as munawara."),
 "munaza": ("مُنَازَة", "منازہ", "منازه", "मुनाज़ा", "منازه", "uncertain_form", "Unknown", "Female",
            "No reliable root analysis established.", False, "low",
            "Munaza is recorded at low confidence. CRITICAL SOURCE ERROR: the source gave the Latin string 'Munaza' instead of a script form and glossed the name 'One who is helped'; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "munazir": ("مُنَاظِر", "مناظر", "مناظر", "मुनाज़िर", "مناظر", "munazir", "Arabic", "Male",
             "Arabic root ن ظ ر (n-ẓ-r); مُنَاظِر (Munāẓir)", False, "high",
             "Munazir is Arabic مُنَاظِر (Munāẓir) 'one who debates, disputant', from the root ن ظ ر (n-ẓ-r). The source gloss 'Debater' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male."),
 "munazza": ("مُنَزَّهَة", "منزہ", "منزه", "मुनज़्ज़ा", "منزه", "munazza", "Arabic", "Female",
             "Arabic root ن ز ه (n-z-h); مُنَزَّهَة (Munazzaha)", False, "high",
             "Munazza is Arabic مُنَزَّهَة (Munazzaha) 'purified, free from fault' (feminine), from the root ن ز ه (n-z-h). The source gloss 'Beautiful and lovely' is unsupported and has been replaced with the lexical sense."),
 "mundi": ("مُنْدِي", "مندی", "مندی", "मुंदी", "مندي", "mundi", "Arabic", "Male",
           "Arabic مُنْدِي (Mundī)", False, "medium",
           "Mundi is recorded as Arabic مُنْدِي (Mundī), a male given name. The source gloss 'Intelligent, Wise' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "muneeb": ("مُنِيب", "منیب", "منیب", "मुनीब", "منیب", "muneeb", "Arabic", "Male",
            "Arabic root ن و ب (n-w-b); مُنِيب (Munīb)", False, "high",
            "Muneeb is Arabic مُنِيب (Munīb) 'one who turns to God, repentant', from the root ن و ب (n-w-b). The source gloss 'Consoler, Helper' is unsupported and has been replaced with the lexical sense. Same name as moneeb."),
 "muneer": ("مُنِير", "منیر", "منیر", "मुनीर", "منیر", "muneer", "Arabic", "Male",
            "Arabic root ن و ر (n-w-r); مُنِير (Munīr)", False, "high",
            "Muneer is Arabic مُنِير (Munīr) 'luminous, illuminating', from the root ن و ر (n-w-r). The source gloss 'Guide, teacher, leader' is unsupported and has been replaced with the lexical sense. Same name as munir."),
 "muneera": ("مُنِيرَة", "منیرہ", "منیره", "मुनीरा", "منیره", "muneera", "Arabic", "Female",
             "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
             "Muneera is Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). The source gloss 'The Light-Giver' is broadly consistent. Same name as munirah."),
 "muneerah": ("مُنِيرَة", "منیرہ", "منیره", "मुनीरा", "منیره", "muneera", "Arabic", "Female",
              "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
              "Muneerah is Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source gave مُنۈرَة (a non-standard form); the correct form is مُنِيرَة. The source gloss 'Guide, Light' is partly consistent. Same name as muneera."),
 "munerah": ("مُنِيرَة", "منیرہ", "منیره", "मुनीरा", "منیره", "muneera", "Arabic", "Female",
             "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
             "Munerah is Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source gave منرة (a non-standard form); the correct form is مُنِيرَة. The source gloss 'A light-giving one' is broadly consistent. Same name as muneera."),
 "munia": ("مُنْيَة", "منیا", "منیا", "मुनिया", "منیا", "munia", "Arabic", "Female",
           "Arabic root م ن ي (m-n-y); مُنْيَة (Munyah)", False, "high",
           "Munia is Arabic مُنْيَة (Munyah) 'wish, desire', from the root م ن ي (m-n-y). The source gloss 'Jewel, Precious Stone' is unsupported and has been replaced with the lexical sense. Same name as munya."),
 "munib": ("مُنِيب", "منیب", "منیب", "मुनीब", "منیب", "munib", "Arabic", "Male",
           "Arabic root ن و ب (n-w-b); مُنِيب (Munīb)", False, "high",
           "Munib is Arabic مُنِيب (Munīb) 'one who turns to God, repentant', from the root ن و ب (n-w-b). The source gloss 'Obliging' is unsupported and has been replaced with the lexical sense. Same name as muneeb."),
 "munif": ("مُنِيف", "منیف", "منیف", "मुनीफ़", "منیف", "munif", "Arabic", "Male",
           "Arabic root ن ي ف (n-y-f); مُنِيف (Munīf)", False, "high",
           "Munif is Arabic مُنِيف (Munīf) 'elevated, lofty, high', from the root ن ي ف (n-y-f). The source gloss 'Forgiving, Generous' is unsupported and has been replaced with the lexical sense."),
 "munim": ("مُنْعِم", "منعم", "منعم", "मुनिम", "منعم", "munim", "Arabic", "Male",
           "Arabic root ن ع م (n-ʿ-m); مُنْعِم (Munʿim)", False, "high",
           "Munim is Arabic مُنْعِم (Munʿim) 'benefactor, bestower of favours', from the root ن ع م (n-ʿ-m). The source gloss 'Protector, Guardian' is unsupported and has been replaced with the lexical sense."),
 "munir": ("مُنِير", "منیر", "منیر", "मुनीर", "منیر", "munir", "Arabic", "Male",
           "Arabic root ن و ر (n-w-r); مُنِير (Munīr)", False, "high",
           "Munir is Arabic مُنِير (Munīr) 'luminous, radiant, illuminating', from the root ن و ر (n-w-r). The source gloss 'Luminous, Radiant, Illuminating' is consistent. Same name as muneer."),
 "munira": ("منيرة", "منیرہ", "منیره", "मुनीरा", "منیره", "muneera", "Arabic", "Female",
            "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
            "Munira is Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as muneera."),
 "munirah": ("مُنِيرَة", "منیرہ", "منیره", "मुनीरा", "منیره", "munirah", "Arabic", "Female",
             "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
             "Munirah is Arabic مُنِيرَة (Munīra) 'luminous, shining light' (feminine), from the root ن و ر (n-w-r). The source gloss 'Shining Light' is consistent. Same name as muneera."),
 "munirat": ("مُنِيرَة", "منیرہ", "منیره", "मुनीरा", "منیره", "muneera", "Arabic", "Female",
             "Arabic root ن و ر (n-w-r); مُنِيرَة (Munīra)", False, "high",
             "Munirat is recorded here as Arabic مُنِيرَة (Munīra) 'luminous, illuminating' (feminine), from the root ن و ر (n-w-r). The source gloss 'redeemer, savior, protector' is unsupported and has been replaced with the lexical sense. Same name as muneera."),
 "munis": ("مُونِس", "مونس", "مونس", "मूनिस", "مونس", "munis", "Arabic", "Male",
           "Arabic root أ ن س (ʾ-n-s); مُونِس (Mūnis)", False, "high",
           "Munis is Arabic مُونِس (Mūnis) 'companion, friendly, sociable', from the root أ ن س (ʾ-n-s). The source gloss 'Pleasant, Agreeable' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as monis."),
 "munisa": ("مُونِسَة", "مونیسہ", "مونیسه", "मुनीसा", "مونیسه", "munisa", "Arabic", "Female",
            "Arabic root أ ن س (ʾ-n-s); مُونِسَة (Mūnisa)", False, "high",
            "Munisa is Arabic مُونِسَة (Mūnisa) 'companion, friendly' (feminine), from the root أ ن س (ʾ-n-s). The source gloss 'Pious, Godly' is unsupported and has been replaced with the lexical sense."),
 "munna": ("مُنَّى", "منیٰ", "منی", "मुन्ना", "منی", "muna", "Arabic", "Female",
           "Arabic root م ن ي (m-n-y); مُنَى (Munā)", False, "high",
           "Munna is recorded here as Arabic مُنَى (Munā) 'wishes, desires', from the root م ن ي (m-n-y). CRITICAL SOURCE ERROR: the source gave the Latin string 'Munna' instead of a script form. The source gloss 'Protector' is unsupported and has been replaced with the lexical sense. Same name as muna."),
 "munsif": ("مُنْصِف", "منصف", "منصف", "मुन्सिफ़", "منصف", "munsif", "Arabic", "Male",
            "Arabic root ن ص ف (n-ṣ-f); مُنْصِف (Munṣif)", False, "high",
            "Munsif is Arabic مُنْصِف (Munṣif) 'fair, just, equitable', from the root ن ص ف (n-ṣ-f). The source gloss 'Just and Fair' is consistent. Same name as moncef."),
 "muntaha": ("مُنْتَهَى", "منتہیٰ", "منتهی", "मुंतहा", "منتهی", "muntaha", "Arabic", "Female",
             "Arabic root ن ه ي (n-h-y); مُنْتَهَى (Muntahā)", False, "high",
             "Muntaha is Arabic مُنْتَهَى (Muntahā) 'the utmost limit, endpoint', from the root ن ه ي (n-h-y); it occurs in the Qur'anic phrase سِدْرَة الْمُنْتَهَى. The source gloss 'Goal, Aim, Summit, Peak' is broadly consistent."),
 "muntasir": ("مُنْتَصِر", "منتصر", "منتصر", "मुंतसिर", "منتصر", "muntasir", "Arabic", "Male",
              "Arabic root ن ص ر (n-ṣ-r); مُنْتَصِر (Muntaṣir)", False, "high",
              "Muntasir is Arabic مُنْتَصِر (Muntaṣir) 'victorious, one who triumphs', from the root ن ص ر (n-ṣ-r). The source gloss 'Desirer of Victory' is unsupported and has been replaced with the lexical sense."),
 "muntazir": ("مُنْتَظِر", "منتظر", "منتظر", "मुंतज़िर", "منتظر", "muntazir", "Arabic", "Male",
              "Arabic root ن ظ ر (n-ẓ-r); مُنْتَظِر (Muntaẓir)", False, "high",
              "Muntazir is Arabic مُنْتَظِر (Muntaẓir) 'one who waits, expectant', from the root ن ظ ر (n-ẓ-r). The source gloss 'One who withholds, patiently endures' is unsupported and has been replaced with the lexical sense."),
 "munya": ("مُنْيَة", "منیہ", "منیه", "मुनिया", "منیه", "munya", "Arabic", "Female",
           "Arabic root م ن ي (m-n-y); مُنْيَة (Munyah)", False, "high",
           "Munya is Arabic مُنْيَة (Munyah) 'wish, desire', from the root م ن ي (m-n-y). The source gloss 'Comfort, Consolation' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as muna."),
 "munzir": ("مُنْذِر", "منذر", "منذر", "मुन्ज़िर", "منذر", "munzir", "Arabic", "Male",
            "Arabic root ن ذ ر (n-dh-r); مُنْذِر (Mundhir)", False, "high",
            "Munzir is Arabic مُنْذِر (Mundhir) 'warner, one who warns', from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave مُنْजिِر (Devanagari characters mixed into the Arabic field); the correct form is مُنْذِر. The source gloss 'The Victor' is unsupported and has been replaced with the lexical sense."),
 "muqadas": ("مُقَدَّس", "مقدس", "مقدس", "मुक़द्दस", "مقدس", "muqadas", "Arabic", "Female",
             "Arabic root ق د س (q-d-s); مُقَدَّس (Muqaddas)", False, "high",
             "Muqadas is Arabic مُقَدَّس (Muqaddas) 'sacred, holy, pure', from the root ق د س (q-d-s). The source gloss 'Honored, Pious, Sacred' is partly consistent."),
 "muqtada": ("مُقْتَدَى", "مقتدیٰ", "مقتدی", "मुक़्तदा", "مقتدی", "muqtada", "Arabic", "Male",
             "Arabic root ق د و (q-d-w); مُقْتَدَى (Muqtadā)", False, "high",
             "Muqtada is Arabic مُقْتَدَى (Muqtadā) 'one who is followed, leader', from the root ق د و (q-d-w). CRITICAL SOURCE ERROR: the source gave مقtADA (Latin characters mixed into the Arabic field); the correct form is مُقْتَدَى. The source gloss 'Ordered, Directed, Guided' is unsupported and has been replaced with the lexical sense."),
 "muqtadir": ("مُقْتَدِر", "مقتدر", "مقتدر", "मुक़्तदिर", "مقتدر", "muqtadir", "Arabic", "Male",
              "Arabic root ق د ر (q-d-r); مُقْتَدِر (Muqtadir)", False, "high",
              "Muqtadir is Arabic مُقْتَدِر (Muqtadir) 'powerful, capable, able', from the root ق د ر (q-d-r). CRITICAL SOURCE ERROR: the source gave المقتدر (with the definite article); the name form is مُقْتَدِر. The source gloss 'Determined, Firm, Decisive' is unsupported and has been replaced with the lexical sense."),
 "muraad": ("مُرَاد", "مراد", "مراد", "मुराद", "مراد", "murad", "Arabic", "Male",
            "Arabic root ر و د (r-w-d); مُرَاد (Murād)", False, "high",
            "Muraad is Arabic مُرَاد (Murād) 'wished-for, desired', from the root ر و د (r-w-d). CRITICAL SOURCE ERROR: the source gave موراد (a non-standard form); the correct form is مُرَاد. The source gloss 'Desire, Wish' is broadly consistent. Same name as murad."),
 "murad": ("مُرَاد", "مراد", "مراد", "मुराद", "مراد", "murad", "Arabic", "Male",
           "Arabic root ر و د (r-w-d); مُرَاد (Murād)", False, "high",
           "Murad is Arabic مُرَاد (Murād) 'wished-for, desired', from the root ر و د (r-w-d). The source gloss 'Wished or desired' is consistent. Same name as muraad and mourad."),
 "murah": ("مُرَاح", "مراح", "مراح", "मुराह", "مراح", "murah", "Arabic", "Male",
           "Arabic مُرَاح (Murāḥ)", False, "medium",
           "Murah is recorded as Arabic مُرَاح (Murāḥ), a male given name. The source gloss 'Bitter, Astringent' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "murazi": ("مُرَاضِي", "مراضی", "مراضی", "मुराज़ी", "مراضي", "murazi", "Arabic", "Male",
            "Arabic مُرَاضِي (Murāḍī)", False, "medium",
            "Murazi is recorded as Arabic مُرَاضِي (Murāḍī), a male given name. The source gloss 'Helper, Assistant' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "murid": ("مُرِيد", "مرید", "مرید", "मुरीद", "مرید", "murid", "Arabic", "Male",
           "Arabic root ر و د (r-w-d); مُرِيد (Murīd)", False, "high",
           "Murid is Arabic مُرِيد (Murīd) 'disciple, one who desires', from the root ر و د (r-w-d). The source gloss 'One who desires' is consistent."),
 "mursal": ("مُرْسَل", "مرسل", "مرسل", "मुरसल", "مرسل", "mursal", "Arabic", "Male",
            "Arabic root ر س ل (r-s-l); مُرْسَل (Mursal)", False, "high",
            "Mursal is Arabic مُرْسَل (Mursal) 'sent, messenger', from the root ر س ل (r-s-l). The source gloss 'Asker' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "mursaleen": ("مُرْسَلِين", "مرسلین", "مرسلین", "मुरसलीन", "مرسلین", "mursaleen", "Arabic", "Male",
               "Arabic root ر س ل (r-s-l); مُرْسَلِين (Mursalīn)", False, "high",
               "Mursaleen is Arabic مُرْسَلِين (Mursalīn) 'messengers', the plural of مُرْسَل (mursal), from the root ر س ل (r-s-l). The source gloss 'Messengers' is consistent. Same name as mursalin."),
 "mursalin": ("مُرْسَلِين", "مرسلین", "مرسلین", "मुरसलीन", "مرسلین", "mursalin", "Arabic", "Male",
              "Arabic root ر س ل (r-s-l); مُرْسَلِين (Mursalīn)", False, "high",
              "Mursalin is Arabic مُرْسَلِين (Mursalīn) 'messengers', the plural of مُرْسَل (mursal), from the root ر س ل (r-s-l). The source gloss 'The one who brings the message' is unsupported and has been replaced with the lexical sense. Same name as mursaleen."),
 "murshad": ("مُرْشِد", "مرشد", "مرشد", "मुर्शिद", "مرشد", "murshid", "Arabic", "Male",
             "Arabic root ر ش د (r-sh-d); مُرْشِد (Murshid)", False, "high",
             "Murshad is a spelling variant of Arabic مُرْشِد (Murshid) 'guide, teacher', from the root ر ش د (r-sh-d). The source gloss 'Guide, Teacher' is consistent. Same name as murshid."),
 "murshid": ("مُرْشِد", "مرشد", "مرشد", "मुर्शिद", "مرشد", "murshid", "Arabic", "Male",
             "Arabic root ر ش د (r-sh-d); مُرْشِد (Murshid)", False, "high",
             "Murshid is Arabic مُرْشِد (Murshid) 'guide, teacher, master', from the root ر ش د (r-sh-d). The source gloss 'Guide, Teacher, Master' is consistent. Same name as murshad."),
 "murshida": ("مُرْشِدَة", "مرشدہ", "مرشده", "मुर्शिदा", "مرشده", "murshida", "Arabic", "Female",
              "Arabic root ر ش د (r-sh-d); مُرْشِدَة (Murshida)", False, "high",
              "Murshida is Arabic مُرْشِدَة (Murshida) 'guide, teacher' (feminine), from the root ر ش د (r-sh-d). The source gloss 'Guide, Helper' is broadly consistent."),
}
