# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 49 (nuhaa..pir).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": olka -> Latin "Olka"; omama -> Latin
   "Omama"; orang -> Latin "Orang"; orna -> "Aisha" (Latin); ozra -> "Ali" (Latin);
   palwasha -> Latin "Palwasha"; pamir -> Latin "Pamir"; pania -> Latin "Pania";
   paria -> Latin "Paria"; parivash -> "Ahmad" (Latin); parla -> Latin "Parla";
   parmida -> Latin "Parmida"; parna -> Latin "Parna"; parnia -> Latin "Parnia";
   parva -> Latin "Parva"; parween -> Latin "Parween"; parwez -> Latin "Parwez";
   pegah -> Latin "Pegah"; pinar -> Latin "Pinar"; orah -> "Unknown";
   oula -> "Unknown"; parisa -> "عربي_Parisa" (placeholder);
   oktai -> أحمد; ozhan -> أحمد; parastu -> أحمد; parinaz -> عائشة;
   parvin -> عائشة; osama -> عثامة; ossama -> عُصَمَةُ; orwa -> أروى;
   omaira -> أميرة; omaima -> عويميا; olfat -> ألفات; ons -> أونس;
   orhan/orkhan -> أورخان; ozge -> أوزغه; parastoo -> بارستو; parsa -> بارسا;
   parvana -> فروھانة; parwana -> بروانة; parwar -> باروار; parwaz -> براوز;
   parwiz -> بارويز; pasha -> باشا; payam -> بيام; pervaiz -> برويز;
   perveen -> فروان; peyman -> بيامان; pir -> بير.
 * EMPTY STUBS (8-key records, no data): omair, omar, parvez.
 * MISLABELLED ORIGIN: orhan/orkhan (Turkish), ozge (Turkish), ozhan (Turkish),
   parastoo/parastu/paria/parinaz/parisa/parivash/parmida/parna/parnia/parsa/
   parva/parvana/parwana/parveen/parvin/parween/parwez/parwiz/payam/pegah/
   peyman (Persian), parla (Turkish), palwasha (Pashto), pamir (Persian),
   pania (Maori/other), pinar (Turkish), oktai (Turkish), orang (Malay),
   orna (Hebrew/Irish), ozra (Persian/Bosnian), pir (Persian).
 * DEGARBLED GLOSSES: nuhaa "Prophetess mentioned in the Quran",
   nujood "Eloquent, Intelligent", numa "Rest", numaan "Reliever of Hardship",
   numan "Blood, Red", nurat "Light, Radiance", nuril "Light, Enlightenment",
   nurin "Light of Faith", nurul "Light of God", nurun "Light of God",
   nusaiba "Support, Helper, Aid", nusaibah "Giver of good news",
   nusha "Restless, agitated", nushad "Granted by Allah", nusrat "Help, Victory",
   nuzha "Journey, Excursion", nuzhat "Amusement, Entertainment",
   obaid "Servant", obaida "Brave, Lion", obaidah "Servant",
   oktai "Strong, Powerful", olfat "Sweet Basil", olka "Small lake",
   omaid "Hope and Expectation", omaima "Gentle, soft, or delicate",
   omaira "Life, Long Life", omama "Mother of the Believers",
   omaria "Feminine form of Omar", omeed "Prosperity, Happiness",
   omer "Long life", omid "Hope", omran "Mountain man",
   ons "One, Unity, Gathering", oraib "Radiant, shining", orang "Orange Fruit",
   orhan "Golden mountain", orjun "Exalted, Noble", orkhan "Man of Mountain",
   orna "Bright, Radiant", orwa "Lion", osama "Living man", osamaa "Life, Tender",
   osamah "Lion of God", osman "Praiseworthy", osmanli "Ottoman Empire",
   ossama "Success", othmane "Supporter of the weak", oula "Light, Illumination",
   owais "Little Wolf", ozge "Gift of God", ozhan "brave lion",
   ozra "Light, Radiant", palwasha "Jewel, precious one", pamir "High, noble",
   pania "Divine Grace", parastoo "Butterfly", parastu "Protector",
   paria "Butterfly", parinaz "Light, Bright", parisa "Noble and blessed",
   parivash "Gentle Breeze", parla "Lotus flower", parmida "The Fragrant Garden",
   parna "Lotus", parnia "Gift of God", parsa "Basket", parva "Maiden, young girl",
   parvana "Maiden, Lady", parveen "Moonlight", parvin "Meadow, Garden",
   parwana "Butterfly", parwar "Protector, Caretaker", parwaz "Traveler, Soarer, Skyward",
   parween "Meadow", parwez "Brave, Strong", parwiz "Traveler, Seeker",
   pasha "Governor, leader", payam "Message, News", pegah "Dove, Bird",
   pervaiz "Conqueror, Victorious", perveen "Seer, Observer",
   peyman "Reliable, Trustworthy, Protector", pinar "pine tree",
   pir "Sea explorer".
 * GENDER ERRORS: nujum, numa, nurin, nurul, nurun, nuryn, nusrat, nuzha,
   nuzhat, ons, orang, ozge, ozra, pamir, parwar, pir were labelled unisex
   where documented usage is male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated48 import GLOSSES as _G48

GLOSSES = dict(_G48)
GLOSSES.update({
    "nuhaa": {"en": "Nuhaa; intelligence, understanding", "ur": "نہیٰ، عقل، فہم", "fa": "نهی، خرد", "hi": "नुहा, बुद्धि", "ps": "نهی، عقل", "ar": "النُّهَى، الْعَقْل"},
    "nujood": {"en": "Nujood; a female given name", "ur": "نجود (زنانہ نام)", "fa": "نجود (نام زنانه)", "hi": "नजूद (स्त्री नाम)", "ps": "نجود (ښځينه نوم)", "ar": "نُجُود (اسْم عَلَم مُؤَنَّث)"},
    "stars": {"en": "Stars", "ur": "نجوم، ستارے", "fa": "نجوم، ستارگان", "hi": "नुजूम, तारे", "ps": "نجوم، ستوري", "ar": "النُّجُوم"},
    "numa": {"en": "Numa; a female given name", "ur": "نوما (زنانہ نام)", "fa": "نوما (نام زنانه)", "hi": "नूमा (स्त्री नाम)", "ps": "نوما (ښځينه نوم)", "ar": "نُومَا (اسْم عَلَم مُؤَنَّث)"},
    "naaman3": {"en": "Nu'man; a male given name", "ur": "نعمان (مردانہ نام)", "fa": "نعمان (نام مردانه)", "hi": "नोमान (पुरुष नाम)", "ps": "نعمان (نر نوم)", "ar": "نُعْمَان (اسْم عَلَم مُذَكَّر)"},
    "nur": {"en": "Nur; light, radiance", "ur": "نور، روشنی", "fa": "نور، روشنایی", "hi": "नूर, प्रकाश", "ps": "نور، رڼا", "ar": "النُّور"},
    "nurah": {"en": "Nurah; light (feminine)", "ur": "نورہ، روشنی", "fa": "نوره، روشنایی", "hi": "नूरा, प्रकाश", "ps": "نوره، رڼا", "ar": "النُّورَة، النُّور"},
    "nurain": {"en": "Nurain; two lights", "ur": "نورین، دو نور", "fa": "نورین، دو نور", "hi": "नूरैन, दो प्रकाश", "ps": "نورین، دوه رڼا", "ar": "النُّورَيْن (نُورَان)"},
    "nuran": {"en": "Nuran; full of light", "ur": "نوران، روشنی سے بھرا", "fa": "نوران، پر از نور", "hi": "नूरान, प्रकाश से भरा", "ps": "نوران، رڼا ډک", "ar": "نُورَان، الْمُنِير"},
    "nurani": {"en": "Nurani; luminous, of light", "ur": "نورانی، روشن", "fa": "نورانی، نورانی", "hi": "नूरानी, प्रकाशमान", "ps": "نوراني، روښانه", "ar": "النُّورَانِي، الْمُنِير"},
    "nurat": {"en": "Nurat; light, radiance", "ur": "نورت، روشنی", "fa": "نورت، روشنایی", "hi": "नूरत, प्रकाश", "ps": "نورت، رڼا", "ar": "النُّورَة، النُّور"},
    "nuray": {"en": "Nuray; light, radiance", "ur": "نورے، روشنی", "fa": "نورای، روشنایی", "hi": "नूरय, प्रकाश", "ps": "نورې، رڼا", "ar": "نُورَاي، النُّور"},
    "nureen": {"en": "Nureen; light, luminous", "ur": "نورین، روشن", "fa": "نورین، نورانی", "hi": "नौरीन, प्रकाशमान", "ps": "نورین، روښانه", "ar": "نُورِين، الْمُنِيرَة"},
    "nuri": {"en": "Nuri; luminous, of light", "ur": "نوری، روشن", "fa": "نوری، نورانی", "hi": "नूरी, प्रकाशमान", "ps": "نوري، روښانه", "ar": "النُّورِي، الْمُنِير"},
    "nuria": {"en": "Nuria; luminous, of light", "ur": "نوریہ، روشن", "fa": "نوریه، نورانی", "hi": "नूरिया, प्रकाशमान", "ps": "نوریه، روښانه", "ar": "النُّورِيَة، الْمُنِيرَة"},
    "nuril": {"en": "Nuril; light, enlightenment", "ur": "نورل، روشنی", "fa": "نورل، روشنایی", "hi": "नूरिल, प्रकाश", "ps": "نورل، رڼا", "ar": "نُورِل، النُّور"},
    "nurin": {"en": "Nurin; light, luminous", "ur": "نورین، روشن", "fa": "نورین، نورانی", "hi": "नूरीन, प्रकाशमान", "ps": "نورین، روښانه", "ar": "نُورِين، الْمُنِيرَة"},
    "nurul": {"en": "Nurul; light of (construct)", "ur": "نور ال، نورِ", "fa": "نور ال، نورِ", "hi": "नूरुल, प्रकाश", "ps": "نور ال، د رڼا", "ar": "نُورُ الـ (الْإِضَافَة)"},
    "nurun": {"en": "Nurun; light of (construct)", "ur": "نورون، نورِ", "fa": "نورون، نورِ", "hi": "नूरुन, प्रकाश", "ps": "نورون، د رڼا", "ar": "نُورُن (الْإِضَافَة)"},
    "nuryn": {"en": "Nuryn; light, luminous", "ur": "نورین، روشن", "fa": "نورین، نورانی", "hi": "नूरीन, प्रकाशमान", "ps": "نورین، روښانه", "ar": "نُورِين، الْمُنِيرَة"},
    "nusaiba": {"en": "Nusaiba; a female given name", "ur": "نصیبہ (زنانہ نام)", "fa": "نصیبه (نام زنانه)", "hi": "नुसैबा (स्त्री नाम)", "ps": "نصیبه (ښځينه نوم)", "ar": "نُسَيْبَة (اسْم عَلَم مُؤَنَّث)"},
    "nusaibah": {"en": "Nusaibah; a female given name", "ur": "نصیبہ (زنانہ نام)", "fa": "نصیبه (نام زنانه)", "hi": "नुसैबा (स्त्री नाम)", "ps": "نصیبه (ښځينه نوم)", "ar": "نُسَيْبَة (اسْم عَلَم مُؤَنَّث)"},
    "nusha": {"en": "Nusha; a female given name", "ur": "نوشہ (زنانہ نام)", "fa": "نوشا (نام زنانه)", "hi": "नुशा (स्त्री नाम)", "ps": "نوشا (ښځينه نوم)", "ar": "نُوشَا (اسْم عَلَم مُؤَنَّث)"},
    "nushad": {"en": "Nushad; happy, joyful (Persian)", "ur": "نوشاد، خوش", "fa": "نوشاد، خوشحال", "hi": "नुशाद, प्रसन्न", "ps": "نوشاد، خوشحاله", "ar": "نُوشَاد (الْمَسْرُور)"},
    "nusrat": {"en": "Nusrat; help, victory", "ur": "نصرت، مدد، فتح", "fa": "نصرت، یاری", "hi": "नुसरत, सहायता", "ps": "نصرت، مرسته", "ar": "النُّصْرَة، الْغَوْث"},
    "nusrath": {"en": "Nusrath; help, assistance", "ur": "نصرت، مدد", "fa": "نصرت، یاری", "hi": "नुसरत, सहायता", "ps": "نصرت، مرسته", "ar": "النُّصْرَة، الْغَوْث"},
    "nuzha": {"en": "Nuzha; excursion, outing", "ur": "نزہہ، سیر", "fa": "نزهه، گردش", "hi": "नुज़हा, सैर", "ps": "نزهه، سیر", "ar": "النُّزْهَة، التَّنَزُّه"},
    "nuzhat": {"en": "Nuzhat; excursion, outing", "ur": "نزہت، سیر، تفریح", "fa": "نزهت، گردش", "hi": "नुज़हत, सैर", "ps": "نزهت، سیر", "ar": "النُّزْهَة، التَّنَزُّه"},
    "obaid": {"en": "Obaid; little servant", "ur": "عبید، چھوٹا بندہ", "fa": "عبید، بنده کوچک", "hi": "उबैद, छोटा सेवक", "ps": "عبید، کوچنی بنده", "ar": "عُبَيْد، الْعَبْد الصَّغِير"},
    "obaida": {"en": "Obaida; little servant", "ur": "عبیدہ، چھوٹا بندہ", "fa": "عبیده، بنده کوچک", "hi": "उबैदा, छोटा सेवक", "ps": "عبیده، کوچنی بنده", "ar": "عُبَيْدَة، الْعَبْد الصَّغِير"},
    "obaidah": {"en": "Obaidah; little servant", "ur": "عبیدہ، چھوٹا بندہ", "fa": "عبیده، بنده کوچک", "hi": "उबैदा, छोटा सेवक", "ps": "عبیده، کوچنی بنده", "ar": "عُبَيْدَة، الْعَبْد الصَّغِير"},
    "oktai": {"en": "Oktai; a male given name (Turkish)", "ur": "اوکتای (مردانہ نام)", "fa": "اوکتای (نام مردانه)", "hi": "ओकताई (पुरुष नाम)", "ps": "اوکتای (نر نوم)", "ar": "أُوكْتَاي (اسْم عَلَم تُرْكِيّ)"},
    "olfat": {"en": "Olfat; a female given name", "ur": "الف ت (زنانہ نام)", "fa": "الفت (نام زنانه)", "hi": "उलफ़त (स्त्री नाम)", "ps": "الفت (ښځينه نوم)", "ar": "أُلْفَت (اسْم عَلَم مُؤَنَّث)"},
    "olka": {"en": "Olka; a female given name", "ur": "اولکا (زنانہ نام)", "fa": "اولکا (نام زنانه)", "hi": "ओल्का (स्त्री नाम)", "ps": "اولکا (ښځينه نوم)", "ar": "أُولْكَا (اسْم عَلَم مُؤَنَّث)"},
    "omaid": {"en": "Omaid; hope, expectation", "ur": "امید، توقع", "fa": "امید، انتظار", "hi": "उम्मीद, आशा", "ps": "هیله، تمه", "ar": "الْأَمَل، الرَّجَاء"},
    "omaima": {"en": "Omaima; a female given name", "ur": "امیمہ (زنانہ نام)", "fa": "امیمه (نام زنانه)", "hi": "उमैमा (स्त्री नाम)", "ps": "امیمه (ښځينه نوم)", "ar": "أُمَيْمَة (اسْم عَلَم مُؤَنَّث)"},
    "omair": {"en": "Omair; a male given name", "ur": "عمیر (مردانہ نام)", "fa": "عمیر (نام مردانه)", "hi": "उमैर (पुरुष नाम)", "ps": "عمیر (نر نوم)", "ar": "عُمَيْر (اسْم عَلَم مُذَكَّر)"},
    "omaira": {"en": "Omaira; a female given name", "ur": "عمیرہ (زنانہ نام)", "fa": "عمیره (نام زنانه)", "hi": "उमैरा (स्त्री नाम)", "ps": "عمیره (ښځينه نوم)", "ar": "عُمَيْرَة (اسْم عَلَم مُؤَنَّث)"},
    "omama": {"en": "Omama; a female given name", "ur": "امامہ (زنانہ نام)", "fa": "امامه (نام زنانه)", "hi": "उमामा (स्त्री नाम)", "ps": "امامه (ښځينه نوم)", "ar": "أُمَامَة (اسْم عَلَم مُؤَنَّث)"},
    "omar": {"en": "Omar; flourishing, long-lived", "ur": "عمر، طویل العمر", "fa": "عمر، بلندعمر", "hi": "उमर, दीर्घायु", "ps": "عمر، اوږد عمر", "ar": "عُمَر، طَوِيل الْعُمْر"},
    "omaria": {"en": "Omaria; of Omar (feminine)", "ur": "عمریہ، عمر سے منسوب (مؤنث)", "fa": "عمریه، منسوب به عمر", "hi": "उमरिया, उमर से संबंधित", "ps": "عمريه، د عمر اړوند", "ar": "عُمَرِيَّة، مَنْسُوب إِلَى عُمَر"},
    "omeed": {"en": "Omeed; hope, expectation", "ur": "امید، توقع", "fa": "امید، انتظار", "hi": "उम्मीद, आशा", "ps": "هیله، تمه", "ar": "الْأَمَل، الرَّجَاء"},
    "omer": {"en": "Omer; flourishing, long-lived", "ur": "عمر، طویل العمر", "fa": "عمر، بلندعمر", "hi": "उमर, दीर्घायु", "ps": "عمر، اوږد عمر", "ar": "عُمَر، طَوِيل الْعُمْر"},
    "omid": {"en": "Omid; hope (Persian)", "ur": "امید، توقع", "fa": "امید، انتظار", "hi": "उम्मीद, आशा", "ps": "هیله، تمه", "ar": "أُمِيد (الْأَمَل)"},
    "omran": {"en": "Omran; a male given name", "ur": "عمران (مردانہ نام)", "fa": "عمران (نام مردانه)", "hi": "उमरान (पुरुष नाम)", "ps": "عمران (نر نوم)", "ar": "عِمْرَان (اسْم عَلَم مُذَكَّر)"},
    "ons": {"en": "Ons; sociability, intimacy", "ur": "انس، مانوسیت", "fa": "انس، مانوسیت", "hi": "उन्स, सामीप्य", "ps": "انس، مانوسیت", "ar": "الْأُنْس، الْمُؤَانَسَة"},
    "orah": {"en": "Orah; light, radiance", "ur": "اورہ، روشنی", "fa": "اوره، روشنایی", "hi": "ओरा, प्रकाश", "ps": "اوره، رڼا", "ar": "أُورَة، النُّور"},
    "oraib": {"en": "Oraib; a male given name", "ur": "عریب (مردانہ نام)", "fa": "عریب (نام مردانه)", "hi": "उरैब (पुरुष नाम)", "ps": "عریب (نر نوم)", "ar": "عُرَيْب (اسْم عَلَم مُذَكَّر)"},
    "orang": {"en": "Orang; a male given name (Malay)", "ur": "اورنگ (مردانہ نام)", "fa": "اورنگ (نام مردانه)", "hi": "ओरंग (पुरुष नाम)", "ps": "اورنګ (نر نوم)", "ar": "أُورَنْغ (اسْم عَلَم مَلَايُوِيّ)"},
    "orhan": {"en": "Orhan; a male given name (Turkish)", "ur": "اورخان (مردانہ نام)", "fa": "اورخان (نام مردانه)", "hi": "ओरहान (पुरुष नाम)", "ps": "اورخان (نر نوم)", "ar": "أُورْخَان (اسْم عَلَم تُرْكِيّ)"},
    "orjun": {"en": "Orjun; a male given name", "ur": "ارجن (مردانہ نام)", "fa": "ارجن (نام مردانه)", "hi": "ओरजुन (पुरुष नाम)", "ps": "ارجن (نر نوم)", "ar": "أُورْجُن (اسْم عَلَم مُذَكَّر)"},
    "orkhan": {"en": "Orkhan; a male given name (Turkish)", "ur": "اورخان (مردانہ نام)", "fa": "اورخان (نام مردانه)", "hi": "ओरखान (पुरुष नाम)", "ps": "اورخان (نر نوم)", "ar": "أُورْخَان (اسْم عَلَم تُرْكِيّ)"},
    "orna": {"en": "Orna; a female given name", "ur": "اورنا (زنانہ نام)", "fa": "اورنا (نام زنانه)", "hi": "ओरना (स्त्री नाम)", "ps": "اورنا (ښځينه نوم)", "ar": "أُورْنَا (اسْم عَلَم مُؤَنَّث)"},
    "orwa": {"en": "Orwa; a male given name", "ur": "عروہ (مردانہ نام)", "fa": "عروه (نام مردانه)", "hi": "उरवा (पुरुष नाम)", "ps": "عروه (نر نوم)", "ar": "عُرْوَة (اسْم عَلَم مُذَكَّر)"},
    "osama": {"en": "Osama; a male given name", "ur": "اسامہ (مردانہ نام)", "fa": "اسامه (نام مردانه)", "hi": "उसामा (पुरुष नाम)", "ps": "اسامه (نر نوم)", "ar": "أُسَامَة (اسْم عَلَم مُذَكَّر)"},
    "osamaa": {"en": "Osamaa; a male given name", "ur": "اسامہ (مردانہ نام)", "fa": "اسامه (نام مردانه)", "hi": "उसामा (पुरुष नाम)", "ps": "اسامه (نر نوم)", "ar": "أُسَامَة (اسْم عَلَم مُذَكَّر)"},
    "osamah": {"en": "Osamah; a male given name", "ur": "اسامہ (مردانہ نام)", "fa": "اسامه (نام مردانه)", "hi": "उसामा (पुरुष नाम)", "ps": "اسامه (نر نوم)", "ar": "أُسَامَة (اسْم عَلَم مُذَكَّر)"},
    "osman": {"en": "Osman; a male given name", "ur": "عثمان (مردانہ نام)", "fa": "عثمان (نام مردانه)", "hi": "उस्मान (पुरुष नाम)", "ps": "عثمان (نر نوم)", "ar": "عُثْمَان (اسْم عَلَم مُذَكَّر)"},
    "osmanli": {"en": "Osmanli; Ottoman (relational)", "ur": "عثمانی، عثمان سے منسوب", "fa": "عثمانی، منسوب به عثمان", "hi": "उस्मानली, उस्मान से संबंधित", "ps": "عثماني، د عثمان اړوند", "ar": "الْعُثْمَانِي، مَنْسُوب إِلَى عُثْمَان"},
    "ossama": {"en": "Ossama; a male given name", "ur": "اسامہ (مردانہ نام)", "fa": "اسامه (نام مردانه)", "hi": "उसामा (पुरुष नाम)", "ps": "اسامه (نر نوم)", "ar": "أُسَامَة (اسْم عَلَم مُذَكَّر)"},
    "othmane": {"en": "Othmane; a male given name", "ur": "عثمان (مردانہ نام)", "fa": "عثمان (نام مردانه)", "hi": "उस्मान (पुरुष नाम)", "ps": "عثمان (نر نوم)", "ar": "عُثْمَان (اسْم عَلَم مُذَكَّر)"},
    "oula": {"en": "Oula; a female given name", "ur": "اولیٰ (زنانہ نام)", "fa": "اولی (نام زنانه)", "hi": "औला (स्त्री नाम)", "ps": "اولی (ښځينه نوم)", "ar": "أُولَى (اسْم عَلَم مُؤَنَّث)"},
    "owais": {"en": "Owais; a male given name", "ur": "اویس (مردانہ نام)", "fa": "اویس (نام مردانه)", "hi": "औवैस (पुरुष नाम)", "ps": "اویس (نر نوم)", "ar": "أُوَيْس (اسْم عَلَم مُذَكَّر)"},
    "ozge": {"en": "Ozge; a female given name (Turkish)", "ur": "اوزگے (زنانہ نام)", "fa": "اوزگه (نام زنانه)", "hi": "ओज़्गे (स्त्री नाम)", "ps": "اوزګه (ښځينه نوم)", "ar": "أُوزْغَة (اسْم عَلَم تُرْكِيّ)"},
    "ozhan": {"en": "Ozhan; a male given name (Turkish)", "ur": "اوزہان (مردانہ نام)", "fa": "اوزهان (نام مردانه)", "hi": "ओज़हान (पुरुष नाम)", "ps": "اوزهان (نر نوم)", "ar": "أُوزْهَان (اسْم عَلَم تُرْكِيّ)"},
    "ozra": {"en": "Ozra; a female given name", "ur": "عذرا (زنانہ نام)", "fa": "عذرا (نام زنانه)", "hi": "उज़रा (स्त्री नाम)", "ps": "عذرا (ښځينه نوم)", "ar": "عَذْرَاء (اسْم عَلَم مُؤَنَّث)"},
    "palwasha": {"en": "Palwasha; a female given name (Pashto)", "ur": "پلوشہ (زنانہ نام)", "fa": "پلوشه (نام زنانه)", "hi": "पलवाशा (स्त्री नाम)", "ps": "پلوشه (ښځينه نوم)", "ar": "بَلْوَشَة (اسْم عَلَم بَشْتُونِيّ)"},
    "pamir": {"en": "Pamir; a male given name (Persian)", "ur": "پامیر (مردانہ نام)", "fa": "پامیر (نام مردانه)", "hi": "पामीर (पुरुष नाम)", "ps": "پامیر (نر نوم)", "ar": "بَامِير (اسْم عَلَم فَارِسِيّ)"},
    "pania": {"en": "Pania; a female given name", "ur": "پانیہ (زنانہ نام)", "fa": "پانیا (نام زنانه)", "hi": "पानिया (स्त्री नाम)", "ps": "پانیا (ښځينه نوم)", "ar": "بَانِيَة (اسْم عَلَم مُؤَنَّث)"},
    "parastoo": {"en": "Parastoo; swallow, butterfly (Persian)", "ur": "پرستو، ابابیل", "fa": "پرستو، چلچله", "hi": "परस्तू, अबाबील", "ps": "پرستو، ابابیل", "ar": "بَرَسْتُو (السُّنُونُو)"},
    "parastu": {"en": "Parastu; swallow, butterfly (Persian)", "ur": "پرستو، ابابیل", "fa": "پرستو، چلچله", "hi": "परस्तू, अबाबील", "ps": "پرستو، ابابیل", "ar": "بَرَسْتُو (السُّنُونُو)"},
    "paria": {"en": "Paria; a female given name (Persian)", "ur": "پریا (زنانہ نام)", "fa": "پریا (نام زنانه)", "hi": "परिया (स्त्री नाम)", "ps": "پریا (ښځينه نوم)", "ar": "بَرِيَا (اسْم عَلَم فَارِسِيّ)"},
    "parinaz": {"en": "Parinaz; a female given name (Persian)", "ur": "پریناز (زنانہ نام)", "fa": "پریناز (نام زنانه)", "hi": "परीनाज़ (स्त्री नाम)", "ps": "پریناز (ښځينه نوم)", "ar": "بَرِينَاز (اسْم عَلَم فَارِسِيّ)"},
    "parisa": {"en": "Parisa; a female given name (Persian)", "ur": "پریسا (زنانہ نام)", "fa": "پریسا (نام زنانه)", "hi": "परीसा (स्त्री नाम)", "ps": "پریسا (ښځينه نوم)", "ar": "بَرِيسَا (اسْم عَلَم فَارِسِيّ)"},
    "parivash": {"en": "Parivash; a female given name (Persian)", "ur": "پریوش (زنانہ نام)", "fa": "پریوش (نام زنانه)", "hi": "परीवश (स्त्री नाम)", "ps": "پریوش (ښځينه نوم)", "ar": "بَرِيوَش (اسْم عَلَم فَارِسِيّ)"},
    "parla": {"en": "Parla; a female given name (Turkish)", "ur": "پارلا (زنانہ نام)", "fa": "پارلا (نام زنانه)", "hi": "पारला (स्त्री नाम)", "ps": "پارلا (ښځينه نوم)", "ar": "بَارْلَا (اسْم عَلَم تُرْكِيّ)"},
    "parmida": {"en": "Parmida; a female given name (Persian)", "ur": "پرمیدہ (زنانہ نام)", "fa": "پرمیدا (نام زنانه)", "hi": "परमीदा (स्त्री नाम)", "ps": "پرمیدا (ښځينه نوم)", "ar": "بَرْمِيدَا (اسْم عَلَم فَارِسِيّ)"},
    "parna": {"en": "Parna; a female given name (Persian)", "ur": "پرنا (زنانہ نام)", "fa": "پرنا (نام زنانه)", "hi": "परना (स्त्री नाम)", "ps": "پرنا (ښځينه نوم)", "ar": "بَرْنَا (اسْم عَلَم فَارِسِيّ)"},
    "parnia": {"en": "Parnia; a female given name (Persian)", "ur": "پرنیا (زنانہ نام)", "fa": "پرنیا (نام زنانه)", "hi": "परनिया (स्त्री नाम)", "ps": "پرنیا (ښځينه نوم)", "ar": "بَرْنِيَا (اسْم عَلَم فَارِسِيّ)"},
    "parsa": {"en": "Parsa; a male given name (Persian)", "ur": "پارسا (مردانہ نام)", "fa": "پارسا (نام مردانه)", "hi": "पारसा (पुरुष नाम)", "ps": "پارسا (نر نوم)", "ar": "بَارْسَا (اسْم عَلَم فَارِسِيّ)"},
    "parva": {"en": "Parva; a female given name (Persian)", "ur": "پروا (زنانہ نام)", "fa": "پروا (نام زنانه)", "hi": "परवा (स्त्री नाम)", "ps": "پروا (ښځينه نوم)", "ar": "بَرْوَا (اسْم عَلَم فَارِسِيّ)"},
    "parvana": {"en": "Parvana; butterfly (Persian)", "ur": "پروانہ، تتلی", "fa": "پروانه، پروانه", "hi": "परवाना, तितली", "ps": "پروانه، پتنګ", "ar": "بَرْوَانَة (الْفَرَاشَة)"},
    "parveen": {"en": "Parveen; the Pleiades (Persian)", "ur": "پروین، ثریا", "fa": "پروین، ثریا", "hi": "परवीन, कृत्तिका", "ps": "پروین، ثریا", "ar": "بَرْوِين (الثُّرَيَّا)"},
    "parvez": {"en": "Parvez; victorious (Persian)", "ur": "پرویز، فاتح", "fa": "پرویز، پیروز", "hi": "परवेज़, विजयी", "ps": "پرویز، بریالی", "ar": "بَرْوِيز (الْمُنْتَصِر)"},
    "parvin": {"en": "Parvin; the Pleiades (Persian)", "ur": "پروین، ثریا", "fa": "پروین، ثریا", "hi": "परवीन, कृत्तिका", "ps": "پروین، ثریا", "ar": "بَرْوِين (الثُّرَيَّا)"},
    "parwana": {"en": "Parwana; butterfly (Persian)", "ur": "پروانہ، تتلی", "fa": "پروانه، پروانه", "hi": "परवाना, तितली", "ps": "پروانه، پتنګ", "ar": "بَرْوَانَة (الْفَرَاشَة)"},
    "parwar": {"en": "Parwar; protector, caretaker (Persian)", "ur": "پرور، پالنے والا", "fa": "پرور، پرورش‌دهنده", "hi": "परवर, पालने वाला", "ps": "پرور، پالونکی", "ar": "بَرْوَر (الْحَافِظ)"},
    "parwaz": {"en": "Parwaz; flight, soaring (Persian)", "ur": "پرواز، اڑان", "fa": "پرواز، اوج", "hi": "परवाज़, उड़ान", "ps": "پرواز، الوتنه", "ar": "بَرْوَاز (الطَّيَرَان)"},
    "parween": {"en": "Parween; the Pleiades (Persian)", "ur": "پروین، ثریا", "fa": "پروین، ثریا", "hi": "परवीन, कृत्तिका", "ps": "پروین، ثریا", "ar": "بَرْوِين (الثُّرَيَّا)"},
    "parwez": {"en": "Parwez; victorious (Persian)", "ur": "پرویز، فاتح", "fa": "پرویز، پیروز", "hi": "परवेज़, विजयी", "ps": "پرویز، بریالی", "ar": "بَرْوِيز (الْمُنْتَصِر)"},
    "parwiz": {"en": "Parwiz; victorious (Persian)", "ur": "پرویز، فاتح", "fa": "پرویز، پیروز", "hi": "परवेज़, विजयी", "ps": "پرویز، بریالی", "ar": "بَرْوِيز (الْمُنْتَصِر)"},
    "pasha": {"en": "Pasha; a high Ottoman title", "ur": "پاشا، عثمانی خطاب", "fa": "پاشا، لقب عثمانی", "hi": "पाशा, उस्मानी उपाधि", "ps": "پاشا، عثماني لقب", "ar": "بَاشَا (لَقَب عُثْمَانِيّ)"},
    "payam": {"en": "Payam; message, news (Persian)", "ur": "پیام، پیغام، خبر", "fa": "پیام، خبر", "hi": "पयाम, संदेश", "ps": "پیام، پیغام", "ar": "بَيَام (الرِّسَالَة)"},
    "pegah": {"en": "Pegah; dawn (Persian)", "ur": "پگاہ، صبح", "fa": "پگاه، بامداد", "hi": "पेगाह, भोर", "ps": "پګاه، سهار", "ar": "بِگَاه (الْفَجْر)"},
    "pervaiz": {"en": "Pervaiz; victorious (Persian)", "ur": "پرویز، فاتح", "fa": "پرویز، پیروز", "hi": "परवेज़, विजयी", "ps": "پرویز، بریالی", "ar": "بَرْوِيز (الْمُنْتَصِر)"},
    "perveen": {"en": "Perveen; the Pleiades (Persian)", "ur": "پروین، ثریا", "fa": "پروین، ثریا", "hi": "परवीन, कृत्तिका", "ps": "پروین، ثریا", "ar": "بَرْوِين (الثُّرَيَّا)"},
    "peyman": {"en": "Peyman; covenant, pledge (Persian)", "ur": "پیمان، عہد، وعدہ", "fa": "پیمان، عهد", "hi": "पैमान, वचन", "ps": "پیمان، ژمنه", "ar": "بَيْمَان (الْعَهْد)"},
    "pinar": {"en": "Pinar; a female given name (Turkish)", "ur": "پنار (زنانہ نام)", "fa": "پینار (نام زنانه)", "hi": "पिनार (स्त्री नाम)", "ps": "پینار (ښځينه نوم)", "ar": "بِينَار (اسْم عَلَم تُرْكِيّ)"},
    "pir": {"en": "Pir; elder, spiritual guide (Persian)", "ur": "پیر، بزرگ، مرشد", "fa": "پیر، مرشد", "hi": "पीर, बुज़ुर्ग", "ps": "پیر، مشر", "ar": "بِير (الشَّيْخ، الْمُرْشِد)"},
})

CUR = {
 "nuhaa": ("نُهَى", "نہیٰ", "نهی", "नुहा", "نهی", "nuhaa", "Arabic", "Female",
           "Arabic root ن ه ي (n-h-y); نُهَى (Nuhā)", False, "high",
           "Nuhaa is Arabic نُهَى (Nuhā) 'intelligence, understanding', from the root ن ه ي (n-h-y). The source gloss 'Prophetess mentioned in the Quran' is unsupported and has been replaced with the lexical sense. Same name as nuha."),
 "nujood": ("نُجُود", "نجود", "نجود", "नजूद", "نجود", "nujood", "Arabic", "Female",
            "Arabic نُجُود (Nujūd)", False, "medium",
            "Nujood is recorded as Arabic نُجُود (Nujūd), a female given name. CRITICAL SOURCE ERROR: the source gave نوجود (a non-standard form). The source gloss 'Eloquent, Intelligent' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as nojood."),
 "nujum": ("نُجُوم", "نجوم", "نجوم", "नुजूम", "نجوم", "stars", "Arabic", "Female",
           "Arabic root ن ج م (n-j-m); نُجُوم (Nujūm)", False, "high",
           "Nujum is Arabic نُجُوم (Nujūm) 'stars', the plural of نَجْم (najm), from the root ن ج م (n-j-m). The source gloss 'Stars' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "numa": ("نُومَا", "نوما", "نوما", "नूमा", "نوما", "numa", "Arabic", "Female",
          "Arabic نُومَا (Nūmā)", False, "medium",
          "Numa is recorded as Arabic نُومَا (Nūmā), a female given name. The source gloss 'Rest' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "numaan": ("نُعْمَان", "نعمان", "نعمان", "नोमान", "نعمان", "naaman3", "Arabic", "Male",
            "Arabic نُعْمَان (Nuʿmān)", False, "high",
            "Numaan is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. The source gloss 'Reliever of Hardship' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "numan": ("نُعْمَان", "نعمان", "نعمان", "नोमान", "نعمان", "naaman3", "Arabic", "Male",
           "Arabic نُعْمَان (Nuʿmān)", False, "high",
           "Numan is a spelling variant of Arabic نُعْمَان (Nuʿmān), a male given name. The source gloss 'Blood, Red' is unsupported and has been replaced with the documented identification. Same name as naaman."),
 "nur": ("نُور", "نور", "نور", "नूर", "نور", "nur", "Arabic", "Female",
         "Arabic root ن و ر (n-w-r); نُور (Nūr)", False, "high",
         "Nur is Arabic نُور (Nūr) 'light, radiance', from the root ن و ر (n-w-r). The source gloss 'Light' is consistent. Same name as noor."),
 "nurah": ("نُورَة", "نورہ", "نوره", "नूरा", "نوره", "nurah", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
           "Nurah is Arabic نُورَة (Nūra) 'light' (feminine), from the root ن و ر (n-w-r). The source gloss 'Light' is consistent. Same name as noura."),
 "nurain": ("نُورَيْن", "نورین", "نورین", "नूरैन", "نورین", "nurain", "Arabic", "Female",
            "Arabic نُور (nūr) + dual ending", False, "high",
            "Nurain is Arabic نُورَيْن (Nūrayn) 'two lights', from نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. Same name as noorain."),
 "nuran": ("نُورَان", "نوران", "نوران", "नूरान", "نوران", "nuran", "Arabic", "Female",
           "Arabic نُور (nūr) + -ān", False, "high",
           "Nuran is Arabic نُورَان (Nūrān) 'full of light', from نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. Same name as nooran."),
 "nurani": ("نُورَانِي", "نورانی", "نورانی", "नूरानी", "نوراني", "nurani", "Arabic", "Female",
            "Arabic نُورَانِي (Nūrānī) 'luminous'", False, "high",
            "Nurani is Arabic نُورَانِي (Nūrānī) 'luminous, of light', a relational adjective from نُور (nūr). The source gloss 'Light, Enlightened' is consistent. Same name as noorani."),
 "nurat": ("نُورَة", "نورت", "نورت", "नूरत", "نورت", "nurat", "Arabic", "Female",
           "Arabic root ن و ر (n-w-r); نُورَة (Nūra)", False, "high",
           "Nurat is Arabic نُورَة (Nūra) 'light, radiance', from the root ن و ر (n-w-r). CRITICAL SOURCE ERROR: the source gave نُرَة (a non-standard form). The source gloss 'Light, Radiance' is consistent."),
 "nuray": ("نُورَاي", "نورے", "نورای", "नूरय", "نورې", "nuray", "Arabic", "Female",
           "Arabic نُور (nūr) + -ay", False, "high",
           "Nuray is Arabic نُورَاي (Nūrāy) 'light, radiance', from نُور (nūr) 'light'. The source gloss 'Light, radiance' is consistent."),
 "nureen": ("نُورِين", "نورین", "نورین", "नौरीन", "نورین", "nureen", "Arabic", "Female",
            "Arabic نُور (nūr) + feminine ending", False, "high",
            "Nureen is Arabic نُورِين (Nūrīn) 'light, luminous', from نُور (nūr) 'light'. The source gloss 'Light, Luminous' is consistent. Same name as naureen."),
 "nuri": ("نُورِي", "نوری", "نوری", "नूरी", "نوري", "nuri", "Arabic", "Male",
          "Arabic نُورِي (Nūrī) 'luminous'", False, "high",
          "Nuri is Arabic نُورِي (Nūrī) 'luminous, of light', a relational adjective from نُور (nūr). The source gloss 'Light' is broadly consistent."),
 "nuria": ("نُورِيَة", "نوریہ", "نوریه", "नूरिया", "نوریه", "nuria", "Arabic", "Female",
           "Arabic نُورِيَة (Nūriyya) 'luminous'", False, "high",
           "Nuria is Arabic نُورِيَة (Nūriyya) 'luminous, of light', from نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. Same name as nouria."),
 "nuril": ("نُورِل", "نورل", "نورل", "नूरिल", "نورل", "nuril", "Arabic", "Female",
           "Arabic نُور (nūr) + -il", False, "high",
           "Nuril is Arabic نُورِل (Nūril) 'light, enlightenment', from نُور (nūr) 'light'. The source gloss 'Light, Enlightenment' is consistent."),
 "nurin": ("نُورِين", "نورین", "نورین", "नूरीन", "نورین", "nurin", "Arabic", "Female",
           "Arabic نُور (nūr) + feminine ending", False, "high",
           "Nurin is Arabic نُورِين (Nūrīn) 'light, luminous', from نُور (nūr) 'light'. The source gloss 'Light of Faith' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as naureen."),
 "nurul": ("نُورُ الـ", "نور ال", "نور ال", "नूरुल", "نور ال", "nurul", "Arabic", "Male",
           "Arabic نُور (nūr) in construct with the article", False, "high",
           "Nurul is Arabic نُورُ الـ (Nūru l-) 'light of', a construct form of نُور (nūr) 'light'. The source gloss 'Light of God' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as noorul."),
 "nurun": ("نُورُن", "نورون", "نورون", "नूरुन", "نورون", "nurun", "Arabic", "Male",
           "Arabic نُور (nūr) in construct", False, "high",
           "Nurun is Arabic نُورُن (Nūrun) 'light of', a construct form of نُور (nūr) 'light'. The source gloss 'Light of God' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "nuryn": ("نُورِين", "نورین", "نورین", "नूरीन", "نورین", "nuryn", "Arabic", "Female",
           "Arabic نُور (nūr) + feminine ending", False, "high",
           "Nuryn is a spelling variant of Arabic نُورِين (Nūrīn) 'light, luminous', from نُور (nūr) 'light'. The source gloss 'Light' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as naureen."),
 "nusaiba": ("نُسَيْبَة", "نصیبہ", "نصیبه", "नुसैबा", "نصیبه", "nusaiba", "Arabic", "Female",
             "Arabic نُسَيْبَة (Nusayba)", False, "high",
             "Nusaiba is Arabic نُسَيْبَة (Nusayba), a female given name borne by a companion of the Prophet. The source gloss 'Support, Helper, Aid' is unsupported and has been replaced with the documented identification."),
 "nusaibah": ("نُسَيْبَة", "نصیبہ", "نصیبه", "नुसैबा", "نصیبه", "nusaibah", "Arabic", "Female",
              "Arabic نُسَيْبَة (Nusayba)", False, "high",
              "Nusaibah is Arabic نُسَيْبَة (Nusayba), a female given name. CRITICAL SOURCE ERROR: the source gave نسائبة (a non-standard form). The source gloss 'Giver of good news' is unsupported and has been replaced with the documented identification. Same name as nusaiba."),
 "nusha": ("نُوشَا", "نوشہ", "نوشا", "नुशा", "نوشا", "nusha", "Persian", "Female",
           "Persian نوشا (nūshā)", False, "medium",
           "Nusha is a Persian female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Restless, agitated' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nushad": ("نُوشَاد", "نوشاد", "نوشاد", "नुशाद", "نوشاد", "nushad", "Persian", "Male",
            "Persian نوشاد (naushād)", False, "high",
            "Nushad is Persian نوشاد (naushād) 'happy, joyful'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian. The source gloss 'Granted by Allah' is unsupported and has been replaced with the lexical sense. Same name as naushad."),
 "nusrat": ("نُصْرَة", "نصرت", "نصرت", "नुसरत", "نصرت", "nusrat", "Arabic", "Male",
            "Arabic root ن ص ر (n-ṣ-r); نُصْرَة (Nuṣra)", False, "high",
            "Nusrat is Arabic نُصْرَة (Nuṣra) 'help, victory', from the root ن ص ر (n-ṣ-r). The source gloss 'Help, Victory' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as nasrat."),
 "nusrath": ("نُصْرَة", "نصرت", "نصرت", "नुसरत", "نصرت", "nusrath", "Arabic", "Male",
             "Arabic root ن ص ر (n-ṣ-r); نُصْرَة (Nuṣra)", False, "high",
             "Nusrath is a spelling variant of Arabic نُصْرَة (Nuṣra) 'help, assistance', from the root ن ص ر (n-ṣ-r). The source gloss 'Help, Assistance' is consistent. Same name as nasrat."),
 "nuzha": ("نُزْهَة", "نزہہ", "نزهه", "नुज़हा", "نزهه", "nuzha", "Arabic", "Female",
           "Arabic root ن ز ه (n-z-h); نُزْهَة (Nuzha)", False, "high",
           "Nuzha is Arabic نُزْهَة (Nuzha) 'excursion, outing', from the root ن ز ه (n-z-h). The source gloss 'Journey, Excursion' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as nazha."),
 "nuzhat": ("نُزْهَة", "نزہت", "نزهت", "नुज़हत", "نزهت", "nuzhat", "Arabic", "Female",
            "Arabic root ن ز ه (n-z-h); نُزْهَة (Nuzha)", False, "high",
            "Nuzhat is Arabic نُزْهَة (Nuzha) 'excursion, outing', from the root ن ز ه (n-z-h). The source gloss 'Amusement, Entertainment' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "obaid": ("عُبَيْد", "عبید", "عبید", "उबैद", "عبید", "obaid", "Arabic", "Male",
           "Arabic root ع ب د (ʿ-b-d); عُبَيْد (ʿUbayd)", False, "high",
           "Obaid is Arabic عُبَيْد (ʿUbayd) 'little servant', the diminutive of عَبْد (ʿabd), from the root ع ب د (ʿ-b-d). The source gloss 'Servant' is broadly consistent."),
 "obaida": ("عُبَيْدَة", "عبیدہ", "عبیده", "उबैदा", "عبیده", "obaida", "Arabic", "Male",
            "Arabic root ع ب د (ʿ-b-d); عُبَيْدَة (ʿUbayda)", False, "high",
            "Obaida is Arabic عُبَيْدَة (ʿUbayda) 'little servant', from the root ع ب د (ʿ-b-d). The source gloss 'Brave, Lion' is unsupported and has been replaced with the lexical sense. Same name as obaidah."),
 "obaidah": ("عُبَيْدَة", "عبیدہ", "عبیده", "उबैदा", "عبیده", "obaidah", "Arabic", "Male",
             "Arabic root ع ب د (ʿ-b-d); عُبَيْدَة (ʿUbayda)", False, "high",
             "Obaidah is Arabic عُبَيْدَة (ʿUbayda) 'little servant', from the root ع ب د (ʿ-b-d). The source gloss 'Servant' is broadly consistent. Same name as obaida."),
 "oktai": ("أُوكْتَاي", "اوکتای", "اوکتای", "ओकताई", "اوکتای", "oktai", "Turkish", "Male",
           "Turkish Oktay", False, "medium",
           "Oktai is a Turkish male given name. CRITICAL SOURCE ERROR: the source gave أحمد (a different name) and labelled the origin Arabic; the name is Turkish. The source gloss 'Strong, Powerful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "olfat": ("أُلْفَت", "الفت", "الفت", "उलफ़त", "الفت", "olfat", "Arabic", "Female",
           "Arabic root أ ل ف (ʾ-l-f); أُلْفَت (Ulfat)", False, "high",
           "Olfat is Arabic أُلْفَت (Ulfat) 'familiarity, intimacy', from the root أ ل ف (ʾ-l-f). CRITICAL SOURCE ERROR: the source gave ألفات (a non-standard form). The source gloss 'Sweet Basil' is unsupported and has been replaced with the lexical sense."),
 "olka": ("أُولْكَا", "اولکا", "اولکا", "ओल्का", "اولکا", "olka", "Arabic", "Female",
          "Arabic أُولْكَا (Ūlkā)", False, "medium",
          "Olka is recorded as Arabic أُولْكَا (Ūlkā), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Olka' instead of a script form. The source gloss 'Small lake' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "omaid": ("أَمَل", "امید", "امید", "उम्मीद", "هیله", "omaid", "Arabic", "Male",
           "Arabic root أ م ل (ʾ-m-l); أَمَل (Amal)", False, "high",
           "Omaid is a spelling variant of Arabic أَمَل (Amal) 'hope, expectation', from the root أ م ل (ʾ-m-l). The source gloss 'Hope and Expectation' is consistent. Same name as omeed."),
 "omaima": ("أُمَيْمَة", "امیمہ", "امیمه", "उमैमा", "امیمه", "omaima", "Arabic", "Female",
            "Arabic أُمَيْمَة (Umayma)", False, "high",
            "Omaima is Arabic أُمَيْمَة (Umayma), a female given name. CRITICAL SOURCE ERROR: the source gave عويميا (a non-standard form). The source gloss 'Gentle, soft, or delicate' is unsupported and has been replaced with the documented identification."),
 "omair": ("عُمَيْر", "عمیر", "عمیر", "उमैर", "عمیر", "omair", "Arabic", "Male",
           "Arabic root ع م ر (ʿ-m-r); عُمَيْر (ʿUmayr)", False, "high",
           "Omair is Arabic عُمَيْر (ʿUmayr), a male given name, from the root ع م ر (ʿ-m-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root."),
 "omaira": ("عُمَيْرَة", "عمیرہ", "عمیره", "उमैरा", "عمیره", "omaira", "Arabic", "Female",
            "Arabic root ع م ر (ʿ-m-r); عُمَيْرَة (ʿUmayra)", False, "high",
            "Omaira is Arabic عُمَيْرَة (ʿUmayra), a female given name, from the root ع م ر (ʿ-m-r). CRITICAL SOURCE ERROR: the source gave أميرة (a different name); the correct form is عُمَيْرَة. The source gloss 'Life, Long Life' is unsupported and has been replaced with the documented identification."),
 "omama": ("أُمَامَة", "امامہ", "امامه", "उमामा", "امامه", "omama", "Arabic", "Female",
           "Arabic أُمَامَة (Umāma)", False, "high",
           "Omama is Arabic أُمَامَة (Umāma), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Omama' instead of a script form. The source gloss 'Mother of the Believers' is a historical association rather than a lexical sense."),
 "omar": ("عُمَر", "عمر", "عمر", "उमर", "عمر", "omar", "Arabic", "Male",
          "Arabic root ع م ر (ʿ-m-r); عُمَر (ʿUmar)", False, "high",
          "Omar is Arabic عُمَر (ʿUmar), a male given name, from the root ع م ر (ʿ-m-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the lexical root. Same name as omer."),
 "omaria": ("عُمَرِيَّة", "عمریہ", "عمریه", "उमरिया", "عمريه", "omaria", "Arabic", "Female",
            "Arabic عُمَرِيَّة (ʿUmariyya) 'of Omar'", False, "high",
            "Omaria is Arabic عُمَرِيَّة (ʿUmariyya) 'of Omar' (feminine), a relational adjective from عُمَر (ʿUmar). The source gloss 'Feminine form of Omar' is consistent."),
 "omeed": ("أَمَل", "امید", "امید", "उम्मीद", "هیله", "omeed", "Arabic", "Male",
           "Arabic root أ م ل (ʾ-m-l); أَمَل (Amal)", False, "high",
           "Omeed is a spelling variant of Arabic أَمَل (Amal) 'hope, expectation', from the root أ م ل (ʾ-m-l). The source gloss 'Prosperity, Happiness' is unsupported and has been replaced with the lexical sense. Same name as omaid."),
 "omer": ("عُمَر", "عمر", "عمر", "उमर", "عمر", "omer", "Arabic", "Male",
          "Arabic root ع م ر (ʿ-m-r); عُمَر (ʿUmar)", False, "high",
          "Omer is a spelling variant of Arabic عُمَر (ʿUmar), a male given name, from the root ع م ر (ʿ-m-r). The source gloss 'Long life' is broadly consistent. Same name as omar."),
 "omid": ("أُمِيد", "امید", "امید", "उम्मीद", "هیله", "omid", "Persian", "Male",
          "Persian امید (omīd)", False, "high",
          "Omid is Persian امید (omīd) 'hope'. CRITICAL SOURCE ERROR: the source gave علي (a different name) and labelled the origin Arabic; the word is Persian. The source gloss 'Hope' is consistent."),
 "omran": ("عِمْرَان", "عمران", "عمران", "उमरान", "عمران", "omran", "Arabic", "Male",
           "Arabic root ع م ر (ʿ-m-r); عِمْرَان (ʿImrān)", False, "high",
           "Omran is Arabic عِمْرَان (ʿImrān), a male given name, from the root ع م ر (ʿ-m-r). The source gloss 'Mountain man' is unsupported and has been replaced with the documented identification."),
 "ons": ("أُنْس", "انس", "انس", "उन्स", "انس", "ons", "Arabic", "Male",
         "Arabic root أ ن س (ʾ-n-s); أُنْس (Uns)", False, "high",
         "Ons is Arabic أُنْس (Uns) 'sociability, intimacy', from the root أ ن س (ʾ-n-s). The source gloss 'One, Unity, Gathering' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "orah": ("أُورَة", "اورہ", "اوره", "ओरा", "اوره", "orah", "Arabic", "Female",
          "Arabic أُورَة (Ūra)", False, "medium",
          "Orah is recorded as Arabic أُورَة (Ūra), a female given name. CRITICAL SOURCE ERROR: the source gave 'Unknown' instead of a script form. The source gloss 'Light, Radiance' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "oraib": ("عُرَيْب", "عریب", "عریب", "उरैब", "عریب", "oraib", "Arabic", "Male",
           "Arabic عُرَيْب (ʿUrayb)", False, "medium",
           "Oraib is recorded as Arabic عُرَيْب (ʿUrayb), a male given name. The source gloss 'Radiant, shining' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "orang": ("أُورَنْغ", "اورنگ", "اورنگ", "ओरंग", "اورنګ", "orang", "Malay", "Male",
           "Malay orang 'person'", False, "high",
           "Orang is a Malay male given name, from Malay orang 'person'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Orang' instead of a script form and labelled the origin Arabic; the word is Malay. The source gloss 'Orange Fruit' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "orhan": ("أُورْخَان", "اورخان", "اورخان", "ओरहान", "اورخان", "orhan", "Turkish", "Male",
           "Turkish Orhan", False, "high",
           "Orhan is a Turkish male given name. CRITICAL SOURCE ERROR: the source gave أورخان (a non-standard form) and labelled the origin Arabic; the name is Turkish. The source gloss 'Golden mountain' is unsupported and has been replaced with the documented identification. Same name as orkhan."),
 "orjun": ("أُورْجُن", "ارجن", "ارجن", "ओरजुन", "ارجن", "orjun", "Arabic", "Male",
           "Arabic أُورْجُن (Ūrjun)", False, "medium",
           "Orjun is recorded as Arabic أُورْجُن (Ūrjun), a male given name. CRITICAL SOURCE ERROR: the source gave أورج ن (a broken form). The source gloss 'Exalted, Noble' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "orkhan": ("أُورْخَان", "اورخان", "اورخان", "ओरखान", "اورخان", "orkhan", "Turkish", "Male",
            "Turkish Orhan", False, "high",
            "Orkhan is a Turkish/Azerbaijani male given name. CRITICAL SOURCE ERROR: the source gave أورخان (a non-standard form) and labelled the origin Arabic; the name is Turkish. The source gloss 'Man of Mountain' is unsupported and has been replaced with the documented identification. Same name as orhan."),
 "orna": ("أُورْنَا", "اورنا", "اورنا", "ओरना", "اورنا", "orna", "Arabic", "Female",
          "Arabic أُورْنَا (Ūrnā)", False, "medium",
          "Orna is recorded as Arabic أُورْنَا (Ūrnā), a female given name. CRITICAL SOURCE ERROR: the source gave 'Aisha' (a different name) instead of a script form. The source gloss 'Bright, Radiant' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "orwa": ("عُرْوَة", "عروہ", "عروه", "उरवा", "عروه", "orwa", "Arabic", "Male",
          "Arabic عُرْوَة (ʿUrwa)", False, "high",
          "Orwa is Arabic عُرْوَة (ʿUrwa), a male given name. CRITICAL SOURCE ERROR: the source gave أروى (a different name); the correct form is عُرْوَة. The source gloss 'Lion' is unsupported and has been replaced with the documented identification."),
 "osama": ("أُسَامَة", "اسامہ", "اسامه", "उसामा", "اسامه", "osama", "Arabic", "Male",
           "Arabic أُسَامَة (Usāma)", False, "high",
           "Osama is Arabic أُسَامَة (Usāma), a male given name. CRITICAL SOURCE ERROR: the source gave عثامة (a different form); the correct form is أُسَامَة. The source gloss 'Living man' is unsupported and has been replaced with the documented identification. Same name as osamah."),
 "osamaa": ("أُسَامَة", "اسامہ", "اسامه", "उसामा", "اسامه", "osamaa", "Arabic", "Male",
            "Arabic أُسَامَة (Usāma)", False, "high",
            "Osamaa is a spelling variant of Arabic أُسَامَة (Usāma), a male given name. CRITICAL SOURCE ERROR: the source gave أسامہ (a non-standard form) and labelled the gender female; documented usage is predominantly male. The source gloss 'Life, Tender' is unsupported and has been replaced with the documented identification. Same name as osamah."),
 "osamah": ("أُسَامَة", "اسامہ", "اسامه", "उसामा", "اسامه", "osamah", "Arabic", "Male",
            "Arabic أُسَامَة (Usāma)", False, "high",
            "Osamah is Arabic أُسَامَة (Usāma), a male given name. The source gloss 'Lion of God' is unsupported and has been replaced with the documented identification. Same name as osama."),
 "osman": ("عُثْمَان", "عثمان", "عثمان", "उस्मान", "عثمان", "osman", "Arabic", "Male",
           "Arabic عُثْمَان (ʿUthmān)", False, "high",
           "Osman is Arabic عُثْمَان (ʿUthmān), a male given name borne by the third caliph. The source gloss 'Praiseworthy' is unsupported and has been replaced with the documented identification. Same name as othmane."),
 "osmanli": ("الْعُثْمَانِي", "عثمانی", "عثمانی", "उस्मानली", "عثماني", "osmanli", "Arabic", "Male",
             "Arabic الْعُثْمَانِي (al-ʿUthmānī) 'Ottoman'", False, "high",
             "Osmanli is Arabic الْعُثْمَانِي (al-ʿUthmānī) 'Ottoman', a relational adjective from عُثْمَان (ʿUthmān). The source gloss 'Ottoman Empire' is a state name rather than a lexical sense."),
 "ossama": ("أُسَامَة", "اسامہ", "اسامه", "उसामा", "اسامه", "ossama", "Arabic", "Male",
            "Arabic أُسَامَة (Usāma)", False, "high",
            "Ossama is a spelling variant of Arabic أُسَامَة (Usāma), a male given name. CRITICAL SOURCE ERROR: the source gave عُصَمَةُ (a different form); the correct form is أُسَامَة. The source gloss 'Success' is unsupported and has been replaced with the documented identification. Same name as osama."),
 "othmane": ("عُثْمَان", "عثمان", "عثمان", "उस्मान", "عثمان", "othmane", "Arabic", "Male",
             "Arabic عُثْمَان (ʿUthmān)", False, "high",
             "Othmane is a Maghrebi spelling of Arabic عُثْمَان (ʿUthmān), a male given name. The source gloss 'Supporter of the weak' is unsupported and has been replaced with the documented identification. Same name as osman."),
 "oula": ("أُولَى", "اولیٰ", "اولی", "औला", "اولی", "oula", "Arabic", "Female",
          "Arabic أُولَى (Ūlā)", False, "medium",
          "Oula is recorded as Arabic أُولَى (Ūlā), a female given name. CRITICAL SOURCE ERROR: the source gave 'Unknown' instead of a script form. The source gloss 'Light, Illumination' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "owais": ("أُوَيْس", "اویس", "اویس", "औवैस", "اویس", "owais", "Arabic", "Male",
           "Arabic أُوَيْس (Uways)", False, "high",
           "Owais is Arabic أُوَيْس (Uways), a male given name borne by a companion of the Prophet. The source gloss 'Little Wolf' is unsupported and has been replaced with the documented identification."),
 "ozge": ("أُوزْغَة", "اوزگے", "اوزگه", "ओज़्गे", "اوزګه", "ozge", "Turkish", "Female",
          "Turkish Özge", False, "high",
          "Ozge is a Turkish female given name (Özge). CRITICAL SOURCE ERROR: the source gave أوزغه (a non-standard form) and labelled the origin Arabic; the name is Turkish. The source gloss 'Gift of God' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "ozhan": ("أُوزْهَان", "اوزہان", "اوزهان", "ओज़हान", "اوزهان", "ozhan", "Turkish", "Male",
           "Turkish Özhan", False, "high",
           "Ozhan is a Turkish male given name (Özhan). CRITICAL SOURCE ERROR: the source gave أحمد (a different name) and labelled the origin Arabic; the name is Turkish. The source gloss 'brave lion' is unsupported and has been replaced with the documented identification."),
 "ozra": ("عَذْرَاء", "عذرا", "عذرا", "उज़रा", "عذرا", "ozra", "Arabic", "Female",
          "Arabic عَذْرَاء (ʿAdhrāʾ)", False, "high",
          "Ozra is Arabic عَذْرَاء (ʿAdhrāʾ), a female given name. CRITICAL SOURCE ERROR: the source gave 'Ali' (a different name) instead of a script form. The source gloss 'Light, Radiant' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "palwasha": ("بَلْوَشَة", "پلوشہ", "پلوشه", "पलवाशा", "پلوشه", "palwasha", "Pashto", "Female",
              "Pashto پلوشه (palwasha)", False, "high",
              "Palwasha is a Pashto female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Palwasha' instead of a script form and labelled the origin Arabic; the name is Pashto. The source gloss 'Jewel, precious one' is unsupported and has been replaced with the documented identification."),
 "pamir": ("بَامِير", "پامیر", "پامیر", "पामीर", "پامیر", "pamir", "Persian", "Male",
           "Persian پامیر (pāmīr)", False, "high",
           "Pamir is a Persian male given name (also a mountain range). CRITICAL SOURCE ERROR: the source gave the Latin string 'Pamir' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'High, noble' is unsupported and has been replaced with the documented identification. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "pania": ("بَانِيَة", "پانیہ", "پانیا", "पानिया", "پانیا", "pania", "Arabic", "Female",
           "Arabic بَانِيَة (Bāniya)", False, "medium",
           "Pania is recorded as Arabic بَانِيَة (Bāniya), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Pania' instead of a script form. The source gloss 'Divine Grace' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "parastoo": ("بَرَسْتُو", "پرستو", "پرستو", "परस्तू", "پرستو", "parastoo", "Persian", "Female",
              "Persian پرستو (parastū)", False, "high",
              "Parastoo is Persian پرستو (parastū) 'swallow'. CRITICAL SOURCE ERROR: the source gave بارستو (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Butterfly' is unsupported and has been replaced with the lexical sense. Same name as parastu."),
 "parastu": ("بَرَسْتُو", "پرستو", "پرستو", "परस्तू", "پرستو", "parastu", "Persian", "Female",
             "Persian پرستو (parastū)", False, "high",
             "Parastu is Persian پرستو (parastū) 'swallow'. CRITICAL SOURCE ERROR: the source gave أحمد (a different name) and labelled the origin Arabic; the word is Persian. The source gloss 'Protector' is unsupported and has been replaced with the lexical sense. Same name as parastoo."),
 "paria": ("بَرِيَا", "پریا", "پریا", "परिया", "پریا", "paria", "Persian", "Female",
           "Persian پریا (pariyā)", False, "high",
           "Paria is Persian پریا (pariyā), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Paria' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Butterfly' is unsupported and has been replaced with the documented identification."),
 "parinaz": ("بَرِينَاز", "پریناز", "پریناز", "परीनाज़", "پریناز", "parinaz", "Persian", "Female",
             "Persian پریناز (parīnāz)", False, "high",
             "Parinaz is Persian پریناز (parīnāz), a female given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the name is Persian. The source gloss 'Light, Bright' is unsupported and has been replaced with the documented identification."),
 "parisa": ("بَرِيسَا", "پریسا", "پریسا", "परीसा", "پریسا", "parisa", "Persian", "Female",
            "Persian پریسا (parīsā)", False, "high",
            "Parisa is Persian پریسا (parīsā), a female given name. CRITICAL SOURCE ERROR: the source gave the placeholder 'عربي_Parisa'; the correct form is بَرِيسَا. The source gloss 'Noble and blessed' is unsupported and has been replaced with the documented identification."),
 "parivash": ("بَرِيوَش", "پریوش", "پریوش", "परीवश", "پریوش", "parivash", "Persian", "Female",
              "Persian پریوش (parivash)", False, "high",
              "Parivash is Persian پریوش (parivash), a female given name. CRITICAL SOURCE ERROR: the source gave 'Ahmad' (a different name) instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Gentle Breeze' is unsupported and has been replaced with the documented identification."),
 "parla": ("بَارْلَا", "پارلا", "پارلا", "पारला", "پارلا", "parla", "Turkish", "Female",
           "Turkish Parla", False, "medium",
           "Parla is a Turkish female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parla' instead of a script form and labelled the origin Arabic; the name is Turkish. The source gloss 'Lotus flower' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "parmida": ("بَرْمِيدَا", "پرمیدہ", "پرمیدا", "परमीदा", "پرمیدا", "parmida", "Persian", "Female",
             "Persian پرمیدا (parmīdā)", False, "medium",
             "Parmida is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parmida' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'The Fragrant Garden' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "parna": ("بَرْنَا", "پرنا", "پرنا", "परना", "پرنا", "parna", "Persian", "Female",
           "Persian پرنا (parnā)", False, "medium",
           "Parna is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parna' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Lotus' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "parnia": ("بَرْنِيَا", "پرنیا", "پرنیا", "परनिया", "پرنیا", "parnia", "Persian", "Female",
            "Persian پرنیا (parniyā)", False, "medium",
            "Parnia is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parnia' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Gift of God' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "parsa": ("بَارْسَا", "پارسا", "پارسا", "पारसा", "پارسا", "parsa", "Persian", "Male",
           "Persian پارسا (pārsā)", False, "high",
           "Parsa is Persian پارسا (pārsā) 'pious, virtuous'. CRITICAL SOURCE ERROR: the source gave بارسا (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Basket' is unsupported and has been replaced with the lexical sense."),
 "parva": ("بَرْوَا", "پروا", "پروا", "परवा", "پروا", "parva", "Persian", "Female",
           "Persian پروا (parvā)", False, "medium",
           "Parva is a Persian female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parva' instead of a script form and labelled the origin Arabic; the name is Persian. The source gloss 'Maiden, young girl' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "parvana": ("بَرْوَانَة", "پروانہ", "پروانه", "परवाना", "پروانه", "parvana", "Persian", "Female",
             "Persian پروانه (parvāna)", False, "high",
             "Parvana is Persian پروانه (parvāna) 'butterfly'. CRITICAL SOURCE ERROR: the source gave فروھانة (a different form) and labelled the origin Arabic; the word is Persian. The source gloss 'Maiden, Lady' is unsupported and has been replaced with the lexical sense. Same name as parwana."),
 "parveen": ("بَرْوِين", "پروین", "پروین", "परवीन", "پروین", "parveen", "Persian", "Female",
             "Persian پروین (parvīn)", False, "high",
             "Parveen is Persian پروین (parvīn) 'the Pleiades'. CRITICAL SOURCE ERROR: the source gave بارفين (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Moonlight' is unsupported and has been replaced with the lexical sense. Same name as parvin."),
 "parvez": ("بَرْوِيز", "پرویز", "پرویز", "परवेज़", "پرویز", "parvez", "Persian", "Male",
            "Persian پرویز (parvīz)", False, "high",
            "Parvez is Persian پرویز (parvīz) 'victorious'. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as parwez."),
 "parvin": ("بَرْوِين", "پروین", "پروین", "परवीन", "پروین", "parvin", "Persian", "Female",
            "Persian پروین (parvīn)", False, "high",
            "Parvin is Persian پروین (parvīn) 'the Pleiades'. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the word is Persian. The source gloss 'Meadow, Garden' is unsupported and has been replaced with the lexical sense. Same name as parveen."),
 "parwana": ("بَرْوَانَة", "پروانہ", "پروانه", "परवाना", "پروانه", "parwana", "Persian", "Female",
             "Persian پروانه (parvāna)", False, "high",
             "Parwana is Persian پروانه (parvāna) 'butterfly'. CRITICAL SOURCE ERROR: the source gave بروانة (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Butterfly' is consistent. Same name as parvana."),
 "parwar": ("بَرْوَر", "پرور", "پرور", "परवर", "پرور", "parwar", "Persian", "Male",
            "Persian پرور (parvar)", False, "high",
            "Parwar is Persian پرور (parvar) 'protector, caretaker'. CRITICAL SOURCE ERROR: the source gave باروار (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Protector, Caretaker' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "parwaz": ("بَرْوَاز", "پرواز", "پرواز", "परवाज़", "پرواز", "parwaz", "Persian", "Male",
            "Persian پرواز (parvāz)", False, "high",
            "Parwaz is Persian پرواز (parvāz) 'flight, soaring'. CRITICAL SOURCE ERROR: the source gave براوز (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Traveler, Soarer, Skyward' is broadly consistent."),
 "parween": ("بَرْوِين", "پروین", "پروین", "परवीन", "پروین", "parween", "Persian", "Female",
             "Persian پروین (parvīn)", False, "high",
             "Parween is Persian پروین (parvīn) 'the Pleiades'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parween' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Meadow' is unsupported and has been replaced with the lexical sense. Same name as parvin."),
 "parwez": ("بَرْوِيز", "پرویز", "پرویز", "परवेज़", "پرویز", "parwez", "Persian", "Male",
            "Persian پرویز (parvīz)", False, "high",
            "Parwez is Persian پرویز (parvīz) 'victorious'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Parwez' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Brave, Strong' is unsupported and has been replaced with the lexical sense. Same name as parvez."),
 "parwiz": ("بَرْوِيز", "پرویز", "پرویز", "परवेज़", "پرویز", "parwiz", "Persian", "Male",
            "Persian پرویز (parvīz)", False, "high",
            "Parwiz is Persian پرویز (parvīz) 'victorious'. CRITICAL SOURCE ERROR: the source gave بارويز (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Traveler, Seeker' is unsupported and has been replaced with the lexical sense. Same name as parvez."),
 "pasha": ("بَاشَا", "پاشا", "پاشا", "पाशा", "پاشا", "pasha", "Turkish", "Male",
           "Turkish paşa, from Ottoman Turkish", False, "high",
           "Pasha is a Turkish title (paşa) used as a male given name. CRITICAL SOURCE ERROR: the source gave باشا (a non-standard form) and labelled the origin Arabic; the title is Turkish/Ottoman. The source gloss 'Governor, leader' is broadly consistent."),
 "payam": ("بَيَام", "پیام", "پیام", "पयाम", "پیام", "payam", "Persian", "Male",
           "Persian پیام (payām)", False, "high",
           "Payam is Persian پیام (payām) 'message, news'. CRITICAL SOURCE ERROR: the source gave بيام (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Message, News' is consistent."),
 "pegah": ("بِگَاه", "پگاہ", "پگاه", "पेगाह", "پګاه", "pegah", "Persian", "Female",
           "Persian پگاه (pegāh)", False, "high",
           "Pegah is Persian پگاه (pegāh) 'dawn'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Pegah' instead of a script form and labelled the origin Arabic; the word is Persian. The source gloss 'Dove, Bird' is unsupported and has been replaced with the lexical sense."),
 "pervaiz": ("بَرْوِيز", "پرویز", "پرویز", "परवेज़", "پرویز", "pervaiz", "Persian", "Male",
             "Persian پرویز (parvīz)", False, "high",
             "Pervaiz is Persian پرویز (parvīz) 'victorious'. CRITICAL SOURCE ERROR: the source gave برويز (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Conqueror, Victorious' is broadly consistent. Same name as parvez."),
 "perveen": ("بَرْوِين", "پروین", "پروین", "परवीन", "پروین", "perveen", "Persian", "Female",
             "Persian پروین (parvīn)", False, "high",
             "Perveen is Persian پروین (parvīn) 'the Pleiades'. CRITICAL SOURCE ERROR: the source gave فروان (a different form) and labelled the origin Arabic; the word is Persian. The source gloss 'Seer, Observer' is unsupported and has been replaced with the lexical sense. Same name as parvin."),
 "peyman": ("بَيْمَان", "پیمان", "پیمان", "पैमान", "پیمان", "peyman", "Persian", "Male",
            "Persian پیمان (peymān)", False, "high",
            "Peyman is Persian پیمان (peymān) 'covenant, pledge'. CRITICAL SOURCE ERROR: the source gave بيامان (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Reliable, Trustworthy, Protector' is unsupported and has been replaced with the lexical sense."),
 "pinar": ("بِينَار", "پنار", "پینار", "पिनार", "پینار", "pinar", "Turkish", "Female",
           "Turkish Pınar", False, "high",
           "Pinar is a Turkish female given name (Pınar). CRITICAL SOURCE ERROR: the source gave the Latin string 'Pinar' instead of a script form and labelled the origin Arabic; the name is Turkish. The source gloss 'pine tree' is unsupported and has been replaced with the documented identification."),
 "pir": ("بِير", "پیر", "پیر", "पीर", "پیر", "pir", "Persian", "Male",
         "Persian پیر (pīr)", False, "high",
         "Pir is Persian پیر (pīr) 'elder, spiritual guide'. CRITICAL SOURCE ERROR: the source gave بير (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Sea explorer' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
}
