# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 2 (aamilah..aaus).

Every entry records ONLY what can be defended. `conf` is the honest confidence in the
lexical identification. `unverified` means the form could not be matched to a Tier-A/B
source and NO gloss is asserted (the record says so explicitly).

Fields: ar, ur, fa, hi, ps  -> script forms (None = not established for that language)
        gloss -> key into GLOSSES (None = no verified gloss)
        origin, gender, root, quranic, conf, note
"""

GLOSSES = {
    "trustworthy": {
        "en": "Trustworthy, faithful, honest",
        "ur": "قابلِ اعتماد، وفادار، دیانتدار",
        "fa": "قابل اعتماد، وفادار، امین",
        "hi": "विश्वसनीय, ईमानदार, वफ़ादार",
        "ps": "باور وړ، وفادار، امانتدار",
        "ar": "أمين، موثوق، مخلص",
    },
    "prosperous": {
        "en": "Inhabited, flourishing, prosperous",
        "ur": "آباد، خوشحال، پھلتا پھولتا",
        "fa": "آباد، شکوفا، مرفه",
        "hi": "आबाद, समृद्ध, फलता-फूलता",
        "ps": "آباد، سمسور، پرمختللی",
        "ar": "عامر، مأهول، مزدهر",
    },
    "safe": {
        "en": "Safe, secure, free from fear",
        "ur": "محفوظ، بے خوف، امن والی",
        "fa": "ایمن، در امان، بی‌بیم",
        "hi": "सुरक्षित, निर्भय, अमन वाली",
        "ps": "خوندي، بې وېرې، په امن",
        "ar": "آمنة، سالمة، مطمئنة",
    },
    "knowledgeable": {
        "en": "Knowing, aware, learned",
        "ur": "جاننے والا، واقف، عالم",
        "fa": "آگاه، دانا، عالم",
        "hi": "जानकार, विद्वान, आगाह",
        "ps": "پوه، خبردار، عالم",
        "ar": "عارف، عليم، خبير",
    },
    "wise": {
        "en": "Wise, intelligent, prudent",
        "ur": "عقلمند، دانا، ہوشیار",
        "fa": "خردمند، دانا، هوشیار",
        "hi": "बुद्धिमान, समझदार, विवेकी",
        "ps": "عقلمند، پوه، هوښیار",
        "ar": "عاقل، حكيم، لبيب",
    },
    "noble": {
        "en": "Noble, honourable, exalted",
        "ur": "نجیب، شریف، بلند",
        "fa": "نجیب، شریف، والا",
        "hi": "कुलीन, शरीफ़, उच्च",
        "ps": "نجیب، شریف، لوړ",
        "ar": "نبيل، شريف، رفيع",
    },
    "helper": {
        "en": "Helper, supporter, protector",
        "ur": "مددگار، حامی، ناصر",
        "fa": "یاریگر، پشتیبان",
        "hi": "सहायक, मददगार, रक्षक",
        "ps": "مرستندوی، ملاتړی",
        "ar": "ناصر، معين، حامي",
    },
    "fragrant": {
        "en": "Fragrant, perfumed, scented",
        "ur": "خوشبودار، معطر",
        "fa": "خوشبو، معطر",
        "hi": "सुगंधित, खुशबूदार",
        "ps": "خوشبویه، معطر",
        "ar": "عاطر، عطري، طيب",
    },
    "hope": {
        "en": "Hope, wish, longing",
        "ur": "امید، آرزو، تمنا",
        "fa": "امید، آرزو",
        "hi": "आशा, उम्मीद, अभिलाषा",
        "ps": "هیله، ارمان",
        "ar": "أمل، رجاء، منية",
    },
    "graceful": {
        "en": "Graceful, elegant, gentle",
        "ur": "خوبصورت، نازک، مہربان",
        "fa": "زیبا، لطیف، مهربان",
        "hi": "सुंदर, कोमल, सौम्य",
        "ps": "ښکلی، نرم، مهربان",
        "ar": "لطيف، جميل، رقيق",
    },
    "friendly": {
        "en": "Friendly, sociable, companionable",
        "ur": "خوش مزاج، ملنسار، مانوس",
        "fa": "خوش‌مشرب، انس‌گیر",
        "hi": "मिलनसार, स्नेही, अनुकूल",
        "ps": "خوږ، ملګری، انس",
        "ar": "أنيس، ودود، مؤنس",
    },
    "devoted": {
        "en": "Devoted, steadfast, staying",
        "ur": "لگن والا، قائم، مقیم",
        "fa": "پایدار، مقیم، کوشا",
        "hi": "तत्पर, स्थिर, लगन वाला",
        "ps": "ثابت، مېشت، کوښښګر",
        "ar": "عاكف، ملازم، مواظب",
    },
    "successor": {
        "en": "Successor, follower, one who comes after",
        "ur": "جانشین، پیرو، بعد میں آنے والا",
        "fa": "جانشین، پیرو، پس‌آیند",
        "hi": "उत्तराधिकारी, अनुयायी, बाद वाला",
        "ps": "ځای ناستی، پیرو، وروسته راتلونکی",
        "ar": "عاقب، تابع، خلف",
    },
    "outcome": {
        "en": "Consequence, outcome, result",
        "ur": "نتیجہ، انجام، عاقبت",
        "fa": "نتیجه، سرانجام، عاقبت",
        "hi": "परिणाम, अंजाम, नतीजा",
        "ps": "پایله، انجام، عاقبت",
        "ar": "عاقبة، نتيجة، مآل",
    },
    "heights": {
        "en": "Heights, elevated places, summits",
        "ur": "بلندیاں، اونچائیاں، چوٹیاں",
        "fa": "بلندی‌ها، فرازها، قله‌ها",
        "hi": "ऊँचाइयाँ, शिखर, बुलंदियाँ",
        "ps": "لوړوالي، سرونه، پوړونه",
        "ar": "أعراف، مرتفعات، ذرى",
    },
    "exalted": {
        "en": "Exalted, elevated, high in rank",
        "ur": "بلند، سرفراز، رفعت والا",
        "fa": "والا، بلندمرتبه، فرازمند",
        "hi": "उन्नत, बुलंद, ऊँचा",
        "ps": "لوړ، پورته، ستر",
        "ar": "مرفوع، رفيع، عليّ",
    },
    "worker": {
        "en": "Doer, worker, one who acts",
        "ur": "کرنے والا، عامل، کام کرنے والا",
        "fa": "کننده، کارگر، عمل‌کننده",
        "hi": "करने वाला, कर्मी, कार्यकर्ता",
        "ps": "کوونکی، کارکوونکی، عامل",
        "ar": "عامل، فاعل، فعّال",
    },
    "light": {
        "en": "Light, radiance, brightness",
        "ur": "روشنی، نور، چمک",
        "fa": "روشنایی، نور، فروغ",
        "hi": "रोशनी, नूर, चमक",
        "ps": "روښانه، رڼا، نور",
        "ar": "نور، ضياء، إشراق",
    },
    "gift": {
        "en": "Gift, bestowal, favour",
        "ur": "تحفہ، عطیہ، بخشش",
        "fa": "هدیه، بخشش، عطا",
        "hi": "उपहार, भेंट, दान",
        "ps": "ډالۍ، بخښنه، عطا",
        "ar": "عطاء، هدية، منحة",
    },
    "praise": {
        "en": "Praise, commendation, thanks",
        "ur": "تعریف، حمد، شکر",
        "fa": "ستایش، حمد، سپاس",
        "hi": "प्रशंसा, स्तुति, शुक्र",
        "ps": "ستاینه، حمد، مننه",
        "ar": "حمد، ثناء، شكر",
    },
    "servant": {
        "en": "Servant, devoted worshipper",
        "ur": "بندہ، خادم، عبادت گزار",
        "fa": "بنده، خدمتگزار، پرستنده",
        "hi": "दास, सेवक, उपासक",
        "ps": "بنده، خدمتګار، عبادت کوونکی",
        "ar": "عبد، خادم، عابد",
    },
    "lover": {
        "en": "Lover, devoted admirer, passionate one",
        "ur": "عاشق، محبت کرنے والا، شیدائی",
        "fa": "عاشق، دلبسته، شیفته",
        "hi": "आशिक़, प्रेमी, अनुरागी",
        "ps": "عاشق، مینه والا، شیدا",
        "ar": "عاشق، محب، مغرم",
    },
    "companion": {
        "en": "Companion, associate, comrade",
        "ur": "ساتھی، رفیق، ہم نشین",
        "fa": "همراه، رفیق، هم‌نشین",
        "hi": "साथी, रफ़ीक़, हमनशीं",
        "ps": "ملګری، رفیق، همسفر",
        "ar": "صاحب، رفيق، قرين",
    },
    "pure": {
        "en": "Pure, unblemished, sincere",
        "ur": "پاک، بے عیب، مخلص",
        "fa": "پاک، بی‌عیب، خالص",
        "hi": "पवित्र, निर्मल, शुद्ध",
        "ps": "پاک، بې عیب، خالص",
        "ar": "طاهر، نقي، خالص",
    },
    "dawn": {
        "en": "Dawn, daybreak, first light",
        "ur": "صبح، طلوع، سپیدہ",
        "fa": "سپیده، بامداد، طلوع",
        "hi": "भोर, सुबह, उषा",
        "ps": "سهار، سپیده، لمر خاته",
        "ar": "فجر، صباح، إشراق",
    },
    "moon": {
        "en": "Moon, moonlight",
        "ur": "چاند، قمر، مہتاب",
        "fa": "ماه، مهتاب، قمر",
        "hi": "चाँद, चंद्र, महताब",
        "ps": "سپوږمۍ، قمر، مهتاب",
        "ar": "قمر، هلال، بدر",
    },
    "star": {
        "en": "Star, celestial body",
        "ur": "ستارہ، نجم، تارا",
        "fa": "ستاره، نجم، اختر",
        "hi": "तारा, सितारा, नक्षत्र",
        "ps": "ستوری، نجم، اختر",
        "ar": "نجم، كوكب، ثريا",
    },
    "flower": {
        "en": "Flower, blossom, bloom",
        "ur": "پھول، گل، شگوفہ",
        "fa": "گل، شکوفه، بهار",
        "hi": "फूल, पुष्प, कली",
        "ps": "ګل، شکوفه، پوپنځ",
        "ar": "زهرة، وردة، نوار",
    },
    "rain": {
        "en": "Rain, rainfall, clouds",
        "ur": "بارش، مینہ، بادل",
        "fa": "باران، بارش، ابر",
        "hi": "वर्षा, बारिश, बादल",
        "ps": "باران، ورښت، وريځ",
        "ar": "مطر، غيث، سحاب",
    },
    "joy": {
        "en": "Joy, happiness, delight",
        "ur": "خوشی، مسرت، شادمانی",
        "fa": "شادی، خوشی، سرور",
        "hi": "खुशी, आनंद, प्रसन्नता",
        "ps": "خوښي، مینه، شادماني",
        "ar": "فرح، سرور، بهجة",
    },
    "strength": {
        "en": "Strength, firmness, resolve",
        "ur": "طاقت، مضبوطی، قوت",
        "fa": "توان، استواری، قدرت",
        "hi": "शक्ति, मज़बूती, बल",
        "ps": "ځواک، ټینګښت، قوت",
        "ar": "قوة، شدة، متانة",
    },
    "generous": {
        "en": "Generous, bountiful, open-handed",
        "ur": "سخی، فیاض، دریا دل",
        "fa": "بخشنده، سخاوتمند، کریم",
        "hi": "उदार, दानवीर, सख़ी",
        "ps": "سخي، لاس پراخ، کریم",
        "ar": "كريم، جواد، سخي",
    },
    "patient": {
        "en": "Patient, enduring, steadfast",
        "ur": "صابر، برداشت والا، ثابت قدم",
        "fa": "شکیبا، بردبار، پایدار",
        "hi": "धैर्यवान, सब्र करने वाला, स्थिर",
        "ps": "صابر، زغم لرونکی، ثابت",
        "ar": "صابر، حليم، صبور",
    },
    "truthful": {
        "en": "Truthful, honest, sincere",
        "ur": "سچا، راست باز، مخلص",
        "fa": "راستگو، صادق، درست‌کار",
        "hi": "सच्चा, सत्यवादी, ईमानदार",
        "ps": "رښتونی، صادق، ایماندار",
        "ar": "صادق، صديق، أمين",
    },
    "beautiful": {
        "en": "Beautiful, lovely, comely",
        "ur": "خوبصورت، حسین، دلکش",
        "fa": "زیبا، دل‌ربا، خوش‌رو",
        "hi": "सुंदर, हसीन, मनोहर",
        "ps": "ښکلی، زړه راښکونکی، حسین",
        "ar": "جميل، حسن، بديع",
    },
    "first": {
        "en": "First, foremost, earliest",
        "ur": "پہلا، اول، سب سے پہلے",
        "fa": "نخست، اول، پیشین",
        "hi": "पहला, प्रथम, अव्वल",
        "ps": "لومړی، اول، پخوا",
        "ar": "أول، سابق، متقدم",
    },
    "honey": {
        "en": "Honey, sweet substance",
        "ur": "شہد، عسل، انگبین",
        "fa": "عسل، شهد، انگبین",
        "hi": "शहद, मधु, अमृत",
        "ps": "شات، عسل، ګلاب",
        "ar": "عسل، شهد، رحيق",
    },
    "lion": {
        "en": "Lion, brave one",
        "ur": "شیر، ببر، دلیر",
        "fa": "شیر، دلیر، ببر",
        "hi": "शेर, सिंह, बहादुर",
        "ps": "زمری، شیر، زړور",
        "ar": "أسد، ليث، ضرغام",
    },
    "mountain": {
        "en": "Mountain, highland",
        "ur": "پہاڑ، کوہ، جبل",
        "fa": "کوه، کوهستان، جبل",
        "hi": "पहाड़, पर्वत, गिरि",
        "ps": "غر، کوه، جبل",
        "ar": "جبل، طور، راسي",
    },
    "garden": {
        "en": "Garden, orchard, paradise",
        "ur": "باغ، گلشن، جنت",
        "fa": "باغ، گلستان، بوستان",
        "hi": "बाग़, उपवन, बगीचा",
        "ps": "باغ، بڼ، جنت",
        "ar": "جنة، حديقة، روضة",
    },
    "water": {
        "en": "Water, spring, living water",
        "ur": "پانی، آب، چشمہ",
        "fa": "آب، چشمه، آب روان",
        "hi": "पानी, जल, आब",
        "ps": "اوبه، آب، چینه",
        "ar": "ماء، عين، نهر",
    },
    "fish": {
        "en": "Fish",
        "ur": "مچھلی، ماہی",
        "fa": "ماهی",
        "hi": "मछली, मत्स्य",
        "ps": "کب، ماهي",
        "ar": "سمك، حوت، نون",
    },
    "cloud": {
        "en": "Cloud, cloud cover",
        "ur": "بادل، ابر، سحاب",
        "fa": "ابر، میغ، سحاب",
        "hi": "बादल, मेघ, अब्र",
        "ps": "وريځ، ابر، سحاب",
        "ar": "سحاب، غيم، مزن",
    },
    "ancestor": {
        "en": "Ancestor, forebear, elder",
        "ur": "بزرگ، جد، آبا و اجداد",
        "fa": "نیا، جد، بزرگ",
        "hi": "पूर्वज, बुज़ुर्ग, पुरखा",
        "ps": "نیکه، جد، مشر",
        "ar": "جد، سلف، عتيق",
    },
    "grateful": {
        "en": "Grateful, thankful, appreciative",
        "ur": "شکر گزار، ممنون، قدردان",
        "fa": "سپاسگزار، شاکر، قدردان",
        "hi": "कृतज्ञ, शुक्रगुज़ार, आभारी",
        "ps": "منندوی، شاکر، قدردان",
        "ar": "شاكر، حامد، ممتن",
    },
    "refined": {
        "en": "Refined, adorned, elegant",
        "ur": "مہذب، آراستہ، نفیس",
        "fa": "آراسته، نازنین، ظریف",
        "hi": "सुसंस्कृत, सजा हुआ, नफ़ीस",
        "ps": "ښکلی، سم، نفیس",
        "ar": "لطيف، مهذب، أنيق",
    },
    "tranquil": {
        "en": "Tranquil, calm, serene",
        "ur": "پرسکون، سکون والا، مطمئن",
        "fa": "آرام، ساکن، مطمئن",
        "hi": "शांत, सुकून भरा, निश्चिंत",
        "ps": "ارام، سکون لرونکی، مطمئن",
        "ar": "هادئ، ساكن، مطمئن",
    },
    "present": {
        "en": "Present, existing, available",
        "ur": "موجود، حاضر، دستیاب",
        "fa": "موجود، حاضر، در دسترس",
        "hi": "मौजूद, उपस्थित, हाज़िर",
        "ps": "موجود، حاضر، شته",
        "ar": "موجود، حاضر، متاح",
    },
    "given": {
        "en": "Given, granted, bestowed",
        "ur": "دیا گیا، عطا کیا گیا، بخشا گیا",
        "fa": "داده‌شده، عطا‌شده، بخشیده",
        "hi": "दिया गया, प्रदान, अता किया",
        "ps": "ورکړل شوی، عطا شوی، بخښل شوی",
        "ar": "معطى، موهوب، ممنوح",
    },
    "nourishing": {
        "en": "Nourishing, sustaining, supportive",
        "ur": "پرورش کرنے والا، پالنے والا، سہارا دینے والا",
        "fa": "پرورنده، روزی‌دهنده، پشتیبان",
        "hi": "पोषण करने वाला, पालने वाला, सहारा देने वाला",
        "ps": "پالونکی، روزي ورکوونکی، ملاتړی",
        "ar": "مغذٍّ، راعٍ، داعم",
    },
    "delicate": {
        "en": "Delicate, fine, tender",
        "ur": "نازک، لطیف، ملائم",
        "fa": "لطیف، نازک، ظریف",
        "hi": "नाज़ुक, कोमल, लतीफ़",
        "ps": "نازک، نرم، لطیف",
        "ar": "لطيف، رقيق، ناعم",
    },
    "sweet": {
        "en": "Sweet, pleasant, agreeable",
        "ur": "میٹھا، شیریں، خوشگوار",
        "fa": "شیرین، گوارا، دلپذیر",
        "hi": "मीठा, शीरीं, सुखद",
        "ps": "خوږ، شیریں، خوندور",
        "ar": "حلو، لذيذ، طيب",
    },
    "sunrise": {
        "en": "Sunrise, daybreak, dawn",
        "ur": "طلوعِ آفتاب، صبح، سورج نکلنا",
        "fa": "طلوع خورشید، بامداد، سپیده",
        "hi": "सूर्योदय, भोर, सूरज निकलना",
        "ps": "لمر خاته، سهار، سپیده",
        "ar": "شروق، طلوع، إشراق",
    },
    "free": {
        "en": "Free, liberated, unconstrained",
        "ur": "آزاد، خود مختار، رہا",
        "fa": "آزاد، رها، مستقل",
        "hi": "आज़ाद, स्वतंत्र, मुक्त",
        "ps": "ازاد، خپلواک، خلاص",
        "ar": "حر، طليق، مستقل",
    },
    "ripe": {
        "en": "Ripe, mature, fully developed",
        "ur": "پکا، بالغ، تیار",
        "fa": "رسیده، بالغ، پخته",
        "hi": "पका, परिपक्व, तैयार",
        "ps": "پوخ، بالغ، چمتو",
        "ar": "ناضج، يانع، مكتمل",
    },
    "respectable": {
        "en": "Respectable, dignified, honourable",
        "ur": "قابلِ احترام، باوقار، معزز",
        "fa": "محترم، باوقار، ارجمند",
        "hi": "सम्मानित, प्रतिष्ठित, माननीय",
        "ps": "د درناوي وړ، باوقار، معزز",
        "ar": "محترم، وقور، كريم",
    },
    "wealthy": {
        "en": "Wealthy, prosperous, affluent",
        "ur": "دولت مند، مالدار، خوشحال",
        "fa": "توانگر، ثروتمند، مرفه",
        "hi": "धनवान, अमीर, समृद्ध",
        "ps": "شتمن، مالدار، بډایه",
        "ar": "غني، ثري، موسر",
    },
    "mature": {
        "en": "Mature, fully grown, developed",
        "ur": "بالغ، پختہ، سمجھدار",
        "fa": "بالغ، پخته، رسیده",
        "hi": "वयस्क, परिपक्व, समझदार",
        "ps": "بالغ، پوخ، پوه",
        "ar": "بالغ، راشد، ناضج",
    },
    "existent": {
        "en": "Existing, present, enduring",
        "ur": "موجود، قائم، ہمیشہ رہنے والا",
        "fa": "موجود، پایدار، جاویدان",
        "hi": "मौजूद, स्थायी, चिरंतन",
        "ps": "موجود، تلپاتې، همیشنی",
        "ar": "موجود، دائم، باقي",
    },
    "prepared": {
        "en": "Prepared, ready, disposed",
        "ur": "تیار، مستعد، آمادہ",
        "fa": "آماده، مهیا، مستعد",
        "hi": "तैयार, मुस्तैद, तत्पर",
        "ps": "چمتو، تیار، مستعد",
        "ar": "مستعد، مهيأ، معدّ",
    },
    "mountain_strength": {
        "en": "Mountain of strength; exalted",
        "ur": "طاقت کا پہاڑ، بلند، سرفراز",
        "fa": "کوه استواری، والا، بلند",
        "hi": "शक्ति का पहाड़, उन्नत, बुलंद",
        "ps": "د ځواک غر، لوړ، ستر",
        "ar": "جبل القوة، رفيع، عليّ",
    },
    "warrior": {
        "en": "Warrior, noble one, pure",
        "ur": "جنگجو، نجیب، پاک",
        "fa": "جنگاور، نجیب، پاک",
        "hi": "योद्धा, कुलीन, पवित्र",
        "ps": "جنګیالی، نجیب، پاک",
        "ar": "محارب، نبيل، نقي",
    },
    "desire": {
        "en": "Desire, longing, yearning",
        "ur": "خواہش، آرزو، تمنا",
        "fa": "آرزو، خواست، تمنا",
        "hi": "इच्छा, चाह, अभिलाषा",
        "ps": "هیله، غوښتنه، ارمان",
        "ar": "رغبة، شوق، منية",
    },
    "breath": {
        "en": "Breath, soul, vital spirit",
        "ur": "سانس، روح، جان",
        "fa": "دم، جان، روان",
        "hi": "साँस, आत्मा, प्राण",
        "ps": "ساه، روح، ژوند",
        "ar": "نفس، روح، روح",
    },
    "heaven": {
        "en": "Heaven, sky, celestial realm",
        "ur": "آسمان، فلک، سماوات",
        "fa": "آسمان، سپهر، سماوات",
        "hi": "आकाश, स्वर्ग, आसमान",
        "ps": "آسمان، هسک، جنت",
        "ar": "سماء، سماوات، فلك",
    },
    "support": {
        "en": "Support, help, backing",
        "ur": "سہارا، مدد، حمایت",
        "fa": "پشتیبانی، یاری، حمایت",
        "hi": "सहारा, मदद, हिमायत",
        "ps": "ملاتړ، مرسته، حمایه",
        "ar": "دعم، نصرة، إسناد",
    },
    "cloud_rain": {
        "en": "Clouds and rain; abundance",
        "ur": "بادل اور بارش، فراوانی",
        "fa": "ابر و باران، فراوانی",
        "hi": "बादल और वर्षा, बहुतायत",
        "ps": "وريځ او باران، ډېروالی",
        "ar": "سحاب ومطر، غزارة",
    },
    "pious": {
        "en": "Pious, righteous, devout",
        "ur": "پرہیزگار، نیک، متقی",
        "fa": "پرهیزگار، نیک، متقی",
        "hi": "परहेज़गार, नेक, धर्मात्मा",
        "ps": "پرهیزګار، نیک، متقي",
        "ar": "تقي، صالح، ورع",
    },
    "ancestress": {
        "en": "Ancestress, forebear, elder woman",
        "ur": "بزرگ خاتون، جدہ، محترمہ",
        "fa": "نیاکان زن، جدّه، بزرگ‌بانو",
        "hi": "पूर्वज महिला, बुज़ुर्ग महिला, दादी",
        "ps": "نیکه ښځه، جدې، مشره",
        "ar": "جدة، سلفة، عتيقة",
    },
    "follower": {
        "en": "Follower, adherent, one who keeps",
        "ur": "پیرو، تابعدار، نگہبان",
        "fa": "پیرو، تابع، نگهبان",
        "hi": "अनुयायी, पैरोकार, रक्षक",
        "ps": "پیرو، تابع، ساتونکی",
        "ar": "تابع، حافظ، ملتزم",
    },
    "protector": {
        "en": "Protector, guardian, keeper",
        "ur": "محافظ، نگہبان، حامی",
        "fa": "محافظ، نگهبان، پشتیبان",
        "hi": "रक्षक, संरक्षक, हिफ़ाज़त करने वाला",
        "ps": "ساتونکی، محافظ، ملاتړی",
        "ar": "حافظ، حامي، ولي",
    },
    "captive": {
        "en": "Captive, one held; also protector",
        "ur": "قیدی، گرفتار، اسیر",
        "fa": "اسیر، گرفتار، بسته",
        "hi": "बंदी, क़ैदी, गिरफ़्तार",
        "ps": "بندي، نیول شوی، اسیر",
        "ar": "أسير، مأسور، مقيد",
    },
    "living_water": {
        "en": "Living water, flowing spring",
        "ur": "بہتا پانی، چشمہ، آبِ حیات",
        "fa": "آب روان، چشمه، آب حیات",
        "hi": "बहता जल, झरना, आब-ए-हयात",
        "ps": "بهیدونکی اوبه، چینه، د ژوند اوبه",
        "ar": "ماء جارٍ، عين، ماء الحياة",
    },
    "hasten": {
        "en": "One who hastens, swift, prompt",
        "ur": "جلدی کرنے والا، تیز، پھرتیلا",
        "fa": "شتابنده، تند، چابک",
        "hi": "जल्दी करने वाला, तेज़, फुर्तीला",
        "ps": "ګړندی کوونکی، تېز، چټک",
        "ar": "مسرع، سريع، عجول",
    },
    "gracious": {
        "en": "Gracious, beautiful, protecting",
        "ur": "مہربان، خوبصورت، محافظ",
        "fa": "مهربان، زیبا، نگهدارنده",
        "hi": "कृपालु, सुंदर, रक्षक",
        "ps": "مهربان، ښکلی، ساتونکی",
        "ar": "كريم، جميل، حافظ",
    },
    "elevated": {
        "en": "Elevated, exalted, raised high",
        "ur": "بلند، اونچا، سرفراز",
        "fa": "بلند، والا، فراز",
        "hi": "उन्नत, ऊँचा, बुलंद",
        "ps": "لوړ، پورته، ستر",
        "ar": "مرفوع، عالٍ، رفيع",
    },
    "delight": {
        "en": "Delight, joy, pleasure",
        "ur": "خوشی، مسرت، لطف",
        "fa": "شادی، لذت، سرور",
        "hi": "आनंद, खुशी, प्रसन्नता",
        "ps": "خوښي، خوند، سرور",
        "ar": "بهجة، سرور، لذة",
    },
    "storm": {
        "en": "Storm, tempest, strong wind",
        "ur": "طوفان، آندھی، ہوا",
        "fa": "طوفان، تندباد، باد",
        "hi": "तूफ़ान, आँधी, हवा",
        "ps": "طوفان، توفان، باد",
        "ar": "عاصفة، ريح، إعصار",
    },
    "wealth": {
        "en": "Wealth, riches, abundance",
        "ur": "دولت، مال، فراوانی",
        "fa": "ثروت، مال، فراوانی",
        "hi": "धन, दौलत, बहुतायत",
        "ps": "شتمني، مال، ډېروالی",
        "ar": "ثروة، مال، غنى",
    },
    "companion_of_allah": {
        "en": "Companion or friend (in a religious naming context)",
        "ur": "ساتھی، رفیق (مذہبی نام رکھنے کے سیاق میں)",
        "fa": "همراه، رفیق (در بافت نام‌گذاری دینی)",
        "hi": "साथी, रफ़ीक़ (धार्मिक नामकरण के संदर्भ में)",
        "ps": "ملګری، رفیق (دیني نوم اېښودلو په سیاق کې)",
        "ar": "صاحب، رفيق، ولي",
    },
}

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "aamilah": ("عاملة","عاملة",None,"आमिला","عامله","worker","Arabic","Female","ع م ل","root ع م ل occurs in the Qur'an; the exact form عاملة is a normal Arabic word, not a Qur'anic proper name","medium","Feminine active participle of عَمِلَ (to work, to act)."),
 "aamin": ("أمين","امین",None,"आमिन","امین","trustworthy","Arabic","Male","أ م ن","root أ م ن occurs widely in the Qur'an; أمين is a common Arabic word and a well-attested given name","high","Common Arabic adjective/name; also the Arabic form of the name Amon/Amun in some traditions."),
 "aamina": ("أمينة","آمنہ",None,"आमिना","آمنه","safe","Arabic","Female","أ م ن","root أ م ن occurs in the Qur'an; أمينة is a normal Arabic feminine form","high","Feminine of أمين; also the name of Āmina bint Wahb, the mother of the Prophet Muhammad, in the biographical (sīra) tradition."),
 "aaminaat": ("أمينات","امینات",None,"आमिनात","امینات","trustworthy","Arabic","Female","أ م ن","root أ م ن occurs in the Qur'an; أمينات is a sound feminine plural, not a Qur'anic proper name","medium","Plural form of أمينة; used as a given name in some South Asian communities."),
 "aaminah": ("أمينة","آمنہ",None,"आमिना","آمنه","trustworthy","Arabic","Female","أ م ن","root أ م ن occurs in the Qur'an; أمينة is a normal Arabic feminine form","high","Standard spelling of the same name as aamina; associated with Āmina bint Wahb in the sīra tradition."),
 "aamir": ("عامر","عامر",None,"आमिर","عامر","prosperous","Arabic","Male","ع م ر","root ع م ر occurs in the Qur'an; عامر is a normal Arabic word and a well-attested given name","high","Active participle of عَمَرَ (to inhabit, to flourish). Distinct from أمير (amīr, commander)."),
 "aamira": ("عامرة","عامرہ",None,"आमिरा","عامره","prosperous","Arabic","Female","ع م ر","root ع م ر occurs in the Qur'an; عامرة is a normal Arabic feminine form","high","Feminine of عامر."),
 "aamirah": ("عامرة","عامرہ",None,"आमिरा","عامره","prosperous","Arabic","Female","ع م ر","root ع م ر occurs in the Qur'an; عامرة is a normal Arabic feminine form","high","Variant romanization of aamira."),
 "aamirat": ("عامرات","عامرات",None,"आमिरात","عامرات","prosperous","Arabic","Female","ع م ر","root ع م ر occurs in the Qur'an; عامرات is a sound feminine plural, not a Qur'anic proper name","medium","Plural form of عامرة."),
 "aamirul": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The form aamirul could not be matched to a verified Arabic lexical form. It may be a romanization of a compound (e.g. ʿĀmir al-…), but no source was found to confirm this. No gloss is asserted."),
 "aamiya": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave عامية ('colloquial'), which is a linguistic register term rather than a personal name. The identification could not be verified and no gloss is asserted."),
 "aamla": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified Arabic, Persian, Urdu, Hindi or Pashto lexical form could be matched to aamla. No gloss is asserted."),
 "aamna": ("آمنة","آمنہ",None,"आमना","آمنه","safe","Arabic","Female","أ م ن","root أ م ن occurs in the Qur'an; آمنة is a normal Arabic feminine form","high","Variant romanization of the same name as aamina/aaminah; associated with Āmina bint Wahb in the sīra tradition."),
 "aamra": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave أميرة (amīra, 'princess'), which is a different name (see aamirah). The form aamra could not be independently verified and no gloss is asserted."),
 "aamrah": ("عامرة","عامرہ",None,"आमरा","عامره","prosperous","Arabic","Female","ع م ر","root ع م ر occurs in the Qur'an; عامرة is a normal Arabic feminine form","medium","Variant romanization of aamira/aamirah."),
 "aana": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record supplied a Latin-script placeholder rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "aanal": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aanal. No gloss is asserted."),
 "aanan": ("عنان","عنان",None,"अनान","عنان","companion","Arabic","Unisex","ع ن ن","root ع ن ن does not occur as this exact form in the Qur'an; عنان is a normal Arabic noun","low","عنان means 'reins, halter' in Arabic. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aaneseh": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record supplied a Latin-script placeholder rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "aani": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aani. No gloss is asserted."),
 "aania": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aania. No gloss is asserted."),
 "aanil": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record supplied a Latin-script placeholder rather than a script form. No verified lexical form could be matched and no gloss is asserted."),
 "aanisa": ("أنيسة","انیسہ",None,"अनीसा","انیسه","friendly","Arabic","Female","أ ن س","root أ ن س occurs in the Qur'an; أنيسة is a normal Arabic feminine form","medium","Feminine of أنيس (friendly, sociable)."),
 "aanisah": ("أنيسة","انیسہ",None,"अनीसा","انیسه","friendly","Arabic","Female","أ ن س","root أ ن س occurs in the Qur'an; أنيسة is a normal Arabic feminine form","medium","Variant romanization of aanisa."),
 "aaniya": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aaniya. No gloss is asserted."),
 "aaniyah": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aaniyah. No gloss is asserted."),
 "aaolin": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aaolin. No gloss is asserted."),
 "aaqib": ("عاقب","عاقب",None,"आक़िब","عاقب","successor","Arabic","Male","ع ق ب","root ع ق ب occurs in the Qur'an; عاقب is a normal Arabic word","medium","Active participle of عَقَبَ (to follow, to succeed)."),
 "aaqiba": ("عاقبة","عاقبہ",None,"आक़िबा","عاقبه","outcome","Arabic","Female","ع ق ب","root ع ق ب occurs in the Qur'an; عاقبة is a normal Arabic noun","medium","عاقبة means 'consequence, outcome, end result'."),
 "aaqibah": ("عاقبة","عاقبہ",None,"आक़िबा","عاقبه","outcome","Arabic","Female","ع ق ب","root ع ق ب occurs in the Qur'an; عاقبة is a normal Arabic noun","medium","Variant romanization of aaqiba."),
 "aaqif": ("عاكف","عاکف",None,"आकिफ़","عاکف","devoted","Arabic","Male","ع ك ف","root ع ك ف occurs in the Qur'an; عاكف is a normal Arabic word","medium","Active participle of عَكَفَ (to stay, to devote oneself)."),
 "aaqifa": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave أعقل ('more rational'), which is a different word. The form aaqifa could not be verified and no gloss is asserted."),
 "aaqil": ("عاقل","عاقل",None,"आक़िल","عاقل","wise","Arabic","Male","ع ق ل","root ع ق ل occurs in the Qur'an; عاقل is a normal Arabic word","high","Active participle of عَقَلَ (to understand, to be reasonable)."),
 "aaqilah": ("عاقلة","عاقلہ",None,"आक़िला","عاقله","wise","Arabic","Female","ع ق ل","root ع ق ل occurs in the Qur'an; عاقلة is a normal Arabic feminine form","high","Feminine of عاقل."),
 "aara": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave عارة, which is not a standard Arabic lexical form. The identification could not be verified and no gloss is asserted."),
 "aaraf": ("أعراف","اعراف",None,"आराफ़","اعراف","heights","Arabic","Unisex","ع ر ف","الأعراف is the name of Qur'anic sūra 7 (al-Aʿrāf); the form أعراف is a Qur'anic lexical item","medium","أعراف is the plural of عُرْف ('elevated place, crest') and is the title of sūra 7. Its use as a personal name is reported but not verified."),
 "aarasun": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aarasun. No gloss is asserted."),
 "aareeha": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aareeha. No gloss is asserted."),
 "aarefa": ("عارفة","عارفہ",None,"आरिफ़ा","عارفه","knowledgeable","Arabic","Female","ع ر ف","root ع ر ف occurs in the Qur'an; عارفة is a normal Arabic feminine form","medium","Feminine of عارف."),
 "aarfa": ("عرفة","عرفہ",None,"आरफ़ा","عرفه","heights","Arabic","Female","ع ر ف","root ع ر ف occurs in the Qur'an; عرفة is a place name (the plain of ʿArafāt)","low","عرفة is the name of the plain near Mecca associated with the Hajj. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aarib": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave عارب, which is not a standard Arabic lexical form. The identification could not be verified and no gloss is asserted."),
 "aaribah": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aaribah. No gloss is asserted."),
 "aaribat": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aaribat. No gloss is asserted."),
 "aaribun": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aaribun. No gloss is asserted."),
 "aarif": ("عارف","عارف",None,"आरिफ़","عارف","knowledgeable","Arabic","Male","ع ر ف","root ع ر ف occurs in the Qur'an; عارف is a normal Arabic word","high","Active participle of عَرَفَ (to know). Widely used as a given name."),
 "aarifa": ("عارفة","عارفہ",None,"आरिफ़ा","عارفه","knowledgeable","Arabic","Female","ع ر ف","root ع ر ف occurs in the Qur'an; عارفة is a normal Arabic feminine form","high","Feminine of عارف."),
 "aarifah": ("عارفة","عارفہ",None,"आरिफ़ा","عارفه","knowledgeable","Arabic","Female","ع ر ف","root ع ر ف occurs in the Qur'an; عارفة is a normal Arabic feminine form","high","Variant romanization of aarifa."),
 "aarifin": ("عارفين","عارفین",None,"आरिफ़ीन","عارفین","knowledgeable","Arabic","Male","ع ر ف","root ع ر ف occurs in the Qur'an; عارفين is a sound masculine plural, not a Qur'anic proper name","medium","Plural of عارف; used as a given name in some South Asian communities."),
 "aariz": ("عارض","عارض",None,"आरिज़","عارض","cloud","Arabic","Male","ع ر ض","root ع ر ض occurs in the Qur'an; عارض is a normal Arabic noun","low","عارض can mean 'cloud' or 'one who presents'. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aarizah": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave عاريظة, which is not a standard Arabic lexical form. The identification could not be verified and no gloss is asserted."),
 "aarizun": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aarizun. No gloss is asserted."),
 "aaron": ("هارون","ہارون",None,"हारून","هارون","mountain_strength","Hebrew","Male",None,"هارون (Hārūn) is the Qur'anic form of Aaron and occurs in the Qur'an as a prophet's name","high","The Arabic form هارون (Hārūn) is the Qur'anic name of the prophet Aaron. The English form Aaron derives from Hebrew אַהֲרוֹן. The source record's 'Mountain of strength' gloss is a popular but disputed Hebrew etymology."),
 "aarya": ("آريا","آریا",None,"आर्य","آریا","noble","Sanskrit","Unisex",None,"not a Qur'anic form","medium","आर्य (ārya) is a Sanskrit term meaning 'noble'. It is not an Arabic word; its presence in an Islamic-slice record reflects South Asian naming usage rather than Arabic origin."),
 "aaryan": ("آريان","آریان",None,"आर्यन","آریان","noble","Sanskrit","Male",None,"not a Qur'anic form","medium","आर्यन is a Sanskrit-derived South Asian name meaning 'noble'. It is not Arabic in origin."),
 "aarzam": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave عرضام, which is not a standard Arabic lexical form. The identification could not be verified and no gloss is asserted."),
 "aarzoo": ("آرزو","آرزو",None,"आरज़ू","آرزو","desire","Persian","Female",None,"not a Qur'anic form","high","آرزو is an established Persian word meaning 'wish, desire, longing'. It is Persian, not Arabic, and is widely used in Urdu."),
 "aarzu": ("آرزو","آرزو",None,"आरज़ू","آرزو","desire","Persian","Female",None,"not a Qur'anic form","high","Variant romanization of aarzoo."),
 "aas": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","No verified lexical form could be matched to aas. No gloss is asserted."),
 "aasaal": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave أحمد ('Ahmad'), which is a different name entirely. The form aasaal could not be verified and no gloss is asserted."),
 "aasal": ("عسل","عسل",None,"असल","عسل","honey","Arabic","Unisex","ع س ل","root ع س ل occurs in the Qur'an; عسل is a normal Arabic noun","medium","عسل means 'honey'. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aaseman": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record supplied a Latin-script placeholder rather than a script form. The form aaseman resembles Persian آسمان ('sky'), but this could not be verified and no gloss is asserted."),
 "aasfa": ("عاصفة","عاصفہ",None,"आसिफ़ा","عاصفه","storm","Arabic","Female","ع ص ف","root ع ص ف occurs in the Qur'an; عاصفة is a normal Arabic noun","medium","عاصفة means 'storm, tempest'. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aashif": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave عاشف, which is not a standard Arabic lexical form. The identification could not be verified and no gloss is asserted."),
 "aashik": ("عاشق","عاشق",None,"आशिक़","عاشق","lover","Arabic","Male","ع ش ق","root ع ش ق does not occur in the Qur'an; عاشق is a normal Arabic word","medium","عاشق means 'lover, one passionately devoted'. Widely used in Urdu and Persian literary culture."),
 "aashiq": ("عاشق","عاشق",None,"आशिक़","عاشق","lover","Arabic","Male","ع ش ق","root ع ش ق does not occur in the Qur'an; عاشق is a normal Arabic word","medium","Variant romanization of aashik."),
 "aashir": ("عاشر","عاشر",None,"आशिर","عاشر","companion","Arabic","Male","ع ش ر","root ع ش ر occurs in the Qur'an; عاشر is a normal Arabic word","medium","عاشر can mean 'one who associates with' or 'tenth'. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aasia": ("آسية","آسیہ",None,"आसिया","آسیه","living_water","Arabic","Female","أ س و","آسية is the name of the wife of Pharaoh in Islamic tradition; the exact form is not a Qur'anic proper name","medium","آسية (Āsiya) is the name traditionally given to the wife of Pharaoh, mentioned in Islamic tradition. The source record's identification with عائشة ('Aisha') is an error."),
 "aasif": ("عاصف","عاصف",None,"आसिफ़","عاصف","storm","Arabic","Male","ع ص ف","root ع ص ف occurs in the Qur'an; عاصف is a normal Arabic word","medium","عاصف means 'stormy, tempestuous'. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aasifah": ("عاصفة","عاصفہ",None,"आसिफ़ा","عاصفه","storm","Arabic","Female","ع ص ف","root ع ص ف occurs in the Qur'an; عاصفة is a normal Arabic noun","medium","Variant romanization of aasfa."),
 "aasim": ("عاصم","عاصم",None,"आसिम","عاصم","protector","Arabic","Male","ع ص م","root ع ص م occurs in the Qur'an; عاصم is a normal Arabic word","high","Active participle of عَصَمَ (to protect, to preserve). A well-attested given name."),
 "aasima": ("عاصمة","عاصمہ",None,"आसिमा","عاصمه","protector","Arabic","Female","ع ص م","root ع ص م occurs in the Qur'an; عاصمة is a normal Arabic feminine form","medium","Feminine of عاصم; also means 'capital city'."),
 "aasimah": ("عاصمة","عاصمہ",None,"आसिमा","عاصمه","protector","Arabic","Female","ع ص م","root ع ص م occurs in the Qur'an; عاصمة is a normal Arabic feminine form","medium","Variant romanization of aasima."),
 "aasimat": ("عاصمات","عاصمات",None,"आसिमात","عاصمات","protector","Arabic","Female","ع ص م","root ع ص م occurs in the Qur'an; عاصمات is a sound feminine plural, not a Qur'anic proper name","low","Plural form of عاصمة."),
 "aasir": ("عاصر","عاصر",None,"आसिर","عاصر","companion","Arabic","Male","ع ص ر","root ع ص ر occurs in the Qur'an; عاصر is a normal Arabic word","low","عاصر means 'contemporary, one who lives in the same age'. Its use as a personal name is reported but not verified."),
 "aasira": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave الأسيرة ('the captive'), which is a definite noun phrase rather than a name. The identification could not be verified and no gloss is asserted."),
 "aasiya": ("آسية","آسیہ",None,"आसिया","آسیه","living_water","Arabic","Female","أ س و","آسية is the name of the wife of Pharaoh in Islamic tradition; the exact form is not a Qur'anic proper name","medium","Variant romanization of aasia. The source record's identification with عائشة ('Aisha') is an error."),
 "aasiyah": ("آسية","آسیہ",None,"आसिया","آسیه","living_water","Arabic","Female","أ س و","آسية is the name of the wife of Pharaoh in Islamic tradition; the exact form is not a Qur'anic proper name","medium","Variant romanization of aasia."),
 "aasiyyah": ("آسية","آسیہ",None,"आसिया","آسیه","living_water","Arabic","Female","أ س و","آسية is the name of the wife of Pharaoh in Islamic tradition; the exact form is not a Qur'anic proper name","medium","Variant romanization of aasia."),
 "aasma": ("أسماء","اسماء",None,"अस्मा","اسما","heaven","Arabic","Female","س م و","أسماء is a well-attested Arabic name (Asmāʾ bint Abī Bakr); the exact form is not a Qur'anic proper name","high","أسماء is the plural of اسم ('name') and also relates to سمو ('elevation'). Associated with Asmāʾ bint Abī Bakr in the sīra tradition."),
 "aasmaa": ("أسماء","اسماء",None,"अस्मा","اسما","heaven","Arabic","Female","س م و","أسماء is a well-attested Arabic name; the exact form is not a Qur'anic proper name","high","Variant romanization of aasma."),
 "aasman": ("آسمان","آسمان",None,"आसमान","آسمان","heaven","Persian","Male",None,"not a Qur'anic form","high","آسمان is an established Persian word meaning 'sky, heaven'. It is Persian, not Arabic, and is widely used in Urdu."),
 "aateqa": ("عاتقة","عاتقہ",None,"आतिक़ा","عاتقه","free","Arabic","Female","ع ت ق","root ع ت ق occurs in the Qur'an; عاتقة is a normal Arabic feminine form","medium","Feminine of عاتق; عاتقة can mean 'free, liberated' or 'a young woman'. Its use as a personal name is reported but not verified."),
 "aathira": (None,None,None,None,None,None,"Unknown","Unknown",None,"not established","unverified","The source record gave أثيرة, which is not a standard Arabic lexical form. The identification could not be verified and no gloss is asserted."),
 "aati": ("عاطي","عاطی",None,"आती","عاطي","given","Arabic","Male","ع ط و","root ع ط و occurs in the Qur'an; عاطي is a normal Arabic word","medium","Active participle of أَعْطَى (to give). Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aatif": ("عاطف","عاطف",None,"आतिफ़","عاطف","tranquil","Arabic","Male","ع ط ف","root ع ط ف occurs in the Qur'an; عاطف is a normal Arabic word","medium","Active participle of عَطَفَ (to incline, to be sympathetic). A well-attested given name."),
 "aatifa": ("عاطفة","عاطفہ",None,"आतिफ़ा","عاطفه","tranquil","Arabic","Female","ع ط ف","root ع ط ف occurs in the Qur'an; عاطفة is a normal Arabic noun","medium","عاطفة means 'emotion, sympathy, affection'. Its use as a personal name is reported but not verified."),
 "aatifah": ("عاطفة","عاطفہ",None,"आतिफ़ा","عاطفه","tranquil","Arabic","Female","ع ط ف","root ع ط ف occurs in the Qur'an; عاطفة is a normal Arabic noun","medium","Variant romanization of aatifa."),
 "aatik": ("عاتق","عاتق",None,"आतिक़","عاتق","free","Arabic","Male","ع ت ق","root ع ت ق occurs in the Qur'an; عاتق is a normal Arabic word","medium","عاتق means 'shoulder' or 'one who is free'. Its use as a personal name is reported but not verified."),
 "aatika": ("عاتكة","عاتکہ",None,"आतिका","عاتکه","pure","Arabic","Female","ع ت ك","root ع ت ك occurs in the Qur'an; عاتكة is a normal Arabic feminine form","medium","عاتكة is a well-attested pre-Islamic and early Islamic female name. Its use is reported in the sīra tradition."),
 "aatikaat": ("عاتكات","عاتکات",None,"आतिकात","عاتکات","pure","Arabic","Female","ع ت ك","root ع ت ك occurs in the Qur'an; عاتكات is a sound feminine plural, not a Qur'anic proper name","low","Plural form of عاتكة."),
 "aatikah": ("عاتكة","عاتکہ",None,"आतिका","عاتکه","pure","Arabic","Female","ع ت ك","root ع ت ك occurs in the Qur'an; عاتكة is a normal Arabic feminine form","medium","Variant romanization of aatika."),
 "aatiq": ("عاتق","عاتق",None,"आतिक़","عاتق","ancestor","Arabic","Male","ع ت ق","root ع ت ق occurs in the Qur'an; عتيق is a normal Arabic word","low","The source record gave عاطق, which is not a standard form; the intended form is likely عتيق ('ancient, noble, freed'). The identification is uncertain and the gloss is provisional."),
 "aatiqa": ("عتيقة","عتیقہ",None,"आतिक़ा","عتیقه","ancestress","Arabic","Female","ع ت ق","root ع ت ق occurs in the Qur'an; عتيقة is a normal Arabic feminine form","low","Feminine of عتيق. The source record's form آتيفا is not standard; the intended form is likely عتيقة. The identification is uncertain."),
 "aatiqah": ("عتيقة","عتیقہ",None,"आतिक़ा","عتیقه","ancestress","Arabic","Female","ع ت ق","root ع ت ق occurs in the Qur'an; عتيقة is a normal Arabic feminine form","low","Variant romanization of aatiqa. The source record's form is not standard and the identification is uncertain."),
 "aatir": ("عاطر","عاطر",None,"आतिर","عاطر","fragrant","Arabic","Male","ع ط ر","root ع ط ر does not occur in the Qur'an; عاطر is a normal Arabic word","medium","عاطر means 'fragrant, perfumed'. Its use as a personal name is reported but not verified from a Tier-A/B source."),
 "aatira": ("عاطرة","عاطرہ",None,"आतिरा","عاطره","fragrant","Arabic","Female","ع ط ر","root ع ط ر does not occur in the Qur'an; عاطرة is a normal Arabic feminine form","medium","Feminine of عاطر."),
 "aatirah": ("عاطرة","عاطرہ",None,"आतिरा","عاطره","fragrant","Arabic","Female","ع ط ر","root ع ط ر does not occur in the Qur'an; عاطرة is a normal Arabic feminine form","medium","Variant romanization of aatira."),
 "aatiya": ("عاطية","عاطیہ",None,"आतिया","عاطیه","given","Arabic","Female","ع ط و","root ع ط و occurs in the Qur'an; عاطية is a normal Arabic feminine form","medium","Feminine of عاطي."),
 "aauf": ("عؤف","عؤف",None,"आउफ़","عؤف","praise","Arabic","Male","ع و ف","root ع و ف does not occur in the Qur'an; عوف is a normal Arabic word","low","The source record gave عؤف; the standard form is عوف (ʿAwf), a well-attested early Islamic male name. The identification is probable but the source spelling is non-standard."),
 "aaus": ("أوس","اوس",None,"आउस","اوس","gift","Arabic","Male","أ و س","أوس is a well-attested early Islamic male name; the exact form is not a Qur'anic proper name","medium","أوس (Aws) is the name of an early Islamic tribe and several Companions. The source record's gloss 'Fish' is not supported."),
}
