# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 55 (sabawoon..safwa).

FINAL BATCH — 93 names (the remaining tail of the Islamic list).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": sabeel -> Latin "Sabeel";
   sadaf -> "عربي_Sadaf" (placeholder prefix); sadah -> Latin "Sadah";
   sadan -> Latin "Sa'dān"; sabrin -> Latin "Sabrin";
   sadegh -> Latin "Saadiq"; sadit -> Latin "Sadit";
   safina -> Latin "Safina"; sabir -> empty; sabreen -> empty;
   sadiq -> empty; safiyyah -> empty; sabi -> عائشة; sadun -> علي;
   sabawoon -> سبأون; sabbagh -> سباغ; sabbir -> سببر; sabeeh -> سبيح;
   sabeeha -> سبيحة; sabeeka -> سبي كة; sabeen -> سبين; sabeena -> سابينا;
   sabeer -> سبير; sabeha -> سبها; saber -> صابر; sabera -> صابرة;
   sabha -> سبحة; sabia -> سبيا; sabih -> سبح; sabiha -> سبيحة;
   sabika -> سبيكا; sabil -> سبيل; sabira -> صبيرة; sabit -> صَابِط;
   sabiya -> سبية; saboor -> صبور; sabr -> صبر; sabra -> صبرا;
   sabreena -> سبرينة; sabri -> سابر ى; sabria -> سبريا; sabrine -> سبرين;
   sabuhi -> سبحة; sabur -> صبور; sadam -> صدام; sadaqat -> صدقات;
   sadat -> صادَت; saddam -> صدام; sadeem -> سعدم; sadeen -> سدين;
   sadeeq -> صادق; sadi -> سدي; sadia -> سعدية; sadiah -> ساديه;
   sadid -> سديد; sadik -> صادق; sadika -> ساد يقة; sadin -> صادق;
   sadiqa -> صادقة; sadir -> سدير; sadiya -> سعدية; sadiyah -> سادية;
   sadq -> صدق; sadr -> سدر; sadra -> سدرة; sadri -> سدري;
   sadruddin -> سدرو ددين; saee -> سعي; saeed -> سعيد; saeeda -> سائ دة;
   safa -> صفا; safaa -> صفاء; safar -> سفر; safdar -> صفدر;
   safee -> صفي; safeena -> صفينة; safeenah -> صفينة; safeer -> سفير;
   safeera -> سفيرة; saffa -> سفاء; saffan -> صِفان; saffron -> زعفران;
   safi -> صفي; safia -> سفيهة; safin -> صفي; safinaz -> سفيناز;
   safir -> صفير; safira -> سفيرة; safiya -> صفية; safiyah -> صفية;
   safiyya -> صفية; safura -> صفورة; safwa -> صفوة.
 * EMPTY STUBS (8-key records, no data): sabir, sabreen, sadiq, safiyyah.
 * MISLABELLED ORIGIN: sabawoon (Pashto), sadegh (Persian), safdar (Persian),
   saffron (English/plant name), sabi (Hebrew), sabra (Hebrew),
   safiyya (Hebrew), sabri (Turkish), sabuhi (Turkish).
 * DEGARBLED GLOSSES: sabawoon "The Bright Moon", sabbagh "Little One",
   sabbir "Supplier, Provider", sabeeh "Pure, Clear", sabeeha "Beautiful",
   sabeeka "Seeker, Lover", sabeel "Well, canal, path to water",
   sabeen "Peaceful", sabeena "Moon, radiant, beautiful",
   sabeer "Knowledgeable", sabeha "Patient", saber "Sword",
   sabera "Intelligent", sabha "Mountain, hill, mound",
   sabi "Old, Ancient, Wise, Patient", sabia "Intelligent, Wise",
   sabih "Patient, Steadfast", sabiha "Bringer of Glad Tidings",
   sabika "Little One", sabil "Path, Way, Road", sabira "Patient, Enduring",
   sabit "Firm, Strong, Steadfast", sabiya "Patient",
   saboor "Patient, Steadfast", sabr "Patience, endurance",
   sabra "Fruit, Sweet", sabreena "Moonlight", sabri "Patience, Endurance",
   sabria "Intelligent, Wise", sabrin "Moon",
   sabrine "Patient, gentle, and beautiful", sabuhi "Companion, Helper",
   sabur "Patient, Enduring", sadaf "Noble and blessed", sadah "Meadow",
   sadam "One who confronts, Brave", sadan "Fortunate, Lucky",
   sadaqat "Charity, Benevolence", sadat "Ruler, Lady",
   saddam "Exalted, Noble, Mighty", sadeem "Moon", sadeen "Garden or Flowers",
   sadeeq "Truthful", sadegh "Righteous", sadi "Just, Righteous",
   sadia "Truthful, Honest", sadiah "Meadow, Garden, Joy",
   sadid "Support, Help, Aid", sadik "Truthful", sadika "Truthful, sincere",
   sadin "Gladdener", sadiqa "Truthful, sincere friend",
   sadir "Gardener, Cultivator", sadit "Lady of the Garden",
   sadiya "Follower of the Right Path", sadiyah "Moon", sadq "Truthful",
   sadr "chief, leader", sadra "Saffron", sadri "Happy, Joyful, Delighted",
   sadruddin "Servant of God", sadun "Gift, Reward", saee "The One Who Weeps",
   saeed "Happy, Blessed", saeeda "Lady, Mistress",
   safa "Purified, Clean, Sacred", safaa "Clean and Pure", safar "Traveler",
   safdar "Protector, Defender", safee "Secure, Safe, Protected",
   safeena "Protected One", safeenah "Protector", safeer "Traveler, Messenger",
   safeera "Purity, Perfection", saffa "Gentle, peaceful", saffan "Pure, Clear",
   saffron "Yellow Saffron", safi "Pure", safia "Safe", safin "Sailor, Seafarer",
   safina "Safe or Sound", safinaz "Pure and Chaste", safir "Traveler",
   safira "Purity, Light, Transparency", safiya "Pure and Untainted",
   safiyah "Pure, Chaste", safiyya "Pure, Chaste", safura "Pure, Chaste",
   safwa "Pure, Hidden Treasure".
 * GENDER ERRORS: sabbagh, sabi, sabih, sabr, sadan, sadi, saffa, saffron,
   safi were labelled unisex where documented usage is male or female.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated54 import GLOSSES as _G54

GLOSSES = dict(_G54)
GLOSSES.update({
    "sabawoon": {"en": "Sabawoon; a male given name (Pashto)", "ur": "سباوون (مردانہ نام)", "fa": "سباوون (نام مردانه)", "hi": "सबावून (पुरुष नाम)", "ps": "سباوون (نر نوم)", "ar": "سَبَاوُون (اسْم عَلَم بَشْتُونِيّ)"},
    "sabbagh": {"en": "Sabbagh; dyer (occupational)", "ur": "صباغ، رنگ ساز", "fa": "صباغ، رنگرز", "hi": "सब्बाग़, रंगरेज़", "ps": "صباغ، رنګوونکی", "ar": "الصَّبَّاغ، صَابِغ"},
    "sabbir": {"en": "Sabbir; a male given name", "ur": "صابر (مردانہ نام)", "fa": "صابر (نام مردانه)", "hi": "सब्बीर (पुरुष नाम)", "ps": "صابر (نر نوم)", "ar": "صَبِير (اسْم عَلَم مُذَكَّر)"},
    "sabeeh": {"en": "Sabeeh; beautiful, handsome", "ur": "صبیح، خوبصورت", "fa": "صبیح، زیبا", "hi": "सबीह, सुंदर", "ps": "صبیح، ښکلی", "ar": "الصَّبِيح، الْجَمِيل"},
    "sabeeha": {"en": "Sabeeha; beautiful (feminine)", "ur": "صبیحہ، خوبصورت", "fa": "صبیحه، زیبا", "hi": "सबीहा, सुंदर", "ps": "صبیحه، ښکلې", "ar": "صَبِيحَة، الْجَمِيلَة"},
    "sabeeka": {"en": "Sabeeka; a female given name", "ur": "سبیکہ (زنانہ نام)", "fa": "سبیکه (نام زنانه)", "hi": "सबीका (स्त्री नाम)", "ps": "سبیکه (ښځينه نوم)", "ar": "سَبِيكَة (اسْم عَلَم مُؤَنَّث)"},
    "sabeel": {"en": "Sabeel; way, path", "ur": "سبیل، راستہ", "fa": "سبیل، راه", "hi": "सबील, रास्ता", "ps": "سبیل، لار", "ar": "السَّبِيل، الطَّرِيق"},
    "sabeen": {"en": "Sabeen; a female given name", "ur": "سبین (زنانہ نام)", "fa": "سبین (نام زنانه)", "hi": "सबीन (स्त्री नाम)", "ps": "سبین (ښځينه نوم)", "ar": "سَبِين (اسْم عَلَم مُؤَنَّث)"},
    "sabeena": {"en": "Sabeena; a female given name", "ur": "سبینہ (زنانہ نام)", "fa": "سبینا (نام زنانه)", "hi": "सबीना (स्त्री नाम)", "ps": "سبینا (ښځينه نوم)", "ar": "سَابِينَا (اسْم عَلَم مُؤَنَّث)"},
    "sabeer": {"en": "Sabeer; patient, enduring", "ur": "صابر، صبر کرنے والا", "fa": "صابر، شکیبا", "hi": "सबीर, धैर्यवान", "ps": "صابر، صبر کوونکی", "ar": "الصَّبِير، الصَّابِر"},
    "sabeha": {"en": "Sabeha; a female given name", "ur": "سبیہہ (زنانہ نام)", "fa": "سبیحه (نام زنانه)", "hi": "सबीहा (स्त्री नाम)", "ps": "سبیحه (ښځينه نوم)", "ar": "سَبِيهَة (اسْم عَلَم مُؤَنَّث)"},
    "saber": {"en": "Saber; patient, enduring", "ur": "صابر، صبر کرنے والا", "fa": "صابر، شکیبا", "hi": "साबिर, धैर्यवान", "ps": "صابر، صبر کوونکی", "ar": "الصَّابِر، الصَّبُور"},
    "sabera": {"en": "Sabera; patient, enduring (feminine)", "ur": "صابرہ، صبر کرنے والی", "fa": "صابره، شکیبا", "hi": "साबिरा, धैर्यवान", "ps": "صابره، صبر کوونکې", "ar": "صَابِرَة، الصَّابِرَة"},
    "sabha": {"en": "Sabha; a female given name", "ur": "سبحہ (زنانہ نام)", "fa": "سبحه (نام زنانه)", "hi": "सबहा (स्त्री नाम)", "ps": "سبحه (ښځينه نوم)", "ar": "سَبْحَة (اسْم عَلَم مُؤَنَّث)"},
    "sabi": {"en": "Sabi; a male given name (Hebrew)", "ur": "سبی (مردانہ نام)", "fa": "سبی (نام مردانه)", "hi": "सबी (पुरुष नाम)", "ps": "سبي (نر نوم)", "ar": "سَابِي (اسْم عَلَم عِبْرِيّ)"},
    "sabia": {"en": "Sabia; a female given name", "ur": "سبیعہ (زنانہ نام)", "fa": "سبیعه (نام زنانه)", "hi": "सबिया (स्त्री नाम)", "ps": "سبیعه (ښځينه نوم)", "ar": "سَبِيعَة (اسْم عَلَم مُؤَنَّث)"},
    "sabih": {"en": "Sabih; beautiful, handsome", "ur": "صبیح، خوبصورت", "fa": "صبیح، زیبا", "hi": "सबीह, सुंदर", "ps": "صبیح، ښکلی", "ar": "الصَّبِيح، الْجَمِيل"},
    "sabiha": {"en": "Sabiha; beautiful (feminine)", "ur": "صبیحہ، خوبصورت", "fa": "صبیحه، زیبا", "hi": "सबीहा, सुंदर", "ps": "صبیحه، ښکلې", "ar": "صَبِيحَة، الْجَمِيلَة"},
    "sabika": {"en": "Sabika; a female given name", "ur": "سبیکہ (زنانہ نام)", "fa": "سبیکا (نام زنانه)", "hi": "सबीका (स्त्री नाम)", "ps": "سبیکا (ښځينه نوم)", "ar": "سَبِيكَة (اسْم عَلَم مُؤَنَّث)"},
    "sabil": {"en": "Sabil; way, path", "ur": "سبیل، راستہ", "fa": "سبیل، راه", "hi": "सबील, रास्ता", "ps": "سبیل، لار", "ar": "السَّبِيل، الطَّرِيق"},
    "sabir": {"en": "Sabir; patient, enduring", "ur": "صابر، صبر کرنے والا", "fa": "صابر، شکیبا", "hi": "साबिर, धैर्यवान", "ps": "صابر، صبر کوونکی", "ar": "الصَّابِر، الصَّبُور"},
    "sabira": {"en": "Sabira; patient, enduring (feminine)", "ur": "صابرہ، صبر کرنے والی", "fa": "صابره، شکیبا", "hi": "साबिरा, धैर्यवान", "ps": "صابره، صبر کوونکې", "ar": "صَابِرَة، الصَّابِرَة"},
    "sabit": {"en": "Sabit; firm, steadfast", "ur": "ثابت، مضبوط", "fa": "ثابت، استوار", "hi": "साबित, दृढ़", "ps": "ثابت، ټینګ", "ar": "الثَّابِت، الرَّاسِخ"},
    "sabiya": {"en": "Sabiya; a female given name", "ur": "سبیہ (زنانہ نام)", "fa": "سبیه (نام زنانه)", "hi": "सबिया (स्त्री नाम)", "ps": "سبیه (ښځينه نوم)", "ar": "سَبِيَّة (اسْم عَلَم مُؤَنَّث)"},
    "saboor": {"en": "Saboor; very patient, enduring", "ur": "صبور، بہت صابر", "fa": "صبور، بسیار شکیبا", "hi": "सबूर, धैर्यवान", "ps": "صبور، ډېر صابر", "ar": "الصَّبُور، الصَّابِر"},
    "sabr": {"en": "Sabr; patience, endurance", "ur": "صبر، تحمل", "fa": "صبر، شکیبایی", "hi": "सब्र, धैर्य", "ps": "صبر، صبر", "ar": "الصَّبْر، التَّحَمُّل"},
    "sabra": {"en": "Sabra; a female given name (Hebrew)", "ur": "صبرا (زنانہ نام)", "fa": "صبرا (نام زنانه)", "hi": "सब्रा (स्त्री नाम)", "ps": "صبرا (ښځينه نوم)", "ar": "صَبْرَا (اسْم عَلَم عِبْرِيّ)"},
    "sabreen": {"en": "Sabreen; patient ones (plural)", "ur": "صابرین، صبر کرنے والے", "fa": "صابرین، شکیبایان", "hi": "साबिरीन, धैर्यवान", "ps": "صابرین، صبر کوونکي", "ar": "الصَّابِرِين، الصَّابِرُون"},
    "sabreena": {"en": "Sabreena; a female given name", "ur": "صابرینہ (زنانہ نام)", "fa": "صابرینا (نام زنانه)", "hi": "सबरीना (स्त्री नाम)", "ps": "صابرینا (ښځينه نوم)", "ar": "صَابْرِينَا (اسْم عَلَم مُؤَنَّث)"},
    "sabri": {"en": "Sabri; patient, enduring (relational)", "ur": "صبری، صبر سے منسوب", "fa": "صبری، منسوب به صبر", "hi": "सब्र, धैर्य से संबंधित", "ps": "صبري، د صبر اړوند", "ar": "الصَّبْرِي، مَنْسُوب إِلَى الصَّبْر"},
    "sabria": {"en": "Sabria; patient, enduring (feminine)", "ur": "صبریہ، صبر کرنے والی", "fa": "صبریه، شکیبا", "hi": "सबरिया, धैर्यवान", "ps": "صبریه، صبر کوونکې", "ar": "صَبْرِيَّة، الصَّابِرَة"},
    "sabrin": {"en": "Sabrin; patient ones (plural)", "ur": "صابرین، صبر کرنے والے", "fa": "صابرین، شکیبایان", "hi": "साबरीन, धैर्यवान", "ps": "صابرین، صبر کوونکي", "ar": "الصَّابِرِين، الصَّابِرُون"},
    "sabrine": {"en": "Sabrine; a female given name", "ur": "صابرین (زنانہ نام)", "fa": "صابرین (نام زنانه)", "hi": "सबरीन (स्त्री नाम)", "ps": "صابرین (ښځينه نوم)", "ar": "صَابْرِين (اسْم عَلَم مُؤَنَّث)"},
    "sabuhi": {"en": "Sabuhi; morning-like (Turkish)", "ur": "صبوحی، صبح سے منسوب", "fa": "صبوحی، منسوب به صبح", "hi": "सबूही, प्रभात से संबंधित", "ps": "صبوحي، د سهار اړوند", "ar": "صَبُوحِي، مَنْسُوب إِلَى الصَّبَاح"},
    "sabur": {"en": "Sabur; very patient, enduring", "ur": "صبور، بہت صابر", "fa": "صبور، بسیار شکیبا", "hi": "सबूर, धैर्यवान", "ps": "صبور، ډېر صابر", "ar": "الصَّبُور، الصَّابِر"},
    "sadaf": {"en": "Sadaf; shell, mother-of-pearl", "ur": "صدف، سیپ", "fa": "صدف، صدف", "hi": "सदफ़, सीप", "ps": "صدف، صدف", "ar": "الصَّدَف، الْمَحَار"},
    "sadah": {"en": "Sadah; a female given name", "ur": "سدہ (زنانہ نام)", "fa": "سده (نام زنانه)", "hi": "सदा (स्त्री नाम)", "ps": "سده (ښځينه نوم)", "ar": "سَدَة (اسْم عَلَم مُؤَنَّث)"},
    "sadam": {"en": "Sadam; a male given name", "ur": "صدام (مردانہ نام)", "fa": "صدام (نام مردانه)", "hi": "सदाम (पुरुष नाम)", "ps": "صدام (نر نوم)", "ar": "صَدَام (اسْم عَلَم مُذَكَّر)"},
    "sadan": {"en": "Sadan; happy, fortunate", "ur": "سعدان، خوش نصیب", "fa": "سعدان، خوشبخت", "hi": "सादान, प्रसन्न", "ps": "سعدان، خوشحاله", "ar": "سَعْدَان، السَّعِيد"},
    "sadaqat": {"en": "Sadaqat; charity, alms (plural)", "ur": "صدقات، خیرات", "fa": "صدقات، خیرات", "hi": "सदक़ात, दान", "ps": "صدقات، خیرات", "ar": "الصَّدَقَات، الصَّدَقَة"},
    "sadat": {"en": "Sadat; lords, masters (plural)", "ur": "سادات، سردار", "fa": "سادات، سروران", "hi": "सादात, सरदार", "ps": "سادات، مشران", "ar": "السَّادَات، السَّيِّد"},
    "saddam": {"en": "Saddam; a male given name", "ur": "صدام (مردانہ نام)", "fa": "صدام (نام مردانه)", "hi": "सद्दाम (पुरुष नाम)", "ps": "صدام (نر نوم)", "ar": "صَدَّام (اسْم عَلَم مُذَكَّر)"},
    "sadeem": {"en": "Sadeem; a female given name", "ur": "سدیم (زنانہ نام)", "fa": "سدیم (نام زنانه)", "hi": "सदीम (स्त्री नाम)", "ps": "سدیم (ښځينه نوم)", "ar": "سَدِيم (اسْم عَلَم مُؤَنَّث)"},
    "sadeen": {"en": "Sadeen; a female given name", "ur": "سدین (زنانہ نام)", "fa": "سدین (نام زنانه)", "hi": "सदीन (स्त्री नाम)", "ps": "سدین (ښځينه نوم)", "ar": "سَدِين (اسْم عَلَم مُؤَنَّث)"},
    "sadeeq": {"en": "Sadeeq; truthful, sincere", "ur": "صدیق، سچا", "fa": "صدیق، راستگو", "hi": "सदीक़, सच्चा", "ps": "صدیق، رښتونی", "ar": "الصَّدِيق، الصَّادِق"},
    "sadegh": {"en": "Sadegh; truthful, sincere (Persian)", "ur": "صادق، سچا", "fa": "صادق، راستگو", "hi": "सादेग़, सच्चा", "ps": "صادق، رښتونی", "ar": "الصَّادِق، الصِّدْق"},
    "sadi": {"en": "Sadi; fortunate, happy", "ur": "سعدی، خوش نصیب", "fa": "سعدی، خوشبخت", "hi": "सादी, भाग्यशाली", "ps": "سعدي، نیکمرغه", "ar": "السَّعْدِي، السَّعِيد"},
    "sadia": {"en": "Sadia; happy, fortunate (feminine)", "ur": "سعدیہ، خوش نصیب", "fa": "سعدیه، خوشبخت", "hi": "सादिया, प्रसन्न", "ps": "سعدیه، خوشحاله", "ar": "سَعْدِيَّة، السَّعِيدَة"},
    "sadiah": {"en": "Sadiah; happy, fortunate (feminine)", "ur": "سادیہ، خوش نصیب", "fa": "سادیه، خوشبخت", "hi": "सादिया, प्रसन्न", "ps": "سادیه، خوشحاله", "ar": "سَادِيَة، السَّعِيدَة"},
    "sadid": {"en": "Sadid; sound, correct", "ur": "سدید، درست", "fa": "سدید، درست", "hi": "सदीद, सही", "ps": "سدید، سم", "ar": "السَّدِيد، الصَّوَاب"},
    "sadik": {"en": "Sadik; truthful, sincere", "ur": "صادق، سچا", "fa": "صادق، راستگو", "hi": "सादिक़, सच्चा", "ps": "صادق، رښتونی", "ar": "الصَّادِق، الصِّدْق"},
    "sadika": {"en": "Sadika; truthful, sincere (feminine)", "ur": "صادقہ، سچی", "fa": "صادقه، راستگو", "hi": "सादिक़ा, सच्ची", "ps": "صادقه، رښتونې", "ar": "صَادِقَة، الصَّادِقَة"},
    "sadin": {"en": "Sadin; a male given name", "ur": "سادن (مردانہ نام)", "fa": "سادن (نام مردانه)", "hi": "सादिन (पुरुष नाम)", "ps": "سادن (نر نوم)", "ar": "سَادِن (اسْم عَلَم مُذَكَّر)"},
    "sadiq": {"en": "Sadiq; truthful, sincere", "ur": "صادق، سچا", "fa": "صادق، راستگو", "hi": "सादिक़, सच्चा", "ps": "صادق، رښتونی", "ar": "الصَّادِق، الصِّدْق"},
    "sadiqa": {"en": "Sadiqa; truthful, sincere (feminine)", "ur": "صادقہ، سچی", "fa": "صادقه، راستگو", "hi": "सादिक़ा, सच्ची", "ps": "صادقه، رښتونې", "ar": "صَادِقَة، الصَّادِقَة"},
    "sadir": {"en": "Sadir; a male given name", "ur": "سدیر (مردانہ نام)", "fa": "سدیر (نام مردانه)", "hi": "सदीर (पुरुष नाम)", "ps": "سدیر (نر نوم)", "ar": "سَدِير (اسْم عَلَم مُذَكَّر)"},
    "sadit": {"en": "Sadit; a female given name", "ur": "سدیت (زنانہ نام)", "fa": "سدیت (نام زنانه)", "hi": "सदित (स्त्री नाम)", "ps": "سدیت (ښځينه نوم)", "ar": "سَدِيت (اسْم عَلَم مُؤَنَّث)"},
    "sadiya": {"en": "Sadiya; happy, fortunate (feminine)", "ur": "سعدیہ، خوش نصیب", "fa": "سعدیه، خوشبخت", "hi": "सादिया, प्रसन्न", "ps": "سعدیه، خوشحاله", "ar": "سَعْدِيَّة، السَّعِيدَة"},
    "sadiyah": {"en": "Sadiyah; happy, fortunate (feminine)", "ur": "سادیہ، خوش نصیب", "fa": "سادیه، خوشبخت", "hi": "सादिया, प्रसन्न", "ps": "سادیه، خوشحاله", "ar": "سَادِيَة، السَّعِيدَة"},
    "sadq": {"en": "Sadq; truthfulness, sincerity", "ur": "صدق، سچائی", "fa": "صدق، راستی", "hi": "सदक़, सच्चाई", "ps": "صدق، رښتیا", "ar": "الصِّدْق، الصَّدَاقَة"},
    "sadr": {"en": "Sadr; chest, foremost part; chief", "ur": "صدر، سینہ، سربراہ", "fa": "صدر، سینه، رئیس", "hi": "सद्र, वक्ष, प्रमुख", "ps": "صدر، سینه، مشر", "ar": "الصَّدْر، الرَّئِيس"},
    "sadra": {"en": "Sadra; a female given name (Persian)", "ur": "صدرا (زنانہ نام)", "fa": "صدرا (نام زنانه)", "hi": "सदरा (स्त्री नाम)", "ps": "صدرا (ښځينه نوم)", "ar": "صَدْرَا (اسْم عَلَم فَارِسِيّ)"},
    "sadri": {"en": "Sadri; of the chest, foremost (relational)", "ur": "صدری، صدر سے منسوب", "fa": "صدری، منسوب به صدر", "hi": "सद्री, सद्र से संबंधित", "ps": "صدري، د صدر اړوند", "ar": "الصَّدْرِي، مَنْسُوب إِلَى الصَّدْر"},
    "sadruddin": {"en": "Sadruddin; foremost of the faith", "ur": "صدرالدین، دین کا سربراہ", "fa": "صدرالدین، پیشوای دین", "hi": "सदरुद्दीन, धर्म का प्रमुख", "ps": "صدرالدین، د دین مشر", "ar": "صَدْرُ الدِّين (الْإِضَافَة)"},
    "sadun": {"en": "Sadun; a male given name", "ur": "سعدون (مردانہ نام)", "fa": "سعدون (نام مردانه)", "hi": "सादून (पुरुष नाम)", "ps": "سعدون (نر نوم)", "ar": "سَعْدُون (اسْم عَلَم مُذَكَّر)"},
    "saee": {"en": "Saee; effort, striving", "ur": "سعی، کوشش", "fa": "سعی، کوشش", "hi": "सई, प्रयास", "ps": "سعي، هڅه", "ar": "السَّعْي، الْجُهْد"},
    "saeed": {"en": "Saeed; happy, fortunate", "ur": "سعید، خوش نصیب", "fa": "سعید، خوشبخت", "hi": "सईद, प्रसन्न", "ps": "سعید، خوشحاله", "ar": "السَّعِيد، السَّعَادَة"},
    "saeeda": {"en": "Saeeda; happy, fortunate (feminine)", "ur": "سعیدہ، خوش نصیب", "fa": "سعیده، خوشبخت", "hi": "सईदा, प्रसन्न", "ps": "سعیده، خوشحاله", "ar": "سَعِيدَة، السَّعِيدَة"},
    "safa": {"en": "Safa; purity, clarity", "ur": "صفا، پاکیزگی", "fa": "صفا، پاکی", "hi": "सफ़ा, पवित्रता", "ps": "صفا، پاکوالی", "ar": "الصَّفَا، الصَّفَاء"},
    "safaa": {"en": "Safaa; purity, clarity", "ur": "صفاء، پاکیزگی", "fa": "صفاء، پاکی", "hi": "सफ़ा, पवित्रता", "ps": "صفاء، پاکوالی", "ar": "الصَّفَاء، النَّقَاء"},
    "safar": {"en": "Safar; journey, travel", "ur": "سفر، سفر", "fa": "سفر، سفر", "hi": "सफ़र, यात्रा", "ps": "سفر، سفر", "ar": "السَّفَر، الرِّحْلَة"},
    "safdar": {"en": "Safdar; a male given name (Persian)", "ur": "صفدر (مردانہ نام)", "fa": "صفدر (نام مردانه)", "hi": "सफ़दर (पुरुष नाम)", "ps": "صفدر (نر نوم)", "ar": "صَفْدَر (اسْم عَلَم فَارِسِيّ)"},
    "safee": {"en": "Safee; pure, clear", "ur": "صفی، خالص", "fa": "صفی، پاک", "hi": "सफ़ी, शुद्ध", "ps": "صفي، پاک", "ar": "الصَّفِي، النَّقِيّ"},
    "safeena": {"en": "Safeena; ship, vessel", "ur": "سفینہ، کشتی", "fa": "سفینه، کشتی", "hi": "सफ़ीना, जहाज़", "ps": "سفینه، بېړۍ", "ar": "السَّفِينَة، الْفُلْك"},
    "safeenah": {"en": "Safeenah; ship, vessel", "ur": "سفینہ، کشتی", "fa": "سفینه، کشتی", "hi": "सफ़ीना, जहाज़", "ps": "سفینه، بېړۍ", "ar": "السَّفِينَة، الْفُلْك"},
    "safeer": {"en": "Safeer; ambassador, envoy", "ur": "سفیر، ایلچی", "fa": "سفیر، فرستاده", "hi": "सफ़ीर, दूत", "ps": "سفیر، استازی", "ar": "السَّفِير، الرَّسُول"},
    "safeera": {"en": "Safeera; ambassador, envoy (feminine)", "ur": "سفیرہ، ایلچی", "fa": "سفیره، فرستاده", "hi": "सफ़ीरा, दूत", "ps": "سفیره، استازې", "ar": "سَفِيرَة، السَّفِيرَة"},
    "saffa": {"en": "Saffa; a female given name", "ur": "صفا (زنانہ نام)", "fa": "صفا (نام زنانه)", "hi": "सफ़्फ़ा (स्त्री नाम)", "ps": "صفا (ښځينه نوم)", "ar": "صَفَّا (اسْم عَلَم مُؤَنَّث)"},
    "saffan": {"en": "Saffan; pure, clear", "ur": "صفان، خالص", "fa": "صفان، پاک", "hi": "सफ़्फ़ान, शुद्ध", "ps": "صفان، پاک", "ar": "صِفَان، الصَّافِي"},
    "saffron": {"en": "Saffron; the saffron spice (English)", "ur": "زعفران، کیسر", "fa": "زعفران، زعفران", "hi": "ज़ाफ़रान, केसर", "ps": "زعفران، زعفران", "ar": "الزَّعْفَرَان"},
    "safi": {"en": "Safi; pure, clear", "ur": "صفی، خالص", "fa": "صفی، پاک", "hi": "सफ़ी, शुद्ध", "ps": "صفي، پاک", "ar": "الصَّفِي، النَّقِيّ"},
    "safia": {"en": "Safia; pure, clear (feminine)", "ur": "صفیہ، خالص", "fa": "صفیه، پاک", "hi": "सफ़िया, शुद्ध", "ps": "صفیه، پاکه", "ar": "صَفِيَّة، الصَّفِيَّة"},
    "safin": {"en": "Safin; pure, clear", "ur": "صفی، خالص", "fa": "صفی، پاک", "hi": "सफ़ीन, शुद्ध", "ps": "صفي، پاک", "ar": "الصَّفِي، النَّقِيّ"},
    "safina": {"en": "Safina; ship, vessel", "ur": "سفینہ، کشتی", "fa": "سفینه، کشتی", "hi": "सफ़ीना, जहाज़", "ps": "سفینه، بېړۍ", "ar": "السَّفِينَة، الْفُلْك"},
    "safinaz": {"en": "Safinaz; a female given name", "ur": "سفیناز (زنانہ نام)", "fa": "سفیناز (نام زنانه)", "hi": "सफ़ीनाज़ (स्त्री नाम)", "ps": "سفیناز (ښځينه نوم)", "ar": "سَفِينَاز (اسْم عَلَم مُؤَنَّث)"},
    "safir": {"en": "Safir; ambassador, envoy", "ur": "سفیر، ایلچی", "fa": "سفیر، فرستاده", "hi": "सफ़ीर, दूत", "ps": "سفیر، استازی", "ar": "السَّفِير، الرَّسُول"},
    "safira": {"en": "Safira; ambassador, envoy (feminine)", "ur": "سفیرہ، ایلچی", "fa": "سفیره، فرستاده", "hi": "सफ़ीरा, दूत", "ps": "سفیره، استازې", "ar": "سَفِيرَة، السَّفِيرَة"},
    "safiya": {"en": "Safiya; pure, clear (feminine)", "ur": "صفیہ، خالص", "fa": "صفیه، پاک", "hi": "सफ़िया, शुद्ध", "ps": "صفیه، پاکه", "ar": "صَفِيَّة، الصَّفِيَّة"},
    "safiyah": {"en": "Safiyah; pure, clear (feminine)", "ur": "صفیہ، خالص", "fa": "صفیه، پاک", "hi": "सफ़िया, शुद्ध", "ps": "صفیه، پاکه", "ar": "صَفِيَّة، الصَّفِيَّة"},
    "safiyya": {"en": "Safiyya; pure, clear (feminine)", "ur": "صفیہ، خالص", "fa": "صفیه، پاک", "hi": "सफ़िया, शुद्ध", "ps": "صفیه، پاکه", "ar": "صَفِيَّة، الصَّفِيَّة"},
    "safiyyah": {"en": "Safiyyah; pure, clear (feminine)", "ur": "صفیہ، خالص", "fa": "صفیه، پاک", "hi": "सफ़िया, शुद्ध", "ps": "صفیه، پاکه", "ar": "صَفِيَّة، الصَّفِيَّة"},
    "safura": {"en": "Safura; a female given name", "ur": "صفورہ (زنانہ نام)", "fa": "صفوره (نام زنانه)", "hi": "सफ़ूरा (स्त्री नाम)", "ps": "صفوره (ښځينه نوم)", "ar": "صَفُورَة (اسْم عَلَم مُؤَنَّث)"},
    "safwa": {"en": "Safwa; purity, the choicest part", "ur": "صفوہ، خالص", "fa": "صفوه، برگزیده", "hi": "सफ़वा, शुद्ध", "ps": "صفوه، غوره", "ar": "الصَّفْوَة، الْخَالِص"},
})

CUR = {
 "sabawoon": ("سَبَاوُون", "سباوون", "سباوون", "सबावून", "سباوون", "sabawoon", "Pashto", "Male",
              "Pashto سباوون (sabāwūn)", False, "medium",
              "Sabawoon is a Pashto male given name. CRITICAL SOURCE ERROR: the source gave سبأون (a non-standard form) and labelled the origin Arabic; the name is Pashto. The source gloss 'The Bright Moon' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabbagh": ("صَبَّاغ", "صباغ", "صباغ", "सब्बाग़", "صباغ", "sabbagh", "Arabic", "Male",
             "Arabic root ص ب غ (ṣ-b-gh); صَبَّاغ (Ṣabbāgh)", False, "high",
             "Sabbagh is Arabic صَبَّاغ (Ṣabbāgh) 'dyer', an occupational name from the root ص ب غ (ṣ-b-gh). CRITICAL SOURCE ERROR: the source gave سباغ (a non-standard form). The source gloss 'Little One' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "sabbir": ("صَبِير", "صابر", "صابر", "सब्बीर", "صابر", "sabbir", "Arabic", "Male",
            "Arabic root ص ب ر (ṣ-b-r); صَبِير (Ṣabīr)", False, "high",
            "Sabbir is a spelling variant of Arabic صَبِير (Ṣabīr) 'patient, enduring', from the root ص ب ر (ṣ-b-r). CRITICAL SOURCE ERROR: the source gave سببر (a non-standard form). The source gloss 'Supplier, Provider' is unsupported and has been replaced with the lexical sense. Same name as sabir."),
 "sabeeh": ("صَبِيح", "صبیح", "صبیح", "सबीह", "صبیح", "sabeeh", "Arabic", "Male",
            "Arabic root ص ب ح (ṣ-b-ḥ); صَبِيح (Ṣabīḥ)", False, "high",
            "Sabeeh is Arabic صَبِيح (Ṣabīḥ) 'beautiful, handsome', from the root ص ب ح (ṣ-b-ḥ). The source gloss 'Pure, Clear' is unsupported and has been replaced with the lexical sense. Same name as sabih."),
 "sabeeha": ("صَبِيحَة", "صبیحہ", "صبیحه", "सबीहा", "صبیحه", "sabeeha", "Arabic", "Female",
             "Arabic root ص ب ح (ṣ-b-ḥ); صَبِيحَة (Ṣabīḥa)", False, "high",
             "Sabeeha is Arabic صَبِيحَة (Ṣabīḥa) 'beautiful' (feminine), from the root ص ب ح (ṣ-b-ḥ). The source gloss 'Beautiful' is consistent. Same name as sabiha."),
 "sabeeka": ("سَبِيكَة", "سبیکہ", "سبیکه", "सबीका", "سبیکه", "sabeeka", "Arabic", "Female",
             "Arabic سَبِيكَة (Sabīka)", False, "medium",
             "Sabeeka is recorded as Arabic سَبِيكَة (Sabīka), a female given name. CRITICAL SOURCE ERROR: the source gave سبي كة (a broken form). The source gloss 'Seeker, Lover' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabeel": ("سَبِيل", "سبیل", "سبیل", "सबील", "سبیل", "sabeel", "Arabic", "Male",
            "Arabic root س ب ل (s-b-l); سَبِيل (Sabīl)", False, "high",
            "Sabeel is Arabic سَبِيل (Sabīl) 'way, path', from the root س ب ل (s-b-l). CRITICAL SOURCE ERROR: the source gave the Latin string 'Sabeel' instead of a script form. The source gloss 'Well, canal, path to water' is broadly consistent. Same name as sabil."),
 "sabeen": ("سَبِين", "سبین", "سبین", "सबीन", "سبین", "sabeen", "Arabic", "Female",
            "Arabic سَبِين (Sabīn)", False, "medium",
            "Sabeen is recorded as Arabic سَبِين (Sabīn), a female given name. The source gloss 'Peaceful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabeena": ("سَابِينَا", "سبینہ", "سبینا", "सबीना", "سبینا", "sabeena", "Arabic", "Female",
             "Arabic سَابِينَا (Sābīnā)", False, "medium",
             "Sabeena is recorded as Arabic سَابِينَا (Sābīnā), a female given name. The source gloss 'Moon, radiant, beautiful' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabeer": ("صَبِير", "صابر", "صابر", "सबीर", "صابر", "sabeer", "Arabic", "Male",
            "Arabic root ص ب ر (ṣ-b-r); صَبِير (Ṣabīr)", False, "high",
            "Sabeer is a spelling variant of Arabic صَبِير (Ṣabīr) 'patient, enduring', from the root ص ب ر (ṣ-b-r). The source gloss 'Knowledgeable' is unsupported and has been replaced with the lexical sense. Same name as sabir."),
 "sabeha": ("سَبِيهَة", "سبیہہ", "سبیحه", "सबीहा", "سبیحه", "sabeha", "Arabic", "Female",
            "Arabic سَبِيهَة (Sabīha)", False, "medium",
            "Sabeha is recorded as Arabic سَبِيهَة (Sabīha), a female given name. The source gloss 'Patient' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "saber": ("صَابِر", "صابر", "صابر", "साबिर", "صابر", "saber", "Arabic", "Male",
           "Arabic root ص ب ر (ṣ-b-r); صَابِر (Ṣābir)", False, "high",
           "Saber is a spelling variant of Arabic صَابِر (Ṣābir) 'patient, enduring', from the root ص ب ر (ṣ-b-r). The source gloss 'Sword' is unsupported and has been replaced with the lexical sense. Same name as sabir."),
 "sabera": ("صَابِرَة", "صابرہ", "صابره", "साबिरा", "صابره", "sabera", "Arabic", "Female",
            "Arabic root ص ب ر (ṣ-b-r); صَابِرَة (Ṣābira)", False, "high",
            "Sabera is Arabic صَابِرَة (Ṣābira) 'patient, enduring' (feminine), from the root ص ب ر (ṣ-b-r). The source gloss 'Intelligent' is unsupported and has been replaced with the lexical sense. Same name as sabira."),
 "sabha": ("سَبْحَة", "سبحہ", "سبحه", "सबहा", "سبحه", "sabha", "Arabic", "Female",
           "Arabic root س ب ح (s-b-ḥ); سَبْحَة (Sabḥa)", False, "high",
           "Sabha is Arabic سَبْحَة (Sabḥa), a female given name from the root س ب ح (s-b-ḥ). The source gloss 'Mountain, hill, mound' is unsupported and has been replaced with the documented identification."),
 "sabi": ("سَابِي", "سبی", "سبی", "सबी", "سبي", "sabi", "Hebrew", "Male",
          "Hebrew סבי (Sabi)", False, "medium",
          "Sabi is a Hebrew male given name. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the name is Hebrew. The source gloss 'Old, Ancient, Wise, Patient' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. The identification is recorded at medium confidence."),
 "sabia": ("سَبِيعَة", "سبیعہ", "سبیعه", "सबिया", "سبیعه", "sabia", "Arabic", "Female",
           "Arabic سَبِيعَة (Sabīʿa)", False, "medium",
           "Sabia is recorded as Arabic سَبِيعَة (Sabīʿa), a female given name. The source gloss 'Intelligent, Wise' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabih": ("صَبِيح", "صبیح", "صبیح", "सबीह", "صبیح", "sabih", "Arabic", "Male",
           "Arabic root ص ب ح (ṣ-b-ḥ); صَبِيح (Ṣabīḥ)", False, "high",
           "Sabih is Arabic صَبِيح (Ṣabīḥ) 'beautiful, handsome', from the root ص ب ح (ṣ-b-ḥ). CRITICAL SOURCE ERROR: the source gave سبح (a different form). The source gloss 'Patient, Steadfast' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "sabiha": ("صَبِيحَة", "صبیحہ", "صبیحه", "सबीहा", "صبیحه", "sabiha", "Arabic", "Female",
            "Arabic root ص ب ح (ṣ-b-ḥ); صَبِيحَة (Ṣabīḥa)", False, "high",
            "Sabiha is Arabic صَبِيحَة (Ṣabīḥa) 'beautiful' (feminine), from the root ص ب ح (ṣ-b-ḥ). The source gloss 'Bringer of Glad Tidings' is unsupported and has been replaced with the lexical sense. Same name as sabeeha."),
 "sabika": ("سَبِيكَة", "سبیکہ", "سبیکا", "सबीका", "سبیکا", "sabika", "Arabic", "Female",
            "Arabic سَبِيكَة (Sabīka)", False, "medium",
            "Sabika is recorded as Arabic سَبِيكَة (Sabīka), a female given name. The source gloss 'Little One' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as sabeeka."),
 "sabil": ("سَبِيل", "سبیل", "سبیل", "सबील", "سبیل", "sabil", "Arabic", "Male",
           "Arabic root س ب ل (s-b-l); سَبِيل (Sabīl)", False, "high",
           "Sabil is Arabic سَبِيل (Sabīl) 'way, path', from the root س ب ل (s-b-l). The source gloss 'Path, Way, Road' is consistent."),
 "sabir": ("صَابِر", "صابر", "صابر", "साबिर", "صابر", "sabir", "Arabic", "Male",
           "Arabic root ص ب ر (ṣ-b-r); صَابِر (Ṣābir)", False, "high",
           "Sabir is Arabic صَابِر (Ṣābir) 'patient, enduring', from the root ص ب ر (ṣ-b-r). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "sabira": ("صَابِرَة", "صابرہ", "صابره", "साबिरा", "صابره", "sabira", "Arabic", "Female",
            "Arabic root ص ب ر (ṣ-b-r); صَابِرَة (Ṣābira)", False, "high",
            "Sabira is Arabic صَابِرَة (Ṣābira) 'patient, enduring' (feminine), from the root ص ب ر (ṣ-b-r). The source gloss 'Patient, Enduring' is consistent."),
 "sabit": ("ثَابِت", "ثابت", "ثابت", "साबित", "ثابت", "sabit", "Arabic", "Male",
           "Arabic root ث ب ت (th-b-t); ثَابِت (Thābit)", False, "high",
           "Sabit is a spelling variant of Arabic ثَابِت (Thābit) 'firm, steadfast', from the root ث ب ت (th-b-t). CRITICAL SOURCE ERROR: the source gave صَابِط (a different form). The source gloss 'Firm, Strong, Steadfast' is consistent. Same name as thabit."),
 "sabiya": ("سَبِيَّة", "سبیہ", "سبیه", "सबिया", "سبیه", "sabiya", "Arabic", "Female",
            "Arabic سَبِيَّة (Sabiyya)", False, "medium",
            "Sabiya is recorded as Arabic سَبِيَّة (Sabiyya), a female given name. The source gloss 'Patient' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "saboor": ("صَبُور", "صبور", "صبور", "सबूर", "صبور", "saboor", "Arabic", "Male",
            "Arabic root ص ب ر (ṣ-b-r); صَبُور (Ṣabūr)", False, "high",
            "Saboor is Arabic صَبُور (Ṣabūr) 'very patient, enduring', an intensive form from the root ص ب ر (ṣ-b-r). The source gloss 'Patient, Steadfast' is broadly consistent. Same name as sabur."),
 "sabr": ("صَبْر", "صبر", "صبر", "सब्र", "صبر", "sabr", "Arabic", "Male",
          "Arabic root ص ب ر (ṣ-b-r); صَبْر (Ṣabr)", False, "high",
          "Sabr is Arabic صَبْر (Ṣabr) 'patience, endurance', from the root ص ب ر (ṣ-b-r). The source gloss 'Patience, endurance' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "sabra": ("صَبْرَا", "صبرا", "صبرا", "सब्रा", "صبرا", "sabra", "Hebrew", "Female",
           "Hebrew צברה (Sabra)", False, "medium",
           "Sabra is a Hebrew female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Hebrew. The source gloss 'Fruit, Sweet' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabreen": ("صَابِرِين", "صابرین", "صابرین", "साबिरीन", "صابرین", "sabreen", "Arabic", "Female",
             "Arabic root ص ب ر (ṣ-b-r); صَابِرِين (Ṣābirīn)", False, "high",
             "Sabreen is Arabic صَابِرِين (Ṣābirīn) 'patient ones', the plural of صَابِر (ṣābir), used as a female given name. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as sabrin."),
 "sabreena": ("صَابْرِينَا", "صابرینہ", "صابرینا", "सबरीना", "صابرینا", "sabreena", "Arabic", "Female",
              "Arabic صَابْرِينَا (Ṣābrīnā)", False, "medium",
              "Sabreena is recorded as Arabic صَابْرِينَا (Ṣābrīnā), a female given name. The source gloss 'Moonlight' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sabri": ("صَبْرِي", "صبری", "صبری", "सबरी", "صبري", "sabri", "Arabic", "Male",
           "Arabic صَبْرِي (Ṣabrī) 'of patience'", False, "high",
           "Sabri is Arabic صَبْرِي (Ṣabrī) 'of patience', a relational adjective from صَبْر (ṣabr). CRITICAL SOURCE ERROR: the source gave سابر ى (a broken form). The source gloss 'Patience, Endurance' is broadly consistent."),
 "sabria": ("صَبْرِيَّة", "صبریہ", "صبریه", "सबरिया", "صبریه", "sabria", "Arabic", "Female",
            "Arabic صَبْرِيَّة (Ṣabriyya) 'of patience' (feminine)", False, "high",
            "Sabria is Arabic صَبْرِيَّة (Ṣabriyya) 'of patience' (feminine), a relational adjective from صَبْر (ṣabr). The source gloss 'Intelligent, Wise' is unsupported and has been replaced with the lexical sense."),
 "sabrin": ("صَابِرِين", "صابرین", "صابرین", "साबरीन", "صابرین", "sabrin", "Arabic", "Female",
            "Arabic root ص ب ر (ṣ-b-r); صَابِرِين (Ṣābirīn)", False, "high",
            "Sabrin is Arabic صَابِرِين (Ṣābirīn) 'patient ones', the plural of صَابِر (ṣābir), used as a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Sabrin' instead of a script form. The source gloss 'Moon' is unsupported and has been replaced with the lexical sense. Same name as sabreen."),
 "sabrine": ("صَابْرِين", "صابرین", "صابرین", "सबरीन", "صابرین", "sabrine", "Arabic", "Female",
             "Arabic root ص ب ر (ṣ-b-r); صَابِرِين (Ṣābirīn)", False, "high",
             "Sabrine is a spelling variant of Arabic صَابِرِين (Ṣābirīn) 'patient ones', used as a female given name. The source gloss 'Patient, gentle, and beautiful' is unsupported and has been replaced with the lexical sense. Same name as sabrin."),
 "sabuhi": ("صَبُوحِي", "صبوحی", "صبوحی", "सबूही", "صبوحي", "sabuhi", "Turkish", "Male",
            "Turkish Sabuhi, from Arabic صَبُوحِي", False, "high",
            "Sabuhi is the Turkish form of Arabic صَبُوحِي (Ṣabūḥī) 'morning-like', a relational adjective from صَبَاح (ṣabāḥ). CRITICAL SOURCE ERROR: the source gave سبحة (a different form) and labelled the origin Arabic; the name as used is Turkish. The source gloss 'Companion, Helper' is unsupported and has been replaced with the lexical sense."),
 "sabur": ("صَبُور", "صبور", "صبور", "सबूर", "صبور", "sabur", "Arabic", "Male",
           "Arabic root ص ب ر (ṣ-b-r); صَبُور (Ṣabūr)", False, "high",
           "Sabur is Arabic صَبُور (Ṣabūr) 'very patient, enduring', an intensive form from the root ص ب ر (ṣ-b-r). The source gloss 'Patient, Enduring' is consistent. Same name as saboor."),
 "sadaf": ("صَدَف", "صدف", "صدف", "सदफ़", "صدف", "sadaf", "Arabic", "Female",
           "Arabic root ص د ف (ṣ-d-f); صَدَف (Ṣadaf)", False, "high",
           "Sadaf is Arabic صَدَف (Ṣadaf) 'shell, mother-of-pearl', from the root ص د ف (ṣ-d-f). CRITICAL SOURCE ERROR: the source gave 'عربي_Sadaf' (a placeholder prefix); the correct form is صَدَف. The source gloss 'Noble and blessed' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender male; documented usage is predominantly female."),
 "sadah": ("سَدَة", "سدہ", "سده", "सदा", "سده", "sadah", "Arabic", "Female",
           "Arabic سَدَة (Sada)", False, "medium",
           "Sadah is recorded as Arabic سَدَة (Sada), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Sadah' instead of a script form. The source gloss 'Meadow' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadam": ("صَدَام", "صدام", "صدام", "सदाम", "صدام", "sadam", "Arabic", "Male",
           "Arabic صَدَام (Ṣadām)", False, "high",
           "Sadam is a spelling variant of Arabic صَدَام (Ṣadām), a male given name. The source gloss 'One who confronts, Brave' is unsupported and has been replaced with the documented identification. Same name as saddam."),
 "sadan": ("سَعْدَان", "سعدان", "سعدان", "सादान", "سعدان", "sadan", "Arabic", "Male",
           "Arabic root س ع د (s-ʿ-d); سَعْدَان (Saʿdān)", False, "high",
           "Sadan is a spelling variant of Arabic سَعْدَان (Saʿdān) 'happy, fortunate', from the root س ع د (s-ʿ-d). CRITICAL SOURCE ERROR: the source gave the Latin string \"Sa'dān\" instead of a script form. The source gloss 'Fortunate, Lucky' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as saadan."),
 "sadaqat": ("صَدَقَات", "صدقات", "صدقات", "सदक़ात", "صدقات", "sadaqat", "Arabic", "Female",
             "Arabic root ص د ق (ṣ-d-q); صَدَقَات (Ṣadaqāt)", False, "high",
             "Sadaqat is Arabic صَدَقَات (Ṣadaqāt) 'charity, alms', the plural of صَدَقَة (ṣadaqa). The source gloss 'Charity, Benevolence' is consistent."),
 "sadat": ("سَادَات", "سادات", "سادات", "सादात", "سادات", "sadat", "Arabic", "Female",
           "Arabic root س و د (s-w-d); سَادَات (Sādāt)", False, "high",
           "Sadat is Arabic سَادَات (Sādāt) 'lords, masters', the plural of سَيِّد (sayyid). CRITICAL SOURCE ERROR: the source gave صادَت (a non-standard form). The source gloss 'Ruler, Lady' is broadly consistent."),
 "saddam": ("صَدَّام", "صدام", "صدام", "सद्दाम", "صدام", "saddam", "Arabic", "Male",
            "Arabic صَدَّام (Ṣaddām)", False, "high",
            "Saddam is Arabic صَدَّام (Ṣaddām), a male given name. The source gloss 'Exalted, Noble, Mighty' is unsupported and has been replaced with the documented identification."),
 "sadeem": ("سَدِيم", "سدیم", "سدیم", "सदीम", "سدیم", "sadeem", "Arabic", "Female",
            "Arabic سَدِيم (Sadīm)", False, "medium",
            "Sadeem is recorded as Arabic سَدِيم (Sadīm), a female given name. CRITICAL SOURCE ERROR: the source gave سعدم (a non-standard form). The source gloss 'Moon' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadeen": ("سَدِين", "سدین", "سدین", "सदीन", "سدین", "sadeen", "Arabic", "Female",
            "Arabic سَدِين (Sadīn)", False, "medium",
            "Sadeen is recorded as Arabic سَدِين (Sadīn), a female given name. The source gloss 'Garden or Flowers' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadeeq": ("صَدِيق", "صدیق", "صدیق", "सदीक़", "صدیق", "sadeeq", "Arabic", "Male",
            "Arabic root ص د ق (ṣ-d-q); صَدِيق (Ṣadīq)", False, "high",
            "Sadeeq is Arabic صَدِيق (Ṣadīq) 'truthful, sincere; friend', from the root ص د ق (ṣ-d-q). The source gloss 'Truthful' is consistent. Same name as sadiq."),
 "sadegh": ("صَادِق", "صادق", "صادق", "सादेग़", "صادق", "sadegh", "Persian", "Male",
            "Persian صادق (sādeq), from Arabic صَادِق", False, "high",
            "Sadegh is the Persian form of Arabic صَادِق (Ṣādiq) 'truthful, sincere'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Saadiq' instead of a script form and labelled the origin Arabic; the name as used is Persian. The source gloss 'Righteous' is broadly consistent. Same name as sadiq."),
 "sadi": ("سَعْدِي", "سعدی", "سعدی", "सादी", "سعدي", "sadi", "Arabic", "Male",
          "Arabic سَعْدِي (Saʿdī) 'fortunate'", False, "high",
          "Sadi is a spelling variant of Arabic سَعْدِي (Saʿdī) 'fortunate, happy', a relational adjective from سَعْد (saʿd). The source gloss 'Just, Righteous' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as saadi."),
 "sadia": ("سَعْدِيَّة", "سعدیہ", "سعدیه", "सादिया", "سعديه", "sadia", "Arabic", "Female",
           "Arabic سَعْدِيَّة (Saʿdiyya) 'fortunate' (feminine)", False, "high",
           "Sadia is Arabic سَعْدِيَّة (Saʿdiyya) 'happy, fortunate' (feminine), a relational adjective from سَعْد (saʿd). The source gloss 'Truthful, Honest' is unsupported and has been replaced with the lexical sense. Same name as saadia."),
 "sadiah": ("سَادِيَة", "سادیہ", "سادیه", "सादिया", "سادیه", "sadiah", "Arabic", "Female",
            "Arabic سَادِيَة (Sādiya)", False, "medium",
            "Sadiah is recorded as Arabic سَادِيَة (Sādiya), a female given name. The source gloss 'Meadow, Garden, Joy' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadid": ("سَدِيد", "سدید", "سدید", "सदीद", "سدید", "sadid", "Arabic", "Male",
           "Arabic root س د د (s-d-d); سَدِيد (Sadīd)", False, "high",
           "Sadid is Arabic سَدِيد (Sadīd) 'sound, correct', from the root س د د (s-d-d). The source gloss 'Support, Help, Aid' is unsupported and has been replaced with the lexical sense."),
 "sadik": ("صَادِق", "صادق", "صادق", "सादिक़", "صادق", "sadik", "Arabic", "Male",
           "Arabic root ص د ق (ṣ-d-q); صَادِق (Ṣādiq)", False, "high",
           "Sadik is a spelling variant of Arabic صَادِق (Ṣādiq) 'truthful, sincere', from the root ص د ق (ṣ-d-q). The source gloss 'Truthful' is consistent. Same name as sadiq."),
 "sadika": ("صَادِقَة", "صادقہ", "صادقه", "सादिक़ा", "صادقه", "sadika", "Arabic", "Female",
            "Arabic root ص د ق (ṣ-d-q); صَادِقَة (Ṣādiqa)", False, "high",
            "Sadika is Arabic صَادِقَة (Ṣādiqa) 'truthful, sincere' (feminine), from the root ص د ق (ṣ-d-q). CRITICAL SOURCE ERROR: the source gave ساد يقة (a broken form). The source gloss 'Truthful, sincere' is consistent. Same name as sadiqa."),
 "sadin": ("سَادِن", "سادن", "سادن", "सादिन", "سادن", "sadin", "Arabic", "Male",
           "Arabic سَادِن (Sādin)", False, "medium",
           "Sadin is recorded as Arabic سَادِن (Sādin), a male given name. CRITICAL SOURCE ERROR: the source gave صادق (a different name). The source gloss 'Gladdener' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadiq": ("صَادِق", "صادق", "صادق", "सादिक़", "صادق", "sadiq", "Arabic", "Male",
           "Arabic root ص د ق (ṣ-d-q); صَادِق (Ṣādiq)", False, "high",
           "Sadiq is Arabic صَادِق (Ṣādiq) 'truthful, sincere', from the root ص د ق (ṣ-d-q). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "sadiqa": ("صَادِقَة", "صادقہ", "صادقه", "सादिक़ा", "صادقه", "sadiqa", "Arabic", "Female",
            "Arabic root ص د ق (ṣ-d-q); صَادِقَة (Ṣādiqa)", False, "high",
            "Sadiqa is Arabic صَادِقَة (Ṣādiqa) 'truthful, sincere' (feminine), from the root ص د ق (ṣ-d-q). The source gloss 'Truthful, sincere friend' is broadly consistent."),
 "sadir": ("سَدِير", "سدیر", "سدیر", "सदीर", "سدیر", "sadir", "Arabic", "Male",
           "Arabic سَدِير (Sadīr)", False, "medium",
           "Sadir is recorded as Arabic سَدِير (Sadīr), a male given name. The source gloss 'Gardener, Cultivator' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadit": ("سَدِيت", "سدیت", "سدیت", "सदित", "سدیت", "sadit", "Arabic", "Female",
           "Arabic سَدِيت (Sadīt)", False, "medium",
           "Sadit is recorded as Arabic سَدِيت (Sadīt), a female given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Sadit' instead of a script form. The source gloss 'Lady of the Garden' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadiya": ("سَعْدِيَّة", "سعدیہ", "سعدیه", "सादिया", "سعديه", "sadiya", "Arabic", "Female",
            "Arabic سَعْدِيَّة (Saʿdiyya) 'fortunate' (feminine)", False, "high",
            "Sadiya is Arabic سَعْدِيَّة (Saʿdiyya) 'happy, fortunate' (feminine), a relational adjective from سَعْد (saʿd). The source gloss 'Follower of the Right Path' is unsupported and has been replaced with the lexical sense. Same name as saadia."),
 "sadiyah": ("سَادِيَة", "سادية", "سادیه", "सादिया", "سادیه", "sadiyah", "Arabic", "Female",
             "Arabic سَادِيَة (Sādiya)", False, "medium",
             "Sadiyah is recorded as Arabic سَادِيَة (Sādiya), a female given name. The source gloss 'Moon' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as sadiah."),
 "sadq": ("صِدْق", "صدق", "صدق", "सदक़", "صدق", "sadq", "Arabic", "Male",
         "Arabic root ص د ق (ṣ-d-q); صِدْق (Ṣidq)", False, "high",
         "Sadq is Arabic صِدْق (Ṣidq) 'truthfulness, sincerity', from the root ص د ق (ṣ-d-q). The source gloss 'Truthful' is broadly consistent."),
 "sadr": ("صَدْر", "صدر", "صدر", "सद्र", "صدر", "sadr", "Arabic", "Male",
          "Arabic root ص د ر (ṣ-d-r); صَدْر (Ṣadr)", False, "high",
          "Sadr is Arabic صَدْر (Ṣadr) 'chest, foremost part; chief', from the root ص د ر (ṣ-d-r). The source gloss 'chief, leader' is broadly consistent."),
 "sadra": ("صَدْرَا", "صدرا", "صدرا", "सदरा", "صدرا", "sadra", "Persian", "Female",
           "Persian صدرا (Sadrā)", False, "medium",
           "Sadra is a female given name from Persian صدرا (Sadrā). CRITICAL SOURCE ERROR: the source gave سدرة (a different form) and labelled the origin Arabic; the name is Persian. The source gloss 'Saffron' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "sadri": ("صَدْرِي", "صدری", "صدری", "सद्री", "صدري", "sadri", "Arabic", "Male",
           "Arabic صَدْرِي (Ṣadrī) 'of the chest, foremost'", False, "high",
           "Sadri is Arabic صَدْرِي (Ṣadrī) 'of the chest, foremost', a relational adjective from صَدْر (ṣadr). The source gloss 'Happy, Joyful, Delighted' is unsupported and has been replaced with the lexical sense."),
 "sadruddin": ("صَدْرُ الدِّين", "صدرالدین", "صدرالدین", "सदरुद्दीन", "صدرالدین", "sadruddin", "Arabic", "Male",
               "Arabic صَدْر (ṣadr) in construct with الدِّين (al-dīn)", False, "high",
               "Sadruddin is Arabic صَدْرُ الدِّين (Ṣadru l-Dīn) 'foremost of the faith', a construct name. CRITICAL SOURCE ERROR: the source gave سدرو ددين (a broken form). The source gloss 'Servant of God' is unsupported and has been replaced with the lexical sense."),
 "sadun": ("سَعْدُون", "سعدون", "سعدون", "सादून", "سعدون", "sadun", "Arabic", "Male",
           "Arabic root س ع د (s-ʿ-d); سَعْدُون (Saʿdūn)", False, "high",
           "Sadun is Arabic سَعْدُون (Saʿdūn), a male given name from the root س ع د (s-ʿ-d). CRITICAL SOURCE ERROR: the source gave علي (a different name); the correct form is سَعْدُون. The source gloss 'Gift, Reward' is unsupported and has been replaced with the documented identification."),
 "saee": ("سَعْي", "سعی", "سعی", "सई", "سعي", "saee", "Arabic", "Female",
          "Arabic root س ع ي (s-ʿ-y); سَعْي (Saʿy)", False, "high",
          "Saee is Arabic سَعْي (Saʿy) 'effort, striving', from the root س ع ي (s-ʿ-y). The source gloss 'The One Who Weeps' is unsupported and has been replaced with the lexical sense."),
 "saeed": ("سَعِيد", "سعید", "سعید", "सईद", "سعید", "saeed", "Arabic", "Male",
           "Arabic root س ع د (s-ʿ-d); سَعِيد (Saʿīd)", False, "high",
           "Saeed is Arabic سَعِيد (Saʿīd) 'happy, fortunate', from the root س ع د (s-ʿ-d). The source gloss 'Happy, Blessed' is broadly consistent."),
 "saeeda": ("سَعِيدَة", "سعیدہ", "سعیده", "सईदा", "سعیده", "saeeda", "Arabic", "Female",
            "Arabic root س ع د (s-ʿ-d); سَعِيدَة (Saʿīda)", False, "high",
            "Saeeda is Arabic سَعِيدَة (Saʿīda) 'happy, fortunate' (feminine), from the root س ع د (s-ʿ-d). CRITICAL SOURCE ERROR: the source gave سائ دة (a broken form). The source gloss 'Lady, Mistress' is unsupported and has been replaced with the lexical sense. Same name as sa-idah."),
 "safa": ("صَفَا", "صفا", "صفا", "सफ़ा", "صفا", "safa", "Arabic", "Female",
          "Arabic root ص ف و (ṣ-f-w); صَفَا (Ṣafā)", False, "high",
          "Safa is Arabic صَفَا (Ṣafā) 'purity, clarity', from the root ص ف و (ṣ-f-w). The source gloss 'Purified, Clean, Sacred' is broadly consistent."),
 "safaa": ("صَفَاء", "صفاء", "صفاء", "सफ़ा", "صفاء", "safaa", "Arabic", "Female",
           "Arabic root ص ف و (ṣ-f-w); صَفَاء (Ṣafāʾ)", False, "high",
           "Safaa is Arabic صَفَاء (Ṣafāʾ) 'purity, clarity', from the root ص ف و (ṣ-f-w). The source gloss 'Clean and Pure' is consistent. Same name as safa."),
 "safar": ("سَفَر", "سفر", "سفر", "सफ़र", "سفر", "safar", "Arabic", "Male",
           "Arabic root س ف ر (s-f-r); سَفَر (Safar)", False, "high",
           "Safar is Arabic سَفَر (Safar) 'journey, travel', from the root س ف ر (s-f-r). The source gloss 'Traveler' is broadly consistent."),
 "safdar": ("صَفْدَر", "صفدر", "صفدر", "सफ़दर", "صفدر", "safdar", "Persian", "Male",
            "Persian صفدر (Safdar)", False, "high",
            "Safdar is a Persian male given name, صفدر (Safdar). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name is Persian/Urdu. The source gloss 'Protector, Defender' is unsupported and has been replaced with the documented identification."),
 "safee": ("صَفِي", "صفی", "صفی", "सफ़ी", "صفي", "safee", "Arabic", "Male",
           "Arabic root ص ف و (ṣ-f-w); صَفِي (Ṣafī)", False, "high",
           "Safee is a spelling variant of Arabic صَفِي (Ṣafī) 'pure, clear', from the root ص ف و (ṣ-f-w). The source gloss 'Secure, Safe, Protected' is unsupported and has been replaced with the lexical sense. Same name as safi."),
 "safeena": ("سَفِينَة", "سفینہ", "سفینه", "सफ़ीना", "سفینه", "safeena", "Arabic", "Female",
             "Arabic root س ف ن (s-f-n); سَفِينَة (Safīna)", False, "high",
             "Safeena is Arabic سَفِينَة (Safīna) 'ship, vessel', from the root س ف ن (s-f-n). The source gloss 'Protected One' is unsupported and has been replaced with the lexical sense. Same name as safina."),
 "safeenah": ("سَفِينَة", "سفینہ", "سفینه", "सफ़ीना", "سفینه", "safeenah", "Arabic", "Female",
              "Arabic root س ف ن (s-f-n); سَفِينَة (Safīna)", False, "high",
              "Safeenah is Arabic سَفِينَة (Safīna) 'ship, vessel', from the root س ف ن (s-f-n). The source gloss 'Protector' is unsupported and has been replaced with the lexical sense. Same name as safina."),
 "safeer": ("سَفِير", "سفیر", "سفیر", "सफ़ीर", "سفیر", "safeer", "Arabic", "Male",
            "Arabic root س ف ر (s-f-r); سَفِير (Safīr)", False, "high",
            "Safeer is Arabic سَفِير (Safīr) 'ambassador, envoy', from the root س ف ر (s-f-r). The source gloss 'Traveler, Messenger' is broadly consistent. Same name as safir."),
 "safeera": ("سَفِيرَة", "سفیرہ", "سفیره", "सफ़ीरा", "سفیره", "safeera", "Arabic", "Female",
             "Arabic root س ف ر (s-f-r); سَفِيرَة (Safīra)", False, "high",
             "Safeera is Arabic سَفِيرَة (Safīra) 'ambassador, envoy' (feminine), from the root س ف ر (s-f-r). The source gloss 'Purity, Perfection' is unsupported and has been replaced with the lexical sense. Same name as safira."),
 "saffa": ("صَفَّا", "صفا", "صفا", "सफ़्फ़ा", "صفا", "saffa", "Arabic", "Female",
           "Arabic صَفَّا (Ṣaffā)", False, "medium",
           "Saffa is recorded as Arabic صَفَّا (Ṣaffā), a female given name. The source gloss 'Gentle, peaceful' is unsupported; no confident lexical sense is asserted. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. The identification is recorded at medium confidence."),
 "saffan": ("صِفَان", "صفان", "صفان", "सफ़्फ़ान", "صفان", "saffan", "Arabic", "Male",
            "Arabic root ص ف و (ṣ-f-w); صِفَان (Ṣifān)", False, "high",
            "Saffan is Arabic صِفَان (Ṣifān) 'pure, clear', from the root ص ف و (ṣ-f-w). The source gloss 'Pure, Clear' is consistent."),
 "saffron": ("زَعْفَرَان", "زعفران", "زعفران", "ज़ाफ़रान", "زعفران", "saffron", "English", "Female",
             "English saffron, from Arabic زَعْفَرَان", False, "high",
             "Saffron is an English given name taken from the spice, ultimately from Arabic زَعْفَرَان (zaʿfarān). CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the name as used is English. The source gloss 'Yellow Saffron' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "safi": ("صَفِي", "صفی", "صفی", "सफ़ी", "صفي", "safi", "Arabic", "Male",
          "Arabic root ص ف و (ṣ-f-w); صَفِي (Ṣafī)", False, "high",
          "Safi is Arabic صَفِي (Ṣafī) 'pure, clear', from the root ص ف و (ṣ-f-w). The source gloss 'Pure' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "safia": ("صَفِيَّة", "صفیہ", "صفیه", "सफ़िया", "صفيه", "safia", "Arabic", "Female",
           "Arabic root ص ف و (ṣ-f-w); صَفِيَّة (Ṣafiyya)", False, "high",
           "Safia is Arabic صَفِيَّة (Ṣafiyya) 'pure, clear' (feminine), from the root ص ف و (ṣ-f-w). CRITICAL SOURCE ERROR: the source gave سفيهة (a different form). The source gloss 'Safe' is unsupported and has been replaced with the lexical sense. Same name as safiya."),
 "safin": ("صَفِي", "صفی", "صفی", "सफ़ीन", "صفي", "safin", "Arabic", "Male",
           "Arabic root ص ف و (ṣ-f-w); صَفِي (Ṣafī)", False, "high",
           "Safin is a spelling variant of Arabic صَفِي (Ṣafī) 'pure, clear', from the root ص ف و (ṣ-f-w). CRITICAL SOURCE ERROR: the source gave صفي (a different form). The source gloss 'Sailor, Seafarer' is unsupported and has been replaced with the lexical sense. Same name as safi."),
 "safina": ("سَفِينَة", "سفینہ", "سفینه", "सफ़ीना", "سفینه", "safina", "Arabic", "Female",
            "Arabic root س ف ن (s-f-n); سَفِينَة (Safīna)", False, "high",
            "Safina is Arabic سَفِينَة (Safīna) 'ship, vessel', from the root س ف ن (s-f-n). CRITICAL SOURCE ERROR: the source gave the Latin string 'Safina' instead of a script form. The source gloss 'Safe or Sound' is unsupported and has been replaced with the lexical sense."),
 "safinaz": ("سَفِينَاز", "سفیناز", "سفیناز", "सफ़ीनाज़", "سفیناز", "safinaz", "Arabic", "Female",
             "Arabic سَفِينَاز (Safīnāz)", False, "medium",
             "Safinaz is recorded as Arabic سَفِينَاز (Safīnāz), a female given name. The source gloss 'Pure and Chaste' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "safir": ("سَفِير", "سفیر", "سفیر", "सफ़ीर", "سفیر", "safir", "Arabic", "Male",
           "Arabic root س ف ر (s-f-r); سَفِير (Safīr)", False, "high",
           "Safir is Arabic سَفِير (Safīr) 'ambassador, envoy', from the root س ف ر (s-f-r). The source gloss 'Traveler' is broadly consistent. Same name as safeer."),
 "safira": ("سَفِيرَة", "سفیرہ", "سفیره", "सफ़ीरा", "سفیره", "safira", "Arabic", "Female",
            "Arabic root س ف ر (s-f-r); سَفِيرَة (Safīra)", False, "high",
            "Safira is Arabic سَفِيرَة (Safīra) 'ambassador, envoy' (feminine), from the root س ف ر (s-f-r). The source gloss 'Purity, Light, Transparency' is unsupported and has been replaced with the lexical sense. Same name as safeera."),
 "safiya": ("صَفِيَّة", "صفیہ", "صفیه", "सफ़िया", "صفيه", "safiya", "Arabic", "Female",
            "Arabic root ص ف و (ṣ-f-w); صَفِيَّة (Ṣafiyya)", False, "high",
            "Safiya is Arabic صَفِيَّة (Ṣafiyya) 'pure, clear' (feminine), from the root ص ف و (ṣ-f-w). The source gloss 'Pure and Untainted' is broadly consistent. Same name as safia."),
 "safiyah": ("صَفِيَّة", "صفیہ", "صفیه", "सफ़िया", "صفيه", "safiyah", "Arabic", "Female",
             "Arabic root ص ف و (ṣ-f-w); صَفِيَّة (Ṣafiyya)", False, "high",
             "Safiyah is Arabic صَفِيَّة (Ṣafiyya) 'pure, clear' (feminine), from the root ص ف و (ṣ-f-w). The source gloss 'Pure, Chaste' is broadly consistent. Same name as safiya."),
 "safiyya": ("صَفِيَّة", "صفیہ", "صفیه", "सफ़िया", "صفيه", "safiyya", "Arabic", "Female",
             "Arabic root ص ف و (ṣ-f-w); صَفِيَّة (Ṣafiyya)", False, "high",
             "Safiyya is Arabic صَفِيَّة (Ṣafiyya) 'pure, clear' (feminine), from the root ص ف و (ṣ-f-w). The source gloss 'Pure, Chaste' is broadly consistent. Same name as safiya."),
 "safiyyah": ("صَفِيَّة", "صفیہ", "صفیه", "सफ़िया", "صفيه", "safiyyah", "Arabic", "Female",
              "Arabic root ص ف و (ṣ-f-w); صَفِيَّة (Ṣafiyya)", False, "high",
              "Safiyyah is Arabic صَفِيَّة (Ṣafiyya) 'pure, clear' (feminine), from the root ص ف و (ṣ-f-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as safiya."),
 "safura": ("صَفُورَة", "صفورہ", "صفوره", "सफ़ूरा", "صفوره", "safura", "Arabic", "Female",
            "Arabic صَفُورَة (Safūra)", False, "medium",
            "Safura is recorded as Arabic صَفُورَة (Safūra), a female given name. The source gloss 'Pure, Chaste' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "safwa": ("صَفْوَة", "صفوہ", "صفوه", "सफ़वा", "صفوه", "safwa", "Arabic", "Female",
           "Arabic root ص ف و (ṣ-f-w); صَفْوَة (Ṣafwa)", False, "high",
           "Safwa is Arabic صَفْوَة (Ṣafwa) 'purity, the choicest part', from the root ص ف و (ṣ-f-w). The source gloss 'Pure, Hidden Treasure' is broadly consistent."),
}
