# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 44 (murtada..nacira).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": musan -> Latin "Musan"; musawir -> Latin
   "Musawir"; musli -> Latin "Musli"; mutalib -> Latin "Mutalib"; mutia -> Latin
   "Mutia"; naaman -> Latin "Na'aman"; nabiha -> Latin "Nabiha";
   nacira -> "Ali" (a different name); mussah -> أحمد (a different name);
   musthafa -> مستحفى; mustaqeem -> مصتقعم; mutasim -> مطعسم; mutaz -> مُتَعَزّ;
   muzammal -> مُظَمَّل; muzaffar -> منزفر; muzahid -> مزاحد; muzzammil -> مزمّل;
   musarat -> مصرةت; musarrat -> مسرات; musfira -> مصفيرة; musfirah -> مسفرة;
   muslihah -> مسلحة; musleh -> مسلح; mushtak -> مشتق; muskaan/muskan -> موسكان;
   mutahar -> مُتَحَر; muti -> مطي; muyassar -> مياسر; muza -> موزا;
   muzna -> مُزنہ; myesha -> ميشا; myrah -> ميره; naail -> ناعل;
   naazneen -> ناضنين; nabaz -> نبز; nabihah -> نبيحة.
 * EMPTY STUBS (8-key records, no data): musa, mustafa, nabeel.
 * MISLABELLED ORIGIN: naaz (Persian), muskaan/muskan (Urdu/Hindi), myesha
   (an English spelling of Aisha), nacer (a Latin-alphabet spelling).
 * DEGARBLED GLOSSES: murtada "Lover", murtaja "Support, Helper",
   murtazi "One who strives, struggles", murtuja "Chosen One",
   musaab "Warrior or Fighter", musaad "Supporter of Good",
   musab "Magnificent, excellent", musaddiq "One who is honest and truthful",
   musan "Calm", musarat "Delight, pleasure", musarrat "Ornamented, Embellished",
   musawir "Painted, Colorful", musfira "Pure and Chaste", musfirah "Pure and Chaste",
   mushahid "Witness", musheer "Traveler", mushfiq "Seeker of beauty, truth, or pleasure",
   mushtak "Chooser", muska "Musk fragrance", muskaan "A twinkling star",
   muskan "Fragrant flower", musleh "Guide, teacher, leader", musli "Seeker, Follower",
   muslih "Bringing Peace", muslihah "Reconcile, Set Right", muslimin "Muslim",
   mussah "Guide, Teacher", mustaf "Chosen one", mustafaa "Praiseworthy, Commended",
   mustajab "Responsive, Answering", mustakim "The Truthful",
   mustansar "Support, Strength", mustansir "Guide, leader, finder",
   mustaqeem "Constantly present", mustaqim "Walks on the Straight Path",
   musthafa "Chosen one, beloved", mutahar "Pious, Wise", mutahir "Pure, Immaculate",
   mutalib "Dedicated, devout, or having a lover", mutasim "Firm, Established",
   mutassim "One who is given power or authority", mutawakkil "Trusts in Allah",
   mutaz "Withheld", muthanna "Reviver, Renewer", muti "Governor, Leader",
   mutia "Mother's love", mutlaq "Unrestrained, Free",
   muwafaq "Reunited, Agreed, Successful", muyassar "Delicately prepared",
   muza "Drawn from the Arabic root 'm-z-y'", muzaffar "Triumphant, Victorious",
   muzahid "Striver, Warrior", muzakkir "Remembrer, Recall",
   muzammal "Subduer, Victorious", muzna "Raindrop",
   muzzammil "One who is constantly present", myesha "Intense one", myrah "Grace",
   naahil "A stream, or a mole (in the face)", naail "Helpful",
   naaim "Given to the good-doer", naaima "Graceful, attractive",
   naajih "Successful, Helper", naaman "Given by God", naasih "Advisor, Counselor",
   naaz "Grace, beauty", naazneen "Delight, pleasure, joy",
   naba "Awakening, Announcement", nabat "Garden, Paradise", nabaz "Given by Allah",
   nabeeh "Gentle, Kind", nabeeha "Gracious, Pleasing", nabeela "Noble, High-born",
   nabeelah "Companion of the Prophet", nabhan "Grape", nabih "Intelligent, Wise, Capable",
   nabiha "Intelligent, Noble", nabihah "Guided by God, Pure",
   nabila "Little girl, female child", nabilah "Noble, Exalted",
   nacer "Born, brought to life, revived", nacira "Pure, innocent".
 * GENDER ERRORS: murtaja, murtuja, mutassim, muza, muzna, naahil, nabat were
   labelled unisex where documented usage is male or the form is a common noun.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated43 import GLOSSES as _G43

GLOSSES = dict(_G43)
GLOSSES.update({
    "chosen_murtada": {"en": "Chosen, selected, approved", "ur": "مرتضیٰ، چنا ہوا، پسندیدہ", "fa": "مرتضی، برگزیده", "hi": "मुर्तज़ा, चुना हुआ", "ps": "مرتضی، غوره شوی", "ar": "الْمُرْتَضَى، الْمُخْتَار"},
    "murtazi": {"en": "Murtazi; one who is content, satisfied", "ur": "مرتضی، راضی، مطمئن", "fa": "مرتضی، خشنود", "hi": "मुर्तज़ी, संतुष्ट", "ps": "مرتضی، راضي", "ar": "الْمُرْتَضِي، الرَّاضِي"},
    "musab": {"en": "Musab; a male given name", "ur": "مصعب (مردانہ نام)", "fa": "مصعب (نام مردانه)", "hi": "मुसअब (पुरुष नाम)", "ps": "مصعب (نر نوم)", "ar": "مُصْعَب (اسْم عَلَم مُذَكَّر)"},
    "musaad": {"en": "Musaad; happy, fortunate", "ur": "مسعد، خوش، بختور", "fa": "مسعد، خوشبخت", "hi": "मुसअद, प्रसन्न", "ps": "مسعد، خوشحاله", "ar": "مُسْعَد، السَّعِيد"},
    "musaddiq": {"en": "Musaddiq; one who affirms the truth", "ur": "مصدق، سچ کی تصدیق کرنے والا", "fa": "مصدق، تصدیق‌کننده", "hi": "मुसद्दिक़, सत्य की पुष्टि करने वाला", "ps": "مصدق، رښتیا تاییدوونکی", "ar": "الْمُصَدِّق، الْمُؤَيِّد"},
    "musadiq": {"en": "Musadiq; one who affirms the truth", "ur": "مصدق، سچ کی تصدیق کرنے والا", "fa": "مصدق، تصدیق‌کننده", "hi": "मुसादिक़, सत्य की पुष्टि करने वाला", "ps": "مصدق، رښتیا تاییدوونکی", "ar": "الْمُصَادِق، الْمُصَدِّق"},
    "musafer": {"en": "Musafer; traveller, voyager", "ur": "مسافر، سفر کرنے والا", "fa": "مسافر، سفرکننده", "hi": "मुसाफ़िर, यात्री", "ps": "مسافر، سفر کوونکی", "ar": "الْمُسَافِر، الرَّاحِل"},
    "musarrat": {"en": "Musarrat; joy, delight, happiness", "ur": "مسرت، خوشی، شادمانی", "fa": "مسرت، شادی", "hi": "मुसर्रत, प्रसन्नता", "ps": "مسرت، خوښي", "ar": "الْمَسَرَّة، الْفَرَح"},
    "musawir": {"en": "Musawir; painter, one who depicts", "ur": "مصور، تصویر بنانے والا", "fa": "مصور، نگارگر", "hi": "मुसव्विर, चित्रकार", "ps": "مصور، انځورګر", "ar": "الْمُصَوِّر، الرَّسَّام"},
    "musfira": {"en": "Musfira; bright, radiant (feminine)", "ur": "مسفرہ، روشن، چمکدار", "fa": "مسفره، درخشان", "hi": "मुस्फ़िरा, चमकदार", "ps": "مسفره، روښانه", "ar": "الْمُسْفِرَة، الْمُشْرِقَة"},
    "mushahid": {"en": "Mushahid; witness, observer", "ur": "مشاہد، گواہ، دیکھنے والا", "fa": "مشاهد، گواه", "hi": "मुशाहिद, गवाह", "ps": "مشاهد، شاهد", "ar": "الْمُشَاهِد، الشَّاهِد"},
    "mushir": {"en": "Mushir; advisor, counsellor, guide", "ur": "مشیر، مشورہ دینے والا، رہنما", "fa": "مشیر، راهنما", "hi": "मुशीर, सलाहकार", "ps": "مشیر، سلاکار", "ar": "الْمُشِير، النَّاصِح"},
    "mushfiq": {"en": "Mushfiq; compassionate, kind, anxious for others", "ur": "مشفق، مہربان، شفیق", "fa": "مشفق، مهربان", "hi": "मुशफ़िक़, दयालु", "ps": "مشفق، مهربان", "ar": "الْمُشْفِق، الْعَطُوف"},
    "mushtaq": {"en": "Mushtaq; longing, yearning, desirous", "ur": "مشتاق، آرزومند، مشتاق", "fa": "مشتاق، آرزومند", "hi": "मुश्ताक़, उत्सुक", "ps": "مشتاق، هيله مند", "ar": "الْمُشْتَاق، الْمُتَشَوِّق"},
    "muska": {"en": "Muska; musk, a fragrant substance", "ur": "مسک، مشک", "fa": "مسک، مشک", "hi": "मुस्क, कस्तूरी", "ps": "مسک، مشک", "ar": "الْمِسْك"},
    "muskan": {"en": "Muskan; smile", "ur": "مسکان، مسکراہٹ", "fa": "مسکان، لبخند", "hi": "मुस्कान, मुस्कुराहट", "ps": "مسکان، موسکا", "ar": "الِابْتِسَامَة"},
    "muslih": {"en": "Muslih; reformer, one who sets things right", "ur": "مصلح، اصلاح کرنے والا", "fa": "مصلح، اصلاح‌گر", "hi": "मुस्लिह, सुधारक", "ps": "مصلح، سمون کوونکی", "ar": "الْمُصْلِح، الْمُصْلِح"},
    "muslim": {"en": "Muslim; one who submits to God", "ur": "مسلم، اللہ کے تابع", "fa": "مسلمان، تسلیم‌شده", "hi": "मुस्लिम, आत्मसमर्पित", "ps": "مسلمان، غاړه غړونکی", "ar": "الْمُسْلِم، الْمُنْقَاد لِلَّه"},
    "muslima": {"en": "Muslima; one who submits to God (feminine)", "ur": "مسلمہ، اللہ کے تابع (مؤنث)", "fa": "مسلمه، تسلیم‌شده (مؤنث)", "hi": "मुस्लिमा, आत्मसमर्पित (स्त्री)", "ps": "مسلمه، غاړه غړونکې", "ar": "الْمُسْلِمَة، الْمُنْقَادَة لِلَّه"},
    "muslimin": {"en": "Muslimin; Muslims (plural)", "ur": "مسلمین، مسلمان", "fa": "مسلمین، مسلمانان", "hi": "मुस्लिमीन, मुसलमान", "ps": "مسلمین، مسلمانان", "ar": "الْمُسْلِمِين، الْمُسْلِمُونَ"},
    "mustafa": {"en": "Mustafa; chosen, selected", "ur": "مصطفیٰ، چنا ہوا، منتخب", "fa": "مصطفی، برگزیده", "hi": "मुस्तफ़ा, चुना हुआ", "ps": "مصطفی، غوره شوی", "ar": "الْمُصْطَفَى، الْمُخْتَار"},
    "mustajab": {"en": "Mustajab; answered, granted (of prayer)", "ur": "مستجاب، قبول شدہ (دعا)", "fa": "مستجاب، اجابت‌شده", "hi": "मुस्तजाब, स्वीकृत", "ps": "مستجاب، قبول شوی", "ar": "الْمُسْتَجَاب، الْمَقْبُول"},
    "mustaqim": {"en": "Mustaqim; straight, upright, correct", "ur": "مستقیم، سیدھا، درست", "fa": "مستقیم، راست", "hi": "मुस्तक़ीम, सीधा", "ps": "مستقیم، سم", "ar": "الْمُسْتَقِيم، الْقَوِيم"},
    "mustansir": {"en": "Mustansir; one who seeks help or victory", "ur": "مستنصر، مدد یا فتح مانگنے والا", "fa": "مستنصر، یاری‌خواه", "hi": "मुस्तनसिर, सहायता चाहने वाला", "ps": "مستنصر، مرسته غوښتونکی", "ar": "الْمُسْتَنْصِر، طَالِب النَّصْر"},
    "mustapha": {"en": "Mustapha; chosen, selected", "ur": "مصطفیٰ، چنا ہوا", "fa": "مصطفی، برگزیده", "hi": "मुस्तफ़ा, चुना हुआ", "ps": "مصطفی، غوره شوی", "ar": "الْمُصْطَفَى، الْمُخْتَار"},
    "mutahar": {"en": "Mutahar; purified, pure", "ur": "مطہر، پاک، صاف", "fa": "مطهر، پاک", "hi": "मुतह्हर, पवित्र", "ps": "مطهر، پاک", "ar": "الْمُطَهَّر، الطَّاهِر"},
    "mutahir": {"en": "Mutahir; purifying, cleansing", "ur": "مطہر، پاک کرنے والا", "fa": "مطهر، پاک‌کننده", "hi": "मुताहिर, शुद्ध करने वाला", "ps": "مطهر، پاکوونکی", "ar": "الْمُطَهِّر، الْمُنَقِّي"},
    "mutalib": {"en": "Mutalib; seeker, one who demands", "ur": "مطلب، طلب کرنے والا، خواہشمند", "fa": "مطلب، خواهان", "hi": "मुतलिब, चाहने वाला", "ps": "مطلب، غوښتونکی", "ar": "الْمُطَّلِب، الطَّالِب"},
    "mutasim": {"en": "Mutasim; one who holds fast, clings firmly", "ur": "معتصم، مضبوطی سے تھامنے والا", "fa": "معتصم، چنگ‌زننده", "hi": "मोतसिम, मज़बूती से थामने वाला", "ps": "معتصم، کلک نیول", "ar": "الْمُعْتَصِم، الْمُمْسِك"},
    "mutawakkil": {"en": "Mutawakkil; one who trusts in God", "ur": "متوکل، اللہ پر بھروسہ کرنے والا", "fa": "متوکل، توکل‌کننده", "hi": "मुतवक्किल, ईश्वर पर भरोसा करने वाला", "ps": "متوکل، په الله توکل کوونکی", "ar": "الْمُتَوَكِّل، الْمُعْتَمِد عَلَى اللَّه"},
    "mutaz": {"en": "Mutaz; glorified, honoured, proud", "ur": "معتز، معزز، فخر کرنے والا", "fa": "معتز، سربلند", "hi": "मोताज़, गौरवान्वित", "ps": "معتز، ویاړلی", "ar": "الْمُعْتَزّ، الْمُكَرَّم"},
    "muthanna": {"en": "Muthanna; doubled, twofold", "ur": "مثنیٰ، دوہرا، دگنا", "fa": "مثنی، دوگانه", "hi": "मुसन्ना, दोहरा", "ps": "مثنی، دوه ځله", "ar": "الْمُثَنَّى، الْمَثْنَى"},
    "muti": {"en": "Muti; obedient, compliant", "ur": "مطیع، فرمانبردار", "fa": "مطیع، فرمانبردار", "hi": "मुती, आज्ञाकारी", "ps": "مطیع، غاړه غړونکی", "ar": "الْمُطِيع، الْمُنْقَاد"},
    "mutia": {"en": "Mutia; obedient (feminine)", "ur": "مطیعہ، فرمانبردار (مؤنث)", "fa": "مطیعه، فرمانبردار (مؤنث)", "hi": "मुतीआ, आज्ञाकारिणी", "ps": "مطیعه، غاړه غړونکې", "ar": "الْمُطِيعَة، الْمُنْقَادَة"},
    "mutlaq": {"en": "Mutlaq; absolute, unrestricted, free", "ur": "مطلق، آزاد، بے قید", "fa": "مطلق، آزاد", "hi": "मुतलक़, निरपेक्ष", "ps": "مطلق، آزاد", "ar": "الْمُطْلَق، الْحُرّ"},
    "muwafaq": {"en": "Muwafaq; successful, reconciled, agreed", "ur": "موفق، کامیاب، متفق", "fa": "موفق، کامیاب", "hi": "मुवाफ़िक़, सफल", "ps": "موفق، بریالی", "ar": "الْمُوَفَّق، النَّاجِح"},
    "muyassar": {"en": "Muyassar; made easy, facilitated", "ur": "میسر، آسان کیا گیا", "fa": "میسر، آسان‌شده", "hi": "मुयस्सर, सुलभ", "ps": "میسر، آسانه شوی", "ar": "الْمُيَسَّر، الْمُسَهَّل"},
    "muzaffar": {"en": "Muzaffar; victorious, triumphant", "ur": "مظفر، فتح پانے والا", "fa": "مظفر، پیروز", "hi": "मुज़फ़्फ़र, विजयी", "ps": "مظفر، بریالی", "ar": "الْمُظَفَّر، الْمَنْصُور"},
    "muzahid": {"en": "Muzahid; one who strives, fighter", "ur": "مجاہد، جدوجہد کرنے والا", "fa": "مجاهد، کوشنده", "hi": "मुजाहिद, संघर्ष करने वाला", "ps": "مجاهد، هڅه کوونکی", "ar": "الْمُجَاهِد، الْمُكَافِح"},
    "muzakkir": {"en": "Muzakkir; one who reminds, admonisher", "ur": "مذکر، یاد دلانے والا", "fa": "مذکر، یادآور", "hi": "मुज़क्किर, याद दिलाने वाला", "ps": "مذکر، یادوونکی", "ar": "الْمُذَكِّر، الْمُنَبِّه"},
    "muzammil": {"en": "Muzammil; one wrapped in a cloak", "ur": "مزمل، چادر اوڑھنے والا", "fa": "مزمل، جامه‌پوش", "hi": "मुज़म्मिल, चादर ओढ़ने वाला", "ps": "مزمل، کملی غوړېدونکی", "ar": "الْمُزَّمِّل، الْمُتَزَمِّل"},
    "muzna": {"en": "Muzna; rain cloud, raindrop", "ur": "مزنہ، بادل، بارش کا قطرہ", "fa": "مزنه، ابر باران‌زا", "hi": "मुज़्ना, वर्षा-बादल", "ps": "مزنه، باراني ورېځ", "ar": "الْمُزْنَة، السَّحَابَة"},
    "myesha": {"en": "Myesha; a spelling of Aisha", "ur": "میشا، عائشہ کی ہجے", "fa": "میشا، املای عایشه", "hi": "मीशा, आइशा की वर्तनी", "ps": "میشا، د عایشې لیکنه", "ar": "مِيشَا (صِيغَة لِاسْم عَائِشَة)"},
    "myrah": {"en": "Myrah; a female given name", "ur": "میرہ (زنانہ نام)", "fa": "میرا (نام زنانه)", "hi": "मायरा (स्त्री नाम)", "ps": "میره (ښځينه نوم)", "ar": "مَيْرَة (اسْم عَلَم مُؤَنَّث)"},
    "naahil": {"en": "Naahil; thin, slender, lean", "ur": "ناہل، دبلا، پتلا", "fa": "ناهل، لاغر", "hi": "नाहिल, दुबला", "ps": "ناهل، نری", "ar": "النَّاهِل، النَّحِيف"},
    "naail": {"en": "Naail; one who obtains, attainer", "ur": "نائل، حاصل کرنے والا", "fa": "نائل، دست‌یابنده", "hi": "नाइल, प्राप्त करने वाला", "ps": "نائل، ترلاسه کوونکی", "ar": "النَّائِل، الْحَاصِل"},
    "naaim": {"en": "Naaim; soft, delicate, pleasant", "ur": "ناعم، نرم، خوشگوار", "fa": "ناعم، نرم", "hi": "नाइम, कोमल", "ps": "ناعم، نرم", "ar": "النَّاعِم، اللَّيِّن"},
    "naaima": {"en": "Naaima; soft, delicate, pleasant (feminine)", "ur": "نعیمہ، نرم، خوشگوار (مؤنث)", "fa": "نعیمه، نرم (مؤنث)", "hi": "नईमा, कोमल (स्त्री)", "ps": "نعیمه، نرمه", "ar": "النَّعِيمَة، اللَّيِّنَة"},
    "naajih": {"en": "Naajih; successful, prosperous", "ur": "ناجح، کامیاب", "fa": "ناجح، کامیاب", "hi": "नाजिह, सफल", "ps": "ناجح، بریالی", "ar": "النَّاجِح، الْمُوَفَّق"},
    "naaman": {"en": "Naaman; a male given name", "ur": "نعمان (مردانہ نام)", "fa": "نعمان (نام مردانه)", "hi": "नअमान (पुरुष नाम)", "ps": "نعمان (نر نوم)", "ar": "نُعْمَان (اسْم عَلَم مُذَكَّر)"},
    "naasih": {"en": "Naasih; advisor, sincere counsellor", "ur": "ناصح، خیر خواہ، مشورہ دینے والا", "fa": "ناصح، خیرخواه", "hi": "नासिह, शुभचिंतक", "ps": "ناصح، خیر غوښتونکی", "ar": "النَّاصِح، الْمُشِير"},
    "naasir": {"en": "Naasir; helper, supporter", "ur": "ناصر، مددگار، حامی", "fa": "ناصر، یاری‌کننده", "hi": "नासिर, सहायक", "ps": "ناصر، مرستندوی", "ar": "النَّاصِر، الْمُعِين"},
    "naaz": {"en": "Naaz; pride, coquetry, elegance", "ur": "ناز، ادا، نخرہ", "fa": "ناز، ادا", "hi": "नाज़, अदा", "ps": "ناز، ادا", "ar": "النَّاز (دَلّ وَغُنْج)"},
    "naazneen": {"en": "Naazneen; delicate, charming, sweetheart", "ur": "نازنین، نازک، پیاری", "fa": "نازنین، دلبر", "hi": "नाज़नीन, सुंदर", "ps": "نازنین، ښکلې", "ar": "النَّازَنِين، اللَّطِيفَة"},
    "naba": {"en": "Naba; news, announcement, tidings", "ur": "نبأ، خبر، اطلاع", "fa": "نبأ، خبر", "hi": "नबा, समाचार", "ps": "نبأ، خبر", "ar": "النَّبَأ، الْخَبَر"},
    "nabat": {"en": "Nabat; plants, vegetation", "ur": "نبات، پودے، سبزہ", "fa": "نبات، گیاهان", "hi": "नबात, पौधे", "ps": "نبات، بوټي", "ar": "النَّبَات، الْعُشْب"},
    "nabaz": {"en": "Nabaz; a male given name", "ur": "نبز (مردانہ نام)", "fa": "نبز (نام مردانه)", "hi": "नबाज़ (पुरुष नाम)", "ps": "نبز (نر نوم)", "ar": "نَبَز (اسْم عَلَم مُذَكَّر)"},
    "nabeeh": {"en": "Nabeeh; noble, distinguished, intelligent", "ur": "نبیہ، نجیب، ذہین", "fa": "نبیه، نجیب", "hi": "नबीह, कुलीन", "ps": "نبیه، نومیالی", "ar": "النَّبِيه، النَّجِيب"},
    "nabeeha": {"en": "Nabeeha; noble, distinguished (feminine)", "ur": "نبیہہ، نجیب (مؤنث)", "fa": "نبیهه، نجیب (مؤنث)", "hi": "नबीहा, कुलीन (स्त्री)", "ps": "نبیهه، نومیالې", "ar": "النَّبِيهَة، النَّجِيبَة"},
    "nabeel": {"en": "Nabeel; noble, high-born", "ur": "نبیل، نجیب، شریف", "fa": "نبیل، نجیب", "hi": "नबील, कुलीन", "ps": "نبیل، نومیالی", "ar": "النَّبِيل، النَّجِيب"},
    "nabeela": {"en": "Nabeela; noble, high-born (feminine)", "ur": "نبیلہ، نجیب (مؤنث)", "fa": "نبيله، نجیب (مؤنث)", "hi": "नबीला, कुलीन (स्त्री)", "ps": "نبيله، نومیالې", "ar": "النَّبِيلَة، النَّجِيبَة"},
    "nabhan": {"en": "Nabhan; a male given name", "ur": "نبہان (مردانہ نام)", "fa": "نبهان (نام مردانه)", "hi": "नभान (पुरुष नाम)", "ps": "نبهان (نر نوم)", "ar": "نَبْهَان (اسْم عَلَم مُذَكَّر)"},
    "nabi": {"en": "Nabi; prophet", "ur": "نبی، پیغمبر", "fa": "نبی، پیامبر", "hi": "नबी, पैग़ंबर", "ps": "نبي، پیغمبر", "ar": "النَّبِي، الرَّسُول"},
    "nabih": {"en": "Nabih; noble, distinguished, intelligent", "ur": "نبیہ، نجیب، ذہین", "fa": "نبیه، نجیب", "hi": "नबीह, कुलीन", "ps": "نبیه، نومیالی", "ar": "النَّبِيه، النَّجِيب"},
    "nabiha": {"en": "Nabiha; noble, distinguished (feminine)", "ur": "نبیہہ، نجیب (مؤنث)", "fa": "نبیهه، نجیب (مؤنث)", "hi": "नबीहा, कुलीन (स्त्री)", "ps": "نبیهه، نومیالې", "ar": "النَّبِيهَة، النَّجِيبَة"},
    "nabihah": {"en": "Nabihah; noble, distinguished (feminine)", "ur": "نبیہہ، نجیب (مؤنث)", "fa": "نبیهه، نجیب (مؤنث)", "hi": "नबीहा, कुलीन (स्त्री)", "ps": "نبیهه، نومیالې", "ar": "النَّبِيهَة، النَّجِيبَة"},
    "nabil": {"en": "Nabil; noble, high-born", "ur": "نبیل، نجیب، شریف", "fa": "نبیل، نجیب", "hi": "नबील, कुलीन", "ps": "نبیل، نومیالی", "ar": "النَّبِيل، النَّجِيب"},
    "nabila": {"en": "Nabila; noble, high-born (feminine)", "ur": "نبیلہ، نجیب (مؤنث)", "fa": "نبيله، نجیب (مؤنث)", "hi": "नबीला, कुलीन (स्त्री)", "ps": "نبيله، نومیالې", "ar": "النَّبِيلَة، النَّجِيبَة"},
    "nacer": {"en": "Nacer; helper, supporter", "ur": "ناصر، مددگار", "fa": "ناصر، یاری‌کننده", "hi": "नासिर, सहायक", "ps": "ناصر، مرستندوی", "ar": "النَّاصِر، الْمُعِين"},
    "nacira": {"en": "Nacira; helper, supporter (feminine)", "ur": "ناصرہ، مددگار (مؤنث)", "fa": "ناصره، یاری‌کننده (مؤنث)", "hi": "नासिरा, सहायिका", "ps": "ناصره، مرستندوې", "ar": "النَّاصِرَة، الْمُعِينَة"},
})

CUR = {
 "murtada": ("مُرْتَضَى", "مرتضیٰ", "مرتضی", "मुर्तज़ा", "مرتضی", "chosen_murtada", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); مُرْتَضَى (Murtadā)", False, "high",
             "Murtada is Arabic مُرْتَضَى (Murtadā) 'chosen, selected, approved', from the root ر ض و (r-ḍ-w). The source gloss 'Lover' is unsupported and has been replaced with the lexical sense. Same name as murtaza."),
 "murtadha": ("مُرْتَضَى", "مرتضیٰ", "مرتضی", "मुर्तज़ा", "مرتضی", "chosen_murtada", "Arabic", "Male",
              "Arabic root ر ض و (r-ḍ-w); مُرْتَضَى (Murtadā)", False, "high",
              "Murtadha is Arabic مُرْتَضَى (Murtadā) 'chosen, selected, approved', from the root ر ض و (r-ḍ-w). The source gloss 'Chosen or Accepted' is consistent. Same name as murtada."),
 "murtaja": ("مُرْتَجَى", "مرتجیٰ", "مرتجا", "मुर्तजा", "مرتجا", "hoped_for", "Arabic", "Male",
             "Arabic root ر ج و (r-j-w); مُرْتَجَى (Murtajā)", False, "high",
             "Murtaja is Arabic مُرْتَجَى (Murtajā) 'hoped-for, desired', from the root ر ج و (r-j-w). The source gloss 'Support, Helper' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male."),
 "murtaza": ("مُرْتَضَى", "مرتضیٰ", "مرتضی", "मुर्तज़ा", "مرتضی", "chosen_murtada", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); مُرْتَضَى (Murtadā)", False, "high",
             "Murtaza is Arabic مُرْتَضَى (Murtadā) 'chosen, selected, approved', from the root ر ض و (r-ḍ-w). The source gloss 'Triumphant, Victorious' is unsupported and has been replaced with the lexical sense. Same name as murtada."),
 "murtazi": ("مُرْتَضِي", "مرتضی", "مرتضی", "मुर्तज़ी", "مرتضی", "murtazi", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); مُرْتَضِي (Murtadī)", False, "high",
             "Murtazi is Arabic مُرْتَضِي (Murtadī) 'one who is content, satisfied', from the root ر ض و (r-ḍ-w). The source gloss 'One who strives, struggles' is unsupported and has been replaced with the lexical sense."),
 "murtuja": ("مُرْتَجَاة", "مرتجاة", "مرتجاه", "मुर्तुजा", "مرتجاه", "hoped_for", "Arabic", "Male",
             "Arabic root ر ج و (r-j-w); مُرْتَجَى (Murtajā)", False, "high",
             "Murtuja is recorded here as Arabic مُرْتَجَى (Murtajā) 'hoped-for, desired', from the root ر ج و (r-j-w). The source gloss 'Chosen One' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male. Same name as murtaja."),
 "murtuza": ("مُرْتَضَى", "مرتضیٰ", "مرتضی", "मुर्तुज़ा", "مرتضی", "chosen_murtada", "Arabic", "Male",
             "Arabic root ر ض و (r-ḍ-w); مُرْتَضَى (Murtadā)", False, "high",
             "Murtuza is a spelling variant of Arabic مُرْتَضَى (Murtadā) 'chosen, selected', from the root ر ض و (r-ḍ-w). The source gloss 'Chosen One' is consistent. Same name as murtada."),
 "musa": ("موسى", "موسیٰ", "موسی", "मूसा", "موسی", "moses", "Arabic", "Male",
          "Arabic مُوسَى (Mūsā)", False, "high",
          "Musa is Arabic مُوسَى (Mūsā), the name of Moses, a prophet named in the Qur'an. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and identification have been established from the Qur'anic name. Same name as moosa and mosa."),
 "musaab": ("مُصْعَب", "مصعب", "مصعب", "मुसअब", "مصعب", "musab", "Arabic", "Male",
            "Arabic مُصْعَب (Muṣʿab)", False, "high",
            "Musaab is Arabic مُصْعَب (Muṣʿab), a male given name borne by a companion of the Prophet. CRITICAL SOURCE ERROR: the source gave موسعب (a non-standard form); the correct form is مُصْعَب. The source gloss 'Warrior or Fighter' is unsupported and has been replaced with the documented identification."),
 "musaad": ("مُسْعَد", "مسعد", "مسعد", "मुसअद", "مسعد", "musaad", "Arabic", "Male",
            "Arabic root س ع د (s-ʿ-d); مُسْعَد (Musʿad)", False, "high",
            "Musaad is Arabic مُسْعَد (Musʿad) 'happy, fortunate', from the root س ع د (s-ʿ-d). The source gloss 'Supporter of Good' is unsupported and has been replaced with the lexical sense."),
 "musab": ("مُصْعَب", "مصعب", "مصعب", "मुसअब", "مصعب", "musab", "Arabic", "Male",
           "Arabic مُصْعَب (Muṣʿab)", False, "high",
           "Musab is Arabic مُصْعَب (Muṣʿab), a male given name borne by a companion of the Prophet. CRITICAL SOURCE ERROR: the source gave مصاب (a different form); the correct form is مُصْعَب. The source gloss 'Magnificent, excellent' is unsupported and has been replaced with the documented identification. Same name as musaab."),
 "musaddiq": ("مُصَدِّق", "مصدق", "مصدق", "मुसद्दिक़", "مصدق", "musaddiq", "Arabic", "Male",
              "Arabic root ص د ق (ṣ-d-q); مُصَدِّق (Muṣaddiq)", False, "high",
              "Musaddiq is Arabic مُصَدِّق (Muṣaddiq) 'one who affirms the truth', from the root ص د ق (ṣ-d-q). The source gloss 'One who is honest and truthful' is broadly consistent."),
 "musadiq": ("مُصَادِق", "مصدق", "مصدق", "मुसादिक़", "مصدق", "musadiq", "Arabic", "Male",
             "Arabic root ص د ق (ṣ-d-q); مُصَادِق (Muṣādiq)", False, "high",
             "Musadiq is Arabic مُصَادِق (Muṣādiq) 'one who affirms the truth', from the root ص د ق (ṣ-d-q). The source gloss 'Truthful, One Who Affirms the Truth' is consistent. Same name as musaddiq."),
 "musafer": ("مُسَافِر", "مسافر", "مسافر", "मुसाफ़िर", "مسافر", "musafer", "Arabic", "Male",
             "Arabic root س ف ر (s-f-r); مُسَافِر (Musāfir)", False, "high",
             "Musafer is Arabic مُسَافِر (Musāfir) 'traveller, voyager', from the root س ف ر (s-f-r). The source gloss 'Traveler, Voyager' is consistent."),
 "musan": ("مُسَنَّى", "مسنیٰ", "مسنی", "मुसन", "مسنی", "uncertain_form", "Unknown", "Male",
           "No reliable root analysis established.", False, "low",
           "Musan is recorded at low confidence. CRITICAL SOURCE ERROR: the source gave the Latin string 'Musan' instead of a script form and glossed the name 'Calm'; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "musarat": ("مَسَرَّة", "مسرت", "مسرت", "मुसर्रत", "مسرت", "musarrat", "Arabic", "Female",
             "Arabic root س ر ر (s-r-r); مَسَرَّة (Masarra)", False, "high",
             "Musarat is Arabic مَسَرَّة (Masarra) 'joy, delight, happiness', from the root س ر ر (s-r-r). CRITICAL SOURCE ERROR: the source gave مصرةت (a non-standard form); the correct form is مَسَرَّة. The source gloss 'Delight, pleasure' is consistent. Same name as musarrat."),
 "musarrat": ("مَسَرَّة", "مسرت", "مسرت", "मुसर्रत", "مسرت", "musarrat", "Arabic", "Female",
              "Arabic root س ر ر (s-r-r); مَسَرَّة (Masarra)", False, "high",
              "Musarrat is Arabic مَسَرَّة (Masarra) 'joy, delight, happiness', from the root س ر ر (s-r-r). CRITICAL SOURCE ERROR: the source gave مسرات (a non-standard form); the correct form is مَسَرَّة. The source gloss 'Ornamented, Embellished' is unsupported and has been replaced with the lexical sense. Same name as musarat."),
 "musawir": ("مُصَوِّر", "مصور", "مصور", "मुसव्विर", "مصور", "musawir", "Arabic", "Male",
             "Arabic root ص و ر (ṣ-w-r); مُصَوِّر (Muṣawwir)", False, "high",
             "Musawir is Arabic مُصَوِّر (Muṣawwir) 'painter, one who depicts', from the root ص و ر (ṣ-w-r). CRITICAL SOURCE ERROR: the source gave the Latin string 'Musawir' instead of a script form. The source gloss 'Painted, Colorful' is unsupported and has been replaced with the lexical sense."),
 "musfira": ("مُسْفِرَة", "مسفرہ", "مسفره", "मुस्फ़िरा", "مسفره", "musfira", "Arabic", "Female",
             "Arabic root س ف ر (s-f-r); مُسْفِرَة (Musfira)", False, "high",
             "Musfira is Arabic مُسْفِرَة (Musfira) 'bright, radiant' (feminine), from the root س ف ر (s-f-r). CRITICAL SOURCE ERROR: the source gave مصفيرة (a non-standard form); the correct form is مُسْفِرَة. The source gloss 'Pure and Chaste' is unsupported and has been replaced with the lexical sense. Same name as musfirah."),
 "musfirah": ("مُسْفِرَة", "مسفرہ", "مسفره", "मुस्फ़िरा", "مسفره", "musfira", "Arabic", "Female",
              "Arabic root س ف ر (s-f-r); مُسْفِرَة (Musfira)", False, "high",
              "Musfirah is Arabic مُسْفِرَة (Musfira) 'bright, radiant' (feminine), from the root س ف ر (s-f-r). CRITICAL SOURCE ERROR: the source gave مسفرة (a non-standard form); the correct form is مُسْفِرَة. The source gloss 'Pure and Chaste' is unsupported and has been replaced with the lexical sense. Same name as musfira."),
 "mushahid": ("مُشَاهِد", "مشاہد", "مشاهد", "मुशाहिद", "مشاهد", "mushahid", "Arabic", "Male",
              "Arabic root ش ه د (sh-h-d); مُشَاهِد (Mushāhid)", False, "high",
              "Mushahid is Arabic مُشَاهِد (Mushāhid) 'witness, observer', from the root ش ه د (sh-h-d). The source gloss 'Witness' is consistent."),
 "musheer": ("مُشِير", "مشیر", "مشیر", "मुशीर", "مشیر", "mushir", "Arabic", "Male",
             "Arabic root ش و ر (sh-w-r); مُشِير (Mushīr)", False, "high",
             "Musheer is Arabic مُشِير (Mushīr) 'advisor, counsellor, guide', from the root ش و ر (sh-w-r). The source gloss 'Traveler' is unsupported and has been replaced with the lexical sense. Same name as mushir."),
 "mushfiq": ("مُشْفِق", "مشفق", "مشفق", "मुशफ़िक़", "مشفق", "mushfiq", "Arabic", "Male",
             "Arabic root ش ف ق (sh-f-q); مُشْفِق (Mushfiq)", False, "high",
             "Mushfiq is Arabic مُشْفِق (Mushfiq) 'compassionate, kind, anxious for others', from the root ش ف ق (sh-f-q). The source gloss 'Seeker of beauty, truth, or pleasure' is unsupported and has been replaced with the lexical sense."),
 "mushir": ("مُشِير", "مشیر", "مشیر", "मुशीर", "مشیر", "mushir", "Arabic", "Male",
            "Arabic root ش و ر (sh-w-r); مُشِير (Mushīr)", False, "high",
            "Mushir is Arabic مُشِير (Mushīr) 'advisor, counsellor, guide', from the root ش و ر (sh-w-r). The source gloss 'Advisor, Counselor, or one who gives guidance' is consistent. Same name as musheer."),
 "mushtaaq": ("مُشْتَاق", "مشتاق", "مشتاق", "मुश्ताक़", "مشتاق", "mushtaq", "Arabic", "Male",
              "Arabic root ش و ق (sh-w-q); مُشْتَاق (Mushtāq)", False, "high",
              "Mushtaaq is Arabic مُشْتَاق (Mushtāq) 'longing, yearning, desirous', from the root ش و ق (sh-w-q). The source gloss 'Longing, Desiring' is consistent. Same name as mushtaq."),
 "mushtak": ("مُشْتَاق", "مشتاق", "مشتاق", "मुश्ताक़", "مشتاق", "mushtaq", "Arabic", "Male",
             "Arabic root ش و ق (sh-w-q); مُشْتَاق (Mushtāq)", False, "high",
             "Mushtak is a spelling variant of Arabic مُشْتَاق (Mushtāq) 'longing, yearning', from the root ش و ق (sh-w-q). CRITICAL SOURCE ERROR: the source gave مشتق (a different form); the correct form is مُشْتَاق. The source gloss 'Chooser' is unsupported and has been replaced with the lexical sense. Same name as mushtaq."),
 "mushtaq": ("مُشْتَاق", "مشتاق", "مشتاق", "मुश्ताक़", "مشتاق", "mushtaq", "Arabic", "Male",
             "Arabic root ش و ق (sh-w-q); مُشْتَاق (Mushtāq)", False, "high",
             "Mushtaq is Arabic مُشْتَاق (Mushtāq) 'longing, yearning, desirous', from the root ش و ق (sh-w-q). The source gloss 'Desire, longing' is consistent. Same name as mushtaaq."),
 "muska": ("مِسْك", "مسک", "مسک", "मुस्क", "مسک", "muska", "Arabic", "Female",
           "Arabic مِسْك (Misk) 'musk'", False, "high",
           "Muska is Arabic مِسْك (Misk) 'musk, a fragrant substance'. The source gloss 'Musk fragrance' is consistent. Recorded as a common noun also used as a given name."),
 "muskaan": ("मुस्कान", "مسکان", "مسکان", "मुस्कान", "مسکان", "muskan", "Hindi", "Female",
             "Hindi मुस्कान (muskān) 'smile'", False, "high",
             "Muskaan is Hindi मुस्कान (muskān) 'smile', also used in Urdu. CRITICAL SOURCE ERROR: the source gave موسكان (a non-standard form) and labelled the origin Arabic; the word is Hindi/Urdu. The source gloss 'A twinkling star' is unsupported and has been replaced with the lexical sense. Same name as muskan."),
 "muskan": ("मुस्कान", "مسکان", "مسکان", "मुस्कान", "مسکان", "muskan", "Hindi", "Female",
            "Hindi मुस्कान (muskān) 'smile'", False, "high",
            "Muskan is Hindi मुस्कान (muskān) 'smile', also used in Urdu. CRITICAL SOURCE ERROR: the source gave موسكان (a non-standard form) and labelled the origin Arabic; the word is Hindi/Urdu. The source gloss 'Fragrant flower' is unsupported and has been replaced with the lexical sense. Same name as muskaan."),
 "musleh": ("مُصْلِح", "مصلح", "مصلح", "मुस्लिह", "مصلح", "muslih", "Arabic", "Male",
            "Arabic root ص ل ح (ṣ-l-ḥ); مُصْلِح (Muṣliḥ)", False, "high",
            "Musleh is Arabic مُصْلِح (Muṣliḥ) 'reformer, one who sets things right', from the root ص ل ح (ṣ-l-ḥ). CRITICAL SOURCE ERROR: the source gave مسلح (a different form); the correct form is مُصْلِح. The source gloss 'Guide, teacher, leader' is unsupported and has been replaced with the lexical sense. Same name as muslih."),
 "musli": ("مُصَلِّي", "مصلی", "مصلی", "मुसल्ली", "مصلی", "worshipper_praying", "Arabic", "Male",
           "Arabic root ص ل و (ṣ-l-w); مُصَلِّي (Muṣallī)", False, "high",
           "Musli is recorded here as Arabic مُصَلِّي (Muṣallī) 'one who prays, worshipper', from the root ص ل و (ṣ-l-w). CRITICAL SOURCE ERROR: the source gave the Latin string 'Musli' instead of a script form. The source gloss 'Seeker, Follower' is unsupported and has been replaced with the lexical sense."),
 "muslih": ("مُصْلِح", "مصلح", "مصلح", "मुस्लिह", "مصلح", "muslih", "Arabic", "Male",
            "Arabic root ص ل ح (ṣ-l-ḥ); مُصْلِح (Muṣliḥ)", False, "high",
            "Muslih is Arabic مُصْلِح (Muṣliḥ) 'reformer, one who sets things right', from the root ص ل ح (ṣ-l-ḥ). The source gloss 'Bringing Peace' is broadly consistent. Same name as musleh."),
 "muslihah": ("مُصْلِحَة", "مصلحہ", "مصلحه", "मुस्लिहा", "مصلحه", "reformer_f", "Arabic", "Female",
              "Arabic root ص ل ح (ṣ-l-ḥ); مُصْلِحَة (Muṣliḥa)", False, "high",
              "Muslihah is Arabic مُصْلِحَة (Muṣliḥa) 'reformer, one who sets things right' (feminine), from the root ص ل ح (ṣ-l-ḥ). CRITICAL SOURCE ERROR: the source gave مسلحة (a different form); the correct form is مُصْلِحَة. The source gloss 'Reconcile, Set Right' is broadly consistent."),
 "muslim": ("مُسْلِم", "مسلم", "مسلم", "मुस्लिम", "مسلم", "muslim", "Arabic", "Male",
            "Arabic root س ل م (s-l-m); مُسْلِم (Muslim)", False, "high",
            "Muslim is Arabic مُسْلِم (Muslim) 'one who submits to God', from the root س ل م (s-l-m). The source gloss 'One who submits to Allah' is consistent."),
 "muslima": ("مُسْلِمَة", "مسلمہ", "مسلمه", "मुस्लिमा", "مسلمه", "muslima", "Arabic", "Female",
             "Arabic root س ل م (s-l-m); مُسْلِمَة (Muslima)", False, "high",
             "Muslima is Arabic مُسْلِمَة (Muslima) 'one who submits to God' (feminine), from the root س ل م (s-l-m). The source gloss 'Follower of Islam' is broadly consistent. Same name as muslimah."),
 "muslimah": ("مُسْلِمَة", "مسلمہ", "مسلمه", "मुस्लिमा", "مسلمه", "muslima", "Arabic", "Female",
              "Arabic root س ل م (s-l-m); مُسْلِمَة (Muslima)", False, "high",
              "Muslimah is Arabic مُسْلِمَة (Muslima) 'one who submits to God' (feminine), from the root س ل م (s-l-m). The source gloss 'Submissive to Allah' is broadly consistent. Same name as muslima."),
 "muslimin": ("مُسْلِمِين", "مسلمین", "مسلمین", "मुस्लिमीन", "مسلمین", "muslimin", "Arabic", "Male",
              "Arabic root س ل م (s-l-m); مُسْلِمِين (Muslimīn)", False, "high",
              "Muslimin is Arabic مُسْلِمِين (Muslimīn) 'Muslims', the plural of مُسْلِم (muslim), from the root س ل م (s-l-m). The source gloss 'Muslim' is broadly consistent. Recorded as a plural form also used as a given name."),
 "mussah": ("مُوسَى", "موسیٰ", "موسی", "मूसा", "موسی", "moses", "Arabic", "Male",
            "Arabic مُوسَى (Mūsā)", False, "high",
            "Mussah is recorded here as Arabic مُوسَى (Mūsā), the name of Moses, a prophet named in the Qur'an. CRITICAL SOURCE ERROR: the source gave أحمد (a different name) and glossed the name 'Guide, Teacher'; the source gloss is unsupported. Same name as musa."),
 "mustaf": ("مُصْطَفَى", "مصطفیٰ", "مصطفی", "मुस्तफ़ा", "مصطفی", "mustafa", "Arabic", "Male",
            "Arabic root ص ف و (ṣ-f-w); مُصْطَفَى (Muṣṭafā)", False, "high",
            "Mustaf is a short spelling of Arabic مُصْطَفَى (Muṣṭafā) 'chosen, selected', from the root ص ف و (ṣ-f-w). The source gloss 'Chosen one' is consistent. Same name as mustafa."),
 "mustafa": ("مصطفى", "مصطفیٰ", "مصطفی", "मुस्तफ़ा", "مصطفی", "mustafa", "Arabic", "Male",
             "Arabic root ص ف و (ṣ-f-w); مُصْطَفَى (Muṣṭafā)", False, "high",
             "Mustafa is Arabic مُصْطَفَى (Muṣṭafā) 'chosen, selected', from the root ص ف و (ṣ-f-w); it is an epithet of the Prophet. CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as mostafa."),
 "mustafaa": ("مُصْطَفَى", "مصطفیٰ", "مصطفی", "मुस्तफ़ा", "مصطفی", "mustafa", "Arabic", "Male",
              "Arabic root ص ف و (ṣ-f-w); مُصْطَفَى (Muṣṭafā)", False, "high",
              "Mustafaa is a spelling variant of Arabic مُصْطَفَى (Muṣṭafā) 'chosen, selected', from the root ص ف و (ṣ-f-w). The source gloss 'Praiseworthy, Commended' is unsupported and has been replaced with the lexical sense. Same name as mustafa."),
 "mustajab": ("مُسْتَجَاب", "مستجاب", "مستجاب", "मुस्तजाब", "مستجاب", "mustajab", "Arabic", "Male",
              "Arabic root ج و ب (j-w-b); مُسْتَجَاب (Mustajāb)", False, "high",
              "Mustajab is Arabic مُسْتَجَاب (Mustajāb) 'answered, granted (of prayer)', from the root ج و ب (j-w-b). The source gloss 'Responsive, Answering' is broadly consistent."),
 "mustakim": ("مُسْتَقِيم", "مستقیم", "مستقیم", "मुस्तक़ीम", "مستقیم", "mustaqim", "Arabic", "Male",
              "Arabic root ق و م (q-w-m); مُسْتَقِيم (Mustaqīm)", False, "high",
              "Mustakim is a spelling variant of Arabic مُسْتَقِيم (Mustaqīm) 'straight, upright, correct', from the root ق و م (q-w-m). The source gloss 'The Truthful' is unsupported and has been replaced with the lexical sense. Same name as mustaqim."),
 "mustansar": ("مُسْتَنْصِر", "مستنصر", "مستنصر", "मुस्तनसिर", "مستنصر", "mustansir", "Arabic", "Male",
               "Arabic root ن ص ر (n-ṣ-r); مُسْتَنْصِر (Mustanṣir)", False, "high",
               "Mustansar is a spelling variant of Arabic مُسْتَنْصِر (Mustanṣir) 'one who seeks help or victory', from the root ن ص ر (n-ṣ-r). The source gloss 'Support, Strength' is unsupported and has been replaced with the lexical sense. Same name as mustansir."),
 "mustansir": ("مُسْتَنْصِر", "مستنصر", "مستنصر", "मुस्तनसिर", "مستنصر", "mustansir", "Arabic", "Male",
               "Arabic root ن ص ر (n-ṣ-r); مُسْتَنْصِر (Mustanṣir)", False, "high",
               "Mustansir is Arabic مُسْتَنْصِر (Mustanṣir) 'one who seeks help or victory', from the root ن ص ر (n-ṣ-r). CRITICAL SOURCE ERROR: the source gave مُسْتانصر (a non-standard form); the correct form is مُسْتَنْصِر. The source gloss 'Guide, leader, finder' is unsupported and has been replaced with the lexical sense. Same name as mustansar."),
 "mustapha": ("مُصْطَفَى", "مصطفیٰ", "مصطفی", "मुस्तफ़ा", "مصطفی", "mustafa", "Arabic", "Male",
              "Arabic root ص ف و (ṣ-f-w); مُصْطَفَى (Muṣṭafā)", False, "high",
              "Mustapha is a spelling variant of Arabic مُصْطَفَى (Muṣṭafā) 'chosen, selected', from the root ص ف و (ṣ-f-w). The source gloss 'Chosen one, elect' is consistent. Same name as mustafa."),
 "mustaqeem": ("مُسْتَقِيم", "مستقیم", "مستقیم", "मुस्तक़ीम", "مستقیم", "mustaqim", "Arabic", "Male",
               "Arabic root ق و م (q-w-m); مُسْتَقِيم (Mustaqīm)", False, "high",
               "Mustaqeem is a spelling variant of Arabic مُسْتَقِيم (Mustaqīm) 'straight, upright, correct', from the root ق و م (q-w-m). CRITICAL SOURCE ERROR: the source gave مصتقعم (a non-standard form); the correct form is مُسْتَقِيم. The source gloss 'Constantly present' is unsupported and has been replaced with the lexical sense. Same name as mustaqim."),
 "mustaqim": ("مُسْتَقِيم", "مستقیم", "مستقیم", "मुस्तक़ीम", "مستقیم", "mustaqim", "Arabic", "Male",
              "Arabic root ق و م (q-w-m); مُسْتَقِيم (Mustaqīm)", False, "high",
              "Mustaqim is Arabic مُسْتَقِيم (Mustaqīm) 'straight, upright, correct', from the root ق و م (q-w-m). The source gloss 'Walks on the Straight Path' is a religious application of the lexical sense. Same name as mustakim."),
 "musthafa": ("مُصْطَفَى", "مصطفیٰ", "مصطفی", "मुस्तफ़ा", "مصطفی", "mustafa", "Arabic", "Male",
              "Arabic root ص ف و (ṣ-f-w); مُصْطَفَى (Muṣṭafā)", False, "high",
              "Musthafa is a spelling variant of Arabic مُصْطَفَى (Muṣṭafā) 'chosen, selected', from the root ص ف و (ṣ-f-w). CRITICAL SOURCE ERROR: the source gave مستحفى (a non-standard form); the correct form is مُصْطَفَى. The source gloss 'Chosen one, beloved' is partly consistent. Same name as mustafa."),
 "mutahar": ("مُطَهَّر", "مطہر", "مطهر", "मुतह्हर", "مطهر", "mutahar", "Arabic", "Male",
             "Arabic root ط ه ر (ṭ-h-r); مُطَهَّر (Muṭahhar)", False, "high",
             "Mutahar is Arabic مُطَهَّر (Muṭahhar) 'purified, pure', from the root ط ه ر (ṭ-h-r). CRITICAL SOURCE ERROR: the source gave مُتَحَر (a non-standard form); the correct form is مُطَهَّر. The source gloss 'Pious, Wise' is unsupported and has been replaced with the lexical sense. Same name as mutahir."),
 "mutahir": ("مُطَهِّر", "مطہر", "مطهر", "मुताहिर", "مطهر", "mutahir", "Arabic", "Male",
             "Arabic root ط ه ر (ṭ-h-r); مُطَهِّر (Muṭahhir)", False, "high",
             "Mutahir is Arabic مُطَهِّر (Muṭahhir) 'purifying, cleansing', from the root ط ه ر (ṭ-h-r). The source gloss 'Pure, Immaculate' is broadly consistent. Same name as mutahar."),
 "mutalib": ("مُطَّلِب", "مطلب", "مطلب", "मुतलिब", "مطلب", "mutalib", "Arabic", "Male",
             "Arabic root ط ل ب (ṭ-l-b); مُطَّلِب (Muṭṭalib)", False, "high",
             "Mutalib is Arabic مُطَّلِب (Muṭṭalib) 'seeker, one who demands', from the root ط ل ب (ṭ-l-b); it occurs in the compound name ʿAbd al-Muṭṭalib. CRITICAL SOURCE ERROR: the source gave the Latin string 'Mutalib' instead of a script form. The source gloss 'Dedicated, devout, or having a lover' is unsupported and has been replaced with the lexical sense."),
 "mutasim": ("مُعْتَصِم", "معتصم", "معتصم", "मोतसिम", "معتصم", "mutasim", "Arabic", "Male",
             "Arabic root ع ص م (ʿ-ṣ-m); مُعْتَصِم (Muʿtaṣim)", False, "high",
             "Mutasim is Arabic مُعْتَصِم (Muʿtaṣim) 'one who holds fast, clings firmly', from the root ع ص م (ʿ-ṣ-m). CRITICAL SOURCE ERROR: the source gave مطعسم (a non-standard form); the correct form is مُعْتَصِم. The source gloss 'Firm, Established' is broadly consistent. Same name as motasim."),
 "mutassim": ("مُعْتَصِم", "معتصم", "معتصم", "मोतसिम", "معتصم", "mutasim", "Arabic", "Male",
              "Arabic root ع ص م (ʿ-ṣ-m); مُعْتَصِم (Muʿtaṣim)", False, "high",
              "Mutassim is a spelling variant of Arabic مُعْتَصِم (Muʿtaṣim) 'one who holds fast', from the root ع ص م (ʿ-ṣ-m). The source gloss 'One who is given power or authority' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is male. Same name as mutasim."),
 "mutawakkil": ("مُتَوَكِّل", "متوکل", "متوکل", "मुतवक्किल", "متوکل", "mutawakkil", "Arabic", "Male",
                "Arabic root و ك ل (w-k-l); مُتَوَكِّل (Mutawakkil)", False, "high",
                "Mutawakkil is Arabic مُتَوَكِّل (Mutawakkil) 'one who trusts in God', from the root و ك ل (w-k-l). The source gloss 'Trusts in Allah' is consistent."),
 "mutaz": ("مُعْتَزّ", "معتز", "معتز", "मोताज़", "معتز", "mutaz", "Arabic", "Male",
           "Arabic root ع ز ز (ʿ-z-z); مُعْتَزّ (Muʿtazz)", False, "high",
           "Mutaz is Arabic مُعْتَزّ (Muʿtazz) 'glorified, honoured, proud', from the root ع ز ز (ʿ-z-z). CRITICAL SOURCE ERROR: the source gave مُتَعَزّ (a non-standard form); the correct form is مُعْتَزّ. The source gloss 'Withheld' is unsupported and has been replaced with the lexical sense. Same name as motaz."),
 "muthanna": ("مُثَنَّى", "مثنیٰ", "مثنی", "मुसन्ना", "مثنی", "muthanna", "Arabic", "Male",
              "Arabic root ث ن ي (th-n-y); مُثَنَّى (Muthannā)", False, "high",
              "Muthanna is Arabic مُثَنَّى (Muthannā) 'doubled, twofold', from the root ث ن ي (th-n-y). The source gloss 'Reviver, Renewer' is unsupported and has been replaced with the lexical sense."),
 "muti": ("مُطِيع", "مطیع", "مطیع", "मुती", "مطیع", "muti", "Arabic", "Male",
          "Arabic root ط و ع (ṭ-w-ʿ); مُطِيع (Muṭīʿ)", False, "high",
          "Muti is Arabic مُطِيع (Muṭīʿ) 'obedient, compliant', from the root ط و ع (ṭ-w-ʿ). CRITICAL SOURCE ERROR: the source gave مطي (a non-standard form); the correct form is مُطِيع. The source gloss 'Governor, Leader' is unsupported and has been replaced with the lexical sense."),
 "mutia": ("مُطِيعَة", "مطیعہ", "مطیعه", "मुतीआ", "مطیعه", "mutia", "Arabic", "Female",
           "Arabic root ط و ع (ṭ-w-ʿ); مُطِيعَة (Muṭīʿa)", False, "high",
           "Mutia is Arabic مُطِيعَة (Muṭīʿa) 'obedient' (feminine), from the root ط و ع (ṭ-w-ʿ). CRITICAL SOURCE ERROR: the source gave the Latin string 'Mutia' instead of a script form. The source gloss \"Mother's love\" is unsupported and has been replaced with the lexical sense."),
 "mutlaq": ("مُطْلَق", "مطلق", "مطلق", "मुतलक़", "مطلق", "mutlaq", "Arabic", "Male",
            "Arabic root ط ل ق (ṭ-l-q); مُطْلَق (Muṭlaq)", False, "high",
            "Mutlaq is Arabic مُطْلَق (Muṭlaq) 'absolute, unrestricted, free', from the root ط ل ق (ṭ-l-q). The source gloss 'Unrestrained, Free' is consistent."),
 "muwafaq": ("مُوَفَّق", "موفق", "موفق", "मुवाफ़िक़", "موفق", "muwafaq", "Arabic", "Male",
             "Arabic root و ف ق (w-f-q); مُوَفَّق (Muwaffaq)", False, "high",
             "Muwafaq is Arabic مُوَفَّق (Muwaffaq) 'successful, reconciled, agreed', from the root و ف ق (w-f-q). The source gloss 'Reunited, Agreed, Successful' is partly consistent."),
 "muyassar": ("مُيَسَّر", "میسر", "میسر", "मुयस्सर", "میسر", "muyassar", "Arabic", "Female",
              "Arabic root ي س ر (y-s-r); مُيَسَّر (Muyassar)", False, "high",
              "Muyassar is Arabic مُيَسَّر (Muyassar) 'made easy, facilitated', from the root ي س ر (y-s-r). CRITICAL SOURCE ERROR: the source gave مياسر (a non-standard form); the correct form is مُيَسَّر. The source gloss 'Delicately prepared' is unsupported and has been replaced with the lexical sense."),
 "muza": ("مُزَّة", "مزہ", "مزه", "मुज़ा", "مزه", "uncertain_form", "Unknown", "Unknown",
          "No reliable root analysis established.", False, "low",
          "Muza is recorded at low confidence. CRITICAL SOURCE ERROR: the source gave موزا (a non-standard form) and glossed the name with a root reference; no verified Arabic lexical form could be confirmed for this spelling. No confident meaning is asserted."),
 "muzaffar": ("مُظَفَّر", "مظفر", "مظفر", "मुज़फ़्फ़र", "مظفر", "muzaffar", "Arabic", "Male",
              "Arabic root ظ ف ر (ẓ-f-r); مُظَفَّر (Muẓaffar)", False, "high",
              "Muzaffar is Arabic مُظَفَّر (Muẓaffar) 'victorious, triumphant', from the root ظ ف ر (ẓ-f-r). CRITICAL SOURCE ERROR: the source gave منزفر (a non-standard form); the correct form is مُظَفَّر. The source gloss 'Triumphant, Victorious' is consistent."),
 "muzahid": ("مُجَاهِد", "مجاہد", "مجاهد", "मुजाहिद", "مجاهد", "muzahid", "Arabic", "Male",
             "Arabic root ج ه د (j-h-d); مُجَاهِد (Mujāhid)", False, "high",
             "Muzahid is a spelling variant of Arabic مُجَاهِد (Mujāhid) 'one who strives, fighter', from the root ج ه د (j-h-d). CRITICAL SOURCE ERROR: the source gave مزاحد (a non-standard form); the correct form is مُجَاهِد. The source gloss 'Striver, Warrior' is broadly consistent. Same name as mujahid."),
 "muzakkir": ("مُذَكِّر", "مذکر", "مذکر", "मुज़क्किर", "مذکر", "muzakkir", "Arabic", "Male",
              "Arabic root ذ ك ر (dh-k-r); مُذَكِّر (Mudhakkir)", False, "high",
              "Muzakkir is Arabic مُذَكِّر (Mudhakkir) 'one who reminds, admonisher', from the root ذ ك ر (dh-k-r). The source gloss 'Remembrer, Recall' is broadly consistent."),
 "muzammal": ("مُزَّمِّل", "مزمل", "مزمل", "मुज़म्मिल", "مزمل", "muzammil", "Arabic", "Male",
              "Arabic root ز م ل (z-m-l); مُزَّمِّل (Muzzammil)", False, "high",
              "Muzammal is a spelling variant of Arabic مُزَّمِّل (Muzzammil) 'one wrapped in a cloak', from the root ز م ل (z-m-l); it is a Qur'anic sura name. CRITICAL SOURCE ERROR: the source gave مُظَمَّل (a non-standard form); the correct form is مُزَّمِّل. The source gloss 'Subduer, Victorious' is unsupported and has been replaced with the lexical sense. Same name as muzzammil."),
 "muzna": ("مُزْنَة", "مزنہ", "مزنه", "मुज़्ना", "مزنه", "muzna", "Arabic", "Female",
           "Arabic root م ز ن (m-z-n); مُزْنَة (Muzna)", False, "high",
           "Muzna is Arabic مُزْنَة (Muzna) 'rain cloud, raindrop', from the root م ز ن (m-z-n). CRITICAL SOURCE ERROR: the source gave مُزنہ (a non-standard form); the correct form is مُزْنَة. The source gloss 'Raindrop' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "muzzammil": ("مُزَّمِّل", "مزمل", "مزمل", "मुज़म्मिल", "مزمل", "muzammil", "Arabic", "Male",
               "Arabic root ز م ل (z-m-l); مُزَّمِّل (Muzzammil)", False, "high",
               "Muzzammil is Arabic مُزَّمِّل (Muzzammil) 'one wrapped in a cloak', from the root ز م ل (z-m-l); it is a Qur'anic sura name. CRITICAL SOURCE ERROR: the source gave مزمّل (a non-standard form); the correct form is مُزَّمِّل. The source gloss 'One who is constantly present' is unsupported and has been replaced with the lexical sense. Same name as muzammal."),
 "myesha": ("عائشة", "عائشہ", "عایشه", "मीशा", "عایشه", "myesha", "Arabic", "Female",
            "Arabic عَائِشَة (ʿĀʾisha)", False, "high",
            "Myesha is an English spelling of Arabic عَائِشَة (ʿĀʾisha), the name of the Prophet's wife. CRITICAL SOURCE ERROR: the source gave ميشا (a non-standard form) and glossed the name 'Intense one'; the source gloss is unsupported. Same name as aisha."),
 "myrah": ("مَيْرَة", "میرہ", "میره", "मायरा", "میره", "myrah", "Arabic", "Female",
           "Arabic مَيْرَة (Mayra)", False, "medium",
           "Myrah is recorded as Arabic مَيْرَة (Mayra), a female given name. CRITICAL SOURCE ERROR: the source gave ميره (a non-standard form) and glossed the name 'Grace'; the source gloss is unsupported. The identification is recorded at medium confidence."),
 "naahil": ("نَاهِل", "ناہل", "ناهل", "नाहिल", "ناهل", "naahil", "Arabic", "Male",
            "Arabic root ن ه ل (n-h-l); نَاهِل (Nāhil)", False, "high",
            "Naahil is Arabic نَاهِل (Nāhil) 'thin, slender, lean', from the root ن ه ل (n-h-l). The source gloss 'A stream, or a mole (in the face)' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "naail": ("نَائِل", "نائل", "نائل", "नाइल", "نائل", "naail", "Arabic", "Male",
           "Arabic root ن ي ل (n-y-l); نَائِل (Nāʾil)", False, "high",
           "Naail is Arabic نَائِل (Nāʾil) 'one who obtains, attainer', from the root ن ي ل (n-y-l). CRITICAL SOURCE ERROR: the source gave ناعل (a non-standard form); the correct form is نَائِل. The source gloss 'Helpful' is unsupported and has been replaced with the lexical sense."),
 "naaim": ("نَاعِم", "ناعم", "ناعم", "नाइम", "ناعم", "naaim", "Arabic", "Male",
           "Arabic root ن ع م (n-ʿ-m); نَاعِم (Nāʿim)", False, "high",
           "Naaim is Arabic نَاعِم (Nāʿim) 'soft, delicate, pleasant', from the root ن ع م (n-ʿ-m). The source gloss 'Given to the good-doer' is unsupported and has been replaced with the lexical sense."),
 "naaima": ("نَعِيمَة", "نعیمہ", "نعیمه", "नईमा", "نعیمه", "naaima", "Arabic", "Female",
            "Arabic root ن ع م (n-ʿ-m); نَعِيمَة (Naʿīma)", False, "high",
            "Naaima is Arabic نَعِيمَة (Naʿīma) 'soft, delicate, pleasant' (feminine), from the root ن ع م (n-ʿ-m). The source gloss 'Graceful, attractive' is broadly consistent."),
 "naajih": ("نَاجِح", "ناجح", "ناجح", "नाजिह", "ناجح", "naajih", "Arabic", "Male",
            "Arabic root ن ج ح (n-j-ḥ); نَاجِح (Nājiḥ)", False, "high",
            "Naajih is Arabic نَاجِح (Nājiḥ) 'successful, prosperous', from the root ن ج ح (n-j-ḥ). The source gloss 'Successful, Helper' is partly consistent."),
 "naaman": ("نُعْمَان", "نعمان", "نعمان", "नअमान", "نعمان", "naaman", "Arabic", "Male",
            "Arabic نُعْمَان (Nuʿmān)", False, "high",
            "Naaman is Arabic نُعْمَان (Nuʿmān), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string \"Na'aman\" instead of a script form. The source gloss 'Given by God' is unsupported and has been replaced with the documented identification."),
 "naasih": ("نَاصِح", "ناصح", "ناصح", "नासिह", "ناصح", "naasih", "Arabic", "Male",
            "Arabic root ن ص ح (n-ṣ-ḥ); نَاصِح (Nāṣiḥ)", False, "high",
            "Naasih is Arabic نَاصِح (Nāṣiḥ) 'advisor, sincere counsellor', from the root ن ص ح (n-ṣ-ḥ). The source gloss 'Advisor, Counselor' is consistent."),
 "naasir": ("نَاصِر", "ناصر", "ناصر", "नासिर", "ناصر", "naasir", "Arabic", "Male",
            "Arabic root ن ص ر (n-ṣ-r); نَاصِر (Nāṣir)", False, "high",
            "Naasir is Arabic نَاصِر (Nāṣir) 'helper, supporter', from the root ن ص ر (n-ṣ-r). The source gloss 'Helper, Supporter' is consistent. Same name as nacer."),
 "naaz": ("ناز", "ناز", "ناز", "नाज़", "ناز", "naaz", "Persian", "Female",
          "Persian ناز (nāz)", False, "high",
          "Naaz is Persian ناز (nāz) 'pride, coquetry, elegance'. CRITICAL SOURCE ERROR: the source labelled the origin Arabic; the word is Persian. The source gloss 'Grace, beauty' is broadly consistent."),
 "naazneen": ("نازنین", "نازنین", "نازنین", "नाज़नीन", "نازنین", "naazneen", "Persian", "Female",
              "Persian نازنین (nāzanīn)", False, "high",
              "Naazneen is Persian نازنین (nāzanīn) 'delicate, charming, sweetheart'. CRITICAL SOURCE ERROR: the source gave ناضنين (a non-standard form) and labelled the origin Arabic; the word is Persian. The source gloss 'Delight, pleasure, joy' is unsupported and has been replaced with the lexical sense."),
 "naba": ("نَبَأ", "نبأ", "نبأ", "नबा", "نبأ", "naba", "Arabic", "Female",
          "Arabic root ن ب أ (n-b-ʾ); نَبَأ (Nabaʾ)", False, "high",
          "Naba is Arabic نَبَأ (Nabaʾ) 'news, announcement, tidings', from the root ن ب أ (n-b-ʾ). The source gloss 'Awakening, Announcement' is partly consistent. Recorded as a common noun also used as a given name."),
 "nabat": ("نَبَات", "نبات", "نبات", "नबात", "نبات", "nabat", "Arabic", "Female",
           "Arabic root ن ب ت (n-b-t); نَبَات (Nabāt)", False, "high",
           "Nabat is Arabic نَبَات (Nabāt) 'plants, vegetation', from the root ن ب ت (n-b-t). The source gloss 'Garden, Paradise' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female."),
 "nabaz": ("نَبَز", "نبز", "نبز", "नबाज़", "نبز", "nabaz", "Arabic", "Male",
           "Arabic نَبَز (Nabaz)", False, "medium",
           "Nabaz is recorded as Arabic نَبَز (Nabaz), a male given name. The source gloss 'Given by Allah' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nabeeh": ("نَبِيه", "نبیہ", "نبیه", "नबीह", "نبیه", "nabeeh", "Arabic", "Male",
            "Arabic root ن ب ه (n-b-h); نَبِيه (Nabīh)", False, "high",
            "Nabeeh is Arabic نَبِيه (Nabīh) 'noble, distinguished, intelligent', from the root ن ب ه (n-b-h). The source gloss 'Gentle, Kind' is unsupported and has been replaced with the lexical sense. Same name as nabih."),
 "nabeeha": ("نَبِيهَة", "نبیہہ", "نبیهه", "नबीहा", "نبیهه", "nabeeha", "Arabic", "Female",
             "Arabic root ن ب ه (n-b-h); نَبِيهَة (Nabīha)", False, "high",
             "Nabeeha is Arabic نَبِيهَة (Nabīha) 'noble, distinguished' (feminine), from the root ن ب ه (n-b-h). The source gloss 'Gracious, Pleasing' is unsupported and has been replaced with the lexical sense. Same name as nabiha."),
 "nabeel": ("نبيل", "نبیل", "نبیل", "नबील", "نبیل", "nabeel", "Arabic", "Male",
            "Arabic root ن ب ل (n-b-l); نَبِيل (Nabīl)", False, "high",
            "Nabeel is Arabic نَبِيل (Nabīl) 'noble, high-born', from the root ن ب ل (n-b-l). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nabil."),
 "nabeela": ("نَبِيلَة", "نبیلہ", "نبيله", "नबीला", "نبيله", "nabeela", "Arabic", "Female",
             "Arabic root ن ب ل (n-b-l); نَبِيلَة (Nabīla)", False, "high",
             "Nabeela is Arabic نَبِيلَة (Nabīla) 'noble, high-born' (feminine), from the root ن ب ل (n-b-l). The source gloss 'Noble, High-born' is consistent. Same name as nabila."),
 "nabeelah": ("نَبِيلَة", "نبیلہ", "نبيله", "नबीला", "نبيله", "nabeela", "Arabic", "Female",
              "Arabic root ن ب ل (n-b-l); نَبِيلَة (Nabīla)", False, "high",
              "Nabeelah is Arabic نَبِيلَة (Nabīla) 'noble, high-born' (feminine), from the root ن ب ل (n-b-l). The source gloss 'Companion of the Prophet' is a historical association rather than a lexical sense. Same name as nabila."),
 "nabhan": ("نَبْهَان", "نبہان", "نبهان", "नभान", "نبهان", "nabhan", "Arabic", "Male",
            "Arabic نَبْهَان (Nabhān)", False, "medium",
            "Nabhan is recorded as Arabic نَبْهَان (Nabhān), a male given name. The source gloss 'Grape' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nabi": ("نَبِي", "نبی", "نبی", "नबी", "نبي", "nabi", "Arabic", "Male",
          "Arabic root ن ب أ (n-b-ʾ); نَبِي (Nabī)", False, "high",
          "Nabi is Arabic نَبِي (Nabī) 'prophet', from the root ن ب أ (n-b-ʾ). The source gloss 'Prophet' is consistent. Recorded as a title also used as a given name."),
 "nabih": ("نَبِيه", "نبیہ", "نبیه", "नबीह", "نبیه", "nabih", "Arabic", "Male",
           "Arabic root ن ب ه (n-b-h); نَبِيه (Nabīh)", False, "high",
           "Nabih is Arabic نَبِيه (Nabīh) 'noble, distinguished, intelligent', from the root ن ب ه (n-b-h). The source gloss 'Intelligent, Wise, Capable' is partly consistent. Same name as nabeeh."),
 "nabiha": ("نَبِيهَة", "نبیہہ", "نبیهه", "नबीहा", "نبیهه", "nabiha", "Arabic", "Female",
            "Arabic root ن ب ه (n-b-h); نَبِيهَة (Nabīha)", False, "high",
            "Nabiha is Arabic نَبِيهَة (Nabīha) 'noble, distinguished' (feminine), from the root ن ب ه (n-b-h). CRITICAL SOURCE ERROR: the source gave the Latin string 'Nabiha' instead of a script form. The source gloss 'Intelligent, Noble' is partly consistent. Same name as nabeeha."),
 "nabihah": ("نَبِيهَة", "نبیہہ", "نبیهه", "नबीहा", "نبیهه", "nabiha", "Arabic", "Female",
             "Arabic root ن ب ه (n-b-h); نَبِيهَة (Nabīha)", False, "high",
             "Nabihah is Arabic نَبِيهَة (Nabīha) 'noble, distinguished' (feminine), from the root ن ب ه (n-b-h). CRITICAL SOURCE ERROR: the source gave نبيحة (a non-standard form); the correct form is نَبِيهَة. The source gloss 'Guided by God, Pure' is unsupported and has been replaced with the lexical sense. Same name as nabiha."),
 "nabil": ("نَبِيل", "نبیل", "نبیل", "नबील", "نبیل", "nabil", "Arabic", "Male",
           "Arabic root ن ب ل (n-b-l); نَبِيل (Nabīl)", False, "high",
           "Nabil is Arabic نَبِيل (Nabīl) 'noble, high-born', from the root ن ب ل (n-b-l). The source gloss 'Noble, High-born' is consistent. Same name as nabeel."),
 "nabila": ("نَبِيلَة", "نبیلہ", "نبيله", "नबीला", "نبيله", "nabila", "Arabic", "Female",
            "Arabic root ن ب ل (n-b-l); نَبِيلَة (Nabīla)", False, "high",
            "Nabila is Arabic نَبِيلَة (Nabīla) 'noble, high-born' (feminine), from the root ن ب ل (n-b-l). The source gloss 'Little girl, female child' is unsupported and has been replaced with the lexical sense. Same name as nabeela."),
 "nabilah": ("نَبِيلَة", "نبیلہ", "نبيله", "नबीला", "نبيله", "nabila", "Arabic", "Female",
             "Arabic root ن ب ل (n-b-l); نَبِيلَة (Nabīla)", False, "high",
             "Nabilah is Arabic نَبِيلَة (Nabīla) 'noble, high-born' (feminine), from the root ن ب ل (n-b-l). The source gloss 'Noble, Exalted' is consistent. Same name as nabila."),
 "nacer": ("نَاصِر", "ناصر", "ناصر", "नासिर", "ناصر", "nacer", "Arabic", "Male",
           "Arabic root ن ص ر (n-ṣ-r); نَاصِر (Nāṣir)", False, "high",
           "Nacer is a Latin-alphabet spelling of Arabic نَاصِر (Nāṣir) 'helper, supporter', from the root ن ص ر (n-ṣ-r). The source gloss 'Born, brought to life, revived' is unsupported and has been replaced with the lexical sense. Same name as naasir."),
 "nacira": ("نَاصِرَة", "ناصرہ", "ناصره", "नासिरा", "ناصره", "nacira", "Arabic", "Female",
            "Arabic root ن ص ر (n-ṣ-r); نَاصِرَة (Nāṣira)", False, "high",
            "Nacira is a Latin-alphabet spelling of Arabic نَاصِرَة (Nāṣira) 'helper, supporter' (feminine), from the root ن ص ر (n-ṣ-r). CRITICAL SOURCE ERROR: the source gave 'Ali' (a different name) in the Arabic field. The source gloss 'Pure, innocent' is unsupported and has been replaced with the lexical sense."),
}
