# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 45 (nada..najid).

Source defects found in this batch:
 * WRONG / PLACEHOLDER "Arabic forms": nadeen -> "N/A"; nadeer -> "نadir" (Latin
   mixed into the Arabic field); nadi -> Latin "Nadi"; nadyne -> Latin "Nadyne";
   naef -> Latin "Naef"; naib -> "Nabi" (a different word); nail -> Latin "Nail";
   najee -> Latin "Najee"; naguib -> "نaguib" (Latin mixed in);
   nadheem -> نظيم; nadhirah -> نادرة; nadr -> نضر; nadrah -> ندرة;
   nafeesa -> نافيسہ; nafiz -> نفض; nagib -> ناجب; nagina -> ناجنة;
   nagla -> نغلة; nahi -> نحي; nahida -> نهيدة; nahyan -> نَهْيَانْ;
   nailah -> نعله; naimat -> نعمات; nain -> نَيْن; naina -> عائشة (a different name);
   nair -> نير; najam -> نجم; najd -> نجد; najet -> نجم.
 * EMPTY STUBS (8-key records, no data): nada, nadia, nadim, nafisa, nahla, najat.
 * MISLABELLED ORIGIN: nadeen (an English spelling), nadyne (an English spelling),
   nadi (a Hindi/Urdu word), naina (a Hindi name), nagina (Urdu), nair (a Malayalam
   name), nain (a Hindi name), naguib (a Latin-alphabet spelling).
 * DEGARBLED GLOSSES: nadaa "Awakening, call, summons", nadeem "Bringer of peace",
   nadeen "Gentle, soft", nadeer "guide, light", nadeera "A helper, support, or solace",
   nader "Gift, Present", nadheem "Radiant, glowing", nadheer "Observer, Watcher",
   nadhir "Warner", nadhira "Intense longing, desire", nadhirah "One who gives warning",
   nadhrah "A source of light", nadi "Friend", nadiaa "Intense, Radiant",
   nadiah "Tender, delicate, gentle", nadil "Gift, bounty", nadima "Delight, Pleasure",
   nadira "Rarity, Rare One", nadjib "Gift, reward, honor", nadjiba "Supporting",
   nadr "Sweat", nadra "Gratefulness, contentment", nadrah "Call to prayer, invocation",
   nadwa "Discussion, Council, Debate", nadyne "Mystery, Divine Secret",
   naeema "Tranquil, Soft, Comforting", naeemah "Gentle, Kind, Generous",
   naef "Gentle, soft", nael "Night", naela "Night", nafas "Breath of life",
   nafees "Precious, Rare, Valuable", nafeesa "Pure, Virtuous", nafeesah "Precious thing",
   nafeezah "Melting, Soft, Tender", nafesa "Delicacy, sweetness, softness",
   nafi "Pure, Clean", nafia "Delight, pleasure", nafisah "Precious, valuable",
   nafissa "Delightful, sweet, fragrant", nafiz "Giver, Donor", nafizah "Gift from Allah",
   naghma "Melody, Tune", nagi "Restorer, Bright, Radiant", nagib "Given, Generous",
   nagina "Jewel, Precious One", nagla "Radiant, Brilliant", naguib "Giver, Generous, Noble",
   nagwa "Graceful", nahad "Rest", nahal "Acquirer of good", nahar "River",
   naheed "Delicate, refined, and noble", naheeda "Guide, Leader", nahi "Refusal, Disapproval",
   nahid "Venus, planet", nahida "First to bloom, First to rise, Morning",
   nahyan "Elevated, Exalted", naib "Deputy, Helper, Assistant", naida "Helper, Supporter",
   naif "Clear, Straightforward, Honest", naiim "Given as a gift", nail "Little nail",
   naila "Grace, beauty, gentle", nailah "Gentle Wave", naim "Noble, Gracious",
   naima "Comfort, peace, serenity", naimah "Graceful", naimat "Nur or Light",
   nain "Luminary, Light-giver", naina "Radiant, Intense Light", nair "Light, Sun",
   najaah "Deliverance, Salvation, Victory", najaf "Venerated, Sacred",
   najah "Victory, Triumph", najam "Dew", najd "Desert", najda "Guiding, Helping",
   najdat "Revival, Resurrection", najdi "Originator, Founder", najee "Victorious",
   najeeb "Kind and just", najeeba "Noble, Generous", najet "Victorious, Conquering",
   naji "Intelligent, Wise", najiah "Elegant", najib "Noble, Generous",
   najiba "Noble, exalted", najibah "Noble, generous", najid "Helper, assistant".
 * GENDER ERRORS: nafas, nafees, nagi, nahad, nahal, nahar, naheed, nain, nair,
   najah, najd, najdi were labelled unisex where documented usage is male or the
   form is a common noun with no personal-name gender.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated44 import GLOSSES as _G44

GLOSSES = dict(_G44)
GLOSSES.update({
    "nada": {"en": "Nada; dew, generosity", "ur": "ندی، شبنم، سخاوت", "fa": "ندى، شبنم", "hi": "नदा, ओस", "ps": "ندی، شبنم", "ar": "النَّدَى، الطَّلّ"},
    "nadaa": {"en": "Nadaa; call, summons, announcement", "ur": "نداء، پکار، اعلان", "fa": "نداء، فراخوان", "hi": "निदा, पुकार", "ps": "نداء، غږ", "ar": "النِّدَاء، الدُّعَاء"},
    "nadeem": {"en": "Nadeem; companion, close friend", "ur": "ندیم، ساتھی، ہم نشین", "fa": "ندیم، همدم", "hi": "नदीम, साथी", "ps": "ندیم، ملګری", "ar": "النَّدِيم، الصَّدِيق"},
    "nadeer": {"en": "Nadeer; rare, uncommon", "ur": "ندیر، نایاب، کمیاب", "fa": "ندیر، کمیاب", "hi": "नदीर, दुर्लभ", "ps": "ندیر، کم پېښ", "ar": "النَّدِير، النَّادِر"},
    "nadeera": {"en": "Nadeera; rare, precious (feminine)", "ur": "ندیرہ، نایاب (مؤنث)", "fa": "ندیره، کمیاب (مؤنث)", "hi": "नदीरा, दुर्लभ (स्त्री)", "ps": "ندیره، کم پېښه", "ar": "النَّدِيرَة، النَّادِرَة"},
    "nader": {"en": "Nader; rare, precious", "ur": "نادر، نایاب، کمیاب", "fa": "نادر، کمیاب", "hi": "नादिर, दुर्लभ", "ps": "نادر، کم پېښ", "ar": "النَّادِر، الْقَلِيل"},
    "nadheem": {"en": "Nadheem; companion, close friend", "ur": "ندیم، ساتھی", "fa": "ندیم، همدم", "hi": "नदीम, साथी", "ps": "ندیم، ملګری", "ar": "النَّدِيم، الصَّدِيق"},
    "nadheer": {"en": "Nadheer; warner, one who warns", "ur": "نذیر، ڈرانے والا، خبردار کرنے والا", "fa": "نذیر، هشداردهنده", "hi": "नज़ीर, चेतावनी देने वाला", "ps": "نذیر، خبردار کوونکی", "ar": "النَّذِير، الْمُنْذِر"},
    "nadhir": {"en": "Nadhir; warner, one who warns", "ur": "نذیر، ڈرانے والا", "fa": "نذیر، هشداردهنده", "hi": "नज़ीर, चेतावनी देने वाला", "ps": "نذیر، خبردار کوونکی", "ar": "النَّذِير، الْمُنْذِر"},
    "nadhira": {"en": "Nadhira; warner (feminine)", "ur": "نذیرہ، ڈرانے والی", "fa": "نذیره، هشداردهنده (مؤنث)", "hi": "नज़ीरा, चेतावनी देने वाली", "ps": "نذیره، خبردار کوونکې", "ar": "النَّذِيرَة، الْمُنْذِرَة"},
    "nadhrah": {"en": "Nadhrah; radiance, brightness", "ur": "نضرہ، رونق، چمک", "fa": "نضره، درخشندگی", "hi": "नज़रा, चमक", "ps": "نضره، ځلا", "ar": "النَّضْرَة، الْبَهْجَة"},
    "nadi": {"en": "Nadi; a river or channel", "ur": "ندی، ندی نالہ", "fa": "ندی، رودخانه", "hi": "नदी, नदी", "ps": "نډۍ، سیند", "ar": "النَّدِي (نَهْر)"},
    "nadia": {"en": "Nadia; tender, delicate", "ur": "نادیہ، نرم، نازک", "fa": "نادیه، نرم", "hi": "नादिया, कोमल", "ps": "نادیه، نرمه", "ar": "نَادِيَة، النَّدِيَّة"},
    "nadiaa": {"en": "Nadiaa; tender, delicate (feminine)", "ur": "نادیہ، نرم (مؤنث)", "fa": "نادیه، نرم (مؤنث)", "hi": "नादिया, कोमल (स्त्री)", "ps": "نادیه، نرمه", "ar": "النَّدِيَّة، اللَّطِيفَة"},
    "nadiah": {"en": "Nadiah; tender, delicate (feminine)", "ur": "نادیہ، نرم (مؤنث)", "fa": "نادیه، نرم (مؤنث)", "hi": "नादिया, कोमल (स्त्री)", "ps": "نادیه، نرمه", "ar": "النَّدِيَّة، اللَّطِيفَة"},
    "nadil": {"en": "Nadil; a male given name", "ur": "ندل (مردانہ نام)", "fa": "ندل (نام مردانه)", "hi": "नदिल (पुरुष नाम)", "ps": "ندل (نر نوم)", "ar": "نَدِل (اسْم عَلَم مُذَكَّر)"},
    "nadim": {"en": "Nadim; companion, close friend", "ur": "ندیم، ساتھی، ہم نشین", "fa": "ندیم، همدم", "hi": "नदीम, साथी", "ps": "ندیم، ملګری", "ar": "النَّدِيم، الصَّدِيق"},
    "nadima": {"en": "Nadima; companion, close friend (feminine)", "ur": "ندیمہ، ساتھی (مؤنث)", "fa": "ندیمه، همدم (مؤنث)", "hi": "नदीमा, साथी (स्त्री)", "ps": "ندیمه، ملګرې", "ar": "النَّدِيمَة، الصَّدِيقَة"},
    "nadir": {"en": "Nadir; rare, precious", "ur": "نادر، نایاب، کمیاب", "fa": "نادر، کمیاب", "hi": "नादिर, दुर्लभ", "ps": "نادر، کم پېښ", "ar": "النَّادِر، الْقَلِيل"},
    "nadira": {"en": "Nadira; rare, precious (feminine)", "ur": "نادرہ، نایاب (مؤنث)", "fa": "نادره، کمیاب (مؤنث)", "hi": "नादिरा, दुर्लभ (स्त्री)", "ps": "نادره، کم پېښه", "ar": "النَّادِرَة، الْقَلِيلَة"},
    "nadjib": {"en": "Nadjib; noble, distinguished", "ur": "نجیب، نجیب، شریف", "fa": "نجیب، نجیب", "hi": "नजीब, कुलीन", "ps": "نجیب، نومیالی", "ar": "النَّجِيب، الشَّرِيف"},
    "nadjiba": {"en": "Nadjiba; noble, distinguished (feminine)", "ur": "نجیبہ، نجیب (مؤنث)", "fa": "نجیبه، نجیب (مؤنث)", "hi": "नजीबा, कुलीन (स्त्री)", "ps": "نجیبه، نومیالې", "ar": "النَّجِيبَة، الشَّرِيفَة"},
    "nadr": {"en": "Nadr; a male given name", "ur": "نضر (مردانہ نام)", "fa": "نضر (نام مردانه)", "hi": "नदर (पुरुष नाम)", "ps": "نضر (نر نوم)", "ar": "نَضْر (اسْم عَلَم مُذَكَّر)"},
    "nadra": {"en": "Nadra; radiance, brightness", "ur": "نضرہ، رونق، چمک", "fa": "نضره، درخشندگی", "hi": "नदरा, चमक", "ps": "نضره، ځلا", "ar": "النَّضْرَة، الْبَهْجَة"},
    "nadwa": {"en": "Nadwa; council, assembly, club", "ur": "ندوہ، مجلس، انجمن", "fa": "ندوه، انجمن", "hi": "नदवा, सभा", "ps": "ندوه، جرګه", "ar": "النَّدْوَة، الْمَجْلِس"},
    "nadyne": {"en": "Nadyne; a spelling of Nadia", "ur": "نادین، نادیہ کی ہجے", "fa": "نادین، املای نادیه", "hi": "नादीन, नादिया की वर्तनी", "ps": "نادین، د نادیې لیکنه", "ar": "نَادِين (صِيغَة لِاسْم نَادِيَة)"},
    "naeem": {"en": "Naeem; blessing, comfort, bliss", "ur": "نعیم، نعمت، آرام", "fa": "نعیم، نعمت", "hi": "नईम, आशीर्वाद", "ps": "نعیم، نعمت", "ar": "النَّعِيم، النِّعْمَة"},
    "naeema": {"en": "Naeema; blessing, comfort (feminine)", "ur": "نعیمہ، نعمت (مؤنث)", "fa": "نعیمه، نعمت (مؤنث)", "hi": "नईमा, आशीर्वाद (स्त्री)", "ps": "نعیمه، نعمت", "ar": "النَّعِيمَة، الْمُنْعَمَة"},
    "naef": {"en": "Naef; a male given name", "ur": "نائف (مردانہ نام)", "fa": "نائف (نام مردانه)", "hi": "नाइफ़ (पुरुष नाम)", "ps": "نائف (نر نوم)", "ar": "نَائِف (اسْم عَلَم مُذَكَّر)"},
    "nael": {"en": "Nael; one who obtains, attainer", "ur": "نائل، حاصل کرنے والا", "fa": "نائل، دست‌یابنده", "hi": "नाइल, प्राप्त करने वाला", "ps": "نائل، ترلاسه کوونکی", "ar": "النَّائِل، الْحَاصِل"},
    "naela": {"en": "Naela; one who obtains (feminine)", "ur": "نائلہ، حاصل کرنے والی", "fa": "نائله، دست‌یابنده (مؤنث)", "hi": "नाइला, प्राप्त करने वाली", "ps": "نائله، ترلاسه کوونکې", "ar": "النَّائِلَة، الْحَاصِلَة"},
    "nafas": {"en": "Nafas; breath, soul, self", "ur": "نفس، سانس، روح", "fa": "نفس، دم", "hi": "नफ़स, साँस", "ps": "نفس، ساه", "ar": "النَّفَس، الرُّوح"},
    "nafees": {"en": "Nafees; precious, rare, valuable", "ur": "نفیس، قیمتی، نایاب", "fa": "نفیس، گران‌بها", "hi": "नफ़ीस, बहुमूल्य", "ps": "نفیس، قیمتي", "ar": "النَّفِيس، الثَّمِين"},
    "nafeesa": {"en": "Nafeesa; precious, valuable (feminine)", "ur": "نفیسہ، قیمتی (مؤنث)", "fa": "نفیسه، گران‌بها (مؤنث)", "hi": "नफ़ीसा, बहुमूल्य (स्त्री)", "ps": "نفیسه، قیمتي", "ar": "النَّفِيسَة، الثَّمِينَة"},
    "nafeezah": {"en": "Nafeezah; precious, valuable (feminine)", "ur": "نفیسہ، قیمتی (مؤنث)", "fa": "نفیسه، گران‌بها (مؤنث)", "hi": "नफ़ीज़ा, बहुमूल्य (स्त्री)", "ps": "نفیسه، قیمتي", "ar": "النَّفِيسَة، الثَّمِينَة"},
    "nafesa": {"en": "Nafesa; precious, valuable (feminine)", "ur": "نفیسہ، قیمتی (مؤنث)", "fa": "نفیسه، گران‌بها (مؤنث)", "hi": "नफ़ीसा, बहुमूल्य (स्त्री)", "ps": "نفیسه، قیمتي", "ar": "النَّفِيسَة، الثَّمِينَة"},
    "nafi": {"en": "Nafi; beneficial, useful", "ur": "نافع، نفع دینے والا", "fa": "نافع، سودمند", "hi": "नाफ़ि, लाभदायक", "ps": "نافع، ګټور", "ar": "النَّافِع، الْمُفِيد"},
    "nafia": {"en": "Nafia; beneficial, useful (feminine)", "ur": "نافعہ، نفع دینے والی", "fa": "نافعه، سودمند (مؤنث)", "hi": "नाफ़िया, लाभदायक (स्त्री)", "ps": "نافعه، ګټوره", "ar": "النَّافِعَة، الْمُفِيدَة"},
    "nafis": {"en": "Nafis; precious, valuable", "ur": "نفیس، قیمتی", "fa": "نفیس، گران‌بها", "hi": "नफ़ीस, बहुमूल्य", "ps": "نفیس، قیمتي", "ar": "النَّفِيس، الثَّمِين"},
    "nafisa": {"en": "Nafisa; precious, valuable (feminine)", "ur": "نفیسہ، قیمتی (مؤنث)", "fa": "نفیسه، گران‌بها (مؤنث)", "hi": "नफ़ीसा, बहुमूल्य (स्त्री)", "ps": "نفیسه، قیمتي", "ar": "النَّفِيسَة، الثَّمِينَة"},
    "nafissa": {"en": "Nafissa; precious, valuable (feminine)", "ur": "نفیسہ، قیمتی (مؤنث)", "fa": "نفیسه، گران‌بها (مؤنث)", "hi": "नफ़ीसा, बहुमूल्य (स्त्री)", "ps": "نفیسه، قیمتي", "ar": "النَّفِيسَة، الثَّمِينَة"},
    "nafiz": {"en": "Nafiz; effective, penetrating, one who carries out", "ur": "نافذ، مؤثر، نافذ کرنے والا", "fa": "نافذ، کارساز", "hi": "नाफ़िज़, प्रभावी", "ps": "نافذ، اغېزمن", "ar": "النَّافِذ، الْمُؤَثِّر"},
    "nafizah": {"en": "Nafizah; effective, penetrating (feminine)", "ur": "نافذہ، مؤثر (مؤنث)", "fa": "نافذه، کارساز (مؤنث)", "hi": "नाफ़िज़ा, प्रभावी (स्त्री)", "ps": "نافذه، اغېزمنه", "ar": "النَّافِذَة، الْمُؤَثِّرَة"},
    "naghma": {"en": "Naghma; melody, tune", "ur": "نغمہ، سر، ترانہ", "fa": "نغمه، آهنگ", "hi": "नग़मा, धुन", "ps": "نغمه، سندره", "ar": "النَّغْمَة، اللَّحْن"},
    "nagi": {"en": "Nagi; one who is saved, survivor", "ur": "ناجی، نجات پانے والا", "fa": "ناجی، رهاشده", "hi": "नाजी, बचने वाला", "ps": "ناجي، ژغورل شوی", "ar": "النَّاجِي، الْمُنْجَى"},
    "nagib": {"en": "Nagib; noble, distinguished", "ur": "نجیب، نجیب، شریف", "fa": "نجیب، نجیب", "hi": "नजीब, कुलीन", "ps": "نجیب، نومیالی", "ar": "النَّجِيب، الشَّرِيف"},
    "nagina": {"en": "Nagina; a gem, jewel", "ur": "نگینہ، جواہر، نگ", "fa": "نگینه، جواهر", "hi": "नगीना, रत्न", "ps": "نگینه، ګاڼه", "ar": "النَّگِينَة (جَوْهَر)"},
    "nagla": {"en": "Nagla; a female given name", "ur": "نجلہ (زنانہ نام)", "fa": "نجله (نام زنانه)", "hi": "नजला (स्त्री नाम)", "ps": "نجله (ښځينه نوم)", "ar": "نَجْلَة (اسْم عَلَم مُؤَنَّث)"},
    "naguib": {"en": "Naguib; noble, distinguished", "ur": "نجیب، نجیب، شریف", "fa": "نجیب، نجیب", "hi": "नगीब, कुलीन", "ps": "نجیب، نومیالی", "ar": "النَّجِيب، الشَّرِيف"},
    "nagwa": {"en": "Nagwa; a female given name", "ur": "نجویٰ (زنانہ نام)", "fa": "نجوا (نام زنانه)", "hi": "नजवा (स्त्री नाम)", "ps": "نجوا (ښځينه نوم)", "ar": "نَجْوَى (اسْم عَلَم مُؤَنَّث)"},
    "nahad": {"en": "Nahad; a male given name", "ur": "نہاد (مردانہ نام)", "fa": "نهاد (نام مردانه)", "hi": "नहाद (पुरुष नाम)", "ps": "نهاد (نر نوم)", "ar": "نَهَاد (اسْم عَلَم مُذَكَّر)"},
    "nahal": {"en": "Nahal; a young plant, sapling", "ur": "نہال، پودا، ننھا درخت", "fa": "نهال، نهال", "hi": "निहाल, पौधा", "ps": "نهال، بوټی", "ar": "النَّهَال (الْغَرْس)"},
    "nahar": {"en": "Nahar; river, stream", "ur": "نہر، دریا، ندی", "fa": "نهر، رود", "hi": "नहर, नदी", "ps": "نهر، سیند", "ar": "النَّهْر، الْجَدْوَل"},
    "naheed": {"en": "Naheed; a female given name", "ur": "ناہید (زنانہ نام)", "fa": "ناهید (نام زنانه)", "hi": "नाहीद (स्त्री नाम)", "ps": "ناهید (ښځينه نوم)", "ar": "نَاهِيد (اسْم عَلَم مُؤَنَّث)"},
    "naheeda": {"en": "Naheeda; a female given name", "ur": "ناہیدہ (زنانہ نام)", "fa": "ناهیده (نام زنانه)", "hi": "नाहीदा (स्त्री नाम)", "ps": "ناهیده (ښځينه نوم)", "ar": "نَاهِيدَة (اسْم عَلَم مُؤَنَّث)"},
    "nahi": {"en": "Nahi; prohibition, forbidding", "ur": "نہی، ممانعت، روک", "fa": "نهی، بازداشتن", "hi": "नही, निषेध", "ps": "نهي، منع", "ar": "النَّهْي، الْمَنْع"},
    "nahid": {"en": "Nahid; a female given name", "ur": "ناہید (زنانہ نام)", "fa": "ناهید (نام زنانه)", "hi": "नाहिद (स्त्री नाम)", "ps": "ناهید (ښځينه نوم)", "ar": "نَاهِد (اسْم عَلَم مُؤَنَّث)"},
    "nahida": {"en": "Nahida; a female given name", "ur": "ناہیدہ (زنانہ نام)", "fa": "ناهیده (نام زنانه)", "hi": "नाहीदा (स्त्री नाम)", "ps": "ناهیده (ښځينه نوم)", "ar": "نَاهِيدَة (اسْم عَلَم مُؤَنَّث)"},
    "nahla": {"en": "Nahla; a drink of water, first draught", "ur": "نہلہ، پانی کا گھونٹ", "fa": "نهله، جرعه آب", "hi": "नहला, जल का घूँट", "ps": "نهله، د اوبو څښاک", "ar": "النَّهْلَة، الشَّرْبَة"},
    "nahyan": {"en": "Nahyan; a male given name", "ur": "نہیان (مردانہ نام)", "fa": "نهیان (نام مردانه)", "hi": "नहयान (पुरुष नाम)", "ps": "نهیان (نر نوم)", "ar": "نَهْيَان (اسْم عَلَم مُذَكَّر)"},
    "naib": {"en": "Naib; deputy, representative", "ur": "نائب، قائم مقام، نائب", "fa": "نایب، جانشین", "hi": "नायब, प्रतिनिधि", "ps": "نایب، مرستیال", "ar": "النَّائِب، الْوَكِيل"},
    "naida": {"en": "Naida; a female given name", "ur": "نایدہ (زنانہ نام)", "fa": "نایده (نام زنانه)", "hi": "नाइदा (स्त्री नाम)", "ps": "نایده (ښځينه نوم)", "ar": "نَايِدَة (اسْم عَلَم مُؤَنَّث)"},
    "naif": {"en": "Naif; high land, elevated", "ur": "نائف، بلند زمین", "fa": "نائف، بلندی", "hi": "नाइफ़, ऊँचाई", "ps": "نائف، لوړه ځمکه", "ar": "النَّائِف، الْمُرْتَفِع"},
    "naiim": {"en": "Naiim; blessing, comfort, bliss", "ur": "نعیم، نعمت، آرام", "fa": "نعیم، نعمت", "hi": "नईम, आशीर्वाद", "ps": "نعیم، نعمت", "ar": "النَّعِيم، النِّعْمَة"},
    "nail": {"en": "Nail; one who obtains, attainer", "ur": "نائل، حاصل کرنے والا", "fa": "نائل، دست‌یابنده", "hi": "नाइल, प्राप्त करने वाला", "ps": "نائل، ترلاسه کوونکی", "ar": "النَّائِل، الْحَاصِل"},
    "naila": {"en": "Naila; one who obtains, attainer (feminine)", "ur": "نائلہ، حاصل کرنے والی", "fa": "نائله، دست‌یابنده (مؤنث)", "hi": "नाइला, प्राप्त करने वाली", "ps": "نائله، ترلاسه کوونکې", "ar": "النَّائِلَة، الْحَاصِلَة"},
    "nailah": {"en": "Nailah; one who obtains, attainer (feminine)", "ur": "نائلہ، حاصل کرنے والی", "fa": "نائله، دست‌یابنده (مؤنث)", "hi": "नाइला, प्राप्त करने वाली", "ps": "نائله، ترلاسه کوونکې", "ar": "النَّائِلَة، الْحَاصِلَة"},
    "naim": {"en": "Naim; blessing, comfort, bliss", "ur": "نعیم، نعمت، آرام", "fa": "نعیم، نعمت", "hi": "नईम, आशीर्वाद", "ps": "نعیم، نعمت", "ar": "النَّعِيم، النِّعْمَة"},
    "naima": {"en": "Naima; soft, delicate, pleasant (feminine)", "ur": "نعیمہ، نرم، خوشگوار (مؤنث)", "fa": "نعیمه، نرم (مؤنث)", "hi": "नईमा, कोमल (स्त्री)", "ps": "نعیمه، نرمه", "ar": "النَّعِيمَة، اللَّيِّنَة"},
    "naimat": {"en": "Naimat; blessings, favours (plural)", "ur": "نعمات، نعمتیں", "fa": "نعمات، نعمت‌ها", "hi": "निमात, आशीर्वाद", "ps": "نعمات، نعمتونه", "ar": "النِّعْمَات، النِّعَم"},
    "nain": {"en": "Nain; the eye, a spring", "ur": "نین، آنکھ، چشمہ", "fa": "نین، چشمه", "hi": "नैन, आँख", "ps": "نین، سترګه", "ar": "النَّيْن (الْعَيْن)"},
    "naina": {"en": "Naina; the eyes (Hindi)", "ur": "نینا، آنکھیں", "fa": "نینا، چشمان", "hi": "नैना, आँखें", "ps": "نینا، سترګې", "ar": "نَيْنَا (الْعُيُون)"},
    "nair": {"en": "Nair; a Kerala surname and given name", "ur": "نائر (کیرالہ کا نام)", "fa": "نایر (نام کرالا)", "hi": "नायर (केरल नाम)", "ps": "نایر (د کیرالا نوم)", "ar": "نَايِر (اسْم عَلَم هِنْدِيّ)"},
    "najaah": {"en": "Najaah; success, deliverance", "ur": "نجاح، کامیابی، نجات", "fa": "نجاح، کامیابی", "hi": "नजाह, सफलता", "ps": "نجاح، بریا", "ar": "النَّجَاح، الْفَلَاح"},
    "najaf": {"en": "Najaf; a city in Iraq", "ur": "نجف، عراق کا شہر", "fa": "نجف، شهری در عراق", "hi": "नजफ़, इराक़ का शहर", "ps": "نجف، د عراق ښار", "ar": "النَّجَف، مَدِينَة فِي الْعِرَاق"},
    "najah": {"en": "Najah; success, deliverance", "ur": "نجاح، کامیابی، نجات", "fa": "نجاح، کامیابی", "hi": "नजाह, सफलता", "ps": "نجاح، بریا", "ar": "النَّجَاح، الْفَلَاح"},
    "najam": {"en": "Najam; star", "ur": "نجم، ستارہ", "fa": "نجم، ستاره", "hi": "नजम, तारा", "ps": "نجم، ستوری", "ar": "النَّجْم، الْكَوْكَب"},
    "najat": {"en": "Najat; salvation, deliverance, safety", "ur": "نجات، رہائی، سلامتی", "fa": "نجات، رهایی", "hi": "नजात, मुक्ति", "ps": "نجات، خلاصون", "ar": "النَّجَاة، الْخَلَاص"},
    "najd": {"en": "Najd; highland, plateau", "ur": "نجد، بلند زمین", "fa": "نجد، بلندی", "hi": "नज्द, ऊँचा मैदान", "ps": "نجد، لوړه ځمکه", "ar": "النَّجْد، الْمُرْتَفَع"},
    "najda": {"en": "Najda; help, succour", "ur": "نجدہ، مدد، امداد", "fa": "نجده، یاری", "hi": "नज्दा, सहायता", "ps": "نجده، مرسته", "ar": "النَّجْدَة، الْغَوْث"},
    "najdat": {"en": "Najdat; help, succour", "ur": "نجدات، مدد، امداد", "fa": "نجدات، یاری", "hi": "नज्दात, सहायता", "ps": "نجدات، مرسته", "ar": "النَّجْدَات، الْغَوْث"},
    "najdi": {"en": "Najdi; of the highland, highlander", "ur": "نجدی، نجد سے منسوب", "fa": "نجدی، منسوب به نجد", "hi": "नज्दी, नज्द से संबंधित", "ps": "نجدي، د نجد اړوند", "ar": "النَّجْدِي، مَنْسُوب إِلَى نَجْد"},
    "najee": {"en": "Najee; one who is saved, survivor", "ur": "ناجی، نجات پانے والا", "fa": "ناجی، رهاشده", "hi": "नाजी, बचने वाला", "ps": "ناجي، ژغورل شوی", "ar": "النَّاجِي، الْمُنْجَى"},
    "najeeb": {"en": "Najeeb; noble, distinguished", "ur": "نجیب، نجیب، شریف", "fa": "نجیب، نجیب", "hi": "नजीब, कुलीन", "ps": "نجیب، نومیالی", "ar": "النَّجِيب، الشَّرِيف"},
    "najeeba": {"en": "Najeeba; noble, distinguished (feminine)", "ur": "نجیبہ، نجیب (مؤنث)", "fa": "نجیبه، نجیب (مؤنث)", "hi": "नजीबा, कुलीन (स्त्री)", "ps": "نجیبه، نومیالې", "ar": "النَّجِيبَة، الشَّرِيفَة"},
    "najet": {"en": "Najet; salvation, deliverance", "ur": "نجات، رہائی", "fa": "نجات، رهایی", "hi": "नजात, मुक्ति", "ps": "نجات، خلاصون", "ar": "النَّجَاة، الْخَلَاص"},
    "naji": {"en": "Naji; one who is saved, survivor", "ur": "ناجی، نجات پانے والا", "fa": "ناجی، رهاشده", "hi": "नाजी, बचने वाला", "ps": "ناجي، ژغورل شوی", "ar": "النَّاجِي، الْمُنْجَى"},
    "najiah": {"en": "Najiah; one who is saved (feminine)", "ur": "ناجیہ، نجات پانے والی", "fa": "ناجیه، رهاشده (مؤنث)", "hi": "नाजिया, बचने वाली", "ps": "ناجیه، ژغورل شوې", "ar": "النَّاجِيَة، الْمُنْجَاة"},
    "najib": {"en": "Najib; noble, distinguished", "ur": "نجیب، نجیب، شریف", "fa": "نجیب، نجیب", "hi": "नजीब, कुलीन", "ps": "نجیب، نومیالی", "ar": "النَّجِيب، الشَّرِيف"},
    "najiba": {"en": "Najiba; noble, distinguished (feminine)", "ur": "نجیبہ، نجیب (مؤنث)", "fa": "نجیبه، نجیب (مؤنث)", "hi": "नजीबा, कुलीन (स्त्री)", "ps": "نجیبه، نومیالې", "ar": "النَّجِيبَة، الشَّرِيفَة"},
    "najid": {"en": "Najid; a male given name", "ur": "نجید (مردانہ نام)", "fa": "نجید (نام مردانه)", "hi": "नजीद (पुरुष नाम)", "ps": "نجید (نر نوم)", "ar": "نَجِيد (اسْم عَلَم مُذَكَّر)"},
})

CUR = {
 "nada": ("نَدَى", "ندی", "ندى", "नदा", "ندی", "nada", "Arabic", "Female",
          "Arabic root ن د و (n-d-w); نَدَى (Nadā)", False, "high",
          "Nada is Arabic نَدَى (Nadā) 'dew, generosity', from the root ن د و (n-d-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "nadaa": ("نِدَاء", "نداء", "نداء", "निदा", "نداء", "nadaa", "Arabic", "Female",
           "Arabic root ن د و (n-d-w); نِدَاء (Nidāʾ)", False, "high",
           "Nadaa is Arabic نِدَاء (Nidāʾ) 'call, summons, announcement', from the root ن د و (n-d-w). The source gloss 'Awakening, call, summons' is partly consistent."),
 "nadeem": ("نَدِيم", "ندیم", "ندیم", "नदीम", "ندیم", "nadeem", "Arabic", "Male",
            "Arabic root ن د م (n-d-m); نَدِيم (Nadīm)", False, "high",
            "Nadeem is Arabic نَدِيم (Nadīm) 'companion, close friend', from the root ن د م (n-d-m). The source gloss 'Bringer of peace' is unsupported and has been replaced with the lexical sense. Same name as nadim."),
 "nadeen": ("نَادِين", "نادین", "نادین", "नादीन", "نادین", "nadyne", "Arabic", "Female",
            "Arabic نَادِين (Nādīn), a spelling of نَادِيَة (Nādiya)", False, "medium",
            "Nadeen is a spelling of Arabic نَادِيَة (Nādiya) 'tender, delicate'. CRITICAL SOURCE ERROR: the source gave 'N/A' instead of a script form. The source gloss 'Gentle, soft' is broadly consistent. The identification is recorded at medium confidence. Same name as nadia."),
 "nadeer": ("نَدِير", "ندیر", "ندیر", "नदीर", "ندیر", "nadeer", "Arabic", "Male",
            "Arabic root ن د ر (n-d-r); نَدِير (Nadīr)", False, "high",
            "Nadeer is Arabic نَدِير (Nadīr) 'rare, uncommon', from the root ن د ر (n-d-r). CRITICAL SOURCE ERROR: the source gave 'نadir' (Latin characters mixed into the Arabic field); the correct form is نَدِير. The source gloss 'guide, light' is unsupported and has been replaced with the lexical sense. Same name as nadir."),
 "nadeera": ("نَدِيرَة", "ندیرہ", "ندیره", "नदीरा", "ندیره", "nadeera", "Arabic", "Female",
             "Arabic root ن د ر (n-d-r); نَدِيرَة (Nadīra)", False, "high",
             "Nadeera is Arabic نَدِيرَة (Nadīra) 'rare, precious' (feminine), from the root ن د ر (n-d-r). The source gloss 'A helper, support, or solace' is unsupported and has been replaced with the lexical sense. Same name as nadira."),
 "nader": ("نَادِر", "نادر", "نادر", "नादिर", "نادر", "nader", "Arabic", "Male",
           "Arabic root ن د ر (n-d-r); نَادِر (Nādir)", False, "high",
           "Nader is Arabic نَادِر (Nādir) 'rare, precious', from the root ن د ر (n-d-r). The source gloss 'Gift, Present' is unsupported and has been replaced with the lexical sense. Same name as nadir."),
 "nadheem": ("نَدِيم", "ندیم", "ندیم", "नदीम", "ندیم", "nadeem", "Arabic", "Male",
             "Arabic root ن د م (n-d-m); نَدِيم (Nadīm)", False, "high",
             "Nadheem is a spelling variant of Arabic نَدِيم (Nadīm) 'companion, close friend', from the root ن د م (n-d-m). CRITICAL SOURCE ERROR: the source gave نظيم (a different form); the correct form is نَدِيم. The source gloss 'Radiant, glowing' is unsupported and has been replaced with the lexical sense. Same name as nadeem."),
 "nadheer": ("نَذِير", "نذیر", "نذیر", "नज़ीर", "نذیر", "nadheer", "Arabic", "Male",
             "Arabic root ن ذ ر (n-dh-r); نَذِير (Nadhīr)", False, "high",
             "Nadheer is Arabic نَذِير (Nadhīr) 'warner, one who warns', from the root ن ذ ر (n-dh-r). The source gloss 'Observer, Watcher' is unsupported and has been replaced with the lexical sense. Same name as nadhir."),
 "nadhir": ("نَذِير", "نذیر", "نذیر", "नज़ीर", "نذیر", "nadhir", "Arabic", "Male",
            "Arabic root ن ذ ر (n-dh-r); نَذِير (Nadhīr)", False, "high",
            "Nadhir is Arabic نَذِير (Nadhīr) 'warner, one who warns', from the root ن ذ ر (n-dh-r). The source gloss 'Warner' is consistent. Same name as nadheer."),
 "nadhira": ("نَذِيرَة", "نذیرہ", "نذیره", "नज़ीरा", "نذیره", "nadhira", "Arabic", "Female",
             "Arabic root ن ذ ر (n-dh-r); نَذِيرَة (Nadhīra)", False, "high",
             "Nadhira is Arabic نَذِيرَة (Nadhīra) 'warner' (feminine), from the root ن ذ ر (n-dh-r). The source gloss 'Intense longing, desire' is unsupported and has been replaced with the lexical sense."),
 "nadhirah": ("نَذِيرَة", "نذیرہ", "نذیره", "नज़ीरा", "نذیره", "nadhira", "Arabic", "Female",
              "Arabic root ن ذ ر (n-dh-r); نَذِيرَة (Nadhīra)", False, "high",
              "Nadhirah is Arabic نَذِيرَة (Nadhīra) 'warner' (feminine), from the root ن ذ ر (n-dh-r). CRITICAL SOURCE ERROR: the source gave نادرة (a different form); the correct form is نَذِيرَة. The source gloss 'One who gives warning' is consistent. Same name as nadhira."),
 "nadhrah": ("نَضْرَة", "نضرہ", "نضره", "नज़रा", "نضره", "nadhrah", "Arabic", "Female",
             "Arabic root ن ض ر (n-ḍ-r); نَضْرَة (Naḍra)", False, "high",
             "Nadhrah is Arabic نَضْرَة (Naḍra) 'radiance, brightness', from the root ن ض ر (n-ḍ-r). The source gloss 'A source of light' is broadly consistent."),
 "nadi": ("نَدِي", "ندی", "ندی", "नदी", "ندی", "nadi", "Hindi", "Male",
          "Hindi नदी (nadī) 'river'", False, "high",
          "Nadi is Hindi नदी (nadī) 'river', also used in Urdu. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nadi' instead of a script form and labelled the origin Arabic; the word is Hindi/Urdu. The source gloss 'Friend' is unsupported and has been replaced with the lexical sense."),
 "nadia": ("نَادِيَة", "نادیہ", "نادیه", "नादिया", "نادیه", "nadia", "Arabic", "Female",
           "Arabic root ن د و (n-d-w); نَادِيَة (Nādiya)", False, "high",
           "Nadia is Arabic نَادِيَة (Nādiya) 'tender, delicate', from the root ن د و (n-d-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "nadiaa": ("نَدِيَّة", "ندیه", "ندیه", "नादिया", "ندیه", "nadiaa", "Arabic", "Female",
            "Arabic root ن د و (n-d-w); نَدِيَّة (Nadiyya)", False, "high",
            "Nadiaa is Arabic نَدِيَّة (Nadiyya) 'tender, delicate' (feminine), from the root ن د و (n-d-w). CRITICAL SOURCE ERROR: the source gave ندیه (a non-standard form); the correct form is نَدِيَّة. The source gloss 'Intense, Radiant' is unsupported and has been replaced with the lexical sense. Same name as nadia."),
 "nadiah": ("نَدِيَّة", "ندیه", "ندیه", "नादिया", "ندیه", "nadiaa", "Arabic", "Female",
            "Arabic root ن د و (n-d-w); نَدِيَّة (Nadiyya)", False, "high",
            "Nadiah is Arabic نَدِيَّة (Nadiyya) 'tender, delicate' (feminine), from the root ن د و (n-d-w). The source gloss 'Tender, delicate, gentle' is consistent. Same name as nadia."),
 "nadil": ("نَدِل", "ندل", "ندل", "नदिल", "ندل", "nadil", "Arabic", "Male",
           "Arabic نَدِل (Nadil)", False, "medium",
           "Nadil is recorded as Arabic نَدِل (Nadil), a male given name. The source gloss 'Gift, bounty' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nadim": ("نَدِيم", "ندیم", "ندیم", "नदीम", "ندیم", "nadeem", "Arabic", "Male",
           "Arabic root ن د م (n-d-m); نَدِيم (Nadīm)", False, "high",
           "Nadim is Arabic نَدِيم (Nadīm) 'companion, close friend', from the root ن د م (n-d-m). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nadeem."),
 "nadima": ("نَدِيمَة", "ندیمہ", "ندیمه", "नदीमा", "ندیمه", "nadima", "Arabic", "Female",
            "Arabic root ن د م (n-d-m); نَدِيمَة (Nadīma)", False, "high",
            "Nadima is Arabic نَدِيمَة (Nadīma) 'companion, close friend' (feminine), from the root ن د م (n-d-m). The source gloss 'Delight, Pleasure' is unsupported and has been replaced with the lexical sense."),
 "nadir": ("نَادِر", "نادر", "نادر", "नादिर", "نادر", "nadir", "Arabic", "Male",
           "Arabic root ن د ر (n-d-r); نَادِر (Nādir)", False, "high",
           "Nadir is Arabic نَادِر (Nādir) 'rare, precious', from the root ن د ر (n-d-r). The source gloss 'Rare, precious' is consistent. Same name as nader."),
 "nadira": ("نَادِرَة", "نادرہ", "نادره", "नादिरा", "نادره", "nadira", "Arabic", "Female",
            "Arabic root ن د ر (n-d-r); نَادِرَة (Nādira)", False, "high",
            "Nadira is Arabic نَادِرَة (Nādira) 'rare, precious' (feminine), from the root ن د ر (n-d-r). CRITICAL SOURCE ERROR: the source gave ناضرة (a different form); the correct form is نَادِرَة. The source gloss 'Rarity, Rare One' is broadly consistent. Same name as nadeera."),
 "nadirah": ("نَدِيرَة", "ندیرہ", "ندیره", "नदीरा", "ندیره", "nadeera", "Arabic", "Female",
             "Arabic root ن د ر (n-d-r); نَدِيرَة (Nadīra)", False, "high",
             "Nadirah is Arabic نَدِيرَة (Nadīra) 'rare, precious' (feminine), from the root ن د ر (n-d-r). The source gloss 'Rare, precious' is consistent. Same name as nadira."),
 "nadjib": ("نَجِيب", "نجیب", "نجیب", "नजीब", "نجیب", "nadjib", "Arabic", "Male",
            "Arabic root ن ج ب (n-j-b); نَجِيب (Najīb)", False, "high",
            "Nadjib is a spelling variant of Arabic نَجِيب (Najīb) 'noble, distinguished', from the root ن ج ب (n-j-b). The source gloss 'Gift, reward, honor' is unsupported and has been replaced with the lexical sense. Same name as najib."),
 "nadjiba": ("نَجِيبَة", "نجیبہ", "نجیبه", "नजीबा", "نجیبه", "nadjiba", "Arabic", "Female",
             "Arabic root ن ج ب (n-j-b); نَجِيبَة (Najība)", False, "high",
             "Nadjiba is a spelling variant of Arabic نَجِيبَة (Najība) 'noble, distinguished' (feminine), from the root ن ج ب (n-j-b). The source gloss 'Supporting' is unsupported and has been replaced with the lexical sense. Same name as najiba."),
 "nadr": ("نَضْر", "نضر", "نضر", "नदर", "نضر", "nadr", "Arabic", "Male",
          "Arabic نَضْر (Naḍr)", False, "medium",
          "Nadr is recorded as Arabic نَضْر (Naḍr), a male given name. CRITICAL SOURCE ERROR: the source gave نضر (a non-standard form) and glossed the name 'Sweat'; the source gloss is unsupported. The identification is recorded at medium confidence."),
 "nadra": ("نَضْرَة", "نضرہ", "نضره", "नदरा", "نضره", "nadhrah", "Arabic", "Female",
           "Arabic root ن ض ر (n-ḍ-r); نَضْرَة (Naḍra)", False, "high",
           "Nadra is Arabic نَضْرَة (Naḍra) 'radiance, brightness', from the root ن ض ر (n-ḍ-r). The source gloss 'Gratefulness, contentment' is unsupported and has been replaced with the lexical sense. Same name as nadhrah."),
 "nadrah": ("نَضْرَة", "نضرہ", "نضره", "नदरा", "نضره", "nadhrah", "Arabic", "Female",
            "Arabic root ن ض ر (n-ḍ-r); نَضْرَة (Naḍra)", False, "high",
            "Nadrah is Arabic نَضْرَة (Naḍra) 'radiance, brightness', from the root ن ض ر (n-ḍ-r). CRITICAL SOURCE ERROR: the source gave ندرة (a different form); the correct form is نَضْرَة. The source gloss 'Call to prayer, invocation' is unsupported and has been replaced with the lexical sense. Same name as nadhrah."),
 "nadwa": ("نَدْوَة", "ندوہ", "ندوه", "नदवा", "ندوه", "nadwa", "Arabic", "Female",
           "Arabic root ن د و (n-d-w); نَدْوَة (Nadwa)", False, "high",
           "Nadwa is Arabic نَدْوَة (Nadwa) 'council, assembly, club', from the root ن د و (n-d-w). The source gloss 'Discussion, Council, Debate' is consistent."),
 "nadyne": ("نَادِين", "نادین", "نادین", "नादीन", "نادین", "nadyne", "Arabic", "Female",
            "Arabic نَادِين (Nādīn), a spelling of نَادِيَة (Nādiya)", False, "medium",
            "Nadyne is a spelling of Arabic نَادِيَة (Nādiya) 'tender, delicate'. CRITICAL SOURCE ERROR: the source gave the Latin string 'Nadyne' instead of a script form. The source gloss 'Mystery, Divine Secret' is unsupported and has been replaced with the lexical sense. The identification is recorded at medium confidence. Same name as nadia."),
 "naeem": ("نَعِيم", "نعیم", "نعیم", "नईम", "نعیم", "naeem", "Arabic", "Male",
           "Arabic root ن ع م (n-ʿ-m); نَعِيم (Naʿīm)", False, "high",
           "Naeem is Arabic نَعِيم (Naʿīm) 'blessing, comfort, bliss', from the root ن ع م (n-ʿ-m). The source gloss 'Blessing or Comfort' is consistent. Same name as naim."),
 "naeema": ("نَعِيمَة", "نعیمہ", "نعیمه", "नईमा", "نعیمه", "naeema", "Arabic", "Female",
            "Arabic root ن ع م (n-ʿ-m); نَعِيمَة (Naʿīma)", False, "high",
            "Naeema is Arabic نَعِيمَة (Naʿīma) 'blessing, comfort' (feminine), from the root ن ع م (n-ʿ-m). CRITICAL SOURCE ERROR: the source gave ناعمة (a different form); the correct form is نَعِيمَة. The source gloss 'Tranquil, Soft, Comforting' is broadly consistent. Same name as naima."),
 "naeemah": ("نَعِيمَة", "نعیمہ", "نعیمه", "नईमा", "نعیمه", "naeema", "Arabic", "Female",
             "Arabic root ن ع م (n-ʿ-m); نَعِيمَة (Naʿīma)", False, "high",
             "Naeemah is Arabic نَعِيمَة (Naʿīma) 'blessing, comfort' (feminine), from the root ن ع م (n-ʿ-m). The source gloss 'Gentle, Kind, Generous' is unsupported and has been replaced with the lexical sense. Same name as naima."),
 "naef": ("نَائِف", "نائف", "نائف", "नाइफ़", "نائف", "naef", "Arabic", "Male",
          "Arabic نَائِف (Nāʾif)", False, "medium",
          "Naef is recorded as Arabic نَائِف (Nāʾif), a male given name. CRITICAL SOURCE ERROR: the source gave the Latin string 'Naef' instead of a script form. The source gloss 'Gentle, soft' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nael": ("نَائِل", "نائل", "نائل", "नाइल", "نائل", "nael", "Arabic", "Male",
          "Arabic root ن ي ل (n-y-l); نَائِل (Nāʾil)", False, "high",
          "Nael is Arabic نَائِل (Nāʾil) 'one who obtains, attainer', from the root ن ي ل (n-y-l). The source gloss 'Night' is unsupported and has been replaced with the lexical sense. Same name as nail."),
 "naela": ("نَائِلَة", "نائلہ", "نائله", "नाइला", "نائله", "naela", "Arabic", "Female",
           "Arabic root ن ي ل (n-y-l); نَائِلَة (Nāʾila)", False, "high",
           "Naela is Arabic نَائِلَة (Nāʾila) 'one who obtains' (feminine), from the root ن ي ل (n-y-l). CRITICAL SOURCE ERROR: the source gave نعيلة (a different form); the correct form is نَائِلَة. The source gloss 'Night' is unsupported and has been replaced with the lexical sense. Same name as naila."),
 "nafas": ("نَفَس", "نفس", "نفس", "नफ़स", "نفس", "nafas", "Arabic", "Male",
           "Arabic root ن ف س (n-f-s); نَفَس (Nafas)", False, "high",
           "Nafas is Arabic نَفَس (Nafas) 'breath, soul, self', from the root ن ف س (n-f-s). The source gloss 'Breath of life' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "nafees": ("نَفِيس", "نفیس", "نفیس", "नफ़ीस", "نفیس", "nafees", "Arabic", "Male",
            "Arabic root ن ف س (n-f-s); نَفِيس (Nafīs)", False, "high",
            "Nafees is Arabic نَفِيس (Nafīs) 'precious, rare, valuable', from the root ن ف س (n-f-s). The source gloss 'Precious, Rare, Valuable' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as nafis."),
 "nafeesa": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीसा", "نفیسه", "nafeesa", "Arabic", "Female",
             "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
             "Nafeesa is Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). CRITICAL SOURCE ERROR: the source gave نافيسہ (a non-standard form); the correct form is نَفِيسَة. The source gloss 'Pure, Virtuous' is unsupported and has been replaced with the lexical sense. Same name as nafisa."),
 "nafeesah": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीसा", "نفیسه", "nafeesa", "Arabic", "Female",
              "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
              "Nafeesah is Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). The source gloss 'Precious thing' is broadly consistent. Same name as nafisa."),
 "nafeezah": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीज़ा", "نفیسه", "nafeesa", "Arabic", "Female",
              "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
              "Nafeezah is a spelling variant of Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). The source gloss 'Melting, Soft, Tender' is unsupported and has been replaced with the lexical sense. Same name as nafisa."),
 "nafesa": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीसा", "نفیسه", "nafeesa", "Arabic", "Female",
            "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
            "Nafesa is a spelling variant of Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). The source gloss 'Delicacy, sweetness, softness' is unsupported and has been replaced with the lexical sense. Same name as nafisa."),
 "nafi": ("نَافِع", "نافع", "نافع", "नाफ़ि", "نافع", "nafi", "Arabic", "Male",
          "Arabic root ن ف ع (n-f-ʿ); نَافِع (Nāfiʿ)", False, "high",
          "Nafi is Arabic نَافِع (Nāfiʿ) 'beneficial, useful', from the root ن ف ع (n-f-ʿ). The source gloss 'Pure, Clean' is unsupported and has been replaced with the lexical sense."),
 "nafia": ("نَافِعَة", "نافعہ", "نافعه", "नाफ़िया", "نافعه", "nafia", "Arabic", "Female",
           "Arabic root ن ف ع (n-f-ʿ); نَافِعَة (Nāfiʿa)", False, "high",
           "Nafia is Arabic نَافِعَة (Nāfiʿa) 'beneficial, useful' (feminine), from the root ن ف ع (n-f-ʿ). The source gloss 'Delight, pleasure' is unsupported and has been replaced with the lexical sense."),
 "nafis": ("نَفِيس", "نفیس", "نفیس", "नफ़ीस", "نفیس", "nafis", "Arabic", "Male",
           "Arabic root ن ف س (n-f-s); نَفِيس (Nafīs)", False, "high",
           "Nafis is Arabic نَفِيس (Nafīs) 'precious, valuable', from the root ن ف س (n-f-s). The source gloss 'Precious, Valuable' is consistent. Same name as nafees."),
 "nafisa": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीसा", "نفیسه", "nafeesa", "Arabic", "Female",
            "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
            "Nafisa is Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root. Same name as nafeesa."),
 "nafisah": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीसा", "نفیسه", "nafeesa", "Arabic", "Female",
             "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
             "Nafisah is Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). The source gloss 'Precious, valuable' is consistent. Same name as nafisa."),
 "nafissa": ("نَفِيسَة", "نفیسہ", "نفیسه", "नफ़ीसा", "نفیسه", "nafeesa", "Arabic", "Female",
             "Arabic root ن ف س (n-f-s); نَفِيسَة (Nafīsa)", False, "high",
             "Nafissa is a spelling variant of Arabic نَفِيسَة (Nafīsa) 'precious, valuable' (feminine), from the root ن ف س (n-f-s). The source gloss 'Delightful, sweet, fragrant' is unsupported and has been replaced with the lexical sense. Same name as nafisa."),
 "nafiz": ("نَافِذ", "نافذ", "نافذ", "नाफ़िज़", "نافذ", "nafiz", "Arabic", "Male",
           "Arabic root ن ف ذ (n-f-dh); نَافِذ (Nāfidh)", False, "high",
           "Nafiz is Arabic نَافِذ (Nāfidh) 'effective, penetrating, one who carries out', from the root ن ف ذ (n-f-dh). CRITICAL SOURCE ERROR: the source gave نفض (a different form); the correct form is نَافِذ. The source gloss 'Giver, Donor' is unsupported and has been replaced with the lexical sense."),
 "nafizah": ("نَافِذَة", "نافذہ", "نافذه", "नाफ़िज़ा", "نافذه", "nafizah", "Arabic", "Female",
             "Arabic root ن ف ذ (n-f-dh); نَافِذَة (Nāfidha)", False, "high",
             "Nafizah is Arabic نَافِذَة (Nāfidha) 'effective, penetrating' (feminine), from the root ن ف ذ (n-f-dh). The source gloss 'Gift from Allah' is unsupported and has been replaced with the lexical sense."),
 "naghma": ("نَغْمَة", "نغمہ", "نغمه", "नग़मा", "نغمه", "naghma", "Arabic", "Female",
            "Arabic root ن غ م (n-gh-m); نَغْمَة (Naghma)", False, "high",
            "Naghma is Arabic نَغْمَة (Naghma) 'melody, tune', from the root ن غ م (n-gh-m). The source gloss 'Melody, Tune' is consistent."),
 "nagi": ("نَاجِي", "ناجی", "ناجی", "नाजी", "ناجي", "nagi", "Arabic", "Male",
          "Arabic root ن ج و (n-j-w); نَاجِي (Nājī)", False, "high",
          "Nagi is Arabic نَاجِي (Nājī) 'one who is saved, survivor', from the root ن ج و (n-j-w). The source gloss 'Restorer, Bright, Radiant' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as naji."),
 "nagib": ("نَجِيب", "نجیب", "نجیب", "नजीब", "نجیب", "najib", "Arabic", "Male",
           "Arabic root ن ج ب (n-j-b); نَجِيب (Najīb)", False, "high",
           "Nagib is a spelling variant of Arabic نَجِيب (Najīb) 'noble, distinguished', from the root ن ج ب (n-j-b). CRITICAL SOURCE ERROR: the source gave ناجب (a different form); the correct form is نَجِيب. The source gloss 'Given, Generous' is unsupported and has been replaced with the lexical sense. Same name as najib."),
 "nagina": ("نگینہ", "نگینہ", "نگینه", "नगीना", "نگینه", "nagina", "Urdu", "Female",
            "Urdu نگینہ (nagīna) 'a gem, jewel'", False, "high",
            "Nagina is Urdu نگینہ (nagīna) 'a gem, jewel', from Persian نگین (negīn). CRITICAL SOURCE ERROR: the source gave ناجنة (a different form) and labelled the origin Arabic; the word is Urdu/Persian. The source gloss 'Jewel, Precious One' is consistent."),
 "nagla": ("نَجْلَة", "نجلہ", "نجله", "नजला", "نجله", "nagla", "Arabic", "Female",
           "Arabic نَجْلَة (Najla)", False, "medium",
           "Nagla is recorded as Arabic نَجْلَة (Najla), a female given name. CRITICAL SOURCE ERROR: the source gave نغلة (a non-standard form) and glossed the name 'Radiant, Brilliant'; the source gloss is unsupported. The identification is recorded at medium confidence."),
 "naguib": ("نَجِيب", "نجیب", "نجیب", "नगीब", "نجیب", "najib", "Arabic", "Male",
            "Arabic root ن ج ب (n-j-b); نَجِيب (Najīb)", False, "high",
            "Naguib is a Latin-alphabet spelling of Arabic نَجِيب (Najīb) 'noble, distinguished', from the root ن ج ب (n-j-b). CRITICAL SOURCE ERROR: the source gave 'نaguib' (Latin characters mixed into the Arabic field). The source gloss 'Giver, Generous, Noble' is partly consistent. Same name as najib."),
 "nagwa": ("نَجْوَى", "نجویٰ", "نجوا", "नजवा", "نجوا", "nagwa", "Arabic", "Female",
           "Arabic root ن ج و (n-j-w); نَجْوَى (Najwā)", False, "high",
           "Nagwa is Arabic نَجْوَى (Najwā) 'secret conversation, whispering', from the root ن ج و (n-j-w). The source gloss 'Graceful' is unsupported and has been replaced with the lexical sense."),
 "nahad": ("نَهَاد", "نہاد", "نهاد", "नहाद", "نهاد", "nahad", "Arabic", "Male",
           "Arabic نَهَاد (Nahād)", False, "medium",
           "Nahad is recorded as Arabic نَهَاد (Nahād), a male given name. The source gloss 'Rest' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nahal": ("نَهَال", "نہال", "نهال", "निहाल", "نهال", "nahal", "Arabic", "Male",
           "Arabic نَهَال (Nahāl) 'a young plant'", False, "high",
           "Nahal is Arabic نَهَال (Nahāl) 'a young plant, sapling'. The source gloss 'Acquirer of good' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "nahar": ("نَهْر", "نہر", "نهر", "नहर", "نهر", "nahar", "Arabic", "Male",
           "Arabic root ن ه ر (n-h-r); نَهْر (Nahr)", False, "high",
           "Nahar is Arabic نَهْر (Nahr) 'river, stream', from the root ن ه ر (n-h-r). The source gloss 'River' is consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "naheed": ("نَاهِيد", "ناہید", "ناهید", "नाहीद", "ناهید", "naheed", "Persian", "Female",
            "Persian ناهید (nāhīd)", False, "high",
            "Naheed is Persian ناهید (nāhīd), a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic and the gender unisex; the name is Persian and documented usage is female. The source gloss 'Delicate, refined, and noble' is unsupported; no confident lexical sense is asserted."),
 "naheeda": ("نَاهِيدَة", "ناہیدہ", "ناهیده", "नाहीदा", "ناهیده", "naheeda", "Persian", "Female",
             "Persian ناهید (nāhīd) + Arabic feminine ending", False, "medium",
             "Naheeda is a feminine form of Persian ناهید (nāhīd), a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic. The source gloss 'Guide, Leader' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "nahi": ("نَهْي", "نہی", "نهی", "नही", "نهي", "nahi", "Arabic", "Female",
          "Arabic root ن ه ي (n-h-y); نَهْي (Nahy)", False, "high",
          "Nahi is Arabic نَهْي (Nahy) 'prohibition, forbidding', from the root ن ه ي (n-h-y). CRITICAL SOURCE ERROR: the source gave نحي (a non-standard form); the correct form is نَهْي. The source gloss 'Refusal, Disapproval' is broadly consistent. Recorded as a common noun also used as a given name."),
 "nahid": ("نَاهِد", "ناہد", "ناهد", "नाहिद", "ناهد", "nahid", "Persian", "Female",
           "Persian ناهید (nāhīd)", False, "high",
           "Nahid is Persian ناهید (nāhīd), a female given name. CRITICAL SOURCE ERROR: the source labelled the origin Arabic. The source gloss 'Venus, planet' is a documented association of the Persian name. Same name as naheed."),
 "nahida": ("نَاهِيدَة", "ناہیدہ", "ناهیده", "नाहीदा", "ناهیده", "naheeda", "Persian", "Female",
            "Persian ناهید (nāhīd) + Arabic feminine ending", False, "medium",
            "Nahida is a feminine form of Persian ناهید (nāhīd), a female given name. CRITICAL SOURCE ERROR: the source gave نهيدة (a non-standard form) and labelled the origin Arabic. The source gloss 'First to bloom, First to rise, Morning' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence. Same name as naheeda."),
 "nahla": ("نَهْلَة", "نہلہ", "نهله", "नहला", "نهله", "nahla", "Arabic", "Female",
           "Arabic root ن ه ل (n-h-l); نَهْلَة (Nahla)", False, "high",
           "Nahla is Arabic نَهْلَة (Nahla) 'a drink of water, first draught', from the root ن ه ل (n-h-l). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "nahyan": ("نَهْيَان", "نہیان", "نهیان", "नहयान", "نهیان", "nahyan", "Arabic", "Male",
            "Arabic نَهْيَان (Nahyān)", False, "medium",
            "Nahyan is recorded as Arabic نَهْيَان (Nahyān), a male given name. CRITICAL SOURCE ERROR: the source gave نَهْيَانْ (a non-standard form). The source gloss 'Elevated, Exalted' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "naib": ("نَائِب", "نائب", "نائب", "नायब", "نائب", "naib", "Arabic", "Male",
          "Arabic root ن و ب (n-w-b); نَائِب (Nāʾib)", False, "high",
          "Naib is Arabic نَائِب (Nāʾib) 'deputy, representative', from the root ن و ب (n-w-b). CRITICAL SOURCE ERROR: the source gave 'Nabi' (a different word); the correct form is نَائِب. The source gloss 'Deputy, Helper, Assistant' is partly consistent."),
 "naida": ("نَايِدَة", "نایدہ", "نایده", "नाइदा", "نایده", "naida", "Arabic", "Female",
           "Arabic نَايِدَة (Nāyida)", False, "medium",
           "Naida is recorded as Arabic نَايِدَة (Nāyida), a female given name. The source gloss 'Helper, Supporter' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "naif": ("نَائِف", "نائف", "نائف", "नाइफ़", "نائف", "naif", "Arabic", "Male",
          "Arabic root ن ي ف (n-y-f); نَائِف (Nāʾif)", False, "high",
          "Naif is Arabic نَائِف (Nāʾif) 'high land, elevated', from the root ن ي ف (n-y-f). The source gloss 'Clear, Straightforward, Honest' is unsupported and has been replaced with the lexical sense. Same name as naef."),
 "naiim": ("نَعِيم", "نعیم", "نعیم", "नईम", "نعیم", "naeem", "Arabic", "Male",
           "Arabic root ن ع م (n-ʿ-m); نَعِيم (Naʿīm)", False, "high",
           "Naiim is a spelling variant of Arabic نَعِيم (Naʿīm) 'blessing, comfort, bliss', from the root ن ع م (n-ʿ-m). The source gloss 'Given as a gift' is unsupported and has been replaced with the lexical sense. Same name as naeem."),
 "nail": ("نَائِل", "نائل", "نائل", "नाइल", "نائل", "nail", "Arabic", "Male",
          "Arabic root ن ي ل (n-y-l); نَائِل (Nāʾil)", False, "high",
          "Nail is Arabic نَائِل (Nāʾil) 'one who obtains, attainer', from the root ن ي ل (n-y-l). CRITICAL SOURCE ERROR: the source gave the Latin string 'Nail' instead of a script form. The source gloss 'Little nail' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male. Same name as nael."),
 "naila": ("نَائِلَة", "نائلہ", "نائله", "नाइला", "نائله", "naila", "Arabic", "Female",
           "Arabic root ن ي ل (n-y-l); نَائِلَة (Nāʾila)", False, "high",
           "Naila is Arabic نَائِلَة (Nāʾila) 'one who obtains' (feminine), from the root ن ي ل (n-y-l). The source gloss 'Grace, beauty, gentle' is unsupported and has been replaced with the lexical sense. Same name as naela."),
 "nailah": ("نَائِلَة", "نائلہ", "نائله", "नाइला", "نائله", "naila", "Arabic", "Female",
            "Arabic root ن ي ل (n-y-l); نَائِلَة (Nāʾila)", False, "high",
            "Nailah is Arabic نَائِلَة (Nāʾila) 'one who obtains' (feminine), from the root ن ي ل (n-y-l). CRITICAL SOURCE ERROR: the source gave نعله (a different form); the correct form is نَائِلَة. The source gloss 'Gentle Wave' is unsupported and has been replaced with the lexical sense. Same name as naila."),
 "naim": ("نَعِيم", "نعیم", "نعیم", "नईम", "نعیم", "naeem", "Arabic", "Male",
          "Arabic root ن ع م (n-ʿ-m); نَعِيم (Naʿīm)", False, "high",
          "Naim is Arabic نَعِيم (Naʿīm) 'blessing, comfort, bliss', from the root ن ع م (n-ʿ-m). The source gloss 'Noble, Gracious' is unsupported and has been replaced with the lexical sense. Same name as naeem."),
 "naima": ("نَعِيمَة", "نعیمہ", "نعیمه", "नईमा", "نعیمه", "naeema", "Arabic", "Female",
           "Arabic root ن ع م (n-ʿ-m); نَعِيمَة (Naʿīma)", False, "high",
           "Naima is Arabic نَعِيمَة (Naʿīma) 'blessing, comfort' (feminine), from the root ن ع م (n-ʿ-m). CRITICAL SOURCE ERROR: the source gave نائمة (a different form); the correct form is نَعِيمَة. The source gloss 'Comfort, peace, serenity' is broadly consistent. Same name as naeema."),
 "naimah": ("نَعِيمَة", "نعیمہ", "نعیمه", "नईमा", "نعیمه", "naeema", "Arabic", "Female",
            "Arabic root ن ع م (n-ʿ-m); نَعِيمَة (Naʿīma)", False, "high",
            "Naimah is Arabic نَعِيمَة (Naʿīma) 'blessing, comfort' (feminine), from the root ن ع م (n-ʿ-m). CRITICAL SOURCE ERROR: the source gave نائمة (a different form); the correct form is نَعِيمَة. The source gloss 'Graceful' is unsupported and has been replaced with the lexical sense. Same name as naeema."),
 "naimat": ("نِعْمَات", "نعمات", "نعمات", "निमात", "نعمات", "naimat", "Arabic", "Female",
            "Arabic root ن ع م (n-ʿ-m); نِعْمَات (Niʿmāt)", False, "high",
            "Naimat is Arabic نِعْمَات (Niʿmāt) 'blessings, favours', the plural of نِعْمَة (niʿma), from the root ن ع م (n-ʿ-m). The source gloss 'Nur or Light' is unsupported and has been replaced with the lexical sense."),
 "nain": ("نَيْن", "نین", "نین", "नैन", "نین", "nain", "Hindi", "Male",
          "Hindi नैन (nain) 'eye'", False, "high",
          "Nain is Hindi नैन (nain) 'eye', also used in Urdu. CRITICAL SOURCE ERROR: the source gave نَيْن (a non-standard form) and labelled the origin Arabic; the word is Hindi/Urdu. The source gloss 'Luminary, Light-giver' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "naina": ("नैना", "نینا", "نینا", "नैना", "نینا", "naina", "Hindi", "Female",
           "Hindi नैना (nainā) 'the eyes'", False, "high",
           "Naina is Hindi नैना (nainā) 'the eyes', also used in Urdu. CRITICAL SOURCE ERROR: the source gave عائشة (a different name) and labelled the origin Arabic; the name is Hindi. The source gloss 'Radiant, Intense Light' is unsupported and has been replaced with the lexical sense."),
 "nair": ("نَايِر", "نائر", "نایر", "नायर", "نایر", "nair", "Malayalam", "Male",
           "Malayalam നായർ (nāyar), a Kerala surname and given name", False, "medium",
           "Nair is a Kerala surname and given name (Malayalam നായർ). CRITICAL SOURCE ERROR: the source gave نير (a non-standard form) and labelled the origin Arabic; the name is not Arabic. The source gloss 'Light, Sun' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
 "najaah": ("نَجَاح", "نجاح", "نجاح", "नजाह", "نجاح", "najaah", "Arabic", "Female",
            "Arabic root ن ج ح (n-j-ḥ); نَجَاح (Najāḥ)", False, "high",
            "Najaah is Arabic نَجَاح (Najāḥ) 'success, deliverance', from the root ن ج ح (n-j-ḥ). The source gloss 'Deliverance, Salvation, Victory' is partly consistent. Same name as najah."),
 "najaf": ("نَجَف", "نجف", "نجف", "नजफ़", "نجف", "najaf", "Arabic", "Male",
           "Arabic نَجَف (Najaf), a city in Iraq", False, "high",
           "Najaf is Arabic نَجَف (Najaf), the name of a city in Iraq, used occasionally as a personal name. The source gloss 'Venerated, Sacred' is a cultural association rather than a lexical sense. Recorded as a place name; no personal-name gender usage is asserted."),
 "najah": ("نَجَاح", "نجاح", "نجاح", "नजाह", "نجاح", "najaah", "Arabic", "Female",
           "Arabic root ن ج ح (n-j-ḥ); نَجَاح (Najāḥ)", False, "high",
           "Najah is Arabic نَجَاح (Najāḥ) 'success, deliverance', from the root ن ج ح (n-j-ḥ). The source gloss 'Victory, Triumph' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly female. Same name as najaah."),
 "najam": ("نَجْم", "نجم", "نجم", "नजम", "نجم", "najam", "Arabic", "Male",
           "Arabic root ن ج م (n-j-m); نَجْم (Najm)", False, "high",
           "Najam is Arabic نَجْم (Najm) 'star', from the root ن ج م (n-j-m). CRITICAL SOURCE ERROR: the source gave نجم (a non-standard form); the correct form is نَجْم. The source gloss 'Dew' is unsupported and has been replaced with the lexical sense. Same name as najm."),
 "najat": ("نَجَاة", "نجات", "نجات", "नजात", "نجات", "najat", "Arabic", "Female",
           "Arabic root ن ج و (n-j-w); نَجَاة (Najāt)", False, "high",
           "Najat is Arabic نَجَاة (Najāt) 'salvation, deliverance, safety', from the root ن ج و (n-j-w). CRITICAL SOURCE ERROR: the source record was an empty stub with no data; the form and sense have been established from the lexical root."),
 "najd": ("نَجْد", "نجد", "نجد", "नज्द", "نجد", "najd", "Arabic", "Male",
          "Arabic root ن ج د (n-j-d); نَجْد (Najd)", False, "high",
          "Najd is Arabic نَجْد (Najd) 'highland, plateau', from the root ن ج د (n-j-d). The source gloss 'Desert' is broadly consistent. CRITICAL SOURCE ERROR: the source labelled the gender unisex; the form is a common noun with no personal-name gender."),
 "najda": ("نَجْدَة", "نجدہ", "نجده", "नज्दा", "نجده", "najda", "Arabic", "Female",
           "Arabic root ن ج د (n-j-d); نَجْدَة (Najda)", False, "high",
           "Najda is Arabic نَجْدَة (Najda) 'help, succour', from the root ن ج د (n-j-d). The source gloss 'Guiding, Helping' is broadly consistent."),
 "najdat": ("نَجْدَات", "نجدات", "نجدات", "नज्दात", "نجدات", "najdat", "Arabic", "Male",
            "Arabic root ن ج د (n-j-d); نَجْدَات (Najdāt)", False, "high",
            "Najdat is Arabic نَجْدَات (Najdāt) 'help, succour', from the root ن ج د (n-j-d). The source gloss 'Revival, Resurrection' is unsupported and has been replaced with the lexical sense."),
 "najdi": ("نَجْدِي", "نجدی", "نجدی", "नज्दी", "نجدي", "najdi", "Arabic", "Male",
           "Arabic نَجْدِي (Najdī) 'of the highland'", False, "high",
           "Najdi is Arabic نَجْدِي (Najdī) 'of the highland, highlander', a relational adjective from نَجْد (Najd). The source gloss 'Originator, Founder' is unsupported and has been replaced with the lexical sense. CRITICAL SOURCE ERROR: the source labelled the gender unisex; documented usage is predominantly male."),
 "najee": ("نَاجِي", "ناجی", "ناجی", "नाजी", "ناجي", "najee", "Arabic", "Male",
           "Arabic root ن ج و (n-j-w); نَاجِي (Nājī)", False, "high",
           "Najee is a spelling variant of Arabic نَاجِي (Nājī) 'one who is saved, survivor', from the root ن ج و (n-j-w). CRITICAL SOURCE ERROR: the source gave the Latin string 'Najee' instead of a script form. The source gloss 'Victorious' is unsupported and has been replaced with the lexical sense. Same name as naji."),
 "najeeb": ("نَجِيب", "نجیب", "نجیب", "नजीब", "نجیب", "najib", "Arabic", "Male",
            "Arabic root ن ج ب (n-j-b); نَجِيب (Najīb)", False, "high",
            "Najeeb is Arabic نَجِيب (Najīb) 'noble, distinguished', from the root ن ج ب (n-j-b). The source gloss 'Kind and just' is unsupported and has been replaced with the lexical sense. Same name as najib."),
 "najeeba": ("نَجِيبَة", "نجیبہ", "نجیبه", "नजीबा", "نجیبه", "najeeba", "Arabic", "Female",
             "Arabic root ن ج ب (n-j-b); نَجِيبَة (Najība)", False, "high",
             "Najeeba is Arabic نَجِيبَة (Najība) 'noble, distinguished' (feminine), from the root ن ج ب (n-j-b). The source gloss 'Noble, Generous' is partly consistent. Same name as najiba."),
 "najet": ("نَجَاة", "نجات", "نجات", "नजात", "نجات", "najat", "Arabic", "Female",
           "Arabic root ن ج و (n-j-w); نَجَاة (Najāt)", False, "high",
           "Najet is a spelling variant of Arabic نَجَاة (Najāt) 'salvation, deliverance', from the root ن ج و (n-j-w). CRITICAL SOURCE ERROR: the source gave نجم (a different form); the correct form is نَجَاة. The source gloss 'Victorious, Conquering' is unsupported and has been replaced with the lexical sense. Same name as najat."),
 "naji": ("نَاجِي", "ناجی", "ناجی", "नाजी", "ناجي", "naji", "Arabic", "Male",
          "Arabic root ن ج و (n-j-w); نَاجِي (Nājī)", False, "high",
          "Naji is Arabic نَاجِي (Nājī) 'one who is saved, survivor', from the root ن ج و (n-j-w). The source gloss 'Intelligent, Wise' is unsupported and has been replaced with the lexical sense. Same name as najee."),
 "najiah": ("نَاجِيَة", "ناجیہ", "ناجیه", "नाजिया", "ناجیه", "najiah", "Arabic", "Female",
            "Arabic root ن ج و (n-j-w); نَاجِيَة (Nājiya)", False, "high",
            "Najiah is Arabic نَاجِيَة (Nājiya) 'one who is saved' (feminine), from the root ن ج و (n-j-w). The source gloss 'Elegant' is unsupported and has been replaced with the lexical sense."),
 "najib": ("نَجِيب", "نجیب", "نجیب", "नजीब", "نجیب", "najib", "Arabic", "Male",
           "Arabic root ن ج ب (n-j-b); نَجِيب (Najīb)", False, "high",
           "Najib is Arabic نَجِيب (Najīb) 'noble, distinguished', from the root ن ج ب (n-j-b). The source gloss 'Noble, Generous' is partly consistent. Same name as najeeb."),
 "najiba": ("نَجِيبَة", "نجیبہ", "نجیبه", "नजीबा", "نجیبه", "najiba", "Arabic", "Female",
            "Arabic root ن ج ب (n-j-b); نَجِيبَة (Najība)", False, "high",
            "Najiba is Arabic نَجِيبَة (Najība) 'noble, distinguished' (feminine), from the root ن ج ب (n-j-b). The source gloss 'Noble, exalted' is partly consistent. Same name as najeeba."),
 "najibah": ("نَجِيبَة", "نجیبہ", "نجیبه", "नजीबा", "نجیبه", "najiba", "Arabic", "Female",
             "Arabic root ن ج ب (n-j-b); نَجِيبَة (Najība)", False, "high",
             "Najibah is Arabic نَجِيبَة (Najība) 'noble, distinguished' (feminine), from the root ن ج ب (n-j-b). The source gloss 'Noble, generous' is partly consistent. Same name as najiba."),
 "najid": ("نَجِيد", "نجید", "نجید", "नजीद", "نجید", "najid", "Arabic", "Male",
           "Arabic نَجِيد (Najīd)", False, "medium",
           "Najid is recorded as Arabic نَجِيد (Najīd), a male given name. The source gloss 'Helper, assistant' is unsupported; no confident lexical sense is asserted. The identification is recorded at medium confidence."),
}
